### ISSUE TITLE
Can't upload Android app to Crashlytics Beta

### ISSUE THREAD

**Issue by piresbruno** [fastlane/fastlane#9389] opened 2017-06-06 18:58 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I'm not being able to upload releases to Fabric Beta with Fastlane.
Even when i once configure `api_token` and `build_secret`, is reports`Build successfully uploaded to Crashlytics Beta`, but the release doesn't appear in Fabric.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

### Captured Output

Command Used: `beta`
<details><summary>Output/Log</summary>

```

Successfully loaded Appfile at path '/Users/brunopires/Documents/Developer/Repository/android-driver/fastlane/Appfile'
- json_key_file: 'fastlane-5c8e768c2419.json'
- package_name: 'com.app.driver'
-------
DEBUG [2017-06-06 19:46:03.11]: Checking if there are any plugins that should be loaded...
INFO [2017-06-06 19:46:03.13]: -------------------------------------------------
INFO [2017-06-06 19:46:03.13]: --- Step: Verifying required fastlane version ---
INFO [2017-06-06 19:46:03.13]: -------------------------------------------------
INFO [2017-06-06 19:46:03.14]: Your fastlane version 2.37.0 matches the minimum requirement of 1.109.0  ✅
INFO [2017-06-06 19:46:03.14]: Driving the lane 'beta' 🚀
INFO [2017-06-06 19:46:03.14]: --------------------
INFO [2017-06-06 19:46:03.14]: --- Step: gradle ---
INFO [2017-06-06 19:46:03.14]: --------------------
INFO [2017-06-06 19:46:03.14]: $ /Users/brunopires/Documents/Developer/Repository/android-driver/gradlew assembleRegularRelease -p .
INFO [2017-06-06 19:46:03.88]: ▸ Parallel execution is an incubating feature.
INFO [2017-06-06 19:46:03.92]: ▸ NDK is missing a "platforms" directory.
INFO [2017-06-06 19:46:03.93]: ▸ If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to /Users/brunopires/Library/Android/sdk/ndk-bundle.
INFO [2017-06-06 19:46:03.93]: ▸ If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.
INFO [2017-06-06 19:46:04.03]: ▸ Jack is disabled, but one of the plugins you are using supports Java 8 language features.
INFO [2017-06-06 19:46:04.03]: ▸ Jack is disabled, but one of the plugins you are using supports Java 8 language features.
INFO [2017-06-06 19:46:04.05]: ▸ Jack is disabled, but one of the plugins you are using supports Java 8 language features.
INFO [2017-06-06 19:46:04.05]: ▸ Jack is disabled, but one of the plugins you are using supports Java 8 language features.
INFO [2017-06-06 19:46:04.06]: ▸ The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
INFO [2017-06-06 19:46:04.08]: ▸ :ya-app-driver:preBuild UP-TO-DATE
INFO [2017-06-06 19:46:04.08]: ▸ :ya-app-driver:preRegularReleaseBuild UP-TO-DATE
INFO [2017-06-06 19:46:04.08]: ▸ :ya-app-driver:checkRegularReleaseManifest
INFO [2017-06-06 19:46:04.09]: ▸ :ya-app-driver:preDebugBuild UP-TO-DATE
INFO [2017-06-06 19:46:04.09]: ▸ :ya-app-driver:preReleaseBuild UP-TO-DATE
INFO [2017-06-06 19:46:04.09]: ▸ :ya-app-driver:preRegularDebugBuild UP-TO-DATE
INFO [2017-06-06 19:46:04.09]: ▸ :ya-app-driver:prepareComAfollestadMaterialDialogsCore0861Library
INFO [2017-06-06 19:46:04.09]: ▸ :ya-app-driver:prepareComAndroidSupportAnimatedVectorDrawable2510Library
INFO [2017-06-06 19:46:04.09]: ▸ :ya-app-driver:prepareComAndroidSupportAppcompatV72510Library
INFO [2017-06-06 19:46:04.09]: ▸ :ya-app-driver:prepareComAndroidSupportCardviewV72411Library
INFO [2017-06-06 19:46:04.09]: ▸ :ya-app-driver:prepareComAndroidSupportDesign2510Library
INFO [2017-06-06 19:46:04.09]: ▸ :ya-app-driver:preDebugAndroidTestBuild UP-TO-DATE
INFO [2017-06-06 19:46:04.09]: ▸ :ya-app-driver:preRegularDebugAndroidTestBuild UP-TO-DATE
INFO [2017-06-06 19:46:04.09]: ▸ :ya-app-driver:prepareComAndroidSupportMultidex101Library
INFO [2017-06-06 19:46:04.09]: ▸ :ya-app-driver:prepareComAndroidSupportRecyclerviewV72510Library
INFO [2017-06-06 19:46:04.09]: ▸ :ya-app-driver:prepareComAndroidSupportSupportCompat2531Library
INFO [2017-06-06 19:46:04.09]: ▸ :ya-app-driver:prepareComAndroidSupportSupportCoreUi2531Library
INFO [2017-06-06 19:46:04.09]: ▸ :ya-app-driver:prepareComAndroidSupportSupportCoreUtils2531Library
INFO [2017-06-06 19:46:04.09]: ▸ :ya-app-driver:prepareComAndroidSupportSupportFragment2531Library
INFO [2017-06-06 19:46:04.09]: ▸ :ya-app-driver:prepareComAndroidSupportSupportMediaCompat2531Library
INFO [2017-06-06 19:46:04.09]: ▸ :ya-app-driver:prepareComAndroidSupportSupportV42531Library
INFO [2017-06-06 19:46:04.09]: ▸ :ya-app-driver:prepareComAndroidSupportSupportVectorDrawable2510Library
INFO [2017-06-06 19:46:04.09]: ▸ :ya-app-driver:prepareComAndroidSupportTransition2510Library
INFO [2017-06-06 19:46:04.09]: ▸ :ya-app-driver:prepareComAnthonycrGrantPermissions112Library
INFO [2017-06-06 19:46:04.09]: ▸ :ya-app-driver:prepareComCrashlyticsSdkAndroidAnswers1313Library
INFO [2017-06-06 19:46:04.09]: ▸ :ya-app-driver:prepareComCrashlyticsSdkAndroidAnswersShim006Library
INFO [2017-06-06 19:46:04.10]: ▸ :ya-app-driver:prepareComCrashlyticsSdkAndroidBeta125Library
INFO [2017-06-06 19:46:04.10]: ▸ :ya-app-driver:prepareComCrashlyticsSdkAndroidCrashlytics268Library
INFO [2017-06-06 19:46:04.10]: ▸ :ya-app-driver:prepareComCrashlyticsSdkAndroidCrashlyticsCore2317Library
INFO [2017-06-06 19:46:04.10]: ▸ :ya-app-driver:prepareComGoogleAndroidGmsPlayServicesAnalytics1026Library
INFO [2017-06-06 19:46:04.10]: ▸ :ya-app-driver:prepareComGoogleAndroidGmsPlayServicesAnalyticsImpl1026Library
INFO [2017-06-06 19:46:04.10]: ▸ :ya-app-driver:prepareComGoogleAndroidGmsPlayServicesBase1026Library
INFO [2017-06-06 19:46:04.10]: ▸ :ya-app-driver:prepareComGoogleAndroidGmsPlayServicesBasement1026Library
INFO [2017-06-06 19:46:04.10]: ▸ :ya-app-driver:prepareComGoogleAndroidGmsPlayServicesGcm1026Library
INFO [2017-06-06 19:46:04.10]: ▸ :ya-app-driver:prepareComGoogleAndroidGmsPlayServicesIid1026Library
INFO [2017-06-06 19:46:04.10]: ▸ :ya-app-driver:prepareComGoogleAndroidGmsPlayServicesLocation1026Library
INFO [2017-06-06 19:46:04.10]: ▸ :ya-app-driver:prepareComGoogleAndroidGmsPlayServicesMaps1026Library
INFO [2017-06-06 19:46:04.10]: ▸ :ya-app-driver:prepareComGoogleAndroidGmsPlayServicesTagmanagerV4Impl1026Library
INFO [2017-06-06 19:46:04.10]: ▸ :ya-app-driver:prepareComGoogleAndroidGmsPlayServicesTasks1026Library
INFO [2017-06-06 19:46:04.10]: ▸ :ya-app-driver:prepareComMakeramenRoundedimageview221Library
INFO [2017-06-06 19:46:04.10]: ▸ :ya-app-driver:prepareComSothreeSlidinguppanelLibrary331Library
INFO [2017-06-06 19:46:04.10]: ▸ :ya-app-driver:prepareComViewpagerindicatorLibrary241Library
INFO [2017-06-06 19:46:04.10]: ▸ :ya-app-driver:prepareComWangAviLibrary105Library
INFO [2017-06-06 19:46:04.10]: ▸ :ya-app-driver:prepareComZendeskBelvedere1021Library
INFO [2017-06-06 19:46:04.11]: ▸ :ya-app-driver:prepareComZendeskSdk1921Library
INFO [2017-06-06 19:46:04.11]: ▸ :ya-app-driver:prepareComZendeskSdkProviders1921Library
INFO [2017-06-06 19:46:04.11]: ▸ :ya-app-driver:prepareIoFabricSdkAndroidFabric1317Library
INFO [2017-06-06 19:46:04.11]: ▸ :ya-app-driver:prepareIoReactivexRxandroid110Library
INFO [2017-06-06 19:46:04.11]: ▸ :ya-app-driver:prepareMeDm7BarcodescannerCore192Library
INFO [2017-06-06 19:46:04.11]: ▸ :ya-app-driver:prepareMeDm7BarcodescannerZxing192Library
INFO [2017-06-06 19:46:04.11]: ▸ :ya-app-driver:prepareMeZhanghaiAndroidMaterialprogressbarLibrary116Library
INFO [2017-06-06 19:46:04.11]: ▸ :ya-app-driver:preparePlCharmasAndroidAndroidReactiveLocation08Library
INFO [2017-06-06 19:46:04.11]: ▸ :ya-app-driver:prepareRegularReleaseDependencies
INFO [2017-06-06 19:46:04.11]: ▸ :ya-app-driver:compileRegularReleaseAidl UP-TO-DATE
INFO [2017-06-06 19:46:04.12]: ▸ :ya-app-driver:compileRegularReleaseRenderscript UP-TO-DATE
INFO [2017-06-06 19:46:04.12]: ▸ :ya-app-driver:generateRegularReleaseBuildConfig
INFO [2017-06-06 19:46:04.12]: ▸ :ya-app-driver:mergeRegularReleaseShaders UP-TO-DATE
INFO [2017-06-06 19:46:04.12]: ▸ :ya-app-driver:compileRegularReleaseShaders UP-TO-DATE
INFO [2017-06-06 19:46:04.12]: ▸ :ya-app-driver:generateRegularReleaseAssets UP-TO-DATE
INFO [2017-06-06 19:46:04.13]: ▸ :ya-app-driver:mergeRegularReleaseAssets UP-TO-DATE
INFO [2017-06-06 19:46:04.13]: ▸ :ya-app-driver:generateRegularReleaseResValues UP-TO-DATE
INFO [2017-06-06 19:46:04.13]: ▸ :ya-app-driver:generateRegularReleaseResources UP-TO-DATE
INFO [2017-06-06 19:46:04.17]: ▸ :ya-app-driver:mergeRegularReleaseResources UP-TO-DATE
INFO [2017-06-06 19:46:04.17]: ▸ :ya-app-driver:processRegularReleaseManifest UP-TO-DATE
INFO [2017-06-06 19:46:04.19]: ▸ :ya-app-driver:fabricGenerateResourcesRegularRelease
INFO [2017-06-06 19:46:05.26]: ▸ :ya-app-driver:processRegularReleaseResources
INFO [2017-06-06 19:46:05.26]: ▸ :ya-app-driver:generateRegularReleaseSources
INFO [2017-06-06 19:46:05.41]: ▸ :ya-app-driver:incrementalRegularReleaseJavaCompilationSafeguard
INFO [2017-06-06 19:46:05.41]: ▸ :ya-app-driver:javaPreCompileRegularRelease
INFO [2017-06-06 19:46:06.99]: ▸ :ya-app-driver:compileRegularReleaseJavaWithJavacNote: Some input files use or override a deprecated API.
INFO [2017-06-06 19:46:06.99]: ▸ Note: Recompile with -Xlint:deprecation for details.
INFO [2017-06-06 19:46:06.99]: ▸ Note: Some input files use unchecked or unsafe operations.
INFO [2017-06-06 19:46:06.99]: ▸ Note: Recompile with -Xlint:unchecked for details.
INFO [2017-06-06 19:46:07.06]: ▸ :ya-app-driver:compileRetrolambdaRegularReleaseobjc[72540]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/bin/java (0x1029124c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x1029da4e0). One of the two will be used. Which one is undefined.
INFO [2017-06-06 19:46:08.30]: ▸ :ya-app-driver:compileRegularReleaseNdk UP-TO-DATE
INFO [2017-06-06 19:46:08.30]: ▸ :ya-app-driver:compileRegularReleaseSources
INFO [2017-06-06 19:46:09.32]: ▸ :ya-app-driver:transformClassesWithJarMergingForRegularRelease
INFO [2017-06-06 19:46:12.06]: ▸ :ya-app-driver:transformClassesWithMultidexlistForRegularRelease
INFO [2017-06-06 19:46:16.52]: ▸ :ya-app-driver:transformClassesWithDexForRegularRelease
INFO [2017-06-06 19:46:16.52]: ▸ :ya-app-driver:mergeRegularReleaseJniLibFolders UP-TO-DATE
INFO [2017-06-06 19:46:16.53]: ▸ :ya-app-driver:transformNativeLibsWithMergeJniLibsForRegularRelease UP-TO-DATE
INFO [2017-06-06 19:46:16.53]: ▸ :ya-app-driver:processRegularReleaseJavaRes UP-TO-DATE
INFO [2017-06-06 19:46:16.53]: ▸ :ya-app-driver:transformResourcesWithMergeJavaResForRegularRelease UP-TO-DATE
INFO [2017-06-06 19:46:16.53]: ▸ :ya-app-driver:validateSigningRegularRelease
INFO [2017-06-06 19:46:19.20]: ▸ :ya-app-driver:packageRegularRelease
INFO [2017-06-06 19:46:19.20]: ▸ :ya-app-driver:assembleRegularRelease
INFO [2017-06-06 19:46:19.20]: ▸ BUILD SUCCESSFUL
INFO [2017-06-06 19:46:19.20]: ▸ Total time: 15.969 secs
INFO [2017-06-06 19:46:19.65]: -------------------------
INFO [2017-06-06 19:46:19.65]: --- Step: crashlytics ---
INFO [2017-06-06 19:46:19.65]: -------------------------
INFO [2017-06-06 19:46:19.65]: Uploading the build to Crashlytics Beta. Time for some ☕️.
DEBUG [2017-06-06 19:46:19.65]: java -jar /Users/brunopires/Library/CrashlyticsAndroid/crashlytics-devtools.jar -androidRes . -apiKey [[API_TOKEN]] -apiSecret [[BUILD_SECRET]] -uploadDist '/Users/brunopires/Documents/Developer/Repository/android-driver/ya-app-driver/build/outputs/apk/ya-app-driver-safertaxi-Regular-release.apk' -androidManifest '/var/folders/c7/lt18gbms43nfntk342v92syw0000gn/T/xml20170606-72501-8v69fh' -betaDistributionEmails 'bruno.pires@safertaxi.com' -betaDistributionReleaseNotesFilePath '/var/folders/c7/lt18gbms43nfntk342v92syw0000gn/T/changelog20170606-72501-xlz938' -betaDistributionGroupAliases 'Business' -betaDistributionNotifications true
ERROR [2017-06-06 19:46:21.07]: Shell command exited with exit status 1 instead of 0.
ERROR [2017-06-06 19:46:21.07]:  WARN - The upload distribution task failed because it received invalid input. Contact support@fabric.io for help.
Exception in thread "main" com.crashlytics.tools.android.exception.PluginException: Distribution upload failed.
	at com.crashlytics.tools.android.DeveloperTools.processProperties(DeveloperTools.java:667)
	at com.crashlytics.tools.android.DeveloperTools.processArgsInternal(DeveloperTools.java:348)
	at com.crashlytics.tools.android.DeveloperTools.main(DeveloperTools.java:273)
Caused by: com.crashlytics.tools.android.exception.DistributionException: The upload distribution task failed because it received invalid input. Contact support@fabric.io for help.
	at com.crashlytics.tools.android.DistributionTasks.uploadDistribution(DistributionTasks.java:87)
	at com.crashlytics.tools.android.DeveloperTools.processProperties(DeveloperTools.java:665)
	... 2 more

DEBUG [2017-06-06 19:46:21.07]:  WARN - The upload distribution task failed because it received invalid input. Contact support@fabric.io for help.
Exception in thread "main" com.crashlytics.tools.android.exception.PluginException: Distribution upload failed.
	at com.crashlytics.tools.android.DeveloperTools.processProperties(DeveloperTools.java:667)
	at com.crashlytics.tools.android.DeveloperTools.processArgsInternal(DeveloperTools.java:348)
	at com.crashlytics.tools.android.DeveloperTools.main(DeveloperTools.java:273)
Caused by: com.crashlytics.tools.android.exception.DistributionException: The upload distribution task failed because it received invalid input. Contact support@fabric.io for help.
	at com.crashlytics.tools.android.DistributionTasks.uploadDistribution(DistributionTasks.java:87)
	at com.crashlytics.tools.android.DeveloperTools.processProperties(DeveloperTools.java:665)
	... 2 more

INFO [2017-06-06 19:46:21.07]: Build successfully uploaded to Crashlytics Beta 🌷
INFO [2017-06-06 19:46:21.07]: Visit https://fabric.io/_/beta to add release notes and notify testers.
INFO [2017-06-06 19:46:21.07]: Successfully generated documentation at path '/Users/brunopires/Documents/Developer/Repository/android-driver/fastlane/README.md'

+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | Verifying required  | 0           |
|      | fastlane version    |             |
| 2    | gradle              | 16          |
| 3    | crashlytics         | 1           |
+------+---------------------+-------------+

INFO [2017-06-06 19:46:21.11]: fastlane.tools finished successfully 🎉


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "5921f40d-be39-4df7-8116-518e86ae7696"

lane :beta do

  # build 
  gradle(task: 'assembleRegularRelease')
  crashlytics(api_token: "<KEY>",
           build_secret: "<KEY>",
                 emails: emails,
                 groups: 'Business',
                  notes: 'new application build', # Check out the changelog_from_git_commits action
               apk_path: "#{Actions.lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]}")  
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file "fastlane-5c8e768c2419.json" # Path to the json secret file - Follow https://github.com/fastlane/supply#setup to get one
package_name "com.app.driver" # e.g. com.krausefx.app
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.37.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2017-06-06**
</details>

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "5921f40d-be39-4df7-8116-518e86ae7696"

lane :beta do

  # build 
  gradle(task: 'assembleRegularRelease')

  crashlytics(api_token: "<KEY>",
           build_secret: "<KEY>,
                 groups: 'Business',
                  notes: 'new application build', # Check out the changelog_from_git_commits action
               apk_path: "#{Actions.lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]}")  
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file "fastlane-5c8e768c2419.json" # Path to the json secret file - Follow https://github.com/fastlane/supply#setup to get one
package_name "com.app.driver" # e.g. com.krausefx.app
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.37.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2017-06-06**
</details>

**Comment by piresbruno** [comment] 2017-06-06 22:19
As far as i now, and the docs report, code signing issues exist only in iOS @fastlane-bot

**Comment by kirakik** [comment] 2017-08-05 23:41
@piresbruno were you able to fix your issue? I am getting the same problem

**Comment by BigPike** [comment] 2017-09-14 16:52
i've the same problem too

**Comment by ohayon** [comment] 2017-09-14 19:17
Hey everyone! Apologies for the issues, I'm curious, is this something you have been able to do successfully via the Fabric Android Studio plugin? 🐙

**Comment by BigPike** [comment] 2017-09-15 09:22
Fabric does not work for me as fatlane  :(

**Comment by ohayon** [comment] 2017-09-15 15:35
It sounds like some parameters being sent through to the API might not be properly formatted. @piresbruno could you share what the `emails` variable you have looks like? 

@BigPike and @kirakik, would you both share the code that you have that is calling the crashlytics action? Thank you!!

**Comment by gabceb** [comment] 2017-10-08 08:05
I am experiencing this at the moment and keep getting the same errors. As soon as I add any release notes or groups it returns a bad response from the server. See below for code and commands generated

### Release with release notes (BAD)

```
gradle(
      project_dir: "android/",
      task: "assemble",
      build_type: "releaseBeta"
    )

    crashlytics(
      api_token: "7c7e99aa89e29ce5f5a1a0316c9c2bb6d10941e4",
      build_secret: "a1363e2d4431456ba67e3f1b0887f5cfecf6e62e9180ec96c4edb3cdd0198e7e",
      apk_path: "android/app/build/outputs/apk/app-releaseBeta.apk",
      # groups: "internal-android-testers",
      notes: changelog
    )
```

Command generated by Fastlane: 
```
java -jar /Users/gabrielcebrian/Library/CrashlyticsAndroid/crashlytics-devtools.jar -androidRes . -apiKey FAKE -apiSecret FAKE -uploadDist '/Users/gabrielcebrian/Projects/tes/mobile/app-job-mobile/android/app/build/outputs/apk/app-releaseBeta.apk' -androidManifest '/var/folders/xh/qh3rd10d1k3_bg1r7jml148w0000gn/T/xml20171008-38190-1q8iv9b' -betaDistributionReleaseNotesFilePath '/var/folders/xh/qh3rd10d1k3_bg1r7jml148w0000gn/T/changelog20171008-38190-1uhd32z' -betaDistributionNotifications true
```

### Release with groups (BAD)

```
gradle(
      project_dir: "android/",
      task: "assemble",
      build_type: "releaseBeta"
    )

    crashlytics(
      api_token: "7c7e99aa89e29ce5f5a1a0316c9c2bb6d10941e4",
      build_secret: "a1363e2d4431456ba67e3f1b0887f5cfecf6e62e9180ec96c4edb3cdd0198e7e",
      apk_path: "android/app/build/outputs/apk/app-releaseBeta.apk",
      groups: "internal-android-testers",
      # notes: changelog
    )
```

### Release with no release notes or groups (GOOD)

```
gradle(
      project_dir: "android/",
      task: "assemble",
      build_type: "releaseBeta"
    )

    crashlytics(
      api_token: "7c7e99aa89e29ce5f5a1a0316c9c2bb6d10941e4",
      build_secret: "a1363e2d4431456ba67e3f1b0887f5cfecf6e62e9180ec96c4edb3cdd0198e7e",
      apk_path: "android/app/build/outputs/apk/app-releaseBeta.apk",
      # groups: "internal-android-testers",
      # notes: changelog
    )
```

Command generated by Fastlane: 
```
java -jar /Users/gabrielcebrian/Library/CrashlyticsAndroid/crashlytics-devtools.jar -androidRes . -apiKey FAKE -apiSecret FAKE -uploadDist '/Users/gabrielcebrian/Projects/tes/mobile/app-job-mobile/android/app/build/outputs/apk/app-releaseBeta.apk' -androidManifest '/var/folders/xh/qh3rd10d1k3_bg1r7jml148w0000gn/T/xml20171008-37651-ja22ma' -betaDistributionNotifications true
```

**Comment by gabceb** [comment] 2017-10-08 09:18
FWIW I am also not seeing the build upload even when it supposedly finishes correctly. I am able to upload build via the Android Studios IDE

**Comment by gabceb** [comment] 2017-10-13 06:11
Im trying to work out the correct parameters with @TKBurner for this

**Comment by komarekw** [comment] 2017-11-07 08:24
Hi @gabceb 
did you fixed the issue? We have the same issue here if we are using a proxy. If I try to upload without proxy it works as before. 

BR,
Werner

**Comment by ISFELLY** [comment] 2017-11-13 16:38
Hello if you work under a corporate proxy , a quick solution is to add the the java proxy params on "$JAVA_TOOL_OPTIONS" 

-Dhttp.proxyHost=yourproxy.yourdomain -Dhttp.proxyPort=80 -Dhttps.proxyHost=yourproxy.yourdomain -Dhttps.proxyPort=80 -Dhttp.nonProxyHosts=”localhost|127.0.0.1|*.yourdomain"

a better solution is to update the fastlane/lib/fastlane/helper/crashlytics_helper.rb

to generate a java cmd which can check at least the $JAVA_HOME and include a $JAVA_OPTS params by default.

**Comment by komarekw** [comment] 2017-11-15 09:25
Hi @ISFELLY 
Thanks for your answer but I tried it this solution as well. I guess the problem is that I have to provide username and password for our proxy. :-(

BR,
Werner

**Comment by dms90** [comment] 2017-11-22 20:10
Same error here! :(

Any news?

**Comment by dms90** [comment] 2017-11-23 13:37
@piresbruno I had the same issue. 

This worked for me:
1. Create the app in Fabric from Android Studio Plugin. Yo need to upload the first apk to Crashlytics following this steps: https://docs.fabric.io/android/beta/beta-walkthrough.html
2. Then I was able to upload via Fastlane 👍 

It seems that you first need to create the app.

**Comment by anticafe** [comment] 2017-12-20 07:11
@dms90  Is there any solution to upload app without need to install Fabric plugin?

**Comment by dms90** [comment] 2017-12-22 17:25
@anticafe it seems that is fixed now. Which version of Fastlane are you using?

**Comment by KrauseFx** [comment] 2018-01-02 19:24
Hey everyone, it seems like this happens when you haven't fully on-boarded your app to Fabric. Can you make sure you can deploy a new Beta build using the Fabric Mac app, and then try it again with _fastlane_?

**Comment by gabceb** [comment] 2018-01-02 19:26
I have not tried this for at least a month but unless something has changed I can successfully upload via the Android Studio plugin but not via Fastlane

**Comment by joshfriend** [comment] 2018-01-08 22:22
`fastlane beta` failed for me until I had onboarded with the android studio plugin and submitted at least one build.

Passing the `notes` parameter is still breaking the build as @gabceb mentioned in his [earlier comment](https://github.com/fastlane/fastlane/issues/9389#issuecomment-334990346).

Omitting the `notes` allows the fastlane command to succeed, but the build does not appear on fabric.

**Comment by joshfriend** [comment] 2018-02-23 14:54
bump so the bot doesn't close it while I try again 😠

**Closed** 2018-05-01 17:35 UTC
Labels: status: waiting-for-reply

**Comment by joshfriend** [comment] 2018-05-23 23:07
Update: fastlane uploads to crashlytics are working for me on a new app that i just started without fiddling with any of the `notes` parameter nonsense
