### ISSUE TITLE
[Screengrab] succesfully creates screenshots but looks in the wrong folder for them

### ISSUE THREAD

**Issue by henningBunk** [fastlane/fastlane#13787] opened 2018-11-30 10:49 UTC
### Question Checklist

- [x] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

Fastlane screengrab is creating screenshots and copies them to my computer, but than tells me that there are no screenshots.

### Question Description

* When screengrab is finishing it copies the screenshots to my computer with `adb pull` from `/sdcard/my.app/screengrab/` successfully.
* Than it wants to get the screenshots again from `/data/data/my.app/app_screengrab/`. This fails because the folder does not exist.
* The logcat tells me, that screengrab is using `/storage/emulated/0/my.app/screengrab/` as directory to save the pngs to.

Why is screengrab looking into the /data/data folder? Why isn't it using one of the other two paths? Can I prevent this somehow?

### Logs

Logcat (Excerpt):
```
2018-11-30 10:54:15.788 5537-5564/my.app D/Screengrab: Using screenshot storage directory: /storage/emulated/0/my.app/screengrab/fr-CA/images/screenshots
2018-11-30 10:54:15.905 5537-5564/my.app D/Screengrab: Captured screenshot "main.png"

```
 Fastlane:

```
➜  myApp git:(hb/screenshots) ✗ fastlane screengrab --locales 'fr-CA'
[✔] 🚀
[10:15:25]: fastlane detected a Gemfile in the current directory
[10:15:25]: however it seems like you don't use `bundle exec`
[10:15:25]: to launch fastlane faster, please use
[10:15:25]:
[10:15:25]: $ bundle exec fastlane screengrab --locales fr-CA
[10:15:25]:
[10:15:25]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[10:15:25]: Successfully loaded '/Users/henning.bunk/repos/android/wetter-app/Screengrabfile' 📄

+-----------------------------+-------------------------------------------------------------------------------------------------------------------------+
|                                                        Detected Values from './Screengrabfile'                                                        |
+-----------------------------+-------------------------------------------------------------------------------------------------------------------------+
| launch_arguments            | ["isScreengrab true"]                                                                                                   |
| build_tools_version         | 27.0.1                                                                                                                  |
| reinstall_app               | false                                                                                                                   |
| app_apk_path                | wetterApp/build/outputs/apk/myApp/uitest/my-App-uitest.apk                         |
| tests_apk_path              | wetterApp/build/outputs/apk/androidTest/myApp/uitest/my-App-uitest-androidTest.apk |
| app_package_name            | my.app                                                                                            |
| tests_package_name          | my.app.test                                                                                                    |
| use_tests_in_packages       | ["my.app.tests"]                                                                                     |
| test_instrumentation_runner | my.app.RxTestRunner                                                                                  |
| output_directory            | fastlane/screengrab                                                                                                     |
| clear_previous_screenshots  | false                                                                                                                   |
| skip_open_summary           | true                                                                                                                    |
+-----------------------------+-------------------------------------------------------------------------------------------------------------------------+


+-----------------------------+-------------------------------------------------------------------------------------------------------------------------+
|                                                            Summary for screengrab 2.108.0                                                             |
+-----------------------------+-------------------------------------------------------------------------------------------------------------------------+
| locales                     | ["fr-CA"]                                                                                                               |
| build_tools_version         | 27.0.1                                                                                                                  |
| clear_previous_screenshots  | false                                                                                                                   |
| output_directory            | fastlane/screengrab                                                                                                     |
| skip_open_summary           | true                                                                                                                    |
| app_package_name            | my.app                                                                                            |
| tests_package_name          | my.app.test                                                                                                    |
| use_tests_in_packages       | ["my.app.tests"]                                                                                     |
| launch_arguments            | ["isScreengrab true"]                                                                                                   |
| test_instrumentation_runner | my.app.RxTestRunner                                                                                  |
| ending_locale               | en-US                                                                                                                   |
| app_apk_path                | app/build/outputs/apk/myApp/uitest/my-App-uitest.apk                         |
| tests_apk_path              | app/build/outputs/apk/androidTest/myApp/uitest/my-App-uitest-androidTest.apk |
| device_type                 | phone                                                                                                                   |
| exit_on_test_failure        | true                                                                                                                    |
| reinstall_app               | false                                                                                                                   |
+-----------------------------+-------------------------------------------------------------------------------------------------------------------------+

[10:15:26]: $ /Users/henning.bunk/Library/Android/sdk/platform-tools/adb devices -l
[10:15:26]: ▸ List of devices attached
[10:15:26]: ▸ emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:5
[10:15:26]: $ /Users/henning.bunk/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell echo \$EXTERNAL_STORAGE
[10:15:26]: ▸ /sdcard
[10:15:26]: Cleaning screenshots on device
ls: /sdcard/my.app/screengrab: No such file or directory
[10:15:26]: Exit status: 1
ls: /data/data/my.app/app_screengrab: No such file or directory
[10:15:26]: Exit status: 1
[10:15:26]: Validating app APK
[10:15:26]: $ /Users/henning.bunk/Library/Android/sdk/build-tools/28.0.3/aapt dump permissions wetterApp/build/outputs/apk/myApp/uitest/my-App-uitest.apk
[10:15:26]: ▸ package: my.app
[10:15:26]: ▸ uses-permission: name='android.permission.DISABLE_KEYGUARD'
[10:15:26]: ▸ uses-permission: name='android.permission.WAKE_LOCK'
[10:15:26]: ▸ uses-permission: name='android.permission.WRITE_EXTERNAL_STORAGE'
[10:15:26]: ▸ uses-permission: name='android.permission.READ_EXTERNAL_STORAGE'
[10:15:26]: ▸ uses-permission: name='android.permission.CHANGE_CONFIGURATION'
[10:15:26]: ▸ uses-permission: name='android.permission.ACCESS_FINE_LOCATION'
[10:15:26]: ▸ uses-permission: name='android.permission.ACCESS_COARSE_LOCATION'
[10:15:26]: ▸ uses-permission: name='android.permission.INTERNET'
[10:15:26]: ▸ uses-permission: name='android.permission.ACCESS_NETWORK_STATE'
[10:15:26]: ▸ uses-permission: name='com.google.android.providers.gsf.permission.READ_GSERVICES'
[10:15:26]: ▸ uses-permission: name='android.permission.VIBRATE'
[10:15:26]: ▸ uses-permission: name='android.permission.CAMERA'
[10:15:26]: ▸ uses-permission: name='android.permission.RECEIVE_BOOT_COMPLETED'
[10:15:26]: ▸ uses-permission: name='com.android.vending.BILLING'
[10:15:26]: ▸ uses-permission: name='android.permission.ACCESS_WIFI_STATE'
[10:15:26]: ▸ uses-permission: name='com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE'
[10:15:26]: ▸ uses-permission: name='com.google.android.c2dm.permission.RECEIVE'
[10:15:26]: Installing app APK
[10:15:26]: $ /Users/henning.bunk/Library/Android/sdk/platform-tools/adb -s emulator-5554 install -t -r wetterApp/build/outputs/apk/myApp/uitest/my-App-uitest.apk
[10:15:28]: ▸ Success
[10:15:28]: Installing tests APK
[10:15:28]: $ /Users/henning.bunk/Library/Android/sdk/platform-tools/adb -s emulator-5554 install -t -r wetterApp/build/outputs/apk/androidTest/myApp/uitest/my-App-uitest-androidTest.apk
[10:15:30]: ▸ Success
[10:15:30]: Granting the permission necessary to change locales on the device
[10:15:30]: $ /Users/henning.bunk/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell pm grant my.app android.permission.CHANGE_CONFIGURATION
[10:15:30]: $ /Users/henning.bunk/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop ro.build.version.sdk
[10:15:30]: ▸ 28
[10:15:30]: Granting the permissions necessary to access device external storage
[10:15:30]: $ /Users/henning.bunk/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell pm grant my.app android.permission.WRITE_EXTERNAL_STORAGE
[10:15:30]: $ /Users/henning.bunk/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell pm grant my.app android.permission.READ_EXTERNAL_STORAGE
[10:15:30]: Running tests for locale: fr-CA
[10:15:30]: $ /Users/henning.bunk/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am instrument --no-window-animation -w \
-e testLocale fr_CA \
-e endingLocale en_US \
-e package my.app.tests \
-e isScreengrab true \
my.app.test/my.app.RxTestRunner
[10:15:41]: ▸ my.app.tests.MainScreenshots:
[10:16:27]: ▸ my.app.tests.MainScreenshots:....
[10:16:30]: ▸ Time: 55.69
[10:16:30]: ▸ OK (9 tests)
[10:16:30]: Pulling captured screenshots from the device
[10:16:30]: $ /Users/henning.bunk/Library/Android/sdk/platform-tools/adb -s emulator-5554 pull /sdcard/my.app/screengrab /var/folders/1z/r9tnh30d2295kv_vs7q1f47r0000gp/T/d20181130-3871-1ty3xa1
ls: /data/data/my.app/app_screengrab: No such file or directory
[10:16:31]: Exit status: 1
[10:16:31]: Screenshots copied to fastlane/fr-CA/images/phoneScreenshots
[10:16:31]: Make sure you've used Screengrab.screenshot() in your tests and that your expected tests are being run.

[!] No screenshots were detected 📷❌
```

**Comment by janpio** [comment] 2018-11-30 12:05
Screengrab is set up to handle 2 possible locations of screenshots. An internal and an external path. "/sdcard/my.app/screengrab/" is the external in your case, "/data/data/my.app/app_screengrab" the internal. All actions are executed on those both paths, failing if the folder does not exist - but that should not be a problem (that's the `ls: /data/data/my.app/app_screengrab: No such file or directory` you see towards the end).

When first pulling the screenshots, screengrab moves them to a temporary folder and later moves them to the selected target, that is what causes the "Screenshots copied to fastlane/fr-CA/images/phoneScreenshots" output: https://github.com/fastlane/fastlane/blob/0bf2e8cc0d6b83c3a36dd4cc195173edb4bedba7/screengrab/lib/screengrab/runner.rb#L309-L339

No in this code, I see a replacement of `screengrab`:
https://github.com/fastlane/fastlane/blob/0bf2e8cc0d6b83c3a36dd4cc195173edb4bedba7/screengrab/lib/screengrab/runner.rb#L323-L327
This could theoretically clash with your configured `output_directory: fastlane/screengrab` maybe. Can you try not setting that value or setting it so something else and see what happens then?

Edit: Just saw you actually wrote you _are_ getting screenshots. At the expected path? Correct number? If not at the correct path, then this could explain why a later function that tries to count the number of screenshots gets 0 - there this faulty `screengrab` replacement that I described above in the path does _not_ happen.

**Comment by henningBunk** [comment] 2018-12-03 07:37
Hi janpio,
you are my hero! With your input I could find the reason for the error. It is indeed the replacement of the word `screengrab` in the output path. 

Im was using the path `fastlane/screengrab` but the screenshots were copied to `fastlane`. When I am switching the output path to `fastlane/output` the screenshots are copied to `fastlane/output` and the log is as expected:

```
[08:26:36]: Pulling captured screenshots from the device
[08:26:36]: $ /Users/henning.bunk/Library/Android/sdk/platform-tools/adb -s emulator-5554 pull /sdcard/my.app/screengrab /var/folders/1z/r9tnh30d2295kv_vs7q1f47r0000gp/T/d20181203-11452-16tl4t8
ls: /data/data/my.app/app_screengrab: No such file or directory
[08:26:36]: Exit status: 1
[08:26:36]: Screenshots copied to fastlane/output/fr-CA/images/phoneScreenshots
[08:26:36]: Generating HTML Report
[08:26:36]: Successfully created HTML file with an overview of all the screenshots: '/Users/henning.bunk/repos/android/my-app/fastlane/output/screenshots.html'
[08:26:36]: Captured 4 screenshots! 📷✨
```

🎉  🙇 
Thanks a lot!

Maybe this should be documented?

**Comment by janpio** [comment] 2018-12-03 10:00
This should be fixed - this is definitely not the intended behavior ;) I added the `bug` label here, so lets hope someone will take a look and rewrite the code to be more robust.

**Comment by henningBunk** [comment] 2019-01-07 06:39
I think this issue is still existing.

**Comment by henningBunk** [comment] 2019-02-15 08:08
I think this issue is still existing.

**Comment by henningBunk** [comment] 2019-04-02 07:27
still open

**Comment by henningBunk** [comment] 2019-05-13 07:36
I dont think this is fixed

**Closed** 2019-07-04 17:33 UTC
Labels: complexity: you can do this, status: waiting-for-reply, tool: screengrab, type: bug
