### ISSUE TITLE
Uploading when not logged in correctly?

### ISSUE THREAD

**Issue by Jules2010** [fastlane/fastlane#13553] opened 2018-10-17 19:06 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When running snapshot then frameit then uploading screenshots, I get the follow error...

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre>
security: SecKeychainAddInternetPassword <NULL>: The user name or passphrase you entered is not correct.
Could not store password in keychain
[19:58:33]: Login successful

+--------------------------------------+---------------------------------------------+
|                              deliver 2.107.0 Summary                               |
+--------------------------------------+---------------------------------------------+
| skip_binary_upload                   | true                                        |
| skip_metadata                        | true                                        |
| screenshots_path                     | /Users/jm/Dropbox/Code_ObjC/screenshots/sfc |
| metadata_path                        | ./fastlane/metadata                         |
| platform                             | ios                                         |
| edit_live                            | false                                       |
| use_live_version                     | false                                       |
| skip_screenshots                     | false                                       |
| skip_app_version_update              | false                                       |
| force                                | false                                       |
| overwrite_screenshots                | false                                       |
| submit_for_review                    | false                                       |
| reject_if_possible                   | false                                       |
| automatic_release                    | false                                       |
| phased_release                       | false                                       |
| run_precheck_before_submit           | true                                        |
| precheck_default_rule_level          | warn                                        |
| ignore_language_directory_validation | false                                       |
| precheck_include_in_app_purchases    | true                                        |
+--------------------------------------+---------------------------------------------+

[19:58:35]: Framed screenshots are detected! 🖼 Non-framed screenshot files may be skipped. 🏃
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-GB/iPad Air-happy.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-GB/iPad Air-happycalendar.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-GB/iPad Air-main.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-GB/iPad Air-sad.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-GB/iPad Pro (12.9-inch)-happy.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-GB/iPad Pro (12.9-inch)-happycalendar.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-GB/iPad Pro (12.9-inch)-main.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-GB/iPad Pro (12.9-inch)-sad.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-GB/iPad Pro (9.7-inch)-happy.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-GB/iPad Pro (9.7-inch)-happycalendar.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-GB/iPad Pro (9.7-inch)-main.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-GB/iPad Pro (9.7-inch)-sad.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-GB/iPhone 5s-happy.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-GB/iPhone 5s-happycalendar.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-GB/iPhone 5s-main.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-GB/iPhone 5s-sad.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-GB/iPhone 8 Plus-happy.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-GB/iPhone 8 Plus-happycalendar.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-GB/iPhone 8 Plus-main.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-GB/iPhone 8 Plus-sad.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-GB/iPhone 8-happy.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-GB/iPhone 8-happycalendar.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-GB/iPhone 8-main.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-GB/iPhone 8-sad.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-GB/iPhone SE-happy.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-GB/iPhone SE-happycalendar.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-GB/iPhone SE-main.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-GB/iPhone SE-sad.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-GB/iPhone X-happy.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-GB/iPhone X-happycalendar.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-GB/iPhone X-main.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-GB/iPhone X-sad.png
[19:58:35]: Framed screenshots are detected! 🖼 Non-framed screenshot files may be skipped. 🏃
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-US/iPad Air-happy.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-US/iPad Air-happycalendar.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-US/iPad Air-main.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-US/iPad Air-sad.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-US/iPad Pro (12.9-inch)-happy.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-US/iPad Pro (12.9-inch)-happycalendar.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-US/iPad Pro (12.9-inch)-main.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-US/iPad Pro (12.9-inch)-sad.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-US/iPad Pro (9.7-inch)-happy.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-US/iPad Pro (9.7-inch)-happycalendar.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-US/iPad Pro (9.7-inch)-main.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-US/iPad Pro (9.7-inch)-sad.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-US/iPhone 5s-happy.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-US/iPhone 5s-happycalendar.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-US/iPhone 5s-main.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-US/iPhone 5s-sad.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-US/iPhone 8 Plus-happy.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-US/iPhone 8 Plus-happycalendar.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-US/iPhone 8 Plus-main.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-US/iPhone 8 Plus-sad.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-US/iPhone 8-happy.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-US/iPhone 8-happycalendar.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-US/iPhone 8-main.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-US/iPhone 8-sad.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-US/iPhone SE-happy.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-US/iPhone SE-happycalendar.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-US/iPhone SE-main.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-US/iPhone SE-sad.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-US/iPhone X-happy.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-US/iPhone X-happycalendar.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-US/iPhone X-main.png
[19:58:35]: 🏃 Skipping screenshot file: /Users/jm/Dropbox/Code_ObjC/Screenshots/sfc/en-US/iPhone X-sad.png
[19:58:39]: #<ArgumentError: different prefix: "/" and "fastlane">
[19:58:39]: /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/pathname.rb:520:in `relative_path_from'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.107.0/deliver/lib/deliver/html_generator.rb:38:in `render_relative_path'
(erb):240:in `block (3 levels) in render'
(erb):239:in `each'
(erb):239:in `each_with_index'
(erb):239:in `block (2 levels) in render'
(erb):233:in `each'
(erb):233:in `block in render'
(erb):157:in `each'
(erb):157:in `render'
/usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/erb.rb:896:in `eval'
/usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/erb.rb:896:in `result'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.107.0/deliver/lib/deliver/html_generator.rb:56:in `render'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.107.0/deliver/lib/deliver/html_generator.rb:13:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.107.0/deliver/lib/deliver/runner.rb:180:in `validate_html'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.107.0/deliver/lib/deliver/runner.rb:117:in `upload_metadata'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.107.0/deliver/lib/deliver/runner.rb:38:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.107.0/fastlane/lib/fastlane/actions/upload_to_app_store.rb:16:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.107.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.107.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.107.0/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.107.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.107.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.107.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.107.0/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
Fastfile:34:in `block (2 levels) in parsing_binding'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.107.0/fastlane/lib/fastlane/lane.rb:33:in `call'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.107.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.107.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.107.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.107.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.107.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.107.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
/usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
/usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.107.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
/usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.107.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.107.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.107.0/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.107.0/bin/fastlane:23:in `<top (required)>'
/usr/local/bin/fastlane:23:in `load'
/usr/local/bin/fastlane:23:in `<main>'
[19:58:39]: Could not render HTML preview. Do you still want to continue?
n

[19:59:00]: Starting with the upload of screenshots...
[✔] Activating languages en-GB, en-US...
</pre>
</details>

### Environment

<details>
  <pre>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                         |
| --------------------------- | --------------------------------------------- |
| OS                          | 10.13.6                                       |
| Ruby                        | 2.4.1                                         |
| Bundler?                    | false                                         |
| Git                         | git version 2.10.1                            |
| Installation Source         | /usr/local/bin/fastlane                       |
| Host                        | Mac OS X 10.13.6 (17G65)                      |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.1_1/lib            |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                   |
| Is contained                | false                                         |
| Is homebrew                 | false                                         |
| Is installed via Fabric.app | false                                         |
| Xcode Path                  | /Applications/Xcode10.app/Contents/Developer/ |
| Xcode Version               | 10.0                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

before_all do
	ENV["SLACK_URL"] = "https://hooks.slack.com/services/snip" # Webhook 	URL created in Slack
end

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do

    capture_screenshots(
    	workspace: "Sad Face Chart.xcworkspace", 
    	scheme: ENV['SCHEME'], 
    	output_directory: ENV['SCREENSHOT_PATH'])

    frame_screenshots(white: true, path: ENV['SCREENSHOT_PATH'])


    upload_to_app_store(
    	skip_binary_upload: true, 
    	skip_metadata: true, 
    	screenshots_path: ENV['SCREENSHOT_PATH'],
    	app_identifier: ENV['BUNDLE_ID'])

    slack(
      message: "Screenshots finished.",
      success: true,
     )

  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier(ENV['BUNDLE_ID']) # The bundle identifier of your app


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.107.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| domain_name               | 0.5.99999999 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.5.0        |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| emoji_regex               | 0.1.1        |
| faraday                   | 0.15.3       |
| fastimage                 | 2.1.4        |
| json                      | 2.1.0        |
| bundler                   | 1.16.4       |
| httpclient                | 2.8.3        |
| jwt                       | 2.1.0        |
| signet                    | 0.10.0       |
| os                        | 1.0.0        |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.6        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| retriable                 | 3.1.2        |
| declarative-option        | 0.1.0        |
| declarative               | 0.0.10       |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| google-api-client         | 0.23.9       |
| openssl                   | 2.1.1        |
| io-console                | 0.4.6        |
</details>

*generated on:* **2018-10-17**
</details>
</pre>
</details>

**Comment by janpio** [comment] 2018-11-17 19:17
Hi @Jules2010, did I understand correctly from your output that you mistyped your Keychain password, which caused the password not being saved in the keychain and then later you get this unrelated error? Or what exactly are the steps to reproduce this?

**Comment by janpio** [comment] 2018-11-17 19:18
Possibly duplicate of https://github.com/fastlane/fastlane/issues/13512

**Closed** 2019-01-03 17:34 UTC
Labels: status: waiting-for-reply, tool: deliver
