### ISSUE TITLE
Upload to crashlytics is not stable

### ISSUE THREAD

**Issue by tmp120210** [fastlane/fastlane#1164] opened 2016-01-21 13:23 UTC
I'm using fastlane for nightly buids and keep them in the crashlytics.

To do this, I added crashlytics action with following config: 

crashlytics(
          api_token: "token",
          build_secret: "secret",
      ipa_path: "project.ipa",
      notes: "Nightly build at " + Time.new.strftime("%H:%M:%S %d.%m.%Y"),
      emails: ['mails'],
      notifications: false,
      debug: true
)

I've noticed that sometimes build automatically submitted to crashlytics and sometimes not. Generally, when fastlane fails to upload the binary, I just execute the same shell command and it works normally.

fastlane log:
/iosdomoby/Domoby.app.dSYM.zip", :XCODEBUILD_ARCHIVE=>"/Users/tmp120210/Library/Developer/Xcode/Archives/2016-01-21/Domoby 2016-01-21 16.12.02.xcarchive"}
[16:14:15]: Exit status of command './Pods/Crashlytics/Crashlytics.framework/submit token secret -ipaPath 'project.ipa' -emails 'mails' -notesPath '/var/folders/4g/_3dyg_0534q0wd8qbd0r325h0000gn/T/changelog20160121-85494-1uehkdt' -notifications NO -debug YES' was 1 instead of 0.
2016-01-21 16:13:46.954 submit Crashlytics: Crashlytics.framework/submit 1.3.5 (15)
2016-01-21 16:13:46.961 submit Crashlytics: Path to IPA manually provided: project.ipa
2016-01-21 16:13:47.495 submit Crashlytics: Path To App: /var/folders/4g/_3dyg_0534q0wd8qbd0r325h0000gn/T/Domoby/Payload/Domoby.app
2016-01-21 16:13:52.157 submit Crashlytics: Added Release Notes Successfully 200
2016-01-21 16:13:52.624 submit Crashlytics: Added Testers/Groups Successfully 200
2016-01-21 16:13:52.633 submit Crashlytics: Submitting IPA at /var/folders/4g/_3dyg_0534q0wd8qbd0r325h0000gn/T/com.crashlytics.mac/distributions/EB28DBCB-5AB9-47C8-B80E-EC220F1EEC14.ipa
2016-01-21 16:14:13.984 submit Crashlytics: Unable to submit build. Response code: 0
2016-01-21 16:14:13.994 submit Crashlytics: Failed to upload binary

Then, I manually run this shell command:
Michaels-Air:ios tmp120210$ ./Pods/Crashlytics/Crashlytics.framework/submit token secret -ipaPath 'project.ipa' -emails 'mails' -notifications NO -debug YES
2016-01-21 16:14:58.778 submit Crashlytics: Crashlytics.framework/submit 1.3.5 (15)
2016-01-21 16:14:58.784 submit Crashlytics: Path to IPA manually provided: project.ipa
2016-01-21 16:14:59.176 submit Crashlytics: Path To App: /var/folders/4g/_3dyg_0534q0wd8qbd0r325h0000gn/T/Domoby/Payload/Domoby.app
2016-01-21 16:15:04.228 submit Crashlytics: Added Testers/Groups Successfully 200
2016-01-21 16:15:04.236 submit Crashlytics: Submitting IPA at /var/folders/4g/_3dyg_0534q0wd8qbd0r325h0000gn/T/com.crashlytics.mac/distributions/4B32E38A-922B-4C6A-B26A-E387B731BE8C.ipa
2016-01-21 16:15:16.812 submit Crashlytics: Uploaded Successfully 202

crashreport hash from fastlane: a2c7fb6b0d04c522076e8f9e96d44f29

**Comment by tompowered** [comment] 2016-01-22 03:39
I'm seeing similar behavior recently.

**Comment by suprie** [comment] 2016-01-27 04:24
Mine the command said it's successfully build and uploaded to Crashlytics, but somehow the binary is not uploaded yet. I need to manually upload the binary

**Comment by mfurtak** [comment] 2016-01-29 14:46
Hi folks, a couple questions: 

1. Is this fairly easy to reproduce, or is it fairly rare?
1. How large are the IPA files you are sending?

**Comment by tmp120210** [comment] 2016-01-29 18:38
@mfurtak Hello!
1. Yes, I can easily reproduce it. Actually, it doesn't work for me in 50% cases.
2. my ipa is about 10Mb

**Comment by mfurtak** [comment] 2016-02-12 17:25
@tmp120210 @suprie @tompowered Hm... what area of the world are you in? There may be regional routing things at play here... :earth_americas: 

Is it consistent about always failing on the uploading IPA step? Does it ever fail on the Adding Notes or Adding Testers steps?

**Comment by tmp120210** [comment] 2016-02-26 10:27
I'm in Russia, Saint-Petersburg. I don't think that it depends on routing, because Fabric3 always succeeds to upload the ipa.

Yes, it always fails on uploading IPA step, all notes and testers steps are working fine.

**Comment by diejmon** [comment] 2016-03-02 10:25
I have the same issue. Would be good if crashlitics tool could try to reupload binary if upload fails.

**Comment by ppaulojr** [comment] 2016-03-02 20:04
I have the same issue, and since fastlane is now part of Fabric it would be interesting to have Crashlytics working

**Comment by evgeny1** [comment] 2016-03-04 23:53
```
2016-03-04 15:05:39.389 submit Crashlytics: Crashlytics.framework/submit 1.3.5 (15)
2016-03-04 15:05:45.286 submit Crashlytics: Added Testers/Groups Successfully 200
2016-03-04 15:05:51.418 submit Crashlytics: Uploaded Successfully 202
```
Despite these success messages, nothing gets uploaded most of the time, the file size is 19 MB.

**Comment by ex3ndr** [comment] 2016-03-24 19:36
Still not uploading at all, Mac App uploads well. Just immediately exit command with success return code.

**Comment by TKBurner** [comment] 2016-03-25 17:38
@ex3ndr Thanks for letting us know. Can you send over the full output when you run fastlane run crashlytics?

Thanks!

**Comment by evgeny1** [comment] 2016-03-25 19:55
@TKBurner why did you close this issue?

**Comment by ex3ndr** [comment] 2016-03-26 02:42
I have found problem. I have specified path to framework internal "submit" command. When executed via fastlane all debug information is not shown anywhere and i can't see that i need to change path.

**Comment by TKBurner** [comment] 2016-03-28 15:22
@ex3ndr Are you up and running?

**Comment by janandre** [comment] 2016-03-31 15:57
I experience the same issue, tried everything i could find on the internet.
I thought the issue is to find the right crashlytics url, so i tried almost every combination and paths to a submit file. In almost all cases i end up with this error:

```
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.39.0/lib/fastlane_core/ui/interface.rb:120:in `crash!': [!] Shell command exited with exit status 1 instead of 0. (FastlaneCore::Interface::FastlaneCrash)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.39.0/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/helper/sh_helper.rb:44:in `sh_no_action'
```

But in the fabric portal i can see the new version! The file is obviously missing.

After adding ` crashlytics_path: './Pods/Crashlytics/Crashlytics.framework'` i get a success message.
BUT there is **nothing** in the fabric portal!

**Comment by TKBurner** [comment] 2016-04-01 13:02
@janandre Can you post the full output of when you run 'fastlane run crashlytics'? Also can you run fastlane -v and ruby -v and send over those results. Definitely want to have a look at this :+1:

**Comment by janandre** [comment] 2016-04-03 15:20
This are my versions of fastlane and ruby:

<img width="521" alt="bildschirmfoto 2016-04-03 um 16 57 08" src="https://cloud.githubusercontent.com/assets/9200290/14233099/fc38b5e8-f9be-11e5-8c47-ec1fe60a8770.png">

And this is the output when i use the default path (no parameter set).
<img width="1680" alt="bildschirmfoto 2016-04-03 um 17 03 09" src="https://cloud.githubusercontent.com/assets/9200290/14233107/4b4be61e-f9bf-11e5-9ff9-040db7a7b9d0.png">
<img width="1487" alt="bildschirmfoto 2016-04-03 um 17 03 23" src="https://cloud.githubusercontent.com/assets/9200290/14233108/4f01294a-f9bf-11e5-88bc-53c89e0935eb.png">

But theres a new version added to my fabric account, without uploading build.
<img width="639" alt="bildschirmfoto 2016-04-03 um 17 14 03" src="https://cloud.githubusercontent.com/assets/9200290/14233122/8e8c29a2-f9bf-11e5-8c19-314b259eaa65.png">

If i set the crashlytics_path, it runs through smoothly, but nothing happens on fabric side.
As you can see, it seems it jumps over the step of uploading, the success message is almost instantly printed out.
<img width="515" alt="bildschirmfoto 2016-04-03 um 17 13 27" src="https://cloud.githubusercontent.com/assets/9200290/14233136/ca50d190-f9bf-11e5-8c8c-4369f68b7a34.png">

THANKS for your tip with `fastlane run crashlytics`, this worked - as you can see in the picture, 1.0.21 was uploaded successfully :)

But i do not understand, why it does not work inside a lane.
<img width="787" alt="bildschirmfoto 2016-04-03 um 17 20 23" src="https://cloud.githubusercontent.com/assets/9200290/14233145/68ac3488-f9c0-11e5-9575-890cb0ca6aed.png">

**Comment by TKBurner** [comment] 2016-04-04 17:31
Hi @janandre! Great to hear from you. Can you send me the output when your 'fastlane run crashlytics'

Thanks!

**Comment by janandre** [comment] 2016-04-04 18:45
@TKBurner it runs smoothly and uploads correct!

`MacBook-Pro-Jan:Retold2 janandre$ fastlane run crashlytics
[20:31:17]: -------------------------
[20:31:17]: --- Step: crashlytics ---
[20:31:17]: -------------------------
[20:31:17]: To not be asked about this value, you can specify it using 'api_token'
Crashlytics Beta API Token: xxx
[20:32:02]: To not be asked about this value, you can specify it using 'build_secret'
Crashlytics Build Secret: xxx
[20:32:22]: Uploading the build to Crashlytics Beta. Time for some ☕️.
[20:38:43]: Build successfully uploaded to Crashlytics Beta 🌷
[20:38:43]: Result: true
`

**Comment by TKBurner** [comment] 2016-04-05 14:26
@janandre What happens if you don't set the IPA path in the Crashlytics action? It seems like we might not be uploading the one gym is creating. It should automatically hand it off if you call them in the same lane.

Thanks!

**Comment by janandre** [comment] 2016-04-07 10:31
@TKBurner It does not change anything. I added the ipa path during later trys, hoping that it could solve the problem. Without it its the same behaviour. Don't upload or create anything on fabrics side, but print success message.

**Comment by janandre** [comment] 2016-04-07 10:33
Right now i stay at Fastlane 1.68 should i update to 1.80?

**Comment by sgwilym** [comment] 2016-04-07 10:35
I had the same problem with crashlytics not uploading the build and reporting a success — this seems to be resolved by removing the `crashlytics_path` param!

**Comment by janandre** [comment] 2016-04-07 11:25
@sgwilym Tried that too, but than i get this FastlaneCrash like in the screenshot above.

**Comment by TKBurner** [comment] 2016-04-07 13:20
Hi @janandre! Thanks for following up. Can you update Fastlane core and see if your issue is resolved? It looks like your local copy of the gem might be in a bad state.

![image](https://cloud.githubusercontent.com/assets/1987108/14352302/d52e14c6-fca1-11e5-8c38-563f76510fc8.png)

**Comment by janandre** [comment] 2016-04-07 14:02
@TKBurner updated to the newest Version now

<img width="1413" alt="bildschirmfoto 2016-04-07 um 15 58 16" src="https://cloud.githubusercontent.com/assets/9200290/14353504/a441a84a-fcd9-11e5-8a84-3723e6328df0.png">

I think it is the same error.

<img width="1381" alt="bildschirmfoto 2016-04-07 um 16 00 38" src="https://cloud.githubusercontent.com/assets/9200290/14353588/f9aa9896-fcd9-11e5-86e7-e874b36f3c08.png">

This is printed at the beginning. Is this write permission crucial?

**Comment by TKBurner** [comment] 2016-04-08 18:57
Thanks for following up @janandre! I'm going to have the team here take a look and see what could be causing this. Thanks for working with us! :+1:

**Comment by tallyho42** [comment] 2016-04-12 09:27
I'm having absolutely the same issue...in my case it's happening only when I use "groups" argument when running crashlytics...if i use emails, or nothing at all everything works just fine...

```
def upload_to_crashlytics(changelog, notify)
    crashlytics(
        api_token: "XXXXX",
        build_secret: "XXXX",
        notes: changelog,
        notifications: notify,
        groups: ["Team TEST"]
      )
  end
```

the resulting log is identical to the one posted by @janandre previously ...

**Comment by janandre** [comment] 2016-04-12 12:22
@TKBurner Your welcome!
@tallyho42 Thats a good hint! I will try it.

**Comment by TKBurner** [comment] 2016-04-12 14:26
Thanks for following up @tallyho42 and @janandre. Glad we got this pinpointed to the groups argument. We'll follow up once we get a chance to investigate. I'm also going to mark this as help wanted in case someone in the community wants to have a look too 👍

**Comment by mfurtak** [comment] 2016-04-14 18:15
@tallyho42 Would you be willing to share the app_identifier of your app so I can dig a little further on our back-end?

**Comment by mfurtak** [comment] 2016-04-14 18:32
Hi everyone! Thanks for the reports :+1: I have a theory about what is going wrong here.

When using the `groups` parameter, it's important to use the group **alias** names for each group you'd like to distribute to. A group's alias can be found in the web UI. If you're viewing the Beta page, you can open the groups dialog here:

![screen shot 2016-04-14 at 2 27 23 pm](https://cloud.githubusercontent.com/assets/343134/14539176/4bb65c10-024d-11e6-971e-6aa0c9c2f933.png)

And then each group's alias is listed here:

![screen shot 2016-04-14 at 2 22 04 pm](https://cloud.githubusercontent.com/assets/343134/14539018/796f6c92-024c-11e6-868b-0acd9ea4911a.png)

There are a couple reasons why aliases exist:

1. They are restricted to a safer set of characters to try to make command line invocations a bit easier
1. They are created once when the group is created, but are not affected by later edits to the group. This allows your scripts to be stable, even if you decide to change the group's name.

So, in my example case here, I want to specify 

`groups: ["dev-team-1"]` :white_check_mark: 

_not_ 

`groups: ["Android Devs"]` :x: 

Can folks give that a try and let me know what you find? Thanks!

**Comment by mfurtak** [comment] 2016-04-14 18:59
I should note that the original reporter was not using `groups` so I believe the above may help some folks, but doesn't address the original question about inconsistent results when uploading.

**Comment by janandre** [comment] 2016-04-15 06:07
@mfurtak  THANKS! For me this fixed the issue! Now it works like a charm :)
Maybe its possible to print out a hint, if it cannot find the group alias. I don't think
that i am the only one who fell over this.

Great team and product!

**Comment by tallyho42** [comment] 2016-04-15 10:38
Yepp, that was it :) *facepalm* Thanks a lot, really! 

Also, sorry, that we didn't notice this on our own...on our defense though, i haven't found any info about this on fastlane pages...Maybe the error could be more specific or something...

**Comment by mfurtak** [comment] 2016-04-15 14:25
Hi folks! Glad you're back up and running! :rocket: 

I've updated [the documentation](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md#crashlytics-beta) to provide this info as well, so hopefully folks in the future have a better shot. :+1: 

As far as making the tool give a better error message... that's a bit trickier, but we'll see what can be done!

**Comment by fisch0920** [comment] 2016-04-18 10:13
Note that I ran into a similar issue with the `groups` argument to crashlytics.  In general, it is a problem that the crashlytics submit shell action swallows stdout because it just appeared to be crashing until I ran the submit function directly and realized the submit was failing.

```
2016-04-18 16:54:52.462 submit Crashlytics: Crashlytics.framework/submit 1.3.5 (16)
2016-04-18 16:54:52.469 submit Crashlytics: Path to IPA manually provided: fastlane/build/eko.ipa
2016-04-18 16:54:53.004 submit Crashlytics: Path To App: /var/folders/5_/6s453vvn2vn75t4r4xjvgy600000gn/T/eko/Payload/eko.app
2016-04-18 16:55:00.148 submit Crashlytics: Unable to add testers: Project ekogreen is inactive
2016-04-18 16:55:00.148 submit Crashlytics: Failed to add testers/groups to the release
```

This was failing because of the issue described [here](https://twittercommunity.com/t/add-new-ios-app-to-crashlytics-beta-via-command-line/56620), specifically that the project I was trying to upload was "inactive" e.g., hadn't sent any events yet by running the app.  This was very important to my use case for automatically building & uploading hundreds of white-labeled apps.

**Comment by TKBurner** [comment] 2016-04-20 17:16
@fisch0920 Followed up with you on our other ticket 👍

**Comment by jsonfellin** [comment] 2016-04-22 15:39
I'm having a similar issue with publishing to Crashlytics.  Here's the crash report number from the output: "01f5059bb3773a89438d678a73ac4ac6".  It's not the group name issue described above.  Also, it seems to publish about 50% of the time without fail.  I am in Italy and my IPA is 135 MB, I'm guessing these could be an issue?  Thanks for any help.

**Comment by TKBurner** [comment] 2016-04-26 14:16
Hi @jsonfellin! Thanks for reporting those additional details. It seems like it could be a network issue, do you run into this when you submit directly through the Fabric Mac app?

Thanks!

**Comment by jsonfellin** [comment] 2016-04-26 17:32
Thanks for responding, I haven't had any trouble with uploading via the Fabric app though it does take awhile, around 20 minutes.  On my latest release with fastlane I connected to a US VPN and it did manage to go through just fine.  I'll post further crash reports here as they come up.  Thanks again for the great tool!

**Comment by TKBurner** [comment] 2016-04-27 15:41
@jsonfellin Thanks for letting us know. There is a timeout in the crashlytics action that is proabably what you are running into. I'm glad the VPN helped. What country is your local IP in?

**Comment by jsonfellin** [comment] 2016-04-28 06:52
I'm in Italy.  I did another release yesterday on the VPN and it worked fine.  I'll keep you posted.  Thanks!

**Comment by TKBurner** [comment] 2016-04-28 16:13
@jsonfellin Glad to hear you got up and running. Do you have other connectivity issues ever? If this is consistent, email support[at]fabric.io since it seems like a Beta upload issue. Thanks!

**Closed** 2016-07-06 18:14 UTC
Labels: action, bug, help wanted, waiting-for-reply

**Comment by ohwutup** [comment] 2016-07-07 13:59
This thread has gotten long, let me summarize the issues

0. There was a meta-issue here that the output from the Crashlytics tools was not being echoed in failure cases, we improved that with https://github.com/fastlane/fastlane/pull/4526, and hopefully the errors are more clear now.
1. When using the `groups` parameter you must use the `group-alias` and not the group name, the alias can be found in the web-ui.
2. Some users are reporting flakey uploads, especially for larger uploads far from our datacenters in Virginia, USA, we have not found a consistent thread to these.  Some folks have reported success when changing network (e.g to VPN)

Since these issues have gotten interleaved, I'm going to keep this closed for now, but please open a new issue for any problems with fastlane and crashlytics.

**Comment by adriantofan** [comment] 2016-08-11 18:09
I had the same issue, Crashalitycs with cocoapods not working. By running 
`Pods/Crashlytics/Crashlytics.framework/submit 
error: The submit binary delivered by cocoapods is in a new location, under '${PODS_ROOT}/Crashlytics/submit'. This script was put in place for backwards compatibility, but it relies on PODS_ROOT, which does not have a value in your current setup. Please update the path to the submit binary to fix this issue.`
I've discovered that I need to use 
`    crashlytics(crashlytics_path: "./Pods/Crashlytics/",`
instead of 
`    crashlytics(crashlytics_path: "./Pods/Crashlytics/Crashlytics.framework",`

**Comment by TKBurner** [comment] 2016-08-12 14:51
@adriantofan Thanks for sharing your solution. Let me know if you still need any help!

**Comment by adriantofan** [comment] 2016-08-12 15:41
seems to be working now. 

thank you

**Comment by hernangonzalez** [comment] 2016-10-20 16:08
Hi, i am getting this error using `crashlytics(crashlytics_path: "./Pods/Crashlytics/"` :
```
[13:04:40]: Uploading the build to Crashlytics Beta. Time for some ☕️.
[13:05:21]: 2016-10-20 13:04:40.671 submit Crashlytics: Crashlytics.framework/submit 1.3.5 (18)
2016-10-20 13:05:01.533 submit Crashlytics: Added Release Notes Successfully 200
2016-10-20 13:05:21.023 submit Crashlytics: Unable to submit build. Response code: 0
2016-10-20 13:05:21.088 submit Crashlytics: Failed to upload binary
```
If I use `crashlytics(crashlytics_path: "./Pods/Crashlytics/Crashlytics.framework"` it reports ok, though it does not upload anything. 

This is my configuration there:
```
        crashlytics(api_token: "...",
                    build_secret: "...",
                    notes: "Automated build from Fastlane.",
                    crashlytics_path: "./Pods/Crashlytics/",
                    notifications: true)
```

Any idea what's wrong here? Thank you.

**Comment by hernangonzalez** [comment] 2016-10-20 16:40
I got it to work by including the ipa path as well:
```
        crashlytics(api_token: "...",
                    build_secret: "...",
                    notes: "Automated build from Fastlane.",
                    crashlytics_path: "./Pods/Crashlytics/",
                    ipa_path: "./<your target file>.ipa",
                    notifications: true)
```

**Comment by sameer-ahmed** [comment] 2016-10-20 17:12
i am using correct alias for group,  and i am also using 

`crashlytics_path: "./Pods/Crashlytics/"`

still same issue, its says uploaded successfully but binary not actually uploaded to fabric

**Comment by hernangonzalez** [comment] 2016-10-21 13:08
Yes, actually it is randomly working for me now (like 50% of times). I am thinking this might be actually the submit tool on Crashlytics framework, and not a fastlane issue really.

**Comment by A1iAshoor** [comment] 2016-10-25 12:56
@henriquegemignani same here, I thought maybe the file size is large here 200mb but when I do it manually it work fine from fabric.app

**Comment by TKBurner** [comment] 2016-10-25 23:00
@A1iAshoor Are you seeing this 100% of the time? Thanks for working with me.

**Comment by A1iAshoor** [comment] 2016-10-26 08:15
@TKBurner I'd say now it's 100% but it used to work on the second time I push the build, now it's not even working on the second push. The only way it works when I do it through their Fabric.app

This is what I'm using.. crashlytics v.3.8.3 (latest)

```
      crashlytics(
        api_token: "XXX",
        build_secret: "XXX",
        ipa_path: "./XXX.ipa",
        crashlytics_path: "./Pods/Crashlytics",
        notes: "v#{get_version_number}"
      )
```

**Comment by hernangonzalez** [comment] 2016-10-27 12:12
I've been getting 100% of the time, so went ahead and run it manually. It fails for me with groups, so I created an `.sh` to run it with emails. Seems to be working all the time so far.
```
Pods/Crashlytics/submit $token $secret -ipaPath ./Filename.ipa -emails $emails  -notifications YES
```
Issue is definitely within the Crashlytics submit tool in its framewok.

**Comment by TKBurner** [comment] 2016-10-28 15:59
@A1iAshoor Are you using cocoapods or the frameworks to integrate Crashlytics?  Does it succeed if you remove notes? Thanks!

@hernangonzalez Can you share your full input and output? I want to take a look. Thanks so much!

**Comment by A1iAshoor** [comment] 2016-10-30 07:46
@TKBurner hey man, I used to use the framework but when it started to fail, I switched to cocoapods `crashlytics_path: "./Pods/Crashlytics"`

I haven't tried without notes, will give is a shot now, otherwise I'll use @hernangonzalez approach, thanks for sharing mate.

**Comment by A1iAshoor** [comment] 2016-10-31 09:27
Not working `sh "./Pods/Crashlytics/submit XXX XXX -ipaPath ./XXX.ipa -emails XXX -notifications YES"` :(

**Comment by TKBurner** [comment] 2016-11-01 16:22
@A1iAshoor Thanks for following up. Can you add the --verbose flag to your command so I can take a look at the output? Thanks!

**Comment by rafaelnobrepd** [comment] 2016-12-28 17:05
@TKBurner I've been experiencing similar issues with latest Fabric (1.6.11) / Crashlytics (3.8.3) pods
When running with multiple groups in the crashlytics action, it won't send the build to Crashlytics.
Action is called like this:
```
crashlytics(
      api_token:"redacted",
      build_secret:"redacted",
      groups:["beta-testers","alpha-testers],
      crashlytics_path: './Pods/Crashlytics',
      notes_path: './ReleaseNotes.txt',
      notifications: true
    )
```

When running the `submit` binary manually, I noticed that using `-groupAliases "beta-testers, alpha-testers"` works, while `-groupAliases beta-testers, alpha-testers` and `-groupAliases 'beta-testers, alpha-testers'` fails.

According to [this](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/helper/crashlytics_helper.rb#L26) , it looks like fastlane is building one of the last two examples above (sorry as I really am awful at Ruby and don't fully understand what would be produced by that line), which fails on the latest `submit` binary

**Comment by rafaelnobrepd** [comment] 2017-01-06 16:02
I've found a work around to this: don't use an array of aliases. Use a comma separated string instead such as `groups:'"beta-testers,alpha-testers"',`
