### ISSUE TITLE
Automatically upload DSYM to Firebase/Crashlytics

### ISSUE THREAD

**Issue by taglia3** [fastlane/fastlane#13096] opened 2018-08-13 17:23 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I want to automatically upload the .DSYM file to Firebase/Crashlytics.

My GoogleService-Info.plist is located at _"${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/GoogleService-Info.plist"_

I've a RunScript Phase with:
`"${PODS_ROOT}/Fabric/run"`

But it doesn't upload the .DSYM file to the Firebase portal. Why?
Can I resolve by using the _upload_symbols_to_crashlytics_ lane?
How can I configure the gsp_path?

**Comment by taglia3** [comment] 2018-08-14 08:00
Fixed by simply using _upload_symbols_to_crashlytics(gsp_path: gsp_path)_ with _gsp_path_ correctly configured.

**Comment by MauriceArikoglu** [comment] 2018-09-05 14:31
@taglia3 would you be so kind as to show an example of a configured gsp_path? Or point to the direction where one could find details on configuration? Thanks

**Comment by mmdock** [comment] 2018-10-27 02:02
I am also struggling to get this to work.  I have a lane that looks like the following:
```
  desc "Fetch and upload dSYM files to Firebase Crashlytics"
  lane :refresh_dsyms_firebase do |options|
    download_dsyms(version: options[:version])        
    upload_symbols_to_crashlytics(gsp_path: "./App/GoogleService-Info.plist") 
    clean_build_artifacts
  end
```


After that I see:

[17:22:47]: invalid byte sequence in UTF-8
[17:22:47]: invalid byte sequence in UTF-8
[17:22:47]: invalid byte sequence in UTF-8

and one of these for every dSYM file:
[17:22:48]: Shell command exited with exit status  instead of 0.
[17:22:48]: Uploading '70DBE65E-227E-3754-89F2-EEFA6B8EEC2F.dSYM'...

**Comment by leonirqranio** [comment] 2018-10-30 12:38
What is the solution?

**Comment by MauriceArikoglu** [comment] 2018-10-31 09:33
@mmdock I cannot help you. Struggling with this myself. I'll update in case I find a solution

**Comment by eli-symbolab** [comment] 2018-11-15 15:45
Also experiencing this problem.
`Shell command exited with exit status  instead of 0` is puzzling as there's no error code to look up. I don't have the `invalid byte sequence` errors though. No problems if I leave out the `gsp_path`.

**Comment by gableh** [comment] 2018-11-24 10:44
Hi, if you were migrating from Fabric to Firebase then do check if `CRASHLYTICS_API_TOKEN` is being set as an env variable and unset it before running `upload_symbols_to_crashlytics`.

The issue is that if the upload_symbols binary is called with both the api token and gsp path then it seems to ignore the gsp path which makes it end up not uploading to Firebase.

**Comment by mmdock** [comment] 2018-11-24 20:03
@gableh I was just coming back to this thread to say the same! I just figured it out after a co-worker and I debugged for a little while this morning. That executable should know to prioritize the gsm path since everything is migrating to Firebase.

**Comment by Hans92** [comment] 2018-11-28 19:18
I also have this issue. I'm trying to use different name of the .plist file:

```
upload_symbols_to_crashlytics(
			gsp_path: /Resources/GoogleService-Info-" + CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier) + ".plist"
			)
```

`
Also I'm getting:
`invalid byte sequence in UTF-8`
but the upload looks good. The problem is dSYMs never reach Firebase.

**Comment by mmdock** [comment] 2018-11-28 21:17
@Hans92 this is a dumb question, but where is the "Resources" folder located? is the google plist file not located within the project directory?

**Comment by Hans92** [comment] 2018-11-28 21:35
I have to modify my message, sorry. Resources folder is located in the same directory as project file.

I have also checked that it takes a correct file and upload processes is finished without any errors. Still, Crashlytics reports missing dSYMs.

**Comment by gableh** [comment] 2018-11-29 11:30
Check if the upload_symbols binary is being called with a -a option. If it is, it means you still have an api_token variable thats being set somewhere, probably in the env.

**Comment by Hans92** [comment] 2018-11-29 11:36
How can I check it?

**Comment by gableh** [comment] 2018-12-03 02:45
looks perfectly fine to me, theres another line after that which shows the dSYM UDID thats being uploaded. If thats the same as what Crashlytics is looking for as well then I'm not entirely sure what the problem could be.

**Comment by matthewcook333** [comment] 2018-12-12 22:37
Running into the same problem as @Hans92 , where using a specific GoogleService-Info-X.plist, wondering if anyone else also running into same or have solution? The upload processes finishes without any errors, just doesn't show up in Firebase Crashlytics.

**Comment by evertoncunha** [comment] 2018-12-26 15:55
My problem was using uploadDSYM file, from the Carthage distribution, instead upload-symbols, from the Pod distribution. Now it's working fine.

**Comment by ppamorim** [comment] 2019-01-15 14:41
Any solution for this? I am stuck.

**Comment by icorn** [comment] 2019-01-29 16:13
I have the same problem like @Hans92 , @matthewcook333 , and @retsohuang . Are there any news? 

I get `invalid byte sequence in UTF-8` 23 times on every call, even when I change the GoogleService-Info.plist file to an empty file. No dSYM in the Firebase Crashlytics console.

**Comment by mrgrauel** [comment] 2019-02-01 07:58
I also have the same Issue! Why is the issue closed if so many people have a problem?

**Comment by onurtuna** [comment] 2019-03-28 11:49
> Also experiencing this problem.
> `Shell command exited with exit status instead of 0` is puzzling as there's no error code to look up. I don't have the `invalid byte sequence` errors though. No problems if I leave out the `gsp_path`.

@eli-symbolab What do you mean with `leave out`?

**Comment by eli-symbolab** [comment] 2019-03-28 11:54
@onurtuna I mean that if I run `upload_symbols_to_crashlytics()` without specifying `gsp_path` it runs fine, it just doesn't upload to Firebase (I assume).

**Comment by mmdock** [comment] 2019-04-01 22:36
@eli-symbolab that is a short term work around.  All you are doing is uploading to Fabric, which then forwards to Firebase.  Eventually, that won't really be an option as far as I know.

**Comment by mmdock** [comment] 2019-04-01 22:53
So, just to confirm with everyone, the issue is the following (i think):

**Comment by mmdock** [comment] 2019-04-01 23:09
@taglia3 you closed this issue, but I have my gsp path correctly and this isn't working.  This is happening to us who have migrated from Fabric Crashlytics into Firebase Crashlytics.  The migration docs have made no mention of removing the Fabric token (at least not that I saw when I did it back in August or July or whenever).  In order to make upload_symbols_to_crashlytics work, those of use in the weird transition limbo have to either a) not configure gsp path and upload to Fabric which then forwards to Firebase which will break in a month or two, or b) remove fabric token from Info.plist before uploading to firebase each time.  

If I missed that I was to remove the Fabric config or if Firebase have since updated the migration docs to include that, please let me know.  Otherwise, the upload_symbols_to_crashlytics needs to prioritize gsp path over the Fabric token.

**Comment by mmdock** [comment] 2019-04-02 04:10
@onurtuna this issue was mostly resolved successfully 11 days ago via https://github.com/fastlane/fastlane/pull/14439 but only uploads to Firebase crashlytics if you manually set the gsp path. Otherwise, it still runs successfully but will upload to Fabric as mentioned by @eli-symbolab

**Closed** 2019-05-12 17:32 UTC
Labels: status: has-pr, status: waiting-for-reply, tool: action
