### ISSUE TITLE
Authentication credentials are missing or invalid.

### ISSUE THREAD

**Issue by jakubgs** [fastlane/fastlane#20270] opened 2022-05-12 12:18 UTC
### Issue Description
We are seeing iOS build failures due to following issue:
```
Authentication credentials are missing or invalid.
  - Provide a properly configured and signed bearer token, and make sure that it has not expired.
    Learn more about Generating Tokens for API Requests https://developer.apple.com/go/?id=api-generating-tokens
```
I have researched it in this issue:

* https://github.com/status-im/status-react/issues/13352

And it appears others are also experiencing it. It appears to have started today. Most probably the issue is on the Apple side.

### Context
We are using most recent `2.205.2` version as are other people that reported this issue: @Dmytro-Mishchenko and @rborn.

**Comment by jakubgs** [comment] 2022-05-12 12:23
As suggested in these issues and discussions:

* https://github.com/fastlane/fastlane/discussions/18100
* https://github.com/fastlane/fastlane/issues/19072

I - and others - have attempted to change the `duration` parameter for `app_store_connect_api_key` but both default `500` and maximum value of `1200` make no difference.

**Comment by jakubgs** [comment] 2022-05-12 12:24
One red herring that I fond was an expired "Paid Application" agreement:

![image](https://user-images.githubusercontent.com/2212681/168073921-1f70de27-edab-4af2-ae6e-9e922846c476.png)

But accepting it has made no difference. It appears that something must have changed on the Apple Store Connect backend.

**Comment by alizons** [comment] 2022-05-12 12:25
we are seeing that as well. Can it be an issues on Apple / AppStore Connect sides?

**Comment by jakubgs** [comment] 2022-05-12 12:26
Yes, this would be my assumption. We have not changed anything in our Fastlane configuration, nor have we changed Fastlane version of renewed any certificates. The issues started happening today without any correlated changes.

My guess would also be that the problem is on the App Store Connect side.

**Comment by Dmytro-Mishchenko** [comment] 2022-05-12 12:30
The issue appeared around 4 hours ago for us. Reproduces every time.
In addition, AppStore Connect sometimes loads slow for me today, so I'd also assume that issue is on the Apple side.

**Comment by Darkilen** [comment] 2022-05-12 12:31
The issue appeared around 4 hours ago for us too. Reproduces every time too.

**Comment by jesperjohansson** [comment] 2022-05-12 12:34
We are also having this issue currently and we are getting error 500 errors on appstoreconnect.com. Their status page says App Store Connect & App Store Connect API is online/no problems... 😬

**Comment by 1Siger1** [comment] 2022-05-12 12:35
The issue started appear about 4 hours and it stays this way till now.

**Comment by jakubgs** [comment] 2022-05-12 12:36
Our first build failed with this error at `09:23:51` UTC.

**Comment by jakubgs** [comment] 2022-05-12 12:42
As noticed by @JencirJamal Apple finally updated their status page with info about Apple Store Connect API issues:

![image](https://user-images.githubusercontent.com/2212681/168077075-33c62850-6344-47b3-b4a8-eba06b19dc6c.png)

https://developer.apple.com/system-status/

**Comment by SergeyKovalenko** [comment] 2022-05-12 12:43
We faced the same issue. But were managed to upload ipa via Transporter app as a tempo solution.

**Comment by jakubgs** [comment] 2022-05-12 13:03
Looks like it's recovering, we had a successful build a moment ago.

**Comment by rborn** [comment] 2022-05-12 13:13
Still not working for me, will update when it does, if 😅

**Comment by JohannDesobry** [comment] 2022-05-12 13:15
same for me here

**Comment by mrtnlst** [comment] 2022-05-12 13:18
We're seeing the same issue.

**Comment by ErickMaeda** [comment] 2022-05-12 13:32
It's working again for me. (No changes needed)

**Comment by kamvoick** [comment] 2022-05-12 13:56
Same here when launching `match` lane. As a workaround we returned back to [providing FASTLANE_SESSION env](https://docs.fastlane.tools/best-practices/continuous-integration/#environment-variables-to-set)

**Comment by js-adalo** [comment] 2022-05-12 17:08
Is this resolved for everyone? We're still having issues.

**Comment by geoffreyclifton** [comment] 2022-05-12 17:28
Had a few uploads go through just now successfully.

**Comment by kvacquier** [comment] 2022-05-12 21:59
I Still have the issue here.

**Comment by crazymanish** [comment] 2022-05-13 10:10
it seems, AppStoreConnect is back 💪 and to be honest, this issue is out of control from us (Unrelated to Fastlane scripts) so closing this issue...keep shipping! 🚀

**Comment by crazymanish** [comment] 2022-05-13 10:45
Btw, just notice...AppStoreConnect is having issues again! Looks like, some WWDC 🆎 testing is going on... 😂
Let's wait! 
https://developer.apple.com/system-status/

<img width="539" alt="Schermafbeelding 2022-05-13 om 12 41 39 PM" src="https://user-images.githubusercontent.com/5364500/168267677-c665fc4d-5156-4df1-ba9c-08077b41959a.png">

**Comment by crazymanish** [comment] 2022-05-13 11:22
> I created this issue mostly for visibility purposes, 

You have a point...Re-opening this issue again because AppStoreConnect is again not behaving well and as you said, maybe helpful for some new users.
we can close it later when AppStoreConnect will become stable again.  

Thank you.

**Comment by maxckelly** [comment] 2022-06-06 00:54
Seem to be getting this again. Had a successful upload on 2nd June but now getting the same error. Updated fastlane to `2.206.2` and still occurring. Any one else have the same? Apple services seem to all green as well...

**Comment by Vyazovoy** [comment] 2022-06-14 18:19
Same error with `2.206.2`

**Comment by maxckelly** [comment] 2022-06-14 20:14
@Vyazovoy - When I updated my xCode it seemed to fix it.

**Comment by axi92** [comment] 2022-06-30 10:55
I get the error with fastlane 2.206.2 and 2.207.0

**Comment by mcdurdin** [comment] 2022-07-04 22:19
We received the error today as well (and spent some time chasing a secondary error which it turns out has been reported in Fastlane multiple times "Error finding relevant GitHub issues: undefined method `map' for nil:NilClass" - #13877, #12587, #5817, #7274...).

**Closed** 2022-09-03 17:31 UTC
Labels: status: waiting-for-reply

**Comment by jeheonjeol** [comment] 2022-09-14 09:00
Same error with https://github.com/fastlane/fastlane/issues/20645

```
...
Waiting for App Store Connect to finish processing the new build (1.0.0 - 1) for IOS
Waiting for App Store Connect to finish processing the new build (1.0.0 - 1) for IOS
Waiting for App Store Connect to finish processing the new build (1.0.0 - 1) for IOS
...
Authentication credentials are missing or invalid. - Provide a properly configured and signed bearer token, and make sure that it has not expired. Learn more about Generating Tokens for API Requests [https://developer.apple.com/go/?id=api-generating-tokens](https://developer.apple.com/go/?id=api-generating-tokens%1B[0m)
...
fastlane finished with errors
...
```

> fastlane version: `2.194.0`

**Comment by co-dax** [comment] 2022-12-20 21:28
@crazymanish this error is back again.

**Comment by mdgeist** [comment] 2023-01-06 19:01
> @crazymanish this error is back again.

I've seen this happen on and off for a few weeks. Sometimes it happens and sometimes it doesn't even with the duration for the key set to `1200` .

**Comment by ducbm051291** [comment] 2023-02-13 11:07
OMG, Just got this error today :(

**Comment by iTofu** [comment] 2023-03-31 08:47
It still happens…… #21160

**Comment by pavlobu** [comment] 2023-11-27 15:22
Happens on my side sometimes.

```
[15:21:25]: Authentication credentials are missing or invalid. - Provide a properly configured and signed bearer token, and make sure that it has not expired. Learn more about Generating Tokens for API Requests https://developer.apple.com/go/?id=api-generating-tokens
```

It fails on upload_to_testflight step.
But app_store_connect_api_key step is not generating any errors.

**Comment by pavlobu** [comment] 2023-12-06 18:01
> Also seeing this behavior @pavlobu.

setting FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD didn't solve the problem in my case
