### ISSUE TITLE
Fastlane_core's strict Commander version requirement makes updating gems difficult

### ISSUE THREAD

**Issue by hyperspacemark** [fastlane/fastlane#4028] opened 2016-04-01 17:42 UTC
Commander is a common gem dependency. Fastlane_core's gemspec specifies `== 4.3.5`. If other gems in a Gemfile are specifying a version of Commander which resolves to higher than `4.3.5` according to their pessimistic requirement, that gem cannot be updated to its latest version.

Would it be possible to use a less strict version requirement for Commander?

**Comment by asfalcone** [comment] 2016-04-01 18:10
Closing as a dupe of #3966. Please track the conversation there! :+1:

**Closed by asfalcone** 2016-04-01 18:10 UTC
Labels: fastlane_core
