### ISSUE TITLE
App-specific password does not seem to work

### ISSUE THREAD

**Issue by famanson** [fastlane/fastlane#7199] opened 2016-11-28 11:03 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I generated a fresh app-specific password and tried running `deliver` to upload my ipa when it said the credentials are invalid

##### Complete output when running fastlane, including the stack trace and command used

```
export DELIVER_PASSWORD="<fresh app-specific password>" && deliver --username sonnycnn24117@gmail.com --app 1037854626 --team_id 9DE4B762BF --ipa build/Esplorio.ipa --skip_screenshots --skip_metadata --force
[10:48:02]: Login to iTunes Connect (sonnycnn24117@gmail.com)
The login credentials for 'sonnycnn24117@gmail.com' seem to be wrong
The password was taken from the environment variable
Please make sure it is correct
Please run this tool again to apply the new password
```

### Environment

```
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                         |
| ------------------- | --------------------------------------------- |
| OS                  | 10.12.1                                       |
| Ruby                | 2.2.4                                         |
| Bundler?            | false                                         |
| Git                 | git version 2.7.4                             |
| Installation Source | /Users/son/.rbenv/versions/2.2.4/bin/fastlane |
| Host                | Mac OS X 10.12.1 (16B2555)                    |
| Ruby Lib Dir        | /Users/son/.rbenv/versions/2.2.4/lib          |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                    |
| Is contained        | false                                         |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/   |
| Xcode Version       | 8.1                                           |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file defines all the lanes

default_platform :ios


platform :ios do
  lane :build do
    desc "Perform a beta build"
    gym
    pilot
    hockey(
       api_token: ENV['HOCKEY_API_TOKEN'],
       ipa: './build/esplorio.ipa',
       dsym: './build/esplorio.app.dSYM.zip'
    )
  end

  lane :beta_build do
    desc "Increment a beta build"
    increment_build_number(xcodeproj: 'esplorio.xcodeproj')
  end

  desc "Increment a beta version"
  lane :beta_version do
    increment_build_number
    increment_version_number
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "io.esplor.ios" # The bundle identifier of your app
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| spaceship           | 0.38.1  | ✅ Up-To-Date  |
| fastlane_core       | 0.57.1  | ✅ Up-To-Date  |
| deliver             | 1.15.1  | ✅ Up-To-Date  |
| snapshot            | 1.16.4  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| pem                 | 1.4.0   | ✅ Up-To-Date  |
| cert                | 1.4.4   | ✅ Up-To-Date  |
| sigh                | 1.11.2  | ✅ Up-To-Date  |
| produce             | 1.3.1   | ✅ Up-To-Date  |
| gym                 | 1.12.1  | ✅ Up-To-Date  |
| pilot               | 1.12.1  | ✅ Up-To-Date  |
| scan                | 0.14.2  | ✅ Up-To-Date  |
| supply              | 0.7.1   | ✅ Up-To-Date  |
| match               | 0.11.0  | ✅ Up-To-Date  |
| screengrab          | 0.5.6   | ✅ Up-To-Date  |
| fastlane            | 1.110.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| terminal-table            | 1.4.5        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.9.2        |
| faraday_middleware        | 0.10.0       |
| dotenv                    | 2.1.0        |
| net-ssh                   | 3.1.1        |
| net-sftp                  | 2.1.2        |
| plist                     | 3.1.0        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| krausefx-shenzhen         | 0.14.11      |
| slack-notifier            | 1.5.1        |
| rouge                     | 1.10.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.6.3        |
| addressable               | 2.3.8        |
| colored                   | 1.2          |
| credentials_manager       | 0.16.2       |
| multi_xml                 | 0.5.5        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160310 |
| http-cookie               | 1.0.2        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| xcode-install             | 2.0.2        |
| word_wrap                 | 1.0.0        |
| multi_json                | 1.11.2       |
| babosa                    | 1.0.2        |
| excon                     | 0.45.4       |
| gh_inspector              | 1.0.2        |
| fastlane_core             | 0.57.1       |
| bundler                   | 1.12.5       |
| mini_magick               | 4.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0221  |
| mime-types                | 3.0          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.3        |
| memoist                   | 0.14.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.2        |
| googleauth                | 0.5.1        |
| thor                      | 0.19.1       |
| httpclient                | 2.7.1        |
| google-api-client         | 0.9.4        |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.9.1        |
| activesupport             | 4.2.7.1      |
| json                      | 1.8.3        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| nanaimo                   | 0.2.2        |
| xcodeproj                 | 1.4.1        |
</details>

*generated on:* **2016-11-28**
</details>
```

**Comment by hjanuschka** [comment] 2016-11-28 14:48
how did you generate the app specific PW? - see sample here: https://github.com/fastlane/fastlane/issues/6095#issuecomment-258125943

**Comment by famanson** [comment] 2016-11-29 09:57
@hjanuschka I followed that guide. It has been working for us brilliantly for the past month then it stopped working yesterday. I've no idea why this happened... :(

**Comment by hjanuschka** [comment] 2016-11-29 10:35
can you try `spaceauth -u user@email.com` maybe the 2fa cookie has expired, i remember something about a month lifetime of the cookie

**Comment by famanson** [comment] 2016-11-29 11:01
@hjanuschka `spaceauth -u sonnycnn24117@gmail.com` with my main password + 2FA is fine, but running it with an app-specific password still fails

We are not using `FASTLANE_SESSION` though. On top of that the `deliver` command I mentioned in the PR description is run on a fresh machine every time on CI so should the cookie really be a problem?

**Comment by hjanuschka** [comment] 2016-11-29 11:36
sorry - i  don't use 2fa on my itc accounts, i have to pass this on.
@TKBurner  can you help here

**Comment by famanson** [comment] 2016-12-02 09:47
@hjanuschka @TKBurner hi guys, did you get on with this? I am not sure what I am doing wrong here so any kind of help/direction would be appreciated

**Comment by quetool** [comment] 2016-12-07 18:54
Hi, I have same issue, I tried by generating a specific password on https://appleid.apple.com/account/manage
I also tried by generating the FASTLANE_SESSION
I also tried by setting FASTLANE_PASSWORD in my Appfile

Nothing works yet! I always get same error

<img width="1391" alt="captura de pantalla 2016-12-07 a las 15 53 43" src="https://cloud.githubusercontent.com/assets/14978705/20981964/64f1804e-bc95-11e6-861a-8bb34291c54b.png">

**Comment by quetool** [comment] 2016-12-07 19:38
i solved it, this is how i did:

I run 

`fatlane-credentials remove -- username myusername`

then i run my lane again (fastlane release), wich is conformed like this

```
lane :release do
    produce
    pem
    cert
    sigh
    gym(scheme: "MyScheme")
    # snapshot
    deliver(force: true)
    # frameit
  end
```

when the terminal prompted me for my password FIRST TIME i entered my apple id password
the SECOND TIME i entered the specific generated password from https://appleid.apple.com/account/manage WITH OUT the dash char "-"
and all worked like a charm

I hope it helps!

**Comment by famanson** [comment] 2016-12-08 10:04
@quetool I thought when you entered your password the first time it is already cached inside credentials manager? Meaning it will just work like you entered your usual password the next time? Or am I missing something here?

I tried what you did and it's still failing. It fails even on a fresh machine on our CI still...

**Comment by famanson** [comment] 2016-12-08 10:06
@quetool it's worth noting your error output is completely different from mine though. Mine simply fails saying

```
[10:06:05]: Login to iTunes Connect (username)
The login credentials for 'username' seem to be wrong
```

**Comment by quetool** [comment] 2016-12-08 13:55
No, it is not in credentials manager because i remove it with the first command

`fastlane-credentials remove --username myusername`

I am new but I will try to help.

In your first post you say 

```
export DELIVER_PASSWORD="<fresh app-specific password>" && deliver --username sonnycnn24117@gmail.com --app 1037854626 --team_id 9DE4B762BF --ipa build/Esplorio.ipa --skip_screenshots --skip_metadata --force
[10:48:02]: Login to iTunes Connect (sonnycnn24117@gmail.com)
The login credentials for 'sonnycnn24117@gmail.com' seem to be wrong
**_The password was taken from the environment variable_**
Please make sure it is correct
Please run this tool again to apply the new password
```

So you are trying to pass the password in the command line with DELIVER_PASSWORD="<fresh app-specific password>" but as you have setted the password in your ENV variable too, it seems that is what is taking, ignoring the passed one from the command line... I am in the right way?

Can you delete the password from the ENV variables (i thought you put it in the Appfile like me, I have to delete it, plus, it is not secure) and then try to perform my solution? When you perform my solution, if I am in the right way, you will have to put first the "original" password of your Apple ID and if you get the 2F error (like me) with the terminal waiting for a password, you put then your app specific password...

Let me know.... Sorry for my english!

**Comment by quetool** [comment] 2016-12-09 00:20
@famanson Fastlane team answered me in Twitter ![](http://i.imgur.com/C1NipSH.jpg)

**Comment by KrauseFx** [comment] 2017-01-04 16:18
We just spent some time trying to reproduce the issue, however everything went flawlessly for us. Could you please update to the latest _fastlane_ release, make sure you run 2.4.0 by running `fastlane -v` and try it again? 

If you have 2 factor or 2 step enabled, make sure that the first time you get asked for a 4 or 6 digits code from your phone, and then later on when uploading a binary using the transporter, you should be asked for an application specific password. 

We updated the 2 factor docs to be easier to understand, especially when using it on a CI machine:

Please let us know if that works for you, and if not, share the complete output when running _fastlane_ with your configuration files.

---

### Support for CI machines

#### Web sessions

To generate a web session for your CI machine, use

```sh
fastlane spaceauth -u apple@krausefx.com
```

This will authenticate you and provide a string that can be transferred to your CI system:

```
export FASTLANE_SESSION='---\n- !ruby/object:HTTP::Cookie\n  name: DES5c148586dfd451e55afbaaa5f62418f91\n  value: HSARMTKNSRVTWFla1+yO4gVPowH17VaaaxPFnUdMUegQZxqy1Ie1c2v6bM1vSOzIbuOmrl/FNenlScsd/NbF7/Lw4cpnL15jsyg0TOJwP32tC/NguPiyOaaaU+jrj4tf4uKdIywVaaaFSRVT\n  domain: idmsa.apple.com\n  for_domain: true\n  path: "/"\n  secure: true\n  httponly: true\n  expires: 2016-04-27 23:55:56.000000000 Z\n  max_age: \n  created_at: 2016-03-28 16:55:57.032086000 -07:00\n  accessed_at: 2016-03-28 19:11:17.828141000 -07:00\n'
```

Copy everything from `---\n` to your CI server and provide it as environment variable named `FASTLANE_SESSION`.

#### Transporter

If you want to upload builds to TestFlight/iTunes Connect from your CI, you have to generate an application specific password:

1. Visit [appleid.apple.com/account/manage](https://appleid.apple.com/account/manage)
1. Generate a new application specific password
1. Provide the application specific password using an environment variable `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`.

Alternatively you can enter the password when you're asked the first time _fastlane_ uploads a build.

**Comment by jeffyoung** [comment] 2017-01-12 15:09
Hi @KrauseFx. On the other thread, I was just trying to understand what is needed to ensure the app-specific password is picked up by CI.  (I'm working on adding this support for Visual Studio Team Services and wanted to be clear about what I need to do.)  So it sounds like there needs to be 2 env vars, FASTLANE_SESSION as well as FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD set in order to for 2FA to work from a CI build.  Once I get my task updated, I can try them out.  I just want to be sure I understand what I need to send to fastlane before doing the work.

**Comment by KrauseFx** [comment] 2017-01-12 15:33
> So it sounds like there needs to be 2 env vars, FASTLANE_SESSION as well as FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD set in order to for 2FA to work from a CI build
That is correct. The `FASTLANE_SESSION` is used for everything around the Developer Portal and iTunes Connect, and the `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD` is only use for the iTunes Transporter to upload the binary to iTunes Connect. 
Without 2 factor enabled, none of those values need to be provided 👍

**Comment by KrauseFx** [comment] 2017-01-13 09:25
I'll close this issue for now, please submit a new one if you're still running into problems 👍

**Closed by KrauseFx** 2017-01-13 09:25 UTC

**Comment by RedPlumber** [comment] 2017-01-27 12:17
@KrauseFx 
![screen shot 2017-01-27 at 12 16 44](https://cloud.githubusercontent.com/assets/1003786/22370684/8d2596fa-e48a-11e6-9d41-7d45bd1cf7e3.png)
please can I get some help? Where and how do I need to specify FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD and FASTLANE_SESSION ?
I am using Jenkins and Fastlane uploading using test flight action. Thanks

**Comment by KrauseFx** [comment] 2017-04-04 22:10
Hey everyone, _fastlane_ now fully supports both two-factor and two-step verification 👋 

Please make sure to update to the latest version of _fastlane_ by running 

```
fastlane update_fastlane
```

If you use a `Gemfile`, just run `bundle update`

### On your computer 🚀
To use _fastlane_ with two-factor, just run _fastlane_ as you usually would. You'll be asked for the verification method, and a 4 or 6 digits pin. Everything will just work out of the box 📦 

### On your continuous integration system 💻 
Check out the [official two-factor docs](https://docs.fastlane.tools/best-practices/continuous-integration/#two-step-or-two-factor-auth) for more information on how to setup two-step on CI system. You'll have to authenticate on your local machine to get a session cookie, which you then transfer to your CI.

----

If you have any issues setting this up, please submit [a new issue](https://github.com/fastlane/fastlane/issues/new) so we can help you get up and running 👍

**Comment by pmadruga** [comment] 2017-04-11 09:31
I solved this by just removing the dashes of the generated password for a specific application, just as @quetool mentioned. There was no need to remove the username and add it again.
