### ISSUE TITLE
Problem uploading screenshots with Deliver

### ISSUE THREAD

**Issue by ZevEisenberg** [fastlane/fastlane#9304] opened 2017-05-28 23:44 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I'm running `fastlane deliver --skip_binary_upload --skip_metadata` to upload some screenshots. I already uploaded the binary, but the screenshot upload failed in the same way as documented in this bug, so I'm trying to re-upload the screenshots only. It keeps failing with the same error. The build is showing up on iTunes Connect, in the state "Prepare for Submission". There are existing screenshots from the prior version.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you
**Note:** The command I used reported that `--capture_output` was an invalid option, so I've copied and pasted.

```
$ bundle exec fastlane deliver --skip_binary_upload --skip_metadata --verbose --force
Successfully loaded Appfile at path '/Users/igeek/Projects/Padiddle 2/Padiddle/fastlane/Appfile'
- app_identifier: 'com.zeveisenberg.Padiddle'
- apple_id: 'zev@zeveisenberg.com'
- team_id: '2KJHM26Y46'
-------
INFO [2017-05-28 19:41:34.88]: Successfully loaded '/Users/igeek/Projects/Padiddle 2/Padiddle/fastlane/Deliverfile' 📄

+---------------------+-------------------------+
| Detected Values from './fastlane/Deliverfile' |
+---------------------+-------------------------+
| metadata_path       | ../../Padiddle metadata |
+---------------------+-------------------------+

INFO [2017-05-28 19:41:34.88]: Login to iTunes Connect (zev@zeveisenberg.com)
Looking for iTunes Connect Team with ID 619522
INFO [2017-05-28 19:41:36.98]: Login successful

+-----------------------+---------------------------+
|              deliver 2.35.1 Summary               |
+-----------------------+---------------------------+
| skip_binary_upload    | true                      |
| skip_metadata         | true                      |
| force                 | true                      |
| metadata_path         | ../../Padiddle metadata   |
| screenshots_path      | ./fastlane/screenshots    |
| app_version           | 2.0                       |
| username              | zev@zeveisenberg.com      |
| app_identifier        | com.zeveisenberg.Padiddle |
| edit_live             | false                     |
| ipa                   | Padiddle.ipa              |
| platform              | ios                       |
| skip_screenshots      | false                     |
| submit_for_review     | false                     |
| automatic_release     | false                     |
| dev_portal_team_id    | 2KJHM26Y46                |
| overwrite_screenshots | false                     |
+-----------------------+---------------------------+

INFO [2017-05-28 19:41:37.87]: Making sure the latest version on iTunes Connect matches '2.0' from the ipa file...
INFO [2017-05-28 19:41:39.18]: '2.0' is the latest version on iTunes Connect
INFO [2017-05-28 19:41:40.56]: Starting with the upload of screenshots...
INFO [2017-05-28 19:41:40.57]: Activating languages en-US, fr-Fr, it, zh-Hans, zh-Hant...

Looking for related GitHub issues on fastlane/fastlane...
Search query: The request could not be completed because:
	There are one or more errors on the page.

URL: https://api.github.com/search/issues?q=The%20request%20could%20not%20be%20completed%20because:%0A%09There%20are%20one%20or%20more%20errors%20on%20the%20page.+repo:fastlane/fastlane
➡️  deliver: error when setting phone number
    https://github.com/fastlane/fastlane/issues/8839 [open] 6 💬
    2 weeks ago

➡️  Incorrect error message when trying to upload build while the app is in Waiting-for-review status [mac]
    https://github.com/fastlane/fastlane/issues/7905 [open] 6 💬
    30 Mar 2017

➡️  Fastlane Deliver failing after "activating languges"
    https://github.com/fastlane/fastlane/issues/9050 [open] 4 💬
    3 weeks ago

and 17 more at: https://github.com/fastlane/fastlane/search?q=The%20request%20could%20not%20be%20completed%20because:%0A%09There%20are%20one%20or%20more%20errors%20on%20the%20page.&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/igeek/.rvm/gems/ruby-2.2.4/gems/fastlane-2.35.1/spaceship/lib/spaceship/tunes/tunes_client.rb:162:in `handle_itc_response': [!] The request could not be completed because: (Spaceship::TunesClient::ITunesConnectError)
	There are one or more errors on the page.
	from /Users/igeek/.rvm/gems/ruby-2.2.4/gems/fastlane-2.35.1/spaceship/lib/spaceship/tunes/tunes_client.rb:324:in `block in update_app_version!'
	from /Users/igeek/.rvm/gems/ruby-2.2.4/gems/fastlane-2.35.1/spaceship/lib/spaceship/tunes/tunes_client.rb:1283:in `with_tunes_retry'
	from /Users/igeek/.rvm/gems/ruby-2.2.4/gems/fastlane-2.35.1/spaceship/lib/spaceship/tunes/tunes_client.rb:317:in `update_app_version!'
	from /Users/igeek/.rvm/gems/ruby-2.2.4/gems/fastlane-2.35.1/spaceship/lib/spaceship/tunes/app_version.rb:362:in `save!'
	from /Users/igeek/.rvm/gems/ruby-2.2.4/gems/fastlane-2.35.1/deliver/lib/deliver/upload_screenshots.rb:35:in `upload'
	from /Users/igeek/.rvm/gems/ruby-2.2.4/gems/fastlane-2.35.1/deliver/lib/deliver/runner.rb:63:in `upload_metadata'
	from /Users/igeek/.rvm/gems/ruby-2.2.4/gems/fastlane-2.35.1/deliver/lib/deliver/runner.rb:21:in `run'
	from /Users/igeek/.rvm/gems/ruby-2.2.4/gems/fastlane-2.35.1/deliver/lib/deliver/commands_generator.rb:67:in `block (2 levels) in run'
	from /Users/igeek/.rvm/gems/ruby-2.2.4/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/igeek/.rvm/gems/ruby-2.2.4/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/igeek/.rvm/gems/ruby-2.2.4/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Users/igeek/.rvm/gems/ruby-2.2.4/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/igeek/.rvm/gems/ruby-2.2.4/gems/fastlane-2.35.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/igeek/.rvm/gems/ruby-2.2.4/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Users/igeek/.rvm/gems/ruby-2.2.4/gems/fastlane-2.35.1/deliver/lib/deliver/commands_generator.rb:168:in `run'
	from /Users/igeek/.rvm/gems/ruby-2.2.4/gems/fastlane-2.35.1/deliver/lib/deliver/commands_generator.rb:12:in `start'
	from /Users/igeek/.rvm/gems/ruby-2.2.4/gems/fastlane-2.35.1/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Users/igeek/.rvm/gems/ruby-2.2.4/gems/fastlane-2.35.1/bin/fastlane:20:in `<top (required)>'
	from /Users/igeek/.rvm/gems/ruby-2.2.4/bin/fastlane:23:in `load'
	from /Users/igeek/.rvm/gems/ruby-2.2.4/bin/fastlane:23:in `<main>'
	from /Users/igeek/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `eval'
	from /Users/igeek/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `<main>'
```
### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                             |
| --------------------------- | ------------------------------------------------- |
| OS                          | 10.12.5                                           |
| Ruby                        | 2.2.4                                             |
| Bundler?                    | true                                              |
| Git                         | git version 2.13.0                                |
| Installation Source         | ~/.rvm/gems/ruby-2.2.4/bin/fastlane               |
| Host                        | Mac OS X 10.12.5 (16F73)                          |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.2.4/lib                      |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                       |
| Is contained                | false                                             |
| Is homebrew                 | false                                             |
| Is installed via Fabric.app | false                                             |
| Xcode Path                  | /Applications/Xcode_8.3.2.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.96.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."

  end

  desc "Runs all the tests"
  lane :test do
    scan(scheme: "Padiddle")
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(
    scheme: "Padiddle",
    include_symbols: true,
    include_bitcode: true
    )
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(
    scheme: "Padiddle",
    include_symbols: true,
    include_bitcode: true
    )
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.zeveisenberg.Padiddle" # The bundle identifier of your app
apple_id "zev@zeveisenberg.com" # Your Apple email address

team_id "2KJHM26Y46"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.35.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| i18n                      | 0.8.1        |
| minitest                  | 5.10.2       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.3        |
| activesupport             | 4.2.8        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.1        |
| clamp                     | 0.6.5        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.2.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.2.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.0.3        |
| molinillo                 | 0.5.7        |
| ruby-macho                | 1.1.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| cocoapods                 | 1.2.1        |
| colored                   | 1.2          |
| colorize                  | 0.8.1        |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.55.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.12.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.28       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.2.1        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 0.0.4        |
| synx                      | 0.2.1        |
</details>

*generated on:* **2017-05-28**
</details>

**Comment by tsafrir** [comment] 2017-05-29 12:42
I got a similar issue.
with skip binary but with metadata. 
deliver failed with this message:
`You must add at least one screenshot. You must add at least one screenshot. [en-US]: You must add at least one screenshot. [en-US]: You must add at least one screenshot. There are one or more errors on the page.`

**Comment by ohayon** [comment] 2017-05-31 17:30
Hey @ZevEisenberg, thanks for raising this issue! According to some of our internal tools, it looks like this was caused by an issue on iTC servers. Are you still seeing this issue? Or have you been able to be successful with this flow since? cc @tsafrir Thanks! 🚀

**Comment by ZevEisenberg** [comment] 2017-06-01 02:48
@ohayon thanks for checking in. I just updated Fastlane to the latest release and tried again, and I'm sorry to report that I'm still seeing the same issue:

<details><summary>Terminal Output</summary>

```bundle exec fastlane deliver --skip_binary_upload --skip_metadata --verbose --force
Successfully loaded Appfile at path '/Users/igeek/Projects/Padiddle 2/Padiddle/fastlane/Appfile'
- app_identifier: 'com.zeveisenberg.Padiddle'
- apple_id: 'zev@zeveisenberg.com'
- team_id: '2KJHM26Y46'
-------
INFO [2017-05-31 22:45:54.20]: Successfully loaded '/Users/igeek/Projects/Padiddle 2/Padiddle/fastlane/Deliverfile' 📄

+---------------------+-------------------------+
| Detected Values from './fastlane/Deliverfile' |
+---------------------+-------------------------+
| metadata_path       | ../../Padiddle metadata |
+---------------------+-------------------------+

INFO [2017-05-31 22:45:54.21]: Login to iTunes Connect (zev@zeveisenberg.com)
Looking for iTunes Connect Team with ID 619522
INFO [2017-05-31 22:45:56.46]: Login successful

+-----------------------+---------------------------+
|              deliver 2.36.0 Summary               |
+-----------------------+---------------------------+
| skip_binary_upload    | true                      |
| skip_metadata         | true                      |
| force                 | true                      |
| metadata_path         | ../../Padiddle metadata   |
| screenshots_path      | ./fastlane/screenshots    |
| app_version           | 2.0                       |
| username              | zev@zeveisenberg.com      |
| app_identifier        | com.zeveisenberg.Padiddle |
| edit_live             | false                     |
| ipa                   | Padiddle.ipa              |
| platform              | ios                       |
| skip_screenshots      | false                     |
| submit_for_review     | false                     |
| automatic_release     | false                     |
| dev_portal_team_id    | 2KJHM26Y46                |
| overwrite_screenshots | false                     |
+-----------------------+---------------------------+

INFO [2017-05-31 22:45:57.28]: Making sure the latest version on iTunes Connect matches '2.0' from the ipa file...
INFO [2017-05-31 22:45:59.14]: '2.0' is the latest version on iTunes Connect
INFO [2017-05-31 22:46:00.67]: Starting with the upload of screenshots...
INFO [2017-05-31 22:46:00.67]: Activating languages en-US, fr-Fr, it, zh-Hans, zh-Hant...

Looking for related GitHub issues on fastlane/fastlane...
Search query: The request could not be completed because:
	There are one or more errors on the page.

URL: https://api.github.com/search/issues?q=The%20request%20could%20not%20be%20completed%20because:%0A%09There%20are%20one%20or%20more%20errors%20on%20the%20page.+repo:fastlane/fastlane
➡️  deliver: error when setting phone number
    https://github.com/fastlane/fastlane/issues/8839 [open] 6 💬
    2 weeks ago

➡️  Incorrect error message when trying to upload build while the app is in Waiting-for-review status [mac]
    https://github.com/fastlane/fastlane/issues/7905 [open] 7 💬
    2 days ago

➡️  Problem uploading screenshots with Deliver
    https://github.com/fastlane/fastlane/issues/9304 [open] 3 💬
    9 hours ago

and 18 more at: https://github.com/fastlane/fastlane/search?q=The%20request%20could%20not%20be%20completed%20because:%0A%09There%20are%20one%20or%20more%20errors%20on%20the%20page.&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/igeek/.rvm/gems/ruby-2.2.4/gems/fastlane-2.36.0/spaceship/lib/spaceship/tunes/tunes_client.rb:162:in `handle_itc_response': [!] The request could not be completed because: (Spaceship::TunesClient::ITunesConnectError)
	There are one or more errors on the page.
	from /Users/igeek/.rvm/gems/ruby-2.2.4/gems/fastlane-2.36.0/spaceship/lib/spaceship/tunes/tunes_client.rb:324:in `block in update_app_version!'
	from /Users/igeek/.rvm/gems/ruby-2.2.4/gems/fastlane-2.36.0/spaceship/lib/spaceship/tunes/tunes_client.rb:1283:in `with_tunes_retry'
	from /Users/igeek/.rvm/gems/ruby-2.2.4/gems/fastlane-2.36.0/spaceship/lib/spaceship/tunes/tunes_client.rb:317:in `update_app_version!'
	from /Users/igeek/.rvm/gems/ruby-2.2.4/gems/fastlane-2.36.0/spaceship/lib/spaceship/tunes/app_version.rb:362:in `save!'
	from /Users/igeek/.rvm/gems/ruby-2.2.4/gems/fastlane-2.36.0/deliver/lib/deliver/upload_screenshots.rb:35:in `upload'
	from /Users/igeek/.rvm/gems/ruby-2.2.4/gems/fastlane-2.36.0/deliver/lib/deliver/runner.rb:63:in `upload_metadata'
	from /Users/igeek/.rvm/gems/ruby-2.2.4/gems/fastlane-2.36.0/deliver/lib/deliver/runner.rb:21:in `run'
	from /Users/igeek/.rvm/gems/ruby-2.2.4/gems/fastlane-2.36.0/deliver/lib/deliver/commands_generator.rb:67:in `block (2 levels) in run'
	from /Users/igeek/.rvm/gems/ruby-2.2.4/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/igeek/.rvm/gems/ruby-2.2.4/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/igeek/.rvm/gems/ruby-2.2.4/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Users/igeek/.rvm/gems/ruby-2.2.4/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/igeek/.rvm/gems/ruby-2.2.4/gems/fastlane-2.36.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:39:in `run!'
	from /Users/igeek/.rvm/gems/ruby-2.2.4/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Users/igeek/.rvm/gems/ruby-2.2.4/gems/fastlane-2.36.0/deliver/lib/deliver/commands_generator.rb:168:in `run'
	from /Users/igeek/.rvm/gems/ruby-2.2.4/gems/fastlane-2.36.0/deliver/lib/deliver/commands_generator.rb:12:in `start'
	from /Users/igeek/.rvm/gems/ruby-2.2.4/gems/fastlane-2.36.0/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Users/igeek/.rvm/gems/ruby-2.2.4/gems/fastlane-2.36.0/bin/fastlane:20:in `<top (required)>'
	from /Users/igeek/.rvm/gems/ruby-2.2.4/bin/fastlane:23:in `load'
	from /Users/igeek/.rvm/gems/ruby-2.2.4/bin/fastlane:23:in `<main>'
	from /Users/igeek/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `eval'
	from /Users/igeek/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `<main>'
```

</details>

**Comment by ohayon** [comment] 2017-06-01 17:27
Thanks for the update @ZevEisenberg and apologies for the trouble! I think this could have something to do with the `--skip_metadeta` option not being properly supported. Looking into this and will hopefully have a fix for you soon! 🐙

**Comment by ohayon** [comment] 2017-06-02 20:28
Turns out this was an issue with case sensitivity of language codes as directory names and Apple has apparently decided to enforce case sensitivity. We just pushed a fix that will make sure screenshot directories can use case-insensitive language codes.  https://github.com/fastlane/fastlane/pull/9349

**Comment by ohayon** [comment] 2017-06-02 20:28
Thanks to @ZevEisenberg for help debugging!

**Closed by ohayon** 2017-06-02 20:28 UTC
