### ISSUE TITLE
Mapping file does not get uploaded along with the APK for Android

### ISSUE THREAD

**Issue by nabhak25** [fastlane/fastlane#11888] opened 2018-02-21 12:14 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>I have tried to upload mapping file by specifying its path in the Fastfile. Also tried with using supply command directly in the terminal. I checked for existing issues which may have addressed this,
 but the links keep on redirecting to new issues and no solution. Please help.
</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.5 (Apple Git-94)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  #desc "Runs all the tests"
  #lane :test do
    #gradle(task: "test")
  #end

  #desc "Submit a new Beta Build to Crashlytics Beta"
  #lane :beta do
    #gradle(task: "assembleRelease")
    #crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  #end

  #desc "Deploy a new version to the Google Play"
  #lane :deploy do
    #gradle(task: "assembleRelease")
    #upload_to_play_store
  #end
  
  desc "Information: Print version codes"
  lane :print do
    google_play_track_version_codes(
    track: 'production'
    )
 end
 
 desc "Deploy a Beta version to the Google Play"
  lane :beta do
    gradle(task: 'clean')
    gradle(
      task: "assemble",
      build_type: "Release",
      print_command: false,
    upload_to_play_store(
    track: 'beta',
    check_superseded_tracks: true,
    mapping: "path/to/mapping/file"
    )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file "path/to/json/key" # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name "app.package.name" # e.g. com.krausefx.app
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.81.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.6        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.2        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| commander-fastlane        | 4.4.6        |
| highline                  | 1.7.10       |
| excon                     | 0.60.0       |
| CFPropertyList            | 2.3.6        |
| libxml-ruby               | 3.0.0        |
| plist                     | 3.4.0        |
| fastimage                 | 2.1.1        |
</details>

*generated on:* **2018-02-21**
</details></pre>
</details>

**Comment by olivierg13** [comment] 2018-02-21 16:20
Hey folks,

I got the same problem today, it looks like a regression it was working 2 weeks ago.

Summary when uploading a new apk:
`
+-------------------------+----------------------------------------------------+
[18:05:27] |                          [32mSummary for supply 2.81.0[0m                           |
[18:05:27] +-------------------------+----------------------------------------------------+
[18:05:27] | apk                     | ../dist/netflix-5.14-25917-release.apk             |
[18:05:27] | mapping                 | build/outputs/mapping/release/mapping.txt          |
[18:05:27] | track                   | beta                                               |
[18:05:27] | skip_upload_metadata    | true                                               |
[18:05:27] | skip_upload_images      | true                                               |
[18:05:27] | skip_upload_screenshots | true                                               |
[18:05:27] | package_name            | com.netflix.mediaclient                            |
[18:05:27] | metadata_path           | ./fastlane/metadata/android                        |
[18:05:27] | json_key                | fastlane/metatron/root/metatron/decrypted/key.json |
[18:05:27] | skip_upload_apk         | false                                              |
[18:05:27] | validate_only           | false                                              |
[18:05:27] | check_superseded_tracks | false                                              |
[18:05:27] +-------------------------+----------------------------------------------------+
[...] (some preparing stuff)
[18:05:34] [02:05:19]: Preparing apk at path '../dist/netflix-5.14-25917-release.apk' for upload...
[18:05:43] [02:05:28]: Updating track 'beta'...
[18:05:44] [02:05:29]: Uploading all changes to Google Play...
[18:05:50] [02:05:35]: [32mSuccessfully finished the upload to Google Play[0m
`
Run on a Jenkins machine using the command:
`fastlane supply --apk $apkPath --mapping $mappingPath --track beta --skip_upload_metadata --skip_upload_images --skip_upload_screenshots`

Don't hesitate if you need anything else!

Thank you in advance 😃 

Olivier

**Comment by nabhak25** [comment] 2018-02-22 05:44
@olivierg13 We use Gitlab for Continuous Integration. 
I have mentioned the path to mapping file just like the command you posted. The mapping file is not getting uploaded. Is there any alternatives through which I can upload mapping file using Fastfile or supply command? 

It would be helpful if you can demonstrate with a sample code snippet.

Thank you for your help!

**Comment by olivierg13** [comment] 2018-02-22 16:32
@nabhak25 If there are some alternatives, I'm not aware of them (except manual uploading).
If you reference it in the Fastfile, the result is probably going to be the same, at it looks like the argument is well received.

PS: I have the same problem too, my mapping file is not uploaded to PS.

**Comment by thauz** [comment] 2018-02-23 09:26
Same here. It seems to have stopped working at 19. Feb between 12:16 and 14:57 (CET) 😆

**Comment by dvdrlee** [comment] 2018-03-08 17:50
Similar to ☝️ our last successful upload of mapping.txt file was on 2/16 and the next one on 2/21 failed

**Comment by joshdholtz** [comment] 2018-03-09 14:31
@thauz @dvdrlee (and everyone else) Hmmm... I just successfully sent up a mapping.txt file 🤔 Which is totally not what I expected to happen and now I'm unsure of how to help 😱 

Am I doing something differently than what you are all doing?

## Worked for me? 😬 
![screen shot 2018-03-09 at 8 02 09 am](https://user-images.githubusercontent.com/401294/37211029-3f74d224-2370-11e8-9d81-6b2daabefd33.png)

### build.gradle
```
    buildTypes {
        release {
            debuggable false
            minifyEnabled true
            shrinkResources true
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
```

### Fastfile
```rb
lane :release do
  gradle(
    task: 'assemble',
    build_type: 'Release'
  )

  apk_path = Actions.lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
  mapping_path = File.absolute_path "../app/build/outputs/mapping/release/mapping.txt"

  supply(
    apk: apk_path,
    mapping: mapping_path,
    package_name: 'example.screengrab.fastlane.tools.fastlanescreengrabexample',
    track: 'alpha',
    skip_upload_metadata: true,
    skip_upload_images: true,
    skip_upload_screenshots: true,
    json_key: './fastlane/google_play2.json',

    validate_only: false
  )
end
```

**Comment by olivierg13** [comment] 2018-03-09 15:57
It worked for me again last night (><)
I think the mapping file upload is back, maybe a Google Api issue?

**Comment by joshdholtz** [comment] 2018-03-09 16:27
YES! Let's say that ^ Going to close this for now but feel free to comment/reopen if you see this happening some more 😊

**Comment by thauz** [comment] 2018-03-09 16:28
Works for me too :-)
The clue was to explicitly set the skip_upload_xyz to false (for my scenario). It obviously defaults to true and this apparently was no problem until 19.2. Google API seems to be more strict now.
So thanks @joshdholtz . You pushed me into the right direction 👍

**Closed by joshdholtz** 2018-03-09 16:27 UTC

**Comment by nabhak25** [comment] 2018-03-12 09:12
Works for me too! Thank you all for your help! 🥂
