### ISSUE TITLE
undefined method `map' for nil:NilClass

### ISSUE THREAD

**Issue by fsemkin** [fastlane/fastlane#12587] opened 2018-05-22 11:35 UTC
```
ERROR [2018-05-22 14:18:36.46]: Error finding relevant GitHub issues: undefined method `map' for nil:NilClass
Did you mean?  tap
/Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.96.0/spaceship/lib/spaceship/client.rb:478:in `send_shared_login_request': [!] The request could not be completed because: (Spaceship::Tunes::Error)
 	{"authType"=>"non-sa"}
 aa=A000E3CFA3F19BCDBE6E60DC198340C4; Domain=idmsa.apple.com; Path=/; Secure; HttpOnly, dslang=US-EN; Domain=apple.com; Path=/; Secure; HttpOnly, site=USA; Domain=apple.com; Path=/; Secure; HttpOnly, acn01=9YoHTH6q2o6VHfx8NmRlU34zWX8BTgx3wfNddAAQOtjXwkRv; Max-Age=31536000; Expires=Wed, 22-May-2019 11:18:35 GMT; Domain=apple.com; Path=/; Secure; HttpOnly
 	from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.96.0/spaceship/lib/spaceship/tunes/tunes_client.rb:123:in `send_login_request'
 	from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.96.0/spaceship/lib/spaceship/client.rb:662:in `do_login'
 	from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.96.0/spaceship/lib/spaceship/client.rb:363:in `login'
 	from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.96.0/spaceship/lib/spaceship/client.rb:71:in `login'
 	from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.96.0/spaceship/lib/spaceship/tunes/spaceship.rb:24:in `login'
 	from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.96.0/deliver/lib/deliver/runner.rb:31:in `login'
 	from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.96.0/deliver/lib/deliver/runner.rb:23:in `initialize'
 	from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.96.0/deliver/lib/deliver/commands_generator.rb:79:in `new'
 	from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.96.0/deliver/lib/deliver/commands_generator.rb:79:in `block (2 levels) in run'
 	from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
 	from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
 	from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
 	from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.96.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
 	from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
 	from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.96.0/deliver/lib/deliver/commands_generator.rb:182:in `run'
 	from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.96.0/deliver/lib/deliver/commands_generator.rb:17:in `start'
 	from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.96.0/fastlane/lib/fastlane/cli_tools_distributor.rb:100:in `take_off'
 	from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.96.0/bin/fastlane:20:in `<top (required)>'
 	from /Users/admin/.rbenv/versions/2.3.1/bin/fastlane:23:in `load'
 	from /Users/admin/.rbenv/versions/2.3.1/bin/fastlane:23:in `<main>'
```

**Comment by joshdholtz** [comment] 2018-05-22 12:19
This is a duplicate of https://github.com/fastlane/fastlane/issues/12577#issuecomment-390811299

**Closed by joshdholtz** 2018-05-22 12:19 UTC
