### ISSUE TITLE
Can't get release train info via spaceship

### ISSUE THREAD

**Issue by lbrownell-gpsw** [fastlane/fastlane#14889] opened 2019-06-12 14:33 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools) -- more specifically, the spaceship docs...over and over again.
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Originally reported in https://github.com/fastlane/fastlane/issues/14666, which looks remarkably similar, but was requested to create a new ticket:

Using fastlane 2.125.2, the three methods (I know of) to get to a build train or the builds within one are all failing. From the spaceship playground:
```
[4] pry(#<Spaceship::Playground>)> app = Spaceship::Tunes::Application.find("my.bundle.id")                                                                                              
=> <Spaceship::Tunes::Application 
	apple_id="xxxxx", 
	name="mycompany", 
	vendor_id="CGAPP-001", 
	bundle_id="my.bundle.id", 
	last_modified=1560273211000, 
	issues_count=0, 
	app_icon_preview_url="https://url-to-our-icon-image.png", 
	version_sets=[<Spaceship::Tunes::VersionSet 
		type="APP", 
		application=<Spaceship::Tunes::Application 
		#<Object ...>>, 
		platform="ios">]>

[5] pry(#<Spaceship::Playground>)> versions = app.all_build_train_numbers                                                                                                                   
NoMethodError: undefined method `[]' for #<Spaceship::ConnectAPI::Response:0x007fd86f49c768>
from /Users/lbrownell/.rvm/gems/ruby-2.3.3/gems/fastlane-2.125.2/spaceship/lib/spaceship/test_flight/build_trains.rb:24:in `block in all'

[6] pry(#<Spaceship::Playground>)> train = app.build_trains["6.0"]                                                                                                                          
NoMethodError: undefined method `[]' for #<Spaceship::ConnectAPI::Response:0x007fd81d3664b8>
from /Users/lbrownell/.rvm/gems/ruby-2.3.3/gems/fastlane-2.125.2/spaceship/lib/spaceship/test_flight/build_trains.rb:24:in `block in all'

[7] pry(#<Spaceship::Playground>)> app.all_processing_builds                                                                                                                                
NoMethodError: undefined method `[]' for #<Spaceship::ConnectAPI::Response:0x007fd878031760>
from /Users/lbrownell/.rvm/gems/ruby-2.3.3/gems/fastlane-2.125.2/spaceship/lib/spaceship/test_flight/build_trains.rb
```

##### Command executed

See above

##### Complete output when running fastlane, including the stack trace and command used

See above

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                           |
| --------------------------- | ----------------------------------------------- |
| OS                          | 10.14.5                                         |
| Ruby                        | 2.3.3                                           |
| Bundler?                    | false                                           |
| Git                         | git version 2.20.1 (Apple Git-117)              |
| Installation Source         | ~/.rvm/gems/ruby-2.3.3/bin/fastlane             |
| Host                        | Mac OS X 10.14.5 (18F203)                       |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.3/lib                    |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                     |
| Is contained                | false                                           |
| Is homebrew                 | false                                           |
| Is installed via Fabric.app | false                                           |
| Xcode Path                  | /Applications/Xcode10.2.app/Contents/Developer/ |
| Xcode Version               | 10.2                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.125.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                   | Version      |
| --------------------- | ------------ |
| did_you_mean          | 1.0.0        |
| executable-hooks      | 1.3.2        |
| bundler-unload        | 1.0.2        |
| rubygems-bundler      | 1.4.4        |
| bundler               | 2.0.1        |
| io-console            | 0.4.5        |
| slack-notifier        | 2.3.2        |
| atomos                | 0.1.3        |
| claide                | 1.0.2        |
| colored2              | 3.1.2        |
| nanaimo               | 0.2.6        |
| xcodeproj             | 1.9.0        |
| rouge                 | 2.0.7        |
| xcpretty              | 0.3.0        |
| terminal-notifier     | 2.0.0        |
| terminal-table        | 1.8.0        |
| addressable           | 2.5.2        |
| multipart-post        | 2.0.0        |
| word_wrap             | 1.0.0        |
| public_suffix         | 2.0.5        |
| tty-spinner           | 0.8.0        |
| babosa                | 1.0.2        |
| colored               | 1.2          |
| commander-fastlane    | 4.4.6        |
| http-cookie           | 1.0.3        |
| faraday-cookie_jar    | 0.0.6        |
| mini_magick           | 4.5.1        |
| multi_xml             | 0.6.0        |
| rubyzip               | 1.2.3        |
| security              | 0.1.3        |
| faraday_middleware    | 0.12.2       |
| naturally             | 2.2.0        |
| simctl                | 1.6.5        |
| jwt                   | 2.1.0        |
| uber                  | 0.1.0        |
| declarative-option    | 0.1.0        |
| representable         | 3.0.4        |
| signet                | 0.9.1        |
| httpclient            | 2.8.3        |
| google-api-client     | 0.23.7       |
| google-cloud-env      | 1.1.0        |
| google-cloud-core     | 1.3.0        |
| digest-crc            | 0.4.1        |
| google-cloud-storage  | 1.16.0       |
| emoji_regex           | 0.1.1        |
| tty-cursor            | 0.6.0        |
| tty-screen            | 0.6.5        |
| faraday               | 0.15.2       |
| json                  | 2.1.0        |
| highline              | 1.7.10       |
| excon                 | 0.62.0       |
| CFPropertyList        | 3.0.0        |
| plist                 | 3.4.0        |
| memoist               | 0.16.0       |
| googleauth            | 0.6.6        |
| unf                   | 0.1.4        |
| domain_name           | 0.5.20180417 |
| fastimage             | 2.1.3        |
| unicode-display_width | 1.4.0        |
| multi_json            | 1.13.1       |
| os                    | 1.0.0        |
| psych                 | 2.1.0        |
| retriable             | 3.1.2        |
| mime-types            | 3.2.2        |
| mime-types-data       | 3.2018.0812  |
| declarative           | 0.0.10       |
</details>
 </pre>
</details>

**Comment by janpio** [comment] 2019-06-12 14:55
Another report in the original issue of the 410 gone focused issue: https://github.com/fastlane/fastlane/issues/14666#issuecomment-498227886

**Comment by cooksimo** [comment] 2019-06-12 22:06
This is a duplicate of #14884

**Comment by lbrownell-gpsw** [comment] 2019-06-12 22:44
@cooksimo And so it is!  And your ticket was a duplicate of what I reported in https://github.com/fastlane/fastlane/issues/14666 before you posted your ticket.

@janpio I assume this would should be closed in favor of https://github.com/fastlane/fastlane/issues/14884, since there is action on it?

**Comment by janpio** [comment] 2019-06-13 08:56
Sounds reasonable @lbrownell-gpsw. I wasn't aware of that other issue as well, with the spaceship testflight changes stuff is a bit new and confusing for now.

Let's move over to #14884 then :)

**Closed by janpio** 2019-06-13 08:56 UTC
Labels: tool: spaceship
