### ISSUE TITLE
match development get 757: unexpected token at 'Bad Request' error

### ISSUE THREAD

**Issue by bobbeat** [fastlane/fastlane#5865] opened 2016-08-24 09:14 UTC
***:match ***$ match development

+-----------------------+-----------------------------------------+
|                     Summary for match 0.6.2                     |
+-----------------------+-----------------------------------------+
| git_url               | git@***:gzm/matchtest.git |
| type                  | development                             |
| git_branch            | master                                  |
| keychain_name         | login.keychain                          |
| readonly              | false                                   |
| verbose               | false                                   |
| force                 | false                                   |
| shallow_clone         | false                                   |
| force_for_new_devices | false                                   |
| skip_docs             | false                                   |
+-----------------------+-----------------------------------------+

[16:21:52]: Cloning remote git repo...
[16:21:53]: 🔓  Successfully decrypted certificates repo
[16:21:53]: To not be asked about this value, you can specify it using 'username'
Your Apple ID Username:***
[16:22:00]: Verifying that the certificate and profile are still valid on the Dev Portal...
Multiple teams found on the Developer Portal, please enter the number of the team you want to use: 
1) *** "*** Technology Co., Ltd" (In-House)
2) *** "*** Technology Co., Ltd." (Company/Organization)
2
[16:22:14]: To not be asked about this value, you can specify it using 'app_identifier'
The bundle identifier of your app: ***         
[16:22:25]: Couldn't find a valid code signing identity in the git repo for development... creating one for you now

+---------------+---------------------------------------------------+
|                      Summary for cert 1.4.1                       |
+---------------+---------------------------------------------------+
| development   | true                                              |
| force         | true                                              |
| username      | ***                              |
| keychain_path | /Users/***/Library/Keychains/login.keychain |
+---------------+---------------------------------------------------+

[16:22:25]: Starting login with user '***'
Multiple teams found on the Developer Portal, please enter the number of the team you want to use: 
1) *** "*** Technology Co., Ltd" (In-House)
2) *** "*** Technology Co., Ltd." (Company/Organization)
2
[16:22:32]: Successfully logged in
[16:22:35]: 🔒  Successfully encrypted certificates repo

Looking for related GitHub issues on fastlane/fastlane...

➡️  Still getting '757: unexpected token at "Bad Request"'
   https://github.com/fastlane/fastlane/issues/5827 [closed] 40 💬
   2 hours ago

➡️  "unexpected token at 'Bad Request'" from Spaceship when attempting to repair a provisioning profile
   https://github.com/fastlane/fastlane/issues/5813 [closed] 36 💬
   10 hours ago

➡️  Bad Request - portal_client.rb - associate_groups_with_app
   https://github.com/fastlane/fastlane/issues/2049 [closed] 1 💬
   a day ago

and 22 more at: https://github.com/fastlane/fastlane/search?q=757:%20unexpected%20token%20at%20'Bad%20Request'&type=Issues&utf8=✓
/Library/Ruby/Gems/2.0.0/gems/json-1.8.3/lib/json/common.rb:155:in `parse': [!] 757: unexpected token at 'Bad Request' (Faraday::ParsingError)
	from /Library/Ruby/Gems/2.0.0/gems/json-1.8.3/lib/json/common.rb:155:in `parse'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response/parse_json.rb:11:in `block in <class:ParseJson>'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:48:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:48:in `parse'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:39:in `process_response'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:32:in `block in call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.31.1/lib/spaceship/client.rb:410:in `block in send_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.31.1/lib/spaceship/client.rb:328:in `with_retry'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.31.1/lib/spaceship/client.rb:409:in `send_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.31.1/lib/spaceship/client.rb:385:in `request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.31.1/lib/spaceship/portal/portal_client.rb:284:in `create_certificate!'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.31.1/lib/spaceship/portal/certificate.rb:298:in `create!'
	from /Library/Ruby/Gems/2.0.0/gems/cert-1.4.1/lib/cert/runner.rb:137:in `create_certificate'
	from /Library/Ruby/Gems/2.0.0/gems/cert-1.4.1/lib/cert/runner.rb:37:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/cert-1.4.1/lib/cert/runner.rb:6:in `launch'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.6.2/lib/match/generator.rb:19:in `generate_certificate'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.6.2/lib/match/runner.rb:49:in `certificate'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.6.2/lib/match/runner.rb:17:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.6.2/lib/match/commands_generator.rb:55:in `block (3 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.50.2/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.6.2/lib/match/commands_generator.rb:121:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.6.2/lib/match/commands_generator.rb:12:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.6.2/bin/match:6:in `<top (required)>'
	from /usr/local/bin/match:23:in `load'
	from /usr/local/bin/match:23:in `<main>'

### Configuration Files

Matchfile:
git_url "git@techgit.***.com:gzm/matchtest.git"

type "development" # The default type, can be: appstore, adhoc or development

app_identifier "com.***.***" 
username "ios_server@***.com" # Your Apple Developer Portal username

### Environment

fastlane version (run `fastlane -v`):
fastlane 1.101.0
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
no
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
no

**Comment by bobbeat** [comment] 2016-08-24 09:50
anyone knows the problem?give me a favor.   Ths!

**Comment by uny** [comment] 2016-08-24 09:53
Same issue.
https://github.com/fastlane/fastlane/issues/5827, https://github.com/fastlane/fastlane/issues/5813 and https://github.com/fastlane/fastlane/issues/2049 does not solve my problem.

**Comment by medslt** [comment] 2016-08-24 13:29
Same problem here when I run Pem module (https://github.com/fastlane/fastlane/tree/master/pem)

**Comment by asfalcone** [comment] 2016-08-24 15:00
Duplicate of #5827

**Comment by TKBurner** [comment] 2016-08-24 15:06
@medslt @bobbeat Thanks for reporting this. Closing as duplicate. Please follow over there. Thanks!

**Closed by TKBurner** 2016-08-24 15:06 UTC
Labels: spaceship
