### ISSUE TITLE
increment_build_number precondition check issue

### ISSUE THREAD

**Issue by tfonfara** [fastlane/fastlane#14357] opened 2019-03-07 09:58 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
[`increment_build_number`](https://docs.fastlane.tools/actions/increment_build_number/#increment_build_number) can be called with and without `build_number` parameter. In [increment_build_number.rb:33](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/increment_build_number.rb#L33) there's a check if Apple Generic Versioning is enabled, but this is only relevant if no build number is provided, as only in this case Apple Generic Versioning is being used. If `agvtool` is executed with a build number as parameter this number is just being using and inserted in the plist files. So the expectation should be that line 33 is only executed if no build number is provided, otherwise the tool will not work properly.
Workaround for that issue is to set `CURRENT_PROJECT_VERSION` to 1 (or any other number).

##### Command executed
`increment_build_number(
     build_number: "75"
)`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>There does not seem to be a CURRENT_PROJECT_VERSION key set for this project.  Add this key to your target's expert build settings.
Apple Generic Versioning is not enabled in this project.
Before being able to increment and read the version number from your Xcode project, you first need to setup your project properly. Please follow the guide at https://developer.apple.com/library/content/qa/qa1827/_index.html</pre>
</details>

### Environment

<details>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.3                                     |
| Ruby                        | 2.6.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.17.2 (Apple Git-113)          |
| Installation Source         | ~/.rbenv/versions/2.6.1/bin/fastlane        |
| Host                        | Mac OS X 10.14.3 (18D109)                   |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.1/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2q  20 Nov 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | de_DE.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.117.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.6.0        |
| bundler                   | 1.17.3       |
| faraday_middleware        | 0.13.1       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
</details>

*generated on:* **2019-03-07**
</details>

**Comment by mollyIV** [comment] 2019-03-07 22:51
👋 @tfonfara Thanks for opening an issue! 

`increcrement_build_number` action uses `agvtool` under the hood. According to [the documentation](https://developer.apple.com/library/archive/qa/qa1827/_index.html) you should enable `agvtool` in your project first in order to use it.

You got an error because it looks like you **didn't enable** `avgtool` in your project (even though you set a build number `increment_build_number(build_number: "75")`). I played with `agvtool` a bit. 

* when I had `avgtool` **disabled** in my Xcode project
<img width="816" alt="screenshot 2019-03-07 at 23 44 41" src="https://user-images.githubusercontent.com/10795657/53994597-0ab0b080-4133-11e9-895f-ced6b0aee94f.png">

![image](https://user-images.githubusercontent.com/10795657/53994625-1ac89000-4133-11e9-8f10-a8e701654b82.png)

![image](https://user-images.githubusercontent.com/10795657/53994662-2f0c8d00-4133-11e9-8f2e-0d42b6fae63c.png)

* when I had `avgtool` **enabled** in my Xcode project

![image](https://user-images.githubusercontent.com/10795657/53994704-477ca780-4133-11e9-81b9-5073249db34e.png)

![image](https://user-images.githubusercontent.com/10795657/53994717-4ea3b580-4133-11e9-93d6-f4cb907ebc69.png)

**Conclusion**

Please note that the last thing we do in `increment_build_number` action is:
https://github.com/fastlane/fastlane/blob/2987340ff764142aa343c0eafda977384c5f8d2d/fastlane/lib/fastlane/actions/increment_build_number.rb#L49-L52

so we use `agvtool` again ☝️ 

Considering all above I'd say the current behaviour of the action is **correct** (even though you can successfully execute `agvtool new-version -all 21` with `agvtool` option disabled). 

WDYT? 🤔

**Comment by tfonfara** [comment] 2019-03-15 22:39
@mollyIV got your point, but isn't the idea of injecting a build number from external to not use Apple Generic Versioning? My use case for example is to get the build number from a CI tool, so I don't need to save it in the project settings at all. Also where you use `agvtool` in the end wouldn't be necessary as you already got the result (`build_number`) as parameter, so no need to read it from the project settings.
Or would you say to use `agvtool` as I do is let's say undocumented behaviour that shouldn't be used? 🤔

**Comment by mollyIV** [comment] 2019-03-16 07:48
Hmm, I see 🤔Thanks @tfonfara for providing more context 🙇  

I think the problem is that the documentation is not very clear. I'd vote for adding the support for providing `build_number` even though `agvtool` option is disabled 👍 

I am going to create pull request 👍

**Comment by tfonfara** [comment] 2019-03-16 09:37
@mollyIV cool, thank you 🙏🎉😁

**Comment by mollyIV** [comment] 2019-03-16 17:43
@tfonfara here we go: https://github.com/fastlane/fastlane/pull/14409 🎁

**Comment by tfonfara** [comment] 2019-03-17 11:13
👏😊

**Comment by tfonfara** [comment] 2019-04-16 21:56
@mollyIV do you have any estimation when this gets merged? 😊

**Comment by mollyIV** [comment] 2019-04-17 04:45
👋@tfonfara I believe it's gonna be merged pretty soon 🤞😊

**Closed** 2019-04-25 14:43 UTC
Labels: complexity: you can do this, tool: action, type: bug
