### ISSUE TITLE
"Invalid screen size" error for iPad due to invalid screen size in device_types.rb

### ISSUE THREAD

**Issue by michaellenaghan** [fastlane/fastlane#18243] opened 2021-02-19 17:21 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Framed iPad 10.2 inch screenshots are 1620 x 2160 because of [this](https://github.com/fastlane/fastlane/blob/557ae2fff6925c5ac9d8f05d7070c5b7a46a119e/frameit/lib/frameit/device_types.rb#L127) line in `device_types.rb`. But according to [this](https://help.apple.com/app-store-connect/#/devd274dd925) page Apple expects 1668 x 2224. The discrepancy is causing the screenshot upload to fail.

(Fastlane's error message says: `Invalid screen size (Actual size is 1620x2160...)`.)

##### Command executed

The error is created by `frameit` and detected by `upload_to_app_store`.

##### Complete output when running fastlane, including the stack trace and command used

<details>
<pre>
...
[19:52:13]: --- Step: upload_to_app_store ---
[19:52:13]: ---------------------------------
[19:52:13]: Successfully loaded '/Users/.../fastlane/Deliverfile' 📄

+-----------------------------+--------------------------------------+
|           Detected Values from './fastlane/Deliverfile'            |
+-----------------------------+--------------------------------------+
...
+-----------------------------+--------------------------------------+

[19:52:13]: Login to App Store Connect (...)
[19:52:14]: Login successful

+--------------------------------------+--------------------------------------+
|                           deliver 2.174.0 Summary                           |
+--------------------------------------+--------------------------------------+
| app_version                          | ...                               |
| skip_screenshots                     | false                                |
| screenshots_path                     | ./fastlane/screenshots               |
| metadata_path                        | ./fastlane/metadata                  |
| username                             | ...                  |
| app_identifier                       | ...   |
| platform                             | ios                                  |
| edit_live                            | false                                |
| use_live_version                     | false                                |
| skip_binary_upload                   | true                                 |
| skip_metadata                        | true                                 |
| skip_app_version_update              | false                                |
| force                                | false                                |
| overwrite_screenshots                | true                                 |
| submit_for_review                    | false                                |
| reject_if_possible                   | false                                |
| phased_release                       | false                                |
| reset_ratings                        | false                                |
| app_rating_config_path               | ./fastlane/metadata/app_rating_conf  |
|                                      | ig.json                              |
| submission_information.add_id_info_  | false                                |
| serves_ads                           |                                      |
| submission_information.add_id_info_  | false                                |
| uses_idfa                            |                                      |
| submission_information.content_righ  | false                                |
| ts_contains_third_party_content      |                                      |
| submission_information.export_compl  | false                                |
| iance_uses_encryption                |                                      |
| team_id                              | ...                               |
| dev_portal_team_id                   | ...                           |
| run_precheck_before_submit           | true                                 |
| precheck_default_rule_level          | error                                |
| copyright                            | ...                   |
| name.default                         | ...                       |
| ignore_language_directory_validatio  | false                                |
| n                                    |                                      |
| precheck_include_in_app_purchases    | true                                 |
+--------------------------------------+--------------------------------------+
...
[19:52:19]: 🚫 Invalid screenshots were detected! Here are the reasons:
[19:52:19]: 🚫 Error: ./fastlane/screenshots/en-US/iPad (8th generation)-1-Overview_framed.png - Invalid screen size (Actual size is 1620x2160. See the specifications to fix https://help.apple.com/app-store-connect/#/devd274dd925)
[19:52:19]: 🚫 Error: ./fastlane/screenshots/en-US/iPad (8th generation)-2-Ready_framed.png - Invalid screen size (Actual size is 1620x2160. See the specifications to fix https://help.apple.com/app-store-connect/#/devd274dd925)
...
</pre>
</details>

### Environment

<details>
<summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.2.1                                                         |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.30.0                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 11.2.1 (20D74)                                           |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.4                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_CA.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
...
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
...
```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.174.0 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.3.0        |
| bundler                       | 1.17.2       |
| etc                           | 1.0.1        |
| forwardable                   | 1.2.0        |
| rake                          | 13.0.3       |
| CFPropertyList                | 3.0.3        |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| artifactory                   | 3.0.15       |
| atomos                        | 0.1.3        |
| aws-eventstream               | 1.1.0        |
| aws-partitions                | 1.427.0      |
| aws-sigv4                     | 1.2.2        |
| jmespath                      | 1.4.0        |
| aws-sdk-core                  | 3.112.0      |
| aws-sdk-kms                   | 1.42.0       |
| aws-sdk-s3                    | 1.88.1       |
| babosa                        | 1.0.4        |
| claide                        | 1.0.3        |
| colored                       | 1.2          |
| colored2                      | 3.1.2        |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| declarative                   | 0.0.20       |
| declarative-option            | 0.1.0        |
| digest-crc                    | 0.6.3        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| dotenv                        | 2.7.6        |
| emoji_regex                   | 3.2.1        |
| excon                         | 0.79.0       |
| faraday-net_http              | 1.0.1        |
| multipart-post                | 2.0.0        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.3.0        |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.2        |
| gh_inspector                  | 1.1.3        |
| jwt                           | 2.2.2        |
| memoist                       | 0.16.2       |
| multi_json                    | 1.15.0       |
| os                            | 1.1.1        |
| signet                        | 0.14.1       |
| googleauth                    | 0.15.1       |
| httpclient                    | 2.8.3        |
| mini_mime                     | 1.0.2        |
| uber                          | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.2        |
| google-api-client             | 0.38.0       |
| rexml                         | 3.2.4        |
| webrick                       | 1.7.0        |
| google-apis-core              | 0.2.1        |
| google-apis-iamcredentials_v1 | 0.1.0        |
| google-apis-storage_v1        | 0.2.0        |
| google-cloud-env              | 1.4.0        |
| google-cloud-errors           | 1.0.1        |
| google-cloud-core             | 1.5.0        |
| google-cloud-storage          | 1.30.0       |
| json                          | 2.5.1        |
| mini_magick                   | 4.11.0       |
| plist                         | 3.6.0        |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| naturally                     | 2.2.1        |
| simctl                        | 1.6.8        |
| slack-notifier                | 2.3.2        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| word_wrap                     | 1.0.0        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| xcpretty-travis-formatter     | 1.0.1        |
</details>

*generated on:* **2021-02-19**
</details>

**Comment by max-ott** [comment] 2021-02-24 11:40
Duplicate of #18244 18244

**Comment by michaellenaghan** [comment] 2021-02-24 11:54
Not a duplicate. This is a different error for a different device -- and, most importantly, with a different cause.

**Comment by michaellenaghan** [comment] 2021-02-24 20:05
The dimensions listed in `device_types.rb` are correct; Apple's specifications show different (but larger) dimensions, which is something they apparently sometimes do. Still, something is failing somewhere. I'll poke around a bit more.

**Comment by michaellenaghan** [comment] 2021-02-24 23:33
The iPad Air (4th generation), a new 11 inch iPad, also produces an error, in `frameit`:

```
[17:42:08]: Unsupported screen size [1640, 2360] for path './en-US/iPad Air (4th generation)-1-Overview.png'
```

Looks like different new devices have different problems in different places. In the case of the 4th generation Air the problem is a missing row in `device_types.rb`. In the case of the iPhone 12 Pro the problem is missing rows in `app_screenshot.rb`. I haven't pinpointed the problem with the 8th generation iPad yet. It currently produces 1620x2160 screenshots. Apple says it expects 1668x2224 for 10.5 inch iPads. Maybe it's possible to pad screenshots when they're framed? Maybe Apple's specifications are wrong (or misleading)?

Not sure it's worth opening this can of worms.

**Comment by thomasdelgado** [comment] 2021-04-06 00:47
Hello! I think I'm having a similar problem. Mine is with iPad Pro (12.9-inch)(4th generation). 

I've noticed that `frameit` changes the screenshot resolution from a valid `2732x2048` to an invalid `2048x2048`.

![Screen Shot 2021-04-05 at 21 46 44](https://user-images.githubusercontent.com/3489795/113643321-6b837d80-9658-11eb-8885-132c625faf84.png)

![Screen Shot 2021-04-05 at 21 46 57](https://user-images.githubusercontent.com/3489795/113643333-73432200-9658-11eb-9347-711dfa307a40.png)

**Comment by michaellenaghan** [comment] 2021-04-06 01:05
I'm not sure how it would end up square...? Take a look at #18394 which ends with this conclusion: `frameit` seems to require a background and either a title or a keyword to produce "expected" results.

**Comment by thomasdelgado** [comment] 2021-04-06 14:47
Hey @michaellenaghan, thanks for replying! 

Yeah, I wondered why that would happen as well. Actually I did take a look in that issue but couldn't find any conclusion. 

I'm using the most `framefile.json` possible, with a background and title (not keyword though). This "square effect" is not happening in the iPad 9.7"

**Comment by michaellenaghan** [comment] 2021-04-06 16:10
OK.

I'm no expert in this, just another user who ran into problems, but here's my suggestion: use the 3rd generation instead of the 4th. That's what I do. There are a few places (for example, [here](https://github.com/fastlane/fastlane/blob/e601edcb933aa066b36beb60547f3519a6053e0d/frameit/frames_generator/Rakefile#L71) and [here](https://github.com/fastlane/fastlane/blob/c2295ea00d03bfe159984e79e731af24a3f748c7/deliver/spec/app_screenshot_spec.rb#L32)) where the 4th generation gets special-cased; maybe those special cases are now failing? (Having said that, personally I've never seen `frameit` generate square images. If you have the same problem with the 3rd generation we'll have to look elsewhere for the cause.)

**Comment by thomasdelgado** [comment] 2021-04-06 18:09
Thank you for taking your time to help me even though you're not an expert. I really appreciate! 

Yes, since I didn't want to wait, I was looking for a workaround but want to let you guys know that I was having a similar problem. 

So, trying 3rd and 2nd generation things get a little bit worse... It doesn't apply the frame. 
I'm getting the following errors. 
```Tried looking for offset information for 'portrait', Apple iPad Pro in ```
``` Could not find offset_information for './screenshots/pt-BR/iPad Pro (12.9-inch) (2nd generation)```

I've noticed that those frames are not listed here: https://github.com/fastlane/frameit-frames/tree/gh-pages/latest, only the 4th generation. 
If you look in the commit history, there was a hot fix about that, but it seems it was removed in the most recent commits. 

So it looks that we can't generate any `frameit` screenshot for the iPad 12.9 family at the moment 😐

**Comment by thomasdelgado** [comment] 2021-04-06 18:11
Oh, forgot to mention: 

I've download those frames manually and added to my local latest folder, but it seems that it needs more than that to work.

**Comment by michaellenaghan** [comment] 2021-04-06 18:49
Yes, there's a JSON file (`~/.fastlane/frameit/latest/offsets.json`) that has info `frameit` needs. I think the correct way to get the latest frames is to use:

    bundle exec fastlane frameit download_frames

**Comment by thomasdelgado** [comment] 2021-04-06 19:40
The offset advice did the trick to solve the second problem!  I had to put back the 2nd and 3rd offsets in the `offsets.json` and it was able to add those frames. 

However, the initial problem about square frames happen as well with those iPads. 

about uploading the latest_frames, my advice is to not run right now since there is not data about those iPads in the last commit. 

Thank you for your insights!

**Closed** 2021-07-07 17:33 UTC
Labels: status: waiting-for-reply
