### ISSUE TITLE
Rsync failure prevents ipa from being built

### ISSUE THREAD

**Issue by ScottRobbins** [fastlane/fastlane#5019] opened 2016-06-06 19:50 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Most of the time when I run `gym` (and xcodebuild for that matter manually) at the step of exporting the archive to an `ipa` file fails with Rsync issues. It will complete correctly about 20% of the time, however.

##### Complete output when running fastlane, including the stack trace and command used
Command: `gym`

Output ending:
```
[15:42:47]: ▸ Archive Succeeded
[15:42:47]: $ /usr/bin/xcrun /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/gym-1.6.3/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/jm/kyw35ndn6xz_qbwxg7d8nqzc0000gp/T/gym_config20160606-21485-18eqyg6.plist' -archivePath '/Users/dashboard/Library/Developer/Xcode/Archives/2016-06-06/NameOfApp 2016-06-06 15.40.34.xcarchive' -exportPath '/var/folders/jm/kyw35ndn6xz_qbwxg7d8nqzc0000gp/T/gym_output20160606-21485-zej28q' 

* keychain 2.8.2 ~ http://www.funtoo.org
* Inheriting ssh-agent (forwarded)

+ xcodebuild -exportArchive -exportOptionsPlist /var/folders/jm/kyw35ndn6xz_qbwxg7d8nqzc0000gp/T/gym_config20160606-21485-18eqyg6.plist -archivePath '/Users/dashboard/Library/Developer/Xcode/Archives/2016-06-06/NameOfApp 2016-06-06 15.40.34.xcarchive' -exportPath /var/folders/jm/kyw35ndn6xz_qbwxg7d8nqzc0000gp/T/gym_output20160606-21485-zej28q
2016-06-06 15:42:48.402 xcodebuild[24936:2251905] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/jm/kyw35ndn6xz_qbwxg7d8nqzc0000gp/T/NameOfApp_2016-06-06_15-42-48.402.xcdistributionlogs'.
2016-06-06 15:42:48.425 xcodebuild[24936:2251905] [MT] DeveloperPortal: Using pre-existing current store at URL (file:///Users/dashboard/Library/Developer/Xcode/DeveloperPortal%207.3.1.db).
2016-06-06 15:42:50.015 xcodebuild[24936:2251905] [MT] IDEDistribution: Step failed: <IDEDistributionPackagingStep: 0x7fcf0d380b70>: Error Domain=IDEFoundationErrorDomain Code=1 "Rsync failed" UserInfo={NSLocalizedDescription=Rsync failed}
error: exportArchive: Rsync failed

Error Domain=IDEFoundationErrorDomain Code=1 "Rsync failed" UserInfo={NSLocalizedDescription=Rsync failed}

** EXPORT FAILED **
[15:42:50]: Exit status: 70

[!] Error packaging up the application
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

I have a `Gymfile` that looks like
```
scheme "NameOfScheme"
output_directory "./artifacts"
output_name "OutputName"
```

### Environment

gym version `1.6.3`

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

rbenv

**Comment by vpolouchkine** [comment] 2016-06-09 21:52
Can you try using the `use_legacy_build_api` option?

**Comment by KrauseFx** [comment] 2016-06-10 00:02
Duplicate of https://github.com/fastlane/fastlane/issues/4150#issuecomment-224983058

**Closed by KrauseFx** 2016-06-10 00:02 UTC
Labels: gym
