### ISSUE TITLE
Make sure you've used Screengrab.screenshot() in your tests and that your expected tests are being run.

### ISSUE THREAD

**Issue by rahul19393** [fastlane/fastlane#10800] opened 2017-11-04 12:33 UTC
Make sure you've used Screengrab.screenshot() in your tests and that your expected tests are being run.

fastlane env
[18:02:34]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[18:02:36]: Generating fastlane environment output, this might take a few seconds...
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.2                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.5 (Apple Git-94)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.2/lib            |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0                                         |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby

# Customise this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.62.1"

default_platform :android

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assembleRelease")
    supply
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

lane :playstorelive do
  gradle(
    task: 'assemble',
    build_type: 'Release'
  )
  supply # Uploads the APK built in the gradle step above
end
lane :playstore do
  gradle(
    task: 'assemble',
    build_type: 'Release'
  )
end
lane :screenshots do
  screengrab
  supply
end
lane :sreengrb do
screengrab(
app_package_name: 'com.mute.app',
  locales: ["en-US", "fr-FR", "ja-JP"],
  clear_previous_screenshots: true,
tests_apk_path: "/Users/acumeettechnologies/AndroidStudioProjects/MyApplication2/app/build/outputs/apk/app-debug.apk"
)
end
error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file "/Users/acumeettechnologies/Desktop/certificate/secret.json" # Path to the json secret file - Follow https://github.com/fastlane/supply#setup to get one
package_name "com.mute.app" # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.63.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 2.0.4        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.4       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| io-console                | 0.4.6        |
| openssl                   | 2.0.5        |
</details>

![screen shot 2017-11-04 at 6 07 22 pm](https://user-images.githubusercontent.com/28038072/32405443-1d0e2402-c18b-11e7-9705-e1bfe7dd787c.png)

**Comment by joshdholtz** [comment] 2017-11-08 00:04
Duplicate of #10817

**Closed by joshdholtz** 2017-11-08 00:04 UTC

**Comment by rahul19393** [comment] 2017-11-08 04:46
hi,

Thanks for your reply, i want to ask that can i take screenshots without
launch app in android by using screengrab?


*Thanks & Regards,*
*Rahul pal*
Android Developer | Acumeet Technologies Pvt. Ltd
*Mobile:* (+91) 9650878516
*Mail:* rahul.pal@acumeet.com <soumitra.mishra@acumeet.com>
*Web: *www.acumeet.com

**Comment by joshdholtz** [comment] 2017-11-08 13:07
@rahul19393 You have to launch the app (via tests) to take screenshots 🙃 All information/instructions can be found here - https://docs.fastlane.tools/actions/screengrab/#screengrab

**Comment by rahul19393** [comment] 2017-11-09 04:59
Ok Thanks,

If i don't want to launch app then there is no option to take screenshot.Is
it right?



*Thanks & Regards,*
*Rahul pal*
Android Developer | Acumeet Technologies Pvt. Ltd
*Mobile:* (+91) 9650878516
*Mail:* rahul.pal@acumeet.com <soumitra.mishra@acumeet.com>
*Web: *www.acumeet.com

**Comment by joshdholtz** [comment] 2017-11-09 15:23
@rahul19393 That is correct 👌 The app needs to run the build the views and run the logic so it can configure the screenshots properly for you. There is no way to do that without running the app.
