### ISSUE TITLE
[frameit] Title has very small font and aligned to right

### ISSUE THREAD

**Issue by jkleroy** [fastlane/fastlane#11464] opened 2018-01-07 23:06 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I recently updated fastlane on my mac and ever since frameit has issues.
I am trying to update screenshots for the App Store but the title now appears tiny and aligned to right.
I attached two screenshots, one produced a few months ago, another with the latest version of fastlane.

Current output: 
![1_packing_framed](https://user-images.githubusercontent.com/7473932/34655306-9ad6e94c-f407-11e7-81c1-a7029fc6396a.png)

Output a few months ago: 
![1_packing_framed](https://user-images.githubusercontent.com/7473932/34655315-b5ee289e-f407-11e7-8009-d72b45a65f5c.png)

##### Complete output when running fastlane, including the stack trace and command used

```
frameit silver
[✔] 🚀 
[00:02:00]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[00:02:00]: Using device frames version 'latest'
[00:02:00]: Framing screenshot './no/1_Packing.png'
Forced orientation: 
Forced orientation: 
identify: geometry does not contain image `/var/folders/_c/_4wt3z4d0wndqw9kc6yxk1kr0000gn/T/mini_magick20180108-28651-16ehgel.png' @ warning/attribute.c/GetImageBoundingBox/240.
mogrify: geometry does not contain image `/var/folders/_c/_4wt3z4d0wndqw9kc6yxk1kr0000gn/T/mini_magick20180108-28651-16ehgel.png' @ warning/transform.c/CropImage/640.
composite: invalid profile length `/var/folders/_c/_4wt3z4d0wndqw9kc6yxk1kr0000gn/T/mini_magick20180108-28651-lk83s.png' @ warning/png.c/MagickPNGWarningHandler/1705.
Forced orientation: 
Forced orientation: 
Forced orientation: 
composite: invalid profile length `/var/folders/_c/_4wt3z4d0wndqw9kc6yxk1kr0000gn/T/mini_magick20180108-28651-rn8frm.png' @ warning/png.c/MagickPNGWarningHandler/1705.
convert: invalid profile length `/var/folders/_c/_4wt3z4d0wndqw9kc6yxk1kr0000gn/T/mini_magick20180108-28651-1hxrit7.png' @ warning/png.c/MagickPNGWarningHandler/1705.
[00:02:21]: Added frame: '/Users/jleroy/Desktop/TEMP/test/no/1_Packing_framed.png'
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.73.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.7.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| libxml-ruby               | 3.0.0        |
</details>

*generated on:* **2018-01-08**
</details>

**Comment by janpio** [comment] 2018-01-07 23:40
@milch is it normal that it has empty output for "Force orientation"?

@jkleroy 
What is your configuration for `frameit`?
Does this also happen if you only try to frame 1 screenshot? Can you upload it so we can reproduce?
Are the error messages in the output new or did you get them before as well?

**Comment by jkleroy** [comment] 2018-01-07 23:50
I remember seeing some errors when I was framing screenshots a few months ago but not the "Force orientation" message.

Here is the frameit configuration folder.
@janpio Please let me know if you reproduce.

[frameit_folder_jkleroy.zip](https://github.com/fastlane/fastlane/files/1610332/frameit_folder_jkleroy.zip)

**Comment by janpio** [comment] 2018-01-08 14:39
I can reproduce the problem, although only with `fastlane frameit` as I have a plain gem installation of fastlane I just created:

```
MacBook-Pro:Downloads sujan$ cd frameit_folder_jkleroy
MacBook-Pro:frameit_folder_jkleroy sujan$ ls
Framefile.json		background_grey.jpg	title.strings
Raleway-SemiBold.ttf	keyword.strings
background.jpg		no
MacBook-Pro:frameit_folder_jkleroy sujan$ frameit silver
-bash: frameit: command not found
MacBook-Pro:frameit_folder_jkleroy sujan$ fastlane frameit silver
[✔] 🚀 
[15:19:44]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[15:19:45]: Using device frames version 'latest'
[15:19:45]: Framing screenshot './no/1_Packing.png'
Forced orientation: 
Forced orientation: 
identify: geometry does not contain image `/var/folders/fc/b8w3s81974l3zhjsfb0krl_w0000gn/T/mini_magick20180108-1302-8pfgan.png' @ warning/attribute.c/GetImageBoundingBox/240.
mogrify: geometry does not contain image `/var/folders/fc/b8w3s81974l3zhjsfb0krl_w0000gn/T/mini_magick20180108-1302-8pfgan.png' @ warning/transform.c/CropImage/641.
composite: invalid profile length `/var/folders/fc/b8w3s81974l3zhjsfb0krl_w0000gn/T/mini_magick20180108-1302-8dpmby.png' @ warning/png.c/MagickPNGWarningHandler/1744.
Forced orientation: 
Forced orientation: 
Forced orientation: 
composite: invalid profile length `/var/folders/fc/b8w3s81974l3zhjsfb0krl_w0000gn/T/mini_magick20180108-1302-qdohym.png' @ warning/png.c/MagickPNGWarningHandler/1744.
convert: invalid profile length `/var/folders/fc/b8w3s81974l3zhjsfb0krl_w0000gn/T/mini_magick20180108-1302-a9hifd.png' @ warning/png.c/MagickPNGWarningHandler/1744.
[15:20:17]: Added frame: '/Users/sujan/Downloads/frameit_folder_jkleroy/no/1_Packing_framed.png'
MacBook-Pro:frameit_folder_jkleroy sujan$ 
```

I looked into frameit's code a tiny bit, I think the `Force orientation: ` has nothing to do with it but should probably be fixed in a new PR as this output looks quite a bit odd.

The real problem seems to occur when `.identify` is called on the image, here: https://github.com/fastlane/fastlane/blob/8e8292f5aea86d4ac8be1f105a6b4c36e2643855/frameit/lib/frameit/editor.rb#L372

I then played with your data a bit, seems that as soon as I add a `keyword` it works again.

My guess: This is a regression of #11124. Can you maybe look into this @funnel20? First step would be to confirm it with an unrelated screenshot and new frameit setup instead of reusing the one @jkleroy provided.

**Comment by janpio** [comment] 2018-01-08 14:54
@jkleroy If you are in a hurry, try to install fastlane 2.68.0 and see if it works there. This would also help us pinpoint the problem, #11124 was released in 2.69.0.

**Comment by jkleroy** [comment] 2018-01-08 14:57
I am in a hurry, I was just about to ask you which version to install 👍 
Sorry for my ignorance, how do I revert back to an older version of fastlane?

**Comment by janpio** [comment] 2018-01-08 14:57
No idea myself, but StackOverflow says: https://stackoverflow.com/questions/17026441/how-to-install-a-specific-version-of-a-ruby-gem

**Comment by funnel20** [comment] 2018-01-08 15:39
My https://github.com/fastlane/fastlane/issues/10440#issuecomment-348762239 shows that I have verified it with:

> Only used the mandatory title.string, no keywords

This was before the final implementation with the new Trimbox class, so I should double-check.

**Comment by funnel20** [comment] 2018-01-08 16:32
I have done several tests with version 2.68.0 (without my fix for #10440) and 2.72.0 (with fix).

In both cases when using NO _keywords.strings_ file, it works as expected; only the title is horizontally centred.
However, when using a _keywords.strings_ file with an empty string (e.g. `"01" = "";`), the issue occurs due to my fix.
When running it with 2.68.0 a warning from MiniMagick is shown (but still the proper screenshot is created):

> [17:21:39]: Framing screenshot './en-US/iPhone SE-01_RemoteTab.png'
> mogrify: geometry does not contain image `/var/folders/7g/n55n1s5x3z931vflyvwp_7280000gn/T/mini_magick20180108-31078-1x74tx8.png' @ warning/attribute.c/GetImageBoundingBox/240.

I will try to fix this the next few days.

**Short-term work-around**
@jkleroy If you do not use keywords, instead of using empty strings in your _keywords.strings_ file remove the _keywords.strings_ file. 
Or use Fastlane 2.68.2 (latest release before this issue is introduced in 2.69.0).

**Comment by janpio** [comment] 2018-01-08 16:37
Awesome, thanks for taking a look @funnel20!

**Comment by jkleroy** [comment] 2018-01-08 16:49
@funnel20 thank you very much. 👍 
I just noticed this issue with another project that didn't have any keyword.strings file.
But the Framefile.json was full of empty keyword references. Removing these references also corrected the issue.

**Comment by funnel20** [comment] 2018-01-09 10:22
@jkleroy I'm glad you have a temporary work-around. 
Of course my intention is to find a proper solution to handle empty keyword strings (either in _Framefile.json_ or _keywords.strings_).

**Comment by funnel20** [comment] 2018-01-09 14:07
The most elegant solution that I can think of is to ignore empty strings in either _Framefile.json_ or _keywords.strings_. Than my existing code will just ran fine, similar to when no _keywords.strings_ exists.

The location I want to do this is in `def fetch_text(type)` which returns the configuration text from: 

**_keywords.strings_**
This is the line where it returns the string from _keywords.strings_:
https://github.com/fastlane/fastlane/blob/a8ff50981d5f9162ca8971d6b9cf242a90063191/frameit/lib/frameit/editor.rb#L445

When I add a condition that the string should not be empty it works as expected:
```Ruby
return result.last if result && result.last.length > 0  # Ignore empty string
```

**_Framefile.json_**
A few lines below, the fallback code to retrieve the text from the _Framefile.json_ is:
https://github.com/fastlane/fastlane/blob/a8ff50981d5f9162ca8971d6b9cf242a90063191/frameit/lib/frameit/editor.rb#L449

In order to modify and verify this, I need to add a keyword to my _Framefile.json_.
But I have no clue what the syntax is, as I can't find it in the Frameit docu.

@jkleroy You mentioned you had keywords defined in your Framefile. Can you post it here please?

**Comment by janpio** [comment] 2018-01-09 16:00
Your length check is working, the problem is that before `result` was already filled with that array/hash/map (whatever it is called in ruby):
https://github.com/fastlane/fastlane/blob/a8ff50981d5f9162ca8971d6b9cf242a90063191/frameit/lib/frameit/editor.rb#L444-L445
Maybe use another variable name in 444+445? That is not the result anyway, but an array that includes the result...

**Comment by funnel20** [comment] 2018-01-10 10:39
@janpio Excellent observation, thanks.

I have refactored that particular `result` to `text_array`. And the other `result` (that is used in the return) to `text`, as the name of the function is `fetch_text()`.
Now I can nest the criteria for a non-empty string inline.

Besides from this particular issue, I enhanced the UI logs:

1. Moved this above the line that actually performs it and added the name of the *.strings file:
`UI.verbose("Falling back to text in Framefile.json as there was nothing specified in the #{type}.strings file")`
2. Added the _title.strings_ file:
`UI.user_error!("Could not get title for screenshot #{screenshot.path}. Please provide one in your Framefile.json or title.strings")`

This leads to:
```Ruby
    # Fetches the title + keyword for this particular screenshot
    def fetch_text(type)
      UI.user_error!("Valid parameters :keyword, :title") unless [:keyword, :title].include?(type)

      # Try to get it from a keyword.strings or title.strings file
      strings_path = File.join(File.expand_path("..", screenshot.path), "#{type}.strings")
      if File.exist?(strings_path)
        parsed = StringsParser.parse(strings_path)
        text_array = parsed.find { |k, v| screenshot.path.upcase.include?(k.upcase) }
        return text_array.last if text_array && text_array.last.length > 0  # Ignore empty string
      end
                            
      UI.verbose("Falling back to text in Framefile.json as there was nothing specified in the #{type}.strings file")

      # No string files, fallback to Framefile config
      text = fetch_config[type.to_s]['text'] if fetch_config[type.to_s] && fetch_config[type.to_s]['text'] && fetch_config[type.to_s]['text'].length > 0 # Ignore empty string
                            
      if type == :title and !text
        # title is mandatory
        UI.user_error!("Could not get title for screenshot #{screenshot.path}. Please provide one in your Framefile.json or title.strings")
      end

      return text
    end
```

An added bonus of my edits to `fetch_text()` is that that last `UI.user_error` is now also called when the title is defined as an empty string. This wasn't the case before (even in 2.68.2 without fix #10440) and the code failed as an image was created without text content:

> [11:32:14]: Framing screenshot './en-US/iPhone SE-01_RemoteTab.png'
> mogrify: geometry does not contain image `/var/folders/7g/n55n1s5x3z931vflyvwp_7280000gn/T/mini_magick20180110-40105-1ky6nc2.png' @ warning/attribute.c/GetImageBoundingBox/240.
> mogrify: geometry does not contain image `/var/folders/7g/n55n1s5x3z931vflyvwp_7280000gn/T/mini_magick20180110-40105-j5eg7k.png' @ warning/attribute.c/GetImageBoundingBox/240.

Another benefit is that the code runs faster when no (or empty) keyword is specified, because the whole code section for creating a text image and performing the Trimbox calculations is omitted because there is only a title key:
https://github.com/fastlane/fastlane/blob/d70c7d5b65c822a7d4546ac0b7d365b4f94ba71c/frameit/lib/frameit/editor.rb#L338

**Comment by janpio** [comment] 2018-01-10 11:02
Awesome. Can't wait to review that PR.

If you really want to hit it out of the park, you could also create a few (additional?) tests that check make these cases will work in the future as well.

**Comment by funnel20** [comment] 2018-01-10 11:09
**Verification**
I use the following requirements:

1. The `title` can be defined in either the _Framefile.json_ or in _title.strings_
2. The `keyword` can be defined in either the _Framefile.json_ or in _keyword.strings_
3. The definition in the _*.strings_ file takes precedence over the definition in _Framefile.json_
4. The `title` is mandatory. When no `title` is found in both files, or an empty string is defined, an error should be shown in Terminal and no screenshot should be created.
5. The `keyword` is optional. When specified, it should be shown left of the `title` in the screenshot.
6. The `title` and optional `keyword` should be horizontally aligned in the center of the screenshot (this issue).
7. The `title` and optional `keyword` should be vertically aligned in such a way that they share a common text baseline in the screenshot (issue #10440).

**Tests**

Description | 2.68.2 (before fix #10440) | 2.75.1 (latest incl. #10440)) | 2.75.1 + this fix
----------- | -------- | -- | --
No definition at all (not in _Framefile.json_ and no _*.strings_ files) | Warning (W1) shown, screenshot with no text created. | Warning (W1) shown, screenshot with no text created. | Proper error (E1) shown, no screenshot created = REQ-4
Define a title in _Framefile.json_ only, no _*.strings_ files | tbd | tbd | tbd
Define an empty title in _Framefile.json_ only, no _*.strings_ files | tbd | tbd | tbd
Define no title in _Framefile.json_ and one in _title.strings_, no _keyword.strings_ file | tbd | tbd | tbd
Define no title in _Framefile.json_ and an empty one in _title.strings_, no _keyword.strings_ file  | tbd | tbd | tbd
Define a title in _Framefile.json_ and a different title in _title.strings_, no _keyword.strings_ file | tbd | tbd | tbd

W1 =
> [11:32:14]: Framing screenshot './en-US/iPhone SE-01_RemoteTab.png'
> mogrify: geometry does not contain image `/var/folders/7g/n55n1s5x3z931vflyvwp_7280000gn/T/mini_magick20180110-40105-1ky6nc2.png' @ warning/attribute.c/GetImageBoundingBox/240.
> mogrify: geometry does not contain image `/var/folders/7g/n55n1s5x3z931vflyvwp_7280000gn/T/mini_magick20180110-40105-j5eg7k.png' @ warning/attribute.c/GetImageBoundingBox/240.

E1 =

**Comment by funnel20** [comment] 2018-01-10 12:51
**Conclusion**
The 2 fails are NOT present in this fix, while all REQs are met.
So this solution does not only repair this reported issue (small title in top right corner) but also an unreported issue that an empty title wasn't reported as erroneous.

**Comment by janpio** [comment] 2018-01-10 13:01
Oh wow - I hope you are really good with Markdown tables and didn't spend a few hours on this (as I would have to...). 

I actually thought of a `_spec` file in here: https://github.com/fastlane/fastlane/tree/master/frameit/spec

**Comment by funnel20** [comment] 2018-01-10 13:02
@janpio While working on this file _editor.rb_ I have one suggestion for refactoring.
Several variables are called `title_image` or `title_images`, see for example: https://github.com/fastlane/fastlane/blob/d70c7d5b65c822a7d4546ac0b7d365b4f94ba71c/frameit/lib/frameit/editor.rb#L265-L269

These are often used in a loop or struct, while it contains the data for either the keys "title" and "keyword".
So it's either the "title image" or "keyword image". The variable name `title_image` is highly confusion, as it might also contain the "keyword image".

The images are a graphical representation of the title and keyword text, so I would suggest to use `text_image` and `text_images`.

This will also apply to function `def build_title_images(max_width, max_height)`.
Do you agree?

**Comment by janpio** [comment] 2018-01-10 13:07
Makes absolute sense - probably one was added after the other and the variables not renamed properly. Would be a second, separate PR though to not mix stuff together. 

(If your first PR touches the same code, you might want to a) wait with creating the second one until this is merged or b) create the branch from the branch from the first PR (which will make it's PR commit history a bit messy until it is merged, but then get cleaned up automatically) so you don't get any nasty merge conflicts later)

**Comment by funnel20** [comment] 2018-01-10 13:30
OK, I'll choose option a).

I want to refactor a function name. How can I ensure that the current function name isn't used in any other file inside Fastlane?

**Comment by janpio** [comment] 2018-01-10 13:38
1. Run the test suite with `bundle exec fastlane test` (see https://github.com/fastlane/fastlane/blob/master/YourFirstPR.md) - if something fails, look into it
2. Search the code for the function name (manual style)
3. Maybe there is also a ruby IDE that can help with that - I am just using VS Code (and breaking stuff all the time, so I might not be the best person to ask...)

**Comment by funnel20** [comment] 2018-01-10 13:38
@janpio Is that `_spec.rb` for the automatic circle test?
Is there any documentation on how to:

- write such as file
- test such a file locally

**Comment by janpio** [comment] 2018-01-10 13:49
- Yes, these are Rspec tests, commonly used for ruby testing.
- I "learned" it by looking at other test files and lost of copy pasting.
- To run one specific file you use e.g. `bundle exec rspec .\fastlane\spec\fastlane_require_spec.rb`.

**Comment by funnel20** [comment] 2018-01-10 13:52
Awesome. I'll postpone that, so we can get this fix out first.
At least we have my table with the tests here for reference.

Shall I make the PR?

**Comment by janpio** [comment] 2018-01-10 13:53
Yep, sounds good to me.

**Comment by janpio** [comment] 2018-01-11 11:38
So @funnel20's PR to fix this was just merged and will be released with the next update. Follow #11518 to get notified when this happens

Thanks @funnel20!

**Closed** 2018-01-11 11:37 UTC
Labels: tool: frameit

**Comment by funnel20** [comment] 2018-01-11 14:18
@janpio I want to make a 2nd PR with the proposed renamed variables.
Forgive me my newbie question, but how can I update my forked repo to the latest master?
My common work-around is to delete my fork completely and fork again, but I hope this can be more easy.

**Comment by janpio** [comment] 2018-01-11 14:28
See here:
https://stackoverflow.com/a/13273853
Here is an alternative with the Github web UI: https://www.sitepoint.com/quick-tip-sync-your-fork-with-the-original-without-the-cli/

(But I still often just get rid of my old fork to be honest... One of the nicest things of becoming a contributor here was that I can create branches on `fastlane/fastlane` directly :)) )

**Comment by funnel20** [comment] 2018-01-11 16:01
@janpio Thanks, I'll try them next time, because somehow I destroyed my fork (again).

**Comment by funnel20** [comment] 2018-01-11 16:01
I created PR #11532, can you please review it?

**Comment by janpio** [comment] 2018-01-11 16:49
> somehow I destroyed my fork (again).

Haha, I know the feeling. Happens to me all the time, even with normal branches...

**Comment by funnel20** [comment] 2018-01-11 18:05
Yup. I'm used to Subversion and somehow I can't get Git into my system. Will follow some course, because I'm feeling quite stupid 🤔

**Comment by funnel20** [comment] 2018-01-16 23:52
@jkleroy This fix is scheduled to be released in 2.77.0. 
Can you please verify it and report back if it works as intended?

**Comment by jkleroy** [comment] 2018-01-17 00:18
I sure will, thanks @funnel20

**Comment by funnel20** [comment] 2018-01-17 12:57
@janpio Thanks to your link in https://github.com/fastlane/fastlane/issues/11464#issuecomment-356949767 I finally succeeded to update my local fork to master via SourceTree. 👍
