### ISSUE TITLE
ERROR: Bridging header problem with fastlane: Project Swift and libs in Objective-C

### ISSUE THREAD

**Issue by luanhenriq10** [fastlane/fastlane#8192] opened 2017-02-10 18:52 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines]

### Issue Description
Hello,

I am finding a weird error when installing fastlane in my project. I be able to install, create the fastlane archive and start a lane. However, when i call the fastlane beta method, fastlane execute with an error: XXXXXXXXYYYYY.h' file not found in my bridging header.

This mean that the fastlane was not able to found some of the archives inside of my bridging header. My project is in swift 2.2 and i am using some librarys in Objective-C, due to the availability of the libraries and theirs functionalities.

Anyone can help-me with this issue? 
For now, the project is without the fastlane. :/

##### Complete output when running fastlane, including the stack trace and command used
```▸ Compiling UIScrollView+TPKeyboardAvoidingAdditions.m
▸ Compiling TPKeyboardAvoiding_vers.c
▸ Linking TPKeyboardAvoiding
▸ Linking TPKeyboardAvoiding
▸ Generating 'TPKeyboardAvoiding.framework.dSYM'
▸ Copying TPKeyboardAvoiding-umbrella.h
▸ Copying TPKeyboardAvoidingCollectionView.h
▸ Copying TPKeyboardAvoidingScrollView.h
▸ Copying TPKeyboardAvoidingTableView.h
▸ Copying UIScrollView+TPKeyboardAvoidingAdditions.h
▸ Touching TPKeyboardAvoiding.framework
▸ Building Pods/TextFieldEffects [Release]
▸ Check Dependencies
▸ Processing Info.plist
▸ Compiling AkiraTextField.swift
▸ Compiling HoshiTextField.swift
▸ Compiling IsaoTextField.swift
▸ Compiling JiroTextField.swift
▸ Compiling KaedeTextField.swift
▸ Compiling MadokaTextField.swift
▸ Compiling MinoruTextField.swift
▸ Compiling TextFieldsEffects.swift
▸ Compiling YokoTextField.swift
▸ Compiling YoshikoTextField.swift
▸ Compiling AkiraTextField.swift
▸ Compiling HoshiTextField.swift
▸ Compiling IsaoTextField.swift
▸ Compiling JiroTextField.swift
▸ Compiling KaedeTextField.swift
▸ Compiling MadokaTextField.swift
▸ Compiling MinoruTextField.swift
▸ Compiling TextFieldsEffects.swift
▸ Compiling YokoTextField.swift
▸ Compiling YoshikoTextField.swift
▸ Compiling TextFieldEffects-dummy.m
▸ Compiling TextFieldEffects_vers.c
▸ Compiling TextFieldEffects-dummy.m
▸ Compiling TextFieldEffects_vers.c
▸ Linking TextFieldEffects
▸ Linking TextFieldEffects
▸ Generating 'TextFieldEffects.framework.dSYM'
▸ Copying TextFieldEffects-umbrella.h
▸ Touching TextFieldEffects.framework
▸ Building Pods/YLProgressBar [Release]
▸ Check Dependencies
▸ Processing Info.plist
▸ Compiling YLProgressBar-dummy.m
▸ Compiling YLProgressBar.m
▸ Compiling YLProgressBar_vers.c
▸ Compiling YLProgressBar-dummy.m
▸ Compiling YLProgressBar.m
▸ Compiling YLProgressBar_vers.c
▸ Linking YLProgressBar
▸ Linking YLProgressBar
▸ Generating 'YLProgressBar.framework.dSYM'
▸ Copying YLProgressBar-umbrella.h
▸ Copying YLProgressBar.h
▸ Touching YLProgressBar.framework
▸ Building Pods/iCarousel [Release]
▸ Check Dependencies
▸ Processing Info.plist
▸ Compiling iCarousel-dummy.m
▸ Compiling iCarousel.m
▸ Compiling iCarousel_vers.c
▸ Compiling iCarousel-dummy.m
▸ Compiling iCarousel.m
▸ Compiling iCarousel_vers.c
▸ Linking iCarousel
▸ Linking iCarousel
▸ Generating 'iCarousel.framework.dSYM'
▸ Copying iCarousel-umbrella.h
▸ Copying iCarousel.h
▸ Touching iCarousel.framework
▸ Building Pods/oHTTP [Release]
▸ Check Dependencies
▸ Processing Info.plist
▸ Compiling oHTTP.swift
▸ Compiling oHTTPEnvironment.swift
▸ Compiling oHTTP.swift
▸ Compiling oHTTPEnvironment.swift
▸ Compiling oHTTP-dummy.m
▸ Compiling oHTTP_vers.c
▸ Compiling oHTTP-dummy.m
▸ Compiling oHTTP_vers.c
▸ Linking oHTTP
▸ Linking oHTTP
▸ Generating 'oHTTP.framework.dSYM'
▸ Copying oHTTP-umbrella.h
▸ Touching oHTTP.framework
▸ Building Pods/pop [Release]
▸ Check Dependencies
▸ Processing Info.plist
▸ Compiling pop-dummy.m
▸ Compiling POPAnimatableProperty.mm
▸ Compiling POPAnimation.mm
▸ Compiling POPAnimationEvent.mm
▸ Compiling POPAnimationExtras.mm
▸ Compiling POPAnimationRuntime.mm
▸ Compiling POPAnimationTracer.mm
▸ Compiling POPAnimator.mm
▸ Compiling POPBasicAnimation.mm
▸ Compiling POPCGUtils.mm
▸ Compiling POPCustomAnimation.mm
▸ Compiling POPDecayAnimation.mm
▸ Compiling POPGeometry.mm
▸ Compiling POPLayerExtras.mm
▸ Compiling POPMath.mm
▸ Compiling POPPropertyAnimation.mm
▸ Compiling POPSpringAnimation.mm
▸ Compiling POPVector.mm
▸ Compiling TransformationMatrix.cpp
▸ Compiling pop_vers.c
▸ Compiling pop-dummy.m
▸ Compiling POPAnimatableProperty.mm
▸ Compiling POPAnimation.mm
▸ Compiling POPAnimationEvent.mm
▸ Compiling POPAnimationExtras.mm
▸ Compiling POPAnimationRuntime.mm
▸ Compiling POPAnimationTracer.mm
▸ Compiling POPAnimator.mm
▸ Compiling POPBasicAnimation.mm
▸ Compiling POPCGUtils.mm
▸ Compiling POPCustomAnimation.mm
▸ Compiling POPDecayAnimation.mm
▸ Compiling POPGeometry.mm
▸ Compiling POPLayerExtras.mm
▸ Compiling POPMath.mm
▸ Compiling POPPropertyAnimation.mm
▸ Compiling POPSpringAnimation.mm
▸ Compiling POPVector.mm
▸ Compiling TransformationMatrix.cpp
▸ Compiling pop_vers.c
▸ Linking pop
▸ Linking pop
▸ Generating 'pop.framework.dSYM'
▸ Copying pop-umbrella.h
▸ Copying POP.h
▸ Copying POPAnimatableProperty.h
▸ Copying POPAnimation.h
▸ Copying POPAnimationEvent.h
▸ Copying POPAnimationExtras.h
▸ Copying POPAnimationTracer.h
▸ Copying POPAnimator.h
▸ Copying POPBasicAnimation.h
▸ Copying POPCustomAnimation.h
▸ Copying POPDecayAnimation.h
▸ Copying POPDefines.h
▸ Copying POPGeometry.h
▸ Copying POPLayerExtras.h
▸ Copying POPPropertyAnimation.h
▸ Copying POPSpringAnimation.h
▸ Touching pop.framework
▸ Building Pods/Pods-Easy [Release]
▸ Check Dependencies
▸ Processing Info.plist
▸ Compiling Pods-Easy-dummy.m
▸ Compiling Pods_Easy_vers.c
▸ Compiling Pods-Easy-dummy.m
▸ Compiling Pods_Easy_vers.c
▸ Copying Pods-Easy-umbrella.h
▸ Touching Pods_Easy.framework
▸ Building Easy/Easy [(Production)]
▸ Check Dependencies
▸ Running script '[CP] Check Pods Manifest.lock'
▸ Running script '[CP] Check Pods Manifest.lock'

❌  /Users/LuanDamasceno/Documents/Zup/Projetos/Vivo/vivo-easy-ios/Easy/Easy-Bridging-Header.h:7:9: 'FBSDKMessengerShareKit/FBSDKMessengerShareKit.h' file not found 
```

### Environment

fastlane env -> 2.14.2

Do you use bundler to execute fastlane (i.e. bundle exec fastlane)? no

Do you use a Ruby environment manager (e.g. chruby, rbenv, rvm)? yes

**Comment by luanhenriq10** [comment] 2017-02-15 17:30
Someone?

**Comment by mgrebenets** [comment] 2017-02-22 06:53
Hi Luan

When it comes to building ur project fastlane doesn't really do anything
special. Under the hood it calls the very same xcodebuild command you would
use directly.

You can see the xcodebuild command in the log and then try to run that or
similar command directly in the terminal. Chances are high that u will get
same error, which means it has something to do with ur project setup. I
would guess header search paths, probably.

I personally was in situations when the project builds in Xcode but has
compile errors when building it with xcodebuild from command line. For
example, Xcode is more forgiving for relative paths in build settings,
while command line may fail to resolve them.

**Comment by ohayon** [comment] 2017-02-28 14:54
Hey @luanhenriq10, @mgrebenets is right, it would be best to reproduce this issue just by running the `xcodebuild` command that _fastlane_ shows it is running. Given that _fastlane_ just calls `xcodebuild` itself, that will be the most reliable way to single out the issue.

I am going to close this for now as it seems to be an issue with the project building rather than _fastlane_ but please feel free to comment again here if you are still needing any help! 🐙 👍

**Closed by ohayon** 2017-02-28 14:54 UTC
