### ISSUE TITLE
[deliver][spaceship] SSL_connect SYSCALL returned=5 errno=0 state=SSLv3 read server hello A

### ISSUE THREAD

**Issue by GandjaFuzz** [fastlane/fastlane#6580] opened 2016-10-17 12:41 UTC
error: SSL_connect SYSCALL returned=5 errno=0 state=SSLv3 read server hello A
in time deliver
log
```
[14:47:18]: Successfully uploaded initial set of metadata to iTunes Connect
[14:47:22]: Starting with the upload of screenshots...
[14:47:22]: Uploading 12 screenshots for language ru
[14:47:22]: Uploading '/Users/Shared/Jenkins/Home/workspace/tmp/285/Api/fastlane/screenshots/ru/iPadPro(12.9-inch)-01Menu-portrait_framed.png'...
[14:47:31]: Uploading '/Users/Shared/Jenkins/Home/workspace/tmp/285/Api/fastlane/screenshots/ru/iPadPro(12.9-inch)-02Nav-portrait_framed.png'...
[14:47:49]: Uploading '/Users/Shared/Jenkins/Home/workspace/tmp/285/Api/fastlane/screenshots/ru/iPadPro(12.9-inch)-03Cart-portrait_framed.png'...
[14:47:54]: Uploading '/Users/Shared/Jenkins/Home/workspace/tmp/285/Api/fastlane/screenshots/ru/iPhone7-01Menu-portrait_framed.png'...
[14:48:01]: Uploading '/Users/Shared/Jenkins/Home/workspace/tmp/285/Api/fastlane/screenshots/ru/iPhone7-02Nav-portrait_framed.png'...
[14:48:08]: Uploading '/Users/Shared/Jenkins/Home/workspace/tmp/285/Api/fastlane/screenshots/ru/iPhone7-03Cart-portrait_framed.png'...
[14:48:12]: Uploading '/Users/Shared/Jenkins/Home/workspace/tmp/285/Api/fastlane/screenshots/ru/iPhone7Plus-01Menu-portrait_framed.png'...
[14:48:23]: Uploading '/Users/Shared/Jenkins/Home/workspace/tmp/285/Api/fastlane/screenshots/ru/iPhone7Plus-02Nav-portrait_framed.png'...
[14:48:36]: Uploading '/Users/Shared/Jenkins/Home/workspace/tmp/285/Api/fastlane/screenshots/ru/iPhone7Plus-03Cart-portrait_framed.png'...
[14:48:40]: Uploading '/Users/Shared/Jenkins/Home/workspace/tmp/285/Api/fastlane/screenshots/ru/iPhoneSE-01Menu-portrait_framed.png'...
[14:48:46]: Uploading '/Users/Shared/Jenkins/Home/workspace/tmp/285/Api/fastlane/screenshots/ru/iPhoneSE-02Nav-portrait_framed.png'...
[14:48:55]: Uploading '/Users/Shared/Jenkins/Home/workspace/tmp/285/Api/fastlane/screenshots/ru/iPhoneSE-03Cart-portrait_framed.png'...
[14:48:58]: Saving changes
[14:49:36]: Successfully uploaded screenshots to iTunes Connect
[14:49:38]: Price Tier unchanged (tier 0)
[14:49:40]: Uploading app icon...
[14:49:46]: Uploading binary to iTunes Connect
[14:49:46]: Going to upload updated app to iTunes Connect
[14:49:46]: This might take a few minutes. Please don't interrupt the script.
[14:51:01]: iTunes Transporter successfully finished its job
[14:51:01]: ------------------------------------------------------------------------------------------------------
[14:51:01]: Successfully uploaded package to iTunes Connect. It might take a few minutes until it's visible online.
[14:51:01]: ------------------------------------------------------------------------------------------------------
[14:51:01]: Finished the upload to iTunes Connect
[14:51:02]: Variable Dump:
[14:51:02]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios auto_release", :SIGH_PROFILE_TYPE=>"app-store", :IPA_OUTPUT_PATH=>"/Users/Shared/Jenkins/Home/workspace/tmp/285/Api/Restaurant.ipa", :DSYM_OUTPUT_PATH=>"/Users/Shared/Jenkins/Home/workspace/tmp/285/Api/Restaurant.app.dSYM.zip", :XCODEBUILD_ARCHIVE=>"/Users/Shared/Jenkins/Library/Developer/Xcode/Archives/2016-10-17/Restaurant 2016-10-17 14.39.20.xcarchive", :SNAPSHOT_SCREENSHOTS_PATH=>"/Users/Shared/Jenkins/Home/workspace/tmp/285/Api/fastlane/screenshots"}
[14:51:02]: {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Unexpected Error"], "info"=>nil}, "statusCode"=>"ERROR"}

+------+---------------------------------------------------------------+-------------+
|                                  fastlane summary                                  |
+------+---------------------------------------------------------------+-------------+
| Step | Action                                                        | Time (in s) |
+------+---------------------------------------------------------------+-------------+
| 1    | Verifying required fastlane version                           | 0           |
| 2    | default_platform                                              | 0           |
| 3    | find '/Users/Shared/Jenkins/Home/workspace/tmp/285/Api/fastla | 0           |
| 4    | match                                                         | 301         |
| 5    | gym                                                           | 48          |
| 6    | find '/Users/Shared/Jenkins/Home/workspace/tmp/285/Api/fastla | 0           |
| 7    | find '/Users/Shared/Jenkins/Home/workspace/tmp/285/Api/fastla | 0           |
| 8    | snapshot                                                      | 332         |
| 9    | frameit                                                       | 69          |
| 10   | find '/Users/Shared/Jenkins/Home/workspace/tmp/285/Api/fastla | 0           |
| 💥    | deliver                                                       | 249         |
+------+---------------------------------------------------------------+-------------+

[14:51:02]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

[14:51:14]: Error finding relevant GitHub issues: SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A
```

**Comment by hjanuschka** [comment] 2016-10-17 12:48
possible duplicate of https://github.com/fastlane/fastlane/issues/6553

**Comment by asfalcone** [comment] 2016-10-17 15:52
@GandjaFuzz Going to close as a duplicate. Please follow #6553 as @hjanuschka mentions.

**Closed by asfalcone** 2016-10-17 15:52 UTC
