### ISSUE TITLE
ERROR - Crashlytics Developer Tools error. java.io.FileNotFoundException: /tmp/changelog20160928-32826-b1gtf0 (No such file or directory)

### ISSUE THREAD

**Issue by spirosoik** [fastlane/fastlane#6325] opened 2016-09-28 18:53 UTC
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
##### Complete output when running fastlane, including the stack trace and command used

```
ERROR - Crashlytics Developer Tools error.
java.io.FileNotFoundException: /tmp/changelog20160928-32826-b1gtf0 (No such file or directory)
    at java.io.FileInputStream.open0(Native Method)
    at java.io.FileInputStream.open(FileInputStream.java:195)
    at java.io.FileInputStream.<init>(FileInputStream.java:138)
    at com.google.common.io.Files$FileByteSource.openStream(Files.java:126)
    at com.google.common.io.Files$FileByteSource.openStream(Files.java:116)
    at com.google.common.io.ByteSource$AsCharSource.openStream(ByteSource.java:435)
    at com.google.common.io.CharSource.read(CharSource.java:162)
    at com.google.common.io.Files.toString(Files.java:367)
    at com.crashlytics.tools.android.DeveloperTools.getPropertyValueOrValueFromPropertyPath(DeveloperTools.java:743)
    at com.crashlytics.tools.android.DeveloperTools.processProperties(DeveloperTools.java:662)
    at com.crashlytics.tools.android.DeveloperTools.processArgsInternal(DeveloperTools.java:348)
    at com.crashlytics.tools.android.DeveloperTools.main(DeveloperTools.java:273)
Exception in thread "main" com.crashlytics.tools.android.exception.PluginException: Crashlytics Developer Tools error.
    at com.crashlytics.tools.android.DeveloperTools.processArgsInternal(DeveloperTools.java:356)
    at com.crashlytics.tools.android.DeveloperTools.main(DeveloperTools.java:273)
Caused by: java.io.FileNotFoundException: /tmp/changelog20160928-32826-b1gtf0 (No such file or directory)
    at java.io.FileInputStream.open0(Native Method)
    at java.io.FileInputStream.open(FileInputStream.java:195)
    at java.io.FileInputStream.<init>(FileInputStream.java:138)
    at com.google.common.io.Files$FileByteSource.openStream(Files.java:126)
    at com.google.common.io.Files$FileByteSource.openStream(Files.java:116)
    at com.google.common.io.ByteSource$AsCharSource.openStream(ByteSource.java:435)
    at com.google.common.io.CharSource.read(CharSource.java:162)
    at com.google.common.io.Files.toString(Files.java:367)
    at com.crashlytics.tools.android.DeveloperTools.getPropertyValueOrValueFromPropertyPath(DeveloperTools.java:743)
    at com.crashlytics.tools.android.DeveloperTools.processProperties(DeveloperTools.java:662)
    at com.crashlytics.tools.android.DeveloperTools.processArgsInternal(DeveloperTools.java:348)
    ... 1 more
```
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:

``` ruby

  desc "Share to QA"
  lane :share_qa do
    message = last_git_commit[:message]
    if ENV['CRASHLYTICS_API_KEY'] && ENV['CRASHLYTICS_BUILD_SECRET']
        crashlytics(
            notes: message,
            groups: ['internal-beta-testers'],
            api_token: ENV['CRASHLYTICS_API_KEY'],
            build_secret: ENV['CRASHLYTICS_BUILD_SECRET']
        )
    end
    postToSlack(message, "QA")
  end
```
### Environment

fastlane version (run `fastlane -v`): 1.104.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? yes

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? no

This happens only when I have `notes` message in `crashlytics()`.  In my local machine works without a problem in CircleCI crashes every time.

I can see that you are trying to create a temp file here https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/crashlytics.rb#L11 
but for some reason never created or something different?

**Comment by spirosoik** [comment] 2016-09-29 14:13
btw If I remove `notes` it work and I can understand because it's not creating a new file but this is not really acceptable. I want to add a changelog for each beta build in fabric.

**Comment by romanr** [comment] 2016-10-04 15:19
I have exactly same error about changelog not found. Removing crashlytics "`notes:`" fixed the issue.

The irony is that I spent two hours migrating from gradle-based crashlytics uploading to fastlane  because of fastlane's nice `changelog_from_git_commits`. To find out in the end that I can't upload with notes.

**Comment by spirosoik** [comment] 2016-10-04 15:22
@romanr yes the issue is that temp changelog file cannot be created. quick workaround is to create your file and write the changelog by your own. Check the following:

```ruby
sh("touch changelog.txt")
File.write("/home/ubuntu/<your-app-name>/fastlane/changelog.txt"], last_git_commit[:message])
```

**Comment by TKBurner** [comment] 2016-10-11 16:01
@spirosoik What happens if you pass a string as the notes rather than a variable? Thanks!

**Comment by spirosoik** [comment] 2016-10-11 16:18
@TKBurner didn't try but variable which I am adding is a string so I don't think that there will be a different behavior. if there is it's super weird which I don't think is possible.

**Comment by TKBurner** [comment] 2016-10-11 20:45
@spirosoik Are you able to get things up and running if you provide a file to notes_path rather than using notes directly? Thanks!

**Comment by spirosoik** [comment] 2016-10-12 05:30
@TKBurner what I wrote here https://github.com/fastlane/fastlane/issues/6325#issuecomment-251420947 it works without a problem with `notes_path` but still you need to fix that guys, I added so many extra steps to make it and it must work out of the box.

**Comment by TKBurner** [comment] 2016-10-12 20:07
@spirosoik Thanks! Are you interested in submitting a PR to correct this? We'd love to see that 👍 👍 💯

**Comment by spirosoik** [comment] 2016-10-13 06:11
@TKBurner it's really possible I think I know the reason of the problem.

**Comment by TKBurner** [comment] 2016-10-17 21:23
@spirosoik Awesome! Let me know if you have any questions about contributing 👍

**Comment by spirosoik** [comment] 2016-12-17 08:26
this is occurred only to CircleCI and doesn't exist in TravisCI

**Comment by yapiskan** [comment] 2016-12-21 03:30
@spirosoik it is also happening for me in Travis CI. not consistently but happening time to time. and when it happens, it last for 4-5 builds consequently.

**Comment by spirosoik** [comment] 2016-12-21 08:56
@yapiskan true story suddenly yesterday was started crashing for us, so I reverted back to the example which I wrote above.

**Comment by yapiskan** [comment] 2016-12-22 21:18
@spirosoik I tried that on Travis but the machine travis assigned for our Android project is running on Debian and I just couldn't find the path to the changelog file. How did you find that path on ubuntu? Maybe I can follow to understand it for Debian.

**Comment by spirosoik** [comment] 2016-12-23 08:30
you need to do the following @yapiskan:

```ruby

        sh("cd .. && touch changelog.txt")
        File.write("./changelog.txt", message)
        crashlytics(
            notes_path: "./changelog.txt",
            groups: ['qa'],
            api_token: crashlytics_api_key,
            build_secret: crashlytics_build_secret 
        )
```

**Comment by asfalcone** [comment] 2017-01-10 16:53
@yapiskan Did you have a chance to try @spirosoik's solution? Let us know if that has things working correctly for you!

**Comment by joxad** [comment] 2017-01-13 15:09
Hi method from @spirosoik working for me ! 
I got the same problem when using 

 message = last_git_commit[:message]
    if ENV['CRASHLYTICS_API_KEY'] && ENV['CRASHLYTICS_BUILD_SECRET']
        crashlytics(
            notes: message,
            groups: ['internal-beta-testers'],
            api_token: ENV['CRASHLYTICS_API_KEY'],
            build_secret: ENV['CRASHLYTICS_BUILD_SECRET']
        )
    end

**Comment by spirosoik** [comment] 2017-01-13 15:31
@asfalcone for sure there is a bug what we do right now is a workaround! It's not the proper behavior of fastlane. Something bad happens when fastlane tries to create a tmp file in directory `/tmp/<hash>`

**Comment by xiangyu-sun** [comment] 2017-02-08 06:35
even after I did the workaround, and I have the local change log there, adding that 'notes_path' dose not making Crashlytics  Beta have the Release note. Any one had this problem?

**Comment by spirosoik** [comment] 2017-02-08 09:20
@xiangyu-sun did you follow the instructions above. for us it works nicely for 3 different repos in travis-ci.

**Comment by xiangyu-sun** [comment] 2017-02-10 05:36
sh("cd .. && touch changelog.txt")
    File.write("./changelog.txt", ENV["GIT_COMMIT_LOG"])
    sh "cat ./changelog.txt"
    crashlytics(
      notes_path: "./changelog.txt",
      api_token: token,
      build_secret: key,
      groups: "android-develop"
    )

looks like this, and the CAT proved something in the changelog, but still, the Release Notes shows nothing.

Travis log:
[06:26:11]: ------------------------------------------
[06:26:11]: --- Step: cd .. && touch changelog.txt ---
[06:26:11]: ------------------------------------------
[06:26:11]: $ cd .. && touch changelog.txt
[06:26:11]: ---------------------------------
[06:26:11]: --- Step: cat ./changelog.txt ---
[06:26:11]: ---------------------------------
[06:26:11]: $ cat ./changelog.txt
[06:26:11]: ▸ Merge branch 'develop' of https://github.com/xxxxx/xxxx into develop
[06:26:11]: -------------------------
[06:26:11]: --- Step: crashlytics ---
[06:26:11]: -------------------------
[06:26:11]: Downloading Crashlytics Support Library - this might take a minute...

**Comment by spirosoik** [comment] 2017-02-10 06:46
@xiangyu-sun 

you need to use this:

`File.write("changelog.txt", last_git_commit[:message])`

**Comment by spirosoik** [comment] 2017-02-10 12:43
Yes we are using the same for two projects and works without a problem. @xiangyu-sun I think I found your problem:

```
crashlytics(
            notes_path: "fastlane/changelog.txt", <------- This is the fix
            groups: ['internal-beta-testers'],
            api_token: key,
            build_secret: secret
        )
```

**Comment by xiangyu-sun** [comment] 2017-02-13 02:42
yes, finally found out notes_path for Android required absolute path, I think this is the problem.
Thanks @spirosoik

**Comment by lernerb** [comment] 2017-03-07 15:52
Is there any fix for this coming out on android soon? This is definitely a blocker for us using fastlane on Android. Same stack trace with the tmp file not found, seeing the issue with both `notes` and `notes_path`.

**Comment by spirosoik** [comment] 2017-03-07 16:10
@lernerb above your comment there is already a merged PR so you can try and give us feedback back! We will help also contributors to close the issue if it has been fixed.

**Comment by lernerb** [comment] 2017-03-09 21:05
I'm trying to find the root cause. I tried updating to 2.19.3 and am still seeing the following error occasionally. Approximately 50% of the builds go through fine, the other 50% fail with the trace:

```
[20:52:53]: [32mUploading the build to Crashlytics Beta. Time for some ☕️.[0m
[20:52:55]: [31mERROR - Crashlytics Developer Tools error.
java.io.FileNotFoundException: /tmp/changelog20170309-3390-1piytgi (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at com.google.common.io.Files$FileByteSource.openStream(Files.java:126)
	at com.google.common.io.Files$FileByteSource.openStream(Files.java:116)
	at com.google.common.io.ByteSource$AsCharSource.openStream(ByteSource.java:435)
	at com.google.common.io.CharSource.read(CharSource.java:162)
	at com.google.common.io.Files.toString(Files.java:367)
	at com.crashlytics.tools.android.DeveloperTools.getPropertyValueOrValueFromPropertyPath(DeveloperTools.java:743)
	at com.crashlytics.tools.android.DeveloperTools.processProperties(DeveloperTools.java:662)
	at com.crashlytics.tools.android.DeveloperTools.processArgsInternal(DeveloperTools.java:348)
	at com.crashlytics.tools.android.DeveloperTools.main(DeveloperTools.java:273)
Exception in thread "main" com.crashlytics.tools.android.exception.PluginException: Crashlytics Developer Tools error.
	at com.crashlytics.tools.android.DeveloperTools.processArgsInternal(DeveloperTools.java:356)
	at com.crashlytics.tools.android.DeveloperTools.main(DeveloperTools.java:273)
Caused by: java.io.FileNotFoundException: /tmp/changelog20170309-3390-1piytgi (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at com.google.common.io.Files$FileByteSource.openStream(Files.java:126)
	at com.google.common.io.Files$FileByteSource.openStream(Files.java:116)
	at com.google.common.io.ByteSource$AsCharSource.openStream(ByteSource.java:435)
	at com.google.common.io.CharSource.read(CharSource.java:162)
	at com.google.common.io.Files.toString(Files.java:367)
	at com.crashlytics.tools.android.DeveloperTools.getPropertyValueOrValueFromPropertyPath(DeveloperTools.java:743)
	at com.crashlytics.tools.android.DeveloperTools.processProperties(DeveloperTools.java:662)
	at com.crashlytics.tools.android.DeveloperTools.processArgsInternal(DeveloperTools.java:348)
	... 1 more
```

**Closed** 2017-05-17 21:12 UTC
Labels: action, auto-closed, awaiting-reply, waiting-for-reply

**Comment by doron-kettner** [comment] 2017-07-24 11:14
Reoccur when working with Jenkins

**Comment by maybegil** [comment] 2017-07-26 08:40
I am having the same problem working with CircleCI. Do we have a final solution?

**Comment by doron-kettner** [comment] 2017-07-26 11:16
My problem was related to the permissions of the shell task in a Jenkins job.
Originally, I altered the designated workspace to a different than the Jenkins default workspace.
I modified it back to Jenkins default and changed the /tmp folder permission to 777 using chmod command
Not the best approach but it did the trick

**Comment by maybegil** [comment] 2017-07-26 11:27
@doron-kettner I could solved it with this:

`sh("cd .. && touch changelog.txt")
  message = last_git_commit[:message]
  File.write("./changelog.txt", message)
  # upload to Beta by Crashlytics
  crashlytics(
    notes_path: "fastlane/changelog.txt",
    api_token: api_token_num,
    build_secret: build_secret_num,
    groups: "testers",
 )`

Just like @xiangyu-sun said 💃 . Thanks for the reply!

**Comment by lernerb** [comment] 2017-07-26 11:34
Yup as of right now that's the workaround that I ended up with as well. It seems like the only way for the Dev team to fix this would to have a /tmp directory within fastlane, or remove the usage of it completely.
