### ISSUE TITLE
Pilot generate filename with special characters

### ISSUE THREAD

**Issue by fnazarios** [fastlane/fastlane#10356] opened 2017-09-18 19:58 UTC
### Issue Description
With new 2.57.0 fastlane version, pilot crashes with this log:
```swift 
[16:47:40]: Login successful
[16:47:41]: Ready to upload new build to TestFlight (App: XXXXXXXX)...
[16:47:42]: Going to upload updated app to iTunes Connect
[16:47:42]: This might take a few minutes. Please don't interrupt the script.
[16:47:52]: [Transporter Error Output]: The filename MyApp(1c9e0d30d8f53g56hbeed9b3934fh910e7d6a59bd71f91445aaa).ipa in the package contains an invalid character(s).  The valid characters are: A-Z, a-z, 0-9, dash, period, underscore, but the name cannot start with a dash, period, or underscore
[16:47:52]: Transporter transfer failed.
```
### Environment
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13                                       |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.5 (Apple Git-94)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.13 (17A360a)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.1_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0                                         |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.57.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.2.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| CFPropertyList            | 2.3.5        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.0       |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| io-console                | 0.4.6        |
| openssl                   | 2.0.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
</details>

*generated on:* **2017-09-18**
</details>

**Comment by dtrukr** [comment] 2017-09-18 20:40
Seems to be related to https://github.com/fastlane/fastlane/issues/10327

**Comment by gasthana0** [comment] 2017-09-18 21:01
I am also seeing this error on 2.57.0. Pilot is working fine with 2.56.0.

**Comment by codyrotwein** [comment] 2017-09-18 22:29
Ditto

**Comment by dtrukr** [comment] 2017-09-19 05:26
OK, so I needed deliver/pilot to work again locally earlier today, so I made a PR to fix this: https://github.com/fastlane/fastlane/pull/10357

**Comment by vmalyi** [comment] 2017-09-19 09:13
Downgrading Fastlane to 2.56.0 helps.

**Comment by KrauseFx** [comment] 2017-09-19 09:23
Thanks y'all for reporting this, and sorry for breaking it in the first place, this is now fixed with the most recent release, please update 👍

**Comment by omerfarukyilmaz** [comment] 2017-09-19 09:29
Confirmed 2.57.1 fixes the issue.

Thanks @dtrukr for the fast work and all fastlane developers for the quick approves and merge!

**Comment by KrauseFx** [comment] 2017-09-19 09:32
Thanks for all your support ❤️

**Comment by joshtobin** [comment] 2017-09-19 10:07
Awesome, this was breaking my builds 1 hour ago, I went to a meeting and came back and it had been fixed. Thanks for the quick fix!

**Closed** 2017-11-12 10:21 UTC
Labels: status: auto-closed, status: waiting-for-reply
