### ISSUE TITLE
Automatic submission of a new app identifier to Fabric.

### ISSUE THREAD

**Issue by fabiomassimo** [fastlane/fastlane#734] opened 2015-10-25 16:40 UTC
Fastlane improved my deployment process by bringing it to an entire new level.
Now that it is part of Fabric I would like that the Crashlytics action gets a new option: upload a build for an app identifier that was never submitted to your Fabric's organisation.

## Examples

* All my projects are deployed through `Fastlane` installed on a osx-server-machine and sent to Crashlytics for beta distribution.
Since most of the time the app identifier of my application changes per configuration, it could happen that an app identifier was never registered to my Fabric's organization before because the app, having that identifier, was never launched from my dev-machine, therefore, never submitted through the Fabric app.

* Old projects: https://twitter.com/iamfabiomilano/status/629264597816594432

## Current status

When trying to deploy through fastlane without never submitting the app identifier through the Fabric app:

```
We couldn't validate app with bundle ID *** in the selected organization, so make sure you've first added your app through the Crashlytics app. You can check that your API key and build secret are correct by going here: https://crashlytics.com/settings/organizations Then select the org and click on API key or build secret underneath the org name.
```

This error is returned from the CLI tool shipped with the Crashlytics framework which is used by the `fastlane`'s action: Crashlytics.
I strongly believe that some actions are required from the Crashlytics team first, in order to be able to implement this feature.

**Comment by xfreebird** [comment] 2015-10-26 17:08
:+1:  This so familiar. 

At least we can upload from command line the ```ipa``` without the need to recompile the project.
Can't say the same for Android ```apk``` files, only by recompiling the project.

**Comment by Sega-Zero** [comment] 2015-11-23 21:02
Faced the same trouble. Crashlytics twitter team [promised](https://twitter.com/crashlytics/status/667768134389075969) me that this feature will be added in the future. Right now I'm trying to defeat this by launching the app in the simulator with `ios-sim` like that:
```ruby
if options[:beta]
    #crashlytics wants app to be activated 
    xcodebuild(
        scheme: "Debug",
        workspace: 'Sample.xcworkspace',
        derivedDataPath: './Build',
        arch: "i386",
        sdk: "iphonesimulator9.1"
    )

    sh('ios-sim launch ../Build//Build/Products/Debug-iphonesimulator/Sample.app --devicetypeid "com.apple.CoreSimulator.SimDeviceType.iPhone-6, 9.1" --verbose --exit')
    sh('echo wait for 10 seconds to ensure app is activated && sleep 10 && echo waiting done')
end
```

That way it works, but sometimes I still get <code>We couldn't validate app with bundle ID ...</code> error. I hope Crashlytics will add automatic activation in the future.

**Comment by KrauseFx** [comment] 2015-11-23 21:35
@Sega-Zero I chatted with Mike about this and currently it is required that an app is built and run before it will be active in your Fabric dashboard. Adding a way to only build your app and have it be added to Fabric is something I raised up. Adding this is something that Mike will discuss further with the team!

**Comment by Sega-Zero** [comment] 2015-11-23 21:41
You will save a lot of time and travis cpu =) Waiting for you, guys, praying this feature will be there!

**Comment by ohwutup** [comment] 2016-02-25 21:06
Hi everyone! This is an awesome request and definitely something that we would like to make happen down the line. I am going to close this issue and mark it as a feature request and we will reopen it as soon as we are able to start work to this goal. Please feel free to comment here and continue discussion, all feedback would be great. Thank you!! :tada: :rocket:

**Closed by ohwutup** 2016-02-25 21:06 UTC

**Comment by iCarambaa** [comment] 2016-09-06 13:05
Hi everyone, are there any news on this?

**Comment by TKBurner** [comment] 2016-09-06 17:59
@iCarambaa Thanks for following up on this. Right now you'll still need to onboard with Crashlytics before you can use this action. Thanks!

**Comment by Saurman** [comment] 2016-09-13 16:12
Hello, i am facing same problem. We have build machine that compiles git branch and replaces info.plist file based on client profile (new bundle id for each client). We are not uploading builds to crashlytics (we use enterprise account and distribute IPA files from our download page). Problem is, in 95% app is not registered by Fabric. I suspect Fabric run script build phase, most likely fastlane is not setting all required environment variables for fabric binary to run with a success. 

Is there any way i can print an output for run script phase to a console when execute fastlane command?

**Comment by TKBurner** [comment] 2016-09-14 16:34
@Saurman I think you'll find it works better if you use cocoapods. https://fabric.io/kits/ios/crashlytics/install

Thanks!

**Comment by Saurman** [comment] 2016-09-18 20:19
@TKBurner it is using cocoa pods but i am still not seeing apps on web site. Steps to reproduce:
1) create new project and setup fabric using cocoa pods and common installation manual
2) build and run to make sure it works
3) setup fastlane to produce IPA file
4) change bundle ID
5) run fastlane and install created IPA 
6) run app - nothing happens, app is not registered on fabric web site

**Comment by TKBurner** [comment] 2016-09-22 21:15
Hi @Saurman Are you running the app in the simulator with the run script build phase in place? Thanks!

**Comment by Sega-Zero** [comment] 2016-09-22 21:24
@Saurman, there is no automatic app activation with fastlane yet. Unfortunately you still have to run an app with a new bundle id in the simulator or on the device before you can submit to crashlytics.
You may use my script above to automate it via ios-sim, it works, but takes longer time that expected to be.
Hope crashlytics team will add app activation with command-line option, or with https request officially.

**Comment by TKBurner** [comment] 2016-09-22 21:34
@Sega-Zero Thanks for stepping in. I'll talk to the Fabric team about this going forward.

**Comment by Saurman** [comment] 2016-09-28 05:49
@TKBurner @Sega-Zero we are not, why would a build machine whose purpose to create IPA files should run an app in simulator? What u are saying is not entirely true, i've tried installing fresh IPA on a device and run it - app will not register with fabric. I suspect the have compiler directive that runs activation code only when executed by iOS simulator (which is BS imo)

**Comment by Saurman** [comment] 2016-10-07 14:17
I've solved a problem by using fastlane scan tool. Appears that Fabric registers new apps only after app is launched on simulator

**Comment by Sega-Zero** [comment] 2016-10-07 14:18
Can you share your workaround here?

**Comment by TKBurner** [comment] 2016-10-11 15:30
@Sega-Zero Thanks for reaching out. If you just run scan with the default values it will register your app with Fabric. Let me know how it goes!

**Comment by Sega-Zero** [comment] 2016-11-02 18:21
Couldn't get it working. Would be very thankful if you share some sample project

**Comment by TKBurner** [comment] 2016-11-02 19:07
@Sega-Zero Can you show me your fastfile. Do you have a run script build phase in the project? Does the info.plist get the update of the crashlytics key?

Thanks!

**Comment by jaroslavas** [comment] 2017-01-05 11:39
@TKBurner Could you please share working lane example that could register app with crashlytics?

**Comment by KrauseFx** [comment] 2017-01-05 11:40
When you have Crashlytics set up for your project and run it in the simulator or real device once, it automatically gets registered.

**Comment by jaroslavas** [comment] 2017-01-05 11:41
Yes, but what if my CI creates new apps with new Bundle ID's?

**Comment by KrauseFx** [comment] 2017-01-05 11:46
Yeah, that works just fine, just run it in the simulator once using _scan_ by running your tests 👍

**Comment by Sega-Zero** [comment] 2017-01-05 12:20
@KrauseFx can you share some sample project (xcode + fastlane) that will demonstrate activation of a new bundle id in crashlytics with succesfull binary upload? Couldn't get it working fast enough, so had to defer the experiments untill a less time-consuming moment for my project.

**Comment by janmisar** [comment] 2017-01-19 08:38
I use similar workaround as @Sega-Zero but without `ios-sim` dependency (I dont't want any node and javascript).

```
# make build for simulator
xcodebuild(
        scheme: "MyApp",
        configuration: "Release",
        derivedDataPath: './build',
        sdk: "iphonesimulator10.2"
)

# select any iphone simulator
simulator_id = `xcrun instruments -s devices`.split(/$/).select { |item| (item.include? "10.2") && (item.include? "iPhone") }.last.scan(/\[(.*)\]/).last.first

sh("xcrun simctl shutdown #{simulator_id} || true") # shutdown running simulator (it fails when it's not running, but we want to ignore that error)
sh("xcrun simctl boot #{simulator_id}")
sh("xcrun simctl install #{simulator_id} $(pwd)/../build/Build/Products/#{configuration}-iphonesimulator/#{event.name}.app")
sh("xcrun simctl launch #{simulator_id} com.example.MyApp")
sleep(15) # wait some time to start app and register to crashylitics
sh("xcrun simctl shutdown #{simulator_id} || true")
```

It does not run real simulator window and it seems to be more stable than other ways of launching simulator.

**Comment by janmisar** [comment] 2017-01-19 08:50
I also tried to figure out how crashlytics SDK registers new app and run it manually. It sends multipart POST to `https://api.crashlytics.com/spi/v1/platforms/ios/apps` with headers:

```
X-Crashlytics-API-Client-Build-Version: 60
Content-Type: multipart/form-data
X-Crashlytics-Developer-Token: xxxx
User-Agent: io.fabric.sdk.ios/1.6.11 (60)
X-Crashlytics-API-Client-Display-Version: 1.6.11
X-Crashlytics-API-Key: xxxxx
X-Crashlytics-API-Client-Id: io.fabric.sdk.ios
```
and fileds:

```
app[identifier]: com.example.MyApp
app[instance_identifier]: xxxxx
app[name]: MyApp
app[build_version]: 999
app[display_version]: 1.0
app[source]: 1
app[minimum_sdk_version]: 9.1.0
app[built_sdk_version]: 10.2.0
app[build][libraries][com.twitter.crashlytics.ios]: 3.8.3
app[build][libraries][io.fabric.sdk.ios]: 1.6.11
app[build][libraries][com.twitter.answers.ios]: 1.3.3
app[build][libraries][com.twitter.sdk.ios]: 2.7.0
app[slices][][arch]: arm64
app[slices][][uuid]: xxxxx
app[icon][hash]: xxxx
app[icon][prerendered]: false
app[icon][width]: 120
app[icon][height]: 120
app[icon][data]: {file.png}
```
It answers `201 Created` but there is no app created on Crashlytics so I was not successful, but it could be a way. I have no more time to spend with this issue, but it could be a clue for someone. I used [BurpSuite](https://cjwirth.com/2015/04/15/debugging-https-traffic/) to analyse network traffic so you can continue ;-)
