### ISSUE TITLE
bundler: failed to load command: fastlane (/usr/local/lib/ruby/gems/2.7.0/bin/fastlane)

### ISSUE THREAD

**Issue by AshrafYEzouli** [fastlane/fastlane#17621] opened 2020-11-15 22:49 UTC
after run this command : 
sudo bundle exec fastlane distribute_to_firebase build_type:Debug

I got the below outputs

[✔] 🚀 
+-------------------------------------------+---------+-----------------------------------------------------------+
|                                                  Used plugins                                                   |
+-------------------------------------------+---------+-----------------------------------------------------------+
| Plugin                                    | Version | Action                                                    |
+-------------------------------------------+---------+-----------------------------------------------------------+
| fastlane-plugin-teams                     | 0.2.0   | teams                                                     |
| fastlane-plugin-get_version_code          | 0.2.0   | get_version_code                                          |
| fastlane-plugin-gmail                     | 0.1.2   | gmail                                                     |
| fastlane-plugin-firebase_app_distribution | 0.2.4   | firebase_app_distribution_login firebase_app_distribution |
+-------------------------------------------+---------+-----------------------------------------------------------+

[00:44:50]: ------------------------------
[00:44:50]: --- Step: default_platform ---
[00:44:50]: ------------------------------
[00:44:50]: Driving the lane 'android distribute_to_firebase' 🚀
[00:44:50]: ---------------------------
[00:44:50]: --- Step: assembleDebug ---
[00:44:50]: ---------------------------
[00:44:50]: $ /Users/ashrafezouli/Downloads/LPProjects/Marshal-FlyJo/Marshal/gradlew assembleDebug -p .
[00:44:51]: ▸ > Configure project :app
[00:44:51]: ▸ WARNING: The option setting 'android.enableR8=true' is deprecated.
[00:44:51]: ▸ It will be removed in version 5.0 of the Android Gradle plugin.
[00:44:51]: ▸ You will no longer be able to disable R8
[00:44:51]: ▸ > Task :app:preBuild UP-TO-DATE
[00:44:51]: ▸ > Task :app:preDebugBuild UP-TO-DATE
[00:44:51]: ▸ > Task :dexter:preBuild UP-TO-DATE
[00:44:51]: ▸ > Task :dexter:preDebugBuild UP-TO-DATE
[00:44:51]: ▸ > Task :dexter:compileDebugAidl NO-SOURCE
[00:44:51]: ▸ > Task :library:preBuild UP-TO-DATE
[00:44:51]: ▸ > Task :library:preDebugBuild UP-TO-DATE
[00:44:51]: ▸ > Task :library:compileDebugAidl NO-SOURCE
[00:44:51]: ▸ > Task :dexter:packageDebugRenderscript NO-SOURCE
[00:44:51]: ▸ > Task :library:packageDebugRenderscript NO-SOURCE
[00:44:51]: ▸ > Task :app:generateDebugBuildConfig UP-TO-DATE
[00:44:51]: ▸ > Task :app:javaPreCompileDebug UP-TO-DATE
[00:44:51]: ▸ > Task :dexter:writeDebugAarMetadata UP-TO-DATE
[00:44:51]: ▸ > Task :library:writeDebugAarMetadata UP-TO-DATE
[00:44:51]: ▸ > Task :app:generateDebugResValues UP-TO-DATE
[00:44:51]: ▸ > Task :app:injectCrashlyticsMappingFileIdDebug UP-TO-DATE
[00:44:51]: ▸ > Task :app:processDebugGoogleServices UP-TO-DATE
[00:44:51]: ▸ > Task :dexter:compileDebugRenderscript NO-SOURCE
[00:44:51]: ▸ > Task :dexter:generateDebugResValues UP-TO-DATE
[00:44:51]: ▸ > Task :dexter:generateDebugResources UP-TO-DATE
[00:44:51]: ▸ > Task :dexter:packageDebugResources UP-TO-DATE
[00:44:51]: ▸ > Task :library:compileDebugRenderscript NO-SOURCE
[00:44:51]: ▸ > Task :library:generateDebugResValues UP-TO-DATE
[00:44:51]: ▸ > Task :library:generateDebugResources UP-TO-DATE
[00:44:51]: ▸ > Task :library:packageDebugResources UP-TO-DATE
[00:44:51]: ▸ > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[00:44:51]: ▸ > Task :app:extractDeepLinksDebug UP-TO-DATE
[00:44:51]: ▸ > Task :dexter:extractDeepLinksDebug UP-TO-DATE
[00:44:51]: ▸ > Task :dexter:processDebugManifest UP-TO-DATE
[00:44:51]: ▸ > Task :library:extractDeepLinksDebug UP-TO-DATE
[00:44:51]: ▸ > Task :library:processDebugManifest UP-TO-DATE
[00:44:51]: ▸ > Task :dexter:compileDebugLibraryResources UP-TO-DATE
[00:44:51]: ▸ > Task :dexter:parseDebugLocalResources UP-TO-DATE
[00:44:51]: ▸ > Task :dexter:generateDebugRFile UP-TO-DATE
[00:44:51]: ▸ > Task :library:compileDebugLibraryResources UP-TO-DATE
[00:44:51]: ▸ > Task :library:parseDebugLocalResources UP-TO-DATE
[00:44:51]: ▸ > Task :library:generateDebugRFile UP-TO-DATE
[00:44:51]: ▸ > Task :dexter:generateDebugBuildConfig UP-TO-DATE
[00:44:51]: ▸ > Task :dexter:javaPreCompileDebug UP-TO-DATE
[00:44:51]: ▸ > Task :dexter:compileDebugJavaWithJavac UP-TO-DATE
[00:44:51]: ▸ > Task :dexter:bundleLibCompileToJarDebug UP-TO-DATE
[00:44:51]: ▸ > Task :library:generateDebugBuildConfig UP-TO-DATE
[00:44:51]: ▸ > Task :library:javaPreCompileDebug UP-TO-DATE
[00:44:51]: ▸ > Task :library:compileDebugJavaWithJavac UP-TO-DATE
[00:44:51]: ▸ > Task :library:bundleLibCompileToJarDebug UP-TO-DATE
[00:44:51]: ▸ > Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
[00:44:51]: ▸ > Task :app:mergeDebugShaders UP-TO-DATE
[00:44:51]: ▸ > Task :app:compileDebugShaders NO-SOURCE
[00:44:51]: ▸ > Task :app:generateDebugAssets UP-TO-DATE
[00:44:51]: ▸ > Task :dexter:mergeDebugShaders UP-TO-DATE
[00:44:51]: ▸ > Task :dexter:compileDebugShaders NO-SOURCE
[00:44:51]: ▸ > Task :dexter:generateDebugAssets UP-TO-DATE
[00:44:51]: ▸ > Task :dexter:packageDebugAssets UP-TO-DATE
[00:44:51]: ▸ > Task :library:mergeDebugShaders UP-TO-DATE
[00:44:51]: ▸ > Task :library:compileDebugShaders NO-SOURCE
[00:44:51]: ▸ > Task :library:generateDebugAssets UP-TO-DATE
[00:44:51]: ▸ > Task :library:packageDebugAssets UP-TO-DATE
[00:44:51]: ▸ > Task :app:processDebugJavaRes NO-SOURCE
[00:44:51]: ▸ > Task :dexter:processDebugJavaRes NO-SOURCE
[00:44:51]: ▸ > Task :dexter:bundleLibResDebug NO-SOURCE
[00:44:51]: ▸ > Task :library:processDebugJavaRes NO-SOURCE
[00:44:51]: ▸ > Task :library:bundleLibResDebug NO-SOURCE
[00:44:51]: ▸ > Task :app:checkDebugDuplicateClasses UP-TO-DATE
[00:44:51]: ▸ > Task :dexter:bundleLibRuntimeToJarDebug UP-TO-DATE
[00:44:51]: ▸ > Task :library:bundleLibRuntimeToJarDebug UP-TO-DATE
[00:44:51]: ▸ > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[00:44:51]: ▸ > Task :dexter:mergeDebugJniLibFolders UP-TO-DATE
[00:44:51]: ▸ > Task :dexter:mergeDebugNativeLibs NO-SOURCE
[00:44:51]: ▸ > Task :dexter:stripDebugDebugSymbols NO-SOURCE
[00:44:51]: ▸ > Task :dexter:copyDebugJniLibsProjectOnly UP-TO-DATE
[00:44:51]: ▸ > Task :library:mergeDebugJniLibFolders UP-TO-DATE
[00:44:51]: ▸ > Task :library:mergeDebugNativeLibs NO-SOURCE
[00:44:51]: ▸ > Task :library:stripDebugDebugSymbols NO-SOURCE
[00:44:51]: ▸ > Task :library:copyDebugJniLibsProjectOnly UP-TO-DATE
[00:44:51]: ▸ > Task :app:validateSigningDebug UP-TO-DATE
[00:44:51]: ▸ > Task :dexter:copyDebugJniLibsProjectAndLocalJars UP-TO-DATE
[00:44:51]: ▸ > Task :dexter:extractDebugAnnotations UP-TO-DATE
[00:44:51]: ▸ > Task :dexter:mergeDebugGeneratedProguardFiles UP-TO-DATE
[00:44:51]: ▸ > Task :dexter:mergeDebugConsumerProguardFiles UP-TO-DATE
[00:44:51]: ▸ > Task :dexter:prepareLintJarForPublish UP-TO-DATE
[00:44:51]: ▸ > Task :dexter:mergeDebugJavaResource UP-TO-DATE
[00:44:51]: ▸ > Task :dexter:syncDebugLibJars UP-TO-DATE
[00:44:51]: ▸ > Task :dexter:bundleDebugAar UP-TO-DATE
[00:44:51]: ▸ > Task :dexter:compileDebugSources UP-TO-DATE
[00:44:51]: ▸ > Task :dexter:assembleDebug UP-TO-DATE
[00:44:51]: ▸ > Task :library:copyDebugJniLibsProjectAndLocalJars UP-TO-DATE
[00:44:51]: ▸ > Task :library:extractDebugAnnotations UP-TO-DATE
[00:44:51]: ▸ > Task :library:mergeDebugGeneratedProguardFiles UP-TO-DATE
[00:44:51]: ▸ > Task :library:mergeDebugConsumerProguardFiles UP-TO-DATE
[00:44:51]: ▸ > Task :library:prepareLintJarForPublish UP-TO-DATE
[00:44:51]: ▸ > Task :library:mergeDebugJavaResource UP-TO-DATE
[00:44:51]: ▸ > Task :library:syncDebugLibJars UP-TO-DATE
[00:44:51]: ▸ > Task :library:bundleDebugAar UP-TO-DATE
[00:44:51]: ▸ > Task :library:compileDebugSources UP-TO-DATE
[00:44:51]: ▸ > Task :library:assembleDebug UP-TO-DATE
[00:44:51]: ▸ > Task :app:compileDebugRenderscript NO-SOURCE
[00:44:51]: ▸ > Task :app:compileDebugAidl NO-SOURCE
[00:44:51]: ▸ > Task :app:checkDebugAarMetadata UP-TO-DATE
[00:44:51]: ▸ > Task :app:generateDebugResources UP-TO-DATE
[00:44:52]: ▸ > Task :app:mergeDebugResources UP-TO-DATE
[00:44:52]: ▸ > Task :app:processDebugMainManifest UP-TO-DATE
[00:44:52]: ▸ > Task :app:processDebugManifest UP-TO-DATE
[00:44:52]: ▸ > Task :app:processDebugManifestForPackage UP-TO-DATE
[00:44:54]: ▸ > Task :app:processDebugResources
[00:44:54]: ▸ > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[00:44:54]: ▸ > Task :app:compileDebugSources UP-TO-DATE
[00:44:54]: ▸ > Task :app:mergeDebugAssets UP-TO-DATE
[00:44:54]: ▸ > Task :app:compressDebugAssets UP-TO-DATE
[00:44:55]: ▸ > Task :app:transformClassesWithParanoidForDebug
[00:44:55]: ▸ > Task :app:mergeDebugJavaResource UP-TO-DATE
[00:44:56]: ▸ > Task :app:transformClassesWithRealmTransformerForDebug
[00:44:59]: ▸ > Task :app:dexBuilderDebug
[00:44:59]: ▸ > Task :app:mergeExtDexDebug UP-TO-DATE
[00:44:59]: ▸ > Task :app:mergeLibDexDebug UP-TO-DATE
[00:44:59]: ▸ > Task :app:mergeDebugNativeLibs UP-TO-DATE
[00:44:59]: ▸ > Task :app:stripDebugDebugSymbols UP-TO-DATE
[00:45:00]: ▸ > Task :app:mergeProjectDexDebug
[00:45:02]: ▸ > Task :app:packageDebug
[00:45:02]: ▸ > Task :app:assembleDebug
[00:45:02]: ▸ BUILD SUCCESSFUL in 12s
[00:45:02]: ▸ 80 actionable tasks: 6 executed, 74 up-to-date
[00:45:03]: ------------------------------
[00:45:03]: --- Step: get_version_code ---
[00:45:03]: ------------------------------
[00:45:03]: The get_version_code plugin will use gradle file at (app/build.gradle)!
[00:45:03]: 👍 Version name found: 5
[00:45:03]: ------------------------------
[00:45:03]: --- Step: get_version_code ---
[00:45:03]: ------------------------------
[00:45:03]: The get_version_code plugin will use gradle file at (app/build.gradle)!
[00:45:03]: 👍 Version name found: 1.1.10
[00:45:03]: -------------------
[00:45:03]: --- Step: gmail ---
[00:45:03]: -------------------
+-------------------------------------+--------------------------------------------------------------------------------------------------------------------------+
|                                                                          Lane Context                                                                          |
+-------------------------------------+--------------------------------------------------------------------------------------------------------------------------+
| DEFAULT_PLATFORM                    | android                                                                                                                  |
| PLATFORM_NAME                       | android                                                                                                                  |
| LANE_NAME                           | android distribute_to_firebase                                                                                           |
| GRADLE_BUILD_TYPE                   | Debug                                                                                                                    |
| GRADLE_ALL_APK_OUTPUT_PATHS         | ["/Users/ashrafezouli/Downloads/LPProjects/Marshal-FlyJo/Marshal/app/build/outputs/apk/debug/Fly jo (1.1.10)-debug.apk"] |
| GRADLE_ALL_AAB_OUTPUT_PATHS         | []                                                                                                                       |
| GRADLE_ALL_OUTPUT_JSON_OUTPUT_PATHS | []                                                                                                                       |
| GRADLE_ALL_MAPPING_TXT_OUTPUT_PATHS | []                                                                                                                       |
| GRADLE_APK_OUTPUT_PATH              | /Users/ashrafezouli/Downloads/LPProjects/Marshal-FlyJo/Marshal/app/build/outputs/apk/debug/Fly jo (1.1.10)-debug.apk     |
| VERSION_CODE                        | 1.1.10                                                                                                                   |
+-------------------------------------+--------------------------------------------------------------------------------------------------------------------------+
[00:45:05]: 534-5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbv

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 2    | assembleDebug    | 13          |
| 3    | get_version_code | 0           |
| 4    | get_version_code | 0           |
| 💥   | gmail            | 1           |
+------+------------------+-------------+

[00:45:05]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
bundler: failed to load command: fastlane (/usr/local/lib/ruby/gems/2.7.0/bin/fastlane)
Net::SMTPAuthenticationError: [!] 534-5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbv

  /usr/local/Cellar/ruby/2.7.2/lib/ruby/2.7.0/net/smtp.rb:975:in `check_auth_response'
  /usr/local/Cellar/ruby/2.7.2/lib/ruby/2.7.0/net/smtp.rb:736:in `auth_plain'
  /usr/local/Cellar/ruby/2.7.2/lib/ruby/2.7.0/net/smtp.rb:728:in `authenticate'
  /usr/local/Cellar/ruby/2.7.2/lib/ruby/2.7.0/net/smtp.rb:565:in `do_start'
  /usr/local/Cellar/ruby/2.7.2/lib/ruby/2.7.0/net/smtp.rb:518:in `start'
  /usr/local/lib/ruby/gems/2.7.0/gems/mail-2.6.6/lib/mail/network/delivery_methods/smtp.rb:111:in `deliver!'
  /usr/local/lib/ruby/gems/2.7.0/gems/mail-2.6.6/lib/mail/message.rb:2149:in `do_delivery'
  /usr/local/lib/ruby/gems/2.7.0/gems/mail-2.6.6/lib/mail/message.rb:239:in `deliver'
  /usr/local/lib/ruby/gems/2.7.0/gems/mail-2.6.6/lib/mail/mail.rb:141:in `deliver'
  /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-plugin-gmail-0.1.2/lib/fastlane/plugin/gmail/actions/gmail_action.rb:26:in `run'
  /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.167.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
  /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.167.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
  /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.167.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
  /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.167.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
  /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.167.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
  /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.167.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.167.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:134:in `send_email'
  Fastfile:48:in `block (2 levels) in parsing_binding'
  /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.167.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.167.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.167.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.167.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.167.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
  /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.167.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.167.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.167.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.167.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
  /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.167.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.167.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.167.0/bin/fastlane:23:in `<top (required)>'
  /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:23:in `load'
  /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:23:in `<top (required)>'

**Comment by max-ott** [comment] 2020-11-17 11:48
Duplicate of #17620

**Closed by max-ott** 2020-11-17 11:48 UTC
