### ISSUE TITLE
Uploading 30 sec video promotion file

### ISSUE THREAD

**Issue by prolog3001** [fastlane/fastlane#9871] opened 2017-07-27 08:04 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

**Comment by prolog3001** [comment] 2017-07-27 08:06
The App store enables to upload a short video clip together with the screenshots.
The problem is that uploading can be done only via Safari...
Is there any option to upload this promotion clip with fastlane?
Thank you.

**Comment by mpirri** [comment] 2017-07-27 14:58
While this functionality has been offered by _fastlane_ in the past (via the `spaceship` `upload_trailer` method), it is currently not working properly with the latest version if iTC.

We are working on a fix at the moment - you can track the progress of this fix here: https://github.com/fastlane/fastlane/issues/9660

Thanks for writing in, and I'm sorry I don't have better news for you!  🚀

**Comment by prolog3001** [comment] 2017-07-28 14:24
Thank you for this information.
I will keep tracking on #9660 hopefully will be resolved soon...

**Comment by ohayon** [comment] 2017-08-01 14:53
Hey @prolog3001 if you don't mind, I am going to close this issue as a dupe of #9660 and we are going to try to get a fix out shortly! 🐙

**Closed by ohayon** 2017-08-01 14:53 UTC
