### ISSUE TITLE
xcodebuild: error: option '-configuration' may only be provided once

### ISSUE THREAD

**Issue by yukiasai** [fastlane/fastlane#7106] opened 2016-11-21 05:31 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

The same error occurs in **gym**, **scan** and **snapshot**.

✅ Issue Description ✅

#### gym

```
+----------------------+-----------------------------+
|               Summary for gym 1.12.0               |
+----------------------+-----------------------------+
| configuration        | Release                     |
| project              | ./MyApp.xcodeproj           |
| scheme               | MyApp                       |
| destination          | generic/platform=iOS        |
| output_name          | MyApp                       |
| clean                | false                       |
| output_directory     | .                           |
| silent               | false                       |
| use_legacy_build_api | false                       |
| buildlog_path        | ~/Library/Logs/gym          |
| xcode_path           | /Applications/Xcode-8.1.app |
+----------------------+-----------------------------+

[13:49:44]: $ set -o pipefail && xcodebuild -scheme MyApp -project ./MyApp.xcodeproj -configuration Release -configuration 'Release' -destination 'generic/platform=iOS' -archivePath /Users/asai/Library/Developer/Xcode/Archives/2016-11-21/MyApp\ 2016-11-21\ 13.49.44.xcarchive archive | tee /Users/asai/Library/Logs/gym/MyApp-MyApp.log | xcpretty
[13:49:44]: ▸ xcodebuild: error: option '-configuration' may only be provided once
```

#### scan

```
+-----------------------+--------------------------------------------------------------------------+
|                                     Summary for scan 0.14.1                                      |
+-----------------------+--------------------------------------------------------------------------+
| configuration         | Debug                                                                    |
| project               | ./MyApp.xcodeproj                                                        |
| scheme                | MyApp                                                                    |
| derived_data_path     | /Users/asai/Library/Developer/Xcode/DerivedData/MyApp-grxcojpsdpspsaf... |
| clean                 | false                                                                    |
| code_coverage         | false                                                                    |
| address_sanitizer     | false                                                                    |
| skip_build            | false                                                                    |
| output_directory      | ./fastlane/test_output                                                   |
| output_types          | html,junit                                                               |
| buildlog_path         | ~/Library/Logs/scan                                                      |
| open_report           | false                                                                    |
| skip_slack            | false                                                                    |
| slack_only_on_failure | false                                                                    |
| use_clang_report_name | false                                                                    |
| fail_build            | true                                                                     |
| xcode_path            | /Applications/Xcode-8.1.app                                              |
+-----------------------+--------------------------------------------------------------------------+

[14:15:54]: $ set -o pipefail && env NSUnbufferedIO=YES xcodebuild -scheme MyApp -project ./MyApp.xcodeproj -configuration Debug -configuration 'Debug' -destination 'platform=iOS Simulator,id=099E8FA1-0830-4F2D-A27D-83FE4BF7AF25' -derivedDataPath '/Users/asai/Library/Developer/Xcode/DerivedData/MyApp-grxcojpsdpspsafugmesrdyptsue' build test | tee '/Users/asai/Library/Logs/scan/MyApp-MyApp.log' | xcpretty 
[14:15:54]: ▸ Loading...
[14:15:54]: ▸ xcodebuild: error: option '-configuration' may only be provided once
```

#### snapshot

```
+----------------------------+---------------------------------------------------------------------+
|                                   Summary for snapshot 1.16.3                                    |
+----------------------------+---------------------------------------------------------------------+
| configuration              | Debug                                                               |
| project                    | ./MyApp.xcodeproj                                                   |
| scheme                     | MyApp                                                               |
| devices                    | ["iPhone 5", "iPhone 6", "iPhone 6 Plus", "iPhone 7", "iPhone 7 ... |
| output_directory           | /Users/asai/Desktop/MyApp/fastlane/screenshots                      |
| languages                  | ["en-US"]                                                           |
| launch_arguments           | [""]                                                                |
| skip_open_summary          | false                                                               |
| clear_previous_screenshots | false                                                               |
| reinstall_app              | false                                                               |
| erase_simulator            | false                                                               |
| localize_simulator         | false                                                               |
| app_identifier             | com.yukiasai.myapp                                                  |
| buildlog_path              | ~/Library/Logs/snapshot                                             |
| clean                      | false                                                               |
| number_of_retries          | 1                                                                   |
| stop_after_first_error     | false                                                               |
| xcode_path                 | /Applications/Xcode-8.1.app                                         |
+----------------------------+---------------------------------------------------------------------+

...

[13:52:35]: ------------------------
[13:52:35]: --- iPhone 5 - en-US ---
[13:52:35]: ------------------------
[13:52:35]: $ set -o pipefail && xcodebuild -scheme MyApp -project ./MyApp.xcodeproj -configuration Debug -configuration 'Debug' -derivedDataPath '/var/folders/c2/g3241qmj6271x67j24qqjwjc0000gp/T/snapshot_derived20161121-81050-19rg3cu' -destination 'platform=iOS Simulator,id=48E6DB8E-6D6C-48E3-BD32-AE8908BF3AAA,OS=10.1' FASTLANE_SNAPSHOT=YES build test | tee /Users/asai/Library/Logs/snapshot/MyApp-MyApp.log | xcpretty 
[13:52:35]: ▸ Loading...
[13:52:35]: ▸ xcodebuild: error: option '-configuration' may only be provided once
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                                 |
| ------------------- | ----------------------------------------------------- |
| OS                  | 10.11.6                                               |
| Ruby                | 2.2.3                                                 |
| Bundler?            | true                                                  |
| Git                 | git version 2.9.3 (Apple Git-75)                      |
| Installation Source | ~/Desktop/MyApp/vendor/bundle/ruby/2.2.0/bin/fastlane |
| Host                | Mac OS X 10.11.6 (15G1108)                            |
| Ruby Lib Dir        | ~/.rbenv/versions/2.2.3/lib                           |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                           |
| Is contained        | false                                                 |
| Xcode Path          | /Applications/Xcode-8.1.app/Contents/Developer/       |
| Xcode Version       | 8.1                                                   |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | ja_JP.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "1.110.0"

default_platform :ios

platform :ios do
  desc "Build"
  lane :build do
    gym(
      configuration: "Release",
    )
  end

  desc "Test"
  lane :test do
    scan(
      configuration: "Debug",
    )
  end

  desc "Snapshot"
  lane :snap do
    snapshot(
      configuration: "Debug",
    )
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.yukiasai.myapp" # The bundle identifier of your app
apple_id "yukiasai@gmail.com" # Your Apple email address

team_id "NRUDQDRGJZ"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| fastlane_core       | 0.56.0  | ✅ Up-To-Date  |
| spaceship           | 0.37.0  | ✅ Up-To-Date  |
| cert                | 1.4.4   | ✅ Up-To-Date  |
| deliver             | 1.15.1  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| gym                 | 1.12.0  | ✅ Up-To-Date  |
| sigh                | 1.11.2  | ✅ Up-To-Date  |
| match               | 0.11.0  | ✅ Up-To-Date  |
| pem                 | 1.4.0   | ✅ Up-To-Date  |
| pilot               | 1.12.1  | ✅ Up-To-Date  |
| produce             | 1.3.0   | ✅ Up-To-Date  |
| scan                | 0.14.1  | ✅ Up-To-Date  |
| screengrab          | 0.5.6   | ✅ Up-To-Date  |
| snapshot            | 1.16.3  | ✅ Up-To-Date  |
| supply              | 0.7.1   | ✅ Up-To-Date  |
| fastlane            | 1.110.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| bundler                   | 1.13.6       |
| CFPropertyList            | 2.3.3        |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| minitest                  | 5.9.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| addressable               | 2.3.8        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| security                  | 0.1.3        |
| credentials_manager       | 0.16.2       |
| excon                     | 0.54.0       |
| gh_inspector              | 1.0.2        |
| multi_json                | 1.12.1       |
| plist                     | 3.2.0        |
| rubyzip                   | 1.1.7        |
| terminal-table            | 1.4.5        |
| fastlane_core             | 0.56.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.10.1       |
| fastimage                 | 1.6.8        |
| multi_xml                 | 0.5.5        |
| claide                    | 1.0.1        |
| dotenv                    | 2.1.1        |
| mini_magick               | 4.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| krausefx-shenzhen         | 0.14.11      |
| slack-notifier            | 1.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.20       |
| terminal-notifier         | 1.7.1        |
| word_wrap                 | 1.0.0        |
| xcode-install             | 2.0.9        |
| nanaimo                   | 0.2.2        |
| xcodeproj                 | 1.4.1        |
</details>

*generated on:* **2016-11-21**
</details>

### Idea

I think that it is caused by change of https://github.com/fastlane/fastlane/pull/6542.

* gym #7108 
* scan #7109 
* snapshot #7107 

thank you.

**Comment by TKBurner** [comment] 2016-11-21 16:53
@yukiasai Thanks again for contributing! We'll work with you on the PRs soon! 👍

**Comment by mfurtak** [comment] 2016-11-21 18:29
Reproduced locally. :+1: I'll reopen this until we merge and ship the fixes.

**Comment by mfurtak** [comment] 2016-11-21 18:50
Your fixes have been merged, and will go out in the next _snapshot_, _scan_, and _gym_ releases. Thanks very much! 🎉

**Comment by fabioknoedtbcgdv** [comment] 2016-11-21 21:15
@mfurtak any guess when is going to be the next release? this bug is currently breaking my CI & CD.
any advices how to avoid that for now? reverting any of the versions to an earlier one? gym, fastlane_core, scan? Thanks!

**Comment by mfurtak** [comment] 2016-11-21 21:47
Hi @fabioknoedtbcgdv - good news!

[_snapshot_ 1.16.4](https://github.com/fastlane/fastlane/releases/tag/snapshot/1.16.4), [_scan_ 0.14.2](https://github.com/fastlane/fastlane/releases/tag/scan/0.14.2), and [_gym_ 1.12.1](https://github.com/fastlane/fastlane/releases/tag/gym/1.12.1) have all been released! 🚀 

Please get those updates, and let us know how things look 👍

**Closed by mfurtak** 2016-11-21 21:47 UTC

**Comment by fabioknoedtbcgdv** [comment] 2016-11-21 22:23
@mfurtak yes, it does work for me (gym)!

**Comment by wolesolana** [comment] 2016-11-23 18:39
Hi @yukiasai @mfurtak when I run the latest fastlane build with `xcov`, the following error is generated: 

```fastlane finished with errors

[!] Could not find option for key :configuration. Available keys: workspace, project, scheme, source_directory, derived_data_path, output_directory, html_report, markdown_report, json_report, minimum_coverage_percentage, ignore_file_path, include_test_targets, slack_url, slack_channel, skip_slack, exclude_targets, include_targets```

Could this be related to this bug fix?

**Comment by mfurtak** [comment] 2016-11-24 01:42
Hi @wolesolana - it looks like this may have already been discussed and resolved over on `xcov`'s side. 👍 

https://github.com/nakiostudio/xcov/issues/54

**Comment by wolesolana** [comment] 2016-11-24 20:50
Thanks @mfurtak  I updated `xcov` and it's working fine now.
