### ISSUE TITLE
[Regression] Broken pipe when uploading binaries

### ISSUE THREAD

**Issue by allenhsu** [fastlane/fastlane#13571] opened 2018-10-22 11:08 UTC
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information
- Breaking version: [e.g. `2.107.0`]
- Last working version: [e.g. `2.105.2`]

### Regression Description
We're using fastlane to deploy iOS apps on CI server. We have proxy set up on CI server, I'm not sure about the root cause but we're not able to upload binaries with DAV option on, via this proxy. I noticed that in fastlane 2.106.0 (https://github.com/fastlane/fastlane/pull/13404) DAV is by default turned on, it makes our CI server not able to upload binaries. Is it possible to revert the default behavior so it's consistent with previous versions?

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[16:42:01]: [31m[Transporter Error Output]: An error occurred while uploading the file 225e0ae8c5f64b696b98d0b557310b9f1696be80738b9d20e6954ee4da9bf704.ipa.
[0m
[16:42:01]: [31m[Transporter Error Output]: An exception has occurred: Broken pipe (Write failed)
[0m
[16:42:01]: [31m[Transporter Error Output]: Failed to upload file: /tmp/638021335.itmsp/225e0ae8c5f64b696b98d0b557310b9f1696be80738b9d20e6954ee4da9bf704.ipa
[0m
[16:42:04]: [31mTransporter transfer failed.[0m
[16:42:04]: 
[16:42:04]: [31mAn error occurred while uploading the file 225e0ae8c5f64b696b98d0b557310b9f1696be80738b9d20e6954ee4da9bf704.ipa.
An exception has occurred: Broken pipe (Write failed)
Failed to upload file: /tmp/638021335.itmsp/225e0ae8c5f64b696b98d0b557310b9f1696be80738b9d20e6954ee4da9bf704.ipa
[0m
[16:42:04]: [33m[iTMSTransporter] [2018-10-22 16:42:04 CST] <main> DBG-X:   parameter EnableJWTForAllCalls = false
[0m
[16:42:04]: [33m[iTMSTransporter] [2018-10-22 16:42:04 CST] <main> DBG-X:   parameter SessionExpiration = 2018-10-26T08:42:03.177Z
[0m
[16:42:04]: [33m[iTMSTransporter] [2018-10-22 16:42:04 CST] <main> DBG-X:   parameter Success = true
[0m
[16:42:04]: [33m[iTMSTransporter] [2018-10-22 16:42:04 CST] <main> DBG-X:   parameter StreamingSettings = {LogStreamingEnabled=true, MultipartUploadsEnabled=true, AssetDescriptionStreamingEnabled=false}
[0m
[16:42:04]: [33m[iTMSTransporter] 
[0m
[16:42:04]: [33m[iTMSTransporter] 
[0m
[16:42:04]: [33m[iTMSTransporter] 
[0m
[16:42:04]: [33m[iTMSTransporter] Package Summary:
[0m
[16:42:04]: [33m[iTMSTransporter]  
[0m
[16:42:04]: [33m[iTMSTransporter] 1 package(s) were not uploaded because they had problems:
[0m
[16:42:04]: [33m[iTMSTransporter] 	/tmp/638021335.itmsp - Error Messages:
[0m
[16:42:04]: [33m[iTMSTransporter] 		     An error occurred while uploading the file 225e0ae8c5f64b696b98d0b557310b9f1696be80738b9d20e6954ee4da9bf704.ipa.
[0m
[16:42:04]: [33m[iTMSTransporter] 		An exception has occurred: Broken pipe (Write failed)
[0m
[16:42:04]: [33m[iTMSTransporter] 		  Failed to upload file: /tmp/638021335.itmsp/225e0ae8c5f64b696b98d0b557310b9f1696be80738b9d20e6954ee4da9bf704.ipa
[0m
[16:42:04]: [33m[iTMSTransporter] [2018-10-22 16:42:04 CST] <main> DBG-X: Returning 1
[0m
[16:42:04]: iTunes Transporter output above ^
[16:42:04]: [31mAn error occurred while uploading the file 225e0ae8c5f64b696b98d0b557310b9f1696be80738b9d20e6954ee4da9bf704.ipa.
An exception has occurred: Broken pipe (Write failed)
Failed to upload file: /tmp/638021335.itmsp/225e0ae8c5f64b696b98d0b557310b9f1696be80738b9d20e6954ee4da9bf704.ipa
Return status of iTunes Transporter was 1: An error occurred while uploading the file 225e0ae8c5f64b696b98d0b557310b9f1696be80738b9d20e6954ee4da9bf704.ipa.
\nAn exception has occurred: Broken pipe (Write failed)
\nFailed to upload file: /tmp/638021335.itmsp/225e0ae8c5f64b696b98d0b557310b9f1696be80738b9d20e6954ee4da9bf704.ipa
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.[0m</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14                                       |
| Ruby                        | 2.4.4                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.19.1                          |
| Installation Source         | ~/.rbenv/versions/2.4.4/bin/fastlane        |
| Host                        | Mac OS X 10.14 (18A391)                     |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.4/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2o  27 Mar 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.0                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.107.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| bundler                   | 1.16.2       |
| io-console                | 0.4.6        |
| CFPropertyList            | 2.3.6        |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.10       |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.3        |
| awesome_print             | 1.8.0        |
| babosa                    | 1.0.2        |
| builder                   | 3.2.3        |
| clipboard                 | 1.1.2        |
| gherkin                   | 4.1.3        |
| cucumber-core             | 1.5.0        |
| cucumber-wire             | 0.0.1        |
| diff-lcs                  | 1.3          |
| multi_json                | 1.13.1       |
| multi_test                | 0.1.2        |
| cucumber                  | 2.99.0       |
| edn                       | 1.1.1        |
| geocoder                  | 1.4.9        |
| httpclient                | 2.8.3        |
| json                      | 1.8.6        |
| command_runner_ng         | 0.1.4        |
| thor                      | 0.20.0       |
| run_loop                  | 2.7.1        |
| slowhandcuke              | 0.0.3        |
| calabash-cucumber         | 0.21.5       |
| claide                    | 1.0.2        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.5.3        |
| cocoapods-deintegrate     | 1.0.2        |
| cocoapods-downloader      | 1.2.1        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.5        |
| ruby-macho                | 1.2.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| cocoapods                 | 1.5.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.5.0        |
| emoji_regex               | 0.1.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.3       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.4        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.6        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| xcode-install             | 2.4.1        |
</details>

*generated on:* **2018-10-22**
</details>

**Comment by joshdholtz** [comment] 2018-10-22 18:34
Duplicate of #13572

**Comment by joshdholtz** [comment] 2018-10-22 18:34
Duplicate of #13572

**Closed by joshdholtz** 2018-10-22 18:34 UTC
Labels: status: regression
