### ISSUE TITLE
Match could not find App ID

### ISSUE THREAD

**Issue by EvgeniyGushchin** [fastlane/fastlane#11243] opened 2017-12-16 07:20 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm trying to generate certificates for my app using `match` but `match` doesn't able to find App ID
(see output below). 
I have tried to register App ID manually and using `produce` command. Both times `match` failed to find App ID
##### Complete output when running fastlane, including the stack trace and command used

bundle exec fastlane match appstore

+-----------------------+----------------+
|        Summary for match 2.69.3        |
+-----------------------+----------------+
| type                  | appstore       |
| git_branch            | master         |
| keychain_name         | login.keychain |
| readonly              | false          |
| verbose               | false          |
| force                 | false          |
| skip_confirmation     | false          |
| shallow_clone         | false          |
| clone_branch_directly | false          |
| force_for_new_devices | false          |
| skip_docs             | false          |
| platform              | ios            |
+-----------------------+----------------+

[13:00:00]: To not be asked about this value, you can specify it using 'git_url'
[13:00:00]: URL to the git repo containing all the certificates: git@github.com:myapp/ios-certificates.git
[13:00:11]: Cloning remote git repo...
[13:00:11]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[13:00:18]: 🔓  Successfully decrypted certificates repo
[13:00:18]: To not be asked about this value, you can specify it using 'username'
[13:00:18]: Your Apple ID Username: 
[13:00:37]: Verifying that the certificate and profile are still valid on the Dev Portal...
[13:00:44]: To not be asked about this value, you can specify it using 'app_identifier'
[13:00:44]: The bundle identifier(s) of your app (comma-separated): com.bsl.bsl
[13:00:50]: 
[13:00:50]: ==========================================
[13:00:50]: Could not find App ID with bundle identifier '["com.bsl.bsl"]'
[13:00:50]: You can easily generate a new App ID on the Developer Portal using 'produce':
[13:00:50]: 
[13:00:50]: fastlane produce -u myuser@com.br -a ["com.bsl.bsl"] --skip_itc
[13:00:50]: 
[13:00:50]: You will be asked for any missing information, like the full name of your app
[13:00:50]: If the app should also be created on iTunes Connect, remove the --skip_itc from the command above
[13:00:50]: ==========================================
[13:00:50]: 
[13:00:50]: An app with that bundle ID needs to exist in order to create a provisioning profile for it
[13:00:50]: ================================================================
[13:00:51]: Available apps:
- br.com.xkeysti.BSL (BSL)
- com.bsl.bsl (BSL EAD)
- bsl.tmp (bsl-tmp)
- br.com.xkeysti.CEBRAC (Xcode iOS App ID br com xkeysti CEBRAC)
- * (Xcode iOS Wildcard App ID)
[13:00:51]: Make sure to run `fastlane match` with the same user and team every time.

[!] Couldn't find bundle identifier '["com.bsl.bsl"]' for the user 'myuser@.com.br']

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.1                                     |
| Ruby                        | 2.2.2                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.8.1                           |
| Installation Source         | ~/.rvm/gems/ruby-2.3.0/bin/fastlane         |
| Host                        | Mac OS X 10.13.1 (17B1003)                  |
| Ruby Lib Dir                | ~/.rbenv/versions/2.2.2/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2e 3 Dec 2015                   |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.69.3  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

**Comment by EvgeniyGushchin** [comment] 2017-12-16 08:14
Version of Fastlane 2.68.2 works fine.

I've added additional logs to `app.rb` to method `def find(bundle_id, mac: false)` and have found that `bundle_id` contains additional symbols.
```
  app.bundle_id  is "com.bsl.bsl"
  parameter bundle_id is "[\"com.bsl.bsl\"]"
```

**Comment by GalRyalto** [comment] 2017-12-18 12:10
I had the same issue, my bundle id was generated the same way and oust;t be found on the developer bundle.  

Try to add app_identifier to the match command: 
 fastlane match  --app_identifier com.****

It worked for us

**Comment by mattmanske** [comment] 2017-12-29 22:10
Having the same issue on v 2.71.0 - dropping to v 2.68.2 worked though

**Comment by KrauseFx** [comment] 2017-12-30 17:54
Thanks everyone for reporting, I'd love to resolve this issue for you, but nobody shared their configuration file with me 😢 

Related commits it seems:
- https://github.com/fastlane/fastlane/commit/36b56785a6bebfa54ee727ac170228f0eb4ce24d
- https://github.com/fastlane/fastlane/commit/0151fd557bd7e8d48f7bbdbc8afe747d8dc07e55

Related issue
- https://github.com/fastlane/fastlane/issues/11324

**Comment by KrauseFx** [comment] 2017-12-30 17:55
I'm happy to work on and ship a fix for this, but I do need a way to reproduce the problem. Thanks :)

**Comment by danstepanov** [comment] 2017-12-30 23:03
@mattmanske How did you drop to v 2.68.2? I tried using `sudo gem install fastlane --version 2.68.2` but upon running `fastlane --version` afterwards, it still says 2.71.1 :( 

@KrauseFx Which config file are you referring to? My project doesn't seem to have anything like a fastlane.config or anything like that.

**Comment by danstepanov** [comment] 2017-12-30 23:05
Steps to recreate on my end, specific to my project are to run `fastlane match`, specify my git url that contains my certificates, pick my individual dev account, pass in the bundle id for my app and then this error appears.

**Comment by danstepanov** [comment] 2017-12-30 23:09
Figure out how to downgrade fastlane `sudo gem uninstall fastlane` and then just pick the version to uninstall, in this case 2.71.1

**Comment by KrauseFx** [comment] 2017-12-31 15:36
@danstepanov Where do you define the app identifier? Do you have a Fastfile, Appfile or Matchfile? If none of them, do you use an environment variable? If not, do you let _fastlane_ automatically detect the bundle identifier?

**Comment by radko93** [comment] 2018-01-03 16:08
I have a similar issue with fastlane `2.72.0`. I tried passing one or multiple app identifiers. Seems that fastlane has a problem with parsing app identifiers (I use the CLI interface to pass indentifiers). All I get is:
> Could not find App ID with bundle identifier '["com.xx.ZZ.YYY"'

**Comment by taquitos** [comment] 2018-01-03 18:23
@radko93, can you confirm how you're calling match to get this error?

is it like: `fastlane match development -a ["bundle.id.1", "bundle.id.2"]` ?

**Comment by KrauseFx** [comment] 2018-01-03 22:02
Thanks everyone, please **do** share the exact notation of how you call _match_, how do you pass the app identifier? Otherwise we can't reproduce the problem... @taquitos' PR should fix things, but we can't say for sure without a reproducible example

**Comment by danstepanov** [comment] 2018-01-03 22:04
I just call `fastlane match` and use a github repo with my certificates, then i supply the app identifier manually.

**Comment by KrauseFx** [comment] 2018-01-03 22:06
@danstepanov

> then i supply the app identifier manually.

There are 7 ways in fastlane to pass a parameter. Can you tell us more how? :) Ideally the complete code call

**Comment by danstepanov** [comment] 2018-01-03 23:26
@KrauseFx 

```
➜  mobile-application git:(develop) fastlane match
Ignoring bcrypt-3.1.11 because its extensions are not built.  Try: gem pristine bcrypt --version 3.1.11
Ignoring bindex-0.5.0 because its extensions are not built.  Try: gem pristine bindex --version 0.5.0
Ignoring byebug-9.0.6 because its extensions are not built.  Try: gem pristine byebug --version 9.0.6
Ignoring ffi-1.9.18 because its extensions are not built.  Try: gem pristine ffi --version 1.9.18
Ignoring nio4r-2.0.0 because its extensions are not built.  Try: gem pristine nio4r --version 2.0.0
Ignoring nokogiri-1.7.1 because its extensions are not built.  Try: gem pristine nokogiri --version 1.7.1
Ignoring pg-0.20.0 because its extensions are not built.  Try: gem pristine pg --version 0.20.0
Ignoring puma-3.8.2 because its extensions are not built.  Try: gem pristine puma --version 3.8.2
Ignoring sqlite3-1.3.13 because its extensions are not built.  Try: gem pristine sqlite3 --version 1.3.13
Ignoring websocket-driver-0.6.5 because its extensions are not built.  Try: gem pristine websocket-driver --version 0.6.5
[18:22:20]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile

+-----------------------+------------------------+
|            Summary for match 2.68.2            |
+-----------------------+------------------------+
| git_branch            | master                 |
| type                  | development            |
| username              | danhstepanov@gmail.com |
| keychain_name         | login.keychain         |
| readonly              | false                  |
| verbose               | false                  |
| force                 | false                  |
| skip_confirmation     | false                  |
| shallow_clone         | false                  |
| clone_branch_directly | false                  |
| force_for_new_devices | false                  |
| skip_docs             | false                  |
| platform              | ios                    |
+-----------------------+------------------------+

[18:22:23]: To not be asked about this value, you can specify it using 'git_url'
[18:22:23]: URL to the git repo containing all the certificates: [MY_CERTIFICATES_GITHUB_REPO_URL]
[18:22:38]: Cloning remote git repo...
[18:22:38]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[18:22:39]: 🔓  Successfully decrypted certificates repo
[18:22:39]: Verifying that the certificate and profile are still valid on the Dev Portal...
Multiple teams found on the Developer Portal, please enter the number of the team you want to use:
1) TEAMID1 "Team 1" (Company/Organization)
2) TEAMID2 "Team 2" (Company/Organization)
3) MYID "Daniel Stepanov" (Individual)
4) TEAMID3 "Team 3" (In-House)
5) TEAMID4 "Team 4 (Company/Organization)
3
[18:22:47]: To not be asked about this value, you can specify it using 'app_identifier'
[18:22:47]: The bundle identifier(s) of your app (comma-separated): [I_TYPE_IN_MY_APP_BUNDLE_ID_HERE]
```

**Comment by taquitos** [comment] 2018-01-03 23:31
Awesome, thank you @danstepanov

**Comment by KrauseFx** [comment] 2018-01-04 12:08
Ah alright, so this is a different error then, when you get asked for the missing value, taking a look now

**Comment by KrauseFx** [comment] 2018-01-04 12:19
Alright, thanks everyone, I was able to reproduce the issue, and provide a fix for it: https://github.com/fastlane/fastlane/pull/11423

**Comment by KrauseFx** [comment] 2018-01-04 12:19
This will be live with the next releas

**Closed** 2018-01-04 20:58 UTC

**Comment by danstepanov** [comment] 2018-01-04 21:05
Thanks @KrauseFx and @taquitos!
