### ISSUE TITLE
Deliver: Phased release (phased_release) does not seem to work

### ISSUE THREAD

**Issue by strongbox-mark** [fastlane/fastlane#16502] opened 2020-05-23 16:05 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Setting the phased_release parameter of deliver does not set the build to phased release in iTunes Connect.

##### Command executed
No error as such, just doesn't set the build to phased release. Sample from the script I'm running which uploads fine:

```
bundle exec fastlane ios both
```

Key deliver call here:

```
    deliver(metadata_path: "fastlane/metadata-ios-alternative",
            skip_metadata: true,
         skip_screenshots: true,
                      ipa: "build/ios-alternative/#{version}/#{build}/ios-alternative.ipa",
           app_identifier: "my.app.id.pro",
        submit_for_review: false,
       reject_if_possible: true,
           phased_release: true)
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
[17:31:43]: ---------------------
[17:31:43]: --- Step: deliver ---
[17:31:43]: ---------------------
[17:31:43]: Successfully loaded '/Users/username/dev/myapp/fastlane/Deliverfile' 📄
[17:31:43]: No values defined in './fastlane/Deliverfile'
[17:31:43]: Login to App Store Connect (me@email.com)
[17:31:45]: Login successful

+--------------------------------------+----------------------------------------------------------------------------+
|                                              deliver 2.148.1 Summary                                              |
+--------------------------------------+----------------------------------------------------------------------------+
| metadata_path                        | fastlane/metadata-ios-alternative                                          |
| skip_metadata                        | true                                                                       |
| skip_screenshots                     | true                                                                       |
| ipa                                  | /Users/username/dev/app/build/ios-alternative/1.48.6/2911/ios-alternative.ipa |
| app_identifier                       | my.app.id.pro                                              |
| submit_for_review                    | false                                                                      |
| reject_if_possible                   | true                                                                       |
| phased_release                       | true                                                                       |
| screenshots_path                     | ./fastlane/screenshots                                                     |
| app_version                          | 1.48.6                                                                     |
| username                             | me@email.com                                                              |
| platform                             | ios                                                                        |
| edit_live                            | false                                                                      |
| use_live_version                     | false                                                                      |
| skip_binary_upload                   | false                                                                      |
| skip_app_version_update              | false                                                                      |
| force                                | false                                                                      |
| overwrite_screenshots                | false                                                                      |
| automatic_release                    | false                                                                      |
| reset_ratings                        | false                                                                      |
| team_id                              | my-team-id                                                                |
| dev_portal_team_id                   | my-portal-team-id                                                          |
| run_precheck_before_submit           | true                                                                       |
| precheck_default_rule_level          | warn                                                                       |
| individual_metadata_items            | []                                                                         |
| ignore_language_directory_validation | false                                                                      |
| precheck_include_in_app_purchases    | true                                                                       |
+--------------------------------------+----------------------------------------------------------------------------+

[17:31:46]: Making sure the latest version on App Store Connect matches '1.48.6' from the ipa file...
[17:31:48]: '1.48.6' is the latest version on App Store Connect
[17:31:51]: Uploading app icon...
[17:31:56]: Uploading binary to App Store Connect
[17:31:57]: Going to upload updated app to App Store Connect
[17:31:57]: This might take a few minutes. Please don't interrupt the script.

[17:59:23]: iTunes Transporter successfully finished its job
[17:59:23]: ------------------------------------------------------------------------------------------------------------------
[17:59:23]: --- Successfully uploaded package to App Store Connect. It might take a few minutes until it's visible online. ---
[17:59:23]: ------------------------------------------------------------------------------------------------------------------
[17:59:23]: Finished the upload to App Store Connect
[17:59:25]: Running precheck before submitting to review, if you'd like to disable this check you can set run_precheck_before_submit to false
[17:59:25]: Running precheck 👮‍♀️ 👮

+--------------------------+-------------------------------+
|               Summary for precheck 2.148.1               |
+--------------------------+-------------------------------+
| default_rule_level       | warn                          |
| include_in_app_purchases | true                          |
| app_identifier           | my.app.id.pro |
| username                 | me@email.com           |
| team_id                  | my-team-id                      |
+--------------------------+-------------------------------+

[17:59:25]: Checking app for precheck rule violations
[17:59:34]: Reading in-app purchases. If you have a lot, this might take a while
[17:59:34]: You can disable IAP checking by setting the `include_in_app_purchases` flag to `false`
[17:59:35]: Done reading in-app purchases
[17:59:36]: ✅  Passed: No negative  sentiment
[17:59:36]: ✅  Passed: No placeholder text
[17:59:36]: ✅  Passed: No mentioning  competitors
[17:59:36]: ✅  Passed: No future functionality promises
[17:59:36]: ✅  Passed: No words indicating test content
[17:59:36]: ✅  Passed: No curse words
[17:59:36]: ✅  Passed: No words indicating your IAP is free
[17:59:36]: ✅  Passed: Incorrect, or missing copyright date
[17:59:37]: ✅  Passed: No broken urls
[17:59:37]: precheck 👮‍♀️ 👮  finished without detecting any potential problems 🛫
[17:59:37]: Cruising back to lane 'ios both' 🚘

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | default_platform           | 0           |
| 2    | prompt                     | 4           |
| 3    | increment_build_number     | 0           |
| 4    | increment_version_number   | 0           |
| 5    | Switch to ios regular lane | 0           |
| 6    | get_version_number         | 0           |
| 7    | get_build_number           | 0           |
| 8    | build_app                  | 153         |
| 9    | set_changelog              | 10          |
| 10   | deliver                    | 1423        |
| 11   | Switch to ios family lane  | 0           |
| 12   | get_version_number         | 0           |
| 13   | get_build_number           | 0           |
| 14   | build_app                  | 164         |
| 15   | set_changelog              | 7           |
| 16   | deliver                    | 1673        |
+------+----------------------------+-------------+

[17:59:37]: fastlane.tools just saved you 57 minutes! 🎉
  </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.4                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.2 (Apple Git-127)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.4 (19E287)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.4.1                                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# - Download Metadata
# fastlane deliver download_metadata --metadata_path fastlane/metadata-ios --app_identifier my.app.id --app_version 1.48.1
# fastlane deliver download_metadata --metadata_path fastlane/metadata-mac --app_identifier my.app.id.mac --app_version 1.13.10 --platform=osx

default_platform(:ios)

platform :mac do
    desc "Push a new release build to the App Store"

    lane :both do
        ver = prompt(text: "Version: ")
        increment_build_number(xcodeproj: "mac/mac.xcodeproj")
        increment_version_number(version_number: "#{ver}", xcodeproj: "mac/mac.xcodeproj")

        regular
        alternative
    end

  lane :regular do
    version = get_version_number(xcodeproj: "mac/mac.xcodeproj", target: "MyAppName")
    build = get_build_number(xcodeproj: "mac/mac.xcodeproj")
    
    build_app(workspace: "MyAppName.xcworkspace",
                 scheme: "mac",
       output_directory: "build/mac/#{version}/#{build}")

    deliver(metadata_path: "fastlane/metadata-mac",
            skip_metadata: true,
         skip_screenshots: true,
                      pkg: "build/mac/#{version}/#{build}/MyAppName.pkg",
           app_identifier: "my.app.id.mac",
        submit_for_review: false,
           phased_release: true,
       reject_if_possible: true,
        run_precheck_before_submit: false,
        precheck_include_in_app_purchases: false )
  end

  lane :alternative do
    version = get_version_number(xcodeproj: "mac/mac.xcodeproj", target: "MyAppName-Alternative")
    build = get_build_number(xcodeproj: "mac/mac.xcodeproj")
    
    build_app(workspace: "MyAppName.xcworkspace",
                 scheme: "mac-Alternative",
       output_directory: "build/mac-alternative/#{version}/#{build}")

    deliver(metadata_path: "fastlane/metadata-mac",
            skip_metadata: true,
         skip_screenshots: true,
                      pkg: "build/mac-alternative/#{version}/#{build}/MyAppName.pkg",
           app_identifier: "my.app.id.mac.pro",
        submit_for_review: false,
           phased_release: true,
       reject_if_possible: true,
        run_precheck_before_submit: false,
        precheck_include_in_app_purchases: false )
  end
end

platform :ios do
  desc "Push a new release build to the App Store"
 
  lane :both do
    ver = prompt(text: "Version: ")
    increment_build_number(xcodeproj: "MyAppName.xcodeproj")
    increment_version_number(version_number: "#{ver}", xcodeproj: "MyAppName.xcodeproj")
    
    regular
    alternative
  end

  lane :regular do                  
    version = get_version_number(xcodeproj: "MyAppName.xcodeproj", target: "MyAppName-iOS")
    build = get_build_number(xcodeproj: "MyAppName.xcodeproj")
    
    build_app(workspace: "MyAppName.xcworkspace", 
                 scheme: "MyAppName-iOS",
       output_directory: "build/ios/#{version}/#{build}",
            output_name: "ios.ipa")

    set_changelog(app_identifier: "my.app.id", version: "#{version}") # from fastlane/changelog.txt

    deliver(metadata_path: "fastlane/metadata-ios",
            skip_metadata: true,
         skip_screenshots: true,
                      ipa: "build/ios/#{version}/#{build}/ios.ipa",
           app_identifier: "my.app.id",
        submit_for_review: false,
           phased_release: true,
       reject_if_possible: true,
        precheck_include_in_app_purchases: false )
  end

  lane :alternative do
    version = get_version_number(xcodeproj: "MyAppName.xcodeproj", target: "MyAppName-iOS")
    build = get_build_number(xcodeproj: "MyAppName.xcodeproj")
    
    build_app(workspace: "MyAppName.xcworkspace",
                 scheme: "MyAppName-iOS-alternative",
       output_directory: "build/ios-alternative/#{version}/#{build}",
            output_name: "ios-alternative.ipa" )

    set_changelog(app_identifier: "my.app.id.pro", version: "#{version}") # from fastlane/changelog.txt

    deliver(metadata_path: "fastlane/metadata-ios-alternative",
            skip_metadata: true,
         skip_screenshots: true,
                      ipa: "build/ios-alternative/#{version}/#{build}/ios-alternative.ipa",
           app_identifier: "my.app.id.pro",
        submit_for_review: false,
       reject_if_possible: true,
           phased_release: true)
   end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
apple_id("my@email.com") # Your Apple email address
itc_team_id("my-team-id") # App Store Connect Team ID
team_id("my-portal-team-id") # Developer Portal Team ID


```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.148.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.16.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.73.0       |
| faraday                   | 1.0.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 1.17.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.0        |
| googleauth                | 0.12.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.5.1        |
| google-cloud-storage      | 1.26.1       |
| emoji_regex               | 1.0.1        |
| CFPropertyList            | 3.0.2        |
| json                      | 2.3.0        |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.1.3        |
| aws-partitions            | 1.319.0      |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.96.1       |
| aws-sdk-kms               | 1.31.0       |
| aws-sdk-s3                | 1.66.0       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>

*generated on:* **2020-05-23**
</details>

**Comment by strongbox-mark** [comment] 2020-06-24 17:21
Bump... just to keep this alive until the recent App Store deliver issues are fixed and I can check on this again

**Comment by strongbox-mark** [comment] 2020-07-02 09:47
Update: This is still an issue with 2.150.0.rc4

**Comment by strongbox-mark** [comment] 2020-08-09 18:06
Hi, this is still and issue as of 2.155.1 - Thanks!

**Comment by john-mejia** [comment] 2020-09-25 16:00
@strongbox-mark I'm having this same issue, did you ever get around this?

**Comment by strongbox-mark** [comment] 2020-09-25 16:02
I'm afraid not, I got tired of trying to keep the issue open too :) 

You only get a week or so to update and I haven't uploaded in the last week, I'm afraid this issue got closed and I don't have the option to re-open. :(

**Comment by john-mejia** [comment] 2020-09-25 16:04
@joshdholtz is it worth creating a new issue for this or can this be re-opened?

**Comment by joshdholtz** [comment] 2020-09-25 16:09
Thanks for ping! Reopened and will look into!

**Comment by joshdholtz** [comment] 2020-09-28 18:09
@strongbox-mark @john-mejia I think this might be because you have `skip_metadata: true` 🤔 This is technically metadata so that needs to be `false` in order for it to update 😬

**Comment by john-mejia** [comment] 2020-09-28 19:21
Will give that a try @joshdholtz  - Thanks. Could this also explain why my test user/password stopped persisting from older versions after the connectAPI changes?

**Comment by joshdholtz** [comment] 2020-09-28 19:27
@john-mejia It shouldn't have stopped persisting 😬 I don't have any issues over here with mine persisting 🤔 But there are to things at play here.

1. The session is stored in `~/.fastlane/spaceship/<email>` directory
    - There could be some issue with this not getting stored? Maybe?
2. The password for you Apple ID is stored in Keychain access
    - This is what gets looked at after the session expires and you enter your email address. If you are relying on your password to be entered automatically and its not reading from here, your keychain may not be unlocked? Maybe?

**Comment by john-mejia** [comment] 2020-09-28 19:31
Sorry my credentials, I'm talking about the beta user and password that we have to provide Apple to test the app during review. I've never had this in the metadata folder but the App Store kept the previously used credentials.After the changes it no longer has them. 

I know I can solve this buy adding the beta_user/pw file in metadata, just haven't gotten around to it.

**Comment by robmaceachern** [comment] 2020-09-28 20:03
@joshdholtz FWIW we are also (trying) to use `phased_release: true` with `skip_metadata: true` and running into this problem. We don't really want Fastlane to touch the other metadata. What's the safest way to configure this?

Maybe leaving the `metadata` directory empty and `phased_release: true, skip_metadata: false`?

**Comment by joshdholtz** [comment] 2020-09-28 20:05
@robmaceachern Making meta data empty and setting skip to false is the correct work around right now 🤔 I'll look into moving this outside of metadata though! I just need to make sure its backwards compatible enough to make that change 😬

**Comment by joshdholtz** [comment] 2020-09-28 20:06
@john-mejia Oh interesting.... Can you create a new issue for that and mention me in it? That does sound like a regression that I might have missed 😬

**Comment by strongbox-mark** [comment] 2020-09-30 10:47
Thanks a million @joshdholtz for looking into this. I will be uploading a new version of my app in a few days and will come back and let you know how it goes...

**Comment by strongbox-mark** [comment] 2020-10-07 10:31
Can confirm that emptying metadata directory and setting skip_metadata=false workaround works. Thank you :) 

It would be great to have this switch separate from metadata entirely. Cheers! Feel free to close out.

**Closed** 2020-11-23 17:31 UTC
Labels: status: auto-closed, status: waiting-for-reply, status: workaround available, tool: deliver
