### ISSUE TITLE
Exit status 12 (Error packaging up the application) when using update_app_identifier with Xcode 8

### ISSUE THREAD

**Issue by pirocso** [fastlane/fastlane#6319] opened 2016-09-28 15:28 UTC
I am using the latest fastlane build.

When I use Xcode 8, it fails with message "Exit status: 12" and "Error packaging up the application"

```
The issue only appears when using _update_app_identifier_ before _gym_. If I comment out _update_app_identifier_, no errors.

_update_app_identifier(app_identifier: ENV['APPID'], plist_path: "Info.plist")
gym(scheme: "Scheme Name", output_name: ENV['APPNAME'], use_legacy_build_api:true)_
```

I have confirmed this with puts commands that both environment variables exist and that they output the correct data. This issue only exists with Xcode 8 not Xcode 7.

```
Exit status: 12
Variable dump:
{:DEFAULT_PLATFORM=>:ios, :ENVIRONMENT=>"envName", :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios build_app"}
Error packaging up the application
```

Also - this is definitely NOT a code signing issue. The archive is created perfectly fine with both Xcode 8 and Xcode 7 from the IDE.

**Comment by dittma75** [comment] 2016-09-28 23:06
When I received an "Exit Status 12" error, I replaced `gym` with something like
`system("gym -s \"Scheme Name\" -n #{ENV['APPNAME']}")`
as a work-around in the affected lane, and it worked.
I received the same suggestion to use `use_legacy_build_api` on the original error, but doing that didn't help.  However, I didn't not have to pass the `use_legacy_build_api` for my app to build.  If the above command doesn't work, try:
`system("gym -s \"Scheme Name\" -n #{ENV['APPNAME']} --use_legacy_build_api true")`

Granted, this is a work-around that I found that worked for my situation.  Your mileage may vary. Surely there must be a correct way to fix the actual problem.

**Comment by pirocso** [comment] 2016-09-29 18:04
Ok so this solves this issue - thanks for that. Now it seems the update_app_identifier simply doesn't work - my bundle ID remains the same for both builds being run.

This is what I do:

- build_all lane: calls cocoa pods and calls sh "fastlane build_app --env env1" and "fastlane build_app --env env2". For env1 and env2, I have a .env.env1 and .env.env2 file with APPID=com.test.env1 and APPID=com.test.env2.

- build_app lane: 
   update_app_identifier(app_identifier: ENV['APPID'], plist_path: "Info.plist")
   system("gym -s \"SchemeName\" -n #{ENV['APPNAME']} --use_legacy_build_api true")

APPNAME is define in .env.env1 and .env.env2

Result:
Build is now successful thanks to @dittma75 but the bundle id for both ipa files is the same even tough they are different in .env.env1 and .env.env2

**Comment by dittma75** [comment] 2016-09-29 19:31
Well, `system` forks a new process with a new environment.  I suspect it fixes are problems because, somewhere along the line, Fastlane's environment is getting messed up.  In your case, you are going to have to pass the environment in the `gym` command.  Unfortunately, Fastlane seems to depend on an environment that it keeps (which you are essentially ignoring by calling `gym` with `system`).  You can't pass an app identifier to gym as far as I'm aware.
However, you can emulate what update_app_identifier is doing by using xcodeproj, which is a gem used by Cocoapods (and update_app_identifier directly).  Again, Fastlane uses this xcodeproj gem in scripts that are already written, but you could probably rig something up yourself in the meantime.  Do you know exactly what field you're looking to change?

**Comment by pirocso** [comment] 2016-09-30 14:39
Yes the bundle ID

**Comment by dittma75** [comment] 2016-09-30 15:56
Well, looking at `update_app_identifier.rb` in `<gem_path>/fastlane-1.X.X/lib/fastlane/actions` (the path for your fastlane installation), it appears that the goal is to update `PRODUCT_BUNDLE_IDENTIFIER` in the .pbxproj file associated with your Xcode project.  This script will do that for each of your configurations for the given .xcodeproj file (excuse the poor indentation... couldn't figure out GitHub's markdown to make it neater):

`require 'xcodeproj'`
`project = Xcodeproj::Project.open('path/to/xcodeproj_dir.xcodeproj')`
`project.build_configuration_list.build_configurations.each do |bc|`
`  if (bc.name == 'Development')`
`    bc.build_settings["PRODUCT_BUNDLE_IDENTIFIER"] = 'com.example.dev.app'`
`  elsif (bc.name == 'Production')`
`    bc.build_settings["PRODUCT_BUNDLE_IDENTIFIER"] = 'com.example.app'`
`  end`
`end`
`project.save`

So, if you have two configurations for your app named Development and Production, this will set Development's `PRODUCT_BUNDLE_IDENTIFIER` to `com.example.dev.app` and Production's `PRODUCT_BUNDLE_IDENTIFIER` to `com.example.app` in your `path/to/xcodeproj_dir.xcodeproj/project.pbxproj` file.

If you just want to set all of them regardless of configuration, replace the body of the `project.build_configuration_list.build_configurations.each`loop with: 
`bc.build_settings["PRODUCT_BUNDLE_IDENTIFIER"] = 'your.bundle.identifier'`.

That may or may not be what you want, but feel free to give it a try.  Either put it in a Ruby script and call it where you would call `update_app_identifier` or put the code exactly where you would call `update_app_identifier`.
Again, I'm trying to provide workarounds that probably aren't as nice, flexible, or useful as the folks of Fastlane actually addressing your underlying problem.  However, I'd like it if you could get your apps to build :).

**Comment by TKBurner** [comment] 2016-10-04 14:59
Hi @pirocso This is a duplicate of #6289 We are tracking it over there and I've reached out to the core team. Thanks!

**Closed by TKBurner** 2016-10-04 14:59 UTC
