### ISSUE TITLE
Publish screengrab to maven central

### ISSUE THREAD

**Issue by pocmo** [fastlane/fastlane#18174] opened 2021-02-10 13:09 UTC
JCenter will go away eventually:
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

It seems like screengrab (`tools.fastlane:screengrab`) is currently only available via JCenter (bintray). Would it be possible to publish it to Maven Central?

Falcon (`com.jraska:falcon`), which screengrab depends on, is affected too. This seems to be tracked here:
https://github.com/jraska/Falcon/issues/52

**Comment by penn5** [comment] 2021-02-15 13:23
This is a duplicate of #12651

**Comment by pocmo** [comment] 2021-02-15 18:05
Oh, sorry, I searched for an issue but was somehow unable to find it. I'll close this here then.

**Comment by penn5** [comment] 2021-03-16 19:00
@joshdholtz could you please double check why #12651 is locked? Is there a plan to fix this? The AGP now warns if you are using jcenter repositories. I could resolve this by adding it to #18003 perhaps?

**Comment by joshdholtz** [comment] 2021-03-16 19:01
It's the bots fault 😩 I'll be working on getting it published to maven soon!

**Comment by penn5** [comment] 2021-04-16 22:27
Bad bot

**Closed** 2021-07-17 17:33 UTC
Labels: status: waiting-for-reply, tool: screengrab

**Comment by joshdholtz** [comment] 2021-10-15 12:45
Update on this but it's published 😊
