### ISSUE TITLE
Fastlane docs layout is misaligned on Safari

### ISSUE THREAD

**Issue by RishabhTayal** [fastlane/fastlane#7930] opened 2017-01-20 05:16 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

here is a screenshot of the fastlane docs. Something wrong with the layout.

<img width="878" alt="screenshot 2017-01-19 23 15 55" src="https://cloud.githubusercontent.com/assets/2100166/22136901/52830d40-de9d-11e6-815a-3676f3170a1a.png">

**Comment by mfurtak** [comment] 2017-01-20 13:27
This problem appears to persist past one page reload. Steps to reproduce:

1. Visit https://docs.fastlane.tools/getting-started/android/beta-deployment/ (see that text is unreadable, as above)
2. CMD+R or CTRL+R to reload (see that text is fixed)
3. Click on "Release Deployment" in the sidebar to load a new page (see that the text is broken again)
4. Click on "Beta Deployment" in the sidebar to return to the first page (see that the text is broken again)

**Comment by mfurtak** [comment] 2017-01-20 13:28
The most recent thing to change with the docs site is TurboLinks, so I am suspicious of that.

**Comment by hjanuschka** [comment] 2017-01-20 14:13
@mfurtak - how about trying it - reverting the turbolink pr and see if problem is fixed?

**Comment by mfurtak** [comment] 2017-01-20 14:32
@hjanuschka That sounds reasonable. It's not something I can do today, but I would support this 👍

**Comment by hjanuschka** [comment] 2017-01-20 18:31
@mfurtak done, and you where right, removing turbolinks fixes the issue permanently. -> https://github.com/fastlane/docs/pull/259

**Comment by mfurtak** [comment] 2017-01-20 18:54
@hjanuschka Thanks for doing that - we'll need to wait to make any such change, unfortunately. I'll try to get back to you ASAP, but it might take until next week 🙁

**Comment by KrauseFx** [comment] 2017-01-20 18:57
Is this related to the recent turbo link change maybe?

**Comment by hjanuschka** [comment] 2017-01-20 19:09
@KrauseFx jep since then

**Comment by mfurtak** [comment] 2017-01-20 19:24
Thanks @hjanuschka and @RishabhTayal - I've merged and deployed your PR so this is now fixed in production. 🚀

**Closed by mfurtak** 2017-01-20 19:24 UTC

**Comment by RishabhTayal** [comment] 2017-01-20 19:51
It looks good now but  there is an issue with the linking to right section in the page. For ex: https://docs.fastlane.tools/getting-started/ios/beta-deployment/#fetching-the-latest-build-number-from-testflight doesn't take you to the 'fetching the latest build number' section in the docs.
