### ISSUE TITLE
Unexpected behaviour for plist_path in action update_info_plist

### ISSUE THREAD

**Issue by tbaranes** [fastlane/fastlane#4036] opened 2016-04-02 21:15 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

It's not really an error, but more a conception choice which give me some issues. 

I wanted to use `update_info_plist` while specifying  an xcodeproj, all the example are describing the parameter `plist_path` this way:  `plist_path: "path/to/Info.plist"`. So, I just replaced the placeholder and put the real path to my plist. 

Here is the problem:  `plist_path` doesn't expect the real path of the plist, but the path relative of the `xcodeproj`. It's even more confusing when you don't specify the xcodeproj since its using the first `xcodeproj` found.

I finally found my solution by looking at the code which give me the solution at my issue. I found two issues (?) there:

```ruby
 # Read existing plist file
          info_plist_path = File.join(folder, "..", params[:plist_path])
          UI.user_error!("Couldn't find info plist file at path '#{params[:plist_path]}'") unless File.exist?(info_plist_path)
          plist = Plist.parse_xml(info_plist_path)
```

1 - As said above, I had to give the plist's path relative to the Xcodeproj path since a `join` is used. Why the plist path isn't the real one directly? It would be less confusing
2 - The error is showing the path give in parameter `#{params[:plist_path]}'")` which is even more confusing since the path was correct... 

If that both points are working as expected, it would be great to change a bit the examples to explain that the `plist_path` is relative to the xcodeproj. 

##### Complete output when running fastlane, including the stack trace and command used

When specifying the `xcode_proj`:

```ruby
Couldn't find info plist file at path 'parameter_plist_path'
```

### Configuration Files

Fastfile:
```ruby
before_all do  
end

lane :increment_ios_build do
  update_info_plist(
    xcodeproj: "your_path",
    plist_path: "the_real_plist_path,
    block: lambda { |plist|
      plist['CFBundleVersion'] = "10"
    }
  )
end

after_all do |lane|
end
```

The same fast file could be used without passing `xcodeproj`.

### Environment

fastlane version (fastlane -v): 1.70.0
Do you use bundler, rbenv or ram? `bundler`

**Comment by TKBurner** [comment] 2016-04-04 17:41
@tbaranes great to hear from you. Can you let me know how this isn't a duplicate of #4037? Thanks!

**Comment by tbaranes** [comment] 2016-04-04 17:46
The #4037 is a bug issue, just reporting that it crashes if doesn't found the xcodeproj, and a question to improve the behaviour related to the `xcodeproj` parameter.
The above issue is a pure question and an ask to improve the docs / implementation about the action `update_info_plist`, and more specifically the parameter `plist_path`.

I can go more in details if you want, but that is the main difference between the both issues which don't have the same final goal :)

**Comment by TKBurner** [comment] 2016-04-05 14:23
Interesting feedback. The reason we did this was to streamline the path since a lot of people use them in line with command line as parameters. I'm going to mark this as a feature request to improve the way we handle this error situation. I'll make sure more of the team looks it over. Thanks!

**Comment by tbaranes** [comment] 2016-04-05 14:47
Shouldn't you reopen it in that case? :laughing:

**Comment by TKBurner** [comment] 2016-04-06 16:50
Hi @tbaranes. I'm going to leave this open until we review it. Thanks!

**Comment by ohwutup** [comment] 2016-05-24 15:50
Hey @tbaranes sorry for the back-and-forth here. We are going to re-close this issue for now as it is not at the top of the priority list. If you would like to submit a PR with a fix we would be happy to review it and get it merged in! Feel free to reopen the issue if you get a chance to bite off the work!

**Closed by ohwutup** 2016-05-24 15:50 UTC
Labels: action, fastlane, feature
