### ISSUE TITLE
Code signing is required for product type 'Application' in SDK 'iOS 10.3'

### ISSUE THREAD

**Issue by bhawin-bigstep** [fastlane/fastlane#11844] opened 2018-02-14 16:18 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I ran fastlane gym and got this error:
Code signing is required for product type 'Application' in SDK 'iOS 10.3'

I have certificate and provisioning profile downloaded via "fastlane cert" and "fastlane sigh"

I am able to create archive manually with product->archive from my xcode 9 

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>BigSteps-MacBook-Air:datatest bigstep$ sudo fastlane gym
[✔] 🚀 
[21:22:50]: fastlane detected a Gemfile in the current directory
[21:22:50]: however it seems like you don't use `bundle exec`
[21:22:50]: to launch fastlane faster, please use
[21:22:50]: 
[21:22:50]: $ bundle exec fastlane gym
[21:22:50]: 
[21:22:50]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[21:22:51]: $ xcodebuild -list -project ./datatest.xcodeproj
[21:22:51]: $ xcodebuild -showBuildSettings -scheme datatest -project ./datatest.xcodeproj
[21:22:52]: Detected provisioning profile mapping: {:"bigstep.datatest"=>"bigstep.datatest AppStore"}

+--------------------------------------+--------------------------------------+
|                           Summary for gym 2.81.0                            |
+--------------------------------------+--------------------------------------+
| project                              | ./datatest.xcodeproj                 |
| scheme                               | datatest                             |
| destination                          | generic/platform=iOS                 |
| export_options.provisioningProfiles  | bigstep.datatest AppStore            |
| .bigstep.datatest                    |                                      |
| output_name                          | datatest                             |
| build_path                           | /Users/bigstep/Library/Developer/Xc  |
|                                      | ode/Archives/2018-02-14              |
| clean                                | false                                |
| output_directory                     | .                                    |
| silent                               | false                                |
| skip_package_ipa                     | false                                |
| buildlog_path                        | ~/Library/Logs/gym                   |
| skip_profile_detection               | false                                |
| xcode_path                           | /Applications/Xcode.app              |
+--------------------------------------+--------------------------------------+

[21:22:52]: $ set -o pipefail && xcodebuild -scheme datatest -project ./datatest.xcodeproj -destination 'generic/platform=iOS' -archivePath /Users/bigstep/Library/Developer/Xcode/Archives/2018-02-14/datatest\ 2018-02-14\ 21.22.52.xcarchive archive | tee /Users/bigstep/Library/Logs/gym/datatest-datatest.log | xcpretty
[21:22:53]: ▸ Building datatest/datatest [Release]
[21:22:53]: ▸ Check Dependencies
[21:22:53]: ▸ ❌  Code signing is required for product type 'Application' in SDK 'iOS 10.3'
[21:22:53]: ▸ ** ARCHIVE FAILED **
[21:22:53]: ▸ The following build commands failed:
[21:22:53]: ▸ Check dependencies
[21:22:53]: ▸ (1 failure)
▸ Building datatest/datatest [Release]
▸ Check Dependencies

❌  Code signing is required for product type 'Application' in SDK 'iOS 10.3'

** ARCHIVE FAILED **

The following build commands failed:
Check dependencies
(1 failure)
[21:22:53]: Exit status: 65

+-------------+-------------------------+
|           Build environment           |
+-------------+-------------------------+
| xcode_path  | /Applications/Xcode.app |
| gym_version | 2.81.0                  |
| sdk         | iPhoneOS10.3.sdk        |
+-------------+-------------------------+

[21:22:53]: ▸ === BUILD TARGET datatest OF PROJECT datatest WITH CONFIGURATION Release ===
[21:22:53]: ▸ Check dependencies
[21:22:53]: ▸ No iOS profile matching 'W84Y3AR95Z/bigstep.datatest AppStore' found:  Xcode couldn't find a profile matching 'W84Y3AR95Z/bigstep.datatest AppStore'. Install the profile (by dragging and dropping it onto Xcode's dock item) or select a different one in the General tab of the target editor.
[21:22:53]: ▸ Code signing is required for product type 'Application' in SDK 'iOS 10.3'
[21:22:53]: 
[21:22:53]: ⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
[21:22:53]: 📋  For the complete and more detailed error log, check the full log at:
[21:22:53]: 📋  /Users/bigstep/Library/Logs/gym/datatest-datatest.log
[21:22:53]: 
[21:22:53]: There seems to be a mismatch between your provided `export_method` in gym
[21:22:53]: and the selected provisioning profiles. You passed the following options:
[21:22:53]:   export_method:      
[21:22:53]:   Bundle identifier:  bigstep.datatest
[21:22:53]:   Profile name:       bigstep.datatest AppStore
[21:22:53]:   Profile type:       app-store
[21:22:53]: Make sure to either change the `export_method` passed from your Fastfile or CLI
[21:22:53]: or select the correct provisioning profiles by updating your Xcode project
[21:22:53]: or passing the profiles to use by using match or manually via the `export_options` hash
[21:22:53]: 
[21:22:53]: 
[21:22:53]: Looks like fastlane ran into a build/archive error with your project
[21:22:53]: It's hard to tell what's causing the error, so we wrote some guides on how
[21:22:53]: to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
[21:22:53]: Before submitting an issue on GitHub, please follow the guide above and make
[21:22:53]: sure your project is set up correctly.
[21:22:53]: fastlane uses `xcodebuild` commands to generate your binary, you can see the
[21:22:53]: the full commands printed out in yellow in the above log.
[21:22:53]: Make sure to inspect the output above, as usually you'll find more error information there
[21:22:53]: 
[21:22:53]: Seems like Xcode is not happy with the code signing setup
[21:22:53]: Please make sure to check out the raw `xcodebuild` output
[21:22:53]: /Users/bigstep/Library/Logs/gym/datatest-datatest.log
[21:22:53]: The very bottom of the file will tell you the raw Xcode error message
[21:22:53]: indicating on why the code signing step failed

[!] Error building the application - see the log above</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13                                                          |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.11.0 (Apple Git-81)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13 (17A405)                                        |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 8.3.2                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  	desc "Push a new beta build to TestFlight"
  	lane :release do
  		build_app(
		    export_method: "app-store",
		    export_options: {
		      	provisioningProfiles: { 
		        	"bigstep.datatest" => "bigstep.datatest AppStore"
		      	}
		    }
	  	)
	end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "bigstep.datatest" # The bundle identifier of your app
apple_id "support01@socialengineaddons.com" # Your Apple email address

itc_team_id "10291639" # iTunes Connect Team ID
team_id "W84Y3AR95Z" # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.81.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| CFPropertyList            | 2.3.6        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.60.0       |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.1.2        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.1       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
| faraday                   | 0.14.0       |
| json                      | 2.1.0        |
| atomos                    | 0.1.2        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.6        |
</details>

*generated on:* **2018-02-14**
</details></pre>
</details>

**Comment by bhawin-bigstep** [comment] 2018-02-14 16:21
@fastlane-bot  Yes , I did that

**Comment by minuscorp** [comment] 2018-02-14 21:06
Hi @bhawin-bigstep, did you check that in your target settings are you using the certificate provided by fastlane? (i.e., `sigh appstore com.XXX.YYY`)

**Comment by bhawin-bigstep** [comment] 2018-02-15 03:05
@minuscorp  Yes. I have execute this command  , and it downloaded the same provisioning which is already present in my local machine

**Comment by minuscorp** [comment] 2018-02-15 17:26
So `match` provides a the certificates that is downloaded from your private cert repo and maps it into your `xcodebuild` command through `gym`. It seems to me that there're differences between the certificate that xcode is using and the one that is downloaded and installed in the `gym` step. In your situation I'd try to clear all certificates that are in the machine installed (you can find the Signing identities in Keychain, and the provisioning profiles in `~/Library/MobileDevice/Provisioning\ Profiles. Provisioning profiles`. And try to set the certs again from xcode (once match downloads them) and then trying to `gym` again.

**Comment by bhawin-bigstep** [comment] 2018-02-15 17:57
@minuscorp  , I am not using `match` right now.
Seems to me that its some kind of configuration problem.
I have only one production certificate in my developers.apple.com account

**Comment by minuscorp** [comment] 2018-02-18 20:05
Is there a reason why you use `cert` and `sigh` instead of `match` standalone? Personally, I think that the problem is with the Signing identities that you already have in your account. They can be easily deleted and re-generated using `match nuke`. Which will generate new Signing Identities and new Proviosioning Profiles according to their identity.

**Comment by mwoollard** [comment] 2018-02-21 11:31
I'm seeing the same issue (except SDK 11.2) returning to build a project that has been idle for a couple of months. Since last build `Xcode` + `fastlane` updated. We're using `match` - will try the `match nuke` suggestion and let you know if things are fixed.

**Comment by mwoollard** [comment] 2018-02-21 12:36
I can confirm `match nuke` fixed issue for me

**Comment by minuscorp** [comment] 2018-02-21 12:46
Feel free to close the issue whenever you want😁🚀

**Closed** 2018-04-09 17:33 UTC
Labels: status: waiting-for-reply
