### ISSUE TITLE
Crash when try to add already existing device by register_devices action

### ISSUE THREAD

**Issue by skywinder** [fastlane/fastlane#1080] opened 2016-01-12 13:42 UTC
register_devices crashes when device already exists.
Crash number: `413cf8bcc5c4fe8f9530a83c63961403`

CC @lmirosevic

**Comment by vpolouchkine** [comment] 2016-01-12 17:11
Can you please provide the version and the full log?

**Comment by lmirosevic** [comment] 2016-01-12 18:04
I can't reproduce this, I always run `register_devices` with already registered devices in there and it works as it should. The action was designed to be idempotent.

**Comment by skywinder** [comment] 2016-01-12 18:05
fastlane 1.49.0

```
{
  "event_id": "413cf8bcc5c4fe8f9530a83c63961403",
  "message": "RuntimeError: The device UDID 'b6fef6903ed471ad50fd3bcf18495cd153326333' already exists on this team.",
  "timestamp": "2016-01-12T13:38:01",
  "time_spent": null,
  "level": 40,
  "project": null,
  "platform": "ruby",
  "logger": "",
  "culprit": "spaceship/portal/device.rb in create! at line 151",
  "server_name": "npi7efa96.fxpro.local",
  "modules": {
    "abstract_type": "0.0.7",
    "actionmailer": "4.1.4",
    "actionpack": "4.1.4",
    "actionview": "4.1.4",
    "activejob": "4.2.0",
    "activemodel": "4.1.4",
    "activerecord": "4.1.4",
    "activesupport": "4.1.4",
    "adamantium": "0.2.0",
    "addressable": "2.3.6",
    "ansi": "1.5.0",
    "arel": "5.0.1.20140414130214",
    "ast": "2.0.0",
    "astrolabe": "1.3.0",
    "autoparse": "0.3.3",
    "aws-sdk": "1.59.0",
    "aws-sdk-core": "2.0.29",
    "aws-sdk-resources": "2.0.29",
    "aws-sdk-v1": "1.59.0",
    "babosa": "1.0.2",
    "bcrypt": "3.1.9",
    "bcrypt-ruby": "3.0.1",
    "bigdecimal": "1.2.4",
    "bitbucket-cli": "0.0.3",
    "bitbucket_rest_api": "0.1.7",
    "buftok": "0.2.0",
    "builder": "3.2.2",
    "bumper_pusher": "0.1.17",
    "bundle": "0.0.1",
    "bundler": "1.7.6",
    "bundler-unload": "1.0.2",
    "capybara": "2.4.4",
    "cert": "0.1.5",
    "certified": "1.0.0",
    "changelog_merger": "0.1.2.1",
    "childprocess": "0.5.6",
    "choice": "0.1.6",
    "claide": "0.7.0",
    "clamp": "0.6.5",
    "cliver": "0.3.2",
    "cocoapods": "0.36.0.rc.1",
    "cocoapods-core": "0.35.0",
    "cocoapods-deintegrate": "0.2.1",
    "cocoapods-downloader": "0.8.0",
    "cocoapods-plugins": "0.3.2",
    "cocoapods-search": "0.1.0",
    "cocoapods-stats": "0.6.1",
    "cocoapods-trunk": "0.4.1",
    "cocoapods-try": "0.4.2",
    "codeclimate-test-reporter": "0.4.7",
    "coderay": "1.1.0",
    "coffee-rails": "4.0.1",
    "coffee-script": "2.2.0",
    "coffee-script-source": "1.7.0",
    "colored": "1.2",
    "colorize": "0.7.7",
    "commander": "4.2.1",
    "concord": "0.1.5",
    "constraintClean": "1.0.3",
    "coveralls": "0.7.12",
    "crack": "0.4.2",
    "credentials_manager": "0.2.1",
    "cupertino": "1.3.0",
    "daemons": "1.2.3",
    "debase": "0.1.0",
    "debase-ruby_core_source": "0.7.2",
    "deliver": "0.9.1",
    "descendants_tracker": "0.0.4",
    "diff-lcs": "1.2.5",
    "docile": "1.1.5",
    "domain_name": "0.5.23",
    "dotenv": "0.11.1",
    "dotenv-deployment": "0.0.2",
    "em-synchrony": "1.0.3",
    "equalizer": "0.0.9",
    "erubis": "2.7.0",
    "escape": "0.0.4",
    "eventmachine": "1.0.3",
    "excon": "0.45.1",
    "execjs": "2.2.1",
    "executable-hooks": "1.3.2",
    "extlib": "0.9.16",
    "facets": "3.0.0",
    "faraday": "0.8.9",
    "faraday-cookie_jar": "0.0.6",
    "faraday_middleware": "0.9.1",
    "fastimage": "1.6.8",
    "fastlane": "0.7.0",
    "fastlane_core": "0.5.2",
    "ffi": "1.9.8",
    "filewatcher": "0.5.2",
    "foreman": "0.78.0",
    "frameit": "1.0.0",
    "fuzzy_match": "2.0.4",
    "gem-wrappers": "1.2.7",
    "git": "1.2.8",
    "git-up": "0.5.12",
    "github_api": "0.12.2",
    "github_changelog_generator": "1.10.0",
    "globalid": "0.3.3",
    "google-api-client": "0.8.6",
    "googleauth": "0.4.2",
    "grit": "2.5.0",
    "gym": "1.2.0",
    "hashie": "3.3.1",
    "highline": "1.6.21",
    "hike": "1.2.3",
    "httmultiparty": "0.3.16",
    "http": "0.6.3",
    "http-cookie": "1.0.2",
    "http-form_data": "1.0.0",
    "http_parser.rb": "0.6.0",
    "httparty": "0.11.0",
    "hub": "1.12.4",
    "i18n": "0.6.9",
    "ice_nine": "0.11.1",
    "iniparse": "1.4.0",
    "io-console": "0.4.2",
    "jbuilder": "2.1.1",
    "jmespath": "1.0.2",
    "jquery-rails": "3.1.1",
    "json": "1.7.7",
    "jwt": "1.0.0",
    "kgio": "2.9.2",
    "krausefx-shenzhen": "0.14.2",
    "launchy": "2.2.0",
    "little-plugger": "1.1.4",
    "logging": "2.0.0",
    "lolcat": "42.1.0",
    "lolcommits": "0.5.7",
    "loofah": "2.0.1",
    "lunchy": "0.8.0",
    "mail": "2.5.4",
    "match": "0.2.2",
    "mechanize": "2.5.1",
    "memoist": "0.12.0",
    "memoizable": "0.4.2",
    "methadone": "1.2.6",
    "method_source": "0.8.2",
    "mime-types": "1.25.1",
    "mimemagic": "0.2.1",
    "mini_magick": "3.8.1",
    "mini_portile": "0.6.1",
    "minitest": "4.7.5",
    "molinillo": "0.1.2",
    "multi_json": "1.10.1",
    "multi_xml": "0.5.5",
    "multipart-post": "1.2.0",
    "nap": "0.8.0",
    "naught": "1.0.0",
    "net-http-digest_auth": "1.4",
    "net-http-persistent": "2.9.4",
    "net-sftp": "2.1.2",
    "net-ssh": "2.9.1",
    "netrc": "0.7.8",
    "nokogiri": "1.6.4",
    "ntlm-http": "0.1.1",
    "oauth": "0.4.7",
    "oauth2": "1.0.0",
    "oauth2-client": "1.1.3",
    "octokit": "4.0.1",
    "oj": "2.0.14",
    "open4": "1.3.4",
    "overcommit": "0.25.0",
    "paint": "0.8.7",
    "parser": "2.2.0.3",
    "pbxplorer": "1.0.0",
    "pdf-core": "0.5.1",
    "pem": "0.4.0",
    "phantomjs": "1.9.8.0",
    "pilot": "0.2.0",
    "plist": "3.1.0",
    "poltergeist": "1.5.1",
    "polyglot": "0.3.5",
    "posix-spawn": "0.3.9",
    "power_assert": "0.2.1",
    "powerpack": "0.1.0",
    "prawn": "2.0.1",
    "private_attr": "1.1.0",
    "procto": "0.0.2",
    "produce": "0.2.0",
    "pry": "0.10.1",
    "psych": "2.0.5",
    "rack": "1.5.2",
    "rack-test": "0.6.2",
    "rails": "4.1.4",
    "rails-deprecated_sanitizer": "1.0.3",
    "rails-dom-testing": "1.0.5",
    "rails-html-sanitizer": "1.0.1",
    "rails_12factor": "0.0.2",
    "rails_serve_static_assets": "0.0.1",
    "rails_stdout_logging": "0.0.2",
    "railties": "4.1.4",
    "rainbow": "2.0.0",
    "raindrops": "0.13.0",
    "rake": "10.1.0",
    "rdoc": "4.1.0",
    "reek": "3.1",
    "rest-client": "1.6.8",
    "retriable": "1.4.1",
    "rouge": "1.10.1",
    "rspec": "3.1.0",
    "rspec-core": "3.1.7",
    "rspec-expectations": "3.1.2",
    "rspec-mocks": "3.1.3",
    "rspec-support": "3.1.2",
    "rubocop": "0.29.1",
    "ruby-debug-ide": "0.4.23.beta11",
    "ruby-lint": "2.0.3",
    "ruby-progressbar": "1.7.5",
    "rubygems-bundler": "1.4.4",
    "rubygems-update": "2.4.4",
    "rubyzip": "1.1.6",
    "rvm": "1.11.3.9",
    "safe_yaml": "1.0.4",
    "sass": "3.2.19",
    "sass-rails": "4.0.3",
    "sawyer": "0.6.0",
    "scan": "0.3.3",
    "sdoc": "0.4.0",
    "security": "0.1.3",
    "sentry-raven": "0.15.2",
    "shenzhen": "0.9.0",
    "shopify_theme": "0.0.25",
    "sigh": "0.4.9",
    "signet": "0.6.1",
    "simple_oauth": "0.3.0",
    "simplecov": "0.9.2",
    "simplecov-html": "0.9.0",
    "slack-notifier": "1.2.0",
    "slop": "3.6.0",
    "snapshot": "0.6.1",
    "spaceship": "0.0.15",
    "spring": "1.1.3",
    "sprockets": "2.11.0",
    "sprockets-rails": "2.1.3",
    "sqlite3": "1.3.10",
    "subexec": "0.2.3",
    "supply": "0.2.2",
    "synx": "0.0.61",
    "term-ansicolor": "1.0.7",
    "terminal-notifier": "1.6.2",
    "terminal-table": "1.4.5",
    "test-unit": "2.1.5.0",
    "thor": "0.19.1",
    "thread_safe": "0.3.4",
    "tilt": "1.4.1",
    "tins": "1.3.5",
    "treetop": "1.4.15",
    "trollop": "1.16.2",
    "ttfunk": "1.4.0",
    "tumblr_client": "0.8.5",
    "turbolinks": "2.2.2",
    "twitter": "4.8.1",
    "tzinfo": "1.2.1",
    "uglifier": "2.5.1",
    "unf": "0.1.4",
    "unf_ext": "0.0.6",
    "unicorn": "4.8.3",
    "unparser": "0.2.4",
    "webmock": "1.19.0",
    "webrobots": "0.1.1",
    "websocket-driver": "0.5.4",
    "websocket-extensions": "0.1.2",
    "xcode-install": "1.0.1",
    "xcodeproj": "0.20.2",
    "xcpretty": "0.1.10",
    "xcpretty-travis-formatter": "0.0.3",
    "xml-simple": "1.1.5",
    "xpath": "2.0.0",
    "yam": "2.0.2",
    "yard": "0.8.7.6"
  },
  "extra": {
  },
  "tags": {
  },
  "user": {
  },
  "exception": {
    "values": [
      {
        "type": "RuntimeError",
        "value": "The device UDID 'b6fef6903ed471ad50fd3bcf18495cd153326333' already exists on this team.",
        "module": "",
        "stacktrace": {
          "frames": [
            {
              "pre_context": [
                "  warn \"unable to load executable-hooks/hooks\" if ENV.key?('ExecutableHooks_DEBUG')\n",
                "end\n",
                "\n"
              ],
              "post_context": [
                null,
                null,
                null
              ],
              "abs_path": "/Users/petrkorolev/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks",
              "function": "<main>",
              "lineno": 15,
              "in_app": false,
              "context_line": "eval File.read($0), binding, $0\n",
              "project_root": null,
              "filename": "/Users/petrkorolev/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks"
            },
            {
              "pre_context": [
                "  warn \"unable to load executable-hooks/hooks\" if ENV.key?('ExecutableHooks_DEBUG')\n",
                "end\n",
                "\n"
              ],
              "post_context": [
                null,
                null,
                null
              ],
              "abs_path": "/Users/petrkorolev/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks",
              "function": "eval",
              "lineno": 15,
              "in_app": false,
              "context_line": "eval File.read($0), binding, $0\n",
              "project_root": null,
              "filename": "/Users/petrkorolev/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks"
            },
            {
              "pre_context": [
                "end\n",
                "\n",
                "gem 'fastlane', version\n"
              ],
              "post_context": [
                null,
                null,
                null
              ],
              "abs_path": "/Users/petrkorolev/.rvm/gems/ruby-2.1.5/bin/fastlane",
              "function": "<main>",
              "lineno": 23,
              "in_app": false,
              "context_line": "load Gem.bin_path('fastlane', 'fastlane', version)\n",
              "project_root": null,
              "filename": "/Users/petrkorolev/.rvm/gems/ruby-2.1.5/bin/fastlane"
            },
            {
              "pre_context": [
                "end\n",
                "\n",
                "gem 'fastlane', version\n"
              ],
              "post_context": [
                null,
                null,
                null
              ],
              "abs_path": "/Users/petrkorolev/.rvm/gems/ruby-2.1.5/bin/fastlane",
              "function": "load",
              "lineno": 23,
              "in_app": false,
              "context_line": "load Gem.bin_path('fastlane', 'fastlane', version)\n",
              "project_root": null,
              "filename": "/Users/petrkorolev/.rvm/gems/ruby-2.1.5/bin/fastlane"
            },
            {
              "pre_context": [
                "\n",
                "begin\n",
                "  FastlaneCore::UpdateChecker.start_looking_for_update('fastlane')\n"
              ],
              "post_context": [
                "rescue => ex\n",
                "  FastlaneCore::CrashReporting.handle_crash(ex)\n",
                "ensure\n"
              ],
              "abs_path": "/Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/fastlane-1.49.0/bin/fastlane",
              "function": "<top (required)>",
              "lineno": 161,
              "in_app": false,
              "context_line": "  FastlaneApplication.new.run\n",
              "project_root": null,
              "filename": "/Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/fastlane-1.49.0/bin/fastlane"
            },
            {
              "pre_context": [
                "\n",
                "    default_command :trigger\n",
                "\n"
              ],
              "post_context": [
                "  end\n",
                "end\n",
                "\n"
              ],
              "abs_path": "/Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/fastlane-1.49.0/bin/fastlane",
              "function": "run",
              "lineno": 155,
              "in_app": false,
              "context_line": "    run!\n",
              "project_root": null,
              "filename": "/Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/fastlane-1.49.0/bin/fastlane"
            },
            {
              "pre_context": [
                "      never_trace!\n",
                "    ).each do |meth|\n",
                "      eval <<-END, binding, __FILE__, __LINE__\n"
              ],
              "post_context": [
                "          ::Commander::Runner.instance.#{meth}(*args, &block)\n",
                "        end\n",
                "      END\n"
              ],
              "abs_path": "/Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/commander-4.3.5/lib/commander/delegates.rb",
              "function": "run!",
              "lineno": 15,
              "in_app": false,
              "context_line": "        def #{meth}(*args, &block)\n",
              "project_root": null,
              "filename": "commander/delegates.rb"
            },
            {
              "pre_context": [
                "      parse_global_options\n",
                "      remove_global_options options, @args\n",
                "      if trace\n"
              ],
              "post_context": [
                "      else\n",
                "        begin\n",
                "          run_active_command\n"
              ],
              "abs_path": "/Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/commander-4.3.5/lib/commander/runner.rb",
              "function": "run!",
              "lineno": 68,
              "in_app": false,
              "context_line": "        run_active_command\n",
              "project_root": null,
              "filename": "commander/runner.rb"
            },
            {
              "pre_context": [
                "      if alias? command_name_from_args\n",
                "        active_command.run(*(@aliases[command_name_from_args.to_s] + args_without_command_name))\n",
                "      else\n"
              ],
              "post_context": [
                "      end\n",
                "    end\n",
                "\n"
              ],
              "abs_path": "/Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/commander-4.3.5/lib/commander/runner.rb",
              "function": "run_active_command",
              "lineno": 428,
              "in_app": false,
              "context_line": "        active_command.run(*args_without_command_name)\n",
              "project_root": null,
              "filename": "commander/runner.rb"
            },
            {
              "pre_context": [
                "    #\n",
                "\n",
                "    def run(*args)\n"
              ],
              "post_context": [
                "    end\n",
                "\n",
                "    #:stopdoc:\n"
              ],
              "abs_path": "/Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/commander-4.3.5/lib/commander/command.rb",
              "function": "run",
              "lineno": 153,
              "in_app": false,
              "context_line": "      call parse_options_and_call_procs(*args)\n",
              "project_root": null,
              "filename": "commander/command.rb"
            },
            {
              "pre_context": [
                "      meth = @when_called.shift || :call\n",
                "      options = proxy_option_struct\n",
                "      case object\n"
              ],
              "post_context": [
                "      when Class then meth != :call ? object.new.send(meth, args, options) : object.new(args, options)\n",
                "      else object.send(meth, args, options) if object\n",
                "      end\n"
              ],
              "abs_path": "/Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/commander-4.3.5/lib/commander/command.rb",
              "function": "call",
              "lineno": 178,
              "in_app": false,
              "context_line": "      when Proc then object.call(args, options)\n",
              "project_root": null,
              "filename": "commander/command.rb"
            },
            {
              "pre_context": [
                "      meth = @when_called.shift || :call\n",
                "      options = proxy_option_struct\n",
                "      case object\n"
              ],
              "post_context": [
                "      when Class then meth != :call ? object.new.send(meth, args, options) : object.new(args, options)\n",
                "      else object.send(meth, args, options) if object\n",
                "      end\n"
              ],
              "abs_path": "/Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/commander-4.3.5/lib/commander/command.rb",
              "function": "call",
              "lineno": 178,
              "in_app": false,
              "context_line": "      when Proc then object.call(args, options)\n",
              "project_root": null,
              "filename": "commander/command.rb"
            },
            {
              "pre_context": [
                "\n",
                "      c.action do |args, options|\n",
                "        if Fastlane::FastlaneFolder.setup?\n"
              ],
              "post_context": [
                "        else\n",
                "          create = agree('Could not find fastlane in current directory. Would you like to set it up? (y/n)'.yellow, true)\n",
                "          Fastlane::Setup.new.run if create\n"
              ],
              "abs_path": "/Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/fastlane-1.49.0/bin/fastlane",
              "function": "block (2 levels) in run",
              "lineno": 37,
              "in_app": false,
              "context_line": "          Fastlane::CommandLineHandler.handle(args, options)\n",
              "project_root": null,
              "filename": "/Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/fastlane-1.49.0/bin/fastlane"
            },
            {
              "pre_context": [
                "      end\n",
                "\n",
                "      dot_env = Helper.is_test? ? nil : options.env\n"
              ],
              "post_context": [
                "    end\n",
                "\n",
                "    # Helper to convert into the right data type\n"
              ],
              "abs_path": "/Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/fastlane-1.49.0/lib/fastlane/command_line_handler.rb",
              "function": "handle",
              "lineno": 30,
              "in_app": false,
              "context_line": "      Fastlane::LaneManager.cruise_lane(platform, lane, lane_parameters, dot_env)\n",
              "project_root": null,
              "filename": "fastlane/command_line_handler.rb"
            },
            {
              "pre_context": [
                "      started = Time.now\n",
                "      e = nil\n",
                "      begin\n"
              ],
              "post_context": [
                "      rescue => ex\n",
                "        Helper.log.info 'Variable Dump:'.yellow\n",
                "        Helper.log.info Actions.lane_context\n"
              ],
              "abs_path": "/Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/fastlane-1.49.0/lib/fastlane/lane_manager.rb",
              "function": "cruise_lane",
              "lineno": 46,
              "in_app": false,
              "context_line": "        ff.runner.execute(lane, platform, parameters)\n",
              "project_root": null,
              "filename": "fastlane/lane_manager.rb"
            },
            {
              "pre_context": [
                "      path_to_use = Fastlane::FastlaneFolder.path || Dir.pwd\n",
                "      parameters ||= {}\n",
                "      begin\n"
              ],
              "post_context": [
                "          # Call the platform specific before_all block and then the general one\n",
                "\n",
                "          before_all_blocks[current_platform].call(current_lane, parameters) if before_all_blocks[current_platform] && current_platform\n"
              ],
              "abs_path": "/Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/fastlane-1.49.0/lib/fastlane/runner.rb",
              "function": "execute",
              "lineno": 46,
              "in_app": false,
              "context_line": "        Dir.chdir(path_to_use) do # the file is located in the fastlane folder\n",
              "project_root": null,
              "filename": "fastlane/runner.rb"
            },
            {
              "pre_context": [
                "      path_to_use = Fastlane::FastlaneFolder.path || Dir.pwd\n",
                "      parameters ||= {}\n",
                "      begin\n"
              ],
              "post_context": [
                "          # Call the platform specific before_all block and then the general one\n",
                "\n",
                "          before_all_blocks[current_platform].call(current_lane, parameters) if before_all_blocks[current_platform] && current_platform\n"
              ],
              "abs_path": "/Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/fastlane-1.49.0/lib/fastlane/runner.rb",
              "function": "chdir",
              "lineno": 46,
              "in_app": false,
              "context_line": "        Dir.chdir(path_to_use) do # the file is located in the fastlane folder\n",
              "project_root": null,
              "filename": "fastlane/runner.rb"
            },
            {
              "pre_context": [
                "          before_all_blocks[current_platform].call(current_lane, parameters) if before_all_blocks[current_platform] && current_platform\n",
                "          before_all_blocks[nil].call(current_lane, parameters) if before_all_blocks[nil]\n",
                "\n"
              ],
              "post_context": [
                "\n",
                "          # `after_all` is only called if no exception was raised before\n",
                "          # Call the platform specific before_all block and then the general one\n"
              ],
              "abs_path": "/Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/fastlane-1.49.0/lib/fastlane/runner.rb",
              "function": "block in execute",
              "lineno": 52,
              "in_app": false,
              "context_line": "          return_val = lane_obj.call(parameters) # by default no parameters\n",
              "project_root": null,
              "filename": "fastlane/runner.rb"
            },
            {
              "pre_context": [
                "\n",
                "    # Execute this lane\n",
                "    def call(parameters)\n"
              ],
              "post_context": [
                "    end\n",
                "\n",
                "    # @return [String] The lane + name of the lane. If there is no platform, it will only be the lane name\n"
              ],
              "abs_path": "/Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/fastlane-1.49.0/lib/fastlane/lane.rb",
              "function": "call",
              "lineno": 36,
              "in_app": false,
              "context_line": "      block.call(parameters || {})\n",
              "project_root": null,
              "filename": "fastlane/lane.rb"
            },
            {
              "pre_context": [
                "\n",
                "    # Execute this lane\n",
                "    def call(parameters)\n"
              ],
              "post_context": [
                "    end\n",
                "\n",
                "    # @return [String] The lane + name of the lane. If there is no platform, it will only be the lane name\n"
              ],
              "abs_path": "/Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/fastlane-1.49.0/lib/fastlane/lane.rb",
              "function": "call",
              "lineno": 36,
              "in_app": false,
              "context_line": "      block.call(parameters || {})\n",
              "project_root": null,
              "filename": "fastlane/lane.rb"
            },
            {
              "abs_path": "Fastfile",
              "function": "block (2 levels) in parsing_binding",
              "lineno": 36,
              "in_app": false,
              "project_root": null,
              "filename": "Fastfile"
            },
            {
              "pre_context": [
                "      # confusing\n",
                "      if class_ref && class_ref.respond_to?(:run)\n",
                "        # Action is available, now execute it\n"
              ],
              "post_context": [
                "      else\n",
                "        raise \"Action '#{method_sym}' of class '#{class_name}' was found, but has no `run` method.\".red\n",
                "      end\n"
              ],
              "abs_path": "/Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/fastlane-1.49.0/lib/fastlane/fast_file.rb",
              "function": "method_missing",
              "lineno": 149,
              "in_app": false,
              "context_line": "        return self.runner.execute_action(method_sym, class_ref, arguments)\n",
              "project_root": null,
              "filename": "fastlane/fast_file.rb"
            },
            {
              "pre_context": [
                "      verify_supported_os(method_sym, class_ref)\n",
                "\n",
                "      begin\n"
              ],
              "post_context": [
                "          Actions.execute_action(class_ref.step_text) do\n",
                "            # arguments is an array by default, containing an hash with the actual parameters\n",
                "            # Since we usually just need the passed hash, we'll just use the first object if there is only one\n"
              ],
              "abs_path": "/Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/fastlane-1.49.0/lib/fastlane/runner.rb",
              "function": "execute_action",
              "lineno": 127,
              "in_app": false,
              "context_line": "        Dir.chdir(custom_dir) do # go up from the fastlane folder, to the project folder\n",
              "project_root": null,
              "filename": "fastlane/runner.rb"
            },
            {
              "pre_context": [
                "      verify_supported_os(method_sym, class_ref)\n",
                "\n",
                "      begin\n"
              ],
              "post_context": [
                "          Actions.execute_action(class_ref.step_text) do\n",
                "            # arguments is an array by default, containing an hash with the actual parameters\n",
                "            # Since we usually just need the passed hash, we'll just use the first object if there is only one\n"
              ],
              "abs_path": "/Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/fastlane-1.49.0/lib/fastlane/runner.rb",
              "function": "chdir",
              "lineno": 127,
              "in_app": false,
              "context_line": "        Dir.chdir(custom_dir) do # go up from the fastlane folder, to the project folder\n",
              "project_root": null,
              "filename": "fastlane/runner.rb"
            },
            {
              "pre_context": [
                "\n",
                "      begin\n",
                "        Dir.chdir(custom_dir) do # go up from the fastlane folder, to the project folder\n"
              ],
              "post_context": [
                "            # arguments is an array by default, containing an hash with the actual parameters\n",
                "            # Since we usually just need the passed hash, we'll just use the first object if there is only one\n",
                "            if arguments.count == 0\n"
              ],
              "abs_path": "/Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/fastlane-1.49.0/lib/fastlane/runner.rb",
              "function": "block in execute_action",
              "lineno": 128,
              "in_app": false,
              "context_line": "          Actions.execute_action(class_ref.step_text) do\n",
              "project_root": null,
              "filename": "fastlane/runner.rb"
            },
            {
              "pre_context": [
                "\n",
                "      begin\n",
                "        Helper.log_alert(\"Step: \" + step_name) if step_name\n"
              ],
              "post_context": [
                "      rescue => ex\n",
                "        exc = ex\n",
                "        error = caller.join(\"\\n\") + \"\\n\\n\" + ex.to_s\n"
              ],
              "abs_path": "/Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/fastlane-1.49.0/lib/fastlane/actions/actions_helper.rb",
              "function": "execute_action",
              "lineno": 37,
              "in_app": false,
              "context_line": "        yield\n",
              "project_root": null,
              "filename": "fastlane/actions/actions_helper.rb"
            },
            {
              "pre_context": [
                "              raise \"You have to call the integration like `#{method_sym}(key: \\\"value\\\")`. Run `fastlane action #{method_sym}` for all available keys. Please check out the current documentation on GitHub.\".red\n",
                "            end\n",
                "\n"
              ],
              "post_context": [
                "          end\n",
                "        end\n",
                "      rescue => ex\n"
              ],
              "abs_path": "/Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/fastlane-1.49.0/lib/fastlane/runner.rb",
              "function": "block (2 levels) in execute_action",
              "lineno": 142,
              "in_app": false,
              "context_line": "            class_ref.run(arguments)\n",
              "project_root": null,
              "filename": "fastlane/runner.rb"
            },
            {
              "pre_context": [
                "        Spaceship.select_team\n",
                "\n",
                "        if devices\n"
              ],
              "post_context": [
                "            raise \"Passed invalid UDID: #{v} for device: #{k}\".red unless UDID_REGEXP =~ v\n",
                "            Spaceship::Device.create!(name: k, udid: v)\n",
                "          end\n"
              ],
              "abs_path": "/Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/fastlane-1.49.0/lib/fastlane/actions/register_devices.rb",
              "function": "run",
              "lineno": 24,
              "in_app": false,
              "context_line": "          device_objs = devices.map do |k, v|\n",
              "project_root": null,
              "filename": "fastlane/actions/register_devices.rb"
            },
            {
              "pre_context": [
                "        Spaceship.select_team\n",
                "\n",
                "        if devices\n"
              ],
              "post_context": [
                "            raise \"Passed invalid UDID: #{v} for device: #{k}\".red unless UDID_REGEXP =~ v\n",
                "            Spaceship::Device.create!(name: k, udid: v)\n",
                "          end\n"
              ],
              "abs_path": "/Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/fastlane-1.49.0/lib/fastlane/actions/register_devices.rb",
              "function": "map",
              "lineno": 24,
              "in_app": false,
              "context_line": "          device_objs = devices.map do |k, v|\n",
              "project_root": null,
              "filename": "fastlane/actions/register_devices.rb"
            },
            {
              "pre_context": [
                "        Spaceship.select_team\n",
                "\n",
                "        if devices\n"
              ],
              "post_context": [
                "            raise \"Passed invalid UDID: #{v} for device: #{k}\".red unless UDID_REGEXP =~ v\n",
                "            Spaceship::Device.create!(name: k, udid: v)\n",
                "          end\n"
              ],
              "abs_path": "/Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/fastlane-1.49.0/lib/fastlane/actions/register_devices.rb",
              "function": "each",
              "lineno": 24,
              "in_app": false,
              "context_line": "          device_objs = devices.map do |k, v|\n",
              "project_root": null,
              "filename": "fastlane/actions/register_devices.rb"
            },
            {
              "pre_context": [
                "        if devices\n",
                "          device_objs = devices.map do |k, v|\n",
                "            raise \"Passed invalid UDID: #{v} for device: #{k}\".red unless UDID_REGEXP =~ v\n"
              ],
              "post_context": [
                "          end\n",
                "        elsif devices_file\n",
                "          require 'csv'\n"
              ],
              "abs_path": "/Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/fastlane-1.49.0/lib/fastlane/actions/register_devices.rb",
              "function": "block in run",
              "lineno": 26,
              "in_app": false,
              "context_line": "            Spaceship::Device.create!(name: k, udid: v)\n",
              "project_root": null,
              "filename": "fastlane/actions/register_devices.rb"
            },
            {
              "pre_context": [
                "\n",
                "          # Find the device by UDID, raise an exception if it already exists\n",
                "          if self.find_by_udid(udid, mac: mac)\n"
              ],
              "post_context": [
                "          end\n",
                "\n",
                "          # It is valid to have the same name for multiple devices\n"
              ],
              "abs_path": "/Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/spaceship-0.19.0/lib/spaceship/portal/device.rb",
              "function": "create!",
              "lineno": 151,
              "in_app": false,
              "context_line": "            raise \"The device UDID '#{udid}' already exists on this team.\"\n",
              "project_root": null,
              "filename": "spaceship/portal/device.rb"
            }
          ]
        }
      }
    ]
  }
}

```

**Comment by skywinder** [comment] 2016-01-12 18:07
lane looks like this 

```
 lane :reg do
        register_devices(
            devices: {
                "iphone6 64gb"=>'4a7601a6063d9e2017c3aceece33fc127e9e7333',
            }
        )
    end

```

**Comment by nickoneill** [comment] 2016-02-02 01:31
I'm seeing this as well on one of my teams. Was there any resolution for you, @skywinder?

**Comment by skywinder** [comment] 2016-02-02 09:32
@nickoneill just exclude registered devices from the list.. not convenient, but there is no any other solutions yet.

**Comment by KrauseFx** [comment] 2016-02-03 19:55
I just pushed a fix, this will be fixed in the next spaceship / fastlane release :+1:

**Closed** 2016-02-03 19:55 UTC

**Comment by nickoneill** [comment] 2016-02-03 20:03
Thanks!

**Comment by brad** [comment] 2016-02-27 02:37
I have fastlane 1.63.1 and I'm still seeing this issue. Crash id 49bcfb9d4f3c36a5b81d327221fb78b7

**Comment by brad** [comment] 2016-02-27 04:34
Sorry, my mistake. It looks like I've encountered a separate issue https://github.com/fastlane/fastlane/issues/1429
