### ISSUE TITLE
Developer Portal not available

### ISSUE THREAD

**Issue by petersuwara** [fastlane/fastlane#8227] opened 2017-02-14 01:52 UTC
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
The content of the the fastfile includes the following :
  match(type:"appstore")

During builds it can take 2-3 attempts to complete the match operation through all App IDs as the following error appears at intermittent intervals.

[12:47:21]: Installing provisioning profile...
[12:47:22]: Installing provisioning profile...
[12:47:23]: An error occured while verifying your certificates and profiles with the Apple Developer Portal.
[12:47:23]: If you already have your certificates stored in git, you can run `match` in readonly mode
[12:47:23]: to just install the certificates and profiles without accessing the Dev Portal.
[12:47:23]: To do so, just pass `readonly: true` to your match call.
[12:47:23]: 🔒  Successfully encrypted certificates repo

Difficult to reproduce. 

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[12:47:25]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.15.0/spaceship/lib/spaceship/client.rb:453:in `parse_response': [!] <?xml version="1.0" encoding="UTF-8"?> (Spaceship::Client::UnexpectedResponse)
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
     <key>resultCode</key>
     <integer>503</integer>
     <key>userString</key>
     <string>The Apple Developer website is undergoing maintenance. For details, visit developer.apple.com/system-status.</string>
     <key>resultString</key>
     <string>The Apple Developer website is undergoing maintenance. For details, visit developer.apple.com/system-status.</string>
     <key>httpCode</key>
     <integer>503</integer>
     <key>userLocale</key>
     <string>en_US</string>
  </dict>
</plist>

	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.15.0/spaceship/lib/spaceship/portal/portal_client.rb:464:in `provisioning_profiles'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.15.0/spaceship/lib/spaceship/portal/provisioning_profile.rb:263:in `all'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.15.0/match/lib/match/spaceship_ensure.rb:54:in `profile_exists'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.15.0/match/lib/match/runner.rb:142:in `fetch_provisioning_profile'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.15.0/match/lib/match/runner.rb:40:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.15.0/match/lib/match/runner.rb:39:in `loop'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.15.0/match/lib/match/runner.rb:39:in `block in run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.15.0/match/lib/match/runner.rb:38:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.15.0/match/lib/match/runner.rb:38:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.15.0/fastlane/lib/fastlane/actions/match.rb:8:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.15.0/fastlane/lib/fastlane/runner.rb:243:in `block (2 levels) in execute_action'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.15.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.15.0/fastlane/lib/fastlane/runner.rb:221:in `block in execute_action'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.15.0/fastlane/lib/fastlane/runner.rb:217:in `chdir'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.15.0/fastlane/lib/fastlane/runner.rb:217:in `execute_action'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.15.0/fastlane/lib/fastlane/runner.rb:139:in `trigger_action_by_name'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.15.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:62:in `block (2 levels) in parsing_binding'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.15.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.15.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.15.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.15.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.15.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.15.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.15.0/fastlane/lib/fastlane/commands_generator.rb:105:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.15.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.15.0/fastlane/lib/fastlane/commands_generator.rb:302:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.15.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.15.0/fastlane/lib/fastlane/cli_tools_distributor.rb:63:in `take_off'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.15.0/bin/fastlane:15:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.3                                     |
| Ruby                | 2.4.0                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | /usr/local/bin/fastlane                     |
| Host                | Mac OS X 10.12.3 (16D32)                    |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.4.0/lib            |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Is homebrew         | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_AU.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.3.0"

default_platform :ios

ENV["XCODEPROJECT"] = "Solution.xcodeproj"
ENV["WORKSPACE"] = "Solution.xcworspace"

platform :ios do
  before_all do
    UI.message "Initialising lanes"
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  lane :inc_major do
    increment_version_number(bump_type: "major")
    increment_build_number(build_number: "0")
  end

  lane :inc_minor do
    increment_version_number(bump_type: "minor")
    increment_build_number(build_number: "0")
  end

  lane :inc_patch do
    increment_version_number(bump_type: "patch")
    increment_build_number(build_number: "0")
  end

  lane :certificates do
    match(type: "development", readonly: true)
    match(type: "appstore", readonly: true)
  end

  desc "Do a build for testing, no submission to testflight"
  lane :on_commit do |options|
    cocoapods
    #match(type: "appstore")
    gym(scheme: "V2 - Demo")
  end

  desc "Do a build for testing, no submission to testflight"
  lane :daily do |options|
    cocoapods
    #match(type: "appstore")
    increment_build_number
    gym(scheme: "V2 - Demo")
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do |options|
    cocoapods

    #match(type: "appstore") # more information: https://codesigning.guide
    increment_build_number
    gym(scheme: "V2 - Demo") # Build your app - more options available


    if options[:skip_submission]
      UI.message "Skipping submission, will only upload IPA"
      pilot(skip_submission: "true")
    else
      UI.message "Will submit and distribute IPA"
      pilot
    end

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    cocoapods

    # match(type: "appstore")
    # snapshot
    gym(scheme: "V2 - Demo") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    UI.message "Lane completed successfully"
    # This block is called, only if the executed lane was successful
    ENV['BUILD_VER'] = get_info_plist_value({key: "CFBundleShortVersionString", path: "Solution/Info.plist"})
    ENV['BUILD_ID']  = get_info_plist_value({key: "CFBundleVersion", path: "Solution/Info.plist"})
    slack(
        message: "Successfully built iOS application \"V2 - Demo\" Ver: #{ENV['BUILD_VER']}. Build: #{ENV['BUILD_ID']}."
    )

    if lane != :on_commit && lane != :certificates
        commit_version_bump(
            message: "Build Complete #{lane}. Ver: #{ENV['BUILD_VER']}. Build: #{ENV['BUILD_ID']}",
            force: true,
            xcodeproj: ENV["XCODEPROJECT"]
        )

        push_to_git_remote
    end
  end

  error do |lane, exception|
  slack(
      message: exception.message,
      success: false
  )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.secureone.v2.demo" # The bundle identifier of your app
apple_id "peter.suwara@verrency.com" # Your Apple email address

team_id "B2NTP3ZB4X"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.15.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.8.0        |
| json                      | 1.8.6        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.10.1       |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.55.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.4       |
| faraday_middleware        | 0.11.0.1     |
| io-console                | 0.4.6        |
| openssl                   | 2.0.2        |
</details>

*generated on:* **2017-02-14**
</details>

**Comment by KrauseFx** [comment] 2017-02-14 02:09
Duplicate of https://github.com/fastlane/fastlane/issues/8208 and https://github.com/fastlane/fastlane/issues/8209, unfortunately that's out of our control when Apple's web services are not available.

You can always run _match_ in readonly mode using `match(readonly: true)`, this way it doesn't try to fetch the latest profiles from the Developer Portal.

**Comment by petersuwara** [comment] 2017-02-14 02:23
Why does it fall over like that even when the services are available ? I mean it's not like the service is down for scheduled updates. It's just that the service cannot be connected to at intermittent intervals. I can run it again 5 seconds later and it would work.

**Comment by KrauseFx** [comment] 2017-02-14 02:35
@petersuwara It's out of our control that the Apple Developer Services are in maintenance mode, sorry.

**Comment by petersuwara** [comment] 2017-02-14 03:09
@KrauseFx I really appreciate how you guys are very responsive. Great work.

It seems like a very strange and recent issue.

I can see that other are in a much more critical position than us. I have already setup the certificates on our build system so can comment these out for now until we get more clarity.

**Comment by KrauseFx** [comment] 2017-02-14 07:19
Sounds good, thanks 👍 Glad to hear you found a temporary solution until all servers are back up again

**Closed by KrauseFx** 2017-02-14 07:19 UTC
