### ISSUE TITLE
Improve macOS support across fastlane family

### ISSUE THREAD

**Issue by ianbytchek** [fastlane/fastlane#8178] opened 2017-02-08 17:09 UTC
This has been thrown back and forth for so long, there are a few pull requests, that never made it into master and even more issues that @fastlane-bot closed due for inactivity and some hacky workarounds. Some comments indicate that this is an easy fix, but everything indicates there's some deeper issue. What's the deal with this? Is it possible or too difficult or something else?

My end mission is to submit my app for review on MAS, deliver action requires pkg file, gym only produces app despite package (or app store) export method being specified.

Gym stood out the most with not allowing to create / export mac package, so instead I'm just using xcarchive action to do that:
https://github.com/fastlane/fastlane/pull/6774
https://github.com/fastlane/fastlane/pull/4246

Deliver also requires some hacking around:
https://github.com/fastlane/fastlane/issues/6673#issuecomment-256959890

Another minor issue that came up recently is the confusion between platform name in deliver and everywhere else:
https://github.com/fastlane/fastlane/issues/7168

**Comment by hjanuschka** [comment] 2017-02-08 18:40
hey @ianbytchek  can you try building the app with gym, which should result in a `myapp.app` 
and later on call this:

```ruby
sh(command: "productbuild --component path/to/myapp.app /Applications ./package.pkg --sign 'Your Signing Identity'")
```

**Comment by KrauseFx** [comment] 2017-02-13 23:42
It would be so cool to support mac apps with _fastlane_, however we don't plan on fully supporting macOS for _fastlane_ for now. The main reason is that it's a mobile app developer tool that's aimed for iOS and Android app developers. 

The problem isn't so much about getting the code now, but guaranteeing that it keeps working in future releases and maintaining it.

**Comment by lacostej** [comment] 2017-02-14 21:00
I started back-porting our older products build pipeline into fastlane today. Some of them have Mac / AppStore support. Could you edit the description of this issue with the links to the PR/issues that related to the overall mac support?

**Comment by ianbytchek** [comment] 2017-02-15 16:45
@lacostej done.

**Comment by ohayon** [comment] 2017-02-28 15:31
Hey @ianbytchek, if i could weigh in here a bit about further macOS support; We *_love_* the fact that you are interested in fixing/adding to _fastlane_ to make it better all around at macOS work. That being said, if you take a look at our [VISION.md](https://github.com/fastlane/fastlane/blob/master/VISION.md), our goal is to be the sharpest tool in the mobile development shed rather than create a bigger foundation for desktop as well. I am going to close the issue for now, as this is more of a feature request, but please feel free to continue discussion here. Thanks! 🚀 🐙

**Closed by ohayon** 2017-02-28 15:31 UTC
