### ISSUE TITLE
Deliver error because of new updates for Screenshot policy on iTunesConnect

### ISSUE THREAD

**Issue by prgnshptlklp** [fastlane/fastlane#5675] opened 2016-08-10 07:34 UTC
I have taken iPhone 6s Plus and iPad Pro Screenshots using Snapshot and uploaded using deliver.

[!] The request could not be completed because:
	You must provide a screenshot or choose to inherit from a larger size. You must provide a screenshot or choose to inherit from a larger size. You must provide a screenshot or choose to inherit from a larger size. You must provide a screenshot or choose to inherit from a larger size. You must provide a screenshot or choose to inherit from a larger size. You must provide a screenshot or choose to inherit from a larger size.

**Comment by iOSAppMaker** [comment] 2016-08-10 16:35
Same problem. I checked iTunes as it shows a new screen size 12.9 inch iPad in addition to the already existing 9.7 inch iPad screensize. 

Does snapshot support the new screensizes?? 
I think also changes are needed for spaceship submit to submit screenshots because now there is a new option to check "Yse 12.9 inch Display" after adding screenshots for each size to save them for itunes use.

**Comment by iOSAppMaker** [comment] 2016-08-10 16:44
Sorry, the 12.9 inch iPad Pro screensize already existed, I just hadn' included them. Anyway, there is anew "Use #{inch_size} inch Display" option that has to be checked in iTunes.

**Comment by KrauseFx** [comment] 2016-08-10 17:41
Thanks for the report, I'll try to reproduce the error 👍

**Comment by KrauseFx** [comment] 2016-08-10 21:43
I prepared 2 PRs for this: https://github.com/fastlane/fastlane/pull/5698 and https://github.com/fastlane/fastlane/pull/5699.

I'll prepare a new release, as soon as we have more testers and I got a code review 👍

**Closed** 2016-08-11 16:52 UTC
Labels: deliver, spaceship

**Comment by aniaMu** [comment] 2016-08-12 22:02
Since handling localization is a similar issue when uploading screenshots, I'll add this info here:
`You must provide a screenshot or choose to inherit from your primary localization.`
Hopefully you can take it into account in your update.

**Comment by dellheng** [comment] 2016-08-18 06:39
@aniaMu +1

**Comment by TKBurner** [comment] 2016-08-22 20:18
@aniaMu Thanks for reaching out about this. It should be corrected now if you run `sudo gem update fastlane`. Let me know how it goes!
