### ISSUE TITLE
Scan: Without Fastfile: undefined method `downcase' for nil:NilClass (NoMethodError) on 2.105.0

### ISSUE THREAD

**Issue by fabb** [fastlane/fastlane#13411] opened 2018-09-21 09:05 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

`fastlane scan` fails on 2.105.0. It succeeds on 2.104.0.

ℹ️ Note that I don't have a `Fastfile`, and this seems to cause the issue. When I create an empty `Fastfile`, everything works fine. It seems like in `fastlane_folder.rb` the case of a `nil` `Fastfile` was not anticipated.

##### Complete output when running fastlane, including the stack trace and command used

```
$ fastlane scan --workspace myproject.xcworkspace --scheme myproject --output_types junit --output_files myproject.xml --output_directory reports/junit --device 'iPad Air 2'

NoMethodError: [!] undefined method `downcase' for nil:NilClass
  /path/to/project/vendor/bundle/ruby/2.3.0/gems/fastlane-2.105.0/fastlane_core/lib/fastlane_core/fastlane_folder.rb:24:in `swift?'
  /path/to/project/vendor/bundle/ruby/2.3.0/gems/fastlane-2.105.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:71:in `run!'
  /path/to/project/vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /path/to/project/vendor/bundle/ruby/2.3.0/gems/fastlane-2.105.0/scan/lib/scan/commands_generator.rb:75:in `run'
  /path/to/project/vendor/bundle/ruby/2.3.0/gems/fastlane-2.105.0/scan/lib/scan/commands_generator.rb:15:in `start'
  /path/to/project/vendor/bundle/ruby/2.3.0/gems/fastlane-2.105.0/fastlane/lib/fastlane/cli_tools_distributor.rb:100:in `take_off'
  /path/to/project/vendor/bundle/ruby/2.3.0/gems/fastlane-2.105.0/bin/fastlane:20:in `<top (required)>'
  /path/to/project/vendor/bundle/ruby/2.3.0/bin/fastlane:22:in `load'
  /path/to/project/vendor/bundle/ruby/2.3.0/bin/fastlane:22:in `<top (required)>'
```

### Environment

I cannot run `fastlane env` just because of the same error described above 😬

**Comment by Syrou** [comment] 2018-09-21 09:15
Can't even run fastlane init myself

**Comment by ff-ahumberston** [comment] 2018-09-21 10:32
This is a duplicate of #13403, but I can confirm dropping a Fastlane/fastfile into the working directory will workaround the issue.

**Comment by joshdholtz** [comment] 2018-09-21 11:28
`2.105.1` is out now and has the fix for this issue 🚀

**Closed** 2018-09-21 11:29 UTC
