### ISSUE TITLE
Deliver from Travis CI is timing out

### ISSUE THREAD

**Issue by levibostian** [fastlane/fastlane#15508] opened 2019-10-16 20:50 UTC
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Travis CI fails to run `deliver` past `Going to upload updated app to App Store Connect. This might take a few minutes. Please don't interrupt the script.` step. Travis fails the CI job at this step. 

This issue is a duplicate of [this issue](https://github.com/fastlane/fastlane/issues/14909). I commented on the issue as I encountered the same issue back then (in June) and am making this new issue since it is happening again, today. 

Helpful info:
* `deliver` on Travis has been working great with no issues for a couple years until late June 2019 when the original GitHub issue was created. About a week later, the issue went away and I was able to use `deliver` normally on Travis again. 
* Back in June 2019 when I had the original issue and today when I have encountered the Travis issue again, I am able to successfully run `deliver` from my local computer without any problems. I have never encountered this issue on my local machine, only Travis. 
* Since June 2019, I have encountered this issue maybe 10% of the time when I deploy on Travis. I would simply restart the CI job and the 2nd try `deliver` would work just fine. Today, however, I have restarted the CI job 4 times with all 4 failing with the same error. I then run the fastlane job on my local machine and it works first try. 

The [original GitHub issue](https://github.com/fastlane/fastlane/issues/14909) mentions the possibility that Travis may take > 10 minutes to upload the build to Apple. For reference, here are the timestamps for running `deliver` successfully from my local computer to show it taking < 10 minutes for me locally. 

```
[14:31:41]: Making sure the latest version on App Store Connect matches '0.5.15' from the ipa file...
[14:31:42]: '0.5.15' is the latest version on App Store Connect
[14:31:44]: Loading './fastlane/metadata/en-US/description.txt'...
[14:31:44]: Loading './fastlane/metadata/en-US/keywords.txt'...
[14:31:44]: Loading './fastlane/metadata/en-US/support_url.txt'...
[14:31:44]: Loading './fastlane/metadata/en-US/promotional_text.txt'...
[14:31:44]: Loading './fastlane/metadata/en-US/name.txt'...
[14:31:44]: Loading './fastlane/metadata/en-US/subtitle.txt'...
[✔] Activating language en-US...
[14:31:49]: Setting the app's age rating...
[✔] Uploading metadata to App Store Connect
[14:31:51]: Successfully uploaded set of metadata to App Store Connect
[14:31:53]: Starting with the upload of screenshots...
[14:31:53]: Removing all previously uploaded screenshots...
[14:31:53]: Successfully uploaded screenshots to App Store Connect
[14:31:53]: Price Tier unchanged (tier 0)
[14:31:55]: Uploading app icon...
[14:31:58]: Uploading binary to App Store Connect
[14:32:00]: Going to upload updated app to App Store Connect
[14:32:00]: This might take a few minutes. Please don't interrupt the script.
[14:40:51]: iTunes Transporter successfully finished its job
[14:40:51]: ------------------------------------------------------------------------------------------------------------------
[14:40:51]: --- Successfully uploaded package to App Store Connect. It might take a few minutes until it's visible online. ---
[14:40:51]: ------------------------------------------------------------------------------------------------------------------
[14:40:51]: Finished the upload to App Store Connect
```

##### Complete output when running fastlane, including the stack trace and command used
See original GitHub issue. 

### Environment

I couldn't figure out how to do this on Travis since it uses Tmate as ssh sessions and I can't copy/paste from there. 

The travis environment is: 
```
os: osx
osx_image: xcode10.2
language: swift	
```

With Gemfile.lock
```
GIT
  remote: https://github.com/levibostian/CocoaCache
  revision: 799518993dec30b702f608204878ab5e836137d3
  ref: 799518993d
  specs:
    cocoacache (0.1.0)
      colored2 (~> 3.1)

GEM
  remote: https://rubygems.org/
  specs:
    CFPropertyList (3.0.1)
    activesupport (4.2.11.1)
      i18n (~> 0.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    addressable (2.7.0)
      public_suffix (>= 2.0.2, < 5.0)
    atomos (0.1.3)
    babosa (1.0.3)
    backports (3.15.0)
    claide (1.0.3)
    claide-plugins (0.9.2)
      cork
      nap
      open4 (~> 1.3)
    cocoapods (1.7.5)
      activesupport (>= 4.0.2, < 5)
      claide (>= 1.0.2, < 2.0)
      cocoapods-core (= 1.7.5)
      cocoapods-deintegrate (>= 1.0.3, < 2.0)
      cocoapods-downloader (>= 1.2.2, < 2.0)
      cocoapods-plugins (>= 1.0.0, < 2.0)
      cocoapods-search (>= 1.0.0, < 2.0)
      cocoapods-stats (>= 1.0.0, < 2.0)
      cocoapods-trunk (>= 1.3.1, < 2.0)
      cocoapods-try (>= 1.1.0, < 2.0)
      colored2 (~> 3.1)
      escape (~> 0.0.4)
      fourflusher (>= 2.3.0, < 3.0)
      gh_inspector (~> 1.0)
      molinillo (~> 0.6.6)
      nap (~> 1.0)
      ruby-macho (~> 1.4)
      xcodeproj (>= 1.10.0, < 2.0)
    cocoapods-check (1.1.0)
      cocoapods (~> 1.0)
    cocoapods-core (1.7.5)
      activesupport (>= 4.0.2, < 6)
      fuzzy_match (~> 2.0.4)
      nap (~> 1.0)
    cocoapods-deintegrate (1.0.4)
    cocoapods-downloader (1.2.2)
    cocoapods-plugins (1.0.0)
      nap
    cocoapods-search (1.0.0)
    cocoapods-stats (1.1.0)
    cocoapods-trunk (1.3.1)
      nap (>= 0.8, < 2.0)
      netrc (~> 0.11)
    cocoapods-try (1.1.0)
    colored (1.2)
    colored2 (3.1.2)
    colorize (0.8.1)
    commander-fastlane (4.4.6)
      highline (~> 1.7.2)
    concurrent-ruby (1.1.5)
    connection_pool (2.2.2)
    cork (0.3.0)
      colored2 (~> 3.1)
    danger (6.0.9)
      claide (~> 1.0)
      claide-plugins (>= 0.9.2)
      colored2 (~> 3.1)
      cork (~> 0.1)
      faraday (~> 0.9)
      faraday-http-cache (~> 2.0)
      git (~> 1.5)
      kramdown (~> 2.0)
      kramdown-parser-gfm (~> 1.0)
      no_proxy_fix
      octokit (~> 4.7)
      terminal-table (~> 1)
    danger-ios_version_change (0.1.7)
      danger-plugin-api (~> 1.0)
    danger-plugin-api (1.0.0)
      danger (> 2.0)
    danger-swiftlint (0.23.0)
      danger
      rake (> 10)
      thor (~> 0.19)
    declarative (0.0.10)
    declarative-option (0.1.0)
    digest-crc (0.4.1)
    domain_name (0.5.20190701)
      unf (>= 0.0.5, < 1.0.0)
    dotenv (2.7.5)
    emoji_regex (1.0.1)
    escape (0.0.4)
    ethon (0.12.0)
      ffi (>= 1.3.0)
    excon (0.67.0)
    faraday (0.17.0)
      multipart-post (>= 1.2, < 3)
    faraday-cookie_jar (0.0.6)
      faraday (>= 0.7.4)
      http-cookie (~> 1.0.0)
    faraday-http-cache (2.0.0)
      faraday (~> 0.8)
    faraday_middleware (0.13.1)
      faraday (>= 0.7.4, < 1.0)
    fastimage (2.1.7)
    fastlane (2.134.0)
      CFPropertyList (>= 2.3, < 4.0.0)
      addressable (>= 2.3, < 3.0.0)
      babosa (>= 1.0.2, < 2.0.0)
      bundler (>= 1.12.0, < 3.0.0)
      colored
      commander-fastlane (>= 4.4.6, < 5.0.0)
      dotenv (>= 2.1.1, < 3.0.0)
      emoji_regex (>= 0.1, < 2.0)
      excon (>= 0.45.0, < 1.0.0)
      faraday (~> 0.17)
      faraday-cookie_jar (~> 0.0.6)
      faraday_middleware (~> 0.13.1)
      fastimage (>= 2.1.0, < 3.0.0)
      gh_inspector (>= 1.1.2, < 2.0.0)
      google-api-client (>= 0.21.2, < 0.24.0)
      google-cloud-storage (>= 1.15.0, < 2.0.0)
      highline (>= 1.7.2, < 2.0.0)
      json (< 3.0.0)
      jwt (~> 2.1.0)
      mini_magick (>= 4.9.4, < 5.0.0)
      multi_xml (~> 0.5)
      multipart-post (~> 2.0.0)
      plist (>= 3.1.0, < 4.0.0)
      public_suffix (~> 2.0.0)
      rubyzip (>= 1.3.0, < 2.0.0)
      security (= 0.1.3)
      simctl (~> 1.6.3)
      slack-notifier (>= 2.0.0, < 3.0.0)
      terminal-notifier (>= 2.0.0, < 3.0.0)
      terminal-table (>= 1.4.5, < 2.0.0)
      tty-screen (>= 0.6.3, < 1.0.0)
      tty-spinner (>= 0.8.0, < 1.0.0)
      word_wrap (~> 1.0.0)
      xcodeproj (>= 1.8.1, < 2.0.0)
      xcpretty (~> 0.3.0)
      xcpretty-travis-formatter (>= 0.0.3)
    fastlane-plugin-appicon (0.14.1)
      json
      mini_magick (>= 4.9.4, < 5.0.0)
    fastlane-plugin-resize_screenshots (0.1.0)
      mini_magick
    ffi (1.11.1)
    fourflusher (2.3.1)
    fuzzy_match (2.0.4)
    gh (0.14.0)
      addressable
      backports
      faraday (~> 0.8)
      multi_json (~> 1.0)
      net-http-persistent (>= 2.7)
      net-http-pipeline
    gh_inspector (1.1.3)
    git (1.5.0)
    google-api-client (0.23.9)
      addressable (~> 2.5, >= 2.5.1)
      googleauth (>= 0.5, < 0.7.0)
      httpclient (>= 2.8.1, < 3.0)
      mime-types (~> 3.0)
      representable (~> 3.0)
      retriable (>= 2.0, < 4.0)
      signet (~> 0.9)
    google-cloud-core (1.3.1)
      google-cloud-env (~> 1.0)
    google-cloud-env (1.2.1)
      faraday (~> 0.11)
    google-cloud-storage (1.16.0)
      digest-crc (~> 0.4)
      google-api-client (~> 0.23)
      google-cloud-core (~> 1.2)
      googleauth (>= 0.6.2, < 0.10.0)
    googleauth (0.6.7)
      faraday (~> 0.12)
      jwt (>= 1.4, < 3.0)
      memoist (~> 0.16)
      multi_json (~> 1.11)
      os (>= 0.9, < 2.0)
      signet (~> 0.7)
    highline (1.7.10)
    http-cookie (1.0.3)
      domain_name (~> 0.5)
    httpclient (2.8.3)
    i18n (0.9.5)
      concurrent-ruby (~> 1.0)
    json (2.2.0)
    jwt (2.1.0)
    kramdown (2.1.0)
    kramdown-parser-gfm (1.1.0)
      kramdown (~> 2.0)
    launchy (2.4.3)
      addressable (~> 2.3)
    memoist (0.16.0)
    mime-types (3.3)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2019.1009)
    mini_magick (4.9.5)
    minitest (5.11.3)
    molinillo (0.6.6)
    multi_json (1.14.1)
    multi_xml (0.6.0)
    multipart-post (2.0.0)
    nanaimo (0.2.6)
    nap (1.1.0)
    naturally (2.2.0)
    net-http-persistent (3.1.0)
      connection_pool (~> 2.2)
    net-http-pipeline (1.0.1)
    net-ssh (5.2.0)
    netrc (0.11.0)
    no_proxy_fix (0.1.2)
    octokit (4.14.0)
      sawyer (~> 0.8.0, >= 0.5.3)
    open4 (1.3.4)
    os (1.0.1)
    plist (3.5.0)
    public_suffix (2.0.5)
    pusher-client (0.6.2)
      json
      websocket (~> 1.0)
    rake (12.3.3)
    representable (3.0.4)
      declarative (< 0.1.0)
      declarative-option (< 0.2.0)
      uber (< 0.2.0)
    rest-client (2.0.2)
      http-cookie (>= 1.0.2, < 2.0)
      mime-types (>= 1.16, < 4.0)
      netrc (~> 0.8)
    retriable (3.1.2)
    rouge (2.0.7)
    ruby-macho (1.4.0)
    rubyzip (1.3.0)
    sawyer (0.8.2)
      addressable (>= 2.3.5)
      faraday (> 0.8, < 2.0)
    security (0.1.3)
    signet (0.12.0)
      addressable (~> 2.3)
      faraday (~> 0.9)
      jwt (>= 1.5, < 3.0)
      multi_json (~> 1.10)
    simctl (1.6.6)
      CFPropertyList
      naturally
    slack-notifier (2.3.2)
    terminal-notifier (2.0.0)
    terminal-table (1.8.0)
      unicode-display_width (~> 1.1, >= 1.1.1)
    thor (0.20.3)
    thread_safe (0.3.6)
    travis (1.8.10)
      backports
      faraday (~> 0.9)
      faraday_middleware (~> 0.9, >= 0.9.1)
      gh (~> 0.13)
      highline (~> 1.6)
      launchy (~> 2.1)
      pusher-client (~> 0.4)
      typhoeus (~> 0.6, >= 0.6.8)
    trent (0.3.0)
      colorize (~> 0.8, >= 0.8.1)
      net-ssh (~> 5.0, >= 5.0.2)
      travis (~> 1.8, >= 1.8.2)
    tty-cursor (0.7.0)
    tty-screen (0.7.0)
    tty-spinner (0.9.1)
      tty-cursor (~> 0.7)
    typhoeus (0.8.0)
      ethon (>= 0.8.0)
    tzinfo (1.2.5)
      thread_safe (~> 0.1)
    uber (0.1.0)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.7.6)
    unicode-display_width (1.6.0)
    websocket (1.2.8)
    word_wrap (1.0.0)
    xcodeproj (1.12.0)
      CFPropertyList (>= 2.3.3, < 4.0)
      atomos (~> 0.1.3)
      claide (>= 1.0.2, < 2.0)
      colored2 (~> 3.1)
      nanaimo (~> 0.2.6)
    xcpretty (0.3.0)
      rouge (~> 2.0.7)
    xcpretty-travis-formatter (1.0.0)
      xcpretty (~> 0.2, >= 0.0.7)

PLATFORMS
  ruby

DEPENDENCIES
  cocoacache!
  cocoapods (~> 1.7.5)
  cocoapods-check (~> 1.0)
  danger (~> 6.0.9)
  danger-ios_version_change (~> 0.1.6)
  danger-swiftlint (~> 0.23.0)
  fastlane
  fastlane-plugin-appicon
  fastlane-plugin-resize_screenshots
  rest-client (~> 2.0)
  trent (~> 0.3.0)

BUNDLED WITH
   1.17.3
```

**Comment by joshavant** [comment] 2019-10-28 22:12
Also experiencing this issue, with nearly all the same details. (Used to work fine, started randomly timing out, recently has started to always fail).

Watching.

**Comment by levibostian** [comment] 2019-10-28 22:35
@joshavant you mention that the issue has *nearly* all of the same details. To help resolve this issue, could you give some insight as to what is different from your experience from mine?

**Comment by joshavant** [comment] 2019-10-28 23:10
I can't corroborate anything around June 2019, as we setup our Travis deployment in late September. Also, we didn't have enough of a sample size to confirm any specific percentage of failing builds when things were 'working' (although, we did have a nonzero amount of randomly failing builds).

**Comment by joshavant** [comment] 2019-10-28 23:12
I can't corroborate anything around June 2019, as we setup our Travis deployment in late September. Also, we didn't have enough of a sample size to confirm any specific percentage of failing builds when things were 'working' (although, we did have a nonzero amount of randomly failing builds). But for all the aspects you described that do apply to our situation, everything matches.

**Comment by joshavant** [comment] 2019-11-27 02:39
I ended up finding a solution to this. The root cause was that the upload of our build took more than 10 minutes.

The way Fastlane is currently implemented, during the part of the process where the file is being transferred over the network to Apple, no console updates are emitted. If this process takes more than 10 minutes, it will cause Travis to timeout.

You can confirm the amount of time your build takes by running a Travis build in Debug mode (which does not enforce the 10 minute timeout), connecting to the SSH session, observing the Fastlane run, and checking the console message timestamps when the upload starts + completes. Ours was within a few seconds of 10 minutes.

Right now, it seems that the only way to getting Fastlane to emit any console messages during the upload process is running Fastlane in verbose mode ([docs](https://docs.fastlane.tools/codesigning/troubleshooting/#fastlane)).

Sure enough, when we ran Fastlane in verbose mode, the Travis timeouts stopped and everything started working as expected.

**Comment by levibostian** [comment] 2019-11-27 12:41
I say that is worth me giving that a try, @joshavant. Thanks! 

I have started to find random situations recently where Travis stalls during other commands that I run (even just `bundle install`!). Makes me think that Travis has some sort of network inconsistency issue. 

But, your solution gets us by this issue. Thanks! I'll give that a shot! Considering verbose mode is not that much more chatty.

**Closed** 2020-01-04 17:32 UTC
Labels: status: waiting-for-reply, tool: deliver, type: ci
