### ISSUE TITLE
Create ipa with dsym symbols included

### ISSUE THREAD

**Issue by barbelith** [fastlane/fastlane#432] opened 2015-07-21 14:31 UTC
I'm using crashlytics, and when I upload an ipa for beta testing, it does not have the dsym symbols, and crashlytics asks for them when there is a crash

```
  ipa({
      workspace: ENV['WORKSPACE'],
      configuration: 'Release',
      scheme: ENV['SCHEME'],
      ipa: ENV['SCHEME'] + ".ipa"
    })
```

The ipa action generates the dsym file and the ipa file, but crashlytics does not have a way to upload the symbols with their api

**Comment by KrauseFx** [comment] 2015-07-22 09:20
The dsym file for Crashlytics is uploaded automatically by the Mac app as far as I know. That's the code that is used by `shenzhen` to upload the `ipa` file: https://github.com/nomad/shenzhen/blob/master/lib/shenzhen/plugins/crashlytics.rb

This works fine for all users. Can you make sure to have Crashlytics properly set up (Build Phase) and have the Crashlytics Mac app running?

**Comment by barbelith** [comment] 2015-07-22 09:29
Yes, I have the fabric app running, because it detects the archive when the compilation is finished and the archive is generated and prompts me to upload it in the menu bar. 
And if I upload the app via the app it goes with the symbols, but not using the command line tool.

I use crashlytics via cocoapods 
```
  pod 'Fabric'
  pod 'Crashlytics'
```

The code I use for crashlytics is 
```
   crashlytics({
      crashlytics_path: './Pods/Crashlytics/Crashlytics.framework',
      api_token: ENV['CRASHLYTICS_API_TOKEN'],
      build_secret: ENV['CRASHLYTICS_BUILD_SECRET'],
      ipa_path: ENV['SCHEME'] + ".ipa",
      groups: "Expansoft",
      notifications: "YES"
    })
```

**Comment by alexsinger** [comment] 2015-07-22 13:32
@barbelith Alex here from Fabric. @KrauseFx tweeted out and I wanted to see if there's anything I can help with. Are you submitting through the Fabric app or /submit command and are you calling the /run command in your run script build phase? If you can let me know the bundle id and your Fabric organization, I can check out things on our backend too.

**Comment by KrauseFx** [comment] 2015-07-22 13:49
Thanks for helping here @alexsinger :+1: 

This is the first time a user reported the dsym upload doesn't work, as it's usually uploaded completely automatically. 

`fastlane` builds using [shenzhen](https://github.com/nomad/shenzhen) and then uploads the `ipa` file using the `shenzhen` crashlytics integration.

**Comment by barbelith** [comment] 2015-07-22 13:53
Hi, @alexsinger 

I use the crashlytics action from fastlane, that uses shenzhen under the hood, with crashlytics as a pod.

My organization is 53be7a549254292a3d0002ab, and it has happened me with the new apps that use only fastlane for building and uploading the apps.
These are two bundle ids that have no dsyms: com.eventwo.abertisglobal2015 and com.eventwo.astellasri2015

I have a single project with a lot of targets, and i use a different .env files to provide the custom configuration for each target

This is the full lane I'm using:

```
desc "Submit a new Beta Build to Crashlytics"
  lane :beta do
    ensure_git_status_clean

    profile_path = "apps/" + ENV['SCHEME'] + '/AdHoc_'+ ENV['BUNDLE_ID'] + '.mobileprovision'

    if !File.exists?(profile_path)
      download_provisioning
    end

    increment_build

    ipa({
      workspace: ENV['WORKSPACE'],
      configuration: ENV['CONFIG'],
      scheme: ENV['SCHEME'],
      ipa: ENV['SCHEME'] + ".ipa"
    })

    resign({
      ipa: ENV['SCHEME'] + ".ipa",
      provisioning_profile: "fastlane/" + profile_path,
      signing_identity: ENV['SIGNING_IDENTITY']
    })

    crashlytics({
      crashlytics_path: './Pods/Crashlytics/Crashlytics.framework',
      api_token: ENV['CRASHLYTICS_API_TOKEN'],
      build_secret: ENV['CRASHLYTICS_BUILD_SECRET'],
      ipa_path: ENV['SCHEME'] + ".ipa",
      groups: "Expansoft",
      notifications: "YES"
    })
    
    sh 'git add -A'
    sh 'git commit -m "Subida build version de app ' + ENV['SCHEME'] + '"'

    push_to_git_remote
  end
```

If there is any other info I can provide, tell me

**Comment by barbelith** [comment] 2015-08-03 09:25
Hi, @alexsinger , ¿did you see anything about the issue?

Thanks a lot

**Comment by alexsinger** [comment] 2015-08-03 13:02
@barbelith sorry I totally missed your last message! I'm going to look into this today.

**Comment by alexsinger** [comment] 2015-08-03 20:35
@barbelith can I take a look at your run script build phase?

**Comment by barbelith** [comment] 2015-08-04 06:13
@alexsinger I'm using Fabric integrated via CocoaPods as explained here http://docs.fabric.io/ios/fabric/cocoapods.html

My build phase is:
./Pods/Fabric/Fabric.framework/run XXX XXX

**Comment by daveanderson** [comment] 2015-10-02 16:22
Note: iTunesConnect will also provide crash reports if your Xcode knows about your iTunesConnect AppleID **and** if the `.ipa` includes a folder of `.symbol` files. Manually exporting from an `.xcarchive` gives you an option to include these symbols, however building the app with `gym` does not appear to do the same.

As this title for this issue is *Create ipa with dsym symbols included* please consider this my request for iTC support by including `.symbol` files within the .ipa (not just a Crashlytics/Fabric-specific workaround)

**Comment by apouche** [comment] 2015-10-29 06:31
Any updates on this ? I'm having the exact same issue. Pretty sure this is related to fastlane though as it's working fine with my previous `bash` build and upload scripts

**Comment by apouche** [comment] 2015-10-29 07:28
After digging into this a little more this is actually a **SERIOUS** crashlytics regression. Downgrading to:
```
pod 'Fabric', '= 1.4.1', :configurations => ['AdHoc', 'Release']
pod 'Crashlytics', '= 3.2.0', :configurations => ['AdHoc', 'Release']
```
Makes the dsym upload process working fine again. A wild guess is that this bug was introduced when Fabric engineers supported bitcode since the dsym files for bitcode enabled apps needs to be downloaded from iTunes Connect. @barbelith can you confirm you have this issue being tracked down ? I will open a ticket from my organization.

**Comment by cemo** [comment] 2015-11-02 14:24
@barbelith Would you mind answering @apouche's question? We have exactly same problem currently.

**Comment by apouche** [comment] 2015-11-02 14:26
Just as a followup, I've been contacted by Fabric support, but we didn't find any solutions yet.

**Comment by cemo** [comment] 2015-11-02 19:11
@apouche Thanks for the follow up. Is still downgrading a workaround? And Is there any fast way to detect missing dsym files? (Consider me as a noob please)

**Comment by barbelith** [comment] 2015-11-03 07:11
Hi, in my case after changing to changing to Fabric I haven't had any issues with the dsyms, and it looks that they are always bundled with the ipa

I've checked some ipas recently created and they have the Symbols folder inside

```
  pod 'Fabric'
  pod 'Crashlytics'
```

I use gym for building the app

```
  gym({
      workspace: ENV['WORKSPACE'],
      configuration: ENV['CONFIG'],
      scheme: ENV['SCHEME'],
      output_name: ENV['SCHEME'] + ".ipa",
      output_directory: "archives",
      provisioning_profile_path: "fastlane/" + profile_path,
      codesigning_identity: ENV['SIGNING_IDENTITY'],
      silent: true,
    })
```

**Comment by jaroslavas** [comment] 2015-11-05 13:20
Had the same issue. Downgraded fabric as @apouche said. Disabled bitcode and added fabric's run script (which now annoys me with it's notifications after each build). Now error reporting is working.

**Comment by JaviSoto** [comment] 2015-12-10 19:58
Hi everyone!
I'm going through some old issues to see if I can help with anything. Is this still an issue for you folks?

**Comment by apouche** [comment] 2015-12-10 20:40
Hey JaviSoto I haven't had a chance to retry with the latest Crashlytics build but in any case this is definitely not a fastlane issue. I think you should close it.

**Comment by daveanderson** [comment] 2015-12-10 23:29
I wouldn't consider this closed unless the symbols are *inside* the .ipa to allow iTunesConnect Crash Reports (inside Xcode) to work.

**Comment by JaviSoto** [comment] 2015-12-11 01:39
Hi @daveanderson. I'm a bit confused. Is this an issue when submitting the ipas to the app store, or to crashlytics?
In the latter case, the dsyms are uploaded as part of the post-build phase that calls the `submitDSYM` script inside crashlytics.

**Comment by Rking788** [comment] 2016-01-04 00:14
Hi @JaviSoto ,

I am having issues with dSYMs not being uploaded to Crashlytics. When I log into the Fabric dashboard and view the new version in the Beta tab, the alert comes up in the bottom saying it is missing.

Do you think this is an issue with the crashlytics fastlane action being configured incorrectly or the Fabric.framework/run build script.

**Comment by JaviSoto** [comment] 2016-01-04 17:22
Hi rob,

Did you by any chance figure out which dsyms are not being uploaded? Is it
the main app binary's dsyms, or are you using Swift frameworks, maybe using
Carthage?
On Sun, Jan 3, 2016 at 4:14 PM Rob <notifications@github.com> wrote:

> Hi @JaviSoto <https://github.com/JaviSoto> ,
>
> I am having issues with dSYMs not being uploaded to Crashlytics. When I
> log into the Fabric dashboard and view the new version in the Beta tab, the
> alert comes up in the bottom saying it is missing.
>
> Do you think this is an issue with the crashlytics fastlane action being
> configured incorrectly or the Fabric.framework/run build script.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fastlane/fastlane/issues/432#issuecomment-168557137>.
>
-- 
Javier Soto

**Comment by Rking788** [comment] 2016-01-04 18:26
Sorry @JaviSoto the dSYMs that were missing were from a pretty old version of the app. I am not using any Swift frameworks though or Carthage. The version that was missing it was uploaded before using fastlane so i assume there was an issue in my Jenkins setup or a manual upload.

**Comment by humblehacker** [comment] 2016-01-06 21:05
@JaviSoto I'm having a problem with dSYMs not being uploaded, but it is because I have bitcode turned on (required for apps with embedded Watch app).  [Crashlytics documentation has this to say](https://docs.fabric.io/ios/crashlytics/advanced-setup.html#bitcode-enabled-apps):

> Bitcode enabled applications are required to download their dSYM from Xcode and then upload it to Crashlytics so that we can symbolicate the crashes. DSYMs for Bitcode enabled apps can be downloaded from Xcode’s Organizer. Select the specific Archive of your app and then hit the “Download dSYMs” button which will insert the Bitcode compiled dSYMs into the original Archive. Then manually upload the dSYM to Crashlytics via the steps above. 

So it seems there is some work for fastlane (Spaceship?) to do here, namely adding the ability to programmatically perform the same action that clicking the highlighted button performs, which is downloading dSYMs and embedding them into the ipa before submission.

![Xcode Organizer](https://docs.fabric.io/ios/_images/xcode-download-dsyms.png)

**Comment by Rking788** [comment] 2016-01-06 23:01
@humblehacker I"m pretty sure fastlane already provides this for you when using the gym or ipa actions to build your application. I was mistaken when i thought they weren't getting to Crashlytics. They were. I am using gym to build my app and in my output directory I have .ipa and .dsym.zip files. You could also take a look at the `dsym_zip` action described in this doc:

https://github.com/fastlane/fastlane/blob/master/docs/Actions.md

Hopefully this helps.

**Comment by humblehacker** [comment] 2016-01-07 04:46
Thanks @Rking788.  I'm just figuring this all out, but it looks like that only works for non-bitcode enabled apps.  Because the app is recompiled from bitcode on Apple's servers, the dSYMs generated during the local build won't work. [From the docs](https://developer.apple.com/library/tvos/documentation/IDEs/Conceptual/AppDistributionGuide/AppThinning/AppThinning.html#//apple_ref/doc/uid/TP40012582-CH35-SW2):

> After you distribute your app using iTunes Connect, you can download the dSYMs file for the build.

That's done by hitting the "Download dSYMs" button above.

**Comment by prsolucoes** [comment] 2016-02-26 11:16
Hi,

I have created a tool to upload it:
https://github.com/prsolucoes/fabric-upload-dsym

Thanks.

**Comment by apouche** [comment] 2016-04-20 13:16
The issue is that Fabric now uses the Fabric app to process dsym uploads. (Also the submit path was changed but that was already taken care of by the fastlane team). So, obviously, if you are going through a CI machine, it won't work. Just make sure that you add the `upload_symbols_to_crashlytics` action after the `crashlytics` one.

Example
```ruby
   # upload ipa
    crashlytics({
      ipa_path: './build/YourApp.ipa',
      notes_path: './changelog.txt',
      notifications: true,
      groups: [ENV['GIT_BRANCH'] == 'master' ? 'Everyone' : 'Developers']
    })

    # upload dsym
    upload_symbols_to_crashlytics
```

**Comment by asfalcone** [comment] 2016-04-20 13:56
Thanks @apouche! I'm going to close this issue now since folks can use `upload_symbols_to_crashlytics` to upload dsyms now.

**Closed by asfalcone** 2016-04-20 13:56 UTC
Labels: awaiting-reply
