### ISSUE TITLE
The request could not be completed because: Unauthorized Access

### ISSUE THREAD

**Issue by TheGenial** [fastlane/fastlane#15411] opened 2019-09-30 06:27 UTC
I am trying to add fastlane into my project. I have 2FA enabled and entered the verification code. when I tried to create lane as "fastlane create_app" then it required to give 6 digit code. After pressing the code it shows: "Unauthorized Access." Note that i'm using Xcode 11 and macOS Mojave (version 10.14.6)

```
[✔] 🚀 
[16:36:52]: fastlane detected a Gemfile in the current directory
[16:36:52]: however it seems like you don't use `bundle exec`
[16:36:52]: to launch fastlane faster, please use
[16:36:52]: 
[16:36:52]: $ bundle exec fastlane produce
[16:36:52]: 
[16:36:52]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile

+----------------+------------+
| Summary for produce 2.131.0 |
+----------------+------------+
| sku            | 1569839813 |
| platform       | ios        |
| language       | English    |
| skip_itc       | false      |
| skip_devcenter | false      |
+----------------+------------+

[16:36:53]: To not be asked about this value, you can specify it using 'username'
[16:36:53]: Your Apple ID Username: ***
Two-factor Authentication (6 digits code) is enabled for account '***'
More information about Two-factor Authentication: https://support.apple.com/en-us/HT204915

If you're running this in a non-interactive session (e.g. server or CI)
check out https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification

(Input `sms` to escape this prompt and select a trusted phone number to send the code as a text message)

(You can also set the environment variable `SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER` to automate this)
(Read more at: https://github.com/fastlane/fastlane/blob/master/spaceship/docs/Authentication.md#auto-select-sms-via-spaceship-2fa-sms-default-phone-number)

Please enter the 6 digit code:
580503
Requesting session...

Looking for related GitHub issues on fastlane/fastlane...

➡️  The request could not be completed because: Unauthorized Access
    https://github.com/fastlane/fastlane/issues/15411 [open] 0 💬
    3 hours ago

➡️  The request could not be completed because:Unauthorized Access
    https://github.com/fastlane/fastlane/issues/13923 [closed] 14 💬
    31 Jul 2019

➡️  Unauthorized Access when I use Fastlane pilot upload
    https://github.com/fastlane/fastlane/issues/15125 [closed] 6 💬
    2 weeks ago

and 14 more at: https://github.com/fastlane/fastlane/search?q=The%20request%20could%20not%20be%20completed%20because%3A%0A%09Unauthorized%20Access&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.

[!] The request could not be completed because:
	Unauthorized Access
```

---

This is my fastlane env:

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.6                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.23.0                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14.6 (18G103)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.5                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Library/Developer/CommandLineTools/                           |
| Xcode Version               |                                                                |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.131.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.1        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.67.0       |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.3.1      |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.0.2        |
| faraday_middleware        | 0.13.1       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.0904  |
| mime-types                | 3.3          |
| multi_json                | 1.13.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.1        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.1        |
| google-cloud-core         | 1.3.1        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
| psych                     | 2.1.0.1      |
</details>

*generated on:* **2019-09-30**
</details>

```

**Comment by janpio** [comment] 2019-09-30 11:55
Any additional output with `--verbose`? Or does it really jsut end after "	Unauthorized Access"?

**Comment by mikehardy** [comment] 2019-09-30 13:59
I just saw this, this morning, after having successful testflight releases on Saturday and Sunday. However, mine was after the binary was successfully transferred to apple and was conflated with a legitimate "invalid binary" rejection (I was missing a plist permission string), so perhaps @TheGenial your binary had a legitimate problem, or perhaps after I fix my invalid binary issue I will still have this issue myself.

**Comment by mikehardy** [comment] 2019-09-30 18:59
I cannot reproduce. After fixing my real problem, I successfully delivered to TestFlight 

```
\(virtualenv) mike@kunashir:~/work/Kullki/ksocialscore/packages/public-app (vp1) % fastlane -v
fastlane installation at path:
/Users/mike/.rvm/gems/ruby-2.6.3/gems/fastlane-2.131.0/bin/fastlane
-----------------------------
[✔] 🚀 
fastlane 2.131.0
```

**Comment by TheGenial** [comment] 2019-10-01 02:36
@janpio It ends after " Unauthorized Access".

**Comment by TheGenial** [comment] 2019-10-01 02:43
@mikehardy I'm trying with a fresh project and nothing found like what you have.

**Comment by janpio** [comment] 2019-10-01 10:29
Can you try https://docs.fastlane.tools/actions/spaceship_logs/ to get the latest requests?

**Comment by TheGenial** [comment] 2019-10-02 05:46
@janpio It showing there isn't any spaceship_log file in my directory folder:
```
**: **$ fastlane run spaceship_logs latest:"true" print_contents:"true"
[✔] 🚀 
[11:43:26]: fastlane detected a Gemfile in the current directory
[11:43:26]: however it seems like you don't use `bundle exec`
[11:43:26]: to launch fastlane faster, please use
[11:43:26]: 
[11:43:26]: $ bundle exec fastlane run spaceship_logs latest:true print_contents:true
[11:43:26]: 
[11:43:26]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[11:43:27]: ----------------------------
[11:43:27]: --- Step: spaceship_logs ---
[11:43:27]: ----------------------------
[11:43:27]: No Spaceship log files found
[11:43:27]: Result: []
```
It's also suggesting me to upgrade the fastlane from 2.131.0 to 2.132.0. I'm new to fastlane and can't figure it out also.

**Comment by janpio** [comment] 2019-10-02 13:05
Hm, what command did you execute in your first text of the issue?

**Comment by TheGenial** [comment] 2019-10-04 06:27
fastlane produce

**Comment by Dids** [comment] 2019-10-07 11:29
Any update on this? Also seeing this now, with `Unauthorized Access` being thrown immediately after entering the 6 digit code.

**Comment by janpio** [comment] 2019-10-07 11:44
Is there a simple way for us to attempt to reproduce this without too much setup needed?

**Comment by TheGenial** [comment] 2019-10-10 06:05
@janpio Sorry I didn't understand what you mean by this.

**Comment by janpio** [comment] 2019-10-10 06:52
What are the simplest steps you can come up with to get this result that is broken?

**Comment by TheGenial** [comment] 2019-10-11 05:41
@janpio I tried with "Web session/token" but it isn't working for me

```
fastlane spaceauth -u (account_name)
[✔] 🚀 
[11:30:44]: fastlane detected a Gemfile in the current directory
[11:30:44]: however it seems like you don't use `bundle exec`
[11:30:44]: to launch fastlane faster, please use
[11:30:44]: 
[11:30:44]: $ bundle exec fastlane spaceauth -u (account_name)
[11:30:44]: 
[11:30:44]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
Logging into to App Store Connect (account_name)...
Two-factor Authentication (6 digits code) is enabled for account '(account_name)'
More information about Two-factor Authentication: https://support.apple.com/en-us/HT204915

If you're running this in a non-interactive session (e.g. server or CI)
check out https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification

(Input `sms` to escape this prompt and select a trusted phone number to send the code as a text message)

(You can also set the environment variable `SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER` to automate this)
(Read more at: https://github.com/fastlane/fastlane/blob/master/spaceship/docs/Authentication.md#auto-select-sms-via-spaceship-2fa-sms-default-phone-number)

Please enter the 6 digit code:
647355
Requesting session...
Could not login to App Store Connect
Please check your credentials and try again.
This could be an issue with App Store Connect,
Please try unsetting the FASTLANE_SESSION environment variable
(if it is set) and re-run `fastlane spaceauth`

Exception type: Spaceship::UnauthorizedAccessError
```

**Comment by TheGenial** [comment] 2019-10-16 08:02
@janpio I didn't find any solution yet. Can you please help me?

**Comment by janpio** [comment] 2019-10-16 09:47
The "Auth lost" means that you got a 401 back on the `auth` call, which doesn't make too much sense when you got a 409 first, which you get when your credentials are valid (so not a 401) and you have to do 2FA: https://github.com/fastlane/fastlane/blob/b2ea0580c12fea7f03bcdabe81986275c0128069/spaceship/lib/spaceship/client.rb#L492-L498 Super confusing.

Can you try a different account if this works for you then?

**Comment by TheGenial** [comment] 2019-10-21 04:38
Really didn't understand why this is happening.

**Comment by Dids** [comment] 2019-10-21 05:55
For me it seems to have fixed itself. Not sure of it was on Apple's end, or if it was being blocked by pending information in ITC (contact info updates in this case).

**Comment by heshamghalaab** [comment] 2019-10-21 17:25
solved for me by adding the command `bundle exec fastlane produce`

**Closed** 2019-11-28 17:32 UTC
Labels: status: waiting-for-reply, tool: produce, topic: authentication

**Comment by TheGenial** [comment] 2020-01-07 08:57
@janpio My previous problem was solved by removing the credentials using  ` fastlane fastlane-credentials remove --username ***` and adding environment variable of `user & password ` in fastfile.  Now the same error occurring when I'm trying to authenticate with the same id using a different mac.  

**Before that I checked**
- Fastlane is updated.
- I have read the documentation and contribution guidelines.

**The ways I tried**

1. Running a simple late related to testflight, prompt for 6 digit code. After pressing that code it shows ` Unauthorized access `
2.   Setting the environment variable as did before but didn't work.
3. Try to login using spaceship but it shows the same error. Here is the log: 

```
siliconorchard@SOL-MAC-MINI try % fastlane spaceship -u ***                       
[✔] 🚀 
[12:58:52]: fastlane detected a Gemfile in the current directory
[12:58:52]: However, it seems like you didn't use `bundle exec`
[12:58:52]: To launch fastlane faster, please use
[12:58:52]: 
[12:58:52]: $ bundle exec fastlane spaceship -u shoebamin017@gmail.com
[12:58:52]: 
[12:58:52]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
Logging into to App Store Connect (shoebamin017@gmail.com)...
-------------------------------------------------------------------------------------
Please provide your Apple Developer Program account credentials
The login information you enter will be stored in your macOS Keychain
You can also pass the password using the `FASTLANE_PASSWORD` environment variable
See more information about it on GitHub: https://github.com/fastlane/fastlane/tree/master/credentials_manager
-------------------------------------------------------------------------------------
Password (for ***): ***************
Two-factor Authentication (6 digits code) is enabled for account '***'
More information about Two-factor Authentication: https://support.apple.com/en-us/HT204915

If you're running this in a non-interactive session (e.g. server or CI)
check out https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification

(Input `sms` to escape this prompt and select a trusted phone number to send the code as a text message)

(You can also set the environment variable `SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER` to automate this)
(Read more at: https://github.com/fastlane/fastlane/blob/master/spaceship/docs/Authentication.md#auto-select-sms-via-spaceship-2fa-sms-default-phone-number)

Please enter the 6 digit code:
820109
Requesting session...
Could not login to App Store Connect...
Logging into the Developer Portal (***)...
Could not login to the Developer Portal...
---------------------------------------
| Welcome to the spaceship playground |
---------------------------------------

Enter docs to open up the documentation
Enter exit to exit the spaceship playground
Enter _ to access the return value of the last executed command

Just enter the commands and confirm with Enter
[1] pry(#<Spaceship::Playground>)> 
```

But the fact is if I copy the "spaceship" folder to my second device where I tried to login and past it into the `.fastlane` in-home directory it automatically authenticates the user and using that I upload a build into testflight. Why 2FA is not working? Is there any issue with the OS?
