### ISSUE TITLE
[match] Generate profiles with new Xcode 11 certificates attached

### ISSUE THREAD

**Issue by Blackjacx** [fastlane/fastlane#15031] opened 2019-07-16 13:58 UTC
#### Motivation Behind Feature
To be able to use Xcode 11 Beta on devices and in CI.

#### Feature Description
Now Xcode 11 has some new kind of development Certificates. Actually there are 2 kinds of development certificates now. One for Xcode 10.x and below and one for Xcode 11.x and above. The provisioning profiles generated by `match` are only connected to the Xcode 10x  cert. 

It would be nice if every profile generated would support both certs.

**Comment by nebiros** [comment] 2019-08-08 16:16
We are having the same issue, Xcode 11 beta 5  produce this error: `doesn't include signing certificate`

**Comment by jeffvstudio** [comment] 2019-08-08 16:17
Same here :point_up_2::skin-tone-2:

**Comment by samjp** [comment] 2019-08-11 01:29
I was able to workaround this for now by editing the appropriate provisioning profile in the developer portal. There is an additional certificate to include in the profile that is labelled as being "For use in Xcode 11 or later". Selecting it and re-downloading the profile through Xcode got me going again.

**Comment by Hanstad** [comment] 2019-09-02 14:12
I have the same issue. My workarround was to create the certificate and profiles manually, then encrypt these and add it to our certificate repo so that match can use it. I had to use a different name for my certificate branch of these types. 
I would be nice if Fastlane could support this new type of certificates.

**Comment by RetepV** [comment] 2019-09-09 13:34
And I'm having the same issue as well. Can we have a fix for this? Because now I have to manually update all the profiles like Hanstad is doing, for every time that we add a new device to the profile.

Pretty please? :)

**Comment by yoxisem544** [comment] 2019-09-17 08:27
Same issue here, would like to know if all certificates are included in development provision file. :)

**Comment by intoxicated** [comment] 2019-09-18 22:26
woah.. apple makes this worse :|. So, do we have to manually create profiles until it get fixed to use xcode 11 or later?

**Comment by yusuftor** [comment] 2019-09-20 11:48
Now that Xcode 11 is released, can we please have an update??

**Comment by bes** [comment] 2019-09-23 08:20
I literally want to throw my computer through a window every time crapple break things. Please fix this ❤️

**Comment by StarWars** [comment] 2019-09-25 09:10
Bump :). The problem is live and still unsolved.

**Comment by itsallmememe** [comment] 2019-09-25 11:24
Bump Bump. Running into this as well!

**Comment by aastlind** [comment] 2019-09-25 12:27
Getting this error as well.

Gym log:
Code Signing Error: Provisioning profile "match AppStore com.mydomain.app" doesn't support the iCloud.com.mydomain.app iCloud Container.
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 13.0'

**Comment by fishercraigj** [comment] 2019-09-25 20:52
Bump bump bump

**Comment by JackTudor96** [comment] 2019-09-26 10:41
Having the same issue too.

**Comment by adamwaite** [comment] 2019-09-26 10:45
Same issue here.

Workaround:
<img width="1229" alt="Screenshot 2019-09-26 at 11 45 17" src="https://user-images.githubusercontent.com/1426233/65682607-29d14a00-e053-11e9-9b5d-e8291d315c36.png">

**Comment by Blackjacx** [comment] 2019-09-26 11:59
Yeah but if you have 10 apps and therefore 20 profiles (dev / distribution) you don’t want to do this each time you add a new device or regenerate the credentials which was the idea behind opening this issue.

**Comment by JackTudor96** [comment] 2019-09-26 12:45
Thanks @adamwaite , really handy. 

@Blackjacx hence he used the word "workaround"

**Comment by GLJeffery** [comment] 2019-09-27 02:47
has anyone been able to get the new Apple Distribution certificates successfully into their fastlane repository?

I've been able to get the new provisioning profiles in with the workaround, but anytime I try to export the Apple Distribution certificate and import it into the repository using `irb`, the end result is that whoever calls the `match` function isn't able to get the private key, just the cert, and so building fails. But I'm exporting the cer and the p12 the same way it would normally be done from Keychain Access.

**Comment by GLJeffery** [comment] 2019-09-27 02:55
> I have the same issue. My workarround was to create the certificate and profiles manually, then encrypt these and add it to our certificate repo so that match can use it. I had to use a different name for my certificate branch of these types.
> I would be nice if Fastlane could support this new type of certificates.

how did you go about importing the new certificates into the repo? I've got the profiles down, but I'm wondering if I'm exporting my `.cer` and `.p12` incorrectly, I'm doing it the same way as before (from Keychain Access, right click the main cer and export as `.cer`, and then export the key under the arrow as `.p12`) but that doesn't ever work when I run match, `p12` doesn't make it. Is there a separate step needed? (do I need to do `pem` stuff)

**Comment by fishercraigj** [comment] 2019-09-27 04:18
I'm not going to lie, this particular problem has brought me CI/CD pipes to a screeching halt since Xcode 11 and I'm just getting tired of all the patches that Fastlane understandably has to deal with.  It was a tough decision but I took the last 2 days and scripted out my whole CI purely using bash/xcodebuild so that I'm no longer reliant on any 3rd party tooling, with the exception to Cocoapods and even those pods will soon become Swift Packages.  Even shaved a couple minutes off build times!  But even running Catlina Beta versions on spare machines, you can tell that changes are coming to the Mac.  Hell, I even had to install rbenv just to do a dang cocoapods install!!!

I think I've used fastlane for about 7 years or so.  It's been a good ride but Apple keeps sticking it to them which is a damn shame because it has always been at the top of my list for tools.  I hope we meet again Fastlane, you will definitely be missed.  :)

**Comment by Hanstad** [comment] 2019-09-27 10:37
@fishercraigj 
Maybe a silly question, but did you remember to encrypt the files before adding to certificates repo?

**Comment by GLJeffery** [comment] 2019-09-27 12:52
I did the steps in the https://docs.fastlane.tools/advanced/other/#manually-manage-the-fastlane-match-repo which successfully decrypts and encrypts/pushes to git. Provisioning profile downloads perfectly, only the apple distribution certificate doesn't work

**Comment by fishercraigj** [comment] 2019-09-27 18:42
> @fishercraigj
> Maybe a silly question, but did you remember to encrypt the files before adding to certificates repo?

@Hanstad - Yeah, I got it working that way before I migrated off of fastlane.

**Comment by jpizzitola** [comment] 2019-09-28 16:54
Ugh..... This breaking change has killed my CI/CD pipeline.  Apple can be so frustrating sometimes.......

**Comment by hjh5696** [comment] 2019-09-29 19:17
For newbies like me, let me share my workaround.

1. Optionally, nuke previous certificates and provisioning profiles. (I did it to avoid confusion with the new certificates. For provisioning profiles, you could just edit them to be connected with the following new certificates below instead of creating new ones)


2. manually create new development/distribution certificates with new options, download and register to your keychain.
![image](https://user-images.githubusercontent.com/16831251/65837568-3a0a5300-e2f9-11e9-9e18-8d417348993a.png)


3. If you invalidated all provisioning profiles in 1, then create them again with the new certificates you created. If not, you can edit existing provisioning profiles to have new certificates. Download all the valid provisioning profiles.
![image](https://user-images.githubusercontent.com/16831251/65837641-3a571e00-e2fa-11e9-9ed6-d10736b15303.png)


4. Export .cer, .p12 from Keychain Access. 
For .cer file, right click on your certificate and export it. 
![image](https://user-images.githubusercontent.com/16831251/65837828-3deba480-e2fc-11e9-97c1-28c432302e59.png)
For .p12 file, select your certificate and private key together and right click on them. Export it. Here, you should not set password since Fastlane does not support this now.
![image](https://user-images.githubusercontent.com/16831251/65837873-c4a08180-e2fc-11e9-9c88-e77c7d6bcb49.png)


5. Change your .cer, .p12 file names to appropriate certificate identifier. You can check it in apple developer portal.
![image](https://user-images.githubusercontent.com/16831251/65837942-86579200-e2fd-11e9-8053-71f624123d92.png)


6. Unfold the "Instructions" and follow the "Decryption Instructions" in the link below, which enables to manually edit the "github repo" containing your certificates and provisioning profiles.
https://docs.fastlane.tools/advanced/other/#manually-manage-the-fastlane-match-repo
![image](https://user-images.githubusercontent.com/16831251/65837676-af2a5800-e2fa-11e9-9a16-8f41c217ae4f.png)


7. When you've done all the instructions, then you can find the certificate repo folder starting with /var/folders. In that, update your certificates and provisioning profiles with all the newly created or changed ones. (all .p12, .cer, . mobileprovision files)


8. Do not manually commit the changes. Follow "Encryption Instructions" in the link.

Now I believe your repo successfully updated with new certificates and provisioning profiles. It worked same as before with CI as well. Hope it helped.

**Closed** 2019-09-30 18:38 UTC
Labels: tool: match, topic: xcode11

**Comment by RetepV** [comment] 2019-10-24 13:16
> I'm not going to lie, this particular problem has brought me CI/CD pipes to a screeching halt since Xcode 11 and I'm just getting tired of all the patches that Fastlane understandably has to deal with and all the work arounds that we have to come up with.
> 
> It was a tough decision but I took the last 2 days and scripted out my whole CI purely using bash/xcodebuild so that I'm no longer reliant on any 3rd party tooling, with the exception to Cocoapods and even those pods will soon become Swift Packages. Even shaved a couple minutes off build times! Even running Catlina Beta versions on spare machines, you can tell that changes are coming to the Mac. Hell, I even had to install rbenv just to do a dang cocoapods install!!!
> 
> I think I've used fastlane for about 7 years or so. It's been a good ride but Apple keeps sticking it to them which is a damn shame because it has always been at the top of my list for tools. I hope we meet again Fastlane, you will definitely be missed. :)

But now you are solely responsible for those scripts and cannot pass the blame to anyone else anymore when they break.

**Comment by RetepV** [comment] 2019-10-24 13:20
@joshdholtz : You are a hero, Sir.

**Comment by Blackjacx** [comment] 2019-10-24 14:52
@RetepV wow thats awesome! I also thought about writing all of this `simply` in bash but apple changes the things so often - it would be a maintenance hell I think... Could you make your effort public?

**Comment by fishercraigj** [comment] 2019-10-24 16:49
> > I'm not going to lie, this particular problem has brought me CI/CD pipes to a screeching halt since Xcode 11 and I'm just getting tired of all the patches that Fastlane understandably has to deal with and all the work arounds that we have to come up with.
> > It was a tough decision but I took the last 2 days and scripted out my whole CI purely using bash/xcodebuild so that I'm no longer reliant on any 3rd party tooling, with the exception to Cocoapods and even those pods will soon become Swift Packages. Even shaved a couple minutes off build times! Even running Catlina Beta versions on spare machines, you can tell that changes are coming to the Mac. Hell, I even had to install rbenv just to do a dang cocoapods install!!!
> > I think I've used fastlane for about 7 years or so. It's been a good ride but Apple keeps sticking it to them which is a damn shame because it has always been at the top of my list for tools. I hope we meet again Fastlane, you will definitely be missed. :)
> 
> But now you are solely responsible for those scripts and cannot pass the blame to anyone else anymore when they break.

That is probably the most terrifying reason I've ever heard of to use a 3rd party library.  I'm just going to assume you were joking.  :)

**Comment by RetepV** [comment] 2019-12-03 14:24
> That is probably the most terrifying reason I've ever heard of to use a 3rd party library. I'm just going to assume you were joking. :)

I apologise for not having added a smiley. It was sarcasm. But like all sarcasm there is a level of truth in it as well.

See. The problem with dropping Fastlane and writing your own scripting, is that your own scripting will break just like Fastlane does. Because just like it happens with Fastlane, Apple does not tell YOU that they made any breaking changes either. And you will have to fix it just as well.

The only thing that you win is that you can make the fixes faster. But you pay for it by loosing time. Time that you should have spent on other things.

Even if Fastlane is fixed slowly, it still WILL be fixed at some point. And there will be no more effort for you than updating Fastlane.

The thing is... When you do everything yourself, you will loose time. But when you depend on Fastlane or other 3rd party tools, you WON'T loose time (provided that a fix will be made at some point). You only loose PATIENCE.

But patience can always be regained. Time can never be regained. Loosing patience costs nobody a thing (ok, maybe your sanity). Loosing time can cost you everything.

**Comment by rishi1596** [comment] 2019-12-23 14:00
Is anyone still facing this issue? because I am still facing the issue
Fastlane script works properly with Xcode 10.2  but the same script breaks when executed with Xcode 11.1. The error message mentions "Provisioning profile doesn't include signing certificate"
Also, when the generated provisioning profiles are manually selected in respective Xcode then too it displays the same error.

PS. New provisioning profile were created using match command when executing fast lane script in both the environment.

**Comment by kevnm67** [comment] 2019-12-23 23:20
> Is anyone still facing this issue? because I am still facing the issue
> Fastlane script works properly with Xcode 10.2 but the same script breaks when executed with Xcode 11.1. The error message mentions "Provisioning profile doesn't include signing certificate"
> Also, when the generated provisioning profile is manually selected in Xcode 11.1 it displays the same error and works fine with Xcode 10.2.
> 
> PS. New provisioning profile were created using match command when executing fast lane script in both the environment.

@rishi1596 Either following [this suggestion above](https://github.com/fastlane/fastlane/issues/15031#issuecomment-520192447) or, at least at the time the issue first appeared, I found removing/nuking non-Xcode 11 certificates in favor of the new Apple Development/Distribution certificate types resolved the issue.  Every time another iOS developer generated an older cert type I noticed our CI builds failed at signing.  Not sure if this continues to happen.

**Comment by rishi1596** [comment] 2019-12-24 05:34
> > Is anyone still facing this issue? because I am still facing the issue
> > Fastlane script works properly with Xcode 10.2 but the same script breaks when executed with Xcode 11.1. The error message mentions "Provisioning profile doesn't include signing certificate"
> > Also, when the generated provisioning profile is manually selected in Xcode 11.1 it displays the same error and works fine with Xcode 10.2.
> > PS. New provisioning profile were created using match command when executing fast lane script in both the environment.
> 
> @rishi1596 Either following [this suggestion above](https://github.com/fastlane/fastlane/issues/15031#issuecomment-520192447) or, at least at the time the issue first appeared, I found removing/nuking non-Xcode 11 certificates in favor of the new Apple Development/Distribution certificate types resolved the issue. Every time another iOS developer generated an older cert type I noticed our CI builds failed at signing. Not sure if this continues to happen.

At the time of running with Xcode 11 all non-Xcode 11 certificates were revoked. And at the same time none of the iOS developer generated older type certificate.

**Comment by koxon** [comment] 2020-01-18 21:54
Any update on this ?

**Comment by olsamaja** [comment] 2020-01-20 14:59
@koxon I'm not sure there will be any udpate on this issue. 

I think @rishi1596 is right. Having some devs on Xcode 10 and others using Xcode 11 seems to raise issues. Ideally, everybody should be on the same Xcode version, which could be a problem for some teams.

Provisioning profiles can be associated with **only one certificate** at a time. It seems that if you associate a profile with a Xcode 11 cert, then you won't be able to export the IPA from Xcode 10. If you associate it with an older cert, then you won't be able to export the IPA from Xcode 11.

I managed to successfully export an IPA (and upload it to APC) from my local mac on which I installed Xcode 11, after generating a new _Apple Distribution certificate_ from Xcode 11, as Xcode was telling me that _No Apple Distribution certificate was found_.

Unfortunately, running a **fastlane** lane on my mac (to simulate our CI mac), which runs match/build/gym _failed_ at export... because the certs used (by _match_, and stored in a git repo) are non-Xcode 11 ones. 

I think the only options, are:
1. to **nuke** the certs
2. to run **fastane match** with _generate_apple_certs=true_
3. to have all your devs & CI switching to Xcode 11

**Comment by rishi1596** [comment] 2020-01-22 06:08
> Any update on this ?

I have implemented fastlane on the system with Xcode 10.2 and its working fine through terminal as well as through jenkins. But facing the same issue with Xcode 11.1.

By any chance the possibility of failure in Xcode 11.1 is because the distribution certificate is generated from Xcode 10.2 environment?

**Comment by rishi1596** [comment] 2020-01-22 06:14
> @koxon I'm not sure there will be any udpate on this issue.
> 
> I think @rishi1596 is right. Having some devs on Xcode 10 and others using Xcode 11 seems to raise issues. Ideally, everybody should be on the same Xcode version, which could be a problem for some teams.
> 
> Provisioning profiles can be associated with **only one certificate** at a time. It seems that if you associate a profile with a Xcode 11 cert, then you won't be able to export the IPA from Xcode 10. If you associate it with an older cert, then you won't be able to export the IPA from Xcode 11.
> 
> I managed to successfully export an IPA (and upload it to APC) from my local mac on which I installed Xcode 11, after generating a new _Apple Distribution certificate_ from Xcode 11, as Xcode was telling me that _No Apple Distribution certificate was found_.
> 
> Unfortunately, running a **fastlane** lane on my mac (to simulate our CI mac), which runs match/build/gym _failed_ at export... because the certs used (by _match_, and stored in a git repo) are non-Xcode 11 ones.
> 
> My undesrtanding is the only options, are:
> 
> 1. to **nuke** the certs
> 2. to run **fastane match** with _generate_apple_certs=true_
> 3. to have all your devs & CI switching to Xcode 11
> 
> Unfortunately this is not working for me. I have nuked the certs, ran match, and now have only Xcode 11 ones. I still have an **Exit status: 70.**
> 
> ```
> error: exportArchive: IPA processing failed
> Error Domain=IDEFoundationErrorDomain Code=1 "IPA processing failed" UserInfo={NSLocalizedDescription=IPA processing failed}
> ```

Hi,
As per your conclusion I had followed the same steps at the time of implementation with Xcode 11.1 i.e all the provisional profiles were associated with Xcode 11.1 certs but the solution didn't work for me.
And in my case I am the only developer so multiple Xcode version isn't the issue.

**Comment by tpaik18** [comment] 2020-01-30 06:46
Help please! I'm having a similar problem to @rishi1596 of Xcode 11 showing 
> Provisioning profile "match Development org.auderenow.fluathome-us" doesn't include signing certificate "iPhone Developer: Audere iOSDev (longstring)". 

right after I did `fastlane match nuke development` and `fastlane match development --force`. I'm using fastlane 2.141.0 on MacOS 10.15.2. 

It seems to be a mismatch of the new certificate being created as "Apple Development: Audere iOSDev" but the new profile seems to be referencing the old certificate named "iPhone Developer: Audere iOSDev" which is gone now. 

Just in case it helped, I followed what @bes did in https://github.com/fastlane/fastlane/issues/6757 about opening my keychain and manually deleting the old "iPhone Developer" certificate. That did not help; after that XCode's error changed to 
> No certificate for team 'Audere' matching 'iPhone Developer: Audere iOSDev (longstring)' found
> Select a different signing certificate for CODE_SIGN_IDENTITY, a team that matches your selected certificate, or switch to automatic provisioning.

Then there is a Manage Certificates... button below that. When I click on it it pops up a list of certificates that include a newly created "Audere iOSDev" certificate of type Apple Development, which I want to select, but I am unable to select any certificates in that dialog! 

I'm desperate here. I've tried restarting XCode, rebooting the Mac, running `fastlane match development --force` or variations of that many times, downloading the new certs and profiles from the Apple Developer Portal and double-clicking them to manually add them, but nothing is helping. 

All of our devs have switched over to XCode 11 and I can't figure out why the profile is still pointing to some "iPhone Developer" certificate after nuking and regenerating.

**Comment by tpaik18** [comment] 2020-01-30 19:46
Figured it out. I had to edit CODE_SIGNING_IDENTITY in project.pbxproj where it was still referencing "iPhone Developer...". After I updated it to "Apple Development" my XCode error went away. Thanks.

**Comment by olsamaja** [comment] 2020-01-30 23:22
@tpaik18 

> Figured it out. I had to edit CODE_SIGNING_IDENTITY in project.pbxproj where it was still referencing "iPhone Developer...". After I updated it to "Apple Development" my XCode error went away. Thanks.

mmm... weird. Doing didn't do anything for me. Having **iPhone Developer** or **Apple Development** doesn't change anything, but my project includes a Today Widget and a Notification Service, which I removed from my staging target (I have no issues on my release target though), and it worked ... so, for the moment, I can start my CI/QA process (without the Today widget the Notification Service).

**Comment by jrista** [comment] 2020-03-12 00:44
The certificates and profile for one of my projects just expired, and we have suddenly begun experiencing this issue. Our certs must have been created before XCode 11 was released last year, and they have been working until now, so we did not encounter issues before.

It seems that with the latest versions of xcode, any newly generated certs and profiles from `fastlane match` do not work. This has brought our development to a crushing halt, as we rely heavily on CI/CD and fiddling with xcode settings manually is not an option (not that doing so appears to work anyway, based on prior comments.)

I'm curious why this issue has received no fastlane developer attention... This is a pretty serious issue, as it effectively kills the key benefit of `fastlane match`: Not having to deal with it every year when certs and profiles expire! It also makes building through CI/CD pretty much impossible, which is the only way we build and deploy. Would be really nice if fastlane could be fixed (soon) so that we can continue using it with XCode 11.

**Comment by hdinhof1** [comment] 2020-03-18 21:58
To anybody else wondering if you can update to Xcode 11,  without any manual steps, you can! These  comments above were before fastlane updated match/cert/sigh as mentioned above/here: https://github.com/fastlane/fastlane/pull/15410 

I solved this by going into the certificates github repo and removing any certs (.cert and .p12) and profiles that were linked to the old certificates. Then and this is important, I went into the Apple Developer portal and revoked all "iOS Development" and "iOS Distribution" certs, as well as deleted any profiles linked to those certs. Also in the portal if you created new Xcode 11 certs for either type "Development" or "Distribution" remove those too. Then match recreated and re-linked everything.

**Comment by rishi1596** [comment] 2020-03-21 11:09
> To anybody else wondering if you can update to Xcode 11, without any manual steps, you can! These comments above were before fastlane updated match/cert/sigh as mentioned above/here: #15410
> 
> I solved this by going into the certificates github repo and removing any certs (.cert and .p12) and profiles that were linked to the old certificates. Then and this is important, I went into the Apple Developer portal and revoked all "iOS Development" and "iOS Distribution" certs, as well as deleted any profiles linked to those certs. Also in the portal if you created new Xcode 11 certs for either type "Development" or "Distribution" revoke those too. Then match with the new flag `generate_apple_certs: true` recreated and re-linked everything.

Is it necessary to revoke all the certificates and profiles from Apple Developer portal and github repo? do you mean to start code signing from scratch i.e to create new signing certificates and provisional profiles?
