### ISSUE TITLE
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

### ISSUE THREAD

**Issue by khantthulinn** [fastlane/fastlane#3899] opened 2016-03-23 04:10 UTC
I am new to fastlane. I run fastlane ios Development and I saw error when I upload to hockey.

This is full stack. I already try some method from https://github.com/fastlane/fastlane/issues/745
and update my cert also. 

`/Users/thulinn/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:923:in `connect': [!] SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (Faraday::SSLError)
	from /Users/thulinn/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:923:in `block in connect'
	from /Users/thulinn/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
	from /Users/thulinn/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:923:in `connect'
	from /Users/thulinn/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
	from /Users/thulinn/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:852:in `start'
	from /Users/thulinn/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:1375:in `request'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:82:in `perform_request'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response/follow_redirects.rb:76:in `perform_with_redirection'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response/follow_redirects.rb:64:in `call'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/faraday-0.9.2/lib/faraday/request/url_encoded.rb:15:in `call'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/faraday-0.9.2/lib/faraday/request/multipart.rb:14:in `call'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/krausefx-shenzhen-0.14.7/lib/shenzhen/plugins/hockeyapp.rb:29:in `upload_build'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.67.0/lib/fastlane/actions/hockey.rb:50:in `run'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.67.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.67.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.67.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.67.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.67.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.67.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:18:in `block (2 levels) in parsing_binding'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.67.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.67.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.67.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.67.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.67.0/lib/fastlane/runner.rb:46:in `execute'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.67.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.67.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.67.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/fastlane_core-0.39.0/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.67.0/bin/fastlane:156:in `run'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.67.0/bin/fastlane:162:in `<top (required)>'
	from /Users/thulinn/.rvm/rubies/ruby-2.2.1/bin/fastlane:23:in `load'
	from /Users/thulinn/.rvm/rubies/ruby-2.2.1/bin/fastlane:23:in `<main>'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
`

My lane is like this. How shall I do? 

 gym(
      configuration: "Debug",
      scheme: "CAGInTouch - Development",
      use_legacy_build_api: true,
    )
    hockey(
      notes: 'Test Fastlane For Development',
      notify: '0', 
      status: '2', 
      api_token: 'd02a6613d1d94e2da4dc2ab9d2ec4ddc', #fake 
      notes_type: '0',
      mandatory: '1',
    )
  end

**Comment by KrauseFx** [comment] 2016-03-23 07:54
Does that part of the FAQs help?https://github.com/fastlane/fastlane/blob/master/fastlane/docs/FAQs.md#im-getting-an-ssl-error

**Comment by khantthulinn** [comment] 2016-03-23 08:58
Yes. I have tried that one. I still have that issue. 
<a href="http://tinypic.com?ref=33o2t8o" target="_blank"><img src="http://i67.tinypic.com/33o2t8o.png" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by TKBurner** [comment] 2016-03-23 14:31
Hi @khantthulinn! Great to hear from you. Can you update your comment to this format:  https://github.com/fastlane/fastlane/blob/master/ISSUE_TEMPLATE.md .

I can't wait to dig in! :+1:

**Comment by markuswinkler** [comment] 2016-03-23 22:20
same issue. Tried the tip from above, same SSL error.
fastlane 1.68.0
openssl 1.0.2g

**Comment by wkoszek** [comment] 2016-03-26 07:32
@markuswinkler had the same problem today. I have `rvm reinstall`with brew's openssl and it helped.

**Comment by khantthulinn** [comment] 2016-03-28 02:52
@TKBurner Hi Thanks. This is how I use fastlane.

### Issue Description

As written in 1st post

##### Complete output when running fastlane, including the stack trace and command used

As written in 1st post

### Configuration Files


Fastfile:
```ruby
# http://support.hockeyapp.net/kb/api/api-versions

default_platform :ios

platform :ios do
  before_all do
    
  end

  desc “CAG In.Touch Development”
  lane :Development do
  
    gym(
      configuration: "Debug",
      scheme: "CAGInTouch - Development",
      use_legacy_build_api: true,
    )
    hockey(
      notes: 'Test Fastlane For Development',
      notify: '0', 
      status: '2', 
      api_token: 'demo',
      notes_type: '0',
      mandatory: '1',
    )
  end

  desc “CAG In.Touch Staging"
  lane :Staging do

    gym(
      configuration: "Staging",
      scheme: "CAGInTouch - Staging",
    )
    hockey(
      notes: 'Test Fastlane For Staging',
      notify: '0', 
      status: '2', 
      api_token: 'demo',
      notes_type: '0',
      mandatory: '1',
    )
  end

  desc “CAG In.Touch Production"
  lane :Production do

    gym(
      configuration: "Release",
      scheme: "CAGInTouch - Production",
    )
    hockey(
      notes: 'Test Fastlane For Production',
      notify: '0', 
      status: '2', 
      api_token: 'demo',
      notes_type: '0',
      mandatory: '1',
    )
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end



# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/docs/Actions.md
```

### Environment

fastlane version (fastlane -v):
I use rvm. Ruby is 2.2.3 and fastlane version is 1.67.0

**Comment by khantthulinn** [comment] 2016-03-28 02:58
@markuswinkler I try to reinstall and I got this error. 

<a href="http://tinypic.com?ref=35me63k" target="_blank"><img src="http://i65.tinypic.com/35me63k.png" border="0" alt="Image and video hosting by TinyPic"></a>

When I try to update rvm, I got another error. 

<a href="http://tinypic.com?ref=33d9fle" target="_blank"><img src="http://i64.tinypic.com/33d9fle.png" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by markuswinkler** [comment] 2016-03-28 03:35
hmm, running these three commands in sequence solved it for me

```
brew update && brew upgrade openssl
rvm osx-ssl-certs update all
rvm reinstall ruby-2.2.3 --with-openssl-dir=/usr/local
```

**Comment by TKBurner** [comment] 2016-03-28 15:01
@khantthulinn Have you tried the commands in @markuswinkler comment?

Thanks!

**Comment by tabrindle** [comment] 2016-05-05 21:31
I can confirm that the solution @markuswinkler posted works. I think this ticket can be closed; this is nothing more than the openssl issues posted in the FAQ.

**Comment by vpolouchkine** [comment] 2016-05-05 21:53
Closing as this seems to be solved.

**Closed by vpolouchkine** 2016-05-05 21:53 UTC
Labels: fastlane

**Comment by aymericbouzy** [comment] 2016-07-14 09:54
@markuswinkler's solution works, but all my gems have been removed in the process : is there a way to prevent this ? It's too late for me anyway, I'm simply asking for future users.

**Comment by KrauseFx** [comment] 2016-08-03 06:51
@aymericbouzy Yes there is, you should use a Gemfile for all your projects. More information about how to get started on the [CocoaPods guide](https://guides.cocoapods.org/using/a-gemfile.html). This way you store all your project's dependencies in version control and can easily install on gems on a new machine 👍

**Comment by aymericbouzy** [comment] 2016-08-03 07:05
Thanks @KrauseFx. I do use a Gemfile, but not necessarily for all my gems. Maybe add a step to check all currently installed gems not present in the Gemfile, add them if necessary, and then clean the project.
