### ISSUE TITLE
Error when running fastlane_update action

### ISSUE THREAD

**Issue by thoughtcroft** [fastlane/fastlane#469] opened 2015-08-04 01:05 UTC
fastlane_update action generated an exception "undefined method `version' for nil:NilClass"

See gist: https://gist.github.com/thoughtcroft/d00f88b628401f78d5b7

**Comment by KrauseFx** [comment] 2015-08-04 09:07
Thanks for reporting @thoughtcroft 

The issue is caused by 
```ruby
        all_updated_tools = updater.installer.installed_gems.select do |updated_tool|
          updated_tool.version > highest_versions[updated_tool.name].version
        end
```

Maybe @milch could take a quick look at this?

**Comment by milch** [comment] 2015-08-05 09:23
Unless some tool changed its name with an update, I don't really see how this could cause a problem. `updated_tool` can't be nil, and the information from `highest_versions` is used to update in the first place.

**Comment by JaviSoto** [comment] 2015-12-10 20:08
Hi @thoughtcroft! is this still an issue? :)

**Comment by asfalcone** [comment] 2016-03-29 20:16
Going to close this issue since it hasn't been updated in some time.

**Closed by asfalcone** 2016-03-29 20:16 UTC
