### ISSUE TITLE
Fastlane screengrab throws adb not found error

### ISSUE THREAD

**Issue by kadam840** [fastlane/fastlane#16121] opened 2020-03-05 11:57 UTC
#16021 # New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm trying to generate screenshots. But screengrab fails.
##### Command executed
fastlane screengrab

##### Complete output when running fastlane, including the stack trace and command used
C:\Users\subhas\StudioProjects\shabdkosh-android-app>fastlane screengrab
 [✔] 🚀
[17:14:59]: fastlane detected a Gemfile in the current directory
[17:14:59]: However, it seems like you didn't use `bundle exec`
[17:14:59]: To launch fastlane faster, please use
[17:14:59]:
[17:14:59]: $ bundle exec fastlane screengrab
[17:14:59]:
[17:14:59]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
'cat' is not recognized as an internal or external command,
operable program or batch file.
[17:15:04]: The `adb` command could not be found relative to your provided ANDROID_HOME at C:\Users\subhas\AppData\Local\Android\Sdk\
[17:15:04]: Please ensure that the Android SDK is installed and the platform-tools directory is present

[!] adb command not found

### Environment

C:\Users\subhas\StudioProjects\shabdkosh-android-app>fastlane env
 [✔] 🚀
[17:22:22]: fastlane detected a Gemfile in the current directory
[17:22:22]: However, it seems like you didn't use `bundle exec`
[17:22:22]: To launch fastlane faster, please use
[17:22:22]:
[17:22:22]: $ bundle exec fastlane env
[17:22:22]:
[17:22:22]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[17:22:23]: Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                       |
| --------------------------- | --------------------------- |
| OS                          | UNKNOWN                     |
| Ruby                        | 2.6.5                       |
| Bundler?                    | false                       |
| Git                         | not found                   |
| Installation Source         | C:/Ruby26-x64/bin/fastlane  |
| Host                        | Unknown  ()                 |
| Ruby Lib Dir                | C:/Ruby26-x64/lib           |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019 |
| Is contained                | false                       |
| Is homebrew                 | false                       |
| Is installed via Fabric.app | false                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

flavors ={
#listof flavors
}


platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Fetch meta data of apps"
  lane :fetchMetadata do
        flavors.each do |flavor,pack|
                   sh("fastlane supply init --json_key C:/Shabdkosh/KEYSTORE/play_key.json --metadata_path ./metadata/"+flavor+" --package_name "+pack)
       end
  end

  desc "Buid single apk"
  lane :build_app do

    flavor = UI.input("Enter flavor code")
    pack = flavors[flavor]
    UI.success("package '#{pack}'")
    gradle(
      task: "clean"
    )

    gradle(
      task: 'assemble',
      flavor:flavor,
      build_type: 'Debug'
   )
    gradle(
      task: 'assemble' + flavor,
      build_type: 'DebugAndroidTest'
    )

    capture_android_screenshots(
      app_package_name: pack,
      clear_previous_screenshots: true,
      output_directory: 'fastlane/metadata/' + flavor,
      app_apk_path: "app/build/outputs/apk/" + flavor + "/debug/app-" + flavor + "-arm64-v8a-debug.apk",
      tests_apk_path: "app/build/outputs/apk/androidTest/" + flavor + "/debug/app-" + flavor+"-debug-androidTest.apk"
    )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("C:\Shabdkosh\KEYSTORE") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("example.com") # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.143.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.15.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.72.0       |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 1.17.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.25.1       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-eventstream           | 1.0.3        |
| aws-sigv4                 | 1.1.1        |
| aws-sdk-core              | 2.11.460     |
| aws-sdk-resources         | 2.11.460     |
| aws-sdk                   | 2.11.460     |
| json                      | 2.3.0        |
| multi_json                | 1.14.1       |
| signet                    | 0.13.0       |
| os                        | 1.0.1        |
| memoist                   | 0.16.2       |
| googleauth                | 0.11.0       |
| google-cloud-env          | 1.3.1        |
| digest-crc                | 0.5.1        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| fiddle                    | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| zlib                      | 1.0.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
</details>

*generated on:* **2020-03-05**

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by joshdholtz** [comment] 2020-03-05 17:45
@kadam840 Looking into!

**Comment by joshdholtz** [comment] 2020-03-05 17:48
@kadam840 Has this worked in the past for you? Or is this the first time you are trying `screengrab`? 

Are you able to run something like `adb --version` in your command prompt outside of _fastlane_?

**Comment by kadam840** [comment] 2020-03-05 17:50
This is the first time Im working on screengrab.

**Comment by janpio** [comment] 2020-03-05 21:09
Duplicate of https://github.com/fastlane/fastlane/issues/16075

Please don't do that @kadam840, you just wasted @joshdholtz 's time.

**Closed by janpio** 2020-03-05 21:09 UTC

**Comment by kadam840** [comment] 2020-03-06 06:46
> @kadam840 Has this worked in the past for you? Or is this the first time you are trying `screengrab`?
> 
> Are you able to run something like `adb --version` in your command prompt outside of _fastlane_?

yes. adb is up to date and working through command line.

**Comment by kadam840** [comment] 2020-03-06 06:47
I dont understand what is wrong with fastlane.

**Comment by kadam840** [comment] 2020-03-06 06:48
There are already similar issues but  you have not solved it for any of them.
