### ISSUE TITLE
App Review information not persisting from previous version

### ISSUE THREAD

**Issue by john-mejia** [fastlane/fastlane#17333] opened 2020-09-28 20:25 UTC
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: After ConnectAPI changes

### Regression Description

Prior to the ConnectAPI changes, any new build sent to App Store would keep the review information from the previous build. (beta user name and beta password). 

In the latest builds, this information has not persisted, we've been having to manually input it every time. 

Our lane for this has been pretty straight forward:
```
appstore(		     
       username: ENV['APPSTORE_USERNAME'],
       force: true,
       app_version: "#{version}"
     )
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by john-mejia** [comment] 2020-09-28 20:26
@joshdholtz, as requested [here](https://github.com/fastlane/fastlane/issues/16502#issuecomment-700253322) - Let me know if you need more details here. I didn't think the environment would be too helpful for this one.

**Comment by joshdholtz** [comment] 2020-09-28 20:27
@john-mejia Greatly appreciated it! I won't be able to look in to anymore today (I got some family stuff to do) but I will look into tomorrow (or Wednesday at latest) for you!

**Comment by max-ott** [comment] 2020-10-01 09:12
Is this for complete app review information or only username/password? (Possible duplicate of https://github.com/fastlane/fastlane/issues/17309)

**Comment by john-mejia** [comment] 2020-10-01 13:22
It's just the username/password as far as I've noticed. It looks like this is indeed a duplicate of #17309

**Closed** 2020-11-08 17:30 UTC
Labels: status: waiting-for-reply, tool: deliver
