### ISSUE TITLE
[download_dsyms] Wrong build version and dSYMS selected for "latest" version

### ISSUE THREAD

**Issue by Kaspik** [fastlane/fastlane#17474] opened 2020-10-20 11:05 UTC
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues) - yes, existing issues: https://github.com/fastlane/fastlane/issues/17326, somehow related: https://github.com/fastlane/fastlane/issues/17202

### Issue Description
Based on docs [here](http://docs.fastlane.tools/actions/download_dsyms/#download_dsyms): `The app version for dSYMs you wish to download, pass in 'latest' to download only the latest build's dSYMs or 'live' to download only the live version dSYMs`
We have a CI that builds project, sends it to the TestFlight, waits for build processing, distributes it to the users and updates dSYMs. I was expecting when calling `"latest"` that the dSYMs are dSYMs for currently uploaded build.
When calling `download_dsyms` with `version: "latest"`, it downloads dSYMs for latest live version. Shouldn't that be happening for `version: "live"`?

##### Command executed
```
desc "Uploads build with given IPA path to the TestFlight and submits build for review or sends it out to TestFlight users if build is approved already"
   private_lane :send_testflight_build do |options|

      puts options[:ipa_path]

      # Trigger testflight build
      pilot(
         ipa: options[:ipa_path],
         beta_app_review_info: {
            contact_email: "email",
            contact_first_name: "name",
            contact_last_name: "surname",
            contact_phone: "phone",
            demo_account_name: "email",
            demo_account_password: "password",
            notes: "notes"
         },
         changelog: default_changelog,
         beta_app_description: beta_app_description,
         beta_app_feedback_email: "email",
         demo_account_required: true,
         distribute_external: true,
         groups: ['Group 1', 'Group 2', 'Group 3']
      )

      update_dsyms
   end
```

Then `update_dsyms` lane is:
```
desc "Downloads dSYMs for latest uploaded build and uploads them to Firebase Crashlytics"
   lane :update_dsyms do |options|
      # Download dSYM files from AppStore Connect
      download_dsyms(
         version: "latest",
         wait_for_dsym_processing: true,
         wait_timeout: 900
      )

      # Upload dSYM files from AppStore Connect to Firebase Cryshlatics
      sh "../Pods/FirebaseCrashlytics/upload-symbols -gsp '../Supporting Files/GoogleService-Info.plist' -p ios #{lane_context[SharedValues::DSYM_PATHS].first}"
   end
```

##### Complete output when running fastlane, including the stack trace and command used
```
[06:06:20]: Waiting for App Store Connect to finish processing the new build (7.13.0 - 1068) for IOS
[06:06:51]: Successfully finished processing the build 7.13.0 - 1068 for IOS
[06:23:56]: Successfully set the beta_app_feedback_email and/or beta_app_description
[06:40:47]: Successfully set the changelog for build
[06:40:48]: Distributing new build to testers: 7.13.0 - 1068
[06:40:54]: Successfully distributed build to External testers 🚀
[06:40:54]: ---------------------------------------------
[06:40:54]: --- Step: Switch to ios update_dsyms lane ---
[06:40:54]: ---------------------------------------------
[06:40:54]: Cruising over to lane 'ios update_dsyms' 🚖
[06:40:54]: ----------------------------
[06:40:54]: --- Step: download_dsyms ---
[06:40:54]: ----------------------------
[06:40:54]: Login to App Store Connect
[06:40:55]: Login successful
[06:41:00]: Looking for latest version...
[06:41:01]: Looking for dSYM files for 'com.ClassDojo' on platform IOS v7.12.0 (1066)
[06:41:48]: 🔑  Successfully downloaded dSYM file for 7.12.0 - 1066 to 'com.ClassDojo-7.12.0-1066.dSYM.zip'
```

### fastlane gems
```
| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.164.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**
```

<details><summary><b>Loaded gems</b></summary>

| Gem                                  | Version      |
| ------------------------------------ | ------------ |
| did_you_mean                         | 1.4.0        |
| bundler                              | 2.1.4        |
| uri                                  | 0.10.0       |
| rake                                 | 13.0.1       |
| CFPropertyList                       | 3.0.2        |
| concurrent-ruby                      | 1.1.7        |
| i18n                                 | 1.8.5        |
| minitest                             | 5.14.2       |
| thread_safe                          | 0.3.6        |
| tzinfo                               | 1.2.7        |
| activesupport                        | 5.2.4.4      |
| public_suffix                        | 4.0.6        |
| addressable                          | 2.7.0        |
| httpclient                           | 2.8.3        |
| json                                 | 2.3.1        |
| algoliasearch                        | 1.27.4       |
| atomos                               | 0.1.3        |
| aws-eventstream                      | 1.1.0        |
| aws-partitions                       | 1.383.0      |
| aws-sigv4                            | 1.2.2        |
| jmespath                             | 1.4.0        |
| aws-sdk-core                         | 3.109.1      |
| aws-sdk-kms                          | 1.39.0       |
| aws-sdk-s3                           | 1.83.1       |
| babosa                               | 1.0.4        |
| claide                               | 1.0.3        |
| colored2                             | 3.1.2        |
| cork                                 | 0.3.0        |
| nap                                  | 1.1.0        |
| open4                                | 1.3.4        |
| claide-plugins                       | 0.9.2        |
| fuzzy_match                          | 2.0.4        |
| netrc                                | 0.11.0       |
| ffi                                  | 1.13.1       |
| ethon                                | 0.12.0       |
| typhoeus                             | 1.4.0        |
| cocoapods-core                       | 1.10.0.rc.1  |
| cocoapods-deintegrate                | 1.0.4        |
| cocoapods-downloader                 | 1.4.0        |
| cocoapods-plugins                    | 1.0.0        |
| cocoapods-search                     | 1.0.0        |
| cocoapods-trunk                      | 1.5.0        |
| cocoapods-try                        | 1.2.0        |
| escape                               | 0.0.4        |
| fourflusher                          | 2.3.1        |
| gh_inspector                         | 1.1.3        |
| molinillo                            | 0.6.6        |
| ruby-macho                           | 1.4.0        |
| nanaimo                              | 0.3.0        |
| xcodeproj                            | 1.19.0       |
| cocoapods                            | 1.10.0.rc.1  |
| colored                              | 1.2          |
| highline                             | 1.7.10       |
| commander-fastlane                   | 4.4.6        |
| multipart-post                       | 2.0.0        |
| ruby2_keywords                       | 0.0.2        |
| faraday                              | 1.1.0        |
| faraday-http-cache                   | 2.2.0        |
| rchardet                             | 1.8.0        |
| git                                  | 1.7.0        |
| rexml                                | 3.2.4        |
| kramdown                             | 2.3.0        |
| kramdown-parser-gfm                  | 1.1.0        |
| no_proxy_fix                         | 0.1.2        |
| sawyer                               | 0.8.2        |
| octokit                              | 4.18.0       |
| unicode-display_width                | 1.7.0        |
| terminal-table                       | 1.8.0        |
| danger                               | 8.1.0        |
| danger-duplicate_localizable_strings | 0.3.0        |
| thor                                 | 0.20.3       |
| danger-swiftlint                     | 0.24.4       |
| dotenv                               | 2.7.6        |
| emoji_regex                          | 3.0.0        |
| excon                                | 0.78.0       |
| unf_ext                              | 0.0.7.7      |
| unf                                  | 0.1.4        |
| domain_name                          | 0.5.20190701 |
| http-cookie                          | 1.0.3        |
| faraday-cookie_jar                   | 0.0.7        |
| faraday_middleware                   | 1.0.0        |
| fastimage                            | 2.2.0        |
| jwt                                  | 2.2.2        |
| memoist                              | 0.16.2       |
| multi_json                           | 1.15.0       |
| os                                   | 1.1.1        |
| signet                               | 0.14.0       |
| googleauth                           | 0.14.0       |
| mini_mime                            | 1.0.2        |
| declarative                          | 0.0.20       |
| declarative-option                   | 0.1.0        |
| uber                                 | 0.1.0        |
| representable                        | 3.0.4        |
| retriable                            | 3.1.2        |
| google-api-client                    | 0.38.0       |
| digest-crc                           | 0.6.1        |
| google-cloud-env                     | 1.4.0        |
| google-cloud-errors                  | 1.0.1        |
| google-cloud-core                    | 1.5.0        |
| google-cloud-storage                 | 1.29.1       |
| mini_magick                          | 4.10.1       |
| plist                                | 3.5.0        |
| rubyzip                              | 2.3.0        |
| security                             | 0.1.3        |
| naturally                            | 2.2.0        |
| simctl                               | 1.6.8        |
| slack-notifier                       | 2.3.2        |
| terminal-notifier                    | 2.0.0        |
| tty-screen                           | 0.8.1        |
| tty-cursor                           | 0.7.1        |
| tty-spinner                          | 0.9.3        |
| word_wrap                            | 1.0.0        |
| rouge                                | 2.0.7        |
| xcpretty                             | 0.3.0        |
| xcpretty-travis-formatter            | 1.0.0        |
| xcresult                             | 0.2.1        |
| xcov                                 | 1.7.5        |
| danger-xcov                          | 0.5.0        |
</details>

**Comment by Kaspik** [comment] 2020-10-20 11:12
@joshdholtz I believe this was introduced in bigger changes like https://github.com/fastlane/fastlane/pull/17148.

**Comment by joshdholtz** [comment] 2020-10-20 19:40
Ohhhhhhhh... I think I see what is going on 😔 Will fix tomorrow!

**Comment by Kaspik** [comment] 2020-11-11 10:21
@joshdholtz I see you moved this to Doing 15 days ago, any blocker or is everything okay? :)

**Comment by joshdholtz** [comment] 2020-11-11 11:31
@Kaspik Foggy mind from US elections, emergency issues, and life 🤷‍♂️ Haven't forgotten about this though!

**Comment by Kaspik** [comment] 2021-01-13 17:33
Please reopen.

**Comment by rogerluan** [comment] 2021-02-13 18:35
Reopening upon request ☝️

**Comment by rogerluan** [comment] 2021-02-13 20:41
Hey @Kaspik I took a stab at resolving your issue and this seems to be a proper solution, as I confirmed in my tests: https://github.com/fastlane/fastlane/pull/18201

If you could help test it to see if it resolves your scenario, that'd be really helpful! 

Thanks for reporting this regression 💪

**Comment by rogerluan** [comment] 2021-02-13 20:42
Hey btw @joshdholtz since this issue seemed inactive for awhile I took the liberty of taking it from your plate 🙈 please forgive me for my sins 🙇 
I'd appreciate a review from your end though ❤️

**Comment by Kaspik** [comment] 2021-02-13 20:56
Thanks, will take a look!

**Closed** 2021-02-18 16:59 UTC
Labels: status: regression, tool: download_dsyms
