### ISSUE TITLE
app_store_build_number always returns 1

### ISSUE THREAD

**Issue by tarbayev** [fastlane/fastlane#14595] opened 2019-04-15 10:34 UTC
`app_store_build_number` always returns 1, when using it like this:
```
    latest_build_number = app_store_build_number(
      app_identifier: app_id,
      initial_build_number: 0,
      version: get_version_number,
      live: false
    )
```

`fastlane 2.120.0`
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.14.3                                          |
| Ruby                        | 2.5.1                                            |
| Bundler?                    | true                                             |
| Git                         | git version 2.21.0                               |
| Installation Source         | ~/.rbenv/versions/2.5.1/bin/fastlane             |
| Host                        | Mac OS X 10.14.3 (18D109)                        |
| Ruby Lib Dir                | ~/.rbenv/versions/2.5.1/lib                      |
| OpenSSL Version             | OpenSSL 1.0.2q  20 Nov 2018                      |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode-10.1.app/Contents/Developer/ |
| Xcode Version               | 10.1                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform(:ios)

platform :ios do
  desc "Fetches and builds frameworks using Carthage"
  lane :bootstrap do
    carthage(command: "bootstrap", platform: "ios", cache_builds: true, toolchain: "com.apple.dt.toolchain.Swift_4_2_1")
  end

  desc "Installs Sourcery tool"
  lane :install_sourcery do
    Dir.chdir("..") do
      script_path = File.join(ENV["PWD"], "install_sourcery.sh")
      sh(script_path, "0.15.0")
    end
  end

  desc "Generates mocks using Sourcery. You can provide \"watch\" parameter (watch:) to observe sourcers in real time"
  lane :generate_mocks do |options|
    sourcery_path = File.join(ENV["PWD"], "Sourcery/sourcery")
    templates_path = File.join(ENV["PWD"], "mocky.yml")

    unless File.file?(sourcery_path)
      install_sourcery
    end
    if options[:watch]
      sh(sourcery_path, "--config", templates_path, "--watch")
    else
      sh(sourcery_path, "--config", templates_path)
    end
  end

  desc "Lints the project using SwiftLint"
  lane :lint do
    run_swiftilt
  end

  def run_swiftilt
    gitlab_project_url = ENV["CI_PROJECT_URL"]

    if gitlab_project_url
      artifacts_dir = File.join(ENV["PWD"], ENV["ARTIFACTS_DIR"])
      FileUtils.mkdir_p(artifacts_dir)

      host = URI(gitlab_project_url).host
      ENV["DANGER_GITLAB_HOST"] = host
      ENV["DANGER_GITLAB_API_BASE_URL"] = "https://#{host}/api/v4"

      danger(
        danger_id: "lint",
        dangerfile: "Dangerfile-lint",
        verbose: true,
        fail_on_errors: true
      )
    else
      swiftlint
    end
  end

  desc "Runs tests on the project"
  lane :test do
    scan(
      scheme: ENV["FLX_TEST_SCHEME"],
      output_directory: ENV["ARTIFACTS_DIR"],
      clean: true
    )
  end

  desc "Make a build and upload it to TestFlight\n
  :environment [sandbox, production]. Default to sandbox."
  lane :deploy do |options|
    
    # project file will be modified for signing during the deployment
    # the changes will be discarded after deployment completion
    ensure_git_status_clean

    environment = options[:environment]&.to_sym || :sandbox

    app_identifiers = {
      sandbox: "com.flixbus.ios.flixapp.sandbox",
      production: "com.flixbus.ios.flixapp"
    }

    app_id = app_identifiers[environment]

    latest_build_number = latest_testflight_build_number(
      app_identifier: app_id,
      initial_build_number: 0,
      version: get_version_number,
      live: false
    )

    increment_build_number(
      build_number: latest_build_number + 1
    )

    password = SecureRandom.base64
    keychain_name = "fastlane"

    ENV["MATCH_KEYCHAIN_NAME"] = keychain_name
    ENV["MATCH_KEYCHAIN_PASSWORD"] = password

    keychain_path = File.expand_path("~/Library/Keychains/#{keychain_name}-db")

    if File.exist? keychain_path
      puts "Removing existing keychain #{keychain_path}"
      delete_keychain(
        name: keychain_name
      )
    end

    create_keychain(
      name: keychain_name,
      password: password,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: true
    )

    # create_keychain adds keychain to the end of search list,
    # we want it to be the first to search in
    keychains = Action.sh("security list-keychains -d user").shellsplit
    keychains.unshift File.expand_path(keychain_path)
    Actions.sh("security list-keychains -s #{keychains.shelljoin}", log: true)

    match_type = "appstore"

    # fetch provisioning profile
    match(
      app_identifier: app_id,
      type: match_type,
      keychain_name: keychain_name,
      keychain_password: password,
      readonly: true,
      verbose: true
    )

    sceme_names = {
      sandbox: "flixapp-sandbox",
      production: "flixapp-production"
    }

    # required for using match results
    disable_automatic_code_signing

    # update with provisional profile provided by match
    update_project_provisioning(
      profile: ENV[Match::Utils.environment_variable_name_profile_path(
        app_identifier: app_id,
        type: match_type
      )],
      build_configuration: "Release",
      code_signing_identity: "iPhone Distribution"
    )

    # build the app
    gym(
      scheme: sceme_names[environment],
      # workspace: ENV["FLX_WORKSPACE"], # Provide a workspace name if you have more than one project
      export_method: "app-store",
      clean: true,
      codesigning_identity: "iPhone Distribution",
      xcargs: {
        "PRODUCT_BUNDLE_IDENTIFIER": app_id
      }
    )

    app_description = "Built from #{git_branch} #{last_git_commit[:abbreviated_commit_hash]}"

    # upload to TestFlight
    pilot(
      skip_submission: true,
      skip_waiting_for_build_processing: false,
      changelog: app_description
    )

    delete_keychain(
      name: keychain_name
    )

    # resetting project file
    reset_git_repo(
      force: true,
      files: [
        "flixapp.xcodeproj"
      ]
    )
  end

  desc "Fetches & applies most recent translations from SPA"
  lane :update_translations do
    Dir.mktmpdir do |tmp_path|
      flx_download_spa(
        project_name: 'pax-app-android-ios',
        output_path: tmp_path,
        exclude_patterns: ['MeinFernbus/strings/MFB/*'],
      )

      languages = flx_get_project_languages

      unknown_language_dirs = Dir["#{tmp_path}/**/*"].select do |f|
        (File.directory? f) && (File.extname(f) == '.lproj') && (!languages.include? File.basename(f, '.lproj'))
      end

      FileUtils.rm_r unknown_language_dirs
      Dir["#{tmp_path}/MeinFernbus/strings/FlixBus/*"].each do |path|
        next unless File.directory? path
        FileUtils.cp_r path, '../flixapp/Strings'
      end
    end
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
apple_id("mobile-jenkins@flixbus.com") # Your Apple email address
itc_team_id("13395800")

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.120.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| bundler                   | 2.0.1        |
| fileutils                 | 1.1.0        |
| rake                      | 12.3.2       |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| cork                      | 0.3.0        |
| nap                       | 1.1.0        |
| open4                     | 1.3.4        |
| claide-plugins            | 0.9.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| faraday-http-cache        | 1.3.1        |
| git                       | 1.5.0        |
| kramdown                  | 1.17.0       |
| no_proxy_fix              | 0.1.2        |
| sawyer                    | 0.8.1        |
| octokit                   | 4.13.0       |
| unicode-display_width     | 1.4.1        |
| terminal-table            | 1.8.0        |
| danger                    | 5.11.1       |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| multi_xml                 | 0.6.0        |
| httparty                  | 0.16.3       |
| gitlab                    | 4.8.0        |
| danger-gitlab             | 6.0.0        |
| thor                      | 0.20.3       |
| danger-swiftlint          | 0.18.2       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.7.2        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.62.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.0        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.2.0        |
| mini_magick               | 4.5.1        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.1        |
| tty-spinner               | 0.9.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| xcode-install             | 2.5.0        |
</details>

*generated on:* **2019-04-17**
</details>

Might be related to #14540

**Comment by elmdecoste** [comment] 2019-04-15 19:26
We are also experiencing this issue, no matter the build number we are receiving the same version code. Attached is the `fastlane env` and the calls we are making via spaceship

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.4                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.17.2 (Apple Git-113)                             |
| Installation Source         | ~/Projects/project/vendor/bundle/ruby/2.3.0/bin/fastlane       |
| Host                        | Mac OS X 10.14.4 (18E226)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.5                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 10.1                                                           |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |



### Spaceship Calls

def set_project_build_number(data)
    bundle_id = bundle_identifier(data)

    Spaceship::Tunes.login(USERNAME)
    Spaceship::Tunes.select_team
    app = Spaceship::Tunes::Application.find(bundle_id)
    version = data["version"]
    train = app.build_trains[version]
    
    puts "Getting latest build number for version:" + version
    
    if train == nil
        puts "No version found on iTunes. Setting build number to 0"
        increment_build_number(build_number: 0)
    else
        build_count = train.first.build_version.to_i
        puts "Build number reported by iTunes Connect: " + build_count.to_s
        increment_build_number(build_number: build_count + 1)
    end
end


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.120.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| bundler                   | 1.16.5       |
| io-console                | 0.4.5        |
| CFPropertyList            | 2.3.6        |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.10       |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| atomos                    | 0.1.3        |
| awesome_print             | 1.8.0        |
| babosa                    | 1.0.2        |
| builder                   | 3.2.3        |
| clipboard                 | 1.1.1        |
| gherkin                   | 4.1.3        |
| cucumber-core             | 1.5.0        |
| cucumber-wire             | 0.0.1        |
| diff-lcs                  | 1.3          |
| multi_json                | 1.13.1       |
| multi_test                | 0.1.2        |
| cucumber                  | 2.99.0       |
| edn                       | 1.1.1        |
| geocoder                  | 1.4.7        |
| httpclient                | 2.8.3        |
| json                      | 1.8.6        |
| command_runner_ng         | 0.1.3        |
| thor                      | 0.20.0       |
| run_loop                  | 2.6.6        |
| slowhandcuke              | 0.0.3        |
| calabash-cucumber         | 0.21.5       |
| claide                    | 1.0.2        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.5.3        |
| cocoapods-deintegrate     | 1.0.2        |
| cocoapods-downloader      | 1.2.1        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.5        |
| ruby-macho                | 1.2.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.2        |
| cocoapods                 | 1.5.3        |
| colored                   | 1.2          |
| colorize                  | 0.8.1        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.7.2        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.5        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| google-cloud-storage      | 1.16.0       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.5.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.1        |
| tty-spinner               | 0.9.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| git                       | 1.4.0        |
</details>


*generated on:* **2019-04-15**
</details>

**Comment by nzaghini-phorest** [comment] 2019-04-17 09:36
I had same issue but with latest update it seems fixed now. 

Below my env! 👍

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.4                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.20.1 (Apple Git-117)                             |
| Installation Source         | ~/vendor/cache/ruby/2.3.0/bin/fastlane                         |
| Host                        | Mac OS X 10.14.4 (18E226)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.5                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 10.2                                                           |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby

    desc "Bumps the build number, builds and distributes to TestFlight Beta"
    lane :beta do  
      current_build_number = latest_testflight_build_number(version: get_version_number)
      new_build_number = increment_build_number(build_number: current_build_number + 1)
      
      build
      pilot(skip_waiting_for_build_processing: "true")

      build_number = "#{get_version_number}(#{new_build_number})"
      tag(platform: "iOS", build_number: build_number)
      
    end

```
</details>

**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.120.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                                 | Version | Update-Status |
| -------------------------------------- | ------- | ------------- |
| fastlane-plugin-increment_version_code | 0.4.3   | ✅ Up-To-Date  |
| fastlane-plugin-versioning_android     | 0.1.0   | ✅ Up-To-Date  |
| fastlane-plugin-update_android_strings | 0.1.0   | ✅ Up-To-Date  |


<details><summary><b>Loaded gems</b></summary>

| Gem                                    | Version      |
| -------------------------------------- | ------------ |
| did_you_mean                           | 1.0.0        |
| bundler                                | 1.17.2       |
| io-console                             | 0.4.5        |
| CFPropertyList                         | 3.0.0        |
| public_suffix                          | 2.0.5        |
| addressable                            | 2.6.0        |
| atomos                                 | 0.1.3        |
| babosa                                 | 1.0.2        |
| claide                                 | 1.0.2        |
| colored                                | 1.2          |
| colored2                               | 3.1.2        |
| highline                               | 1.7.10       |
| commander-fastlane                     | 4.4.6        |
| declarative                            | 0.0.10       |
| declarative-option                     | 0.1.0        |
| digest-crc                             | 0.4.1        |
| unf_ext                                | 0.0.7.5      |
| unf                                    | 0.1.4        |
| domain_name                            | 0.5.20180417 |
| dotenv                                 | 2.7.2        |
| emoji_regex                            | 1.0.1        |
| excon                                  | 0.64.0       |
| multipart-post                         | 2.0.0        |
| faraday                                | 0.15.4       |
| http-cookie                            | 1.0.3        |
| faraday-cookie_jar                     | 0.0.6        |
| faraday_middleware                     | 0.13.1       |
| fastimage                              | 2.1.5        |
| gh_inspector                           | 1.1.3        |
| jwt                                    | 2.1.0        |
| memoist                                | 0.16.0       |
| multi_json                             | 1.13.1       |
| os                                     | 1.0.0        |
| signet                                 | 0.11.0       |
| googleauth                             | 0.6.7        |
| httpclient                             | 2.8.3        |
| mime-types-data                        | 3.2019.0331  |
| mime-types                             | 3.2.2        |
| uber                                   | 0.1.0        |
| representable                          | 3.0.4        |
| retriable                              | 3.1.2        |
| google-api-client                      | 0.23.9       |
| google-cloud-env                       | 1.0.5        |
| google-cloud-core                      | 1.3.0        |
| google-cloud-storage                   | 1.16.0       |
| json                                   | 2.2.0        |
| mini_magick                            | 4.5.1        |
| multi_xml                              | 0.6.0        |
| plist                                  | 3.5.0        |
| rubyzip                                | 1.2.2        |
| security                               | 0.1.3        |
| naturally                              | 2.2.0        |
| simctl                                 | 1.6.5        |
| slack-notifier                         | 2.3.2        |
| terminal-notifier                      | 2.0.0        |
| unicode-display_width                  | 1.5.0        |
| terminal-table                         | 1.8.0        |
| tty-screen                             | 0.6.5        |
| tty-cursor                             | 0.6.1        |
| tty-spinner                            | 0.9.0        |
| word_wrap                              | 1.0.0        |
| nanaimo                                | 0.2.6        |
| xcodeproj                              | 1.8.2        |
| rouge                                  | 2.0.7        |
| xcpretty                               | 0.3.0        |
| xcpretty-travis-formatter              | 1.0.0        |
| fastlane-plugin-increment_version_code | 0.4.3        |
| ox                                     | 2.10.0       |
| fastlane-plugin-update_android_strings | 0.1.0        |
| fastlane-plugin-versioning_android     | 0.1.0        |
| netrc                                  | 0.11.0       |
| rest-client                            | 2.0.2        |
| xcode-install                          | 2.5.0        |
</details>


*generated on:* **2019-04-17**
</details>

**Comment by tarbayev** [comment] 2019-04-17 12:24
I switched to `latest_testflight_build_number` as a workaround.

**Comment by ramnac** [comment] 2019-04-26 21:52
@tarbayev @elmdecoste 

The problem is sort by Uploaded date for the get builds in the code. Which I fixed it and the PR is open.

You can try using my forked repo. Let me know if that solves your problem.

(You can do so by replacing gem 'fastlane' with gem 'fastlane', :git => 'https://github.com/ramnac/fastlane', :branch => 'master' and then running bundle update)

**Comment by octav-daysix** [comment] 2019-04-29 15:33
I found this issue very useful: [How to set CURRENT_PROJECT_VERSION in xcode 8](https://stackoverflow.com/a/55525399.)
Instead of modifing the value in "build version" in xCode, you modify 
`CFBundleVersion` 
`CFBundleShortVersionString` 
in info.plist make sure that CFBundleShortVersionString is the same as the Build Version number.
Then publish and if you run app_store_build_number now it should work as expect.

**Closed** 2019-06-09 17:33 UTC
Labels: status: waiting-for-reply, tool: action
