### ISSUE TITLE
fastlane pilot add doesn't add testers 

### ISSUE THREAD

**Issue by bencollier** [fastlane/fastlane#8728] opened 2017-03-31 12:29 UTC
### New Issue Checklist

- [🚀] Updated fastlane to the latest version
- [🚀] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Running `fastlane pilot add` doesn't add the tester, but errors with:

```
[!] Some operations failed: [testername@example.com]: User [appleid@example.com] (Team ID [123456]) doesn't have enough permission for the following action: parse_response
```

This is with an App Developer role, which has permission to add testers when done through iTC. Likely related, trying to upload a csv of testers fails with _unable to add tester_ for each row in the csv.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

--capture_output doesn't work with `fastlane pilot add`

**Comment by bencollier** [comment] 2017-03-31 12:34
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.3.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rbenv/versions/2.3.0/bin/fastlane        |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.0/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.24.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.8.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.1       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.7       |
| faraday_middleware        | 0.10.1       |
| io-console                | 0.4.5        |
</details>


*generated on:* **2017-03-31**
</details>

**Comment by hjanuschka** [comment] 2017-04-03 06:22
could you rerun it with `fastlane --verbose pilot add` so we'd get a full stacktrace, and see where exactly the exception is raised?

many thx!

**Comment by bencollier** [comment] 2017-04-03 09:13
Sure thing, `fastlane --verbose pilot add` didn't work btw, needed `fastlane pilot add --verbose`

Output:

```
INFO [2017-04-03 10:10:46.40]: Login successful
ERROR [2017-04-03 10:10:47.16]: Could not create tester tester@example.com
ERROR [2017-04-03 10:10:47.16]: [tester@example.com]: User developer@example.com (Team ID 12345) doesn't have enough permission for the following action: parse_response
/Users/bencollier/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-2.24.0/fastlane_core/lib/fastlane_core/ui/interface.rb:150:in `user_error!': [!] Some operations failed: [ tester@example.com]: User developer@example.com (Team ID 12345) doesn't have enough permission for the following action: parse_response (FastlaneCore::Interface::FastlaneError)
	from /Users/bencollier/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-2.24.0/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/bencollier/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-2.24.0/pilot/lib/pilot/commands_generator.rb:37:in `handle_multiple'
	from /Users/bencollier/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-2.24.0/pilot/lib/pilot/commands_generator.rb:94:in `block (2 levels) in run'
	from /Users/bencollier/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/bencollier/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Users/bencollier/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/bencollier/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-2.24.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/bencollier/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Users/bencollier/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-2.24.0/pilot/lib/pilot/commands_generator.rb:158:in `run'
	from /Users/bencollier/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-2.24.0/pilot/lib/pilot/commands_generator.rb:12:in `start'
	from /Users/bencollier/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-2.24.0/fastlane/lib/fastlane/cli_tools_distributor.rb:51:in `take_off'
	from /Users/bencollier/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-2.24.0/bin/fastlane:20:in `<top (required)>'
	from /Users/bencollier/.rbenv/versions/2.3.0/bin/fastlane:23:in `load'
	from /Users/bencollier/.rbenv/versions/2.3.0/bin/fastlane:23:in `<main>'
```

This is an Apple ID that belongs to multiple teams.

**Comment by hjanuschka** [comment] 2017-04-03 09:33
thx - sorry about the wrong position about the verbose flag.

ok looks like the error gets swallowed - to further debug it - could you try running the following code:

debug.rb
```
require "spaceship"

#variables
tester_email = "tester@mail.com"
apple_id = "apple_id@me.com" 
app_id = "my.app.id"


Spaceship::Tunes.login(apple_id)
Spaceship::Tunes.select_team

tester = Spaceship::Tunes::Tester::Internal.find(tester_email)
tester ||= Spaceship::Tunes::Tester::External.find(tester_email)


app = Spaceship::Application.find(app_id)
tester.add_to_app!(app.apple_id)

```

currently i bet on `Application.find()` failing due to permissions - would be awesome if we can confirm this.

**Comment by bencollier** [comment] 2017-04-03 09:45
You got it!

```
/Users/bencollier/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-2.24.0/spaceship/lib/spaceship/client.rb:506:in `raise_insuffient_permission_error!': User tester@example.com (Team ID 123456) doesn't have enough permission for the following action: parse_response (Spaceship::Client::InsufficientPermissions)
	from /Users/bencollier/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-2.24.0/spaceship/lib/spaceship/client.rb:481:in `detect_most_common_errors_and_raise_exceptions'
	from /Users/bencollier/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-2.24.0/spaceship/lib/spaceship/client.rb:458:in `parse_response'
	from /Users/bencollier/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-2.24.0/spaceship/lib/spaceship/tunes/tunes_client.rb:1142:in `testers'
	from /Users/bencollier/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-2.24.0/spaceship/lib/spaceship/tunes/tester.rb:79:in `all'
	from /Users/bencollier/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-2.24.0/spaceship/lib/spaceship/tunes/tester.rb:86:in `find'

```

**Comment by hjanuschka** [comment] 2017-04-03 10:49
ok - so if you grant the app to the user will it work - how does the webinterface look, you see the app?
i don't see any "easy" fix - to get rid of `Application.find`  - as it is required to find the app-id (nummeric) by given bundle identifier (string)


the request that seems to  fail is:
`ra/apps/manageyourapps/summary/v2`

as a workaround (requires you to atleast get one time the app-id)

```ruby
require "spaceship"

#variables
tester_email = "tester@mail.com"
apple_id = "apple_id@me.com" 
app_id = 12121212


Spaceship::Tunes.login(apple_id)
Spaceship::Tunes.select_team

tester = Spaceship::Tunes::Tester::Internal.find(tester_email)
tester ||= Spaceship::Tunes::Tester::External.find(tester_email)

tester.add_to_app!(apple_id)

```

this would actually do what `pilot add` does without calling the `Application.find``

**Comment by bencollier** [comment] 2017-04-03 11:08
Sorry - I mislead you earlier. It's actually failing on both of these:

```
tester = Spaceship::Tunes::Tester::Internal.find(tester_email)
tester ||= Spaceship::Tunes::Tester::External.find(tester_email)
```

```
/Users/bencollier/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-2.24.0/spaceship/lib/spaceship/client.rb:506:in `raise_insuffient_permission_error!': User sdfsf@sfs.com (Team ID 123456) doesn't have enough permission for the following action: parse_response (Spaceship::Client::InsufficientPermissions)
	from /Users/bencollier/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-2.24.0/spaceship/lib/spaceship/client.rb:481:in `detect_most_common_errors_and_raise_exceptions'
	from /Users/bencollier/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-2.24.0/spaceship/lib/spaceship/client.rb:458:in `parse_response'
	from /Users/bencollier/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-2.24.0/spaceship/lib/spaceship/tunes/tunes_client.rb:1142:in `testers'
	from /Users/bencollier/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-2.24.0/spaceship/lib/spaceship/tunes/tester.rb:79:in `all'
	from /Users/bencollier/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-2.24.0/spaceship/lib/spaceship/tunes/tester.rb:86:in `find'
	from debug.rb:17:in `<main>'
```


Running 
```
app = Spaceship::Application.find(app_id)
puts "App ID is:  #{app.apple_id}"
```
On the same account gives me back the correct app id without any issue.

I'm perfectly able to add new testers in the web iTC.

**Comment by bencollier** [comment] 2017-04-03 11:13
For what it's worth, calling something like:

```
Spaceship::Tunes::Tester.external.create!(email: "tester@mathiascarignani.com", first_name: "Cary", last_name: "Bennett", groups: ["Testers"])
```

Directly doesn't work either (same permission issue).

**Comment by hjanuschka** [comment] 2017-04-03 11:14
ok thx for the information, going to create a test account with dev. role, and trying to figure out what the problem is, i ll come back to you as soon as possible.

**Comment by bencollier** [comment] 2017-04-03 11:23
This is with an App Manager role, which has access to fiddle with External testers. Developer role can only do internal.

Anything we can do to help let me know 🎉

**Comment by hjanuschka** [comment] 2017-04-03 11:32
@bencollier i created a itc account with developer role.

ok so atleast i got the adding of internal testers working now:


```ruby
require "spaceship"
Spaceship::Tunes.login("hjanuschka@gmail.com")
app = Spaceship::Application.find("krone.at-fivexfive")

tester_email = "itc@krone.at"


tester = Spaceship::Tunes::Tester::Internal.find_by_app(app.apple_id, tester_email)
tester.add_to_app!(app.apple_id)
```

changing `Tester::Internal.find`  to `Tester::Internal.find_by_app`  works, as it uses another endpoint.


still trying to figure out about external testers.

**Comment by hjanuschka** [comment] 2017-04-03 12:05
@bencollier ok thats a can of worms 😨 

however - having a account set to "App-manager" - with the right app granted
the following code works for me - creating and adding an external tester:


```ruby
require "spaceship"

Spaceship::Tunes.login("hjanuschka@gmail.com")
app = Spaceship::Application.find("krone.at-fivexfive")


attrs = {}
attrs["emailAddress"] = {"value" =>  "hjanuschka+tester12@gmail.com" }
attrs["firstName"] = {"value" =>  "Helmut" }
attrs["lastName"] = {"value" =>  "Januschka1" }
tester = Spaceship::Tunes::Tester::External.factory(attrs)

tester.add_to_app!(app.apple_id)
```


let me know if you have any further troubles, if both solutions work, we can think of doing a PR to fix it inside pilot.

**Comment by bencollier** [comment] 2017-04-03 14:35
@hjanuschka it bloody works! Thanks for digging!

Boarding hasn't worked with any account aside from Admin for a year - so I'm presuming this fix would benefit that, and the CSV upload to. 

Great stuff!

**Comment by hjanuschka** [comment] 2017-04-03 15:03
@bencollier thx for the feedback, i ll try to pack it in a PR 👍  (but will take some time)

**Comment by hjanuschka** [comment] 2017-04-05 06:39
@bencollier i did a PR: #8776 which should implement the fixes found in this issue, maybe you could give it a test run.

**Comment by tzm41** [comment] 2017-05-01 20:17
Thanks! Seeing the issue and hoping the fix could be merged soon.

**Closed** 2017-07-09 20:32 UTC
Labels: status: auto-closed, status: waiting-for-reply, tool: pilot
