### ISSUE TITLE
Deliver uploading 3rd gen iPad screenshots into 2nd gen iPad slot

### ISSUE THREAD

**Issue by scorpion35** [fastlane/fastlane#14474] opened 2019-03-26 14:54 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
3rd gen iPad screenshots are uploaded into 2nd gen iPad's slot. Think Apple's API is getting confused (because 3rd gen iPad and 2nd gen iPad screenshot dimensions are same) and sending them to 2nd gen iPad slot, eventually causing doubles in 2nd gen iPad slots.

##### Command executed
`fastlane deliver run -f -u <myusername> --skip_screenshots false -z TBD`

##### Complete output when running fastlane, including the stack trace and command, used

[10:10:50]: Uploading 25 screenshots for language en-US
**[10:10:50]: Uploading './screenshots/en-US/1_12.9inchiPad_EN_app_2732x2048_01.jpg'...**
...
**[10:11:03]: Uploading './screenshots/en-US/2_12.9inchiPad_EN_app_2732x2048_02.jpg'...**
...
**[10:11:13]: Uploading './screenshots/en-US/3_12.9inchiPad_EN_app_2732x2048_03.jpg'...**
...
**[10:11:26]: Uploading './screenshots/en-US/4_12.9inchiPad_EN_app_2732x2048_04.jpg'...**
...
**[10:11:49]: Uploading './screenshots/en-US/5_12.9inchiPad_EN_app_2732x2048_05.jpg'...**
...
[✔] Saving changes 

![output_result](https://user-images.githubusercontent.com/18679225/55007197-61ccd700-4fb5-11e9-9905-16f8a2ab5de4.png)

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.3                                     |
| Ruby                        | 2.5.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.16.2                          |
| Installation Source         | ~/.rbenv/versions/2.5.1/bin/fastlane        |
| Host                        | Mac OS X 10.14.3 (18D109)                   |
| Ruby Lib Dir                | ~/.rbenv/versions/2.5.1/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2q  20 Nov 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.2                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.119.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| unicode-display_width     | 1.4.1        |
| plist                     | 3.5.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.1        |
| tty-spinner               | 0.9.0        |
| faraday                   | 0.15.4       |
| fastimage                 | 2.1.5        |
| dotenv                    | 2.7.1        |
| bundler                   | 2.0.1        |
| faraday_middleware        | 0.13.1       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| httpclient                | 2.8.3        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| os                        | 1.0.0        |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.7        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| retriable                 | 3.1.2        |
| declarative-option        | 0.1.0        |
| declarative               | 0.0.10       |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| google-api-client         | 0.23.9       |
| digest-crc                | 0.4.1        |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| openssl                   | 2.1.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.1.0        |
| ipaddr                    | 1.2.0        |
| psych                     | 3.0.2        |
</details>

*generated on:* **2019-03-26**
</details>

**Comment by scorpion35** [comment] 2019-03-26 14:55
Please let me know if you need more information! :)

**Comment by scorpion35** [comment] 2019-03-26 15:57
Turns out, it sent them to 2nd gen iPad and there are double's now.

https://help.apple.com/app-store-connect/#/devd274dd925. 

```
12.9 inch (iPad Pro (3rd generation)) | 2048 x 2732 pixels (portrait)2732 x 2048 pixels (landscape) | Optional | Upload 12.9-inch iPad Pro (3rd generation) screenshots
---
12.9 inch (iPad Pro (2nd generation)) | 2048 x 2732 pixels (portrait)2732 x 2048 pixels (landscape) | Required if app runs on iPad | Upload 12.9-inch iPad Pro (2nd generation) screenshots
```

Think we have a bigger problem here 🤦‍♂️ 

Does anyone know how to make differentiate these two using Fastlane?

**Comment by hnakamura-fsv** [comment] 2019-03-26 20:36
duplicate of #14116 - theres a bit more information and discussion there

**Comment by janpio** [comment] 2019-03-26 22:24
I looked into this via #14116 and other issues before and always got lost along the way. It would be awesome if you could also dig deeper @scorpion35, maybe you can make sense of all of this 😍

**Comment by scorpion35** [comment] 2019-03-27 12:30
Sure, I will take a look :)

**Comment by philipp-heyse** [comment] 2019-04-11 09:49
If you needs an asap dirty workaround (as we did), we have a version which has a simple rule: if the screenshots path includes "3gen" we change the mapping:
https://github.com/soulan/fastlane 

note: we only use deliver, so i don't know if this will match any of your usecases

**Comment by brightsider** [comment] 2019-04-13 12:41
@philipp-heyse 
[15:39:07]: Uploading 24 screenshots for language de-DE
[15:39:07]: Uploading './fastlane/screenshots/de-DE/iPad Pro (12.9-inch) (2nd generation)-1-Albums.png'...
[15:39:11]: Uploading './fastlane/screenshots/de-DE/iPad Pro (12.9-inch) (2nd generation)-2-Album.png'...
[15:39:20]: Uploading './fastlane/screenshots/de-DE/iPad Pro (12.9-inch) (2nd generation)-3-Photo.png'...
[15:39:35]: Uploading './fastlane/screenshots/de-DE/iPad Pro (12.9-inch) (2nd generation)-4-Map.png'...
[15:39:44]: Uploading './fastlane/screenshots/de-DE/iPad Pro (12.9-inch) (2nd generation)-5-Date.png'...
[15:39:53]: Uploading './fastlane/screenshots/de-DE/iPad Pro (12.9-inch) (2nd generation)-6-Settings.png'...
[15:39:59]: Uploading './fastlane/screenshots/de-DE/iPad Pro (12.9-inch) (3rd generation)-1-Albums.png'...
[15:40:02]: Uploading './fastlane/screenshots/de-DE/iPad Pro (12.9-inch) (3rd generation)-2-Album.png'...
[15:40:05]: Uploading './fastlane/screenshots/de-DE/iPad Pro (12.9-inch) (3rd generation)-3-Photo.png'...
[15:40:10]: Uploading './fastlane/screenshots/de-DE/iPad Pro (12.9-inch) (3rd generation)-4-Map.png'...
[15:40:16]: Too many screenshots found for device 'iPad Pro' in 'de-DE', skipping this one (./fastlane/screenshots/de-DE/iPad Pro (12.9-inch) (3rd generation)-5-Date.png)
[15:40:16]: Too many screenshots found for device 'iPad Pro' in 'de-DE', skipping this one (./fastlane/screenshots/de-DE/iPad Pro (12.9-inch) (3rd generation)-6-Settings.png)

**Comment by philipp-heyse** [comment] 2019-04-13 13:14
Yes. If you check the comment it saif "3gen"
You have to change the Line to match "3rd" but our screenshots are generated elsewhere and needed different mapping.

**Comment by philipp-heyse** [comment] 2019-04-13 13:15
I only posted this to point out a possible quickfix herr

**Comment by janpio** [comment] 2019-04-13 13:51
@philipp-heyse Could you maybe create a PR with your quickfix? It most probably won't be used and merged, but it will give people a place to reply (like @brightsider did) and let us track it as _one_ possible workaround. Would be neat.

**Comment by brightsider** [comment] 2019-04-13 13:52
@janpio @philipp-heyse #14576 working

**Comment by salmanasiddiqui** [comment] 2019-04-16 23:28
The following file can be used to fix this issue, got this from @philipp-heyse fork

File: `fastlane/lib/deliver/app_screenshot.rb`
Content:
```
require 'deliver'

module Deliver
  # AppScreenshot represents one screenshots for one specific locale and
  # device type.
  class AppScreenshot
    module ScreenSize
      # iPad Pro 3gen
      IOS_IPAD_PRO_12_9 = "iOS-iPad-Pro-12.9"
    end

    # The iTC API requires a different notation for the device
    def device_type
      matching = {
          ScreenSize::IOS_35 => "iphone35",
          ScreenSize::IOS_40 => "iphone4",
          ScreenSize::IOS_47 => "iphone6", # also 7 and 8
          ScreenSize::IOS_55 => "iphone6Plus", # also 7 Plus & 8 Plus
          ScreenSize::IOS_58 => "iphone58",
          ScreenSize::IOS_65 => "iphone65",
          ScreenSize::IOS_IPAD => "ipad",
          ScreenSize::IOS_IPAD_10_5 => "ipad105",
          ScreenSize::IOS_IPAD_11 => "ipadPro11",
          ScreenSize::IOS_IPAD_PRO => "ipadPro",
          ScreenSize::IOS_IPAD_PRO_12_9 => "ipadPro129",
          ScreenSize::IOS_40_MESSAGES => "iphone4",
          ScreenSize::IOS_47_MESSAGES => "iphone6", # also 7 & 8
          ScreenSize::IOS_55_MESSAGES => "iphone6Plus", # also 7 Plus & 8 Plus
          ScreenSize::IOS_58_MESSAGES => "iphone58",
          ScreenSize::IOS_65_MESSAGES => "iphone65",
          ScreenSize::IOS_IPAD_MESSAGES => "ipad",
          ScreenSize::IOS_IPAD_PRO_MESSAGES => "ipadPro",
          ScreenSize::IOS_IPAD_10_5_MESSAGES => "ipad105",
          ScreenSize::IOS_IPAD_11_MESSAGES => "ipadPro11",
          ScreenSize::MAC => "desktop",
          ScreenSize::IOS_APPLE_WATCH => "watch",
          ScreenSize::IOS_APPLE_WATCH_SERIES4 => "watchSeries4",
          ScreenSize::APPLE_TV => "appleTV"
      }
      return matching[self.screen_size]
    end

    def formatted_name
      matching = {
          ScreenSize::IOS_35 => "iPhone 4",
          ScreenSize::IOS_40 => "iPhone 5",
          ScreenSize::IOS_47 => "iPhone 6", # and 7
          ScreenSize::IOS_55 => "iPhone 6 Plus", # and 7 Plus
          ScreenSize::IOS_58 => "iPhone XS",
          ScreenSize::IOS_61 => "iPhone XR",
          ScreenSize::IOS_65 => "iPhone XS Max",
          ScreenSize::IOS_IPAD => "iPad",
          ScreenSize::IOS_IPAD_10_5 => "iPad 10.5",
          ScreenSize::IOS_IPAD_11 => "iPad 11",
          ScreenSize::IOS_IPAD_PRO => "iPad Pro",
          ScreenSize::IOS_IPAD_PRO_12_9 => "iPad Pro 12.9",
          ScreenSize::IOS_40_MESSAGES => "iPhone 5 (iMessage)",
          ScreenSize::IOS_47_MESSAGES => "iPhone 6 (iMessage)", # also 7 & 8
          ScreenSize::IOS_55_MESSAGES => "iPhone 6 Plus (iMessage)", # also 7 Plus & 8 Plus
          ScreenSize::IOS_58_MESSAGES => "iPhone XS (iMessage)",
          ScreenSize::IOS_61_MESSAGES => "iPhone XR (iMessage)",
          ScreenSize::IOS_65_MESSAGES => "iPhone XS Max (iMessage)",
          ScreenSize::IOS_IPAD_MESSAGES => "iPad (iMessage)",
          ScreenSize::IOS_IPAD_PRO_MESSAGES => "iPad Pro (iMessage)",
          ScreenSize::IOS_IPAD_10_5_MESSAGES => "iPad 10.5 (iMessage)",
          ScreenSize::IOS_IPAD_11_MESSAGES => "iPad 11 (iMessage)",
          ScreenSize::MAC => "Mac",
          ScreenSize::IOS_APPLE_WATCH => "Watch",
          ScreenSize::IOS_APPLE_WATCH_SERIES4 => "Watch Series4",
          ScreenSize::APPLE_TV => "Apple TV"
      }
      return matching[self.screen_size]
    end


    def self.calculate_screen_size(path)
      size = FastImage.size(path)

      UI.user_error!("Could not find or parse file at path '#{path}'") if size.nil? || size.count == 0

      # Walk up two directories and test if we need to handle a platform that doesn't support landscape
      path_component = Pathname.new(path).each_filename.to_a[-3]
      if path_component.eql?("appleTV")
        skip_landscape = true
      end

      # iMessage screenshots have same resolution as app screenshots so we need to distinguish them
      devices = path_component.eql?("iMessage") ? self.device_messages : self.devices

      devices.each do |device_type, array|
        array.each do |resolution|
          if skip_landscape
            if size[0] == (resolution[0]) && size[1] == (resolution[1]) # portrait
              if device_type == ScreenSize::IOS_IPAD_PRO && path.include?("gen3")
                device_type = ScreenSize::IOS_IPAD_PRO_12_9
              end
              return device_type
            end
          else
            if (size[0] == (resolution[0]) && size[1] == (resolution[1])) || # portrait
                (size[1] == (resolution[0]) && size[0] == (resolution[1])) # landscape
              if device_type == ScreenSize::IOS_IPAD_PRO && path.include?("gen3")
                device_type = ScreenSize::IOS_IPAD_PRO_12_9
              end
              return device_type
            end
          end
        end
      end

      UI.user_error!("Unsupported screen size #{size} for path '#{path}'")
    end
  end

  ScreenSize = AppScreenshot::ScreenSize
end
```

and then just require this in your `Fastfile`. screenshots containing `gen3` will be uploaded as ipad gen3 screenshots.

This is a good quickfix, but I would suggest that instead of adding another mapping like this, fastlane should support a behavior where user can tell what `key` to use when uploading screenshots. Lets say if there is a directory in `screenshot/<locale>/ipadPro129` then fastlane should the name of this directory. Screenshot directly in `screenshot/<locale>/` should work as they do currently. This way whatever will be added later by apple, users' can workaround it

**Comment by janpio** [comment] 2019-05-20 11:04
This should be fixed now, see these instructions: https://docs.fastlane.tools/actions/deliver/#uploading-screenshots-for-ipad-pro-129-inch-3rd-generation

**Closed by janpio** 2019-05-20 11:04 UTC
Labels: status: waiting-for-reply, tool: deliver, topic: ipad pro 12.9 3rd gen, type: bug
