### ISSUE TITLE
upload_to_testflight submitting wrong build

### ISSUE THREAD

**Issue by ConfusedVorlon** [fastlane/fastlane#13300] opened 2018-09-05 18:40 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [ x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Fastlane is building the correct variant of my app - then submitting something completely different to testFlight

specifically - build is building the correct app. 

```
| PLATFORM_NAME      | ios                                                                              |
| LANE_NAME          | ios beta                                                                         |
| BUILD_NUMBER       | 59                                                                               |
| IPA_OUTPUT_PATH    | /Users/rob/tmp/FastlaneBuild/iPlayerRemote.ipa    
```
when I check the output path, this has the correct bundle id and build number in the info.plist

however the upload generates the following error
```

[19:20:46]: [Transporter Error Output]: ERROR ITMS-90055: "This bundle is invalid. The bundle identifier cannot be changed from the current value, 'com.HobbyistSoftware.iPlayerRemote'. If you want to change your bundle identifier, you will need to create a new application in App Store Connect."
[19:20:46]: [Transporter Error Output]: ERROR ITMS-90053: "This bundle is invalid. The bundle identifier is already in use by a different software package."
[19:20:46]: [Transporter Error Output]: ERROR ITMS-90188: "Invalid Pre-Release Build. The CFBundleVersion key in the app’s Info.plist file contains a build number (42) that’s lower than the latest build number (53) that’s been submitted for the app version '1.4'."
[19:20:46]: Transporter transfer failed.
[19:20:46]: 
[19:20:46]: ERROR ITMS-90055: "This bundle is invalid. The bundle identifier cannot be changed from the current value, 'com.HobbyistSoftware.iPlayerRemote'. If you want to change your bundle identifier, you will need to create a new application in App Store Connect."
ERROR ITMS-90053: "This bundle is invalid. The bundle identifier is already in use by a different software package."
ERROR ITMS-90188: "Invalid Pre-Release Build. The CFBundleVersion key in the app’s Info.plist file contains a build number (42) that’s lower than the latest build number (53) that’s been submitted for the app version '1.4'."
```

I don't know what build is actually getting uploaded, or where it is coming from. It clearly isn't the output from the build command. Unfortunately upload_to_testflight doesn't seem to log where it is getting the app it uploads.

here is my lane definition:

```
  desc "Upload a new Beta Build to Apple TestFlight"
  lane :beta do
  	increment_build_number
    build_app(workspace: "ChillRemote.xcworkspace", 
      scheme: ENV['DLV_SCHEME'],
      silent: true)
    upload_to_testflight(
      changelog: "New look for settings. Better browsing for YouTube, Amazon and Hulu",
      beta_app_description: "Remote control for Netflix, Amazon Prime and YouTube on Chrome",
      beta_app_feedback_email: "rob@hobbyistsoftware.com",
      distribute_external: true,
      notify_external_testers: true,
      skip_submission: false,
      groups: "ChillRemote",
      app_identifier: ENV['DLV_APP_ID']
      )
  end
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
Robs-Retina-iMac:ChillRemote rob$ fastlane beta --env iplayer
[✔] 🚀 
[18:56:25]: fastlane detected a Gemfile in the current directory
[18:56:25]: however it seems like you don't use `bundle exec`
[18:56:25]: to launch fastlane faster, please use
[18:56:25]: 
[18:56:25]: $ bundle exec fastlane beta --env iplayer
[18:56:25]: 
[18:56:25]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[18:56:25]: ------------------------------
[18:56:25]: --- Step: default_platform ---
[18:56:25]: ------------------------------
[18:56:25]: Loading from './fastlane/.env.iplayer'
[18:56:25]: Driving the lane 'ios beta' 🚀
[18:56:25]: ------------------------------------
[18:56:25]: --- Step: increment_build_number ---
[18:56:25]: ------------------------------------
Current version of project ChillRemote is: 
    57

/Users/rob/Documents/Development/Mac/iPhoneSwift/ChillRemote
[18:56:26]: $ cd /Users/rob/Documents/Development/Mac/iPhoneSwift/ChillRemote && agvtool next-version -all && cd -
[18:56:26]: ▸ Setting version of project ChillRemote to:
[18:56:26]: ▸ 58.
[18:56:26]: ▸ Also setting CFBundleVersion key (assuming it exists)
[18:56:26]: ▸ Updating CFBundleVersion in Info.plist(s)...
[18:56:26]: ▸ Updated CFBundleVersion in "ChillRemote.xcodeproj/../ChillRemote/Config/Info-beta.plist" to 58
[18:56:26]: ▸ Updated CFBundleVersion in "ChillRemote.xcodeproj/../ChillRemote/Config/Info-iPlayer.plist" to 58
[18:56:26]: ▸ Updated CFBundleVersion in "ChillRemote.xcodeproj/../ChillRemote/Config/Info-local.plist" to 58
[18:56:26]: ▸ Updated CFBundleVersion in "ChillRemote.xcodeproj/../ChillRemote/Config/Info.plist" to 58
[18:56:26]: ▸ Updated CFBundleVersion in "ChillRemote.xcodeproj/../ChillRemoteTests/Info.plist" to 58
[18:56:26]: ▸ Updated CFBundleVersion in "ChillRemote.xcodeproj/../ChillRemoteUITests/Info.plist" to 58
[18:56:26]: ▸ /Users/rob/Documents/Development/Mac/iPhoneSwift/ChillRemote
[18:56:27]: -----------------------
[18:56:27]: --- Step: build_app ---
[18:56:27]: -----------------------
[18:56:27]: Successfully loaded '/Users/rob/Documents/Development/Mac/iPhoneSwift/ChillRemote/fastlane/Gymfile' 📄

+---------------------+---------------------+
| Detected Values from './fastlane/Gymfile' |
+---------------------+---------------------+
| scheme              | iPlayerRemote       |
| output_directory    | ~/tmp/FastlaneBuild |
+---------------------+---------------------+

[18:56:27]: $ xcodebuild -showBuildSettings -workspace ChillRemote.xcworkspace -scheme iPlayerRemote
2018-09-05 18:56:27.925 xcodebuild[93029:9823249] [MT] PluginLoading: Required plug-in compatibility UUID 426A087B-D3AA-431A-AFDF-F135EC00DE1C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/OneSkyPlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs

+------------------------+--------------------------------------------------------+
|                             Summary for gym 2.103.1                             |
+------------------------+--------------------------------------------------------+
| workspace              | ChillRemote.xcworkspace                                |
| scheme                 | iPlayerRemote                                          |
| destination            | generic/platform=iOS                                   |
| output_name            | iPlayerRemote                                          |
| build_path             | /Users/rob/Library/Developer/Xcode/Archives/2018-09-05 |
| clean                  | false                                                  |
| output_directory       | ~/tmp/FastlaneBuild                                    |
| silent                 | false                                                  |
| skip_package_ipa       | false                                                  |
| result_bundle          | false                                                  |
| buildlog_path          | ~/Library/Logs/gym                                     |
| skip_profile_detection | false                                                  |
| xcode_path             | /Applications/Xcode.app                                |
+------------------------+--------------------------------------------------------+

//build output snipped

[19:19:18]: Successfully exported and compressed dSYM file
[19:19:18]: Successfully exported and signed the ipa file:
[19:19:18]: /Users/rob/tmp/FastlaneBuild/iPlayerRemote.ipa
[19:19:18]: ----------------------------------
[19:19:18]: --- Step: upload_to_testflight ---
[19:19:18]: ----------------------------------
[19:19:18]: Login to App Store Connect (hobbyist@hobbyistsoftware.com)
[19:19:20]: Login successful
[19:19:22]: Ready to upload new build to TestFlight (App: 1435087086)...
[19:19:24]: Going to upload updated app to App Store Connect
[19:19:24]: This might take a few minutes. Please don't interrupt the script.
[19:20:46]: [Transporter Error Output]: ERROR ITMS-90055: "This bundle is invalid. The bundle identifier cannot be changed from the current value, 'com.HobbyistSoftware.iPlayerRemote'. If you want to change your bundle identifier, you will need to create a new application in App Store Connect."
[19:20:46]: [Transporter Error Output]: ERROR ITMS-90053: "This bundle is invalid. The bundle identifier is already in use by a different software package."
[19:20:46]: [Transporter Error Output]: ERROR ITMS-90188: "Invalid Pre-Release Build. The CFBundleVersion key in the app’s Info.plist file contains a build number (42) that’s lower than the latest build number (53) that’s been submitted for the app version '1.4'."
[19:20:46]: Transporter transfer failed.
[19:20:46]: 
[19:20:46]: ERROR ITMS-90055: "This bundle is invalid. The bundle identifier cannot be changed from the current value, 'com.HobbyistSoftware.iPlayerRemote'. If you want to change your bundle identifier, you will need to create a new application in App Store Connect."
ERROR ITMS-90053: "This bundle is invalid. The bundle identifier is already in use by a different software package."
ERROR ITMS-90188: "Invalid Pre-Release Build. The CFBundleVersion key in the app’s Info.plist file contains a build number (42) that’s lower than the latest build number (53) that’s been submitted for the app version '1.4'."
+--------------------+----------------------------------------------------------------------------------+
|                                             Lane Context                                              |
+--------------------+----------------------------------------------------------------------------------+
| DEFAULT_PLATFORM   | ios                                                                              |
| ENVIRONMENT        | iplayer                                                                          |
| PLATFORM_NAME      | ios                                                                              |
| LANE_NAME          | ios beta                                                                         |
| BUILD_NUMBER       | 59                                                                               |
| IPA_OUTPUT_PATH    | /Users/rob/tmp/FastlaneBuild/iPlayerRemote.ipa                                   |
| DSYM_OUTPUT_PATH   | /Users/rob/tmp/FastlaneBuild/iPlayerRemote.app.dSYM.zip                          |
| XCODEBUILD_ARCHIVE | /Users/rob/Library/Developer/Xcode/Archives/2018-09-05/iPlayerRemote 2018-09-05  |
|                    | 19.16.30.xcarchive                                                               |
+--------------------+----------------------------------------------------------------------------------+

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | default_platform       | 0           |
| 2    | increment_build_number | 1           |
| 3    | build_app              | 171         |
| 💥   | upload_to_testflight   | 88          |
+------+------------------------+-------------+

[19:20:46]: fastlane finished with errors
</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.6                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.15.2 (Apple Git-101.1)        |
| Installation Source         | ~/.rvm/gems/ruby-2.4.0/bin/fastlane         |
| Host                        | Mac OS X 10.13.6 (17G65)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.0/lib                |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.4.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Increment build number"
  lane :increment do
    increment_build_number
  end

  desc "Update all fastlane tools"
  lane :update do
    update_fastlane
  end

  desc "Frame Screenshots"
  lane :frame do
    screenshots_path = "./fastlane/"+ENV['DLV_SCHEME']+"/screenshots"

    puts("frame path: #{screenshots_path}")
    frame_screenshots(path: screenshots_path)
  end

  desc "Upload a new Beta Build to Apple TestFlight"
  lane :beta do
  	increment_build_number
    build_app(workspace: "ChillRemote.xcworkspace", scheme: ENV['DLV_SCHEME'])
    upload_to_testflight(
      changelog: "New look for settings. Better browsing for YouTube, Amazon and Hulu",
      beta_app_description: "Remote control for Netflix, Amazon Prime and YouTube on Chrome",
      beta_app_feedback_email: "rob@hobbyistsoftware.com",
      distribute_external: true,
      notify_external_testers: true,
      skip_submission: false,
      groups: "ChillRemote",
      app_identifier: ENV['DLV_APP_ID']
      )
  end

  desc "Upload screenshots to the App Store"
  lane :screenshots do
   upload_to_app_store(
    force: true,
    skip_screenshots: false,
    skip_metadata: true,
    skip_binary_upload: true,
    submit_for_review: false,
    automatic_release: false,
    )
 end

 desc "Upload metadata to the App Store"
 lane :metadata do
   upload_to_app_store(
    force: true,
    skip_screenshots: true,
    skip_metadata: false,
    skip_binary_upload: true,
    submit_for_review: false,
    automatic_release: false,
    )
 end

 desc "Push a new release build to the App Store"
 lane :release do
  xcode_select("/Applications/Xcode.app")
  increment_build_number
  build_app(workspace: "ChillRemote.xcworkspace", scheme: ENV['DLV_SCHEME'])
  upload_to_app_store(
    force: true,
    skip_screenshots: true,
    skip_metadata: false,
    skip_binary_upload: false,
    submit_for_review: true,
    automatic_release: true,
    submission_information: {
      add_id_info_uses_idfa: true,
      add_id_info_serves_ads: true,
      export_compliance_uses_encryption: false,
      export_compliance_encryption_updated: false
    }
    )


end


end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier(ENV['DLV_APP_ID']) # The bundle identifier of your app
apple_id("hobbyist@hobbyistsoftware.com") # Your Apple email address

itc_team_id("18645") # iTunes Connect Team ID
team_id("JHV5RC82C3") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.103.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| terminal-table            | 1.8.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| commander-fastlane        | 4.4.6        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| faraday_middleware        | 0.12.2       |
| emoji_regex               | 0.1.1        |
| slack-notifier            | 2.3.2        |
| CFPropertyList            | 3.0.0        |
| unicode-display_width     | 1.4.0        |
| plist                     | 3.4.0        |
| addressable               | 2.5.2        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| highline                  | 1.7.10       |
| excon                     | 0.62.0       |
| faraday                   | 0.15.2       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| fastimage                 | 2.1.3        |
| json                      | 2.1.0        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.5.0        |
| bundler                   | 1.16.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| httpclient                | 2.8.3        |
| jwt                       | 2.1.0        |
| signet                    | 0.9.0        |
| os                        | 1.0.0        |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.6        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| retriable                 | 3.1.2        |
| declarative-option        | 0.1.0        |
| declarative               | 0.0.10       |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| google-api-client         | 0.23.5       |
| openssl                   | 2.0.2        |
| io-console                | 0.4.6        |
| mini_portile2             | 2.3.0        |
| nokogiri                  | 1.8.4        |
</details>

*generated on:* **2018-09-05**
</details>

**Comment by getaaron** [comment] 2018-09-05 22:03
Thanks for the report 👍🏼

This is a duplicate of https://github.com/fastlane/fastlane/issues/10945 which we are still investigating. If you are able to uncover the cause of the issue please add a comment there.

**Closed by getaaron** 2018-09-05 22:03 UTC

**Comment by ConfusedVorlon** [comment] 2018-09-05 23:07
@getaaron I don't know what code is shared here, it seems somewhat different to me.

in my report for #10945, deliver actually uploaded the correct build, then selected the wrong build
in this bug, upload_to_testflight is uploading the wrong build

certainly similar - but just wanted to double check that it is a dupe
