### ISSUE TITLE
Running xcrun extractLocStrings as part of Fastlane causes crash for duplicated high-codepoint unicode localisable strings

### ISSUE THREAD

**Issue by sdjmchattie** [fastlane/fastlane#15153] opened 2019-08-07 10:47 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
We run `xcrun extractLocStrings` as part of our fastlane workflow and we have a project where some of the localisable strings contain high-codepoint unicode characters such as "µm" where the `µ` is the high-codepoint character.  This string is localisable in multiple parts of the codebase and by default `xcrun extractLocStrings` outputs standard output warning you that you have used multiple comments for those strings.

When fastlane outputs to screen the first instance of one of the warnings where the localisable string contains a high-codepoint character, it crashes with the stacktrace shown further below.

I was able to supress the output of the warnings from `xcrun extractLocStrings` by using the flag `-q` but this is not the default and fastlane should be able to handle the output generated by any tool.

##### Command executed

`bin/fastlane test`

##### Complete output when running fastlane, including the stack trace and command used

```bash
/Users/my_user/buildAgent/work/1234567890abcdef/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.127.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:71:in `split': [!] invalid byte sequence in UTF-8 (ArgumentError)
	from /Users/my_user/buildAgent/work/1234567890abcdef/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.127.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:71:in `command_output'
	from /Users/my_user/buildAgent/work/1234567890abcdef/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.127.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Users/my_user/buildAgent/work/1234567890abcdef/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.127.0/fastlane/lib/fastlane/helper/sh_helper.rb:57:in `block (2 levels) in sh_control_output'
	from /Users/my_user/buildAgent/work/1234567890abcdef/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.127.0/fastlane/lib/fastlane/helper/sh_helper.rb:56:in `each'
	from /Users/my_user/buildAgent/work/1234567890abcdef/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.127.0/fastlane/lib/fastlane/helper/sh_helper.rb:56:in `block in sh_control_output'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open3.rb:205:in `popen_run'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open3.rb:190:in `popen2e'
	from /Users/my_user/buildAgent/work/1234567890abcdef/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.127.0/fastlane/lib/fastlane/helper/sh_helper.rb:54:in `sh_control_output'
	from /Users/my_user/buildAgent/work/1234567890abcdef/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.127.0/fastlane/lib/fastlane/helper/sh_helper.rb:16:in `sh_no_action'
	from /Users/my_user/buildAgent/work/1234567890abcdef/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.127.0/fastlane/lib/fastlane/fast_file.rb:213:in `block in sh'
	from /Users/my_user/buildAgent/work/1234567890abcdef/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.127.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/my_user/buildAgent/work/1234567890abcdef/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.127.0/fastlane/lib/fastlane/fast_file.rb:212:in `sh'
	from /Users/my_user/buildAgent/work/1234567890abcdef/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.127.0/fastlane/lib/fastlane/fast_file.rb:206:in `sh'
	from Fastfile:145:in `block (2 levels) in parsing_binding'
	from /Users/my_user/buildAgent/work/1234567890abcdef/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.127.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/my_user/buildAgent/work/1234567890abcdef/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.127.0/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
	from /Users/my_user/buildAgent/work/1234567890abcdef/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.127.0/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
	from /Users/my_user/buildAgent/work/1234567890abcdef/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.127.0/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
	from Fastfile:176:in `block (2 levels) in parsing_binding'
	from /Users/my_user/buildAgent/work/1234567890abcdef/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.127.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/my_user/buildAgent/work/1234567890abcdef/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.127.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/my_user/buildAgent/work/1234567890abcdef/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.127.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/my_user/buildAgent/work/1234567890abcdef/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.127.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/my_user/buildAgent/work/1234567890abcdef/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.127.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Users/my_user/buildAgent/work/1234567890abcdef/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.127.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/my_user/buildAgent/work/1234567890abcdef/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.127.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/my_user/buildAgent/work/1234567890abcdef/_vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/my_user/buildAgent/work/1234567890abcdef/_vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/my_user/buildAgent/work/1234567890abcdef/_vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/my_user/buildAgent/work/1234567890abcdef/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.127.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/my_user/buildAgent/work/1234567890abcdef/_vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/my_user/buildAgent/work/1234567890abcdef/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.127.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	from /Users/my_user/buildAgent/work/1234567890abcdef/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.127.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/my_user/buildAgent/work/1234567890abcdef/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.127.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	from /Users/my_user/buildAgent/work/1234567890abcdef/_vendor/bundle/ruby/2.3.0/gems/fastlane-2.127.0/bin/fastlane:23:in `<top (required)>'
	from /Users/my_user/buildAgent/work/1234567890abcdef/bin/fastlane:29:in `load'
	from /Users/my_user/buildAgent/work/1234567890abcdef/bin/fastlane:29:in `<main>'
```

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.6                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.20.1 (Apple Git-117)                             |
| Installation Source         | bin/fastlane                                                   |
| Host                        | Mac OS X 10.14.6 (18G87)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.5                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode1030.app/Contents/Developer/                |
| Xcode Version               | 10.3                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.128.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                    | Version | Update-Status |
| ------------------------- | ------- | ------------- |
| fastlane-plugin-appcenter | 1.2.1   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| bundler                   | 1.16.6       |
| io-console                | 0.4.5        |
| rake                      | 12.3.2       |
| CFPropertyList            | 3.0.0        |
| concurrent-ruby           | 1.1.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.11.1     |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| eventmachine              | 1.2.7        |
| websocket-extensions      | 0.1.4        |
| websocket-driver          | 0.7.1        |
| faye-websocket            | 0.10.9       |
| childprocess              | 1.0.1        |
| rubyzip                   | 1.2.3        |
| selenium-webdriver        | 3.142.3      |
| appium_lib_core           | 3.2.0        |
| mini_portile2             | 2.4.0        |
| nokogiri                  | 1.10.3       |
| tomlrb                    | 1.2.8        |
| appium_lib                | 10.3.1       |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| colorize                  | 0.8.1        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| diff-lcs                  | 1.3          |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.66.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.1        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.0        |
| google-cloud-core         | 1.3.0        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.2.0        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| fastlane-plugin-appcenter | 1.2.1        |
| handlebars-source         | 4.0.14       |
| libv8                     | 3.16.14.19   |
| ref                       | 2.0.0        |
| therubyracer              | 0.12.3       |
| handlebars                | 0.8.0        |
| netrc                     | 0.11.0       |
| rest-client               | 2.0.2        |
| rspec-support             | 3.8.2        |
| rspec-core                | 3.8.2        |
| rspec-expectations        | 3.8.4        |
| rspec-mocks               | 3.8.1        |
| rspec                     | 3.8.0        |
| rubyXL                    | 3.4.5        |
| ruby_rncryptor            | 3.0.2        |
</details>

*generated on:* **2019-08-07**
</details></pre>
</details>

**Comment by janpio** [comment] 2019-08-07 21:06
What does your `test` lane look like?

**Comment by sdjm-tessella** [comment] 2019-08-08 09:04
Sorry yes, the `test` lane is below:

```ruby
  lane :test do
    extract_strings
    ensure_git_status_clean
    scan(
      scheme: build_scheme_name,
      slack_channel: slack_channel,
      slack_message: "Branch #{git_branch}",
      slack_only_on_failure: true
    )
  end
```

where `extract_strings` is:

```ruby
  lane :extract_strings do
    sh "cd .. && ./scripts/extract-strings.sh #{project_name}"
    sh "cd .. && ./scripts/strings_tool.rb --patch --project #{project_name}"
  end
```

And the script crashing fastlane is the `extract-strings.sh` one which contains the command (truncated to remove unrelated things):

```sh
extracted_strings=$1/ExtractedStrings/

echo "> Extracting strings from code"
find "$1" \( -name "*.m" -o -name "*.mm" -o -name "*.swift" \) -print0 | xargs -0 xcrun extractLocStrings -o "$extracted_strings"
```

**Comment by janpio** [comment] 2019-08-08 10:32
Ok, so this is a problem with the output the command is giving to `sh`. Can you share what it returns as a file so we can reproduce with `sh('cat file.txt')` or similar?

**Comment by sdjm-tessella** [comment] 2019-08-08 11:55
This file reproduces the error by including `sh('cat text.txt')` in the Fastfile.

[text.txt](https://github.com/fastlane/fastlane/files/3481571/text.txt)

**Comment by sdjm-tessella** [comment] 2019-09-09 07:58
I can confirm the bug still exists in Fastlane version 2.130.0

**Comment by sdjm-tessella** [comment] 2019-10-18 08:56
I can confirm the bug still exists in Fastlane version 2.134.0

**Comment by sdjm-tessella** [comment] 2019-11-27 09:53
I can confirm the bug still exists in Fastlane version 2.137.0

**Comment by sdjm-tessella** [comment] 2020-01-08 09:52
I can confirm the bug still exists in Fastlane version 2.139.0

**Comment by sdjm-tessella** [comment] 2020-02-18 10:36
I can confirm the bug still exists in Fastlane version 2.141.0

**Comment by sdjm-tessella** [comment] 2020-04-01 15:03
I can confirm the bug still exists in Fastlane version 2.144.0

**Comment by sdjm-tessella** [comment] 2020-05-11 08:23
I can confirm the bug still exists in Fastlane version 2.146.1

**Comment by sdjm-tessella** [comment] 2020-06-19 10:05
I can confirm the bug still exists in Fastlane version 2.149.1

**Comment by StephanKornerTrihow** [comment] 2020-07-20 13:18
It seems that Fastlane version 2.152.0 still has the same bug.

I keep getting the following 3 messages when trying to run any `bundle exec fastlane`command...

Running xcrun extractLocStrings as part of Fastlane causes crash for duplicated high-codepoint unicode localisable strings
    https://github.com/fastlane/fastlane/issues/15153 [open] 20 💬
    3 weeks ago

➡️  failed on flutter project
    https://github.com/fastlane/fastlane/issues/16085 [closed] 2 💬
    6 weeks ago

➡️  Upload to Crashlytics doesn't work cause of invalid byte sequence
    https://github.com/fastlane/fastlane/issues/14176 [closed] 11 💬
    10 Sep 2019

**Comment by sdjm-tessella** [comment] 2020-08-20 15:23
I can confirm the bug still exists in Fastlane version 2.156.1

**Comment by sdjm-tessella** [comment] 2020-09-30 10:47
I can confirm the bug still exists in Fastlane version 2.161.0

**Comment by sdjm-tessella** [comment] 2020-11-09 10:18
I can confirm the bug still exists in Fastlane version 2.166.0

**Comment by rogerluan** [comment] 2020-11-10 08:37
@sdjm-tessella I'm able to run this:

>find . \( -name "*.m" -o -name "*.mm" -o -name "*.swift" \) -print0 | xargs -0 xcrun extractLocStrings -o test

With `NSLocalizedString(" µm", comment: "")` in my codebase without being throw any warning (via CLI) 🤔 How's your setup to throw the warning again? 🙏 

I'll test using your test.txt now 👍

**Comment by sdjm-tessella** [comment] 2020-11-10 10:38
Hi.  Thanks for your feedback.  I was advised August 2019 (see at the top of this issue) to set up a Fastfile which just calls on the shell to output the contents of the attached `test.txt` file with `cat` so my Fastfile contains the following when I'm testing.  I just run `./bin/fastlane` and choose the `ios` lane and it hits the issue:

```
# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.2.2"

default_platform :ios

platform :ios do

  desc "Extract the strings for a particular project"
  lane :extract_strings do
    sh('cat ../text.txt')
  end

end
```

**Comment by rogerluan** [comment] 2020-11-10 10:48
After lots of debugging, I don't know what else to try, this seems to be an issue with Ruby (?) - or maybe just `split` function of ruby.

You can reproduce this issue in `irb` like this:

```ruby
# Just to prove my env vars are correctly set
irb(main):027:0> puts "#{ENV["LANG"]}, #{ENV["LANGUAGE"]}, #{ENV["LC_ALL"]}"
en_US.UTF-8, en_US.UTF-8, en_US.UTF-8
=> nil 
irb(main):029:0> File.open("text.txt", "r:UTF-8", &:read)
=> "> Extracting strings from code\nextractLocStrings: warning: Key \" secs\" used with multiple comments \"No problem\" & \"Fastlane won't crash\"\nextractLocStrings: warning: Key \" \xB5m\" used with multiple comments \"Uh oh\" & \"This causes a crash\" & \"Invalid byte sequence\"\n"
irb(main):030:0> File.open("text.txt", "r:UTF-8", &:read).split()
# <crash happens here>
irb(main):028:0> "\xB5".split()
# <crash happens here as well>
```

I also tried \x00B5 as pointed out here https://unicode-table.com/en/00B5/:

```ruby
irb(main):031:0> "\x00B5".split()
=> ["\u0000B5"]
```
But it shouldn't print that, it should print the unicode character (micro sign). Like this (https://unicode-table.com/en/0067/):

```
irb(main):033:0> "\x67"
=> "g"
```


This will probably need someone more experienced with encoding to take a look at. From what I can tell, this is unrelated to _fastlane_, though, as you can observe. @sdjm-tessella do you still want to keep this issue open?

**Comment by sdjm-tessella** [comment] 2020-11-10 14:40
I've been meaning to look at this myself for a very long time but haven't yet gotten around to it.  I have my suspicions though that this might be to do with unicode normalisation.  As you've already noticed, there are different ways to represent the micro sign in unicode.  I suspect the one in my `text.txt` file is one kind of them and `split` doesn't like it.  It may be possible to use unicode normalisation before using split to make sure split only receives unicode that it can split.  https://www.honeybadger.io/blog/ruby-unicode-normalization/ looks like a good summary of unicode normalisation in Ruby.

**Comment by rogerluan** [comment] 2020-11-10 15:40
Very interesting @sdjm-tessella I hadn't heard about unicode normalization that until now. Let me know if you findings, if you have the chance the take a look at this before I do!

Also, if anyone's curious to investigate this as well: now that we isolated this issue away from fastlane, we can probably iterate over the problem over irb and bring the solution back into _fastlane_ when we come up with one, that should significantly increase debugging speed 🙌

**Comment by sdjmchattie** [comment] 2020-12-18 20:28
I can confirm the bug still exists in Fastlane version 2.170.0

**Comment by rogerluan** [comment] 2020-12-19 21:57
<sub>_2 debugging hours later………_ 😄 </sub>

Got some good news! 🎉 (_I think_)

I investigated this a bit further:
- I tried to reproduce this bug by just reading a micro character and I couldn't create a Localizable.strings file with the glitched character anymore 🤔 Then I realized that `NSLocalizedString("µ", comment: "")` reproduces a perfectly fine output, whereas if you add a letter `m` in front of it, it glitches, such as: `NSLocalizedString("µm", comment: "")`. Hm, interesting.
- This made me believe that the bug could be in `xcrun extractLocStrings` (aka `genstrings`).
- By running `genstrings` with no parameters, it will print its help utility. I realized there's a `-u` option for unicode output 🎉 Unfortunately, using it didn't reproduce much of a different result 😅 
- So then I went to its [man](https://www.manpagez.com/man/1/genstrings/)), and realized that -u seems to be enabled by default nowadays.
- BUT, in the man I also learned that genstrings output is encoded in UTF-16 and not UTF-8 🤯 That solved it!!

So now I can successfully use genstrings to create an output, read that output using `File.open("Localizable.strings", "r:UTF-16", &:read)` in irb, and then that one prints the micro character correctly. Calling `split()` on this output also works just fine 👌 

Notice that if you open the generated `Localizable.strings`, copy and paste its content into a new file and save (e.g. as `.txt`), the encoding will be lost and the file seems to be just broken then. It displays fine, but then I believe the file's nominal encoding (utf-8) will be different than the actual encoding (utf-16) 🤔 

Now the challenge is to think how we can solve this issue in fastlane core, so that it doesn't crash. The obvious solution is to tell users to don't pass anything other than utf-8-encoded files/strings... I don't know if that's a good approach - would that work for you, @sdjmchattie ? The problem with "just convert whatever is passed to utf-8" is that I don't think that's possible, without knowing what the input is encoded in.

Do you have any thoughts on possible solutions @sdjmchattie ?

**Comment by sdjmchattie** [comment] 2021-01-03 23:02
Hi @rogerluan thanks for spending so much time on this issue.  I took some time today to fiddle around with this myself and I can see where the error occurs and I can see that it is indeed an issue with encodings.  Specifically, like you said `genstrings` is outputting UTF-16 and then Ruby tries to split it using UTF-8 which causes code points to be encountered that aren't valid in UTF-8.  I thought I had a fix, but have now realised it was a spurious fix.  I'm not 100% sure, but I think each line of output from PTY could be in any encoding and its hard to work out which encoding a line has from just the bytes of the string.  I don't think there is a good fix for this in fastlane after all.

I think your suggestion to update the documentation would be good.  And probably some way of getting the thrown error to tell the user that this might be the issue so they will actually notice and read the documentation about it.  My only concern with doing this is that we aren't reading the output of `genstrings` from a file before sending it to fastlane.  It is what `genstrings` has generated as standard output, but I guess/hope you can redirect the standard output with a `|` to be converted to UTF-8 before sending to fastlane which circumvents the issue.

**Comment by sdjmchattie** [comment] 2021-01-03 23:33
It would be good to get your feedback on my attempt at fixing this issue though @rogerluan .  If you think it's good, then I would be delighted to put in a pull request for it.

https://github.com/fastlane/fastlane/compare/master...sdjmchattie:shell-stdout-fix-15153

**Comment by rogerluan** [comment] 2021-01-04 04:15
Interesting findings @sdjmchattie ! 

After reviewing your proposed changes:

- Your solution looks good, and viable to me! 
- I'd probably rename `make_utf_8` to something along the lines of `encode_as_utf_8_if_possible` 
- Were you able to test all 3 scenarios locally? E.g. using your broken txt file uploaded in this thread, using a direct output from genstrings, and using a perfectly fine utf8 string? 
- Mind adding some unit tests around this, using mocked files that represent broken behaviors (such as exactly the ones we discussed in this thread)? 😊 

Feel free to open the PR (even if a draft one) so we can discuss further changes if needed (or just approve it) and run CI 🙌 

Thanks for investigating a proper fix for this issue! 🙏

**Comment by sdjmchattie** [comment] 2021-01-10 20:52
Thanks for the feedback @rogerluan I will make the branch tidier and add some tests in the coming couple of weeks and submit a pull request.  It would be good to see a partial fix -- obviously it relies on the encodings of inputs being in the list in the code, but at least the encoding of the strings is being considered.  I did do some manual testing of this, but not as a complete run through.  The original reason for submitting this bug isn't relevant to my current work any more, but I still want to get it fixed.

**Comment by rogerluan** [comment] 2021-01-11 03:03
Sounds great!
Yeah, we ended up taking too long to get to it 🙈 but they at least we figured it out together 💪

Looking forward to reviewing that PR! 🤗

**Comment by sdjmchattie** [comment] 2021-02-10 19:14
This is being fixed in a pull request I have open.

**Closed** 2021-04-07 11:49 UTC
Labels: status: has-pr, tool: action, type: bug
