### ISSUE TITLE
Title and Keyword Errors with Frame-it and Far East Fonts

### ISSUE THREAD

**Issue by gtfannn** [fastlane/fastlane#5155] opened 2016-06-17 17:41 UTC
### New Issue Checklist

- [ x] Updated fastlane to the latest version
- [ x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
When I run Frame-it, it works correctly for most languages but is putting ?? ????? in the Title and Keywords of Far East Languages.  I tried to specify fonts for these languages in the Framefile.json but I am unsure whether I have the right fonts.

Any ideas on how to fix this?

![iphone5-0launch_framed](https://cloud.githubusercontent.com/assets/19999358/16159374/6a16443e-3490-11e6-9403-0cf96aef15a7.png)
![iphone5-0launch_framed](https://cloud.githubusercontent.com/assets/19999358/16159396/88fef44a-3490-11e6-982f-b91d09ad168f.png)

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:

```ruby
fastlane_version "1.95.0"

default_platform :ios

platform :ios do

  before_all do
# ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."


  end

  desc "Creates new screenshots and frameit"
  lane :screens do
    snapshot
    frameit(white: true, path: './fastlane/screenshots')
  end

  desc "uploads screens to itunes connect"
  lane :upload_screens do
    deliver(app: 839654331, app_identifier: "com.thomasgulli.iMergency", skip_metadata: true, force: true)
  end

  desc "just runs frameit on all images"
  lane :test_frameit do
    frameit(white: true, path: './fastlane/screenshots')
  end

  desc "will build all apps for appstore push you use xcode organizer to push to app store under widows menu"
  lane :build_appstore do
    build_app
    build_widget
    build_watchapp
  end

  desc "builds main app for appstore"
  lane :build_app do
    gym(project: "EmergencyPhoneNumbers.xcodeproj", scheme: "EmergencyPhoneNumbers", use_legacy_build_api:true)
  end

  desc "builds widget *may not needed"
  lane :build_widget do
    gym(project: "EmergencyPhoneNumbers.xcodeproj", scheme: "EmergencyTodayWidget", use_legacy_build_api:true)
  end

  desc "builds watchapp"
  lane :build_watchapp do
    gym(project: "EmergencyPhoneNumbers.xcodeproj", scheme: "EmergencyPhoneNumbers WatchKit App", use_legacy_build_api:true)
  end

  desc "gets all certs for a build pw is tripwhistle2016"
  lane :get_certs do
    match(type: "appstore")
    match(type: "adhoc")
    match(type:"development")
  end

end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```

### Framefile

```json
{
  "default": {
    "keyword": {
      "fonts": [
        {
          "font": "./fonts/NimbusSanL-Reg.otf",
          "supported": ["da","de-DE","el","en-AU","en-CA","en-GB", "en-US", "es-ES","es-MX","fi","fr-CA", "fr-FR","id", "it","ms", "nl","no","pt-BR","pt-PT","sv","tr","vi"]
        },
        {
          "font": "./fonts/chinese.ttf",
          "supported": ["zh-Hans","zh-Hant"]
        },
        {
          "font": "./fonts/japanese.otf",
          "supported": ["ja"]
        },
        {
          "font": "./fonts/korean.ttf",
          "supported": ["ko"]
        },
        {
          "font": "./fonts/russian.ttf",
          "supported": ["ru"]
        },
        {
          "font": "./fonts/thai.ttf",
          "supported": ["th"]
        }
      ]
    },
    "title": {
      "fonts": [
        {
          "font": "./fonts/NimbusSanL-Reg.otf",
          "supported": ["da","de-DE","el","en-AU","en-CA","en-GB", "en-US", "es-ES","es-MX","fi","fr-CA", "fr-FR","id", "it","ms", "nl","no","pt-BR","pt-PT","sv","tr","vi"]
        },
        {
          "font": "./fonts/chinese.ttf",
          "supported": ["zh-Hans","zh-Hant"]
        },
        {
          "font": "./fonts/japanese.otf",
          "supported": ["ja-JP"]
        },
        {
          "font": "./fonts/korean.ttf",
          "supported": ["ko-KR"]
        },
        {
          "font": "./fonts/russian.ttf",
          "supported": ["ru-RU"]
        },
        {
          "font": "./fonts/thai.ttf",
          "supported": ["th"]
        }
      ],
      "color": "#545454"
    },
    "background": "./background.jpg",
    "padding": 50
  },


  "data": [
    {
      "filter": "0Launch",
      "keyword": {
        "color": "#d21559"
      }
    },
    {
      "filter": "1CallPolice",
      "keyword": {
        "color": "#feb909"
      }
    },
    {
      "filter": "2ChooseCountry",
      "keyword": {
        "color": "#aa4dbc"
      }
    },
    {
      "filter": "3MapView",
      "keyword": {
        "color": "#31bb48"
      }
    }
  ]
}
```

**Comment by vpolouchkine** [comment] 2016-06-20 21:12
Take a look at this Framefile for Chinese, Japanese, and Korean setup: https://github.com/fastlane/examples/blob/master/MindNode/screenshots/Framefile.json

**Comment by gtfannn** [comment] 2016-06-21 13:29
Yes, I set it up like that - The issue appears to be that I keep selecting fonts that don't recognize some of the characters.  For example, I found a new font for Japanese and now the ?? ????? are replaced by actual characters in 3 out of 4 screenshots.  I used Mac's font book to find the fonts I put in place.  Do you have the actual font files for the example?

**Comment by vpolouchkine** [comment] 2016-06-23 19:57
Can you confirm that the strings that appear as ?? render properly in a text editor using that font?

**Comment by mithiljadhav** [comment] 2016-06-23 20:10
@gtfannn You can try downloading fonts for Japanese, Korean, Chinese Simplified/Traditional from here: https://www.google.com/get/noto/

I was also facing this issue. Using these fonts and correctly referencing them from Framefile.json fixed it for me.

**Comment by Damnum** [comment] 2016-08-10 15:39
@gtfannn have you solved the issue? I'm having the same problem and I also used the noto fonts suggested by @mithiljadhav, the fonts are still messed up for Japanese, Korean and Chinese. It only works for Thai.

**Comment by Damnum** [comment] 2016-08-10 15:51
Never mind, my bad. I had the fonts mixed up, it works now.

**Comment by vpolouchkine** [comment] 2016-08-12 18:34
I'm going to go ahead and close this. Please re-open if the issue is still relevant.

**Closed by vpolouchkine** 2016-08-12 18:34 UTC
Labels: frameit
