### ISSUE TITLE
Snapshot html is blank even after the test successfully passed  

### ISSUE THREAD

**Issue by Prabat** [fastlane/fastlane#6376] opened 2016-10-04 10:34 UTC
fastlane 1.104.0
snapshot 1.16.1
xcode 8.0

Snapshot Configuration file:
--------------------------------------------------------------------------------------------------
```
# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
 devices([
   "iPhone 7",
   "iPhone 7 Plus"
#   "iPhone 5",
#   "iPhone 4s",
#   "iPad Retina",
#   "iPad Pro"
 ])

languages([
  "en-US",
  "de-DE"
#  "it-IT",
#  ["pt", "pt_BR"] # Portuguese with Brazilian locale
])

# Arguments to pass to the app on launch. See https://github.com/fastlane/snapshot#launch-arguments
# launch_arguments(["-favColor red"])

# The name of the scheme which contains the UI Tests
# scheme "SchemeName"

# Where should the resulting screenshots be stored?
# output_directory "./screenshots"

# clear_previous_screenshots true # remove the '#' to clear all previously generated screenshots before creating new ones

# Choose which project/workspace to use
# project "./Project.xcodeproj"
# workspace "./Project.xcworkspace"

# For more information about all available options run
# snapshot --help
```
---------------------------------------------------------------------------------------------------

After execution, tests are passed & screenshots are loaded into the output folder
Even html file also generated but when it opened it is blank.

Output html file:
```
<!DOCTYPE html>
<html>
  <head>
    <title>fastlane/snapshot</title>
    <meta charset="UTF-8">
    <style type="text/css">
      * {
        font-family: "HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
        font-weight: 300;
      }
      .language {

      }
      .deviceName {
        display: block;
        font-size: 30px;
        padding-bottom: 24px;
        padding-top: 45px;
      }
      .screenshot {
        cursor: pointer;
        border: 1px #EEE solid;
        z-index: 0;
      }
      th {
        text-align: left;
      }
      td {
        text-align: center;
        min-width: 200px;
      }
      #overlay {
        position:fixed;
        top:0;
        left:0;
        background:rgba(0,0,0,0.8);
        z-index:5;
        width:100%;
        height:100%;
        display:none;
        cursor: zoom-out;
        text-align: center;
      }
      #imageDisplay {
        height: auto;
        width: auto;
        z-index: 10;
        cursor: pointer;
      }
      #imageInfo {
        background: none repeat scroll 0 0 rgba(0, 0, 0, 0.2);
        border-radius: 5px;
        color: white;
        margin: 20px;
        padding: 10px;
        position: absolute;
        right: 0;
        top: 0;
        width: 250px;
        z-index: -1;
      }
      #imageInfo:hover {
        z-index: 20;
      }
    </style>
  </head>
  <body>
    
    
    


    
      <div id="overlay">
        <img id="imageDisplay" src="" alt="" />
        <div id="imageInfo"></div>
      </div>
      <script type="text/javascript">
        var overlay        = document.getElementById('overlay');
        var imageDisplay   = document.getElementById('imageDisplay');
        var imageInfo      = document.getElementById('imageInfo');
        var screenshotLink = document.getElementsByClassName('screenshotLink');

        function doClick(el) {
          if (document.createEvent) {
            var evObj = document.createEvent('MouseEvents', true);
            evObj.initMouseEvent("click", false, true, window, 0, 0, 0, 0, 0, false, false, false, false, 0, null);
            el.dispatchEvent(evObj);
          } else if (document.createEventObject) { //IE
            var evObj = document.createEventObject();
            el.fireEvent('onclick', evObj);
          }
        }

        for (index = 0; index < screenshotLink.length; ++index) {
          screenshotLink[index].addEventListener('click', function(e) {
            e.preventDefault();
            
            var img = e.target;
            if (e.target.tagName == 'A') {
              img = e.target.children[0];
            }
            
            // beautify
            var tmpImg = new Image();
            tmpImg.src = img.src;
            imageDisplay.style.height     = 'auto';
            imageDisplay.style.width     = 'auto';
            if (window.innerHeight < tmpImg.height) {
              imageDisplay.style.height = document.documentElement.clientHeight+'px';
            } else if (window.innerWidth < tmpImg.width) {
              imageDisplay.style.width = document.documentElement.clientWidth;+'px';
            } else {
              imageDisplay.style.paddingTop = parseInt((window.innerHeight - tmpImg.height) / 2)+'px';
            }

            imageDisplay.src             = img.src;
            imageDisplay.alt             = img.alt;
            imageDisplay.dataset.counter = img.dataset.counter;
            
            imageInfo.innerHTML          = '<h3>'+img.alt+'</h3>';
            imageInfo.innerHTML         += decodeURI(img.src.split("/").pop());
            imageInfo.innerHTML         += '<br />'+tmpImg.height+'&times;'+tmpImg.width+'px';
                    
            overlay.style.display        = "block";
          });
        }
        
        imageDisplay.addEventListener('click', function(e) {
          e.stopPropagation(); // !
          
          overlay.style.display = "none";
          
          img_counter = parseInt(e.target.dataset.counter) + 1;
          try {
            link = document.body.querySelector('img[data-counter="'+img_counter+'"]').parentNode;
          } catch (e) {
            try {
              link = document.body.querySelector('img[data-counter="0"]').parentNode;
            } catch (e) {
              return false;
            }
          }
          doClick(link);
        });

        overlay.addEventListener('click', function(e) {
          overlay.style.display = "none";
        })
        
      function keyPressed(e) {
        e = e || window.event;
        var charCode = e.keyCode || e.which;
        switch(charCode) {
          case 27: // Esc
            overlay.style.display = "none";
            break;
          case 34: // right-arrow, Page Down, keypad right, ...
          case 39:
          case 54:
          case 102:
            e.preventDefault();
            doClick(imageDisplay);
            break;
          case 33: // left-arrow, Page Up, keypad right, ...
          case 37:
          case 52:
          case 100:
            e.preventDefault();
            document.getElementById('imageDisplay').dataset.counter -= 2; // hacky
            doClick(imageDisplay);
            break;
         }
      };
      document.body.addEventListener('keydown', keyPressed);
      </script>
  </body>
</html>
```

**Comment by itleo31** [comment] 2016-10-10 08:00
Any help on this?

**Comment by Prabat** [comment] 2016-10-10 08:34
Yeah sure, I have executed so many times but html page is blank (Not displaying any screenshots on it).

**Comment by TKBurner** [comment] 2016-10-11 16:11
@Prabat @itleo31 Were you able to get this working previously for this project? I want to see if this is a config issue or an issue caused by a potential update on our end. Thanks!

**Comment by Prabat** [comment] 2016-10-12 09:44
@TKBurner Verified one more time & analyzed the issue.
Snapshot is taking the screenshots for all versions of simulator but html report page is not updated with screenshots particularly for  **iPhone 7**, **iPhone 7 Plus** & **iPhone SE**.

Please look at the issue.

**Comment by TKBurner** [comment] 2016-10-12 18:56
@Prabat Thanks for following up. Can you provide a sample project that is affected by this? First run `fastlane run update_fastlane`. I want to try and reproduce this over here. Thanks!

**Comment by itleo31** [comment] 2016-10-13 10:11
@Prabat is right. I can make it works on iPhone 6, but not for 7, 7+, SE. My snapshot version is 1.16.2

**Comment by TKBurner** [comment] 2016-10-13 15:49
@itleo31 Thanks for following up. I sent this out to the core team so we can all take a look. We'll update on this thread. Hope you have a great weekend coming up 👍

**Comment by dkk** [comment] 2016-10-20 16:31
Same here, doesn't work with iPhone 7 (using Snapshot 1.16.2)

**Comment by TKBurner** [comment] 2016-10-25 16:08
@dkk Thanks for following up. We are still looking into this. 👍

**Comment by mpirri** [comment] 2016-10-25 18:44
An update: we've been able to produce this on our end, and are looking into the issue further. Thanks again for all the info on this!

**Comment by mpirri** [comment] 2016-10-27 20:16
This issue should be fixed in the latest release of _snapshot_, version 1.16.3.  If you are still not able to generate iPhone 7/7+ screenshots with that version, let us know. I'm going to close the issue for now, however.

**Closed by mpirri** 2016-10-27 20:16 UTC
Labels: bug, snapshot, you can do this
