### ISSUE TITLE
[Feature request] Ability to expand path in ensure_no_debug_code

### ISSUE THREAD

**Issue by NachoSoto** [fastlane/fastlane#940] opened 2015-12-02 01:32 UTC
I was trying to do this:
```ruby
ensure_no_debug_code(
            text: "fcontext(",
            extension: ".swift",
            path: path
)
```
where `path` is
```
"{Framework1Tests,Framework2Tests,Framework3Tests}"
```
so that it can match the different folders containing the tests for all my frameworks. Unfortunately this fails right now:
```
Couldn't find the folder at '.../project/{Framework1Tests,Framework2Tests,Framework3Tests}'
```

I think because it's currently [checking if the path exists](https://github.com/fastlane/fastlane/blob/master/lib/fastlane/actions/ensure_no_debug_code.rb#L57) without expanding it first.

Am I missing an alternate way of doing this? Alternatively `path` could also take an array of paths.

**Comment by KrauseFx** [comment] 2015-12-02 17:04
Does it work if you do 
```ruby
["Framework1Tests", "Framework2Tests"].each do |path|
  ensure_no_debug_code(
            text: "fcontext(",
            extension: ".swift",
            path: path
  )
end
```

Just curios if the problem is the check because you pass multiple values using  `{}`

**Comment by NachoSoto** [comment] 2015-12-02 17:09
Oh, I guess I should learn how to :gem: first :sweat_smile: 

> Just curios if the problem is the check because you pass multiple values using {}

Yeah, but what you suggest is totally the way to do it! Thanks :D

**Comment by KrauseFx** [comment] 2015-12-03 04:02
@NachoSoto can you check: would this work without the additional `raise` in the verify block? I assume the `Dir["..."]` supports your notation, right?

**Comment by ohwutup** [comment] 2016-03-11 19:24
Hey @NachoSoto and @KrauseFx! I am going to close this issue for lack of conversation, but obviously, please continue conversation, and we can reopen if you guys are still interested in discussing. #springcleaning. :sparkle:

**Closed by ohwutup** 2016-03-11 19:24 UTC
