### ISSUE TITLE
Something went wrong when creating the new app - it's not listed in the apps list (Produce)

### ISSUE THREAD

**Issue by dholdaway** [fastlane/fastlane#4797] opened 2016-05-23 20:03 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

```
[20:25:43]: ---------------------
[20:25:43]: --- Step: produce ---
[20:25:43]: ---------------------
+----------------+----------------------------------+
|             Summary for produce 1.1.2             |
+----------------+----------------------------------+
| username       | xxx |
| app_name       | xxx              |
| app_identifier | xxx                |
| skip_itc       | true                             |
| sku            | 1464031544                       |
| language       | English                          |
| skip_devcenter | false                            |
| team_id        | VFX8SCY653                       |
+----------------+----------------------------------+
[20:25:47]: Creating new app 'xxx
' on the Apple Dev Center
[20:25:48]: Created app 6EA3DYPZTK

Something went wrong when creating the new app - it's not listed in the apps list

[20:25:48]: fastlane finished with errors
/Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/fastlane_core-0.44.0/lib/fastlane_core/ui/interface.rb:127:in `crash!': [!] Something went wrong when creating the new app - it's not listed in the apps list (FastlaneCore::Interface::FastlaneCrash)

```
When i login to the apple dev centre i can see the app 

Name:xxx
Prefix:VFX8SCY653
ID:xxx

and the id and name match

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
produce(
username: USERNAME,
app_name: ENV["IPANAME"],
app_identifier: ENV["APP_IDENTIFIER"],
skip_itc: true
)
cert(development:true)
sigh(force: true,app_identifier: ENV["APP_IDENTIFIER"])
ipa({
configuration: Release,
scheme:xxx,
identity:"iPhone Distribution: xxx(xxx)"
})
```

### Environment

fastlane version (run `fastlane -v`):

1.89.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
nope
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
rvm

**Comment by vpolouchkine** [comment] 2016-05-24 15:25
Does this happen when you add any app?

**Comment by vpolouchkine** [comment] 2016-06-16 18:18
It looks like there hasn’t been any recent activity on this issue in some time, so I’m closing it. If this is still a problem, feel free to re-open a new issue and I’d be happy to help :+1:

**Comment by lakamsani** [comment] 2016-08-06 07:55
Hi @vpolouchkine  some more info where I ran into this. I used this command to create a new app in just Dev Center. 

produce create -a $APP_ID -u $USER -i -q "$APP_NAME"

That worked.  After a few days  I tried creating it in just ITC using this command. 
produce create -a $APP_ID  -u $USER -d -q "$APP_NAME"

it gave the same error as the OP wrote above i.e. 
Something went wrong when creating the new app - it's not listed in the apps list
But it did create the app in ITC. Subsequent run of the same says the app is already there. This is with the 1.1.2 produce. So could be harmless error.

**Comment by lukethoene** [comment] 2016-08-08 17:45
We have a unique business model in which we submit 15 to 20 new apps daily.  What I'm seeing (since mid week last week) is what appears to be a delay in the app showing up in the dev portal list.  So when the script moves on to create the provisioning profile, it doesn't "see" the app and fails at that point.

Up to then, it has successfully created the certs and the app listing in Connect, so our current workaround is to revoke the certs and restart the script as if it's brand new.  At that point, enough time has passed that our app list now shows the new listing, and the rest of the deployment works as expected.

**Comment by lukethoene** [comment] 2016-08-08 17:46
updates to existing apps are unaffected

**Comment by ericertl** [comment] 2016-08-09 17:08
Hi @vpolouchkine 
Could we add a new parameter (fetch_delay int seconds) in **produce** to introduce a delay between the app creation in ITC and the command that searches for the app?

It should be in **[produce/lib/produce/itunes_connect.rb](https://github.com/fastlane/fastlane/blob/9c0494ef5e7d71afc51c73fe0b141b02e8991d9c/produce/lib/produce/itunes_connect.rb)** 
Something like:
```
Spaceship::Tunes::Application.create!(name: Produce.config[:app_name], 
                                              primary_language: language,
                                              version: Produce.config[:app_version] || "1.0",
                                              sku: Produce.config[:sku].to_s, # might be an int
                                              bundle_id: app_identifier,
                                              bundle_id_suffix: Produce.config[:bundle_identifier_suffix],
                                              company_name: Produce.config[:company_name])
sleep([:fetch_delay])
application = fetch_application
UI.crash!("Something went wrong when creating the new app - it's not listed in the App's list") unless application
```

**Comment by KrauseFx** [comment] 2016-08-09 17:50
I'd very much prefer to avoid having a waiting time, as it's a hacky solution/workaround. Is there any other way we can solve this?

**Comment by KrauseFx** [comment] 2016-08-09 17:51
> We have a unique business model in which we submit 15 to 20 new apps daily. What I'm seeing (since mid week last week) is what appears to be a delay in the app showing up in the dev portal list. So when the script moves on to create the provisioning profile, it doesn't "see" the app and fails at that point.

A lot of companies use fastlane for that - what steps are necessary to run into this error? `produce`, `cert` and `sigh`, right?

**Comment by ericertl** [comment] 2016-08-09 18:06
Hi @KrauseFx 

We run **produce** in separate lanes, one with skip_itc and the other with skip_devcenter because we had problems with the app list in the devcenter not updating fast enough.
As the app base keeps growing, we now are facing issues with produce creating the app in ITC as Spaceship doesn't seem to find the app it just created (most likely due the huge amount of apps we have)

For similar problems we asked for the introduction of the **skip_fetch_profiles** param in **sigh** long time ago

**Comment by ericertl** [comment] 2016-08-09 18:12
If a delay is too hacky, could we add a number of retries to `application = fetch_application` after the app is created?

**Comment by KrauseFx** [comment] 2016-08-09 18:12
This is definitely something that should be fixed, as it's one of the main uses of fastlane.

**Comment by ericertl** [comment] 2016-08-09 18:19
My 2 cents. Why doesn't Spaceship return the application it just created? That way you could skip the `application = fetch_application`command.
Even if ITC API doesn't return all the info, I guess you get a request status for success, so you could build an application object with the info provided to create it

**Comment by KrauseFx** [comment] 2016-08-10 17:33
@ericertl Because the return value doesn't contain all the information yet and therefore later steps (like `deliver` will fail)

**Comment by KrauseFx** [comment] 2016-08-10 17:34
I just pushed https://github.com/fastlane/fastlane/pull/5688 - this will be in the next release. Thanks everyone for your help 🚀

**Comment by ericertl** [comment] 2016-08-10 18:29
Thanks @KrauseFx, that was fast! Can't wait for next release. 
So, for what I could get spaceship code and now confirmed on your fix, spaceship did return an application object (although incomplete per your comments prone to fail in next steps).

An correct me if I'm wrong: the new behaviour would retry 60 times with 10 seconds sleep between each retry (give or take 10 mins plus the request time)?

**Closed** 2016-08-10 18:42 UTC
Labels: bug, produce, spaceship

**Comment by lupugabriel** [comment] 2016-12-01 10:55
Hi there. i have a solution for this. After you create the app in terminal. Just upload a build and the app will appear.

Basically i do these steps:

run from terminal to create the app.
upload a first build from xCode
the app will appear on ItunesConnect once the build is uploaded.
app = Spaceship::Tunes::Application.find("com.*****") it will work.
