### ISSUE TITLE
OpenSSL error

### ISSUE THREAD

**Issue by self-creative** [fastlane/fastlane#4267] opened 2016-04-20 01:18 UTC
ruby-2.0.0-p598/lib/ruby/2.0.0/net/http.rb:918:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (Faraday::SSLError)

**Comment by MickeyHub** [comment] 2016-04-20 02:36
#1418

**Comment by asfalcone** [comment] 2016-04-20 13:58
Closing as a duplicate of #1418. If you are running into addition problems please submit another issue that follows is the [ISSUE TEMPLATE](https://github.com/fastlane/fastlane/blob/master/ISSUE_TEMPLATE.md)

**Closed by asfalcone** 2016-04-20 13:58 UTC
