### ISSUE TITLE
Fastlane Precheck fails with 'Failed: No broken urls-> unreachable URLs in app metadata'

### ISSUE THREAD

**Issue by sheinix** [fastlane/fastlane#11027] opened 2017-11-27 10:59 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm running precheck as always, and since two days ago started to fail with unreachable url, for support, marketing and privacy URL's. The urls are ok, they don't redirect and they are giving a 200 OK status.

### Captured Output

Command Used: `check_metadata`
<details><summary>Output/Log</summary>

```

Successfully loaded Appfile at path '/Users/juannuvreni/Desktop/Development/Mascoteros/mascoteros-ios/Mascoteros/fastlane/Appfile'
- apple_id: 'apple@mascoteros.com'
- team_id: '2279G3HUYX'
-------

+--------------------------+----------------------+
|           Summary for precheck 2.66.2           |
+--------------------------+----------------------+
| username                 | apple@mascoteros.com |
| default_rule_level       | error                |
| include_in_app_purchases | true                 |
+--------------------------+----------------------+

Looking for iTunes Connect Team with ID 118116013

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | cocoapods                           | 20          |
| 💥   | precheck                            | 5           |
+------+-------------------------------------+-------------+



```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.1                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.6 (Apple Git-96)           |
| Installation Source         | ~/.rvm/gems/ruby-2.4.0/bin/fastlane         |
| Host                        | Mac OS X 10.13.1 (17B48)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.0e  16 Feb 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.54.1"

default_platform :ios

platform :ios do
  before_all do
    
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..." TO-DO: Set the hook with Slack
   
    cocoapods
    
  end

  desc "Runs all the tests"
  lane :test do
          scan(scheme: "Pods-MascoterosTests",
               clean: true,
               device: "iPhone 6s (10.3)",
       )
  end

  # You can define as many lanes as you want
############################################################################################################################################################################
  desc "MASCOTEROS - BETA : Run the tests and then upload a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta_release do
    
    ENV["APP_IDENTIFIER"] = "com.mascoteros.MascoterosIOS.TestFlight"
    
    match(type: "appstore")
    increment_build_number
    #commit_version_bump
    gym(scheme: "Mascoteros-Staging")
    pilot
  end
############################################################################################################################################################################
  desc "MASCOTEROS - RELEASE : Run the tests and then upload a new release Build to Apple Appstore"
  desc "Deploy a new version to the App Store"
  lane :release do

    ENV["APP_IDENTIFIER"] = "com.mascoteros.MascoterosIOS"

    match(type: "appstore")
    #snapshot
    #frameit
    increment_build_number
    #increment_version_number(bump_type: "minor")
    gym(scheme: "Mascoteros-AppStore") # Build your app - more options available
    deliver(precheck_default_rule_level: :error)
    #deliver(force: true)
    
  end

############################################################################################################################################################################
  desc "MASCOTEROS - PRECHECK : Pre check before uploading to appstore"
  lane :check_metadata do
    precheck
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer

```
</details>

<details><summary>`./Appfile`</summary>

```ruby
app_identifier ENV["APP_IDENTIFIER"] #"com.mascoteros.MascoterosIOS" # The bundle identifier of your app
apple_id "apple@mascoteros.com" # Your Apple email address

team_id "2279G3HUYX" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.66.2  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.2        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.4       |
| io-console                | 0.4.6        |
| openssl                   | 2.0.2        |
| bigdecimal                | 1.3.0        |
| psych                     | 2.2.2        |
</details>

*generated on:* **2017-11-27**
</details>

**Comment by janpio** [comment] 2017-11-27 13:56
Maybe related: https://github.com/fastlane/fastlane/issues/9927
@sheinix can you have a look at this one and confirm or deny that this is similar?

**Comment by sheinix** [comment] 2017-11-27 14:22
It is similar, same error, but the urls are ok, they don't redirect and they are giving a 200 OK status.

**Comment by janpio** [comment] 2017-11-27 14:42
lol, only now I see that was _you_ posting there with the non-redirected URL, and even I that told you to create a new issue - sorry :)

**Comment by sheinix** [comment] 2017-11-27 15:33
Haha yes, no worries!

**Comment by janpio** [comment] 2017-11-27 15:37
Can you run your command or lane with `--verbose` and see if this gives you additional helpful output?

**Comment by milch** [comment] 2017-11-27 22:40
@sheinix Also, please run the following command from the command line in your project directory: 

```bash
echo -e "\`\`\`\n" $(cat fastlane/metadata/en-US/marketing_url.txt) "\n\`\`\`" | pbcopy
```

Make sure the path after `cat` points to one of the files with a URL that is failing. It should copy the output to the clipboard. Please paste the result here, exactly as it was copied

**Comment by akwilliamson** [comment] 2017-11-28 00:13
I'm also having this problem.

**Comment by janpio** [comment] 2017-11-28 10:26
Then do the same what @milch suggested to @sheinix please.

**Comment by sheinix** [comment] 2017-11-28 10:39
I ran the echo script that @milch suggested:
```
 https://www.mascoteros.com 
```

And after that, the precheck with --verbose:

```
`$ fastlane precheck --verbose
[11:36:29]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
Successfully loaded Appfile at path '/Users/juannuvreni/Desktop/Development/Mascoteros/mascoteros-ios/Mascoteros/fastlane/Appfile'
- apple_id: 'apple@mascoteros.com'
- team_id: '****'
-------
WARN [2017-11-28 11:36:31.75]: In the config file './fastlane/Deliverfile' you have the line app_identifier, but didn't provide any value. Make sure to append a value right after the option name. Make sure to check the docs for more information

+--------------------------+----------------------+
|           Summary for precheck 2.66.2           |
+--------------------------+----------------------+
| username                 | apple@mascoteros.com |
| default_rule_level       | error                |
| include_in_app_purchases | true                 |
+--------------------------+----------------------+

INFO [2017-11-28 11:36:31.80]: Starting login with user 'apple@mascoteros.com'
Looking for iTunes Connect Team with ID ****
INFO [2017-11-28 11:36:37.50]: Successfully logged in
INFO [2017-11-28 11:36:37.50]: Checking app for precheck rule violations
WARN [2017-11-28 11:36:37.50]: To not be asked about this value, you can specify it using 'app_identifier'
 [2017-11-28 11:36:37.50]: The bundle identifier of your app: com.mascoteros.MascoterosIOS
INFO [2017-11-28 11:36:53.71]: Reading in-app purchases. If you have a lot, this might take a while
INFO [2017-11-28 11:36:53.71]: You can disable IAP checking by setting the `include_in_app_purchases` flag to `false`
INFO [2017-11-28 11:36:54.91]: Done reading in-app purchases
INFO [2017-11-28 11:36:55.93]: ✅  Passed: No negative  sentiment
INFO [2017-11-28 11:36:55.93]: ✅  Passed: No placeholder text
INFO [2017-11-28 11:36:55.93]: ✅  Passed: No mentioning  competitors
INFO [2017-11-28 11:36:55.93]: ✅  Passed: No future functionality promises
INFO [2017-11-28 11:36:55.93]: ✅  Passed: No words indicating test content
INFO [2017-11-28 11:36:55.95]: ✅  Passed: No curse words
INFO [2017-11-28 11:36:55.95]: ✅  Passed: No words indicating your IAP is free
DEBUG [2017-11-28 11:36:55.95]: custom_text excluded because no data was passed to it e.g.: custom_text(data: <data here>)
INFO [2017-11-28 11:36:55.95]: ✅  Passed: Incorrect, or missing copyright date
DEBUG [2017-11-28 11:36:55.95]: URL https://www.mascoteros.com not reachable 😵
DEBUG [2017-11-28 11:36:55.95]: URL https://www.mascoteros.com not reachable 😵
DEBUG [2017-11-28 11:36:55.95]: URL https://www.mascoteros.com not reachable 😵
ERROR [2017-11-28 11:36:55.95]: 😵  Failed: No broken urls-> unreachable URLs in app metadata
+------------------------+-----------------------------------------+
|                        Potential problems                        |
+------------------------+-----------------------------------------+
| Field                  | Failure reason                          |
+------------------------+-----------------------------------------+
| support URL: (es-ES)   | unreachable: https://www.mascoteros.com |
| marketing URL: (es-ES) | unreachable: https://www.mascoteros.com |
| privacy URL: (es-ES)   | unreachable: https://www.mascoteros.com |
+------------------------+-----------------------------------------+
WARN [2017-11-28 11:36:55.95]: In the config file './fastlane/Deliverfile' you have the line app_identifier, but didn't provide any value. Make sure to append a value right after the option name. Make sure to check the docs for more information
INFO [2017-11-28 11:36:56.49]: fastlane failed to write the crash report to /Users/juannuvreni/.fastlane/latest_crash.json.
/Users/juannuvreni/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.66.2/fastlane_core/lib/fastlane_core/ui/interface.rb:131:in `user_error!': [!] precheck 👮‍♀️ 👮  found one or more potential problems that must be addressed before submitting to review (FastlaneCore::Interface::FastlaneError)
	from /Users/juannuvreni/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.66.2/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/juannuvreni/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.66.2/precheck/lib/precheck/runner.rb:43:in `run'
	from /Users/juannuvreni/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.66.2/precheck/lib/precheck/commands_generator.rb:34:in `block (2 levels) in run'
	from /Users/juannuvreni/.rvm/gems/ruby-2.4.0@global/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/juannuvreni/.rvm/gems/ruby-2.4.0@global/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Users/juannuvreni/.rvm/gems/ruby-2.4.0@global/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/juannuvreni/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.66.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
	from /Users/juannuvreni/.rvm/gems/ruby-2.4.0@global/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/juannuvreni/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.66.2/precheck/lib/precheck/commands_generator.rb:53:in `run'
	from /Users/juannuvreni/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.66.2/precheck/lib/precheck/commands_generator.rb:12:in `start'
	from /Users/juannuvreni/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.66.2/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Users/juannuvreni/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.66.2/bin/fastlane:20:in `<top (required)>'
	from /Users/juannuvreni/.rvm/gems/ruby-2.4.0/bin/fastlane:22:in `load'
	from /Users/juannuvreni/.rvm/gems/ruby-2.4.0/bin/fastlane:22:in `<main>'`
```

**Comment by janpio** [comment] 2017-11-28 10:54
My next debugging step would be to configure a proxy (after I found out how to do that...) and see what request fastlane is sending and if there actually is a response or not.

**Comment by milch** [comment] 2017-11-28 10:54
That is ... very unusual. I thought you might have some kind of symbols in your URL that make it fail, but it looks like the URL is fine. I tried running precheck with the same URL here and it works without a problem. I haven't used rvm in a while but I remember there were problems with SSL certificates there ([see here](https://rvm.io/support/fixing-broken-ssl-certificates)). I could see that causing an issue here, so can you try running the following command from your shell? (it's what rvm recommends to fix SSL issues)

```bash
rvm osx-ssl-certs update all
```

**Comment by sheinix** [comment] 2017-11-28 11:21
Hi @milch thanks for the response. I ran `ram osx-ssl-certs update all` with this output:
```
Updating certificates for /usr/local/etc/openssl/cert.pem: Updating certificates in '/usr/local/etc/openssl/cert.pem'.
Updated.
Updating certificates for /usr/local/etc/openssl@1.1/cert.pem: Updating certificates in '/usr/local/etc/openssl@1.1/cert.pem'.
Updated.
```
But still the same problem. :/

**Comment by TSCombine** [comment] 2017-12-04 13:36
I suddenly got the same issue:
`/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.0/fastlane_core/lib/fastlane_core/ui/interface.rb:131:in `user_error!': [!] precheck 👮‍♀️ 👮  found one or more potential problems that must be addressed before submitting to review (FastlaneCore::Interface::FastlaneError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.0/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.0/precheck/lib/precheck/runner.rb:43:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.0/fastlane/lib/fastlane/actions/check_app_store_metadata.rb:10:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.0/fastlane/lib/fastlane/runner.rb:231:in `block in execute_action'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.0/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:58:in `block (2 levels) in parsing_binding'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.0/fastlane/lib/fastlane/lane_manager.rb:54:in `cruise_lane'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.0/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.0/fastlane/lib/fastlane/commands_generator.rb:304:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.0/fastlane/lib/fastlane/cli_tools_distributor.rb:75:in `take_off'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.68.0/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'`

**Comment by seanvikoren** [comment] 2017-12-06 00:39
I just updated to fastlane_version "2.68.2", and am getting this as well (same errors using --verbose).

**Comment by janpio** [comment] 2017-12-06 09:40
Someone should configure his local system to use a proxy and look at the requests that are sent out during usage of `precheck`. I think that's the only way to understand what is going on here.

**Comment by milch** [comment] 2017-12-07 11:07
To expand on what @janpio said and because not everyone has a charles licence they can use, here's a small tutorial of what we want you to do:


- Install `mitmproxy`. Easiest way to do this is using homebrew to run `brew install mitmproxy`
- In one Terminal window:
  - Run `sudo mitmproxy` to start the proxy
  - It should just show an empty space at this point with a blue bar at the bottom
  - Leave this window open!
- In a second Terminal window/tab:
  - Set the environment variable `http_proxy` to `http://localhost:8080`: 
  ```bash
  export http_proxy="http://localhost:8080"
  ```
  - Create a ruby file `check.rb` with the following content in your project directory (this is essentially the precheck rule with SSL verification disabled):
  ```ruby
  require 'uri'
  require 'addressable'
  require 'faraday'
  require 'faraday_middleware'
  
  def check(url)
    url = url.to_s.strip
    uri = Addressable::URI.parse(url)
    uri.fragment = nil
    request = Faraday.new(URI.encode(uri.to_s)) do |c|
      c.use FaradayMiddleware::FollowRedirects
      c.adapter :net_http
      c.ssl[:verify_mode] = OpenSSL::SSL::VERIFY_NONE
    end
    puts request.head.status
  end
  ```
  - Load an interactive ruby shell with the script above: 
  ```bash
  irb -r ./check.rb
  ```
  - Call the `check` function with the URLs that are failing from that ruby shell:
  ```ruby
  # for example: (be sure to adjust the path/url)
  check(File.read("./fastlane/metadata/en_US/marketing_url.txt"))
  check("https://www.mascoteros.com")
  ```
- Go back to the first window where you had `mitmproxy` running. It should look something like this: 
![screen shot 2017-12-07 at 11 59 20](https://user-images.githubusercontent.com/279407/33711967-1ce9e52c-db46-11e7-8ab1-3bd6c50ea62e.png)
- Each pair of lines is a request and the response
- You can navigate by typing `j` to go down or `k` to go up by one request. Pressing `<enter>` or clicking on a request will take you to the detail view
- On the detail view you can use `<tab>` or `h`/`l` to navigate between the Request/Response/Detail tabs. You can return to the list by pressing `q`
- Post a screenshot of the request/response list 
- If any of the responses had a status other than 200 (indicated by the `← 200 OK text/html [no content]` lines) navigate to the detail view of that response, go to the "Response" tab there and also post a screenshot of that
- You can quit out of mitmproxy by pressing `q` and then confirming with `y`

**Comment by janpio** [comment] 2017-12-07 11:24
(I'll review and merge that comment as a PR to the docs repo ;))

**Comment by milch** [comment] 2017-12-07 11:27
I don't know if they got rid of it. It's possible they still have it but I find Charles to be slow and the UI to be confusing. `mitmproxy` is simple and works 😊

**Comment by seanvikoren** [comment] 2017-12-07 21:05
Running 'fastlane precheck' on version "2.53.1" works fine by the way.

**Comment by seanvikoren** [comment] 2017-12-09 18:40
Also, I know there is a way to treat this error as a warning, but I can't seem to locate the syntax.

**Comment by funnel20** [comment] 2017-12-09 23:27
I have the same issue where my valid URLs are reported erroneous.
The error "URL https://www.mascoteros.com not reachable 😵" is given in https://github.com/fastlane/fastlane/blob/f2ea29347f894c00dc55e87a0e45c6063319d791/precheck/lib/precheck/rules/unreachable_urls_rule.rb#L35 as part of the `rescue` action.
Doesn't this mean that the `begin` code is failing?

When I isolate the begin code in a small test Ruby file and run it in Terminal, it fails on the request line with:
```
testURLCheck.rb:10:in `<main>': uninitialized constant URI (NameError)
```

Here is the file content of _testURLCheck.rb_: 
```Ruby
require "addressable"
require "faraday"

url = 'http://www.google.com'
url = url.to_s.strip
uri = Addressable::URI.parse(url)
uri.fragment = nil

request = Faraday.new(URI.encode(uri.to_s)) do |connection|
    connection.use FaradayMiddleware::FollowRedirects
    connection.adapter :net_http
end
```

**Comment by funnel20** [comment] 2017-12-09 23:36
I was able to get the script running by:
1. replacing `URI` in the request line by `Addressable::URI`. Now an error on the next line was given about uninitialized constant FaradayMiddleware
2. Add require `"faraday_middleware"`. This was a mistake of my isolated test file.

So only change 1 was the key.

The final code:
```Ruby
require "addressable"
require "faraday"
require "faraday_middleware"

url = 'http://www.google.com'

url = url.to_s.strip
uri = Addressable::URI.parse(url)
uri.fragment = nil

print Addressable::URI.encode(uri.to_s)
request = Faraday.new(Addressable::URI.encode(uri.to_s)) do |connection|
    connection.use FaradayMiddleware::FollowRedirects
    connection.adapter :net_http
end
```

**Comment by funnel20** [comment] 2017-12-10 00:01
I changed this in my local copy and run Deliver, but unfortunately it still shows the error.

**Comment by funnel20** [comment] 2017-12-10 00:17
And found it!!!
I played around with some `print` commands in my local copy and found that the begin code was never run successfully.
So I commented the `begin` line and `rescue` section, to see with verbose logging in which line it would fail. This was:

```
DEBUG [2017-12-10 01:07:32.54]: #<NameError: uninitialized constant Precheck::UnreachableURLRule::Addressable>
DEBUG [2017-12-10 01:07:32.54]: /Users/Martijn/fastlane/precheck/lib/precheck/rules/unreachable_urls_rule.rb:29:in `block in rule_block'
```

So I added `require 'addressable'` to the top of _unreachable_urls_rule.rb_ and ran again. 
Now it passed.
Reverted original `begin` + `rescue` code and ran a final verification:

`INFO [2017-12-10 01:15:47.51]: ✅  Passed: No broken urls`

Even after removing `Addressable::` from the request line, it does work. So that wasn't the issue, but the issue is that lib 'addressable' is not linked.

**Comment by funnel20** [comment] 2017-12-10 00:21
However, I don't understand 2 things:
1. Why did I have the issue with my isolated file where I had to replace `URI` by `Addressable::URI`? In my local Fastlane copy I didn't have to change this. Or does Fastlane links somewhere else to the URI lib?
2. Why does precheck work at @milch, see his https://github.com/fastlane/fastlane/issues/11027#issuecomment-347486879

**Comment by funnel20** [comment] 2017-12-10 12:00
**Recommendation**
The log entry in the exception handling in `rescue` is misleading. 
It prints `"URL #{url} not reachable 😵"` which is not true. 
The real problem is that the code to test the reachability fails to run due to a programming error.

So the string should be something like:
`"Failed to test if URL #{url} is reachable. This seems to be a Fastlane issue."`

**Comment by janpio** [comment] 2017-12-10 12:33
That is very possible - that code is in its first iteration. 

Do you want to start a PR to fix this, so it can be reviewed and eventually merged? 
Seems like a very useful change that would make lots of people happy. Thanks.

**Comment by funnel20** [comment] 2017-12-10 12:48
@janpio Sure, but I need advice which of the solutions should be applied:

> 1. Add `require 'addressable'`
> or
> 2. Replace `Addressable::URI`  by `URI`

I have no overview how these libs are used over the entire project.
Any suggestion?

**Comment by milch** [comment] 2017-12-10 12:50
Yeah I think we're jumping the gun a bit here. First we need to understand why it seems to be working on our setups but failing on others. 

@funnel20 @seanvikoren What did you use to install fastlane?

**Comment by milch** [comment] 2017-12-10 12:54
Also @funnel20, can you run `fastlane env` and check if the `Loaded Gems` section of the output contains `addressable`? If it does it would be even weirder that you get a `NameError` for `Addressable`

**Comment by funnel20** [comment] 2017-12-10 12:54
@milch Years ago I did it via Terminal with something like `gem install`.
And each time I see a green update message, I use `gem update`.

**Comment by funnel20** [comment] 2017-12-10 12:59
`addressable` is not in:

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.1                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.rvm/gems/ruby-2.2.4/bin/fastlane         |
| Host                        | Mac OS X 10.13.1 (17B1003)                  |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.2.4/lib                |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
#
#  Fastfile
#  myTifi
#
#  Created by Martijn Koopman on 27/09/17.
#  Copyright © 2017 iMKapps. All rights reserved.
#
#  $Rev: 3973 $
#  $Date:: 2017-11-02 #$

before_all do
    # Set Xcode version
    ENV['DEVELOPER_DIR'] = '/Applications/Xcode.app/Contents/Developer'
end

# Create a lane.
# Run this via Terminal via: fastlane screenshots
lane :screenshots do
    # Generate screenshots for the App Store:
    snapshot
end

```
</details>

**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.68.2  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                   | Version      |
| --------------------- | ------------ |
| executable-hooks      | 1.3.2        |
| bundler-unload        | 1.0.2        |
| rubygems-bundler      | 1.4.4        |
| bundler               | 1.16.0       |
| slack-notifier        | 1.5.1        |
| claide                | 1.0.2        |
| colored2              | 3.1.2        |
| nanaimo               | 0.2.3        |
| xcodeproj             | 1.5.3        |
| multipart-post        | 2.0.0        |
| word_wrap             | 1.0.0        |
| public_suffix         | 2.0.5        |
| tty-screen            | 0.6.3        |
| babosa                | 1.0.2        |
| colored               | 1.2          |
| commander-fastlane    | 4.4.5        |
| http-cookie           | 1.0.3        |
| faraday-cookie_jar    | 0.0.6        |
| fastimage             | 2.1.0        |
| mini_magick           | 4.5.1        |
| security              | 0.1.3        |
| json                  | 2.1.0        |
| highline              | 1.7.10       |
| excon                 | 0.59.0       |
| rubyzip               | 1.2.1        |
| plist                 | 3.3.0        |
| faraday               | 0.13.1       |
| unf                   | 0.1.4        |
| domain_name           | 0.5.20170404 |
| faraday_middleware    | 0.12.2       |
| terminal-table        | 1.8.0        |
| unicode-display_width | 1.3.0        |
</details>


*generated on:* **2017-12-10**
</details>

**Comment by seanvikoren** [comment] 2017-12-10 18:41
@milch I used cocpods to install fastlane.

**Comment by seanvikoren** [comment] 2017-12-10 19:22
I went ahead and added:
`require 'addressable'`
to unreachable_urls_rule.rb locally and everything is working again.  Which is great because we are about to hit the App store :) 
@funnel20 Thank you for tracking down an initial solution!

**Comment by taquitos** [comment] 2017-12-12 17:14
Sorry all, when merges happen linked issues are auto-closed, ugh. This conversation is still ongoing to determine root cause

**Closed** 2018-02-04 17:31 UTC
Labels: status: waiting-for-reply, tool: precheck, type: bug
