### ISSUE TITLE
App name on TestFlight build without the spaces

### ISSUE THREAD

**Issue by stein-fabricio** [fastlane/fastlane#12154] opened 2018-03-23 21:50 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
After some time searching about fastlane I was able to upload my build to Testflight correctly. All is fine except the app name (the name the user sees, display name on Xcode, not bundle name or bundle id). The app name was suppose to be "Boring Name" (example), after uploading the build and downloading it the name displayed is "BoringNa..." (yeah, it doesn't even shows the complete name). Uploading via Xcode works fine.

What can I do? Anyone having the same issue?

Thanks!

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.3                                                        |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.14.3 (Apple Git-98)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.3 (17D102)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.2                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.86.0"

default_platform :ios

platform :ios do

  # 1
  desc "Creating a code signing certificate and provisioning profile"
  # 2
lane :testflight do
    cert
    sigh
    update_info_plist(
    plist_path: 'project/Info.plist'
    )
    gym(
    scheme: "project",
    export_method: "app-store",
    export_xcargs: "-allowProvisioningUpdates"
    )
    upload_to_testflight
    pilot(skip_waiting_for_build_processing: true)
end

  error do |lane, exception|
  # This block is called if there was an error running a lane.
  end

end
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.87.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                                | Version | Update-Status |
| ----------------------------------------------------- | ------- | ------------- |
| fastlane-plugin-update_provisioning_profile_specifier | 1.3.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                                   | Version      |
| ----------------------------------------------------- | ------------ |
| did_you_mean                                          | 1.0.0        |
| slack-notifier                                        | 2.3.2        |
| atomos                                                | 0.1.2        |
| CFPropertyList                                        | 2.3.6        |
| claide                                                | 1.0.2        |
| colored2                                              | 3.1.2        |
| nanaimo                                               | 0.2.4        |
| xcodeproj                                             | 1.5.7        |
| rouge                                                 | 2.0.7        |
| xcpretty                                              | 0.2.8        |
| terminal-notifier                                     | 1.8.0        |
| unicode-display_width                                 | 1.3.0        |
| terminal-table                                        | 1.8.0        |
| plist                                                 | 3.4.0        |
| public_suffix                                         | 2.0.5        |
| addressable                                           | 2.5.2        |
| multipart-post                                        | 2.0.0        |
| word_wrap                                             | 1.0.0        |
| tty-screen                                            | 0.6.4        |
| tty-cursor                                            | 0.5.0        |
| tty-spinner                                           | 0.8.0        |
| babosa                                                | 1.0.2        |
| colored                                               | 1.2          |
| highline                                              | 1.7.10       |
| commander-fastlane                                    | 4.4.6        |
| excon                                                 | 0.61.0       |
| faraday                                               | 0.14.0       |
| unf_ext                                               | 0.0.7.5      |
| unf                                                   | 0.1.4        |
| domain_name                                           | 0.5.20170404 |
| http-cookie                                           | 1.0.3        |
| faraday-cookie_jar                                    | 0.0.6        |
| fastimage                                             | 2.1.1        |
| gh_inspector                                          | 1.1.3        |
| mini_magick                                           | 4.5.1        |
| multi_json                                            | 1.13.1       |
| multi_xml                                             | 0.6.0        |
| rubyzip                                               | 1.2.1        |
| security                                              | 0.1.3        |
| xcpretty-travis-formatter                             | 1.0.0        |
| dotenv                                                | 2.2.1        |
| bundler                                               | 1.16.1       |
| faraday_middleware                                    | 0.12.2       |
| naturally                                             | 2.1.0        |
| simctl                                                | 1.6.2        |
| uber                                                  | 0.1.0        |
| declarative                                           | 0.0.10       |
| declarative-option                                    | 0.1.0        |
| representable                                         | 3.0.4        |
| retriable                                             | 3.1.1        |
| mime-types-data                                       | 3.2016.0521  |
| mime-types                                            | 3.1          |
| little-plugger                                        | 1.1.4        |
| logging                                               | 2.2.2        |
| jwt                                                   | 2.1.0        |
| memoist                                               | 0.16.0       |
| os                                                    | 0.9.6        |
| signet                                                | 0.8.1        |
| googleauth                                            | 0.6.2        |
| httpclient                                            | 2.8.3        |
| google-api-client                                     | 0.13.6       |
| io-console                                            | 0.4.5        |
| libxml-ruby                                           | 2.9.0        |
| json                                                  | 2.1.0        |
| fastlane-plugin-update_provisioning_profile_specifier | 1.3.0        |
</details>

*generated on:* **2018-03-23**
</details>
<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by joshdholtz** [comment] 2018-03-26 23:51
@stein-fabricio I see that you are replacing the info plist with `update_info_plist`. What are the contents of your plist at `project/Info.plist`?

**Comment by stein-fabricio** [comment] 2018-03-27 00:44
@joshdholtz actually I did this
`update_info_plist(
    plist_path: 'unquOProject/Info.plist',
    display_name: 'Boring name'
    )`
trying to explicit the desired name, but it didn't work either.

**Comment by joshdholtz** [comment] 2018-03-28 14:31
@stein-fabricio This seams to be a "feature" of iOS. If the name you are trying to display is too long for the, it will be smart to try to remove spaces and then add a "..." if it doesn't fit (see my example images below) This doesn't appear to be a fastlane problem (as I was able to replicate this just using Xcode) and I think the only real solution would be to choose a shorter name 😊 

## Just right
<img width="578" alt="screen shot 2018-03-28 at 9 28 17 am" src="https://user-images.githubusercontent.com/401294/38035653-79433500-326a-11e8-8337-5762eec43b3d.png">

## Too long
<img width="538" alt="screen shot 2018-03-28 at 9 27 54 am" src="https://user-images.githubusercontent.com/401294/38035654-79552058-326a-11e8-9bbd-1d5ae126f088.png">

Closing this since this is expected behavior by iOS. Happy fastlaning 🚀

**Closed by joshdholtz** 2018-03-28 14:31 UTC
