### ISSUE TITLE
Update up Error: "You must detail what's new in this version in English

### ISSUE THREAD

**Issue by gran33** [fastlane/fastlane#3714] opened 2016-03-13 13:04 UTC
```
~/vendor/bundle/ruby/2.0.0/gems/spaceship-0.22.0/lib/spaceship/tunes/tunes_client.rb:219:in `handle_itc_response': [!] You must detail what's new in this version in English. (Spaceship::TunesClient::ITunesConnectError)
~/vendor/bundle/ruby/2.0.0/gems/spaceship-0.22.0/lib/spaceship/tunes/tunes_client.rb:681:in `prepare_app_submissions'
~/vendor/bundle/ruby/2.0.0/gems/spaceship-0.22.0/lib/spaceship/tunes/app_submission.rb:117:in `create'
~/vendor/bundle/ruby/2.0.0/gems/spaceship-0.22.0/lib/spaceship/tunes/application.rb:269:in `create_submission'
~/vendor/bundle/ruby/2.0.0/gems/deliver-1.10.3/lib/deliver/submit_for_review.rb:8:in `submit!'
~/vendor/bundle/ruby/2.0.0/gems/deliver-1.10.3/lib/deliver/runner.rb:87:in `submit_for_review'
~/vendor/bundle/ruby/2.0.0/gems/deliver-1.10.3/lib/deliver/runner.rb:30:in `run'
~/vendor/bundle/ruby/2.0.0/gems/deliver-1.10.3/lib/deliver/commands_generator.rb:49:in `block (2 levels) in run'
~/vendor/bundle/ruby/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
~/vendor/bundle/ruby/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
~/vendor/bundle/ruby/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
~/vendor/bundle/ruby/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
~/vendor/bundle/ruby/2.0.0/gems/fastlane_core-0.37.0/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
~/vendor/bundle/ruby/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
~/vendor/bundle/ruby/2.0.0/gems/deliver-1.10.3/lib/deliver/commands_generator.rb:132:in `run'
~/vendor/bundle/ruby/2.0.0/gems/deliver-1.10.3/lib/deliver/commands_generator.rb:12:in `start'
~/vendor/bundle/ruby/2.0.0/gems/deliver-1.10.3/bin/deliver:5:in `<top (required)>'
~/vendor/bundle/ruby/2.0.0/bin/deliver:23:in `load'
~/vendor/bundle/ruby/2.0.0/bin/deliver:23:in `<main>'
```

**Comment by asfalcone** [comment] 2016-03-14 14:11
Closing as dupe of #3715

**Closed by asfalcone** 2016-03-14 14:11 UTC
