### ISSUE TITLE
sigh/cert ignores values in .env file

### ISSUE THREAD

**Issue by gtatgh** [fastlane/fastlane#9872] opened 2017-07-27 08:59 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
It seeams that sigh ignores values defined in .env file. So I have defined for example,
* SIGH_SKIP_INSTALL=true
* SIGH_FORCE=false
* SIGH_CERTIFICATE_ID=${CERTIFICATE_ID}

But log output tell me that this values are ignored.
New certificate has been created and installed locally.

##### Complete output when running fastlane, including the stack trace and command used
<details><summary>match Log</summary>
[10:50:12]: -------------------
[10:50:12]: --- Step: match ---
[10:50:12]: -------------------

+-----------------------+----------------------------------------------+
|                       Summary for match 2.49.0                       |
+-----------------------+----------------------------------------------+
| git_url               | ssh://Bamboo-Daemon@xos-htu-stash:7999/ga  |
|                       | d/ios_certificates.git                       |
| git_branch            | com.company.app.iOSMasterProject          |
| type                  | adhoc                                        |
| app_identifier        | com.company.app.iOSMasterProject          |
| username              | iosdev@company.com                    |
| keychain_name         | login.keychain                               |
| readonly              | false                                        |
| team_id               | TEAM_ID                                   |
| team_name             | company City GmbH                    |
| verbose               | false                                        |
| force                 | false                                        |
| skip_confirmation     | false                                        |
| shallow_clone         | false                                        |
| clone_branch_directly | false                                        |
| force_for_new_devices | true                                         |
| skip_docs             | false                                        |
| platform              | ios                                          |
+-----------------------+----------------------------------------------+

[10:50:12]: Cloning remote git repo...
[10:50:12]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[10:50:13]: Checking out branch com.company.app.iOSMasterProject...
[10:50:13]: 🔓  Successfully decrypted certificates repo
[10:50:13]: Verifying that the certificate and profile are still valid on the Dev Portal...
[10:50:17]: Couldn't find a valid code signing identity in the git repo for distribution... creating one for you now

+---------------+----------------------------------------------+
|                   Summary for cert 2.49.0                    |
+---------------+----------------------------------------------+
| development   | false                                        |
| force         | true                                         |
| username      | iosdev@company.com                    |
| team_id       | TEAM_ID                                   |
| keychain_path | /Users/user/Library/Keychains/login.keycha  |
|               | in-db                                        |
| team_name     | company City GmbH                    |
| platform      | ios                                          |
+---------------+----------------------------------------------+

[10:50:17]: Starting login with user 'iosdev@company.com'
[10:50:19]: Successfully logged in
[10:50:28]: Successfully generated NEW_CERT_ID which was imported to the local machine.
[10:50:29]: Verifying the certificate is properly installed locally...
[10:50:29]: Successfully installed certificate NEW_CERT_ID

+-------------------------------------+-------------------------------------+
|                          Summary for sigh 2.49.0                          |
+-------------------------------------+-------------------------------------+
| app_identifier                      | com.company.app.iOSMasterProject |
| username                            | iosdev@company.com           |
| force                               | true                                |
| cert_id                             | NEW_CERT_ID                          |
| provisioning_name                   | match AdHoc                         |
|                                     | com.company.app.iOSMasterProject |
| ignore_profiles_with_different_name | true                                |
| team_id                             | TEAM_ID                          |
| platform                            | ios                                 |
| adhoc                               | true                                |
| development                         | false                               |
| skip_install                        | true                                |
| team_name                           | company City GmbH           |
| skip_fetch_profiles                 | false                               |
| skip_certificate_verification       | false                               |
+-------------------------------------+-------------------------------------+

[10:50:29]: Starting login with user 'iosdev@company.com'
[10:50:33]: Successfully logged in
[10:50:33]: Fetching profiles...
[10:50:34]: Verifying certificates...
[10:50:34]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you
[10:50:37]: Creating new provisioning profile for 'com.company.app.iOSMasterProject' with name 'match AdHoc com.company.app.iOSMasterProject' for 'ios' platform
[10:50:38]: Downloading provisioning profile...
[10:50:39]: Successfully downloaded provisioning profile...
/var/folders/lr/5vbfxcnd0vd3nm4djf1py7ycg0qddv/T/d20170727-83624-1ksw9u9/profiles/adhoc/AdHoc_com.company.app.iOSMasterProject.mobileprovision
[10:50:39]: Installing provisioning profile...
[10:50:40]: 🔒  Successfully encrypted certificates repo
[10:50:40]: Pushing changes to remote git repo...

+---------------------+------------------------------+------------------------------+
|                          Installed Provisioning Profile                           |
+---------------------+------------------------------+------------------------------+
| Parameter           | Environment Variable         | Value                        |
+---------------------+------------------------------+------------------------------+
| App Identifier      |                              | com.company.app.iOSMaste  |
|                     |                              | rProject                     |
| Type                |                              | adhoc                        |
| Platform            |                              | ios                          |
| Profile UUID        | sigh_com.company.app.iOS  | 2707a04e-59e8-4afc-a857-fdf  |
|                     | MasterProject_adhoc          | a8228ea44                    |
| Profile Name        | sigh_com.company.app.iOS  | match AdHoc                  |
|                     | MasterProject_adhoc_profile  | com.company.app.iOSMaste  |
|                     | -name                        | rProject                     |
| Profile Path        | sigh_com.company.app.iOS  | /Users/user/Library/Mobile  |
|                     | MasterProject_adhoc_profile  | Device/Provisioning          |
|                     | -path                        | Profiles/2707a04e-59e8-4afc  |
|                     |                              | -a857-fdfa8228ea44.mobilepr  |
|                     |                              | ovision                      |
| Development Team ID | sigh_com.company.app.iOS  | TEAM_ID                   |
|                     | MasterProject_adhoc_team-id  |                              |
+---------------------+------------------------------+------------------------------+

[10:50:41]: All required keys, certificates and provisioning profiles are installed 🙌
[10:50:41]: Setting Provisioning Profile type to 'ad-hoc'
[10:50:41]: Cruising back to lane 'ios setup' 🚘
[10:50:41]: Lane setup completed successfully.

+------+------------------------------+-------------+
|                 fastlane summary                  |
+------+------------------------------+-------------+
| Step | Action                       | Time (in s) |
+------+------------------------------+-------------+
| 1    | Verifying required fastlane  | 0           |
|      | version                      |             |
| 2    | default_platform             | 0           |
| 3    | Switch to ios create_app_id  | 0           |
|      | lane                         |             |
| 4    | produce                      | 4           |
| 5    | Switch to ios sync_signing   | 0           |
|      | lane                         |             |
| 6    | match                        | 28          |
+------+------------------------------+-------------+

[10:50:41]: fastlane.tools finished successfully 🎉
</details>

<details>
<summary>sigh configuration in .env</summary>
SIGH_TEAM_ID=${TEAM_ID}

SIGH_TEAM_NAME=${TEAM_NAME}

SIGH_CERTIFICATE_ID=${CERTIFICATE_ID}

SIGH_PLATFORM='ios'

SIGH_SKIP_INSTALL=true

SIGH_FORCE=false
</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.9.2                           |
| Installation Source         | ~/.gem/bin/fastlane                         |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.0/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | de_DE.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/blob/master/fastlane/Fastfile
#
# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`
#
# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.47.0"

default_platform :ios

desc "Print guide to configure new project"
lane :helpme do
	puts ""
	puts "***********************************************************************".cyan
	puts "*                                                                     *".cyan
	puts "* - Define values in 'fastlane/.env' or 'fastlane/.env.default' files *".cyan
	puts "* - Enable Apple Generic Versioning by follow the guide at:           *".cyan
	puts "*   https://developer.apple.com/library/content/qa/qa1827/_index.html *".cyan
	puts "* - Execute `fastlane setup`                                          *".cyan
	puts "*                                                                     *".cyan
	puts "***********************************************************************".cyan
	puts ""
end

platform :ios do
	desc "Create a new App ID on the Developer Portal"
	lane :setup do
		create_app_id
		sync_signing
	end

	desc "Configure, compile, analyze and deploy app"
	lane :build do
		prepare
		compile
		analyze
		deploy
	end

	desc "Configure app"
	lane :prepare do
		update_build_number
		install_cocoapods
		sync_signing
	end

	# https://docs.fastlane.tools/actions/#gym
	desc "Compile and sign app"
	lane :compile do
		disable_automatic_signing
		gym
	end

	desc "Run tests and static analizers"
	lane :analyze do
		unit_tests
	end

	desc "Deploy app"
	lane :deploy do
		# NOP
	end

	desc "Clean after build"
	lane :clean do
		Dir.chdir(ENV["PWD"]) do
			sh("rm -fr #{ENV['GYM_OUTPUT_DIRECTORY']}")
			sh("rm -fr #{ENV['SCAN_OUTPUT_DIRECTORY']}")
			sh("git co -- .")
		end
	end

	# https://docs.fastlane.tools/actions/#increment_build_number
	desc "Update build number"
	private_lane :update_build_number do
		project = ENV["PROJECT"]
		buildNumber = sh("date '+%Y%m%d%H%M'")

		increment_build_number(
			xcodeproj: project,
			build_number: buildNumber
		)
	end

	# https://docs.fastlane.tools/actions/#cocoapods
	desc "Install cocoapods"
	private_lane :install_cocoapods do
		podFile = ENV["POD_FILE"]

		cocoapods(
			podfile: podFile
		)
	end

	# https://docs.fastlane.tools/actions/#testing
	desc "Runs all unit tests"
	private_lane :unit_tests do
		scan
	end

	# https://docs.fastlane.tools/actions/#match
	desc "Sync certificates and provisioning profiles"
	private_lane :sync_signing do
		match
	end

	desc "Disable automatic code signing"
	private_lane :disable_automatic_signing do
		project = ENV["PROJECT"]
		teamId = ENV["TEAM_ID"]

		disable_automatic_code_signing(
			path: project,
			team_id: teamId
		)
	end

	desc "Enable automatic code signing"
	private_lane :enable_automatic_signing do
		project = ENV["PROJECT"]
		teamId = ENV["TEAM_ID"]

		enable_automatic_code_signing(
			path: project,
			team_id: teamId
		)
	end

	# https://docs.fastlane.tools/actions/#produce
	desc "Generate a new App ID on the Developer Portal"
	private_lane :create_app_id do
		identifiers = ENV["APP_IDENTIFIERS"].split(",")
		names = ENV["APP_NAMES"].split(",")

		if names.count != 0 && identifiers.count != names.count
			raise ArgumentError, "The number of identifiers does not match the number of names"
		end

		identifiers.each_index do |index|
			produce(
				app_identifier: identifiers.at(index).strip,
				app_name: names.at(index).strip
			)
		end
	end

	# desc "Generate release notes"
	# private_lane :release_notes do
	# get_version_number
	# changelog = changelog_from_git_commits
	# version_number = lane_context[SharedValues::VERSION_NUMBER]
	# {}"Release notes #{version_number} Automatic build (Last 5 PR):\n#{changelog}"
	# end

	############################# PRE ###############################

	# This block is executed before every action of all platforms
	before_all do |lane|
		puts "Lane #{lane} started."
	end

	############################# POST ##############################

	# This block is called, only if the executed lane was successful
	after_all do |lane|
		puts "Lane #{lane} completed successfully."
	end

	error do |lane, _exception|
		puts "Lane #{lane} failed to complete.".red
	end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
#
# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`
#
# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# The bundle identifier of the app
app_identifier ENV["APP_IDENTIFIERS"]

# Shared Apple Developer Portal account
apple_id ENV["APPLE_ID"]

# Apple Developer Portal team
team_name ENV["TEAM_NAME"]

# Developer Portal Team ID
team_id ENV["TEAM_ID"]
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.49.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170223 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| io-console                | 0.4.6        |
| openssl                   | 2.0.2        |
</details>

*generated on:* **2017-07-27**
</details>

**Comment by tutipeti** [comment] 2017-07-31 12:41
@gtatgh how exactly are you executing the lane here, could you give me an example?

**Comment by gtatgh** [comment] 2017-07-31 13:17
@tutipeti There is no command I typed in. If I right understand [.env description](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Advanced.md#environment-variables) this works only with Fastfile. So I used `lane` for this:
`desc "Create a new App ID on the Developer Portal"`
`lane :setup do`
`create_app_id`
`sync_signing`
`end`
Copy from Fastfile, the whole file is added in question under `fastlane environment` ->`fastlane files` -> `Fastfile`

**Comment by gtatgh** [comment] 2017-07-31 13:23
If I use only `sigh` to create provisioning profile by following command, than right profile will be created.
`fastlane sigh --adhoc true --app_identifier 'com.company.app.iosproject' --username 'iOSDev@company.com' --team_id 'TEAM_ID' --cert_id 'CERT_ID' --platform 'ios'`

**Comment by tutipeti** [comment] 2017-07-31 13:25
@gtatgh well, you must have executed `fastlane` somehow, right? ;) So there was definitely a command that you typed in. Are the `.env` files in the same folder as the `Fastfile`?

**Comment by gtatgh** [comment] 2017-07-31 13:28
Sorry, I have not understand what you mean, so I typed `fastlane ios setup` to execute a lane. Yes, `.env` file is in the same folder as `Fastfile`.

**Comment by ohayon** [comment] 2017-07-31 18:33
Hey @gtatgh - could you try adding `require 'dotenv'; Dotenv.load` to the top of your Fastfile and see if that helps at all? 🐙 🚀

**Comment by ohayon** [comment] 2017-07-31 18:40
I am going to close this issue as a duplicate of https://github.com/fastlane/fastlane/issues/9865. If this is the wrong move, let me know and I am happy to reopen it! 😄 🚀

**Closed by ohayon** 2017-07-31 18:40 UTC

**Comment by gtatgh** [comment] 2017-08-01 07:12
Hi @ohayon, yes this is the duplicate. Thank you for closing it.

**Comment by gtatgh** [comment] 2017-08-01 07:13
Hi @ohayon, yes this is the duplicate. Thank you for closing it. Any news on #9865?
