### ISSUE TITLE
Deliver: Unable to activate activesupport-4.2.7.1, because json-2.0.2 conflicts with json (>= 1.7.7, ~> 1.7)

### ISSUE THREAD

**Issue by yakimant** [fastlane/fastlane#7629] opened 2016-12-21 18:50 UTC
```
⇒  deliver run --app_version 4.57.0 --skip_screenshots --capture_output
/Users/yakimant/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:2284:in `raise_if_conflicts': Unable to activate activesupport-4.2.7.1, because json-2.0.2 conflicts with json (>= 1.7.7, ~> 1.7) (Gem::ConflictError)
        from /Users/yakimant/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:1407:in `activate'
        from /Users/yakimant/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:1441:in `block in activate_dependencies'
        from /Users/yakimant/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:1427:in `each'
        from /Users/yakimant/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:1427:in `activate_dependencies'
        from /Users/yakimant/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:1409:in `activate'
        from /Users/yakimant/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:116:in `require'
        from /Users/yakimant/.rvm/gems/ruby-2.3.1/gems/deliver-2.0.1/lib/deliver/options.rb:1:in `<top (required)>'
        from /Users/yakimant/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from /Users/yakimant/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from /Users/yakimant/.rvm/gems/ruby-2.3.1/gems/deliver-2.0.1/lib/deliver.rb:3:in `<top (required)>'
        from /Users/yakimant/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from /Users/yakimant/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from /Users/yakimant/.rvm/gems/ruby-2.3.1/gems/deliver-2.0.1/bin/deliver:4:in `<top (required)>'
        from /Users/yakimant/.rvm/gems/ruby-2.3.1/bin/deliver:23:in `load'
        from /Users/yakimant/.rvm/gems/ruby-2.3.1/bin/deliver:23:in `<main>'
        from /Users/yakimant/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
        from /Users/yakimant/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by yakimant** [comment] 2016-12-21 19:00
Removed json-2.0.2 as a workaround.

**Comment by milch** [comment] 2016-12-21 21:08
Hi @yakimant, thanks for reporting this. Since you haven't included the output for `fastlane env` I can only guess that you've installed fastlane through rubygems.

Unfortunately rubygems doesn't resolve dependencies very well, so this error tends to happens a lot: https://github.com/fastlane/fastlane/issues?utf8=%E2%9C%93&q=Unable%20to%20activate

The easiest fix for this would be to install fastlane using our new `brew` installation method by running `brew cask install fastlane`. That will install a fully self-contained version of fastlane that is independent of your system environment, so it should always continue to work as intended 👍

**Comment by milch** [comment] 2016-12-21 21:08
I'll close this for now, feel free to let me know if this doesn't work for you and we need to reopen this.

**Closed by milch** 2016-12-21 21:08 UTC
