### ISSUE TITLE
Uploading ipa to TestFlight with --api_key results in error

### ISSUE THREAD

**Issue by SEGVeenstra** [fastlane/fastlane#17528] opened 2020-10-30 13:56 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm trying to deploy an ipa to testflight with the pilot command. But it results in an error.

##### Command executed
`
fastlane pilot upload  --ipa \"path_to_ipa\"  -g "group_name" --team_name "team_name" --changelog "features and fixes" --api_key "{\"key_id\": \"key_id\", \"issuer_id\": \"my_issuer_id\", \"key_filepath\": \"path_to_p8\"}"`

##### Complete output when running fastlane, including the stack trace and command used
```
Traceback (most recent call last):
	16: from /usr/local/bin/fastlane:23:in `<main>'
	15: from /usr/local/bin/fastlane:23:in `load'
	14: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.165.0/bin/fastlane:23:in `<top (required)>'
	13: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.165.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.165.0/pilot/lib/pilot/commands_generator.rb:18:in `start'
	11: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.165.0/pilot/lib/pilot/commands_generator.rb:166:in `run'
	10: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	 9: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.165.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	 8: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	 7: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 6: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.165.0/pilot/lib/pilot/commands_generator.rb:66:in `block (2 levels) in run'
	 4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.165.0/pilot/lib/pilot/build_manager.rb:17:in `upload'
	 3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.165.0/pilot/lib/pilot/manager.rb:16:in `start'
	 2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.165.0/pilot/lib/pilot/manager.rb:20:in `login'
	 1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.165.0/pilot/lib/pilot/manager.rb:33:in `api_token'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.165.0/spaceship/lib/spaceship/connect_api/token.rb:43:in `create': wrong number of arguments (given 1, expected 0) (ArgumentError)
	16: from /usr/local/bin/fastlane:23:in `<main>'
	15: from /usr/local/bin/fastlane:23:in `load'
	14: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.165.0/bin/fastlane:23:in `<top (required)>'
	13: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.165.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.165.0/pilot/lib/pilot/commands_generator.rb:18:in `start'
	11: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.165.0/pilot/lib/pilot/commands_generator.rb:166:in `run'
	10: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	 9: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.165.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	 8: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	 7: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 6: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.165.0/pilot/lib/pilot/commands_generator.rb:66:in `block (2 levels) in run'
	 4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.165.0/pilot/lib/pilot/build_manager.rb:17:in `upload'
	 3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.165.0/pilot/lib/pilot/manager.rb:16:in `start'
	 2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.165.0/pilot/lib/pilot/manager.rb:20:in `login'
	 1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.165.0/pilot/lib/pilot/manager.rb:33:in `api_token'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.165.0/spaceship/lib/spaceship/connect_api/token.rb:43:in `create': [!] wrong number of arguments (given 1, expected 0) (ArgumentError)
```

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> ### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.6                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.6 (19G2021)                                     |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.0.1                                                         |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.165.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| CFPropertyList            | 2.3.6        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.76.0       |
| faraday                   | 1.0.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.10.1       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.6        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.1        |
| googleauth                | 0.13.1       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.3        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-storage      | 1.28.0       |
| emoji_regex               | 3.0.0        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.364.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-sdk-core              | 3.105.0      |
| aws-sdk-kms               | 1.37.0       |
| aws-sdk-s3                | 1.79.1       |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.16.0       |
| bundler                   | 2.1.4        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>

*generated on:* **2020-10-30**</pre>
</details>

**Comment by mrchnk** [comment] 2020-10-30 19:30
You can try to use `--api_key_path` argument as a workaround

**Comment by SEGVeenstra** [comment] 2020-10-31 20:55
> You can try to use `--api_key_path` argument as a workaround

That means I have to put that json into a `.json` file right? Not just a path to the `.p8`?

**Comment by SEGVeenstra** [comment] 2020-11-04 09:31
> You can try to use `--api_key_path` argument as a workaround

Your suggestion worked. It's maybe even a more clean solution to what I was trying. Still weird that it didn't work though.

**Comment by rogerluan** [comment] 2020-11-09 03:20
IIRC we don't officially support `Hash` arguments via CLI. Any `Hash` arguments have to be passed via ruby or env vars. That may be the root cause of this bug 😬 

Link to 'a' docs page that shows this statement: https://docs.fastlane.tools/actions/clean_build_artifacts/#cli

Sorry for the inconvenience.

----

Since it looks like this issue has been resolved, I'm closing this issue 😊 thanks @mrchnk for the solution! 🚀

**Closed by rogerluan** 2020-11-09 03:20 UTC
Labels: tool: pilot, topic: ConnectAPI
