### ISSUE TITLE
Error "No provisioning profile provided" using Xcode 9

### ISSUE THREAD

**Issue by andreaspfurtscheller** [fastlane/fastlane#9939] opened 2017-08-03 00:08 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Since we are developing our project using Xcode 9 beta, codesigning for testflight won't work as it did when we were developing with Xcode 8.
 - using **match** + **gym**
 - Xcode's and fastlane's version are the only things that have changed.
 - I have looked at the threads on the issues #9782, #9909 and #9890, but in my case fastlane selects the expected profile, so I think it might be another issue.
 - Building and exporting using Xcode works flawlessly, so the project settings are ok, I guess.
 - I have also re-configured the code signing settings following the Xcode 9 upgrade guide.
 - Also the provisioning profiles and certificates are valid and installed according to match.
 
At that point I don't know how to fix this by myself, maybe you can help me with this.

### Captured Output

Command Used: `beta`
<details><summary>Output/Log</summary>

```

Successfully loaded Appfile at path '/Users/andreas/Documents/project/fastlane/Appfile'
- app_identifier: 'com.company.project'
- apple_id: '■■■■'
- team_id: '■■■■'
-------

+----------------+--------------------------------------+
|      Detected Values from './fastlane/Matchfile'      |
+----------------+--------------------------------------+
| git_url        | git@github.com:■■■■                  |
|                | /project-certificates.git            |
| app_identifier | ["com.company.project"]              |
| username       | ■■■■                                 |
+----------------+--------------------------------------+


+-----------------------+--------------------------------------+
|                   Summary for match 2.50.1                   |
+-----------------------+--------------------------------------+
| type                  | appstore                             |
| readonly              | true                                 |
| git_url               | git@github.com:■■■■                  |
|                       | /project-certificates.git            |
| app_identifier        | ["com.company.project"]              |
| username              | ■■■■                                 |
| git_branch            | master                               |
| keychain_name         | login.keychain                       |
| team_id               | ■■■■                                 |
| verbose               | false                                |
| force                 | false                                |
| skip_confirmation     | false                                |
| shallow_clone         | false                                |
| clone_branch_directly | false                                |
| force_for_new_devices | false                                |
| skip_docs             | false                                |
| platform              | ios                                  |
+-----------------------+--------------------------------------+


+-------------------+-----------------------------------------------+
|                       Installed Certificate                       |
+-------------------+-----------------------------------------------+
| User ID           | ■■■■                                          |
| Common Name       | iPhone Distribution: ■■■■ (■■■■)              |
| Organisation Unit | ■■■■                                          |
| Organisation      | ■■■■                                          |
| Country           | US                                            |
| Start Datetime    | Jun 21 18:28:42 2017 GMT                      |
| End Datetime      | Jun 21 18:28:42 2018 GMT                      |
+-------------------+-----------------------------------------------+


+---------------------+------------------------+------------------------+
|                    Installed Provisioning Profile                     |
+---------------------+------------------------+------------------------+
| Parameter           | Environment Variable   | Value                  |
+---------------------+------------------------+------------------------+
| App Identifier      |                        | com.company.project    |
| Type                |                        | appstore               |
| Platform            |                        | ios                    |
| Profile UUID        | sigh_com.company.proje | 9eea82fb-258e-4a48-92  |
|                     | ct_appstore            | c2-a0e0956f9dee        |
| Profile Name        | sigh_com.company.proje | match AppStore         |
|                     | ct_appstore_profile-na | ■■■■                   |
|                     | me                     |                        |
| Profile Path        | sigh_com.company.proje | /Users/andreas/Librar  |
|                     | ct_appstore_profile-pa | y/MobileDevice/Provis  |
|                     | th                     | ioning                 |
|                     |                        | Profiles/9eea82fb-258  |
|                     |                        | e-4a48-92c2-a0e0956f9  |
|                     |                        | dee.mobileprovision    |
| Development Team ID | sigh_com.company.proje | ■■■■                   |
|                     | ct_appstore_team-id    |                        |
+---------------------+------------------------+------------------------+


+--------------------------------------+--------------------------------------+
|                           Summary for gym 2.50.1                            |
+--------------------------------------+--------------------------------------+
| scheme                               | project                              |
| clean                                | true                                 |
| include_bitcode                      | false                                |
| export_method                        | app-store                            |
| export_options.provisioningProfiles  | match AppStore com.company.project   |
| .["com.company.project"]             |                                      |
| workspace                            | ./project.xcworkspace                |
| destination                          | generic/platform=iOS                 |
| output_name                          | project                              |
| build_path                           | /Users/andreas/Library/Developer/Xc  |
|                                      | ode/Archives/2017-08-03              |
| output_directory                     | .                                    |
| silent                               | false                                |
| skip_package_ipa                     | false                                |
| buildlog_path                        | ~/Library/Logs/gym                   |
| xcode_path                           | /Applications/Xcode-beta.app         |
+--------------------------------------+--------------------------------------+

+--------------------------------------+----------------------+
|                   Generated Build Command                   |
+--------------------------------------+----------------------+
| Option                               | Value                |
+--------------------------------------+----------------------+
| set -o pipefail &&                   |                      |
| xcodebuild                           |                      |
| -workspace ./project.xcworkspace     |                      |
| -scheme project                      |                      |
| -destination                         | generic/platform=iOS |
| -archivePath                         |                      |
| /Users/andreas/Library/Developer/Xc  |                      |
| ode/Archives/2017-08-03/project\     |                      |
| 2017-08-03\ 00.17.01.xcarchive       |                      |
| clean                                |                      |
| archive                              |                      |
| | tee                                |                      |
| /Users/andreas/Library/Logs/gym/pro  |                      |
| ject-project.log                     |                      |
| | xcpretty                           |                      |
+--------------------------------------+----------------------+
+--------------------------------------+--------------------------------------+
|                          Generated Package Command                          |
+--------------------------------------+--------------------------------------+
| Option                               | Value                                |
+--------------------------------------+--------------------------------------+
| /usr/bin/xcrun                       |                                      |
| /Users/andreas/.fastlane/bin/bundle  |                                      |
| /lib/ruby/gems/2.2.0/gems/fastlane-  |                                      |
| 2.50.1/gym/lib/assets/wrap_xcodebui  |                                      |
| ld/xcbuild-safe.sh -exportArchive    |                                      |
| -exportOptionsPlist                  | /var/folders/41/q1h7w56d4jx1_zlp678  |
|                                      | dq7140000gn/T/gym_config20170803-97  |
|                                      | 862-1nunyvz.plist                    |
| -archivePath                         |                                      |
| /Users/andreas/Library/Developer/Xc  |                                      |
| ode/Archives/2017-08-03/project\     |                                      |
| 2017-08-03\ 00.17.01.xcarchive       |                                      |
| -exportPath                          | /var/folders/41/q1h7w56d4jx1_zlp678  |
|                                      | dq7140000gn/T/gym_output20170803-97  |
|                                      | 862-1fj7zk                           |
+--------------------------------------+--------------------------------------+

Generated plist file with the following values:
▸ -----------------------------------------
▸ {
▸   "provisioningProfiles": {
▸     "[\"com.company.project\"]": "match AppStore com.company.project"
▸   },
▸   "method": "app-store",
▸   "uploadBitcode": false
▸ }
▸ -----------------------------------------
This results in the following plist file:
▸ -----------------------------------------
▸ <?xml version="1.0" encoding="UTF-8"?>
▸ <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
▸ <plist version="1.0">
▸ <dict>
▸ 	<key>method</key>
▸ 	<string>app-store</string>
▸ 	<key>provisioningProfiles</key>
▸ 	<dict>
▸ 		<key>["com.company.project"]</key>
▸ 		<string>match AppStore com.company.project</string>
▸ 	</dict>
▸ 	<key>uploadBitcode</key>
▸ 	<false/>
▸ </dict>
▸ </plist>
▸ -----------------------------------------

+ xcodebuild -exportArchive -exportOptionsPlist /var/folders/41/q1h7w56d4jx1_zlp678dq7140000gn/T/gym_config20170803-97862-1nunyvz.plist -archivePath '/Users/andreas/Library/Developer/Xcode/Archives/2017-08-03/project 2017-08-03 00.17.01.xcarchive' -exportPath /var/folders/41/q1h7w56d4jx1_zlp678dq7140000gn/T/gym_output20170803-97862-1fj7zk
2017-08-03 00:18:38.642 xcodebuild[708:1175359] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/41/q1h7w56d4jx1_zlp678dq7140000gn/T/project_2017-08-03_00-18-38.641.xcdistributionlogs'.
2017-08-03 00:18:40.636 xcodebuild[708:1175359] [MT] IDEDistribution: Step failed: <IDEDistributionSigningAssetsStep: 0x7fab7b2bc4d0>: Error Domain=IDEDistributionSigningAssetStepErrorDomain Code=0 "Locating signing assets failed." UserInfo={NSLocalizedDescription=Locating signing assets failed., IDEDistributionSigningAssetStepUnderlyingErrors=(
"Error Domain=IDEProvisioningErrorDomain Code=9 \"\"project.app\" requires a provisioning profile.\" UserInfo={NSLocalizedDescription=\"project.app\" requires a provisioning profile., NSLocalizedRecoverySuggestion=Select a provisioning profile for the \"Default\" build configuration in the project editor.}"
)}
error: exportArchive: "project.app" requires a provisioning profile.

Error Domain=IDEProvisioningErrorDomain Code=9 ""project.app" requires a provisioning profile." UserInfo={NSLocalizedDescription="project.app" requires a provisioning profile., NSLocalizedRecoverySuggestion=Select a provisioning profile for the "Default" build configuration in the project editor.}

** EXPORT FAILED **

Exit status: 70
No provisioning profile provided
Make sure to pass a valid provisioning for each required target
Check out the docs on how to fix this: https://github.com/fastlane/fastlane/tree/master/gym#export-options

⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
📋  For the complete and more detailed error log, check the full log at:
📋  /Users/andreas/Library/Logs/gym/project-project.log

Looks like fastlane ran into a build/archive error with your project It's hard
to tell what's causing the error, so we wrote some guides on how to troubleshoot
build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
Before submitting an issue on GitHub, please follow the guide above and make sure your project is set up correctly.
fastlane uses `xcodebuild` commands to generate your binary, you can see the the full commands printed out in yellow in the above log.
Make sure to inspect the output above, as usually you'll find more error information there

Lane Context:
{:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta", :SIGH_PROFILE_TYPE=>"app-store", :MATCH_PROVISIONING_PROFILE_MAPPING=>{["com.company.project"]=>"match AppStore com.company.project"}}


+---------------+------------------------------+
|              Build environment               |
+---------------+------------------------------+
| xcode_path    | /Applications/Xcode-beta.app |
| gym_version   | 2.50.1                       |
| export_method | app-store                    |
| sdk           | iPhoneOS11.0.sdk             |
+---------------+------------------------------+


+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | Verifying required  | 0           |
|      | fastlane version    |             |
| 2    | default_platform    | 0           |
| 3    | xcversion           | 0           |
| 4    | match               | 2           |
| 💥   | gym                 | 102         |
+------+---------------------+-------------+



```

</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version '2.49.0'

default_platform :ios

platform :ios do
    before_all do
        xcversion(version: '9.0')
    end

    desc 'Submit a new beta build to Apple TestFlight'
    lane :beta do
        ensure_git_status_clean

        # Codesigning
        match(
            type: 'appstore',
            readonly: true
        )

        # Install cocoapods dependencies
        cocoapods

        gym(
            scheme: 'project',
            clean: true,
            include_bitcode: true,
            export_method: 'app-store'
        )

        # Deliver to TestFlight
        pilot(skip_waiting_for_build_processing: true)
    end

    desc 'Install all certificates on your machine'
    lane :certificates do
        # Install certificates
        match(type: 'development', readonly: true)
        match(type: 'appstore', readonly: true)
    end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "■■■■"   # The bundle identifier of your app
apple_id "■■■■"         # Your Apple email address

team_id "■■■■"          # Developer Portal Team ID
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.50.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2017-08-01**
</details>

**Comment by ohayon** [comment] 2017-08-03 14:47
Hey @andreaspfurtscheller! Apologies for the issues you are having. We are definitely still very much in a situation where not everything is quite working as we would like for Xcode 9. That being said, we definitely want to help out with the issue you are seeing. I have a feeling that it has something to do with `xcodebuild`. Looking at your `fastlane env` it looks like your Xcode Path is set to `/Applciations/Xcode.app` is that pointing to a version of Xcode 8? I know on my machine, that path is an 8.x version and `/Applications/Xcode-beta.app` points to my 9 beta version. Could you try running `sudo xcode-select -s /path/to/your/Xcode 9/beta/app` and then retry your fastlane command? 🚀  🐙

**Comment by drougojrom** [comment] 2017-08-03 15:37
I have the same issue with the same error, but my Xcode version in fastlane environment is Xcode 9.0

**Comment by genadyo** [comment] 2017-08-03 16:16
same issue here too with env of Xcode 9

**Comment by ohayon** [comment] 2017-08-03 16:23
@drougojrom and @genadyo, could you please share the output of `fastlane env` so that we can have as much info as possible about the issue? Thanks!! 😄

**Comment by ohayon** [comment] 2017-08-03 16:23
@drougojrom and @genadyo, could you please share the output of `fastlane env` so that we can have as much info as possible about the issue? Thanks!! 😄

**Comment by genadyo** [comment] 2017-08-03 16:25
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.12.6                                          |
| Ruby                        | 2.4.0                                            |
| Bundler?                    | false                                            |
| Git                         | git version 2.13.3                               |
| Installation Source         | ~/.rvm/gems/ruby-2.4.0/bin/fastlane              |
| Host                        | Mac OS X 10.12.6 (16G29)                         |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.0/lib                     |
| OpenSSL Version             | OpenSSL 1.1.0f  25 May 2017                      |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode-beta.app/Contents/Developer/ |
| Xcode Version               | 9.0                                              |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.50.1  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.2        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.15.3       |
| io-console                | 0.4.6        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.58.0       |
| faraday                   | 0.12.2       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| faraday_middleware        | 0.12.0       |
| json                      | 2.1.0        |
| openssl                   | 2.0.4        |
</details>


*generated on:* **2017-08-03**
</details>

**Comment by andreaspfurtscheller** [comment] 2017-08-03 19:30
Hey @ohayon, sorry, that was my old fastlane env output. Xcode version is already 9.0-beta4.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.12.5                                          |
| Ruby                        | 2.2.4                                            |
| Bundler?                    | false                                            |
| Git                         | git version 2.13.2 (Apple Git-90)                |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane              |
| Host                        | Mac OS X 10.12.5 (16F73)                         |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                       |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                       |
| Is contained                | false                                            |
| Is homebrew                 | true                                             |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode-beta.app/Contents/Developer/ |
| Xcode Version               | 9.0                                              |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version '2.49.0'

default_platform :ios

platform :ios do
    before_all do
        xcversion(version: '9.0')
    end

    lane :beta do
        ensure_git_status_clean

        # Codesigning
        match(
            type: 'appstore',
            readonly: true
        )
        
        cocoapods

        gym(
            scheme: '■■■■',
            clean: true,
            include_bitcode: true,
            export_method: 'app-store'
        )

        # Deliver to TestFlight
        pilot(skip_waiting_for_build_processing: true)
    end
    
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.company.project"    # The bundle identifier of your app
apple_id "■■■■"                         # Your Apple email address

team_id "■■■■"                          # Developer Portal Team ID
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.50.1  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| CFPropertyList            | 2.3.5        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
</details>


*generated on:* **2017-08-03**
</details>

**Comment by andreaspfurtscheller** [comment] 2017-08-08 14:39
Ok, it seems to have something to do with the exportOptionsPlist, which looks like the following:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>method</key>
        <string>app-store</string>
        <key>provisioningProfiles</key>
        <dict>
                <key>[&quot;com.company.project&quot;]</key>
                <string>match AppStore com.company.project</string>
        </dict>
        <key>uploadBitcode</key>
        <true/>
</dict>
</plist>
```

but when changing the provisioningProfile's key by removing the array brackets...
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>method</key>
        <string>app-store</string>
        <key>provisioningProfiles</key>
        <dict>
                <key>com.company.project</key>
                <string>match AppStore com.company.project</string>
        </dict>
        <key>uploadBitcode</key>
        <true/>
</dict>
</plist>
```

... the command just works fine:
```
/usr/bin/xcrun /Users/andreas/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.51.0/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/41/q1h7w56d4jx1_zlp678dq7140000gn/T/gym_config20170808-41057-isy0nv.plist' -archivePath /Users/andreas/Library/Developer/Xcode/Archives/2017-08-08/project\ 2017-08-08\ 13.58.27.xcarchive -exportPath '/var/folders/41/q1h7w56d4jx1_zlp678dq7140000gn/T/gym_output20170808-41057-15can8'
```

```
** EXPORT SUCCEEDED **
```

so, i don't know if this is a real fix, or just a workaround, just wanted to share this find with you.

**Comment by KrauseFx** [comment] 2017-08-08 19:05
Ahh, nice, thanks for the report. This shouldn't be an array, taking a look at where this might come from

**Comment by KrauseFx** [comment] 2017-08-09 22:48
Thanks, I can reproduce now, taking a closer look 👍

**Comment by KrauseFx** [comment] 2017-08-09 23:02
I just pushed https://github.com/fastlane/fastlane/pull/10020, this will be in the next release 🚀

**Comment by andreaspfurtscheller** [comment] 2017-08-10 08:59
That's great, glad that I could help! Quite leiwand :)

**Closed** 2017-08-10 15:12 UTC

**Comment by KrauseFx** [comment] 2017-08-10 15:32
Ah, so viele Österreicher hier unterwegs ❤️
