### ISSUE TITLE
sigh fails with Your session has expired.  Please log in.

### ISSUE THREAD

**Issue by deanrock** [fastlane/fastlane#5386] opened 2016-07-14 10:29 UTC
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I have the issue with sigh with Apple ID which has access to a few developer accounts, but none of them is enterprise (so it's not related to https://github.com/fastlane/fastlane/issues/5384).

sigh works without a problem on another Apple ID which has access to the same developer accounts.

##### Complete output when running fastlane, including the stack trace and command used

```
/Users/dean/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/user_interaction.rb:334: warning: constant ::TimeoutError is deprecated

+-------------------------------------+-----------------------------+
|                      Summary for sigh 1.8.0                       |
+-------------------------------------+-----------------------------+
| username                            | <USERNAME>                  |
| adhoc                               | false                       |
| skip_install                        | false                       |
| development                         | false                       |
| force                               | false                       |
| ignore_profiles_with_different_name | false                       |
| skip_fetch_profiles                 | false                       |
| skip_certificate_verification       | false                       |
+-------------------------------------+-----------------------------+

INFO [2016-07-14 12:24:41.51]: Starting login with user '<USERNAME>'

Looking for related GitHub issues on fastlane/fastlane...
Search query: Apple provided the following error info:
	authentication.failed
	Your session has expired.  Please log in.

URL: https://api.github.com/search/issues?q=Apple%20provided%20the%20following%20error%20info:%0A%09authentication.failed%0A%09Your%20session%20has%20expired.%20%20Please%20log%20in.+repo:fastlane/fastlane
➡️  Enterprise Account - produce login failed return Your session has expired.  Please log in.
   https://github.com/fastlane/fastlane/issues/5384 [open] 9 💬
   10 minutes ago

➡️  Sigh: authentication.failed Your session has expired.  Please log in.
   https://github.com/fastlane/fastlane/issues/4981 [closed] 3 💬
   6 weeks ago

➡️  sigh: authentication.failed / Your session has expired.  Please log in.
   https://github.com/fastlane/fastlane/issues/4157 [closed] 16 💬
   2 weeks ago

and 10 more at: https://github.com/fastlane/fastlane/search?q=Apple%20provided%20the%20following%20error%20info:%0A%09authentication.failed%0A%09Your%20session%20has%20expired.%20%20Please%20log%20in.&type=Issues&utf8=✓
/Users/dean/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spaceship-0.28.0/lib/spaceship/client.rb:434:in `parse_response': [!] Apple provided the following error info: (Spaceship::Client::UnexpectedResponse)
	authentication.failed
	Your session has expired.  Please log in.
	from /Users/dean/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spaceship-0.28.0/lib/spaceship/portal/portal_client.rb:52:in `teams'
	from /Users/dean/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spaceship-0.28.0/lib/spaceship/portal/ui/select_team.rb:35:in `select_team'
	from /Users/dean/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spaceship-0.28.0/lib/spaceship/portal/portal_client.rb:73:in `select_team'
	from /Users/dean/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spaceship-0.28.0/lib/spaceship/portal/spaceship.rb:37:in `select_team'
	from /Users/dean/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spaceship-0.28.0/lib/spaceship/portal/spaceship.rb:81:in `select_team'
	from /Users/dean/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sigh-1.8.0/lib/sigh/runner.rb:16:in `run'
	from /Users/dean/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sigh-1.8.0/lib/sigh/manager.rb:7:in `start'
	from /Users/dean/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sigh-1.8.0/bin/sigh:35:in `block (2 levels) in run'
	from /Users/dean/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/dean/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/dean/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/dean/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane_core-0.48.1/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Users/dean/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/dean/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sigh-1.8.0/bin/sigh:99:in `run'
	from /Users/dean/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sigh-1.8.0/bin/sigh:117:in `<top (required)>'
	from /Users/dean/.rbenv/versions/2.3.0/bin/sigh:23:in `load'
	from /Users/dean/.rbenv/versions/2.3.0/bin/sigh:23:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
I'm using sigh directly, without fastlane.
```

### Environment

fastlane version (run `fastlane -v`): fastlane 1.97.2

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? It fails on machine where I'm using rbenv, and on another one which doesn't have any environment manager installed.

**Comment by weibel** [comment] 2016-07-14 14:47
We have the same problem using Match
Apples system status is all green https://www.apple.com/support/systemstatus/

Match emits the following
`{"responseId"=>"e96c087f-2bf3-472b-af13-0df9d25a4c21", "resultCode"=>1100, "resultString"=>"authentication.failed", "userString"=>"Your session has expired.  Please log in.", "creationTimestamp"=>"2016-07-14T14:39:35Z", "protocolVersion"=>"QH65B2", "userLocale"=>"en_US", "requestUrl"=>"https://developerservices2.apple.com/services/QH65B2/listTeams.action", "httpCode"=>200}`

**Comment by pkitomtaylz** [comment] 2016-07-14 17:04
I'm having the same issue as above, I tried deleting the password from keychain and re-authenticating but I get the session expired message.

**Comment by gabek** [comment] 2016-07-14 17:25
Same here with Match.

**Comment by deanrock** [comment] 2016-07-14 19:23
I found a solution. Adding this user to iTunes Connect (doesn't matter to which team) solves the problem.

After debugging HTTP requests made from the `spaceship` gem, it seems that it successfully retrieves `myacinfo` cookie, but the cookie gets cleared on subsequent requests.

It seems to fail when requesting https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa with `myacinfo` cookie, but getting 302 redirect to https://itunesconnect.apple.com/itc/static/login?appIdKey=***snip***&view=1&path=%2FWebObjects%2FiTunesConnect.woa%3F&errorKey=ITC.signin.error.invalidUser.

**Comment by sfransen** [comment] 2016-07-14 20:36
adding the user to itunesconnect solved my problem I no longer this the login expired problem on my account

**Comment by arunks** [comment] 2016-07-14 21:25
Adding the user to iTC worked. I added the user with a sales role in iTC, not necessarily an admin.

**Comment by adomanico** [comment] 2016-07-14 21:38
Also seeing this

**Comment by TechGuyVN** [comment] 2016-07-15 01:26
@arunks  @sfransen @deanrock  i use Enterprise account, can you guide step to step to add user to ITC ? cause i can find it anywhere in my enterprise account :(

**Comment by inturbidus** [comment] 2016-07-15 14:00
Adding a user to iTunes connect worked for me as well.

**Comment by brockboland** [comment] 2016-07-15 16:03
Same here. I didn't even add it to the same organization: I have a developer account with a client, and for corporate policy reasons, they can't give me access to iTunes Connect. I invited the Apple ID used for the developer account to my own company's iTunes Connect, and that did the trick.

**Comment by oba2cat3** [comment] 2016-07-16 00:53
yup - adding the user to itunes connect solved it for me as well.

**Comment by stulevine** [comment] 2016-07-18 20:44
Well, what if it's an enterprise appleID?  Can't really enable iTunes connect for that one since it's not used for the App Store, just to build app for internal distribution and testing via the enterprise cert?  Anyone have this same issue with an enterprise apple id?

**Comment by shabeepk** [comment] 2016-07-19 10:40
@stulevine
We've got the same issue with enterprise builds...

**Comment by mcactive** [comment] 2016-07-19 11:33
Have the same issue with the enterprise account... As soon as you try to login to itunes connect with an enterprise account; your session is expired.

**Comment by mr-casual** [comment] 2016-07-19 11:44
@stulevine 
yeah.. the same here...

**Comment by TKBurner** [comment] 2016-07-19 14:16
@mcactive @mr-casual @stulevine What exact error do you get? Have you tried logging in at appleid.apple.com? Thanks!

**Comment by nmcdonaldd** [comment] 2016-07-19 22:22
Getting the same error for account added as developer to an Enterprise account. Can log into appleid.apple.com just fine, however.

**Comment by tychop** [comment] 2016-07-20 08:22
Same problem here. We have an enterprise account, and I had to add the enterprise user to my personal iTunesConnect (completely unrelated to the enterprise).
It works now....

**Comment by shabeepk** [comment] 2016-07-20 12:10
@tychop 

That's not an option in our case unfortunately ...

**Comment by medslt** [comment] 2016-07-20 12:40
@stulevine 
 We've got the same issue with enterprise builds... Did you solve it?

**Comment by FrantisekGazo** [comment] 2016-07-20 13:07
adding to iTunes is not an option

**Comment by kpenfound** [comment] 2016-07-20 20:54
+1

**Comment by toume** [comment] 2016-07-21 09:27
+1

**Comment by kpenfound** [comment] 2016-07-21 19:21
@TKBurner I have the exact same error as @FrantisekGazo .  I've logged into appleid.apple.com and everything appears to be normal.  I wasn't prompted to update security questions or anything as mentioned in other threads.

As @stulevine also mentioned, adding the account to iTC isn't an option here

**Comment by KaiJSchaefer** [comment] 2016-07-22 12:14
Same problem here. Any solution?

**Comment by tychop** [comment] 2016-07-22 12:29
Just curious.... Why is adding the account to an iTC not an option?

**Comment by TKBurner** [comment] 2016-07-22 13:33
@kpenfound @KaiJSchaefer If you aren't using enterprise distribution, why is iTC not an option?

Thanks!

**Comment by kpenfound** [comment] 2016-07-22 14:20
@TKBurner 
We have mixed accounts, some enterprise, some aren't.  None of them currently have iTC access.

It seems strange to me that issues are being closed in favor of this workaround.  Is this caused by an authentication change on Apple's end that can't be avoided?

**Comment by TKBurner** [comment] 2016-07-22 14:27
@kpenfound Thanks for following up. Were you able to previously use Sigh without an iTC account attached? As far as I know it's always been a requirement. Thanks!

**Comment by mengxia1966** [comment] 2016-07-22 15:44
@TKBurner  I have a same issue with cert for enterprise account.
I think enterprise account doesn't need an ITC account, so adding ITC is not an option.
I gets following output, when I enter cert --verbose

cert --verbose

+---------------+-----------------------------------------------------+
|                       Summary for cert 1.4.1                        |
+---------------+-----------------------------------------------------+
| development   | false                                               |
| force         | false                                               |
| username      | xxx@xxx                               |
| keychain_path | /Users/xxx/Library/Keychains/login.keychain |
+---------------+-----------------------------------------------------+

INFO [2016-07-22 23:30:33.45]: Starting login with user 'xxx@xxx'
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:427:in `parse_response': [!] Apple provided the following error info: (Spaceship::Client::UnexpectedResponse)
	authentication.failed
	Your session has expired.  Please log in.
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/portal/portal_client.rb:51:in `teams'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/portal/ui/select_team.rb:35:in `select_team'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/portal/portal_client.rb:67:in `select_team'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/portal/spaceship.rb:37:in `select_team'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/portal/spaceship.rb:81:in `select_team'
	from /Library/Ruby/Gems/2.0.0/gems/cert-1.4.1/lib/cert/runner.rb:18:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/cert-1.4.1/lib/cert/runner.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/cert-1.4.1/lib/cert/runner.rb:6:in `launch'
	from /Library/Ruby/Gems/2.0.0/gems/cert-1.4.1/bin/cert:33:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.42.1/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/cert-1.4.1/bin/cert:49:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/cert-1.4.1/bin/cert:55:in `<top (required)>'
	from /usr/local/bin/cert:23:in `load'
	from /usr/local/bin/cert:23:in `<main>'

This is the line I am getting error in portal_client.rb.
req = request(:post, "https://developerservices2.apple.com/services/QH65B2/listTeams.action")

I am not sure why cert gives me this error. Any solution?

**Comment by kpenfound** [comment] 2016-07-22 15:55
@TKBurner Looks like the account I was previously testing with is indeed in iTC, I only ran into this issue when I started testing the process with multiple accounts.  

I'm really just trying to pull provisioning profiles through Spaceship, however I get this same error through Spaceship or Sigh.  As @mengxia1966 also asks, why are Portal requests failing if the account isn't linked to iTC?  I don't see a reason that could be a requirement

**Comment by TKBurner** [comment] 2016-07-22 16:58
@kpenfound Thanks for following up. Can you share the output from spaceship? Because we are using the  APIs provided by Apple some of the access control is beyond our control. Thanks for working with us.

**Comment by kpenfound** [comment] 2016-07-22 17:42
@TKBurner My assumption was that the developer portal and iTC had independent authentications since they are separate services.  The workflow in spaceship/bin/spaceship for authentication reinforced that assumption.

The output from Spacehip is:

`/Library/Ruby/Gems/2.0.0/gems/spaceship-0.28.0/lib/spaceship/client.rb:434:in `parse_response': {"responseId"=>"a2fe6379-428e-4de4-babb-f94ca8a32c56", "resultCode"=>1100, "resultString"=>"authentication.failed", "userString"=>"Your session has expired.  Please log in.", "creationTimestamp"=>"2016-07-22T17:39:38Z", "protocolVersion"=>"QH65B2", "userLocale"=>"en_US", "requestUrl"=>"https://developerservices2.apple.com/services/QH65B2/listTeams.action", "httpCode"=>200} (Spaceship::Client::UnexpectedResponse)
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.28.0/lib/spaceship/portal/portal_client.rb:52:in `teams'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.28.0/lib/spaceship/portal/portal_client.rb:64:in `team_id'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.28.0/lib/spaceship/portal/portal_client.rb:326:in `block in provisioning_profiles'`

**Comment by FrantisekGazo** [comment] 2016-07-23 06:54
@TKBurner I have account without iTC and I was using it with fastlane (sigh included) without any problem for couple weeks, but when I tried to build the same thing this week it didn't work.

**Comment by onmyway133** [comment] 2016-07-25 10:15
I have problem with `sigh` too, fastlane 1.98.0

```
[!] Exit status of command 'terminal-notifier -message "{"responseId"=>"8bfe58f3-c841-4dc1-b34f-7143b643f861", "resultCode"=>1100, "resultString"=>"authentication.failed", "userString"=>"Your session has expired.  Please log in.", "creationTimestamp"=>"2016-07-25T10:06:55Z", "protocolVersion"=>"QH65B2", "userLocale"=>"en_US", "requestUrl"=>"https://developerservices2.apple.com/services/QB65B2/listTeams.action", "httpCode"=>200}"' was 1 instead of 0.
```

**Comment by elianfish** [comment] 2016-07-26 07:24
I have problem with pem too.

Looking for related GitHub issues on fastlane/fastlane...

➡️  sigh fails with Your session has expired.  Please log in.
   https://github.com/fastlane/fastlane/issues/5386 [open] 34 💬
   21 hours ago

➡️  Sigh: authentication.failed Your session has expired.  Please log in.
   https://github.com/fastlane/fastlane/issues/4981 [closed] 3 💬
   03 Jun 2016

➡️  sigh: authentication.failed / Your session has expired.  Please log in.
   https://github.com/fastlane/fastlane/issues/4157 [closed] 16 💬
   4 weeks ago

and 11 more at: https://github.com/fastlane/fastlane/search?q=Apple%20provided%20the%20following%20error%20info:%0A%09authentication.failed%0A%09Your%20session%20has%20expired.%20%20Please%20log%20in.&type=Issues&utf8=✓

[!] Apple provided the following error info:
	authentication.failed
	Your session has expired.  Please log in.

**Comment by stulevine** [comment] 2016-07-26 17:05
has anyone found a solution for this for enterprise customers?  My CI environment is dead in the water and I'd really like to put it back into action.  unfortunately this is a huge blocker.  I've had to resort to manual archiving and uploading to Crashlytics.

**Comment by argie9999** [comment] 2016-07-26 17:23
+1. I'm currently looking through the other issues on this topic and nothing has worked for me. I have an Enterprise account. The only user is also a user in iTC. I can log in manually. I check the 'system status' page and it loads but doesn't show anything (just a blank table with no labels or values, so not sure what I should expect to see...).

**Comment by inturbidus** [comment] 2016-07-26 21:11
I have an enterprise account, and what worked for me is taking the email address associated with my enterprise account and adding it to iTunes under another team with ITunes access.  Obviously enterprise accounts don't need access, so you have to add the email address as a user under another team.

**Comment by lkraider** [comment] 2016-07-27 19:31
Same here, `sigh` was working fine with a user without iTC access before, updated today and now it fails to authenticate.

**Comment by TKBurner** [comment] 2016-07-27 20:28
Hi all! I've circled back with the core team. Also marking this help wanted in case anyone from the community wants to look into it. Hope you have a great day!

**Comment by kpenfound** [comment] 2016-07-27 20:30
Thanks @TKBurner

**Comment by asfalcone** [comment] 2016-07-28 15:56
Thanks all for the reports and sorry that this is causing issues for so many of you. We're hoping to get to the bottom of this.

Has anyone been able to go back to an older version of fastlane and spaceship (something before spaceship 0.28.0) and have their existing setup (without the workaround) able to login? I'm trying to triage this as a regression in our code or a change on the apple side that we need to investigate.

Let me know!

**Comment by asfalcone** [comment] 2016-07-29 18:23
I think I have a fix for this issue. If you have a moment, please pull the code in [this PR](https://github.com/fastlane/fastlane/pull/5548) and `rake install` in the spaceship directory to test. Let me know if this fixes the issue for you! 👍

**Closed** 2016-07-30 22:27 UTC
Labels: bug, help wanted, sigh

**Comment by KrauseFx** [comment] 2016-07-31 07:37
Hey everyone, @asfalcone and me did some more testing and we were able to reproduce the issue. We already pushed a new spaceship release: https://github.com/fastlane/fastlane/releases/tag/spaceship/0.29.1

Please update using `[sudo] gem update spaceship` or `bundle update` (if you use a `Gemfile`)

Please let us know if that fixes the problem 👍

**Comment by argie9999** [comment] 2016-08-01 15:09
This appears to be working for me!  Thanks so much @asfalcone, @KrauseFx!  Fastlane is awesome. thanks for the quick resolution of this issue.

**Comment by xareelee** [comment] 2016-08-03 07:01
How do I know the version of `spaceship` running on my Mac? I've tried `spaceship --version` which doesn't work.

**Comment by KrauseFx** [comment] 2016-08-03 07:12
@xareelee you have to run `gem list --local | grep "spaceship"` or if you use `bundler`, you can just look inside your `Gemfile.lock`

**Comment by onmyway133** [comment] 2016-08-03 07:24
@KrauseFx oh great, but how about `sigh`?

**Comment by KrauseFx** [comment] 2016-08-03 07:30
@onmyway133 This should be fixed for all tools, as long are you update `spaceship`, using `[sudo] gem update spaceship` or `bundle update` (if you use bundler).
With the next release of each tool, the dependency to spaceship is also updated, so every user will get the new version 👍 but in the mean-time, please update manually using the instructions above.

**Comment by onmyway133** [comment] 2016-08-03 13:55
@KrauseFx 🎉 . Just wonder what is the issue? And why does adding account to iTC manually fixes the problem?

**Comment by TKBurner** [comment] 2016-08-12 16:46
@onmyway133 I think this was related to a new security measure on the Apple APIs. Thanks!

**Comment by yishuiliunian** [comment] 2016-08-14 06:19
The have the problem too

Spaceship::Client::UnexpectedResponse: {"responseId"=>"07b7a31e-9673-4457-8e04-625c1c64bd82", "resultCode"=>1100, "resultString"=>"authentication.failed", "userString"=>"Your session has expired.  Please log in.", "creationTimestamp"=>"2016-08-14T06:13:25Z", "protocolVersion"=>"QH65B2", "userLocale"=>"en_US", "requestUrl"=>"https://developerservices2.apple.com/services/QH65B2/listTeams.action", "httpCode"=>200}
from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.31.1/lib/spaceship/client.rb:433:in `parse_response'

**Comment by TKBurner** [comment] 2016-08-22 18:21
Hi @yishuiliunian Thanks for following up on this. Can you let me know if you are still running into this issue if you run `sudo gem update fastlane`?
