### ISSUE TITLE
How to avoid 2FA Login using app-specific passwords

### ISSUE THREAD

**Issue by nyoung-figly** [fastlane/fastlane#14617] opened 2019-04-17 21:12 UTC
### Question Checklist

- [x] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
uploading builds using app-specific password but avoiding 2FA

#### Question Description
🔑 Hi! We've been using fastlane for a long time to build and upload our iOS app from CircleCI to TestFlight, but are now struggling with short 2FA session timeouts and looking for a longer-term solution.

We started out using the docs at https://docs.fastlane.tools/best-practices/continuous-integration/#two-step-or-two-factor-auth and got an automated process working by using FASTLANE_SESSION. As mentioned in a lot of other places, that expires pretty frequently, which kind of destroys the goal of an automated workflow.

The docs suggest that setting FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD is all that is required to upload our app to TestFlight, and we were hoping that meant that fastlane wouldn't try to log in, but that doesn't seem to be the case.

Running the `ios beta` lane fails during the `upload_to_testflight` step (Fastfile included below) as it prompts for the 6-digit verification code during unattended automated builds.

Is there a way to upload a build to TestFlight without being prompted for a 2FA code?

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                  |
| --------------------------- | ------------------------------------------------------ |
| OS                          | 10.13.6                                                |
| Ruby                        | 2.5.3                                                  |
| Bundler?                    | true                                                   |
| Git                         | git version 2.19.1                                     |
| Installation Source         | ~/project/runtime/vendor/cache/ruby/2.5.0/bin/fastlane |
| Host                        | Mac OS X 10.13.6 (17G3025)                             |
| Ruby Lib Dir                | ~/.rubies/ruby-2.5.3/lib                               |
| OpenSSL Version             | OpenSSL 1.0.2p  14 Aug 2018                            |
| Is contained                | false                                                  |
| Is homebrew                 | false                                                  |
| Is installed via Fabric.app | false                                                  |
| Xcode Path                  | /Applications/Xcode-10.1.app/Contents/Developer/       |
| Xcode Version               | 10.1                                                   |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.108.0"

default_platform :ios
xcode_select "/Applications/Xcode-10.1.app"

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
     setup_circle_ci
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    match(type: "appstore", readonly: true) # more information: https://codesigning.guide

    increment_build_number(
      build_number: ENV["REMIX_BUILD_NUMBER"].to_i,
      xcodeproj: "turntable/ios/Turntable.xcodeproj"
    )
    gym
    upload_to_testflight(
      beta_app_description: "Who in the world am I? Ah, that's the great puzzle.",
      skip_submission: true,
      skip_waiting_for_build_processing: true
    )
  end

  desc "Submit a new custom Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :birdshot do
    match(type: "appstore", app_identifier: "io.remixlabs.turntable.*", readonly: true) # more information: https://codesigning.guide

    increment_build_number(
      build_number: ENV["REMIX_BUILD_NUMBER"].to_i,
      xcodeproj: "turntable/ios/Turntable.xcodeproj"
    )
    gym(xcargs: "PROVISIONING_PROFILE_SPECIFIER='match AppStore io.remixlabs.turntable.*'",
        export_options: {
          provisioningProfiles: {
	    # bin/set-custom-app-settings plugs in the non-wildcard bundle_id here
            "$BUNDLE_ID$" => "match AppStore io.remixlabs.turntable.*"
          }
    })
    upload_to_testflight(
      changelog: ENV["REMIX_RELEASE_NOTES"],
      beta_app_description: "Who in the world am I? Ah, that's the great puzzle.",
      skip_waiting_for_build_processing: true
    )

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    match(type: "appstore", readonly: true)
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  desc "Register new device"
  lane :register_new_device do  |options|
    device_name = prompt(text: "Enter the device name: ")
    device_udid = prompt(text: "Enter the device UDID: ")
    device_hash = {}
    device_hash[device_name] = device_udid
    register_devices(
      devices: device_hash
    )
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://github.com/fastlane/fastlane#metrics

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier ENV["bundle_id"] # The bundle identifier of your app

team_id "Z82SA9YU75" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.120.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| bundler                   | 2.0.1        |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.7.2        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.64.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.0        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.2.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.5.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.1        |
| tty-spinner               | 0.9.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2019-04-17**
</details>

**Comment by mgrebenets** [comment] 2019-04-17 22:27
Hi @nyoung-figly 
This looks like a duplicate of https://github.com/fastlane/fastlane/issues/14301

In a nutshell, for your use case, if you provide `apple_id` and set `skip_waiting_for_build_processing` then there's no need to 2FA. The PR to implement the change is here: https://github.com/fastlane/fastlane/pull/14456

Until that change is merged, it's possible to use a longer-living (30 days) session token to keep the fastlane session going for more on CI. This is the change for that: https://github.com/fastlane/fastlane/pull/14525

As a workaround I've been copying whole content of `~/.fastlane/.fastlane/spaceship/<my-apple-id>/cookie` and then replacing all newlines with `\n` and use that as `FASTLANE_SESSION`.

**Closed by mgrebenets** 2019-04-17 22:27 UTC
