### ISSUE TITLE
Scan Fails, but tests pass.  method_missing ?

### ISSUE THREAD

**Issue by MaximusMcCann** [fastlane/fastlane#7987] opened 2017-01-25 04:10 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

All unit tests are passing, but weird errors come out of Scan, and the build fails. :(

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you
```
All tests
Test Suite a-unit-tests.xctest started
LoginRequestTests
✓ testParsingAToken (0.007 seconds)
NavigatorTests
✓ testNavigatingHome (0.150 seconds)
✓ testNavigatingToLogin (0.115 seconds)
RequestOperationTests
✓ testFailure (0.007 seconds)
✓ testSuccess (0.005 seconds)


     Executed 5 tests, with 0 failures (0 unexpected) in 0.283 (0.293) seconds

2017-01-24 19:57:55.016 xcodebuild[3516:11491] Error Domain=IDETestOperationsObserverErrorDomain Code=3 "The operation couldn’t be completed. (DTXProxyChannel error 1.) If you believe this error represents a bug, please attach the log file at /Users/distiller/Library/Developer/Xcode/DerivedData/a-dylglwgiaemptrdacfywrnxriwjb/Logs/Test/24ACEA06-5BF8-4829-A6E6-75A29F876D6E/Session-a-ui-tests-2017-01-24_195642-gxiTJe.log" UserInfo={NSLocalizedDescription=The operation couldn’t be completed. (DTXProxyChannel error 1.) If you believe this error represents a bug, please attach the log file at /Users/distiller/Library/Developer/Xcode/DerivedData/a-dylglwgiaemptrdacfywrnxriwjb/Logs/Test/24ACEA06-5BF8-4829-A6E6-75A29F876D6E/Session-a-ui-tests-2017-01-24_195642-gxiTJe.log}
** TEST FAILED **
ERROR [2017-01-24 19:57:55.72]: Exit status: 65
ERROR [2017-01-24 19:57:59.59]: #<Net::HTTPNotFound:0x007fdb1872e4f8>
+--------------------+----+
|      Test Results       |
+--------------------+----+
| Number of tests    | 12 |
| Number of failures | 0  |
+--------------------+----+

INFO [2017-01-24 19:58:02.98]: Successfully generated report at '/Users/distiller/a/fastlane/test_output/report.html'
INFO [2017-01-24 19:58:06.56]: Successfully generated report at '/Users/distiller/a/fastlane/test_output/report.junit'
INFO [2017-01-24 19:58:06.58]: -------------------------------
INFO [2017-01-24 19:58:06.58]: --- Step: update_info_plist ---
INFO [2017-01-24 19:58:06.58]: -------------------------------
DEBUG [2017-01-24 19:58:06.58]: Taking value for 'plist_path' from environment variable 'FL_UPDATE_PLIST_PATH'
DEBUG [2017-01-24 19:58:06.58]: Taking value for 'plist_path' from environment variable 'FL_UPDATE_PLIST_PATH'
DEBUG [2017-01-24 19:58:06.64]: Taking value for 'plist_path' from environment variable 'FL_UPDATE_PLIST_PATH'
INFO [2017-01-24 19:58:06.64]: Updated a/Info-enterprise.plist 💾.
INFO [2017-01-24 19:58:06.65]: -----------------------------------
INFO [2017-01-24 19:58:06.65]: --- Step: clean_build_artifacts ---
INFO [2017-01-24 19:58:06.65]: -----------------------------------
INFO [2017-01-24 19:58:06.65]: Cleaned up build artifacts 🐙
WARN [2017-01-24 19:58:06.65]: Lane Context:
INFO [2017-01-24 19:58:06.65]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios test", :SCAN_DERIVED_DATA_PATH=>"/Users/distiller/Library/Developer/Xcode/DerivedData/a-dylglwgiaemptrdacfywrnxriwjb", :SCAN_GENERATED_PLIST_FILES=>["/Users/distiller/Library/Developer/Xcode/DerivedData/a-dylglwgiaemptrdacfywrnxriwjb/Logs/Test/24ACEA06-5BF8-4829-A6E6-75A29F876D6E_TestSummaries.plist", "/Users/distiller/Library/Developer/Xcode/DerivedData/a-dylglwgiaemptrdacfywrnxriwjb/Logs/Test/2764C9EF-6770-4D27-B104-F60DA0AD6DB0_TestSummaries.plist"], :SCAN_GENERATED_PLIST_FILE=>"/Users/distiller/Library/Developer/Xcode/DerivedData/a-dylglwgiaemptrdacfywrnxriwjb/Logs/Test/2764C9EF-6770-4D27-B104-F60DA0AD6DB0_TestSummaries.plist"}
ERROR [2017-01-24 19:58:06.65]: Test execution failed. Exit status: 65
INFO [2017-01-24 19:58:06.65]: Successfully generated documentation at path '/Users/distiller/a/fastlane/README.md'

+------+-----------------------+-------------+
|              fastlane summary              |
+------+-----------------------+-------------+
| Step | Action                | Time (in s) |
+------+-----------------------+-------------+
| 1    | update_fastlane       | 2           |
| 2    | default_platform      | 0           |
| 💥   | scan                  | 314         |
| 4    | update_info_plist     | 0           |
| 5    | clean_build_artifacts | 0           |
+------+-----------------------+-------------+

DEBUG [2017-01-24 19:58:06.66]: All plugins are up to date
ERROR [2017-01-24 19:58:06.66]: fastlane finished with errors
DEBUG [2017-01-24 19:58:06.66]: All plugins are up to date
bundler: failed to load command: fastlane (/Users/distiller/a/vendor/bundle/ruby/2.3.0/bin/fastlane)
FastlaneCore::Interface::FastlaneError: [!] Test execution failed. Exit status: 65
  /Users/distiller/a/vendor/bundle/ruby/2.3.0/gems/fastlane-2.11.0/fastlane_core/lib/fastlane_core/ui/interface.rb:145:in `user_error!'
  /Users/distiller/a/vendor/bundle/ruby/2.3.0/gems/fastlane-2.11.0/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
  /Users/distiller/a/vendor/bundle/ruby/2.3.0/gems/fastlane-2.11.0/scan/lib/scan/runner.rb:96:in `handle_results'
  /Users/distiller/a/vendor/bundle/ruby/2.3.0/gems/fastlane-2.11.0/scan/lib/scan/runner.rb:9:in `run'
  /Users/distiller/a/vendor/bundle/ruby/2.3.0/gems/fastlane-2.11.0/scan/lib/scan/manager.rb:14:in `work'
  /Users/distiller/a/vendor/bundle/ruby/2.3.0/gems/fastlane-2.11.0/fastlane/lib/fastlane/actions/scan.rb:21:in `run'
  /Users/distiller/a/vendor/bundle/ruby/2.3.0/gems/fastlane-2.11.0/fastlane/lib/fastlane/runner.rb:239:in `block (2 levels) in execute_action'
  /Users/distiller/a/vendor/bundle/ruby/2.3.0/gems/fastlane-2.11.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/distiller/a/vendor/bundle/ruby/2.3.0/gems/fastlane-2.11.0/fastlane/lib/fastlane/runner.rb:217:in `block in execute_action'
  /Users/distiller/a/vendor/bundle/ruby/2.3.0/gems/fastlane-2.11.0/fastlane/lib/fastlane/runner.rb:213:in `chdir'
  /Users/distiller/a/vendor/bundle/ruby/2.3.0/gems/fastlane-2.11.0/fastlane/lib/fastlane/runner.rb:213:in `execute_action'
  /Users/distiller/a/vendor/bundle/ruby/2.3.0/gems/fastlane-2.11.0/fastlane/lib/fastlane/runner.rb:135:in `trigger_action_by_name'
  /Users/distiller/a/vendor/bundle/ruby/2.3.0/gems/fastlane-2.11.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
  Fastfile:119:in `block (2 levels) in parsing_binding'
  /Users/distiller/a/vendor/bundle/ruby/2.3.0/gems/fastlane-2.11.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/distiller/a/vendor/bundle/ruby/2.3.0/gems/fastlane-2.11.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/distiller/a/vendor/bundle/ruby/2.3.0/gems/fastlane-2.11.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/distiller/a/vendor/bundle/ruby/2.3.0/gems/fastlane-2.11.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/distiller/a/vendor/bundle/ruby/2.3.0/gems/fastlane-2.11.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
  /Users/distiller/a/vendor/bundle/ruby/2.3.0/gems/fastlane-2.11.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
  /Users/distiller/a/vendor/bundle/ruby/2.3.0/gems/fastlane-2.11.0/fastlane/lib/fastlane/commands_generator.rb:105:in `block (2 levels) in run'
  /Users/distiller/a/vendor/bundle/ruby/2.3.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
  /Users/distiller/a/vendor/bundle/ruby/2.3.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
  /Users/distiller/a/vendor/bundle/ruby/2.3.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
  /Users/distiller/a/vendor/bundle/ruby/2.3.0/gems/fastlane-2.11.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
  /Users/distiller/a/vendor/bundle/ruby/2.3.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
  /Users/distiller/a/vendor/bundle/ruby/2.3.0/gems/fastlane-2.11.0/fastlane/lib/fastlane/commands_generator.rb:302:in `run'
  /Users/distiller/a/vendor/bundle/ruby/2.3.0/gems/fastlane-2.11.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
  /Users/distiller/a/vendor/bundle/ruby/2.3.0/gems/fastlane-2.11.0/fastlane/lib/fastlane/cli_tools_distributor.rb:59:in `take_off'
  /Users/distiller/a/vendor/bundle/ruby/2.3.0/gems/fastlane-2.11.0/bin/fastlane:15:in `<top (required)>'
  /Users/distiller/a/vendor/bundle/ruby/2.3.0/bin/fastlane:23:in `load'
  /Users/distiller/a/vendor/bundle/ruby/2.3.0/bin/fastlane:23:in `<top (required)>'
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

Scanfile
```
# For more information about this configuration visit
# https://github.com/fastlane/fastlane/tree/master/scan#scanfile

# In general, you can use the options available
# scan --help

# Remove the # in front of the line to enable the option

scheme "ourScheme"
devices ["iPad Air", "iPad Pro", "iPad Retina"]
clean true
code_coverage true
output_types "html, junit"
open_report false

```

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.2.2                                       |
| Bundler?            | true                                        |
| Git                 | git version 2.9.3 (Apple Git-75)            |
| Installation Source | ~/.rbenv/versions/2.2.2/bin/fastlane        |
| Host                | Mac OS X 10.12.2 (16C67)                    |
| Ruby Lib Dir        | ~/.rbenv/versions/2.2.2/lib                 |
| OpenSSL Version     | OpenSSL 1.0.2d 9 Jul 2015                   |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
update_fastlane
default_platform :ios

platform :ios do

  lane :test do
    scan
  end

end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.aa.aa" # The bundle identifier of your app
apple_id "aa@aa.com" # Your Apple email address

team_id "aaa"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.11.0  | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                   | Version      |
| ------------------------------------- | ------------ |
| bundler                               | 1.13.7       |
| CFPropertyList                        | 2.3.4        |
| i18n                                  | 0.7.0        |
| json                                  | 1.8.6        |
| minitest                              | 5.10.1       |
| thread_safe                           | 0.3.5        |
| tzinfo                                | 1.2.2        |
| activesupport                         | 4.2.7.1      |
| public_suffix                         | 2.0.5        |
| addressable                           | 2.5.0        |
| rubyzip                               | 1.2.0        |
| apktools                              | 0.7.1        |
| aws-sigv4                             | 1.0.0        |
| jmespath                              | 1.3.1        |
| aws-sdk-core                          | 2.7.1        |
| aws-sdk-resources                     | 2.7.1        |
| aws-sdk                               | 2.7.1        |
| babosa                                | 1.0.2        |
| claide                                | 1.0.1        |
| fuzzy_match                           | 2.0.4        |
| nap                                   | 1.1.0        |
| cocoapods-core                        | 1.1.1        |
| cocoapods-deintegrate                 | 1.0.1        |
| cocoapods-downloader                  | 1.1.3        |
| cocoapods-plugins                     | 1.0.0        |
| cocoapods-search                      | 1.0.0        |
| cocoapods-stats                       | 1.0.0        |
| netrc                                 | 0.7.8        |
| cocoapods-trunk                       | 1.1.2        |
| cocoapods-try                         | 1.1.0        |
| colored                               | 1.2          |
| escape                                | 0.0.4        |
| fourflusher                           | 2.0.1        |
| gh_inspector                          | 1.0.3        |
| molinillo                             | 0.5.5        |
| nanaimo                               | 0.2.3        |
| xcodeproj                             | 1.4.2        |
| cocoapods                             | 1.1.1        |
| highline                              | 1.7.8        |
| commander                             | 4.4.3        |
| unf_ext                               | 0.0.7.2      |
| unf                                   | 0.1.4        |
| domain_name                           | 0.5.20161129 |
| dotenv                                | 2.1.2        |
| excon                                 | 0.54.0       |
| multipart-post                        | 2.0.0        |
| faraday                               | 0.11.0       |
| http-cookie                           | 1.0.3        |
| faraday-cookie_jar                    | 0.0.6        |
| faraday_middleware                    | 0.11.0.1     |
| fastimage                             | 2.0.1        |
| jwt                                   | 1.5.6        |
| little-plugger                        | 1.1.4        |
| multi_json                            | 1.12.1       |
| logging                               | 2.1.0        |
| memoist                               | 0.15.0       |
| os                                    | 0.9.6        |
| signet                                | 0.7.3        |
| googleauth                            | 0.5.1        |
| httpclient                            | 2.8.3        |
| hurley                                | 0.2          |
| mime-types-data                       | 3.2016.0521  |
| mime-types                            | 3.1          |
| uber                                  | 0.0.15       |
| representable                         | 2.3.0        |
| retriable                             | 2.1.0        |
| google-api-client                     | 0.9.23       |
| mini_magick                           | 4.5.1        |
| multi_xml                             | 0.6.0        |
| plist                                 | 3.2.0        |
| security                              | 0.1.3        |
| slack-notifier                        | 1.5.1        |
| terminal-notifier                     | 1.7.1        |
| unicode-display_width                 | 1.1.3        |
| terminal-table                        | 1.7.3        |
| word_wrap                             | 1.0.0        |
| rouge                                 | 1.11.1       |
| xcpretty                              | 0.2.4        |
| xcpretty-travis-formatter             | 0.0.4        |
| proxies                               | 0.2.1        |
| s3                                    | 0.3.25       |
</details>

*generated on:* **2017-01-24**
</details>

**Comment by mfurtak** [comment] 2017-01-25 16:15
This appears to be a duplicate of #7987

**Comment by MaximusMcCann** [comment] 2017-01-25 16:44
I'll take your word @mfurtak.  To be fair, this does have different error output.  Cheers, and thanks for the awesome work you guys continue to do on Fastlane!

**Comment by mfurtak** [comment] 2017-01-25 16:51
Mm, yup. I was keying off the `Net::HTTPNotFound` being in both. We'll have them linked together, anyhow, and can revisit as needed :+1:

**Comment by mfurtak** [comment] 2017-01-25 21:32
I've found and fixed the source of `Net::HTTPNotFound` in #8004. To get rid of that message, make sure your `SLACK_URL` is correct.

I've reopened this since that problem was obviously unrelated!

**Comment by MaximusMcCann** [comment] 2017-01-28 17:19
Found that was the issue, cheers.  Now if only Exit 65 randomness would go away ... :/

**Comment by ohayon** [comment] 2017-02-28 21:29
@MaximusMcCann are you still getting the `DTXProxyChannel error 1` issue here?

**Comment by MaximusMcCann** [comment] 2017-03-01 01:13
Not that I've noticed

**Comment by ohayon** [comment] 2017-03-01 01:17
👍 That's great! I am going to close this issue for now but feel free to continue conversation if something come up! 🚀 🐙

**Closed by ohayon** 2017-03-01 01:17 UTC
