### ISSUE TITLE
app_identifier is ignored by `deliver` called from CLI

### ISSUE THREAD

**Issue by berdyshev** [fastlane/fastlane#17697] opened 2020-12-01 10:15 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I have two apps developed within a single codebase. Fastlane also configured to build both of them. One of the apps (e.g. `app1` is a default app). 
I'm trying to upload metadata and screenshots into AppCenter from command line with `app_identifier` parameter (e.g. `app2`, but it's ignored and it uploads metadata into a default app. 

##### Command executed
`bundle exec fastlane run deliver app_identifier='com.domain.app2' screenshots_path:'./fastlane/screenshots/app2' overwrite_screenshots:true metadata_path:'./fastlane/metadata/app2' skip_metadata:true skip_binary_upload:true skip_app_version_update:true`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
✔] 🚀 
+----------------------------------+---------+----------------------------------+
|                                 Used plugins                                  |
+----------------------------------+---------+----------------------------------+
| Plugin                           | Version | Action                           |
+----------------------------------+---------+----------------------------------+
| fastlane-plugin-firebase_app_di  | 0.2.4   | firebase_app_distribution_login  |
| stribution                       |         | firebase_app_distribution        |
| fastlane-plugin-telegram         | 0.1.3   | telegram                         |
+----------------------------------+---------+----------------------------------+

[12:02:03]: ---------------------
[12:02:03]: --- Step: deliver ---
[12:02:03]: ---------------------
[12:02:03]: Login to App Store Connect (b******m@gmail.com)
[12:02:05]: Login successful

+--------------------------------------+-------------------------------+
|                       deliver 2.168.0 Summary                        |
+--------------------------------------+-------------------------------+
| screenshots_path                     | ./fastlane/screenshots/youpro |
| overwrite_screenshots                | true                          |
| metadata_path                        | ./fastlane/metadata/youpro    |
| skip_metadata                        | true                          |
| skip_binary_upload                   | true                          |
| skip_app_version_update              | true                          |
| username                             | berdartem@gmail.com           |
| app_identifier                       | com.domain.app1             |
| platform                             | ios                           |
| edit_live                            | false                         |
| use_live_version                     | false                         |
| skip_screenshots                     | false                         |
| force                                | false                         |
| submit_for_review                    | false                         |
| reject_if_possible                   | false                         |
| phased_release                       | false                         |
| reset_ratings                        | false                         |
| team_id                              | 118743653                     |
| dev_portal_team_id                   | 89KKXAAKTA                    |
| run_precheck_before_submit           | true                          |
| precheck_default_rule_level          | warn                          |
| ignore_language_directory_validation | false                         |
| precheck_include_in_app_purchases    | true                          |
+--------------------------------------+-------------------------------+
 </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 11.0.1                                      |
| Ruby                        | 2.7.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.24.3 (Apple Git-128)          |
| Installation Source         | /usr/local/lib/ruby/gems/2.7.0/bin/fastlane |
| Host                        | macOS 11.0.1 (20B50)                        |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.7.1_2/lib          |
| OpenSSL Version             | OpenSSL 1.1.1f  31 Mar 2020                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.2                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.3"

default_platform :ios

platform :ios do
  before_all do
    # ensure_git_branch
    ensure_git_status_clean
    # git_pull
    
  end

  desc 'Fetch certificates and provisioning profiles'
  lane :certificates do
    match(app_identifier: ['com.domain.app1', 'com.domain.app2'], type: 'development', readonly: true)
    match(app_identifier: ['com.domain.app1', 'com.domain.app2'], type: 'appstore', readonly: true)
  end


  lane :commit_and_push do |options|
    clean_build_artifacts
    commit_version_bump(message: "iOS build #{options[:build]} for #{options[:scheme]}", xcodeproj: './app.xcodeproj', force: true)
    push_to_git_remote
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do |options|
    puts "Building app: #{ENV['APP_NAME']}"
    scheme = ENV['IOS_SCHEME'] ? ENV['IOS_SCHEME'] : "app"
    puts "Scheme used: #{scheme}"

    certificates
    increment_build_number(xcodeproj: './app.xcodeproj')
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: scheme) # Build your app - more options available
    pilot(app_identifier: ENV['APP_BUNDLE_ID'])

    # Upload them to Crashlytics
    upload_symbols_to_crashlytics(
      gsp_path: "Firebase/#{ENV['GOOGLESERVICE_INFO_PLIST']}"
    )
    commit_and_push(build: lane_context[SharedValues::BUILD_NUMBER], scheme: scheme)
  end

  lane :refresh_dsyms do
    # Download dSYM files from iTC
    download_dsyms(version:'latest')

    # Upload them to Crashlytics
    upload_symbols_to_crashlytics(
      gsp_path: "Firebase/#{ENV['GOOGLESERVICE_INFO_PLIST']}"
    )

    # Delete the local dSYM files
    clean_build_artifacts
  end


  desc "Submit a new Beta Build to Firebase App Distribution"
  desc "This will also make sure the profile is up to date"
  lane :firebase do |options|
    puts "Building app: #{ENV['APP_NAME']}"
    scheme = ENV['IOS_SCHEME'] ? ENV['IOS_SCHEME'] : "app"
    puts "Scheme used: #{scheme}"

    match(app_identifier: ENV['APP_BUNDLE_ID'], type: 'adhoc', readonly: true)
    increment_build_number(xcodeproj: './app.xcodeproj')
    gym(
      scheme: scheme,
      export_method: "ad-hoc"
    ) # Build your app - more options available
    firebase_app_distribution(
      app: ENV['FIREBASE_IOS_APP_ID'],
      groups: options[:client] ? "internal, client" : "internal",
      release_notes: options[:notes] ? options[:notes] : "#{ENV['APP_NAME']} release"
    )

    commit_and_push(build: lane_context[SharedValues::BUILD_NUMBER], scheme: scheme)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    match(app_identifier: ['com.domain.app1', 'com.domain.app2'], type: 'appstore', readonly: true)
    increment_build_number(xcodeproj: './app.xcodeproj')
    gym(scheme: "app.prod")
    deliver(
      submit_for_review: true,
      force: true,
      automatic_release: true,
      app_identifier: ENV['APP_BUNDLE_ID'],
      metadata_path: "./fastlane/metadata/#{ENV['PROJECT']}",
      screenshots_path: "./fastlane/screenshots/#{ENV['PROJECT']}",
      submission_information: {
        add_id_info_limits_tracking: false,
        add_id_info_serves_ads: false,
        add_id_info_tracks_action: true,
        add_id_info_tracks_install: true,
        add_id_info_uses_idfa: true,
        content_rights_has_rights: false,
        content_rights_contains_third_party_content: false,
        export_compliance_platform: 'ios',
        export_compliance_compliance_required: false,
        export_compliance_encryption_updated: false,
        export_compliance_app_type: nil,
        export_compliance_uses_encryption: false,
        export_compliance_is_exempt: false,
        export_compliance_contains_third_party_cryptography: false,
        export_compliance_contains_proprietary_cryptography: false,
        export_compliance_available_on_french_store: false
      }
    )

    # Upload them to Crashlytics
    upload_symbols_to_crashlytics(
      gsp_path: "Firebase/#{ENV['GOOGLESERVICE_INFO_PLIST']}"
    )

    commit_and_push(build: lane_context[SharedValues::BUILD_NUMBER], scheme: scheme)
  end

end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.168.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status |
| ----------------------------------------- | ------- | ------------- |
| fastlane-plugin-firebase_app_distribution | 0.2.4   | ✅ Up-To-Date  |
| fastlane-plugin-telegram                  | 0.1.3   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.4.0        |
| bundler                                   | 2.1.2        |
| uri                                       | 0.10.0       |
| rake                                      | 13.0.1       |
| CFPropertyList                            | 3.0.2        |
| public_suffix                             | 4.0.6        |
| addressable                               | 2.7.0        |
| atomos                                    | 0.1.3        |
| aws-eventstream                           | 1.1.0        |
| aws-partitions                            | 1.398.0      |
| aws-sigv4                                 | 1.2.2        |
| jmespath                                  | 1.4.0        |
| aws-sdk-core                              | 3.109.3      |
| aws-sdk-kms                               | 1.39.0       |
| aws-sdk-s3                                | 1.85.0       |
| babosa                                    | 1.0.4        |
| claide                                    | 1.0.3        |
| colored                                   | 1.2          |
| colored2                                  | 3.1.2        |
| highline                                  | 1.7.10       |
| commander-fastlane                        | 4.4.6        |
| declarative                               | 0.0.20       |
| declarative-option                        | 0.1.0        |
| digest-crc                                | 0.6.1        |
| unf_ext                                   | 0.0.7.7      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| dotenv                                    | 2.7.6        |
| emoji_regex                               | 3.2.1        |
| excon                                     | 0.78.0       |
| multipart-post                            | 2.0.0        |
| ruby2_keywords                            | 0.0.2        |
| faraday                                   | 1.1.0        |
| http-cookie                               | 1.0.3        |
| faraday-cookie_jar                        | 0.0.7        |
| faraday_middleware                        | 1.0.0        |
| fastimage                                 | 2.2.0        |
| gh_inspector                              | 1.1.3        |
| jwt                                       | 2.2.2        |
| memoist                                   | 0.16.2       |
| multi_json                                | 1.15.0       |
| os                                        | 1.1.1        |
| signet                                    | 0.14.0       |
| googleauth                                | 0.14.0       |
| httpclient                                | 2.8.3        |
| mini_mime                                 | 1.0.2        |
| uber                                      | 0.1.0        |
| representable                             | 3.0.4        |
| retriable                                 | 3.1.2        |
| google-api-client                         | 0.38.0       |
| google-cloud-env                          | 1.4.0        |
| google-cloud-errors                       | 1.0.1        |
| google-cloud-core                         | 1.5.0        |
| google-cloud-storage                      | 1.29.1       |
| json                                      | 2.3.1        |
| mini_magick                               | 4.11.0       |
| plist                                     | 3.5.0        |
| rubyzip                                   | 2.3.0        |
| security                                  | 0.1.3        |
| naturally                                 | 2.2.0        |
| simctl                                    | 1.6.8        |
| slack-notifier                            | 2.3.2        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.7.0        |
| terminal-table                            | 1.8.0        |
| tty-screen                                | 0.8.1        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| word_wrap                                 | 1.0.0        |
| nanaimo                                   | 0.3.0        |
| xcodeproj                                 | 1.19.0       |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| xcpretty-travis-formatter                 | 1.0.0        |
| fastlane-plugin-firebase_app_distribution | 0.2.4        |
| fastlane-plugin-telegram                  | 0.1.3        |
</details>

*generated on:* **2020-12-01**
</details>

**Comment by rogerluan** [comment] 2020-12-07 13:27
Hey @berdyshev 👋 

Hehe took me a couple mins to understand what was going on, but the problem is that only for `app_identifier` you're using an equal sign (`=`) after the option instead of a colon sign (`:`) 😄 

```diff
-bundle exec fastlane run deliver app_identifier='com.domain.app2' screenshots_path:'./fastlane/screenshots/app2' overwrite_screenshots:true metadata_path:'./fastlane/metadata/app2' skip_metadata:true skip_binary_upload:true skip_app_version_update:true
+bundle exec fastlane run deliver app_identifier:'com.domain.app2' screenshots_path:'./fastlane/screenshots/app2' overwrite_screenshots:true metadata_path:'./fastlane/metadata/app2' skip_metadata:true skip_binary_upload:true skip_app_version_update:true
```

That should solve your issue 🙌 
Let me know if you have further issues; otherwise, closing this ticket 🤗

**Closed by rogerluan** 2020-12-07 13:27 UTC
Labels: tool: deliver
