### ISSUE TITLE
We’ve detected that your app is using an old version of the Google Play developer API.

### ISSUE THREAD

**Issue by ronjunelopez** [fastlane/fastlane#15312] opened 2019-09-15 00:54 UTC
### Feature Request
`upload_to_play_store` upgrade
#### Motivation Behind Feature
I am not sure, if fastlane is using the latest google upload, I have receive this kind of warning from google play console. If this upgrade is not yet implemented, May I request this kind of upgrade.
![image](https://user-images.githubusercontent.com/4947998/64915265-eeeb2e80-d795-11e9-9dbf-72ec84064ffd.png)
 We’ve detected that your app is using an old version of the Google Play developer API.From 1 December 2019, versions 1 and 2 of this API will no longer be available. Update to version 3 before this date

**Comment by rickclephas** [comment] 2019-09-15 09:15
Duplicate of #14573

**Comment by janpio** [comment] 2019-09-17 22:56
@rickclephas has provided the perfect link, we are aware and actively working on fixing this.

**Closed** 2019-09-17 22:56 UTC
Labels: tool: supply
