### ISSUE TITLE
[Fastlane.Swift] `onError` never called.

### ISSUE THREAD

**Issue by andemengo** [fastlane/fastlane#17482] opened 2020-10-21 09:57 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Currently, the method `onError` isn't implemented in `LaneFileProtocol` so that we can't handle errors, for example during `deliver`.
If any lane fails, there is no way to handle the failure.

##### Command executed

Any lane, for example:

`fastlane deliver`

Related: https://github.com/fastlane/fastlane/issues/12381

**Comment by rogerluan** [comment] 2020-11-02 22:55
I'd love to see this working as well! @andemengo if you could open a PR to address this change, that'd be superb! ❤️

**Comment by minuscorp** [comment] 2020-12-03 19:18
Is this still an issue? @andemengo

**Comment by andemengo** [comment] 2020-12-04 11:29
@minuscorp 
I think yes, I didn't have any time to work on it, and in the last version 2.169.0 in `LaneFileProtocol` at line `136`
there is this:

```swift
// We need to catch all possible errors here and display a nice message.
_ = fastfileInstance.perform(NSSelectorFromString(laneMethod), with: parameters)
```

So that I tested in my own project and `onError` isn't called.

Also I've a question about how to run the xcodeproj (if it's needed to write a `testLane` for this fix).
If I try to run the project I get this output in the console:

```
[1607081114.908289]: [FastlaneRunner.RunnerArgument(name: "lane", value: "testLane")]
2020-12-04 12:25:14.937850+0100 FastlaneRunner[29361:18357230] [] nw_socket_handle_socket_event [C1.1:1] Socket SO_ERROR [61: Connection refused]
2020-12-04 12:25:14.938494+0100 FastlaneRunner[29361:18357230] [] nw_socket_handle_socket_event [C1.2:1] Socket SO_ERROR [61: Connection refused]
2020-12-04 12:25:14.938733+0100 FastlaneRunner[29361:18357233] [] nw_connection_get_connected_socket [C1] Client called nw_connection_get_connected_socket on unconnected nw_connection
2020-12-04 12:25:14.938793+0100 FastlaneRunner[29361:18357233] TCP Conn 0x10085f6d0 Failed : error 0:61 [61]
[1607081114.938993]: input stream error occurred
[1607081114.9395242]: sending: { "commandType": "control", "command": {"command":"done"} }
[1607081114.939913]: sending: { "commandType": "control", "command": {"command":"done"} }
[1607081114.939968]: connection closed!
Program ended with exit code: 0
```

For sure I'm missing something, but it's my first issue that I found and that I tried to fix.
Thanks!

**Comment by minuscorp** [comment] 2020-12-04 11:39
Could you provide an snippet of your current setup so I can try to reproduce it locally?

**Comment by minuscorp** [comment] 2020-12-04 13:12
It seems to me also that you aren't booting the fastlane socket manually... Maybe you're forgetting that step

**Comment by andemengo** [comment] 2020-12-04 14:46
Thanks @minuscorp! I wasn't booting the fastlane socket manually! Right!

For the snippet, you can just try to update a build to AppStore Connect, and make it fails. (In my example I add a build error in the code to make it fails). 
In that case, I want use `onError()` in my `Fastfile.swift` in order to send a slack notification. It doesn't work but instead  `afterAll` is called in the right way.

```swift
// FastFile

// MARK: - Error handling
    
func onError(currentLane: String, errorInfo: String) {
    messageOnError(errorInfo)
}
    
func afterAll(with lane: String) {
    messageOnSuccess()
}

// Slack integration

func messageOnError(_ pretext: String) {
    let message: String
    switch selectedLane {
    case .betaTestFlight:
        message = "Error uploading to TestFlight."
    case .release:
        message = "Error uploading to AppStore."
    case .none:
        message = "No supplementary lane executed."
    }
        
    slack(
        message: message,
        pretext: pretext,
        channel: slackChannel,
        slackUrl: slackURL,
        success: false
    )
}

func messageOnSuccess() {
    let message: String
    switch selectedLane {
    case .betaPlaygroundTest:
        message = "App successfully uploaded to TestFlight."
    case .release:
        message = "App successfully uploaded to AppStore."
    case .none:
        return
    }

    slack(
        message: message,
        channel: slackChannel,
        slackUrl: slackURL,
        success: true
    )
}
```

**Comment by minuscorp** [comment] 2020-12-04 16:52
I'll try to figure out why the global on error is not being called then!

**Comment by rogerluan** [comment] 2020-12-14 05:32
> It seems to me also that you aren't booting the fastlane socket manually... Maybe you're forgetting that step

Could you provide more details on how that should be done? I didn't know we had to boot socket manually to receive onError callbacks 🤯 
Thanks in advance!

**Comment by minuscorp** [comment] 2020-12-14 14:29
You shouldn't, but the socket must be running in order to just let the Swift part work. On the other hand is the lack of call of the on error callback, the logs of the socket should provide us the answer about why the callback is not getting called. I suspect that fastlane is not sending that specific error as an error in the socket message and hence the callback is not getting called, a simple sh call with an error callback seems to be working, so that's why my suspect is on the socket side, could you provide the whole lot on submitting the application so I can review what if being sent in the socket?
Also, I'd use the individual error callbacks of the Swift calls instead the global one and see if it works?

**Comment by minuscorp** [comment] 2021-01-14 12:09
CC @andemengo

**Comment by minuscorp** [comment] 2021-03-25 14:44
@andemengo we have a PR that you can checkout resolving this issue! 😄

**Comment by andemengo** [comment] 2021-03-26 17:38
@minuscorp amazing! 🚀 
I'll take a look!

**Closed** 2021-04-06 23:45 UTC
Labels: status: has-pr, topic: swift
