### ISSUE TITLE
`FASTLANE_SESSION` not working even though set it up

### ISSUE THREAD

**Issue by dongminyoon** [fastlane/fastlane#20073] opened 2022-03-17 05:29 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

FASTLANE_SESSION has expired and has been renewed using `fastlane spaceship -u <email>`
and set it up to `.env` but it isn't working

##### Command executed

1. execute `fastlane spaceship -u <email>`
2. set it up to `.env``
3. execute `fastlane run latest_testflight_build_number`
4. occur error ----> `The request could not be completed because:
	Authentication error, you passed an invalid session using the environment variable FASTLANE_SESSION or SPACESHIP_SESSION`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.204.3 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.3.0        |
| did_you_mean                    | 1.6.1        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.91.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.3        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.9.3        |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.6.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.3.7        |
| simctl                          | 1.6.8        |
| jwt                             | 2.3.0        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.0       |
| googleauth                      | 1.1.0        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.2        |
| google-apis-playcustomapp_v1    | 0.7.0        |
| google-apis-androidpublisher_v3 | 0.16.0       |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.10.0       |
| google-apis-storage_v1          | 0.11.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.36.1       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.5.0        |
| aws-partitions                  | 1.554.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.4.0        |
| aws-sdk-core                    | 3.126.0      |
| aws-sdk-kms                     | 1.54.0       |
| aws-sdk-s3                      | 1.112.0      |
| set                             | 1.0.2        |
| forwardable                     | 1.3.2        |
| logger                          | 1.5.0        |
| pathname                        | 0.2.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.3.1        |
| date                            | 3.2.2        |
| timeout                         | 0.2.0        |
| stringio                        | 3.0.1        |
| securerandom                    | 0.1.1        |
| uri                             | 0.11.0       |
| openssl                         | 3.0.0        |
| digest                          | 3.1.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.4        |
| io-wait                         | 0.2.1        |
| zlib                            | 2.1.1        |
| resolv                          | 0.2.1        |
| time                            | 0.2.0        |
| open-uri                        | 0.2.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.2        |
| net-http                        | 0.2.0        |
| ostruct                         | 0.5.2        |
| english                         | 0.7.1        |
| erb                             | 2.2.3        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.11       |
| tempfile                        | 0.1.2        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.6.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.1        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.1        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.3.0        |
| find                            | 0.1.1        |
| yaml                            | 0.2.0        |
| psych                           | 4.0.3        |

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by lcghh** [comment] 2022-03-17 05:40
The request could not be completed because:
	Authentication error, you passed an invalid session using the environment variable FASTLANE_SESSION or SPACESHIP_SESSION
same problem

**Comment by gooson** [comment] 2022-03-17 06:07
same problem

**Comment by Rajasekhar455** [comment] 2022-03-17 06:13
same problem.

**Comment by chinhpn-2177** [comment] 2022-03-17 06:50
same problem

**Comment by clkr** [comment] 2022-03-17 06:53
same problem here

**Comment by BugraOmursunn** [comment] 2022-03-17 06:54
I have same issue

**Comment by clkr** [comment] 2022-03-17 07:01
Duplicate of #20071

**Comment by RafaelFernandezAlv** [comment] 2022-03-17 10:14
same problem here

**Comment by virtualguy** [comment] 2022-03-17 10:23
same here

**Comment by GJBlog** [comment] 2022-03-17 10:38
> The request could not be completed because: Authentication error, you passed an invalid session using the environment variable FASTLANE_SESSION or SPACESHIP_SESSION same problem
> 
> Back to 2.176.0, work for me!

help，how to install special version fastlane?

**Comment by bilaloz** [comment] 2022-03-17 10:43
> 

gem uninstall fastlane
sudo gem install fastlane --version {version}

**Comment by GJBlog** [comment] 2022-03-17 12:16
me too same problem

> 

thanks for you ,but I performed fastlane to submit App review prompt Build number does not exist, I cry...

**Comment by RafaelFernandezAlv** [comment] 2022-03-17 12:45
> The request could not be completed because: Authentication error, you passed an invalid session using the environment variable FASTLANE_SESSION or SPACESHIP_SESSION same problem
> 
> Back to 2.176.0, work for me!

This works, thanks!
Waiting for updates

**Comment by viktor-shmigol** [comment] 2022-03-17 14:50
same problem

**Comment by jamesmcn1** [comment] 2022-03-17 16:00
downgrading to 2.176.0 worked for me

**Comment by bapex** [comment] 2022-03-17 16:11
same problem

**Comment by joshdholtz** [comment] 2022-03-17 17:15
✨ Official Update

This appears to be a duplicate of #20071. Going to close this so we can keep everything together in one issue 🙃

**Closed by joshdholtz** 2022-03-17 17:15 UTC

**Comment by Tihomir01** [comment] 2022-03-17 17:32
same problem  here  . ;/

**Comment by hnarimani** [comment] 2022-03-17 21:19
Same issue here 🙃🙃🙃🙃🙃

**Comment by nledon** [comment] 2022-03-21 18:03
Same problem here.
