### ISSUE TITLE
2.17.0 sigh fetching profiles duration

### ISSUE THREAD

**Issue by danielbowden** [fastlane/fastlane#8263] opened 2017-02-16 02:44 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I've just updated to `2.17.0` which has solved the Apple response issues from previous days. All builds are now passing however the runtime of `sigh` fetching profiles has greatly increased.

I've tried running my lane 9 times now across two machines, on two internet connections in two different cities, both based in Australia. Each time the lane has completed successfully but each run of `sigh` within my fastfile has consistently taken exactly 484s (~8 mins) to complete.

This has blown out our CI run times from 3-4 minutes to 26 minutes.

```
[13:25:32]: Successfully logged in
[13:25:32]: Fetching profiles...
[13:33:51]: Found 1 matching profile(s)
[13:33:51]: Downloading provisioning profile...
[13:33:55]: Successfully downloaded provisioning profile...
```

Happy that our builds are back passing again but just wanted to raise this issue. Suspect it could be more connection problems to Apple, but unsure.
 I've also tried removing `spaceship_itc_service_key.txt` before running.

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.3                                     |
| Ruby                | 2.2.2                                       |
| Bundler?            | true                                        |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.rbenv/versions/2.2.2/bin/fastlane        |
| Host                | Mac OS X 10.12.3 (16D32)                    |
| Ruby Lib Dir        | ~/.rbenv/versions/2.2.2/lib                 |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Is homebrew         | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_AU.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.17.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| bundler                   | 1.13.7       |
| CFPropertyList            | 2.3.5        |
| i18n                      | 0.8.0        |
| json                      | 1.8.6        |
| minitest                  | 5.10.1       |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.1        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.1.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.2        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.1.1        |
| cocoapods-try             | 1.1.0        |
| colored                   | 1.2          |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.0.3        |
| molinillo                 | 0.5.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| cocoapods                 | 1.1.1        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| dotenv                    | 2.2.0        |
| excon                     | 0.55.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.11.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.0.1        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.28       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.2.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |

**Comment by danielbowden** [comment] 2017-02-17 04:50
I've also now tried `2.17.1` which has the same time issue.

It looks to be directly related to the amount of profiles our account has to fetch before it can find a match. I removed old, expired profiles and the time dropped but it is still very long. I cannot remove any more as the rest are required.

Is this as a result of the new API change? Was the previous version still fetching all profiles for the account?

**Comment by mfurtak** [comment] 2017-02-17 11:39
Hi @danielbowden :wave:

Yes, this is related to recent changes that adjust to shifts in the Apple APIs. We're sorry for the speed regression, but we thought it was important to get something out as soon as possible that fixed people's builds in general.

Thanks for the report! We are looking into ways it can be improved :+1:

CC: @snatchev

**Comment by danielbowden** [comment] 2017-02-17 12:03
Hi @mfurtak. Of course, I completely understand. Very appreciative to have the builds back working again. It's definitely a worthwhile trade off. 

If any ideas come up that you would like tested I'd be happy to help out. We have a fairly complex build process for a large set of whitelabel apps (200+ profiles) so I'd probably be able to compare the outcome of any changes for you. 

Thanks again 👍

**Comment by MrAdamBoyd** [comment] 2017-02-17 19:19
Also experiencing this problem, it's taking about 20 minutes to fetch the profiles. We also have a pretty complex build process, with about 1200 profiles. I'd be happy to help you test ideas if you need any help.

Thanks!

**Comment by lukethoene** [comment] 2017-02-17 20:02
20 minutes on the nose for us with fastlane 2.17.1.  

[11:36:22]: Fetching profiles...
[11:55:55]: Found 1 matching profile(s)
[11:55:55]: Recreating the profile
[11:56:10]: Creating new provisioning profile for 'com.xxx.xxxx' with name 'com.xxx.xxxx AppStore' for 'ios' platform
[11:56:28]: Downloading provisioning profile...
[11:56:35]: Successfully downloaded provisioning profile...
[11:56:35]: Installing provisioning profile...

Interestingly, another deployment box running fastlane 2.16.0 / bundler 1.14.4 is now working again just fine.

**Comment by MrAdamBoyd** [comment] 2017-02-17 20:16
@lukethoene same. My computer is running 2.14.2 haven't seen any issues so far.

**Comment by mfurtak** [comment] 2017-02-17 22:02
Thanks for the follow-up and kind offers, everyone. We'll be in touch as soon as we can about this.

**Comment by lukethoene** [comment] 2017-02-21 21:08
I'm not sure if 2.18 was meant to address it, but I updated one machine and am still seeing the lengthy profile-fetch times:

[12:08:52]: Fetching profiles...
[12:27:42]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you

**Comment by tsafrir** [comment] 2017-02-23 21:59
@mfurtak 
As you know, fetching the profiles (`find_by_bundle_id`) also fetches the profile details just to get the app's bundle_id.
Since the default profile name is "<bundle_id> <profile type>" or a name given by user.
May I suggest to add an option to `sigh` to find the profile by matching the application_identifier with the profile name?

I tested it by changing the method `find_by_bundle_id` locally to match the profile.name with the bundle id.
In my case, the process improved from 39 minutes to 5 seconds.

**Comment by mfurtak** [comment] 2017-02-23 22:14
The latest update on this is that we're considering rolling most of these changes back, since we think Xcode is still using the old endpoints that were giving us trouble during the maintenance period. We think those endpoints are no longer having trouble.

If we decide to do that, we will probably make the old calls the default, and include a feature switch to change to the current set of calls in case of emergency.

/cc @asfalcone

**Comment by TechGuyVN** [comment] 2017-02-24 02:26
I face the same problem, too long to fetch profile,
I tried:
- Update newest version 2.18.3: not working
- Roll back 2.14.2 too but not working.
Our system more than 1000 profiles too, any workaround for this case ?
Many Thanks.

**Comment by asfalcone** [comment] 2017-02-24 02:44
@TechGuyVN could you describe how the 2 versions are behaving (getting an error, very slow, etc)? I'm just not sure what you mean by "not working" in each case. Thanks!

**Comment by TechGuyVN** [comment] 2017-02-24 02:50
@asfalcone  I mean sigh fetch  profiles very slow , over 30minutes each time.

**Comment by asfalcone** [comment] 2017-02-24 02:51
@TechGuyVN is 2.14.2 slow for you as well?

**Comment by TechGuyVN** [comment] 2017-02-24 02:54
@asfalcone i tried to downgrade fastlane to 2.14.2,  
`sudo gem install fastlane --version 2.14.2
but i noticed sign still 2.18.3, did i made it wrong ?

**Comment by asfalcone** [comment] 2017-02-24 03:00
You can run `fastlane _2.14.2_ sigh ...` to use the specific version of the _fastlane_ gem to run the command.

**Comment by TechGuyVN** [comment] 2017-02-24 04:20
Thanks @asfalcone , it's can fetch profiles now!

**Comment by lukethoene** [comment] 2017-02-24 05:39
To revert our fastlane setups I actually needed to run "uninstall fastlane" and "uninstall bundler" first.  I also ran uninstall sigh just for good measure ;)

Then, reinstalled each of those with "install [gemname] -v [version]"  for instance "install fastlane -v 2.14.2"

**Comment by asfalcone** [comment] 2017-03-01 16:48
This should be fixed in _faslane_ 2.19.0. We reverted to the old behavior and introduced the `SPACESHIP_AVOID_XCODE_API` env variable. You'll want to use the default behavior for performance reasons but if this API has issues again, you can set SPACESHIP_AVOID_XCODE_API=1 👍. Please give it a try and let me know, thanks!

**Comment by danielbowden** [comment] 2017-03-02 07:49
I've just updated and can confirm https://github.com/fastlane/fastlane/pull/8359 and the `2.19.1` release fixes this issue. 

My profile fetching is back down to around 4-9s and the overall build times have now dropped from the 26 minutes I reported at the start of this issue back to around 2-2.5 minutes.

Thanks @snatchev, @asfalcone & co much appreciated!

Feel free to close this now 👍

**Comment by hjanuschka** [comment] 2017-03-02 07:53
great to here!!! ❤️  going to close this now.

**Closed by hjanuschka** 2017-03-02 07:53 UTC
Labels: sigh, spaceship
