### ISSUE TITLE
deliver: The provided entity includes an unknown attribute - 'startDate' is not an attribute on the resource 'appPrices

### ISSUE THREAD

**Issue by Mehdzor** [fastlane/fastlane#21105] opened 2023-03-05 16:55 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When uploading the first version for a new app and price_tier set to 0, the step fails with an error:

` The provided entity includes an unknown attribute - 'startDate' is not an attribute on the resource 'appPrices' - /included/0/attributes/startDate`

##### Command executed
```
    deliver(
          force: true,
          run_precheck_before_submit: false,
          automatic_release: false,
          skip_metadata: false,
          ipa: File.expand_path(ipa_path)
    )
```

##### Complete output when running fastlane, including the stack trace and command used
```
+--------------------------------------+--------------------------------------+

|                           deliver 2.212.1 Summary                           |
+--------------------------------------+--------------------------------------+
| force                                | true                                 |
| run_precheck_before_submit           | false                                |
| automatic_release                    | false                                |
| skip_metadata                        | false                                |
| ipa                                  | /private/var/lib/********/builds/65  |
|                                      | 481/build/ios/ipa/S****** LTR.ipa    |
| api_key                              | ********                             |
| app_identifier                       | io.******.**jTnuTj.********          |
| screenshots_path                     | ./fastlane/screenshots               |
| metadata_path                        | ./fastlane/metadata                  |
| app_version                          | 5.0.1                                |
| username                             | smart*******@gmail.com               |
| platform                             | ios                                  |
| edit_live                            | false                                |
| use_live_version                     | false                                |
| skip_binary_upload                   | false                                |
| skip_screenshots                     | false                                |
| skip_app_version_update              | false                                |
| overwrite_screenshots                | false                                |
| sync_screenshots                     | false                                |
| submit_for_review                    | false                                |
| verify_only                          | false                                |
| reject_if_possible                   | false                                |
| phased_release                       | false                                |
| reset_ratings                        | false                                |
| price_tier                           | 0                                    |
| precheck_default_rule_level          | warn                                 |
| ignore_language_directory_validatio  | false                                |
| n                                    |                                      |
| precheck_include_in_app_purchases    | true                                 |
+--------------------------------------+--------------------------------------+
[17:08:50]: Making sure the latest version on App Store Connect matches '5.0.1'...

[17:08:51]: Successfully set the version to '5.0.1'
[17:08:51]: Loading './fastlane/metadata/en-US/description.txt'...
[17:08:51]: Loading './fastlane/metadata/en-US/keywords.txt'...
[17:08:51]: Loading './fastlane/metadata/en-US/release_notes.txt'...
[17:08:51]: Loading './fastlane/metadata/en-US/support_url.txt'...
[17:08:51]: Loading './fastlane/metadata/en-US/marketing_url.txt'...
[17:08:51]: Loading './fastlane/metadata/en-US/name.txt'...
[17:08:51]: Loading './fastlane/metadata/en-US/privacy_url.txt'...
[17:08:51]: Loading './fastlane/metadata/copyright.txt'...
[17:08:51]: Loading './fastlane/metadata/primary_category.txt'...
[17:08:51]: Loading './fastlane/metadata/secondary_category.txt'...
[17:08:51]: Loading './fastlane/metadata/review_information/first_name.txt'...
[17:08:51]: Loading './fastlane/metadata/review_information/last_name.txt'...
[17:08:51]: Loading './fastlane/metadata/review_information/phone_number.txt'...
[17:08:51]: Loading './fastlane/metadata/review_information/email_address.txt'...
[17:08:51]: Loading './fastlane/metadata/review_information/demo_user.txt'...
[17:08:51]: Loading './fastlane/metadata/review_information/demo_password.txt'...
[17:08:51]: Loading './fastlane/metadata/review_information/notes.txt'...
[17:08:57]: Will begin uploading metadata for '5.0.1' on App Store Connect
[17:08:57]: Skipping 'release_notes'... this is the first version of the app
[17:08:57]: Uploading metadata to App Store Connect for version
[17:09:00]: Uploading metadata to App Store Connect for localized version 'en-US'
[17:09:01]: Uploading metadata to App Store Connect for localized info 'en-US'
[17:09:05]: Uploading app review information to App Store Connect
[17:09:06]: Error fetching app store review detail - No data
[17:09:09]: Will begin uploading snapshots for '5.0.1' on App Store Connect
[17:09:09]: Starting with the upload of screenshots...
[17:09:14]: Uploaded './fastlane/screenshots/en-US/appStore_4.png'... (3.316193 secs)
[17:09:14]: Uploaded './fastlane/screenshots/en-US/appStore_3.png'... (3.469423 secs)
[17:09:14]: Uploaded './fastlane/screenshots/en-US/appStore_5.png'... (3.50524 secs)
[17:09:14]: Uploaded './fastlane/screenshots/en-US/appStore_2.png'... (3.513161 secs)
[17:09:14]: Uploaded './fastlane/screenshots/en-US/appStore_1.png'... (3.532961 secs)
[17:09:14]: Uploaded './fastlane/screenshots/en-US/appStore_7.png'... (3.615612 secs)
[17:09:14]: Uploaded './fastlane/screenshots/en-US/appStore_6.png'... (3.84562 secs)
[17:09:15]: Uploaded './fastlane/screenshots/en-US/appStore_8.png'... (3.956131 secs)
[17:09:39]: Successfully uploaded all screenshots
[17:09:41]: Successfully uploaded screenshots to App Store Connect
[17:09:41]: App has no prices yet... Enabling all countries in App Store Connect
+------------------+------------+
|         Lane Context          |
+------------------+------------+
| DEFAULT_PLATFORM | ios        |
| PLATFORM_NAME    | ios        |
| LANE_NAME        | ios deploy |
+------------------+------------+
[17:09:45]: The provided entity includes an unknown attribute - 'startDate' is not an attribute on the resource 'appPrices' - /included/0/attributes/startDate
+------+------------------------+-------------+

|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | Verifying fastlane     | 0           |
|      | version                |             |
| 2    | default_platform       | 0           |
| 3    | app_store_connect_api  | 0           |
|      | _key                   |             |
| 4    | Switch to ios          | 0           |
|      | deploy_flutter_to_app  |             |
|      | store lane             |             |
| 💥   | deliver                | 56          |
+------+------------------------+-------------+
[17:09:45]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:

https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
bundler: failed to load command: fastlane (/var/lib/buildben/.rbenv/versions/2.7.2/bin/fastlane)
/private/var/lib/buildben/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/spaceship/lib/spaceship/connect_api/api_client.rb:204:in `handle_response': \e[31m[!] The provided entity includes an unknown attribute - 'startDate' is not an attribute on the resource 'appPrices' - /included/0/attributes/startDate\e[0m (Spaceship::UnexpectedResponse)
	from /private/var/lib/buildben/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/spaceship/lib/spaceship/connect_api/api_client.rb:135:in `patch'
	from /private/var/lib/buildben/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:212:in `patch_app'
	from /private/var/lib/buildben/.rbenv/versions/2.7.2/lib/ruby/2.7.0/forwardable.rb:235:in `patch_app'
	from /private/var/lib/buildben/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/spaceship/lib/spaceship/connect_api/models/app.rb:109:in `update'
	from /private/var/lib/buildben/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/deliver/lib/deliver/upload_price_tier.rb:38:in `upload'
	from /private/var/lib/buildben/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/deliver/lib/deliver/runner.rb:161:in `upload_metadata'
	from /private/var/lib/buildben/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/deliver/lib/deliver/runner.rb:61:in `run'
	from /private/var/lib/buildben/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/actions/upload_to_app_store.rb:22:in `run'
	from /private/var/lib/buildben/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /private/var/lib/buildben/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /private/var/lib/buildben/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /private/var/lib/buildben/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /private/var/lib/buildben/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /private/var/lib/buildben/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /private/var/lib/buildben/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:479:in `block (2 levels) in parsing_binding'
	from /private/var/lib/buildben/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /private/var/lib/buildben/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
	from /private/var/lib/buildben/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
	from /private/var/lib/buildben/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:505:in `block (2 levels) in parsing_binding'
	from /private/var/lib/buildben/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /private/var/lib/buildben/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /private/var/lib/buildben/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /private/var/lib/buildben/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /private/var/lib/buildben/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /private/var/lib/buildben/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /private/var/lib/buildben/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /private/var/lib/buildben/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /private/var/lib/buildben/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /private/var/lib/buildben/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /private/var/lib/buildben/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /private/var/lib/buildben/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /private/var/lib/buildben/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /private/var/lib/buildben/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /private/var/lib/buildben/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /private/var/lib/buildben/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.212.1/bin/fastlane:23:in `<top (required)>'
	from /var/lib/buildben/.rbenv/versions/2.7.2/bin/fastlane:25:in `load'
	from /var/lib/buildben/.rbenv/versions/2.7.2/bin/fastlane:25:in `<top (required)>'
	from /private/var/lib/buildben/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/bundler/cli/exec.rb:58:in `load'
	from /private/var/lib/buildben/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /private/var/lib/buildben/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/bundler/cli/exec.rb:23:in `run'
	from /private/var/lib/buildben/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:478:in `exec'
	from /private/var/lib/buildben/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /private/var/lib/buildben/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /private/var/lib/buildben/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /private/var/lib/buildben/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:31:in `dispatch'
	from /private/var/lib/buildben/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /private/var/lib/buildben/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:25:in `start'
	from /private/var/lib/buildben/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.28/exe/bundle:49:in `block in <top (required)>'
	from /private/var/lib/buildben/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/bundler/friendly_errors.rb:128:in `with_friendly_errors'
	from /private/var/lib/buildben/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.28/exe/bundle:37:in `<top (required)>'
	from /var/lib/buildben/.rbenv/versions/2.7.2/bin/bundle:23:in `load'
	from /var/lib/buildben/.rbenv/versions/2.7.2/bin/bundle:23:in `<main>'

```

### Environment

<details>
 <pre> 
```
[18:49:54]: ▸ swift-driver version: 1.62.15 <summary>✅ fastlane environment ✅</summary>
[18:49:54]: ▸ ### Stack
[18:49:54]: ▸ | Key                         | Value                                               |
[18:49:54]: ▸ | --------------------------- | --------------------------------------------------- |
[18:49:54]: ▸ | OS                          | 13.0.1                                              |
[18:49:54]: ▸ | Ruby                        | 2.7.3                                               |
[18:49:54]: ▸ | Bundler?                    | true                                                |
[18:49:54]: ▸ | Git                         | git version 2.23.0                                  |
[18:49:54]: ▸ | Installation Source         | ~/.rbenv/versions/2.7.3/bin/fastlane                |
[18:49:54]: ▸ | Host                        | macOS 13.0.1 (22A400)                               |
[18:49:54]: ▸ | Ruby Lib Dir                | /private/var/lib/buildben/.rbenv/versions/2.7.3/lib |
[18:49:54]: ▸ | OpenSSL Version             | OpenSSL 1.1.1k  25 Mar 2021                         |
[18:49:54]: ▸ | Is contained                | false                                               |
[18:49:54]: ▸ | Is homebrew                 | false                                               |
[18:49:54]: ▸ | Is installed via Fabric.app | false                                               |
[18:49:54]: ▸ | Xcode Path                  | /Applications/Xcode14.2.app/Contents/Developer/     |
[18:49:54]: ▸ | Xcode Version               | 14.2                                                |
[18:49:54]: ▸ | Swift Version               | 5.7.2                                               |
[18:49:54]: ▸ ### System Locale
[18:49:54]: ▸ | Variable | Value       |   |
[18:49:54]: ▸ | -------- | ----------- | - |
[18:49:54]: ▸ | LANG     | en_US.UTF-8 | ✅ |
[18:49:54]: ▸ | LC_ALL   | en_US.UTF-8 | ✅ |
[18:49:54]: ▸ | LANGUAGE | en_US.UTF-8 | ✅ |
[18:49:54]: ▸ **No Appfile found**
[18:49:54]: ▸ ### fastlane gems
[18:49:54]: ▸ | Gem      | Version | Update-Status |
[18:49:54]: ▸ | -------- | ------- | ------------- |
[18:49:54]: ▸ | fastlane | 2.212.1 | ✅ Up-To-Date  |
[18:49:54]: ▸ ### Loaded fastlane plugins:
[18:49:54]: ▸ | Plugin                                    | Version | Update-Status |
[18:49:54]: ▸ | ----------------------------------------- | ------- | ------------- |
[18:49:54]: ▸ | fastlane-plugin-versioning                | 0.5.1   | ✅ Up-To-Date  |
[18:49:54]: ▸ | fastlane-plugin-firebase_app_distribution | 0.5.0   | ✅ Up-To-Date  |
[18:49:54]: ▸ <details><summary><b>Loaded gems</b></summary>
[18:49:54]: ▸ | Gem                                       | Version      |
[18:49:54]: ▸ | ----------------------------------------- | ------------ |
[18:49:54]: ▸ | did_you_mean                              | 1.4.0        |
[18:49:54]: ▸ | rake                                      | 13.0.6       |
[18:49:54]: ▸ | rexml                                     | 3.2.5        |
[18:49:54]: ▸ | CFPropertyList                            | 3.0.6        |
[18:49:54]: ▸ | concurrent-ruby                           | 1.2.2        |
[18:49:54]: ▸ | i18n                                      | 1.12.0       |
[18:49:54]: ▸ | minitest                                  | 5.17.0       |
[18:49:54]: ▸ | tzinfo                                    | 2.0.6        |
[18:49:54]: ▸ | zeitwerk                                  | 2.6.7        |
[18:49:54]: ▸ | activesupport                             | 6.1.7.2      |
[18:49:54]: ▸ | public_suffix                             | 4.0.7        |
[18:49:54]: ▸ | addressable                               | 2.8.1        |
[18:49:54]: ▸ | httpclient                                | 2.8.3        |
[18:49:54]: ▸ | json                                      | 2.6.3        |
[18:49:54]: ▸ | algoliasearch                             | 1.27.5       |
[18:49:54]: ▸ | artifactory                               | 3.0.15       |
[18:49:54]: ▸ | atomos                                    | 0.1.3        |
[18:49:54]: ▸ | aws-eventstream                           | 1.2.0        |
[18:49:54]: ▸ | aws-partitions                            | 1.716.0      |
[18:49:54]: ▸ | aws-sigv4                                 | 1.5.2        |
[18:49:54]: ▸ | jmespath                                  | 1.6.2        |
[18:49:54]: ▸ | aws-sdk-core                              | 3.170.0      |
[18:49:54]: ▸ | aws-sdk-kms                               | 1.62.0       |
[18:49:54]: ▸ | aws-sdk-s3                                | 1.119.1      |
[18:49:54]: ▸ | babosa                                    | 1.0.4        |
[18:49:54]: ▸ | blockenspiel                              | 0.5.0        |
[18:49:54]: ▸ | bundler                                   | 2.1.4        |
[18:49:54]: ▸ | claide                                    | 1.1.0        |
[18:49:54]: ▸ | fuzzy_match                               | 2.0.4        |
[18:49:54]: ▸ | nap                                       | 1.1.0        |
[18:49:54]: ▸ | netrc                                     | 0.11.0       |
[18:49:54]: ▸ | ffi                                       | 1.15.5       |
[18:49:54]: ▸ | ethon                                     | 0.16.0       |
[18:49:54]: ▸ | typhoeus                                  | 1.4.0        |
[18:49:54]: ▸ | cocoapods-core                            | 1.11.3       |
[18:49:54]: ▸ | cocoapods-deintegrate                     | 1.0.5        |
[18:49:54]: ▸ | cocoapods-downloader                      | 1.6.3        |
[18:49:54]: ▸ | cocoapods-plugins                         | 1.0.0        |
[18:49:54]: ▸ | cocoapods-search                          | 1.0.1        |
[18:49:54]: ▸ | cocoapods-trunk                           | 1.6.0        |
[18:49:54]: ▸ | cocoapods-try                             | 1.2.0        |
[18:49:54]: ▸ | colored2                                  | 3.1.2        |
[18:49:54]: ▸ | escape                                    | 0.0.4        |
[18:49:54]: ▸ | fourflusher                               | 2.3.1        |
[18:49:54]: ▸ | gh_inspector                              | 1.1.3        |
[18:49:54]: ▸ | molinillo                                 | 0.8.0        |
[18:49:54]: ▸ | ruby-macho                                | 2.5.1        |
[18:49:54]: ▸ | nanaimo                                   | 0.3.0        |
[18:49:54]: ▸ | xcodeproj                                 | 1.22.0       |
[18:49:54]: ▸ | cocoapods                                 | 1.11.3       |
[18:49:54]: ▸ | colored                                   | 1.2          |
[18:49:54]: ▸ | highline                                  | 2.0.3        |
[18:49:54]: ▸ | commander                                 | 4.6.0        |
[18:49:54]: ▸ | declarative                               | 0.0.20       |
[18:49:54]: ▸ | digest-crc                                | 0.6.4        |
[18:49:54]: ▸ | unf_ext                                   | 0.0.8.2      |
[18:49:54]: ▸ | unf                                       | 0.1.4        |
[18:49:54]: ▸ | domain_name                               | 0.5.20190701 |
[18:49:54]: ▸ | dotenv                                    | 2.8.1        |
[18:49:54]: ▸ | emoji_regex                               | 3.2.3        |
[18:49:54]: ▸ | excon                                     | 0.99.0       |
[18:49:54]: ▸ | faraday-em_http                           | 1.0.0        |
[18:49:54]: ▸ | faraday-em_synchrony                      | 1.0.0        |
[18:49:54]: ▸ | faraday-excon                             | 1.1.0        |
[18:49:54]: ▸ | faraday-httpclient                        | 1.0.1        |
[18:49:54]: ▸ | multipart-post                            | 2.0.0        |
[18:49:54]: ▸ | faraday-multipart                         | 1.0.4        |
[18:49:54]: ▸ | faraday-net_http                          | 1.0.1        |
[18:49:54]: ▸ | faraday-net_http_persistent               | 1.2.0        |
[18:49:54]: ▸ | faraday-patron                            | 1.0.0        |
[18:49:54]: ▸ | faraday-rack                              | 1.0.0        |
[18:49:54]: ▸ | faraday-retry                             | 1.0.3        |
[18:49:54]: ▸ | ruby2_keywords                            | 0.0.5        |
[18:49:54]: ▸ | faraday                                   | 1.10.3       |
[18:49:54]: ▸ | http-cookie                               | 1.0.5        |
[18:49:54]: ▸ | faraday-cookie_jar                        | 0.0.7        |
[18:49:54]: ▸ | faraday_middleware                        | 1.2.0        |
[18:49:54]: ▸ | fastimage                                 | 2.2.6        |
[18:49:54]: ▸ | jwt                                       | 2.7.0        |
[18:49:54]: ▸ | memoist                                   | 0.16.2       |
[18:49:54]: ▸ | multi_json                                | 1.15.0       |
[18:49:54]: ▸ | os                                        | 1.1.4        |
[18:49:54]: ▸ | signet                                    | 0.17.0       |
[18:49:54]: ▸ | googleauth                                | 1.3.0        |
[18:49:54]: ▸ | mini_mime                                 | 1.1.2        |
[18:49:54]: ▸ | trailblazer-option                        | 0.1.2        |
[18:49:54]: ▸ | uber                                      | 0.1.0        |
[18:49:54]: ▸ | representable                             | 3.2.0        |
[18:49:54]: ▸ | retriable                                 | 3.1.2        |
[18:49:54]: ▸ | webrick                                   | 1.8.1        |
[18:49:54]: ▸ | google-apis-core                          | 0.11.0       |
[18:49:54]: ▸ | google-apis-androidpublisher_v3           | 0.34.0       |
[18:49:54]: ▸ | google-apis-playcustomapp_v1              | 0.13.0       |
[18:49:54]: ▸ | google-apis-iamcredentials_v1             | 0.17.0       |
[18:49:54]: ▸ | google-apis-storage_v1                    | 0.19.0       |
[18:49:54]: ▸ | google-cloud-env                          | 1.6.0        |
[18:49:54]: ▸ | google-cloud-errors                       | 1.3.0        |
[18:49:54]: ▸ | google-cloud-core                         | 1.6.0        |
[18:49:54]: ▸ | google-cloud-storage                      | 1.44.0       |
[18:49:54]: ▸ | mini_magick                               | 4.12.0       |
[18:49:54]: ▸ | naturally                                 | 2.2.1        |
[18:49:54]: ▸ | optparse                                  | 0.1.1        |
[18:49:54]: ▸ | plist                                     | 3.7.0        |
[18:49:54]: ▸ | rubyzip                                   | 2.3.2        |
[18:49:54]: ▸ | security                                  | 0.1.3        |
[18:49:54]: ▸ | simctl                                    | 1.6.10       |
[18:49:54]: ▸ | terminal-notifier                         | 2.0.0        |
[18:49:54]: ▸ | unicode-display_width                     | 1.8.0        |
[18:49:54]: ▸ | terminal-table                            | 1.8.0        |
[18:49:54]: ▸ | tty-screen                                | 0.8.1        |
[18:49:54]: ▸ | tty-cursor                                | 0.7.1        |
[18:49:54]: ▸ | tty-spinner                               | 0.9.3        |
[18:49:54]: ▸ | word_wrap                                 | 1.0.0        |
[18:49:54]: ▸ | rouge                                     | 2.0.7        |
[18:49:54]: ▸ | xcpretty                                  | 0.3.0        |
[18:49:54]: ▸ | xcpretty-travis-formatter                 | 1.0.1        |
[18:49:54]: ▸ | fastlane-plugin-firebase_app_distribution | 0.5.0        |
[18:49:54]: ▸ | fastlane-plugin-versioning                | 0.5.1        |
[18:49:54]: ▸ | versionomy                                | 0.5.0        |
[18:49:54]: ▸ | xcode-install                             | 2.8.1        |
```
</pre>
</details>

**Comment by PWhittle86** [comment] 2023-03-06 10:07
Issue is occurring for me too. Command executed:

```
deliver(
username: USERNAME,
app_identifier: APP_BUNDLE_ID,
force: true,
metadata_path: './fastlane/metadata/',
app_rating_config_path: './fastlane/metadata/rating_config.json',
skip_screenshots: true,
copyright: COPYRIGHT,
price_tier: 0,
skip_binary_upload: true,
app_version: APP_VERSION,
team_id: APP_STORE_CONNECT_TEAM_ID,
api_key: API_KEY,
precheck_include_in_app_purchases: false
)
```
Caps variables have been getting replaced with required data and were working successfully until 3/3/23.

**Comment by mfradcourt** [comment] 2023-03-06 10:54
Same issue here

**Comment by dsmyrnaios** [comment] 2023-03-06 12:54
Same issue here too!

**Comment by lucas-koontz** [comment] 2023-03-06 22:08
AFAIK it's being caused by this [line](https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/connect_api/tunes/tunes.rb#L164).

I did a monkey patch to solve the issue on my end temporarily.

**Comment by Glaubenio** [comment] 2023-03-09 20:17
@lucas-koontz can you share your monkey patch?

**Comment by lutech-uno** [comment] 2023-03-13 09:13
Same issue!

**Comment by pratikathubilo** [comment] 2023-03-16 11:03
> I believe it's being caused by this [line](https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/connect_api/tunes/tunes.rb#L164).
> 
> I did a monkey patch to solve the issue on my end temporarily.

Hey @lucas-koontz I'm not sure how to do this, but could you please help me with solving this temporarily? Perhaps a link to somewhere I could understand what a monkey patch is and how can I add it to my lane?

**Comment by PWhittle86** [comment] 2023-03-16 11:14
@Glaubenio , @pratikathubilo 

I tried commenting out the line of code that Lucas highlighted and my latest upload has worked as expected. 

To do this:

- Find fastlane in your machine. I installed it with Brew and found it in: `/usr/local/Cellar/fastlane/2.212.1/libexec/gems`
- find the file `fastlane/fastlane/blob/master/spaceship/lib/spaceship/connect_api/tunes/tunes.rb` in the version of fastlane installed on your machine.
- Comment out line 164 (`startDate: nil`) and save the file. 
- Run fastlane to see if it worked.

Your mileage may vary, but this worked for me until one of the Fastlane guys can do a proper fix. My suspicion is this is related to the changes Apple are making for app store pricing.

**Comment by Mehdzor** [comment] 2023-04-13 08:54
@lucas-koontz the issue is still there. Can you fix it, please? Keeping the monkey patch on the CI/CD is challenging.

**Comment by Mehdzor** [comment] 2023-04-13 13:48
Fastlane, any news on this one?

**Comment by trinitiwowka** [comment] 2023-04-13 14:04
any news on this one? (2)

**Comment by trinitiwowka** [comment] 2023-04-19 08:58
I got error "The provided entity includes an unknown attribute - 'startDate' is not an attribute on the resource 'appPrices' - /included/0/attributes/startDate" When `price_tier: 0`
and " 'price_tier' value must be a Integer! Found String instead" when `price_tier: 'NONE'`

**Comment by msangals** [comment] 2023-05-10 12:22
Any news on this one?

**Comment by shizu2014** [comment] 2023-07-19 14:00
Is there any news on this?

**Comment by christruong90** [comment] 2023-07-27 20:29
Just started seeing this issue since last update as well

**Comment by PWhittle86** [comment] 2023-08-03 09:21
Chasing up - issue remains outstanding.

**Comment by davidfrasch** [comment] 2023-08-17 13:22
Still an issue

**Comment by mathsnunes** [comment] 2023-08-22 14:57
Hi guys,

Any news here? Is there a PR opened for this issue?

**Comment by PWhittle86** [comment] 2023-09-19 16:46
Issue remains outstanding - just had to reapply the workaround for the latest version of Fastlane. Any updates?

**Comment by rogerluan** [comment] 2023-11-14 04:37
https://github.com/fastlane/fastlane/pull/21633 intends to fix this issue and got merged earlier today. Expect this to be in the very next _fastlane_ release 🙏

**Closed by rogerluan** 2023-11-14 04:37 UTC
