### ISSUE TITLE
Sigh with enabled 'force' recreates profile with first available cert 

### ISSUE THREAD

**Issue by bartoszpolaczykmw** [fastlane/fastlane#8010] opened 2017-01-26 10:46 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Sigh with enabled `force` does remove old profile and creates new one according to all parameters provided. In case of Apple Developer Program, where two certificates are available (popular for enterprise teams) first one is taken. 

```
Found more than one code signing identity. Choosing the first one. Check out `fastlane sigh --help` to see all available options.
[08:36:41]: Available Code Signing Identities for current filters:
[08:36:41]: 	- Name: XXXXXXXX - ID: XXXXXXXXXXX - Expires 03/11/2017
[08:36:41]: 	- Name: XXXXXXXX - ID: XXXXXXXXXXX - Expires 05/11/2018
[08:36:42]: Creating new provisioning profile for '*' with name XXXXXX for ios platform'
[08:36:45]: Downloading provisioning profile...
[08:36:48]: Successfully downloaded provisioning profile...
```

Previous fastlane version created profile with the same certificate as previously (technically it updated old one instead of creating new one).

Change has changed in: https://github.com/fastlane/fastlane/pull/6518/files/52c57be3c345baa7a0d7d1ac300fe4fec9ad41b1

#### Expected behavior(s)

* Fastlane uses the same cert that was used for old provisioning profile
* I could also imagine that fastlane prefers certificate that is available on local machine rather than the first one (random)

#### Workaround

You can specify `cert_id` but this links fastlane configuration (committed to git) with theoretically volatile ID of a cert.

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                           |
| ------------------- | ----------------------------------------------- |
| OS                  | 10.12.2                                         |
| Ruby                | 2.3.3                                           |
| Bundler?            | false                                           |
| Git                 | git version 2.10.1 (Apple Git-78)               |
| Installation Source | /usr/local/bin/fastlane                         |
| Host                | Mac OS X 10.12.2 (16C67)                        |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.3.3/lib                |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                     |
| Is contained        | false                                           |
| Xcode Path          | /Applications/Xcode_820.app/Contents/Developer/ |
| Xcode Version       | 8.2                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.11.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| plist                     | 3.2.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.1        |
| excon                     | 0.54.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
| faraday_middleware        | 0.10.1       |
| io-console                | 0.4.5        |
| rubyzip                   | 1.2.0        |
| terminal-table            | 1.7.3        |
| unicode-display_width     | 1.1.2        |
</details>

*generated on:* **2017-01-26**
</details>

**Comment by younatics** [comment] 2017-02-01 06:22
Could I ask why you use `force: true?` Actually, I don't think you need to use force with your situation.

**Comment by bartoszpolaczykmw** [comment] 2017-02-01 06:26
Just to always use Provisioning Profile that expires in 365 days. 
This is especially useful for Enterprise Team where ipa are directly installed on employee's devices (without AppStore).

**Comment by bartoszpolaczykrailwaymen** [comment] 2017-04-07 12:24
Still observed on fastlane 2.26, 

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rbenv/versions/2.4.0/bin/fastlane        |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.0/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby

default_platform :ios



platform :ios do
  
  lane :sig do
    sigh(force:true, provisioning_name:"BPDistTest",app_identifier:"*", output_path:"output",filename:"demo.mobileprovision")
  end

end```
</details>

**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.26.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170223 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| i18n                      | 0.8.1        |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.10.1       |
| activesupport             | 4.2.8        |
| io-console                | 0.4.6        |
| openssl                   | 2.0.2        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
</details>


*generated on:* **2017-04-07**
</details>

**Comment by KrauseFx** [comment] 2017-05-08 09:34
We'd recommend using _match_ as it would take care of exactly this. 

Could you tell me a little more about why `cert_id` doesn't work?

**Comment by polac24** [comment] 2017-05-08 09:48
Thanks @KrauseFx  for reply!

`cert_id` workaround works, but I was afraid that _sigh_ introduced regression (with unintended behaviour). Since you recommend _match_, you can close this issue

**Comment by KrauseFx** [comment] 2017-05-08 12:32
Sounds good 👍  What regression do you refer to?

**Closed by KrauseFx** 2017-05-08 12:32 UTC

**Comment by polac24** [comment] 2017-05-08 12:37
before https://github.com/fastlane/fastlane/pull/6518/files/52c57be3c345baa7a0d7d1ac300fe4fec9ad41b1
`sigh(force:true, ...` **always** generated provisioning profile with exactly the same `cert_id`. 

Nowadays it may select different `cert_id` if you are unlucky (so behaviour has changed).
