### ISSUE TITLE
Upgrading to Mac OS Catalina and everything's failed

### ISSUE THREAD

**Issue by fortydegrees** [fastlane/fastlane#15582] opened 2019-11-02 12:37 UTC
I've been stuck on this all day and I'm giving up:

```
[12:33:49]: -----------------------
[12:33:49]: --- Step: cocoapods ---
[12:33:49]: -----------------------
[12:33:50]: $ bundle exec pod install
[12:33:50]: ▸ Installing locked Bundler version 2.0.2...
[12:33:51]: ▸ Installing the inferred bundler version (= 2.0.2) failed.
[12:33:51]: ▸ If you'd like to update to the current bundler version (1.14.6) in this project, run `bundle update --bundler`.
[12:33:51]: ▸ The error was: bundler requires Ruby version >= 2.3.0.
```

This is from a fresh install of fastlane after trying to uninstall it and reinstall.

ruby -v returns: ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin19]

bundler -v returns: Bundler version 2.0.2

head -n1 $(which bundle) returns: #!/usr/local/Cellar/ruby/2.6.5/bin/ruby

i've tried updating ruby with homebrew, gem, all of that. 'pod install' on its own was failing but then I just chown -R'd my whole filesystem and that stopped failing. 

I think, for some reason, bundle is using an old version of ruby, but I can't get anything to use that incompatible version of ruby. I have no clue what's going on here.

it's also similar to this issue: https://github.com/fastlane-community/fastlane-plugin-appicon/issues/52

which is what i was originally getting before i uninstalled as a last resort.

**Comment by fortydegrees** [comment] 2019-11-02 12:40
Sure, my pleasure:
```

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15                                       |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.21.0 (Apple Git-122.2)        |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.15 (19A583)                     |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.2                                        |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.3"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "ballpark.ballparky" # The bundle identifier of your app
apple_id "david@playballpark.com" # Your Apple email address

team_id "FXFD4JHGXH" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.28.3  | 💥 Check failed |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.13.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.55.0       |
| faraday                   | 0.17.0       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.13.1       |
</details>


*generated on:* **2019-11-02**
</details>
```

**Comment by fortydegrees** [comment] 2019-11-02 12:46
Okay, I got somewhere:

I switched to bash (exec bash) and downloaded: https://download.fastlane.tools/

which fixed it. All of the previous answers you get from googling didn't work

**Comment by fortydegrees** [comment] 2019-11-02 12:59
I think it was the switch from bash to zsh that didn't help either

**Comment by fortydegrees** [comment] 2019-11-02 13:06
worth noting, for anyone else coming across this, that with 

fastlane beta

i still get the original error:

[13:05:08]: Plugin 'appicon' was not properly loaded, make sure to follow the plugin docs for troubleshooting: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/PluginsTroubleshooting.md

which takes me down the failure rabbit hole

bundle exec fastlane beta, however, works fine.

**Comment by janpio** [comment] 2019-11-03 19:54
Your original problem was a duplicate of this: https://github.com/fastlane/fastlane/issues/15496

If you have other problems, please open a new issue.

**Closed by janpio** 2019-11-03 19:54 UTC
Labels: topic: installation, topic: macOS Catalina
