### ISSUE TITLE
fastlane taking too much time to create or regenerate profiles

### ISSUE THREAD

**Issue by santoshshetty2612** [fastlane/fastlane#9040] opened 2017-05-02 17:02 UTC
Hi,

From past few days I have observed that fastlane is taking too much time to create or regenerate profiles.

Most of the time its stuck on the line:
Verifying that the certificate and profile are still valid on the Dev Portal...

To generate some 10 profiles it took more than 20 hours.

Seems something has changed on Apple end.

I am using match with array of App Ids.

Everything worked well two weeks back.

**Comment by KrauseFx** [comment] 2017-05-02 17:26
Could you share the complete output too, so we can see the time stamps next to the output?

**Comment by santoshshetty2612** [comment] 2017-05-02 17:31
sure @KrauseFx Is there a way I can send the output privately. It contains my app ids which I would prefer to keep it private.

**Comment by stevewallis** [comment] 2017-05-03 12:12
I am using cert & sigh, rather than match, but I have observed the same behaviour for the past ~2 weeks. 
I am currently working on removing cert & sigh from my standard adhoc build and placing them in an optional lane (and caching their results) because they take approx 2 hours to run now.

Here is a sample output from an adhoc build with timestamps:
````
[11:02:02]: ------------------
[11:02:02]: --- Step: cert ---
[11:02:02]: ------------------

+---------------+--------------------------------------------------+
|                     Summary for cert 2.28.4                      |
+---------------+--------------------------------------------------+
| development   | false                                            |
| force         | false                                            |
| username      | xxxxxxx@xxxxxx.com                           |
| team_id       | XXXXXXXXXX                                       |
| team_name     | XXXXXXXXXX                                    |
| keychain_path | /Users/xxxxx/Library/Keychains/login.keychain-db |
| platform      | ios                                              |
+---------------+--------------------------------------------------+

[11:02:02]: Starting login with user 'xxxxxxx@xxxxxx.com'
[11:08:16]: Successfully logged in
[11:57:52]: Found the certificate XXXXXXXX (iOS Distribution) which is installed on the local machine. Using this one.
[11:57:52]: Verifying the certificate is properly installed locally...
[11:57:52]: Successfully installed certificate XXXXXXXXXX
[11:57:52]: Use signing certificate 'XXXXXXXXX' from now on!
[11:57:52]: ------------------
[11:57:52]: --- Step: sigh ---
[11:57:52]: ------------------

+-------------------------------------+--------------------------+
|                    Summary for sigh 2.28.4                     |
+-------------------------------------+--------------------------+
| adhoc                               | true                     |
| force                               | true                     |
| development                         | false                    |
| skip_install                        | false                    |
| app_identifier                      | xxxxxxxxx |
| username                            | xxxxxxx@xxxxxx.com   |
| team_id                             | XXXXXXXX               |
| team_name                           | XXXXXXXX            |
| ignore_profiles_with_different_name | false                    |
| cert_id                             | XXXXXXX               |
| skip_fetch_profiles                 | false                    |
| skip_certificate_verification       | false                    |
| platform                            | ios                      |
+-------------------------------------+--------------------------+

[11:57:52]: Starting login with user 'xxxxxxxx@xxxxxxx.com'
[12:04:07]: Successfully logged in
[12:04:07]: Fetching profiles...
[12:04:10]: Verifying certificates...
[12:10:23]: Found 1 matching profile(s)
[12:10:23]: Recreating the profile
[12:35:07]: Creating new provisioning profile for 'xxxxxxxxxx' with name 'xxxxxxxxxx AdHoc' for 'ios' platform
[12:47:31]: Downloading provisioning profile...
[13:00:01]: Successfully downloaded provisioning profile...
[13:00:01]: Installing provisioning profile...
/Users/xxxxx/.jenkins/jobs/xxxxxxx/workspace/xxxxxxxxx.mobileprovision
[13:00:01]: Setting Provisioning Profile type to 'ad-hoc'
[13:00:01]: -----------------
[13:00:01]: --- Step: gym ---
[13:00:01]: -----------------
````

Note, the slow calls are not always the same, it will stall at different points each time. Occasionally it stalls long enough for ruby to simply log 'execution expired' and the build fails.

I also logged in via the interactive mode of Spaceship, and occasionally calls simply do not respond. Often in testing, if I run the same call twice it will respond immediately once, and not at all the second time.

**Comment by stevewallis** [comment] 2017-05-03 13:28
Okay, we've done some more investigating.
It seems it is an Apple server problem, but not with all their servers.
I am in France, and by default, my `developer.apple.com` is resolving to a block of servers in Amsterdam eg 
`nlams2-vip-bx-001.aaplimg.com`, `nlams2-vip-bx-002.aaplimg.com` etc
I forced my server to resolve it to a US West coast block of servers eg
`ussjc2-vip-bx-001.aaplimg.com` etc 
and the problem disappears.
I think apple need to reboot their servers in NL :)

**Comment by santoshshetty2612** [comment] 2017-05-03 13:36
Hi @stevewallis Is there a way in fastlane I can point to the US West coast block servers?

**Comment by manuelblum** [comment] 2017-05-03 14:27
Thanks @stevewallis ! I had the same problem. 

adding folowing line to /etc/hosts temporary solves my issue
`17.253.5.201    developer.apple.com`

**Comment by stevewallis** [comment] 2017-05-03 14:36
Yeah, I also had to hack it with `/etc/hosts` for now, which is not a good solution, but at least my builds are working again. Hopefully apple resolves the issue with the NL servers.

**Comment by KrauseFx** [comment] 2017-05-03 16:02
Thanks for sharing the details, this is super interesting. Do you think that will be resolved soon? Should we build some kind of check for this into _fastlane_?

**Comment by santoshshetty2612** [comment] 2017-05-03 19:11
worked for me too after adding 17.253.5.201 developer.apple.com in  /etc/hosts

**Comment by KrauseFx** [comment] 2017-05-04 10:26
Thanks everyone, that's very interesting.

To sum up, the Developer Portal servers in Europe are slower than the ones in the U.S. by a factor of about 100. To directly access the U.S. based Developer Portal servers, you have to edit your `/etc/hosts` files using `sudo nano /etc/hosts` (or any other text editor) and append

```
17.253.5.201 developer.apple.com
```

Please make sure to remove that entry again in a few days/weeks, depending on when the issue is resolved.

**Comment by stevewallis** [comment] 2017-05-04 10:44
@KrauseFx no idea for a fix time, got an apple contact? Hopefully it's just a one off issue and it will be resolved.

re: a fastlane fix - 
Currently, it tries to make the SSL connection but gets stuck in SYN_SENT, with no ack coming back, so i guess that means their server is ignoring the packets for some reason. 
I suppose you could check after x amount of time if the connection has received 0 bytes, and if so then force your requests to switch to a different server region?

**Comment by stevewallis** [comment] 2017-05-05 14:37
Update - we notified Apple, and they sent us back a message to retry the Amsterdam servers and they seem to be working again, so you can all probably remove that hack from /etc/hosts.

**Comment by KrauseFx** [comment] 2017-05-05 16:03
Awesome, thanks for confirming @stevewallis

**Comment by KrauseFx** [comment] 2017-05-05 16:35
I'll close this issue for now

**Closed by KrauseFx** 2017-05-05 16:35 UTC
Labels: match
