### ISSUE TITLE
Uploading App Icon Causes iTunes Connect 500

### ISSUE THREAD

**Issue by JustinJiaDev** [fastlane/fastlane#6425] opened 2016-10-06 08:25 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

A successful `fastlane release` will make subsequent `fastlane release` fail. iTunes connect will return `Error: 500 Internal Server Error`. After a few minutes iTunes connect will recover. Then I can upload again. It seems like this issue happens after I added `app_icon` to `Deliverfile`.

It's a iMessage sticker pack app.

##### Complete output when running fastlane, including the stack trace and command used

```
[01:13:29]: -------------------------------------------------
[01:13:29]: --- Step: Verifying required fastlane version ---
[01:13:29]: -------------------------------------------------
[01:13:29]: Your fastlane version 1.105.0 matches the minimum requirement of 1.104.0  ✅
[01:13:29]: ------------------------------
[01:13:29]: --- Step: default_platform ---
[01:13:29]: ------------------------------
[01:13:29]: Driving the lane 'ios meta' 🚀
[01:13:29]: ---------------------
[01:13:29]: --- Step: deliver ---
[01:13:29]: ---------------------
[01:13:29]: Login to iTunes Connect (#########)
[01:13:30]: Login successful

+--------------------------------------+---------------------------------------+
|                            deliver 1.14.0 Summary                            |
+--------------------------------------+---------------------------------------+
| force                                | true                                  |
| skip_binary_upload                   | true                                  |
| skip_screenshots                     | true                                  |
| app_review_information.first_name    | #####                                |
| app_review_information.last_name     | ###                                   |
| app_review_information.phone_number  | #####                     |
| app_review_information.email_address | ######        |
| app_rating_config_path               | ../../Metadata/default_ratings.json   |
| app_icon                             | ../../Metadata/Images/Icon.png |
| price_tier                           | 2                                     |
| automatic_release                    | true                                  |
| screenshots_path                     | ./fastlane/screenshots                |
| metadata_path                        | ./fastlane/metadata                   |
| username                             | #####                  |
| app_identifier                       | #####          |
| skip_metadata                        | false                                 |
| submit_for_review                    | false                                 |
| dev_portal_team_id                   | #####                            |
+--------------------------------------+---------------------------------------+

[01:13:31]: Loading './fastlane/metadata/en-US/description.txt'...
[01:13:31]: Loading './fastlane/metadata/en-US/keywords.txt'...
[01:13:31]: Loading './fastlane/metadata/en-US/support_url.txt'...
[01:13:31]: Loading './fastlane/metadata/en-US/marketing_url.txt'...
[01:13:31]: Loading './fastlane/metadata/en-US/name.txt'...
[01:13:31]: Loading './fastlane/metadata/en-US/privacy_url.txt'...
[01:13:31]: Loading './fastlane/metadata/copyright.txt'...
[01:13:31]: Loading './fastlane/metadata/primary_category.txt'...
[01:13:31]: Loading './fastlane/metadata/secondary_category.txt'...
[01:13:31]: Loading './fastlane/metadata/primary_first_sub_category.txt'...
[01:13:31]: Loading './fastlane/metadata/primary_second_sub_category.txt'...
[01:13:31]: Loading './fastlane/metadata/secondary_first_sub_category.txt'...
[01:13:31]: Loading './fastlane/metadata/secondary_second_sub_category.txt'...
[01:13:31]: Activating language en-US...
[01:13:33]: Uploading metadata to iTunes Connect
[01:13:34]: Successfully uploaded initial set of metadata to iTunes Connect
[01:13:36]: Price Tier unchanged (tier #)
[01:13:36]: Uploading app icon...
[01:13:41]: Finished the upload to iTunes Connect

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | deliver                             | 12          |
+------+-------------------------------------+-------------+

[01:13:41]: fastlane.tools finished successfully 🎉
[01:13:42]: -------------------------------------------------
[01:13:42]: --- Step: Verifying required fastlane version ---
[01:13:42]: -------------------------------------------------
[01:13:42]: Your fastlane version 1.105.0 matches the minimum requirement of 1.104.0  ✅
[01:13:42]: ------------------------------
[01:13:42]: --- Step: default_platform ---
[01:13:42]: ------------------------------
[01:13:42]: Driving the lane 'ios meta' 🚀
[01:13:42]: ---------------------
[01:13:42]: --- Step: deliver ---
[01:13:42]: ---------------------
[01:13:42]: Login to iTunes Connect (######)
[01:13:43]: Login successful
[01:13:43]: Variable Dump:
[01:13:43]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios meta"}
[01:13:43]: {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Unexpected Error"], "info"=>nil}, "statusCode"=>"ERROR"}

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 💥    | deliver                             | 1           |
+------+-------------------------------------+-------------+

[01:13:43]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Unexpected Error
   https://github.com/fastlane/fastlane/issues/3032 [closed] 2 💬
   2 weeks ago

➡️  Unexpected Response error when Running 'Spaceship::Tunes::Application.all'
   https://github.com/fastlane/fastlane/issues/3908 [closed] 1 💬
   2 weeks ago

➡️  Deliver fails to create a new version in iTunes Connect for a Mac App
   https://github.com/fastlane/fastlane/issues/6152 [open] 5 💬
   a week ago

and 4 more at: https://github.com/fastlane/fastlane/search?q=%7B%22data%22=%3Enil,%20%22messages%22=%3E%7B%22warn%22=%3Enil,%20%22error%22=%3E[%22Unexpected%20Error%22],%20%22info%22=%3Enil%7D,%20%22statusCode%22=%3E%22ERROR%22%7D&type=Issues&utf8=✓
/usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.34.2/lib/spaceship/client.rb:453:in `parse_response': [!] {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Unexpected Error"], "info"=>nil}, "statusCode"=>"ERROR"} (Spaceship::Client::UnexpectedResponse)
	from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.34.2/lib/spaceship/tunes/tunes_client.rb:201:in `applications'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.34.2/lib/spaceship/tunes/application.rb:56:in `all'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.34.2/lib/spaceship/tunes/application.rb:62:in `find'
	from /usr/local/lib/ruby/gems/2.3.0/gems/deliver-1.14.0/lib/deliver/detect_values.rb:26:in `find_app'
	from /usr/local/lib/ruby/gems/2.3.0/gems/deliver-1.14.0/lib/deliver/detect_values.rb:5:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/deliver-1.14.0/lib/deliver/runner.rb:8:in `initialize'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.105.0/lib/fastlane/actions/deliver.rb:18:in `new'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.105.0/lib/fastlane/actions/deliver.rb:18:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.105.0/lib/fastlane/runner.rb:202:in `block (2 levels) in execute_action'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.105.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.105.0/lib/fastlane/runner.rb:187:in `block in execute_action'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.105.0/lib/fastlane/runner.rb:186:in `chdir'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.105.0/lib/fastlane/runner.rb:186:in `execute_action'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.105.0/lib/fastlane/runner.rb:112:in `trigger_action_by_name'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.105.0/lib/fastlane/fast_file.rb:140:in `method_missing'
	from Fastfile:23:in `block (2 levels) in parsing_binding'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.105.0/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.105.0/lib/fastlane/runner.rb:49:in `block in execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.105.0/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.105.0/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.105.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.105.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.105.0/lib/fastlane/commands_generator.rb:49:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.52.1/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.105.0/lib/fastlane/commands_generator.rb:244:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.105.0/lib/fastlane/commands_generator.rb:20:in `start'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.105.0/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.105.0/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
fastlane_version "1.104.0"
default_platform :ios
platform :ios do
  desc "Create a new app"
  lane :create do
    produce(
      username: "#####",
      app_identifier: "####",
      app_name: "#####",
      app_version: "1.0",
      language: "English",
      sku: "#####",
      skip_itc: true
    )
  end
  desc "Deploy a new version to the App Store"
  lane :release do
    gym(scheme: "StickerPackExtension")
    deliver(force: true)
  end
  desc "Deploy a new metadata to the App Store"
  lane :meta do
    deliver(force: true, skip_binary_upload: true, skip_screenshots: true)
  end
end
```

Deliverfile:
```ruby
app_review_information(
  first_name: "###",
  last_name: "###",
  phone_number: "###",
  email_address: "#####",
)
app_rating_config_path "../../Metadata/default_ratings.json"
app_icon "../../Metadata/Images/Icon.png"
price_tier 2
automatic_release true
```

### Environment

fastlane version (run `fastlane -v`): fastlane 1.105.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? No

**Comment by KrauseFx** [comment] 2016-10-06 18:06
Could you update to the latest _deliver_ release?

**Comment by drakar4ik** [comment] 2016-10-07 08:35
same problem. After uploading icon via deliver the app is unavailable a few minutes. In iTunes app's page redirects to wa/defaultError. Looks like there is some icon processing or something else...

**Comment by drakar4ik** [comment] 2016-10-07 08:51
i'm changed icon one more time: in iTunes app's page redirects to wa/defaultError, my-apps page returns error 500. The problem taked about 15 seconds.

**Comment by bucengyongyou** [comment] 2016-10-10 03:09
meet the same problem! 
if i dont upload icon, it's ok
if i upload icon, then the iTunes app's page tell a error ,and then after few minutes, it goes well

**Comment by iWaiterDeveloper** [comment] 2016-10-11 11:02
Getting 500 error after deliver too. Using the latest available version

**Comment by TKBurner** [comment] 2016-10-11 14:59
@iWaiterDeveloper @bucengyongyou @drakar4ik Does this persist on a blank project or just a pre-existing project? We'd love to get exact repro steps so I can send this out to the core team. Thanks so much!

**Comment by JustinJiaDev** [comment] 2016-10-12 07:25
For me, it's a project that hasn't been reviewed.

**Comment by bucengyongyou** [comment] 2016-10-12 07:58
@TKBurner   
For me ,it's a project that already exist
First i create a new version of a app in itunesconnect and use deliver to upload icon 
then the iTunes app's page tell a error

**Comment by drakar4ik** [comment] 2016-10-12 08:54
For me, it's a new app with "Prepare for Submission" status. Every deliver (with different icon names) makes app (sometime MyApps page) unavailable for 10sec-7minutes.

**Comment by TKBurner** [comment] 2016-10-12 19:01
@JustinJiaDev @bucengyongyou Can you verify that you are seeing the same behavior as @drakar4ik. 

After running deliver you can't access the app in iTC for several minutes?

Thanks!

**Comment by JustinJiaDev** [comment] 2016-10-12 19:25
Yes. I can't access the app in iTunes Connect for several minutes. Sometimes, I can't access all my apps in the iTunes Connect.

**Comment by bucengyongyou** [comment] 2016-10-13 02:29
i have tested a new created app
the same with @drakar4ik

**Comment by Wojcik** [comment] 2016-10-13 08:52
For me it's a 500 error and I can't see any of our apps for a 5-10 mins after uploading a new version **with an icon** for existing application.

**Comment by TKBurner** [comment] 2016-10-13 16:56
@Wojcik @bucengyongyou @JustinJiaDev Thanks for following up. I sent this out to the core team, however this appears to be a behavior of iTC/API so I'm not sure we can change anything. Thanks!

**Comment by ohwutup** [comment] 2016-10-17 18:17
We are going to close this as it appears to be a dupe of: https://github.com/fastlane/fastlane/issues/6455

**Closed by ohwutup** 2016-10-17 18:17 UTC
Labels: awaiting-reply, bug, deliver

**Comment by asfalcone** [comment] 2016-10-21 20:01
_deliver_ 1.14.3 has been released to fix this! 🚀
