### ISSUE TITLE
Android: creation of a new application on the play market

### ISSUE THREAD

**Issue by lastspringday** [fastlane/fastlane#11821] opened 2018-02-12 13:34 UTC
I have read all android part of the fastlane documentation and I have not found an answer:
Is Fastlane able to create a new application on the play market? Or it is just updates the existed ones?

Thank you in advance

**Comment by KrauseFx** [comment] 2018-02-12 14:44
Duplicate of https://github.com/fastlane/fastlane/issues/4215, https://github.com/fastlane/fastlane/issues/722, amongst others 👍

**Closed by KrauseFx** 2018-02-12 14:44 UTC
