### ISSUE TITLE
Same file error with IPA

### ISSUE THREAD

**Issue by kiri11ko** [fastlane/fastlane#17398] opened 2020-10-07 10:53 UTC
```
[13:44:29]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
Traceback (most recent call last):
	36: from /usr/local/bin/fastlane:23:in `<main>'
	35: from /usr/local/bin/fastlane:23:in `load'
	34: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/bin/fastlane:23:in `<top (required)>'
	33: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	32: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	31: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	30: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	29: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	28: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	27: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	26: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	25: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	24: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	23: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	22: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	21: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	20: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	19: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	18: from Fastfile:9:in `block (2 levels) in parsing_binding'
	17: from Fastfile:67:in `build'
	16: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	15: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	14: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	13: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	11: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	10: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	 9: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/actions/build_app.rb:66:in `run'
	 8: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/gym/lib/gym/manager.rb:19:in `work'
	 7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/gym/lib/gym/runner.rb:35:in `run'
	 6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/gym/lib/gym/runner.rb:235:in `move_ipa'
	 5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/gym/lib/gym/generators/package_command_generator.rb:25:in `ipa_path'
	 4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.162.0/gym/lib/gym/generators/package_command_generator_xcode7.rb:69:in `ipa_path'
	 3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:520:in `mv'
	 2: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1555:in `fu_each_src_dest'
	 1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1573:in `fu_each_src_dest0'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1556:in `block in fu_each_src_dest': [!] same file: /var/folders/0z/tmjdgj0s015_pxnpj8r8qcfm0000gn/T/gym_output20201007-5527-y7u565/APP.ipa and /var/folders/0z/tmjdgj0s015_pxnpj8r8qcfm0000gn/T/gym_output20201007-5527-y7u565/APP.ipa (ArgumentError)

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.6                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.6 (19G2021)                                     |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.0.1                                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | ru_RU.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform(:ios)

platform :ios do	

    lane :develop_test do
        cocoapods(
          podfile: "./Podfile"
        )
        build("ADHOC_TEST", "ad-hoc", "app_adhoc", false)
       	diawi(
            token: "token"
        )

        url = lane_context[SharedValues::UPLOADED_FILE_LINK_TO_DIAWI]
        version = get_version_number(xcodeproj: "app.xcodeproj", target: "app")
        build = get_build_number_from_plist(xcodeproj: "app.xcodeproj", target: "app")

	telegram(
      token: "token",
      chat_id: "id",
      text: "done"
    )
   end

  lane :develop_preprod do
        cocoapods(
          podfile: "./Podfile"
        )
        build("ADHOC_PREPROD", "ad-hoc", "adhocPP", false)
       	diawi(
            token: "token"
        )

        url = lane_context[SharedValues::UPLOADED_FILE_LINK_TO_DIAWI]
        version = get_version_number(xcodeproj: "app.xcodeproj", target: "app")
        build = get_build_number_from_plist(xcodeproj: "app.xcodeproj", target: "app")

	telegram(
      token: "token",
      chat_id: "id",
      text: "done"
    )
   end

  lane :release do
cocoapods(
    		  clean: true,
    		  podfile: "./Podfile"
   	 )
	gym(
		scheme: "RELEASE_PROD",
		export_method: "app-store",
		configuration: "Release_Prod",
		clean: true,
		output_name: "app.ipa"
	) 
end



    def build (scheme, distribution_method, provision_name, need_compile_bitcode = true) 
        UI.message "| build()             |"
        UI.message "| scheme              | #{scheme}"
        UI.message "| distribution_method | #{distribution_method}"
        UI.message "| provision_name      | #{provision_name}"
        bundle_id = "net.app"
        gym(
          scheme: scheme,
          export_method: distribution_method,
          export_options: {
             compileBitcode: need_compile_bitcode,
             method: distribution_method,
             provisioningProfiles: { 
                 bundle_id => provision_name
         }
        }
        )
     end

end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>
```
```ruby
app_identifier("net.app") # The bundle identifier of your app
apple_id("k@dsd.net") # Your Apple email address

itc_team_id("11111") # App Store Connect Team ID
team_id("2222") # Developer Portal Team ID

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.162.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                     | Version | Update-Status |
| -------------------------- | ------- | ------------- |
| fastlane-plugin-diawi      | 2.1.0   | ✅ Up-To-Date  |
| fastlane-plugin-telegram   | 0.1.3   | ✅ Up-To-Date  |
| fastlane-plugin-versioning | 0.4.4   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                        | Version      |
| -------------------------- | ------------ |
| did_you_mean               | 1.3.0        |
| slack-notifier             | 2.3.2        |
| rouge                      | 2.0.7        |
| xcpretty                   | 0.3.0        |
| terminal-notifier          | 2.0.0        |
| unicode-display_width      | 1.7.0        |
| terminal-table             | 1.8.0        |
| plist                      | 3.5.0        |
| addressable                | 2.7.0        |
| multipart-post             | 2.0.0        |
| word_wrap                  | 1.0.0        |
| tty-cursor                 | 0.7.1        |
| tty-spinner                | 0.9.3        |
| babosa                     | 1.0.3        |
| colored                    | 1.2          |
| highline                   | 1.7.10       |
| commander-fastlane         | 4.4.6        |
| faraday                    | 1.0.1        |
| faraday_middleware         | 1.0.0        |
| gh_inspector               | 1.1.3        |
| mini_magick                | 4.10.1       |
| rubyzip                    | 2.3.0        |
| security                   | 0.1.3        |
| xcpretty-travis-formatter  | 1.0.0        |
| bundler                    | 2.1.4        |
| naturally                  | 2.2.0        |
| simctl                     | 1.6.8        |
| uber                       | 0.1.0        |
| declarative-option         | 0.1.0        |
| representable              | 3.0.4        |
| retriable                  | 3.1.2        |
| mini_mime                  | 1.0.2        |
| signet                     | 0.14.0       |
| httpclient                 | 2.8.3        |
| google-api-client          | 0.38.0       |
| nanaimo                    | 0.3.0        |
| colored2                   | 3.1.2        |
| claide                     | 1.0.3        |
| CFPropertyList             | 3.0.2        |
| atomos                     | 0.1.3        |
| xcodeproj                  | 1.18.0       |
| public_suffix              | 4.0.6        |
| tty-screen                 | 0.8.1        |
| excon                      | 0.76.0       |
| unf_ext                    | 0.0.7.7      |
| unf                        | 0.1.4        |
| domain_name                | 0.5.20190701 |
| http-cookie                | 1.0.3        |
| faraday-cookie_jar         | 0.0.7        |
| fastimage                  | 2.2.0        |
| json                       | 2.3.1        |
| dotenv                     | 2.7.6        |
| jwt                        | 2.2.2        |
| declarative                | 0.0.20       |
| multi_json                 | 1.15.0       |
| os                         | 1.1.1        |
| memoist                    | 0.16.2       |
| googleauth                 | 0.13.1       |
| rake                       | 13.0.1       |
| digest-crc                 | 0.6.1        |
| google-cloud-errors        | 1.0.1        |
| google-cloud-env           | 1.3.3        |
| google-cloud-core          | 1.5.0        |
| google-cloud-storage       | 1.29.1       |
| emoji_regex                | 3.0.0        |
| aws-eventstream            | 1.1.0        |
| aws-sigv4                  | 1.2.2        |
| aws-partitions             | 1.380.0      |
| jmespath                   | 1.4.0        |
| aws-sdk-core               | 3.109.1      |
| aws-sdk-kms                | 1.39.0       |
| aws-sdk-s3                 | 1.83.0       |
| forwardable                | 1.2.0        |
| logger                     | 1.3.0        |
| stringio                   | 0.0.2        |
| ipaddr                     | 1.2.2        |
| openssl                    | 2.1.2        |
| ostruct                    | 0.1.0        |
| strscan                    | 1.0.0        |
| date                       | 2.0.0        |
| fileutils                  | 1.1.0        |
| etc                        | 1.0.1        |
| io-console                 | 0.4.7        |
| zlib                       | 1.0.0        |
| libxml-ruby                | 3.1.0        |
| rexml                      | 3.1.9        |
| psych                      | 3.1.0        |
| mutex_m                    | 0.1.0        |
| webrick                    | 1.4.2        |
| http-accept                | 1.7.0        |
| mime-types-data            | 3.2020.0512  |
| mime-types                 | 3.3.1        |
| netrc                      | 0.11.0       |
| rest-client                | 2.1.0        |
| fastlane-plugin-diawi      | 2.1.0        |
| fastlane-plugin-telegram   | 0.1.3        |
| fastlane-plugin-versioning | 0.4.4        |
</details>

*generated on:* **2020-10-07**
</details>

**Comment by rogerluan** [comment] 2020-10-07 15:15
Hey @kiri11ko 👋 Could you please fill out [the appropriate form for reporting issues](https://raw.githubusercontent.com/fastlane/fastlane/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md) in _fastlane_? That way we can assist you better and faster. By looking at your issue description and logs, I can't tell what went wrong for you. Thanks.

**Comment by Strate** [comment] 2020-10-07 16:35
#17365

**Comment by minuscorp** [comment] 2020-10-07 19:17
This is kinda of a duplicate of the linked one or you can provide more information for us to track down the possible bug? 🤗

**Comment by rogerluan** [comment] 2020-10-07 22:31
The previous title looks very similar to the error that is being discussed in #17365 so I linked the PR that fixes that one, to this issue, at least until OP can help us understand more about their context 🙏

**Comment by kiri11ko** [comment] 2020-10-08 07:36
Yes, I also have the name of the application in Russian. Same problem as in #17365

**Comment by rogerluan** [comment] 2020-10-08 13:02
Sweet, thanks for confirming @kiri11ko ! That PR will likely be merged soon enough. Meanwhile, you can use its contents by modifying your Gemfile:

```ruby
gem 'fastlane', :git => 'https://github.com/mollyIV/fastlane.git', :branch => 'gym-fix-building-projects-with-unicode-characters-in-name'
```

**Closed** 2020-10-12 17:14 UTC
Labels: status: has-pr, tool: deliver
