### ISSUE TITLE
Fastlane Deliver failed.  Couldn't find 'split' in nil:NilClass or xcodebuild

### ISSUE THREAD

**Issue by davidmoore1** [fastlane/fastlane#7651] opened 2016-12-22 17:49 UTC
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [x ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Attempted to run deliver to add the ipa file and was got an error that "split"  for nil:NilClass wasn't found.  It also appeared to be looking for xcodebuild in a directory where it was not located.  I did a search and found it in /usr/bin.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

Davids-Mac:Zapoteco_Amatlan davidmoore$ fastlane deliver --ipa "zpoNT_Zapoteco_Amatlan.ipa" --submit_for_review
[12:36:26]: Successfully loaded '/Users/davidmoore/Fastlane/Zapoteco_Amatlan/Deliverfile' 📄

+----------------+--------------------------------------+
|         Detected Values from './Deliverfile'          |
+----------------+--------------------------------------+
| app_identifier | org.wycliffe.app.zapotecoamatlan.zpo |
| username       | david_moore1@wycliffe.org            |
+----------------+--------------------------------------+

[12:36:26]: Login to iTunes Connect (david_moore1@wycliffe.org)
[12:36:29]: Login successful

+-----------------------+--------------------------------------+
|                    deliver 2.2.0 Summary                     |
+-----------------------+--------------------------------------+
| ipa                   | zpoNT_Zapoteco_Amatlan.ipa           |
| submit_for_review     | true                                 |
| app_identifier        | org.wycliffe.app.zapotecoamatlan.zpo |
| username              | david_moore1@wycliffe.org            |
| screenshots_path      | ./screenshots                        |
| metadata_path         | ./metadata                           |
| app_version           | 1.0                                  |
| platform              | ios                                  |
| skip_binary_upload    | false                                |
| skip_screenshots      | false                                |
| skip_metadata         | false                                |
| force                 | false                                |
| automatic_release     | false                                |
| overwrite_screenshots | false                                |
+-----------------------+--------------------------------------+

[12:36:29]: Making sure the latest version on iTunes Connect matches '1.0' from the ipa file...
[12:36:30]: '1.0' is the latest version on iTunes Connect
[12:36:30]: Loading './metadata/en-US/description.txt'...
[12:36:30]: Loading './metadata/en-US/keywords.txt'...
[12:36:30]: Loading './metadata/en-US/release_notes.txt'...
[12:36:30]: Loading './metadata/en-US/support_url.txt'...
[12:36:30]: Loading './metadata/en-US/marketing_url.txt'...
[12:36:30]: Loading './metadata/en-US/name.txt'...
[12:36:30]: Loading './metadata/en-US/privacy_url.txt'...
[12:36:30]: Loading './metadata/copyright.txt'...
[12:36:30]: Loading './metadata/primary_category.txt'...
[12:36:30]: Loading './metadata/secondary_category.txt'...
[12:36:30]: Loading './metadata/primary_first_sub_category.txt'...
[12:36:30]: Loading './metadata/primary_second_sub_category.txt'...
[12:36:30]: Loading './metadata/secondary_first_sub_category.txt'...
[12:36:30]: Loading './metadata/secondary_second_sub_category.txt'...
[12:36:30]: Verifying the upload via the HTML file can be disabled by either adding
[12:36:30]: `force true` to your Deliverfile or using `deliver --force`
Does the Preview on path './Preview.html' look okay for you? (y/n)
y
[12:36:38]: HTML file confirmed...

[12:36:39]: Activating language en-US...
[12:36:43]: Uploading metadata to iTunes Connect
[12:36:46]: Successfully uploaded initial set of metadata to iTunes Connect
[12:36:47]: Starting with the upload of screenshots...
[12:36:47]: Activating language en-US...
[12:36:50]: Uploading 10 screenshots for language en-US
[12:36:50]: Uploading './screenshots/en-US/1_ipad_1.IMG_0145.jpg'...
[12:36:52]: Uploading './screenshots/en-US/1_iphone4_1.IMG_0031.jpg'...
[12:36:53]: Uploading './screenshots/en-US/2_ipad_2.IMG_0146.jpg'...
[12:36:56]: Uploading './screenshots/en-US/2_iphone4_2.IMG_0032.jpg'...
[12:36:57]: Uploading './screenshots/en-US/3_ipad_3.IMG_0147.jpg'...
[12:36:59]: Uploading './screenshots/en-US/3_iphone4_3.IMG_0033.jpg'...
[12:37:00]: Uploading './screenshots/en-US/4_ipad_4.IMG_0148.jpg'...
[12:37:02]: Uploading './screenshots/en-US/4_iphone4_4.IMG_0035.jpg'...
[12:37:04]: Uploading './screenshots/en-US/5_ipad_5.IMG_0149.jpg'...
[12:37:05]: Uploading './screenshots/en-US/5_iphone4_5.IMG_0036.jpg'...
[12:37:06]: Saving changes
[12:37:10]: Successfully uploaded screenshots to iTunes Connect
[12:37:13]: Uploading binary to iTunes Connect
sh: /Library/Developer/CommandLineTools//usr/bin/xcodebuild: No such file or directory
[12:37:15]: undefined method `split' for nil:NilClass
[12:37:15]: Error detecting currently used Xcode installation

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.2.0/fastlane_core/lib/fastlane_core/itunes_transporter.rb:294:in `initialize': [!] undefined method `start_with?' for nil:NilClass (NoMethodError)
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.2.0/deliver/lib/deliver/runner.rb:99:in `new'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.2.0/deliver/lib/deliver/runner.rb:99:in `upload_binary'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.2.0/deliver/lib/deliver/runner.rb:25:in `run'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.2.0/deliver/lib/deliver/commands_generator.rb:62:in `block (2 levels) in run'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.2.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.2.0/deliver/lib/deliver/commands_generator.rb:148:in `run'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.2.0/deliver/lib/deliver/commands_generator.rb:12:in `start'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.2.0/fastlane/lib/fastlane/cli_tools_distributor.rb:45:in `take_off'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.2.0/bin/fastlane:5:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.3.1/bin/fastlane:23:in `load'
	from /usr/local/var/rbenv/versions/2.3.1/bin/fastlane:23:in `<main>'
### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                            |
| ------------------- | ------------------------------------------------ |
| OS                  | 10.11.5                                          |
| Ruby                | 2.3.1                                            |
| Bundler?            | false                                            |
| Git                 | git version 2.7.4 (Apple Git-66)                 |
| Installation Source | /usr/local/var/rbenv/versions/2.3.1/bin/fastlane |
| Host                | Mac OS X 10.11.5 (15F34)                         |
| Ruby Lib Dir        | /usr/local/var/rbenv/versions/2.3.1/lib          |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                      |
| Is contained        | false                                            |
| Xcode Path          | /Library/Developer/CommandLineTools/             |
| Xcode Version       |                                                  |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.2.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.8.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.1        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| addressable               | 2.3.8        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.9.0        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.5.5        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
| faraday_middleware        | 0.10.1       |
| io-console                | 0.4.5        |
</details>

*generated on:* **2016-12-22**
</details>

**Comment by hjanuschka** [comment] 2016-12-22 18:17
@davidmoore1 this seems to be a problem - with detecting xcode installation.
it crashes on trying to detect the xcode major version. and your `fastlane env` also could'nt read out xcode version.


  * can you try running:
    * `xcode-select -p`
  * it should be something like: 
    * `/Applications/Xcode.app/Contents/Developer`

you should be able to set the selected xcode version with:
`xcode-select -s /path/to/your/xcode/Contents/Developer`

let me know if that helps you.

**Comment by davidmoore1** [comment] 2016-12-22 19:13
This is on a system that only has xcode command line tools installed.  Not
the full xcode.  One question might be whether that is a requirement.  I
didn't see it.  Typing xcode-select -p gives me
/Library/Developer/CommandLineTools.  There is a usr/bin under that,
however xcodebuild is not present there.  I only see that in /usr/bin.


*He must increase, but I must decrease (John 3:30)*

David Moore
(cell and sms) 404 247 8885

**Comment by hjanuschka** [comment] 2016-12-22 19:17
i am not sure if fastlane is supported on osx without xcode (only commandline tools).
can't you just install xcode ? like with: https://github.com/KrauseFx/xcode-install

**Comment by davidmoore1** [comment] 2016-12-22 19:25
I can if that is a requirement.  We are trying to get this set up for a
production build system that is relatively low powered so we limit the
installations on that system to what we have to have present.  So, if that
is what it takes, we can.  Other tools, such as the sigh haven't required
that.

*He must increase, but I must decrease (John 3:30)*

David Moore
(cell and sms) 404 247 8885

**Comment by KrauseFx** [comment] 2016-12-24 09:05
_sigh_ doesn't build your app, so it might be different. Either way, we have to fix the error message to explain what the problem is and how to fix it

**Comment by chuyik** [comment] 2016-12-31 11:17
```
$ xcode-select -s  /Applications/Xcode.app/Contents/Developer


xcode-select: error: --switch must be run as root (e.g. `sudo xcode-select --switch <xcode_folder_path>`).
```

**Comment by hjanuschka** [comment] 2016-12-31 11:35
@chuyik run it with sudo (as output says)


`sudo xcode-select -s  /Applications/Xcode.app/Contents/Developer`

**Comment by chuyik** [comment] 2016-12-31 11:52
@hjanuschka Nothing printed out with sudo.

**Comment by hjanuschka** [comment] 2017-01-03 15:02
ok and afterwards running `xcode-select -p` - does it now point to the right xcode?

**Comment by hjanuschka** [comment] 2017-02-27 16:05
@chuyik is still an issue?

**Comment by chuyik** [comment] 2017-02-28 02:10
@hjanuschka Maybe still an issue, but I haven't touch Fastlane since then.

**Comment by hjanuschka** [comment] 2017-02-28 06:36
ok - i am going to close this, feel free to reopen or file a new issue

**Closed by hjanuschka** 2017-02-28 06:36 UTC
Labels: bug
