### ISSUE TITLE
something wrong with login apple id

### ISSUE THREAD

**Issue by liuyuanming** [fastlane/fastlane#4587] opened 2016-05-10 08:22 UTC
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

```
[16:05:03]: fastlane finished with errors
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: 'cf233aaa441f0aa835033fc5bab621bf'
The crash report has been stored locally '/tmp/sentry_cf233aaa441f0aa835033fc5bab621bf.json'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:357:in `finish': [!] buffer error (Zlib::BufError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:357:in `finish'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:262:in `ensure in inflater'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:262:in `inflater'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:274:in `read_body_0'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:201:in `read_body'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1132:in `block in get'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1419:in `block (2 levels) in transport_request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:162:in `reading_body'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1418:in `block in transport_request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1409:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1409:in `transport_request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1382:in `request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1375:in `block in request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:852:in `start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1373:in `request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1131:in `get'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:80:in `perform_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-cookie_jar-0.0.6/lib/faraday/cookie_jar.rb:22:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `get'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:404:in `block in send_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:322:in `with_retry'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:403:in `send_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:379:in `request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:313:in `itc_service_key'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:274:in `block in send_shared_login_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:374:in `block in run_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:388:in `block in build_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/request.rb:26:in `block in create'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/request.rb:25:in `tap'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/request.rb:25:in `create'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:384:in `build_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:370:in `run_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:404:in `block in send_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:322:in `with_retry'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:403:in `send_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:379:in `request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:273:in `send_shared_login_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/portal/portal_client.rb:35:in `send_login_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:346:in `do_login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:225:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:88:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/portal/spaceship.rb:22:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/portal/spaceship.rb:77:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.8.0/lib/sigh/runner.rb:15:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.8.0/lib/sigh/manager.rb:7:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/actions/sigh.rb:20:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/runner.rb:173:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/runner.rb:158:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/runner.rb:157:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/runner.rb:157:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/runner.rb:111:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/fast_file.rb:130:in `method_missing'
	from Fastfile:35:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/commands_generator.rb:42:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.43.2/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/commands_generator.rb:175:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/commands_generator.rb:13:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/cli_tools_distributor.rb:47:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/bin/fastlane:5:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.81.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to public"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.
    # guide
    sigh
    gym # Build your app - more options available
    # pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```

### Environment

fastlane version (run `fastlane -v`):  fastlane 1.87.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?  fastlane beta

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

**Comment by vpolouchkine** [comment] 2016-05-10 15:34
Can you please format your issue per https://github.com/fastlane/fastlane/blob/master/ISSUE_TEMPLATE.md? Thanks!

**Comment by liuyuanming** [comment] 2016-05-11 01:17
I'm so sorry for the first come! I'm has formated my issue.please help me again.thanks very much.

**Comment by vpolouchkine** [comment] 2016-05-11 18:07
Thanks, please share the full log as well.

**Comment by liuyuanming** [comment] 2016-05-12 00:57
Last login: Thu May 12 08:53:30 on console
peters-iMac:~ peter$ cd /Users/peter/Desktop/FastlaneDemo 
peters-iMac:FastlaneDemo peter$ fastlane beta
You use deprecated syntax 'ios beta' in your Appfile.
Please follow the Appfile guide: https://github.com/fastlane/fastlane/blob/master/docs/Appfile.md
[08:56:42]: -------------------------------------------------
[08:56:42]: --- Step: Verifying required fastlane version ---
[08:56:42]: -------------------------------------------------
[08:56:42]: fastlane version valid
[08:56:42]: ------------------------------
[08:56:42]: --- Step: default_platform ---
[08:56:42]: ------------------------------
[08:56:42]: Driving the lane 'ios beta' 🚀
[08:56:42]: ------------------
[08:56:42]: --- Step: sigh ---
[08:56:42]: ------------------
You use deprecated syntax 'ios beta' in your Appfile.
Please follow the Appfile guide: https://github.com/fastlane/fastlane/blob/master/docs/Appfile.md
You use deprecated syntax 'ios beta' in your Appfile.
Please follow the Appfile guide: https://github.com/fastlane/fastlane/blob/master/docs/Appfile.md
You use deprecated syntax 'ios beta' in your Appfile.
Please follow the Appfile guide: https://github.com/fastlane/fastlane/blob/master/docs/Appfile.md
You use deprecated syntax 'ios beta' in your Appfile.
Please follow the Appfile guide: https://github.com/fastlane/fastlane/blob/master/docs/Appfile.md
You use deprecated syntax 'ios beta' in your Appfile.
Please follow the Appfile guide: https://github.com/fastlane/fastlane/blob/master/docs/Appfile.md
You use deprecated syntax 'ios beta' in your Appfile.
Please follow the Appfile guide: https://github.com/fastlane/fastlane/blob/master/docs/Appfile.md
You use deprecated syntax 'ios beta' in your Appfile.
Please follow the Appfile guide: https://github.com/fastlane/fastlane/blob/master/docs/Appfile.md
You use deprecated syntax 'ios beta' in your Appfile.
Please follow the Appfile guide: https://github.com/fastlane/fastlane/blob/master/docs/Appfile.md
You use deprecated syntax 'ios beta' in your Appfile.
Please follow the Appfile guide: https://github.com/fastlane/fastlane/blob/master/docs/Appfile.md
You use deprecated syntax 'ios beta' in your Appfile.
Please follow the Appfile guide: https://github.com/fastlane/fastlane/blob/master/docs/Appfile.md
You use deprecated syntax 'ios beta' in your Appfile.
Please follow the Appfile guide: https://github.com/fastlane/fastlane/blob/master/docs/Appfile.md

+-------------------------------------+--------------------------------------+
|                           Summary for sigh 1.8.0                           |
+-------------------------------------+--------------------------------------+
| adhoc                               | false                                |
| skip_install                        | false                                |
| development                         | false                                |
| force                               | false                                |
| app_identifier                      | com.xiaodao360.EnterpriseXiaoDaoWang |
| username                            | xdw@xiaodao360.com                   |
| ignore_profiles_with_different_name | false                                |
| skip_fetch_profiles                 | false                                |
| skip_certificate_verification       | false                                |
+-------------------------------------+--------------------------------------+

[08:56:43]: Starting login with user 'xdw@xiaodao360.com'
[08:56:44]: Variable Dump:
[08:56:44]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta"}
[08:56:44]: buffer error

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | sigh                                | 1           |
+------+-------------------------------------+-------------+

[08:56:44]: fastlane finished with errors
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: 'e275b6a9739929371c7fd979948d70c7'
The crash report has been stored locally '/tmp/sentry_e275b6a9739929371c7fd979948d70c7.json'

#######################################################################
# fastlane 1.88.0 is available. You are on 1.87.0.
# It is recommended to use the latest version.
# Update using 'sudo gem update fastlane'.
#######################################################################

1.88.0 Improvements
* Fix `build_and_upload_to_appetize` action for custom build locations
* Update `fastlane` to improve stability metrics by tool version
* Improve error message when an action is not available
* Add `update_urban_airship_configuration` action
* Fix typo in `appetize` action

1.87.1 Improvements
* Fixes the Appetize action for Android (thanks @louislarry!)
* Improve frameit when run as a lane (thanks @ekolesnikov!)
* Updated dependencies

Update using 'sudo gem update fastlane'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:357:in `finish': [!] buffer error (Zlib::BufError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:357:in `finish'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:262:in `ensure in inflater'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:262:in `inflater'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:274:in `read_body_0'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:201:in `read_body'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1132:in `block in get'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1419:in `block (2 levels) in transport_request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:162:in `reading_body'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1418:in `block in transport_request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1409:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1409:in `transport_request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1382:in `request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1375:in `block in request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:852:in `start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1373:in `request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1131:in `get'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:80:in `perform_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-cookie_jar-0.0.6/lib/faraday/cookie_jar.rb:22:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `get'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:404:in `block in send_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:322:in `with_retry'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:403:in `send_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:379:in `request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:313:in `itc_service_key'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:274:in `block in send_shared_login_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:374:in `block in run_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:388:in `block in build_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/request.rb:26:in `block in create'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/request.rb:25:in `tap'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/request.rb:25:in `create'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:384:in `build_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:370:in `run_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:404:in `block in send_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:322:in `with_retry'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:403:in `send_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:379:in `request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:273:in `send_shared_login_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/portal/portal_client.rb:35:in `send_login_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:346:in `do_login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:225:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:88:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/portal/spaceship.rb:22:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/portal/spaceship.rb:77:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.8.0/lib/sigh/runner.rb:15:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.8.0/lib/sigh/manager.rb:7:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/actions/sigh.rb:20:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/runner.rb:173:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/runner.rb:158:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/runner.rb:157:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/runner.rb:157:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/runner.rb:111:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/fast_file.rb:130:in `method_missing'
	from Fastfile:35:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/commands_generator.rb:42:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.43.2/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/commands_generator.rb:175:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/commands_generator.rb:13:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/cli_tools_distributor.rb:47:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/bin/fastlane:5:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'

**Comment by vpolouchkine** [comment] 2016-05-12 17:17
Looks like a dupe of #4610. Thanks for the log, we'll track it there.

**Closed by vpolouchkine** 2016-05-12 17:17 UTC
Labels: awaiting-reply
