### ISSUE TITLE
"Check Dependencies" error when building with Gym : Gym bug? Xcode 8? Travis? Human error? 

### ISSUE THREAD

**Issue by ChristopherDrum** [fastlane/fastlane#6219] opened 2016-09-21 02:27 UTC
### New Issue Checklist
- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

When building on Travis CI, I continue to get "check dependencies" errors when doing builds for Fabric Beta distribution (Enterprise builds), with 2 of the 8 dependencies reporting a problem. The problem **appears** to be that manual code signing choices, for example a scheme which uses "iOS Distribution" identity with "Release" configuration", is not being respected by some subprojects (which try to sign against "iOS Development" identity, despite explicitly setting to "iOS Distribution" in the main project)

Using @tmm1 's advice, I spit out the gym log and finally see something that explains the situation (see "output" below). Basically I get two errors, depending on if I explicitly set `codesigning_identity` in Gym. If I **do not** set it, gym's log says it can't find a certificate for iOS Developer on this scheme, which is true. It doesn't exist and it never existed. If I **do** set it, I'm told (for example) `AdjustSdk has conflicting provisioning settings. AdjustSdk is automatically signed, but code signing identity <<REDACTED>> has been manually specified.`

Running locally (running the same Fastlane lane "do_the_beta") I do not have this mysterious certificate in my local keychain, but fastlane builds for Fabric Beta without incident locally. I don't think that certificate has _ever_ existed before for us. The BETA scheme with RELEASE configuration is set to, and should be using, "iOS Distribution," not "iOS Development" when doing our enterprise builds for Fabric Beta.

Our project contains two submodules, but most dependencies are brought into the project via `git subtree`. It is my understanding that these subprojects can be left as-is with "automatic codesigning" and should inherit from the parent project.

So, Adjust and iOS Reachability are trying to sign with "iOS Development" (which is the default build setting for these, and really all, of the subprojects imported), but none of the other projects in the subtree express this problem:
- GRMustache
- SocketRocket
- Some private SDKs
- MBProgressHUD

I'm having a really difficult time understanding how fastlane + gym + Xcode 8 + subproject dependencies + manual code sign works together, and what needs to be set in what way. Every documentation I read seems to assume a very simple, "set the main project targets to manual code signing". I _assume_ this means I should be able to forget about subprojects and let the build system handle those, and yet here we are.

I've looked at the Build Settings for all of the subprojects. They are, indeed, set to `iOS Developer` in the Code Signing Identify, but this is just the default for all of them and was not altered by our team. This just "how things have always been". If the main project is set to manual code signing, and these subprojects are set to "Automatic", should that not override any other legacy settings?

Or, and this would really suck, do we have to manually manage code signing for all subprojects from now on? That wouldn't make much sense to me, because code signing identities are relative to our schemes, and our schemes are unique to our project. Subprojects would have no knowledge of that.
#### What Gym Tried to Run

```
+----------------------+-------------------------+
|             Summary for gym 1.9.0              |
+----------------------+-------------------------+
| scheme               | <<REDACTED>> Beta          |
| configuration        | Release                 |
| sdk                  | iphoneos                |
| use_legacy_build_api | true                    |
| workspace            | ./<<REDACTED>>.xcworkspace |
| destination          | generic/platform=iOS    |
| output_name          | <<REDACTED>>               |
| clean                | false                   |
| output_directory     | .                       |
| silent               | false                   |
| buildlog_path        | ~/Library/Logs/gym      |
+----------------------+-------------------------+
+------------------------------------------------------------------------------------------------------------------+----------------------+
|                                                         Generated Build Command                                                         |
+------------------------------------------------------------------------------------------------------------------+----------------------+
| Option                                                                                                           | Value                |
+------------------------------------------------------------------------------------------------------------------+----------------------+
| set -o pipefail &&                                                                                               |                      |
| xcodebuild                                                                                                       |                      |
| -workspace ./<<REDACTED>>.xcworkspace                                                                               |                      |
| -scheme <<REDACTED>>\ Beta                                                                                          |                      |
| -configuration                                                                                                   | Release              |
| -sdk                                                                                                             | iphoneos             |
| -destination                                                                                                     | generic/platform=iOS |
| -archivePath /Users/travis/Library/Developer/Xcode/Archives/2016-09-21/<<REDACTED>>\ 2016-09-21\ 02.21.20.xcarchive |                      |
| archive                                                                                                          |                      |
| | tee /Users/travis/Library/Logs/gym/<<REDACTED>>-<<REDACTED>>\ Beta.log                                                |                      |
| | xcpretty                                                                                                        |                      |
+------------------------------------------------------------------------------------------------------------------+----------------------+
INFO [2016-09-21 02:21:20.19]: $ set -o pipefail && xcodebuild -workspace ./<<REDACTED>>.xcworkspace -scheme <<REDACTED>>\ Beta -configuration 'Release' -sdk 'iphoneos' -destination 'generic/platform=iOS' -archivePath /Users/travis/Library/Developer/Xcode/Archives/2016-09-21/<<REDACTED>>\ 2016-09-21\ 02.21.20.xcarchive archive | tee /Users/travis/Library/Logs/gym/<<REDACTED>>-<<REDACTED>>\ Beta.log | xcpretty
```
#### Console Output

```
▸ Building Framework/iOSReachability [Release]
▸ Check Dependencies
▸ Building Adjust/AdjustSdk [Release]
▸ Check Dependencies
** ARCHIVE FAILED **
The following build commands failed:
Check dependencies
Check dependencies
(2 failures)
ERROR [2016-09-21 01:43:12.28]: Exit status: 65
WARN [2016-09-21 01:43:12.29]: Variable Dump:
INFO [2016-09-21 01:43:12.29]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios do_the_build"}
ERROR [2016-09-21 01:43:12.29]: Error building the application - see the log above
```
#### ~/Library/Logs/gym/<<REDACTED>>.log

If I **do not** specify a specific `codesigning_identity` in gym:

```
Build settings from command line:
    SDKROOT = iphoneos10.0
=== BUILD TARGET iOSReachability OF PROJECT Framework WITH CONFIGURATION Release ===
Check dependencies
No signing certificate "iOS Development" found:  No "iOS Development" signing certificate matching team ID "9WS<<REDACTED>>" with a private key was found.
=== BUILD TARGET AdjustSdk OF PROJECT Adjust WITH CONFIGURATION Release ===
Check dependencies
No signing certificate "iOS Development" found:  No "iOS Development" signing certificate matching team ID "9WS<<REDACTED>>" with a private key was found.
```

If I **do** specify a specific `codesigning_identity` in gym

```
Build settings from command line:
    CODE_SIGN_IDENTITY = <<REDACTED>>
    SDKROOT = iphoneos10.0
=== BUILD TARGET AdjustSdk OF PROJECT Adjust WITH CONFIGURATION Release ===
Check dependencies
AdjustSdk has conflicting provisioning settings. AdjustSdk is automatically signed, but code signing identity <<REDACTED>> has been manually specified. Set the code signing identity value to "iPhone Developer" in the build settings editor, or switch to manual signing in the project editor.
=== BUILD TARGET iOSReachability OF PROJECT Framework WITH CONFIGURATION Release ===
Check dependencies
iOSReachability has conflicting provisioning settings. iOSReachability is automatically signed, but code signing identity <<REDACTED>> has been manually specified. Set the code signing identity value to "iPhone Developer" in the build settings editor, or switch to manual signing in the project editor.
```

Code signing identity settings for the above two subprojects have been verified to match those of the other subprojects, which return no such error.
### Configuration Files

Travis yml

``` ruby
before_install:
    - rvm get stable --auto-dotfiles
    - rvm use ruby-2.0.0-p648
    - gem install scan -v '>=0.12.1'
    - gem install gym -v '>=1.9.0'
    - gem install fastlane --no-rdoc --no-ri
    - gem cleanup
    - sed -i -e "s/https:\/\/github.com\//git@github.com:/" .gitmodules
    - git submodule update --init --recursive
    - fastlane setup_ci

before_script:
    - open -b com.apple.iphonesimulator

script:
    - fastlane run_test
    - fastlane do_the_build --verbose
```

Fastfile:

``` ruby
# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md

#define some environment variables; remap Travis environment vars to Fastlane equivalents
<<ENVIRONMENT VARIABLES REDACTED>>

default_platform :ios
platform :ios do
    # You can define as many lanes as you want

    desc "Called before EVERY lane, so only use this for important cleanup/sanity-check routines"
    before_all do
        #currently not in use
    end

    desc "Setup keychain, install certificates and provisioning profiles"
    lane :setup_ci do

        #update plist file to reflect the commit used to make this build
        set_info_plist_value(path: INFO_PLIST_PATH, key: 'SNBuildCommitIdentifier', value: CURRENT_COMMIT)

        #create a keychain; KEYCHAIN_PASSWORD is throwaway
        #only used because create_keychain needs one; after this it is never referenced again
        create_keychain(name: BUILD_KEYCHAIN,
            default_keychain: true,
            password: ENV['KEYCHAIN_PASSWORD'],
            unlock: true,
            timeout: 3600,
            lock_when_sleeps: true
        )

        # Add certificates to keychain
        import_certificate(keychain_name: BUILD_KEYCHAIN, certificate_path: "#{CERTS_DIR_PATH}/apple.cer")
        import_certificate(keychain_name: BUILD_KEYCHAIN, certificate_path: "#{CERTS_DIR_PATH}/dist.cer")
        import_certificate(keychain_name: BUILD_KEYCHAIN, certificate_path: "#{CERTS_DIR_PATH}/dist.p12", certificate_password: ENV['BETA_CERTIFICATE_PASSWORD'])
        import_certificate(keychain_name: BUILD_KEYCHAIN, certificate_path: "#{CERTS_DIR_PATH}/App_Store_Certificate.p12", certificate_password: ENV['APPSTORE_CERTIFICATE_PASSWORD'])

        # Copy all provisioning profiles to Xcode default directory (could be replaced with "sigh" command, maybe?)
        sh("mkdir -p #{PROFILE_PATH}")
        sh("cp #{PROFILE_DIR_PATH}/* #{PROFILE_PATH}")
        sh("ls -l #{PROFILE_PATH}")
    end

    lane :run_test do
        scan(scheme: SCHEME_BETA,
            configuration: 'Debug',
            sdk: 'iphonesimulator10.0',
            device: 'iPhone 6'
        )
    end

    desc "Build and upload to Crashlytics Beta" 
    lane :do_the_beta do |options|

        # set project team to enterprise account
        update_project_team(path: PROJECT_FILE_PATH, teamid: TEAM_ID_ENTERPRISE)
        set_info_plist_value(path: INFO_PLIST_PATH, key: 'SNBuildCommitIdentifier', value: CURRENT_COMMIT)

        # set default release notes and revision string
        release_notes = Actions.sh('git log -1').chomp
        revision = options[:build_number]
        distribution_group = FABRIC_BASIC_DISTRIBUTION_GROUP

        # set special release notes and revision for prototype and release branches
        if CURRENT_BRANCH != nil && !CURRENT_BRANCH.empty?
            if CURRENT_BRANCH.start_with?('prototype/')     
                release_notes = "**PROTOTYPE** for #{CURRENT_BRANCH}\n#{release_notes}"
                revision = "PROTO-#{CURRENT_COMMIT}"
                distribution_group = FABRIC_PROTOTYPE_DISTRIBUTION_GROUP
            elsif CURRENT_BRANCH.start_with?('release/')
                release_notes = "**RELEASE** for #{CURRENT_BRANCH}\n#{release_notes}"
                revision = "RELEASE-#{CURRENT_COMMIT}"
            end
        end

        puts release_notes

        #set build version for beta distribution ease-of-installation
        set_info_plist_value(path: INFO_PLIST_PATH, key: 'CFBundleVersion', value: revision)    

        #build the archive and ipa
        gym(scheme: SCHEME_BETA,
            configuration: 'Release',
            sdk: 'iphoneos',
            use_legacy_build_api: true
        )

        #automatically uses the ipa from gym and env vars to fill in upload credentials
        #distribute via crashlytics if it isn't a pull request
        if !pull_request?
            crashlytics(notes: release_notes, groups: [distribution_group])
        end
    end

    def pull_request?
        pr_number = ENV['TRAVIS_PULL_REQUEST']
        pr_number != nil && !pr_number.empty? && pr_number != 'false'
    end
end
```
### Environment

Travis CI, running latest Xcode 8 GM
- fastlane 1.103.0
- fastlane core 0.52.0
- Scan 0.13.0
- Gym 1.9.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
RVM 1.27.0

**Comment by ChristopherDrum** [comment] 2016-09-21 02:46
@fastlane-bot Yeah, I know it is. And the troubleshooting guide hasn't helped me get through this yet. Thanks for the assist though, you're doing a bang-up job 👍

**Comment by ChristopherDrum** [comment] 2016-09-21 02:48
And while we're at it, the information I dump to console in the ~/Library/logs/gym/etc.... was absolutely the most useful information so far. Why doesn't that get dumped to console normally, even when --verbose is set on gym? Knowing that would have saved me SOOOO much time in investigations. 🙇

**Comment by cyupa** [comment] 2016-09-22 11:22
@ChristopherDrum Have you managed to find the root cause of this?

I have the exact same issue

```
▸ Check Dependencies
** ARCHIVE FAILED **


The following build commands failed:
Check dependencies
(1 failure)
ERROR [2016-09-22 14:17:11.15]: Exit status: 65
/Users/ciprian.redinciuc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane_core-0.52.0/lib/fastlane_core/ui/interface.rb:145:in `user_error!': [!] Error building the application - see the log above (FastlaneCore::Interface::FastlaneError)
	from /Users/ciprian.redinciuc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane_core-0.52.0/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/ciprian.redinciuc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/gym-1.9.0/lib/gym/error_handler.rb:53:in `handle_build_error'
	from /Users/ciprian.redinciuc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/gym-1.9.0/lib/gym/runner.rb:101:in `block in build_app'
	from /Users/ciprian.redinciuc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane_core-0.52.0/lib/fastlane_core/command_executor.rb:88:in `execute'
	from /Users/ciprian.redinciuc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/gym-1.9.0/lib/gym/runner.rb:97:in `build_app'
	from /Users/ciprian.redinciuc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/gym-1.9.0/lib/gym/runner.rb:12:in `run'
	from /Users/ciprian.redinciuc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/gym-1.9.0/lib/gym/manager.rb:10:in `work'
	from /Users/ciprian.redinciuc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/gym-1.9.0/lib/gym/commands_generator.rb:42:in `block (2 levels) in run'
	from /Users/ciprian.redinciuc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Users/ciprian.redinciuc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Users/ciprian.redinciuc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/ciprian.redinciuc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane_core-0.52.0/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
	from /Users/ciprian.redinciuc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Users/ciprian.redinciuc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/gym-1.9.0/lib/gym/commands_generator.rb:61:in `run'
	from /Users/ciprian.redinciuc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/gym-1.9.0/lib/gym/commands_generator.rb:15:in `start'
	from /Users/ciprian.redinciuc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/gym-1.9.0/bin/gym:6:in `<top (required)>'
	from /Users/ciprian.redinciuc/.rbenv/versions/2.3.1/bin/gym:23:in `load'
	from /Users/ciprian.redinciuc/.rbenv/versions/2.3.1/bin/gym:23:in `<main>'

```

**Comment by MarkMolina** [comment] 2016-09-22 11:23
Yep, +1, me as well. Keep you updated.

**Comment by puttin** [comment] 2016-09-22 13:27
You guys should check gym log normaly in your `~/library/logs/gym/xxx.log`

For our project, it's the codesign problem.

And we solve that by manual setting in Xcode 8 build setting with developer team and the provisioning profile specifier.

like

DEBUG:
"AwesomeApp Dev"
RELEASE:
"AwesomeApp AppStore"

these are the name in your developer portal profiles

and you can use Fastlane to change the profile use something like

```
def get_profile_name(uuid)
    profiles_path = File.expand_path("~") + "/Library/MobileDevice/Provisioning Profiles/*.mobileprovision"
    profile_paths = Dir[profiles_path]

    profile_paths.each do |profile_path|
      profile = Plist.parse_xml(`security cms -D -i '#{profile_path}'`)
      if profile['UUID'] == uuid
        return profile['Name']
      end
    end
  end

lane :yourlane do
  cert
  sh '"sigh manage -p 'AwesomeApp' --force"' # I have to say the pattern mapping logic in the source file sigh/local_manage some kinds not easy to use
  sigh
  profile_name = get_profile_name lane_context[SharedValues::SIGH_UDID]
  gym(xcargs: "PROVISIONING_PROFILE_SPECIFIER='#{profile_name}'")
end
```

That's what we get everything works again without the recommended `match`.

good luck!

**Comment by vgorloff** [comment] 2016-09-24 15:01
Similar issue on my side. Fixed by following code:

```ruby
...
CMProfilesDirPath = "#{ENV['PWD']}/fastlane/Profiles"

def ci_GetProfileName (profilePath)
   profile = Plist.parse_xml(`security cms -D -i '#{profilePath}'`)
   return profile['Name']
end
   
lane :travis do
   ...
   ci_ProfileFileName = "MyApp.mobileprovision"
   sigh(
     app_identifier: "com.my.domain.appID",
     output_path: CMProfilesDirPath,
     filename: ci_ProfileFileName
   )
   ci_ProfileSpecifier = ci_GetProfileName("#{CMProfilesDirPath}/#{ci_ProfileFileName}")
   gym(
     ...
     configuration: "Release",
     xcargs: "-PROVISIONING_PROFILE_SPECIFIER='#{ci_ProfileSpecifier}' CODE_SIGN_IDENTITY='iPhone Distribution' PROVISIONING_PROFILE=''"
   )
   ...
end
...
```

**Comment by pedro380085** [comment] 2016-09-25 04:07
So basically this is the guide from converting from PROFILE_UDID to PROVISIONING_PROFILE_SPECIFIER

**Comment by pedro380085** [comment] 2016-09-25 04:08
@puttin Isn't it needed to set your `PROVISIONING_PROFILE` to empty?

**Comment by ChristopherDrum** [comment] 2016-09-26 10:02
So, let's be clear about how my project is built:

There is the MainProject.xcworkspace
Which is set up as a gittree, not using CocoaPods
But there are two submodules (private SDKs)

We have two (2) schemes:
    "MainProject" and "MainProject Beta"
We have two (2) product identifiers:
    com.company.mainproject and com.company.mainprojectbeta
We have three (3) configurations:
    "Release"  "Debug"  "Beta"
We have two (2) targets:
    MainProject and MainProjectWidget
    Of course, the widget requires its own identifiers
        - ...MainProject.MainProjectWidget
        - ...MainProjectBeta.MainProjectWidgetBeta

"MainProject Beta" is built using our Enterprise account with the Beta configuration, Beta identifier, and the Beta scheme, and is distributed via Fabric.

"MainProject"  is for our App Store builds using our App Store account and the Release scheme
In this way we can have a new beta installed alongside the App Store version for direct on-device comparisons by the staff at large.

Inside the xcworkspace is...
 - MainProject.xcodeproj
   (which links to a bunch of dependency xcodeproj)
    - Adjust.xcodeproj
    - SocketRocket.xcodeproj
   etc. etc. etc.

The MainProject.xcodeproj is set to manual code sign, automatic is turned off.
Most subprojects are not controlled by us and are set to "Automatic" by default.

Gym builds fail with "Check Dependencies" and this message shows up.
> Check dependencies
 [BEROR]AdjustSdk has conflicting provisioning settings. AdjustSdk is automatically signed, but code signing identity iOS Distribution: <<REDACTED>>, Inc. has been manually specified. Set the code signing identity value to "iPhone Developer" in the build settings editor, or switch to manual signing in the project editor.

Why are subprojects trying to code sign against something other than the main project's identity?
Why does it insist so heavily to side against "iPhone Developer" though "iOS Distribution" was explicitly set on the parent xcodeproj?

I **CAN** get successful builds if I manually turn "off" "Automatic Code Sign" for every single subproject. But this means making sure that every time a subproject updates to maintain this silly set of checkboxes. Easy to forget, and easy to overlook.

I do not see a gym parameter for signing subprojects to match the parent.
Something that would automatically turn off "automatic code sign" and set the code sign to match the parent project. Or is this supposed to happen automatically?

**Comment by WedgeSparda** [comment] 2016-09-27 11:46
Same error error, but unchecking "Automatically manage signing" and using a specific Provision Profile didn't fix the problem.

**Comment by TKBurner** [comment] 2016-09-27 20:51
@ChristopherDrum @cyupa @MarkMolina @puttin @WedgeSparda I have let the core team know about this so we can take a look. Expect an update on this thread 👍

**Comment by pedro380085** [comment] 2016-09-28 02:23
Similar issue here @TKBurner https://github.com/fastlane/fastlane/issues/6055#issuecomment-249602068. Tks!

**Comment by ChristopherDrum** [comment] 2016-09-28 03:04
@WedgeSparda Hmm... I'm already using legacy_build_api: true... but maybe.....
*every* subproject.... needs..... 
some kind of update for Xcode 8 build compatibility? 
Could it be that all this time it wasn't "me" but rather "everyone else is wrong?" Hmmm....

**Comment by viktorrealt** [comment] 2016-09-28 15:50
DEVELOPER_DIR="/Applications/Xcode8.app" PROVISIONING_PROFILE_SPECIFIER=“AAAAAAAAAA/” gym --scheme "AppName" --clean

**Comment by vbresults** [comment] 2016-09-29 04:47
These are all interconnected #6293 #6317.

The solution is to use a pre-8.x Xcode version (in my case, 7.3.1), and everything works as normal.

```bash
DEVELOPER_DIR="/Applications/Xcode7.3.1.app/Contents/Developer" fastlane your_lane_here
```

**Comment by pedro380085** [comment] 2016-09-29 05:27
Oh man, found it!!! http://stackoverflow.com/questions/39594073/post-ios10-xcode-8-0-missing-push-notification-entitlement-error-after-build

**Comment by cyupa** [comment] 2016-09-29 06:52
@pedro380085 That's just one of the cases, as @ChristopherDrum stated, looking into `~/Library/Logs/gym` usually gives you more insight on why the build has failed.

What some of us were experiencing was issues with the enterprise distribution certificates naming.
Match will generate provisioning profiles with `MATCH_FORCE_ENTERPRISE="1"` for enterprise accounts in the following format: **InHouse_my.app.identifier** but when you run match, you can run it with with 3 options: `match development`, `match adhoc` and `match appstore`.

The only valid option at this point is renaming the provisioning profile to **Appstore_my.app.identifier** and running `match appstore` before running `gym`

@TKBurner, do you want me to open an issue for this or, wouldn't a `match inhouse` option make sense?

**Comment by SpacyRicochet** [comment] 2016-09-29 13:04
Can't seem to build my project with Gym either.

This is what the log file specifies;

```
Check dependencies
ecook has conflicting provisioning settings. ecook is automatically signed for development, but a conflicting code signing identity iPhone Distribution has been manually specified. Set the code signing identity value to "iPhone Developer" in the build settings editor, or switch to manual signing in the project editor.
Code signing is required for product type 'Application' in SDK 'iOS 10.0'
```

I tried the above advice, looking through several of the code signing settings in the project. I can't seem to find any reason for why gym would choose the development certificate.

**Signing in all the Pod targets**
![screen shot 2016-09-29 at 14 41 42](https://cloud.githubusercontent.com/assets/904596/18954403/2aaf0f64-8653-11e6-94dd-a1b706b09b5d.png)

**Signing in the app target**
![screen shot 2016-09-29 at 14 50 34](https://cloud.githubusercontent.com/assets/904596/18954705/6c4ea1cc-8654-11e6-8943-8bf9c3c09776.png)

The deprecated provisioning profile is empty in all cases, though I have tried it with filling in the same values as well. Even tried making sure that _no_ configuration actually uses a development certificate, but that fails too.

**Comment by ChristopherDrum** [comment] 2016-10-07 02:42
@vbresults That solution does not help those of us who need to do App Store submissions built against iOS 10 SDK.

**Comment by TKBurner** [comment] 2016-10-11 14:39
@ChristopherDrum @SpacyRicochet Are you able to not use 'automatic' for your provisioning profile selection. Can you let me know if this is related to #6333. We are focusing on code signing improvements within the core team right now so I want to make sure we understand this.

Thanks!

**Comment by ChristopherDrum** [comment] 2016-10-12 03:11
@TKBurner Yes, that was the reason I could not use 'automatic'.
This became a big problem as well, because while I worked on fixing the 'manual' codesign, other developers kept working and had 'automatic' turned on, which triggered some kind of invalidation on the provisioning profiles that I used for 'manual' code signing. We kept chasing each other around the block.

As well, fastlane's own documentation states:
"Occasionally the Automatic setting as the provisioning profile doesn't work reliably... That's why it is recommended to specify a specific provisioning profile somehow"

**Comment by TKBurner** [comment] 2016-10-12 19:42
@ChristopherDrum We recommend manual for sure however because of the new defaults we are going to investigate this. Thanks!

**Comment by JackieQi** [comment] 2016-11-04 23:08
My experience here. I used use_legacy_build_api. it failed using wrong provisioning file. So i turned off automatic signing. and manually picked provisioning file for different configuration. Then everything works perfectly fine. Tested release build with push notification.

**Closed** 2017-01-12 23:29 UTC
Labels: bug, gym, waiting-for-reply
