### ISSUE TITLE
client.rb throws Spaceship::UnexpectedResponse when parse_response.

### ISSUE THREAD

**Issue by motteww** [fastlane/fastlane#20077] opened 2022-03-17 10:58 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
The error suddently block me when I use ruby run fastlane to  register device. It was working in 2 month.
I've spend several hours and already refreshed Apple account and provition file and certificate.

##### Command executed
**ruby /fastlaneScripts/regiDevice.rb**

##### Complete output when running fastlane, including the stack trace and command used
_/Library/Ruby/Gems/2.6.0/gems/fastlane-2.204.3/spaceship/lib/spaceship/client.rb:783:in `parse_response': {"responseId"=>"62b4711d-46d6-4f31-bf8c-c259068daedd", "resultCode"=>3018, "resultString"=>"Please update to Xcode 7.3 or later to continue developing with your Apple ID.", "userString"=>"Please update to Xcode 7.3 or later to continue developing with your Apple ID.", "creationTimestamp"=>"2022-03-17T07:17:34Z", "protocolVersion"=>"QH65B2", "userLocale"=>"en_US", "requestUrl"=>"https://developerservices2.apple.com/services/QH65B2/ios/listProvisioningProfiles.action", "httpCode"=>200} (Spaceship::UnexpectedResponse)
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.204.3/spaceship/lib/spaceship/portal/portal_client.rb:669:in `provisioning_profiles_via_xcode_api'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.204.3/spaceship/lib/spaceship/portal/provisioning_profile.rb:319:in `all'
        from /Users/uftm/SigningPortal/routes/service/../../fastlaneScripts/regiDevice.rb:28:in `<main>'_

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 12.0.1                                                         |
| Ruby                        | 2.6.8                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.32.0 (Apple Git-132)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 12.0.1 (21A559)                                          |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 13.3                                                           |
| Swift Version               | 5.6                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | v|
| LC_ALL   | en_US.UTF-8 | v|
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**
**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.204.3 | vUp-To-Date  |

### Loaded fastlane plugins:
**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| atomos                          | 0.1.3        |
| claide                          | 1.0.3        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| rexml                           | 3.2.5        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.8.0        |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.5        |
| gh_inspector                    | 1.1.3        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 1.17.2       |
| simctl                          | 1.6.8        |
| jwt                             | 2.3.0        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| signet                          | 0.16.0       |
| googleauth                      | 1.1.0        |
| httpclient                      | 2.8.3        |
| google-apis-core                | 0.4.1        |
| google-apis-playcustomapp_v1    | 0.6.0        |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.8.0        |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.34.1       |
| emoji_regex                     | 3.2.3        |
| CFPropertyList                  | 3.0.5        |
| excon                           | 0.89.0       |
| json                            | 2.6.1        |
| trailblazer-option              | 0.1.2        |
| os                              | 1.1.4        |
| webrick                         | 1.7.0        |
| google-apis-androidpublisher_v3 | 0.14.0       |
| google-apis-storage_v1          | 0.10.0       |
| rake                            | 13.0.6       |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.4.0        |
| aws-partitions                  | 1.539.0      |
| jmespath                        | 1.4.0        |
| aws-sdk-core                    | 3.124.0      |
| aws-sdk-kms                     | 1.52.0       |
| aws-sdk-s3                      | 1.109.0      |
| forwardable                     | 1.2.0        |
| logger                          | 1.3.0        |
| date                            | 2.0.0        |
| stringio                        | 0.0.2        |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.2        |
| zlib                            | 1.0.0        |
| mutex_m                         | 0.1.0        |
| ostruct                         | 0.1.0        |
| strscan                         | 1.0.0        |
| io-console                      | 0.4.7        |
| fileutils                       | 1.1.0        |
| etc                             | 1.0.1        |
| libxml-ruby                     | 3.2.1        |
| psych                           | 3.1.0        |
</details>

<details>
  <pre>motteww</pre>
</details>

**Comment by panderman** [comment] 2022-03-17 14:27
Try this：
[https://github.com/fastlane/fastlane/issues/20060](url)

**Comment by ronpelayo** [comment] 2022-03-17 15:36
https://github.com/fastlane/fastlane/issues/20072#issuecomment-1070986839

**Comment by joshdholtz** [comment] 2022-03-17 17:16
✨ Official Update

This appears to be a duplicate of #20071. Going to close this so we can keep everything together in one issue 🙃

**Closed by joshdholtz** 2022-03-17 17:16 UTC

**Comment by motteww** [comment] 2022-03-18 06:02
Revert back to 2.176 not work.

**Comment by motteww** [comment] 2022-03-18 06:51
> Revert back to 2.176 not work.

Revert back to 2.176 not work.

**Comment by motteww** [comment] 2022-03-18 06:52
> Your issues is：Please update to Xcode 7.3 or later to continue developing with your Apple ID.
> 
> Try this： [https://github.com/fastlane/fastlane/issues/20060](url)



> Your issues is：Please update to Xcode 7.3 or later to continue developing with your Apple ID.
> 
> Try this： [https://github.com/fastlane/fastlane/issues/20060](url)

export SPACESHIP_AVOID_XCODE_API = false not work.

**Comment by panderman** [comment] 2022-03-23 01:34
> > Your issues is：Please update to Xcode 7.3 or later to continue developing with your Apple ID.
> 
> > 
> 
> > Try this： [https://github.com/fastlane/fastlane/issues/20060](url)
> 
> 
> 
> 
> 
> 
> 
> > Your issues is：Please update to Xcode 7.3 or later to continue developing with your Apple ID.
> 
> > 
> 
> > Try this： [https://github.com/fastlane/fastlane/issues/20060](url)
> 
> 
> 
> export SPACESHIP_AVOID_XCODE_API = false not work.

Try export SPACESHIP_AVOID_XCODE_API = true or export SPACESHIP_AVOID_XCODE_API = 1，i have the same issues and solved it
