### ISSUE TITLE
Exit status: 139

### ISSUE THREAD

**Issue by wangjinyu** [fastlane/fastlane#10360] opened 2017-09-19 02:42 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

[INSERT OUTPUT HERE]

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13                                       |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.13.5 (Apple Git-94)           |
| Installation Source         | ~/.rvm/gems/ruby-2.4.0/bin/fastlane         |
| Host                        | Mac OS X 10.13 (17A362a)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.0f  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
 # More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "6adb3b06-99a8-4765-be52-94fb5d1a1c44"

default_platform :ios

lane :beta do 
	increment_build_number
	# build your iOS app
	
	gym(
		workspace: "Vodka.xcworkspace",
  		configuration: "Release",
    	scheme: "Vodka"
	)

	# upload to Testflight
  	pilot(skip_waiting_for_build_processing: true)
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
 # The Appfile can be used to specify information that's used across all fastlane
# tools, like your username or the app's bundle identifier.
#
# For more details, check out the documentation at:
# https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

for_lane :beta do
	app_identifier "com.o2riding.ios" # the bundle identifier of your app
	apple_id "jinyuid@gmail.com" # Your Apple ID
end
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.57.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.15.4       |
| io-console                | 0.4.6        |
| CFPropertyList            | 2.3.5        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.59.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.13.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.2       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-09-19**
</details>

[INSERT OUTPUT HERE]

[10:41:16]: ▸ Archive Succeeded
sh: /usr/bin/xattr: /usr/bin/python: bad interpreter: No such file or directory
[10:41:16]: Generated plist file with the following values:
[10:41:16]: ▸ -----------------------------------------
[10:41:16]: ▸ {
[10:41:16]: ▸   "method": "app-store"
[10:41:16]: ▸ }
[10:41:16]: ▸ -----------------------------------------
[10:41:16]: $ /usr/bin/xcrun /Users/jinyu/.rvm/gems/ruby-2.4.0/gems/fastlane-2.57.0/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/3_/f2028c0d6vq_1df3d3gxlj4w0000gn/T/gym_config20170919-65671-9fpg36.plist' -archivePath /Users/jinyu/Library/Developer/Xcode/Archives/2017-09-19/SpeedX\ 2017-09-19\ 10.31.02.xcarchive -exportPath '/var/folders/3_/f2028c0d6vq_1df3d3gxlj4w0000gn/T/gym_output20170919-65671-lqt7ou'
RVM detected, forcing to use system ruby
Now using system ruby.
+ xcodebuild -exportArchive -exportOptionsPlist /var/folders/3_/f2028c0d6vq_1df3d3gxlj4w0000gn/T/gym_config20170919-65671-9fpg36.plist -archivePath '/Users/jinyu/Library/Developer/Xcode/Archives/2017-09-19/SpeedX 2017-09-19 10.31.02.xcarchive' -exportPath /var/folders/3_/f2028c0d6vq_1df3d3gxlj4w0000gn/T/gym_output20170919-65671-lqt7ou
2017-09-19 10:41:17.575 xcodebuild[71353:592538] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/3_/f2028c0d6vq_1df3d3gxlj4w0000gn/T/Vodka_2017-09-19_10-41-17.575.xcdistributionlogs'.
/Users/jinyu/.rvm/gems/ruby-2.4.0/gems/fastlane-2.57.0/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh: line 61: 71353 Segmentation fault: 11  xcodebuild "$@"
[10:41:31]: Exit status: 139

+---------------+-------------------------+
|            Build environment            |
+---------------+-------------------------+
| xcode_path    | /Applications/Xcode.app |
| gym_version   | 2.57.0                  |
| export_method | app-store               |
| sdk           | iPhoneOS11.0.sdk        |
+---------------+-------------------------+

+------------------+------+
|      Lane Context       |
+------------------+------+
| DEFAULT_PLATFORM | ios  |
| PLATFORM_NAME    |      |
| LANE_NAME        | beta |
| BUILD_NUMBER     | 11   |
+------------------+------+
[10:41:31]: Error packaging up the application

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | increment_build_number              | 1           |
| 💥   | gym                                 | 642         |
+------+-------------------------------------+-------------+

**Comment by diederikh** [comment] 2017-09-19 11:59
We were able to solve this by disabling Bitcode on the Xcode project.

**Comment by confucious** [comment] 2017-09-20 01:52
To clarify diederikh's comment, I also solved this by disabling Bitcode, but you have to do it in the configuration.

Add `export_options: { compileBitcode: false}` to your gym parameter.

**Comment by tbaranes** [comment] 2017-09-20 08:27
Got the same issue, but disabling bitcode is not solving it.

**Comment by RustyKnight** [comment] 2017-09-22 08:42
Tripped over this as well, but only for "Debug Configuration", which could mean that bitcode is already disabled for "Release Configuration", not sure, but using `export_options: { compileBitcode: false}` seems to have fixed the issue for the time been

ps- Releasing using Ad-Hoc profile

**Comment by sgtsquiggs** [comment] 2017-09-27 23:43
I am seeing this error on one computer, but not another computer:


```
RVM detected, forcing to use system ruby
Now using system ruby.
+ xcodebuild -exportArchive -exportOptionsPlist /var/folders/mf/yj7sfdnj55719hxrm1zsmdsr0000gn/T/gym_config20170927-8280-1v04p8d.plist -archivePath '/Users/matthew/Library/Developer/Xcode/Archives/2017-09-27/Amano 2017-09-27 19.39.30.xcarchive' -exportPath /var/folders/mf/yj7sfdnj55719hxrm1zsmdsr0000gn/T/gym_output20170927-8280-f4p26y
2017-09-27 19:40:21.844 xcodebuild[9586:282648] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/mf/yj7sfdnj55719hxrm1zsmdsr0000gn/T/Amano Lewitt_2017-09-27_19-40-21.844.xcdistributionlogs'.
/Users/matthew/.rvm/gems/ruby-2.4.0@ios/gems/fastlane-2.59.0/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh: line 61:  9586 Segmentation fault: 11  xcodebuild "$@"
[19:40:26]: Exit status: 139
```

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.14.1                          |
| Installation Source         | ~/.rvm/gems/ruby-2.4.0@ios/bin/fastlane     |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.0/lib                |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.56.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Update certificates/profiles via match"
  lane :matchup do
    match(
      type: "appstore",
      app_identifier: "com.paddle8.dev.amano"
    )
    match(
      type: "appstore"
    )
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    ensure_git_status_clean
    increment_build_number
    match(
      type: "appstore",
      app_identifier: "com.paddle8.dev.amano",
      readonly: true
    )
    gym(
      scheme: "Amano Lewitt"
    )
    changelog_from_git_commits
    testflight(
      app_identifier: "com.paddle8.dev.amano"
    )
    clean_up_and_commit
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    ensure_git_status_clean
    increment_build_number
    match(
      type: "appstore",
      readonly: true
    )
    # snapshot
    gym(
      scheme: "Amano Release"
    )
    deliver(
      force: true,
      submit_for_review: true
    )
    # frameit
    clean_up_and_commit
  end

  private_lane :clean_up_and_commit do |options|
    clean_build_artifacts
    build = get_build_number(xcodeproj: "Paddle8.xcodeproj")
    commit_version_bump(
      xcodeproj: "Paddle8.xcodeproj",
      message: "Build #{build}"
    )
  end

  after_all do |lane|
    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.paddle8.dev.amano" # The bundle identifier of your app
apple_id "matthew@paddle8.com" # Your Apple email address
team_id "H7XB97H8TE" # Developer Portal Team ID


app_identifier "com.paddle8.silentauction"
apple_id ENV["APPLE_ID"] || "matthew@paddle8.com"
team_id "H7XB97H8TE"

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.59.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.14.6       |
| io-console                | 0.4.6        |
| CFPropertyList            | 2.3.5        |
| i18n                      | 0.8.6        |
| minitest                  | 5.10.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.3        |
| activesupport             | 4.2.10       |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.3.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.2.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.0.3        |
| molinillo                 | 0.5.7        |
| ruby-macho                | 1.1.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.2        |
| cocoapods                 | 1.3.1        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.59.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.13.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.0        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.2       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 0.0.4        |
</details>


*generated on:* **2017-09-27**
</details>

**Comment by David-Drechsel-ewerk** [comment] 2017-09-28 12:30
I also see this behaviour for enterprise builds:
`2017-09-28 14:11:11.706 xcodebuild[86093:1241825] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/xz/wf6bc68s2g5dt79kn4cmgn6h0000gp/T/StadtpolizeiAppEnterpriseInt_2017-09-28_14-11-11.706.xcdistributionlogs'.
/usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.59.0/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh: line 61: 86093 Segmentation fault: 11  xcodebuild "$@"
[14:12:58]: [31mExit status: 139`

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.3.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.5 (Apple Git-94)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.3.3/lib            |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "1.87.1"

default_platform :ios

NOW = DateTime.now
project = './StadtpolizeiApp.xcodeproj'

platform :ios do
  before_all do
    increment_build_number(
      build_number: NOW.strftime("%Y%m%d%H%M"),
      xcodeproj: project
    )

  #  sh("cd .. && /usr/local/bin/carthage update")

  end

  desc "This increments the minor version and buildnumber of the project"
  lane :release_minor do
    increment_version_number(
      bump_type: "minor",
      xcodeproj: project
    )
  end

  desc "This increments the patch version and buildnumber of the project"
  lane :release_patch do
    increment_version_number(
      bump_type: "patch",
      xcodeproj: project
    )
  end

  lane :artifact do
    match(type: "appstore")
    gym(scheme: "StadtpolizeiApp")
  end

  lane :enterprise do
    update_app_identifier(
      xcodeproj: project,
      plist_path: "StadtpolizeiApp/Info.plist",
      app_identifier: 'com.ewerk.enterprise.hpiappep'
    )
    ENV["MATCH_FORCE_ENTERPRISE"] = "1"
    ENV["MATCH_GIT_URL"] = "ssh://git@bitbucket.it.ewerk.com:7999/ewerk/match-enterprise.git"
    match(
         type: 'enterprise',
         username: 'ios@ewerk.com',
         team_id: 'KQ5Q2T8ZCN',
         team_name: 'EWERK IT GmbH',
         app_identifier: 'com.ewerk.enterprise.hpiappep',
         shallow_clone: false,
       )
     gym(
      codesigning_identity: "iPhone Distribution: EWERK IT GmbH",
      export_method: "enterprise",
      scheme: "StadtpolizeiAppEnterprise",
      include_bitcode: false
    )
  end

  lane :enterprise_debug do
    update_app_identifier(
      xcodeproj: project,
      plist_path: "StadtpolizeiApp/Info.plist",
      app_identifier: 'com.ewerk.enterprise.hpiappep'
    )
    ENV["MATCH_FORCE_ENTERPRISE"] = "1"
    ENV["MATCH_GIT_URL"] = "ssh://git@bitbucket.it.ewerk.com:7999/ewerk/match-enterprise.git"
    match(
         type: 'enterprise',
         username: 'ios@ewerk.com',
         team_id: 'KQ5Q2T8ZCN',
         team_name: 'EWERK IT GmbH',
         app_identifier: 'com.ewerk.enterprise.hpiappep',
         shallow_clone: false,
       )
     gym(
      codesigning_identity: "iPhone Distribution: EWERK IT GmbH",
      export_method: "enterprise",
      scheme: "StadtpolizeiAppEnterpriseDEBUG",
      include_bitcode: false
    )
  end

  lane :enterprise_int do
    update_app_identifier(
      xcodeproj: project,
      plist_path: "StadtpolizeiApp/Info.plist",
      app_identifier: 'com.ewerk.enterprise.hpiappep.int'
    )
    set_info_plist_value(
    path: "StadtpolizeiApp/Info.plist",
    key: "defaultServerURL",
    value: "https://ep-int.pti.ch/ep-backend"
    )
    set_info_plist_value(
    path: "StadtpolizeiApp/Info.plist",
    key: "CFBundleName",
    value: "App EP-INT"
    )
    ENV["MATCH_FORCE_ENTERPRISE"] = "1"
    ENV["MATCH_GIT_URL"] = "ssh://git@bitbucket.it.ewerk.com:7999/ewerk/match-enterprise.git"
    match(
         type: 'enterprise',
         username: 'ios@ewerk.com',
         team_id: 'KQ5Q2T8ZCN',
         team_name: 'EWERK IT GmbH',
         app_identifier: 'com.ewerk.enterprise.hpiappep.int',
         shallow_clone: false,
       )
     gym(
      codesigning_identity: "iPhone Distribution: EWERK IT GmbH",
      export_method: "enterprise",
      scheme: "StadtpolizeiAppEnterpriseInt",
      include_bitcode: false
    )
  end

  after_all do |lane|
  end

  error do |lane, exception|
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.ewerk.StadtpolizeiApp" # The bundle identifier of your app
apple_id "ios@ewerk.com" # Your Apple email address
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.59.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.2        |
| slack-notifier            | 1.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| mini_magick               | 4.5.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| io-console                | 0.4.6        |
| excon                     | 0.59.0       |
| rubyzip                   | 1.2.1        |
| plist                     | 3.3.0        |
| faraday                   | 0.13.1       |
| faraday_middleware        | 0.12.2       |
| jwt                       | 1.5.6        |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| bundler                   | 1.15.4       |
| terminal-table            | 1.8.0        |
| unicode-display_width     | 1.3.0        |
</details>


*generated on:* **2017-09-28**
</details>

**Comment by getaaron** [comment] 2017-10-09 23:08
I think this is a duplicate of https://github.com/fastlane/fastlane/issues/10133 which has some more extensive analysis / discussion, so we may want to close this issue.

**Comment by hawkish** [comment] 2017-10-13 12:28
Got the exact same issue. Setting export_options: {compileBitcode: false} in gym fixed the segmentation fault.

**Closed** 2017-12-06 12:40 UTC
Labels: status: waiting-for-reply
