### ISSUE TITLE
team_id does not automatically select correct team when provisioning in iTunes Connect

### ISSUE THREAD

**Issue by ssteinerx** [fastlane/fastlane#4301] opened 2016-04-21 14:08 UTC
### Issue Description

My Apple ID belongs to two teams.  I have specified the team_id I wish to use in my Appfile.  It seems that there is no matching between the team_id and the iTunes Connect access corresponding to the team.

I searched for some way to indicate the correct iTunes Connect id (which is different from the team_id), but did not find one.
##### Unexpected output when running fastlane

```
Confusingly, I got this prompt even though I specified a team_id in my Appfile:

Multiple iTunes Connect teams found, please enter the number of the team you want to use:

1) "xxxxx" (2*******)
2) "yyyyy" (1******)
```
### Configuration Files

Fastfile is copied directly from doc, only using :provision for the moment; there is one team_id specified  in the Appfile and I'm not doing anything fancy.
### Environment

fastlane 1.81.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

NO

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
NO

System ruby: ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]

All gems up to date.

**Comment by vpolouchkine** [comment] 2016-04-21 16:28
Can you please still share the Fastfile so we're on the same page? Thanks!

**Comment by ssteinerx** [comment] 2016-04-21 17:05
```ruby
fastlane_version "1.81.0"

default_platform :ios

platform :ios do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/...
  end

  # 1
  desc "Creating a code signing certificate and provisioning profile"
  # 2
  lane :provision do
    # 3
    produce(
      app_name: 'TheAppName',
      language: 'English',
      app_version: '1.0',
      sku: 'THESKU'
    )
    # 4
    cert
    # 5
    sigh(force: true)
  end

  error do |lane, exception|
    slack(
      message: exception.message,
      success: false
    )
  end
end
```

**Comment by ssteinerx** [comment] 2016-04-21 17:07
Appfile:

```
# The bundle identifier of your app
app_identifier "com.xxxz.applicationname"
apple_id "ssteinerX@gmail.com" 	# Your Apple email address
team_id "ABCDEFGHIJ"  	 #  Developer Portal Team ID
```

**Comment by TKBurner** [comment] 2016-04-22 20:12
Hi @ssteinerx! Thanks for following up. Can you pass the team_id as a parameter to produce directly? This should clear up your issue 👍

**Comment by ssteinerx** [comment] 2016-04-22 21:09
The thing is, the team_id and the iTunes Connect ids are not the same; should there be two different ones in the Appfile?

**Comment by jacao** [comment] 2016-04-25 16:01
I had a similar issue, resolved it by setting the following environment variable at the start of my fastfile:

ENV["FASTLANE_ITC_TEAM_ID"] = "< iTunes Connect Id>"

**Comment by ssteinerx** [comment] 2016-04-25 16:26
@jacao Had you found that documented somewhere?  I'm just getting started with fastlane and that wasn't mentioned in any of the tutorials I've seen so far...

**Comment by TKBurner** [comment] 2016-04-25 18:31
Hi @ssteinerx can you let me know if setting the env variable resolves your issue. Thanks!

**Comment by jacao** [comment] 2016-04-26 08:08
@ssteinerx I couldn't see it in the documentation, ended up searching the codebase and found that this variable was the way to do it, did it work?

**Comment by TKBurner** [comment] 2016-04-26 16:48
@jacao Thanks for sharing! We'll make sure to update the docs 👍

**Comment by ssteinerx** [comment] 2016-04-26 16:57
@jacao Haven't been back to that project yet.  @TKBurner are you going to add a separate value to the config file for handling this?  Very helpful if so!

**Comment by TKBurner** [comment] 2016-04-27 15:39
@ssteinerx Thanks for following up. What exactly would you like to see, I want to make sure I fully understand before circling back with the team 👍

**Comment by ssteinerx** [comment] 2016-04-27 18:03
Just as we have:
```
team_id "ABCDEFGHIJ"     #  Developer Portal Team ID
```

We should have:

```
itunes_connect_id "ABCDEFG"  # iTunes Connect ID
```

**Comment by TKBurner** [comment] 2016-04-28 17:43
@ssteinerx Thanks! I'll surface this with the team 👍

**Comment by ssteinerx** [comment] 2016-06-28 15:33
If it has been added to the code, you should close this issue; not me.

**Comment by biolinh** [comment] 2016-06-29 00:40
as @ssteinerx said:

> The thing is, the team_id and the iTunes Connect ids are not the same; should there be two different ones in the Appfile?

Both of values of them are not same.
I can find the team id in Membership tab in Apple Developer Account, but I dont know where find iTunes Connect ids ? 
Have tried http://apple.stackexchange.com/a/158151 but it isn't same as iTunes Connect teams.

**Comment by TKBurner** [comment] 2016-06-30 16:33
@biolinh Thanks for following up on this. Are you currently running into an issue using one of the tools?

Thanks!

**Comment by ssteinerx** [comment] 2016-06-30 20:11
I stopped trying to use the product as this was a complete showstopper.

**Comment by parkej60** [comment] 2016-07-11 15:15
I'm pretty sure this is still not working correctly. I keep trying to do this and am getting told the app id doesn't exist. Just to reiterate @ssteinerx point, this really makes Fastlane & Deliver pretty useless for us.

**Comment by parkej60** [comment] 2016-07-11 15:18
Note, that once I hardcoded the team_id and / or created the app manually on iTunes connect the deliver process ran successfully. Sorry I can't explicitly say which one fixed the problem.

**Comment by lfarah** [comment] 2016-08-28 07:56
I can confirm that it doesn't work.
<img width="566" alt="screen shot 2016-08-28 at 12 55 51 am" src="https://cloud.githubusercontent.com/assets/6511079/18032467/2e3b659a-6cba-11e6-9597-5ac807453447.png">

Appfile:
```
app_identifier "farah.lucas.Kodeo" # The bundle identifier of your app
apple_id "dev@lucasfarah.me" # Your Apple email address

team_id "NN3TD9EB8G"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```

**Comment by TKBurner** [comment] 2016-08-29 20:41
@lfarah Thanks for following up on this. Can you please let me know the exact input that you are giving. I'd love to route this to the internal team. Thanks!

**Comment by lfarah** [comment] 2016-08-30 03:12
@TKBurner What information do you want me to provide? [our app is open source](https://github.com/troydo42/kodeo), so you can take a look at the codebase.

**Comment by TKBurner** [comment] 2016-08-30 19:19
@lfarah Thanks for following up. Can you share your full command line input and output from this run? Definitely want to get this resolved 👍

**Comment by KrauseFx** [comment] 2016-08-31 03:49
Yeah, you can already specify the Team ID for both the Dev Portal and for iTunes Connect, check out the docs here https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```ruby
app_identifier "tools.fastlane.app"       # The bundle identifier of your app

apple_dev_portal_id "portal@company.com"  # Apple Developer Account
itunes_connect_id "tunes@company.com"     # iTunes Connect Account

team_id "Q2CBPJ58CA" # Developer Portal Team ID
itc_team_id "18742801" # iTunes Connect Team ID
```

**Comment by lfarah** [comment] 2016-09-05 09:14
@KrauseFx I used the identifiers above but when getting the ```latest_testflight_build_number```, it won't recognize the ```itc_team_id```:
```
[02:09:15]: --------------------------------------------
[02:09:15]: --- Step: latest_testflight_build_number ---
[02:09:15]: --------------------------------------------
Multiple iTunes Connect teams found, please enter the number of the team you want to use:
1) "Lucas Farah" (118033180)
2) "Osvane Mendes" (117813478)
```

## My Appfile
```
app_identifier "farah.lucas.Kodeo"       # The bundle identifier of your app

apple_dev_portal_id "dev@lucasfarah.me"  # Apple Developer Account
itunes_connect_id "dev@lucasfarah.me"     # iTunes Connect Account

team_id "NN3TD9EB8G" # Developer Portal Team ID
itc_team_id "118033180" # iTunes Connect Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```

## My fastfile
```
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.97.2"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
    
  end

  # 1 
  desc "Creating a code signing certificate and provisioning profile"
  # 2
  lane :provision do
    # 3 
    produce(
      app_name: 'farah.lucas.kodeo',
      language: 'English',
      app_version: '1.0',
      sku: '123abc'
    )
    # 4
    cert
    # 5
    sigh(force: true)
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    increment_build_number({
      build_number: latest_testflight_build_number + 1
    })    
    gym(scheme: "Kodeo") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do  |lane| 
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do  |lane, exception| 
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```

**Comment by TKBurner** [comment] 2016-09-06 18:37
@lfarah Have you tried setting these as ENV? I think that'll cause the expected behavior. Thanks!

**Comment by KrauseFx** [comment] 2016-09-06 21:47
@lfarah Are you using the latest fastlane release?

**Comment by lfarah** [comment] 2016-09-07 03:32
@TKBurner      ENV["ITC_TEAM_ID"] = "118033180" didn't work:

```
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.97.2"

default_platform :ios
ENV["ITC_TEAM_ID"] = "118033180"

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
     ENV["ITC_TEAM_ID"] = "118033180"
    cocoapods
  end

  # 1 
  desc "Creating a code signing certificate and provisioning profile"
  # 2
  lane :provision do
    # 3 
    produce(
      itc_team_name: "118033180",
      app_name: 'farah.lucas.kodeo',
      language: 'English',
      app_version: '1.0',
      sku: '123abc'
    )
    # 4
    cert
    # 5
    sigh(force: true)
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide

    increment_build_number({
      itc_team_id: "118033180",
      build_number: latest_testflight_build_number + 1
    })    
    gym(scheme: "Kodeo") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do  |lane| 
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do  |lane, exception| 
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
@KrauseFx yes, I use ```update_fastlane```

**Comment by i-schuetz** [comment] 2016-09-08 14:30
@KrauseFx
@TKBurner

Same here, neither setting itc_team_id in Appfile or ENV["ITC_TEAM_ID"] in Fastfile help. It will ask

Multiple iTunes Connect teams found, please enter the number of the team you want to use: 
1) ...
2) ...

**Comment by i-schuetz** [comment] 2016-09-08 14:40
@KrauseFx
@TKBurner
@lfarah

Same here, neither setting itc_team_id in Appfile or ENV["ITC_TEAM_ID"] in Fastfile help. Using 0.51.0. It will ask

> 
> Multiple iTunes Connect teams found, please enter the number of the team you want to use: 
> 1) ...
> 2) ...

My appfile looks like this

```
app_identifier "tools.fastlane.app"       # The bundle identifier of your app
 
apple_dev_portal_id "portal@company.com"  # Apple Developer Account
itunes_connect_id "tunes@company.com"     # iTunes Connect Account

team_id "Q2CBPJ58CA" # Developer Portal Team ID
itc_team_id "18742801" # iTunes Connect Team ID
```


(with my data obviously)

**Comment by KrauseFx** [comment] 2016-09-08 16:54
Are you sure the team you provided via the Appfile or env variable exists? The TEAM ID must be the actual ID, while the team name must only be the name.

**Comment by i-schuetz** [comment] 2016-09-08 16:58
The team ID exists. Everything works fine if I run the action myself and select the ITC team ID when I'm prompted. The problem now is that I'm running this from Jenkins, so I can't select it. I copy pasted the number which appears in the prompt for the itc_team_id.

**Comment by i-schuetz** [comment] 2016-09-08 19:24
Is there a way to debug this?

**Comment by Douvi** [comment] 2016-09-11 18:29
Someone found a solutions ? I have the same bug...

**Comment by TKBurner** [comment] 2016-09-13 19:06
@Douvi @i-schuetz Thanks so much for working with us on this. I've circled back with the core team. Thanks!

**Comment by Douvi** [comment] 2016-09-14 00:14
@TKBurner Basically `itc_team_id` work with `gym`, `pilot` but not with `latest_testflight_build_number()`. When I run `latest_testflight_build_number()` I got

```
[20:53:04]: --------------------------------------------
[20:53:04]: --- Step: latest_testflight_build_number ---
[20:53:04]: --------------------------------------------
Multiple iTunes Connect teams found, please enter the number of the team you want to use: 
1) "name 1" (11111)
2) "name 2" (22222)
3) "name 3" (33333)
4) "name 4" (44444)
```

**Comment by i-schuetz** [comment] 2016-09-19 23:00
Can confirm the problem is `latest_testflight_build_number`

**Comment by TKBurner** [comment] 2016-09-26 18:03
@Douvi @i-schuetz Can you make sure all these variables are set:

Your iTunesConnect and Developer accounts can have separate emails so we have it separated out in the tool:

```
app_identifier "tools.fastlane.app"       # The bundle identifier of your app

apple_dev_portal_id "portal@company.com"  # Apple Developer Account
itunes_connect_id "tunes@company.com"     # iTunes Connect Account

team_id "Q2CBPJ58CA" # Developer Portal Team ID
itc_team_id "18742801" # iTunes Connect Team ID
```

**Comment by i-schuetz** [comment] 2016-09-26 18:39
They are set. Above in the conversation is the file I was using at that point.

**Comment by TKBurner** [comment] 2016-10-04 15:27
@i-schuetz Thanks for following up. I circled back with the team to get more attention on this thread. Thanks so much!

**Comment by ssteinerx** [comment] 2016-10-04 19:46
@TKBurner maybe you should stop *"circling"* and *"surfacing"* and just get the bug fixed.

**Comment by lfarah** [comment] 2016-10-04 19:55
@TKBurner thanks for giving us *free* support of Fastlane and telling the team to have more attention on this fix! 😃

**Comment by TKBurner** [comment] 2016-10-06 22:38
@ssteinerx I can't wait to see this fixed either and sorry that this is still affecting you. ❤️ 

@lfarah Thanks so much!

I added our community PR flag to this as well so we can make sure to get as many resources on this as possible. If anyone is interested in investigating we'd love to see that.

To make sure that I'm definitive on what I'm communicating to the team:

The action latest_test_flight_build_number is not inheriting team id, and this is causing it to fail to run autonomously. Is that correct?

Thanks again 👍 👍

**Comment by KrauseFx** [comment] 2016-10-07 01:21
Hey everyone, I was doing a lot of experiments, and noticed some rough edges around how the team ID isn't automatically converted from integer to strings, and how some actions have an inconsistent handling of the available teams.

I therefore pushed a bunch of PRs, that should fix all the issues you mentioned above:

- https://github.com/fastlane/fastlane/pull/6444 will unify how Team IDs and Team Names are handled across fastlane actions
- https://github.com/fastlane/fastlane/pull/6442 will validate that the iTunes Connect team is actually available
- https://github.com/fastlane/fastlane/pull/6443 will show more details on what team ID or name you provided, and shows a message if it can't be found. Extra information when using `--verbose`
- https://github.com/fastlane/fastlane/pull/6445 will add a nice summary of an `Appfile` and what `Appfile` is loaded when using the `--verbose` flag when running _fastlane_ 

The PRs are ready, as soon as they are reviewed and merged, we'll publish new releases for all those tools 👍 

@lfarah can you confirm that the team selection for iTunes Connect works for other tools (e.g. _deliver_, _pilot_), but not for `latest_testflight_build_number`? 

Thanks everybody for all the information provided, I hope the above posted pull requests will solve all the remaining issues 🚀

**Comment by Douvi** [comment] 2016-10-13 00:47
I just try with the new version `1.105.2` and I do not see any issue 👍 
Thanks all team fastlane

**Comment by gschwienbacher** [comment] 2016-10-13 09:21
@biolinh in reply to your [unanswered question](https://github.com/fastlane/fastlane/issues/4301#issuecomment-229225306):
> as @ssteinerx said:

> The thing is, the team_id and the iTunes Connect ids are not the same; should there be two different ones in the Appfile?
> Both of values of them are not same.
> I can find the team id in Membership tab in Apple Developer Account, but I dont know where find iTunes Connect ids ? 
> Have tried http://apple.stackexchange.com/a/158151 but it isn't same as iTunes Connect teams.

I had a hard time to find out the iTunes Connect ids as well (thx apple for making this super hard to find out...), so I want to share my approach:

* Login to itunesconnect (https://itunesconnect.apple.com/)
* Get output (JSON) from (https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/user/detail)
* You can now get your iTunes Connect ids from the `associatedAccounts` array with the different `contentProvider` objects - the entry named `contentProviderId` reflects the iTunes Connect id, lookup for the name value to pick the correct one

Hope these hints will help you and other people saving time while finding out the correct value for itc_team_id.

@KrauseFx  and fastlane team: thx for solving this issue. We con confirm it works with the newest version `1.105.2` (**and** choosing the correct (!) iTunes Connect id when finally accomplished to find out...)

**Comment by TKBurner** [comment] 2016-10-13 16:26
@gschwienbacher Thanks for sharing your investigation! We're really happy to have you using _fastlane_. Hope that you have a great weekend coming up! 👍

**Comment by pedro380085** [comment] 2016-11-09 22:53
thanks @TKBurner and @KrauseFx for your support 👍 

If I may add a suggestion, I think it would be a cool addition to the docs that, if you are in two teams, you must specify both the team_id and itc_team_id at https://github.com/fastlane/fastlane/blob/505ce4f462a4d9083a5334c81a6aaac8fa302aee/fastlane/docs/Appfile.md
When I was reading it for the first time I thought I only needed to choose one of the pairs, not both.

**Comment by bladebunny** [comment] 2017-03-13 04:51
Seems like this is not fully resolved?   I'm a new Fastlane user so I'm sure I'm doing things wrong.  
Like others on this thread, I have a personal dev account that is also associated with a different team account.  Trying to build with my dev account but create the app on the other team's account, which is working, and submit to their ITunes Connect account - which is not working for me.

I did a tutorial my first time thru and did not set up either an iTunes Connect Id or an Itc Team Id - with the result being the app was created on my personal iTunes account.  I then read back up on a different issue thread and added the itunes_connect_id.  And again the app was added to my personal ITunes connect account.  Then I found this thread, went to my desired team iTunes connect account; found the team Id and added an itc_team_id.  

And, again, the app was added to my personal ITunes Connect account.  So frustrating.  Fastlane is clearly awesome but I can't use it for this project at least (and have to figure out how to clean up my personal iTunes Connect account now).

**Comment by KrauseFx** [comment] 2017-05-02 08:14
Hey @bladebunny, this should be resolved in the most recent _fastlane_ version, check out the [Appfile docs](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md) for more information.

To your question, _produce_ accesses both iTunes Connect and the Apple Developer Portal. So it will use both teams, the `itc_team_id` for iTunes Connect, and the `team_id` for the Dev Portal. Could you submit a new issue, where you share your configuration, and the complete output, so we can take a look? 👍

**Closed by KrauseFx** 2017-05-02 08:14 UTC
Labels: deliver, fastlane, todo-docs
