### ISSUE TITLE
Could not upload binary to iTunes Connect

### ISSUE THREAD

**Issue by nAviram** [fastlane/fastlane#4339] opened 2016-04-24 09:37 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
uploading ipa file with gym fails - followed by this error:
##### Complete output when running fastlane, including the stack trace and command used

The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.

The iTMSTransporter Java app was not found at '/Applications/Xcode.app/Contents/Applications/Application Loader.app/Contents/itms/lib/itmstransporter-launcher.jar'.

If you're using Xcode 6, please select the shell script executor by setting the environment variable FASTLANE_ITUNES_TRANSPORTER_USE_SHELL_SCRIPT=1

[!] Could not upload binary to iTunes Connect. Check out the error above

### Environment
* Mac mini (Late 2014)
* OS X 10.10.5
* XCode 6.4

fastlane version (run `fastlane -v`): 1.81.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? no

**Comment by TKBurner** [comment] 2016-04-25 20:42
Hi @nAviram! Thanks for reaching out. This is a known issue. Have you tried the solution offered in the error message:
Set your env:

FASTLANE_ITUNES_TRANSPORTER_USE_SHELL_SCRIPT=1

Let me know if that clears things up for you. Hope that you have a great day! 👍

**Comment by nAviram** [comment] 2016-04-26 11:21
Hi @TKBurner ! Thanks for your reply!
I tried 
**_FASTLANE_ITUNES_TRANSPORTER_USE_SHELL_SCRIPT=1 
_**
but with no good - still the same error.

I've found this issue in another thread:
https://github.com/fastlane/fastlane/issues/4227

suggesting there that this issue should work out in XCode 7... so I hope at least once I'll upgrade it would be fine...

meanwhile - any solutions \ workarounds are welcome...

Thanks!

**Comment by mfurtak** [comment] 2016-04-26 14:11
Hi @nAviram - thanks for the report!

I'm going to close this as a duplicate of #4227, and I'll work on keeping that issue updated with more information as we go 👍

**Comment by mfurtak** [comment] 2016-04-26 14:18
Actually, I've thought better of it :) This ticket is more clearly about the problem with Xcode 6, so I'll use this ticket to post further updates on that situation. 👍

**Comment by mfurtak** [comment] 2016-04-26 18:20
I have reproduced this problem locally.

**Comment by mfurtak** [comment] 2016-04-26 18:40
Hi @nAviram 👋 

It is true that the Java setup for the iTMSTransporter has changed significantly from Xcode 6.4 to 7.x.

However! Using the environment variable `FASTLANE_ITUNES_TRANSPORTER_USE_SHELL_SCRIPT=1` allows things to work properly for me. When using Xcode 6.4 and my `beta` lane to upload to TestFlight, I can run fastlane like this:

```
FASTLANE_ITUNES_TRANSPORTER_USE_SHELL_SCRIPT=1 fastlane beta
```

And that allows things to work OK. Can you give that a try? If it doesn't work, can you provide the exact command that you are running as well as your `Fastfile`?

**Comment by mfurtak** [comment] 2016-04-26 20:19
I have merged #4375 to make shell script execution the default choice if we detect that you're using Xcode 6.x. That will go out in the next release! 🚀

**Comment by nAviram** [comment] 2016-04-27 10:00
Hi @mfurtak  - I'm using **Deliver**...
The command I'm using is:
deliver --skip_metadata --skip_screenshots --ipa fileToUpload.ipa

The output I'm getting is the same, after I'm doing the workaround:
 FASTLANE_ITUNES_TRANSPORTER_USE_SHELL_SCRIPT=1
and running deliver - I'm getting this error:

[14:13:28]: The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
[14:13:28]: The iTMSTransporter Java app was not found at '/Applications/Xcode.app/Contents/Applications/Application Loader.app/Contents/itms/lib/itmstransporter-launcher.jar'.
[14:13:28]: If you're using Xcode 6, please select the shell script executor by setting the environment variable FASTLANE_ITUNES_TRANSPORTER_USE_SHELL_SCRIPT=1

[!] Could not upload binary to iTunes Connect. Check out the error above

**Comment by TKBurner** [comment] 2016-04-27 13:55
Hi @nAviram! Thanks for following up. @mfurtak's PR should resolve your issue. Can you update once we've made our next release?

**Comment by nAviram** [comment] 2016-04-27 14:00
Sure thing! looking forward to it... please update me when it's done.

**Comment by mfurtak** [comment] 2016-04-27 14:59
Hi @nAviram - please give it a try by combining the environment variable with your deliver command, like:

```
FASTLANE_ITUNES_TRANSPORTER_USE_SHELL_SCRIPT=1 deliver --skip_metadata --skip_screenshots --ipa fileToUpload.ipa
```

🐚 ✨

**Comment by mfurtak** [comment] 2016-04-27 18:03
I've shipped [`fastlane_core` 0.42.1](https://github.com/fastlane/fastlane/releases/tag/fastlane_core/0.42.1) which contains the fix to handle Xcode 6.x automatically. 🚀 

If you run `gem update fastlane_core` you should be able to pull that down, and then I believe it should work for you with no work-arounds required 🙌 

Please let me know what you see!

**Closed by mfurtak** 2016-04-27 18:03 UTC
Labels: awaiting-reply, deliver, question

**Comment by nAviram** [comment] 2016-04-28 09:59
it works!
thanks!!! 
👍

**Comment by KrauseFx** [comment] 2016-04-28 13:23
Glad to hear you got it resolved @nAviram 👍

**Comment by dockusan** [comment] 2016-05-10 04:43
Hi. Thank for great library. I have same problem but I use deliver in fastfile. How to add FASTLANE_ITUNES_TRANSPORTER_USE_SHELL_SCRIPT as option in deliver?
```
lane :build_deploy_full do
  deliver(
    ipa: ENV['IPA_PATH'],
    metadata_path: ENV['METADATA_PATH'],
    screenshots_path: ENV['SCREENSHOTS_PATH'],
    app_version: ENV['APP_VERSION'],
    skip_screenshots: true,
    #FASTLANE_ITUNES_TRANSPORTER_USE_SHELL_SCRIPT: 1
    )
end
```

**Comment by mfurtak** [comment] 2016-05-10 13:35
Hi @dockusan :wave:

FASTLANE_ITUNES_TRANSPORTER_USE_SHELL_SCRIPT should be used as an environment variable. If you're calling `fastlane` and you want to specify it, you can run:

```bash
FASTLANE_ITUNES_TRANSPORTER_USE_SHELL_SCRIPT=1 fastlane build_deploy_full
```

**Comment by dockusan** [comment] 2016-05-11 03:43
I will try. Thank you so much.

**Comment by wkoszek** [comment] 2016-10-03 02:57
@mfurtak @KrauseFx Hi guys. I don't know if something is weird with my installation of XCode or not, but I have XCode 8 and I still have to set `FASTLANE_ITUNES_TRANSPORTER_USE_SHELL_SCRIPT`. Kinda leads to question whether it shouldn't just be the default. Anyway, no problem on my side here. With this variable set, it works

**Comment by mfurtak** [comment] 2016-10-03 13:56
Hi @wkoszek - thanks for the report. :+1:

https://github.com/fastlane/fastlane/issues/6151#issuecomment-249993354 has some history about why the ENV var exists, and you can follow that ticket for updates on a fix for the Xcode 8 issues.
