### ISSUE TITLE
Fastlane produce create - Service Unavailable.

### ISSUE THREAD

**Issue by mkuhnsbuildfire** [fastlane/fastlane#9092] opened 2017-05-05 23:29 UTC
### New Issue Checklist

- [X ] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Fastlane produce create is working in one of my environments, but not in another. I have included both environments. I have redacted some of the more sensitive info

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

FASTLANE_PASSWORD=XXXXXXXX fastlane produce create -u XXXXXXXXX -a com.bf.test -q 'CPC'

[!] The request could not be completed because:
	<html><body><b>Http/1.1 Service Unavailable</b></body> </html>

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

ENVIRONMENT THAT DOESN'T WORK:
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.1                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.10.1 (Apple Git-78)           |
| Installation Source         | ~/.rbenv/versions/2.3.1/bin/fastlane        |
| Host                        | Mac OS X 10.12.1 (16B2555)                  |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.1/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.28.9  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.1       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.7       |
| faraday_middleware        | 0.10.1       |
| io-console                | 0.4.5        |
</details>
 
ENVIRONMENT THAT DOES WORK:
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.3.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.3.3/lib            |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.28.8  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
| faraday_middleware        | 0.10.1       |
| io-console                | 0.4.5        |
</details>

**Comment by KrauseFx** [comment] 2017-05-08 13:00
Hey @mkuhnsbuildfire, thanks for raising this. It seems like it's a temporary server issue, can you try again today?

**Comment by mkuhnsbuildfire** [comment] 2017-05-08 16:31
Thanks for the response. I see what you are saying with trying again and it being temporary, but I reran this over and over and it repeatedly failed. This also doesn't happen on all Fastlane Produce calls. 
I downgraded from 2.28.9 to 2.28.8 and it seems to be working. Perhaps there was a regression in the latest version?
I really like what you guys are doing, let me know if you need any other information.

**Comment by wimbledon** [comment] 2017-05-08 16:59
I'm having the same issue with 2.28.9 as well. 
@mkuhnsbuildfire, how did you downgrade to 2.28.8? What are the specific command you used?

**Comment by wimbledon** [comment] 2017-05-08 17:21
I realized that the same issue happens in 2.28.8. It does not happen all the time though, it happens half of the time.

**Comment by taisukeh** [comment] 2017-05-09 10:54
Same issue by insigh action with 2.28.7.

**Comment by KrauseFx** [comment] 2017-05-09 11:11
```
fastlane produce -u felix@sunapps.net -q CPC987 --verbose

+----------------+------------------------+
|       Summary for produce 2.28.9        |
+----------------+------------------------+
| app_identifier | net.sunapps.yolokinder |
| app_name       | CPC987                 |
| sku            | 1494328111             |
| platform       | ios                    |
| language       | English                |
| skip_itc       | false                  |
| skip_devcenter | false                  |
+----------------+------------------------+

Multiple teams found on the Developer Portal, please enter the number of the team you want to use:1
INFO [2017-05-09 13:10:22.74]: Creating new app 'CPC987' on the Apple Dev Center
INFO [2017-05-09 13:10:24.82]: Created app 4ZB9M4AD8L
INFO [2017-05-09 13:10:25.15]: Finished creating new app 'CPC987' on the Dev Center
Multiple iTunes Connect teams found, please enter the number of the team you want to use:
Note: to automatically choose the team, provide either the iTunes Connect Team ID, or the Team Name in your fastlane/Appfile:
Alternatively you can pass the team name or team ID using the `FASTLANE_ITC_TEAM_ID` or `FASTLANE_ITC_TEAM_NAME` environment variable

  itc_team_id "117954211"

or

  itc_team_name "Felix Krause"

1) "Felix Krause" (117954211)
2
INFO [2017-05-09 13:10:33.51]: Creating new app 'CPC987' on iTunes Connect
INFO [2017-05-09 13:10:36.02]: Ensuring version number
INFO [2017-05-09 13:10:36.02]: Successfully created new app 'CPC987' on iTunes Connect with ID 1234541421
1234541421
```

I just tried it with the most recent _fastlane_ version and things work as expected. In which country are you based?

**Comment by vbresults** [comment] 2017-05-09 15:21
Using the latest version and maybe only 1 out of 20 requests will go through successfully, the rest show this Service Unavailable message.

**Comment by mkuhnsbuildfire** [comment] 2017-05-09 16:47
@wimbledon sudo gem install fastlane -v 2.28.8.

This downgrade seems to have address some of my issues, but not all. I process a lot of apps for different developers and I am based in the US. For some of the logins, this consistently fails. So if I immediately run again, it fails. If I wait an hour, it still fails. This seems to be an edge case for certain logins.

I could provide examples, but I would need to give you logins. Let me know if you have some suggestions.

**Comment by tommeier** [comment] 2017-05-09 20:47
We're seeing this also lately, I don't believe it has anything to do with latest fast lane. In particular I'm seeing it on match requests for provisioning profiles, if multiple builds all request at the same time one will get through and the others return the dreaded 'Service Unavailable' error. A wild guess from the patterns I've been seeing is that Apple have changed their API and throttling on multiple concurrent requests from the same API.

**Comment by vbresults** [comment] 2017-05-13 09:36
@KrauseFx This is a showstopper, how do we solve this?

**Comment by tommeier** [comment] 2017-05-15 07:19
OK had some time to narrow this down. I focused on `match` as thats where we're seeing it, but you can duplicate this error every time by running: 

```
(1..5).to_a.map do |x| Thread.new do
    result = `bundle exec fastlane match adhoc --app_identifier 'au.com.my_app_identifier' --shallow_clone --verbose`
    puts "-" * 100
    puts "Thread: #{x}"
    puts result
    puts "-" * 100
  end
end.each{|t| t.join}
```

And this is triggered in `spaceship/lib/spaceship/client.rb:430:in `send_shared_login_request'`, which is the login request to https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/wa

My guess would be Apple has put in some more serious flood protection here, which is triggered when multiple processes from the same IP address attempt to access.

Though my tests are on `match` the same applies to anything using `Spaceship` and triggering a login.

Possible solutions would be to retry - this works but you need to add a random delay to _try_ to avoid collisions. I did look into file locks, but this is of course useless when running on a build server and running the process on multiple boxes (that could be the same time). (for example: https://github.com/tommeier/fastlane/commit/1b94569cfc147f16efa9ee45d776481d4531c656)

For now - I'm going to reduce calls to match/spaceship in our setup, but this is what is going on with this `Service Unavailable` error.

**Comment by vbresults** [comment] 2017-05-16 14:10
@tommeier With root access is there a way to immediately apply this patch to fastlane?

**Comment by tommeier** [comment] 2017-05-16 22:46
@vbresults its more a prototype, being unaware of your setup, but assuming you're using bundler you can simply `bundle open fastlane` and make modifications to see what works for you. Reducing our calls to match from the same IP has worked perfectly for us, we were calling match far too frequently.

**Comment by vbresults** [comment] 2017-05-17 01:16
@tommeier Copying seems to work for everything except `match`, maybe because I'm also doing a write, but that is unavoidable -- and I don't know enough about fastlane to work around this.

**Comment by ohayon** [comment] 2017-05-22 19:30
Hey @tommeier I am working on tracking down the source and a good fix for this issue... To try to reproduce it better, I am curious if you have 2FA enabled on your Apple ID account? /cc: @vbresults and anyone else who would like to chime in! 🐙

**Comment by tommeier** [comment] 2017-05-22 22:29
:wave: @ohayon - no 2fa activated for our match user no - now more time has passed I can also say we haven't seen it once since reducing our match logins, and stopping all concurrent requests.

**Comment by vbresults** [comment] 2017-05-23 01:58
@ohayon No 2FA

**Comment by ohayon** [comment] 2017-05-23 13:55
Hey @vbresults, I am having a hard time reproducing this issue on my own machine with a handful of test accounts that we use. We did just push and update last night that changes a bit of how auth works. Do you think you could update _fastlane_ and give this another go to see if the changes fixed your issue? Thanks! 🚀

**Comment by vbresults** [comment] 2017-05-23 14:29
@ohayon Just updated, looks like it's fixed now, thank you (:

**Comment by ohayon** [comment] 2017-05-23 14:35
Amazing. Thanks for giving that a shot! :rocket:!

**Closed by ohayon** 2017-05-23 14:35 UTC
