### ISSUE TITLE
fastlane.match: authentication.failed error occurs

### ISSUE THREAD

**Issue by antonm76** [fastlane/fastlane#4172] opened 2016-04-12 17:19 UTC
### New Issue Checklist
fastlane 1.81.0
match 0.4.0

### Issue Description
Authentication error occurs when trying to init match either via fastlane or directly via match.

##### Complete output when running fastlane, including the stack trace and command used

```
{"responseId"=>"fd2a7a52-e055-4e12-bb20-e9dc40b08f35", "resultCode"=>1100, "resultString"=>"authentication.failed", "userString"=>"Your session has expired.  Please log in.", "creationTimestamp"=>"2016-04-12T17:12:49Z", "protocolVersion"=>"QH65B2", "userLocale"=>"en_US", "requestUrl"=>"https://developerservices2.apple.com/services/QH65B2/listTeams.action", "httpCode"=>200}
INFO [2016-04-12 20:12:50.02]: Successfully generated documentation to path '/Users/amyshkovsky/Projects/tlstash/ios_mone/mone/fastlane/README.md'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | match                               | 11          |
+------+-------------------------------------+-------------+

ERROR [2016-04-12 20:12:50.04]: fastlane finished with errors
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.25.1/lib/spaceship/client.rb:427:in `parse_response': [!] Apple provided the following error info: (Spaceship::Client::UnexpectedResponse)
	authentication.failed
	Your session has expired.  Please log in.
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.25.1/lib/spaceship/portal/portal_client.rb:51:in `teams'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.25.1/lib/spaceship/portal/ui/select_team.rb:35:in `select_team'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.25.1/lib/spaceship/portal/portal_client.rb:67:in `select_team'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.25.1/lib/spaceship/portal/spaceship.rb:37:in `select_team'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.25.1/lib/spaceship/portal/spaceship.rb:81:in `select_team'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.4.0/lib/match/spaceship_ensure.rb:20:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.4.0/lib/match/runner.rb:11:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.4.0/lib/match/runner.rb:11:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/actions/match.rb:11:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:22:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.41.2/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/bin/fastlane:168:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/bin/fastlane:174:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

**Comment by KrauseFx** [comment] 2016-04-13 07:43
It seems like that's a duplicate of https://github.com/fastlane/fastlane/issues/4157#issuecomment-208559847, could you check if the solution works for you?

**Comment by antonm76** [comment] 2016-04-13 12:10
We were using just a word for our team's AppleID, changing it to email and setting security questions solved the problem, thank you.

**Closed** 2016-04-13 12:11 UTC
Labels: match, spaceship

**Comment by TKBurner** [comment] 2016-04-13 14:07
@antonm76 Thanks for following up. Glad to hear you got up and running 👍

**Comment by mdamjanic7** [comment] 2016-04-17 09:17
Hey @TKBurner, unfortunately I'm still having this problem. I created a new Apple ID just for match, and I constantly keep having this issue. Going to appleid.apple.com doesn't show anything out of the ordinary (username is an email address, no missing security questions...). 
I also tried using my personal account (again, no problems when logging in through appleid.apple.com), but I keep getting the same message.

The only thing that might be out of the ordinary is that it is an Enterprise account. I checked #1790, #4157 and #2054 but I still have no idea what to do.

**Comment by i2amsam** [comment] 2016-04-17 13:17
@mdamjanic7 was this previously working and then stopped working, or are you setting things up for the first time? Could you try:

```
gem install spaceship -v 0.24.1
gem uninstall spaceship -v 0.25.1
gem uninstall spaceship -v 0.25.0

gem list spaceship // (verify 0.24.1 is the newest version)

```

And try `match` again?  That should help rule out recent changes on the `fastlane` side.
