### ISSUE TITLE
Can't upload to itunesconnect test flight  when password contains special characters

### ISSUE THREAD

**Issue by dgoyaldiksha** [fastlane/fastlane#4254] opened 2016-04-19 07:09 UTC
When trying to upload an ipa to test flight,It throws below error,I have special characters in itunes password.

Transporter transfer failed.

11:42:21: Return status of iTunes Transporter was 1: 
11:42:21: Return status of iTunes Transporter was 1: 
11:42:21: Password contains special characters, which may not be handled properly by iTMSTransporter. If you experience problems uploading to iTunes Connect, please consider changing your password to something with only alphanumeric characters.
11:42:21: Could not download/upload from iTunes Connect! It's probably related to your password or your internet connection.

[!] Error uploading ipa file, more information see above

So it's now impossible for us to release updates.
Is There any workaround for this, my fastlane core version is 0.41.2

**Comment by vpolouchkine** [comment] 2016-04-19 22:56
Can you please format your issue per https://github.com/fastlane/fastlane/blob/master/ISSUE_TEMPLATE.md? Thanks!

**Comment by dgoyaldiksha** [comment] 2016-04-20 04:42
yup sure! Here it is

### Issue Description

Whenever I try to upload build to testflight,It always throw below error.the command as well as output are below:

`Dikshas-MacBook-Pro:DrivingStyleEstimation diksha$ pilot upload
[10:02:52]: Login to iTunes Connect (Apple ID)
/Library/Ruby/Gems/2.0.0/gems/security-0.1.3/lib/security/password.rb:88: warning: Insecure world writable dir /usr/local in PATH, mode 040777
[10:03:03]: Login successful
[10:03:04]: Ready to upload new build to TestFlight (App: 1099705219)...
[10:03:04]: Going to upload updated app to iTunes Connect
[10:03:04]: This might take a few minutes, please don't interrupt the script
[10:03:35]: [Transporter Error Output]: Could not start delivery: all transports failed diagnostics
[10:03:35]: Transporter transfer failed.
[10:03:35]: 
[10:03:35]: Could not start delivery: all transports failed diagnostics
[10:03:35]: Return status of iTunes Transporter was 1: Could not start delivery: all transports failed diagnostics
[10:03:35]: Could not start delivery: all transports failed diagnostics
Return status of iTunes Transporter was 1: Could not start delivery: all transports failed diagnostics
[10:03:35]: Password contains special characters, which may not be handled properly by iTMSTransporter. If you experience problems uploading to iTunes Connect, please consider changing your password to something with only alphanumeric characters.
[10:03:35]: Could not download/upload from iTunes Connect! It's probably related to your password or your internet connection.

[!] Error uploading ipa file, more information see above
Dikshas-MacBook-Pro:DrivingStyleEstimation diksha$ `

## Configuration Files

FastFile:
`fastlane_version "1.81.0"

default_platform :ios

 
platform :ios do
 
  # 1 
  desc "Creating a code signing certificate and provisioning profile"
  # 2
  lane :provision do
    # 3 
    produce(
      app_name: 'DrivingStyleEstimation',
      language: 'English',
      app_version: '1.0',
      sku: '123abc'
    )
    # 4
    cert
    # 5
    sigh(adhoc: true)
  end
 
  error do |lane, exception|
    # This block is called, if there was an error running a specific lane.
  end



desc "Create ipa"
lane :build do
  gym
end

desc "Upload to App Store"
lane :upload do
  deliver
end
 
end
`

## Environment
fastlane_version "1.81.0"
fastlane-core version 0.41.2

**Comment by mfurtak** [comment] 2016-04-20 14:09
Hi @dgoyaldiksha - thanks for the report! 👍 

Despite the `pilot`'s speculation about your password (which we've had problems with in the past), I think another error message indicates that this is a network connectivity problem:

```
[Transporter Error Output]: Could not start delivery: all transports failed diagnostics
```

Can you try the work-around mentioned in #235 and let me know if it works for you? If not, please include the `--verbose` flag when you run, and post your output one more time. Thanks!

**Comment by TKBurner** [comment] 2016-04-20 14:42
@dgoyaldiksha Thanks for reaching out. We are aware of this issue and our current solution is this error message. This has to do with the way Spaceship communicates with ITunes Connect. If your password fails you should consider changing it to something with only alpha numeric characters. I'm closing this out because we aren't able to take action right now. However, rest assured we are aware of this and will move forward when we can. 👍

**Comment by TKBurner** [comment] 2016-04-20 14:44
This is a duplicate of #1600. Closing out for housekeeping. We'd still love to look into this over there 👍

**Closed by TKBurner** 2016-04-20 14:44 UTC
Labels: awaiting-reply, pilot
