### ISSUE TITLE
Deliver doesn't submit for review even though it said it did.

### ISSUE THREAD

**Issue by jostster** [fastlane/fastlane#8260] opened 2017-02-15 22:02 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Deliver says it successfully submitted application for review when it really didn't. We use encryption in our app as well as advertisement ID. I did not specify a config for these arguments so I imagine that it failed at that point when submitting the application for review. However, in the logs it still shows it was successfully submitted for review. I had to manually login to itunes connect and submit the application.

The deliver should return an error if it is unable to properly submit for review if that option is set to true.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

```
[16:32:44]: Loading './fastlane/metadata/en-US/description.txt'...
[16:32:44]: Loading './fastlane/metadata/en-US/keywords.txt'...
[16:32:44]: Loading './fastlane/metadata/en-US/release_notes.txt'...
[16:32:44]: Loading './fastlane/metadata/en-US/support_url.txt'...
[16:32:44]: Loading './fastlane/metadata/en-US/marketing_url.txt'...
[16:32:44]: Loading './fastlane/metadata/en-US/name.txt'...
[16:32:44]: Loading './fastlane/metadata/en-US/privacy_url.txt'...
[16:32:44]: Loading './fastlane/metadata/copyright.txt'...
[16:32:44]: Loading './fastlane/metadata/primary_category.txt'...
[16:32:44]: Loading './fastlane/metadata/secondary_category.txt'...
[16:32:44]: Loading './fastlane/metadata/primary_first_sub_category.txt'...
[16:32:44]: Loading './fastlane/metadata/primary_second_sub_category.txt'...
[16:32:44]: Loading './fastlane/metadata/secondary_first_sub_category.txt'...
[16:32:44]: Loading './fastlane/metadata/secondary_second_sub_category.txt'...
[16:32:45]: Activating language en-US...
[16:32:49]: Uploading metadata to iTunes Connect
[16:32:51]: Successfully uploaded set of metadata to iTunes Connect
[16:32:51]: Starting with the upload of screenshots...
[16:32:51]: Successfully uploaded screenshots to iTunes Connect
[16:32:54]: Uploading binary to iTunes Connect
[16:32:59]: Going to upload updated app to iTunes Connect
[16:32:59]: This might take a few minutes. Please don't interrupt the script.
[16:36:19]: iTunes Transporter successfully finished its job
[16:36:19]: --------------------------------------------------------------------
[16:36:19]: Successfully uploaded package to iTunes Connect. It might take a few minutes until it's visible online.
[16:36:19]: --------------------------------------------------------------------
[16:36:19]: Finished the upload to iTunes Connect
[16:36:22]: Selecting the latest build...
[16:36:24]: Waiting iTunes Connect processing for build 2.3.3 (344.87)... this might take a while...
[16:36:56]: Waiting iTunes Connect processing for build 2.3.3 (344.87)... this might take a while...
[16:37:30]: Waiting iTunes Connect processing for build 2.3.3 (344.87)... this might take a while...
[16:38:01]: Waiting iTunes Connect processing for build 2.3.3 (344.87)... this might take a while...
[16:38:32]: Waiting iTunes Connect processing for build 2.3.3 (344.87)... this might take a while...
[16:39:04]: Waiting iTunes Connect processing for build 2.3.3 (344.87)... this might take a while...
[16:39:36]: Waiting iTunes Connect processing for build 2.3.3 (344.87)... this might take a while...
[16:40:09]: Waiting iTunes Connect processing for build 2.3.3 (344.87)... this might take a while...
[16:40:42]: Selecting build 2.3.3 (344.87)...
[16:40:43]: Successfully selected build
[16:40:43]: Submitting the app for review...
[16:40:55]: Successfully submitted the app for review!
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

```
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                                          |
| ------------------- | -------------------------------------------------------------- |
| OS                  | 10.12.3                                                        |
| Ruby                | 2.0.0                                                          |
| Bundler?            | false                                                          |
| Git                 | git version 2.10.1 (Apple Git-78)                              |
| Installation Source | /usr/local/bin/fastlane                                        |
| Host                | Mac OS X 10.12.3 (16D32)                                       |
| Ruby Lib Dir        | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version     | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained        | false                                                          |
| Is homebrew         | false                                                          |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version       | 8.2.1                                                          |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.17.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.7.7        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.10.1       |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.55.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.4       |
| faraday_middleware        | 0.11.0.1     |
</details>


*generated on:* **2017-02-15**
</details>
```

**Comment by LucasVanDongen** [comment] 2017-02-21 19:35
Same problem here but without the advertisement ID. My account uses 2FA and it's not the main account for the company (but I have elevated rights at the moment).

```
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                                          |
| ------------------- | -------------------------------------------------------------- |
| OS                  | 10.12                                                          |
| Ruby                | 2.0.0                                                          |
| Bundler?            | false                                                          |
| Git                 | git version 2.10.1 (Apple Git-78)                              |
| Installation Source | /usr/local/bin/fastlane                                        |
| Host                | Mac OS X 10.12 (16A323)                                        |
| Ruby Lib Dir        | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version     | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained        | false                                                          |
| Is homebrew         | false                                                          |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version       | 8.2.1                                                          |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "1.106.2"

default_platform :ios

platform :ios do
  before_all do
    cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    ensure_git_branch(
      branch: "develop"
    )
    #scan
  end

  #desc "Make screenshots"
  #lane :screenshots do
  #  snapshot
    #frameit(white: true)
  #end

  desc "Push"
  lane :push do
    #ensure_git_branch(
    #  branch: "master"
    #)
    #snapshot
    deliver(
      force: true
    )
  end
end```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "REDACTED" # The bundle identifier of your app
apple_id "REDACTED" # Your Apple email address

team_id "REDACTED"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.18.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.9.0        |
| activesupport             | 4.2.6        |
| CFPropertyList            | 2.3.3        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.10.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.6.3        |
| terminal-table            | 1.4.5        |
| plist                     | 3.1.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| excon                     | 0.45.4       |
| faraday                   | 0.9.2        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160310 |
| http-cookie               | 1.0.2        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.4        |
| memoist                   | 0.14.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.2        |
| googleauth                | 0.5.1        |
| thor                      | 0.19.1       |
| httpclient                | 2.8.0        |
| google-api-client         | 0.9.8        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.5.5        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.12.5       |
| faraday_middleware        | 0.10.0       |
| json                      | 1.8.3        |
</details>


*generated on:* **2017-02-21**
</details>
```

**Comment by hjanuschka** [comment] 2017-02-22 15:09
please try to set the answers via options (`submission_information` in deliver:

>adopt to your settings.

```ruby
deliver(submission_information: {
      add_id_info_limits_tracking: true,
      add_id_info_serves_ads: true,
      add_id_info_tracks_action: true,
      add_id_info_tracks_install: true,
      add_id_info_uses_idfa: true,
      content_rights_has_rights: true,
      content_rights_contains_third_party_content: true,
      export_compliance_platform: 'ios',
      export_compliance_compliance_required: false,
      export_compliance_encryption_updated: false,
      export_compliance_app_type: nil,
      export_compliance_uses_encryption: false,
      export_compliance_is_exempt: false,
      export_compliance_contains_third_party_cryptography: false,
      export_compliance_contains_proprietary_cryptography: false,
      export_compliance_available_on_french_store: false
    })
```

**Comment by LucasVanDongen** [comment] 2017-02-22 17:57
At first it gave me an unknown error, something I considered hopeful. But after some careful massaging of the settings I'm now back at the same problem. Happy confetti yet nothing in the store. The settings are as follows:

```
    deliver(
      force: true,
      submission_information: {
        add_id_info_limits_tracking: false,
        add_id_info_serves_ads: false,
        add_id_info_tracks_action: false,
        add_id_info_tracks_install: false,
        add_id_info_uses_idfa: false,
        content_rights_has_rights: false,
        content_rights_contains_third_party_content: false,
        export_compliance_platform: 'ios',
        export_compliance_compliance_required: false,
        export_compliance_encryption_updated: true,
        export_compliance_app_type: nil,
        export_compliance_uses_encryption: true,
        export_compliance_is_exempt: false,
        export_compliance_contains_third_party_cryptography: true,
        export_compliance_contains_proprietary_cryptography: true,
        export_compliance_available_on_french_store: false
      },
      app_review_information: {
        first_name: 'Lucas',
        last_name: 'van Dongen',
        phone_number: '+43 11111',
        email_address: 'finger@interestingdomain.com',
        demo_user: 'test1234',
        demo_password: 'test1234',
        notes: ''
      }
    )
```

The app does use a lot of encryption but won't be used outside of the US AppStore.

**Comment by jostster** [comment] 2017-02-23 15:21
Yes when using the subission_information param it works, but this task was more created for the false status of it saying it was submitted when it wasn't. This could leave people with CI to believe their application was submitted if they don't go in and check the itunes connect status after each deliver.

**Comment by LucasVanDongen** [comment] 2017-02-23 15:33
@jostster it still behaves the same here *with* the submission_information

**Comment by stonedauwg** [comment] 2017-02-23 22:17
Same issue here with fastlane 2.18.3. Deliver says success for review submission and it never submitted. Manually submitting using iTunesConnect site works fine. @jostster to answer your question it asks about 3 things: crypto usage, third party content usage, and Advertising ID usage.

**Comment by stonedauwg** [comment] 2017-02-23 22:19
@jostster and @LucasVanDongen - did this work for you in previous versions of fastlane? This is personally my first go of it and so far the only issue I've encountered.

**Comment by jostster** [comment] 2017-02-23 23:25
I hadn't tried it in previous version. However, I did submit today and it went through fine. Here is my lane that worked. I only do encryption and ad tracking. I haven't tried a version yet where the encryption has changed but with these values when I submit when my encryption hasn't changed works.

```
lane :deploy_appstore do |values|
  	app_submission_info = {
		add_id_info_uses_idfa: true, 
		add_id_info_tracks_install: true, 
		add_id_info_tracks_action: true, 
		add_id_info_limits_tracking: true,
		export_compliance_encryption_updated: false
	}
    deliver(ipa:"app.ipa", submit_for_review: true, submission_information: app_submission_info)
    slack(message: "Successfully submitted to appstore!", success: true)
  end
```

**Comment by jostster** [comment] 2017-02-23 23:31
my recommendation is deliver should return a value if it was successful or not. the only way it is successful is if it succeeds based on the params. This task was created because with the app_submission_info not set but submit_for_review: true, it would say it was submitted for review but it really errored out because it didn't pass the submission_information which is required before submission.

**Comment by stonedauwg** [comment] 2017-02-24 00:23
Interesting because @LucasVanDongen, like me, is saying his still wasn't working even after adding all that submission info. I am currently only setting the following

`submission_information({
  add_id_info_serves_ads: false,
  export_compliance_contains_third_party_cryptography: false
})`

and mine is succeeding but **not** being submitted for review. I will try your settings, with them obviously set to false since we don't use Ads or crypto and see if that combo gets it to actually submit. I definitely have submit_for_review:true because without it you don't even get the log about it being submitted for review (even though it actually is not submitting)

**Comment by stonedauwg** [comment] 2017-02-24 00:38
Just attempted it with info I had above plus the properties from @jostster as submission info and this time it worked! So does this mean fastlane/ITC _requires_ some of those properties?

**Comment by jostster** [comment] 2017-02-24 00:45
@stonedauwg if you go into ITC and attempt to submit manually does it prompt you with some check boxes to check? if so then those are the fields that you will need to specify in fastlane.

**Comment by stonedauwg** [comment] 2017-02-24 00:57
@jostster That's the strange thing, manually it asks about: export crypto, 3rd party content and Ad IDs. I only specified 2 of those 3 in the submission info above as you can see. I did not specify the `content_rights_contains_third_party_content property`, so it can't be as simple as just have the ones it asks for on the web portal. Must be something else that ITC requires that fastlane deliver doesn't warn about not providing

**Comment by jostster** [comment] 2017-02-24 01:27
so if you specify `content_rights_contains_third_party_content` then it wont submit? because in your previous post you said `submission_information({ add_id_info_serves_ads: false, export_compliance_contains_third_party_cryptography: false })` which is different.

**Comment by stonedauwg** [comment] 2017-02-24 14:25
@jostster I tried those two plus the third option of content_rights_contains_third_party_content and it did **not** work. So its definitely one of the _other_ settings it requires. If I had to guess maybe add_id_info_uses_idfa but I'd have to try them one at a time to be sure

**Comment by stonedauwg** [comment] 2017-02-24 18:36
Got it work again, this time only with these minimal settings:

```
submission_information({
  add_id_info_serves_ads: false,
  export_compliance_contains_third_party_cryptography: false,
  export_compliance_encryption_updated: false,
  add_id_info_uses_idfa: false,
  content_rights_contains_third_party_content: false
})
```
Previous to that I had sent the 4 above minus export_compliance_encryption_updated, so that was defineitely key. That said, I'm not sure if some of those above I know **arent** necessary, but that is the 5 I seem to need to get it to submit

**Comment by hjanuschka** [comment] 2017-02-28 14:13
issue seems to be resolved - going to close it, feel free to reopen or file a new one at any time

**Comment by jostster** [comment] 2017-02-28 16:08
@hjanuschka I dont think this is resolved. The issue was originally created as the deliver says it WAS submitted for review when it really wasn't. Submit is not checking for a proper response it seems before relaying it was submitted.

**Comment by LucasVanDongen** [comment] 2017-03-08 18:54
I agree with @jostster 

After iterating over a few variations I ended up with this:

```
    deliver(
      force: true,
      app_review_information: {
        #redacted out
      },
      submission_information: {
        add_id_info_serves_ads: false,
        export_compliance_contains_third_party_cryptography: false
      },
      app_version: "3.4.2"
    )
```

I was actually surprised to see it appear in iTunes Connect all of a sudden!

**Comment by evilDave** [comment] 2017-04-21 01:43
This does not seem to be resolved:

INFO [2017-04-21 10:27:42.76]: Submitting the app for review...
INFO [2017-04-21 10:28:11.07]: Successfully submitted the app for review!

app not submitted for review.

Just to be clear, this issue is with the reporting of success when not successful, not the failure - I assume that if I correct the problem in the deliver call (thanks @LucasVanDongen for the info) it should work.

**Comment by Wojcik** [comment] 2017-06-12 14:53
Same for me
[17:52:22]: Successfully selected build
[17:52:22]: Submitting the app for review...
[17:52:33]: Setting 'add_id_info_serves_ads' to 'false'...
[17:52:33]: Setting 'export_compliance_contains_third_party_cryptography' to 'false'...
[17:52:33]: Setting 'export_compliance_encryption_updated' to 'false'...
[17:52:33]: Setting 'add_id_info_uses_idfa' to 'false'...
[17:52:33]: Setting 'content_rights_contains_third_party_content' to 'false'...
[17:52:35]: Successfully submitted the app for review!
Build was selected, but app is still in Prepare for sumbittion status

**Comment by hksna** [comment] 2017-09-21 22:37
How do I specify submission_information through Shell. I'm using fastlane deliver command through bash on Mac server. Here goes the command. I'm not sure how do I pass export_compliance and idfa information through this.

fastlane deliver --skip_binary_upload --submit_for_review -x false -f true  -u hks@netapp.com

**Comment by DMAPro** [comment] 2017-10-11 20:54
Still having this issue with Fastlane 2.61.0. Deliver is reporting success although it failed to submit the app for review.

**Comment by LucasVanDongen** [comment] 2017-10-11 21:00
@DMAPro I think the best approach is uploading it manually, note all the things that are asked and what you answered and add only that information and nothing else. This tool automates that process and if you are adding stuff that is not required (like answering a question never asked in your path) you might trigger unexpected problems.

**Comment by DMAPro** [comment] 2017-10-12 12:44
@LucasVanDongen, thanks. That's understood. The issue isn't that Fastlane doesn't do something. The issue is exactly that Fastlane says it did something when it didn't. So, in any case with any release we've got to go to iTunesConnect and manually verify that it was actually submitted, or verify that we received a confirmation e-mail from Apple.
If deliver said, that it was able to upload metadata, but not to submit the app for review, it would be a valid behavior.
In any case, deliver is still extremely helpful, since all I have to do now is just press "Submit for review". But if it was possible to trust the "success" message that it returns again, it would be great :)

**Comment by LucasVanDongen** [comment] 2017-10-12 12:46
@DMAPro that's right, Fastlane should either ignore incompatible sets of parameters, show a warning or even stop with an error. All would be better than getting a positive confirmation while it fails.

**Comment by DMAPro** [comment] 2017-10-12 12:58
@LucasVanDongen True. Do you know if there's anything we need to do to get this issue reopened? Or is activity in the comments enough? Maybe we should @-mention anyone from the Fastlane team?

**Comment by taquitos** [comment] 2017-10-12 15:13
@DMAPro @LucasVanDongen I'm taking a look at this today.

**Comment by taquitos** [comment] 2017-10-12 18:42
Oh boy. I found the root cause of this. Looks like Apple started returning errors in different places. Working on a fix.

**Closed** 2017-10-12 20:21 UTC
Labels: status: waiting-for-reply
