### ISSUE TITLE
Pilot changelog parameter not adding what's new when run in a fastlane lane?

### ISSUE THREAD

**Issue by lemonkey** [fastlane/fastlane#698] opened 2015-10-14 19:19 UTC
I was trying to use the new changelog parameter for the pilot action (internal testing) in one of my lanes and I'm not seeing my text in the "What's New" section of a processed TestFlight beta build on iTunes Connect. 

Incidentally it doesn't seem that Apple is also showing any what's new text in the TestFlight iOS app if it is entered after the fact.

fastlane (1.32.4)
fastlane_core (0.22.1)
pilot (0.3.0)

Usage of pilot action:

pilot(
      ipa: "path to ipa file",
      skip_submission: true,
      changelog: "Testing what's new"
    )

**Comment by camh** [comment] 2016-01-20 03:13
Also seeing this. Using a `prompt` action to set a changelog doesn't show up in iTunes Connect or the TestFlight app.

Manually setting a description in iTunes Connect shows up in the app, though.

**Comment by marcelo-schroeder** [comment] 2016-01-22 23:16
I was about to create an issue for this. I've started using Fastlane a couple of months ago and one of the tasks I have automated is the submission of my app to Testflight for internal testing using the pilot action. The changelog parameter has never worked for me. Whatever string I pass to it, it never shows app in the "What to Test" field of a build submitted for testing. The description of the issue here mentions the "What's New" section though... is that something different? Maybe my understanding of what the changelog parameter should do is incorrect?

**Comment by whootang12** [comment] 2016-01-22 23:34
+1.  I also was under the understanding that this param would populate "What to Test" section in Testflight.  This is what is populated in the email sent to users and shown in the release notes of the testflight app.  This is only included in those if it is saved while the build updated is still being "processed".  It'd be great if this could be automated, otherwise I have to upload via pilot, then manually log into iTunes Connect to save these values.

**Comment by marcelo-schroeder** [comment] 2016-01-22 23:38
I completely agree. And Apple is obviously making it more difficult by having this small window in which you can update the text, which is weird...

**Comment by Paulo-Branco** [comment] 2016-01-22 23:43
It's the same thing. The "What to test" field is sometimes (wrongly) referred to as "What's New". As far as I know setting the changelog (which only affects the AppStore page) is working properly, it's just the TestFlights' fields that people are having trouble with. The only way I could get around this was by writing a ruby script that used spaceship directly to set the "What to test" on TestFlight builds.

**Comment by whootang12** [comment] 2016-01-23 03:53
Any chance you can share what you have it seems to be working?

**Comment by squarefrog** [comment] 2016-01-26 08:56
This did indeed used to work, there is [an issue on Pilot](https://github.com/fastlane/pilot/issues/86) regarding it. 

@Paulo-Branco any chance you can share your script for setting "What to Test" directly though Spaceship?

**Comment by ohwutup** [comment] 2016-01-28 21:32
going to close this issue as its a dupe of https://github.com/fastlane/pilot/issues/86. feel free to reopen if you feel necessary! thanks!

**Closed** 2016-01-28 21:32 UTC

**Comment by urimagisto** [comment] 2016-04-27 13:28
I am facing the same pilot issue for not being able to upload the changelog into "What to test" field, however when manually adding in ITC site i am able to see it reflected in testFlight app via my mobile(after the build is already uploaded). Is there anyone who managed to solve it through pilot fastlane tool?

I am using:
pilot 1.5.0
Xcode 7.3
EL capitan 10.11.4

running: pilot --verbose upload --skip_submission --changelog "testing What to test field" \
-u my_user \
-a bundleId \
-i $PATH_IPA
