### ISSUE TITLE
Update privacy url in App Store is not working now.

### ISSUE THREAD

**Issue by BiswajitRedoQ** [fastlane/fastlane#21745] opened 2023-12-20 11:31 UTC
### New Regression Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information
- Breaking version: 2.217.0
- Last working version: 2.216.0

### Regression Description
fastlane deliver on 2.217.0 fails to upload a privacy url for an iOS app from fastlane/metadata/en-GB/privacy_url. This works as expected on fastlane 2.216.0.

<img width="514" alt="Screenshot 2023-12-20 at 4 23 22 PM" src="https://github.com/fastlane/fastlane/assets/154425598/a1882f95-4341-4c4f-ba50-f4195f48af8e">

### Testing Steps
1. Change the privacy url in a project with fastlane/metadata/en-GB/privacy_url.txt
2. Use fastlane deliver to upload the change

**Comment by shizu2014** [comment] 2023-12-24 00:52
same

**Comment by Lutzifer** [comment] 2024-01-02 14:56
is this a duplicate of #21744 or do they differ in some way? if they are duplicates, please close one of the issues

**Comment by lacostej** [comment] 2024-02-23 10:12
closing this in favor of #21744

**Closed by lacostej** 2024-02-23 10:12 UTC
