### ISSUE TITLE
Match sets wrong app group id on developer portal

### ISSUE THREAD

**Issue by RishabhTayal** [fastlane/fastlane#8483] opened 2017-03-09 16:10 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I have separate app identifier and separate app group identifier for different `type`(development, adhd, appstore). Sometimes when I run `match` the app group identifiers are wrongly reassigned on developer.apple.com automatically by `fastlane`. 

#### Original:
```
com.app.identifier1 -> com.appgroup.identifier1
com.app.identifier2 -> com.appgroup.identifier2
```
#### becomes
```
com.app.identifier1 -> com.appgroup.identifier2
com.app.identifier2 -> com.appgroup.identifier2
```

**Comment by yukiasai** [comment] 2017-03-12 07:47
I have a same problem. But I don't know the cause. I'll try to fix it!

**Comment by yukiasai** [comment] 2017-03-13 03:51
@RishabhTayal I guess this issue is similar to https://github.com/lionheart/openradar-mirror/issues/16702 . Is `Automatically manage signing` on your project turned on? It may reassign the app group identifier.

**Comment by RishabhTayal** [comment] 2017-03-13 14:05
@yukiasai The `Automatically manage signing` is turned off.

**Comment by RishabhTayal** [comment] 2017-03-13 14:06
I found there is an option in `produce` we can use to associate a group with app id (`associate_group`). But that command assigns the group everytime which makes all the provisioning profile invalid. we have to run `match` again on the app id.

**Closed** 2017-06-19 14:14 UTC
Labels: status: auto-closed, status: waiting-for-reply, tool: match
