### ISSUE TITLE
Potential Issue with update_info_plist

### ISSUE THREAD

**Issue by jeeftor** [fastlane/fastlane#3664] opened 2016-03-10 01:23 UTC
I'm pretty sure there is an issue with `update_info_plist` action.  I keep coming getting these git-diff "thingys" all the time:
![screen shot 2016-03-09 at 8 21 29 pm](https://cloud.githubusercontent.com/assets/6491743/13656419/a532b20a-e634-11e5-880f-2b52c8739ca6.png)

    -<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    +<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">

It looks like its stripping **Computer** out of the plist. - I'm not 100% sure this is the culprit but I am running that function (a lot) and I think besides xcode its the only thing touching the plist file.  I'll try to look in more detail tomorrow.

**Comment by ohwutup** [comment] 2016-05-24 20:21
Hey @jeeftor, I noticed this as well in a project of mine. I believe it is the result of the `Plist` ruby class. It writes differently than whatever Xcode is using under the hood. Although I think this fixed in more recent versions as I am not able to reproduce the issue. I am going to close this for now, but if you can still repro on up to date versions, leave steps here and we will reopen the issue. Thanks! 🍡

**Closed by ohwutup** 2016-05-24 20:21 UTC
Labels: bug, fastlane, help wanted
