### ISSUE TITLE
[Fastlane.Swift] Error "You can only pass either a workspace or a project path, not both"

### ISSUE THREAD

**Issue by stherold** [fastlane/fastlane#18471] opened 2021-03-29 15:32 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I run `bundle exec fastlane init swift` (no problems) and `bundle exec fastlane` and directly get the error:

```
[17:29:41]: You can only pass either a workspace or a project path, not both
[17:29:41]: fastlane finished with errors

[!] You can only pass either a workspace or a project path, not both
```

##### Command executed
- `bundle exec fastlane init swift` 
- `bundle exec fastlane`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
[17:29:41]: loading manifest: /Users/stherold/.gem/gems/fastlane-2.179.0/fastlane/swift/upgrade_manifest.json
[17:29:41]: FastlaneSwiftRunner project is up-to-date
+-----------+----------------------------+
|              Lane Context              |
+-----------+----------------------------+
| LANE_NAME | readLatestBuildNumbersLane |
+-----------+----------------------------+
[17:29:41]: You can only pass either a workspace or a project path, not both
[17:29:41]: fastlane finished with errors

[!] You can only pass either a workspace or a project path, not both
 </pre>
</details>

### Environment

<details>
  <pre> 
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.2.3                                                         |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.30.2                                             |
| Installation Source         | ~/.gem/bin/fastlane                                            |
| Host                        | macOS 11.2.3 (20D91)                                           |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.4                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile.swift`</summary>

```ruby
import Foundation

class Fastfile: LaneFile {

    func readLatestBuildNumbersLane(withOptions options:[String: String]?) throws {
        desc("Description of what the lane does")

    }
}

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.179.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.3.0        |
| bundler                       | 2.2.13       |
| rake                          | 13.0.3       |
| CFPropertyList                | 3.0.3        |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| artifactory                   | 3.0.15       |
| atomos                        | 0.1.3        |
| aws-eventstream               | 1.1.1        |
| aws-partitions                | 1.436.0      |
| aws-sigv4                     | 1.2.3        |
| jmespath                      | 1.4.0        |
| aws-sdk-core                  | 3.113.0      |
| aws-sdk-kms                   | 1.43.0       |
| aws-sdk-s3                    | 1.93.0       |
| babosa                        | 1.0.4        |
| claide                        | 1.0.3        |
| colored2                      | 3.1.2        |
| cork                          | 0.3.0        |
| nap                           | 1.1.0        |
| open4                         | 1.3.4        |
| claide-plugins                | 0.9.2        |
| coderay                       | 1.1.3        |
| colored                       | 1.2          |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| faraday-net_http              | 1.0.1        |
| multipart-post                | 2.0.0        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.3.0        |
| faraday-http-cache            | 2.2.0        |
| rchardet                      | 1.8.0        |
| git                           | 1.8.1        |
| rexml                         | 3.2.4        |
| kramdown                      | 2.3.1        |
| kramdown-parser-gfm           | 1.1.0        |
| no_proxy_fix                  | 0.1.2        |
| sawyer                        | 0.8.2        |
| octokit                       | 4.20.0       |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| danger                        | 8.2.3        |
| danger-plugin-api             | 1.0.0        |
| danger-changelog              | 0.6.1        |
| danger-commit_lint            | 0.0.7        |
| thor                          | 0.20.3       |
| danger-swiftlint              | 0.24.5       |
| dotenv                        | 2.7.6        |
| emoji_regex                   | 3.2.2        |
| excon                         | 0.79.0       |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.3        |
| gh_inspector                  | 1.1.3        |
| jwt                           | 2.2.2        |
| memoist                       | 0.16.2       |
| multi_json                    | 1.15.0       |
| os                            | 1.1.1        |
| signet                        | 0.15.0       |
| googleauth                    | 0.16.0       |
| httpclient                    | 2.8.3        |
| mini_mime                     | 1.0.3        |
| declarative                   | 0.0.20       |
| declarative-option            | 0.1.0        |
| uber                          | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.2        |
| google-api-client             | 0.38.0       |
| digest-crc                    | 0.6.3        |
| webrick                       | 1.7.0        |
| google-apis-core              | 0.3.0        |
| google-apis-iamcredentials_v1 | 0.2.0        |
| google-apis-storage_v1        | 0.3.0        |
| google-cloud-env              | 1.5.0        |
| google-cloud-errors           | 1.1.0        |
| google-cloud-core             | 1.6.0        |
| google-cloud-storage          | 1.31.0       |
| json                          | 2.5.1        |
| mini_magick                   | 4.11.0       |
| naturally                     | 2.2.1        |
| plist                         | 3.6.0        |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| simctl                        | 1.6.8        |
| slack-notifier                | 2.3.2        |
| terminal-notifier             | 2.0.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| word_wrap                     | 1.0.0        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| xcpretty-travis-formatter     | 1.0.1        |
| xcresult                      | 0.2.1        |
| xcov                          | 1.7.5        |
| danger-xcov                   | 0.5.0        |
| method_source                 | 1.0.0        |
| pry                           | 0.14.0       |
</details>

*generated on:* **2021-03-29**
</details>
 </pre>
</details>

**Comment by stherold** [comment] 2021-03-29 15:54
Okay I found this only happens when I do not **manually** rebuild `fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj` after modification - is this intended?

**Comment by stherold** [comment] 2021-03-29 15:54
Just a side question - is it possible to output colored error message in FL Swift?

**Comment by minuscorp** [comment] 2021-03-29 18:19
Why'd you modify exactly the project?
Where do you want the output to be colored? In the console or in the xcode debug console?

**Comment by Blackjacx** [comment] 2021-03-30 09:29
> Why'd you modify exactly the project?

I just open the project to modify Fastfile.swift [as described in the official docs](https://docs.fastlane.tools/getting-started/ios/fastlane-swift/#step-2). It is the same as `./fastlane/Fastfile.swift`. But when I don't rebuild this project, the execution of fastlane results in the error above :-(

> Where do you want the output to be colored? In the console or in the xcode debug console?

In the console when executing `bundle exec fastlane <lane_name>` I try to get a red colored output similar to `UI.error "💥"` in ruby.

**Comment by minuscorp** [comment] 2021-03-30 11:49
Could you share more about the backtrace?

**Comment by minuscorp** [comment] 2021-03-30 11:52
Seems like fastlane is trying to execute the following lane `readLatestBuildNumbersLane `, could you share more info about that lane?

**Comment by Blackjacx** [comment] 2021-03-30 13:37
This is just an example lane, it's empty. The error also happens when I run `bundle exec fastlane`. I just need to modify Fastfile.swift.

**Comment by minuscorp** [comment] 2021-03-30 14:27
I'll try to figure out which lane is Swift trying to execute there and why is crashing.

**Comment by Peelz** [comment] 2021-04-01 02:17
I have got this message also, and I fixed by remove parameter in build_ios_app.
You have to pass **project** or **workspace** (can not even pass nil)

**Comment by minuscorp** [comment] 2021-04-01 12:23
Related to #17343

**Comment by stherold** [comment] 2021-04-09 19:15
Not sure if this is all related. As I said, I just need to modify Fastfile.swift, e.g. just add a space or line break, and run `bundle exec fastlane`. Then I get this error. It seems I hjave to rebuild the FastlaneRunner project everytime I modify Fastfile.swift. Is that correct? Why can't this happen automatically? Or am I doing something wrong?

**Comment by Blackjacx** [comment] 2021-04-09 19:16
Not sure if this is all related. As I said, I just need to modify Fastfile.swift, e.g. just add a space or line break, and run `bundle exec fastlane`. Then I get this error. It seems I hjave to rebuild the FastlaneRunner project everytime I modify Fastfile.swift. Is that correct? Why can't this happen automatically? Or am I doing something wrong?

**Comment by minuscorp** [comment] 2021-04-09 20:46
I understood wrongly, I assumed that the bug was raised by the lane content itself and not by the Swift project loads itself, so when a Swift configuration is made it builds the fastlane project, which creates the binary that is being executed afterwards so it'll load an old representation of the Fastfile if no build is being made between runs, but I'd need a whole backtrace to dig into the issue more (it seems to be cut off in the issue) maybe with `logMode verbose` you can send me the whole log, hopefully.

**Comment by Blackjacx** [comment] 2021-04-12 09:23
Hmm not much more info except the trace... Maybe it helps: 

```
$ bundle exec fastlane --verbose
[✔] 🚀
DEBUG [2021-04-12 11:22:18.24]: Checking if there are any plugins that should be loaded...
INFO [2021-04-12 11:22:18.35]: loading manifest: /Users/stherold/.gem/gems/fastlane-2.180.1/fastlane/swift/upgrade_manifest.json
DEBUG [2021-04-12 11:22:18.41]: No missing groups found, so we don't need to worry about adding new groups
DEBUG [2021-04-12 11:22:18.41]: Actions.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.56/0.9.56
DEBUG [2021-04-12 11:22:18.41]: Fastlane.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.117/0.9.117
DEBUG [2021-04-12 11:22:18.41]: DeliverfileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.64/0.9.64
DEBUG [2021-04-12 11:22:18.41]: GymfileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.67/0.9.67
DEBUG [2021-04-12 11:22:18.41]: MatchfileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.61/0.9.61
DEBUG [2021-04-12 11:22:18.41]: Plugins.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.56/0.9.56
DEBUG [2021-04-12 11:22:18.41]: PrecheckfileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.60/0.9.60
DEBUG [2021-04-12 11:22:18.41]: ScanfileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.72/0.9.72
DEBUG [2021-04-12 11:22:18.41]: ScreengrabfileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.62/0.9.62
DEBUG [2021-04-12 11:22:18.41]: SnapshotfileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.56/0.9.56
DEBUG [2021-04-12 11:22:18.41]: LaneFileProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2021-04-12 11:22:18.41]: ControlCommand.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2021-04-12 11:22:18.41]: RubyCommand.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2021-04-12 11:22:18.41]: RubyCommandable.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2021-04-12 11:22:18.41]: Runner.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2021-04-12 11:22:18.41]: SocketClient.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2021-04-12 11:22:18.41]: SocketClientDelegateProtocol.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2021-04-12 11:22:18.41]: SocketResponse.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2021-04-12 11:22:18.41]: main.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2021-04-12 11:22:18.41]: ArgumentProcessor.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2021-04-12 11:22:18.41]: RunnerArgument.swift FastlaneRunnerAPIVersion (bundled/target): 0.9.2/0.9.2
DEBUG [2021-04-12 11:22:18.41]: Checking for new user-provided tool configuration files
INFO [2021-04-12 11:22:18.42]: FastlaneSwiftRunner project is up-to-date
DEBUG [2021-04-12 11:22:18.42]: Found changes to user's Fastfile.swift, setting re-build runner flag
DEBUG [2021-04-12 11:22:18.42]: Building FastlaneSwiftRunner
WARN [2021-04-12 11:22:18.43]: Lane Context:
INFO [2021-04-12 11:22:18.43]: {:LANE_NAME=>nil}
ERROR [2021-04-12 11:22:18.43]: You can only pass either a workspace or a project path, not both
ERROR [2021-04-12 11:22:18.43]: fastlane finished with errors

Traceback (most recent call last):
	35: from /Users/stherold/.gem/bin/bundle:23:in `<main>'
	34: from /Users/stherold/.gem/bin/bundle:23:in `load'
	33: from /Users/stherold/.gem/gems/bundler-2.2.16/exe/bundle:37:in `<top (required)>'
	32: from /Users/stherold/.gem/gems/bundler-2.2.16/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
	31: from /Users/stherold/.gem/gems/bundler-2.2.16/exe/bundle:49:in `block in <top (required)>'
	30: from /Users/stherold/.gem/gems/bundler-2.2.16/lib/bundler/cli.rb:24:in `start'
	29: from /Users/stherold/.gem/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	28: from /Users/stherold/.gem/gems/bundler-2.2.16/lib/bundler/cli.rb:30:in `dispatch'
	27: from /Users/stherold/.gem/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	26: from /Users/stherold/.gem/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	25: from /Users/stherold/.gem/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	24: from /Users/stherold/.gem/gems/bundler-2.2.16/lib/bundler/cli.rb:494:in `exec'
	23: from /Users/stherold/.gem/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:28:in `run'
	22: from /Users/stherold/.gem/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:63:in `kernel_load'
	21: from /Users/stherold/.gem/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:63:in `load'
	20: from /Users/stherold/.gem/bin/fastlane:23:in `<top (required)>'
	19: from /Users/stherold/.gem/bin/fastlane:23:in `load'
	18: from /Users/stherold/.gem/gems/fastlane-2.180.1/bin/fastlane:23:in `<top (required)>'
	17: from /Users/stherold/.gem/gems/fastlane-2.180.1/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	16: from /Users/stherold/.gem/gems/fastlane-2.180.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	15: from /Users/stherold/.gem/gems/fastlane-2.180.1/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	14: from /Users/stherold/.gem/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	13: from /Users/stherold/.gem/gems/fastlane-2.180.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	12: from /Users/stherold/.gem/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	11: from /Users/stherold/.gem/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	10: from /Users/stherold/.gem/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 9: from /Users/stherold/.gem/gems/fastlane-2.180.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	 8: from /Users/stherold/.gem/gems/fastlane-2.180.1/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
	 7: from /Users/stherold/.gem/gems/fastlane-2.180.1/fastlane/lib/fastlane/swift_lane_manager.rb:29:in `cruise_lane'
	 6: from /Users/stherold/.gem/gems/fastlane-2.180.1/fastlane/lib/fastlane/swift_lane_manager.rb:248:in `ensure_runner_built!'
	 5: from /Users/stherold/.gem/gems/fastlane-2.180.1/fastlane/lib/fastlane/swift_lane_manager.rb:286:in `build_runner!'
	 4: from /Users/stherold/.gem/gems/fastlane-2.180.1/gym/lib/gym/module.rb:15:in `config='
	 3: from /Users/stherold/.gem/gems/fastlane-2.180.1/gym/lib/gym/detect_values.rb:18:in `set_additional_default_values'
	 2: from /Users/stherold/.gem/gems/fastlane-2.180.1/fastlane_core/lib/fastlane_core/project.rb:13:in `detect_projects'
	 1: from /Users/stherold/.gem/gems/fastlane-2.180.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Users/stherold/.gem/gems/fastlane-2.180.1/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': You can only pass either a workspace or a project path, not both (FastlaneCore::Interface::FastlaneError)
	35: from /Users/stherold/.gem/bin/bundle:23:in `<main>'
	34: from /Users/stherold/.gem/bin/bundle:23:in `load'
	33: from /Users/stherold/.gem/gems/bundler-2.2.16/exe/bundle:37:in `<top (required)>'
	32: from /Users/stherold/.gem/gems/bundler-2.2.16/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
	31: from /Users/stherold/.gem/gems/bundler-2.2.16/exe/bundle:49:in `block in <top (required)>'
	30: from /Users/stherold/.gem/gems/bundler-2.2.16/lib/bundler/cli.rb:24:in `start'
	29: from /Users/stherold/.gem/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	28: from /Users/stherold/.gem/gems/bundler-2.2.16/lib/bundler/cli.rb:30:in `dispatch'
	27: from /Users/stherold/.gem/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	26: from /Users/stherold/.gem/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	25: from /Users/stherold/.gem/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	24: from /Users/stherold/.gem/gems/bundler-2.2.16/lib/bundler/cli.rb:494:in `exec'
	23: from /Users/stherold/.gem/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:28:in `run'
	22: from /Users/stherold/.gem/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:63:in `kernel_load'
	21: from /Users/stherold/.gem/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:63:in `load'
	20: from /Users/stherold/.gem/bin/fastlane:23:in `<top (required)>'
	19: from /Users/stherold/.gem/bin/fastlane:23:in `load'
	18: from /Users/stherold/.gem/gems/fastlane-2.180.1/bin/fastlane:23:in `<top (required)>'
	17: from /Users/stherold/.gem/gems/fastlane-2.180.1/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	16: from /Users/stherold/.gem/gems/fastlane-2.180.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	15: from /Users/stherold/.gem/gems/fastlane-2.180.1/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	14: from /Users/stherold/.gem/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	13: from /Users/stherold/.gem/gems/fastlane-2.180.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	12: from /Users/stherold/.gem/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	11: from /Users/stherold/.gem/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	10: from /Users/stherold/.gem/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 9: from /Users/stherold/.gem/gems/fastlane-2.180.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	 8: from /Users/stherold/.gem/gems/fastlane-2.180.1/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
	 7: from /Users/stherold/.gem/gems/fastlane-2.180.1/fastlane/lib/fastlane/swift_lane_manager.rb:29:in `cruise_lane'
	 6: from /Users/stherold/.gem/gems/fastlane-2.180.1/fastlane/lib/fastlane/swift_lane_manager.rb:248:in `ensure_runner_built!'
	 5: from /Users/stherold/.gem/gems/fastlane-2.180.1/fastlane/lib/fastlane/swift_lane_manager.rb:286:in `build_runner!'
	 4: from /Users/stherold/.gem/gems/fastlane-2.180.1/gym/lib/gym/module.rb:15:in `config='
	 3: from /Users/stherold/.gem/gems/fastlane-2.180.1/gym/lib/gym/detect_values.rb:18:in `set_additional_default_values'
	 2: from /Users/stherold/.gem/gems/fastlane-2.180.1/fastlane_core/lib/fastlane_core/project.rb:13:in `detect_projects'
	 1: from /Users/stherold/.gem/gems/fastlane-2.180.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Users/stherold/.gem/gems/fastlane-2.180.1/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': [!] You can only pass either a workspace or a project path, not both (FastlaneCore::Interface::FastlaneError)
```

**Comment by minuscorp** [comment] 2021-04-12 10:41
Use the parameter `logMode verbose` to the call, so we can see the socket communication flow, but the interesting fail is this line:
`2: from /Users/stherold/.gem/gems/fastlane-2.180.1/fastlane_core/lib/fastlane_core/project.rb:13:in detect_projects'`
Wondering why is this being called, need to take a deeper look into the calls being made, will try to reproduce this locally asap.

**Comment by Blackjacx** [comment] 2021-09-15 16:33
Hey there I guess we can close this. It gets re-opened all the time. But as the bot says there is no activity here. I also don't continue on my Fastlane.swift based project.

**Closed** 2022-01-11 17:32 UTC
Labels: status: waiting-for-reply, topic: swift
