### ISSUE TITLE
pilot find/remove fails with "undefined method `admin?' for nil:NilClass"

### ISSUE THREAD

**Issue by ldjhust** [fastlane/fastlane#9973] opened 2017-08-07 01:57 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

My iTunes Connect account has an `App Manager` role, when I try to use pilot to manage testers, it always fails with the same error:

>PS: I can use this account to manage (search/add/remove) my testers on the iTunes Connect Web, and that's what I do all the time. 

The command I use:

```
fastlane pilot find someont@test.com -a com.xxx.xxx -u <my account>

or

fastlane pilot remove someont@test.com -a com.xxx.xxx -u <my account>
```

And the error message:

```
undefined method `admin?' for nil:NilClass

[!] Some operations failed: undefined method `admin?' for nil:NilClass
```

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

The `--capture_output` argument seems doesn't exist:

```
fastlane pilot remove someont@test.com -a com.xxx.xxx -u <my account> --capture_output

invalid option: --capture_output
```

So I use `--verbose` option:

```
fastlane pilot remove someont@test.com -a com.xxx.xxx -u <my account> --verbose
```

And the verbose output is here:

```
ERROR [2017-08-07 09:54:39.09]: undefined method `admin?' for nil:NilClass
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.51.0.beta.20170807010003/fastlane_core/lib/fastlane_core/ui/interface.rb:131:in `user_error!': [!] Some operations failed: undefined method `admin?' for nil:NilClass (FastlaneCore::Interface::FastlaneError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.51.0.beta.20170807010003/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.51.0.beta.20170807010003/pilot/lib/pilot/commands_generator.rb:38:in `handle_multiple'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.51.0.beta.20170807010003/pilot/lib/pilot/commands_generator.rb:129:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.51.0.beta.20170807010003/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.51.0.beta.20170807010003/pilot/lib/pilot/commands_generator.rb:159:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.51.0.beta.20170807010003/pilot/lib/pilot/commands_generator.rb:12:in `start'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.51.0.beta.20170807010003/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.51.0.beta.20170807010003/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.1_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version                    | Update-Status |
| -------- | -------------------------- | ------------- |
| fastlane | 2.51.0.beta.20170807010003 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.57.1       |
| faraday                   | 0.12.2       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.3       |
| faraday_middleware        | 0.12.0       |
| io-console                | 0.4.6        |
| openssl                   | 2.0.3        |
</details>

*generated on:* **2017-08-07**
</details>

Thank you very much for any help!

**Comment by KrauseFx** [comment] 2017-08-07 03:59
Thanks for submitting this issue, seems like it's a duplicate of https://github.com/fastlane/fastlane/issues/9893?

**Comment by KrauseFx** [comment] 2017-08-07 03:59
Actually let's stay on this issue instead

**Comment by taquitos** [comment] 2017-08-07 16:02
I'm taking a look at this right now 👍

**Comment by taquitos** [comment] 2017-08-07 16:38
@ldjhust the username you're using... is that an email address or is it an older appleID that existed before you were required to use your email address for username?

**Comment by ldjhust** [comment] 2017-08-08 01:42
@taquitos Thank you for your hard work! Yes, the username is my email address.

**Comment by taquitos** [comment] 2017-08-08 01:46
Reopening because I'm not positive the patch will fix it, but at the very least, we'll hopefully get some more information on the failure.

**Comment by ldjhust** [comment] 2017-08-09 01:27
@taquitos I tested the new pre-release, the "find" operation is worked as expected now, but the "remove" operation still returns an error as following:

```
Login to iTunes Connect (<my email account>)
Login successful
**Found existing tester someone@test.com**
**Could not remove someone@test.com from app: undefined method `remove_from_app!' for nil:NilClass**
undefined method `remove_from_app!' for nil:NilClass

[!] Some operations failed: undefined method `remove_from_app!' for nil:NilClass
```

The command I use:

```
fastlane pilot remove someone@test.com -a com.xx.xx -u <my email account>
```

The verbose output:

```
Login successful
Found existing tester someone@test.com
ERROR : Could not remove someone@test.com from app: undefined method `remove_from_app!' for nil:NilClass
ERROR : undefined method `remove_from_app!' for nil:NilClass
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.52.0.beta.20170809010003/fastlane_core/lib/fastlane_core/ui/interface.rb:131:in `user_error!': [!] Some operations failed: undefined method `remove_from_app!' for nil:NilClass (FastlaneCore::Interface::FastlaneError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.52.0.beta.20170809010003/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.52.0.beta.20170809010003/pilot/lib/pilot/commands_generator.rb:38:in `handle_multiple'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.52.0.beta.20170809010003/pilot/lib/pilot/commands_generator.rb:129:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.52.0.beta.20170809010003/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.52.0.beta.20170809010003/pilot/lib/pilot/commands_generator.rb:159:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.52.0.beta.20170809010003/pilot/lib/pilot/commands_generator.rb:12:in `start'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.52.0.beta.20170809010003/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.52.0.beta.20170809010003/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'
```

The fastlane env:

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.1_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version                    | Update-Status |
| -------- | -------------------------- | ------------- |
| fastlane | 2.52.0.beta.20170809010003 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.57.1       |
| faraday                   | 0.12.2       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.3       |
| faraday_middleware        | 0.12.0       |
| io-console                | 0.4.6        |
| openssl                   | 2.0.3        |
</details>


*generated on:* **2017-08-09**
</details>

**Comment by ldjhust** [comment] 2017-08-09 02:12
By the way, I just reference #8979 and find that I also can "remove" the first several external testers with this pre-release. But because the "someone@test.com" is not the one of the first several, so it returns the error. Does this is the same reason with #8979 ?

**Comment by taquitos** [comment] 2017-08-09 02:22
😭 I haven't seen #8979, but I'll take a look a little later tomorrow. Making progress... slow but steady.
I'd be willing to guess the underlying cause is the same, a mismatch between appleId and email.

**Comment by ldjhust** [comment] 2017-08-09 02:24
OK, Thank you very much!

**Comment by taquitos** [comment] 2017-08-10 16:33
@ldjhust digging into this, could you tell me the setup required to repro this? How did you add the tester? Is the tester a tester on any other apps? What tester group(s) are they in?

**Comment by ldjhust** [comment] 2017-08-11 01:28
@taquitos OK, thanks very much again! I have 2000 testers, and all of them belong a group 1.0.2, then if I remove a middle tester (for example, the 100th one), an error like above will return. And all of these testers only belong this app.

I think you can repo this like above.

**Comment by ldjhust** [comment] 2017-08-11 01:34
And by the way, I found that I can remove all of them one by one if I according to the order on the "All Testers" tab. But if I try to remove a middle tester then it will be failed like above.

**Comment by taquitos** [comment] 2017-08-11 22:21
@ldjhust I bet this has to do with paging. Currently we use `providers/#{team_id}/apps/#{app_id}/testers?limit=10000` which should return us up to 10k testers for a given app, but maybe that's not happening due to some internal Apple limits. I'll create an account with 2k testers 😮 and try to repro

**Comment by taquitos** [comment] 2017-08-20 01:15
Sorry, I haven't forgotten about this, been busy 😞

**Comment by ldjhust** [comment] 2017-08-21 01:31
Yeah, I know. Thank you very much!:thumbsup:

**Comment by taquitos** [comment] 2017-08-21 23:13
Can confirm, API only returns 40 at a time, regardless of limit

**Comment by ldjhust** [comment] 2017-08-22 01:25
@taquitos Thank you very much for your work! Does this mean we can't delete a tester out of this range use pilot? Do you have a solution for this?

**Comment by taquitos** [comment] 2017-08-22 02:41
🥅 ⚽️ 🐐 !

**Closed** 2017-08-22 18:49 UTC

**Comment by ldjhust** [comment] 2017-08-23 01:49
Thank you very much @taquitos !:thumbsup::thumbsup::thumbsup:
