### ISSUE TITLE
Package Application crashes

### ISSUE THREAD

**Issue by alpersenyurt** [fastlane/fastlane#4128] opened 2016-04-08 18:17 UTC
I have a problem with ""Unable to patch the `PackageApplication` for  tvos swift project.I have updated fastlane version. 

I have fastlane crashes like this:

```
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.41.2/lib/fastlane_core/ui/interface.rb:127:in `crash!': [!] Unable to patch the `PackageApplication` script bundled in Xcode. This is not supported. (FastlaneCore::Interface::FastlaneCrash)
```

After I call this lane I have got the fastlane crash
My fastfile lane:

```ruby
private_lane :build_app do |options|

 gym(
    provisioning_profile_path: "./fastlane/cert/*****iPhone_Development.mobileprovision",
    codesigning_identity: "iPhone Developer:*****",
    export_method: options[:export_method],
    export_team_id: “7YZS5NTGYH”,
    include_bitcode: false,
    use_legacy_build_api: true,
    output_directory: "./build",
    output_name: “Development” 
)
end
```
fastlane version (fastlane -v):1.80.0

**Comment by vpolouchkine** [comment] 2016-04-08 18:33
Please share the full log.

**Comment by alpersenyurt** [comment] 2016-04-11 04:46
full error log ;


/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.41.2/lib/fastlane_core/ui/interface.rb:127:in `crash!': [!] Unable to patch the `PackageApplication` script bundled in Xcode. This is not supported. (FastlaneCore::Interface::FastlaneCrash)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.41.2/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.2/lib/gym/xcodebuild_fixes/package_application_fix.rb:23:in `block in patch_package_application'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:88:in `mktmpdir'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.2/lib/gym/xcodebuild_fixes/package_application_fix.rb:13:in `patch_package_application'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.2/lib/gym/generators/package_command_generator_legacy.rb:14:in `generate'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.2/lib/gym/generators/package_command_generator.rb:16:in `generate'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.2/lib/gym/runner.rb:112:in `package_app'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.2/lib/gym/runner.rb:19:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.2/lib/gym/manager.rb:10:in `work'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.80.0/lib/fastlane/actions/gym.rb:22:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.80.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.80.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.80.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.80.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.80.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.80.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:58:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.80.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.80.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.80.0/lib/fastlane/runner.rb:110:in `try_switch_to_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.80.0/lib/fastlane/fast_file.rb:141:in `rescue in method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.80.0/lib/fastlane/fast_file.rb:136:in `method_missing'
	from Fastfile:28:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.80.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.80.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.80.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.80.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.80.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.80.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.80.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.80.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.41.2/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.80.0/bin/fastlane:158:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.80.0/bin/fastlane:164:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'

**Comment by TKBurner** [comment] 2016-04-11 20:16
Hi @alpersenyurt! Thanks for reaching out. Can you let me know if you are able to run gym from command line without getting this error? Definitely want to get to the bottom of this. 👍

**Comment by alpersenyurt** [comment] 2016-04-12 04:54
Hi @TKBurner  I cant be able to run gym also from command line .I get same error too

**Comment by TKBurner** [comment] 2016-04-12 20:17
@alpersenyurt Thanks for following up! We are going to look into this over here! 👍

**Comment by TKBurner** [comment] 2016-04-14 13:44
dupe of #4170. Hi @alpersenyurt  I'm going to mark this a dupe of 4170, close this ticket, and flag the other one to make sure it gets looked over 👍

**Comment by mfurtak** [comment] 2016-04-14 20:28
Hi @alpersenyurt -

Can you run the following commands for me and let me know what the output is for each?

```
`xcode-select -p`/usr/bin/xcodebuild -version
```

```
md5 `xcode-select -p`/Platforms/iPhoneOS.platform/Developer/usr/bin/PackageApplication
```

Thanks!

**Comment by alpersenyurt** [comment] 2016-04-15 05:00
Hi @mfurtak 

outputs:

`xcode-select -p`/usr/bin/xcodebuild -version

Xcode 7.3
Build version 7D175

md5 `xcode-select -p`/Platforms/iPhoneOS.platform/Developer/usr/bin/PackageApplication

**Comment by mfurtak** [comment] 2016-04-15 13:50
OK, got it. :+1: 

`gym` is failing during a step where we attempt to patch the bad behavior of the `PackageApplication` script to fix arguments given to `codesign`. However, we only attempt to do this if we can verify that it exists in a state we know to be patchable. We do this by checking the MD5 hash value of the file, which is why I asked for you to check that. Unfortunately, the value you gave me doesn't match the value we're looking for.

Have you manually patched the `PackageApplication` script yourself, or in any way modified it?

**Comment by alpersenyurt** [comment] 2016-04-17 20:06
Hi @mfurtak 

No I have not manually patched or modified it.Actually I have this error from our jenkins build machine so I dont know  it is modified  anyway.

**Comment by mfurtak** [comment] 2016-04-20 15:49
Hi @alpersenyurt - we're still looking into this 👍 

This step is unfortunately required for `use_legacy_build_api`. Is turning legacy build API on required for your build? Does it work without it?

The command outputs you gave me... were they for your Jenkins machine, your local machine, or both? Is there any difference in those outputs between those machines?

**Comment by alpersenyurt** [comment] 2016-04-22 20:30
I have tried with  use_legacy_build_api and  without use_legacy_build_api . Both of them is same I had error too. Yes the machine which was have error  is Jenkins machine

**Comment by mfurtak** [comment] 2016-04-22 21:58
Hi @alpersenyurt - I'm not sure how to help any further, so I'm going to try to get some additional 💪 power!

**Comment by KrauseFx** [comment] 2016-04-24 07:55
@alpersenyurt It seems like your version of Xcode has a modified `PackageApplication` script as @mfurtak pointed out. 
Could you try completely uninstalling Xcode and installing it again?
Alternatively please disable the legacy build API by making sure to not include the `use_legacy_build_api` flag in your `Gymfile` or `Fastfile`.

By disabling the legacy build API the `PackageApplication` won't be patched, and it should work as expected. You shouldn't receive the same error message.

Please do so, and share your `Fastfile` (if you have one), your `Gymfile`, the command you ran and the complete output, including the stack trace 👍 

I hope this helps

**Comment by alpersenyurt** [comment] 2016-05-04 11:04
@KrauseFx  @mfurtak 

Thanks it works after reinstalled xcode

**Comment by mfurtak** [comment] 2016-05-04 13:46
Great! Glad you're back in business 💪

**Closed by mfurtak** 2016-05-04 13:46 UTC
Labels: gym

**Comment by tsheaff** [comment] 2016-07-07 00:02
@mfurtak I've tried reinstalling Xcode but I'm getting this same error.  I'm on

```
Version 8.0 beta (8S128d)
```

Here is error log

```
[17:00:58]: ▸ Archive Succeeded
[17:00:58]: Variable Dump:
[17:00:58]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>nil, :LANE_NAME=>"dev", :BUILD_NUMBER=>"368"}
[17:00:58]: Unable to patch the `PackageApplication` script bundled in Xcode. This is not supported.

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | increment_build_number              | 0           |
| 4    | gym                                 | 124         |
+------+-------------------------------------+-------------+

[17:00:58]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Package Application crashes
   https://github.com/fastlane/fastlane/issues/4128 [closed] 16 💬
   04 May 2016


#######################################################################
# fastlane 1.97.2 is available. You are on 1.97.1.
# It is recommended to use the latest version.
# Update using 'sudo gem update fastlane'.
#######################################################################

1.97.2 Support for new 2-factor
- Updated spaceship to support the new 2-factor auth flow
- Updated `activesupport` dependency, so you can install `fastlane` out of the box on system Ruby

Update using 'sudo gem update fastlane'
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.48.1/lib/fastlane_core/ui/interface.rb:127:in `crash!': [!] Unable to patch the `PackageApplication` script bundled in Xcode. This is not supported. (FastlaneCore::Interface::FastlaneCrash)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.48.1/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.3/lib/gym/xcodebuild_fixes/package_application_fix.rb:23:in `block in patch_package_application'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:88:in `mktmpdir'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.3/lib/gym/xcodebuild_fixes/package_application_fix.rb:13:in `patch_package_application'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.3/lib/gym/generators/package_command_generator_legacy.rb:14:in `generate'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.3/lib/gym/generators/package_command_generator.rb:16:in `generate'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.3/lib/gym/runner.rb:118:in `package_app'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.3/lib/gym/runner.rb:20:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.3/lib/gym/manager.rb:10:in `work'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.1/lib/fastlane/actions/gym.rb:22:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.1/lib/fastlane/runner.rb:197:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.1/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.1/lib/fastlane/runner.rb:182:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.1/lib/fastlane/runner.rb:181:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.1/lib/fastlane/runner.rb:181:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.1/lib/fastlane/runner.rb:107:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.1/lib/fastlane/fast_file.rb:140:in `method_missing'
	from Fastfile:19:in `block in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.1/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.1/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.1/lib/fastlane/runner.rb:50:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.1/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.1/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.1/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.1/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.1/lib/fastlane/commands_generator.rb:51:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.48.1/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.1/lib/fastlane/commands_generator.rb:244:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.1/lib/fastlane/commands_generator.rb:20:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.1/lib/fastlane/cli_tools_distributor.rb:47:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.1/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

**Comment by tsheaff** [comment] 2016-07-07 00:21
Here's my lane details:

```
desc "Submit a new Dev Build to Crashlytics"
lane :dev do |options|
  increment_build_number
  gym(
    scheme: "Calm-Dev",
    xcargs: "ARCHIVE=YES", # Used to tell the Fabric run script to upload dSYM file
    use_legacy_build_api: true,
  )

  crashlytics(
    api_token: "**REDACTED**",
    build_secret: "**REDACTED**",
    notes: options[:notes] || "new dev build #{full_version}",
    groups: "Everyone",
  )
end
```

**Comment by tsheaff** [comment] 2016-07-07 00:47
Archiving manually from Xcode and uploading to Crashlytics via the Fabric desktop app works without any issues.

**Comment by apouche** [comment] 2016-07-09 19:40
Same issue for me as well, @tsheaff I wanted to upload to Fabric as well but I can't seem to find the upload option on the Fabric Destkop app how do you upload an xcarchive using it ?

**Comment by apouche** [comment] 2016-07-09 19:43
Disregard my last comment, I found the little "Archives" section the Fabric app.

**Comment by tsheaff** [comment] 2016-07-09 19:46
Yes thiss issue is mysterious and seems relatively rare. Glad im not alone tho. I couldnt find good docs on the PackageApplication script, but then again I dont know much about the inner qorkings of the xcode build process.  Any ideas @mfurtak @KrauseFx ?

**Comment by tsheaff** [comment] 2016-07-14 16:39
This is a much better description of the issue: https://github.com/fastlane/fastlane/issues/5389
