### ISSUE TITLE
frameit not shrinking text for multiline titles

### ISSUE THREAD

**Issue by JosephDuffy** [fastlane/fastlane#11585] opened 2018-01-16 18:28 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

After an update to my app is re-ran my `create_screenshots` lane, which generated my screenshots and then ran `frameit`. However, the newly generated image do not seem to be reducing the size of the text of the title, causing the text to be clipped. I see this across multiple iOS devices and computers performing `frameit`. Below is an example from a 9.7" iPad, followed by the original screenshot.

![ipad pro 9 7-inch -3actionextension_framed](https://user-images.githubusercontent.com/1325813/35013018-c5e87aa8-fb03-11e7-89d4-279663caf50e.png)

![ipad pro 9 7-inch -3actionextension](https://user-images.githubusercontent.com/1325813/35013000-b7fb9e5c-fb03-11e7-9565-8b1b3fb81cc6.png)

##### Complete output when running fastlane, including the stack trace and command used

```
$ fastlane add_device_frames
[18:23:56]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[18:23:56]: ----------------------------------------
[18:23:56]: --- Step: Verifying fastlane version ---
[18:23:56]: ----------------------------------------
[18:23:56]: Your fastlane version 2.76.0 matches the minimum requirement of 1.48.0  ✅
[18:23:56]: ------------------------------
[18:23:56]: --- Step: default_platform ---
[18:23:56]: ------------------------------
[18:23:56]: Driving the lane 'ios add_device_frames' 🚀
[18:23:56]: ---------------------
[18:23:56]: --- Step: frameit ---
[18:23:56]: ---------------------
[18:23:56]: Framing screenshots at path fastlane/screenshots/ (via frameit)
[18:23:56]: Using device frames version 'latest'
[18:23:56]: Framing screenshot './default/iPad Pro (10.5-inch)-3ActionExtension.png'
[18:23:56]: Unknown device type for size iOS-iPad-10.5 for path './default/iPad Pro (10.5-inch)-3ActionExtension.png'
[18:23:56]: Unknown device type for size iOS-iPad-10.5 for path './default/iPad Pro (10.5-inch)-3ActionExtension.png'
[18:23:56]: Unknown device type for size iOS-iPad-10.5 for path './default/iPad Pro (10.5-inch)-3ActionExtension.png'
[18:23:56]: Couldn't find template for screenshot type 'Apple true Space Gray'
[18:23:56]: Please run `fastlane frameit download_frames` to download the latest frames
[18:23:56]: Framing screenshot './default/iPad Pro (12.9-inch)-3ActionExtension.png'
Forced orientation:
Forced orientation:
Forced orientation:
[18:24:11]: Added frame: '/Users/josephduffy/Library/Mobile Documents/com~apple~CloudDocs/Files/Projects/Yetii/Scanula/fastlane/screenshots/default/iPad Pro (12.9-inch)-3ActionExtension_framed.png'
[18:24:11]: Framing screenshot './default/iPad Pro (9.7-inch)-3ActionExtension.png'
Forced orientation:
Forced orientation:
Forced orientation:
[18:24:19]: Added frame: '/Users/josephduffy/Library/Mobile Documents/com~apple~CloudDocs/Files/Projects/Yetii/Scanula/fastlane/screenshots/default/iPad Pro (9.7-inch)-3ActionExtension_framed.png'
[18:24:19]: Framing screenshot './default/iPhone 4s-3ActionExtension.png'
[18:24:19]: Unfortunately 3.5" device frames were discontinued. Skipping screen './default/iPhone 4s-3ActionExtension.png'
[18:24:19]: Looked for: 'Apple iPhone 4 Space Gray.png'
[18:24:19]: Framing screenshot './default/iPhone 8 Plus-3ActionExtension.png'
Forced orientation:
Forced orientation:
Forced orientation:
Forced orientation:
Forced orientation:
[18:24:27]: Added frame: '/Users/josephduffy/Library/Mobile Documents/com~apple~CloudDocs/Files/Projects/Yetii/Scanula/fastlane/screenshots/default/iPhone 8 Plus-3ActionExtension_framed.png'
[18:24:27]: Framing screenshot './default/iPhone 8-3ActionExtension.png'
Forced orientation:
Forced orientation:
Forced orientation:
Forced orientation:
Forced orientation:
[18:24:30]: Added frame: '/Users/josephduffy/Library/Mobile Documents/com~apple~CloudDocs/Files/Projects/Yetii/Scanula/fastlane/screenshots/default/iPhone 8-3ActionExtension_framed.png'
[18:24:30]: Framing screenshot './default/iPhone SE-3ActionExtension.png'
Forced orientation:
Forced orientation:
Forced orientation:
Forced orientation:
Forced orientation:
[18:24:32]: Added frame: '/Users/josephduffy/Library/Mobile Documents/com~apple~CloudDocs/Files/Projects/Yetii/Scanula/fastlane/screenshots/default/iPhone SE-3ActionExtension_framed.png'
[18:24:32]: Framing screenshot './default/iPhone X-3ActionExtension.png'
Forced orientation:
Forced orientation:
Forced orientation:
Forced orientation:
Forced orientation:
[18:24:39]: Added frame: '/Users/josephduffy/Library/Mobile Documents/com~apple~CloudDocs/Files/Projects/Yetii/Scanula/fastlane/screenshots/default/iPhone X-3ActionExtension_framed.png'

+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | Verifying fastlane  | 0           |
|      | version             |             |
| 2    | default_platform    | 0           |
| 3    | frameit             | 42          |
+------+---------------------+-------------+

[18:24:39]: fastlane.tools finished successfully 🎉
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.2                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.15.1                          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13.2 (17C88)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "1.48.0"

default_platform :ios

platform :ios do

  desc "Generate and frame screenshots for the App Store"
  lane :create_screenshots do
    snapshot(skip_open_summary: true, devices: ["iPhone 4s"])
    snapshot(skip_open_summary: true)
    add_device_frames
  end

  lane :add_device_frames do
    frameit(path: "fastlane/screenshots/")
  end

  desc "Submit a new build to TestFlight"
  lane :beta do
    match(type: "appstore")
    gym
    pilot
  end

  desc "Deploy a new version to the App Store"
  lane :submit do
    match(type: "appstore")
    gym
    deliver
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "redacted"
apple_id "redacted@redacted.com"
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.76.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.3        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.5       |
| libxml-ruby               | 3.0.0        |
</details>

*generated on:* **2018-01-16**

In case it's also relevant, here's the output of `magick --version` (it is my understanding that `frameit` utilises imagemagick):

```
Version: ImageMagick 7.0.7-21 Q16 x86_64 2018-01-08 http://www.imagemagick.org
Copyright: © 1999-2018 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules
Delegates (built-in): bzlib freetype jng jpeg ltdl lzma png tiff xml zlib
```

</details>

**Comment by janpio** [comment] 2018-01-16 18:40
Did this work before?
Which version were you using then?

**Comment by JosephDuffy** [comment] 2018-01-16 18:48
I haven't touched this project since around March 2016 (almost 2 years ago), so somewhere around 1.67 (https://github.com/fastlane/fastlane/tags?after=fastlane_core%2F0.40.0). Admittedly I have made a couple of changes to the Fastfile but the .strings file has not changed (and it is respecting the line break, just not resizing the text)

The current version on the app store uses [the previously generated screenshot](http://is2.mzstatic.com/image/thumb/Purple49/v4/7b/62/ae/7b62ae78-e5a1-70be-5bea-580c93e3533a/source/392x696bb.jpg), which might be ok for that screenshot, but I have others that require multiline titles.

**Comment by janpio** [comment] 2018-01-16 19:41
Thanks for the information.

We had some changes there in the last few releases. Could you follow the instructions here to pinpoint it to a version please? https://github.com/fastlane/fastlane/issues/11464#issuecomment-355988006 If it is still ok in `2.68.0` it is probably one of these changes.

**Comment by JosephDuffy** [comment] 2018-01-16 20:28
The problem is still present in `2.68.0`: https://imgur.com/a/6sbjY.

I am now able to easily go back to older versions (via `gem install fastlane -v 2.68.0`) so I am happy to continue testing older version. I will do a bit of testing myself but if there's a specific version or anything you want me to try I will.

**Comment by janpio** [comment] 2018-01-16 20:48
Perfect, lets hope we can pin it down to a specific change or PR - then we can ask its author to maybe take a look ;)

**Comment by JosephDuffy** [comment] 2018-01-16 21:04
`2.14.0` works, [`2.15.0`](https://github.com/fastlane/fastlane/releases/tag/2.15.0) breaks it, and appears to contain `frameit` changes. Since one of the changes is around the title I will experiment a little with different titles, although I do not want to have title in the final screenshots.

**Comment by janpio** [comment] 2018-01-16 21:17
Nice. So https://github.com/fastlane/fastlane/pull/8031 or https://github.com/fastlane/fastlane/pull/8098, right?

Could you please add your screenshots you are right now hosting on Imgur on a comment to this issue? Just drag/drop them into the text box should be enough - I am having problems o view them on Imgur.

**Comment by JosephDuffy** [comment] 2018-01-16 21:23
Yep, #8031 or #8098 appear to have introduce the problem.

I thought it was odd I couldn't find a way to add an image -- just drag it!!! 🤦‍♂️

## fastlane `2.76.1`, no keyword

![ipad pro 9 7-inch -3actionextension_framed](https://user-images.githubusercontent.com/1325813/35012836-1939285c-fb03-11e7-9f14-724741f791f8.png)

## fastlane `2.76.1`, with keyword

![ipad pro 9 7-inch -3actionextension_framed](https://user-images.githubusercontent.com/1325813/35012921-6ce8a644-fb03-11e7-9ab4-d50a8cd27f59.png)

## raw screenshot

![ipad pro 9 7-inch -3actionextension](https://user-images.githubusercontent.com/1325813/35012897-5d2954ce-fb03-11e7-9ae6-cedd9304d821.png)

**Comment by janpio** [comment] 2018-01-16 21:39
Thanks, now I see.

Can you share your configuration files with the text strings? Anything that enables a developer to fully recreate the situation would help.

@funnel20 - this was broken long before you started working on `frameit`, but do you maybe want to take a shot at this anyway? You probably know the code best right now and this again looks like an interesting problem to tackle.

**Comment by JosephDuffy** [comment] 2018-01-16 21:50
Sure!

Here's a stripped down version of my project that will show the behaviour.

[frameit-example.zip](https://github.com/fastlane/fastlane/files/1636947/frameit-example.zip)

Thank you for helping me debug this! Hopefully there's enough information to solve the issue :)

**Comment by funnel20** [comment] 2018-01-16 23:42
@JosephDuffy In https://github.com/fastlane/fastlane/issues/11585#issuecomment-358105091 you mention:

> I can confirm that with the latest version (2.76.1) and a title the text is rendered correctly (all within the image), so the issue is only when a title isn't used.

I expect this should refer to no **keyword** since the title is mandatory:

> I can confirm that with the latest version (2.76.1) and a title the text is rendered correctly (all within the image), so the issue is only when a ~~title~~ keyword isn't used.

Can you please try with the latest master, that contains a fix for issue #11464? That will solve an issue with an empty keyword, although I cannot guarantee that this applies to your multi-line title, as that was not in my test cases.
This fix is scheduled to be released in version 2.77.0.

**Comment by funnel20** [comment] 2018-01-16 23:46
@janpio Is Google still hiring? 🤑

**Comment by janpio** [comment] 2018-01-17 00:06
No idea, I don't work there - I'm also just a random fastlane user that started contributing a bit ;)

**Comment by JosephDuffy** [comment] 2018-01-17 09:27
@funnel20 Yes, I meant no keyword, sorry for the confusion!

I should be able to check if the latest changes on master have fixed the issue this evening (in ~9 hours) and I will post the results here.

**Comment by funnel20** [comment] 2018-01-17 11:50
@JosephDuffy No problem

**Analysis**
I just tested it with the fix for #11464 and it doesn't solve the issue.
Here are 4 examples on iPhone SE:

1. Your original title. It just fits vertically:
![iphone se-01_remotetab_framed 2 lines title only fit](https://user-images.githubusercontent.com/2139844/35040395-347041cc-fb81-11e7-822e-a32956eb27d6.png)

2. A shorter version of your title. It doesn't fit vertically:
![iphone se-01_remotetab_framed 2 lines title only](https://user-images.githubusercontent.com/2139844/35040421-46e573cc-fb81-11e7-956c-6aeae9f86ba3.png)

3. A shorter version of your title with a keyword. The title fits nicely:
![iphone se-01_remotetab_framed 2 lines](https://user-images.githubusercontent.com/2139844/35040463-6e8bcee4-fb81-11e7-8904-d3c1f0338d5a.png)

4. The same as 3 but with a 3rd line in the title. The title doesn't fit vertically:
![iphone se-01_remotetab_framed 3 lines](https://user-images.githubusercontent.com/2139844/35040483-7e154278-fb81-11e7-8693-a4f515247efe.png)

Based on these samples I conclude that the current code does the following:
- It uses an empty area above the device frame to position the title and optional keyword images.
- It only respects the horizontal distance of the area. So it scales the image to a size that fits the horizontal distance while respecting some left and right padding.
- The horizontal padding seems arbitrary when comparing examples 1 and 2.

When adding a keyword, there is less horizontal space for the title, hence the title image is scaled down, so it fits vertically, see example 3.
However, when the title is expanded vertically by adding a 3rd row, the title won't fit anymore as indicated in example 4.

Luckily I made my fix for the vertical text alignment (see #10440) robust, so it also works for multi-line, as indicated by the red lines:
![iphone se-01_remotetab_framed](https://user-images.githubusercontent.com/2139844/35041222-44bfcee6-fb84-11e7-93be-64a0b6b848f8.png)

**Solution**
To solve this issue, the code should be enhanced by also respecting the vertical space of the text area.
In case the text images is taller then the vertical distance, it should shrink both images while maintaining the horizontal alignment.

@janpio Do you agree?

**Comment by janpio** [comment] 2018-01-17 12:03
Totally makes sense what you wrote.

I don't really understand why 1) works but 2) fails - but I guess that is in the code somewhere somehow. First step will probably be to understand and document it better what _exactly_ is happening and maybe add a "summary" above the method or in the docs that explain what steps go on with the text stuff.

These tests were all with padding=0, right? 
Does adding a padding help solve the problem?

**Comment by funnel20** [comment] 2018-01-17 12:08
Example 2 has less words to cover the full width of the image. Hence the image is scaled to a larger font size, so it becomes taller. I.e. there is a difference in the height/width ratio between examples 1 and 2.

I used `"padding": 25` in my Framefile to create the examples.

**Comment by janpio** [comment] 2018-01-17 12:24
TIL that I don't actually know where exactly this `padding` is applied and why. One more thing to document ;)

**Comment by funnel20** [comment] 2018-01-17 12:51
I found a really interesting (and undocumented) part in the code.
It supports 2 formats for `padding`:

1. an integer. This will be used for both horizontal and vertical padding
2. a string in format "`horizontal`x`vertical`", e.g. "100x0"

The second option shows worrying results, as vertical padding 0 implies that the device frame is attached to the bottom of the image. However, it does:
![iphone se-01_remotetab_framed](https://user-images.githubusercontent.com/2139844/35043419-e1113bb0-fb8c-11e7-872b-37d8607b317e.png)

My tentative conclusion: 
Padding seems to be an issue. Both in documentation as in implementation.

The first step towards a solution is to properly define the requirements. Is this something that @KrauseFx should be part of?

**Comment by janpio** [comment] 2018-01-17 13:19
If he wrote the initial implementation, maybe. 

Use the "blame" functionality in Github to find out who wrote that code any maybe read the commit messages and PRs that were written when this was added - maybe this already tells you how it was supposed to work.

Also don't forget that @JosephDuffy reported it to work in an old fastlane version some time ago - so the current behaviour was probably introduced as a bug - maybe the same is true for your last finding.

**Comment by funnel20** [comment] 2018-01-17 14:34
That is one approach. But reverse engineering the code and finding out who did what when is utterly time-consuming.
I always learned to create unambiguous requirements first, and then write the code accordingly.
The code can be (manually) tested against the spec. It also acts as a guide for the reviewer.

What I miss is a requirement for the `padding` parameter, which lacks in the [docu](https://docs.fastlane.tools/actions/frameit/) and the code (as comment).

**Comment by janpio** [comment] 2018-01-17 15:28
You are part of that team ;) But yeah, I will try to get some eyes on this here (and maybe bury my head in the code history a bit as well - with the Github UI it is surprisingly effective and quick).

**Comment by funnel20** [comment] 2018-01-17 15:32
Well, I'm in the code now. It's kinda horrible. Already found the cause of the arbitrary left text padding between my examples 1 and 2 in https://github.com/fastlane/fastlane/issues/11585#issuecomment-358285454.

I'm just rewriting a bunch of stuff while using the following requirements:

1.

**Comment by funnel20** [comment] 2018-01-17 16:33
Here is a fix by respecting the vertical space above the framed device. It shrinks the text image until the height fits within the `padding`. This means I applied the `padding` above AND below the text (and below the framed device).
Here is an example with padding = 25:
![iphone se-01_remotetab_framed](https://user-images.githubusercontent.com/2139844/35053532-9d293da8-fbaa-11e7-8bf8-88b2540ba303.png)

My instant reaction: 

> Hmm, that's a small font size.

So here is an example of applying 0.5*`padding` above and below the text, so the text size is larger:
![iphone se-01_remotetab_framed 0 5 padding](https://user-images.githubusercontent.com/2139844/35053439-62c395c8-fbaa-11e7-8dcb-a3eee00371bc.png)

Another option: apply `padding` above the text and 0.5*`padding` below the text, sot the font size increase and the _outer_ padding is respected:
![iphone se-01_remotetab_framed](https://user-images.githubusercontent.com/2139844/35054251-631a957e-fbac-11e7-908e-e8ae8a7a39ae.png)

So it's all a matter of the definition for `padding`.

**Comment by janpio** [comment] 2018-01-17 17:00
Ok, that looks great already. So you have the code under control, now it's just on use to define something.

@JosephDuffy can you maybe give some insight on how it worked in your [before screenshot your posted](http://is2.mzstatic.com/image/thumb/Purple49/v4/7b/62/ae/7b62ae78-e5a1-70be-5bea-580c93e3533a/source/392x696bb.jpg)? Can you maybe reply to this with a comment that includes both the before screenshot and the variant the current code generates now (and include the `padding` value used for that)?

@funnel20 What exactly _is_ padding? I am not sure at the moment how this applies to _both_ the text(s) and the device frame with the inset screenshot. Did you get how it was meant to work? Can you maybe make the padding `red` or something so it is super simple to grasp?

**Comment by JosephDuffy** [comment] 2018-01-17 19:15
@janpio The original working image that you linked was using a padding of `50`, and `show_complete_frame` was `false`. I have now reduced this to `40`, which is the value in the [previously linked example .zip](https://github.com/fastlane/fastlane/files/1636947/frameit-example.zip).

I don't have the original PNG anymore, but I have downloaded the best image I could find on iTunes Connect:

![ipad 9 7](https://user-images.githubusercontent.com/1325813/35061161-47bd8500-fbb8-11e7-8b6d-6f42fa703d7f.jpg)

If I set the padding back to `50` the current latest version (downloading `master` and using `bundler`) produces the following:

![ipad pro 9 7-inch -3actionextension_framed](https://user-images.githubusercontent.com/1325813/35061732-040f68c6-fbba-11e7-9bf2-b7329388380f.png)

I'm not 100% sure that's what you're asking for so I apologise if I've misinterpreted what you've asked me to do!

@funnel20: Thank you for looking at this it's very much appreciated! :) The images you've posted are looking spot on. I don't think it's really my place to comment on the use of "padding", although I will say that personally I like the last example (0.5 * padding below the text) the most.

**Comment by funnel20** [comment] 2018-01-17 21:12
Off-topic: Is there an issue with the images on GitHub? I don't see any, only hyperlinks.

@janpio Here are a few definitions of padding that basically say the same:
- [Apple](https://developer.apple.com/documentation/appkit/nstextblock.layer/1535819-padding): space surrounding the content area extending to the border. 
- [w3schools](https://www.w3schools.com/css/css_padding.asp): space around an element's content, inside of any defined borders.

**Comment by janpio** [comment] 2018-01-17 21:13
@JosephDuffy Something went wrong with the image uploads in your last comment - nothing is showing for me.

**Comment by funnel20** [comment] 2018-01-17 21:18
It mus be temporary, I can still click on the image names, they are in fact hyperlinks.

**Comment by janpio** [comment] 2018-01-17 21:19
@funnel20 Yes, in the usual sense it is the inner spacing of a container - that much is clear ;)

The question is what the meaning is in our case. Does it apply to the outer borders of the complete image? Or also around the device frame? What about the text?

In your example you applied it 1x to the outer border and 1,1,0.5,1 (top, right, bottom, left) to the text, correct?

Another thing I don't understand right now:
How is decided how "low" the device frame is moved to make space for the text above?

**Comment by janpio** [comment] 2018-01-17 21:21
(Ahh, in Firefox the images are just invisible - in Chrome it displays a broken image with the link)

**Comment by funnel20** [comment] 2018-01-17 21:23
Yep, Safari behaves similar to Chrome. So there is no need to re-add the URLs

**Comment by JosephDuffy** [comment] 2018-01-17 21:30
The images aren't showing inline on mobile safari either, but the links do work :)

Having thought about the padding some more I will provide my 2 cents:

If the padding options were to be updated, perhaps 2 new options could be added: `devicePadding` and `textPadding`. When calculating the spacing between the device and text use the highest value? If only `padding` is provided that value could be used for both.

**Comment by funnel20** [comment] 2018-01-17 21:31
This is the image with padding = 0. It positions the framed device at the bottom at a certain size of the total image (say 90%, must be in the code).
![iphone se-01_remotetab_framed](https://user-images.githubusercontent.com/2139844/35068028-1e4aa504-fbd6-11e7-8c24-7261a17f7e13.png)


When padding >0, the framed device is cropped around it's center (the big red dot), until the defined padding space is below it. This opens more space for the text above the framed device, however, padding should be applied there too.

**Comment by funnel20** [comment] 2018-01-17 21:45
To keep it simple, I would propose to fix the existing code by scaling the font size down for multi-line. 
In such a way that the default existing `padding` should apply the padding around the device and around the text. This creates a vertically aligned text above the device.

That means this:
![iphone se-01_remotetab_framed](https://user-images.githubusercontent.com/2139844/35053532-9d293da8-fbaa-11e7-8bf8-88b2540ba303.png)

On top of that I like the idea from @JosephDuffy  of a second parameter `padding_title` (that fits better related to the other parameters as `stack_title` and `title_below_image`) so users can enlarge the text, while it vertically aligns between the image top and device top. This parameter overrides the global `padding` around the text.

**Comment by janpio** [comment] 2018-01-17 21:58
Simple sounds awesome and good to document ;) Go for it!

**Comment by funnel20** [comment] 2018-01-17 21:59
@JosephDuffy I've run my fix on your screenshot with `padding` = 50, it will look like this:
![ipad pro 9 7-inch - 01 -actionextension_framed](https://user-images.githubusercontent.com/2139844/35069145-9bc09f4a-fbd9-11e7-80fd-5b07d165462b.png)

You'll notice that the font size is significantly smaller than with your existing iTC screenshot. 1 reason is my fix, which respects the vertical padding.
Another reason is that the empty area above the iPad is smaller than in version 2.14.0. This is the result of many Frameit updates.

**Comment by funnel20** [comment] 2018-01-18 15:39
It's already possible to adjust the font size via another undocumented parameter: `font_scale_factor`
This is set by default to 0.1, so the above screenshots are created with this value.
When I add it to my Framefile and set `font_scale_factor` to 0.2, it lowers the device frame so there is more room for larger font size:

![ipad pro 9 7-inch - 01 -actionextension_framed](https://user-images.githubusercontent.com/2139844/35106095-a60883f2-fc6d-11e7-8822-603fbb8dd503.png)

**Conclusions**

- there is no need for an additional `padding_title` as discussed earlier.
- the [documentation](https://docs.fastlane.tools/actions/frameit/) should be updated to reflect all parameters, such as `padding` and `font_scale_factor`

Questions
- What is the range of `font_scale_factor`?
- Why is `font_scale_factor` default at 0.1, and not 1.0?

**Comment by funnel20** [comment] 2018-01-18 15:56
@JosephDuffy You can probably solve this issue by adding `font_scale_factor` to your _Framefile.json_ and set it at a value larger than 0.1. For example 0.2.
Does this work?

**Comment by janpio** [comment] 2018-01-18 16:04
Docs for `frameit` (which is only an alias for `frame_screenshots`) lives here: https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/docs/frame_screenshots.md

`font_scale_factor` is a very strange thing. I guess this is more an internal variable that can also be set via config. That's why its name doesn't make much sense (to users) and its default value doesn't as well. Looking at the code this was just a value for calculation that then was exposed as well. Should just be documented with how it is: 
> `0.1` is default, bigger values make ... and smaller values achieve ...

**Comment by janpio** [comment] 2018-01-18 16:08
I jokingly ask, but there indeed are:
https://github.com/fastlane/fastlane/blob/988f5cf941f2f30804a2d44e606358605382929e/frameit/lib/frameit/editor.rb#L87
https://github.com/fastlane/fastlane/blob/988f5cf941f2f30804a2d44e606358605382929e/frameit/lib/frameit/editor.rb#L356

**Comment by funnel20** [comment] 2018-01-18 16:09
I agree to just document it, because it's very convenient to create more vertical space for multi-line texts.
I've tested with a value of 0.0, which results in unreadable small text and a divide-by-zero in my solution.
Hence I will add the following error in  `actual_font_size`:
```Ruby
def actual_font_size
      font_scale_factor = fetch_config['font_scale_factor'] || 0.1
      UI.user_error!("Parameter 'font_scale_factor' can not be 0. Please provide a value larger than 0.0 in your Framefile.json. The default value is 0.1.") if font_scale_factor == 0.0
      [@image.width * font_scale_factor].max.round
end
```
Do you agree?

**Comment by janpio** [comment] 2018-01-18 16:23
Yep, but get rid of " in your Framefile.json. The default value is 0.1.". Unnecessary and duplicate information in this case I would say.

**Comment by funnel20** [comment] 2018-01-18 16:41
Well, I added the default value as an indication for the magnitude of the value.

**Comment by janpio** [comment] 2018-01-18 16:56
Imho this should be in the docs - but either way is ok I guess. Everything is better than current state.

**Comment by funnel20** [comment] 2018-01-18 17:21
While testing with `stack_title` enabled, different behaviour is shown than with it disabled (i.e. keyword and title side by side):

**Stacked**
The text defines the vertical position of the framed device. So if multi-line text is used, the device is lowered to provide enough space for the text.
This results in ridiculous images like:
![ipad pro 9 7-inch - 01 -actionextension_framed](https://user-images.githubusercontent.com/2139844/35111597-e893c836-fc7b-11e7-88dc-c2f6962a2732.png)
Con: When different text is used for multiple screenshots for the same device, the device size between these screenshots will differ. This is ugly in the App Store.

**Side by side**
The device frame always has the same position. Hence the vertical space for the text is fixed and multi-line text will exceed this space. My current solution is to scale the text down when it exceeds the available vertical space.
Pro: Multiple screenshots for the same device have the same size, which is nice for the App Store.

So again we're back at definitions/requirements. What is the desired behaviour?

**Comment by funnel20** [comment] 2018-01-18 17:24
**Conclusion 546**
Frameit is a mess. I won't make any changes to it until someone writes all unambiguous requirements for all situations and parameters. Because without it, it will be patch on patch by different authors because everyone interprets the logic differently.

**Comment by janpio** [comment] 2018-01-18 17:26
Looking at [the examples in the docs](https://docs.fastlane.tools/actions/frameit/#results) I think multi line wasn't really a big though during implementation. 

I guess 1 line should work perfectly, 2 lines should work okay-ish and everything more can be pretty broken. (Docs would say "works best with 1 line of text, 2 lines is still supported and everything else might look a bit ugly")

Do you understand why there is an empty "line" between keyword and title in the last screen you posted?

**Comment by janpio** [comment] 2018-01-18 17:27
Just start a PR with the changes you have until now, then I can jump in and start messing with the documentation together with you until we have these "requirements". People using `frameit` will have to weigh in during the PR - or after we released the changes. There is no other way to develop stuff like this in the open.

**Comment by funnel20** [comment] 2018-01-18 17:38
> Do you understand why there is an empty "line" between keyword and title in the last screen you posted?

Yes, that's due to my fix for #10440 that makes both text images of the same height. Because then I didn't use multi-line as requirement.

> There is no other way to develop stuff like this in the open.

I strongly disagree. Creating and patching code until everyone is satisfied is a waste of time and energy.
Why can't we first write reqs and than write first-time-right code?

**Comment by funnel20** [comment] 2018-01-18 17:44
As you state the docu doesn't guarantee any succes for multi-line.

There are work-arounds for @JosephDuffy with the current version: by using `font_scale_factor`.
I also guess that setting `stack_title` to true will help, as it pushes the device down.

So if @JosephDuffy can confirm this, that will be the answer to this issue.
The next steps will be to create issues to improve frameit based on proper reqs.

**Comment by janpio** [comment] 2018-01-18 17:58
I am not sure multiline was ever considered as a real requirement - the available example indicate that it probably wasn't.

Of course we can now create a new issue and see that we come to an agreement how all these parameters should work. Just mention me when creating it so I am aware, please.

**Comment by JosephDuffy** [comment] 2018-01-18 20:17
I'm not at home this evening so cannot check until tomorrow, but the screenshots do look very good. `font_scale_factor` sounds a little confusing but I'll tinker with it and I'm sure I'll figure it out.

It's very old now (originally [#25 on the old fastlane repo](https://github.com/fastlane-old/frameit/issues/25)), but #2774 added support for multiline strings.

**Comment by JosephDuffy** [comment] 2018-01-20 15:35
I've just got round to trying with `font_scale_factor`, but it causes single-line titles to have large padding. The changes in #11624 should fix the root of the problem though :) In the meantime, I will probably download and use that fork of fastlane to generate the screenshots.

Thanks for the help @funnel20!

**Comment by janpio** [comment] 2018-01-20 16:56
If you could test that fork and report back this would be really neat :)

**Comment by JosephDuffy** [comment] 2018-01-21 01:26
I've run `frameit` with your branch and it's working like a charm! Thank again 😄

**Comment by funnel20** [comment] 2018-01-21 10:01
@JosephDuffy Thanks for confirming this change.

**Closed** 2018-01-23 10:52 UTC
Labels: tool: frameit, type: bug
