### ISSUE TITLE
[spaceship] NOT WORK SPACESHIP 0.38.1

### ISSUE THREAD

**Issue by GandjaFuzz** [fastlane/fastlane#7198] opened 2016-11-28 07:35 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

```
/usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.38.1/lib/spaceship/tunes/app_version.rb:383:in `upload_screenshot!': [!] wrong number of arguments (given 4, expected 5) (ArgumentError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/deliver-1.15.1/lib/deliver/upload_screenshots.rb:54:in `block (2 levels) in upload'
	from /usr/local/lib/ruby/gems/2.3.0/gems/deliver-1.15.1/lib/deliver/upload_screenshots.rb:41:in `each'
```

**Comment by akkhilns** [comment] 2016-11-28 07:40
i got the same error. I can't upload screenshorts

**Comment by hjanuschka** [comment] 2016-11-28 07:43
@GandjaFuzz @akkhilns  we are aware of this its a duplicate of: https://github.com/fastlane/fastlane/issues/7165

as a workaround you can look at this comment: https://github.com/fastlane/fastlane/issues/7165#issuecomment-263018284


the PR to finaly fix this is here: https://github.com/fastlane/fastlane/pull/7162 this will hopefully merged after the weekend and released!

**Comment by milch** [comment] 2016-11-28 19:15
I'm closing this as a duplicate, please refer to #7165 as mentioned by @hjanuschka

**Closed by milch** 2016-11-28 19:15 UTC
Labels: duplicate
