### ISSUE TITLE
deliver how to update an app ( lack what news info )

### ISSUE THREAD

**Issue by TechGuyVN** [fastlane/fastlane#4549] opened 2016-05-06 23:54 UTC
Hi

I want to update exist app, and the error say :

> [!] The request could not be completed because:
> 	You must detail what's new in this version in English.
> 

Can you  add "what's new" in metadata so we can add info each update on it.

**Comment by TKBurner** [comment] 2016-05-09 19:34
Hi @TechGuyVN Thanks for reaching out. This is a duplicate of #4444 and we will continue to work there. Thanks!

**Closed by TKBurner** 2016-05-09 19:34 UTC
Labels: deliver, feature
