### ISSUE TITLE
Incorrect Verfication Code

### ISSUE THREAD

**Issue by deployagent** [fastlane/fastlane#16126] opened 2020-03-05 21:27 UTC
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
We are using Fastlane to generate a session token by typing

Fastlane spaceauth -u username

eventually we are asked for the 6 digit verification id that comes to my phone.

I enter the ID and it fails to connect and gives unauthorized.

I am able to login to itunesconnect.apple.com with the same credentials.  its not asking for my password.

##### Command executed

fastlane spaceauth -u lance_lyons@uuuuu.com

##### Complete output when running fastlane, including the stack trace and command used

INFO  [15:12:32]: >> GET https://appstoreconnect.apple.com/olympus/v1/session: [undefined body]
DEBUG [15:12:32]: << GET https://appstoreconnect.apple.com/olympus/v1/session: 401 Unauthenticated

Request ID: MPPSPVQESGMXFUEGWFNWTRL3IA.0.0

WARN  [15:12:32]: Auth lost
INFO  [15:12:32]: >> GET https://appstoreconnect.apple.com/olympus/v1/app/config?hostname=itunesconnect.apple.com: [undefined body]
DEBUG [15:12:32]: << GET https://appstoreconnect.apple.com/olympus/v1/app/config?hostname=itunesconnect.apple.com: 200 {"authServiceUrl"=>"https://idmsa.apple.com/appleauth", "authServiceKey"=>"e0b80c3bf78523bfe80974d320935bfa30add02e1bff88ec2166c6bd5a706c42"}
INFO  [15:12:32]: >> POST https://idmsa.apple.com/appleauth/auth/signin: {"accountName":"lance_lyons@uuuuuu.com","password":"***","rememberMe":true}
DEBUG [15:12:32]: << POST https://idmsa.apple.com/appleauth/auth/signin: 409 {"authType"=>"hsa2"}
INFO  [15:12:32]: >> GET https://idmsa.apple.com/appleauth/auth: [undefined body]
DEBUG [15:12:33]: << GET https://idmsa.apple.com/appleauth/auth: 201 {"trustedPhoneNumbers"=>[{"numberWithDialCode"=>"+1 (•••) •••-••15", "obfuscatedNumber"=>"(•••) •••-••15", "pushMode"=>"sms", "id"=>1}], "phoneNumber"=>{"numberWithDialCode"=>"•• (•••) •••-••15", "obfuscatedNumber"=>"(•••) •••-••15", "pushMode"=>"sms", "id"=>1}, "securityCode"=>{"length"=>6, "tooManyCodesSent"=>false, "tooManyCodesValidated"=>false, "securityCodeLocked"=>false, "securityCodeCooldown"=>false}, "mode"=>"sms", "type"=>"verification", "authenticationType"=>"hsa2", "recoveryUrl"=>"https://iforgot.apple.com/phone/add?prs_account_nm=lance_lyons%40onlifehealth.com&autoSubmitAccount=true&appId=142", "cantUsePhoneNumberUrl"=>"https://iforgot.apple.com/iforgot/phone/add?context=cantuse&prs_account_nm=lance_lyons%40onlifehealth.com&autoSubmitAccount=true&appId=142", "recoveryWebUrl"=>"https://iforgot.apple.com/password/verify/appleid?prs_account_nm=lance_lyons%40onlifehealth.com&autoSubmitAccount=true&appId=142", "repairPhoneNumberUrl"=>"https://gsa.apple.com/appleid/account/manage/repair/verify/phone", "repairPhoneNumberWebUrl"=>"https://appleid.apple.com/widget/account/repair?#!repair", "noTrustedDevices"=>true, "aboutTwoFactorAuthenticationUrl"=>"https://support.apple.com/kb/HT204921", "autoVerified"=>false, "showAutoVerificationUI"=>false, "trustedPhoneNumber"=>{"numberWithDialCode"=>"+1 (•••) •••-••15", "obfuscatedNumber"=>"(•••) •••-••15", "pushMode"=>"sms", "id"=>1}, "hsa2Account"=>true, "restrictedAccount"=>false, "managedAccount"=>false, "supportsRecovery"=>true}
INFO  [15:12:52]: >> POST **https://idmsa.apple.com/appleauth/auth/verify/trusteddevice/securitycode: {"securityCode":{"code":"026410"}}
DEBUG [15:12:52]: << POST https://idmsa.apple.com/appleauth/auth/verify/trusteddevice/securitycode: 400 {"service_errors"=>[{"code"=>"-21669", "title"=>"Incorrect Verification Code",** "message"=>"Incorrect verification code.", "suppressDismissal"=>false}], "hasError"=>true}
INFO  [15:12:52]: >> GET https://idmsa.apple.com/appleauth/auth/2sv/trust: [undefined body]
DEBUG [15:12:52]: << GET https://idmsa.apple.com/appleauth/auth/2sv/trust: 400 {"service_errors"=>[{"code"=>"-20528", "message"=>"Error Description not available", "suppressDismissal"=>false}], "hasError"=>true}
INFO  [15:12:52]: >> GET https://appstoreconnect.apple.com/olympus/v1/session: [undefined body]
DEBUG [15:12:52]: << GET https://appstoreconnect.apple.com/olympus/v1/session: 401 Unauthenticated

Request ID: UL54Q7HYAKCLI3ZAQIHCBUBXUY.0.0

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

[⠋] 🚀 Ignoring ffi-1.12.2 because its extensions are not built.  Try: gem pristine ffi --version 1.12.2
[✔] 🚀 
[15:17:16]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[15:17:16]: Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.4                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.21.0                          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.14.4 (18E226)                   |
| Ruby Lib Dir                | /usr/local/opt/rbenv/versions/2.4.0/lib     |
| OpenSSL Version             | OpenSSL 1.1.0j  20 Nov 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.143.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.15.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.72.0       |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.0.2        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.13.0       |
| memoist                   | 0.16.2       |
| os                        | 1.0.1        |
| googleauth                | 0.11.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.5.1        |
| google-cloud-storage      | 1.25.1       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-eventstream           | 1.0.3        |
| aws-sigv4                 | 1.1.1        |
| aws-sdk-core              | 2.11.460     |
| aws-sdk-resources         | 2.11.460     |
| aws-sdk                   | 2.11.460     |
| openssl                   | 2.0.2        |
| io-console                | 0.4.6        |
| psych                     | 2.2.2        |
</details>

*generated on:* **2020-03-05**
</details>

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by janpio** [comment] 2020-03-06 22:08
Duplicate of this here: https://github.com/fastlane/fastlane/issues/16108

**Closed by janpio** 2020-03-06 22:08 UTC

**Comment by llyons** [comment] 2020-03-06 23:14
Thanks that did work.  To be clear you have to enter the sms in the first verification code and then chose the phone number again and enter the second code.   that did work.

thanks
