### ISSUE TITLE
Add timeout parameter to download_dsyms 

### ISSUE THREAD

**Issue by olsh** [fastlane/fastlane#15371] opened 2019-09-24 21:17 UTC
#### Motivation Behind Feature
At the moment `download_dsyms` wait for 5 minutes (this value is hardcoded) until dSYM files appear on AppStoreConnect. Sometimes generating dSYM files takes more than 5 minutes, so fastlane logs an error and continues without downloading dSYM files

https://github.com/fastlane/fastlane/blob/b0ab18b6b1ba509660fb3d490633ccda160a5b08/fastlane/lib/fastlane/actions/download_dsyms.rb#L103-L112

Here is a typical log:

```
[19:03:14][Step 5/5] [12:03:14]: Looking for dSYM files for 'my.app.com' on platform ios v1.0.7 (304)
[19:03:18][Step 5/5] [12:03:18]: Waiting for dSYM file to appear...
[19:03:49][Step 5/5] [12:03:49]: Waiting for dSYM file to appear...
[19:04:20][Step 5/5] [12:04:20]: Waiting for dSYM file to appear...
[19:04:51][Step 5/5] [12:04:51]: Waiting for dSYM file to appear...
[19:05:21][Step 5/5] [12:05:21]: Waiting for dSYM file to appear...
[19:05:52][Step 5/5] [12:05:52]: Waiting for dSYM file to appear...
[19:06:23][Step 5/5] [12:06:23]: Waiting for dSYM file to appear...
[19:06:54][Step 5/5] [12:06:54]: Waiting for dSYM file to appear...
[19:07:24][Step 5/5] [12:07:24]: Waiting for dSYM file to appear...
[19:07:55][Step 5/5] [12:07:55]: Waiting for dSYM file to appear...
[19:08:26][Step 5/5] [12:08:26]: Could not find any dSYM for 304 (1.0.7)
[19:08:26][Step 5/5] [12:08:26]: No dSYM URL for 304 (1.0.7)
[19:08:26][Step 5/5] [12:08:26]: No dSYM files found on App Store Connect - this usually happens when no recompiling has happened yet
```

#### Feature Description
Add a parameter, let's call it `wait_for_dsym_processing_timeout`. Which will specify how long fastlane will wait until dSYM files appear on AppStoreConnect. By default, it's 5 minutes.

#### Alternatives or Workarounds
Add a sleep before calling `download_dsym`.

**Comment by janpio** [comment] 2019-09-27 19:13
Duplicate of https://github.com/fastlane/fastlane/issues/15385

**Closed by janpio** 2019-09-27 19:13 UTC
