### ISSUE TITLE
fastlane init stuck on Apple ID login

### ISSUE THREAD

**Issue by hartbit** [fastlane/fastlane#1407] opened 2016-02-24 13:37 UTC
I've just started trying out fastlane and `fastlane init` is stuck trying to login with a Apple Developer account which only has a Member access to the company's Developer account (no iTunes Connect access).

I see several problems with this:

1) I don't understand why I get `Unauthorised Access`.
2) It shouldn't be retrying indefinitely. There's a decrement missing somewhere :)

![screenshot 2016-02-24 14 29 35](https://cloud.githubusercontent.com/assets/325519/13286834/206cbdbc-db04-11e5-95d4-f090f57430fc.png)

**Comment by otaran** [comment] 2016-02-24 16:43
:+1: I have the same issue using Fastlane 1.63:

```shell
$ fastlane init --verbose
INFO [2016-02-24 08:37:45.06]: Detected iOS/Mac project in current directory...
INFO [2016-02-24 08:37:45.06]: This setup will help you get up and running in no time.
INFO [2016-02-24 08:37:45.06]: fastlane will check what tools you're already using and set up
INFO [2016-02-24 08:37:45.06]: the tool automatically for you. Have fun! 
INFO [2016-02-24 08:37:45.06]: Created new folder './fastlane'.
INFO [2016-02-24 08:37:45.06]: xcrun xcodebuild -list -workspace './***.xcworkspace'
Your Apple ID (e.g. fastlane@krausefx.com): ***
WARN [2016-02-24 08:38:01.61]: Verifying if app is available on the Apple Developer Portal and iTunes Connect...
INFO [2016-02-24 08:38:01.61]: Starting login with user '***'
Multiple teams found on the Developer Portal, please enter the number of the team you want to use: 
1) *** (In-House)
2) *** (Company/Organization)
3) *** (Individual)
1
Auth error received: 'Unauthorized Access'. Login in again then retrying after 3 seconds (remaining: 5)...
Auth error received: 'Unauthorized Access'. Login in again then retrying after 3 seconds (remaining: 5)...
Auth error received: 'Unauthorized Access'. Login in again then retrying after 3 seconds (remaining: 5)...
Auth error received: 'Unauthorized Access'. Login in again then retrying after 3 seconds (remaining: 5)...
Auth error received: 'Unauthorized Access'. Login in again then retrying after 3 seconds (remaining: 5)...
Auth error received: 'Unauthorized Access'. Login in again then retrying after 3 seconds (remaining: 5)...
Auth error received: 'Unauthorized Access'. Login in again then retrying after 3 seconds (remaining: 5)...
Auth error received: 'Unauthorized Access'. Login in again then retrying after 3 seconds (remaining: 5)...
Auth error received: 'Unauthorized Access'. Login in again then retrying after 3 seconds (remaining: 5)...
Auth error received: 'Unauthorized Access'. Login in again then retrying after 3 seconds (remaining: 5)...
Auth error received: 'Unauthorized Access'. Login in again then retrying after 3 seconds (remaining: 5)...
Auth error received: 'Unauthorized Access'. Login in again then retrying after 3 seconds (remaining: 5)...
Auth error received: 'Unauthorized Access'. Login in again then retrying after 3 seconds (remaining: 5)...
Auth error received: 'Unauthorized Access'. Login in again then retrying after 3 seconds (remaining: 5)...
Auth error received: 'Unauthorized Access'. Login in again then retrying after 3 seconds (remaining: 5)...
^C/usr/local/var/rbenv/versions/2.2.3/lib/ruby/2.2.0/net/protocol.rb:155:in `select': Interrupt
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/2.2.0/net/protocol.rb:155:in `rescue in rbuf_fill'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/2.2.0/net/protocol.rb:152:in `rbuf_fill'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/2.2.0/net/protocol.rb:134:in `readuntil'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/2.2.0/net/protocol.rb:144:in `readline'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/2.2.0/net/http/response.rb:39:in `read_status_line'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/2.2.0/net/http/response.rb:28:in `read_new'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/2.2.0/net/http.rb:1414:in `block in transport_request'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/2.2.0/net/http.rb:1411:in `catch'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/2.2.0/net/http.rb:1411:in `transport_request'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/2.2.0/net/http.rb:1384:in `request'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/2.2.0/net/http.rb:1377:in `block in request'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/2.2.0/net/http.rb:853:in `start'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/2.2.0/net/http.rb:1375:in `request'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/2.2.0/net/http.rb:1133:in `get'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:80:in `perform_request'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-cookie_jar-0.0.6/lib/faraday/cookie_jar.rb:22:in `call'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `get'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spaceship-0.21.0/lib/spaceship/client.rb:277:in `block in send_request'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spaceship-0.21.0/lib/spaceship/client.rb:195:in `with_retry'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spaceship-0.21.0/lib/spaceship/client.rb:276:in `send_request'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spaceship-0.21.0/lib/spaceship/client.rb:252:in `request'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spaceship-0.21.0/lib/spaceship/tunes/tunes_client.rb:149:in `send_login_request'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spaceship-0.21.0/lib/spaceship/client.rb:219:in `do_login'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spaceship-0.21.0/lib/spaceship/client.rb:208:in `rescue in with_retry'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spaceship-0.21.0/lib/spaceship/client.rb:195:in `with_retry'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spaceship-0.21.0/lib/spaceship/client.rb:276:in `send_request'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spaceship-0.21.0/lib/spaceship/client.rb:252:in `request'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spaceship-0.21.0/lib/spaceship/tunes/tunes_client.rb:236:in `applications'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spaceship-0.21.0/lib/spaceship/tunes/application.rb:62:in `all'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spaceship-0.21.0/lib/spaceship/tunes/application.rb:68:in `find'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.63.0/lib/fastlane/setup/setup_ios.rb:193:in `detect_if_app_is_available'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.63.0/lib/fastlane/setup/setup_ios.rb:32:in `run'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.63.0/lib/fastlane/setup/setup.rb:19:in `run'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.63.0/bin/fastlane:51:in `block (2 levels) in run'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane_core-0.36.7/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.63.0/bin/fastlane:150:in `run'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane-1.63.0/bin/fastlane:156:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.2.3/bin/fastlane:23:in `load'
	from /usr/local/var/rbenv/versions/2.2.3/bin/fastlane:23:in `<main>'
```

**Comment by ohwutup** [comment] 2016-02-24 17:33
thanks for raising this issue! it looks like the bug got introduced to spaceship in this PR https://github.com/fastlane/spaceship/pull/235/files#diff-148844c062ae98909c19f6c882daeedbR204

ill make a fix and update this issue, in the meantime, you can definitely setup your Fastfile manually, but knowing that is a hassle, i will try to rush this through :octopus:

**Comment by lacostej** [comment] 2016-02-25 09:37
The logic in retry only call log in again if logging in was successful: https://github.com/fastlane/spaceship/blob/0.21.0/lib/spaceship/client.rb#L203-L221

The retry counter was not added because it shouldn't be needed if the whole logic . I meant the 5 retries to be used for the request, not for the login operation. I wonder if we are not finally hitting #242 here. I.e. that we are throwing a `UnauthorizedAccessError` in the retried request instead of something else.

Could you check the spaceship logs if you are getting a 403 here https://github.com/fastlane/spaceship/pull/235/files#diff-65e8ba971206aef69e69097d7f70f869R152

If is treated as a 401 it would cause the loop you are seeing. I can try looking into this tonight.

2. the fact that the decrement was not added was by design. Although I understand the risk, the idea was that I wanted to do the following

request_something
if logged out
  login
  retry request_something

I didn't want to decrease the counter while retrying because there shouldn't be a need if login is handled properly in itself. As you noted you only enter 
The idea was that logging in shouldn't fail itself with a login failed. 
  

This is because it shouldn't fail with a failed login once again here. If the credentials are invalid, it will bail out anyway

**Comment by lacostej** [comment] 2016-02-25 20:57
I wanted to try to investigate that tonight, but it looks like Apple won't send me email invitations to re-create the setup required to test this... So it will have to wait a bit.

**Comment by lacostej** [comment] 2016-03-01 10:17
@harbit This should have been fixed with spaceship 0.21.1.

**Comment by hartbit** [comment] 2016-03-01 11:40
I confirm it's now fixed. Thanks!

**Comment by lacostej** [comment] 2016-03-01 11:59
@hartbit feel free to close this issue then :)

**Closed** 2016-03-01 12:05 UTC
