### ISSUE TITLE
Broken Pipe error when using fastlane with bitbucket

### ISSUE THREAD

**Issue by santoshshetty2612** [fastlane/fastlane#5919] opened 2016-08-27 18:16 UTC
Hi,

May be this problem has been discussed many times, but I am not able to get through this error. It doesn't happen on all the machine. But on my mac, I get this error 9 out of 10 times.

I tried a lot of other solutions including increasing the git buffer size. But nothing worked for me.
git config http.postBuffer 52428800

[23:41:31]: Cloning remote git repo...
Cloning into '/var/folders/xm/g9tcnvy578j5yhnr7qh0xr0r0000gn/T/d20160827-6147-1mvjutj'...
remote: Counting objects: 1530, done.
remote: Compressing objects: 100% (612/612), done.
Write failed: Broken pipe1439/1530), 3.23 MiB | 124.00 KiB/s    
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
[23:42:02]: Exit status: 128

**Comment by nafu** [comment] 2016-08-28 16:02
@santoshshetty2612 

How about trying this?
http://stackoverflow.com/a/28473869/1884748

**Comment by asfalcone** [comment] 2016-08-29 14:14
@santoshshetty2612 It's hard to tell what the problem is from the snippet you posted. Can you please format your issue per the [issue template](https://github.com/fastlane/fastlane/blob/master/ISSUE_TEMPLATE.md) and include a full output as well as your fastfile? Thanks 👍

**Comment by KrauseFx** [comment] 2016-10-05 21:51
This is probably due to your internet connection. I'll close this issue for now, feel free to re-submit if you still experience this problem

**Closed by KrauseFx** 2016-10-05 21:51 UTC
Labels: awaiting-reply
