### ISSUE TITLE
Scan error "Couldn't find specified scheme"

### ISSUE THREAD

**Issue by yakimant** [fastlane/fastlane#17521] opened 2020-10-29 14:23 UTC
I have a scan issue:
```
Couldn't find specified scheme 'MySheme'. Please make sure that the scheme is shared, see https://developer.apple.com/library/content/documentation/IDEs/Conceptual/xcode_guide-continuous_integration/ConfigureBots.html#//apple_ref/doc/uid/TP40013292-CH9-SW3
```

Both
```
xcodebuild -list -workspace My.xcworkspace
xcodebuild -list -project My.xcodeproj
```
list `MyScheme` and it is marked as "Shared" in "Manage Shemes..."

I created an issue for xcodeproj, it seems related:
https://github.com/CocoaPods/Xcodeproj/issues/797

Is it possible to workaround in scan other than switching to xcodebuild?

**Comment by rogerluan** [comment] 2020-11-05 04:53
Seems like the issue is within Xcodeproj gem itself.
I don't think we can easily replace Xcodeproj with another gem right now. We should aim to get this long lasting issue fixed in Xcodeproj gem instead. 
I asked for more info in the Cocoapods/Xcodeproj issue that you linked, this will help us debug the issue, as it's not every project that has this issue

**Comment by ryechus** [comment] 2020-11-05 05:39
The problem is definitely in the Xcodeproj gem, but I was able to solve the issue by making sure the scheme was in the `xcshared` folder. I got the idea from this comment https://github.com/CocoaPods/Xcodeproj/issues/607#issuecomment-633546694

I was able to add the scheme to the folder by clicking the "Autocreate Schemes Now" button in Xcode.

**Comment by rogerluan** [comment] 2020-11-08 15:08
Awesome! I realized that my settings already have the "Autocreate schemes" checked, so maybe that's why I never faced this issue.

For future reference, this is the screen we're referring to, which is shown after clicking "Manage Schemes": 

<img width="672" alt="image" src="https://user-images.githubusercontent.com/8419048/98468821-f56b0f80-21ba-11eb-8ce1-5812bc58b264.png">

I'm gonna close this issue as we seem to have a valid workaround, and anything beyond this workaround is out of our control. :) 

Thanks for digging into this @ryechus ! 🎉

**Closed** 2020-11-08 15:09 UTC
Labels: status: waiting-on-dependency, status: workaround available, tool: scan
