### ISSUE TITLE
Export fails for enterprise with Xcode8

### ISSUE THREAD

**Issue by hachibe** [fastlane/fastlane#6289] opened 2016-09-26 07:28 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When I use Xcode8 and the following gym for exporting by enterprise, it is failed with message "Exit status: 12" and "Error packaging up the application".

```
gym(
  workspace: "xxx.xcworkspace",
  configuration: configuration,
  scheme: scheme,
  silent: true,
  clean: true,
  output_directory: output_directory,
  output_name: output_name,
  codesigning_identity: "xxx",
  export_team_id: "xxx",
  export_method: "enterprise",
  toolchain: "com.apple.dt.toolchain.Swift_2_3",
  use_legacy_build_api: true,
  include_bitcode: false,
)
end
```

##### Complete output when running fastlane, including the stack trace and command used

```
[09:46:24]: -------------------------------------------------
[09:46:24]: --- Step: Verifying required fastlane version ---
[09:46:24]: -------------------------------------------------
[09:46:24]: fastlane version valid
[09:46:24]: ------------------------------
[09:46:24]: --- Step: default_platform ---
[09:46:24]: ------------------------------
[09:46:25]: Driving the lane 'ios ipa_inhouse' 🚀
[09:46:25]: ------------------
[09:46:25]: --- Step: sigh ---
[09:46:25]: ------------------

+-------------------------------------+---------------------------------------+
|                           Summary for sigh 1.11.1                           |
+-------------------------------------+---------------------------------------+
| adhoc                               | false                                 |
| development                         | false                                 |
| skip_install                        | false                                 |
| force                               | false                                 |
| app_identifier                      | xxx                                   |
| username                            | xxx                                   |
| team_id                             | xxx                                   |
| ignore_profiles_with_different_name | false                                 |
| skip_fetch_profiles                 | false                                 |
| skip_certificate_verification       | false                                 |
+-------------------------------------+---------------------------------------+

[09:46:25]: Starting login with user 'xxx'
[09:46:29]: Successfully logged in
[09:46:29]: Fetching profiles...
[09:46:36]: Found 2 matching profile(s)
[09:46:36]: Downloading provisioning profile...
[09:46:37]: Successfully downloaded provisioning profile...
[09:46:37]: Installing provisioning profile...
xxx
[09:46:37]: Setting Provisioning Profile type to 'enterprise'
[09:46:37]: --------------------------------------------------
[09:46:37]: --- Step: Switch to ios update_enterprise lane ---
[09:46:37]: --------------------------------------------------
[09:46:37]: Cruising over to lane 'ios update_enterprise' 🚖
[09:46:37]: -------------------------------
[09:46:37]: --- Step: update_info_plist ---
[09:46:37]: -------------------------------
[09:46:37]: Updated xxx/Application/Info.plist 💾.
[09:46:37]: ---------------------------------
[09:46:37]: --- Step: update_project_team ---
[09:46:37]: ---------------------------------
[09:46:37]: Updating development team (xxx) for the given project 'xxx.xcodeproj/project.pbxproj'
[09:46:37]: Successfully updated project settings to use Developer Team ID 'xxx'
[09:46:37]: -----------------------------------
[09:46:37]: --- Step: update_app_identifier ---
[09:46:37]: -----------------------------------
[09:46:41]: Updated xxx.xcodeproj 💾.
[09:46:41]: Cruising back to lane 'ios ipa_inhouse' 🚘
[09:46:41]: -------------------------------------------------
[09:46:41]: --- Step: Switch to ios build_enterprise lane ---
[09:46:41]: -------------------------------------------------
[09:46:41]: Cruising over to lane 'ios build_enterprise' 🚖
[09:46:41]: ------------------------------------
[09:46:41]: --- Step: increment_build_number ---
[09:46:41]: ------------------------------------
[09:46:41]: $ cd xxx && agvtool new-version -all 0.1.0 && cd -
[09:46:41]: Setting version of project xxx to:
[09:46:41]: 0.1.0.
[09:46:41]: Also setting CFBundleVersion key (assuming it exists)
[09:46:41]: Updating CFBundleVersion in Info.plist(s)...
[09:46:41]: Updated CFBundleVersion in "xxx/Info.plist" to 0.1.0
[09:46:41]: Updated CFBundleVersion in "xxx/Info.plist" to 0.1.0
[09:46:41]: xxx
[09:46:41]: -----------------
[09:46:41]: --- Step: gym ---
[09:46:41]: -----------------
[09:46:41]: Using legacy build system - waiting for radar to be fixed: https://openradar.appspot.com/radar?id=xxx
[09:46:41]: Installing provisioning profile...
[09:46:41]: $ xcodebuild -list -workspace xxx.xcworkspace
[09:46:43]: $ xcodebuild clean -showBuildSettings -workspace xxx.xcworkspace -scheme xxx

+---------------------------+----------------------------------------------------------------------+
|                                      Summary for gym 1.10.0                                      |
+---------------------------+----------------------------------------------------------------------+
| workspace                 | xxx.xcworkspace                                                      |
| configuration             | Debug                                                                |
| scheme                    | xxx                                                                  |
| silent                    | true                                                                 |
| clean                     | true                                                                 |
| output_directory          | build                                                                |
| output_name               | xxx                                                                  |
| codesigning_identity      | iPhone Distribution: xxx                                             |
| export_method             | enterprise                                                           |
| toolchain                 | com.apple.dt.toolchain.Swift_2_3                                     |
| use_legacy_build_api      | true                                                                 |
| include_bitcode           | false                                                                |
| provisioning_profile_path | /Users/xxx/....                                                      |
| destination               | generic/platform=iOS                                                 |
| buildlog_path             | ~/Library/Logs/gym                                                   |
+---------------------------+----------------------------------------------------------------------+

[09:46:47]: Cleaning
[09:46:47]: Check Dependencies
...
[09:49:14]: Copying IconAssets2.framework
[09:49:16]: Running script 'Embed Pods Frameworks'
[09:49:16]: Running script 'Copy Pods Resources'
[09:49:16]: Running script 'Strip Unsupported Architectures'
[09:49:17]: Running script 'Run Script'
[09:49:17]: Touching xxx.app
[09:49:19]: Signing xxx.app
[09:49:22]: Archive Succeeded
[09:49:22]: Legacy build api is enabled, the `export_method` value will be ignored

[09:49:39]: Exit status: 12
[09:49:39]: Variable Dump:
[09:49:39]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios ipa_inhouse", :SIGH_PROFILE_PATH=>"xxx.mobileprovision", :SIGH_PROFILE_PATHS=>["xxx.mobileprovision"], :SIGH_UDID=>"xxx", :SIGH_PROFILE_TYPE=>"enterprise", :BUILD_NUMBER=>"0.1.0"}
[09:49:39]: Error packaging up the application

+------+--------------------------------------+-------------+
|                     fastlane summary                      |
+------+--------------------------------------+-------------+
| Step | Action                               | Time (in s) |
+------+--------------------------------------+-------------+
| 1    | Verifying required fastlane version  | 0           |
| 2    | default_platform                     | 0           |
| 3    | sigh                                 | 12          |
| 4    | Switch to ios update_enterprise lane | 0           |
| 5    | update_info_plist                    | 0           |
| 6    | update_project_team                  | 0           |
| 7    | update_app_identifier                | 3           |
| 8    | Switch to ios build_enterprise lane  | 0           |
| 9    | increment_build_number               | 0           |
| 10   | gym                                  | 178         |
+------+--------------------------------------+-------------+

[09:49:39]: fastlane finished with errors

[!] Error packaging up the application
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
fastlane_version "1.104.0"

default_platform :ios

CONFIGURATION_DEBUG   = "Debug"
CONFIGURATION_RELEASE     = "Release"

platform :ios do
  #====================== Public =================#
  lane :ipa_inhouse do |options|
    version = options[:version]
    config = options[:config] || CONFIGURATION_DEBUG
    config_name = config == CONFIGURATION_DEBUG ? "debug" : "release"
    disp_config = config == CONFIGURATION_DEBUG ? "D" : "R"
    disp_name = options[:disp_name] || "xxx" + version + disp_config

    sigh()

    update_enterprise(
      display_name: disp_name,
    )

    build_enterprise(
      version: version,
      scheme: "xxx",
      output_directory: "build",
      output_name: "xxx_" + config_name + "_inhouse.ipa",
      configuration: config,
    )
  end

  #===================== Private =================#
  private_lane :build_enterprise do |options|
    version          = options[:version]
    scheme           = options[:scheme]
    output_directory = options[:output_directory]
    output_name      = options[:output_name]
    configuration    = options[:configuration]
    production       = options[:production]

    if version
      increment_build_number(
        build_number: version,
        xcodeproj: "xxx.xcodeproj"
      )
    end

    ENV["FASTLANE_XCODE_LIST_TIMEOUT"] = "120"

    gym(
      workspace: "xxx.xcworkspace",
      configuration: configuration,
      scheme: scheme,
      silent: true,
      clean: true,
      output_directory: output_directory,
      output_name: output_name,
      codesigning_identity: "xxx",
      export_team_id: "xxx",
      export_method: "enterprise",
      toolchain: "com.apple.dt.toolchain.Swift_2_3",
      use_legacy_build_api: true,
      include_bitcode: false,
    )
  end

  private_lane :update_enterprise do |options|
    # Update Display Name
    display_name  = options[:display_name]
    update_info_plist(
      plist_path: "xxx/Application/Info.plist",
      display_name: display_name
    )

    # Update Team
    update_project_team(
      path: "xxx.xcodeproj",
      teamid: "xxx"
    )

    # Update BundleIdentifier
    update_app_identifier(
      plist_path: "xxx/Application/Info.plist",
      app_identifier: "xxx"
    )
  end

  error do |lane, exception|
  end
end
```

### Environment

fastlane version (run `fastlane -v`): 1.104.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? yes

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? no

**Comment by hachibe** [comment] 2016-09-26 09:11
> Have you seen our new Code Signing Troubleshooting Guide?

Yes, it is succeeded with Xcode7.

**Comment by TKBurner** [comment] 2016-09-26 18:15
Hi @hachibe, great to hear from you! Does: `xcodebuild clean -showBuildSettings -workspace xxx.xcworkspace -scheme xxx` (with proper values) succeed?

**Comment by hachibe** [comment] 2016-09-26 22:09
@TKBurner Thanks for your reaction!
Yes, it succeed.
xcarchive is also created at organizer.
But ipa is not created.

**Comment by pirocso** [comment] 2016-09-27 17:16
We are having the same issue. For us, the issue only appears when using update_app_identifier before gym. If I comment out update_app_identifier, no errors.

_update_app_identifier(app_identifier: ENV['APPID'], plist_path: "Info.plist")
gym(scheme: "Scheme Name", output_name: ENV['APPNAME'], use_legacy_build_api:true)_

I have confirmed with puts commands that both environment variables exist and that they output the correct data

**Comment by pirocso** [comment] 2016-09-27 19:32
This is definitely NOT a code signing issue. The archive is created perfectly fine with both Xcode 8 and Xcode 7 from the IDE. And as stated above, this only happens if the _update_app_identifier_ command is used.

**Comment by TKBurner** [comment] 2016-09-27 20:40
@hachibe  Can you confirm that this doesn't happen if you remove _update_app_identifier_? Does it only persist for enterprise? Thanks!

**Comment by nexus49** [comment] 2016-09-28 03:31
Same issue here. I can also confirm that the error goes away when commenting out `update_app_identifier`

**Comment by hachibe** [comment] 2016-09-28 14:04
@pirocso Thanks for your helpful advice!
Without `update_app_identifier`, this issue is fixed, ipa is created, and it can be installed!

**Comment by hachibe** [comment] 2016-09-28 14:07
@pirocso I would like to confirm just in case,
why does this issue only exists with Xcode 8 not Xcode 7?

**Comment by hachibe** [comment] 2016-09-28 16:24
@TKBurner 
> Does it only persist for enterprise?
Probably yes, because other projects not for enterprise have no issue.
I'll try by this project not for enterprise with `update_app_identifier`,
and let you know.

**Comment by hachibe** [comment] 2016-09-29 11:32
@TKBurner 
> Does it only persist for enterprise?

It is no, this issue doesn't matter whether enterprise is not.

**Comment by TKBurner** [comment] 2016-10-04 14:56
@hachibe Thanks so much for answering those questions. I followed up with the team here so we can look into it. We'll work with you on this thread.

**Comment by ryanmeisters** [comment] 2016-10-07 00:15
I'm also having this problem, using update_app_identifier to update bundle ids for app, watch app, and watch extension targets. The  update_app_identifier calls successfully replace the bundle identifiers, but gym fails with `Exit Status: 12`. 

The weird thing is that the build succeeds if I comment out the calls to update_app_identifier and re-run (via gym or fastlane) without reverting the changes previously made by update_app_identifier. So update_app_identifier seems to be doing something outside of updating the pbxproj that is causing gym to fail.. 

I'm able to reproduce on demand and am happy to help get this diagnosed.

**Comment by TKBurner** [comment] 2016-10-11 18:21
@ryanmeisters Are you using the legacy_build_api? Does it persist if you turn that off? Thanks!

**Comment by ryanmeisters** [comment] 2016-10-11 19:13
Hey @TKBurner. We are. Our gym invocation is like this:

    gym(
        scheme: app.scheme,
        configuration: app.build_configuration,
        include_bitcode: app.bitcode,
        use_legacy_build_api: true,
        toolchain: :swift_2_3
    )

I just tried removing the legacy build api and I get the Error message: 

> [11:47:12]: Exit status: 70
> ... 
> [11:47:12]: There was an error exporting your application
> [11:47:12]: Unfortunately the new Xcode export API is unstable and causes problems on some projects
> [11:47:12]: You can temporary use the :use_legacy_build_api option to get the build to work again

Here's a gist showing the `update_app_identifier` code that isn't working for me and my current work around. It's weird--I don't see any difference in pbxproj files generated by update_app_identifier vs just doing a find/replace
https://gist.github.com/ryanmeisters/11a95459428a5df5c23c08334bd9e847

**Comment by KrauseFx** [comment] 2016-10-11 19:22
@ryanmeisters Please share the complete output when running it with no legacy build API

**Comment by ryanmeisters** [comment] 2016-10-11 20:34
Certainly. Here's the output without legacy build api
https://gist.github.com/ryanmeisters/87844578df1261774500e7bce2f8164b

Looks like all fingers point at code signing but I could swear I checked and double checked that stuff a million times. There's a message in there about entitlements as well. Maybe that's the issue.

**Comment by TKBurner** [comment] 2016-10-12 20:00
@ryanmeisters Thanks for sharing that. Are you using watchkit? Are you able to reproduce this on a blank Xcode project with the Enterprise cert? Thanks!

**Comment by ryanmeisters** [comment] 2016-10-12 20:08
No problem. We are using watchkit, and we're actually not on an enterprise account. I'll see if I can make some time to try it in a fresh project

**Comment by KrauseFx** [comment] 2016-10-12 21:26
@ryanmeisters What is the `shell_session_update` file? Did you call or add that somewhere? Maybe in your Xcode build phase?

**Comment by ryanmeisters** [comment] 2016-10-12 22:04
@KrauseFx good question. Looks like it's an rvm thing per [this thread](https://github.com/direnv/direnv/issues/210). I did an `rvm get head` as suggested and that message went away, but the `Exit Status: 70` message is the same. 

It seems like I've still got some ruby environment issues though. 

Is forcing use of system ruby expected behavior?
> RVM detected, forcing to use system ruby
Warning! PATH is not properly set up, '/Users/ryan/.rvm/gems/ruby-2.3.1@ios/bin' is not at first place,
usually this is caused by shell initialization files - check them for 'PATH=...' entries,
it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
to fix temporarily in this shell session run: 'rvm use ruby-2.3.1@ios'.
Now using system ruby.

**Comment by mfurtak** [comment] 2016-10-14 18:36
Hi folks 👋 

We're seeing other seemingly related trouble for people using actions like `update_app_identifier` that delegate to `xcodeproj`.

Can you confirm what version of `xcodeproj` you have installed by running 
```
gem which xcodeproj
```

Thanks!

**Comment by mfurtak** [comment] 2016-10-17 15:34
Hi all,

The CocoaPods folks are tracking this problem and trying to work around it in [Xcodeproj](https://github.com/CocoaPods/Xcodeproj).

As noted here: https://github.com/CocoaPods/Xcodeproj/issues/426#issuecomment-251804075 please see if upgrading to `xcodeproj` 1.3.2 and then using the ENV variable `FORK_XCODE_WRITING=true` when running fastlane gets things working again in the short term.

```
gem update xcodeproj
FORK_XCODE_WRITING=true fastlane your_lane
```

Thanks!

**Comment by ryanmeisters** [comment] 2016-10-17 17:45
ah! That made me realize that since fastlane is forcing system ruby it's using an outdated xcodeproj.. I should have realized that before. I updated and now I'm having trouble getting update_app_identifier to find my project file.. will play with it some more and report back

**Comment by asfalcone** [comment] 2016-10-17 20:56
I'm going to close this as a dupe of #6278.

Working on a fix that will incorporate the above mentioned environment variable and suggest that users upgrade to `xcodeproj` 1.3.2

**Closed by asfalcone** 2016-10-17 20:56 UTC
Labels: bug, gym, you can do this

**Comment by TKBurner** [comment] 2016-10-17 21:25
With the latest Xcodeproj release (1.3.2) you can use an ENV var which people report as fixing this: FORK_XCODE_WRITING=true
