### ISSUE TITLE
badge action takes too much time to start in Travis-CI

### ISSUE THREAD

**Issue by Sega-Zero** [fastlane/fastlane#1127] opened 2016-01-18 15:05 UTC
tried a new `badge` action. Looks very cool, but it takes too much time to start, why?
Having this in logs:
> [15:01:14]: -------------------
> [15:01:14]: --- Step: badge ---
> [15:01:14]: -------------------
> [15:01:15]: Start adding badges...
> [15:01:49]: './Project/Assets.xcassets/AppIcon.appiconset/Icon1024.png'

30 seconds? @HazAT, are there any verbosity option to find out what causes such a delay?

**Comment by HazAT** [comment] 2016-01-18 19:05
Is it reproducible?
Because maybe travis is installing some dependencies in the background...

**Comment by Sega-Zero** [comment] 2016-01-18 19:09
Not always, that's the riddle for me. Sometimes the delay is about 4 seconds, sometimes it's 30. Can you add some verbose parameter to make sure it is a travis issue or a badge issue?

**Comment by HazAT** [comment] 2016-01-18 19:19
Ok good to know, will add a verbose option next version, should not be a huge deal.
I will keep you posted on this.
see https://github.com/HazAT/badge/issues/3

**Comment by Sega-Zero** [comment] 2016-01-21 15:10
Caught a `522 Origin Connection Time-out` error, the build went totally broken. Is there any way to stop depend on https://img.shields.io?

**Comment by HazAT** [comment] 2016-01-21 15:33
oh you are right, their site is pretty slow right now.
I've found a issue relating to this https://github.com/badges/shields/issues/445

You could not use a shield, then it should be faster. I am considering adding a not so fancy text on the icon instead of the shield.

**Comment by Sega-Zero** [comment] 2016-01-21 15:40
But I need that shield =) Maybe we could specify a custom shield images, like `--custom` for overlay?

**Comment by HazAT** [comment] 2016-01-21 15:55
There is already a `custom` option.
`badge(custom: "/Users/.../Desktop/badge.png")`
which resizes your passed image to the size of the icon and puts it on top of it.

**Comment by Sega-Zero** [comment] 2016-01-21 15:57
It works for `beta` badge, am I wrong? I need this for shield.

**Comment by Sega-Zero** [comment] 2016-01-25 15:47
At least, can we fallback to just a text captioning if the resource is not reachable?
Like [this](http://merowing.info/2013/03/overlaying-application-version-on-top-of-your-icon/).

**Comment by vpolouchkine** [comment] 2016-04-06 21:27
It looks like there hasn’t been any recent activity on this issue in some time, so I’m closing it. If this is still a problem, feel free to re-open a new issue and I’d be happy to help :+1:

**Closed by vpolouchkine** 2016-04-06 21:27 UTC
Labels: action
