### ISSUE TITLE
Add the ability to use args on swift lanes

### ISSUE THREAD

**Issue by juliengdt** [fastlane/fastlane#11747] opened 2018-01-31 11:26 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

It would be a good idea to let lanes take args in swift modes like this:

```
class Fastfile: LaneFile {
    func hockey(client: String, env: String) { //lane takes here 2 args
    desc("Push a new beta build to TestFlight")
        buildApp(workspace: "myspace.xcworkspace", scheme: schemeFor(env, client))
        uploadToHockeyApp(Credentials.shared.username, clientFor(client))
    }
}
```

#### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.2                                                        |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.14.3 (Apple Git-98)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.2 (17C88)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.2                                                            |

#### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | fr_FR.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.79.0  | ✅ Up-To-Date  |

#### Loaded fastlane plugins:

| Plugin                        | Version | Update-Status |
| ----------------------------- | ------- | ------------- |
| fastlane-plugin-mobile_center | 0.1.5   | ✅ Up-To-Date  |
| fastlane-plugin-versioning    | 0.3.4   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.0.0        |
| slack-notifier                | 2.3.2        |
| CFPropertyList                | 2.3.6        |
| claide                        | 1.0.2        |
| colored2                      | 3.1.2        |
| nanaimo                       | 0.2.3        |
| xcodeproj                     | 1.5.4        |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.2.8        |
| terminal-notifier             | 1.8.0        |
| unicode-display_width         | 1.3.0        |
| terminal-table                | 1.8.0        |
| plist                         | 3.4.0        |
| public_suffix                 | 2.0.5        |
| addressable                   | 2.5.2        |
| multipart-post                | 2.0.0        |
| word_wrap                     | 1.0.0        |
| tty-screen                    | 0.6.4        |
| tty-cursor                    | 0.5.0        |
| tty-spinner                   | 0.8.0        |
| babosa                        | 1.0.2        |
| colored                       | 1.2          |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.5        |
| excon                         | 0.60.0       |
| faraday                       | 0.13.1       |
| unf_ext                       | 0.0.7.4      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20170404 |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.6        |
| fastimage                     | 2.1.1        |
| gh_inspector                  | 1.0.3        |
| json                          | 1.8.3        |
| mini_magick                   | 4.5.1        |
| multi_json                    | 1.13.1       |
| multi_xml                     | 0.6.0        |
| rubyzip                       | 1.2.1        |
| security                      | 0.1.3        |
| xcpretty-travis-formatter     | 1.0.0        |
| dotenv                        | 2.2.1        |
| bundler                       | 1.16.1       |
| faraday_middleware            | 0.12.2       |
| uber                          | 0.1.0        |
| declarative                   | 0.0.10       |
| declarative-option            | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.1        |
| mime-types-data               | 3.2016.0521  |
| mime-types                    | 3.1          |
| little-plugger                | 1.1.4        |
| logging                       | 2.2.2        |
| jwt                           | 2.1.0        |
| memoist                       | 0.16.0       |
| os                            | 0.9.6        |
| signet                        | 0.8.1        |
| googleauth                    | 0.6.2        |
| httpclient                    | 2.8.3        |
| google-api-client             | 0.13.6       |
| io-console                    | 0.4.5        |
| libxml-ruby                   | 2.9.0        |
| fastlane-plugin-mobile_center | 0.1.5        |
| fastlane-plugin-versioning    | 0.3.4        |
</details>

**Comment by taquitos** [comment] 2018-01-31 17:07
Would you mind sharing a little bit about what this helps enable, basically, why you think this is a good idea?

**Comment by juliengdt** [comment] 2018-02-07 08:35
@taquitos i putted an example right above in section *description*

It's quit obvious: do the same behavior as ruby file to enable put params into func ... no ?

**Comment by taquitos** [comment] 2018-02-07 19:33
I guess I wasn't being imaginative enough. It's not a feature I use in fastlane, but you're totally right.

**Comment by daneov** [comment] 2018-02-12 16:24
👍 Readability++

**Comment by VivintMan** [comment] 2018-02-27 21:13
Is this not a duplicate of issue number #11370? [https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjj5IW-_sbZAhXM1IMKHe3CAXUQFggpMAA&url=https%3A%2F%2Fgithub.com%2Ffastlane%2Ffastlane%2Fissues%2F11370&usg=AOvVaw1cX814OgJ1zr8fwUYvntQZ](url)

**Comment by taquitos** [comment] 2018-02-27 22:49
@VivintMan I haven't tried it yet, but I think you **_should_** be able to do:
`func makeBurritoLane(tacos: Integer, beans: Integer) { }`

Then on the command line: 
`fastlane makeBurrito tacos:2 beans:1`

**Comment by VivintMan** [comment] 2018-02-28 00:10
@taquitos excellent! Thanks! TBH, that’s exactly  what I thought I’d try, but I’ve been prepping our codebase for a release and iterating on some policies around our release train, so I wasn’t in a position to try it out. I definitely will tomorrow, though!
Thanks again!

**Closed** 2018-04-09 17:33 UTC
Labels: status: waiting-for-reply, type: enhancement, type: swift

**Comment by doruvil** [comment] 2018-04-10 13:33
I have been trying to pass parameters to lane as it was presented by @juliengdt and @taquitos but it's not working as it is described in this issue tickets.
For that reason I have documented here the whole process:
https://medium.com/@doruvil/fatlane-continous-integration-swift-version-b8851f1f38b6
There are some changes needed still for  **LaneFileProtocol**
