### ISSUE TITLE
[!] undefined method `downcase' for nil:NilClass (NoMethodError) on 2.105.0

### ISSUE THREAD

**Issue by bradx954** [fastlane/fastlane#13403] opened 2018-09-20 19:57 UTC
### Regression

See error below. Switching back to 2.104.0 fixed the issue.

```
/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.0/fastlane_core/lib/fastlane_core/fastlane_folder.rb:24:in `swift?': [!] undefined method `downcase' for nil:NilClass (NoMethodError)
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:71:in `run!'
	from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.0/deliver/lib/deliver/commands_generator.rb:182:in `run'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.0/deliver/lib/deliver/commands_generator.rb:17:in `start'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.0/fastlane/lib/fastlane/cli_tools_distributor.rb:100:in `take_off'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.0/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
Deploy failed, error: exit status 1

**Comment by oddgames-david** [comment] 2018-09-20 19:59
Is there a command to easily switch back?

**Comment by raymiec** [comment] 2018-09-20 20:26
i got the same error when trying fastlane init from a fresh install using brew, removing and installing 2.10 never made any difference.

**Comment by bradx954** [comment] 2018-09-20 21:29
@alexstrong29 used pretty much the exact same thing on bitrise. It's hidden under a "debug" dropdown.

**Comment by alexstrong29** [comment] 2018-09-20 21:33
@bradx954 hadn't heard of bitrise, just checked that out. 
I'm always on the look out to make setting up CI a bit easier! 200 builds as month for free looks quite good!

**Comment by zineer** [comment] 2018-09-21 03:39
This seems to be caused by this change: https://github.com/fastlane/fastlane/pull/13333/files#diff-afee814ded0e79042832f3de1d681a53R71 :(

**Comment by joshdholtz** [comment] 2018-09-21 10:27
Fixing now! Will have new release out shortly 💪

**Comment by ff-ahumberston** [comment] 2018-09-21 10:33
I can confirm dropping a Fastlane/fastfile into the working directory will workaround the issue in the short term, prior to the new release being available.

**Comment by joshdholtz** [comment] 2018-09-21 10:51
Fix is merged and working on a `2.105.1` release. I yanked `2.105.0` from Rubygems so that nobody else will have this issue.

**Closed** 2018-09-21 10:51 UTC
Labels: status: regression

**Comment by joshdholtz** [comment] 2018-09-21 11:28
`2.105.1` is out now and has the fix for this issue 🚀

**Comment by alexstrong29** [comment] 2018-09-21 20:00
@joshdholtz good work looking in to it so quickly!
