### ISSUE TITLE
ITC.response.error.INVALID_REQUEST when distribute an app using pilot

### ISSUE THREAD

**Issue by mohakpatel65** [fastlane/fastlane#6821] opened 2016-11-01 18:49 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
fastlane 1.106.2
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Getting ITC.response.error.INVALID_REQUEST when executing "`pilot distribute --verbose`", "`pilot distribute --distribute_external false --verbose`"

##### Complete output when running fastlane, including the stack trace and command used

```
INFO [2016-11-01 11:46:57.15]: Login to iTunes Connect (****@***.com)
Looking for iTunes Connect Team with ID ****
INFO [2016-11-01 11:46:59.07]: Login successful
DEBUG [2016-11-01 11:46:59.07]: App identifier (***.*****.****)
INFO [2016-11-01 11:47:01.87]: Distributing build 1.0(1) from Inactive -> External
INFO [2016-11-01 11:47:01.87]: Distributing new build to testers

Looking for related GitHub issues on fastlane/fastlane...
Search query: The request could not be completed because:
	ITC.response.error.INVALID_REQUEST

URL: https://api.github.com/search/issues?q=The%20request%20could%20not%20be%20completed%20because:%0A%09ITC.response.error.INVALID_REQUEST+repo:fastlane/fastlane
Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
/usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.36.2/lib/spaceship/tunes/tunes_client.rb:218:in `handle_itc_response': [!] The request could not be completed because: (Spaceship::TunesClient::ITunesConnectError)
	ITC.response.error.INVALID_REQUEST
	from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.36.2/lib/spaceship/tunes/tunes_client.rb:702:in `submit_testflight_build_for_review!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/pilot-1.11.2/lib/pilot/build_manager.rb:168:in `distribute_build'
	from /usr/local/lib/ruby/gems/2.3.0/gems/pilot-1.11.2/lib/pilot/build_manager.rb:73:in `distribute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/pilot-1.11.2/lib/pilot/commands_generator.rb:69:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.53.0/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/pilot-1.11.2/lib/pilot/commands_generator.rb:135:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/pilot-1.11.2/lib/pilot/commands_generator.rb:15:in `start'
	from /usr/local/lib/ruby/gems/2.3.0/gems/pilot-1.11.2/bin/pilot:6:in `<top (required)>'
	from /usr/local/bin/pilot:23:in `load'
	from /usr/local/bin/pilot:23:in `<main>'
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| fastlane_core       | 0.53.0  | ✅ Up-To-Date  |
| spaceship           | 0.36.2  | ✅ Up-To-Date  |
| deliver             | 1.14.5  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| pem                 | 1.3.2   | ✅ Up-To-Date  |
| cert                | 1.4.3   | ✅ Up-To-Date  |
| sigh                | 1.11.2  | ✅ Up-To-Date  |
| produce             | 1.2.1   | ✅ Up-To-Date  |
| gym                 | 1.11.3  | ✅ Up-To-Date  |
| scan                | 0.13.1  | ✅ Up-To-Date  |
| supply              | 0.7.1   | ✅ Up-To-Date  |
| match               | 0.10.0  | ✅ Up-To-Date  |
| screengrab          | 0.5.5   | ✅ Up-To-Date  |
| fastlane            | 1.106.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded***

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version     |
| ------------------------- | ----------- |
| did_you_mean              | 1.0.0       |
| highline                  | 1.7.8       |
| commander                 | 4.4.0       |
| terminal-table            | 1.4.5       |
| json                      | 1.8.3       |
| multipart-post            | 2.0.0       |
| faraday                   | 0.9.2       |
| faraday_middleware        | 0.10.0      |
| dotenv                    | 2.1.1       |
| net-ssh                   | 3.2.0       |
| net-sftp                  | 2.1.2       |
| plist                     | 3.1.0       |
| rubyzip                   | 1.1.7       |
| security                  | 0.1.3       |
| krausefx-shenzhen         | 0.14.10     |
| slack-notifier            | 1.5.1       |
| rouge                     | 1.11.1      |
| xcpretty                  | 0.2.4       |
| terminal-notifier         | 1.7.1       |
| word_wrap                 | 1.0.0       |
| multi_json                | 1.12.1      |
| colored                   | 1.2         |
| babosa                    | 1.0.2       |
| excon                     | 0.54.0      |
| gh_inspector              | 1.0.2       |
| credentials_manager       | 0.16.2      |
| fastlane_core             | 0.53.0      |
| bundler                   | 1.13.5      |
| multi_xml                 | 0.5.5       |
| http-cookie               | 1.0.3       |
| faraday-cookie_jar        | 0.0.6       |
| fastimage                 | 1.6.8       |
| mini_magick               | 4.5.1       |
| xcpretty-travis-formatter | 0.0.4       |
| uber                      | 0.0.15      |
| representable             | 2.3.0       |
| retriable                 | 2.1.0       |
| mime-types-data           | 3.2016.0521 |
| mime-types                | 3.1         |
| hurley                    | 0.2         |
| little-plugger            | 1.1.4       |
| logging                   | 2.1.0       |
| jwt                       | 1.5.6       |
| memoist                   | 0.15.0      |
| os                        | 0.9.6       |
| signet                    | 0.7.3       |
| googleauth                | 0.5.1       |
| httpclient                | 2.8.2.4     |
| google-api-client         | 0.9.19      |
| i18n                      | 0.7.0       |
| thread_safe               | 0.3.5       |
| tzinfo                    | 1.2.2       |
| activesupport             | 4.2.7.1     |
| io-console                | 0.4.5       |
| CFPropertyList            | 2.3.3       |
| claide                    | 1.0.1       |
| nanaimo                   | 0.1.2       |
| xcodeproj                 | 1.4.0       |
</details>

**Comment by gcamp** [comment] 2016-11-02 15:02
I think this is a duplicate of https://github.com/fastlane/fastlane/issues/6818

**Comment by TKBurner** [comment] 2016-11-02 16:28
@mohakpatel65 This is a duplicate. We'll work with you both there and on a PR with @gcamp 👍

**Closed** 2017-01-10 16:39 UTC
Labels: waiting-for-reply
