### ISSUE TITLE
fastlane deliver download_metadata error in language_item.rb

### ISSUE THREAD

**Issue by jiyee** [fastlane/fastlane#8924] opened 2017-04-20 06:31 UTC
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [x ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

deliver metadata action error in language_item.rb, if key is supportURL or privacyURL or marketingURL, others like name can be OK.

error occurs when trying to  download or upload metadata both.

Our app language is zh-Hans only.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[14:28:37]: Do you want to overwrite existing metadata on path '/Users/jiyee/Xcode/RenRenChe/fastlane/metadata'?
(y/n)
y
description
[14:28:41]: Writing to './fastlane/metadata/zh-Hans/description.txt'
keywords
[14:28:41]: Writing to './fastlane/metadata/zh-Hans/keywords.txt'
releaseNotes
[14:28:41]: Writing to './fastlane/metadata/zh-Hans/release_notes.txt'
supportURL

Looking for related GitHub issues on fastlane/fastlane...

➡️  undefined method `edit_version' for nil:NilClass
   https://github.com/fastlane/fastlane/issues/8660 [open] 6 💬
   3 weeks ago

➡️  Deliver Error: undefined method `[]=' for nil:NilClass in spaceship/tunes/language_item.rb
   https://github.com/fastlane/fastlane/issues/8922 [open] 3 💬
   3 minutes ago

➡️  undefined method `id' for nil:NilClass while fastlane sigh repair
   https://github.com/fastlane/fastlane/issues/8184 [open] 3 💬
   01 Mar 2017

and 236 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60[]'%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/jiyee/.rvm/gems/ruby-2.3.1/gems/fastlane-2.27.0/spaceship/lib/spaceship/tunes/language_item.rb:17:in `[]': [!] undefined method `[]' for nil:NilClass (NoMethodError)
	from /Users/jiyee/.rvm/gems/ruby-2.3.1/gems/fastlane-2.27.0/deliver/lib/deliver/setup.rb:44:in `block (2 levels) in generate_metadata_files'
	from /Users/jiyee/.rvm/gems/ruby-2.3.1/gems/fastlane-2.27.0/deliver/lib/deliver/setup.rb:42:in `each'
	from /Users/jiyee/.rvm/gems/ruby-2.3.1/gems/fastlane-2.27.0/deliver/lib/deliver/setup.rb:42:in `block in generate_metadata_files'
	from /Users/jiyee/.rvm/gems/ruby-2.3.1/gems/fastlane-2.27.0/deliver/lib/deliver/setup.rb:41:in `each'
	from /Users/jiyee/.rvm/gems/ruby-2.3.1/gems/fastlane-2.27.0/deliver/lib/deliver/setup.rb:41:in `generate_metadata_files'
	from /Users/jiyee/.rvm/gems/ruby-2.3.1/gems/fastlane-2.27.0/deliver/lib/deliver/commands_generator.rb:158:in `block (2 levels) in run'
	from /Users/jiyee/.rvm/gems/ruby-2.3.1/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/jiyee/.rvm/gems/ruby-2.3.1/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Users/jiyee/.rvm/gems/ruby-2.3.1/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/jiyee/.rvm/gems/ruby-2.3.1/gems/fastlane-2.27.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:40:in `run!'
	from /Users/jiyee/.rvm/gems/ruby-2.3.1/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Users/jiyee/.rvm/gems/ruby-2.3.1/gems/fastlane-2.27.0/deliver/lib/deliver/commands_generator.rb:164:in `run'
	from /Users/jiyee/.rvm/gems/ruby-2.3.1/gems/fastlane-2.27.0/deliver/lib/deliver/commands_generator.rb:12:in `start'
	from /Users/jiyee/.rvm/gems/ruby-2.3.1/gems/fastlane-2.27.0/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Users/jiyee/.rvm/gems/ruby-2.3.1/gems/fastlane-2.27.0/bin/fastlane:20:in `<top (required)>'
	from /Users/jiyee/.rvm/gems/ruby-2.3.1/bin/fastlane:23:in `load'
	from /Users/jiyee/.rvm/gems/ruby-2.3.1/bin/fastlane:23:in `<main>'
	from /Users/jiyee/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/jiyee/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.8.3                           |
| Installation Source         | ~/.rvm/gems/ruby-2.3.1/bin/fastlane         |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.1/lib                |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   | zh_CN.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.27.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.2        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.13.7       |
| io-console                | 0.4.6        |
| slack-notifier            | 1.5.1        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.0.2        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| json                      | 2.0.2        |
| excon                     | 0.54.0       |
| rubyzip                   | 1.2.0        |
| plist                     | 3.2.0        |
| faraday                   | 0.10.1       |
| faraday_middleware        | 0.10.1       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| google-api-client         | 0.9.20       |
| fastimage                 | 2.0.1        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
</details>

*generated on:* **2017-04-20**
</details>

**Comment by alaincaltieri** [comment] 2017-04-20 17:04
Facing the very same issue. Looks like it's caused by a small change of naming in the response from iTC:
` supportURL` => `supportUrl`
`marketingURL` => `marketingUrl`

This does not affect privacyURL afaik

**Comment by mfurtak** [comment] 2017-04-20 17:19
A fix was merged in #8930 and will be shipped in the next release 👍

**Closed by mfurtak** 2017-04-20 17:19 UTC
