### ISSUE TITLE
lane executes in current directory, but action 'sh' executes in ./fastlane/

### ISSUE THREAD

**Issue by GoodMirek** [fastlane/fastlane#6982] opened 2016-11-13 21:02 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

lane executes in current directory, but action 'sh' executes in ./fastlane/ subdirectory
Is that correct and expected?

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                           |
| ------------------- | ----------------------------------------------- |
| OS                  | 10.11.6                                         |
| Ruby                | 2.3.1                                           |
| Bundler?            | false                                           |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/     |
| Xcode Version       | 7.3.1                                           |
| Git                 | git version 2.7.4 (Apple Git-66)                |
| Installation Source | /Users/admin/.rbenv/versions/2.3.1/bin/fastlane |
| Host                | Mac OS X 10.11.6 (15G1004)                      |
| Ruby Lib Dir        | /Users/admin/.rbenv/versions/2.3.1/lib          |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                     |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.108.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    # cocoapods

  end

##### Lane: TEST ########################
  desc "Runs all the tests"
  lane :test do
    scan
  end

##### Lane: SHENV ########################
  desc "Test sh(env) current directory"
  lane :shenv do
    puts("Call of sh('env')")
    sh('env')
    puts("Call of sh('pwd')")
    sh('pwd')
    puts("Call of sh('env')")
    sh('env')
  end

##### Lane: BETAAPPLE ########################
  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :betaapple do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

##### Lane: RELEASE ########################
  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

##### Lane: ALFA ########################
desc "Alfa Test fastlane"
lane :alfa do

  keychain_path = "#{ENV['PWD']}/ci-alfa.keychain"
  puts("Keychain path will be: #{keychain_path}")
  team_id = "U5CS3T9JSF"

  # Delete possible leftover keychain file, otherwise creation of a new temporary keychain would fail
  # Not needed if we can have a keychain file in the current working directory
  if File.exists?(keychain_path)
    puts("Deleting old keychain file: #{keychain_path}")
    FileUtils.rm_f(keychain_path)
  end

  # Cleanup keychain search list
  sh('security list-keychains -s')

  # Creating temporary keychain
  create_keychain(
    path: keychain_path,
    default_keychain: true,
    unlock: true,
    timeout: false,
    password: SecureRandom.base64
  )

  # Provision devices from file Provisioning/devices to Apple developer portal; optimistic provisioning applies
  register_devices(
    devices_file: "./devices"
  )

  # Remove all existing local provisioning profiles and all distribution provisioning profiles on the development portal
  # How to remove undesired provisioning profiles from match repo?
  # TODO; to avoid Xcode select wrong profile
  sh('sigh manage --force --clean_pattern ".*"')

  # Assure we have right adhoc distribution certificates and provisioning profiles
  match(
    git_url: "git@github.com:GrocerKey/ios-repository.git",
    git_branch: "master",
    type: "adhoc",
    app_identifier: [ "com.grocerkey.shopperapp", "*" ],
    username: "mirek@grocerkey.com",
    keychain_name: keychain_path,
    team_id: team_id,
    verbose: true,
    force: true,
    shallow_clone: true,
  )

  ENV['sigh_wildcard_adhoc'] = ENV['sigh_*_adhoc']
  puts "Provisioning profile 'sigh_wildcard_adhoc' UUID is: #{ENV['sigh_wildcard_adhoc']}"
  puts "Provisioning profile 'sigh_com.grocerkey.shopperapp_adhoc' UUID is: #{ENV['sigh_com.grocerkey.shopperapp_adhoc']}"
  sh('env')

# Building and archiving the project with wildcard provisioning profile, to avoid problems with signining of Cocoa pods
# While lane is executed in the current directory, 'sh' action executes in ./fastlane/ subdirectory
#  sh("xcodebuild -jobs 4 -workspace #{ENV['PWD']}/GrocerKey.xcworkspace -scheme 'GrocerKey' -destination generic/platform=iOS -sdk iphoneos9.3 -archivePath #{ENV['PWD']}/build/gkdev.xcarchive clean build archive PROVISIONING_PROFILE=$sigh_wildcard_adhoc")

# Exporting the archive with com.grocerkey.shopperapp provisioning profile
#  sh("xcodebuild -verbose -exportArchive -archivePath #{ENV['PWD']}/build/gkdev.xcarchive -exportOptionsPlist #{ENV['PWD']}/exportOptions.plist -exportPath #{ENV['PWD']}/build")

=begin
# gym compilation would work if pods can be built with com.grocerkey.shopperapp provisioning profile
  gym(
    workspace: "./GrocerKey.xcworkspace",
    scheme: "GrocerKey",
    clean: true,
    output_directory: './build/',
    export_method: 'ad-hoc',
    export_options: './exportOptions.plist',
    build_path: './build/',
    sdk: 'iphoneos9.3',
    destination: 'generic/platform=iOS'
  )
=end

  # Deleting temporary keychain, cleanup
  delete_keychain(
    name: keychain_path
  )

end

##### Lane: BETA ########################
desc "Submit a new Beta build to Hockey App"
lane :beta do

  keychain_name = "ci-beta"

  create_keychain(
    name: keychain_name,
    default_keychain: true,
    unlock: true,
    timeout: 3600,
    lock_when_sleeps: true,
    password: SecureRandom.base64
  )

  # Import distribution certificate
  import_certificate(
    certificate_path: "fastlane/Certificates/distribution.p12",
    certificate_password: ENV["KEY_PASSWORD"],
    keychain_name: keychain_name
  )

  # Provision devices from file Provisioning/devices to Apple developer portal; optimistic provisioning applies
  register_devices(
    devices_file: "Provisioning/devices"
  )

  # Fetch provisioning profile
  sigh(
    adhoc: true,
    username: "arek@macoscope.net",
    team_id: "XA8U8K5RRK",
    provisioning_name: "CI Example Ad Hoc",
    cert_id: "2T3HB2838A"
  )

  increment_build_number(build_number: number_of_commits)

  # Build
  gym(
    configuration: "Ad Hoc",
    sdk: "iphoneos9.2",
    clean: true,
    include_bitcode: false,
    include_symbols: true,
    use_legacy_build_api: true,
    export_method: "enterprise"
  )

  # Push to Hockey
  hockey(
    api_token: ENV["HOCKEY_API_TOKEN"],
    public_identifier: ENV["HOCKEY_APP_ID"],
    notify: '0',
    status: '2',
    notes: last_git_commit[:message] + "n(Uploaded automatically via fastlane)"
  )

  delete_keychain(
    name: keychain_name
  )

end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.grocerkey.shopperapp" # The bundle identifier of your app
apple_id "mirek@grocerkey.com" # Your Apple email address

team_id "U5CS3T9JSF"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| spaceship           | 0.37.0  | ✅ Up-To-Date  |
| fastlane_core       | 0.55.0  | ✅ Up-To-Date  |
| deliver             | 1.15.0  | ✅ Up-To-Date  |
| snapshot            | 1.16.3  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| pem                 | 1.4.0   | ✅ Up-To-Date  |
| cert                | 1.4.4   | ✅ Up-To-Date  |
| sigh                | 1.11.2  | ✅ Up-To-Date  |
| produce             | 1.3.0   | ✅ Up-To-Date  |
| gym                 | 1.12.0  | ✅ Up-To-Date  |
| pilot               | 1.12.0  | ✅ Up-To-Date  |
| scan                | 0.14.1  | ✅ Up-To-Date  |
| supply              | 0.7.1   | ✅ Up-To-Date  |
| match               | 0.11.0  | ✅ Up-To-Date  |
| screengrab          | 0.5.5   | ✅ Up-To-Date  |
| fastlane            | 1.108.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| terminal-table            | 1.4.5        |
| json                      | 1.8.3        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.10.0       |
| faraday_middleware        | 0.10.1       |
| dotenv                    | 2.1.1        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| plist                     | 3.2.0        |
| security                  | 0.1.3        |
| krausefx-shenzhen         | 0.14.11      |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.3        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.2        |
| xcodeproj                 | 1.4.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| credentials_manager       | 0.16.2       |
| multi_xml                 | 0.5.5        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| xcode-install             | 2.0.9        |
| word_wrap                 | 1.0.0        |
| multi_json                | 1.12.1       |
| babosa                    | 1.0.2        |
| excon                     | 0.54.0       |
| rubyzip                   | 1.1.7        |
| gh_inspector              | 1.0.2        |
| fastlane_core             | 0.55.0       |
| bundler                   | 1.13.6       |
| mini_magick               | 4.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.20       |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.9.1        |
| activesupport             | 4.2.7.1      |
| io-console                | 0.4.6        |
</details>

*generated on:* **2016-11-15**
</details>

**Comment by TKBurner** [comment] 2016-11-14 20:03
Hi @GoodMirek Hope you are doing well! Has this behavior changed or is this your first time noticing this behavior? Thanks!

**Comment by GoodMirek** [comment] 2016-11-15 14:37
Hi @TKBurner 
No idea whether it worked before. As quite new user, this is my first time noticing the behavior. The issue is that while sh('env') returns $PWD as the current top level directory of the project, the sh('command') command actually executes in ./fastlane/ subdirectory. Therefore, I cannot call `sh("./script.sh")` but has to call `sh("#{ENV['PWD']}/script.sh")`. This is inconsistent UX compared to e.g.
```
  register_devices(
    devices_file: "./devices"
  )
```
which works for files in the current directory.

It is possible to see the concerned behavior including discrepancy between `$PWD` and `pwd` in output of my test below.
```
fastlane shenv
[09:17:15]: -------------------------------------------------
[09:17:15]: --- Step: Verifying required fastlane version ---
[09:17:15]: -------------------------------------------------
[09:17:15]: Your fastlane version 1.108.0 matches the minimum requirement of 1.108.0  ✅
[09:17:15]: ------------------------------
[09:17:15]: --- Step: default_platform ---
[09:17:15]: ------------------------------
[09:17:15]: Driving the lane 'ios shenv' 🚀
[09:17:15]: Call of sh('env')
[09:17:15]: -----------------
[09:17:15]: --- Step: env ---
[09:17:15]: -----------------
[09:17:15]: $ env
[09:17:15]: ▸ RBENV_VERSION=2.3.1
[09:17:15]: ▸ SHELL=/bin/bash
[09:17:15]: ▸ TERM=xterm
[09:17:15]: ▸ SSH_CLIENT=46.39.172.199 56163 22
[09:17:15]: ▸ TMPDIR=/var/folders/d6/0r6dpnw109b3jj4_k84qwc8w0000gq/T/
[09:17:15]: ▸ SSH_TTY=/dev/ttys000
[09:17:15]: ▸ USER=admin
[09:17:15]: ▸ RBENV_ROOT=/Users/admin/.rbenv
[09:17:15]: ▸ SSH_AUTH_SOCK=/tmp/ssh-RZ33OeX6D0/agent.9826
[09:17:15]: ▸ RBENV_HOOK_PATH=/Users/admin/.rbenv/rbenv.d:/usr/local/Cellar/rbenv/1.0.0/rbenv.d:/usr/local/etc/rbenv.d:/etc/rbenv.d:/usr/lib/rbenv/hooks
[09:17:15]: ▸ PATH=/Users/admin/.rbenv/versions/2.3.1/bin:/usr/local/Cellar/rbenv/1.0.0/libexec:/Users/admin/.rbenv/shims:/Users/admin/.rbenv/bin:/usr/local/opt/openssl/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Applications/Server.app/Contents/ServerRoot/usr/bin:/Applications/Server.app/Contents/ServerRoot/usr/sbin
[09:17:15]: ▸ MAIL=/var/mail/admin
[09:17:15]: ▸ PWD=/Users/admin/iphone-front-end
[09:17:15]: ▸ LANG=en_US.UTF-8
[09:17:15]: ▸ RBENV_SHELL=bash
[09:17:15]: ▸ HOME=/Users/admin
[09:17:15]: ▸ SHLVL=1
[09:17:15]: ▸ RBENV_DIR=/Users/admin/iphone-front-end
[09:17:15]: ▸ LOGNAME=admin
[09:17:15]: ▸ SSH_CONNECTION=46.39.172.199 56163 192.225.162.169 22
[09:17:15]: ▸ RUBYLIB=/usr/local/Cellar/rbenv/1.0.0/rbenv.d/exec/gem-rehash:
[09:17:15]: ▸ __CF_USER_TEXT_ENCODING=0x1F7:0x0:0x0
[09:17:15]: ▸ BUNDLER_ORIG_PATH=/Users/admin/.rbenv/versions/2.3.1/bin:/usr/local/Cellar/rbenv/1.0.0/libexec:/Users/admin/.rbenv/shims:/Users/admin/.rbenv/bin:/usr/local/opt/openssl/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Applications/Server.app/Contents/ServerRoot/usr/bin:/Applications/Server.app/Contents/ServerRoot/usr/sbin
[09:17:15]: ▸ FORK_XCODE_WRITING=true
[09:17:15]: ▸ FASTLANE_LANE_NAME=shenv
[09:17:15]: ▸ FASTLANE_PLATFORM_NAME=ios
[09:17:15]: Call of sh('pwd')
[09:17:15]: -----------------
[09:17:15]: --- Step: pwd ---
[09:17:15]: -----------------
[09:17:15]: $ pwd
[09:17:15]: ▸ /Users/admin/iphone-front-end/fastlane
[09:17:15]: Call of sh('env')
[09:17:15]: -----------------
[09:17:15]: --- Step: env ---
[09:17:15]: -----------------
[09:17:15]: $ env
[09:17:15]: ▸ RBENV_VERSION=2.3.1
[09:17:15]: ▸ SHELL=/bin/bash
[09:17:15]: ▸ TERM=xterm
[09:17:15]: ▸ SSH_CLIENT=46.39.172.199 56163 22
[09:17:15]: ▸ TMPDIR=/var/folders/d6/0r6dpnw109b3jj4_k84qwc8w0000gq/T/
[09:17:15]: ▸ SSH_TTY=/dev/ttys000
[09:17:15]: ▸ USER=admin
[09:17:15]: ▸ RBENV_ROOT=/Users/admin/.rbenv
[09:17:15]: ▸ SSH_AUTH_SOCK=/tmp/ssh-RZ33OeX6D0/agent.9826
[09:17:15]: ▸ RBENV_HOOK_PATH=/Users/admin/.rbenv/rbenv.d:/usr/local/Cellar/rbenv/1.0.0/rbenv.d:/usr/local/etc/rbenv.d:/etc/rbenv.d:/usr/lib/rbenv/hooks
[09:17:15]: ▸ PATH=/Users/admin/.rbenv/versions/2.3.1/bin:/usr/local/Cellar/rbenv/1.0.0/libexec:/Users/admin/.rbenv/shims:/Users/admin/.rbenv/bin:/usr/local/opt/openssl/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Applications/Server.app/Contents/ServerRoot/usr/bin:/Applications/Server.app/Contents/ServerRoot/usr/sbin
[09:17:15]: ▸ MAIL=/var/mail/admin
[09:17:15]: ▸ PWD=/Users/admin/iphone-front-end
[09:17:15]: ▸ LANG=en_US.UTF-8
[09:17:15]: ▸ RBENV_SHELL=bash
[09:17:15]: ▸ HOME=/Users/admin
[09:17:15]: ▸ SHLVL=1
[09:17:15]: ▸ RBENV_DIR=/Users/admin/iphone-front-end
[09:17:15]: ▸ LOGNAME=admin
[09:17:15]: ▸ SSH_CONNECTION=46.39.172.199 56163 192.225.162.169 22
[09:17:15]: ▸ RUBYLIB=/usr/local/Cellar/rbenv/1.0.0/rbenv.d/exec/gem-rehash:
[09:17:15]: ▸ __CF_USER_TEXT_ENCODING=0x1F7:0x0:0x0
[09:17:15]: ▸ BUNDLER_ORIG_PATH=/Users/admin/.rbenv/versions/2.3.1/bin:/usr/local/Cellar/rbenv/1.0.0/libexec:/Users/admin/.rbenv/shims:/Users/admin/.rbenv/bin:/usr/local/opt/openssl/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Applications/Server.app/Contents/ServerRoot/usr/bin:/Applications/Server.app/Contents/ServerRoot/usr/sbin
[09:17:15]: ▸ FORK_XCODE_WRITING=true
[09:17:15]: ▸ FASTLANE_LANE_NAME=shenv
[09:17:15]: ▸ FASTLANE_PLATFORM_NAME=ios

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | env                                 | 0           |
| 4    | pwd                                 | 0           |
| 5    | env                                 | 0           |
+------+-------------------------------------+-------------+
```
I have updated output of `fastlane env` in the description of this issue, to reflect the `shenv` lane.

**Comment by TKBurner** [comment] 2016-11-16 15:16
Hi @GoodMirek Hope you are doing well! I'm marking this as a feature request. It's expected behavior for now. Thanks!

**Comment by AndrewSB** [comment] 2016-12-16 23:14
@TKBurner: I ran into this too, and since `sh('env')` returned my project directory instead of `project_dir/fastlane`, I thought it was a legitimate bug, and I wasn't sure how to execute my script.

The inconsistent behavior is jarring, it seems like a bug to me as well

**Comment by KrauseFx** [comment] 2016-12-16 23:47
Hey everyone, sorry for coming back so late. This has been like it since the initial launch and is something that can't be changed unfortunately, as it would break existing setups. We'll leave it like this for now 👍

**Closed by KrauseFx** 2016-12-16 23:47 UTC
Labels: action, feature

**Comment by GoodMirek** [comment] 2016-12-17 01:00
I am sorry it did not make its way to the major release. Can we at least
highlight it in the documentation, as it is pretty counter- intuitive?

**Comment by KrauseFx** [comment] 2016-12-17 02:17
@GoodMirek Yes, I feel like breaking all existing setups would be a bigger pain. Yes, what's the best location to add that? `Advanced.md`?

**Comment by GoodMirek** [comment] 2016-12-17 23:19
@KrauseFx I understand the concerns. Idea - if you ever considered to change that behavior, there could be a switch available for some time, allowing for the deprecated behavior.

Documentation - in my opinion, `Advanced.md` is a good place to explain, thanks for proposing that. I prefer to also add a reference in the documentation of 'sh' action.
Reference could read: "Be aware of a specific behavior of 'sh' action with regard to its working directory. For details refer to Advanced.md".

What do you think?

**Comment by KrauseFx** [comment] 2016-12-18 01:08
Yes great idea @GoodMirek, thanks! Can you submit a PR to add that to those parts? 👍

**Comment by GoodMirek** [comment] 2017-03-21 09:16
Also related to https://github.com/fastlane/fastlane/issues/155
