### ISSUE TITLE
scan junit files should end with .xml

### ISSUE THREAD

**Issue by KingOfBrian** [fastlane/fastlane#3647] opened 2016-03-09 17:42 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
When I run scan, scan creates a `report.junit` file. This file is valid JUnit XML, however circleCI expects the junit files to end in `.xml`. The file extension `.junit` is not used anywhere else that I can see, no tools that generate junit compatible XML in the past have.

##### Complete output when running fastlane, including the stack trace and command used

```
[09:09:42]: Successfully generated report at '/tmp/circle-junit.f20Mh7C/report.junit'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
    scan(
      output_types: 'junit',
      scheme: '***removed***',
      output_directory: "#{ENV['CIRCLE_TEST_REPORTS']}",
  )
```

### Environment

fastlane version (fastlane -v):
Brians-MBP-2:app bking$ bundle exec fastlane -v
fastlane 1.66.0

**Comment by JagCesar** [comment] 2016-03-22 13:35
Would an accepted fix be to add `xml` as an option of `output_types`?

**Comment by KingOfBrian** [comment] 2016-03-22 14:38
I'd still prefer the file is just named `report-junit.xml`. I've never seen the file extension `.junit`, and I don't think that it was an intentional decision to use a different file extension. I'd rather push the implementation towards standard behavior than add an option (and documentation) for another type that is basically the same.

**Comment by johntmcintosh** [comment] 2016-03-29 13:33
Looks like this may be a duplicate ticket of #1942 where the consensus appears to be to default to a .xml extension.

**Comment by TKBurner** [comment] 2016-03-29 13:54
closing this as a duplicate of #1942. Please track this feature request over there :+1:

**Closed by TKBurner** 2016-03-29 13:54 UTC
Labels: feature, scan
