### ISSUE TITLE
Cannot update languages - could not find an editable version for 'IOS'

### ISSUE THREAD

**Issue by mackankowski** [fastlane/fastlane#16991] opened 2020-08-04 15:53 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

1. Started with `fastlane deliver init` for new project.
2. After `fastlane deliver --force` and partial progress I gets:

**[!] Cannot update languages - could not find an editable version for 'IOS'**

Let's a full log below:
```

[17:47:07]: Login to App Store Connect (...)
[17:47:10]: Login successful

+--------------------------------------+---------------------------+
|                     deliver 2.154.0 Summary                      |
+--------------------------------------+---------------------------+
| force                                | true                      |
| screenshots_path                     | ./fastlane/screenshots    |
| metadata_path                        | ./fastlane/metadata       |
| username                             | ... |
| app_identifier                       | ...     |
| platform                             | ios                       |
| edit_live                            | false                     |
| use_live_version                     | false                     |
| skip_binary_upload                   | false                     |
| skip_screenshots                     | false                     |
| skip_metadata                        | false                     |
| skip_app_version_update              | false                     |
| overwrite_screenshots                | false                     |
| submit_for_review                    | false                     |
| reject_if_possible                   | false                     |
| automatic_release                    | false                     |
| phased_release                       | false                     |
| reset_ratings                        | false                     |
| team_id                              | ...                   |
| dev_portal_team_id                   | ...                |
| run_precheck_before_submit           | true                      |
| precheck_default_rule_level          | warn                      |
| ignore_language_directory_validation | false                     |
| precheck_include_in_app_purchases    | true                      |
+--------------------------------------+---------------------------+

[17:47:15]: Loading './fastlane/metadata/en-US/description.txt'...
[17:47:15]: Loading './fastlane/metadata/en-US/keywords.txt'...
[17:47:15]: Loading './fastlane/metadata/en-US/release_notes.txt'...
[17:47:15]: Loading './fastlane/metadata/en-US/support_url.txt'...
[17:47:15]: Loading './fastlane/metadata/en-US/marketing_url.txt'...
[17:47:15]: Loading './fastlane/metadata/en-US/promotional_text.txt'...
[17:47:15]: Loading './fastlane/metadata/en-US/name.txt'...
[17:47:15]: Loading './fastlane/metadata/en-US/subtitle.txt'...
[17:47:15]: Loading './fastlane/metadata/en-US/privacy_url.txt'...
[17:47:15]: Loading './fastlane/metadata/en-US/apple_tv_privacy_policy.txt'...
[17:47:15]: Loading './fastlane/metadata/copyright.txt'...
[17:47:15]: Loading './fastlane/metadata/primary_category.txt'...
[17:47:15]: Loading './fastlane/metadata/secondary_category.txt'...
[17:47:15]: Loading './fastlane/metadata/primary_first_sub_category.txt'...
[17:47:15]: Loading './fastlane/metadata/primary_second_sub_category.txt'...
[17:47:15]: Loading './fastlane/metadata/secondary_first_sub_category.txt'...
[17:47:15]: Loading './fastlane/metadata/secondary_second_sub_category.txt'...
[17:47:15]: Loading './fastlane/metadata/review_information/first_name.txt'...
[17:47:15]: Loading './fastlane/metadata/review_information/last_name.txt'...
[17:47:15]: Loading './fastlane/metadata/review_information/phone_number.txt'...
[17:47:15]: Loading './fastlane/metadata/review_information/email_address.txt'...
[17:47:15]: Loading './fastlane/metadata/review_information/demo_user.txt'...
[17:47:15]: Loading './fastlane/metadata/review_information/demo_password.txt'...
[17:47:15]: Loading './fastlane/metadata/review_information/notes.txt'...

[!] Cannot update languages - could not find an editable version for 'IOS'
```

AppStoreConnect app language is en-US.

Thanks in advance,
Maciej

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
</pre>
</details>

### Environment

<details>
  <pre> 
### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.154.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.14.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.2        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday                   | 1.0.1        |
| faraday_middleware        | 1.0.0        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.9.5        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.7        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-core         | 1.4.1        |
| google-cloud-storage      | 1.25.0       |
| CFPropertyList            | 3.0.2        |
| excon                     | 0.76.0       |
| fastimage                 | 2.2.0        |
| dotenv                    | 2.7.6        |
| bundler                   | 2.1.4        |
| declarative               | 0.0.20       |
| multi_json                | 1.14.1       |
| signet                    | 0.14.0       |
| os                        | 1.0.1        |
| memoist                   | 0.16.2       |
| googleauth                | 0.13.0       |
| google-cloud-env          | 1.3.3        |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| emoji_regex               | 3.0.0        |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.1        |
| aws-partitions            | 1.350.0      |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.104.3      |
| aws-sdk-kms               | 1.36.0       |
| aws-sdk-s3                | 1.75.0       |
| forwardable               | 1.3.1        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.4.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>

*generated on:* **2020-08-04**

</pre>
</details>

**Comment by mackankowski** [comment] 2020-08-05 11:58
Potential solution is here: https://github.com/fastlane/fastlane/issues/16663#issuecomment-649595540
Or by following this post: https://github.com/fastlane/fastlane/pull/16626#issuecomment-645964941

Let me double-check if it works.

**Comment by JasonConeHM** [comment] 2020-08-12 16:48
For the record, we're also experiencing the same behavior on the save version even with an explicit app version being specified. For us, a follow-up attempt resulted in success without the need for manual intervention.

**Comment by JimHowell20** [comment] 2020-08-13 15:23
I'm getting the same issue here. I confirmed that the error is intermittent, but it's causing about 50% of all of my builds to occasionally fail on this step, so it's really slowing down our build process.  Does anyone have a fix for this?

**Comment by jarrodparkes** [comment] 2020-08-13 15:26
confirmed. having same issue with `v2.152.0`

**Comment by nirre7** [comment] 2020-08-14 09:05
Having the same issue with 2.156.1.

**Comment by ha1f** [comment] 2020-08-14 09:27
I had the same issue with 2.155.3.

I failed to deliver for the first time, but by running the CI workflow again, deliver succeeded.

**Comment by ppamorim** [comment] 2020-08-17 09:10
I am having the same issue in 2.156.1.

**Comment by ppamorim** [comment] 2020-08-17 09:17
@mackankowski None of the solutions sorted the problem.

**Comment by ppamorim** [comment] 2020-08-17 09:29
@joshdholtz Hi, is this issue on track to be fixed?

**Comment by mackankowski** [comment] 2020-08-17 21:03
> @mackankowski None of the solutions sorted the problem.

Did you try to add following property to `delivery` action:

`app_version: lane_context[SharedValues::LATEST_VERSION]`

I think this is what has solved my issue but let me re-check and go back to the topic - I’m not sure now if no app code changes was provided too...

**Comment by fizzle0196** [comment] 2020-08-19 16:15
I am having the same issue on 2.156.1

I tried adding the following to the `deliver` action but both failed:
- `app_version: lane_context[SharedValues::LATEST_VERSION]`
- `app_version: get_version_number(target: target)`

Neither of the above worked for me. However, whenever I get this error, a rerun usually fixes the error. This happens on about 30% of our builds.

**Comment by BenoitDeguine** [comment] 2020-08-23 19:45
Got this error too. Working fine by creating manually the new version on iTunes Connect.

**Comment by rogerluan** [comment] 2020-08-26 10:07
I faced this error too. Simply retrying worked just fine, with no changes.

**Comment by ibuprofane** [comment] 2020-08-27 21:48
I set my versions manually and got this error after I force-killed a build. I rolled the build number and it worked.
Coincidence... who knows?

**Comment by codyrotwein** [comment] 2020-08-29 16:02
I'm having the same issue. I have over 300+ apps to update and fastlane is stopping with this error after a few apps. Very frustrating.

**Comment by frontenddeveloping** [comment] 2020-09-06 05:39
Same issue

**Comment by rubenstolk** [comment] 2020-09-06 09:42
Same issue

**Comment by elmartino** [comment] 2020-09-09 09:41
Yep, same issue here

**Comment by Thangaraj-M** [comment] 2020-09-10 13:33
Getting the same issue

**Comment by mcfarljw** [comment] 2020-09-11 12:51
I'd say this happens nearly 50% of the time when trying to run the bit of code referenced below which updates the release notes and version. Even when it fails with the `Cannot update languages - could not find an editable version for 'IOS'` error App Store Connect seems to show the updated metadata and version so I'm not sure what is failing since it seems to be successful. The problem is when I run my loop to update multiple projects and it fails which causes it to stop.

```ruby
lane :update_release_notes do |options|
    appInfo = getAppInfo(options[:lang])

    upload_to_app_store(
      username: 'myemail@email.com',
      app_identifier: appInfo['id'],
      app_version: $pkgData['version'],
      build_number: $pkgData['build'],
      force: true,
      precheck_include_in_app_purchases: false,
      skip_app_version_update: false,
      skip_binary_upload: true,
      skip_metadata: false,
      skip_screenshots: true
    )
  end

lane :update_all_release_notes do
    $pkgData['cordova'].keys.each do |key|
      update_release_notes(lang: key)
    end
  end
```

**Comment by chriswilke** [comment] 2020-09-12 02:51
fastlane 2.159.0

Mine also dies ~50% of the time using this configuration.

    deliver(submit_for_review: true,
            skip_binary_upload: true,
            skip_app_version_update: false,
            skip_screenshots: "true",
            force: true,
            app_rating_config_path: "./fastlane/metadata/rating_config.json",
            metadata_path: "./fastlane/metadata/#{ENV['SCHEME']}",
            price_tier: ENV['PRICE_TIER'],
            screenshots_path: "./fastlane/screenshots/#{ENV['SCHEME']}",
            submission_information: {
              add_id_info_limits_tracking: true,
              add_id_info_tracks_install: true,
              add_id_info_uses_idfa: true,
              export_compliance_uses_encryption: false
            }
    )

**Comment by rogerluan** [comment] 2020-09-12 16:50
@joshdholtz I quickly debugged this and my guts tell me this is a race condition between "new app version creation" and "reading the app versions" - either on our end or Apple's. Hopefully it's on our end. Do you know if this line executes synchronously or async? https://github.com/rogerluan/fastlane/blame/master/spaceship/lib/spaceship/connect_api/tunes/tunes.rb#L760

A next testing step would be to create a standalone script that simply creates a new app version and then subsequently reads "latest editable app version" to see if they match. If the call above happens sync, then maybe Apple's API doesn't refresh the results when a new version is created in a timely manner. Or there's caching involved - I don't know enough about _fastlane_'s architecture to know what it does under the hood to perform those web requests.

This seems to be affecting many people, we'd all appreciate if you could take a deeper dive into this 🙏 count me in to help debugging or testing, I'll help as much as I can 💪

**Comment by ppamorim** [comment] 2020-09-14 13:50
@rogerluan Any update on this?

**Comment by rogerluan** [comment] 2020-09-14 13:55
Nope @ppamorim , I'm waiting to see if @joshdholtz can shed some light 🤞

**Comment by joshdholtz** [comment] 2020-09-14 14:02
Hello, I’m here starting my workday now! It seems like there could be a race condition. I’ve experience a few things like this before with our latest App Store Connect API migrations. I fixed it in another place but I will add in a retry loop that this morning that _hopefully_ fixes this!

I’ll work on the fix now and get a branch out for you all to try!

**Comment by rogerluan** [comment] 2020-09-14 14:22
Awesome @joshdholtz 😊 thanks for the update! Out of curiosity, though, do you know whether the line I highlighted is executed sync or async? (I have no idea how I'd check that myself, hence why I got blocked 🙈 )

**Comment by joshdholtz** [comment] 2020-09-14 14:30
@rogerluan Everything is sync but the data on the App Store Connect API backend needs some time to process (from what I’ve experienced) so that could be what is happening here.

**Comment by rogerluan** [comment] 2020-09-14 14:34
Got it! In that case, I must agree that retrying sounds like the only way to go for now, unfortunately 😅 
They added 200+ new APIs but there's still so much functionality to be added! hehe

Thanks for the clarification 💪

**Comment by joshdholtz** [comment] 2020-09-14 17:04
Hey fam! I wasn’t able to reproduce this exact case when running in my test projects but I _think_ I have a fix for this in #17235 👇 

If somebody is able to test this out and see if it works that would be ❤️ 

### Testing Steps

Update `Gemfile` and run `bundle install`, `bundle update fastlane`, or `bundle update`

```rb
gem "fastlane", :git => "https://github.com/fastlane/fastlane.git", :branch => "joshdholtz-deliver-add-retry-fetching-edit-versions"
```

**Comment by rogerluan** [comment] 2020-09-14 18:59
Guys, remember that for the fix above to be effectively tested, you must switch to the testing environment (i.e. modify Gemfile and run `bundle install`) BEFORE facing the error. Once you face the error, the next attempt will likely simply just work even if you don't switch to the testing env. So if you wait until you face the error to switch to the testing environment, the testing would be pointless.
🙏 Thanks for the fix @joshdholtz , I reviewed the PR and the logic looks good. I'll report my test results on our next release 😊

**Comment by ppamorim** [comment] 2020-09-15 09:32
@joshdholtz Feels like this is not working, take a look:

![Screenshot 2020-09-15 at 10 24 26](https://user-images.githubusercontent.com/5521682/93193096-525bc380-f73e-11ea-8cfc-6b71d8eb06dd.png)
![Screenshot 2020-09-15 at 10 25 50](https://user-images.githubusercontent.com/5521682/93193100-538cf080-f73e-11ea-8c05-798300ab7051.png)

My script to request the review is:

```ruby
desc "Send to review"
lane :review do

  submit_for_review = UI.confirm("Submit for review?")
  skip_screenshots = UI.confirm("Skip screenshots?")
  automatic_release = UI.confirm("Automatic release?")
  phased_release = UI.confirm("Phased release?")

  IDENTIFIER_ARRAY.each_with_index do |identifier, index|

    infoPlistPath = "./MyApp/#{PLIST_ARRAY[index]}.plist"
    scheme = SCHEME_ARRAY[index]

    versionNumber = get_version_number_from_xcodeproj(
      xcodeproj: "./MyApp.xcodeproj",
      target: scheme)

    buildNumber = get_build_number_from_xcodeproj(
      xcodeproj: "./MyApp.xcodeproj",
      target: scheme)

    begin
      schemeNickname = SCHEME_NICKNAME_ARRAY[index]
      deliver(
        username: "XXX@XXXX.XX",
        app_identifier: identifier,
        submit_for_review: submit_for_review,
        force: true,
        automatic_release: automatic_release,
        phased_release: phased_release,
        skip_binary_upload: true,
        skip_app_version_update: true,
        metadata_path: "./fastlane/metadata/#{schemeNickname}",
        screenshots_path: "./fastlane/screenshots/#{schemeNickname}",
        app_version: versionNumber,
        build_number: buildNumber,
        skip_screenshots: skip_screenshots,
        precheck_include_in_app_purchases: false,
        languages: ['en-US', 'en-GB'],
        submission_information: $submission_info)
    rescue => ex
      puts ex
    end
  end
end
```

**Comment by joshdholtz** [comment] 2020-09-15 15:02
@ppamorim Thanks for the feedback! It looks like you have `skip_app_version_update: true`... I think that is the reason its not create the new version for you 🤔

**Comment by ppamorim** [comment] 2020-09-15 16:06
@joshdholtz It's not clear what `skip_app_version_update` I suspect it's there to prevent the change of an already set value, should be this?

**Comment by joshdholtz** [comment] 2020-09-15 16:08
@ppamorim The [docs](http://docs.fastlane.tools/actions/deliver/#deliver) describe it as `Don't update app version for submission`. This is for when users submit only binaries with `deliver` and don’t want the version number to be updated. If you set this to `false` you should see the the versions be created or updated for you when you submit!

**Comment by joshdholtz** [comment] 2020-09-15 16:13
I think I will update the description to read as `Don’t created or update the app version that is being prepared for submission`

That reads much better 😇

**Closed** 2020-09-15 22:56 UTC
Labels: 2.150.x, tool: deliver
