### ISSUE TITLE
Couldn't find specified scheme 'myapp [Test]'

### ISSUE THREAD

**Issue by Frinkey** [fastlane/fastlane#12183] opened 2018-03-27 18:20 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When i call ```fastlane beta``` fastlane trying to build my project with scheme named ```myapp``` instead of ```myapp [Test]```. 
In my project folder I have a ```myapp.xcworkspace``` which contains ```xcshareddata/xcschemes/myapp [Test].xcscheme```.
If I create a scheme named ```myapp``` (like my target name) and edit ```gym(scheme:)``` to ```myapp``` everything works fine.
A few days ago (on past week) all works fine with current ```Fastfile```

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.3                                                        |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.14.3 (Apple Git-98)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.3 (17D102)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.2                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later

lane :beta do |options|
  # build your iOS app
  gym(
    scheme: "myapp [Test]",
    export_method: "development",
    configuration: 'Release [Test]',
    clean: true,
    output_directory: "./fastlane/build"
  )

  # upload to Beta by Crashlytics
  emails = options[:email] ? options[:email] : [ "my.contact@email.here" ]
  crashlytics(
    api_token: "api_token_here",
    build_secret: "build_secret_here",
    notes: File.read("../fastlane/changelog.md"),
    emails: emails
  )
end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.87.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.4        |
| xcodeproj                 | 1.5.7        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.14.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.1       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| io-console                | 0.4.6        |
| CFPropertyList            | 3.0.0        |
| libxml-ruby               | 3.1.0        |
| json                      | 2.1.0        |
</details>

*generated on:* **2018-03-27**
</details></pre>
</details>

**Comment by getaaron** [comment] 2018-03-27 19:48
@Frinkey We just merged https://github.com/fastlane/fastlane/pull/12182 which should improve the error message. The issue is that since https://github.com/fastlane/fastlane/pull/12027 you need to mark your scheme as 'shared' in Xcode. There are [instructions here](https://developer.apple.com/library/content/documentation/IDEs/Conceptual/xcode_guide-continuous_integration/ConfigureBots.html#//apple_ref/doc/uid/TP40013292-CH9-SW3) if you haven't done it before.

**Comment by Frinkey** [comment] 2018-03-28 06:38
Yeap its checked, but right after starting script it pints:
```
Couldn't find specified scheme 'myapp [Test]'.
[09:30:30]: $ xcodebuild -showBuildSettings -workspace ./myapp.xcworkspace -scheme myapp -configuration Release\ \[Test\]
```

![screen shot 2018-03-28 at 09 29 56](https://user-images.githubusercontent.com/2250376/38012832-9855c9b6-326b-11e8-9f61-bda77edf9b32.png)

I can't understand why its trying to use scheme that i did have configured in my project

**Comment by Frinkey** [comment] 2018-03-29 06:17
@KrauseFx what's going on here?
Issue closed but even if I create a new Single View application with Crashlytics installed by Pods and rename main scheme to something different from target name (checkbox "Shared" are checked for project/workspace - don't matter) it's not working. It's alway trying to build scheme named like target name. All my previously worked projects now can't be build with fastlane.

Maybe I need to completely delete fastlane and reinstall then?

**Comment by zilppuri** [comment] 2018-03-29 11:37
If the correct scheme is being unreachable, I believe it should definitely cancel the build instead of simply selecting the 'default' scheme. I have been accidentally building the wrong scheme & uploading to Crashlytics without even noticing. Once I noticed it took quite some digging to see those two red lines in the fastlane logs.

**Comment by Frinkey** [comment] 2018-03-30 07:40
How I can help with resolving this issue? Maybe reinstalling some tools can help or something like this?

**Closed** 2018-05-07 17:34 UTC
Labels: status: waiting-for-reply
