### ISSUE TITLE
[Regression] PEM not using existing valid certificates ultimately causing error when more than 2 certificates are to be created

### ISSUE THREAD

**Issue by haydus** [fastlane/fastlane#8046] opened 2017-01-29 14:52 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
When running PEM using an app_identifier that already has push certificates, it will create new certificates even thought there are existing ones, and they are still valid for more than 30 days.
While not exceeding 2 certs per app, it will work fine, but beyond that it fails with the following error:
You already have 2 active push profiles for this application/environment. You'll need to revoke an old certificate to make room for a new one

##### Complete output when running fastlane
Successfully loaded Appfile at path '/Projects/xxxxxx/fastlane/Appfile'
- app_identifier: 'xxxxxx'
- apple_id: 'xxxxxx'
- team_id: 'xxxxxx'
-------

+------------------+------------------------+
|          Summary for PEM 2.12.0           |
+------------------+------------------------+
| development      | false                  |
| generate_p12     | true                   |
| force            | false                  |
| save_private_key | true                   |
| app_identifier   | xxxxxx |
| username         | xxxxxx       |
| team_id          | xxxxxx             |
| output_path      | .                      |
+------------------+------------------------+

INFO [2017-01-29 16:39:35.67]: Starting login with user 'xxxxxx
INFO [2017-01-29 16:39:38.70]: Successfully logged in
WARN [2017-01-29 16:39:43.45]: Creating a new push certificate for app 'xxxxxx'.
INFO [2017-01-29 16:39:56.11]: {"responseId"=>"88c4842c-d640-4045-8fb3-26fb0f504575", "resultCode"=>7460, "resultString"=>"You already have a current Apple Push Services certificate or a pending certificate request.", "userString"=>"You already have a current Apple Push Services certificate or a pending certificate request.", "creationTimestamp"=>"2017-01-29T14:39:59Z", "protocolVersion"=>"QH65B2", "userLocale"=>"en_US", "requestUrl"=>"https://developer.apple.com/services-account/QH65B2/account/ios/certificate/submitCertificateRequest.action", "httpCode"=>200}
/Users/shahar/.rvm/gems/ruby-2.3.3/gems/fastlane-2.12.0/fastlane_core/lib/fastlane_core/ui/interface.rb:145:in `user_error!': [!] You already have 2 active push profiles for this application/environment. You'll need to revoke an old certificate to make room for a new one (FastlaneCore::Interface::FastlaneError)
	from /Users/shahar/.rvm/gems/ruby-2.3.3/gems/fastlane-2.12.0/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/shahar/.rvm/gems/ruby-2.3.3/gems/fastlane-2.12.0/pem/lib/pem/manager.rb:51:in `rescue in create_certificate'
	from /Users/shahar/.rvm/gems/ruby-2.3.3/gems/fastlane-2.12.0/pem/lib/pem/manager.rb:45:in `create_certificate'
	from /Users/shahar/.rvm/gems/ruby-2.3.3/gems/fastlane-2.12.0/pem/lib/pem/manager.rb:30:in `start'
	from /Users/shahar/.rvm/gems/ruby-2.3.3/gems/fastlane-2.12.0/pem/lib/pem/commands_generator.rb:33:in `block (2 levels) in run'
	from /Users/shahar/.rvm/gems/ruby-2.3.3/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Users/shahar/.rvm/gems/ruby-2.3.3/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /Users/shahar/.rvm/gems/ruby-2.3.3/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /Users/shahar/.rvm/gems/ruby-2.3.3/gems/fastlane-2.12.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/shahar/.rvm/gems/ruby-2.3.3/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /Users/shahar/.rvm/gems/ruby-2.3.3/gems/fastlane-2.12.0/pem/lib/pem/commands_generator.rb:39:in `run'
	from /Users/shahar/.rvm/gems/ruby-2.3.3/gems/fastlane-2.12.0/pem/lib/pem/commands_generator.rb:11:in `start'
	from /Users/shahar/.rvm/gems/ruby-2.3.3/gems/fastlane-2.12.0/fastlane/lib/fastlane/cli_tools_distributor.rb:45:in `take_off'
	from /Users/shahar/.rvm/gems/ruby-2.3.3/gems/fastlane-2.12.0/bin/fastlane:15:in `<top (required)>'
	from /Users/shahar/.rvm/gems/ruby-2.3.3/bin/fastlane:22:in `load'
	from /Users/shahar/.rvm/gems/ruby-2.3.3/bin/fastlane:22:in `<main>'
	from /Users/shahar/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/shahar/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'

### Environment
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.3                                     |
| Ruby                | 2.3.3                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.rvm/gems/ruby-2.3.3/bin/fastlane         |
| Host                | Mac OS X 10.12.3 (16D32)                    |
| Ruby Lib Dir        | ~/.rvm/rubies/ruby-2.3.3/lib                |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
#update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.37.0"



before_all do
	#update_fastlane
end

lane :splash do
	snapshot
end

lane :release  do |options|

#	cert

	produce(
  		username: 'xxxxxx',
  		app_identifier: 'xxxxxx',
		app_name: 'xxxxxx',
		language: 'English',
		app_version: 'xxxxxx',
		sku: 'xxxxxx',
		company_name: 'xxxxxx'
	)

	# push notification profile    
	pem
      
	# build appstore & deliver
#	sigh(skip_install: true)
	match(type: "appstore")
	gym(scheme: "xxxxxx", output_name: "xxxxxx", configuration: "Release");
	deliver(edit_live: false)

end

lane :archive  do |options|

#	cert

	# push notification profile    
	pem
      
	# provisioning profile
#	sigh(adhoc: true, skip_install: true)
	match(type: "adhoc")
    
	gym(scheme: "xxxxxx", output_name: "xxxxxx", configuration: "Release");

end

lane :archive_admin  do |options|

#	cert

	# push notification profile    
	pem
      
	# provisioning profile
#	sigh(adhoc: true, skip_install: true)
	match(type: "adhoc", force_for_new_devices: true)
    
	gym(scheme: "xxxxxx", output_name: "xxxxxx", configuration: "Release");

end

#after_all do |lane|
  #clean_build_artifacts
#  say "Successfully finished (#{lane})!"
#end

#error do |lane, exception|
#  say "error line #{line} exception #{exception}"
#end


# More information about multiple platforms in fastlane: 
# https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "xxxxxx"
apple_id "xxxxxx" # Your Apple email address

team_id "xxxxxx"

# You can uncomment any of the lines below and add your own
# team selection in case you're in multiple teams
# team_name "Felix Krause"
# team_id "Q2CBPJ58CA"


# you can even provide different app identifiers, Apple IDs and team names per lane:
# https://github.com/KrauseFx/fastlane/blob/master/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.12.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.13.7       |
| io-console                | 0.4.5        |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.8.5        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| faraday_middleware        | 0.10.1       |
</details>

*generated on:* **2017-01-29**
</details>

**Comment by KrauseFx** [comment] 2017-01-30 02:47
Does the user you're running fastlane with have access to the push certificates? Look like it would be useful if fastlane would show some debugging information on why it didn't use certain certificates.

**Comment by sainttail** [comment] 2017-01-30 04:59
I also have this kind of problem so running a check for [this line](https://github.com/fastlane/fastlane/blob/master/pem/lib/pem/manager.rb#L13) I got

so checking `c.name == PEM.config[:app_identifier]` is wrong here should change to 
`c.owner_name == PEM.config[:app_identifier]`

It'd worked before so maybe Apple change something?

```
<Spaceship::Portal::Certificate::VoipPush
	id="D94U79F946",
	name="VoIP Services",
	status="Issued",
	created=2016-11-25 10:49:05 UTC,
	expires=2017-11-25 10:39:05 UTC,
	owner_type="bundle",
	owner_name="com.ekoenterprise.devteam",
	owner_id="L8BH4DZ2AV",
	type_display_id="E5D663CMZW",
	can_download=true>
```

**Comment by KrauseFx** [comment] 2017-01-30 05:11
I was able to reproduce the issue and already working on a fix 👍 Thanks for reporting this

**Comment by KrauseFx** [comment] 2017-01-30 05:22
This will be in the next release, which will be out ASAP 🚀 Thanks everyone for your help! 👍

**Comment by KrauseFx** [comment] 2017-01-30 05:22
You can take a look at the fix here: https://github.com/fastlane/fastlane/pull/8049

**Comment by haydus** [comment] 2017-01-30 16:34
Thanks for the super fast fix!!!
When is the fix expected to be released?

**Closed** 2017-01-30 17:22 UTC

**Comment by KrauseFx** [comment] 2017-01-30 17:27
The new release is live 🚀 https://twitter.com/FastlaneTools/status/826119455017021444 Sorry it took so long

**Comment by tskulbru** [comment] 2017-02-08 13:21
@KrauseFx Im still experiencing this issue. I ran PEM once together with some other stuff for my production lane, which then had an error in it so I had to run the lane again. This time it also tried to generate a new certificate, even though PEM had just recently created a new certificate for me. (Im not using force), using fastlane version 2.14.2.

So ran lane, got a new certificate since it was expiring (correct).
Had to run lane again, and yet again PEM created a new certificate for me. Inevitably it crashed at the PEM step since it had filled up the account with certificates.

**Comment by KrauseFx** [comment] 2017-02-08 18:06
@tsafrir did this exact setup work for you before?

**Comment by tskulbru** [comment] 2017-02-08 18:45
@KrauseFx Just in case you just misspelled my username, yes it did work for me in the past. It would check if a new certificate was needed, and if so create one. the next run it would just validate that its still valid and go about its business. As far as I know, exactly how the PEM flow is intended to be?

**Comment by tsafrir** [comment] 2017-02-08 21:44
@KrauseFx Even if it was a misspelled, then I'm lucky to find this discussion as since I just started to look at this issue myself.

I currently have few similar cases. 
Looking at the code, @tskulbru is right, PEM is checking only the first certificate it detects (`certificate.all.detect`).
So probably for anyone who used PEM after Apple change in the API and before #8049, it will have a 2nd certificate.
Running the latest PEM won't create a 2nd certificate, but will try if you already have two.

**Comment by dfujiwara** [comment] 2017-04-23 06:24
@KrauseFx and/or @tsafrir, I am also running into this issue where PEM thinks I need to create a new certificate even if one of the registered certificates are valid.

`[!] You already have 2 active push profiles for this application/environment. You'll need to revoke an old certificate to make room for a new one`

Looking at the code in pem/lib/pem/manager.rb, it seems like we can check more than the first certificate it detects for the expiration date. Not too familiar with the code, but I am happy to make the change unless I am missing something obvious here.  

Let me know what you guys think. I am running fastlane 2.27.

**Comment by tsafrir** [comment] 2017-04-24 09:45
@dfujiwara I think it will be a great fix.
