### ISSUE TITLE
"Deliver" always uploads screenshots even if not changed.

### ISSUE THREAD

**Issue by kashif789us** [fastlane/fastlane#5242] opened 2016-06-28 07:11 UTC
I just downloaded fastlane deliver and is using it for the first time. One thing I have noticed is that even If I do not change the screenshot which was downloaded from iTunesConnect, deliver re uploads it again. So if I have 600 screenshots and I change only 10 locally, only 10 should re upload not the entire 600. Thank you

**Comment by KrauseFx** [comment] 2016-06-28 09:18
Agreed, basically a duplicate of https://github.com/fastlane/fastlane/pull/3755, we haven't had time to work on this, however feel free to take over https://github.com/fastlane/fastlane/pull/3755 and take it a stab 👍

**Closed by KrauseFx** 2016-06-28 09:18 UTC
