### ISSUE TITLE
Exit status: 65

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1926] opened 2016-03-01 14:50 UTC
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/603144?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @tspecht - Imported from <a href='https://github.com/fastlane/scan/issues/102'>fastlane/scan#102</a>
        </td>
      </tr>
    </table>

Hi guys,

I'm still trying to run scan and, all of a sudden, the Segmentation Fault 11 magically disappeared. Instead now I'm having a different issue:

```
scan(
      workspace: "MyApp.xcworkspace",
      scheme: "MyAppTests",
      device: "iPhone 6s",
      clean: true,
      code_coverage:true
    )
```

```
▸ Running script 'Copy Pods Resources'
▸ Running script 'Embed Pods Frameworks'
▸ Touching MyAppTests.xctest
** TEST FAILED **
ERROR [2016-03-01 15:46:39.65]: Exit status: 65
WARN [2016-03-01 15:46:39.66]: Variable Dump:
INFO [2016-03-01 15:46:39.66]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios test"}
ERROR [2016-03-01 15:46:39.66]: Error building/testing the application - see the log above
```

In Xcode I can run the tests just fine including code coverage being generated. Any hints?

**Comment by tspecht** [comment] 2016-03-14 11:17
Any news on this?

**Comment by asfalcone** [comment] 2016-03-22 20:26
@tspecht What version of xcode are you using?

**Comment by krodak** [comment] 2016-03-25 09:51
Have same issue after switching to XCode 7.3

**Comment by tspecht** [comment] 2016-03-25 09:52
Had Xcode 7.2 but also happening with 7.3

**Comment by Gladkov-Art** [comment] 2016-03-28 12:31
I have "Exit status: 65" too. But my tests run correctly and results html/junits are generated. But the lane can't e finished due to this sudden exit.
The results of running my lane with `--verbose` : 

```
/Users/artemgladkov/.rvm/gems/ruby-2.2.3/gems/fastlane_core-0.37.0/lib/fastlane_core/ui/interface.rb:132:in `user_error!': [!] Test execution failed. Exit status: 65 (FastlaneCore::Interface::FastlaneError)
	from /Users/artemgladkov/.rvm/gems/ruby-2.2.3/gems/fastlane_core-0.37.0/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/artemgladkov/.rvm/gems/ruby-2.2.3/gems/scan-0.5.2/lib/scan/runner.rb:71:in `handle_results'
	from /Users/artemgladkov/.rvm/gems/ruby-2.2.3/gems/scan-0.5.2/lib/scan/runner.rb:9:in `run'
	from /Users/artemgladkov/.rvm/gems/ruby-2.2.3/gems/scan-0.5.2/lib/scan/manager.rb:10:in `work'
	from /Users/artemgladkov/.rvm/gems/ruby-2.2.3/gems/fastlane-1.66.0/lib/fastlane/actions/scan.rb:10:in `run'
	from /Users/artemgladkov/.rvm/gems/ruby-2.2.3/gems/fastlane-1.66.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Users/artemgladkov/.rvm/gems/ruby-2.2.3/gems/fastlane-1.66.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Users/artemgladkov/.rvm/gems/ruby-2.2.3/gems/fastlane-1.66.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Users/artemgladkov/.rvm/gems/ruby-2.2.3/gems/fastlane-1.66.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Users/artemgladkov/.rvm/gems/ruby-2.2.3/gems/fastlane-1.66.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Users/artemgladkov/.rvm/gems/ruby-2.2.3/gems/fastlane-1.66.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from TestLanes:7:in `block (2 levels) in parsing_binding'
	from /Users/artemgladkov/.rvm/gems/ruby-2.2.3/gems/fastlane-1.66.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/artemgladkov/.rvm/gems/ruby-2.2.3/gems/fastlane-1.66.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/artemgladkov/.rvm/gems/ruby-2.2.3/gems/fastlane-1.66.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Users/artemgladkov/.rvm/gems/ruby-2.2.3/gems/fastlane-1.66.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Users/artemgladkov/.rvm/gems/ruby-2.2.3/gems/fastlane-1.66.0/lib/fastlane/runner.rb:46:in `execute'
	from /Users/artemgladkov/.rvm/gems/ruby-2.2.3/gems/fastlane-1.66.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Users/artemgladkov/.rvm/gems/ruby-2.2.3/gems/fastlane-1.66.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/artemgladkov/.rvm/gems/ruby-2.2.3/gems/fastlane-1.66.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Users/artemgladkov/.rvm/gems/ruby-2.2.3/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/artemgladkov/.rvm/gems/ruby-2.2.3/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/artemgladkov/.rvm/gems/ruby-2.2.3/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/artemgladkov/.rvm/gems/ruby-2.2.3/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/artemgladkov/.rvm/gems/ruby-2.2.3/gems/fastlane_core-0.37.0/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Users/artemgladkov/.rvm/gems/ruby-2.2.3/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/artemgladkov/.rvm/gems/ruby-2.2.3/gems/fastlane-1.66.0/bin/fastlane:156:in `run'
	from /Users/artemgladkov/.rvm/gems/ruby-2.2.3/gems/fastlane-1.66.0/bin/fastlane:162:in `<top (required)>'
	from /Users/artemgladkov/.rvm/gems/ruby-2.2.3/bin/fastlane:23:in `load'
	from /Users/artemgladkov/.rvm/gems/ruby-2.2.3/bin/fastlane:23:in `<main>'
	from /Users/artemgladkov/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/artemgladkov/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by i2amsam** [comment] 2016-03-28 20:15
I think there may be different underlying issues in this,  for folks who are seeing this with XCode 7.3 I suspect this is a duplicate of https://github.com/fastlane/fastlane/issues/3886 and I'll be updating over there.

**Comment by TKBurner** [comment] 2016-03-28 20:33
@Gladkov-Art We are going to track this on #3886. Can you follow there? I'm going to close this ticket out, but we'll keep working with you over there! :+1: Thanks

**Closed by TKBurner** 2016-03-28 20:33 UTC
Labels: bug, scan
