### ISSUE TITLE
[Regression] Google Api Error: apkNotificationMessageKeyUpgradeVersionConflict leaves hanging edit for subsequent runs

### ISSUE THREAD

**Issue by amccaleb** [fastlane/fastlane#15646] opened 2019-11-13 21:47 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Running `fastlane supply` after a failed run due to trying to upload a new APK with an already taken version code will fail subsequent runs because an `Edit` is already in progress.

##### Command executed

Portion of fastlane job run over multiple iterations
```
    upload_to_play_store(
      package_name: package_to_upload, 
      track: internal,
      metadata_path: path_to_metadata,
      apk: apk_path,
      skip_upload_aab: true,
      skip_upload_images: false,
      skip_upload_screenshots: false,
      validate_only: true)
```

##### Steps to Reproduce

<details>
<pre>
1.  With an existing Google Play app entry and uploaded APK, run the above command, providing an APK with the same version code as what's already in Google Play.
2. Observe the following Google API Error:
```[!] Google Api Error: apkNotificationMessageKeyUpgradeVersionConflict: APK specifies a version code that has already been used. - APK specifies a version code that has already been used.```
3. Increment the version code of the APK to something not already taken
4. Run the same command with the new APK and observe the following error, trigger on [this line](https://github.com/fastlane/fastlane/blob/master/supply/lib/supply/client.rb#L136)
```[!] You currently have an active edit```
</pre>
</details>

### Possible fix
Abort the pending edit left over by the run that threw the Google API Error. Calling [this](https://github.com/fastlane/fastlane/blob/master/supply/lib/supply/client.rb#L144) in the right places.

### Environment

<details>
<pre>
### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.1                                     |
| Ruby                        | 2.6.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.21.0 (Apple Git-122.2)        |
| Installation Source         | ~/.rbenv/versions/2.6.1/bin/fastlane        |
| Host                        | Mac OS X 10.15.1 (19B88)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.1/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2r  26 Feb 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.2                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   | 

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.135.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                      | Version | Update-Status |
| ------------------------------------------- | ------- | ------------- |
| fastlane-plugin-automated_test_emulator_run | 1.6.0   | ✅ Up-To-Date  |
| fastlane-plugin-versioning_android          | 0.1.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                         | Version      |
| ------------------------------------------- | ------------ |
| did_you_mean                                | 1.3.0        |
| bundler                                     | 2.0.1        |
| etc                                         | 1.0.1        |
| CFPropertyList                              | 3.0.1        |
| public_suffix                               | 2.0.5        |
| addressable                                 | 2.7.0        |
| atomos                                      | 0.1.3        |
| babosa                                      | 1.0.3        |
| claide                                      | 1.0.3        |
| colored                                     | 1.2          |
| colored2                                    | 3.1.2        |
| highline                                    | 1.7.10       |
| commander-fastlane                          | 4.4.6        |
| declarative                                 | 0.0.10       |
| declarative-option                          | 0.1.0        |
| digest-crc                                  | 0.4.1        |
| unf_ext                                     | 0.0.7.6      |
| unf                                         | 0.1.4        |
| domain_name                                 | 0.5.20190701 |
| dotenv                                      | 2.7.5        |
| emoji_regex                                 | 1.0.1        |
| excon                                       | 0.68.0       |
| multipart-post                              | 2.0.0        |
| faraday                                     | 0.17.0       |
| http-cookie                                 | 1.0.3        |
| faraday-cookie_jar                          | 0.0.6        |
| faraday_middleware                          | 0.13.1       |
| fastimage                                   | 2.1.7        |
| gh_inspector                                | 1.1.3        |
| jwt                                         | 2.1.0        |
| memoist                                     | 0.16.1       |
| multi_json                                  | 1.14.1       |
| os                                          | 1.0.1        |
| signet                                      | 0.12.0       |
| googleauth                                  | 0.6.7        |
| httpclient                                  | 2.8.3        |
| mime-types-data                             | 3.2019.1009  |
| mime-types                                  | 3.3          |
| uber                                        | 0.1.0        |
| representable                               | 3.0.4        |
| retriable                                   | 3.1.2        |
| google-api-client                           | 0.23.9       |
| google-cloud-env                            | 1.3.0        |
| google-cloud-core                           | 1.4.1        |
| google-cloud-storage                        | 1.16.0       |
| json                                        | 2.2.0        |
| mini_magick                                 | 4.9.5        |
| multi_xml                                   | 0.6.0        |
| plist                                       | 3.5.0        |
| rubyzip                                     | 1.3.0        |
| security                                    | 0.1.3        |
| naturally                                   | 2.2.0        |
| simctl                                      | 1.6.6        |
| slack-notifier                              | 2.3.2        |
| terminal-notifier                           | 2.0.0        |
| unicode-display_width                       | 1.6.0        |
| terminal-table                              | 1.8.0        |
| tty-screen                                  | 0.7.0        |
| tty-cursor                                  | 0.7.0        |
| tty-spinner                                 | 0.9.1        |
| word_wrap                                   | 1.0.0        |
| nanaimo                                     | 0.2.6        |
| xcodeproj                                   | 1.13.0       |
| rouge                                       | 2.0.7        |
| xcpretty                                    | 0.3.0        |
| xcpretty-travis-formatter                   | 1.0.0        |
| fastlane-plugin-automated_test_emulator_run | 1.6.0        |
| fastlane-plugin-versioning_android          | 0.1.0        |

</pre>
</details>

**Comment by joshdholtz** [comment] 2019-11-13 22:10
@amccaleb Thanks for the report! I will look into right away

**Comment by joshdholtz** [comment] 2019-11-14 00:02
@amccaleb I'm not able to reproduce this at all 😔 I've tried calling uploading a duplicate version and then bumping the version and uploading a second one both between new _fastlane_ sessions and in the same _fastlane_ sessions and I'm not able to get this edit error 🤔

**Comment by amccaleb** [comment] 2019-11-14 01:54
Hmm... so which part isn’t reproducing as described? The Google API error, or the “You already have an active edit” error.

What happens if Timed publishing is turned on in Google Play?

**Comment by joshdholtz** [comment] 2019-11-14 14:39
Correct! The "You already have an active edit" isn't happening on my end. It seems the current edit is being closed for me. 

Ahh, I had no idea "Timed publishing" was a thing 😇 I will give that shot and report back 👌

**Comment by weraaaaz** [comment] 2019-11-14 16:32
I have the same error using 2.125.2 version

**Comment by joshdholtz** [comment] 2019-11-14 17:23
@weraaaaz Is your app also set to "Timed publishing"?

**Comment by amccaleb** [comment] 2019-11-15 01:03
Updated the issue report with the `track` as well as skip flags and validate_only flags being used. @weraaaaz is that similar to your configuration?

**Comment by amccaleb** [comment] 2019-11-15 01:22
Tried working around it by rolling back to 2.134.0 and running again. Was able to run on 2.134.0, but then going back to 2.135.2 failed the same way.

**Comment by emarc-m** [comment] 2019-11-16 01:12
Hi @amccaleb, if you have `Timed publishing` disabled does this error still occur? I have it disabled and I'm getting the same error.

**Comment by amccaleb** [comment] 2019-11-16 01:50
@emarc-m We have fastlane set up to deploy multiple apps starting from a single lane. Some of those have timed published enabled while others don't. The first one in the list which throws the error happens to have Timed Publishing disabled.

Related, I'm still able to repro the issue on 2.136.0.

**Comment by amccaleb** [comment] 2019-11-16 01:53
Random though that I haven't tried out yet. I noticed the file names for screenshots changed between AndroidpublisherV2 and AndroidPublisherV3. When this job runs, it's now trying to upload the same screenshots from before under a different file name. 

Maybe related?

**Comment by emarc-m** [comment] 2019-11-16 20:04
@amccaleb I understand. Thanks for confirming. I'm running into the same issue. 

My project is using `supply` to upload apk splits. For sample supply input please see: https://github.com/fastlane/fastlane/issues/15645#issuecomment-554668957. In our case, we do not use supply to upload screenshots. For what I know we are uploading the split apks and mapping files.

**Comment by amccaleb** [comment] 2019-11-19 21:17
@joshdholtz, @janpio, The more I thumb around the code, the more I think this is actually just an issue with the `validate_only: true` flag.

In `client.rb`, I see this code snippet:
` 
    # Validates the current edit - does not change data on Google Play
    def validate_current_edit!
      ensure_active_edit!

      call_google_api { client.validate_edit(current_package_name, current_edit.id) }
    end

    # Commits the current edit saving all pending changes on Google Play
    def commit_current_edit!
      ensure_active_edit!

      call_google_api { client.commit_edit(current_package_name, current_edit.id) }

      self.current_edit = nil
      self.current_package_name = nil
    end
`

Looking at the last bit of logs when the error happens,
`
[12:56:26]: Validating all track and release changes with Google Play...
[12:56:28]: Successfully validated the upload to Google Play
...
[12:56:28]: You currently have an active edit
`
leads to this chunk of code in `uploader.rb`
`
    def perform_upload
      # ...
      if Supply.config[:validate_only]
        UI.message("Validating all track and release changes with Google Play...")
        client.validate_current_edit!
        UI.success("Successfully validated the upload to Google Play")
      else
        UI.message("Uploading all track and release changes to Google Play...")
        client.commit_current_edit!
        UI.success("Successfully finished the upload to Google Play")
      end

      perform_upload_meta(apk_version_codes)
    end

    def perform_upload_meta(version_codes)
      client.begin_edit(package_name: Supply.config[:package_name])
      # ...
`

And the first line of `begin_edit` in `client.rb` is where the active edit error is thrown:
`
    def begin_edit(package_name: nil)
      UI.user_error!("You currently have an active edit") if @current_edit
      # ....
`

Seeing how the `commit` path works, would it be safe to assume that the validate path should remove the edit once validated, e.g. `client.rb` now has:
` 
    # Validates the current edit - does not change data on Google Play
    def validate_current_edit!
      ensure_active_edit!

      call_google_api { client.validate_edit(current_package_name, current_edit.id) }

      self.current_edit = nil
      self.current_package_name = nil
    end
`

@weraaaaz, @emarc-m does this seems similar to your use cases?

**Comment by emarc-m** [comment] 2019-11-19 22:06
@amccaleb I think it is similar based on the logs. Please see:

```
[14:01:13]: Updating track 'production'...
[14:01:14]: Validating all track and release changes with Google Play...
[14:01:15]: Successfully validated the upload to Google Play
[14:01:15]: Wrote distribution report to REDACTED.
[14:01:15]: {
  "build": {
    "display_name": "REDACTED",
    "distribution_platform_pretty_name": "Google Play",
    "build_info": {
      "pr_number": null,
      "date": "2019-11-19 13:57:36 -0800",
      "build": null
    }
  },
  "error": "You currently have an active edit"
}
```

**Comment by niccokunzmann** [comment] 2019-11-20 14:53
I also ran into this issue and it is reproducible - each time I start the [Travis build](https://travis-ci.org/niccokunzmann/mundraub-android/jobs/611078966#L2163), I get the same error. I run it for the beta track with these parameters:

```
--validate_only true
--skip_upload_images true 
--skip_upload_screenshots true 
--skip_upload_apk true 
--skip_upload_aab true
```

Mentioned by [amccaleb](https://github.com/fastlane/fastlane/issues/15646#issuecomment-555718971), I am suspicious why fastlane would create a commit if it only validates, *after* the validation is successful.

```
[14:40:37]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile

[14:40:37]: Sending anonymous analytics information

[14:40:37]: Learn more at https://docs.fastlane.tools/#metrics

[14:40:37]: No personal or sensitive data is sent.

[14:40:37]: You can disable this by adding `opt_out_usage` at the top of your Fastfile

+-------------------------+------------------------------------------+

|                     Summary for supply 2.136.0                     |

+-------------------------+------------------------------------------+

| track                   | beta                                     |

| apk                     | apks/fruit-radar-google-play-release.apk |

| metadata_path           | /tmp/fruit-radar-metadata                |

| validate_only           | true                                     |

| skip_upload_images      | true                                     |

| skip_upload_screenshots | true                                     |

| skip_upload_apk         | true                                     |

| skip_upload_aab         | true                                     |

| package_name            | eu.quelltext.mundraub                    |

| release_status          | completed                                |

| json_key                | .travis/api.json                         |

| skip_upload_metadata    | false                                    |

| skip_upload_changelogs  | false                                    |

| check_superseded_tracks | false                                    |

| timeout                 | 300                                      |

| deactivate_on_promote   | true                                     |

+-------------------------+------------------------------------------+

[14:40:39]: Validating all track and release changes with Google Play...

[14:40:41]: Successfully validated the upload to Google Play

[!] You currently have an active edit
```

**Comment by joshdholtz** [comment] 2019-11-20 21:46
Ahhhh, this does appear that it could be an issue with validate! I will look into. Thanks to everyone for helping with this ❤️

**Comment by joshdholtz** [comment] 2019-11-20 22:00
OHHHHH... We good now. Got a fix and this will be released in the next version most likely tomorrow 😊 Thanks for all the help and patience ❤️

**Closed** 2019-11-21 15:37 UTC
Labels: status: regression, tool: supply

**Comment by niccokunzmann** [comment] 2019-11-27 10:30
I can confirm this error does not appear any more.

+-------------------------+------------------------------------------+

| Summary for supply 2.137.0|

+-------------------------+------------------------------------------+

| track | beta |

| apk | apks/fruit-radar-google-play-release.apk |

| metadata_path | /tmp/fruit-radar-metadata |

| validate_only | true |

| skip_upload_images | true |

| skip_upload_screenshots | true |

| skip_upload_apk | true |

| skip_upload_aab | true |

| package_name | eu.quelltext.mundraub |

| release_status | completed |

| json_key | .travis/api.json |

| skip_upload_metadata | false |

| skip_upload_changelogs | false |

| check_superseded_tracks | false |

| timeout | 300 |

| deactivate_on_promote | true |

+-------------------------+------------------------------------------+

[!] More than one release found in this track. Please specify with the
:version_code option to select a release.


Now, I can work on another error.
