### ISSUE TITLE
Fetch App Status from Google Play Store

### ISSUE THREAD

**Issue by rockmobile** [fastlane/fastlane#14221] opened 2019-02-11 19:37 UTC
### Question Checklist
* [x]  Updated fastlane to the latest version
* [x]  I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
* [x]  I read [docs.fastlane.tools](https://docs.fastlane.tools)
* [x]  I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Get app status from Google PlayStore (similar to Spaceship)

#### Question Description
Is there something similar to "Spaceship" for Google PlayStore to get app status and rollout percentage?

**Comment by joshdholtz** [comment] 2019-02-12 02:29
@rockmobile This is a duplicate of #12974 which was already answered that this is not available for us to get so going to close even though we would like this feature as well 😉

**Closed by joshdholtz** 2019-02-12 02:29 UTC
