### ISSUE TITLE
notarize: handle lag on Apple server

### ISSUE THREAD

**Issue by odrobnik** [fastlane/fastlane#16770] opened 2020-07-06 18:01 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Querying the request UUID, right after a package has been uploaded to notarization, might fail.

Looking for the error message I found [another tool's solution](https://github.com/electron/electron-notarize/issues/2) was to add 2 seconds delay. I think there should be a grace period, say 1 minute, during which a not found message could be ignored. Because there WAS a `Successfully uploaded package to notarization service with request identifier XXX` - so the UUID must exist eventually.

##### Command executed

```
  notarize(
      package: app_path,
      bundle_id: bundle_id,
      asc_provider: "XXX",
      print_log: true,
      verbose: true
    )
```

##### Complete output when running fastlane, including the stack trace and command used

```
[18:51:21]: Successfully uploaded package to notarization service with request identifier 9279d543-f899-4238-95bf-c73f4ad79fd0
417 [18:51:21]: Waiting to query request status
418 [18:51:51]: Querying request status
419 [18:51:51]: $ xcrun altool --notarization-info 9279d543-f899-4238-95bf-c73f4ad79fd0 -u oliver@drobnik.com -p @env:FL_NOTARIZE_PASSWORD --output-format xml
420 [18:51:53]: ▸ <?xml version="1.0" encoding="UTF-8"?>
421 [18:51:53]: ▸ <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
422 [18:51:53]: ▸ <plist version="1.0">
423 [18:51:53]: ▸ <dict>
424 [18:51:53]: ▸ <key>os-version</key>
425 [18:51:53]: ▸ <string>10.15.5</string>
426 [18:51:53]: ▸ <key>product-errors</key>
427 [18:51:53]: ▸ <array>
428 [18:51:53]: ▸ <dict>
429 [18:51:53]: ▸ <key>code</key>
430 [18:51:53]: ▸ <integer>1519</integer>
431 [18:51:53]: ▸ <key>message</key>
432 [18:51:53]: ▸ <string>Could not find the RequestUUID.</string>
433 [18:51:53]: ▸ <key>userInfo</key>
434 [18:51:53]: ▸ <dict>
435 [18:51:53]: ▸ <key>NSLocalizedDescription</key>
436 [18:51:53]: ▸ <string>Could not find the RequestUUID.</string>
437 [18:51:53]: ▸ <key>NSLocalizedFailureReason</key>
438 [18:51:53]: ▸ <string>Apple Services operation failed.</string>
439 [18:51:53]: ▸ <key>NSLocalizedRecoverySuggestion</key>
440 [18:51:53]: ▸ <string>Could not find the RequestUUID.</string>
441 [18:51:53]: ▸ </dict>
442 [18:51:53]: ▸ </dict>
443 [18:51:53]: ▸ </array>
444 [18:51:53]: ▸ <key>tool-path</key>
445 [18:51:53]: ▸ <string>/Applications/Xcode.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/Versions/A/Frameworks/AppStoreService.framework</string>
446 [18:51:53]: ▸ <key>tool-version</key>
447 [18:51:53]: ▸ <string>4.01.1182</string>
448 [18:51:53]: ▸ </dict>
449 [18:51:53]: ▸ </plist>
450 +-----------------------------------+---------------------------------------------------------------------------------------------------+
451 |                                                             Lane Context                                                              |
452 +-----------------------------------+---------------------------------------------------------------------------------------------------+
453 | ENVIRONMENT                       | Imagineer                                                                                         |
454 | DEFAULT_PLATFORM                  | mac                                                                                               |
455 | PLATFORM_NAME                     | mac                                                                                               |
456 | LANE_NAME                         | mac deploy                                                                                        |
457 | XCODEBUILD_ARCHIVE                | /Users/oliver/Library/Developer/Xcode/Archives/2020-07-06/Imagineer 2020-07-06 18.49.37.xcarchive |
458 | VERSION_NUMBER                    | 1.3.0                                                                                             |
459 | GET_INFO_PLIST_VALUE_CUSTOM_VALUE | 842                                                                                               |
460 +-----------------------------------+---------------------------------------------------------------------------------------------------+
461 [18:51:53]: Exit status of command 'xcrun altool --notarization-info 9279d543-f899-4238-95bf-c73f4ad79fd0 -u oliver@drobnik.com -p @env:FL_NOTARIZE_PASSWORD --output-format xml' was 1 instead of 0.
462 <?xml version="1.0" encoding="UTF-8"?>
463 <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
464 <plist version="1.0">
465 <dict>
466 	<key>os-version</key>
467 	<string>10.15.5</string>
468 	<key>product-errors</key>
469 	<array>
470 		<dict>
471 			<key>code</key>
472 			<integer>1519</integer>
473 			<key>message</key>
474 			<string>Could not find the RequestUUID.</string>
475 			<key>userInfo</key>
476 			<dict>
477 				<key>NSLocalizedDescription</key>
478 				<string>Could not find the RequestUUID.</string>
479 				<key>NSLocalizedFailureReason</key>
480 				<string>Apple Services operation failed.</string>
481 				<key>NSLocalizedRecoverySuggestion</key>
482 				<string>Could not find the RequestUUID.</string>
483 			</dict>
484 		</dict>
485 	</array>
486 	<key>tool-path</key>
487 	<string>/Applications/Xcode.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/Versions/A/Frameworks/AppStoreService.framework</string>
488 	<key>tool-version</key>
489 	<string>4.01.1182</string>
490 </dict>
491 </plist>
492 +------+----------------------+-------------+
493 |             fastlane summary              |
494 +------+----------------------+-------------+
495 | Step | Action               | Time (in s) |
496 +------+----------------------+-------------+
497 | 1    | default_platform     | 0           |
498 | 2    | gym                  | 81          |
499 | 3    | get_version_number   | 0           |
500 | 4    | get_info_plist_value | 0           |
501 | 💥   | notarize             | 56          |
502 +------+----------------------+-------------+
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.5                                     |
| Ruby                        | 2.6.5                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.24.3 (Apple Git-128)          |
| Installation Source         | /usr/local/lib/ruby/gems/2.6.0/bin/fastlane |
| Host                        | Mac OS X 10.15.5 (19F101)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.6.5/lib            |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.5                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | de_AT.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

fastlane_require 'kramdown'
fastlane_require 'net/scp'

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:mac)

platform :mac do
  desc "Create HTML version release notes"
  lane :releasenotes do
    
    changelog_path = Dir.glob("../CHANGELOG.md").first
    text = File.read(changelog_path)
    html = Kramdown::Document.new(text).to_html
    
    File.write('../build/releasenotes.html', html)
  end


  desc "Deploys a version of the app"
  lane :deploy do
    
    scheme = ENV["SCHEME"]
    bundle_id = ENV["APP_ID"]
    target = scheme
    
    build_path = "../build/" + bundle_id
    build_path = File.absolute_path(build_path)
    
    gym(
      scheme: scheme,
      configuration: "Release",
      export_method: "developer-id",
      export_team_id: "PBLMVZA83F",
      output_directory: build_path,
      skip_package_pkg: true
      )
      
    app_path = Dir.glob(build_path + "/*.app").first
    app_path = File.absolute_path(app_path)

    info_path = app_path + "/Contents/Info.plist"

    version = get_version_number(target: target)
    puts("Version is '" + version + "'")

    bundleVersion = get_info_plist_value(path: info_path, key: "CFBundleVersion")
    puts("Build Number is '" + bundleVersion + "'")
    
    notarize(
      package: app_path,
      bundle_id: bundle_id,
      asc_provider: "InternationalColorServices",
      print_log: true,
      verbose: true
    )

    version_folder = build_path + "/" + version + "-" + bundleVersion
    zip_path = version_folder + "/" + scheme.delete(' ') + ".zip"

    zip(
      path: app_path,
      output_path: zip_path,
      verbose: false,
      symlinks: true
    )

    release_notes_path = version_folder + "/releasenotes.html"
    changelog_path = Dir.glob("../CHANGELOG.md").first
    text = File.read(changelog_path)
    html = Kramdown::Document.new(text).to_html
    
    puts("Create Release Notes at '" + release_notes_path + "'")
    
    File.write(release_notes_path, html)

    sftp_upload(
      server_url: "beta.cocoanetics.com",
      server_user: "beta",
      server_port: "222",
      server_password: "Ct8IaRn6",
      target_dir: "/Cocoanetics/" + bundle_id,
      file_paths:[version_folder],
    )
  end
  
  desc "Deploy both versions"
  lane :deploy_all do
      sh "fastlane deploy --env Imagineer"
      sh "fastlane deploy --env ImagineerLite"
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.150.3 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin               | Version | Update-Status |
| -------------------- | ------- | ------------- |
| fastlane-plugin-sftp | 1.2.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| CFPropertyList            | 3.0.2        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.17.0       |
| public_suffix             | 4.0.5        |
| tty-screen                | 0.8.0        |
| excon                     | 0.75.0       |
| faraday                   | 1.0.1        |
| faraday_middleware        | 1.0.0        |
| json                      | 2.3.1        |
| bundler                   | 2.1.4        |
| httpclient                | 2.8.3        |
| multi_json                | 1.14.1       |
| signet                    | 0.14.0       |
| os                        | 1.1.0        |
| memoist                   | 0.16.2       |
| googleauth                | 0.13.0       |
| mini_mime                 | 1.0.2        |
| retriable                 | 3.1.2        |
| declarative-option        | 0.1.0        |
| declarative               | 0.0.20       |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| google-api-client         | 0.38.0       |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-env          | 1.3.2        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.26.2       |
| emoji_regex               | 3.0.0        |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.1        |
| aws-partitions            | 1.338.0      |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.103.0      |
| aws-sdk-kms               | 1.36.0       |
| aws-sdk-s3                | 1.73.0       |
| net-ssh                   | 5.2.0        |
| net-sftp                  | 2.1.2        |
| ed25519                   | 1.2.4        |
| bcrypt_pbkdf              | 1.0.1        |
| fastlane-plugin-sftp      | 1.2.0        |
</details>

*generated on:* **2020-07-06**
</details>

**Comment by robbmcmahan** [comment] 2020-07-07 14:14
I left a message on issue #16710 with the output I was seeing on Jenkins but when I run it locally with the same paramaters it was passing but now i'm getting this same this:

```
[!] Exit status of command 'xcrun altool --notarization-info ac631275-3c7d-46bf-9ee4-2bcfee96e819 -u mobe@salesforce.com -p @env:FL_NOTARIZE_PASSWORD --output-format xml' was 1 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>os-version</key>
	<string>10.15.5</string>
	<key>product-errors</key>
	<array>
		<dict>
			<key>code</key>
			<integer>1519</integer>
			<key>message</key>
			<string>Could not find the RequestUUID.</string>
			<key>userInfo</key>
			<dict>
				<key>NSLocalizedDescription</key>
				<string>Could not find the RequestUUID.</string>
				<key>NSLocalizedFailureReason</key>
				<string>Apple Services operation failed.</string>
				<key>NSLocalizedRecoverySuggestion</key>
				<string>Could not find the RequestUUID.</string>
			</dict>
		</dict>
	</array>
	<key>tool-path</key>
	<string>/Applications/Xcode-11.3/Xcode.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/Versions/A/Frameworks/AppStoreService.framework</string>
	<key>tool-version</key>
	<string>4.01.1182</string>
</dict>
</plist>
```

**Comment by odrobnik** [comment] 2020-07-07 15:37
@robbmcmahan yep, that‘s the symptom... of this lag issue. The UUID should be there because the upload was successful, yet the first request for info fails because it cannot find it.

**Comment by joshdholtz** [comment] 2020-07-07 15:47
@robbmcmahan I will have a fix for this is tonight's release of `2.151.0` 💪

**Comment by robbmcmahan** [comment] 2020-07-07 15:53
@joshdholtz can you tell me what the issue is on Jenkins? It appears to be different:

```
10:45:25  [08:45:25]: Stapling package
10:45:25  [08:45:25]: $ xcrun stapler staple "/Users/iosadmin/03bdce55/workspace/xxx/build/xxx.pkg"
10:45:25  [08:45:25]: ▸ Processing: /Users/iosadmin/03bdce55/workspace/xxx/build/xxx.pkg
10:45:25  [08:45:25]: ▸ error is Error Domain=kCFErrorDomainCFNetwork Code=310 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2096, _kCFStreamErrorDomainKey=4}
10:45:25  [08:45:25]: ▸ CloudKit's response is inconsistent with expections: (null)
10:45:25  [08:45:25]: ▸ The staple and validate action failed! Error 68.
10:45:25  
10:45:25  Looking for related GitHub issues on fastlane/fastlane...
10:45:25  
10:45:26  /Users/iosadmin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': \e[31m[!] Exit status of command 'xcrun stapler staple "/Users/iosadmin/03bdce55/workspace/xxx/build/xxx.pkg"' was 68 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
10:45:26  Processing: /Users/iosadmin/03bdce55/workspace/xxx/build/xxx.pkg
10:45:26  error is Error Domain=kCFErrorDomainCFNetwork Code=310 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2096, _kCFStreamErrorDomainKey=4}
10:45:26  CloudKit's response is inconsistent with expections: (null)
10:45:26  The staple and validate action failed! Error 68.
10:45:26  \e[0m
10:45:26  	from /Users/iosadmin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
10:45:26  	from /Users/iosadmin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
10:45:26  	from /Users/iosadmin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/fastlane/lib/fastlane/helper/sh_helper.rb:12:in `sh'
10:45:26  	from /Users/iosadmin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/fastlane/lib/fastlane/actions/notarize.rb:110:in `staple'
10:45:26  	from /Users/iosadmin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/fastlane/lib/fastlane/actions/notarize.rb:97:in `run'
10:45:26  	from /Users/iosadmin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/fastlane/lib/fastlane/runner.rb:261:in `block (2 levels) in execute_action'
10:45:26  	from /Users/iosadmin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
10:45:26  	from /Users/iosadmin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/fastlane/lib/fastlane/runner.rb:253:in `block in execute_action'
10:45:26  	from /Users/iosadmin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/fastlane/lib/fastlane/runner.rb:227:in `chdir'
10:45:26  	from /Users/iosadmin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
10:45:26  	from /Users/iosadmin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/fastlane/lib/fastlane/one_off.rb:42:in `run'
10:45:26  	from /Users/iosadmin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/fastlane/lib/fastlane/one_off.rb:22:in `execute'
10:45:26  	from /Users/iosadmin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/fastlane/lib/fastlane/commands_generator.rb:224:in `block (2 levels) in run'
10:45:26  	from /Users/iosadmin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
10:45:26  	from /Users/iosadmin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
10:45:26  	from /Users/iosadmin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
10:45:26  	from /Users/iosadmin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
10:45:26  	from /Users/iosadmin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
10:45:26  	from /Users/iosadmin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
10:45:26  	from /Users/iosadmin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
10:45:26  	from /Users/iosadmin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
10:45:26  	from /Users/iosadmin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.150.3/bin/fastlane:23:in `<top (required)>'
10:45:26  	from /Users/iosadmin/.rbenv/versions/2.7.1/bin/fastlane:23:in `load'
10:45:26  	from /Users/iosadmin/.rbenv/versions/2.7.1/bin/fastlane:23:in `<main>'
```

**Comment by joshdholtz** [comment] 2020-07-07 16:00
@robbmcmahan I checked the Apple Forums and it looks like its just a random issue that should get fixed/pass eventually for you. Seems like something on Apple's side - https://developer.apple.com/forums/thread/117057

**Closed** 2020-07-07 20:33 UTC
