### ISSUE TITLE
ApplicationNotFound: No application was found for the given package name

### ISSUE THREAD

**Issue by zealousys2016** [fastlane/fastlane#5507] opened 2016-07-26 11:12 UTC
I followed the steps which are provided by fastlane for android.

but it shows error when i run below command.

supply init --json_key /Users/zealous/AndroidStudioProjects/MyApplication/Unknown.json 

Error : 

Looking for related GitHub issues on fastlane/fastlane...

➡️  Supply failed init option with error: applicationNotFound
   https://github.com/fastlane/fastlane/issues/3628 [closed] 5 💬
   10 Mar 2016

➡️  Supply throws titleAlreadyUsed exception when trying to update an existing App
   https://github.com/fastlane/fastlane/issues/4422 [closed] 6 💬
   5 days ago

/Users/zealous/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/google-api-client-0.9.11/lib/google/apis/core/http_command.rb:211:in `check_status': [!] applicationNotFound: No application was found for the given package name.

**Comment by cescoferraro** [comment] 2016-07-27 14:49
Same here

**Comment by TKBurner** [comment] 2016-07-27 20:43
Hi @zealousys2016 and @cescoferraro! Can you share the full input and output when you run this command? I definitely want to take a look. Hope you have a great day 👍

**Comment by zealousys2016** [comment] 2016-07-28 09:48
Hi TKBurner,

I have setup reference to link "https://github.com/fastlane/fastlane/tree/master/supply#setup"
and i got the json key.

Here is package name : com.zelousys.myapplication

First i run fastlane command.
and then run supply.

Here is full command and output is below

supply -p com.zelousys.myapplication -a alpha

+-------------------------+-----------------------------------------------------------------+
|                                 Summary for supply 0.7.0                                  |
+-------------------------+-----------------------------------------------------------------+
| package_name            | com.zelousys.myapplication                                      |
| track                   | alpha                                                           |
| rollout                 | 1.0                                                             |
| json_key                | /Users/zealous/AndroidStudioProjects/MyApplication/Unknown.json |
| skip_upload_apk         | false                                                           |
| skip_upload_metadata    | false                                                           |
| skip_upload_images      | false                                                           |
| skip_upload_screenshots | false                                                           |
+-------------------------+-----------------------------------------------------------------+


Looking for related GitHub issues on fastlane/fastlane...

➡️  ApplicationNotFound: No application was found for the given package name
   https://github.com/fastlane/fastlane/issues/5507 [open] 2 💬
   12 hours ago

➡️  Supply failed init option with error: applicationNotFound
   https://github.com/fastlane/fastlane/issues/3628 [closed] 5 💬
   10 Mar 2016

➡️  Supply throws titleAlreadyUsed exception when trying to update an existing App
   https://github.com/fastlane/fastlane/issues/4422 [closed] 6 💬
   a week ago

/Users/zealous/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/google-api-client-0.9.11/lib/google/apis/core/http_command.rb:211:in `check_status': [!] applicationNotFound: No application was found for the given package name. (Google::Apis::ClientError)
	from /Users/zealous/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/google-api-client-0.9.11/lib/google/apis/core/api_command.rb:102:in `check_status'
	from /Users/zealous/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/google-api-client-0.9.11/lib/google/apis/core/http_command.rb:179:in `process_response'
	from /Users/zealous/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/google-api-client-0.9.11/lib/google/apis/core/http_command.rb:286:in `execute_once'
	from /Users/zealous/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/google-api-client-0.9.11/lib/google/apis/core/http_command.rb:107:in `block (2 levels) in execute'
	from /Users/zealous/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/retriable-2.1.0/lib/retriable.rb:54:in `block in retriable'
	from /Users/zealous/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `times'
	from /Users/zealous/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `retriable'
	from /Users/zealous/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/google-api-client-0.9.11/lib/google/apis/core/http_command.rb:104:in `block in execute'
	from /Users/zealous/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/retriable-2.1.0/lib/retriable.rb:54:in `block in retriable'
	from /Users/zealous/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `times'
	from /Users/zealous/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `retriable'
	from /Users/zealous/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/google-api-client-0.9.11/lib/google/apis/core/http_command.rb:96:in `execute'
	from /Users/zealous/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/google-api-client-0.9.11/lib/google/apis/core/base_service.rb:346:in `execute_or_queue_command'
	from /Users/zealous/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/google-api-client-0.9.11/generated/google/apis/androidpublisher_v2/service.rb:209:in `insert_edit'
	from /Users/zealous/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/supply-0.7.0/lib/supply/client.rb:81:in `begin_edit'
	from /Users/zealous/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/supply-0.7.0/lib/supply/uploader.rb:6:in `perform_upload'
	from /Users/zealous/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/supply-0.7.0/lib/supply/commands_generator.rb:39:in `block (2 levels) in run'
	from /Users/zealous/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/zealous/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/zealous/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/zealous/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane_core-0.48.3/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Users/zealous/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/zealous/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/supply-0.7.0/lib/supply/commands_generator.rb:57:in `run'
	from /Users/zealous/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/supply-0.7.0/lib/supply/commands_generator.rb:15:in `start'
	from /Users/zealous/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/supply-0.7.0/bin/supply:6:in `<top (required)>'
	from /Users/zealous/.rbenv/versions/2.3.1/bin/supply:23:in `load'
	from /Users/zealous/.rbenv/versions/2.3.1/bin/supply:23:in `<main>'

**Comment by asfalcone** [comment] 2016-08-26 17:31
Duplicate of https://github.com/fastlane/fastlane/issues/3628

You must create the application in Google play before running `supply init`

**Closed by asfalcone** 2016-08-26 17:31 UTC
Labels: awaiting-reply, question, supply
