### ISSUE TITLE
disable_automatic_code_signing problem: Seems to be a very old project file format - please use xcode to upgrade to atlease 0800

### ISSUE THREAD

**Issue by sfrag** [fastlane/fastlane#9270] opened 2017-05-25 08:32 UTC
### New Issue Checklist

- [ x ] Updated fastlane to the latest version
- [ x ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I'm using the new action based on plugin to change with a lane the signing from automatic to manual but when i use it, i have an error that i can't understand and there are no information on internet to solve it. 

I use beta lane above.
Thanks!

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | Verifying required     | 0           |
|      | fastlane version       |             |
| 2    | default_platform       | 0           |
| 3    | cert                   | 5           |
| 4    | sigh                   | 8           |
| 💥   | automatic_code_signin  | 9           |
|      | g                      |             |
+------+------------------------+-------------+

[10:14:16]: fastlane finished with errors

[!] Seems to be a very old project file format - please use xcode to upgrade to atlease 0800

    lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    cert
    sigh
    disable_automatic_code_signing
    gym(scheme: "F2FDefault") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
    end

### fastlane env

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.35.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    cert
    sigh
    disable_automatic_code_signing
    gym(scheme: "Face2FaceDefault") # Build your app - more options available
    pilot

    

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "Face2FaceDefault") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.xxxx.f2ffastlane" # The bundle identifier of your app
apple_id "xxxx@xxxx.com" # Your Apple email address

team_id "2YEE9D624W" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.35.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| plist                     | 3.3.0        |
</details>

*generated on:* **2017-05-25**
</details>

**Comment by taquitos** [comment] 2017-05-26 04:14
Yeah, this is a confusing message. What it is saying is that the project file appears to be an older project, and it is too old for _fastlane_ to be able to parse. You can open the project in a newer version of Xcode and let it update the project file. I have opened a new PR to fix the wording: https://github.com/fastlane/fastlane/pull/9291

**Comment by sfrag** [comment] 2017-05-26 08:11
@taquitos The thing is that this is a new project, it's created by gulp task with cordova so with your comment, the only thing that i can imagine it's that the problem is due to cordova version??

**Comment by taquitos** [comment] 2017-05-26 19:31
Ohh, interesting, yeah, maybe they don't generate the needed attribute `TargetAttributes`
Try opening the project in Xcode and saving, then try _fastlane_ again.

**Comment by rsparrow** [comment] 2017-06-09 19:55
There's the same issue with Ionic (which is based on cordova). So if you are using their tools to generate the project file then it's a bit issue for CI / CD where you don't want to checkin the project files with the source. @taquitos is right it's missing the TargetAttributes.

**Comment by okonon** [comment] 2017-07-17 16:52
same issue here with Ionic/cordova project

**Comment by prabhjotAppmobi** [comment] 2017-08-01 11:07
Same Issue with ionic project on my side.

**Comment by jeandesma** [comment] 2017-08-04 14:21
Same issue with Ionic project. For the CI server, I am using the update_project_codesigning plugin which is deprecated but enables you to set an environment variable (FL_PROJECT_SIGNING_FORCE_UPGRADE) to upgrade your project and the needed TargetAttributes. It would be great to have the same possibility on the automatic_code_signing action.

**Comment by okonon** [comment] 2017-08-04 15:08
That would be great to get in automatic_code_signing action

**Comment by elylucas** [comment] 2017-08-10 16:36
The old plugin update_project_codesigning that uses FL_PROJECT_SIGNING_FORCE_UPGRADE is now marked as deprecated, so it would be great to get this env override in so we can use the integrated automatic_code_signing method from fastlane in cordova projects.

**Comment by StobyWan** [comment] 2017-09-09 17:22
Agreed same issue on Ionic Cordova

**Comment by ohayon** [comment] 2017-09-11 16:41
Hey everyone, not having too much experience with Ionic and Cordova, I'm wondering if this is something that is very straightforward to reproduce? I am going to try making a sample project to reproduce this but if anyone has one to share that would be 💯! Thanks! 🚀

**Comment by danhowitt** [comment] 2017-09-21 11:10
+1 on this. Using cordova 7 

```
Seems to be a very old project file format - please open your project file in a more recent version of Xcode
```

**Comment by HardikDG** [comment] 2017-09-23 07:19
Having the same issue in Ionic/Cordova

I have created a sample swift project in Xcode 9 When I run the command it shows success but it still uses Automatic manage signing when I open the project again in the Xcode. 

Commands I have used is below
```
disable_automatic_code_signing(path:"#{xcode_project_path}")
automatic_code_signing(
    path: "#{xcode_project_path}",
    use_automatic_signing: false
  )
```

**Comment by HardikDG** [comment] 2017-09-23 08:08
I have compared both 'project.pbxproj' of Swift project and Ionic project. 

As per the code [automatic_code_signing.rb](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/automatic_code_signing.rb) it is checking for the `TargetAttributes ` in the pbxproj, which is found in the native project created by Xcode.

```
TargetAttributes = {
					566FBA831F763E6500FE8BDC = {
						CreatedOnToolsVersion = 9.0;
						ProvisioningStyle = Manual;
					};
				}
```

The project created by Cordova/Ionic does not have 'TargetAttributes' this key value pair, that's why it shows error of older version.

**Comment by bartvollebregt** [comment] 2017-10-11 08:51
I'm experiencing the exact same thing. My Cordova project generates a .pbxproj without the `TargetAttributes`. I have to manually edit the project every time it's being build...

**Comment by joshstrange** [comment] 2017-10-11 20:56
Same problem as @bartvollebregt, I'm trying to do the following (all without intervention)

- Checkout project

- Run `ionic cordova prepare`

- Run `fastlane ios beta`

I've tried so many combos of match/sigh/cert/etc that I'm going crazy and I *think* that automatic/manual code signing is a big part of that. AFAICT I can't use the actions to turn this off/on because my .pbxproj file is too old (format). It makes sense that cordova is probably spitting out a .pbxproj file that is older so it supports more versions of XCode but I really don't want to script in:

- open XCode

- Save and exit

Just to upgrade my file.

**Comment by joshstrange** [comment] 2017-10-11 21:00
It looks like this pull request might solve our issues (and allow us to use the plugin)

https://github.com/apache/cordova-ios/pull/343

**Comment by janpio** [comment] 2017-10-16 20:25
I just created https://github.com/ionic-zone/fastlane-plugin-upgrade_super_old_xcode that resurrects some old code that was part of [fastlane-plugin-update_project_codesigning](https://github.com/hjanuschka/fastlane-plugin-update_project_codesigning) (Hi @hjanuschka!) (which got merged into the core action [automatic_code_signing.rb](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/automatic_code_signing.rb) - but the relevant code got removed during the merge). You can use this once or before your build steps in your lane to make sure the project is upgraded.

**Comment by joshstrange** [comment] 2017-10-16 20:30
@janpio Thanks for that! I'll have to try it out to see if it works for us. I literally just hit publish on my blog post on how to setup Fastlane with Ionic: https://joshstrange.com/setting-up-fastlane-with-ionic-cordova-apps/ and ended up writing a little cordova hook to "Upgrade" my XCode project just enough to make it all work: https://gist.github.com/joshstrange/cfb4128f1be7ac60c22a41dad98ea68a#file-add_target_attributes_and_push_notification_cap-js (Mine also adds Push Notification Cap)

**Comment by janpio** [comment] 2017-10-17 08:38
Well, now we can check if both the implementations do the same - as I only "copied" it from an old action, I am not 100% sure it already does everything it should do and only that.

I wanted to have it all in a Fastlane action/plugin as I also work on an Ionic plugin for building Ionic projects, which will use this plugin to make sure everything works out of the box.

**Comment by bartvollebregt** [comment] 2017-10-18 11:12
@janpio I just tried your plugin but for me the problem sadly persists:
`Seems to be a very old project file format - please open your project file in a more recent version of Xcode`

**Comment by janpio** [comment] 2017-10-18 11:39
Can you open an issue on my repo? I'll gladly help debug this, but don't want to hijack this discussion here for it.

**Comment by joshstrange** [comment] 2017-10-18 14:05
@bartvollebregt 100% Agree it's not the best, I think the pull request I linked on cordova-ios might be the best solution all around. I got my code from a combination of there and inspecting the platforms/ios project file after opening it in XCode.

**Closed** 2017-12-11 14:11 UTC
Labels: status: waiting-for-reply
