### ISSUE TITLE
fastlane requires  for windows  os ?

### ISSUE THREAD

**Issue by vishal901** [fastlane/fastlane#7051] opened 2016-11-17 11:07 UTC
this tool working for window os??

**Comment by vishal901** [comment] 2016-11-17 11:27
I have study for https://docs.fastlane.tools/ ,

System Requirements:
 fastlane requires macOS or Linux with Ruby 2.0.0 or above.
https://docs.fastlane.tools/

this tool support for windows 7 etc. or not????

**Comment by hjanuschka** [comment] 2016-11-17 12:04
there are a few gems used, that just don't work on windows. i think `pty` for example - so as for now it seems not to be supported.

**Comment by asfalcone** [comment] 2016-11-21 19:25
Going to close as a duplicate of #2082

**Closed** 2016-11-21 19:25 UTC
