### ISSUE TITLE
xcode_install not working anymore

### ISSUE THREAD

**Issue by s0mmer** [fastlane/fastlane#1268] opened 2016-02-03 13:12 UTC
`xcode_install` suddenly stopped working, I believe it was after I updated Fastlane, but I'm not sure. I'm currently running Fastlane 1.57.0. The error log:

```
14:09:39]: ---------------------------
[14:09:39]: --- Step: xcode_install ---
[14:09:39]: ---------------------------
/Users/sds/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2112:in `raise_if_conflicts': Unable to activate xcode-install-1.2.5, because spaceship-0.19.3 conflicts with spaceship (= 0.15.1) (Gem::ConflictError)
	from /Users/sds/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1280:in `activate'
	from /Users/sds/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems.rb:198:in `rescue in try_activate'
	from /Users/sds/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems.rb:195:in `try_activate'
	from /Users/sds/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
	from /Users/sds/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /Users/sds/.rvm/gems/ruby-2.1.2/gems/fastlane-1.57.0/lib/fastlane/actions/xcode_install.rb:13:in `run'
	from /Users/sds/.rvm/gems/ruby-2.1.2/gems/fastlane-1.57.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Users/sds/.rvm/gems/ruby-2.1.2/gems/fastlane-1.57.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Users/sds/.rvm/gems/ruby-2.1.2/gems/fastlane-1.57.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Users/sds/.rvm/gems/ruby-2.1.2/gems/fastlane-1.57.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Users/sds/.rvm/gems/ruby-2.1.2/gems/fastlane-1.57.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Users/sds/.rvm/gems/ruby-2.1.2/gems/fastlane-1.57.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:15:in `block (2 levels) in parsing_binding'
	from /Users/sds/.rvm/gems/ruby-2.1.2/gems/fastlane-1.57.0/lib/fastlane/runner.rb:49:in `call'
	from /Users/sds/.rvm/gems/ruby-2.1.2/gems/fastlane-1.57.0/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/sds/.rvm/gems/ruby-2.1.2/gems/fastlane-1.57.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Users/sds/.rvm/gems/ruby-2.1.2/gems/fastlane-1.57.0/lib/fastlane/runner.rb:46:in `execute'
	from /Users/sds/.rvm/gems/ruby-2.1.2/gems/fastlane-1.57.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Users/sds/.rvm/gems/ruby-2.1.2/gems/fastlane-1.57.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/sds/.rvm/gems/ruby-2.1.2/gems/fastlane-1.57.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Users/sds/.rvm/gems/ruby-2.1.2@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/sds/.rvm/gems/ruby-2.1.2@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/sds/.rvm/gems/ruby-2.1.2@global/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/sds/.rvm/gems/ruby-2.1.2@global/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/sds/.rvm/gems/ruby-2.1.2@global/gems/fastlane_core-0.36.1/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Users/sds/.rvm/gems/ruby-2.1.2@global/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/sds/.rvm/gems/ruby-2.1.2/gems/fastlane-1.57.0/bin/fastlane:150:in `run'
	from /Users/sds/.rvm/gems/ruby-2.1.2/gems/fastlane-1.57.0/bin/fastlane:156:in `<top (required)>'
	from /Users/sds/.rvm/gems/ruby-2.1.2/bin/fastlane:23:in `load'
	from /Users/sds/.rvm/gems/ruby-2.1.2/bin/fastlane:23:in `<main>'
	from /Users/sds/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/sds/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```

I've tried calling `gem update` and `gem cleanup` but without any luck.

**Comment by GabrielCartier** [comment] 2016-02-05 13:44
Got the same exact problem from updating today.

**Comment by mfurtak** [comment] 2016-02-09 22:27
Hi folks - thanks for the reports! :+1: 

Can I get a little more information about your setup?

If you could drop me as much of your `Fastfile` as you're willing to share for the particular lane that is having trouble, that would help a lot for reproducing the problem.

Also, can you drop me the output of the following command: `gem list spaceship`?

**Comment by s0mmer** [comment] 2016-02-11 08:50
Thanks for getting back to me @mfurtak. (Un)fortunately after updating the Fastlane tools, I'm not able to reproduce this error anymore. I will get back to this if it happens again. Maybe @GabrielCartier is still able to reproduce this?

**Comment by mfurtak** [comment] 2016-02-11 14:58
No problem @s0mmer - the report is appreciated!

**Comment by mfurtak** [comment] 2016-02-12 17:50
I'm going to close this for now. @GabrielCartier please reopen if needed! :+1:

**Comment by s0mmer** [comment] 2016-02-16 11:01
Today I was able to reproduce this on another machine. Here is the requested information:

Fastfile:
```ruby
  before_all do
    # Make sure we start from a clean git repo.
    ensure_git_status_clean
    
    # Clear derived data.
    clear_derived_data
    
    # Make sure everything is built using Xcode 7.2.1
    xcode_install(version: "7.2.1")

    ...
```

Output of `gem list spaceship`:
```
*** LOCAL GEMS ***

spaceship (0.19.4, 0.15.1)
```

Could this issue get reopened @mfurtak?

**Comment by KrauseFx** [comment] 2016-02-16 14:36
@s0mmer could you additionally provide the latest output + stack trace?

**Comment by GabrielCartier** [comment] 2016-02-16 17:03
Sorry for my lack of comments. I still have the issue too.
```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:2007:in `raise_if_conflicts': Unable to activate xcode-install-1.2.5, because spaceship-0.19.4 conflicts with spaceship (= 0.15.1) (Gem::LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1176:in `activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:186:in `rescue in try_activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:183:in `try_activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:132:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.59.0/lib/fastlane/actions/xcode_install.rb:13:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.59.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.59.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.59.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.59.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.59.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.59.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:23:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.59.0/lib/fastlane/runner.rb:49:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.59.0/lib/fastlane/runner.rb:49:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.59.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.59.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.59.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.59.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.59.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.36.4/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.59.0/bin/fastlane:150:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.59.0/bin/fastlane:156:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

My Fastfile goes like this:
```
 before_all do
    # Must setup this first: https://developer.apple.com/library/ios/qa/qa1827/_index.html
    if ENV["BUILD_NUMBER"]
      increment_build_number(
      build_number: ENV["BUILD_NUMBER"].to_i
      )
    else
      increment_build_number
    end

    #Code for the CI only
    if is_ci
      # Update xcode
      xcode_install(version: "7.2.1")

      #verify install
      verify_xcode
    end
    #clear derived data
    clear_derived_data

    #Pod install
    cocoapods
```

**Comment by s0mmer** [comment] 2016-02-19 13:09
@KrauseFx After upgrading ruby, spaceship and Fastlane I no longer experience it on the second machine. I will get back to this issue if it appears on a third machine 😊

**Comment by s0mmer** [comment] 2016-02-22 12:29
After upgrading to spaceship `0.21`, I do not experience this error anymore 👍

**Comment by s0mmer** [comment] 2016-03-01 13:51
Aaaand it's back 😢 After upgrading to spaceship to `0.21.1` and basically updating all fastlane gems followed by a `gem cleanup`, the error re-appeared.

**Comment by vpolouchkine** [comment] 2016-04-06 22:16
@s0mmer Are you still hitting this?

**Comment by mfurtak** [comment] 2016-04-07 00:12
Here's what I understand to be happening:

`fastlane` depends on `spaceship` at a version **>= 0.24.1**
`xcode_install` depends on `spaceship` at _exactly **0.15.1**

These constraints can't be satisfied together, thus the error.

----

Here's what I understand to be the reasoning behind each of these independent decisions:

`fastlane` depends on the latest versions of all the sub-tools in order to have them installed when someone does `gem install fastlane`. The minimum allowable versions for each gets bumped regularly as we fix important bugs in the tools that we want people to receive.

`xcode_install` locks the `spaceship` dependency at 0.15.1 because past that version, a transitive dependency of `spaceship` was introduced that has a native extension written in C. In order to compile that native extension you need to have Xcode command line tools installed... and... you see the problem. That all got discussed in this [`xcode_install` ticket](https://github.com/neonichu/xcode-install/issues/108).

----

So, I think we're at an impasse. We can keep this as a place to put updates, but as far as I know, this is not being looked at right now.

**Comment by s0mmer** [comment] 2016-04-07 06:34
@vpolouchkine Yes, unfortunately I am.

Updating to the latest version of `fastlane` and `xcode-install` I am receiving this error:

```
/Users/sds/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:2284:in `raise_if_conflicts': Unable to activate xcode-install-1.2.5, because spaceship-0.24.1 conflicts with spaceship (= 0.15.1) (Gem::ConflictError)
	from /Users/sds/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1407:in `activate'
	from /Users/sds/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems.rb:196:in `rescue in try_activate'
	from /Users/sds/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems.rb:193:in `try_activate'
	from /Users/sds/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:125:in `rescue in require'
	from /Users/sds/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /Users/sds/.rvm/gems/ruby-2.3.0/gems/fastlane-1.80.0/lib/fastlane/actions/xcode_install.rb:13:in `run'
	from /Users/sds/.rvm/gems/ruby-2.3.0/gems/fastlane-1.80.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Users/sds/.rvm/gems/ruby-2.3.0/gems/fastlane-1.80.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Users/sds/.rvm/gems/ruby-2.3.0/gems/fastlane-1.80.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Users/sds/.rvm/gems/ruby-2.3.0/gems/fastlane-1.80.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Users/sds/.rvm/gems/ruby-2.3.0/gems/fastlane-1.80.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Users/sds/.rvm/gems/ruby-2.3.0/gems/fastlane-1.80.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:43:in `block (2 levels) in parsing_binding'
	from /Users/sds/.rvm/gems/ruby-2.3.0/gems/fastlane-1.80.0/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/sds/.rvm/gems/ruby-2.3.0/gems/fastlane-1.80.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Users/sds/.rvm/gems/ruby-2.3.0/gems/fastlane-1.80.0/lib/fastlane/runner.rb:46:in `execute'
	from /Users/sds/.rvm/gems/ruby-2.3.0/gems/fastlane-1.80.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Users/sds/.rvm/gems/ruby-2.3.0/gems/fastlane-1.80.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/sds/.rvm/gems/ruby-2.3.0/gems/fastlane-1.80.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Users/sds/.rvm/gems/ruby-2.3.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/sds/.rvm/gems/ruby-2.3.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/sds/.rvm/gems/ruby-2.3.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/sds/.rvm/gems/ruby-2.3.0/gems/fastlane_core-0.41.2/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Users/sds/.rvm/gems/ruby-2.3.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/sds/.rvm/gems/ruby-2.3.0/gems/fastlane-1.80.0/bin/fastlane:158:in `run'
	from /Users/sds/.rvm/gems/ruby-2.3.0/gems/fastlane-1.80.0/bin/fastlane:164:in `<top (required)>'
	from /Users/sds/.rvm/gems/ruby-2.3.0/bin/fastlane:23:in `load'
	from /Users/sds/.rvm/gems/ruby-2.3.0/bin/fastlane:23:in `<main>'
	from /Users/sds/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/sds/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by TKBurner** [comment] 2016-04-07 14:31
Thanks for following up @s0mmer! We are still working on a strategy on our end. :+1:

**Comment by neonichu** [comment] 2016-04-09 21:23
I experimented a bit on this problem today and I think there's a somewhat feasible solution, which requires a little bit of extra work for folks wanting to install `xcode-install` on a fresh system.

I have created a fork of `domain_name` without the native dependency with a much higher patch version than the currently released one. Folks which do not want the native dependency can manually install that and then run the `xcode-install` installation using the `--conservative` flag and this will lead to the already installed fork being used, so no native extension is required. This is what people need to run for this:

```bash
curl -sL -O https://github.com/neonichu/ruby-domain_name/releases/download/v0.5.99999999/domain_name-0.5.99999999.gem
gem install domain_name-0.5.99999999.gem
gem install --conservative spaceship
```

For most other folks, who previously installed the developer tools on their system, the regular `gem install` process will work just fine :ok_hand: 

I feel like this is an OK solution to this annoying problem — @mfurtak, @KrauseFx do you see any problems with this?

**Comment by s0mmer** [comment] 2016-04-11 08:49
Thanks @neonichu for looking into this. Using your described approach, I'm able to use `xcode-install` again in my `fastlane` setup.

**Comment by neonichu** [comment] 2016-04-11 08:58
:beers:

**Comment by TKBurner** [comment] 2016-04-11 20:17
@neonichu Thanks so much for stepping in on this!

@s0mmer Glad to hear you got up and running 👍

**Comment by mfurtak** [comment] 2016-04-11 22:09
@neonichu Thanks for researching this work around. It sounds like a reasonable suggestion for now! :+1:

**Comment by KrauseFx** [comment] 2016-05-11 22:56
Thanks again @neonichu, I'm closing this issue for now 👍

**Closed by KrauseFx** 2016-05-11 22:56 UTC
Labels: action, blocked

**Comment by neonichu** [comment] 2016-05-11 23:30
🔑
