### ISSUE TITLE
Add argument to suppress changelog_from_git_commits output

### ISSUE THREAD

**Issue by krin-san** [fastlane/fastlane#11098] opened 2017-12-04 07:48 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Would be nice to have an argument to suppress `changelog_from_git_commits` action output. I'm using this in a few places, not only for changelog generation, so I'd like to lower the flood in build logs.

Originally it was implemented in #4860 but this solution is poor from reviewer perspective.

**Comment by ohayon** [comment] 2017-12-04 16:42
Hey @krin-san - this would definitely be a nice addition to the action. Thanks for submitting the feature request. We would be happy to review a PR adding this functionality if you want to take a crack at it. I am going to close this issue for now, as it is not a bug in _fastlane_ but please feel free to continue discussion here and let us know if we can help! 🚀

**Closed by ohayon** 2017-12-04 16:42 UTC
Labels: complexity: you can do this, tool: action, type: feature
