### ISSUE TITLE
Unable to edit app through fastlane deliver

### ISSUE THREAD

**Issue by Luke-SF** [fastlane/fastlane#9367] opened 2017-06-05 21:22 UTC
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I can update info about a newly created app on iTC but not through fastlane deliver.
The end of the command gives an error:

```
[14:12:30]: Making sure the latest version on iTunes Connect matches '<VERSIONNUMBER>' from the ipa file...

Looking for related GitHub issues on fastlane/fastlane...

➡️  undefined method `edit_version' for nil:NilClass
    https://github.com/fastlane/fastlane/issues/8660 [closed] 8 💬
    a week ago

➡️  Undefined method `fetch` for nil:NilClass (NoMethodError) again?
    https://github.com/fastlane/fastlane/issues/7307 [closed] 4 💬
    3 weeks ago

➡️  [!] undefined method `native_targets' for #<Xcodeproj::Project:[MEMORY_INSTANCE]>
    https://github.com/fastlane/fastlane/issues/8935 [closed] 2 💬
    6 weeks ago

and 61 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60fetch'%20for%20nil&type=Issues&utf8=✓

/Library/Ruby/Gems/2.0.0/gems/fastlane-2.36.0/spaceship/lib/spaceship/tunes/app_version.rb:814:in `block in setup_trailers_for': [!] undefined method `fetch' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.36.0/spaceship/lib/spaceship/tunes/app_version.rb:813:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.36.0/spaceship/lib/spaceship/tunes/app_version.rb:813:in `setup_trailers_for'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.36.0/spaceship/lib/spaceship/tunes/app_version.rb:800:in `block in setup_trailers'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.36.0/spaceship/lib/spaceship/tunes/app_version.rb:798:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.36.0/spaceship/lib/spaceship/tunes/app_version.rb:798:in `setup_trailers'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.36.0/spaceship/lib/spaceship/tunes/app_version.rb:381:in `setup'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.36.0/spaceship/lib/spaceship/base.rb:215:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.36.0/spaceship/lib/spaceship/tunes/app_version.rb:226:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.36.0/spaceship/lib/spaceship/tunes/app_version.rb:226:in `factory'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.36.0/spaceship/lib/spaceship/tunes/app_version.rb:247:in `find'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.36.0/spaceship/lib/spaceship/tunes/application.rb:111:in `edit_version'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.36.0/spaceship/lib/spaceship/tunes/application.rb:212:in `ensure_version!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-2.0.1/lib/deliver/runner.rb:39:in `verify_version'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-2.0.1/lib/deliver/runner.rb:20:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-2.0.1/lib/deliver/commands_generator.rb:65:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.36.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:39:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-2.0.1/lib/deliver/commands_generator.rb:151:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-2.0.1/lib/deliver/commands_generator.rb:13:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-2.0.1/bin/deliver:12:in `<top (required)>'
	from /usr/local/bin/deliver:23:in `load'
	from /usr/local/bin/deliver:23:in `<main>'
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.12.5                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.11.0 (Apple Git-81)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.12.5 (16F73)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 8.3.2                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.36.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.10.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.6.3        |
| terminal-table            | 1.4.5        |
| addressable               | 2.3.8        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.45.4       |
| faraday                   | 0.9.2        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160128 |
| http-cookie               | 1.0.2        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0221  |
| mime-types                | 3.0          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.11.2       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.4        |
| memoist                   | 0.14.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.2        |
| googleauth                | 0.5.1        |
| thor                      | 0.19.1       |
| httpclient                | 2.8.0        |
| google-api-client         | 0.9.5        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.5.5        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.12.5       |
| faraday_middleware        | 0.10.0       |
| json                      | 1.8.3        |
| rubyzip                   | 1.2.0        |
| plist                     | 3.2.0        |
| fastimage                 | 1.9.0        |
</details>

*generated on:* **2017-06-05**
</details>

**Comment by dantaylorseo** [comment] 2017-06-05 21:27
This seems to be an update to the way iTC reports back to Spaceship.

This was working for me one minute and then stopped the next.

I fixed my error by editing app_version.rb:813 to

```
display_families.each do |display_family|
          trailer_var = display_family.fetch("trailer", {})
          next if trailer_var.nil?
          trailer_data = trailer_var.fetch("value")
          next if trailer_data.nil?
          data = {
            device_type: display_family['name'],
            language: row["language"]
          }.merge(trailer_data)
          result << Tunes::AppTrailer.factory(data)
        end
```

I assume other lines will need looking at too @KrauseFx 

What I found was that the object was `{ trailler: nil }` not `{ trailer: { value: nil } }`

**Comment by lukethoene** [comment] 2017-06-05 21:39
Yep deliver is failing for us too with the same `block in setup_trailers_for' fetch-nil no method error

**Comment by cwnowak** [comment] 2017-06-05 22:09
I was having the same issue. Editing the file as @dantaylorseo suggested worked.

**Comment by MaximusMcCann** [comment] 2017-06-05 22:20
Same issue :(

**Comment by KrauseFx** [comment] 2017-06-05 22:52
Thanks everyone, we already pushed a fix, and are in the process of shipping a new release 👍 https://github.com/fastlane/fastlane/pull/9368

**Closed by KrauseFx** 2017-06-05 22:52 UTC

**Comment by KrauseFx** [comment] 2017-06-05 22:56
Could you please update and let us know if that fixes the issue for you? 👍

**Comment by kevinlondon** [comment] 2017-06-05 23:12
The update resolved it for me. Thanks for the super quick turn-around and for tweeting about the issue! Made it easy to trace.

**Comment by scottlemke** [comment] 2017-06-05 23:15
Confirmed that 2.37.0 fixed the issue for me. Thank you for the quick update!

**Comment by lukethoene** [comment] 2017-06-05 23:20
100 percent.  Thanks and well done!

**Comment by bowenisdum** [comment] 2017-06-05 23:56
You guys rock 🥇
