### ISSUE TITLE
Google Api Error: multiApkDowngradedDevice

### ISSUE THREAD

**Issue by lhalegria** [fastlane/fastlane#11052] opened 2017-11-29 14:49 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm facing the `multiApkDowngradedDevice` error and figured out this error is occurring 'cause I have an older versionName "3.6.01" with versionCode 3601 and now I'm trying to upload new versionCode 381 to play store. Doing the proccess manually everything works with not even a warning.
This is not about check_superseded_tracks.

I'm using version `2.67.0`.

##### Complete output when running fastlane, including the stack trace and command used

bundle exec fastlane rexpense_sandbox sandbox_version:"3.8.1-beta" --capture_output
### Captured Output

Command Used: `rexpense_sandbox sandbox_version:3.8.1-beta`
<details><summary>Output/Log</summary>

```

INFO [2017-11-29 12:26:04.72]: Successfully loaded custom action '/media/lhalegria/Data/dev/rexpense-android/Rexpense/fastlane/actions/sign_apk.rb'.
INFO [2017-11-29 12:26:04.72]: Successfully loaded custom action '/media/lhalegria/Data/dev/rexpense-android/Rexpense/fastlane/actions/zipalign.rb'.
DEBUG [2017-11-29 12:26:04.72]: Checking if there are any plugins that should be loaded...
DEBUG [2017-11-29 12:26:04.72]: Loading 'fastlane-plugin-get_version_name' plugin
INFO [2017-11-29 12:26:04.77]: gem 'fastlane-plugin-get_version_name' is already installed
+----------------------------------+---------+------------------+
|                         Used plugins                          |
+----------------------------------+---------+------------------+
| Plugin                           | Version | Action           |
+----------------------------------+---------+------------------+
| fastlane-plugin-get_version_name | 0.2.2   | get_version_name |
+----------------------------------+---------+------------------+

Successfully loaded Appfile at path '/media/lhalegria/Data/dev/rexpense-android/Rexpense/fastlane/Appfile'
- json_key_file: 'fastlane/supply-key-f82c81f8b87e.json'
- package_name: 'com.br.myfreecomm.rexpense'
-------
DEBUG [2017-11-29 12:26:04.88]: Using sandbox_version: 3.8.1-beta
Successfully loaded Appfile at path '/media/lhalegria/Data/dev/rexpense-android/Rexpense/fastlane/Appfile'
- json_key_file: 'fastlane/supply-key-f82c81f8b87e.json'
- package_name: 'com.br.myfreecomm.rexpense'
-------
INFO [2017-11-29 12:26:04.89]: -------------------------------------------------
INFO [2017-11-29 12:26:04.89]: --- Step: Verifying required fastlane version ---
INFO [2017-11-29 12:26:04.89]: -------------------------------------------------
INFO [2017-11-29 12:26:04.89]: Your fastlane version 2.67.0 matches the minimum requirement of 2.67.0  ✅
Successfully loaded Appfile at path '/media/lhalegria/Data/dev/rexpense-android/Rexpense/fastlane/Appfile'
- json_key_file: 'fastlane/supply-key-f82c81f8b87e.json'
- package_name: 'com.br.myfreecomm.rexpense'
-------
Successfully loaded Appfile at path '/media/lhalegria/Data/dev/rexpense-android/Rexpense/fastlane/Appfile'
- json_key_file: 'fastlane/supply-key-f82c81f8b87e.json'
- package_name: 'com.br.myfreecomm.rexpense'
-------
INFO [2017-11-29 12:26:04.90]: ------------------------------
INFO [2017-11-29 12:26:04.90]: --- Step: default_platform ---
INFO [2017-11-29 12:26:04.90]: ------------------------------
Successfully loaded Appfile at path '/media/lhalegria/Data/dev/rexpense-android/Rexpense/fastlane/Appfile'
- json_key_file: 'fastlane/supply-key-f82c81f8b87e.json'
- package_name: 'com.br.myfreecomm.rexpense'
-------
INFO [2017-11-29 12:26:04.90]: Driving the lane 'android rexpense_sandbox' 🚀
Successfully loaded Appfile at path '/media/lhalegria/Data/dev/rexpense-android/Rexpense/fastlane/Appfile'
- json_key_file: 'fastlane/supply-key-f82c81f8b87e.json'
- package_name: 'com.br.myfreecomm.rexpense'
-------
INFO [2017-11-29 12:26:04.91]: --------------------
INFO [2017-11-29 12:26:04.91]: --- Step: gradle ---
INFO [2017-11-29 12:26:04.91]: --------------------
INFO [2017-11-29 12:26:04.92]: $ /media/lhalegria/Data/dev/rexpense-android/Rexpense/gradlew assemblerexpense_sandboxRelease -p .
...
INFO [2017-11-29 12:26:11.41]: ▸ BUILD SUCCESSFUL in 6s
INFO [2017-11-29 12:26:11.41]: ▸ 165 actionable tasks: 1 executed, 164 up-to-date
Successfully loaded Appfile at path '/media/lhalegria/Data/dev/rexpense-android/Rexpense/fastlane/Appfile'
- json_key_file: 'fastlane/supply-key-f82c81f8b87e.json'
- package_name: 'com.br.myfreecomm.rexpense'
-------
Successfully loaded Appfile at path '/media/lhalegria/Data/dev/rexpense-android/Rexpense/fastlane/Appfile'
- json_key_file: 'fastlane/supply-key-f82c81f8b87e.json'
- package_name: 'com.br.myfreecomm.rexpense'
-------
INFO [2017-11-29 12:26:12.55]: ----------------------
INFO [2017-11-29 12:26:12.55]: --- Step: sign_apk ---
INFO [2017-11-29 12:26:12.55]: ----------------------
INFO [2017-11-29 12:26:12.55]: $ jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore /media/lhalegria/Data/dev/rexpense-android/Rexpense/key\ play_google/MyFreecomm/MyFreecomm /media/lhalegria/Data/dev/rexpense-android/Rexpense/rexpense/build/outputs/apk/rexpense_sandbox/release/rexpense-rexpense_sandbox-release-unsigned.apk 'myfreecomm' -keypass *** -storepass *** -tsa http://timestamp.comodoca.com/rfc316 -signedjar /media/lhalegria/Data/dev/rexpense-android/Rexpense/rexpense/rexpense-sandbox.apk
INFO [2017-11-29 12:26:13.02]: ▸ updating: META-INF/MANIFEST.MF
INFO [2017-11-29 12:26:14.02]: ▸ adding: META-INF/MYFREECO.SF
INFO [2017-11-29 12:26:14.02]: ▸ requesting a signature timestamp
INFO [2017-11-29 12:26:14.02]: ▸ TSA location: http://timestamp.comodoca.com/rfc316
INFO [2017-11-29 12:26:14.02]: ▸ adding: META-INF/MYFREECO.RSA
INFO [2017-11-29 12:26:14.03]: ▸ signing: AndroidManifest.xml
...
INFO [2017-11-29 12:26:18.75]: ▸ jar signed.
Successfully loaded Appfile at path '/media/lhalegria/Data/dev/rexpense-android/Rexpense/fastlane/Appfile'
- json_key_file: 'fastlane/supply-key-f82c81f8b87e.json'
- package_name: 'com.br.myfreecomm.rexpense'
-------
Successfully loaded Appfile at path '/media/lhalegria/Data/dev/rexpense-android/Rexpense/fastlane/Appfile'
- json_key_file: 'fastlane/supply-key-f82c81f8b87e.json'
- package_name: 'com.br.myfreecomm.rexpense'
-------
Successfully loaded Appfile at path '/media/lhalegria/Data/dev/rexpense-android/Rexpense/fastlane/Appfile'
- json_key_file: 'fastlane/supply-key-f82c81f8b87e.json'
- package_name: 'com.br.myfreecomm.rexpense'
-------
Successfully loaded Appfile at path '/media/lhalegria/Data/dev/rexpense-android/Rexpense/fastlane/Appfile'
- json_key_file: 'fastlane/supply-key-f82c81f8b87e.json'
- package_name: 'com.br.myfreecomm.rexpense'
-------
INFO [2017-11-29 12:26:18.76]: ----------------------
INFO [2017-11-29 12:26:18.76]: --- Step: zipalign ---
INFO [2017-11-29 12:26:18.76]: ----------------------
ERROR [2017-11-29 12:26:18.77]: Shell command exited with exit status 1 instead of 0.
INFO [2017-11-29 12:26:18.77]: $ zipalign -v -f 4 /media/lhalegria/Data/dev/rexpense-android/Rexpense/rexpense/rexpense-sandbox-unaligned.apk   /media/lhalegria/Data/dev/rexpense-android/Rexpense/rexpense/rexpense-sandbox.apk
INFO [2017-11-29 12:26:18.88]: ▸ Verifying alignment of /media/lhalegria/Data/dev/rexpense-android/Rexpense/rexpense/rexpense-sandbox.apk (4)...
INFO [2017-11-29 12:26:18.88]: ▸ 50 META-INF/MANIFEST.MF (OK - compressed)
...
INFO [2017-11-29 12:26:19.03]: ▸ Verification successful
Successfully loaded Appfile at path '/media/lhalegria/Data/dev/rexpense-android/Rexpense/fastlane/Appfile'
- json_key_file: 'fastlane/supply-key-f82c81f8b87e.json'
- package_name: 'com.br.myfreecomm.rexpense'
-------
Successfully loaded Appfile at path '/media/lhalegria/Data/dev/rexpense-android/Rexpense/fastlane/Appfile'
- json_key_file: 'fastlane/supply-key-f82c81f8b87e.json'
- package_name: 'com.br.myfreecomm.rexpense'
-------
Successfully loaded Appfile at path '/media/lhalegria/Data/dev/rexpense-android/Rexpense/fastlane/Appfile'
- json_key_file: 'fastlane/supply-key-f82c81f8b87e.json'
- package_name: 'com.br.myfreecomm.rexpense'
-------
Successfully loaded Appfile at path '/media/lhalegria/Data/dev/rexpense-android/Rexpense/fastlane/Appfile'
- json_key_file: 'fastlane/supply-key-f82c81f8b87e.json'
- package_name: 'com.br.myfreecomm.rexpense'
-------
INFO [2017-11-29 12:26:19.04]: --------------------
INFO [2017-11-29 12:26:19.04]: --- Step: supply ---
INFO [2017-11-29 12:26:19.04]: --------------------
Successfully loaded Appfile at path '/media/lhalegria/Data/dev/rexpense-android/Rexpense/fastlane/Appfile'
- json_key_file: 'fastlane/supply-key-f82c81f8b87e.json'
- package_name: 'com.br.myfreecomm.rexpense'
-------
Successfully loaded Appfile at path '/media/lhalegria/Data/dev/rexpense-android/Rexpense/fastlane/Appfile'
- json_key_file: 'fastlane/supply-key-f82c81f8b87e.json'
- package_name: 'com.br.myfreecomm.rexpense'
-------
Successfully loaded Appfile at path '/media/lhalegria/Data/dev/rexpense-android/Rexpense/fastlane/Appfile'
- json_key_file: 'fastlane/supply-key-f82c81f8b87e.json'
- package_name: 'com.br.myfreecomm.rexpense'
-------
Successfully loaded Appfile at path '/media/lhalegria/Data/dev/rexpense-android/Rexpense/fastlane/Appfile'
- json_key_file: 'fastlane/supply-key-f82c81f8b87e.json'
- package_name: 'com.br.myfreecomm.rexpense'
-------
Successfully loaded Appfile at path '/media/lhalegria/Data/dev/rexpense-android/Rexpense/fastlane/Appfile'
- json_key_file: 'fastlane/supply-key-f82c81f8b87e.json'
- package_name: 'com.br.myfreecomm.rexpense'
-------

+-------------------------+----------------------------------------------------------------------------------+
|                                         Summary for supply 2.67.0                                          |
+-------------------------+----------------------------------------------------------------------------------+
| package_name            | com.br.myfreecomm.rexpense_sandbox                                               |
| track                   | beta                                                                             |
| skip_upload_screenshots | true                                                                             |
| skip_upload_images      | true                                                                             |
| apk                     | /media/lhalegria/Data/dev/rexpense-android/Rexpense/rexpense/rexpense-sandbox.a  |
|                         | pk                                                                               |
| metadata_path           | ./fastlane/metadata/android                                                      |
| json_key                | fastlane/supply-key-f82c81f8b87e.json                                            |
| skip_upload_apk         | false                                                                            |
| skip_upload_metadata    | false                                                                            |
| validate_only           | false                                                                            |
| check_superseded_tracks | false                                                                            |
+-------------------------+----------------------------------------------------------------------------------+

DEBUG [2017-11-29 12:26:20.61]: Fetching a new access token from Google...
INFO [2017-11-29 12:26:22.55]: Preparing to upload for language 'en-US'...
INFO [2017-11-29 12:26:23.42]: Preparing to upload for language 'pt-BR'...
INFO [2017-11-29 12:26:24.30]: Preparing apk at path '/media/lhalegria/Data/dev/rexpense-android/Rexpense/rexpense/rexpense-sandbox.apk' for upload...
INFO [2017-11-29 12:26:54.45]: Updating changelog for code version '381' and language 'en-US'...
INFO [2017-11-29 12:26:54.84]: Updating changelog for code version '381' and language 'pt-BR'...
INFO [2017-11-29 12:26:55.27]: Updating track 'beta'...
INFO [2017-11-29 12:26:55.70]: Uploading all changes to Google Play...
Successfully loaded Appfile at path '/media/lhalegria/Data/dev/rexpense-android/Rexpense/fastlane/Appfile'
- json_key_file: 'fastlane/supply-key-f82c81f8b87e.json'
- package_name: 'com.br.myfreecomm.rexpense'
-------
WARN [2017-11-29 12:26:59.51]: Lane Context:
INFO [2017-11-29 12:26:59.51]: {:DEFAULT_PLATFORM=>:android, :PLATFORM_NAME=>:android, :LANE_NAME=>"android rexpense_sandbox", :GRADLE_BUILD_TYPE=>"Release", :GRADLE_FLAVOR=>"rexpense_sandbox", :GRADLE_ALL_APK_OUTPUT_PATHS=>["/media/lhalegria/Data/dev/rexpense-android/Rexpense/rexpense/build/outputs/apk/rexpense_sandbox/release/rexpense-rexpense_sandbox-release-unsigned.apk"], :GRADLE_APK_OUTPUT_PATH=>"/media/lhalegria/Data/dev/rexpense-android/Rexpense/rexpense/build/outputs/apk/rexpense_sandbox/release/rexpense-rexpense_sandbox-release-unsigned.apk", :SIGNED_APK_PATH=>"/media/lhalegria/Data/dev/rexpense-android/Rexpense/rexpense/rexpense-sandbox.apk"}
ERROR [2017-11-29 12:26:59.51]: Google Api Error: multiApkDowngradedDevice: Devices with version 3602 of this app would be downgraded to version 381 if they met the following criteria: [(API_LEVEL in range 16-0 AND RELEASE_TRACK containing any of each of [[ALPHA, BETA]] AND SCREENS containing any of each of [[small, normal, large, xlarge]] AND GL_ES_VERSION in range 131072-0 AND FEATURES containing all of [android.hardware.screen.PORTRAIT, android.hardware.FAKETOUCH, android.hardware.LOCATION, android.hardware.CAMERA, android.hardware.WIFI])].
INFO [2017-11-29 12:26:59.51]: Successfully generated documentation at path '/media/lhalegria/Data/dev/rexpense-android/Rexpense/fastlane/README.md'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | gradle                              | 7           |
| 4    | sign_apk                            | 6           |
| 5    | zipalign                            | 0           |
| 💥   | supply                              | 38          |
+------+-------------------------------------+-------------+

DEBUG [2017-11-29 12:26:59.54]: All plugins are up to date
ERROR [2017-11-29 12:26:59.54]: fastlane finished with errors
Successfully loaded Appfile at path '/media/lhalegria/Data/dev/rexpense-android/Rexpense/fastlane/Appfile'
- json_key_file: 'fastlane/supply-key-f82c81f8b87e.json'
- package_name: 'com.br.myfreecomm.rexpense'
-------
DEBUG [2017-11-29 12:26:59.54]: All plugins are up to date


```

</details>

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                                          |
| --------------------------- | ------------------------------------------------------------------------------ |
| OS                          | debian_based stretch/sid                                                       |
| Ruby                        | 2.3.1                                                                          |
| Bundler?                    | true                                                                           |
| Git                         | git version 2.15.0                                                             |
| Installation Source         | /media/lhalegria/Data/dev/rexpense-android/Rexpense/vendor/bundle/bin/fastlane |
| Host                        | Linux Mint 18.2 Sonya debian_based stretch/sid (4.10.0-40-generic)             |
| Ruby Lib Dir                | /usr/lib                                                                       |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                                                     |
| Is contained                | false                                                                          |
| Is homebrew                 | false                                                                          |
| Is installed via Fabric.app | false                                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US       | 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.67.0"

default_platform :android

platform :android do

	#plugin get-version-name still don't support flavors. So we have to pass the sandbox version as a parameter
	before_all do |lane, options|
		ENV["HIPCHAT_API_TOKEN"] = "***"
		if options[:sandbox_version] != nil
			ENV['versionName'] = options[:sandbox_version]
		else
			ENV['versionName'] = get_version_name(
	      		gradle_file_path:"./rexpense/build.gradle"
    		)
		end
	end

  	desc "Deploy a new sandbox beta version to the Google Play Store"
  	lane :rexpense_sandbox do
    	gradle(
      		task: 'assemble',
      		flavor: 'rexpense_sandbox', 
      		build_type: 'Release'
    	)
		sign_apk(
      		keystore_path: "#{File.expand_path("..", Dir.pwd)}/key play_google/MyFreecomm/MyFreecomm",
      		alias: "myfreecomm",
      		storepass: "****",
      		keypass: "****",
      		signed_apk_path: "#{File.expand_path("..", Dir.pwd)}/rexpense/rexpense-sandbox.apk",
      		tsa: "http://timestamp.comodoca.com/rfc316"
    	)
    	zipalign(apk_path: lane_context[SharedValues::SIGNED_APK_PATH])
		supply(
      		package_name: "com.br.myfreecomm.rexpense_sandbox",
      		track: "beta",
      		skip_upload_screenshots: true,
      		skip_upload_images: true,
      		apk: lane_context[SharedValues::SIGNED_APK_PATH]
    	)
    	hipchat(
       		message: ENV['versionName'] + "available",
       		channel: "Channel",
       		api_token: ENV["HIPCHAT_API_TOKEN"],
       		custom_color: "gray",
       		version: "1",
       		notify_room: true,
       		message_format: "text"
    	)
  	end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file "fastlane/supply-key-f82c81f8b87e.json" # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name "com.br.myfreecomm.rexpense" # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.67.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                           | Version | Update-Status |
| -------------------------------- | ------- | ------------- |
| fastlane-plugin-get_version_name | 0.2.2   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                              | Version      |
| -------------------------------- | ------------ |
| bundler                          | 1.16.0       |
| CFPropertyList                   | 2.3.5        |
| public_suffix                    | 2.0.5        |
| addressable                      | 2.5.2        |
| babosa                           | 1.0.2        |
| claide                           | 1.0.2        |
| colored                          | 1.2          |
| colored2                         | 3.1.2        |
| highline                         | 1.7.10       |
| commander-fastlane               | 4.4.5        |
| declarative                      | 0.0.10       |
| declarative-option               | 0.1.0        |
| unf_ext                          | 0.0.7.4      |
| unf                              | 0.1.4        |
| domain_name                      | 0.5.20170404 |
| dotenv                           | 2.2.1        |
| excon                            | 0.59.0       |
| multipart-post                   | 2.0.0        |
| faraday                          | 0.13.1       |
| http-cookie                      | 1.0.3        |
| faraday-cookie_jar               | 0.0.6        |
| faraday_middleware               | 0.12.2       |
| fastimage                        | 2.1.0        |
| gh_inspector                     | 1.0.3        |
| jwt                              | 2.1.0        |
| little-plugger                   | 1.1.4        |
| multi_json                       | 1.12.2       |
| logging                          | 2.2.2        |
| memoist                          | 0.16.0       |
| os                               | 0.9.6        |
| signet                           | 0.8.1        |
| googleauth                       | 0.6.2        |
| httpclient                       | 2.8.3        |
| mime-types-data                  | 3.2016.0521  |
| mime-types                       | 3.1          |
| uber                             | 0.1.0        |
| representable                    | 3.0.4        |
| retriable                        | 3.1.1        |
| google-api-client                | 0.13.6       |
| json                             | 2.1.0        |
| mini_magick                      | 4.5.1        |
| multi_xml                        | 0.6.0        |
| plist                            | 3.3.0        |
| rubyzip                          | 1.2.1        |
| security                         | 0.1.3        |
| slack-notifier                   | 1.5.1        |
| terminal-notifier                | 1.8.0        |
| unicode-display_width            | 1.3.0        |
| terminal-table                   | 1.8.0        |
| tty-screen                       | 0.6.3        |
| word_wrap                        | 1.0.0        |
| nanaimo                          | 0.2.3        |
| xcodeproj                        | 1.5.3        |
| rouge                            | 2.0.7        |
| xcpretty                         | 0.2.8        |
| xcpretty-travis-formatter        | 1.0.0        |
| fastlane-plugin-get_version_name | 0.2.2        |
</details>

*generated on:* **2017-11-29**
</details>

**Comment by corneliu-serediuc** [comment] 2017-12-01 12:23
I opened another similar [issue](https://github.com/fastlane/fastlane/issues/11087), maybe the message will eventually get heart.

**Comment by ohayon** [comment] 2017-12-04 15:46
Ping! @fastlane/android 🤖

**Comment by janpio** [comment] 2017-12-04 16:00
FYI: I started some debugging of this in https://github.com/fastlane/fastlane/issues/11087 with @corneliu-serediuc

**Comment by joshdholtz** [comment] 2018-03-13 21:39
This is a duplicate of #9363. Closing this one to keep everything in one 😊

**Closed by joshdholtz** 2018-03-13 21:39 UTC
Labels: status: waiting-for-reply
