### ISSUE TITLE
Feature request: add build number parameter to download_dsyms

### ISSUE THREAD

**Issue by NachoSoto** [fastlane/fastlane#3952] opened 2016-03-28 01:46 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I have dozens of builds in iTunes Connect, so running `download_dsyms` takes a long time. I'd like to be able to add a parameter so that I can run it for just the latest build number.

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
desc "Upload symbols to Crashlytics"
lane :symbols do
  download_dsyms
  upload_symbols_to_crashlytics
end
```

### Environment

- fastlane version (fastlane -v): `fastlane 1.68.0`.
- `rvm`.

**Comment by TKBurner** [comment] 2016-03-28 15:03
@NachoSoto Thanks for reaching out! I'll make sure the team looks this over. Thanks!

**Comment by KrauseFx** [comment] 2016-03-29 05:11
The idea for this action was to run it in a cron job every few hours or every night. Do you manually trigger it on your machine? If so, any reason why you don't want to run it on a CI? 
Would https://github.com/fastlane/fastlane/pull/3967/files help you?

**Comment by revile** [comment] 2016-03-29 20:29
My use case for this is I run `download_dsyms` followed by `upload_symbols_to_crashlytics` when I'm releasing a build, and I wanted to specify to only download the dSYMs for the build I am releasing.

I didn't realise this was intended to be run via cron or something.

**Comment by NachoSoto** [comment] 2016-03-30 22:15
Yeah I think both usages are totally valid. Personally I do the same as @revile: I just want to upload them on a one by one basis, though I'm glad I can also run this for *all* versions (in case Apple designs to recompile everything – which they seem to do even if the setting is disabled).

**Comment by KrauseFx** [comment] 2016-04-04 07:16
Fixed with https://github.com/fastlane/fastlane/pull/3967/

**Closed by KrauseFx** 2016-04-04 07:16 UTC
Labels: fastlane, feature
