### ISSUE TITLE
Match repository getting huge!

### ISSUE THREAD

**Issue by adamtester** [fastlane/fastlane#8917] opened 2017-04-19 16:07 UTC
Hello

We are using fastlane match for a lot of apps, and it seems to change every certificate every time match is run, so for example the last commit match did changed 384 files, because of this the repo gains about 5mb in size each time and we just hit 1gb.

Is there anything I can do to make it only push the ones it generates rather than the whole lot? Or is this to do with how the encryption works?

The only flag we are using is `shallow_clone`

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "net.xxxx.app01" # The bundle identifier of your app
apple_id "xxxxxx" # Your Apple email address
team_id "xxxx"  # Developer Portal Team ID
```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.24.0  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.4.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.26       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.3       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2017-04-19**
</details>

**Comment by KrauseFx** [comment] 2017-04-19 17:46
Argh, that's not good. The problem is that _match_ by default re-encrypts all certs/profiles, causing it to change on git. I'm not sure if that's something we can easily fix though

**Comment by hjanuschka** [comment] 2017-04-19 18:24
possible duplicate of https://github.com/fastlane/fastlane/issues/8793#issuecomment-292311108

as mentioned there i think introducting a new option - to bypass encryption/decryption should solve it.

with the right warning-notice i think this should solve the problems of the super-large-enterprise users 👍 

@KrauseFx are you fine, with that? (i would do a PR)

**Comment by hjanuschka** [comment] 2017-04-20 05:44
hey 🙌  folks i prepared a PR: https://github.com/fastlane/fastlane/pull/8919
i would love to hear feedback from you if the propsed solution is feasible for you.

**Comment by evilDave** [comment] 2017-06-07 00:58
Is there any plan to fix this? It's now more than a minute to run match, our repo is only 50MB as there are 30 odd profiles in there for all our app brands, environments, notifications etc. Does it do a new clone each time? Could there just be a pull instead? Or am I misunderstanding how this works?

**Comment by evilDave** [comment] 2017-06-07 01:03
So yeah, it's certainly not just with 1000s of apps. There are 6 apps, some with different profiles for dev, beta, stage, test, and live. All with a notifications profile. Adds up to 30. Have seen it getting slower and slower to the point where match takes nearly 2 minutes to run. Adding a device to all of the adhoc profiles takes about 30 minutes.

**Comment by adamtester** [comment] 2017-06-07 08:29
@evilDave don't forget to use `shallow_clone`

A different approach would be to do a reset after each run of match, as the history is useless
https://stackoverflow.com/a/13102849

**Comment by lacostej** [comment] 2017-06-07 08:35
is there a reason why match doesn't use `shallow_clone` by default?

**Comment by evilDave** [comment] 2017-06-07 13:26
I'll give shallow clone a go.

As for resetting, wouldn't the commits still be there?

Are other people just not getting this problem? I guess I've got about 150 commits to the repo with modifying capabilities and adding devices - repo size really multiplies.

**Comment by adcuz** [comment] 2017-06-07 13:45
This is an issue for me too, our repo is approaching 2GB. Watching with
interest.

**Comment by hjanuschka** [comment] 2017-06-07 14:16
the problem is the encryption, as every file changes every time.
to resolve this you can:
> handle with care:

  * clone repo to safe place
  * delete repo on the server
  * recreate empty repo
  * clone empty repo
  * remove `.git` from prev. cloned repo in safe place
  * copy over the files
  * `git add` them - `commit`  and `push`

this should shrink it.

however the problem will come back, as it grows in the future.


for really large repo's - you could upvote this: https://github.com/fastlane/fastlane/pull/8919
which adds a flag to disable encryption (🔥) - then each incremental commit is very small, as only a few files really change.

**Comment by evilDave** [comment] 2017-06-07 21:29
I think disabling encryption, particularly for "more enterprisey" users, seems like the wrong idea. 
The more I think about this issue, the less I think git is a good tool for storing these assets. I mean I get it, we have git, we know git, let's use git. But in this case, the history is not needed, just the hosting. Some way to bypass that (and the link above, now that I've read it properly and noticed the 'git gc' in there, might work as suggested) is good but in the end maybe we are just using the wrong tool. If it does work though, another option might be to modify match to do it by default or by option.

**Comment by evilDave** [comment] 2017-06-07 21:32
Why exactly does match encrypt all of the certs and profiles again? Maybe that can be changed? Even so, the history is useless. The cert or profile has changed and an old one won't work anyway.

**Comment by evilDave** [comment] 2017-06-08 01:41
--shallow_clone makes it better: 30 seconds in lieu of 1:30.
I suppose the repo is still getting huge on github but I care less about that.

**Comment by lacostej** [comment] 2017-06-08 09:10
I don't think we should remove encryption.

Git is for sure n't the best storage method as we are not interested in all history and it has capacity issues. But I suspect we have to stick to it for a while.

It might be possible to encrypt only what we need. But I am not sure how this can be achieved easily. Because of the history and growing repo size, it might still cause issues (not sure how in practice though). For people with 1000 of apps, for sure.

A simpler alternative is as @hjanuschka wrote earlier is to provide a way rewrite the git history. This could be risky if several git push operations are going on simultaneously. We could write a `match prunehistory` or even a more generic `gitprunerepohistory`command for example that could contain several safe guards to reduce that risk.

A long term solution would have been for the storage backend to be flexible. Think s3 or whatever.

**Comment by slhodson969** [comment] 2017-07-11 11:10
We was also having an issue like this. Our repo had reached a size of 200MB and for some reason, our connection was always very slow (~200kb/s) when cloning the repo which made the cloning take around 20-30 minutes. It was a pack file within the .git folder that was causing the size to be so big. I tried many things but the following commands seem to have resolved the issue and now cloning the repository takes seconds rather than minutes.

`$ git reflog expire --expire=now --all`
`$ git repack -ad`
`$ git gc --prune=now`
`$ git push --all --force`
`$ git push --tags --force`

Hopefully this helps others.

**Closed** 2017-09-18 11:21 UTC
Labels: status: auto-closed, status: waiting-for-reply

**Comment by KrauseFx** [comment] 2017-10-03 12:31
Hey everyone, the new release is live, can you update and let us know if that works for you? You might want to squash/clear the history of the repo.

**Comment by WilliamIzzo83** [comment] 2017-10-18 07:53
Hi! Someone happens to know if there is a way to clear history and mantain branches as they are (need this cause I'm using the match's branch feat)?
