### ISSUE TITLE
Google Api Error: multiApkDowngradedDevice

### ISSUE THREAD

**Issue by corneliu-serediuc** [fastlane/fastlane#11087] opened 2017-12-01 12:20 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I have initially uploaded to Google Play a build with a randomly created high version number in the Alpha Channel. Now, whenever I want to push a new build to Google Play with fastlane, I get the following error:

```
INFO [2017-12-01 12:58:49.41]: {:PLATFORM_NAME=>nil, :LANE_NAME=>"deploy_googleplay"}
ERROR [2017-12-01 12:58:49.41]: Google Api Error: multiApkDowngradedDevice:

Devices with version 355826070 of this app would be downgraded to version 2194 if they met the following criteria: [(API_LEVEL in range 21-0 AND RELEASE_TRACK containing any of each of [[ALPHA]] AND SCREENS containing any of each of [[small, normal, large, xlarge]] AND NATIVE_PLATFORM containing any of each of [[armeabi-v7a]] AND GL_ES_VERSION in range 131072-0 AND FEATURES containing all of [android.hardware.FAKETOUCH, android.hardware.LOCATION, android.hardware.CAMERA, android.hardware.camera.FLASH, android.hardware.WIFI])].
```

Nevertheless, I can upload the build manually via Google Play Console. **This means I cannot automate the deployment of an Android build.**

I even wrote to Google Play Developer Support and asked them to remove the wrong high-value-version-builds, but they cannot do that. This is the response I got from them:

> At this time, we do not support the deletion of certain APK due to the regulations of our policy. In this case, I'm afraid I cannot delete the APKs in Alpha track for you.

There are similar issues that (for some unknown reason) were closed, but people are still complaining about it. 

### Captured Output

Command Used: `supply`
<details><summary>Output/Log</summary>

```


+-------------------------+-----------------------------------------------------------+
|                              Summary for supply 2.68.0                              |
+-------------------------+-----------------------------------------------------------+
| json_key                | ~/Desktop/Google Play Android Developer.json |
| package_name            | com.dummy.dummy                                      |
| apk                     | artifacts/android/release/com.dummy.dummy-Signed.apk |
| track                   | alpha                                                     |
| skip_upload_metadata    | true                                                      |
| skip_upload_images      | true                                                      |
| skip_upload_screenshots | true                                                      |
| validate_only           | false                                                     |
| check_superseded_tracks | false                                                     |
| skip_upload_apk         | false                                                     |
+-------------------------+-----------------------------------------------------------+


+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 💥   | supply                              | 14          |
| 3    | notification                        | 0           |
+------+-------------------------------------+-------------+



```

</details>

### Environment

<details><summary>Output/Log</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.12.6                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.14.1                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.12.6 (16G1036)                                     |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.1                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.68.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.3        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.7.7        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.4       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.5       |
</details>

**Comment by janpio** [comment] 2017-12-01 17:46
Can you post more information what command you are executing, what `Fastfile` is used, the complete output you are getting with `--verbose`, please?

I tried to find out more about the error, but it seems to be returned directly from Google's API:
https://github.com/fastlane/fastlane/blob/ce07dd85af5dad2525c9844de59180f90b687d6c/supply/lib/supply/client.rb#L369
This means _if_ there is something _fastlane_ can change, it has to be in the options and parameters used in the API call.

**Comment by corneliu-serediuc** [comment] 2017-12-04 09:49
Thank you @janpio for responding. I am not familiar with the Google Play API, but since the apk upload with a higher version is possible via Google Play Console without errors or even warnings, I assume it should be possible via the API.

Is there a proper way to capture the full API call of a Google Play Console action without using network sniffing tools like Fiddler or Wireshark?

**Comment by janpio** [comment] 2017-12-04 12:05
> ... I assume it should be possible via the API.

Assuming is never a good idea with Google APIs ;)

> Is there a proper way to capture the full API call of a Google Play Console action without using network sniffing tools like Fiddler or Wireshark?

Good question. `client.rb` only hands off to the Google API, and for the Google API I couldn't find any (usable) documentation. I would probably try to debug the `fastlane` code first to see what exactly is handed over to the Google API, then continue to see what is going in there.

But what you could do trivially: 
1. Run your lane with `--verbose`. Interesting additional output?
2. Try the lane with `validate_only` for supply (and `--verbose`). What happens?

**Comment by corneliu-serediuc** [comment] 2017-12-04 20:54
Hi @janpio ! Below is the output for your second request (2). I hope it helps.

```
$ fastlane deploy_googleplay --verbose

/Library/Ruby/Gems/2.0.0/gems/fastimage-2.1.0/lib/fastimage.rb:67: warning: already initialized constant URI::DEFAULT_PARSER
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/common.rb:545: warning: previous definition of DEFAULT_PARSER was here
[21:42:59]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
DEBUG [2017-12-04 21:43:01.58]: Checking if there are any plugins that should be loaded...
WARN [2017-12-04 21:43:01.85]: You require a gem, if this is a third party gem, please use `fastlane_require 'time'` to ensure the gem is installed locally
WARN [2017-12-04 21:43:01.85]: You require a gem, if this is a third party gem, please use `fastlane_require 'commander'` to ensure the gem is installed locally
WARN [2017-12-04 21:43:01.85]: You require a gem, if this is a third party gem, please use `fastlane_require 'pathname'` to ensure the gem is installed locally
INFO [2017-12-04 21:43:01.88]: -------------------------------------------------
INFO [2017-12-04 21:43:01.88]: --- Step: Verifying required fastlane version ---
INFO [2017-12-04 21:43:01.88]: -------------------------------------------------
INFO [2017-12-04 21:43:01.88]: Your fastlane version 2.68.0 matches the minimum requirement of 2.63.0  ✅
INFO [2017-12-04 21:43:01.88]: Driving the lane 'deploy_googleplay' 🚀
INFO [2017-12-04 21:43:01.91]: --------------------
INFO [2017-12-04 21:43:01.91]: --- Step: supply ---
INFO [2017-12-04 21:43:01.91]: --------------------

+-------------------------+-----------------------------------------------------------+
|                              Summary for supply 2.68.0                              |
+-------------------------+-----------------------------------------------------------+
| json_key                | ~/Desktop/Google Play Android Developer-75eb1bfea184.json |
| package_name            | com.xxx.yyy                                      |
| apk                     | artifacts/android/release/com.xxx.yyy-Signed.apk |
| track                   | alpha                                                     |
| skip_upload_metadata    | true                                                      |
| skip_upload_images      | true                                                      |
| skip_upload_screenshots | true                                                      |
| validate_only           | true                                                      |
| check_superseded_tracks | false                                                     |
| skip_upload_apk         | false                                                     |
+-------------------------+-----------------------------------------------------------+

DEBUG [2017-12-04 21:43:02.50]: Fetching a new access token from Google...
INFO [2017-12-04 21:43:04.75]: Preparing apk at path 'artifacts/android/release/com.xxx.yyy-Signed.apk' for upload...
INFO [2017-12-04 21:43:15.40]: Updating track 'alpha'...
INFO [2017-12-04 21:43:15.68]: Validating all changes with Google Play...
INFO [2017-12-04 21:43:16.62]: 
(╯°□°）╯︵ ┻━┻

INFO [2017-12-04 21:43:16.64]: --------------------------
INFO [2017-12-04 21:43:16.64]: --- Step: notification ---
INFO [2017-12-04 21:43:16.64]: --------------------------
WARN [2017-12-04 21:43:16.85]: Lane Context:
INFO [2017-12-04 21:43:16.85]: {:PLATFORM_NAME=>nil, :LANE_NAME=>"deploy_googleplay"}
ERROR [2017-12-04 21:43:16.85]: Google Api Error: multiApkDowngradedDevice: Devices with version 355826070 of this app would be downgraded to version 2196 if they met the following criteria: [(API_LEVEL in range 21-0 AND RELEASE_TRACK containing any of each of [[ALPHA]] AND SCREENS containing any of each of [[small, normal, large, xlarge]] AND NATIVE_PLATFORM containing any of each of [[armeabi-v7a]] AND GL_ES_VERSION in range 131072-0 AND FEATURES containing all of [android.hardware.FAKETOUCH, android.hardware.LOCATION, android.hardware.CAMERA, android.hardware.camera.FLASH, android.hardware.WIFI])].
INFO [2017-12-04 21:43:16.88]: Successfully generated documentation at path '/xxx/yyy/fastlane/README.md'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 💥   | supply                              | 14          |
| 3    | notification                        | 0           |
+------+-------------------------------------+-------------+

ERROR [2017-12-04 21:43:16.89]: fastlane finished with errors

#######################################################################
# fastlane 2.68.1 is available. You are on 2.68.0.
# You should use the latest version.
# Please update using `sudo gem install fastlane`.
#######################################################################

2.68.1 Improvements
* [Spaceship] Ability to use existing IAP screenshots (#10903) via Kevin Cornbower

* Update "you can do this" label search URL (#11102) via James Sherlock

* Revert changes to signingStyle, fixes #11073 (#11100) via Manu Wallner

* [docs] link to CONTRIBUTING from YourFirstPR (#11103) via Jan Piotrowski

* [appium] Support appium android (#11063) via Yusuke Hosonuma

* Update the anchor in Circle.md (#11075) via Alexey

Please update using `sudo gem install fastlane`
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.68.0/fastlane_core/lib/fastlane_core/ui/interface.rb:131:in `user_error!': [!] Google Api Error: multiApkDowngradedDevice: Devices with version 355826070 of this app would be downgraded to version 2196 if they met the following criteria: [(API_LEVEL in range 21-0 AND RELEASE_TRACK containing any of each of [[ALPHA]] AND SCREENS containing any of each of [[small, normal, large, xlarge]] AND NATIVE_PLATFORM containing any of each of [[armeabi-v7a]] AND GL_ES_VERSION in range 131072-0 AND FEATURES containing all of [android.hardware.FAKETOUCH, android.hardware.LOCATION, android.hardware.CAMERA, android.hardware.camera.FLASH, android.hardware.WIFI])]. (FastlaneCore::Interface::FastlaneError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.68.0/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.68.0/supply/lib/supply/client.rb:369:in `rescue in call_google_api'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.68.0/supply/lib/supply/client.rb:367:in `call_google_api'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.68.0/supply/lib/supply/client.rb:111:in `validate_current_edit!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.68.0/supply/lib/supply/uploader.rb:32:in `perform_upload'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.68.0/fastlane/lib/fastlane/actions/upload_to_play_store.rb:21:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.68.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.68.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.68.0/fastlane/lib/fastlane/runner.rb:231:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.68.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.68.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.68.0/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.68.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:165:in `block in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.68.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.68.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.68.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.68.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.68.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.68.0/fastlane/lib/fastlane/lane_manager.rb:54:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.68.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.68.0/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.68.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.68.0/fastlane/lib/fastlane/commands_generator.rb:304:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.68.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.68.0/fastlane/lib/fastlane/cli_tools_distributor.rb:75:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.68.0/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'

```

**Comment by janpio** [comment] 2017-12-05 11:48
Hm, so again:

```
INFO [2017-12-04 21:43:15.68]: Validating all changes with Google Play...
INFO [2017-12-04 21:43:16.62]: 
(╯°□°）╯︵ ┻━┻
...
ERROR [2017-12-04 21:43:16.85]: Google Api Error: multiApkDowngradedDevice: Devices with version 355826070 of this app would be downgraded to version 2196 if they met the following criteria: [(API_LEVEL in range 21-0 AND RELEASE_TRACK containing any of each of [[ALPHA]] AND SCREENS containing any of each of [[small, normal, large, xlarge]] AND NATIVE_PLATFORM containing any of each of [[armeabi-v7a]] AND GL_ES_VERSION in range 131072-0 AND FEATURES containing all of [android.hardware.FAKETOUCH, android.hardware.LOCATION, android.hardware.CAMERA, android.hardware.camera.FLASH, android.hardware.WIFI])].
```

Lets try to reformat that error message:

```
[(
 API_LEVEL in range 21-0 
 AND RELEASE_TRACK containing any of each of [[ALPHA]] 
 AND SCREENS containing any of each of [[small, normal, large, xlarge]] 
 AND NATIVE_PLATFORM containing any of each of [[armeabi-v7a]] 
 AND GL_ES_VERSION in range 131072-0 
 AND FEATURES containing all of [android.hardware.FAKETOUCH, android.hardware.LOCATION, android.hardware.CAMERA, android.hardware.camera.FLASH, android.hardware.WIFI]
)]
```

which indeed does make sense if you uploaded something before in the alpha lane.

> Nevertheless, I can upload the build manually via Google Play Console.

Where and how exactly are you uploading the build in Google Play Console?
Where and how does it appear afterwards?

**Comment by corneliu-serediuc** [comment] 2017-12-05 14:23
Hi again, @janpio!

Below are the steps to uploading the build on Google Play Console:

1. Sign in to Google Play Console.
2. In "All applications" are, select my application.
3. In the left menu, select "Release management".
4. From the sub-menu, select "App releases".
5. Select "MANAGE ALPHA" from the main area.
6. Select "CREATE RELEASE" in the right-upper corner.
7. In the "APKs to add" area, select "BROWSE FILES" and navigate to my signed apk file.
8. Add some content to "What's new in this release?" area.
9. Press "REVIEW" at the end of the form.
10. Press "Start rollout".

By following these steps, I can successfully upload and publish a new build in the Alpha channel.

**Comment by janpio** [comment] 2017-12-05 15:04
That means, in the web UI you can upload an app to the alpha lane with Version code 2194 although you had an app with Version code 131072 before? Does this show in the Artifact library as well?

I get an error message on rollout if I try to do something like that (version code 3 is currently published on alpha lane, was trying to create a new release with verison code 1 apk):

![image](https://user-images.githubusercontent.com/183673/33613775-c400b0ba-d9d5-11e7-97cf-0fae448e5909.png)
![image](https://user-images.githubusercontent.com/183673/33613797-d7a98a42-d9d5-11e7-991a-6922b44f77d3.png)

As expected and what the API would return via an error message as above I think.

**Comment by corneliu-serediuc** [comment] 2017-12-05 15:27
I have been doing this since September. See images below:

VersionCode: 355826070
PublishDate: Sept 19, 2017

![screen shot 2017-12-05 at 16 23 41](https://user-images.githubusercontent.com/2992106/33614905-eb24e67c-d9d8-11e7-956f-83366ec42f1f.png)

VersionCode: 20
PublishDate: Sept 26, 2017

![screen shot 2017-12-05 at 16 24 37](https://user-images.githubusercontent.com/2992106/33614911-f0d16992-d9d8-11e7-909a-3cee9f78b16c.png)

**Comment by janpio** [comment] 2017-12-05 15:36
Ok, but this adds another dimension: 
The version name is different. 
I will have to test that separately.

Any other idea why Google Play web UI could _not_ have a problem with that higher version code in your case?

**Comment by corneliu-serediuc** [comment] 2017-12-05 15:51
Nope!

I am using exactly the same apk file built with a Cake script and I am using the MSBuild command to build it. That's the weird thing about it. I have no idea why the web UI accepts the build.

Is there a way to specify with _supply_ the Version Name of an app? I thought this was embedded in the apk. Oder?

**Comment by janpio** [comment] 2017-12-05 16:15
Yes it is. I was just testing with two APKs that both have the same version name, so I have to see if that makes a difference now.

**Comment by corneliu-serediuc** [comment] 2017-12-06 16:38
Any new discoveries?

**Comment by janpio** [comment] 2017-12-06 16:46
Not working on this right now. Still have the tab open, so when I have some time I will take a look.

**Comment by theill** [comment] 2018-02-08 13:57
If you want to disable these releases you may consider including `check_superseded_tracks: false` with your `supply` command

**Comment by luigifilannino** [comment] 2018-03-05 14:32
@theill I have the same error with check_superseded_tracks: true.
I have a beta version app with 1.1.0 (versionName) and 3 (versionCode) already published. I want to publish a new beta version app with 1.2.0 (versionName) and 1 (versionCode). The error is:

/Users/vobadm/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.1/fastlane_core/lib/fastlane_core/ui/interface.rb:131:in `user_error!': [31m[!] Google Api Error: multiApkDowngradedDevice: Devices with version 3 of this app would be downgraded to version 1 if they met the following criteria: [(API_LEVEL in range 16-0 AND RELEASE_TRACK containing any of each of [[BETA]] AND SCREENS containing any of each of [[small, normal, large, xlarge]] AND NATIVE_PLATFORM containing any of each of [[armeabi-v7a]] AND FEATURES containing all of [android.hardware.screen.portrait, android.hardware.wifi, android.hardware.faketouch])].[0m (FastlaneCore::Interface::FastlaneError)
	from /Users/vobadm/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.1/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/vobadm/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.1/supply/lib/supply/client.rb:369:in `rescue in call_google_api'
	from /Users/vobadm/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.1/supply/lib/supply/client.rb:367:in `call_google_api'
	from /Users/vobadm/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.1/supply/lib/supply/client.rb:118:in `commit_current_edit!'
	from /Users/vobadm/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.1/supply/lib/supply/uploader.rb:36:in `perform_upload'
	from /Users/vobadm/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.1/fastlane/lib/fastlane/actions/upload_to_play_store.rb:21:in `run'
	from /Users/vobadm/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.1/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /Users/vobadm/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/vobadm/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.1/fastlane/lib/fastlane/runner.rb:231:in `block in execute_action'
	from /Users/vobadm/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Users/vobadm/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Users/vobadm/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.1/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /Users/vobadm/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.1/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:22:in `block (2 levels) in parsing_binding'
	from /Users/vobadm/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/vobadm/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/vobadm/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/vobadm/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/vobadm/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/vobadm/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.1/fastlane/lib/fastlane/lane_manager.rb:54:in `cruise_lane'
	from /Users/vobadm/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.1/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/vobadm/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.1/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /Users/vobadm/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/vobadm/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/vobadm/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Users/vobadm/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/vobadm/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
	from /Users/vobadm/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/vobadm/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.1/fastlane/lib/fastlane/commands_generator.rb:304:in `run'
	from /Users/vobadm/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/vobadm/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.1/fastlane/lib/fastlane/cli_tools_distributor.rb:75:in `take_off'
	from /Users/vobadm/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.68.1/bin/fastlane:20:in `<top (required)>'
	from /Users/vobadm/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/vobadm/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'

**Comment by theill** [comment] 2018-03-05 14:42
@luigifilannino You are not allowed to do that. You will always need to have a HIGHER `versionCode` within same track (e.g. if you upload a build in beta track, any update to the beta track will need to have a higher `versionCode`). The flag works if you are using different tracks e.g. if you have set a versionCode in an beta track which is higher than the production track.

In your case the versionCode needs to be at least 4.

**Comment by luigifilannino** [comment] 2018-03-05 14:48
Thank you @theill  :)

**Comment by joshdholtz** [comment] 2018-03-13 21:41
This is a duplicate of #9363. Closing this one to keep everything in one 😊 But also going to link to keep everything in the first issue created

**Closed by joshdholtz** 2018-03-13 21:41 UTC
Labels: tool: supply
