### ISSUE TITLE
Scan hangs until simulator is killed, Xcode 8, iOS 10 simulator

### ISSUE THREAD

**Issue by jshier** [fastlane/fastlane#5173] opened 2016-06-20 20:20 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Running scan under Xcode 8 hangs after tests are complete.
```
[16:16:38]: ▸ ✓ testExample (0.001 seconds)
[16:16:38]: ▸ 	 Executed 1 test, with 0 failures (0 unexpected) in 0.001 (0.003) seconds
[16:16:38]: ▸ 
[16:16:38]: ▸ Test Succeeded
```
If I manually quit the simulator, scan then prints the test output the the fastlane run continues.

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
  desc "Runs all the tests."
  lane :runTests do
    scan(
      configuration: "Debug",
      output_types: "junit",
      device: "iPhone 6s (10.0)",
    )
  end
```

### Environment

fastlane version (run `fastlane -v`):

```
fastlane -v
/Users/jshier/.rvm/gems/ruby-2.3.1@project/gems/commander-4.3.5/lib/commander/user_interaction.rb:334: warning: constant ::TimeoutError is deprecated
fastlane 1.95.0
```

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

Yes, through RVM.

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

Yes, RVM.

**Comment by chrisgibbs** [comment] 2016-06-21 16:49
I'm seeing the same thing. Any known workarounds?

**Comment by afehners** [comment] 2016-06-22 08:21
I'm seeing the same issue when capturing screenshots. Everything will hang at some point waiting for the test to run on the simulator. If I quit the simulator it pops open again and completes the run

**Comment by vpolouchkine** [comment] 2016-06-22 20:15
Thanks for the reports! We'll take a look.

**Comment by carsten-wenderdel** [comment] 2016-07-02 16:09
I have the same issue. A quick and dirty workaround might be the following script. First it tells the shell to kill all iOS simulators after 120 seconds and then runs `fastlane test`, assuming that within 120 seconds the tests all have run. For me it works, reports are created successfully after the kill.

`#!/bin/sh`
`/bin/sh -c "sleep 120 ; killall Simulator"`
`fastlane test`

**Comment by jshier** [comment] 2016-07-06 22:41
Still appears to be an issue using beta 2.

**Comment by jshier** [comment] 2016-07-17 07:17
A teammate wrote a Tcl `expect` script to workaround this issue:
```tcl
#!/usr/bin/env expect
#
# runTests.tcl - wrap the runTests lane, quit the simulator once tests are
# finished to allow it to continue.
#

proc kill_simulator {} {
  system killall Simulator 2> /dev/null || true
  exp_continue
}

set timeout -1

spawn -noecho bundle exec fastlane runTests

expect {
  -re "^.*Test.*Succeeded.*$" kill_simulator
  -re "^.*TEST.*FAILED.*$"    kill_simulator
  eof
}

lassign [wait] fastlane_pid spawn_id os_error_flag exit_status

if {$os_error_flag == 0} {
  exit $exit_status
} else {
  exit 1
}
```

**Comment by jshier** [comment] 2016-07-18 20:03
Still a problem in beta 3 / 1.98.

**Comment by TKBurner** [comment] 2016-07-18 20:17
@jshier Thanks for following up on this. Can you let me know if you have a sample project we can look at that is affected by this issue? That'd help a lot! Thanks so much 👍

**Comment by jshier** [comment] 2016-07-18 20:29
@TKBurner [Here you go](https://github.com/jshier/ScanHangTest). This is actually so easy to replicate any project will do it.

**Comment by TKBurner** [comment] 2016-07-18 20:37
@jshier Thanks! I've looped in the core team 👍

**Comment by mfurtak** [comment] 2016-07-28 15:17
Hi @jshier - we've recently released [`scan` 0.10.0](https://github.com/fastlane/fastlane/releases/tag/scan%2F0.10.0) and [`snapshot` 1.13.0](https://github.com/fastlane/fastlane/releases/tag/snapshot%2F1.13.0) with some improved workarounds behind a feature switch.

Do you mind updating your tools to the latest (`gem update scan snapshot`) and then run them with the the following environment variable set, like:

```
FASTLANE_EXPLICIT_OPEN_SIMULATOR=2 scan
```

or 

```
FASTLANE_EXPLICIT_OPEN_SIMULATOR=2 snapshot
```

The value **2** is significant there. You'll know you got it right if you see output like:

```
Explicitly opening simulator at /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app for device: iPhone 4s
```

After that, please let me know if this gets things working again for you. If not, complete output is always helpful. Thanks! 🚀

**Comment by johntmcintosh** [comment] 2016-07-28 15:34
Thanks @mfurtak ! I've been seeing this as well, and have a small test project that I'm working with. In my case, the issue is still occurring using `scan 0.10.0` and setting the explicit open flag. Output below. Please note the log delay in the timestamps of the log between "Test Succeeded" and the next line (10:29:17 to 10:31:09). It hung there until I quit the simulator manually. Please let me know if there's any other info that would be helpful to pass along. Thanks!

```
→ scan --version
scan 0.10.0

→ FASTLANE_EXPLICIT_OPEN_SIMULATOR=2 scan
[10:29:11]: xcodebuild -list -project FastlaneTesting.xcodeproj
2016-07-28 10:29:11.710 xcodebuild[81779:6456926] [MT] PluginLoading: Required plug-in compatibility UUID 1637F4D5-0B27-416B-A78D-498965D64877 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-07-28 10:29:12.563 xcodebuild[81791:6457000] [MT] PluginLoading: Required plug-in compatibility UUID 1637F4D5-0B27-416B-A78D-498965D64877 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs

+-----------------------+---------------------------+
|              Summary for scan 0.10.0              |
+-----------------------+---------------------------+
| clean                 | true                      |
| project               | FastlaneTesting.xcodeproj |
| scheme                | FastlaneTesting           |
| configuration         | Debug                     |
| device                | iPhone 6 (10.0)           |
| output_types          | junit                     |
| skip_slack            | true                      |
| code_coverage         | false                     |
| address_sanitizer     | false                     |
| skip_build            | false                     |
| output_directory      | ./fastlane/test_output    |
| buildlog_path         | ~/Library/Logs/scan       |
| open_report           | false                     |
| slack_only_on_failure | false                     |
| use_clang_report_name | false                     |
+-----------------------+---------------------------+

[10:29:13]: Killing all running simulators
[10:29:13]: Explicitly opening simulator at /Applications/Xcode-beta.app/Contents/Developer/Applications/Simulator.app for device: iPhone 6
[10:29:13]: $ set -o pipefail && env NSUnbufferedIO=YES xcodebuild -scheme FastlaneTesting -project FastlaneTesting.xcodeproj -configuration 'Debug' -destination 'platform=iOS Simulator,id=E4E259F5-74F4-488C-8FCE-D26641A0F0B8' clean build test | tee '/Users/jtm/Library/Logs/scan/FastlaneTesting-FastlaneTesting.log' | xcpretty 
[10:29:13]: ▸ Loading...
[10:29:14]: ▸ 2016-07-28 10:29:14.106 xcodebuild[81812:6457156] [MT] PluginLoading: Required plug-in compatibility UUID 1637F4D5-0B27-416B-A78D-498965D64877 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
[10:29:15]: ▸ Cleaning FastlaneTesting/FastlaneTesting [Debug]
[10:29:15]: ▸ Check Dependencies
[10:29:15]: ▸ Clean Succeeded
[10:29:15]: ▸ Building FastlaneTesting/FastlaneTesting [Debug]
[10:29:15]: ▸ Check Dependencies
[10:29:15]: ▸ Compiling ViewController.m
[10:29:15]: ▸ Compiling AppDelegate.m
[10:29:15]: ▸ Compiling main.m
[10:29:15]: ▸ Linking FastlaneTesting
[10:29:15]: ▸ Compiling Main.storyboard
[10:29:17]: ▸ Compiling LaunchScreen.storyboard
[10:29:17]: ▸ Processing Info.plist
[10:29:17]: Running Tests: ▸ Touching FastlaneTesting.app
[10:29:17]: ▸ Signing /Users/jtm/Library/Developer/Xcode/DerivedData/FastlaneTesting-btbzikhrsvpvciapfgiytbvmdrac/Build/Products/Debug-iphonesimulator/FastlaneTesting.app
[10:29:17]: ▸ Build Succeeded
[10:29:17]: ▸ 2016-07-28 10:29:17.262 xcodebuild[81812:6457156] [MT] IDETestOperationsObserverDebug: (170D85E8-77A6-43CD-872A-D9EA8FAA30A4) Beginning test session FastlaneTestingTests-170D85E8-77A6-43CD-872A-D9EA8FAA30A4 at 2016-07-28 10:29:17.260 with Xcode 8S174q on target <DVTiPhoneSimulator: 0x7fdca5698180> {
[10:29:17]: ▸ SimDevice: SimDevice : iPhone 6 (E4E259F5-74F4-488C-8FCE-D26641A0F0B8) : state={ Booted } deviceType={ SimDeviceType : com.apple.CoreSimulator.SimDeviceType.iPhone-6 } runtime={ SimRuntime : 10.0 (14A5309d) - com.apple.CoreSimulator.SimRuntime.iOS-10-0 }
[10:29:17]: ▸ } (10.0 (14A5309d))
[10:29:17]: ▸ 2016-07-28 10:29:17.262 xcodebuild[81812:6457293]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
[10:29:17]: ▸ /Users/jtm/Library/Developer/Xcode/DerivedData/FastlaneTesting-btbzikhrsvpvciapfgiytbvmdrac/Logs/Test/79953C70-158B-4BD7-9097-1159805A3DB0/Session-FastlaneTestingTests-2016-07-28_102917-Mt8y9R.log
[10:29:17]: ▸ Building FastlaneTesting/FastlaneTesting [Debug]
[10:29:17]: ▸ Check Dependencies
[10:29:17]: ▸ Building FastlaneTesting/FastlaneTestingTests [Debug]
[10:29:17]: ▸ Check Dependencies
[10:29:17]: ▸ Processing Info.plist
[10:29:17]: ▸ Linking FastlaneTestingTests
[10:29:17]: Running Tests: ▸ Touching FastlaneTestingTests.xctest
[10:29:17]: ▸ Signing /Users/jtm/Library/Developer/Xcode/DerivedData/FastlaneTesting-btbzikhrsvpvciapfgiytbvmdrac/Build/Products/Debug-iphonesimulator/FastlaneTesting.app/PlugIns/FastlaneTestingTests.xctest
[10:29:26]: ▸ All tests
[10:29:26]: ▸ Test Suite FastlaneTestingTests.xctest started
[10:29:26]: ▸ FastlaneTestingTests
[10:29:26]: ▸ ✓ testExample (0.001 seconds)
[10:29:26]: ▸ ◷ testPerformanceExample measured (0.000 seconds)
[10:29:26]: ▸ ✓ testPerformanceExample (0.336 seconds)
[10:29:26]: ▸ 	 Executed 2 tests, with 0 failures (0 unexpected) in 0.336 (0.338) seconds
[10:29:26]: ▸ 
[10:29:27]: ▸ Test Succeeded
+--------------------+-------+
|        Test Results        |
+--------------------+-------+
| Number of tests    | 2     |
| Number of failures | 0     |
+--------------------+-------+

[10:31:09]: Successfully generated report at '/fastlanetesting/FastlaneTesting/fastlane/test_output/report.junit'
```

**Comment by mfurtak** [comment] 2016-07-28 15:44
@johntmcintosh Interesting. That seems like a different pathology to the problem that this workaround has been trying to address.

When your hang occurs, what is the state of your simulator? Has it been terminated? Is it stuck trying to boot at a black screen?

Thanks for the info!

**Comment by johntmcintosh** [comment] 2016-07-28 15:56
I'm starting from a state with no simulator running. Fastlane launches the simulator and I see the app get launched. The tests run, then the host app is terminated, leaving the simulator open, and looking at the homescreen. 

![screen shot 2016-07-28 at 10 55 56 am](https://cloud.githubusercontent.com/assets/931283/17219701/e4160fda-54b1-11e6-99bb-dbf61b9f907b.png)

**Comment by mfurtak** [comment] 2016-07-28 16:04
Ah, interesting indeed. Yes, that's definitely different than what the flag is attempting to work around. I appreciate the info, and I'm curious if that's what @jshier is also seeing for this issue?

**Comment by carsten-wenderdel** [comment] 2016-07-28 16:11
Running `FASTLANE_EXPLICIT_OPEN_SIMULATOR=2 scan` I see exactly the same as @johntmcintosh 
Xcode 8 beta 3 and scan 0.10.0

**Comment by mfurtak** [comment] 2016-07-28 16:16
OK, I'm gathering that this is unrelated to other things I've been working on, so it'll take a new investigation from the top. I'll keep folks up-to-date with what I can find here!

**Comment by johntmcintosh** [comment] 2016-07-28 16:35
Thanks so much @mfurtak ! 

In the meantime, while we're in the process of migrating our project to Xcode 8, we have a feature branch that's being configured for Xcode 8 testing, and the remainder of the branches still being built with Xcode 7. To maintain CI compatibility across all branches, we need CI to just be able to `fastlane test` to run things. Building a bit on @jshier's awesome workaround script, I'm updating our Fastfile like this on our Xcode 8 branch, so that CI triggers the same `test` lane, which calls the tcl script, which triggers a second lane that does all our normal testing stuff, but wrapped in the script's handling of quitting the simulator when necessary.

```
platform :ios do

  lane :test do
    sh "./scripts/runTests.tcl"
  end

  lane :original_test do 
    xcversion(version: "8.0")
    scan(
      project: "FastlaneTesting.xcodeproj",
      scheme: "FastlaneTesting",
      configuration: "Debug",
    )
  end

end
```

Also, for anyone not using bundler and just calling fastlane directly, you can remove `bundle exec` from the `spawn` line in the script. For me, that line becomes

```
spawn -noecho fastlane original_test
```

**Comment by mfurtak** [comment] 2016-07-28 17:32
I've reproduced this locally.

**Comment by mfurtak** [comment] 2016-07-28 17:49
@johntmcintosh If you have a moment, could you give something a try for me? Taken from your build output above, could you run the following command in your project directory?

```
xcodebuild -scheme FastlaneTesting -project FastlaneTesting.xcodeproj -configuration 'Debug' -destination 'platform=iOS Simulator,id=E4E259F5-74F4-488C-8FCE-D26641A0F0B8' clean build test
```

My expectation is that it should succeed without hanging. If so, please then try:

```
xcodebuild -scheme FastlaneTesting -project FastlaneTesting.xcodeproj -configuration 'Debug' -destination 'platform=iOS Simulator,id=E4E259F5-74F4-488C-8FCE-D26641A0F0B8' clean build test | grep "TEST SUCCEEDED"
```

My finding is that the second command will hang forever when done, like with `scan`. Please let me know, thanks!

**Comment by johntmcintosh** [comment] 2016-07-28 19:02
@mfurtak you're expectation is exactly what I see. The first completes without hanging. The second hangs until I quit the simulator.

**Comment by mfurtak** [comment] 2016-07-28 20:03
OK, so it would seem that the new `xcodebuild` can't tolerate being piped to another command while running `build test`... which is pretty much at the core of what `scan` does. 😱 

I've filed this as [rdar://27595098](https://openradar.appspot.com/27595098)

**Comment by johntmcintosh** [comment] 2016-07-28 20:05
I stumbled across a similar thread from xcpretty a few minutes ago that seems to be tracking the same issue: https://github.com/supermarin/xcpretty/issues/227

**Comment by mfurtak** [comment] 2016-07-28 20:13
Yep, good find - it sounds the same. I've noted that mine likely duplicates theirs in my radar.

**Comment by johntmcintosh** [comment] 2016-08-01 19:00
@mfurtak with my test project, this appears to be resolved today by Xcode 8, beta 4.

**Comment by mfurtak** [comment] 2016-08-01 20:03
@johntmcintosh Nice - thanks for the heads-up! I will download it and check it out.

**Comment by mfurtak** [comment] 2016-08-01 21:25
Agreed, this appears to be fixed in beta 4! I'll close this for now, but folks can continue the conversation and we can reopen as needed 👍

**Closed by mfurtak** 2016-08-01 21:25 UTC
Labels: scan

**Comment by KrauseFx** [comment] 2016-08-02 00:24
This is great news, thanks for updating the issue 👍
