### ISSUE TITLE
Enterprise Account - produce login failed return Your session has expired.  Please log in.

### ISSUE THREAD

**Issue by TechGuyVN** [fastlane/fastlane#5384] opened 2016-07-14 04:37 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Everything work great till Today i have problem with same Enterprise Account, when use produce to create app in develope portal , it throw error.
I had researched a lot and see some people report this but nothing work with me. ([4981](https://github.com/fastlane/fastlane/issues/4981) [188](https://github.com/fastlane-old/sigh/issues/188) [3106](https://github.com/fastlane/fastlane/issues/3106)
Please help me solve this!.
##### Complete output when running fastlane, including the stack trace and command used

```
[11:26:22]: -------------------------------------------------
[11:26:22]: --- Step: Verifying required fastlane version ---
[11:26:22]: -------------------------------------------------
[11:26:22]: fastlane version valid
[11:26:22]: ------------------------------
[11:26:22]: --- Step: default_platform ---
[11:26:22]: ------------------------------
[11:26:22]: Driving the lane 'ios enterprise' 🚀
[11:26:22]: ---------------------
[11:26:22]: --- Step: produce ---
[11:26:22]: ---------------------

+----------------+------------------------+
|        Summary for produce 1.1.2        |
+----------------+------------------------+
| username       | xxxxx@xxx.vn    |
| app_identifier | vn.xxx.n1196.enter |
| language       | xxxx             |
| app_name       | H3Q Miki               |
| company_name   | H3Q Miki               |
| app_version    | 1.23                   |
| skip_itc       | true                   |
| sku            | 1468470382             |
| skip_devcenter | false                  |
| team_id        | 9Y437UYEPP             |
+----------------+------------------------+

[11:26:30]: Variable Dump:
[11:26:30]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios enterprise"}
[11:26:30]: {"responseId"=>"61ca829a-9340-466d-976f-b4d79eab112f", "resultCode"=>1100, "resultString"=>"authentication.failed", "userString"=>"Your session has expired.  Please log in.", "creationTimestamp"=>"2016-07-14T04:26:30Z", "protocolVersion"=>"QH65B2", "userLocale"=>"en_US", "requestUrl"=>"https://developerservices2.apple.com/services/QH65B2/listTeams.action", "httpCode"=>200}

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | produce                             | 7           |
+------+-------------------------------------+-------------+

[11:26:30]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Sigh: authentication.failed Your session has expired.  Please log in.
   https://github.com/fastlane/fastlane/issues/4981 [closed] 3 💬
   6 weeks ago

➡️  sigh: authentication.failed / Your session has expired.  Please log in.
   https://github.com/fastlane/fastlane/issues/4157 [closed] 16 💬
   2 weeks ago

➡️  [!] Apple provided the following error info: authentication.failed Your session has expired. Please log in.
   https://github.com/fastlane/fastlane/issues/4337 [closed] 2 💬
   25 Apr 2016

and 9 more at: https://github.com/fastlane/fastlane/search?q=Apple provided the following error info:
	authentication.failed
	Your session has expired.  Please log in.&type=Issues&utf8=✓

[!] Apple provided the following error info:
	authentication.failed
	Your session has expired.  Please log in.
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
 lane :enterprise do
    # match(type: "appstore")
    # snapshot
    ENV["FASTLANE_XCODE_LIST_TIMEOUT"] = "0"

    produce(
        username: 'xxx@xxx.vn',
        app_identifier: 'vn.xxx.n1196.enter',
        language: 'Vietnamese',
        app_name: 'H3Q Miki',
        company_name: 'H3Q Miki',
        app_version: '1.23',
        skip_itc: true
      )
    update_project_team(
    path: "platforms/ios/H3Q Miki.xcodeproj",
    teamid: "9Y437UYEPP"
    )
    sh "produce enable_services --push-notification"
    sh "pem -a  vn.xxx.n1196.enter -u xxx@xxx.vn -e /Users/macpro/Documents/Developer/xxx/1196/certificates"
    cert
    sigh(force: false,output_path:'/Users/macpro/Documents/Developer/xxx/1196/certificates')
    update_project_provisioning(
      xcodeproj: "platforms/ios/H3Q Miki.xcodeproj",
    )
    gym(scheme: 'H3Q Miki', project: "platforms/ios/H3Q Miki.xcodeproj",
      output_directory: "/Users/macpro/Documents/Developer/xxx/1196/Build/Enterprise",
      export_method: "enterprise",
      use_legacy_build_api: true,
      include_bitcode: false,
      clean: true
      )
    
    # frameit
  end
```

### Environment

fastlane version (run `fastlane -v`): fastlane 1.97.2

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? i use default macbook

**Comment by RustyKnight** [comment] 2016-07-14 06:23
Agreed, this was working the before yesterday, isn't now

`{"responseId"=>"ad491748-2152-424a-99f0-6aaa516b72fe", "resultCode"=>1100, "resultString"=>"authentication.failed", "userString"=>"Your session has expired.  Please log in.", "creationTimestamp"=>"2016-07-14T06:12:50Z", "protocolVersion"=>"QH65B2", "userLocale"=>"en_US", "requestUrl"=>"https://developerservices2.apple.com/services/QH65B2/listTeams.action", "httpCode"=>200}`

`AppFile` only contains the bundle identifier and apple id

```
app_identifier "xxx" # The bundle identifier of your app
apple_id "xxx" # Your Apple email address
```
(masked obviously)

`Gymfile`

```
scheme "xxx"
output_directory "./fastlane/builds"
configuration "Debug"
```

`Fastfile`

```
...
cert
sigh
gym
```

Building with Xcode 8 (with project configured for "manual" signing mode and "automatic" signing mode ... test separately obviously)

**Comment by prgnshptlklp** [comment] 2016-07-14 07:33
Getting same error as mentioned, Authentication failed.

Note: This error on produce is for enterprise accounts only, it works fine for normal developer accounts.

**Comment by sondremare** [comment] 2016-07-14 08:53
Getting the exact same error, we have enterprise account aswell. Even tried setting up a completely new user in the development program, got the same error.

**Comment by belyakove** [comment] 2016-07-14 08:54
Same error here. Also with enterprise account.

**Comment by deanrock** [comment] 2016-07-14 09:05
I have the issue with Apple ID which has access to a few developer accounts, but none of them is enterprise.

`sigh` works without a problem on another Apple ID which has access to the same developer accounts.

**Comment by sondremare** [comment] 2016-07-14 10:11
I can say that for me, giving the user iTunes Connect Admin rights worked for me :)

**Comment by TechGuyVN** [comment] 2016-07-14 10:14
@deanrock i think you need to post another isssued!
@sondremare  Can you explain more ? in my case i use Enterprise account, error not happen when use normal develope account.
Thanks for your investigate!

**Comment by sondremare** [comment] 2016-07-14 10:30
@TechGuyVN: Might be the wrong issue, as I am having problems with "match" and not "produce". 
But it seems like the sigh step is failing in exactly the same way for you as for me. 

I too am using an Enterprise account. In your developer portal you have a choice called "iTunes connect" which is where you apply for an app review when going to AppStore. Even though a user has access to the developer portal, access to iTunes connect is not given implicitely. So I added the user in question as an admin in iTunes Connect. And boom, stuff started working again.
Hope this helps you :)

**Comment by bencollier** [comment] 2016-07-14 10:31
We've got the same problem - enterprise account. PEM works fine but produce fails:

```
{"responseId"=>"8b76816d-e7fe-46be-a003-c44754425322", "resultCode"=>1100, "resultString"=>"authentication.failed", "userString"=>"Your session has expired.  Please log in.", "creationTimestamp"=>"2016-07-14T10:11:25Z", "protocolVersion"=>"QH65B2", "userLocale"=>"en_US", "requestUrl"=>"https://developerservices2.apple.com/services/QH65B2/listTeams.action", "httpCode"=>200}
```

**Comment by georgmay** [comment] 2016-07-14 11:12
We've got the same issue as well.

**Comment by michaeltansg** [comment] 2016-07-14 11:59
+1

**Comment by weibel** [comment] 2016-07-14 14:42
Same problem, we're not enterprise. This ticket seems related https://github.com/fastlane/fastlane/issues/5386

**Comment by danielwischer** [comment] 2016-07-14 15:49
+1

**Comment by tefinger** [comment] 2016-07-14 16:39
+1

**Comment by mkm12789** [comment] 2016-07-14 17:18
+1

**Comment by deanrock** [comment] 2016-07-14 19:25
I solved the problem with an account that only has developer accounts here: https://github.com/fastlane/fastlane/issues/5386#issuecomment-232766082 (not sure if it also applies to enterprise accounts).

It seems that adding this Apple ID account to iTunes Connect fixes the problem.

**Comment by pRizz** [comment] 2016-07-14 20:32
+1

**Comment by arunks** [comment] 2016-07-14 21:25
Adding the user to iTC worked. I added the user with a sales role in iTC, not necessarily an admin.

**Comment by jtjacka** [comment] 2016-07-15 00:04
+1.  We do not use iTC with out enterprise account, so it seems the workaround a few people have gotten to work, won't work for us.

**Comment by michaeltansg** [comment] 2016-07-15 03:01
It really does seem like you will need the Apple ID (that is associated to an App Store account) to have access to the iTunes connect. I managed to fix this by getting invited to the iTunes connect and responding to the T&C dialog.

Here's the context:
Apple ID #1 - (enterprise account + app store account - company)
Apple ID #2 - (app store account - personal)

Apple ID #1 is the one with the issue.

Since I wasn't able to be granted iTunes connect for Apple ID #1, I signed in using Apple ID #2 (as the agent), and grant Apple ID #1 as a sales role to my personal app store account.

And after that, fastlane init works fine.

If I then remove Apple ID #1 from the personal app store account and a fastlane step requires "Verifying if app is available on the Apple Developer Portal and iTunes Connect...", it will begin to fail again.

This sounds like a workaround for now. I hope this helps anyone who is investigating into the matter.

**Comment by bencollier** [comment] 2016-07-15 09:15
The workarounds above do work. We changed it ot use an account that has access to many developer / iTC teams and explicitly pass the team_id to produce.

Weird this is happening even when skip_itc is true.

**Comment by TechGuyVN** [comment] 2016-07-15 09:37
i Confirm that add Enterprise account to ITC will resolve this bug, for easy for other people to resolve this, here step to step:
1. Login to Itune Connect by Appstore account
2. Navigate to "User and Role"
3. Click button (+) right of Users label
4. Fill your email of Enterprise account and hit Next --> choose Role Admin ( i haven't try another role yet) --> Done
5. Log out this Acount
6. Login ITC by Enterprise Account
7. a Dialog show, just hit Accept
--> From now try rebuild by Fastlane, everything work perfect again!.

**Comment by bencollier** [comment] 2016-07-15 09:38
I wouldn't class this as a proper fix though? Is there not a better workaround?

**Comment by elianfish** [comment] 2016-07-26 09:48
Strange why enterprise accounts to be added to ITC

**Comment by stulevine** [comment] 2016-07-26 17:53
@TechGuyVN well, thank you for that.  Worked as expected.  Even though IMHO, it is a bit strange to have to do that.  Regardless, great solution!  I have my CI environment with Slack integration back up (and Hubot for triggering builds via slack)

**Comment by TKBurner** [comment] 2016-07-27 21:09
Hi all! The team are going to look into this, it seems to be a new cross tool issue. Thanks for your reports and we will let you know if we need more info!

**Comment by asfalcone** [comment] 2016-07-28 15:53
Thanks all for the reports and sorry that this is causing issues for so many of you. We're hoping to get to the bottom of this. 

Has anyone been able to go back to an older version of `fastlane` and `spaceship` (something before fastlane 1.97.2 and spaceship 0.28.0) and have their existing setup (without the workaround) able to login? I'm trying to triage this as a regression in our code or a change on the apple side that we need to investigate. 

Let me know!

**Comment by asfalcone** [comment] 2016-07-29 18:23
I think I have a fix for this issue. If you have a moment, please pull the code in [this PR](https://github.com/fastlane/fastlane/pull/5548) and `rake install` in the spaceship directory to test. Let me know if this fixes the issue for you! 👍

**Closed** 2016-07-30 22:27 UTC
Labels: bug, help wanted, produce

**Comment by KrauseFx** [comment] 2016-07-31 07:34
Hey everyone, @asfalcone and me did some more testing and we were able to reproduce the issue. We already pushed a new spaceship release: https://github.com/fastlane/fastlane/releases/tag/spaceship/0.29.1

Please update using `[sudo] gem update spaceship` or `bundle update` (if you use a `Gemfile`)

Please let us know if that fixes the problem 👍
