### ISSUE TITLE
Can't use FASTLANE_PASSWORD in Linux environment

### ISSUE THREAD

**Issue by stefanlenoach** [fastlane/fastlane#11690] opened 2018-01-24 22:52 UTC
Hello, I've set up Fastlane on an Amazon Linux box and would like bypass the password-ask every time I want to add a user to testflight. I tried adding the environment variable to the Fastfile: `ENV["FASTLANE_PASSWORD"] = my_password`
I also tried adding it to the local .env file and via using `fastlane fastlane-credentials add ...`. Still whenever I try to add a user to testflight it prompts me for a password. Is there some way I can get around this? 

EDIT: Added the output of `fastlane env`

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key | Value |
| fastlane | 2.78.0 |
| OS | Linux ip-172-31-31-53 4.9.76-3.78.amzn1.x86_64 #1 SMP Fri Jan 12 19:51:35 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |
| Ruby | 2.4.2 |
| Bundler? | true |
| Git | git version 2.13.6 |
| Installation Source | /usr/bin/fastlane |
| Host | Amazon Linux AMI release 2017.09
Kernel \r on an \m Linux ip-172-31-31-53 4.9.76-3.78.amzn1.x86_64 #1 SMP Fri Jan 12 19:51:35 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux (4.9.76-3.78.amzn1.x86_64) |
| Ruby Lib Dir | /usr/lib |
| OpenSSL Version | OpenSSL 1.0.2k  26 Jan 2017 |
| Is contained | false |
| Is homebrew | false |
| Is installed via Fabric.app | false |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
ENV["FASTLANE_PASSWORD"] = ****
# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end

```
</details>

<details><summary>`./Appfile`</summary>

```ruby
json_key_file "" # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name "" # e.g. com.krausefx.app
app_identifier 123456


```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.78.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| io-console                | 0.4.6        |
| CFPropertyList            | 2.3.6        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| babosa                    | 1.0.2        |
| bundler                   | 1.16.1       |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.60.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.14.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.0.3        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.13.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.4        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2018-01-24**
</details>

**Comment by KrauseFx** [comment] 2018-01-25 17:27
Passing as env should work on both Mac and Linux, are you sure it's related to the platform and not something else? Are you sure the env variable is properly set?

**Comment by stefanlenoach** [comment] 2018-01-25 17:35
I think so...you can check how I set it in the Fastfile ^. I also tried adding it in a local .env file as FASTLANE_PASSWORD = "****". I tried following the docs here: https://docs.fastlane.tools/advanced/. Is there something I'm missing?

**Comment by joshdholtz** [comment] 2018-03-13 14:19
@stefanlenoach I _think_ the issue is `.env` and the `Fastlfile` don't get "loaded" in until a lane has been called.

Calling `fastlane fastlane-credentials add ..` doesn't call a lane but actually calls a fastlane tool directly.

## Solution 1
You could do `ENV["FASTLANE_PASSWORD"] = my_password fastlane fastlane-credentials add ..`

## Solution 2
You could add `FASTLANE_PASSWORD` environment variable to your `.bashrc`

## Solution 3
Wait for my PR to get merged which loads `.env` files right away when any fastlane command is executed - https://github.com/fastlane/fastlane/pull/12047

**Closed** 2018-04-29 17:33 UTC
Labels: status: waiting-for-reply
