### ISSUE TITLE
Authentication credentials are missing or invalid. - Provide a properly configured and signed bearer token, and make sure that it has not expired

### ISSUE THREAD

**Issue by khoogheem** [fastlane/fastlane#19072] opened 2021-07-10 15:27 UTC
### New Issue Checklist

- [ x] Updated fastlane to the latest version
- [ x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Started receiving the `Authentication credentials are missing or invalid. - Provide a properly configured and signed bearer token, and make sure that it has not expired` message..  

We had not changed anything in our Fastlane and the API Keys have not been revoked.
I have even tested by creating a new API Key on the itunesConnect.

##### Command executed
```
      api_key = app_store_connect_api_key(
        key_id: "GXXXXXX",
        issuer_id: "69a6de85-xxxxxx-5b8c7c11a4d1",
        key_content: "-----BEGIN PRIVATE KEY-----\nMIqjg1/eUB\nLxxyWE/va\nBWxxxQW3zb\n-----END PRIVATE KEY-----",
        in_house: false
      )

      sigh(
        api_key: api_key,
        adhoc: true,
        force: true
      )
```

I have also tied to just use CI env var which no change.

##### Complete output when running fastlane, including the stack trace and command used
Authentication credentials are missing or invalid. - Provide a properly configured and signed bearer token, and make sure that it has not expired. Learn more about Generating Tokens for API Requests https://developer.apple.com/go/?id=api-generating-tokens

**Comment by khoogheem** [comment] 2021-07-10 15:38
I should probably mention the key is created with role `App Manager`

**Comment by crazymanish** [comment] 2021-07-10 19:07
Hi @khoogheem 

Can you try `sigh` using the **Admin** role? https://developer.apple.com/support/roles/
If you will face an issue with the Admin role too...requesting you to start a discussion here
https://github.com/fastlane/fastlane/discussions/categories/q-a
.
<img width="722" alt="Screenshot 2021-07-10 at 21 05 10" src="https://user-images.githubusercontent.com/5364500/125174024-aef30800-e1c2-11eb-8012-7dc83ab1f9d0.png">

**Comment by khoogheem** [comment] 2021-07-10 20:15
Same issue with Admin

**Comment by khoogheem** [comment] 2021-07-10 20:47
@crazymanish I think there is an issue regardless.. I tested by putting everything into a json so I could just run
`fastlane sigh --api_key_path fastlane/api_key_admin.json`
NO Duration set - Doesn't Work
Duration of 1200: Doesn't work
Duration of 500: 👍  works

**Comment by crazymanish** [comment] 2021-07-11 07:30
this is interesting...reopening

**Comment by formatCvt** [comment] 2021-07-11 13:12
same issue (with `latest_testflight_build_number(api_key_path: $api_key_path)`)

**Comment by IlyaKiselevKolibri** [comment] 2021-07-12 09:37
We are having the same issue using the key with the admin role:

```12:30:33  [11:30:36]: 🔓  Successfully decrypted certificates repo

12:30:33  [11:30:36]: Verifying that the certificate and profile are still valid on the Dev Portal...

12:30:33  [11:30:36]: Creating authorization token for App Store Connect API

12:30:34  [11:30:36]: #<Spaceship::UnauthorizedAccessError: Authentication credentials are missing or invalid. - Provide a properly configured and signed bearer token, and make sure that it has not expired. Learn more about Generating Tokens for API Requests https://developer.apple.com/go/?id=api-generating-tokens>```

**Comment by crazymanish** [comment] 2021-07-12 10:09
Okay, cool! I am not sure why this is causing this suddenly, don't have an AppStoreConnectAPI key to debug this issue. 🤪
I am tagging @joshdholtz for this issue! 😇

**Comment by MatejBalantic** [comment] 2021-07-12 10:27
We are seeing the same issue suddenly with a key that was working fine. It does look like an issue with Apple's API, given that I am unable to create a new token in the App Store Connect, seeing bunch of 500 errors in the developer console.

**Comment by dehlen** [comment] 2021-07-12 10:37
Just confirming that we recently experienced this issue as well.

**Comment by dehlen** [comment] 2021-07-12 10:44
Seems like AppStore Connect has some problems atm? I get an error message and can't see any apps when logging in via Safari.

**Comment by florieger** [comment] 2021-07-12 10:47
Same issue, AppStore Connect website shows error message instead of apps.

**Comment by florieger** [comment] 2021-07-12 11:19
Seems to be fixed.

**Comment by IlyaKiselevKolibri** [comment] 2021-07-12 11:47
Not sure if the AppStore Connect issue was related though, as for us the initial problem with the Auth is there since Friday evening.

**Comment by khoogheem** [comment] 2021-07-12 11:58
Right.. My issues started on my Thursday/Friday builds.. 

Sure it might still be an Apple Issue.. but what made no sense was the default durations just stopped  working.. and I could only get it to work with a duration of 500

**Comment by IlyaKiselevKolibri** [comment] 2021-07-12 12:05
Totally! I can confirm that duration of 500 also does the trick for us.

**Comment by crazymanish** [comment] 2021-07-12 12:52
Adding **500 seconds duration** sounds crazy workaround, but I don't surprise with Apple 🍏🍎 anymore 😇😂

**Comment by weakfl** [comment] 2021-07-13 10:18
Doesn't work for us, even with duration set to 500.

**Comment by cdoky** [comment] 2021-07-13 10:49
It does work for me
> Adding **500 seconds duration** sounds crazy workaround, but I don't surprise with Apple 🍏🍎 anymore 😇😂

**Comment by yakimant** [comment] 2021-07-13 12:47
We didn't change anything (like duration), but it started to work again.

**Comment by itismadhan** [comment] 2021-07-13 14:29
Can confirm that setting the duration to 500 fixes the issue.

**Comment by pvroosendaal** [comment] 2021-07-14 09:04
Adding 500 seconds duration works for us too.

**Comment by crazymanish** [comment] 2021-07-15 10:42
Hi all,
I am closing this as this seems to be a temporary Apple issue, if something crazy will happen again, maybe we can submit **Radar**? 🤔 (Radar project was a mess 5years ago when I work on macOS client in Apple 🤪)

btw, In my team, we don't use any duration and everything seems to work so far... 😉

**Closed by crazymanish** 2021-07-15 10:42 UTC
Labels: status: workaround available, topic: ConnectAPI

**Comment by jacksonsmith** [comment] 2021-07-16 14:54
> @crazymanish I think there is an issue regardless.. I tested by putting everything into a json so I could just run
> `fastlane sigh --api_key_path fastlane/api_key_admin.json`
> NO Duration set - Doesn't Work
> Duration of 1200: Doesn't work
> Duration of 800: Doesn't work
> Duration of 500: 👍 works

this work for us | paring with @fernandaaraujo

**Comment by jonbenk** [comment] 2021-07-20 14:29
Hi all,

I'm facing the same issue here. Does anyone know how to change the token session duration on the Azure DevOps extension for the Apple App Store? Would it be possible via additional fastlane arguments on the task or using an environment variable? Thanks in advance!

**Comment by styrken** [comment] 2021-08-01 19:22
Works for me too with duration 500 🥇

**Comment by ryanjwessel** [comment] 2021-09-08 16:34
My team was experiencing this issue when we had the duration set to `500`. We increased that value to `1200`, which solved it for a time, but now seem to be experiencing it again. 

Do we know what might be the root cause of this issue? Modifying the duration is a flaky solution, especially when deploying app versions via CI/CD.

**Comment by joshuawright11** [comment] 2021-09-18 04:05
Also encountered this; not exactly relevant since I'm using [GitHub actions](https://github.com/Apple-Actions/download-provisioning-profiles) but it seems like the same underlying issue.

For me a retrigger of the GitHub Actions workflow always works; wondering if it's something to do with a rate limit on Apple's side that returns an unhelpful error message.

**Comment by DuMaM** [comment] 2021-09-22 21:20
I'm facing this issue again since 5days...
what's it's interesting when I use app_store_connect_api_key again, then it works fine in second run...

**Comment by abdulbasit18** [comment] 2021-11-11 23:49
> @crazymanish I think there is an issue regardless.. I tested by putting everything into a json so I could just run `fastlane sigh --api_key_path fastlane/api_key_admin.json` NO Duration set - Doesn't Work Duration of 1200: Doesn't work Duration of 800: Doesn't work Duration of 500: 👍 works

@khoogheem Hi I am facing the same issue , but I don't understand where I can add this duration in fastfile and I don't understand the Json file solution 
    app_store_connect_api_key(
       key_id: "XXXXXXXXXXX",
       issuer_id: "XXXXXXXXXXXXXXXXXXXXXX",
       key_content: "XXXXXXXXXXXXXXXXX",
       
       is_key_content_base64: true,
       in_house: false #boolean value if team is Enterprise or not
     )


    # Get the required provisioning profiles
    bundle_identifiers.each do |identifier|
      sigh app_identifier: identifier,
           provisioning_name: provisioning_profile_name(identifier, export_method),
           adhoc: export_method == :adhoc,
           force: export_method == :adhoc
    end
  end

**Comment by wangdetong** [comment] 2021-12-30 13:16
## How to fundamentally solve this problem？
This problem started to appear around `November 15th`. 
Even if I set the `duration to 500`, this problem `occasionally occurs` when packaging. 
But if I call it again, the problem does not appear.
How to fundamentally solve this problem？


```ruby
    app_store_connect_api_key(
      key_id: key_id,
      issuer_id: issuer_id,
      key_content: key_content,
      duration: 500, # maximum 1200
      in_house: false # optional but may be required if using match/sigh
    )

```

**Comment by DuMaM** [comment] 2021-12-30 14:00
@wangdetong Take a look on @andersonvom PR 
https://github.com/fastlane/fastlane/pull/19502
I think it will solve this issues or at least reduce it. I'm also still facing this problem.

**Comment by wangdetong** [comment] 2021-12-31 06:05
> @wangdetong Take a look on @andersonvom #19502 I think it will solve this issues or at least reduce it. I'm also facing this problem for quite long time.

Thank you, I will try

**Comment by andersonvom** [comment] 2021-12-31 19:02
@DuMaM @wangdetong for what it's worth, after adding the changes from #19502 locally, my team has not seen any issues again: we can see in the logs that the failed requests are able to recover after a token refresh.
