### ISSUE TITLE
"curl: (22) The requested URL returned error: 403 Forbidden" in Travis-CI

### ISSUE THREAD

**Issue by Sega-Zero** [fastlane/fastlane#10323] opened 2017-09-13 15:30 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Today my travis builds fail randomly with "curl: (22) The requested URL returned error: 403 Forbidden" error. Haven't faced this issue before. I believe this is kind a regression from #10278

Is there a real need in WWDR installing on travis instances? They do their own patch:
> Fix WWDRCA Certificate
Unable to delete certificate matching "0950B6CD3D2F37EA246A1AAA20DFAADBD6FE1F75"security: AppleWWDRCA.cer: already in /Library/Keychains/System.keychain

Also, it's already included in macOS Sierra, so, is there a real need in this step? This failure is a bit annoying.

##### Complete output when running fastlane, including the stack trace and command used

```shell
[14:11:41]: ---------------------
[14:11:41]: --- Step: produce ---
[14:11:41]: ---------------------
+----------------+--------------------------------+
|           Summary for produce 2.56.0            |
+----------------+--------------------------------+
| app_identifier | com.app.id     |
| app_name       | Autogenerated com.app.id |
| skip_itc       | true                           |
| username       | [secure]               |
| sku            | [secure]                     |
| platform       | ios                            |
| language       | English                        |
| skip_devcenter | false                          |
| team_id        | [secure]                     |
| team_name      | [secure]     |
| itc_team_id    | [secure]                       |
+----------------+--------------------------------+
[14:11:44]: [DevCenter] App 'com.app.id' already exists, nothing to do on the Dev Center
[14:11:44]: -------------------
[14:11:44]: --- Step: is_ci ---
[14:11:44]: -------------------
[14:11:44]: --------------------------------------
[14:11:44]: --- Step: Switch to ios build lane ---
[14:11:44]: --------------------------------------
[14:11:44]: Cruising over to lane 'ios build' 🚖
[14:11:49]: -------------------
[14:11:49]: --- Step: match ---
[14:11:49]: -------------------
+-----------------------+----------------------------------------------+
|                       Summary for match 2.56.0                       |
+-----------------------+----------------------------------------------+
| git_branch            | master                                       |
| type                  | development                                  |
| app_identifier        | com.app.id                   |
| force_for_new_devices | true                                         |
| git_url               | [secure] |
| username              | [secure]                             |
| keychain_name         | ios-build.keychain                           |
| keychain_password     | ********                                     |
| readonly              | false                                        |
| team_id               | [secure]                                   |
| team_name             | [secure]                   |
| verbose               | false                                        |
| force                 | false                                        |
| skip_confirmation     | false                                        |
| shallow_clone         | false                                        |
| clone_branch_directly | false                                        |
| skip_docs             | false                                        |
| platform              | ios                                          |
+-----------------------+----------------------------------------------+
[14:11:49]: Cloning remote git repo...
[14:11:49]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[14:13:28]: 🔓  Successfully decrypted certificates repo
[14:13:28]: Verifying that the certificate and profile are still valid on the Dev Portal...
[14:13:29]: Installing certificate...
security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 403 Forbidden
[14:13:30]: Sending crash report...
[14:13:30]: The stack trace is sanitized so no personal information is sent.
[14:13:30]: To see what we are sending, look here: /Users/travis/.fastlane/latest_crash.json
[14:13:30]: Learn more at https://github.com/fastlane/fastlane#crash-reporting
[14:13:30]: You can disable crash reporting by adding `opt_out_crash_reporting` at the top of your Fastfile

+------------------+-----------+
|         Lane Context         |
+------------------+-----------+
| DEFAULT_PLATFORM | ios       |
| PLATFORM_NAME    | ios       |
| LANE_NAME        | ios auto  |
| PRODUCE_APPLE_ID |           |
| VERSION_NUMBER   | 1.0.0 |
| BUILD_NUMBER     | 1.0.0 |
+------------------+-----------+
[14:13:33]: Could not install WWDR certificate
+------+---------------------------------------------------------------+-------------+
|                                  fastlane summary                                  |
+------+---------------------------------------------------------------+-------------+
| Step | Action                                                        | Time (in s) |
+------+---------------------------------------------------------------+-------------+
| 1    | default_platform                                              | 0           |
| 2    | git_branch                                                    | 0           |
| 3    | Switch to ios beta lane                                       | 0           |
| 4    | is_ci                                                         | 0           |
| 5    | update_app_identifier                                         | 0           |
| 6    | produce                                                       | 3           |
| 7    | is_ci                                                         | 0           |
| 8    | Switch to ios build lane                                      | 0           |
| 💥   | match                                                         | 101         |
+------+---------------------------------------------------------------+-------------+
[14:13:33]: fastlane finished with errors
[!] Could not install WWDR certificate
```

### Environment

[14:13:32]: ▸ <details><summary>✅ fastlane environment ✅</summary>
[14:13:32]: ▸ ### Stack
[14:13:32]: ▸ | Key                         | Value                                                      |
[14:13:32]: ▸ | --------------------------- | ---------------------------------------------------------- |
[14:13:32]: ▸ | OS                          | 10.12.1                                                    |
[14:13:32]: ▸ | Ruby                        | 2.3.1                                                      |
[14:13:32]: ▸ | Bundler?                    | true                                                       |
[14:13:32]: ▸ | Git                         | git version 2.11.0                                         |
[14:13:32]: ▸ | Installation Source         | ~/build/company/iOS/vendor/bundle/ruby/2.3.0/bin/fastlane |
[14:13:32]: ▸ | Host                        | Mac OS X 10.12.1 (16B2555)                                 |
[14:13:32]: ▸ | Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.1/lib                               |
[14:13:32]: ▸ | OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                                |
[14:13:32]: ▸ | Is contained                | false                                                      |
[14:13:32]: ▸ | Is homebrew                 | false                                                      |
[14:13:32]: ▸ | Is installed via Fabric.app | false                                                      |
[14:13:32]: ▸ | Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                |
[14:13:32]: ▸ | Xcode Version               | 8.2                                                        |
[14:13:32]: ▸ ### System Locale
[14:13:32]: ▸ | Variable | Value       |   |
[14:13:32]: ▸ | -------- | ----------- | - |
[14:13:32]: ▸ | LANG     | en_US.UTF-8 | ✅ |
[14:13:32]: ▸ | LC_ALL   | en_US.UTF-8 | ✅ |
[14:13:32]: ▸ | LANGUAGE |             |   |
[14:13:33]: ▸ ### fastlane gems
[14:13:33]: ▸ | Gem      | Version | Update-Status |
[14:13:33]: ▸ | -------- | ------- | ------------- |
[14:13:33]: ▸ | fastlane | 2.56.0  | ✅ Up-To-Date  |
[14:13:33]: ▸ ### Loaded fastlane plugins:
[14:13:33]: ▸ **No plugins Loaded**
[14:13:33]: ▸ <details><summary><b>Loaded gems</b></summary>
[14:13:33]: ▸ | Gem                       | Version      |
[14:13:33]: ▸ | ------------------------- | ------------ |
[14:13:33]: ▸ | io-console                | 0.4.5        |
[14:13:33]: ▸ | CFPropertyList            | 2.3.5        |
[14:13:33]: ▸ | i18n                      | 0.8.6        |
[14:13:33]: ▸ | minitest                  | 5.10.3       |
[14:13:33]: ▸ | thread_safe               | 0.3.6        |
[14:13:33]: ▸ | tzinfo                    | 1.2.3        |
[14:13:33]: ▸ | activesupport             | 4.2.9        |
[14:13:33]: ▸ | public_suffix             | 2.0.5        |
[14:13:33]: ▸ | addressable               | 2.5.2        |
[14:13:33]: ▸ | babosa                    | 1.0.2        |
[14:13:33]: ▸ | bundler                   | 1.15.4       |
[14:13:33]: ▸ | claide                    | 1.0.2        |
[14:13:33]: ▸ | colored                   | 1.2          |
[14:13:33]: ▸ | colored2                  | 3.1.2        |
[14:13:33]: ▸ | highline                  | 1.7.8        |
[14:13:33]: ▸ | commander-fastlane        | 4.4.5        |
[14:13:33]: ▸ | declarative               | 0.0.10       |
[14:13:33]: ▸ | declarative-option        | 0.1.0        |
[14:13:33]: ▸ | unf_ext                   | 0.0.7.4      |
[14:13:33]: ▸ | unf                       | 0.1.4        |
[14:13:33]: ▸ | domain_name               | 0.5.20170404 |
[14:13:33]: ▸ | dotenv                    | 2.2.1        |
[14:13:33]: ▸ | excon                     | 0.59.0       |
[14:13:33]: ▸ | multipart-post            | 2.0.0        |
[14:13:33]: ▸ | faraday                   | 0.13.1       |
[14:13:33]: ▸ | http-cookie               | 1.0.3        |
[14:13:33]: ▸ | faraday-cookie_jar        | 0.0.6        |
[14:13:33]: ▸ | faraday_middleware        | 0.12.2       |
[14:13:33]: ▸ | fastimage                 | 2.1.0        |
[14:13:33]: ▸ | gh_inspector              | 1.0.3        |
[14:13:33]: ▸ | jwt                       | 1.5.6        |
[14:13:33]: ▸ | little-plugger            | 1.1.4        |
[14:13:33]: ▸ | multi_json                | 1.12.2       |
[14:13:33]: ▸ | logging                   | 2.2.2        |
[14:13:33]: ▸ | memoist                   | 0.16.0       |
[14:13:33]: ▸ | os                        | 0.9.6        |
[14:13:33]: ▸ | signet                    | 0.7.3        |
[14:13:33]: ▸ | googleauth                | 0.5.3        |
[14:13:33]: ▸ | httpclient                | 2.8.3        |
[14:13:33]: ▸ | mime-types-data           | 3.2016.0521  |
[14:13:33]: ▸ | mime-types                | 3.1          |
[14:13:33]: ▸ | uber                      | 0.1.0        |
[14:13:33]: ▸ | representable             | 3.0.4        |
[14:13:33]: ▸ | retriable                 | 3.1.1        |
[14:13:33]: ▸ | google-api-client         | 0.13.6       |
[14:13:33]: ▸ | json                      | 2.1.0        |
[14:13:33]: ▸ | mini_magick               | 4.5.1        |
[14:13:33]: ▸ | multi_xml                 | 0.6.0        |
[14:13:33]: ▸ | plist                     | 3.3.0        |
[14:13:33]: ▸ | rubyzip                   | 1.2.1        |
[14:13:33]: ▸ | security                  | 0.1.3        |
[14:13:33]: ▸ | slack-notifier            | 1.5.1        |
[14:13:33]: ▸ | terminal-notifier         | 1.8.0        |
[14:13:33]: ▸ | unicode-display_width     | 1.3.0        |
[14:13:33]: ▸ | terminal-table            | 1.8.0        |
[14:13:33]: ▸ | tty-screen                | 0.5.0        |
[14:13:33]: ▸ | word_wrap                 | 1.0.0        |
[14:13:33]: ▸ | nanaimo                   | 0.2.3        |
[14:13:33]: ▸ | xcodeproj                 | 1.5.1        |
[14:13:33]: ▸ | rouge                     | 2.0.7        |
[14:13:33]: ▸ | xcpretty                  | 0.2.8        |
[14:13:33]: ▸ | xcpretty-travis-formatter | 0.0.4        |
[14:13:33]: ▸ | ffi                       | 1.9.18       |
[14:13:33]: ▸ | mustache                  | 0.99.8       |
[14:13:33]: ▸ | mini_portile2             | 2.2.0        |
[14:13:33]: ▸ | nokogiri                  | 1.8.0        |
[14:13:33]: ▸ | redcarpet                 | 3.4.0        |
[14:13:33]: ▸ | rb-fsevent                | 0.10.2       |
[14:13:33]: ▸ | rb-inotify                | 0.9.10       |
[14:13:33]: ▸ | sass-listen               | 4.0.0        |
[14:13:33]: ▸ | sass                      | 3.5.1        |
[14:13:33]: ▸ | jazzy                     | 0.0.14       |
[14:13:33]: ▸ </details>
[14:13:33]: ▸ *generated on:* **2017-09-13**
[14:13:33]: ▸ </details>

**Comment by ohayon** [comment] 2017-09-14 17:02
Hey @Sega-Zero! Would you mind sharing the output of running that same lane with `--verbose` so we can see the stack trace and some more context around the issue? Thank you!! 🚀

**Comment by Sega-Zero** [comment] 2017-09-14 17:11
This happens very random. Caught that 4 times yesterday and none today. Cannot turn on `--verbose` forever, travis log drops all info after 10k lines, that's not comfortable for my team.

**Comment by ohayon** [comment] 2017-09-14 19:19
Ah totally understand that that is really frustrating. Apple's APIs have been having intermittent issues this week. Probably due to some internal changes they are making for the new releases. I'm glad to hear that you are not getting it today. I am going to close this issue for now, but please reopen it with the stack trace when if/when it reproduces. Thanks a lot! 🐙

**Closed by ohayon** 2017-09-14 19:19 UTC
