### ISSUE TITLE
List of testers doesn't contain Latest Version and Latest Install Date info

### ISSUE THREAD

**Issue by SebastianOsinski** [fastlane/fastlane#4314] opened 2016-04-22 05:49 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

`pilot list` contains names and emails of internal testers, but there are 0 devices listed and both 'Latest version' and 'Latest Install Date' columns are empty
##### Complete output when running fastlane, including the stack trace and command used
(Internal Testers list has reduced number of rows. In reality, there are more rows in this table, but they all look the same - 0 devices and empty two last columns)
`pilot list`
``` 
[07:20:14]: Login to iTunes Connect (sebastian@xxx.com)
[07:20:18]: Login successful
+-----------+-----------+-------------------------------+---------+----------------+---------------------+
|                                            Internal Testers                                            |
+-----------+-----------+-------------------------------+---------+----------------+---------------------+
| First     | Last      | Email                         | Devices | Latest Version | Latest Install Date |
+-----------+-----------+-------------------------------+---------+----------------+---------------------+
| John      | Doe       | john@xxx.com                  | 0       |                |                     |
| Jane      | Doe       | jane@xxx.com                  | 0       |                |                     |
| Sebastian | Osiński   | sebastian@xxx.com             | 0       |                |                     |
+-----------+-----------+-------------------------------+---------+----------------+---------------------+

+-------+------+-------+---------+----------------+---------------------+
|                           External Testers                            |
+-------+------+-------+---------+----------------+---------------------+
| First | Last | Email | Devices | Latest Version | Latest Install Date |
+-------+------+-------+---------+----------------+---------------------+
+-------+------+-------+---------+----------------+---------------------+
```

This is how the list looks on iTunes Connect
<img width="911" alt="screenshot 2016-04-22 07 38 22" src="https://cloud.githubusercontent.com/assets/2934986/14732842/95da0460-085e-11e6-8786-120dd62da035.png">

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
fastlane_version "1.81.0"

default_platform :ios

platform :ios do

  desc "Runs all the tests"
  lane :test do
    scan(scheme: "SchemeName")
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    gym(scheme: "AppName") # Build your app - more options available
    pilot(distribute_external: false)
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "SchemeName") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  desc "Refresh dSYM files and upload them to Crashlytics"
  lane :refresh_dsyms do
    download_dsyms                  # Download dSYM files from iTunes Connect
    upload_symbols_to_crashlytics   # Upload them to Crashlytics
    clean_build_artifacts           # Delete the local dSYM files
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
```

### Environment

fastlane version (run `fastlane -v`):
1.81.0
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
No

**Comment by TKBurner** [comment] 2016-04-22 18:57
Hi @SebastianOsinski! Thanks for reaching out. Are you able to duplicate this issue from another bundle ID? I want to see if we can get exact repro steps so we can investigate. Thanks!

**Comment by SebastianOsinski** [comment] 2016-04-23 08:17
@TKBurner I tested it with another project (which has no fastlane integrated but I just ran `pilot list` and chose iTunes Connect team for this project) and those columns are filled there.

**Comment by TKBurner** [comment] 2016-04-25 22:36
@SebastianOsinski Thanks for following up. Since you can't reproduce reliably this it's going to be a lot harder for us to investigate. Were all the testers added through Pilot for this app? A mix? Or all through Testflight directly? Can you test those states?

**Comment by SebastianOsinski** [comment] 2016-05-01 20:35
@TKBurner All te testers were added through iTunes Connect website. Not sure if its relevant, but the account I use with pilot has `App Manager` role, not `Admin`.

**Comment by TKBurner** [comment] 2016-05-03 15:57
Hi Sebastian, This is a dupe of #4216.

Hi folks! 👋

The issue here is that Apple returns different data depending on how you ask for tester information. Counter-intuitively, when asking for a list of testers outside of the context of an app, you will find that the last three columns are filled with data.

(from someplace outside of your app directory)

pilot list -p your@apple.id
+----------+---------------+----------------------------------+---------+----------------+---------------------+
|                                               Internal Testers                                               |
+----------+---------------+----------------------------------+---------+----------------+---------------------+
| First    | Last          | Email                            | Devices | Latest Version | Latest Install Date |
+----------+---------------+----------------------------------+---------+----------------+---------------------+
| Whoever  | Someguy       | whoever.someguy@gmail.com        | 0       |                |                     |
| Another  | Person        | another.person@gmail.com         | 1       | 1.0 (21)       | 04/27/16 09:44      |
+----------+---------------+----------------------------------+---------+----------------+---------------------+

+----------+-----------+---------------------------+---------+----------------+---------------------+
|                                         External Testers                                          |
+----------+-----------+---------------------------+---------+----------------+---------------------+
| First    | Last      | Email                     | Devices | Latest Version | Latest Install Date |
+----------+-----------+---------------------------+---------+----------------+---------------------+
| Another  | Person    | another.person@gmail.com  | 1       | 1.0 (21)       | 04/27/16 09:44      |
| John     | Doer      | mail@domain.com           | 0       |                |                     |
+----------+-----------+---------------------------+---------+----------------+---------------------+
The version and install data is actually relative to a particular app, but we're not describing which one. 🙁

Then, when we ask for tester information in the context of an app, the shape of the data is quite different, so these fields are not available.

This is definitely a bug, or at least a feature design problem. But it will take some work to address properly. In the mean time, I'm inclined to remove those columns when we have no actual data available to display.

Does that make sense?

**Closed by TKBurner** 2016-05-03 15:57 UTC
Labels: help wanted, pilot, question
