### ISSUE TITLE
Arabic language not supported in metadata

### ISSUE THREAD

**Issue by mtrezza** [fastlane/fastlane#14959] opened 2019-06-27 01:09 UTC
### Issue Description
Arabic language directory `metadata/ar` not recognized as valid.

_Note: Even though the Arabic language directory `screenshots/ar` is recognized as valid when creating screenshots._

##### Command executed
`fastlane deliver --skip_screenshots --skip_binary_upload --verbose --force --phased_release --automatic_release`

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre> .fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': [!] Unsupported directory name(s) for screenshots/metadata in './fastlane/metadata': ar (FastlaneCore::Interface::FastlaneError)
Valid directory names are: ["ca", "cs", "da", "de-DE", "el", "en-AU", "en-CA", "en-GB", "en-US", "es-ES", "es-MX", "fi", "fr-CA", "fr-FR", "he", "hi", "hr", "hu", "id", "it", "ja", "ko", "ms", "nl-NL", "no", "pl", "pt-BR", "pt-PT", "ro", "ru", "sk", "sv", "th", "tr", "uk", "vi", "zh-Hans", "zh-Hant", "appleTV", "iMessage", "default"]

Enable 'ignore_language_directory_validation' to prevent this validation from happening </pre>
</details>

##### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.5                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.20.1 (Apple Git-117)          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.14.5 (18F132)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.2.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.126.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.10.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| jwt                       | 2.1.0        |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| multi_json                | 1.12.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.2.7        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.15.0       |
| emoji_regex               | 0.1.1        |
| libxml-ruby               | 3.0.0        |
| psych                     | 2.0.8        |
</details>

*generated on:* **2019-06-27**
</details>

**Comment by max-ott** [comment] 2019-06-27 08:53
Official language code should be "ar-SA" (based on Apple's requirements)  and got added to https://github.com/fastlane/fastlane/blob/master/fastlane_core/lib/fastlane_core/languages.rb#L14 with 2.126.0

I just checked and if I run this in the console:
````
irb
>> require "fastlane"
=> true
>> available_languages = FastlaneCore::Languages::ALL_LANGUAGES
=> ["ar-SA", "ca", "cs", "da", "de-DE", "el", "en-AU", "en-CA", "en-GB", "en-US", "es-ES", "es-MX", "fi", "fr-CA", "fr-FR", "he", "hi", "hr", "hu", "id", "it", "ja", "ko", "ms", "nl-NL", "no", "pl", "pt-BR", "pt-PT", "ro", "ru", "sk", "sv", "th", "tr", "uk", "vi", "zh-Hans", "zh-Hant"]
```

Could you try to uninstall the gem to the latest version?

**Comment by janpio** [comment] 2019-06-27 10:35
@mtrezza Please don't delete part of the issue template, having your `fastlane env` information here would help us to understand if you are using the latest fastlane version or not. Thanks.

**Comment by mtrezza** [comment] 2019-06-27 14:30
@janpio added environment;
@max-ott That's interesting, because the screenshots are generated and uploaded to the App Store successfully with `ar` as language in the `Snapfile`.

**Comment by janpio** [comment] 2019-06-27 15:23
Looked into the code that throws this error a bit:

https://github.com/fastlane/fastlane/blob/70a41f3c1c17b4ce6eef67c8eac309a7f1637664/deliver/lib/deliver/loader.rb#L27-L31

So `FastlaneCore::Languages::ALL_LANGUAGES` is only used when running the tests @max-ott, otherwise it uses `Spaceship::Tunes.client.available_languages.sort`. That is defined here:

https://github.com/fastlane/fastlane/blob/c7133bb928f6952c47965f4e06fd5c08fb5f961f/spaceship/lib/spaceship/tunes/tunes_client.rb#L761-L767

So this actually seems to make a request to an endpoint from Apple...

**Comment by mackoj** [comment] 2019-07-02 13:10
FWIW I have the same issue.
What can I do to help fix it ?

This is our env.
```
+------------------------------------------------------------------------------+
| (7) fastlane@2.5.0                                                           |
+------------------------------------------------------------------------------+
| id: fastlane                                                                 |
| version: 2.5.0                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2019-07-01T19:58:15Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
INFO[19:58:15]  * [OK] Step dependency (go) installed, available. 
Configs:
- WorkDir: /Users/vagrant/git
- Lane: submit_upload
- UpdateFastlane: true

Expand WorkDir
Expanded WorkDir: /Users/vagrant/git
Ensure cookies for Apple Developer Portal
Session exported
Determine desired Fastlane version
Checking Gemfile.lock (/Users/vagrant/git/Gemfile.lock) for fastlane and bundler gem
Gemfile.lock defined fastlane version: 2.126.0
Gemfile.lock defined bundler version: 1.16.4
Install bundler
$ gem "install" "bundler" "--force" "--no-document" "-v" "1.16.4"
Successfully installed bundler-1.16.4
1 gem installed
Install Fastlane with bundler
$ bundle "_1.16.4_" "install" "--jobs" "20" "--retry" "5"
Using CFPropertyList 3.0.0
Using public_suffix 2.0.5
Using addressable 2.6.0
Using atomos 0.1.3
Using babosa 1.0.2
Using bundler 1.16.4
Using claide 1.0.2
Using colored 1.2
Using colored2 3.1.2
Using highline 1.7.10
Using commander-fastlane 4.4.6
Using declarative 0.0.10
Using declarative-option 0.1.0
Using digest-crc 0.4.1
Using unf_ext 0.0.7.6
Using unf 0.1.4
Using domain_name 0.5.20180417
Using dotenv 2.7.4
Using emoji_regex 1.0.1
Using excon 0.64.0
Using multipart-post 2.0.0
Using faraday 0.15.4
Using http-cookie 1.0.3
Using faraday-cookie_jar 0.0.6
Using faraday_middleware 0.13.1
Using fastimage 2.1.5
Using gh_inspector 1.1.3
Using jwt 2.1.0
Using memoist 0.16.0
Using multi_json 1.13.1
Using os 1.0.1
Using signet 0.11.0
Using googleauth 0.6.7
Using httpclient 2.8.3
Using mime-types-data 3.2019.0331
Using mime-types 3.2.2
Using uber 0.1.0
Using representable 3.0.4
Using retriable 3.1.2
Using google-api-client 0.23.9
Using google-cloud-env 1.2.0
Using google-cloud-core 1.3.0
Using google-cloud-storage 1.16.0
Using json 2.2.0
Using mini_magick 4.5.1
Using multi_xml 0.6.0
Using plist 3.5.0
Using rubyzip 1.2.3
Using security 0.1.3
Using naturally 2.2.0
Using simctl 1.6.5
Using slack-notifier 2.3.2
Using terminal-notifier 2.0.0
Using unicode-display_width 1.6.0
Using terminal-table 1.8.0
Using tty-screen 0.7.0
Using tty-cursor 0.7.0
Using tty-spinner 0.9.1
Using word_wrap 1.0.0
Using nanaimo 0.2.6
Using xcodeproj 1.10.0
Using rouge 2.0.7
Using xcpretty 0.3.0
Using xcpretty-travis-formatter 1.0.0
Using fastlane 2.126.0
Using netrc 0.11.0
Using rest-client 2.0.2
Using onesky-ruby 1.1.0
Using fastlane-plugin-onesky 0.2.1
Using fastlane-plugin-waldo 1.2.1

Bundle complete! 3 Gemfile dependencies, 70 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
Fastlane version:
$ bundle "exec" "fastlane" "--version"
fastlane installation at path:
/Users/vagrant/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/fastlane-2.126.0/bin/fastlane
-----------------------------
fastlane 2.126.0
Run Fastlane
$ bundle "exec" "fastlane" "submit_upload"
+------------------------+---------+-----------------+
|                    Used plugins                    |
+------------------------+---------+-----------------+
| Plugin                 | Version | Action          |
+------------------------+---------+-----------------+
| fastlane-plugin-onesky | 0.2.1   | onesky_upload   |
|                        |         | onesky_download |
| fastlane-plugin-waldo  | 1.2.1   | waldo           |
+------------------------+---------+-----------------+
[19:58:26]: ------------------------------
[19:58:26]: --- Step: default_platform ---
[19:58:26]: ------------------------------
[19:58:26]: Driving the lane 'ios submit_upload' 🚀
[19:58:26]: ---------------------------------
[19:58:26]: --- Step: upload_to_app_store ---
[19:58:26]: ---------------------------------
[19:58:26]: In the config file './fastlane/Deliverfile' you have the line username, but didn't provide any value. Make sure to append a value right after the option name. Make sure to check the docs for more information
[19:58:26]: Successfully loaded '/Users/vagrant/git/fastlane/Deliverfile' 📄
+-----------------------+-----------------------+
| Detected Values from './fastlane/Deliverfile' |
+-----------------------+-----------------------+
| team_id               | [REDACTED]            |
+-----------------------+-----------------------+
[19:58:26]: Login to App Store Connect ([REDACTED])
Session loaded from environment variable is not valid. Continuing with normal login.
[19:58:27]: Login successful
+----------------------------------------------------+-----------------------------------+
|                                deliver 2.126.0 Summary                                 |
+----------------------------------------------------+-----------------------------------+
| ipa                                                | /Users/vagrant/deploy/app.ipa     |
| skip_screenshots                                   | true                              |
| skip_metadata                                      | false                             |
| force                                              | true                              |
| submit_for_review                                  | true                              |
| phased_release                                     | true                              |
| automatic_release                                  | true                              |
| submission_information.add_id_info_limits_tracking | true                              |
| submission_information.add_id_info_serves_ads      | false                             |
| submission_information.add_id_info_tracks_action   | true                              |
| submission_information.add_id_info_tracks_install  | true                              |
| submission_information.add_id_info_uses_idfa       | true                              |
| screenshots_path                                   | ./fastlane/screenshots            |
| metadata_path                                      | ./fastlane/metadata               |
| app_version                                        | 1.17.0                            |
| username                                           | [REDACTED]                        |
| app_identifier                                     | [REDACTED]                        |
| platform                                           | ios                               |
| edit_live                                          | false                             |
| use_live_version                                   | false                             |
| skip_binary_upload                                 | false                             |
| skip_app_version_update                            | false                             |
| overwrite_screenshots                              | false                             |
| reject_if_possible                                 | false                             |
| reset_ratings                                      | false                             |
| team_id                                            | [REDACTED]                        |
| dev_portal_team_id                                 | [REDACTED]                        |
| run_precheck_before_submit                         | true                              |
| precheck_default_rule_level                        | warn                              |
| individual_metadata_items                          | []                                |
| ignore_language_directory_validation               | false                             |
| precheck_include_in_app_purchases                  | true                              |
+----------------------------------------------------+-----------------------------------+
[19:58:28]: Making sure the latest version on App Store Connect matches '1.17.0' from the ipa file...
[19:58:35]: Successfully set the version to '1.17.0'
+------------------+-------------------+
|             Lane Context             |
+------------------+-------------------+
| DEFAULT_PLATFORM | ios               |
| PLATFORM_NAME    | ios               |
| LANE_NAME        | ios submit_upload |
+------------------+-------------------+
[19:58:35]: Unsupported directory name(s) for screenshots/metadata in './fastlane/metadata': ar-SA
Valid directory names are: ["ca", "cs", "da", "de-DE", "el", "en-AU", "en-CA", "en-GB", "en-US", "es-ES", "es-MX", "fi", "fr-CA", "fr-FR", "he", "hi", "hr", "hu", "id", "it", "ja", "ko", "ms", "nl-NL", "no", "pl", "pt-BR", "pt-PT", "ro", "ru", "sk", "sv", "th", "tr", "uk", "vi", "zh-Hans", "zh-Hant", "appleTV", "iMessage", "default"]
Enable 'ignore_language_directory_validation' to prevent this validation from happening
+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | default_platform    | 0           |
| 💥   | upload_to_app_store | 8           |
+------+---------------------+-------------+
[19:58:35]: fastlane finished with errors
[!] Unsupported directory name(s) for screenshots/metadata in './fastlane/metadata': ar-SA
Valid directory names are: ["ca", "cs", "da", "de-DE", "el", "en-AU", "en-CA", "en-GB", "en-US", "es-ES", "es-MX", "fi", "fr-CA", "fr-FR", "he", "hi", "hr", "hu", "id", "it", "ja", "ko", "ms", "nl-NL", "no", "pl", "pt-BR", "pt-PT", "ro", "ru", "sk", "sv", "th", "tr", "uk", "vi", "zh-Hans", "zh-Hant", "appleTV", "iMessage", "default"]
Enable 'ignore_language_directory_validation' to prevent this validation from happening
Fastlane command: (bundle "exec" "fastlane" "submit_upload") failed
If you want to send an issue report to fastlane (https://github.com/fastlane/fastlane/issues/new), you can find the output of fastlane env in the following log file:
/Users/vagrant/deploy/fastlane_env.log
Command failed, error: exit status 1
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | fastlane@2.5.0 (exit code: 1)                                 | 26 sec   |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-io/steps-fastlane/issues           |
| Source: https://github.com/bitrise-io/steps-fastlane                         |
+---+---------------------------------------------------------------+----------+
```

**Comment by max-ott** [comment] 2019-07-02 13:53
Did you guys try `Enable 'ignore_language_directory_validation' to prevent this validation from happening` If so do the metadata get uploaded?

**Comment by mackoj** [comment] 2019-07-02 14:30
This was the next step in the plan but we needed the app on the store so we remove the folder `ar-SA` instead. But I will test it soon.

**Comment by mtrezza** [comment] 2019-07-02 16:10
Tried, did not work with folder name ar-SA.

**Comment by max-ott** [comment] 2019-07-02 16:28
What's the full error message?

**Comment by mtrezza** [comment] 2019-07-02 17:05
I didn’t see an error message, the language was just not updated on App Store Connect.

**Comment by max-ott** [comment] 2019-07-02 18:20
Seems to be an issue on Apple's end. If I run `available_languages = Spaceship::Tunes.client.available_languages.sort` I only get 38 responses

`["ca", "cs", "da", "de-DE", "el", "en-AU", "en-CA", "en-GB", "en-US", "es-ES", "es-MX", "fi", "fr-CA", "fr-FR", "he", "hi", "hr", "hu", "id", "it", "ja", "ko", "ms", "nl-NL", "no", "pl", "pt-BR", "pt-PT", "ro", "ru", "sk", "sv", "th", "tr", "uk", "vi", "zh-Hans", "zh-Hant"]`

Arabic is 100% missing here. I can confirm that the upload is working directly via `spaceship`.

I recommend forking `fastlane` and removing the "Apple check" https://github.com/fastlane/fastlane/blob/70a41f3c1c17b4ce6eef67c8eac309a7f1637664/deliver/lib/deliver/loader.rb#L29 and just use the "hardcoded" Fastlane defaults and check if it is working for you.

**Comment by janpio** [comment] 2019-07-02 18:37
Do we know where this URL `ra/apps/storePreview/regionCountryLanguage` comes from and if it is still used in App Store Connect?

(I checked the history of that code, and in the beginning it was added to _fix_ broken or wrongly cApItAlIzEd language codes in folder names, but later this was changed to a harder verfication. The initial discussion included doubts if that endpoint really returns all the supported languages already - which now bites us)

**Comment by max-ott** [comment] 2019-07-02 19:56
When doing a bunch of language related operations directly on App Store Connect (adding languages, changing primary language etc.) I could not see any calls to that endpoint with Charles.

**Comment by alaincaltieri** [comment] 2019-07-03 06:50
Hi, chipping in since I have the same issue.
That call is actually performed when the app page is loaded, just after selecting an app on App Store Connect. The endpoint is hit just once on loading, any action on languages or saving performs no additional calls.

Something interesting I noticed: there seems to be no reference to the "AR" language in the response body, although you can select Arabic from the UI. Hebrew, which was added the same day as Arabic, is managed correctly and is included in that response... 🤔

**Comment by cherpake** [comment] 2019-07-08 13:51
Having same issue, when uploading with 'ignore_language_directory_validation' it just skips ar-SA folder and nothing gets uploaded for Arabic language :(

**Comment by kashifhisam** [comment] 2019-08-07 14:11
Any update?

**Comment by CzokNorris** [comment] 2019-08-21 19:44
Any update?

**Comment by ainame** [comment] 2019-09-13 13:41
> [12] pry(main)> Spaceship::Tunes.client.available_languages.sort
=> ["ca", "cs", "da", "de-DE", "el", "en-AU", "en-CA", "en-GB", "en-US", "es-ES", "es-MX", "fi", "fr-CA", "fr-FR", "he", "hi", "hr", "hu", "id", "it", "ja", "ko", "ms", "nl-NL", "no", "pl", "pt-BR", "pt-PT", "ro", "ru", "sk", "sv", "th", "tr", "uk", "vi", "zh-Hans", "zh-Hant"]

I just ran the above method locally today but it still returns the same not including "ar" 😞

**Comment by ainame** [comment] 2019-09-20 14:31
It's released but still remains the same.

```
[14] pry(main)> Spaceship::Tunes.client.available_languages.sort
=> ["ca", "cs", "da", "de-DE", "el", "en-AU", "en-CA", "en-GB", "en-US", "es-ES", "es-MX", "fi", "fr-CA", "fr-FR", "he", "hi", "hr", "hu", "id", "it", "ja", "ko", "ms", "nl-NL", "no", "pl", "pt-BR", "pt-PT", "ro", "ru", "sk", "sv", "th", "tr", "uk", "vi", "zh-Hans", "zh-Hant"]
```

**Comment by janpio** [comment] 2019-09-20 15:51
Uhm, the output you posted is identical to that one from the previous message - did I miss anything?

**Comment by ainame** [comment] 2019-09-24 14:56
Oh, I meant that even though iOS 13 including App Store app that supports Arabic metadata had been released this issue hadn't been fixed.

The issue still stays as I checked it now😞 

```
[5] pry(main)> Spaceship::Tunes.client.available_languages.sort
=> ["ca", "cs", "da", "de-DE", "el", "en-AU", "en-CA", "en-GB", "en-US", "es-ES", "es-MX", "fi", "fr-CA", "fr-FR", "he", "hi", "hr", "hu", "id", "it", "ja", "ko", "ms", "nl-NL", "no", "pl", "pt-BR", "pt-PT", "ro", "ru", "sk", "sv", "th", "tr", "uk", "vi", "zh-Hans", "zh-Hant"]
[6] pry(main)> Spaceship::Tunes.client.available_languages.sort.count
=> 38
```

It may not be likely to be fixed anytime soon.

**Comment by talshr** [comment] 2019-10-16 04:42
Having the same issue :-/

**Comment by tache** [comment] 2019-10-26 03:25
Also have this issue.

**Comment by fabioalmeida** [comment] 2019-10-28 11:30
This issue is still happening with fastlane `2.134.0`.

**Comment by mackoj** [comment] 2019-11-27 18:04
This issue should not be closed because it’s still not fixed

**Comment by fabioalmeida** [comment] 2019-11-28 11:57
This issue is still happening with fastlane `2.137.0` so it shouldn't be closed.

If an `ar-SA` folder is present, the following error is triggered:

`[!] Unsupported directory name(s) for screenshots/metadata in './fastlane/metadata': ar-SA
Valid directory names are: ["ca", "cs", "da", "de-DE", "el", "en-AU", "en-CA", "en-GB", "en-US", "es-ES", "es-MX", "fi", "fr-CA", "fr-FR", "he", "hi", "hr", "hu", "id", "it", "ja", "ko", "ms", "nl-NL", "no", "pl", "pt-BR", "pt-PT", "ro", "ru", "sk", "sv", "th", "tr", "uk", "vi", "zh-Hans", "zh-Hant", "appleTV", "iMessage", "default"]`.

**Comment by iliakukharev** [comment] 2019-12-13 16:18
The bug is still there

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.2                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.21.0 (Apple Git-122.2)                           |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.2 (19C57)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.3                                                           |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.137.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.67.0       |
| faraday                   | 0.17.0       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 1.17.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.1009  |
| mime-types                | 3.3          |
| multi_json                | 1.14.0       |
| signet                    | 0.12.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.1        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.2.1        |
| google-cloud-core         | 1.3.1        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
</details>


*generated on:* **2019-12-13**
</details>

**Comment by atitovdev** [comment] 2020-01-08 16:22
Any progress?

**Comment by mackoj** [comment] 2020-01-08 16:33
It fixed on the last fastlane !

**Comment by fabioalmeida** [comment] 2020-01-08 17:43
Validated with Fastlane `2.138.0` and it's working now (it wasn't before in this version), probably solved on App Store Connect side.

**Comment by mackoj** [comment] 2020-01-08 20:35
@fabioalmeida not really it fixed since https://github.com/fastlane/fastlane/releases/tag/2.138.0 with this commit https://github.com/fastlane/fastlane/pull/15572

**Comment by janpio** [comment] 2020-01-09 11:37
🚀

**Closed by janpio** 2020-01-09 11:37 UTC
Labels: tool: deliver, type: bug
