### ISSUE TITLE
Version Conflict.

### ISSUE THREAD

**Issue by bigyanthapa** [fastlane/fastlane#3885] opened 2016-03-22 19:41 UTC
Hi, 
I am trying to use the ScreenGrab library in my Android Project for grabbing screenshots for international languages. But my project won't compile as soon as I added the gradle dependency. It says Version Conflict. 
I check the gradle for this library and it says targetSDK version as 23, but the target SDK for my project is 21. Is there a way to get around this issue.

Thanks

### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

```
INSERT OUTPUT HERE
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# INSERT CONTENT HERE
```

### Environment

fastlane version (fastlane -v):
Do you use bundler, rbenv or rvm?

**Comment by asfalcone** [comment] 2016-03-22 21:17
@bigyanthapa Thanks for checking out screengrab. Can you provide the full gradle output that includes the error you mentioned?

**Comment by bigyanthapa** [comment] 2016-03-22 21:21
@asfalcone Thanks for the reply. Here is the error :
Warning:Conflict with dependency 'com.android.support:support-annotations'. Resolved versions for app (22.2.0) and test app (23.1.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.

**Comment by asfalcone** [comment] 2016-03-23 01:18
Ah ok, so the issue is in the version of the support library not the targetSDK. Our library does use support-annotations:23.1.1.

Can you try using `compile "com.android.support:support-annotations:23.1.1"` in your app?

**Comment by bigyanthapa** [comment] 2016-03-23 13:46
I tried adding that, but I get error right there. The error says,"This support library should not use a different version (23) other than the compileSDKVersion 21 ."

**Comment by mfurtak** [comment] 2016-04-06 00:17
Hi @bigyanthapa - I've merged #4075 to address this, which will be out in the next release.

**Comment by mfurtak** [comment] 2016-04-07 18:48
Hi @bigyanthapa - we've just shipped [`screengrab` 0.3.2](https://github.com/fastlane/fastlane/releases/tag/screengrab/0.3.2) 📷✨ which removes a `targetSdkVersion` declaration from the AAR. Please update your Ruby gem as well as your AAR dependency version and let us know how it looks. :+1:

**Closed by mfurtak** 2016-04-07 18:48 UTC
Labels: screengrab

**Comment by bigyanthapa** [comment] 2016-04-18 20:08
Thank you @mfurtak , I appreciate your help. I will try to integrate the library again.
