### ISSUE TITLE
[Fastlane] latest_testflight_build_number not returning correct latest build number

### ISSUE THREAD

**Issue by ravichandra-ayla** [fastlane/fastlane#18340] opened 2021-03-05 11:39 UTC
### New Issue Checklist

- [yes ] Updated fastlane to the latest version
- [ yes] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ yes] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ yes] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
For one of my app, I am not getting right TF build number. it always returns 4 instead of latest version number.

##### Command executed
fastlane run latest_testflight_build_number

##### Complete output when running fastlane, including the stack trace and command used
abc@MacBook-Pro ABC_iOS % fastlane run latest_testflight_build_number
[⠹] 🚀 Ignoring ffi-1.13.0 because its extensions are not built. Try: gem pristine ffi --version 1.13.0
[✔] 🚀 
[16:59:55]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[16:59:57]: --------------------------------------------
[16:59:57]: --- Step: latest_testflight_build_number ---
[16:59:57]: --------------------------------------------
[16:59:57]: Login to App Store Connect (xyz@abc.com)
[16:59:58]: Login successful
[17:00:03]: Fetching the latest build number for any version
[17:00:04]: Latest upload for version 6.6.6 on ios platform is build: 4
[17:00:04]: Result: 4
abc@MacBook-Pro ABC_iOS % 

<details>
  <pre> followed as per Fastlane action given @ https://docs.fastlane.tools/actions/latest_testflight_build_number/ </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.1                                                           |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.15.0                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 11.1 (20C69)                                             |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.3                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Fastfile (General)
# 
#    Fastlane coordinates actions absed on this file.
#
# Pulls in dependent files, determining inheritance and resolution order.
#
# Functions/variables defined in abc_core and app_core are available
# Additionally, variables defined in the Appfile, 
#    and in 'dotenv' .env property files are also available.
#
# 
fastlane_version "2.105.0"
fastlane_require 'dotenv'

#
# Mainline functions and lanes are defined here
import "abc_core.rb"

# Any app specific overrides are performed here
#    File should be located in app repo
#
# This project_core file, along with the Appfile and any additional .env files should be 
#    associated to the GitHub repo.
sleep 1
import "project_core.rb"

# Anything after this line will override anything else.

def print_app_info 
	UI.message("Printing iOS Appfile Info!")
	app_identifier = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
	apple_id = CredentialsManager::AppfileConfig.try_fetch_value(:apple_id)
	UI.message("Apple ID: #{apple_id}")
	UI.message("App Bundle ID: #{app_identifier}")

	UI.message("Scheme: #{ENV['BUILD_SCHEME']}")
	UI.message("Test Username: #{ENV['TEST_USERNAME']}")
	#test_string()
end

#alias_method :test_string, :old_test_string

# Overrides app_core.rb version, which overrides abc_core.rb version.
#   See import order at top.
def test_string
	UI.message "test_string from the Fastfile"
end

before_all do |lane, options|
	UI.message("Execution of before_all block")
	if ENV['DOTENV'] or options[:dotenv]
		Dotenv.load('Release.env') # Dependency branch specifiers
		UI.important "Pulling in dotenv vars from 'Release.env' file"
	end
	Dotenv.overload('.env.secrets') # Always loads the secrets file if it's available
	Dotenv.overload('.env.ids')
	before_all_project(lane, options)
end


platform :independent do
	desc "Test lane for use with platform idependent projects, such as common_sepia."
	lane :indie_test do
		UI.important("Common Fastfile test")
		print_app_info
	end
end

platform :ios do
	
	desc "Description of what the lane does"
	lane :fasttest do
		print_app_info
	end
	
	override_lane :fasttest_base do
		UI.message("fasttest_base: overridden by main Fastfile")
	end
	
	desc "Simple test to check whether the 'is_ci' fastlane conditional is functioning as expected."
	lane :ci_test do
		if is_ci?
			UI.important "CI System Detected"
		else
			UI.important "No CI System Detected."
		end
	end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# Appfile for abc
#
#    App-specific information for ingestion by fastlane
#
# One of these Appfiles should be included with every app repo.


# Appfile-specific items.  Fastlane-defined sets of properties
# Accessible as follows:
#    CredentialsManager::AppfileConfig.try_fetch_value(:var_name)
#

app_identifier("com.company.app") # The bundle identifier of the app
apple_id(ENV['APPLE_ID']) # Apple ID associated with App Store entry
team_id(ENV['TEAM_ID']) # Team ID used with Xcode code signing


# Other custom environment variables can also be set here
#
# Accessible within Fastfile as follows:
#    ENV['var_name']
#    UI.message("Scheme: #{ENV['var_name']}")

ENV['BUILD_SCHEME'] = "ABC"
ENV['REPO_NAME'] = "ABC_iOS"
ENV['HAS_APPLICATION'] = "true"


ENV['SOURCE_DIR'] = "../ABC"

ENV['SOURCE_DIR2'] = "../ABC WatchKit App"
ENV['SOURCE_DIR3'] = "../ABC WatchKit Extension"


ENV['VERSION_FILE'] = "Info.plist"

ENV['PODFILE_FILE'] = "../Podfile"
ENV['BUILD_SCRIPT_F'] = "../Podfile"

ENV['RELEASE_ENV_FILE'] = "../Release.env"


for_platform :ios do
	for_lane :fasttest do
		# These Appfile values can be overridden (of defined) for specific lanes
		#app_identifier "com.company.myapp.staging"
		#ENV['BUILD_SCHEME'] = "SpecialScheme"
	end
end

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.176.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.16.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| artifactory               | 3.0.15       |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.76.0       |
| faraday                   | 1.0.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.10.1       |
| naturally                 | 2.2.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.6        |
| bundler                   | 1.17.2       |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.1        |
| googleauth                | 0.13.1       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.3        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-storage      | 1.28.0       |
| emoji_regex               | 3.0.0        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.364.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-sdk-core              | 3.105.0      |
| aws-sdk-kms               | 1.37.0       |
| aws-sdk-s3                | 1.79.1       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>

*generated on:* **2021-03-05**
</details>

<details>
  <pre>  abc@MacBook-Pro ABC_iOS % sudo gem install fastlane
Password:
Ignoring ffi-1.13.0 because its extensions are not built. Try: gem pristine ffi --version 1.13.0
Fetching fastlane-2.176.0.gem
Successfully installed fastlane-2.176.0
Parsing documentation for fastlane-2.176.0
Installing ri documentation for fastlane-2.176.0
Done installing documentation for fastlane after 19 seconds
1 gem installed
abc@MacBook-Pro ABC_iOS %  </pre>
</details>

**Comment by max-ott** [comment] 2021-03-05 13:09
Possible duplicate of https://github.com/fastlane/fastlane/issues/18309 Currently we get the version / build codes for the last uploaded build, which might not always be the "latest" build number when it comes to semantic versioning.

**Closed by max-ott** 2021-03-05 13:09 UTC
Labels: duplicate
