### ISSUE TITLE
how can I change the new PRODUCT_BUNDLE_IDENTIFIER in Xcode7

### ISSUE THREAD

**Issue by everettjf** [fastlane/fastlane#684] opened 2015-10-10 10:10 UTC
Apple says in the Xcode 7 release notes that PRODUCT_BUNDLE_IDENTIFIER is now "the recommended place to set the Bundle Identifier for a target." So if you're using BUNDLE_IDENTIFIER anyplace else in your project, you have to change it to PRODUCT_BUNDLE_IDENTIFIER to keep things in sync.

http://stackoverflow.com/questions/32510153/installation-failed-invalid-argument-after-moving-to-xcode-7

**Comment by everettjf** [comment] 2015-10-10 10:38
I found a solution .
'''
sh "sed -i '' 's/#com.xxx.xxx/g' path/project.pbxproj"
'''
But, is there any fastlane actions ?

**Comment by KrauseFx** [comment] 2015-10-11 12:06
There is one to update a plist file: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md#update_info_plist

**Comment by everettjf** [comment] 2015-10-11 18:14
Yes, I got update_info_plist . It works all fine in Xcode 6 , when I want to modify app_identifier in Info.plist file.
But when Xcode 7 came , app_identifier in Info.plist is $(PRODUCT_BUNDLE_IDENTIFIER) , which pointed to PRODUCT_BUNDLE_IDENTIFIER in "project.pbxproj" .
Now we must modify the new app_identifier.

Maybe I'm looking for some tools which could parse or modify the "project.pbxproj" file.

**Comment by squarefrog** [comment] 2015-10-12 13:10
I use Xcode 7 and `update_info_plist` and it doesn't change `PRODUCT_BUNDLE_IDENTIFIER`. However I haven't seen an issue uploading this to TestFlight through `pilot`.

It may well be in the future that `update_info_plist` has to edit the `.pbxproj`.

Are you experiencing any problems or is this just a 'best-practice' situation?

**Comment by everettjf** [comment] 2015-10-12 14:07
Problems I met: 
Two apple accounts ,one is personal account ($99) , another one is enterprise account ($299) .

In my Fastfile , there are two lanes, one is for AppStore lane , and one is for Enterprise In-House lane, where app_identifier is com.xxx.myapp for AppStore Distribution and com.xxx.myappenterprise for In-House Distribution.

**Comment by squarefrog** [comment] 2015-10-12 14:09
I use the `update_info_plist` action to alter my project too. So one lane sets:

    com.example.myapp

Another sets

    com.example.myappbeta

Neither uses the new `PRODUCT_BUNDLE_IDENTIFIER` option, and neither reports issues.

Is there a specific error `Fastlane` throws when you attempt to upload?

**Comment by everettjf** [comment] 2015-10-12 14:15
App identifier is `com.example.appenterprise`  in `Enterprise In-House Provisioning File` , and `com.example.app` in `App Store Provisioning File`.
I met `Code Signing` error , because app identifier in In-House provision file should match .

**Comment by squarefrog** [comment] 2015-10-12 14:21
Just to confirm - if you manually set the `PRODUCT_BUNDLE_IDENTIFIER` before running your lane, it works ok?

**Comment by everettjf** [comment] 2015-10-12 14:26
Yes , Xcode 7 automatic set `PRODUCT_BUNDLE_IDENTIFIER` when I set `Bundle Identifier` in Xcode 7.

**Comment by everettjf** [comment] 2015-10-12 14:29
Sorry about my poor English. 
Maybe I could write an action to provide the function to modify `PRODUCT_BUNDLE_IDENTIFIER`.
Thanks for your response.

**Comment by squarefrog** [comment] 2015-10-12 14:34
No, what I mean is - if you manually set that bundle identifier, then run your lane again your lane work as expected?

I'm trying to see it if it really is necessary to write that action or not. As I mention, I've not set `PRODUCT_BUNDLE_IDENTIFIER` in my projects, I only use `CFBundleIdentifier` as I used to and it allows me to submit.

**Comment by everettjf** [comment] 2015-10-12 14:41
If I run my lane , 
```
update_info_plist(
    plist_path: "Example/Example-Info.plist",
    xcodeproj: "Example.xcodeproj",
    display_name: "Example Beta"
    app_identifier: "com.example.myappbeta"
  )
```
It only change the app identifier `CFBundleIdentifier` in `Info.plist` , not change the `PRODUCT_BUNDLE_IDENTIFIER` in projects.

As the links below says
http://stackoverflow.com/questions/32510153/installation-failed-invalid-argument-after-moving-to-xcode-7

```
This happens because "Upgrade to recommended settings" will change the info.plist's CFBundleIdentifier to point to $(PRODUCT_BUNDLE_IDENTIFIER) instead of the old $(BUNDLE_IDENTIFIER).

Apple says in the Xcode 7 release notes that PRODUCT_BUNDLE_IDENTIFIER is now "the recommended place to set the Bundle Identifier for a target." So if you're using BUNDLE_IDENTIFIER anyplace else in your project, you have to change it to PRODUCT_BUNDLE_IDENTIFIER to keep things in sync.
```

Are you using Xcode 7 ? If is Xcode 7 , you could try create a new project, and open `Info.plist`.
You will see:
CFBundleIdentifier to point to $(PRODUCT_BUNDLE_IDENTIFIER) instead of the old $(BUNDLE_IDENTIFIER).

**Comment by squarefrog** [comment] 2015-10-12 14:47
Yes that is what I'd expect. `update_info_plist` doesn't touch the Xcode project.

Do you specifically get this error?

> Installation Failed
Invalid Argument

What I'm trying to get at is, is setting this key *REQUIRED* for Enterprise installs? I do not set this key in Xcode 7, in fact, it is present, but has no value at all. But when I submit to TestFlight or the App Store, I get no warnings.

**Comment by everettjf** [comment] 2015-10-12 14:55
I do not know this error, where to get this error : 
- Installation Failed
- Invalid Argument
Your project is created by Xcode 6 or below . If you modify the Bundle Identifier using Xcode 7, the `PRODUCT_BUNDLE_IDENTIFIER` will be added to the project file .

Then,now if you update_info_plist , the new added `PRODUCT_BUNDLE_IDENTIFIER` in the project file will not change.

**Comment by squarefrog** [comment] 2015-10-12 15:13
OK that's fine.

Yes that makes a lot more sense now. If I manually update the identifier in Xcode 7, it introduces two changes:

1. Updates `CFBundleIdentifier` to `$(PRODUCT_BUNDLE_IDENTIFIER)` in `Info.plist`
2. Sets `PRODUCT_BUNDLE_IDENTIFIER` to the new identifier in `project.pbxproj`.

Personally, I feel if this is what Apple wants moving forward, it would make sense to add the changes to `update_info_plist`. There is an [Xcodeproj gem](https://github.com/CocoaPods/Xcodeproj) available `Fastlane` gem list, so it wouldn't necessarily be a big change.

**Comment by everettjf** [comment] 2015-10-12 15:26
Great !

**Comment by squarefrog** [comment] 2015-10-12 15:32
In the mean time, deleting whatever is set for `PRODUCT_BUNDLE_IDENTIFIER` and setting the value using `update_info_plist` might work :wink:

**Comment by everettjf** [comment] 2015-10-12 15:39
```
sh "sed -i '' 's/com.example.xxx/com.example.yyy/g' path/project.pbxproj"
```
also works.

**Comment by squarefrog** [comment] 2015-10-12 15:40
Only if you already have a value set. But that is much easier!

**Comment by everettjf** [comment] 2015-10-12 15:43
Yes it is.
While I am debuging app in the real device , it must have a value set.

**Comment by squarefrog** [comment] 2015-10-13 08:12
OK I've figured this out.

@KrauseFx I'm going to work on a Pull Request for this. Do you feel [`update_info_plist`](https://github.com/KrauseFx/fastlane/blob/master/lib/fastlane/actions/update_info_plist.rb) is a good place for the following pseudocode behaviour?

```ruby
if params[:app_identifier]
  # First, check if supplied plist is using the new `PRODUCT_BUNDLE_IDENTIFIER` key
  if plist['CFBundleIdentifier'] == $(PRODUCT_BUNDLE_IDENTIFIER)
    # Load Xcode project
    # set the app_identifier in xcodeproj
  else
    # set the app_identifier in plist
  end
end
```

As Apple want to see this key being used moving forward, would it be more appropriate to raise an exception if a user isn't using it?

According to the Xcode 7 [release notes](https://developer.apple.com/library/prerelease/ios/releasenotes/DeveloperTools/RN-Xcode/Chapters/xc7_release_notes.html), this change is backwards compatible.

> The new build setting Product Bundle Identifier (PRODUCT_BUNDLE_IDENTIFIER) is the recommended place to set the Bundle Identifier for a target. The target’s Info.plist should be configured to use this build setting by referencing it as $(PRODUCT_BUNDLE_IDENTIFIER) in the value for the CFBundleIdentifier key.
Xcode offers to configure this for you when you accept the “Upgrade to recommended settings” project modernization in the issue navigator, unless your target preprocesses its Info.plist file. In that case you will need to configure this setting manually. This change is backwards-compatible to older versions of Xcode.

> This change is required to make certain features work, such as On Demand Resources, if your target preprocesses its Info.plist file. (20887827)

**Comment by everettjf** [comment] 2015-10-13 09:16
Should we create a new "action" like : update_app_identifier ? 
As `update_info_plist` 's name , it only `update Info.plist`.

**Comment by squarefrog** [comment] 2015-10-13 11:14
It's a tricky one.  You're completely right that `update_info_plist` does imply it will only change `Info.plist`. However, the action already takes in an `xcodeproj` parameter. It is also the only current action that allows changing an app identifier.

Like you say, it makes sense to move this action out into a discrete action like `update_app_identifier`. Sole responsibility and such.

**Comment by everettjf** [comment] 2015-10-15 07:21
Yes. I understand . Since the `update_info_plist` action already takes in an `xcodeproj` parameter, it is the right place to change the project currently.

And something else , should this issue be closed now? Or until this feature completed ?

**Comment by squarefrog** [comment] 2015-10-15 07:56
I'd like @KrauseFx opinion before I submit a pull request.

Leave the issue open, it can be closed when I submit a pull request :+1:

**Comment by everettjf** [comment] 2015-10-15 08:09
OK.

**Comment by KrauseFx** [comment] 2015-10-15 16:29
@squarefrog I quickly scrolled over all the comments, sorry if I missed something here.
`update_info_plist` should really only update the plist file, everything else would be non-expected behavior.

Having a dedicated `update_app_identifier` action makes perfect sense and is very clear, so yes, having a new action is the right way :+1:

**Comment by squarefrog** [comment] 2015-10-16 09:32
I've created a pull request now https://github.com/KrauseFx/fastlane/pull/702 :tada:

**Comment by tomassliz** [comment] 2015-10-28 08:39
I have this problem with bundle identifier too. So thank you guys for this clarification! :+1:  I'll wait for merging the pull request.

**Comment by squarefrog** [comment] 2015-10-28 11:54
@tomassliz if you need it sooner, you can add the ruby file to your projects `fastlane/actions` folder and use it now. I've tested it manually and it works fine. Just need to sort the spec.

**Comment by tomassliz** [comment] 2015-10-28 12:31
@squarefrog Thank you but I'm already using [this workaround](https://github.com/fastlane/fastlane/issues/684#issuecomment-147441049).

**Comment by Sega-Zero** [comment] 2015-11-17 18:24
Any news on this? Also, it would be nice if there will be an option to read the current `$(PRODUCT_BUNDLE_IDENTIFIER)` value.

**Comment by squarefrog** [comment] 2015-11-17 18:30
@Sega-Zero see the `sed` workaround in the above post. Unless you know of anyone that can help out with the Ruby?

**Comment by Sega-Zero** [comment] 2015-11-17 18:41
`sed` workaround is nice for now, but it is always better to have a native tool support, so no need in Fastfile changes in the future. As for Ruby - I'm not good at it, but maybe [xcodeproj](https://github.com/CocoaPods/Xcodeproj) can help? There is also a python tool called [mod-pbxproj](https://github.com/kronenthaler/mod-pbxproj).

**Comment by squarefrog** [comment] 2015-11-17 18:49
@Sega-Zero thanks but xcodeproj is the cause of the issue :)

The code I wrote works fine with my manual testing but I can't correctly mock the behaviour for the unit tests running on Linux!

**Comment by KrauseFx** [comment] 2015-12-03 04:11
Thanks again @squarefrog for the implementation, we can close this issue now :+1:

**Closed by KrauseFx** 2015-12-03 04:11 UTC

**Comment by danielgalasko** [comment] 2016-01-11 14:39
Just in case anyone comes here looking for the solution, there is now a [update_app_identifier](https://github.com/fastlane/fastlane/blob/master/lib/fastlane/actions/update_app_identifier.rb) action

```ruby
update_app_identifier(app_identifier: "com.apple.xcode", plist_path: "Xcode/Info.plist")
```

**Comment by jeeftor** [comment] 2016-03-03 20:10
I'm using sed!  Its my savior!

**Comment by fisch0920** [comment] 2016-03-22 19:32
@KrauseFx the `update_app_identifier` is perfect BUT we really need to add its inverse get_app_identifier because currently trying to read the current app_identifier via `get_info_plist_value(key: 'CFBundleIdentifier', path: plist_path)` still runs into this issue.

This is especially important for enterprise apps which change app_identifier in an automated fashion as opposed to most non-enterprise apps which have a single or handful of bundle ids.

**Comment by Sega-Zero** [comment] 2016-03-22 19:36
This could be also easily implemented with this command:
```ruby
proj_id = sh("awk -F '=' '/PRODUCT_BUNDLE_IDENTIFIER/ {print $2; exit}' ../%PROJECT_NAME%.xcodeproj/project.pbxproj | cut -f 1 -d';'").strip!
```
I use it in my Fastfile, since `get_info_plist_value` no longer working

**Comment by fisch0920** [comment] 2016-03-22 19:57
Thanks @Sega-Zero.  I'm currently using this stand-in for `get_app_identifier`:

```ruby
  require 'xcodeproj'

  def get_app_identifier(params)
    info_plist_key = 'INFOPLIST_FILE'
    identifier_key = 'PRODUCT_BUNDLE_IDENTIFIER'

    app_id = get_info_plist_value(key: 'CFBundleIdentifier', path: params[:plist_path])

    if app_id == "$(#{identifier_key})" then
      path = File.expand_path(File.join(ENV['PWD'], params[:xcodeproj]))
      puts 'get_app_identifier'.blue
      puts path
      project = Xcodeproj::Project.open(path)

      # Fetch the build configuration objects
      configs = project.objects.select { |obj| obj.isa == 'XCBuildConfiguration' && !obj.build_settings[identifier_key].nil? }
      raise "Info plist uses $(#{identifier_key}), but xcodeproj does not".red unless configs.count > 0

      configs = configs.select { |obj| obj.build_settings[info_plist_key] == params[:plist_path] }
      raise "Xcodeproj doesn't have configuration with info plist #{params[:plist_path]}.".red unless configs.count > 0

      configs.each do |c|
        return c.build_settings[identifier_key]
      end
    end

    return app_id
  end
```

**Comment by waltermvp** [comment] 2016-06-01 15:27
Any headway here? Im also attempting to build lanes with different bundle ids and using `update_app_identifier` & `update_info_plist`.

The bundle ID in the project does update however is still get "Code Sign error: Provisioning profile does not match bundle identifier..." during the `gym` operation.

**Comment by danielgalasko** [comment] 2016-06-01 15:31
I just used Xcode configurations and made my life so much easier. If you modify the bundle id you end up with modified changes in git which is something you probably don't want? Initially I did as you said and then read the original value, changed it, made build, changed bundle ID back.

I [wrote](https://medium.com/@danielgalasko/run-multiple-versions-of-your-app-on-the-same-device-using-xcode-configurations-1fd3a220c608#.dz3rzn4r7) about this. And at the end of the day you can use gym to specify the configuration which is nice

**Comment by squarefrog** [comment] 2016-06-01 15:32
There has been some discussion about this on my pull request. https://github.com/fastlane/fastlane/pull/702#issuecomment-221186657

I think the separate schemes suggestion seems to be the smartest answer right now as it doesn't involve changing anything at build time.

**Comment by waltermvp** [comment] 2016-06-01 17:22
@danielgalasko @squarefrog thanks for the quick reply, ill take a look at both

**Comment by waltermvp** [comment] 2016-06-01 20:14
@danielgalasko @squarefrog schemas are the way to go for me 2, had them configured previously but was stubborn with the _fastlane_ commands. Thanks for the quick but helpful responses, your contributions to the community are appreciated

**Comment by TKBurner** [comment] 2016-06-07 17:04
@danielgalasko @squarefrog Thanks so much for stepping in! Always great to see our community in action 👍 

@waltermvp Glad to hear you are up and running!
