### ISSUE TITLE
Unable to run scan

### ISSUE THREAD

**Issue by beloso** [fastlane/fastlane#5495] opened 2016-07-25 17:50 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Can not run `scan`

##### Complete output when running fastlane, including the stack trace and command used

```
[18:47:59]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

[18:48:00]: Error finding relevant GitHub issues: undefined method `map' for nil:NilClass

[!] Could not find option for key :xcodebuild_list_silent. Available keys: workspace, project, device, devices, scheme, clean, code_coverage, address_sanitizer, skip_build, output_directory, output_style, output_types, buildlog_path, formatter, derived_data_path, result_bundle, sdk, open_report, configuration, destination, xcargs, xcconfig, slack_url, slack_channel, slack_message, skip_slack, slack_only_on_failure, use_clang_report_name
```

### Environment

fastlane version (run `fastlane -v`): 
`fastlane 1.98.0`

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
rbenv with ruby 2.2.3

**Comment by bootstraponline** [comment] 2016-07-25 18:28
All our iOS builds are failing with this... 😭 

It'd be nice to improve the test suite so entirely broken features don't make it into a release.

**Comment by pj4533** [comment] 2016-07-25 18:38
I was seeing this and it was fine on another machine,  then i updated fastlane_core to 0.48.2, and reproduced it.  So its something in there.

**Comment by pj4533** [comment] 2016-07-25 18:40
Prob something here?  https://github.com/fastlane/fastlane/commit/86234456703d33bc5ff74618c2bdac40b401271f

**Comment by riots100** [comment] 2016-07-25 19:27
Likewise, today we are getting "Could not find option for key :xcodebuild_list_silent" error.

**Comment by adc-amatosov** [comment] 2016-07-25 19:50
I am getting this error for all iOS jobs on Jenkins since 10:30 today...
Is there an easy workaround for the issue?

**Comment by mfurtak** [comment] 2016-07-25 19:51
Hi all - this is on me, sorry! 

A hotfix is in the pipeline and will be released shortly.

**Comment by mfurtak** [comment] 2016-07-25 19:56
OK - [`fastlane_core` 0.48.3](https://github.com/fastlane/fastlane/releases/tag/fastlane_core%2F0.48.3) is out with a hotfix.

`gem update fastlane_core` should get you the update.

Apologies again for this regression - please let me know if you're back in business. 👍

**Comment by bootstraponline** [comment] 2016-07-25 20:02
Thanks for the hotfix! I confirm this resolved the problem.

**Comment by riots100** [comment] 2016-07-25 20:03
this has seemed to fix our issue.

Thx!

**Comment by adc-amatosov** [comment] 2016-07-25 20:03
works for me!! Thanks for quick reaction!

**Closed** 2016-07-25 20:04 UTC

**Comment by beloso** [comment] 2016-07-26 08:30
Back to normal
