### ISSUE TITLE
Can't Set ITC Primary Language

### ISSUE THREAD

**Issue by vbresults** [fastlane/fastlane#7153] opened 2016-11-24 00:21 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Can't set ITC primary language when using produce.  It will always use English in ITC, even though my assets (metadata, screenshots) will be uploaded to the correct language.

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                               |
| ------------------- | --------------------------------------------------- |
| OS                  | 10.11.6                                             |
| Ruby                | 2.3.1                                               |
| Bundler?            | false                                               |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/         |
| Xcode Version       | 8.1                                                 |
| Git                 | git version 2.9.3 (Apple Git-75)                    |
| Installation Source | /Users/user/.rvm/gems/ruby-2.3.1/bin/fastlane |
| Host                | Mac OS X 10.11.6 (15G1108)                          |
| Ruby Lib Dir        | /Users/user/.rvm/rubies/ruby-2.3.1/lib        |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                         |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date        |
| fastlane_core       | 0.53.0  | 🚫 Update availaible |
| spaceship           | 0.36.2  | 🚫 Update availaible |
| deliver             | 1.14.5  | 🚫 Update availaible |
| snapshot            | 1.16.2  | 🚫 Update availaible |
| frameit             | 3.0.0   | ✅ Up-To-Date        |
| pem                 | 1.3.2   | 🚫 Update availaible |
| cert                | 1.4.3   | 🚫 Update availaible |
| sigh                | 1.11.2  | ✅ Up-To-Date        |
| produce             | 1.2.1   | 🚫 Update availaible |
| gym                 | 1.11.3  | 🚫 Update availaible |
| pilot               | 1.11.1  | 🚫 Update availaible |
| scan                | 0.13.1  | 🚫 Update availaible |
| supply              | 0.7.1   | ✅ Up-To-Date        |
| match               | 0.10.0  | 🚫 Update availaible |
| screengrab          | 0.5.5   | 🚫 Update availaible |
| fastlane            | 1.106.2 | 🚫 Update availaible |

### Loaded fastlane plugins:

**No plugins Loaded***

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.13.5       |
| io-console                | 0.4.5        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| terminal-table            | 1.4.5        |
| json                      | 1.8.3        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.9.2        |
| faraday_middleware        | 0.10.0       |
| dotenv                    | 2.1.1        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| plist                     | 3.1.0        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| krausefx-shenzhen         | 0.14.10      |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.8.3        |
| activesupport             | 4.2.7.1      |
| colored                   | 1.2          |
| claide                    | 1.0.1        |
| xcodeproj                 | 1.3.3        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| addressable               | 2.3.8        |
| xcode-install             | 2.0.7        |
| word_wrap                 | 1.0.0        |
| multi_json                | 1.12.1       |
| babosa                    | 1.0.2        |
| excon                     | 0.54.0       |
| gh_inspector              | 1.0.2        |
| credentials_manager       | 0.16.2       |
| fastlane_core             | 0.53.0       |
| multi_xml                 | 0.5.5        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160826 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| mini_magick               | 4.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.18       |
</details>

*generated on:* **2016-11-23**
</details>

**Comment by hjanuschka** [comment] 2016-11-24 06:48
this has been fixed with that PR: 
https://github.com/fastlane/fastlane/pull/7084, you have to wait until there is a new spaceship release.

or overriding your Gemfile and setting spaceship to use `master` branch

**Comment by asfalcone** [comment] 2016-11-24 14:59
Going to close as a duplicate of #7084. Will update over there when the fix is released.

**Closed by asfalcone** 2016-11-24 14:59 UTC
