### ISSUE TITLE
Deliver task says the package has been successfully uploaded but Fastlane finishes with the error "Upload binary failed"

### ISSUE THREAD

**Issue by pauldowman** [fastlane/fastlane#3781] opened 2016-03-16 14:49 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Deliver task says the package has been successfully uploaded but Fastlane finishes with the error "Upload binary failed"

I see `[10:11:05]: [Transporter]: INFO: The package: /tmp/965582748.itmsp has been successfully uploaded.` then: `Successfully uploaded package to iTunes Connect. It might take a few minutes until it's visible online` but then Fastlane exits with an error and the message `Upload binary failed`.

##### Complete output when running fastlane, including the stack trace and command used

NOTE some verbose parts of the output below were removed to stay within GitHub's size limit (and replaced with `...` on a line by itself).

```
[10:02:57]: Using build_number: 30000008
[10:02:57]: -------------------------------------------------
[10:02:57]: --- Step: Verifying required fastlane version ---
[10:02:57]: -------------------------------------------------
[10:02:57]: fastlane version valid
[10:02:58]: ------------------------------
[10:02:58]: --- Step: default_platform ---
[10:02:58]: ------------------------------
[10:03:05]: Driving the lane 'ios deploy' 🚀
[10:03:05]: --------------------------------------
[10:03:05]: --- Step: increment_version_number ---
[10:03:05]: --------------------------------------
[10:03:14]: $ cd /Volumes/Vet2Pet/Vet2Pet_builds/advancedanimalcareofco-ver300000.0.8/ios/project && agvtool new-marketing-version 300000.0.8
[10:03:15]: ▸ Setting CFBundleShortVersionString of project AdvAnimCare to:
[10:03:15]: ▸ 300000.0.8.
[10:03:15]: ▸ Updating CFBundleShortVersionString in Info.plist(s)...
[10:03:15]: ▸ Updated CFBundleShortVersionString in "AdvAnimCare.xcodeproj/../AdvAnimCare/AdvAnimCare-Info.plist" to 300000.0.8
[10:03:15]: ------------------------------------
[10:03:15]: --- Step: increment_build_number ---
[10:03:15]: ------------------------------------
[10:03:15]: $ cd /Volumes/Vet2Pet/Vet2Pet_builds/advancedanimalcareofco-ver300000.0.8/ios/project && agvtool new-version -all 30000008
[10:03:15]: ▸ Setting version of project AdvAnimCare to:
[10:03:15]: ▸ 30000008.
[10:03:15]: ▸ Also setting CFBundleVersion key (assuming it exists)
[10:03:15]: ▸ Updating CFBundleVersion in Info.plist(s)...
[10:03:15]: ▸ Updated CFBundleVersion in "AdvAnimCare.xcodeproj/../AdvAnimCare/AdvAnimCare-Info.plist" to 30000008
[10:03:16]: ---------------------
[10:03:16]: --- Step: produce ---
[10:03:16]: ---------------------

+----------------+----------------------------+
|          Summary for produce 1.1.1          |
+----------------+----------------------------+
| team_id        | V79U32D8T6                 |
| username       | <edited>    |
| app_name       | AdvAnimCare                |
| app_identifier | com.worldbizapps.SID220392 |
| skip_itc       | false                      |
| sku            | 1458137015                 |
| language       | English                    |
| skip_devcenter | false                      |
+----------------+----------------------------+

[10:03:44]: [DevCenter] App 'com.worldbizapps.SID220392' already exists, nothing to do on the Dev Center
[10:03:47]: [iTC] App 'com.worldbizapps.SID220392' already exists (965582748), nothing to do on iTunes Connect
[10:03:48]: ------------------
[10:03:48]: --- Step: cert ---
[10:03:48]: ------------------

+---------------+-------------------------------------------------+
|                     Summary for cert 1.4.0                      |
+---------------+-------------------------------------------------+
| team_id       | V79U32D8T6                                      |
| username      | <edited>                         |
| development   | false                                           |
| force         | false                                           |
| keychain_path | /Users/vet2pet/Library/Keychains/login.keychain |
+---------------+-------------------------------------------------+

[10:03:49]: Starting login with user '<edited>'
[10:03:50]: Successfully logged in
[10:03:54]: Certificate H5C7ZZSW94 (Vet2Pet LLC) can't be found on your local computer
[10:03:54]: Certificate 7EH3RJHJBJ (Vet2Pet LLC) can't be found on your local computer
[10:03:55]: Found the certificate UH2S9ZYS79 (Vet2Pet LLC) which is installed on the local machine. Using this one.
[10:03:55]: Verifying the certificated is properly installed locally...
[10:03:55]: Successfully installed certificate UH2S9ZYS79
[10:03:55]: Use signing certificate 'UH2S9ZYS79' from now on!
[10:03:55]: ------------------
[10:03:55]: --- Step: sigh ---
[10:03:55]: ------------------

+-------------------------------------+----------------------------+
|                      Summary for sigh 1.4.1                      |
+-------------------------------------+----------------------------+
| team_id                             | V79U32D8T6                 |
| username                            | <edited>    |
| app_identifier                      | com.worldbizapps.SID220392 |
| adhoc                               | false                      |
| skip_install                        | false                      |
| development                         | false                      |
| force                               | false                      |
| ignore_profiles_with_different_name | false                      |
| cert_id                             | UH2S9ZYS79                 |
| skip_fetch_profiles                 | false                      |
| skip_certificate_verification       | false                      |
+-------------------------------------+----------------------------+

[10:03:56]: Starting login with user '<edited>'
[10:03:57]: Successfully logged in
[10:03:57]: Fetching profiles...
[10:04:07]: Found 1 matching profile(s)
[10:04:07]: Downloading provisioning profile...
[10:04:07]: Successfully downloaded provisioning profile...
[10:04:08]: Installing provisioning profile...
/Volumes/Vet2Pet/Vet2Pet_builds/advancedanimalcareofco-ver300000.0.8/ios/project/AppStore_com.worldbizapps.SID220392.mobileprovision
[10:04:08]: Setting Provisioning Profile type to 'app-store'
[10:04:08]: -----------------
[10:04:08]: --- Step: pem ---
[10:04:08]: -----------------

+------------------+------------------------------------+
|                 Summary for PEM 1.3.0                 |
+------------------+------------------------------------+
| team_id          | V79U32D8T6                         |
| username         | <edited>            |
| app_identifier   | com.worldbizapps.SID220392         |
| p12_password     | <edited>                     |
| pem_name         | com.worldbizapps.SID220392-apnProd |
| output_path      | /Volumes/Vet2Pet/Vet2Pet_pems      |
| development      | false                              |
| generate_p12     | true                               |
| force            | false                              |
| save_private_key | true                               |
+------------------+------------------------------------+

[10:04:09]: Starting login with user '<edited>'
[10:04:10]: Successfully logged in
[10:04:11]: Existing push notification profile 'SID220392' is valid for 395 more days.
[10:04:11]: You already have a push certificate, which is active for more than 30 more days. No need to create a new one
[10:04:11]: If you still want to create a new one, use the --force option when running PEM.
[10:04:11]: -----------------
[10:04:11]: --- Step: pem ---
[10:04:11]: -----------------

+------------------+-----------------------------------+
|                Summary for PEM 1.3.0                 |
+------------------+-----------------------------------+
| development      | true                              |
| team_id          | V79U32D8T6                        |
| username         | <edited>           |
| app_identifier   | com.worldbizapps.SID220392        |
| p12_password     | <edited>                    |
| pem_name         | com.worldbizapps.SID220392-apnDev |
| output_path      | /Volumes/Vet2Pet/Vet2Pet_pems     |
| generate_p12     | true                              |
| force            | false                             |
| save_private_key | true                              |
+------------------+-----------------------------------+

[10:04:11]: Starting login with user '<edited>'
[10:04:12]: Successfully logged in
[10:04:12]: Existing push notification profile 'SID220392' is valid for 365 more days.
[10:04:12]: You already have a push certificate, which is active for more than 30 more days. No need to create a new one
[10:04:12]: If you still want to create a new one, use the --force option when running PEM.
[10:04:12]: -----------------
[10:04:12]: --- Step: gym ---
[10:04:12]: -----------------
[10:04:15]: Installing provisioning profile...
[10:04:15]: xcrun xcodebuild -list -project './AdvAnimCare.xcodeproj'

+---------------------------+----------------------------------------------------------------------+
|                                      Summary for gym 1.6.2                                       |
+---------------------------+----------------------------------------------------------------------+
| scheme                    | AdvAnimCare                                                          |
| xcargs                    | HEADER_SEARCH_PATHS='$(OBJROOT)/UninstalledProducts/$(PLATFORM_NA... |
| provisioning_profile_path | /Volumes/Vet2Pet/Vet2Pet_builds/advancedanimalcareofco-ver300000.... |
| codesigning_identity      | iPhone Distribution: Vet2Pet LLC (V79U32D8T6)                        |
| export_method             | app-store                                                            |
| project                   | ./AdvAnimCare.xcodeproj                                              |
| destination               | generic/platform=iOS                                                 |
| output_name               | AdvAnimCare                                                          |
| clean                     | false                                                                |
| output_directory          | .                                                                    |
| silent                    | false                                                                |
| use_legacy_build_api      | false                                                                |
| buildlog_path             | ~/Library/Logs/gym                                                   |
+---------------------------+----------------------------------------------------------------------+

[10:04:23]: $ set -o pipefail && xcodebuild -scheme 'AdvAnimCare' -project './AdvAnimCare.xcodeproj' -destination 'generic/platform=iOS' -archivePath '/Users/vet2pet/Library/Developer/Xcode/Archives/2016-03-16/AdvAnimCare 2016-03-16 10.04.23.xcarchive' HEADER_SEARCH_PATHS='$(OBJROOT)/UninstalledProducts/$(PLATFORM_NAME)/include' archive CODE_SIGN_IDENTITY='iPhone Distribution: Vet2Pet LLC (V79U32D8T6)' | tee /Users/vet2pet/Library/Logs/gym/AdvAnimCare-AdvAnimCare.log | xcpretty
[10:04:29]: ▸ Building CordovaLib/CordovaLib [Release]
[10:04:29]: ▸ Check Dependencies
[10:04:29]: ▸ Copying NSDictionary+Extensions.h
[10:04:29]: ▸ Copying NSData+Base64.h
[10:04:29]: ▸ Copying CDVInvokedUrlCommand.h
[10:04:29]: ▸ Copying CDVPluginResult.h
[10:04:29]: ▸ Copying CDVPlugin.h
[10:04:29]: ▸ Copying CDVDebug.h
[10:04:29]: ▸ Copying NSMutableArray+QueueAdditions.h
[10:04:29]: ▸ Copying CDVWhitelist.h
[10:04:29]: ▸ Copying CDVURLProtocol.h
...
[10:05:48]: ▸ Archive Succeeded
[10:05:50]: Successfully stored the archive. You can find it in the Xcode Organizer.
[10:05:50]: $ /usr/bin/xcrun /usr/local/lib/ruby/gems/2.2.0/gems/gym-1.6.2/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/6j/ph_y984j1j1c3tf92zzpq0w80000gn/T/gym20160316-8330-1ghm5nu_config.plist' -archivePath '/Users/vet2pet/Library/Developer/Xcode/Archives/2016-03-16/AdvAnimCare 2016-03-16 10.04.23.xcarchive' -exportPath '/var/folders/6j/ph_y984j1j1c3tf92zzpq0w80000gn/T/gym20160316-8330-1ho7l4k.gym_output' 
[10:05:59]: Compressing 1 dSYM(s)
[10:05:59]: $ cd '/Users/vet2pet/Library/Developer/Xcode/Archives/2016-03-16/AdvAnimCare 2016-03-16 10.04.23.xcarchive/dSYMs' && zip -r '/Volumes/Vet2Pet/Vet2Pet_builds/advancedanimalcareofco-ver300000.0.8/ios/project/AdvAnimCare.app.dSYM.zip' *.dSYM
[10:06:00]: ▸   adding: AdvAnimCare.app.dSYM/ (stored 0%)
[10:06:00]: ▸   adding: AdvAnimCare.app.dSYM/Contents/ (stored 0%)
[10:06:00]: ▸   adding: AdvAnimCare.app.dSYM/Contents/Info.plist (deflated 52%)
[10:06:00]: ▸   adding: AdvAnimCare.app.dSYM/Contents/Resources/ (stored 0%)
[10:06:00]: ▸   adding: AdvAnimCare.app.dSYM/Contents/Resources/DWARF/ (stored 0%)
[10:06:00]: ▸   adding: AdvAnimCare.app.dSYM/Contents/Resources/DWARF/AdvAnimCare (deflated 70%)

[10:06:00]: Successfully exported and compressed dSYM file
[10:06:00]: Successfully exported and signed the ipa file:
[10:06:00]: /Volumes/Vet2Pet/Vet2Pet_builds/advancedanimalcareofco-ver300000.0.8/ios/project/AdvAnimCare.ipa
[10:06:00]: app id: 965582748
[10:06:00]: ---------------------
[10:06:00]: --- Step: deliver ---
[10:06:00]: ---------------------
[10:06:01]: Login to iTunes Connect (<edited>)
[10:06:05]: Login successful

+--------------------+-----------------------------------------------------------------------------+
|                                      deliver 1.10.4 Summary                                      |
+--------------------+-----------------------------------------------------------------------------+
| force              | true                                                                        |
| username           | <edited>                                                     |
| app_identifier     | com.worldbizapps.SID220392                                                  |
| skip_screenshots   | true                                                                        |
| skip_metadata      | false                                                                       |
| submit_for_review  | false                                                                       |
| automatic_release  | false                                                                       |
| price_tier         | 0                                                                           |
| app_icon           | app-store-icon.png                                                          |
| copyright          | Use it please                                                               |
| primary_category   | Business                                                                    |
| description.en-US  | App description                                                             |
| keywords.en-US     | ["keyword"]                                                                 |
| name.en-US         | AdvAnimCare                                                                 |
| ipa                | /Volumes/Vet2Pet/Vet2Pet_builds/advancedanimalcareofco-ver300000.0.8/ios... |
| screenshots_path   | ./fastlane/screenshots                                                      |
| metadata_path      | ./fastlane/metadata                                                         |
| app_version        | 300000.0.8                                                                  |
| skip_binary_upload | false                                                                       |
+--------------------+-----------------------------------------------------------------------------+

[10:06:08]: Making sure the latest version on iTunes Connect matches '300000.0.8' from the ipa file...
[10:06:11]: Successfully set the version to '300000.0.8'
[10:06:11]: Loading './fastlane/metadata/en-US/description.txt'...
[10:06:11]: Loading './fastlane/metadata/en-US/keywords.txt'...
[10:06:11]: Loading './fastlane/metadata/en-US/release_notes.txt'...
[10:06:11]: Loading './fastlane/metadata/en-US/support_url.txt'...
[10:06:11]: Loading './fastlane/metadata/en-US/marketing_url.txt'...
[10:06:11]: Loading './fastlane/metadata/en-US/name.txt'...
[10:06:11]: Loading './fastlane/metadata/en-US/privacy_url.txt'...
[10:06:11]: Loading './fastlane/metadata/copyright.txt'...
[10:06:11]: Loading './fastlane/metadata/primary_category.txt'...
[10:06:11]: Loading './fastlane/metadata/secondary_category.txt'...
[10:06:11]: Loading './fastlane/metadata/primary_first_sub_category.txt'...
[10:06:11]: Loading './fastlane/metadata/primary_second_sub_category.txt'...
[10:06:11]: Loading './fastlane/metadata/secondary_first_sub_category.txt'...
[10:06:12]: Activating language en-US...
[10:06:14]: Uploading metadata to iTunes Connect
[10:06:16]: Successfully uploaded initial set of metadata to iTunes Connect
[10:06:16]: Price Tier unchanged (tier 0)
[10:06:19]: Uploading app icon...
[10:06:25]: Uploading binary to iTunes Connect
[10:06:26]: Going to upload updated app to iTunes Connect
[10:06:26]: This might take a few minutes, please don't interrupt the script
[10:07:28]: [Transporter]: INFO: Transporter is skipping bundle update check: Already checked recently.
[10:07:30]: [Transporter]: INFO: Logging configured successfully.
...
[10:11:02]: [Transporter]: INFO: Package upload progress: 100% completed
[10:11:02]: [Transporter]: INFO: The Signiant transfer engine's status is DISCONNECTED
[10:11:03]: [Transporter]: INFO: The Signiant transfer engine's status is DISCONNECTED
[10:11:03]: [Transporter]: INFO: The file, metadata.xml, was uploaded successfully.
[10:11:03]: [Transporter]: INFO: The file, e1e31a0bbc0b7f43f6435df071fb088d.ipa, was uploaded successfully.
[10:11:03]: [Transporter]: INFO: The status for the upload is SUCCESSFUL.
[10:11:03]: [Transporter]: INFO: The package's files (965582748.itmsp) uploaded successfully.
[10:11:03]: [Transporter]: INFO: Done performing upload.
[10:11:03]: [Transporter]: DBG-X: The transfer time for the package 965582748.itmsp was 9760 milliseconds.
[10:11:03]: [Transporter]: DBG-X: Throughput information for 965582748.itmsp: 0 minutes, 9.76 seconds, 7.47MB, 783.82KB/sec
[10:11:03]: [Transporter]: INFO: Performing uploadDone notification to Apple for package 965582748.itmsp ...
[10:11:03]: [Transporter]: DBG-X: Deflated 587 bytes to 372
[10:11:03]: [Transporter]: DBG-X: Memory: [JVM] 937M free, 982M total, 982M max [System] (Physical) 59M free, 4096M total (Swap) 729M free, 1024M total
[10:11:03]: [Transporter]: DBG-X: Using operation named: uploadDoneWithArguments
[10:11:03]: [Transporter]: DBG-X: Apple's web service operation input parameters:
[10:11:03]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
[10:11:03]: [Transporter]: DBG-X:   parameter BaseVersion = 1.8.7
[10:11:03]: [Transporter]: DBG-X:   parameter CPUToken = 114470bc-52f4-477f-9c4c-b0f5b2f4f075/1458137448104
[10:11:03]: [Transporter]: DBG-X:   parameter ClientChecksumInfo = [{FileSize=7833238, CalculatedChecksum=6f64624e349a7143b098cbf25f4e9f62, FileLastModified=1458137185000, Filename=e1e31a0bbc0b7f43f6435df071fb088d.ipa, CalculationTime=106}]
[10:11:03]: [Transporter]: DBG-X:   parameter ExtraTransportLogCompressed = (suppressed)
[10:11:03]: [Transporter]: DBG-X:   parameter FileSizeInfo = {metadata.xml=450, e1e31a0bbc0b7f43f6435df071fb088d.ipa=7833238}
[10:11:03]: [Transporter]: DBG-X:   parameter NewPackageName = 965582748-20160316071050-207.itmsp
[10:11:03]: [Transporter]: DBG-X:   parameter NumberBytesTransferred = 7833688
[10:11:03]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.11.3 (x86_64); jvm=24.80-b07; jre=1.7.0-internal-root_2015_05_12_09_52-b00
[10:11:03]: [Transporter]: DBG-X:   parameter PackagePathWithoutBase = sgr6_pod1/transporter/content/transporter/Vet2PetLLC
[10:11:03]: [Transporter]: DBG-X:   parameter Throttle = 100000
[10:11:03]: [Transporter]: DBG-X:   parameter TransferTime = 9760
[10:11:03]: [Transporter]: DBG-X:   parameter Transport = Signiant
[10:11:03]: [Transporter]: DBG-X:   parameter TransportLogCompressed = (suppressed)
[10:11:03]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -u <edited> -p **hidden value** -f /tmp/965582748.itmsp -t Signiant -k 100000
[10:11:03]: [Transporter]: DBG-X:   parameter Username = <edited>
[10:11:03]: [Transporter]: DBG-X:   parameter Version = 1.8.8
[10:11:03]: [Transporter]: DBG-X:   parameter iTMSTransporterMode = upload
[10:11:03]: [Transporter]: INFO: id = 20160316101103-512
[10:11:05]: [Transporter]: DBG-X: Apple's web service operation return value:
[10:11:05]: [Transporter]: DBG-X:   parameter Success = true
[10:11:05]: [Transporter]: DBG-X: Unlocking token at path /Users/vet2pet/.itmstransporter/UploadTokens/V2P-build.local_Vet2PetLLC_965582748.itmsp.token
[10:11:05]: [Transporter]: DBG-X: Releasing token file lock
[10:11:05]: [Transporter]: DBG-X: Removing token at path /Users/vet2pet/.itmstransporter/UploadTokens/V2P-build.local_Vet2PetLLC_965582748.itmsp.token
[10:11:05]: [Transporter]: INFO: Done performing uploadDone notification to Apple.
[10:11:05]: [Transporter]: INFO: The package: /tmp/965582748.itmsp has been successfully uploaded.
[10:11:05]: iTunes Transporter successfully finished its job
[10:11:05]: [Transporter]: DBG-X: Returning 0
[10:11:05]: ------------------------------------------------------------------------------------------------------
[10:11:05]: Successfully uploaded package to iTunes Connect. It might take a few minutes until it's visible online.
[10:11:05]: ------------------------------------------------------------------------------------------------------
[10:11:06]: Variable Dump:
[10:11:06]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios deploy", :VERSION_NUMBER=>"300000.0.8", :BUILD_NUMBER=>"There does not seem to be a CURRENT_PROJECT_VERSION key set for this project.  Add this key to your target's expert build settings.", :PRODUCE_APPLE_ID=>"965582748", :CERT_FILE_PATH=>"/Volumes/Vet2Pet/Vet2Pet_builds/advancedanimalcareofco-ver300000.0.8/ios/project/UH2S9ZYS79.cer", :CERT_CERTIFICATE_ID=>"UH2S9ZYS79", :SIGH_PROFILE_PATH=>"/Volumes/Vet2Pet/Vet2Pet_builds/advancedanimalcareofco-ver300000.0.8/ios/project/AppStore_com.worldbizapps.SID220392.mobileprovision", :SIGH_PROFILE_PATHS=>["/Volumes/Vet2Pet/Vet2Pet_builds/advancedanimalcareofco-ver300000.0.8/ios/project/AppStore_com.worldbizapps.SID220392.mobileprovision"], :SIGH_UDID=>"7845814c-c912-4e62-98ea-205e9fa3e5ee", :SIGH_PROFILE_TYPE=>"app-store", :IPA_OUTPUT_PATH=>"/Volumes/Vet2Pet/Vet2Pet_builds/advancedanimalcareofco-ver300000.0.8/ios/project/AdvAnimCare.ipa", :DSYM_OUTPUT_PATH=>"/Volumes/Vet2Pet/Vet2Pet_builds/advancedanimalcareofco-ver300000.0.8/ios/project/AdvAnimCare.app.dSYM.zip", :XCODEBUILD_ARCHIVE=>"/Users/vet2pet/Library/Developer/Xcode/Archives/2016-03-16/AdvAnimCare 2016-03-16 10.04.23.xcarchive"}
[10:11:06]: Upload binary failed

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | increment_version_number            | 9           |
| 4    | increment_build_number              | 1           |
| 5    | produce                             | 32          |
| 6    | cert                                | 7           |
| 7    | sigh                                | 12          |
| 8    | pem                                 | 2           |
| 9    | pem                                 | 1           |
| 10   | gym                                 | 107         |
| 11   | deliver                             | 305         |
+------+-------------------------------------+-------------+

[10:11:10]: fastlane finished with errors

[!] Upload binary failed

```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:

```ruby
fastlane_version "1.55.0"

require ENV["VARIABLES_FILE"]

default_platform :ios

def certificate_name(certificate_path)
  subject = `openssl x509 -in "#{certificate_path}" -inform der -noout -sha1 -subject`
  subject.match(/.*CN=(.*)\/OU=.*/)[1]
end

platform :ios do
  before_all do
  end

  desc "Deploy a new version to the App Store"
  lane :deploy do |options|
    #team_id $v2p_team_id

    increment_version_number(version_number: ENV["VERSION_NUM"])
    increment_build_number(build_number: options[:build_number])

    # snapshot(
    #   scheme: $v2p_app_name
    # )
    #
    # frameit
    
    # Create app id in member center and create app in itunes connect
    produce(
      team_id: $v2p_team_id,
      username: $v2p_apple_id,
      app_name: $v2p_app_name,
      app_identifier: $v2p_app_identifier,
      skip_itc: false
    )
    
    # Generate key and signing cert in member center
    cert(
      team_id: $v2p_team_id,
      username: $v2p_apple_id,
      development: false
    )
    
    # Create provisioning profile using previously generated cert
    sigh(
      team_id: $v2p_team_id,
      username: $v2p_apple_id,
      app_identifier: $v2p_app_identifier
    )

    # Generate APNS certs
    # !!! If you change password you must also change it in our Vets schema in the app !!!
    pem(
      team_id: $v2p_team_id,
      username: $v2p_apple_id,
      app_identifier: $v2p_app_identifier,
      p12_password: '<edited>',
      pem_name: $v2p_app_identifier+"-apnProd",
      output_path: '/Volumes/Vet2Pet/Vet2Pet_pems'
    )

    pem(
      development: true,
      team_id: $v2p_team_id,
      username: $v2p_apple_id,
      app_identifier: $v2p_app_identifier,
      p12_password: '<edited>',
      pem_name: $v2p_app_identifier+"-apnDev",
      output_path: '/Volumes/Vet2Pet/Vet2Pet_pems'
    )

    gym(
      #app_identifier: $v2p_app_identifier,
      scheme: $v2p_app_name,
      xcargs: "HEADER_SEARCH_PATHS='$(OBJROOT)/UninstalledProducts/$(PLATFORM_NAME)/include'",
      provisioning_profile_path: Actions.lane_context[Actions::SharedValues::SIGH_PROFILE_PATH],
      codesigning_identity: certificate_name(Actions.lane_context[Actions::SharedValues::CERT_FILE_PATH])
    )
    
    
    puts "app id: " + Actions.lane_context[Actions::SharedValues::PRODUCE_APPLE_ID]
    
    deliver(force: true,
      #team_id: $v2p_team_id,
      username: $v2p_apple_id,
      app_identifier: $v2p_app_identifier,
      app: Actions.lane_context[Actions::SharedValues::PRODUCE_APPLE_ID],
      skip_screenshots: true,
      skip_metadata: false,
      submit_for_review: false,
      automatic_release: false,
      price_tier: 0,
      app_icon: "app-store-icon.png",
      copyright: "Use it please",
      primary_category: "Business",
      description: {"en-US" => "App description"},
      keywords: {"en-US" => ["keyword"]},
      name: {"en-US" => $v2p_app_name}
    )
  end

  # You can define as many lanes as you want

  after_all do |lane|
  end

  error do |lane, exception|
  end
end


# More information about multiple platforms in fastlane: 
# https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md
```

### Environment

fastlane version (fastlane -v): fastlane 1.66.0

Do you use bundler, rbenv or rvm?

No. ruby 2.2.3p173 installed via homebrew.

**Comment by calebhicks** [comment] 2016-03-16 15:01
Thanks for the additional report @pauldowman.

Duplicate of issue #3780 and #3768 with Spaceship and the tools that depend on it. In this case, Deliver. @revile posted some additional information in #3768 regarding the differences between the Spaceship request and the request through the web UI.

Looking forward to a fix.

**Comment by pauldowman** [comment] 2016-03-16 15:41
Ah, sorry for the duplicate, I must have been posting this at the same time as #3780!

**Comment by calebhicks** [comment] 2016-03-16 15:43
@pauldowman Don't apologize. I only commented that it was a duplicate to point out that there are multiple users reporting the issue.

More information is always better for those trying to tackle the issue. They'll close and duplicate as needed.

**Comment by pauldowman** [comment] 2016-03-16 15:44
BTW, #3780 is also closed now and the title of #3768 doesn't seem to fit with what I saw, (though I'm sure it's technically correct). I'm not sure if someone looking at the issues would immediately see that it's already known.

**Comment by calebhicks** [comment] 2016-03-16 20:27
@mfurtak I don't want to put any pressure on this, I appreciate all you do and put into Fastlane. I'm just curious if you might have an ETA or time you'd hope to have this shipped? 

I have a client project that I had hoped to hand off today, but it will need to wait until this is fixed. I'd like to give them an ETA from my end if at all possible. 

But again, no pressure. Thank you again for the work you put into Fastlane, I use it daily on multiple projects, it's a huge lifesaver. 🚀👍

**Comment by asfalcone** [comment] 2016-03-16 22:33
@calebhicks Sorry this is causing so much trouble! We know you rely on fastlane for important stuff.

We're hoping to look into it today or tomorrow since we've seen that it is impacting a number of people!

**Comment by revile** [comment] 2016-03-16 22:40
@asfalcone I've made a PR to get this started (assuming it is the same issue I raised in #3768). I realise it's rough so if you guys are on to it then feel free to decline :)

**Comment by asfalcone** [comment] 2016-03-16 23:41
@calebhicks https://github.com/fastlane/fastlane/pull/3790 Should address the erroneous `[!] Upload binary failed` message! We should have a release out in just a bit!

**Closed** 2016-03-16 23:43 UTC
Labels: deliver, spaceship

**Comment by KrauseFx** [comment] 2016-03-16 23:48
We just pushed a fix, could you try updating to the latest version of `deliver` and let us know if that fixes your problem :+1: https://github.com/fastlane/deliver/releases/tag/1.10.4

**Comment by pauldowman** [comment] 2016-03-17 13:24
Fixed for me! Thanks, you guys are awesome. :star2:
