### ISSUE TITLE
set_github_release action says the release already exists

### ISSUE THREAD

**Issue by toshi0383** [fastlane/fastlane#575] opened 2015-09-06 14:58 UTC
Here is my app's [repo](https://github.com/toshi0383/LGTM) .  
`fastlane mac release` gives me below.

What's wrong here ? I didn't push any tags named '20' .

```
[23:52:16]: Successfully stored the archive. You can find it in the Xcode Organizer.
[23:52:16]: cd '/Users/toshi0383/Library/Developer/Xcode/Archives/2015-09-06/LGTM 2015-09-06 23.51.41.xcarchive/dSYMs' && zip -r '/Users/toshi0383/dev/LGTM/LGTM.app.dSYM.zip' 'LGTM.app.dSYM'

[23:52:16]: Successfully exported and compressed dSYM file.
[23:52:16]: Successfully exported the .app file:
[23:52:16]: ./LGTM.app
[23:52:16]: ------------------------------
[23:52:16]: --- Step: get_build_number ---
[23:52:16]: ------------------------------
[23:52:16]: [SHELL COMMAND]: cd /Users/toshi0383/dev/LGTM && agvtool what-version -terse
[23:52:16]: [SHELL]: 20
[23:52:16]: --------------------------------
[23:52:16]: --- Step: set_github_release ---
[23:52:16]: --------------------------------
[23:52:16]: Creating release of toshi0383/LGTM on tag "20" with name "".
[23:52:16]: Will also upload assets ["./LGTM.app"].
[23:52:17]: Release on tag 20 already exists!

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | increment_build_number              | 0           |
| 4    | git commit -am "build number"       | 0           |
| 5    | gym                                 | 36          |
| 6    | get_build_number                    | 0           |
| 7    | set_github_release                  | 0           |
+------+-------------------------------------+-------------+

[23:52:17]: fastlane.tools finished successfully 🎉
```

thanks !

**Comment by KrauseFx** [comment] 2015-09-06 16:07
I ran into the same issue just 2 days ago and thought it was a networking issue cc @czechboy0

**Comment by KrauseFx** [comment] 2015-09-06 16:08
Oh, you're using the new assets feature already? :rocket:

**Comment by czechboy0** [comment] 2015-09-06 16:43
Yeah I know what it is, basically it happens when you don't pass `commitish` (the branch to create the tag on). I'll PR a fix in a sec.

**Comment by KrauseFx** [comment] 2015-09-06 16:45
So falling back to `master` by default it should work?

**Comment by czechboy0** [comment] 2015-09-06 16:45
Yeah the problem is it's passing `nil` instead of not including the `commitish` key. Let me fix it.

**Comment by toshi0383** [comment] 2015-09-09 13:04
Is this fix in 1.25.0 ? I'm still experiencing this issue.
I created a sample repo [here](https://github.com/toshi0383/fastlane-playground).
On master branch, do `fastlane mac release` to reproduce.

```
 $ fastlane mac release
[22:01:34]: Driving the lane 'mac release' 🚀
[22:01:34]: --------------------------------
[22:01:34]: --- Step: set_github_release ---
[22:01:34]: --------------------------------
[22:01:34]: Creating release of toshi0383/fastlane-playground on tag "1" with name "".
[22:01:34]: Will also upload assets ["./Sample.file"].
[22:01:35]: Release on tag 1 already exists!

+------+--------------------+-------------+
|            fastlane summary             |
+------+--------------------+-------------+
| Step | Action             | Time (in s) |
+------+--------------------+-------------+
| 1    | set_github_release | 1           |
+------+--------------------+-------------+

[22:01:35]: fastlane.tools finished successfully 🎉
```

**Comment by KrauseFx** [comment] 2015-09-10 00:59
It's been working for me today. The latest release should have this patch already.

**Comment by toshi0383** [comment] 2015-09-10 02:31
still got error on 1.25.1 ...

**Comment by toshi0383** [comment] 2015-09-10 15:25
I think I figured out.
If I put `committish` , it always gives the error ?

```
platform :mac do
  lane :release do
    buildNumber = "4"
    appFile = "./fastlane/Sample.file"
    githubToken = ENV["GITHUB_API_TOKEN"]
    set_github_release(
        repository_name: "toshi0383/fastlane-playground",
        api_token: githubToken,
        name: "test",
        tag_name: buildNumber,
        description: "hello",
        upload_assets: [appFile],
#        commitish: buildNumber, # << causes error
    )
  end
end
```

**Comment by czechboy0** [comment] 2015-09-10 16:46
@toshi0383 `commitish` must be a name of a branch on which to create the tag. If it's not supplied, GitHub creates the tag on the default branch. Here you have `commitish` as `4`... is that a branch name?

**Comment by czechboy0** [comment] 2015-09-10 16:47
The problem seems to be that you're supplying an invalid `commitish`, which GitHub responds to with the same error as when the tag already exists (dumb, I know).

**Comment by toshi0383** [comment] 2015-09-11 00:11
If I put 'master' to committish, it worked fine. Thanks for the advice !!

**Comment by czechboy0** [comment] 2015-09-11 00:32
Happy to help! 

Might be an improvement - to validate the commitish and print error if no commit or branch can be found. That would allow for much more accurate error message in this case.

**Comment by toshi0383** [comment] 2015-09-14 13:07
:+1: 

I think it's nicer to have instruction error messages as you suggest.

Because.. today I got another case.
If I comment-out description parameter as below, I get the error saying "Release on tag 6 already exists!".

```
platform :mac do
  lane :release do
    buildNumber = "6"
    appFile = "./fastlane/Sample.file"
    githubToken = ENV["GITHUB_API_TOKEN"]
    set_github_release(
        repository_name: "toshi0383/fastlane-playground",
        api_token: githubToken,
        name: "test",
        tag_name: buildNumber,
#        description: "hello",
        upload_assets: [appFile],
        commitish: "master",
    )
  end
end
```

**Comment by ksm** [comment] 2015-09-16 08:09
Just reporting in that `set_github_release` worked fine for me yesterday (Fastlane 1.26.0).

How I call it:

    set_github_release(
      tag_name: prefixed_version,
      name: "#{prefixed_version} (#{build_number})",
      description: release_notes,
      is_prerelease: true,
      api_token: github_token,
      repository_name: repo_name,
    )

Thank you @czechboy0 and @KrauseFx.

**Comment by czechboy0** [comment] 2015-09-16 09:04
@toshi0383 Oh, I'll take a look at that later - it's possible that when you don't provide some of the params then GitHub rejects the JSON (which is the same error as when the release already exists).

**Comment by ksm** [comment] 2015-09-23 10:29
The problem just resurfaced for me. Here's part of the log:

```
[12:24:14]: Committed "v0.3-alpha.7 (10)" 💾.
[12:24:14]: -------------------------
[12:24:14]: --- Step: add_git_tag ---
[12:24:14]: -------------------------
[12:24:14]: Adding git tag 'v0.3-alpha.7' 🎯.
[12:24:14]: [SHELL COMMAND]: git tag "v0.3-alpha.7"
[12:24:14]: --------------------------------
[12:24:14]: --- Step: push_to_git_remote ---
[12:24:14]: --------------------------------
[12:24:14]: [SHELL COMMAND]: pwd
[12:24:14]: [SHELL]: /Users/karol/Desktop/myApp
[12:24:14]: [SHELL COMMAND]: git push origin master:master --tags
[12:24:16]: [SHELL]: To git@github.com:ksm/myApp.git
[12:24:16]: [SHELL]: e1ec939..0a10e9a  master -> master
[12:24:16]: [SHELL]: * [new tag]         v0.3-alpha.7 -> v0.3-alpha.7
[12:24:16]: Sucesfully pushed to remote.
[12:24:16]: --------------------------------
[12:24:16]: --- Step: set_github_release ---
[12:24:16]: --------------------------------
[12:24:16]: Creating release of ksm/myApp on tag "v0.3-alpha.7" with name "v0.3-alpha.7 (10)".
[12:24:17]: {"message":"Validation Failed","errors":[{"resource":"Release","code":"custom","message":"Published releases must have a valid tag"}],"documentation_url":"https://developer.github.com/v3/repos/releases/#create-a-release"}
[12:24:17]: Release on tag v0.3-alpha.7 already exists!
```

**Comment by ksm** [comment] 2015-09-23 16:29
@czechboy0 Worked around the above regression by explicitly passing in the `commitish`. 

```
current_branch = git_branch()

set_github_release(
  ...
  commitish: current_branch
)
```

**Comment by KrauseFx** [comment] 2015-09-23 17:45
@ksm @czechboy0 I added the output of the raw error message, which makes things much easier now:

```
Published releases must have a valid tag
```

@ksm Apparently GitHub doesn't like your `prefixed_version` tag

**Comment by czechboy0** [comment] 2015-09-26 12:08
@ksm Can you confirm whether this helped please?

**Comment by czechboy0** [comment] 2015-09-26 15:49
@ksm I see in your fastlane output above that you're adding the tag in a separate step first. You **don't need** to do that. The `set_github_release` action creates the tag for you on the branch passed as `commitish` (could also be a commit, but branch name is a more common case). 

Try to remove the `add_git_tag` action and try again with your original parameters.

**Comment by KrauseFx** [comment] 2015-09-26 18:03
@czechboy0 Very good point! @ksm please confirm that this solves your issue.

**Comment by ksm** [comment] 2015-09-29 15:16
Confirming that it works. Thank you. :bowtie: 

I don't want to remove the `add_git_tag` action from my Fastfile, because I feel like keeping it there makes it explicit that the lane creates a tag. IMO one Fastlane action should have one responsibility.

**Comment by KrauseFx** [comment] 2015-09-29 16:48
@ksm so you're saying you want to create only the GitHub release without a tag? A GitHub release is just a tag with text appended.

**Comment by ksm** [comment] 2015-09-29 21:18
I'm saying I want to add a tag, and I want to setup a GitHub release.

`add_git_tag` - adds a git tag
`set_github_release` - sets up a github release

The above behavior is exactly as it should be. That `set_github_release` can also add a tag I consider a convenience and a side-effect, which I'm not making use of.

I'm also saying I am now a happy Fastlane user. Both actions are now working for me.

**Comment by czechboy0** [comment] 2015-09-29 21:32
Actually, the action `set_github_release` isn't doing that, it's the GitHub API - when you're creating a release, it automatically creates a tag if one doesn't already exist. So by just using `set_github_release`, you're saving time and bandwidth :)

But I see your point about keeping actions single-purpose and I agree with that. However, this is not the action doing this, just the API. In which case, I think relying on that tag being created for you is reasonable.

**Comment by KrauseFx** [comment] 2015-09-29 21:54
Thanks @czechboy0 :+1:

**Comment by ohwutup** [comment] 2016-02-24 17:40
going to close this issue for now because there hasn't been any recent activity, but if there are still issues any of you are having, please feel free to reopen it! :star:

**Closed by ohwutup** 2016-02-24 17:40 UTC
