### ISSUE TITLE
Deliver wrongly uploading binary to Testflight. 

### ISSUE THREAD

**Issue by harryblam** [fastlane/fastlane#9328] opened 2017-05-31 13:04 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When uploading our app to iTunesConnect via deliver, it automatically pushes the same build to TestFlight internal testing. Is there any way to upload to App Store, but not to TestFlight using deliver?

It is worth noting that we have another lane which we use to upload to TestFlight internal testing, with the same bundle id, however built with a different configuration.

Thanks

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rvm/gems/ruby-2.4.0-rc1/bin/fastlane     |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.0-rc1/lib            |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2"

default_platform :ios

platform :ios do
  before_all do

  end

  desc "Runs all the tests"
  lane :test do
    cocoapods
    clear_derived_data
    scan(
      scheme: "WeVat",
      device: "iPhone 7",
      configuration: "Debug",
      clean: true
    )
  end

  lane :build do |options|
    cocoapods
    clear_derived_data
    cert()
    sigh()
    gym(
      workspace: "WeVat.xcworkspace",
      scheme: "WeVat",
      configuration: options[:configuration],
      clean: true
      )
  end

  lane :screenshots do
    reset_simulators
    snapshot
    frameit(gold: true)
    deliver
  end

  lane :increment_testflight_build_no do
    increment_build_number(
      build_number: latest_testflight_build_number + 1,
      xcodeproj: "WeVat.xcodeproj"
    )
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    #test
    increment_testflight_build_no
    ipa = build(configuration: "Beta")
    testflight(ipa: ipa)
  end

  desc "Deploy a new version to the App Store"
  lane :appstoredeploy do
    test
    increment_testflight_build_no
    ipa = build(configuration: "App Store")
    appstore(
      ipa: ipa,
      skip_screenshots: true,
      force: true,
      skip-deploy: true
      )
  end

  after_all do |lane|
  end

  error do |lane, exception|
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.wevat" # The bundle identifier of your app
apple_id "harrybloom18@gmail.com" # Your Apple email address

team_id "..."  # Developer Portal Team ID
itc_team_name "..."

</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.35.1  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.2        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.14.3       |
| io-console                | 0.4.6        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.26       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| faraday_middleware        | 0.11.0.1     |
| json                      | 2.0.2        |
| openssl                   | 2.0.1        |
</details>


*generated on:* **2017-05-31**
</details>
[INSERT OUTPUT HERE]

**Comment by ohayon** [comment] 2017-05-31 14:39
Hey @harryblam, thanks for raising the issue. When builds are uploaded to iTunesConnect via _deliver_ or Xcode, they are automatically available for internal testing in TestFlight (after they finish processing). This is the intended behavior of iTunesConnect and therefor _deliver_. The builds will not however be available for external testing until you add external groups to the builds via iTC on the web or with _pilot_ (which is what I imagine you are using for your other lane). 

I am going to close this issue as it is the way things are supposed to work, but please feel free to continue discussion if you have any more questions. Thanks again! 🚀 🐙

**Closed by ohayon** 2017-05-31 14:39 UTC

**Comment by harryblam** [comment] 2017-05-31 16:24
Thanks for the quick reply @ohayon !

Ah right, that kind of sucks! We have one app where we want to distribute internally at the same time as distributing to App Store, however each built with a different configuration.

The alternative I guess would be to have two different bundle ids for the apps but I felt that we shouldn't need that. Can you suggest any other way we can achieve this?

**Comment by harryblam** [comment] 2017-06-01 10:26
Yeah my thoughts also... The only trouble in the second way you mentioned is that there is no way to differentiate between external and internal builds on the TestFlight app if i'm not mistaken.

Therefore the team will not know if they're downloading the prod or the beta version...

Anyway, thanks for the help on this one @ohayon 👍🏻
