### ISSUE TITLE
Scan stuck on xcodebuild action while fired on bitrise

### ISSUE THREAD

**Issue by cojoj** [fastlane/fastlane#5779] opened 2016-08-17 11:54 UTC
### Issue Description

I have `fastlane` configured for my project and recently I've decided I'd go and try bitrise.io.
Most things seems to work correctly, but I cannot get `scan` to work with this CI.
Curious thing that `gym` works without any problems and also `scan` works perfectly fine on my local machine.

##### Complete output when running fastlane, including the stack trace and command used

```
$ cd .

 (i) No Gemfile found - using system installed fastlane ...
 (i) Updating fastlane ...
$ gem install fastlane --no-document
Successfully installed gh_inspector-1.0.2
Successfully installed fastlane_core-0.50.2
Successfully installed spaceship-0.31.2
Successfully installed cert-1.4.1
Successfully installed sigh-1.9.0
Successfully installed match-0.6.2
Successfully installed supply-0.7.0
Successfully installed scan-0.11.3
Successfully installed pilot-1.10.0
Successfully installed gym-1.7.0
Successfully installed produce-1.2.0
Successfully installed pem-1.3.2
Successfully installed deliver-1.13.2
Successfully installed frameit-2.7.0
Successfully installed snapshot-1.13.1
Successfully installed word_wrap-1.0.0
Successfully installed xcode-install-2.0.2
Successfully installed fastlane-1.100.0
18 gems installed

Fastlane version:
$ fastlane --version
fastlane 1.100.0

Run fastlane:
$ fastlane run_unit_tests
[04:39:09]: ------------------------------
[04:39:09]: --- Step: default_platform ---
[04:39:09]: ------------------------------
[04:39:09]: Driving the lane 'ios run_unit_tests' 🚀
[04:39:09]: FastfileHelper imported
[04:39:09]: --------------------------------
[04:39:09]: --- Step: clear_derived_data ---
[04:39:09]: --------------------------------
[04:39:09]: Derived Data path located at: /Users/vagrant/Library/Developer/Xcode/DerivedData
[04:39:09]: Successfully cleared Derived Data ♻️
[04:39:09]: -----------------------------------
[04:39:09]: --- Step: clean_build_artifacts ---
[04:39:09]: -----------------------------------
[04:39:09]: Cleaned up build artifacts 🐙
[04:39:09]: Using options: {:schemeForTests=>"All tests", :configurationForTests=>"Debug"}
[04:39:09]: ------------------
[04:39:09]: --- Step: scan ---
[04:39:09]: ------------------
[04:39:09]: xcodebuild -list -workspace ./Jodel.xcworkspace
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
lane :run_unit_tests do |options|
    clear_derived_data
    clean_build_artifacts

    ###################################
    # Default parameters
    ###################################
    options = {
        schemeForTests: "All tests",
        configurationForTests: "Debug"
    }.merge(options)
    puts "Using options: #{options.inspect}"
    ###################################
    # Run tests
    ###################################
    jdl_run_tests(options[:schemeForTests], options[:configurationForTests])
end
```

```ruby
def jdl_run_tests(scheme, configuration)
    # scan(scheme: scheme, clean: true, device: "iPhone 6s", configuration: configuration, verbose: true)
    scan(scheme: scheme, configuration: configuration, verbose: true)
end
```

### Environment

https://github.com/bitrise-io/bitrise.io/blob/master/system_reports/osx-xcode-7.3.log

**Comment by matthewjsloane** [comment] 2016-08-17 18:44
Possible duplicate of/related to [this issue](https://github.com/fastlane/fastlane/issues/5163)?

I've had the -showBuildSettings command hang as well in CI, and can reproduce infrequently (~1/100 times) when running a script to do this locally repeatedly.

**Comment by cojoj** [comment] 2016-08-18 05:34
I went through the possibilities... Tested almost everything manually and it seems that it hang because of the `configuration` I pass as an argument.
Original comand was:
```ruby
scan(scheme: scheme, clean: true, device: "iPhone 6s", configuration: configuration, verbose: true)
```

And now I have something like:
```ruby
scan(scheme: scheme, clean: true, device: "iPhone 6s", verbose: true)
```

And latter works just fine, but... in `Release` configuration. Any ideas what am I doing wrong? 😅

**Comment by vpolouchkine** [comment] 2016-08-22 20:30
Hey @cojoj, would you be able to provide a repro project? That would help tremendously in debugging this.

**Comment by cojoj** [comment] 2016-08-22 20:48
Well @vpolouchkine that'd be actually hard... But I suspect it can be CocoaPods related, cause when I change something in our `Podfile` everything seems to work (even with `Debug`). `xcodebuild` is too silent on this one and I cannot make 100% statement on what is actually failing 😭

**Comment by cojoj** [comment] 2016-08-23 12:47
I couldn't find it anywhere, cause it later goes to Fastlane Core, but maybe `scan` is piping this `xcodebuild -list -workspace ./Jodel.xcworkspace`? 

https://openradar.appspot.com/27595098

**Comment by TKBurner** [comment] 2016-08-23 21:23
Hi @cojoj Thanks for following up. Can you add the --verbose flag to see if there is more output to help us out here. Thanks!

**Comment by cojoj** [comment] 2016-08-24 07:40
@TKBurner `scan` is already running with `--verbose` flage and IMO it's still not telling everything 😜

**Comment by TKBurner** [comment] 2016-08-24 16:08
Hi @cojoj Thanks for following up. Can you run the command `xcodebuild -list -workspace ./Jodel.xcworkspace` on your machine and let me know if it runs successfully?

Thanks!

**Comment by cojoj** [comment] 2016-08-24 16:19
Yes, @TKBurner it always runs successfully 😉

**Comment by TKBurner** [comment] 2016-08-26 15:41
Thanks for following up @cojoj. Is your keychain unlocked? Can you send me your full input to `scan`? I want to take a look. Thanks!

**Comment by mooshee** [comment] 2016-08-26 18:06
I'm having the same issue, although it's stuck when I try to run `fastlane init`.

```
$ fastlane init --verbose
DEBUG [2016-08-26 14:03:42.30]: Checking if there are any plugins that should be loaded...
INFO [2016-08-26 14:03:42.31]: Detected iOS/Mac project in current directory...
INFO [2016-08-26 14:03:42.31]: This setup will help you get up and running in no time.
INFO [2016-08-26 14:03:42.31]: fastlane will check what tools you're already using and set up
INFO [2016-08-26 14:03:42.31]: the tool automatically for you. Have fun! 
INFO [2016-08-26 14:03:42.31]: Created new folder './fastlane'.
WARN [2016-08-26 14:03:42.31]: xcodebuild -list -workspace ./ExampleApp.xcworkspace
```

Running `xcodebuild -list -workspace ./ExampleApp.xcworkspace` from the command line works just fine, spitting out the all of the scheme names.

**Comment by cojoj** [comment] 2016-08-26 18:57
@TKBurner firs of all, keychain shouldn't be an issue since I pass all credentials in env variables, so fastlane doesn't have to hit keychain at all.
And regarding exact `scan` inputs. Here you go:
```
# This one is for Unit Tests
scan(scheme: "All tests", clean: true, device: "iPhone 6s", verbose: true)
```
```
# This one for UI Tests
scan(scheme: 'All UI tests', configuration: 'DebugUITests', clean: true, device: "iPhone 6s", verbose: true)
```

**Comment by TKBurner** [comment] 2016-08-29 19:58
@cojoj Have you used this setup, https://github.com/bitrise-io/steps-fastlane? Thanks!

**Comment by cojoj** [comment] 2016-08-30 07:52
Yes @TKBurner I'm using this step.

**Comment by TKBurner** [comment] 2016-08-30 19:50
Hi @cojoj Thanks for continuing to work with me on this. 

To confirm: you are able to run xcodebuild -list -workspace ./Jodel.xcworkspace on bitrise?

Also, can you  let me know which scan command is working on bitrise? Thanks!

**Comment by mooshee** [comment] 2016-08-31 02:39
It appears `fastlane-1.102.0` fixes the issue for me.

**Comment by cojoj** [comment] 2016-08-31 04:57
@TKBurner `xcodebuild -list -workspace ./Jodel.xcworkspace` works on bitrise. Actually running tests directly with their flow works as well (so we had to skip `scan` for now).
It's not that some commands work and some don't. It's rather general problem, cause I've faced same issues locally. It's not deterministic... It's like playing russian roulette 😜

**Comment by TKBurner** [comment] 2016-08-31 19:27
@cojoj Any chance you can check out the new update for fastlane? `sudo gem update fastlane`

Thanks!

**Comment by PlayDevelop** [comment] 2016-09-05 09:42
@TKBurner updated to 1.102.0 and solved this problem for me.  Running xcode 7.3.1

**Comment by tsheaff** [comment] 2016-09-06 23:03
I'm seeing a similar non-deterministic hang.  It seems to hang about ~70% of the time.  Here's the full print, including stack trace, when I cancel the script during the hang:

```
Tylers-MacBook-Pro:ios tsheaff$ fastlane dev notes:"fix super-fast Ken Burns" --verbose
DEBUG [2016-09-06 15:53:12.13]: Checking if there are any plugins that should be loaded...
DEBUG [2016-09-06 15:53:12.16]: Using notes: fix super-fast Ken Burns
INFO [2016-09-06 15:53:12.17]: -------------------------------------------------
INFO [2016-09-06 15:53:12.17]: --- Step: Verifying required fastlane version ---
INFO [2016-09-06 15:53:12.17]: -------------------------------------------------
INFO [2016-09-06 15:53:12.17]: fastlane version valid
INFO [2016-09-06 15:53:12.18]: ------------------------------
INFO [2016-09-06 15:53:12.18]: --- Step: default_platform ---
INFO [2016-09-06 15:53:12.18]: ------------------------------
INFO [2016-09-06 15:53:12.28]: Driving the lane 'dev' 🚀
INFO [2016-09-06 15:53:12.29]: ------------------------------------
INFO [2016-09-06 15:53:12.29]: --- Step: increment_build_number ---
INFO [2016-09-06 15:53:12.29]: ------------------------------------
INFO [2016-09-06 15:53:12.29]: $ cd /Users/tsheaff/Code/private/calm/ios && agvtool next-version -all && cd -
INFO [2016-09-06 15:53:12.59]: ▸ Setting version of project Calm to:
INFO [2016-09-06 15:53:12.59]: ▸ 418.
INFO [2016-09-06 15:53:12.61]: ▸ Also setting CFBundleVersion key (assuming it exists)
INFO [2016-09-06 15:53:12.63]: ▸ Updating CFBundleVersion in Info.plist(s)...
INFO [2016-09-06 15:53:12.64]: ▸ Updated CFBundleVersion in "Calm.xcodeproj/../app/Info.plist" to 418
INFO [2016-09-06 15:53:12.65]: ▸ Updated CFBundleVersion in "Calm.xcodeproj/../siri/Info.plist" to 418
INFO [2016-09-06 15:53:12.66]: ▸ Updated CFBundleVersion in "Calm.xcodeproj/../watch/app/Info.plist" to 418
INFO [2016-09-06 15:53:12.67]: ▸ Updated CFBundleVersion in "Calm.xcodeproj/../watch/extension/Info.plist" to 418
INFO [2016-09-06 15:53:12.68]: ▸ Updated CFBundleVersion in "Calm.xcodeproj/../widget/Info.plist" to 418
INFO [2016-09-06 15:53:12.68]: ▸ /Users/tsheaff/Code/private/calm/ios
(in /Users/tsheaff/Code/private/calm/ios)
(in /Users/tsheaff/Code/private/calm/ios)
fetched programs
fetched scenes
INFO [2016-09-06 15:53:18.47]: -----------------
INFO [2016-09-06 15:53:18.47]: --- Step: gym ---
INFO [2016-09-06 15:53:18.47]: -----------------
WARN [2016-09-06 15:53:18.53]: Using legacy build system - waiting for radar to be fixed: https://openradar.appspot.com/radar?id=4952000420642816
WARN [2016-09-06 15:53:18.59]: xcodebuild -list -workspace ./Calm.xcworkspace
^CWARN [2016-09-06 15:53:24.27]: Variable Dump:
INFO [2016-09-06 15:53:24.27]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>nil, :LANE_NAME=>"dev", :BUILD_NUMBER=>"418"}
INFO [2016-09-06 15:53:24.27]: Successfully generated documentation at path '/Users/tsheaff/Code/private/calm/ios/fastlane/README.md'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | increment_build_number              | 0           |
| 4    | gym                                 | 5           |
+------+-------------------------------------+-------------+

ERROR [2016-09-06 15:53:24.27]: fastlane finished with errors
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.50.3/lib/fastlane_core/helper.rb:17:in ``': Interrupt
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.50.3/lib/fastlane_core/helper.rb:17:in `backticks'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.50.3/lib/fastlane_core/project.rb:219:in `build_settings'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.50.3/lib/fastlane_core/project.rb:177:in `mac?'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.8.0/lib/gym/detect_values.rb:66:in `detect_platform'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.8.0/lib/gym/detect_values.rb:25:in `set_additional_default_values'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.8.0/lib/gym.rb:26:in `config='
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.8.0/lib/gym/manager.rb:4:in `work'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/actions/gym.rb:22:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/runner.rb:190:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/runner.rb:175:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/runner.rb:174:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/runner.rb:174:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/runner.rb:100:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/fast_file.rb:140:in `method_missing'
	from Fastfile:19:in `block in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/runner.rb:49:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/runner.rb:45:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/runner.rb:45:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/commands_generator.rb:49:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.50.3/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/commands_generator.rb:246:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/commands_generator.rb:20:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

When I print the command in `lib/fastlane_core/project.rb:219` I get `xcodebuild -showBuildSettings -workspace ./Calm.xcworkspace -scheme Calm`. When I run that on its own I get the exact same non-determistic hang behavior.  Here is my full fastfile, which references a few custom scripts I call using rake:

```ruby
# Fastfile docs: https://github.com/fastlane/fastlane/tree/master/docs
# Actions here: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

fastlane_version "1.102.0"

default_platform :ios

desc "Runs all the tests"
lane :test do
  scan
end

desc "Submit a new Dev Build to Crashlytics"
lane :dev do |options|
  increment_build_number
  full_version = `rake full_app_version`

  system("rake fetch_bundles")
  gym(
    scheme: "Calm",
    configuration: "Dev-Release",
    xcargs: "ARCHIVE=YES", # Used to tell the Fabric run script to upload dSYM file
    use_legacy_build_api: true,
  )

  crashlytics(
    api_token: "<REDACTED>",
    build_secret: "<REDACTED>",
    notes: options[:notes] || "new dev build #{full_version}",
    groups: "Everyone",
  )
  system("rm -rf calm.ipa")
  system("rake push_to_git[\"dev build #{full_version}\"]")
end

desc "Deploy a new version to the App Store"
lane :itunes do
  increment_build_number
  full_version = `rake full_app_version`

  system("rake fetch_bundles")
  gym(
    scheme: "Calm",
    clean: true,
    use_legacy_build_api: true,
    xcargs: "ARCHIVE=YES",
  )

  deliver(
    force: true,
  )

  system("rm -rf calm.ipa")
  system("rake push_to_git[\"app store build #{full_version}\"]")
  system("rake tag_version")
end
```

**Comment by tsheaff** [comment] 2016-09-06 23:05
Re-reading this thread, it looks like my hang is possibly a fully unrelated issue. Let me know if you want me to file a separate issue.

**Comment by tsheaff** [comment] 2016-09-06 23:12
My issue is fixed by https://github.com/fastlane/fastlane/commit/9d18d6ab6e45944dfad606100ec74e7169f24706

**Comment by mfurtak** [comment] 2016-09-07 20:18
Hi all, we've shipped a workaround (#5626) and timeout/retry solution (#5188) as part of [`fastlane_core` 0.51.0](https://github.com/fastlane/fastlane/releases/tag/fastlane_core/0.51.0) 🚀 

Thanks very much for your help! Please let us know how it looks 👍

**Comment by mfurtak** [comment] 2016-09-07 20:19
We haven't yet updated `gym` and `scan` to depend on this new version of `fastlane_core` directly, so it's possible it won't be pulled in yet. If that's the case, please hang on until we get other confirmation and do releases for `gym` and `scan` 🚀

**Comment by cojoj** [comment] 2016-09-27 11:40
@mfurtak looks like so far everything works for us. I guess you can close this issue for now and if anything happens again we can reopen it, but I don't think it should stick around 😉

**Closed** 2016-09-27 14:33 UTC
Labels: awaiting-reply, question, scan
