### ISSUE TITLE
Unable to upload to AppStore

### ISSUE THREAD

**Issue by prithamprk** [fastlane/fastlane#9949] opened 2017-08-03 18:07 UTC
Still Having issue when trying to upload to the app store. Doesn't say anything regarding why it failed
FastLane version: 2.50.1

```
017-08-03T17:25:03.3692270Z [12:25:03]: Activating language en-US...
2017-08-03T17:25:20.2748000Z +---------------------+--------------------------------------+
2017-08-03T17:25:20.2764450Z |                        [33mLane Context[0m                        |
2017-08-03T17:25:20.2782470Z +---------------------+--------------------------------------+
2017-08-03T17:25:20.2798390Z | DEFAULT_PLATFORM    | ios                                  |
2017-08-03T17:25:20.2811880Z | PLATFORM_NAME       | ios                                  |
2017-08-03T17:25:20.2825210Z | LANE_NAME           | ios release                          |
2017-08-03T17:25:20.2839100Z | CERT_FILE_PATH      | /VSTS-Agent/_work/2/s/eHub/9YR86KP4  |
2017-08-03T17:25:20.2854490Z |                     | 68.cer                               |
2017-08-03T17:25:20.2867820Z | CERT_CERTIFICATE_ID | 9YR86KP468                           |
2017-08-03T17:25:20.2881910Z | SIGH_PROFILE_PATH   | /VSTS-Agent/_work/2/s/eHub/AppStore  |
2017-08-03T17:25:20.2895780Z |                     | _US.TeamSoftwareInc.eHub.mobileprov  |
2017-08-03T17:25:20.2909400Z |                     | ision                                |
2017-08-03T17:25:20.2923510Z | SIGH_PROFILE_PATHS  | ["/VSTS-Agent/_work/2/s/eHub/AppSto  |
2017-08-03T17:25:20.2937750Z |                     | re_US.TeamSoftwareInc.eHub.mobilepr  |
2017-08-03T17:25:20.2951450Z |                     | ovision"]                            |
2017-08-03T17:25:20.2965620Z | SIGH_UDID           | 9f0f928c-8d00-496b-8f29-54a87cb7bee  |
2017-08-03T17:25:20.2979520Z |                     | 3                                    |
2017-08-03T17:25:20.2993370Z | SIGH_UUID           | 9f0f928c-8d00-496b-8f29-54a87cb7bee  |
2017-08-03T17:25:20.3006680Z |                     | 3                                    |
2017-08-03T17:25:20.3027890Z | SIGH_PROFILE_TYPE   | app-store                            |
2017-08-03T17:25:20.3042760Z | IPA_OUTPUT_PATH     | /VSTS-Agent/_work/2/s/eHub/eHub.ipa  |
2017-08-03T17:25:20.3057450Z | DSYM_OUTPUT_PATH    | /VSTS-Agent/_work/2/s/eHub/eHub.app  |
2017-08-03T17:25:20.3071230Z |                     | .dSYM.zip                            |
2017-08-03T17:25:20.3083970Z | XCODEBUILD_ARCHIVE  | /Users/build/Library/Developer/Xcod  |
2017-08-03T17:25:20.3097290Z |                     | e/Archives/2017-08-03/eHub           |
2017-08-03T17:25:20.3111220Z |                     | 2017-08-03 12.22.27.xcarchive        |
2017-08-03T17:25:20.3125070Z +---------------------+--------------------------------------+
2017-08-03T17:25:20.3138830Z [12:25:20]: [31mUnexpected Error[0m
2017-08-03T17:25:20.3146260Z 
2017-08-03T17:25:20.3159570Z +------+---------------------+-------------+
2017-08-03T17:25:20.3174530Z |             [32mfastlane summary[0m             |
2017-08-03T17:25:20.3188670Z +------+---------------------+-------------+
2017-08-03T17:25:20.3202020Z | Step | Action              | Time (in s) |
2017-08-03T17:25:20.3215690Z +------+---------------------+-------------+
2017-08-03T17:25:20.3229690Z | 1    | Verifying required  | 0           |
2017-08-03T17:25:20.3243150Z |      | fastlane version    |             |
2017-08-03T17:25:20.3256310Z | 2    | default_platform    | 0           |
2017-08-03T17:25:20.3269510Z | 3    | cert                | 2           |
2017-08-03T17:25:20.3281960Z | 4    | sigh                | 4           |
2017-08-03T17:25:20.3294410Z | 5    | gym                 | 151         |
2017-08-03T17:25:20.3307650Z | 💥    | [31mdeliver[0m             | 24          |
2017-08-03T17:25:20.3321450Z +------+---------------------+-------------+
2017-08-03T17:25:20.3328280Z 
2017-08-03T17:25:20.3341340Z [12:25:20]: [31mfastlane finished with errors[0m
2017-08-03T17:25:20.3348240Z 
2017-08-03T17:25:20.3360790Z Looking for related GitHub issues on fastlane/fastlane...
2017-08-03T17:25:20.3367130Z 
2017-08-03T17:25:20.7920590Z ➡️  [33mUnexpected Error when submitting the app for review[0m
2017-08-03T17:25:20.7935880Z     https://github.com/fastlane/fastlane/issues/8819 [[31mopen[0m] 2 💬
2017-08-03T17:25:20.7949880Z     6 weeks ago
2017-08-03T17:25:20.7957010Z 
2017-08-03T17:25:20.7976810Z ➡️  [33mDeliver: Unexpected Error when selecting build[0m
2017-08-03T17:25:20.7993730Z     https://github.com/fastlane/fastlane/issues/7757 [[32mclosed[0m] 3 💬
2017-08-03T17:25:20.8007660Z     06 Apr 2017
2017-08-03T17:25:20.8014090Z 
2017-08-03T17:25:20.8027650Z ➡️  [33m"fastlane finished with errors" even though there were no errors[0m
2017-08-03T17:25:20.8042300Z     https://github.com/fastlane/fastlane/issues/8906 [[32mclosed[0m] 6 💬
2017-08-03T17:25:20.8055690Z     a week ago
2017-08-03T17:25:20.8062080Z 
2017-08-03T17:25:20.8076140Z and 9 more at: https://github.com/fastlane/fastlane/search?q=The%20request%20could%20not%20be%20completed%20because:%0A%09Unexpected%20Error&type=Issues&utf8=✓
2017-08-03T17:25:20.8084430Z 
2017-08-03T17:25:20.8098710Z 🔗  You can ⌘ + double-click on links to open them directly in your browser.
2017-08-03T17:25:20.8112750Z [31m
2017-08-03T17:25:20.8125930Z [!] The request could not be completed because:
2017-08-03T17:25:20.8139340Z 	Unexpected Error[0m
2017-08-03T17:25:21.1835450Z ##[error]/bin/bash failed with return code: 1
2017-08-03T17:25:21.1875190Z ##[error]Bash failed with error: /bin/bash failed with return code: 1
2017-08-03T17:25:21.3526980Z ##[section]Finishing: Upload to AppStore
```

**Comment by ohayon** [comment] 2017-08-03 18:21
Hey @prithamprk apologies for the issue you are having! Is it possible you could share all of the out put from your terminal and the output from `fastlane env` ? Thank you! 🚀

**Comment by ohayon** [comment] 2017-08-03 18:26
Hey again @prithamprk I am going to close this as it is a duplicate of https://github.com/fastlane/fastlane/issues/9942#issuecomment-320045222. Feel free to follow along and comment on that issue!

**Closed** 2017-08-03 18:27 UTC
