### ISSUE TITLE
Pilot export includes internal testers

### ISSUE THREAD

**Issue by colinhumber** [fastlane/fastlane#4859] opened 2016-05-26 16:39 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
When performing an export using `pilot export`, internal testers are included in the output, not just external.

##### Complete output when running fastlane, including the stack trace and command used

`pilot export`
`[10:38:23]: Successfully exported CSV to ./testers.csv`

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
N/A

### Environment

fastlane version (run `fastlane -v`):
`fastlane 1.91.0`

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
No

**Comment by vpolouchkine** [comment] 2016-05-27 21:43
Thanks for the report, we'll take a look.

**Comment by mpirri** [comment] 2016-06-02 22:14
@colinhumber I tested this on my own account and you are correct, it does return both internal and external testers. We will need to either figure out why iTunesConnect is returning all testers or else adjust the documentation for the feature. We'll look into getting this fixed on our end (no promises of when we will be able to get to it, I'm afraid), but if you feel so inclined and want to try your hand at fixing the issue yourself, we're happy to accept pull requests. :)

**Comment by mpirri** [comment] 2016-06-02 22:34
@colinhumber Actually, I continued digging into this a bit more - it does appear that `pilot` is doing the right thing for my account, at least by some definition of "right".  If, in iTunesConnect, I select **`Users and Roles`**, and then  click on the **`TestFlight Beta Testers`** tab and then click the **`External`** tab, the list I see is exactly what is exported when I do `pilot export`. However, these external testers do not correspond to the external testers for any of my apps - they appear to be the combination of internal and external testers for all of my apps. This is odd behavior for sure (maybe an iTC bug?), but it does appear that `pilot` is respecting this behavior.

Does my observation what you are seeing?

**Comment by colinhumber** [comment] 2016-06-02 22:54
Yes, I’m seeing the same thing. I hadn’t actually noticed that was the case before. I was just looking at the External users on the app I was wanting to export users for. When looking at the list in Users and Roles > TestFlight Beta Testers > External, I see the same combined list you are. I tried to delete one of my internal users from the external list but they can’t be deleted for some reason. Seems like TestFlight is forcefully grouping internal testers as external ones.


On June 2, 2016 at 4:34:35 PM, mpirri (notifications@github.com) wrote:

@colinhumber Actually, I continued digging into this a bit more - it does appear that pilot is doing the right thing for my account, at least by some definition of "right". If, in iTunesConnect, I select Users and Roles, and then click on the TestFlight Beta Testers tab and then click the External tab, the list I see is exactly what is exported when I do pilot export. However, these external testers do not correspond to the external testers for any of my apps - they appear to be the combination of internal and external testers for all of my apps. This is odd behavior for sure (maybe an iTC bug?), but it does appear that pilot is respecting this behavior.

Does my observation what you are seeing?

**Comment by mpirri** [comment] 2016-06-03 15:04
Okay, yeah, that all makes sense. I also saw the weird behavior where you couldn't actually delete internal testers from that external list - another aspect that makes me suspect that this might be an iTC bug.

I'm going to close this issue with a rather-uncomfortable "works as intended", since it does actually export what iTC considers the "External Tester" list. We'll keep our eyes open for changes in behavior and reach out to Apple to see if they have any thoughts on this.

Thanks!

**Closed by mpirri** 2016-06-03 15:04 UTC
Labels: bug, pilot
