### ISSUE TITLE
match does not select team_id since 2.157.3

### ISSUE THREAD

**Issue by sneps85** [fastlane/fastlane#17154] opened 2020-09-04 10:34 UTC
I think this commit caused the issue:
https://github.com/fastlane/fastlane/commit/00863a5c305605c4eb14d70ef34a03807d1f049a

I am using match the same way, but since 2.157.3 it goes in error as i call it from jenkins and am not able to select the team by user input.

The error I get is:

_Verifying that the certificate and profile are still valid on the Dev Portal...
The current user is in 7 teams. Pass a team ID or call `select_team` to choose a team. Using the first one for now.
Multiple teams found on the Developer Portal, Your Terminal is running in non-interactive mode! Cannot continue from here.
Please check that you set FASTLANE_TEAM_ID or FASTLANE_TEAM_NAME to the right value.
Available Teams:
...

**Multiple Teams found; unable to choose, terminal not interactive!**_

Please fix this asap.
Thank you

**Comment by TewWe** [comment] 2020-09-04 13:19
We are also encountering this bug. Pls. note that you can work it around, if you set the `FASTLANE_TEAM_ID`env variable.

**Comment by TewWe** [comment] 2020-09-04 13:19
Also, I think this is a duplicat of #17153

**Comment by joshdholtz** [comment] 2020-09-04 13:31
Looking into! Duplicate of #17153. Sorry, fam 😔

**Closed by joshdholtz** 2020-09-04 13:31 UTC
