### ISSUE TITLE
Match can't find git_url

### ISSUE THREAD

**Issue by Preau** [fastlane/fastlane#6499] opened 2016-10-11 07:09 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Suddenly Match can't find our defined git_url from the Matchfile, this used to work before. Has anything changed?

##### Complete output when running fastlane, including the stack trace and command used

```
+-----------------------+----------------+
|        Summary for match 0.8.1         |
+-----------------------+----------------+
| git_branch            | master         |
| type                  | development    |
| keychain_name         | login.keychain |
| readonly              | false          |
| verbose               | false          |
| force                 | false          |
| shallow_clone         | false          |
| force_for_new_devices | false          |
| skip_docs             | false          |
+-----------------------+----------------+

WARN [2016-10-11 09:02:49.00]: To not be asked about this value, you can specify it using 'git_url'
URL to the git repo containing all the certificates:
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
opt_out_usage

update_fastlane

fastlane_version "1.104.0"

default_platform :ios

platform :ios do

  lane :update_apns do
    fix_user_schemes(path: "filename.xcodeproj") #create schemes
    match
    sigh(app_identifier: "our.app.identifier")
    pem(generate_p12: true, p12_password: 'password')
   end

end
```

Matchfile:
```ruby
git_url "git@ourrepo.git"

type "appstore" # The default type, can be: appstore, adhoc or development

app_identifier "our.app.identifier"
```

### Environment

fastlane version (run `fastlane -v`): 1.105.1

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? No

**Comment by Preau** [comment] 2016-10-11 09:40
While trying out more it seems adding my variables to the match call itself helps, but I have to do it for each variable, then on the next step sigh, it also can't find my username.

It seems like Fastfile isn't able to read Matchfile or Appfile data somehow.

**Comment by TKBurner** [comment] 2016-10-11 20:56
Hi @Preau What happens if you set the git_url using the https address? Thanks!

**Comment by KrauseFx** [comment] 2016-10-12 00:00
Please share a screenshot of your directory tree, and make sure the Matchfile is inside the _fastlane_ folder

**Comment by humblehacker** [comment] 2016-10-12 23:23
I'm having the same issue.  This is my fastlane directory:
```fastlane
├── Appfile
├── Deliverfile
├── Fastfile
├── Gymfile
├── Matchfile
├── README.md
├── Scanfile
├── actions -> ../.fastlane/actions
├── fixtures -> ../.fastlane/fixtures
├── helper -> ../.fastlane/helper
├── metadata
│   ├── copyright.txt
│   ├── en-US
│   │   ├── description.txt
│   │   ├── keywords.txt
│   │   ├── marketing_url.txt
│   │   ├── name.txt
│   │   ├── privacy_url.txt
│   │   ├── release_notes.txt
│   │   └── support_url.txt
│   ├── primary_category.txt
│   ├── primary_first_sub_category.txt
│   ├── primary_second_sub_category.txt
│   ├── secondary_category.txt
│   ├── secondary_first_sub_category.txt
│   └── secondary_second_sub_category.txt
├── report.xml
├── screenshots
│   ├── README.txt
│   └── en-US
│       ├── 1_iphone35_1.5.0-Splash_640x960_20130113.png
│       ├── 1_iphone4_1.5.0-Splash_640x1136_20130114.png
│       ├── 1_iphone6Plus_1.5.0-Splash_1242x2208_20130114.png
│       ├── 1_iphone6_1.5.0-Splash_750x1334_20130114.png
│       ├── 1_watch_1.img_0236.jpg
│       ├── 2_iphone35_2.3.5-inch\ (iPhone\ 4)\ -\ Screenshot\ 1.jpg
│       ├── 2_iphone4_2.4-inch\ (iPhone\ 5)\ -\ Screenshot\ 1.jpg
│       ├── 2_iphone6Plus_2.5.5-inch\ (iPhone\ 6+)\ -\ Screenshot\ 1.jpg
│       ├── 2_iphone6_2.4.7-inch\ (iPhone\ 6)\ -\ Screenshot\ 1.jpg
│       ├── 2_watch_2.img_0235__1_.jpg
│       ├── 3_iphone35_3.3.5-inch\ (iPhone\ 4)\ -\ Screenshot\ 2.jpg
│       ├── 3_iphone4_3.4-inch\ (iPhone\ 5)\ -\ Screenshot\ 2.jpg
│       ├── 3_iphone6Plus_3.5.5-inch\ (iPhone\ 6+)\ -\ Screenshot\ 2.jpg
│       └── 3_iphone6_3.4.7-inch\ (iPhone\ 6)\ -\ Screenshot\ 2.jpg
├── spec -> ../.fastlane/spec
└── test_output
    ├── report.html
    └── report.junit

9 directories, 39 files
```

**Comment by humblehacker** [comment] 2016-10-12 23:34
Odd, after manually adding in all the parameters from Matchfile, it's now prompting for `username`, which it never asked for before.  The only place in my fastlane configuration that I have a `username` defined is Deliverfile.

**Comment by KrauseFx** [comment] 2016-10-13 00:17
Can you pass the value from your Fastfile?

**Comment by humblehacker** [comment] 2016-10-13 03:31
I keep adding options into my Fastfile for match, but it just leads to more.  Now it gets to the scan stage, and is prompting me with:
> Couldn't automatically detect the project file, please provide a path:

**Comment by Preau** [comment] 2016-10-13 06:52
Yes I'm having the exact same problem as @humblehacker.
I can keep adding parameters to the Fastfile but it should be able to read them from the corresponding files.

```
➜  fastlane git:(master) ✗ tree
.
├── Appfile
├── Deliverfile
├── Fastfile
├── Gymfile
├── Matchfile
├── README.md
├── Snapfile
├── actions
│   ├── fix_user_schemes.rb
│   └── upload_certificate.rb
├── ratings.json
└── report.xml
```

Just for completeness here is my fastlane directory tree.

**Comment by humblehacker** [comment] 2016-10-13 20:17
@KrauseFx As a workaround, assuming the problem is due to a recent release, do you have any suggestions of version(s) to downgrade to?

**Comment by humblehacker** [comment] 2016-10-13 21:25
I've tracked this down to commit a28fde0d9e00a0d7c2a006a74aee37ed8b033921.  In my environment, when match is run by fastlane, the current directory (as checked by `Dir.pwd`) is one level up from where it should be, which is why none of the configuration files nor the project are found.  The offending line is fastlane/runner.rb:180.  

I changed to `.` from `..` and I was able to get through most of Match ok (Matchfile successfully read), but other actions were failing in the opposite direction (looking for files in the fastlane directory).

**Comment by humblehacker** [comment] 2016-10-13 22:20
Workaround:  Set `FORK_XCODE_WRITING` to `true` before running fastlane.  Like this:

```> FORK_XCODE_WRITING=true fastlane <yourlane>```

See https://github.com/CocoaPods/Xcodeproj/issues/426 for more details.

**Comment by KrauseFx** [comment] 2016-10-14 00:14
Can you share your `fix_user_schemes` code? I assume you change the directory there, but never go back?

**Comment by Preau** [comment] 2016-10-14 08:01
I seem to have the exact same issue as @humblehacker, also using `Xcodeproj::Project`.

Prepending my command with `FORK_XCODE_WRITING=true` seems to work for me as well.

Here is my fix_user_schemes.rb

```ruby
module Fastlane
  module Actions

    class FixUserSchemesAction < Action
      def self.run(params)
        # fastlane will take care of reading in the parameter and fetching the environment variable:
        require 'xcodeproj'
 
        UI.message "Path: " + params[:path]
        xcproj = Xcodeproj::Project.open(params[:path])
 
        # Fix schemes not being defined
        xcproj.recreate_user_schemes
 
        xcproj.save
        UI.message "User Schemes recreated."
      end



      #####################################################
      # @!group Documentation
      #####################################################

      def self.description
        "Opens the XCode Project to generate the User Schemes"
      end

      def self.available_options
        # Define all options your action supports. 
        
        # Below a few examples
        [
          FastlaneCore::ConfigItem.new(key: :path,
                                       env_name: "FL_FIX_USER_SCHEMES_PATH", # The name of the environment variable
                                       description: "XCode Project path for FixUserSchemesAction", # a short description of this parameter
                                       is_string: true, # true: verifies the input is a string, false: every kind of value
                                       verify_block: Proc.new do |value|
                                          raise "No XCode Project path for FixUserSchemesAction given, pass using `path: 'project.xcodeproj'`".red unless (value and not value.empty?)
                                       end)
        ]
      end

      def self.output
        # Define the shared values you are going to provide
        # Example
        #[
        #  ['FIX_USER_SCHEMES_CUSTOM_VALUE', 'A description of what this value contains']
        #]
      end

      def self.is_supported?(platform)
        # you can do things like
        # 
        #  true
        # 
        #  platform == :ios
        # 
        #  [:ios, :mac].include?platform
        # 

        platform == :ios
      end
    end
  end
end
```

**Comment by TKBurner** [comment] 2016-10-17 21:17
@Preau @humblehacker Do you think this issue will be resolved if that cocoapods issue is cleared up? Thanks!

**Comment by humblehacker** [comment] 2016-10-17 21:22
@TKBurner That's my expectation, but I have no evidence to back it up.

**Comment by TKBurner** [comment] 2016-10-18 21:38
@humblehacker Looks like it'll be fixed on their next release, can you update this thread at that point? Thanks!

**Comment by KrauseFx** [comment] 2016-10-19 02:06
Could you update to the latest _fastlane_ release and let us know if that solves the problem? 👍

**Comment by Preau** [comment] 2016-10-19 07:05
Hi @KrauseFx 

Everything seems to work again for me! Thanks!

**Comment by asfalcone** [comment] 2016-10-19 13:23
Thanks for the update @Preau 👍

**Closed by asfalcone** 2016-10-19 13:23 UTC
Labels: match, question
