### ISSUE TITLE
`fastlane run update_fastlane` is failing starting from fastlane version 1.67.0

### ISSUE THREAD

**Issue by anton-matosov** [fastlane/fastlane#3892] opened 2016-03-22 22:20 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
While updating from fastlane 1.66.0 it failed with same error as mentioned below.
I have reinstalled it from scratch (deleted ~/.rbenv) but still get the same problem when I run `fastlane run update_fastlane` 

##### Complete output when running fastlane, including the stack trace and command used

```
> fastlane run update_fastlane

[15:12:26]: -----------------------------
[15:12:26]: --- Step: update_fastlane ---
[15:12:26]: -----------------------------
[15:12:26]: Looking for updates for cert, credentials_manager, deliver, fastlane, fastlane_core, frameit, gym, match, pem, pilot, produce, scan, screengrab, sigh, snapshot, spaceship, supply...
[15:12:27]: The update_fastlane action requires rubygems version 2.1.0 or greater.
[15:12:27]: Please update your version of ruby gems before proceeding.
[15:12:27]: $ gem install rubygems-update
[15:12:27]: $ update_rubygems
[15:12:27]: $ gem update --system
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
nothing
```

### Environment

fastlane version (fastlane -v): fastlane 1.67.0
Do you use bundler, rbenv or rvm? rbenv

**Comment by TKBurner** [comment] 2016-03-23 15:02
@anton-matosov I was able to reproduce this locally. I'm going to loop in the team and see what we can do to help :+1: Thanks for reporting this!

**Comment by asfalcone** [comment] 2016-03-23 16:51
Fixed in fastlane [1.68.0](https://github.com/fastlane/fastlane/releases/tag/1.68.0) :tada:

**Closed by asfalcone** 2016-03-23 16:51 UTC
Labels: bug, fastlane

**Comment by mortenholmgaard** [comment] 2016-04-22 12:34
I have a very similar issue for version 1.70 of fastlane:
[14:22:35]: -----------------------------
[14:22:35]: --- Step: update_fastlane ---
[14:22:35]: -----------------------------
[14:22:35]: Looking for updates for cert, credentials_manager, deliver, fastlane, fastlane_core, frameit, gym, match, pem, pilot, produce, scan, screengrab, sigh, snapshot, spaceship, supply...
ERROR:  Loading command: update (Gem::LoadError)
	can't activate addressable-2.4.0, already activated addressable-2.3.8
ERROR:  Loading command: cleanup (Gem::LoadError)
	can't activate addressable-2.4.0, already activated addressable-2.3.8
[14:22:36]: The update_fastlane action requires rubygems version 2.1.0 or greater.
[14:22:36]: Please update your version of ruby gems before proceeding.
[14:22:36]: $ gem install rubygems-update
[14:22:36]: $ update_rubygems
[14:22:36]: $ gem update --system

I have tried all 3 options:
Mortens-Mac-mini:MyEvent mortenholmgaard$ gem install rubygems-update
Successfully installed rubygems-update-2.6.3
Parsing documentation for rubygems-update-2.6.3
Done installing documentation for rubygems-update after 0 seconds
1 gem installed
Mortens-Mac-mini:MyEvent mortenholmgaard$ update_rubygems
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied - /Library/Ruby/Site/2.0.0/gauntlet_rubygems.rb
Mortens-Mac-mini:MyEvent mortenholmgaard$ gem update --system
Updating rubygems-update
Successfully installed rubygems-update-2.6.3
Parsing documentation for rubygems-update-2.6.3
Installing darkfish documentation for rubygems-update-2.6.3
Done installing documentation for rubygems-update after 5 seconds
Parsing documentation for rubygems-update-2.6.3
Done installing documentation for rubygems-update after 0 seconds
Installing RubyGems 2.6.3
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied - /Library/Ruby/Site/2.0.0/gauntlet_rubygems.rb
Mortens-Mac-mini:MyEvent mortenholmgaard$ 

None of them makes it possible for me to update fastlane

But I have no idea if i am using bundler, rbenv or ram?
I have a .bash_profile file with this contents to make update_fastlane work:
export GEM_HOME=~/.gems
export PATH=$PATH:~/.gems/bin

It seems like I need some variant of one of the update ruby gems commands - but as you might have guessed I am not that familiar with Ruby and the gems setup.

**Comment by TKBurner** [comment] 2016-04-22 18:11
Hi @mortenholmgaard! Great to hear from you. What happens if you add sudo to the beginning of your gem update commands?

Thanks!

**Comment by mortenholmgaard** [comment] 2016-04-22 20:10
Same results:

> Mortens-Mac-mini:MyEvent mortenholmgaard$ sudo gem install rubygems-update
> Password:
> Fetching: rubygems-update-2.6.3.gem (100%)
> ERROR:  While executing gem ... (Errno::EPERM)
>     Operation not permitted - /usr/bin/update_rubygems
> Mortens-Mac-mini:MyEvent mortenholmgaard$ sudo update_rubygems
> RubyGems 2.5.0 installed
> Parsing documentation for rubygems-2.5.0
> Installing ri documentation for rubygems-2.5.0
> 
> 
> 
> ------------------------------------------------------------------------------
> 
> RubyGems installed the following executables:
> 	/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/gem
> 
> Ruby Interactive (ri) documentation was installed. ri is kind of like man 
> pages for ruby libraries. You may access it like this:
>   ri Classname
>   ri Classname.class_method
>   ri Classname#instance_method
> If you do not wish to install this documentation in the future, use the
> --no-document flag, or set it as the default in your ~/.gemrc file. See
> 'gem help env' for details.
> 
> Mortens-Mac-mini:MyEvent mortenholmgaard$ sudo gem update --system
> Updating rubygems-update
> ERROR:  While executing gem ... (Errno::EPERM)
>     Operation not permitted - /usr/bin/update_rubygems

Update command:
> [22:09:05]: Looking for updates for cert, credentials_manager, deliver, fastlane, fastlane_core, frameit, gym, match, pem, pilot, produce, scan, screengrab, sigh, snapshot, spaceship, supply...
> ERROR:  Loading command: update (Gem::LoadError)
> 	can't activate addressable-2.4.0, already activated addressable-2.3.8
> ERROR:  Loading command: cleanup (Gem::LoadError)
> 	can't activate addressable-2.4.0, already activated addressable-2.3.8
> [22:09:06]: The update_fastlane action requires rubygems version 2.1.0 or greater.
> [22:09:06]: Please update your version of ruby gems before proceeding.
> [22:09:06]: $ gem install rubygems-update
> [22:09:06]: $ update_rubygems
> [22:09:06]: $ gem update --system

**Comment by TKBurner** [comment] 2016-04-26 14:01
Hi @mortenholmgaard! Thanks for following up. Can you ruby -v for me? Also, have you tried not using the system ruby? Thanks!

**Comment by mortenholmgaard** [comment] 2016-04-27 19:13
It results in:

> ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]

Regarding not using the system ruby, I havn't because I don't even know the difference (and if I am using system ruby). I have only done what it takes to get fastlane running, and my lanes is the only ruby I have written. My only priority with ruby is to get fastlane working.

**Comment by TKBurner** [comment] 2016-04-28 17:42
Hi @mortenholmgaard Thanks for following up. Can you run sudo gem update --system ? Let me know the full output of that command. Thanks!

**Comment by mortenholmgaard** [comment] 2016-04-28 21:07
This is the output of _sudo gem update --system_:

> Mortens-Mac-mini:MyEvent mortenholmgaard$ sudo gem update --system
> Password:
> Updating rubygems-update
> Fetching: rubygems-update-2.6.4.gem (100%)
> ERROR:  While executing gem ... (Errno::EPERM)
>     Operation not permitted - /usr/bin/update_rubygems
> Mortens-Mac-mini:MyEvent mortenholmgaard$

**Comment by TKBurner** [comment] 2016-04-29 15:08
Hi @mortenholmgaard Thanks for following up. This isn't a Fastlane issue at this point. Are you on El Capitan? The other reports I found on StackOver flow of similar issues with other gems suggests that this folder is no longer writable in El Capitan. You'll need to install Ruby via Homebrew or RVM.

Thanks!

**Comment by mortenholmgaard** [comment] 2016-05-01 11:49
Okay I got it working now - thanks!

**Comment by TKBurner** [comment] 2016-05-03 16:21
@mortenholmgaard Awesome! Glad to hear that 👍 Hope you have a great day!
