### ISSUE TITLE
GITLAB CI: Could not retrieve response as fastlane runs in non-interactive mode

### ISSUE THREAD

**Issue by FrancisLeigh** [fastlane/fastlane#17376] opened 2020-10-05 10:25 UTC
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues) ✅ ✅ ✅ ✅ ✅ ✅ 

### Issue Description
`fastlane install_plugins` script within the gitlab pipeline fails every time due to fastlane asking "Should fastlane modify the Gemfile at path 'tmp/Gemfile' for you?" but fastlane is running in non-interactive mode.

The main point of interest is here where the script is expecting an interaction but cannot get one for obvious reasons. 
```bash
...
Installing plugin dependencies...
WARN [2020-10-05 03:15:52.70]: It looks like fastlane plugins are not yet set up for this project.
WARN [2020-10-05 03:15:52.70]: fastlane will modify your existing Gemfile at path '/tmp/Gemfile'
WARN [2020-10-05 03:15:52.70]: This change is necessary for fastlane plugins to work
WARN [2020-10-05 03:15:52.70]: Should fastlane modify the Gemfile at path '/tmp/Gemfile' for you?
...
```

##### Command executed
`fastlane install_plugins --verbose`

output
```bash
$ fastlane install_plugins --verbose
DEBUG [2020-10-05 03:15:52.64]: Checking if there are any plugins that should be loaded...
ERROR [2020-10-05 03:15:52.70]: It seems like you wanted to load some plugins, however they couldn't be loaded
ERROR [2020-10-05 03:15:52.70]: Please follow the troubleshooting guide: https://docs.fastlane.tools/plugins/plugins-troubleshooting/
Successfully loaded Appfile at path '/builds/companyname/frontend/app-name/fastlane/Appfile'
- json_key_file: '../google_play_api_key.json'
- package_name: 'com.companyname.appname'
- app_identifier: 'com.companyname.companynameappname'
- apple_id: 'francis@companyname.com'
-------
Installing plugin dependencies...
WARN [2020-10-05 03:15:52.70]: It looks like fastlane plugins are not yet set up for this project.
WARN [2020-10-05 03:15:52.70]: fastlane will modify your existing Gemfile at path '/tmp/Gemfile'
WARN [2020-10-05 03:15:52.70]: This change is necessary for fastlane plugins to work
WARN [2020-10-05 03:15:52.70]: Should fastlane modify the Gemfile at path '/tmp/Gemfile' for you?
Looking for related GitHub issues on fastlane/fastlane...
Search query: Could not retrieve response as fastlane runs in non-interactive mode
URL: https://api.github.com/search/issues?q=Could%20not%20retrieve%20response%20as%20fastlane%20runs%20in%20non-interactive%20mode+repo:fastlane/fastlane
➡️  Two-Step MFA keeps asking for 6-digit code even when entering latest from SMS
    https://github.com/fastlane/fastlane/issues/16647 [closed] 8 💬
    5 weeks ago
➡️  Fastlane Pilot fails after successfully uploaded and submission due to missing password
    https://github.com/fastlane/fastlane/issues/17069 [closed] 8 💬
    3 weeks ago
➡️  Could not retrieve response as fastlane runs in non-interactive mode
    https://github.com/fastlane/fastlane/issues/15548 [closed] 8 💬
    27 Feb 2020
and 48 more at: https://github.com/fastlane/fastlane/search?q=Could%20not%20retrieve%20response%20as%20fastlane%20runs%20in%20non-interactive%20mode&type=Issues&utf8=✓
/var/lib/gems/2.5.0/gems/fastlane-2.162.0/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!': [!] Could not retrieve response as fastlane runs in non-interactive mode (FastlaneCore::Interface::FastlaneCrash)
	from /var/lib/gems/2.5.0/gems/fastlane-2.162.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:156:in `verify_interactive!'
	from /var/lib/gems/2.5.0/gems/fastlane-2.162.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:134:in `confirm'
	from /var/lib/gems/2.5.0/gems/fastlane-2.162.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /var/lib/gems/2.5.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/plugins/plugin_manager.rb:240:in `setup'
	from /var/lib/gems/2.5.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/plugins/plugin_manager.rb:269:in `ensure_plugins_attached!'
	from /var/lib/gems/2.5.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/plugins/plugin_manager.rb:177:in `install_dependencies!'
	from /var/lib/gems/2.5.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/commands_generator.rb:312:in `block (2 levels) in run'
	from /var/lib/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /var/lib/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /var/lib/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /var/lib/gems/2.5.0/gems/fastlane-2.162.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /var/lib/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /var/lib/gems/2.5.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	from /var/lib/gems/2.5.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /var/lib/gems/2.5.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	from /var/lib/gems/2.5.0/gems/fastlane-2.162.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
Cleaning up file based variables
00:01
ERROR: Job failed: exit code 1
```

```yaml
.android:
    image: mingc/android-build-box:latest
    artifacts:
        paths:
            - fastlane/logs
    before_script:
        - export GRADLE_USER_HOME=$(pwd)/.gradle
        - export CI=1
        - GITLAB_CI=1
        - bundle install
        - fastlane env
        - fastlane install_plugins --verbose
    cache:
        paths:
            - .gradle/wrapper
            - .gradle/caches
```

### Environment

<details>
  <pre> | Key                         | Value                                                       |
| --------------------------- | ----------------------------------------------------------- |
| OS                          | debian_based buster/sid                                     |
| Ruby                        | 2.5.1                                                       |
| Bundler?                    | true                                                        |
| Git                         | git version 2.17.1                                          |
| Installation Source         | /usr/local/bin/fastlane                                     |
| Host                        | Ubuntu 18.04.5 LTS debian_based buster/sid (4.19.78-coreos) |
| Ruby Lib Dir                | /usr/lib                                                    |
| OpenSSL Version             | OpenSSL 1.1.1  11 Sep 2018                                  |
| Is contained                | false                                                       |
| Is homebrew                 | false                                                       |
| Is installed via Fabric.app | false                                                       |
### System Locale
| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ | </pre>
</details>

**Comment by FrancisLeigh** [comment] 2020-10-05 10:30
@fastlane-bot i did

**Comment by rogerluan** [comment] 2020-10-05 18:56
Hey @FrancisLeigh 👋 
I know it sounds obvious, but have you tried going through the [action troubleshooting docs](https://docs.fastlane.tools/plugins/plugins-troubleshooting/)? 🙏

**Comment by FrancisLeigh** [comment] 2020-10-06 05:47
@rogerluan yeah I have read through the troubleshoot guide but to no avail. I'll double check my fastlane version on the CI when I get into work. I don't explicitly set a DEFAULT_GEMFILE_PATH either

**Comment by rogerluan** [comment] 2020-10-06 13:01
I'm digging into this now.

You're seeing the confirmation screen because of the error `It looks like fastlane plugins are not yet set up for this project.`. This verification is done by checking whether your `Gemfile` includes the content necessary to run the plugin.

That part is explained in the troubleshooting docs here: https://docs.fastlane.tools/plugins/plugins-troubleshooting/#gemfile-and-pluginfile

Your Gemfile should look something like this:

```ruby
gem "fastlane"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
```

Your Pluginfile should look something like this

```ruby
# Autogenerated by fastlane

gem 'fastlane-plugin-ruby'
```

You'd get that result, if you ran `fastlane add_plugin [name]` as specified in the [Add a plugin to your project](https://docs.fastlane.tools/plugins/using-plugins/#add-a-plugin-to-your-project). 

Did you try those and it's still not working?

Can you post the full content of your Gemfile and Pluginfile so I can test on my end?

**Comment by rogerluan** [comment] 2020-10-06 13:03
Also, equally important, do you know where your Pluginfile is located at? The code above will look for the Pluginfile at the same path as your Gemfile, and your Gemfile is in a weird tmp location (not sure why). Maybe it is looking up at the wrong Gemfile. Gemfiles are usually in `./Gemfile` (i.e. the same directory as your project), and not in `/tmp/Gemfile` (which looks like a system path, which's also likely outside of your project directory) 🤔 Maybe posting your project directory path will help us debug this issue 😊

**Comment by FrancisLeigh** [comment] 2020-10-06 14:05
@rogerluan Yes i've read through the troubleshooting and haven't had any luck.

See below the relevant files.

*fastlane directory*
`[project root]/fastlane`
![Screenshot 2020-10-06 at 15 02 02](https://user-images.githubusercontent.com/10357801/95211825-f0462980-07e4-11eb-8964-bfc5663b15e8.png)

*[project root]/Gemfile*
```ruby
source "https://rubygems.org"

gem "fastlane"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
```

*[project root]/fastlane/Pluginfile*
```ruby
# Autogenerated by fastlane
#
# Ensure this file is checked in to source control!

gem 'fastlane-plugin-increment_version_code'
gem 'fastlane-plugin-appicon'
gem 'fastlane-plugin-android_versioning'
gem 'fastlane-plugin-firebase_app_distribution', '0.2.2.pre.1'
gem 'fastlane-plugin-badge'
gem 'fastlane-plugin-versioning'
gem 'fastlane-plugin-versioning_android'
```

Let me know if you need anything else, really appreciate you helping.

**Comment by rogerluan** [comment] 2020-10-06 14:23
Hum I just replicated your folders locally and it seems everything's correct:

```
$ ruby Gemfile
./fastlane/Pluginfile
File exists
```

I suspect that this function https://github.com/rubygems/bundler/blob/master/lib/bundler/shared_helpers.rb#L19 is fetching the wrong Gemfile path for you. Instead of looking at `[project root]/Gemfile`, it's reading `/tmp/Gemfile` (which I don't think it's the same path as your project root).

Can you try setting the env var `BUNDLE_GEMFILE` to be `[project root]/Gemfile` instead?

(I reviewed the bundler gem file above, but couldn't figure out why it's picking up /tmp/Gemfile instead of your local Gemfile 😢 - but also, any idea why is there a Gemfile at `/tmp/Gemfile`?)

**Comment by FrancisLeigh** [comment] 2020-10-06 15:12
@rogerluan it looks like the Gemfile @ `/tmp/Gemfile` is used [here](https://github.com/mingchen/docker-android-build-box/blob/master/Dockerfile#L180) by the `mingc/android-build-box:latest` docker image.

My `.android` yaml now looks like. 
```yaml
.android:
    image: mingc/android-build-box:latest
    artifacts:
        paths:
            - fastlane/logs
    before_script:
        - gem update --system
        - export GRADLE_USER_HOME=$(pwd)/.gradle
        - export BUNDLE_GEMFILE=$(pwd)/Gemfile
        - bundle install
        - fastlane install_plugins --verbose
    cache:
        paths:
            - .gradle/wrapper
            - .gradle/caches
```

Going to wait and see how that builds...

**Comment by rogerluan** [comment] 2020-10-06 15:22
> looks like the Gemfile @ `/tmp/Gemfile` is used [here](https://github.com/mingchen/docker-android-build-box/blob/master/Dockerfile#L180) by the `mingc/android-build-box:latest` docker image.

Really really nice catch! That must be it! 
Hopefully your change won't break existing functionality of that docker image 😅

**Comment by rogerluan** [comment] 2020-10-15 16:29
Did it work, @FrancisLeigh ? 😃

**Comment by FrancisLeigh** [comment] 2020-10-15 18:41
@rogerluan no luck I'm afraid, I ran into another error. I can take a look tomorrow at the last error message

**Comment by rogerluan** [comment] 2020-11-02 20:11
@FrancisLeigh any update? 🙏

**Comment by erratir** [comment] 2020-12-04 13:00
I have similar issue. I use `mingc/android-build-box:latest` docker image and Jenkins

**Comment by mirokolodii** [comment] 2020-12-18 09:04
> @rogerluan it looks like the Gemfile @ `/tmp/Gemfile` is used [here](https://github.com/mingchen/docker-android-build-box/blob/master/Dockerfile#L180) by the `mingc/android-build-box:latest` docker image.
> 
> My `.android` yaml now looks like.
> 
> ```yaml
> .android:
>     image: mingc/android-build-box:latest
>     artifacts:
>         paths:
>             - fastlane/logs
>     before_script:
>         - gem update --system
>         - export GRADLE_USER_HOME=$(pwd)/.gradle
>         - export BUNDLE_GEMFILE=$(pwd)/Gemfile
>         - bundle install
>         - fastlane install_plugins --verbose
>     cache:
>         paths:
>             - .gradle/wrapper
>             - .gradle/caches
> ```
> 
> Going to wait and see how that builds...

This has worked for me, with additional setting. Firebase authentication is required as well, described [here](https://firebase.google.com/docs/cli#cli-ci-systems). Generate a new Firebase token and set it as environment variable FIREBASE_TOKEN in Gitlab settings.

**Comment by rogerluan** [comment] 2020-12-19 11:11
Thanks for the feedback and additional info @mirokolodii !

**Comment by rogerluan** [comment] 2020-12-19 11:16
This issue seems to be somewhat resolved, the root cause being that there are 3rd party dependencies that are writing to an environment variable that in my opinion shouldn't be written to by programs, only read by them, and written to by human-driven configuration settings.

There is a workaround proposed for that issue, so I'm closing this issue. If anyone feels strongly about reopening it, let me know 👍

**Closed by rogerluan** 2020-12-19 11:16 UTC
Labels: tool: plugin
