### ISSUE TITLE
Screengrab places screenshots into wrong locale directory

### ISSUE THREAD

**Issue by vanniktech** [fastlane/fastlane#14584] opened 2019-04-13 18:51 UTC
I got this Screengrab file:

```
app_package_name('com.vanniktech.meditationtimer')
use_tests_in_packages(['com.vanniktech.meditationtimer.screenshots'])
test_instrumentation_runner('androidx.test.runner.AndroidJUnitRunner')

app_apk_path('build/outputs/apk/debug/app-1.1.8-debug.apk')
tests_apk_path('build/outputs/apk/androidTest/debug/app-1.1.8-debug-androidTest.apk')

locales(['de-DE', 'tr-TR', 'ru-RU', 'fi-FI', 'es-ES', 'pt-BR', 'pt-PT', 'it-IT', 'fr-FR', 'en-US'])

launch_arguments(['isUsingFastlane true'])

device_type('phone') # ./emulator @Nexus_6P_API_27

exit_on_test_failure(false)
```

when running `fastlane screengrab` the screenshots are put into the first part specific directory though. So instead of having my screenshots inside `./fastlane/metadata/android/it-IT/images/phoneScreenshots` I get them inside `./fastlane/metadata/android/it/images/phoneScreenshots`. This happens for all locales. `de-DE` -> `de`, `en-US` -> `en` etc.

This hasn't always been the case. Was this change intended?

**Comment by janpio** [comment] 2019-04-14 18:29
I am not aware of any recent changes to screengrab that could cause this.

Did this configuration work before as intended? If so, can you pinpoint with which version it started to break?

**Comment by vanniktech** [comment] 2019-04-14 21:45
Yes, it did work before. I wish I could. I believe it was still working around the 2.102 area and it stopped somewhere around 2.110

Is there any easy way I can change between fastlane versions? If so I could try and error and see which version has changed it.

**Comment by janpio** [comment] 2019-04-15 13:36
If you are using a `Gemfile` and executing fastlane via `bundle exec fastlane ...` then you can use `bundle add fastlane --version ...` ([bundle add docs](https://bundler.io/man/bundle-add.1.html)) I guess.

If you are not, then you can probably `gem install fastlane --version ...`. (But you really should use a `Gemfile`)

**Comment by vanniktech** [comment] 2019-04-15 14:17
So I've tried. With 2.112 and earlier:

```ruby
source "https://rubygems.org"

gem "fastlane", "= 2.112.0"
```

when running `bundle install`, I'm running into:

```
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    fastlane (= 2.112.0) was resolved to 2.112.0, which depends on
      bundler (>= 1.12.0, < 2.0.0)

  Current Bundler version:
    bundler (2.0.1)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?

Could not find gem 'bundler (>= 1.12.0, < 2.0.0)', which is required by gem 'fastlane (= 2.112.0)', in any of the sources.
```

2.113.0 does work. However, there the problem is already present so I need an older version. Can you help me out how it's easiest to resolve this particular dependency issue?

**Comment by janpio** [comment] 2019-04-15 14:33
`gem install bundler --version 1.17.3` might help in this case. (Latest 1.x version from https://github.com/bundler/bundler/releases, bundler install command from https://bundler.io/ and version specific install command from https://guides.rubygems.org/command-reference/#gem-install)

**Comment by vanniktech** [comment] 2019-04-15 14:57
Hmm, things are very weird. For some reason, I can't reproduce. Even on super old versions such as 2.60.0. I think that something on my machine has changed which led to a different directory name generation.

```
+-----------------------------+----------------------------------------------------------------------+
|                              Detected Values from './Screengrabfile'                               |
+-----------------------------+----------------------------------------------------------------------+
| app_package_name            | com.vanniktech.gameutilities                                         |
| use_tests_in_packages       | ["com.vanniktech.gameutilities.screenshots"]                         |
| test_instrumentation_runner | androidx.test.runner.AndroidJUnitRunner                              |
| app_apk_path                | build/outputs/apk/debug/app-1.0.11-debug.apk                         |
| tests_apk_path              | build/outputs/apk/androidTest/debug/app-1.0.11-debug-androidTest.apk |
| launch_arguments            | ["isUsingFastlane true"]                                             |
| device_type                 | phone                                                                |
| exit_on_test_failure        | false                                                                |
+-----------------------------+----------------------------------------------------------------------+


+-----------------------------+----------------------------------------------------------------------+
|                                   Summary for screengrab 2.60.0                                    |
+-----------------------------+----------------------------------------------------------------------+
| locales                     | ["de-DE"]                                                            |
| app_package_name            | com.vanniktech.gameutilities                                         |
| use_tests_in_packages       | ["com.vanniktech.gameutilities.screenshots"]                         |
| test_instrumentation_runner | androidx.test.runner.AndroidJUnitRunner                              |
| app_apk_path                | build/outputs/apk/debug/app-1.0.11-debug.apk                         |
| tests_apk_path              | build/outputs/apk/androidTest/debug/app-1.0.11-debug-androidTest.apk |
| launch_arguments            | ["isUsingFastlane true"]                                             |
| device_type                 | phone                                                                |
| exit_on_test_failure        | false                                                                |
| tests_package_name          | com.vanniktech.gameutilities.test                                    |
| android_home                | /home/niklas/android/sdk                                             |
| clear_previous_screenshots  | false                                                                |
| output_directory            | fastlane/metadata/android                                            |
| skip_open_summary           | true                                                                 |
| ending_locale               | en-US                                                                |
| reinstall_app               | false                                                                |
+-----------------------------+----------------------------------------------------------------------+

[16:51:25]: $ adb devices -l
[16:51:25]: ▸ List of devices attached
[16:51:25]: ▸ 710KPTM0518657         device usb:1-8.2 product:taimen model:Pixel_2_XL device:taimen transport_id:3
[16:51:25]: $ adb -s 710KPTM0518657 shell echo \$EXTERNAL_STORAGE
[16:51:25]: ▸ /sdcard
[16:51:25]: Cleaning screenshots on device
[16:51:25]: $ adb -s 710KPTM0518657 shell rm -rf /sdcard/com.vanniktech.gameutilities/screengrab
ls: /data/data/com.vanniktech.gameutilities/app_screengrab: Permission denied
[16:51:25]: Exit status: 1
[16:51:25]: Validating app APK
[16:51:25]: $ /home/niklas/android/sdk/build-tools/28.0.3/aapt dump permissions build/outputs/apk/debug/app-1.0.11-debug.apk
[16:51:25]: ▸ package: com.vanniktech.gameutilities
[16:51:25]: ▸ uses-permission: name='android.permission.DISABLE_KEYGUARD'
[16:51:25]: ▸ uses-permission: name='android.permission.WAKE_LOCK'
[16:51:25]: ▸ uses-permission: name='android.permission.WRITE_EXTERNAL_STORAGE'
[16:51:25]: ▸ uses-permission: name='android.permission.READ_EXTERNAL_STORAGE'
[16:51:25]: ▸ uses-permission: name='android.permission.CHANGE_CONFIGURATION'
[16:51:25]: ▸ uses-permission: name='com.android.vending.BILLING'
[16:51:25]: ▸ uses-permission: name='android.permission.INTERNET'
[16:51:25]: ▸ uses-permission: name='android.permission.ACCESS_NETWORK_STATE'
[16:51:25]: ▸ uses-permission: name='com.google.android.c2dm.permission.RECEIVE'
[16:51:25]: Installing app APK
[16:51:25]: $ adb -s 710KPTM0518657 install -r build/outputs/apk/debug/app-1.0.11-debug.apk
[16:51:25]: ▸ Performing Streamed Install
[16:51:28]: ▸ Success
[16:51:28]: Installing tests APK
[16:51:28]: $ adb -s 710KPTM0518657 install -r build/outputs/apk/androidTest/debug/app-1.0.11-debug-androidTest.apk
[16:51:28]: ▸ Performing Streamed Install
[16:51:32]: ▸ Success
[16:51:32]: Granting the permission necessary to change locales on the device
[16:51:32]: $ adb -s 710KPTM0518657 shell pm grant com.vanniktech.gameutilities android.permission.CHANGE_CONFIGURATION
[16:51:32]: $ adb -s 710KPTM0518657 shell getprop ro.build.version.sdk
[16:51:32]: ▸ 28
[16:51:32]: Granting the permissions necessary to access device external storage
[16:51:32]: $ adb -s 710KPTM0518657 shell pm grant com.vanniktech.gameutilities android.permission.WRITE_EXTERNAL_STORAGE
[16:51:32]: $ adb -s 710KPTM0518657 shell pm grant com.vanniktech.gameutilities android.permission.READ_EXTERNAL_STORAGE
[16:51:32]: Running tests for locale: de-DE
[16:51:32]: $ adb -s 710KPTM0518657 shell am instrument --no-window-animation -w \
-e testLocale de_DE \
-e endingLocale en_US \
-e package com.vanniktech.gameutilities.screenshots \
-e isUsingFastlane true \
com.vanniktech.gameutilities.test/androidx.test.runner.AndroidJUnitRunner
[16:51:38]: ▸ com.vanniktech.gameutilities.screenshots.SettingsScreenShotsTest:.
[16:51:38]: ▸ Time: 2.587
[16:51:38]: ▸ OK (1 test)
[16:51:38]: Pulling captured screenshots from the device
[16:51:38]: $ adb -s 710KPTM0518657 pull /sdcard/com.vanniktech.gameutilities/screengrab /tmp/d20190415-28594-7aj83i
ls: /data/data/com.vanniktech.gameutilities/app_screengrab: Permission denied
[16:51:38]: Exit status: 1
[16:51:38]: Screenshots copied to fastlane/metadata/android/en/images/phoneScreenshots
```

What's also weird is that the testLocale is set to German via `-e testLocale de_DE \`, however the last line says `fastlane/metadata/android/en/images/phoneScreenshots`. Are some parts of locale depending code handled on the phone? Like generating the folder name - if so it can be the case that #14594 does indeed fix this issue.

What's the easiest way to publish the screengrab android library to my local maven repository? Typically there are Gradle tasks such as `publishToMavenLocal` / `installArchives` available but none of them do work for me.

**Comment by janpio** [comment] 2019-04-15 15:53
I would jump in and try to find out how those folder names are generated then... (but don't have the time to do that for you). Searching the codebase for `Screenshots copied to` should be a good way to find where to start backtracking.

> What's the easiest way to publish the screengrab android library to my local maven repository? Typically there are Gradle tasks such as `publishToMavenLocal` / `installArchives` available but none of them do work for me.

I think this is where we are lost on the fastlane side as well, isn't it? So: I have no idea.

**Comment by vanniktech** [comment] 2019-04-16 13:05
> I think this is where we are lost on the fastlane side as well, isn't it? So: I have no idea.

You're using the novoda bintray plugin for publishing - which is a bit unusual. I've written in the PR how I managed to get everything working and also gave an update.

**Comment by vanniktech** [comment] 2019-05-16 19:31
Still an issue since my PR hasn't been merged yet.

**Comment by janpio** [comment] 2019-05-20 09:41
For reference: https://github.com/fastlane/fastlane/pull/14594

**Comment by ppamorim** [comment] 2019-06-14 16:46
I am getting the exact same problem. This screen grab function is totally broken. Is there any idea when it gonna be fixed?

**Comment by ppamorim** [comment] 2019-07-09 15:08
Any idea when this will be solved?

**Comment by ppamorim** [comment] 2019-07-09 16:20
Since my project is only translated to en-GB, I added this script to copy the files to the correct path after the completion of `screengrab`:

```
sh("cp -r fastlane/metadata/#{flavor}/en/images/phoneScreenshots/* fastlane/metadata/#{flavor}/en-GB/images/phoneScreenshots")
```

**Comment by taquitos** [comment] 2019-11-07 19:46
Referenced PR has been merged 🎉

**Comment by vanniktech** [comment] 2019-11-07 20:37
Can we leave this open until there's a new version of the library being released?

**Comment by rogerluan** [comment] 2021-01-08 01:57
Closing this stale PR as https://github.com/fastlane/fastlane/pull/15994 got merged and released a long time ago 😊

**Closed by rogerluan** 2021-01-08 01:57 UTC
Labels: status: has-pr, tool: screengrab
