### ISSUE TITLE
You must provide an answer for this question. You must provide an answer for this question

### ISSUE THREAD

**Issue by sfransen** [fastlane/fastlane#4720] opened 2016-05-18 19:59 UTC
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [ ]x I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I am getting this error when I upload to test flight using pilot.
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.1/lib/spaceship/tunes/tunes_client.rb:174:in `handle_itc_response': [31m[!] The request could not be completed because: (Spaceship::TunesClient::ITunesConnectError)
12:37:51 	You must provide an answer for this question. You must provide an answer for this question.[0m

 what question does it what answered?

##### Complete output when running fastlane, including the stack trace and command used

```

DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS="-t DAV" pilot upload --verbose  --app_identifier com.foo.foo --changelog 'hello' --apple_id ffffff --wait_processing_interval 240 --team_id ffffffff --ipa "ffo.ipa"

2:25:38 INFO [2016-05-18 12:25:38.55]: [32m------------------------------------------------------------------------------------------------------[0m
12:25:38 INFO [2016-05-18 12:25:38.55]: [32mSuccessfully uploaded package to iTunes Connect. It might take a few minutes until it's visible online.[0m
12:25:38 INFO [2016-05-18 12:25:38.55]: [32m------------------------------------------------------------------------------------------------------[0m
12:25:38 INFO [2016-05-18 12:25:38.55]: Successfully uploaded the new binary to iTunes Connect
12:25:38 INFO [2016-05-18 12:25:38.55]: Waiting for iTunes Connect to process the new build
12:29:42 INFO [2016-05-18 12:29:42.46]: Waiting for iTunes Connect to finish processing the new build (1.0.0 - 1077)
12:33:48 INFO [2016-05-18 12:33:48.09]: Waiting for iTunes Connect to finish processing the new build (1.0.0 - 1077)
12:37:48 INFO [2016-05-18 12:37:48.10]: [32mSuccessfully finished processing the build[0m
12:37:48 INFO [2016-05-18 12:37:48.10]: You can now tweet: 
12:37:48 WARN [2016-05-18 12:37:48.10]: [33miTunes Connect #iosprocessingtime 12 minutes[0m
12:37:48 INFO [2016-05-18 12:37:48.10]: Distributing new build to testers
12:37:51 /Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.1/lib/spaceship/tunes/tunes_client.rb:174:in `handle_itc_response': [31m[!] The request could not be completed because: (Spaceship::TunesClient::ITunesConnectError)
12:37:51 	You must provide an answer for this question. You must provide an answer for this question.[0m
12:37:51 	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.1/lib/spaceship/tunes/tunes_client.rb:523:in `update_build_trains!'
12:37:51 	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.1/lib/spaceship/tunes/build_train.rb:144:in `update_testing_status!'
12:37:51 	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.6.0/lib/pilot/build_manager.rb:127:in `distribute_build'
12:37:51 	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.6.0/lib/pilot/build_manager.rb:26:in `upload'
12:37:51 	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.6.0/lib/pilot/commands_generator.rb:60:in `block (2 levels) in run'
12:37:51 	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
12:37:51 	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
12:37:51 	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
12:37:51 	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
12:37:51 	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.43.5/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
12:37:51 	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
12:37:51 	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.6.0/lib/pilot/commands_generator.rb:126:in `run'
12:37:51 	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.6.0/lib/pilot/commands_generator.rb:16:in `start'
12:37:51 	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.6.0/bin/pilot:6:in `<top (required)>'
12:37:51 	from /usr/local/bin/pilot:23:in `load'
12:37:51 	from /usr/local/bin/pilot:23:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# INSERT CONTENT HERE
```

### Environment
Mac OS X 10.11.4
Mac Mini 6,2
fastlane version (run `fastlane -v`):
fastlane 1.89.0
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
no
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
no

**Comment by KrauseFx** [comment] 2016-05-18 21:52
This is a duplicate of many other issues https://github.com/fastlane/fastlane/search?q=You+must+provide+an+answer+for+this+question&type=Issues&utf8=%E2%9C%93

basically that's the reply https://github.com/fastlane/fastlane/issues/4002#issuecomment-218849799

**Closed** 2016-05-19 15:08 UTC
