### ISSUE TITLE
Produce: enable services needs Sign In with Apple capability

### ISSUE THREAD

**Issue by Nightstep** [fastlane/fastlane#16582] opened 2020-06-08 15:25 UTC
#### Motivation Behind Feature
Since Apple requires Sign In with Apple in apps which use social auth services, we need to have an ability to enable this function in fastlane pipeline
If this feature is implemented, please update documentation related to `enable_services`.

Thanks

**Comment by drielingme** [comment] 2020-06-11 10:21
Thank you for this post. Good luck.

**Comment by janpio** [comment] 2020-06-13 21:52
Duplicate of https://github.com/fastlane/fastlane/issues/16233

**Closed by janpio** 2020-06-13 21:52 UTC
Labels: tool: produce
