### ISSUE TITLE
app.live_version get error

### ISSUE THREAD

**Issue by qibinWang** [fastlane/fastlane#17151] opened 2020-09-04 03:02 UTC
### get response error
{
{"data"=>nil, "messages"=>{"warn"=>nil, "info"=>nil, "error"=>["Not Found"]}, "statusCode"=>"ERROR"}
Traceback (most recent call last):
	5: from /Users/027/Desktop/ipa_shell_center/app_build_status.rb:29:in `<main>'
	4: from /Users/027/.rvm/gems/ruby-2.6.5/gems/fastlane-2.157.3/spaceship/lib/spaceship/tunes/application.rb:126:in `live_version'
	3: from /Users/027/.rvm/gems/ruby-2.6.5/gems/fastlane-2.157.3/spaceship/lib/spaceship/tunes/app_version.rb:291:in `find'
	2: from /Users/027/.rvm/gems/ruby-2.6.5/gems/fastlane-2.157.3/spaceship/lib/spaceship/tunes/tunes_client.rb:447:in `app_version'
	1: from /Users/027/.rvm/gems/ruby-2.6.5/gems/fastlane-2.157.3/spaceship/lib/spaceship/tunes/tunes_client.rb:457:in `app_version_data'
/Users/027/.rvm/gems/ruby-2.6.5/gems/fastlane-2.157.3/spaceship/lib/spaceship/client.rb:721:in `parse_response': {"data"=>nil, "messages"=>{"warn"=>nil, "info"=>nil, "error"=>["Not Found"]}, "statusCode"=>"ERROR"} (Spaceship::UnexpectedResponse)
}

### my code
{
Spaceship::Tunes.login(username, password)
ApplicationClient = Spaceship::Tunes::Application
app = ApplicationClient.find(appid)
puts app.live_version  
}

env
{
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                |
| --------------------------- | ------------------------------------ |
| OS                          | 10.14                                |
| Ruby                        | 2.6.5                                |
| Bundler?                    | false                                |
| Git                         | git version 2.20.1 (Apple Git-117)   |
| Installation Source         | ~/.rvm/gems/ruby-2.6.5/bin/fastlane  |
| Host                        | Mac OS X 10.14 (18A391)              |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.5/lib         |
| OpenSSL Version             | OpenSSL 1.1.1f  31 Mar 2020          |
| Is contained                | false                                |
| Is homebrew                 | false                                |
| Is installed via Fabric.app | false                                |
| Xcode Path                  | /Library/Developer/CommandLineTools/ |
| Xcode Version               |                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.157.3 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.15.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.73.0       |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday                   | 1.0.1        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.10.1       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 1.17.3       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.0        |
| googleauth                | 0.11.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.5.1        |
| google-cloud-storage      | 1.26.0       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.296.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.1.1        |
| aws-sdk-core              | 3.94.0       |
| aws-sdk-kms               | 1.30.0       |
| aws-sdk-s3                | 1.61.2       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>

*generated on:* **2020-09-04**

}

**Comment by Hiroto-N** [comment] 2020-09-04 06:28
Seems like Apple has killed a few of the APIs around the old Tunes::Application - see https://github.com/fastlane/fastlane/issues/17140

You'll also need to replace any actions you're doing on the live_version to the new models as well

**Comment by qibinWang** [comment] 2020-09-04 06:33
@Hiroto-N  
      Thank you very much. I have noticed this problem. I am updating the code for verification

**Comment by bhruszka** [comment] 2020-09-04 08:30
I've updated to 2.157.3 and it seems like `Spaceship::Tunes::Application.latest_version` still doesn't work unfortunately.

**Comment by qibinWang** [comment] 2020-09-04 08:59
@bhruszka  
### You can try this code

Spaceship::ConnectAPI.login("xxxxx", "xxx")

app = Spaceship::ConnectAPI::App.find("com.xxxx.app")
version = app.get_latest_app_store_version(platform:Spaceship::ConnectAPI::Platform::IOS)

puts version.app_store_state

it works for me

**Comment by mdyson** [comment] 2020-09-04 16:28
I have a similar issue happening when I upload builds using pilot, when I'm uploading my build to app store connect it succeeds and does show up in app store connect, but fastlane reports it as an error. The only thing I've recently changed was updating to the latest version of fastlane (2.157.3). 


```
[06:00:17]: -------------------
[06:00:17]: --- Step: pilot ---
[06:00:17]: -------------------
[06:00:17]: Login to App Store Connect (----------)
[06:00:18]: Login successful
[06:00:20]: Ready to upload new build to TestFlight (App: -----------)...
[06:00:21]: Going to upload updated app to App Store Connect
[06:00:21]: This might take a few minutes. Please don't interrupt the script.
[06:02:23]: iTunes Transporter successfully finished its job
[06:02:23]: --------------------------------------------------------------------
[06:02:23]: Successfully uploaded package to App Store Connect. It might take a few minutes until it's visible online.
[06:02:23]: --------------------------------------------------------------------
[06:02:23]: Successfully uploaded the new binary to App Store Connect
[06:02:23]: `skip_waiting_for_build_processing` used and no `changelog` supplied - skipping waiting for build processing
[06:02:23]: ----------------------------------------------
[06:02:23]: --- Step: Switch to ios release_notes lane ---
[06:02:23]: ----------------------------------------------
[06:02:23]: Cruising over to lane 'ios release_notes' 🚖
[06:02:28]: -------------------
[06:02:28]: --- Step: slack ---
[06:02:28]: -------------------
[06:02:29]: Successfully sent Slack notification
[06:02:29]: {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Not Found"], "info"=>nil}, "statusCode"=>"ERROR"}
[06:02:29]: fastlane finished with errors
```

**Comment by joshdholtz** [comment] 2020-09-04 18:15
Hello! Most things in `Spaceship::Tunes` (legacy private API) are being deprecated are being switched over to `Spaceship::ConnectAPI`(official public API). I will be working on getting a doc up next week of the equivalent calls and what is all actually migrated.

**Comment by qibinWang** [comment] 2020-09-06 01:45
@joshdholtz  
  Thank you very much.  I will try next week after the doc update

**Comment by qibinWang** [comment] 2020-09-06 01:49
@mdyson 
Some old API  are being deprecated. you can update to the latest API.  just like @joshdholtz  said

**Comment by njoyjoy** [comment] 2020-09-09 04:01
Hi.  I'm a bit lost.  Fastlane no longer works for us.  Is this the same error as here:

bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
Spaceship::UnexpectedResponse: [!] {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Not Found"], "info"=>nil}, "statusCode"=>"ERROR"}
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.158.0/spaceship/lib/spaceship/client.rb:719:in `parse_response'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.158.0/spaceship/lib/spaceship/tunes/tunes_client.rb:456:in `app_version_data'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.158.0/spaceship/lib/spaceship/tunes/tunes_client.rb:447:in `app_version'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.158.0/spaceship/lib/spaceship/tunes/app_version.rb:291:in `find'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.158.0/spaceship/lib/spaceship/tunes/application.rb:126:in `live_version'
  Fastfile:30:in `block (2 levels) in parsing_binding'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:87:in `block (2 levels) in parsing_binding'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.158.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.158.0/bin/fastlane:23:in `<top (required)>'
  /usr/local/bin/fastlane:23:in `load'
  /usr/local/bin/fastlane:23:in `<top (required)>'

**Comment by max-ott** [comment] 2020-09-09 08:19
@njoyjoy Without showing what commands you actually run, this is not very helpful. To keep things on-topic please only provide useful information related to the issue. If you think this is a different problem, open a new issue. 🙏

**Comment by hzeraat2** [comment] 2020-09-09 12:22
@max-ott we are having the same issue with a few iOS Fastlane commands such as: 
**latest_testflight_build_number**

**Comment by qibinWang** [comment] 2020-09-09 14:14
@max-ott 
When I got a build from the get_builds API, I couldn't find the property to get the build number,like "1.0.0"
![image](https://user-images.githubusercontent.com/18628138/92609865-9f2c3e00-f2e9-11ea-808f-78b3653f4c52.png)

how can i get the  "CFBundleShortVersionString" version.
I looked at the code “build,rb” and didn't seem to find anything available 。

![image](https://user-images.githubusercontent.com/18628138/92609209-e6fe9580-f2e8-11ea-8aba-d6b265bc0408.png)

the version  property is not what I need !

**Comment by suren-singh** [comment] 2020-09-11 06:53
@joshdholtz @max-ott I am having issue in resolution_center.
My Code is,
`Spaceship::ConnectAPI.login(ENV['FASTLANE_USER'],ENV['FASTLANE_PASSWORD'])`
`app = Spaceship::ConnectAPI::App.find(ENV['BUNDLE_ID'])`
`liveVersion = app.get_latest_app_store_version(platform:Spaceship::ConnectAPI::Platform::IOS)`
`editVersion = app.get_edit_app_store_version(platform: Spaceship::ConnectAPI::Platform::IOS)`
`h = app.resolution_center`
Here I am getting error in resolution_center

**Comment by khawkins** [comment] 2020-09-14 05:10
@suren-singh As near as I can tell, API access to Resolution Center was not ported by Apple to the public App Store Connect API. There's no mention of such facilities in Apple's docs, beyond the initial App Store submission process.

**Comment by chandler-jose** [comment] 2020-09-23 05:44
I faced similar kind of issue last time, I am still searching for some proper solution [My Balance Now](https://www.mybalancenow.us/)

**Comment by max-ott** [comment] 2020-09-23 10:29
Closing and locking this issue. Please open individual issues for your problems.

- `app.live_version` and `app.edit_version` is no longer supported by Apple. Please use the new `ConnectAPI` code: `app.get_live_app_store_version` and `app.get_edit_app_store_version`

- `app.get_builds` works as intended. You'll need to filter by version or similar to get more information

- Resolution center still works as expected. Apple did not migrate this (yet). Your code crashes because of the above. It's not required for `resolution_center` See: https://github.com/fastlane/fastlane/issues/17298

**Closed by max-ott** 2020-09-23 10:29 UTC
Labels: tool: spaceship
