### ISSUE TITLE
Two factor sessions only lasting a few hours / "Session loaded from environment variable is not valid. Continuing with normal login."

### ISSUE THREAD

**Issue by smock** [fastlane/fastlane#13833] opened 2018-12-06 03:15 UTC
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [ x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

This report is as an end user -- it seems that two factor sessions are only lasting a few hours, as opposed to a month.  I spent a little bit of time digging in, it seems the DES cookie isn't being set.  Is this a temporary outage on the Apple side or an API change for session authentication?

**Comment by TheMetalCode** [comment] 2018-12-06 05:39
I can attest to this as well - we've had to reset our `FASTLANE_SESSION`3-4 times over the last couple of days. We're using version `2.109.1`.

For us, this is occurring during a `match` action that looks something like this:

```
    setup_circle_ci

    match(
      git_url: "git@github.com:[our match repo]",
      type: "adhoc",
      app_identifier: [our app identifier],
      force: true,
      readonly: false
    )
```

The output looks like this:

```
[21:30:08]: -----------------------------
[21:30:08]: --- Step: setup_circle_ci ---
[21:30:08]: -----------------------------
[21:30:08]: Creating temporary keychain: "fastlane_tmp_keychain".
[21:30:08]: Enabling match readonly mode.
[21:30:08]: Skipping Log Path setup as FL_OUTPUT_DIR is unset
[21:30:08]: -------------------
[21:30:08]: --- Step: match ---
[21:30:08]: -------------------

+-----------------------+----------------------------------------------+
|                      Summary for match 2.109.1                       |
+-----------------------+----------------------------------------------+
| git_url               | git@github.com:[REDACTED] |
| type                  | adhoc                                        |
| app_identifier        | [REDACTED]                |
| force                 | true                                         |
| readonly              | false                                        |
| git_branch            | master                                       |
| storage_mode          | git                                          |
| username              | [REDACTED]                          |
| keychain_name         | fastlane_tmp_keychain                        |
| team_id               | [REDACTED]                                   |
| verbose               | false                                        |
| skip_confirmation     | false                                        |
| shallow_clone         | false                                        |
| clone_branch_directly | false                                        |
| force_for_new_devices | false                                        |
| skip_docs             | false                                        |
| platform              | ios                                          |
+-----------------------+----------------------------------------------+

[21:30:08]: Cloning remote git repo...
[21:30:08]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[21:30:13]: 🔓  Successfully decrypted certificates repo
[21:30:13]: Verifying that the certificate and profile are still valid on the Dev Portal...
Session loaded from environment variable is not valid. Continuing with normal login.

Two-step Verification (4 digits code) or Two-factor Authentication (6 digits code) is enabled for account '[REDACTED]'
More information about Two-step Verification (4 digits code): https://support.apple.com/en-us/HT204152
More information about Two-factor Authentication (6 digits code): https://support.apple.com/en-us/HT204915

Two-factor Authentication (6 digits code) is enabled for account '[REDACTED]'
If you're running this in a non-interactive session (e.g. server or CI)
check out https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification
Please enter the 6 digit code: [21:30:15]: -------------------
```

The stack trace at the bottom is here (it seems noisy and not obviously related to the error but just for the sake of due diligence):

```
[21:30:15]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

bundler: failed to load command: fastlane (/Users/distiller/.gem/ruby/2.5.3/bin/fastlane)
NoMethodError: [!] undefined method `strip' for nil:NilClass
Did you mean?  String
Did you mean?  String
  /Users/distiller/.gem/ruby/2.5.3/gems/highline-1.7.10/lib/highline/question.rb:413:in `remove_whitespace'
  /Users/distiller/.gem/ruby/2.5.3/gems/highline-1.7.10/lib/highline.rb:873:in `get_line'
  /Users/distiller/.gem/ruby/2.5.3/gems/highline-1.7.10/lib/highline.rb:891:in `get_response'
  /Users/distiller/.gem/ruby/2.5.3/gems/highline-1.7.10/lib/highline.rb:264:in `ask'
  /Users/distiller/.gem/ruby/2.5.3/gems/fastlane-2.109.1/spaceship/lib/spaceship/two_step_or_factor_client.rb:129:in `handle_two_factor'
  /Users/distiller/.gem/ruby/2.5.3/gems/fastlane-2.109.1/spaceship/lib/spaceship/two_step_or_factor_client.rb:25:in `handle_two_step_or_factor'
  /Users/distiller/.gem/ruby/2.5.3/gems/fastlane-2.109.1/spaceship/lib/spaceship/client.rb:493:in `send_shared_login_request'
  /Users/distiller/.gem/ruby/2.5.3/gems/fastlane-2.109.1/spaceship/lib/spaceship/portal/portal_client.rb:28:in `send_login_request'
  /Users/distiller/.gem/ruby/2.5.3/gems/fastlane-2.109.1/spaceship/lib/spaceship/client.rb:751:in `do_login'
  /Users/distiller/.gem/ruby/2.5.3/gems/fastlane-2.109.1/spaceship/lib/spaceship/client.rb:383:in `login'
  /Users/distiller/.gem/ruby/2.5.3/gems/fastlane-2.109.1/spaceship/lib/spaceship/client.rb:345:in `login'
  /Users/distiller/.gem/ruby/2.5.3/gems/fastlane-2.109.1/spaceship/lib/spaceship/portal/spaceship.rb:25:in `login'
  /Users/distiller/.gem/ruby/2.5.3/gems/fastlane-2.109.1/spaceship/lib/spaceship/portal/spaceship.rb:103:in `login'
  /Users/distiller/.gem/ruby/2.5.3/gems/fastlane-2.109.1/match/lib/match/spaceship_ensure.rb:22:in `initialize'
  /Users/distiller/.gem/ruby/2.5.3/gems/fastlane-2.109.1/match/lib/match/runner.rb:47:in `new'
  /Users/distiller/.gem/ruby/2.5.3/gems/fastlane-2.109.1/match/lib/match/runner.rb:47:in `run'
  /Users/distiller/.gem/ruby/2.5.3/gems/fastlane-2.109.1/fastlane/lib/fastlane/actions/sync_code_signing.rb:12:in `run'
  /Users/distiller/.gem/ruby/2.5.3/gems/fastlane-2.109.1/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
  /Users/distiller/.gem/ruby/2.5.3/gems/fastlane-2.109.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/distiller/.gem/ruby/2.5.3/gems/fastlane-2.109.1/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
  /Users/distiller/.gem/ruby/2.5.3/gems/fastlane-2.109.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  /Users/distiller/.gem/ruby/2.5.3/gems/fastlane-2.109.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  /Users/distiller/.gem/ruby/2.5.3/gems/fastlane-2.109.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Users/distiller/.gem/ruby/2.5.3/gems/fastlane-2.109.1/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
  Fastfile:123:in `block (2 levels) in parsing_binding'
  /Users/distiller/.gem/ruby/2.5.3/gems/fastlane-2.109.1/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/distiller/.gem/ruby/2.5.3/gems/fastlane-2.109.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/distiller/.gem/ruby/2.5.3/gems/fastlane-2.109.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/distiller/.gem/ruby/2.5.3/gems/fastlane-2.109.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/distiller/.gem/ruby/2.5.3/gems/fastlane-2.109.1/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
  /Users/distiller/.gem/ruby/2.5.3/gems/fastlane-2.109.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/distiller/.gem/ruby/2.5.3/gems/fastlane-2.109.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Users/distiller/.gem/ruby/2.5.3/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/distiller/.gem/ruby/2.5.3/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/distiller/.gem/ruby/2.5.3/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/distiller/.gem/ruby/2.5.3/gems/fastlane-2.109.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/distiller/.gem/ruby/2.5.3/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/distiller/.gem/ruby/2.5.3/gems/fastlane-2.109.1/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
  /Users/distiller/.gem/ruby/2.5.3/gems/fastlane-2.109.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Users/distiller/.gem/ruby/2.5.3/gems/fastlane-2.109.1/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
  /Users/distiller/.gem/ruby/2.5.3/gems/fastlane-2.109.1/bin/fastlane:23:in `<top (required)>'
  /Users/distiller/.gem/ruby/2.5.3/bin/fastlane:23:in `load'
  /Users/distiller/.gem/ruby/2.5.3/bin/fastlane:23:in `<top (required)>'
Exited with code 1
```

**Comment by peterfox1** [comment] 2018-12-06 10:44
I'm seeing the same issue even when using an older version of fastlane to create the token too (`2.105.2`) - the session created with this version is now missing the DES cookie, our existing tokens that include this value no longer work / seem to be expired.

**Comment by janpio** [comment] 2018-12-06 18:31
I recently changed the behavior of the spaceship session logic here, which got released with 2.109.x:
https://github.com/fastlane/fastlane/pull/13743/files#diff-a9086da2d7e8a66b647fdabdb0a7cca7L409

Before it would just load the session from the env var, then use it in the request to possibly fail and give an only sometimes accurate error message. Now it tries the validate the session the same way the actual cookie in a file would be validated.

But this change should of course have no consequences to how long the session is valid, or what cookie is safed etc - I am wary and alarmed though.

@peterfox1 reporting that he has the identical issue with 2.105.2 is a relieve then. What output are you @peterfox1 getting when the session expires - does it include "Your session cookie has been expired."?

Can you both elaborate what you mean regarding the DES cookie?

--- 

@TheMetalCode, that stacktrace looks unrelated. Could you please create a new issue for it and explain how you got it after fastlane prompted you to enter the 6 digit code?

**Comment by kevinsperrine** [comment] 2018-12-06 18:39
I'm not certain of all the details, but I'm running into this same issue also with 2.109.1. I'm now having to update the FASTLANE_SESSION every few hours. I'm assuming 3 because the cookie output from spaceship has a max_age of 1800.

```
---\n- !ruby/object:HTTP::Cookie\n  name: myacinfo\n  value: [REDACTED]\n  domain: apple.com\n  for_domain: true\n  path: "/"\n  secure: true\n  httponly: true\n  expires: \n  max_age: \n  created_at: 2018-12-06 12:24:38.569432000 -06:00\n  accessed_at: 2018-12-06 12:24:38.570219000 -06:00\n- !ruby/object:HTTP::Cookie\n  name: dqsid\n  value: [REDACTED]\n  domain: olympus.itunes.apple.com\n  for_domain: false\n  path: "/"\n  secure: true\n  httponly: true\n  expires: \n  max_age: 1800\n  created_at: &1 2018-12-06 12:24:39.009985000 -06:00\n  accessed_at: *1\n
```

This is the stacktrace after failure (may or may not be related, but including for completeness sake).

```
INFO [2018-12-06 10:21:58.32]: Verifying that the certificate and profile are still valid on the Dev Portal...
Reading keychain entry, because either user or password were empty
Loading session from environment variable
Session loaded from environment variable is not valid. Continuing with normal login.

Two-step Verification (4 digits code) or Two-factor Authentication (6 digits code) is enabled for account '[REDACTED]'
More information about Two-step Verification (4 digits code): https://support.apple.com/en-us/HT204152
More information about Two-factor Authentication (6 digits code): https://support.apple.com/en-us/HT204915

Two-factor Authentication (6 digits code) is enabled for account '[REDACTED]'
If you're running this in a non-interactive session (e.g. server or CI)
check out https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification
Please enter the 6 digit code: WARN [2018-12-06 10:21:59.41]: [33m[33mLane Context:[0m
INFO [2018-12-06 10:21:59.41]: {:DEFAULT_PLATFORM=>:ios, :ENVIRONMENT=>"build", :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios build"}
INFO [2018-12-06 10:21:59.41]: [32mSuccessfully generated documentation at path '/Users/vagrant/git/ios/fastlane/README.md'[0m

+------+---------------------------------------------------------------+-------------+
|                                  [32mfastlane summary[0m                                  |
+------+---------------------------------------------------------------+-------------+
| Step | Action                                                        | Time (in s) |
+------+---------------------------------------------------------------+-------------+
| 1    | Verifying fastlane version                                    | 0           |
| 2    | default_platform                                              | 0           |
| 3    | set_info_plist_value                                          | 0           |
| 4    | set_info_plist_value                                          | 0           |
| 5    | wget -O latest.json [REDACTED] | 0           |
| 6    | scripts/replace.sh [REDACTED] | 0           |
| 7    | scripts/images.sh [REDACTED]       | 97          |
| 8    | aws s3 sync s3://[REDACTED]/ | 2           |
| 9    | aws s3 sync s3://[REDACTED]/ | 1           |
| 💥   | [31mmatch[0m                                                         | 2           |
+------+---------------------------------------------------------------+-------------+

ERROR [2018-12-06 10:21:59.43]: [31mfastlane finished with errors[0m

Looking for related GitHub issues on fastlane/fastlane...
Search query: undefined method `strip' for nil
Did you mean?  String

URL: https://api.github.com/search/issues?q=undefined%20method%20%60strip%27%20for%20nil%0ADid%20you%20mean%3F%20%20String+repo:fastlane/fastlane
➡️  [33mTwo factor sessions only lasting a few hours[0m
    https://github.com/fastlane/fastlane/issues/13833 [[31mopen[0m] 2 💬
    15 minutes ago

➡️  [33mTwo factor authentication fails after 2.106.0[0m
    https://github.com/fastlane/fastlane/issues/13603 [[31mopen[0m] 12 💬
    2 weeks ago

➡️  [33mFastlane match template_name[0m
    https://github.com/fastlane/fastlane/issues/11881 [[32mclosed[0m] 6 💬
    22 May 2018

and 2 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60strip%27%20for%20nil%0ADid%20you%20mean%3F%20%20String&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
NoMethodError: [31m[!] undefined method `strip' for nil:NilClass
Did you mean?  String[0m
  /usr/local/lib/ruby/gems/2.5.0/gems/highline-1.7.10/lib/highline/question.rb:413:in `remove_whitespace'
  /usr/local/lib/ruby/gems/2.5.0/gems/highline-1.7.10/lib/highline.rb:873:in `get_line'
  /usr/local/lib/ruby/gems/2.5.0/gems/highline-1.7.10/lib/highline.rb:891:in `get_response'
  /usr/local/lib/ruby/gems/2.5.0/gems/highline-1.7.10/lib/highline.rb:264:in `ask'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.109.1/spaceship/lib/spaceship/two_step_or_factor_client.rb:129:in `handle_two_factor'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.109.1/spaceship/lib/spaceship/two_step_or_factor_client.rb:25:in `handle_two_step_or_factor'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.109.1/spaceship/lib/spaceship/client.rb:493:in `send_shared_login_request'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.109.1/spaceship/lib/spaceship/portal/portal_client.rb:28:in `send_login_request'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.109.1/spaceship/lib/spaceship/client.rb:751:in `do_login'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.109.1/spaceship/lib/spaceship/client.rb:383:in `login'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.109.1/spaceship/lib/spaceship/client.rb:345:in `login'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.109.1/spaceship/lib/spaceship/portal/spaceship.rb:25:in `login'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.109.1/spaceship/lib/spaceship/portal/spaceship.rb:103:in `login'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.109.1/match/lib/match/spaceship_ensure.rb:22:in `initialize'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.109.1/match/lib/match/runner.rb:47:in `new'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.109.1/match/lib/match/runner.rb:47:in `run'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.109.1/fastlane/lib/fastlane/actions/sync_code_signing.rb:12:in `run'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.109.1/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.109.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.109.1/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.109.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.109.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.109.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.109.1/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
  Fastfile:150:in `block (2 levels) in parsing_binding'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.109.1/fastlane/lib/fastlane/lane.rb:33:in `call'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.109.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.109.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.109.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.109.1/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.109.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.109.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.109.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.109.1/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.109.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.109.1/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.109.1/bin/fastlane:23:in `<top (required)>'
  /usr/local/bin/fastlane:23:in `load'
  /usr/local/bin/fastlane:23:in `<top (required)>'
```

**Comment by janpio** [comment] 2018-12-06 19:09
Could you please take a look at your [spaceship logs](https://github.com/fastlane/fastlane/blob/master/spaceship/docs/Debugging.md#logging) and tell here what is happening there?

**Comment by smock** [comment] 2018-12-06 20:04
This line of code references the DES cookie:

https://github.com/fastlane/fastlane/blob/c58e102d26e3ec94175a00cad7ca0e7fb8e3e8b0/spaceship/lib/spaceship/client.rb#L462

which appears to no longer be returned during authentication.

**Comment by TheMetalCode** [comment] 2018-12-06 20:16
@janpio My CI builds will now store spaceship logs in build artifacts. I'll post back with some logs next time I see a 2FA-related failure.

**Comment by janpio** [comment] 2018-12-06 21:14
@smock As far as I know this is leftover code from before spaceship was rewritten to use the `myacinfo` and `dqsid` values, which are currently the relevant ones. (My knowledge here is very superficial though)

**Comment by simonbengtsson** [comment] 2018-12-06 22:24
I'm seeing this both in `2.108.0` and in `2.109.1` and on our ci machine. Related is that the session for appstoreconnect.apple.com etc on my Macbook Pro also expires after a few hours and I have to reenter the two auth code. Seems like something on Apple's end?

**Comment by TheMetalCode** [comment] 2018-12-06 22:57
@janpio Ok, here's a spaceship log from a recent failure, using fastlane `2.109.1`:

```
# Logfile created on 2018-12-06 14:49:25 -0800 by logger.rb/61378
INFO  [14:49:25]: >> GET https://olympus.itunes.apple.com/v1/session: [undefined body] 
DEBUG [14:49:26]: << GET https://olympus.itunes.apple.com/v1/session: 401 Unauthenticated

Request ID: 2KTUBN4ER52QTFIZUY2K7CQX.0.0

WARN  [14:49:26]: Auth lost
INFO  [14:49:26]: >> GET https://olympus.itunes.apple.com/v1/app/config?hostname=itunesconnect.apple.com: [undefined body] 
DEBUG [14:49:27]: << GET https://olympus.itunes.apple.com/v1/app/config?hostname=itunesconnect.apple.com: 200 {"authServiceUrl"=>"https://idmsa.apple.com/appleauth", "authServiceKey"=>"e0b80c3bf78523bfe80974d320935bfa30add02e1bff88ec2166c6bd5a706c42"}
INFO  [14:49:27]: >> POST https://idmsa.apple.com/appleauth/auth/signin: {"accountName":"[REDACTED]","password":"***","rememberMe":true} 
DEBUG [14:49:28]: << POST https://idmsa.apple.com/appleauth/auth/signin: 409 {"authType"=>"hsa2"}
INFO  [14:49:28]: >> GET https://idmsa.apple.com/appleauth/auth: [undefined body] 
DEBUG [14:49:28]: << GET https://idmsa.apple.com/appleauth/auth: 200 {"trustedPhoneNumbers"=>[{"numberWithDialCode"=>"+1 (•••) •••-••35", "pushMode"=>"sms", "obfuscatedNumber"=>"(•••) •••-••35", "id"=>6}, {"numberWithDialCode"=>"+1 (•••) •••-••72", "pushMode"=>"sms", "obfuscatedNumber"=>"(•••) •••-••72", "id"=>5}, {"numberWithDialCode"=>"+1 (•••) •••-••76", "pushMode"=>"sms", "obfuscatedNumber"=>"(•••) •••-••76", "id"=>2}, {"numberWithDialCode"=>"+1 (•••) •••-••91", "pushMode"=>"sms", "obfuscatedNumber"=>"(•••) •••-••91", "id"=>4}, {"numberWithDialCode"=>"+1 (•••) •••-••00", "pushMode"=>"sms", "obfuscatedNumber"=>"(•••) •••-••00", "id"=>3}], "securityCode"=>{"length"=>6, "tooManyCodesSent"=>false, "tooManyCodesValidated"=>false, "securityCodeLocked"=>false}, "authenticationType"=>"hsa2", "recoveryUrl"=>"https://iforgot.apple.com/phone/add?prs_account_nm=[REDACTED]&autoSubmitAccount=true&appId=142", "cantUsePhoneNumberUrl"=>"https://iforgot.apple.com/iforgot/phone/add?context=cantuse&prs_account_nm=[REDACTED]&autoSubmitAccount=true&appId=142", "recoveryWebUrl"=>"https://iforgot.apple.com/password/verify/appleid?prs_account_nm=[REDACTED]&autoSubmitAccount=true&appId=142", "repairPhoneNumberUrl"=>"https://gsa.apple.com/appleid/account/manage/repair/verify/phone", "repairPhoneNumberWebUrl"=>"https://appleid.apple.com/widget/account/repair?#!repair", "aboutTwoFactorAuthenticationUrl"=>"https://support.apple.com/kb/HT204921", "autoVerified"=>false, "showAutoVerificationUI"=>false, "managedAccount"=>false, "trustedPhoneNumber"=>{"numberWithDialCode"=>"+1 (•••) •••-••35", "pushMode"=>"sms", "obfuscatedNumber"=>"(•••) •••-••35", "id"=>6}, "hsa2Account"=>true, "supportsRecovery"=>true}
```

The rub being that the session we generated this morning still hasn't failed yet. I just happened to save the session we generated yesterday afternoon that stopped working late yesterday evening, so I one-off substituted the older session (which I would still expect to work after less than 24 hours) in order to force a failure.

**Comment by janpio** [comment] 2018-12-06 23:11
Ok, that log is pretty much what one would expect - the olympus endpoint doesn't like the session and responds with an `401`. Problem is, before that didn't happen that often, but now it does.

@simonbengtsson 's comment means that this also happens on normal usage in the browser, right?

**Comment by TheMetalCode** [comment] 2018-12-06 23:22
@janpio I ran this by one of the PMs on our team, and he reports that he is having to 2FA into his browser session way more often than usual, multiple times a day.

So that does add to the suspicion that Apple just isn't persisting the session for as long.

**Comment by TheMetalCode** [comment] 2018-12-07 00:52
This may or may not be helpful, but I did use this issue as an opportunity to make updating `FASTLANE_SESSION` faster and easier and thought I'd share: https://gist.github.com/TheMetalCode/d5bc698ef13dc9c1d5fdda698ec33123

The above script assumes CircleCI but could probably be adapted for any CI provider that allows you to set env vars via API.

**Comment by kevinsperrine** [comment] 2018-12-07 01:53
This definitely caused by an Apple change. BitRise also has a notice on their status page. 
![screenshot 2018-12-06 19 46 10](https://user-images.githubusercontent.com/609466/49622575-b78e5c80-f98f-11e8-9724-1d8aa2cc27d1.png) [This commit](https://github.com/bitrise-steplib/steps-ios-auto-provision/pull/47/commits/e7631da37b3329a6320f0e573a43d6552fd53cee#diff-45b19a337b0fddc1fa186fed3a7f5b2b) is how they handled it.  ¯\\_(ツ)_/¯

**Comment by janpio** [comment] 2018-12-07 09:50
Do you understand their workaround @kevinsperrine? Their PR was here: https://github.com/bitrise-steplib/steps-ios-auto-provision/pull/47

**Comment by janpio** [comment] 2018-12-07 11:19
Bitrise updated their incident:
![image](https://user-images.githubusercontent.com/183673/49644928-5a8bb880-fa1a-11e8-8462-777ff5ff35c4.png)

**Comment by kregan10** [comment] 2018-12-11 14:18
Hello, has there been any update or any other potential updates  with this issue?

Has there been any official release from Apple about this?  If so, can someone please let me know where one would find such info :)

**Comment by janpio** [comment] 2018-12-11 14:22
None that I am aware of.

**Comment by simonbengtsson** [comment] 2018-12-11 14:23
We have not heard anything either. Since you can't disable two factor auth an on apple account (?) we ended up creating a new apple account only for deployments.

**Comment by janpio** [comment] 2018-12-12 17:17
No real solution from Bitrise either :(

![image](https://user-images.githubusercontent.com/183673/49886517-22311380-fe3a-11e8-9f73-c5994fc9e253.png)

**Comment by NullIsOne** [comment] 2018-12-26 07:38
We are using action appstore_build_number to check build_number and auto increment if needed.
FASTLANE_SESSION is not valid after 8 hours, like above.
Btw, we are using deliver to appload builds and it is working with FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD.
Why all steps that logging to iTunesconnect can't use FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD to deal with 2FA??

**Comment by janpio** [comment] 2019-01-02 19:35
Because as far as I know (and just confirmed) you can't use an app specific password to log in to App Store Connect. Do you think otherwise?

**Closed** 2019-02-10 17:33 UTC
Labels: status: waiting-for-reply, tool: match, tool: spaceship
