### ISSUE TITLE
Pilot: Cannot remove testers from app / list ignores group

### ISSUE THREAD

**Issue by runloop** [fastlane/fastlane#8979] opened 2017-04-24 13:33 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I am able to remove testers from an app group, but not from the app completely. They still appear under the All Testers tab on ITC. This perhaps would not be an issue, but when I do `fastlane pilot list` it will list all the testers regardless of the whether I include a group or not.

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.11.6                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.10.1 (Apple Git-78)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.11.6 (15G1108)                  |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.0/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.28.3  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.4       |
| faraday_middleware        | 0.11.0.1     |
| io-console                | 0.4.6        |
| openssl                   | 2.0.2        |
| faraday                   | 0.12.1       |
| fastimage                 | 2.1.0        |
</details>

*generated on:* **2017-04-24**
</details>

**Comment by ohayon** [comment] 2017-04-24 18:05
Hey @runloop, wanted to give you a quick heads up, we are working on a fix for this and should get it out pretty shortly!

**Comment by ohayon** [comment] 2017-04-24 19:58
Hey @runloop [this PR](https://github.com/fastlane/fastlane/pull/8983) fixes _pilot_ to remove testers from the app-level when no groups are specified.

**Comment by ohayon** [comment] 2017-04-24 19:58
Feel free to reopen this issue if you are still having problems! Thanks! 🚀

**Comment by runloop** [comment] 2017-05-02 15:27
Just updated to 2.28.7 and I'm still getting issue if I try and remove a tester from an app that doesn't have a default group when specifying no groups.

```
[16:23:11]: Could not remove xxx@xxx.xxx from app: undefined method `remove_from_app!' for nil:NilClass
[16:23:11]: [xxx@xxx.xxx]: undefined method `remove_from_app!' for nil:NilClass
```

**Comment by KrauseFx** [comment] 2017-05-02 16:03
@runloop are you running the most recent release? Can you run `fastlane -v` to ensure it's up to date?

**Comment by runloop** [comment] 2017-05-02 16:06
```
~ $ fastlane -v
fastlane installation at path:
/Users/dan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.28.7/bin/fastlane
-----------------------------
fastlane 2.28.7
```

**Comment by KrauseFx** [comment] 2017-05-02 17:29
Could you also share the stack trace when running _fastlane_? You can get it using `--verbose` at the end of your fastlane call. This will help us fix the issue 👍

**Comment by runloop** [comment] 2017-05-03 13:08
Here you go.

It's worth noting this happens on my app where I had mistakenly deleted the default External Testers group.

```
~ $ fastlane pilot remove xxx@xxx.xxx -a com.runloop.heavyset --verbose
INFO [2017-05-03 14:04:56.78]: Login to iTunes Connect (xxx@xxx.xxx)
Looking for iTunes Connect Team with ID xxxxx
INFO [2017-05-03 14:04:59.80]: Login successful
ERROR [2017-05-03 14:05:02.49]: Could not remove xxx@xxx.xxx from app: undefined method `remove_from_app!' for nil:NilClass
ERROR [2017-05-03 14:05:02.49]: undefined method `remove_from_app!' for nil:NilClass
WARN [2017-05-03 14:05:02.49]: -------------
WARN [2017-05-03 14:05:02.49]: pilot crashed
WARN [2017-05-03 14:05:02.49]: -------------
ERROR [2017-05-03 14:05:02.49]: Unfortunately the TestFlight update from 11th April 2017 changed
ERROR [2017-05-03 14:05:02.49]: the way Testers, Groups, and Builds are managed on iTunesConnect.
ERROR [2017-05-03 14:05:02.49]: We have already fixed a number of features including submitting
ERROR [2017-05-03 14:05:02.49]: builds for testing, adding and removing testers from groups, and
ERROR [2017-05-03 14:05:02.49]: waiting for builds to process.
ERROR [2017-05-03 14:05:02.49]: 
ERROR [2017-05-03 14:05:02.49]: Please open an issue on https://github.com/fastlane/fastlane/issues
ERROR [2017-05-03 14:05:02.49]: if you believe this failure is the result of a bug in _pilot_ and we
ERROR [2017-05-03 14:05:02.49]: will be happy to look into this further.
ERROR [2017-05-03 14:05:02.49]: 
ERROR [2017-05-03 14:05:02.49]: Please stay tuned for more updates from _fastlane_ as we fix more issues!
ERROR [2017-05-03 14:05:02.49]: 
/Users/dan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.28.7/fastlane_core/lib/fastlane_core/ui/interface.rb:150:in `user_error!': [!] Some operations failed: undefined method `remove_from_app!' for nil:NilClass (FastlaneCore::Interface::FastlaneError)
	from /Users/dan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.28.7/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/dan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.28.7/pilot/lib/pilot/commands_generator.rb:38:in `handle_multiple'
	from /Users/dan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.28.7/pilot/lib/pilot/commands_generator.rb:129:in `block (2 levels) in run'
	from /Users/dan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/dan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Users/dan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/dan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.28.7/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:40:in `run!'
	from /Users/dan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Users/dan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.28.7/pilot/lib/pilot/commands_generator.rb:159:in `run'
	from /Users/dan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.28.7/pilot/lib/pilot/commands_generator.rb:12:in `start'
	from /Users/dan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.28.7/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Users/dan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.28.7/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'
```

**Comment by ohayon** [comment] 2017-05-03 13:11
Thanks for that output @runloop! We will definitely look into this, thats super helpful.

**Comment by ohayon** [comment] 2017-05-03 13:42
Hey @runloop, is the tester that you are trying to remove inside of a group (albeit not a default external group)?

**Comment by runloop** [comment] 2017-05-03 13:49
No, I can only see them on iTunesConnect under the All Testers tab. 

But the other side to this issue is that when exporting testers with ```fastlane pilot export``` it's the All Testers 'group' that gets exported. 

So I'm running through that list and comparing against my mailing list and trying to remove those that are not on both.

**Comment by ohayon** [comment] 2017-05-03 13:50
Ahhh, got it. Thanks for the quick reply. Taking a look now.

**Comment by ohayon** [comment] 2017-05-03 13:55
@runloop and just to confirm, this is within an app, not from the Users and Roles section of iTC right?

**Comment by runloop** [comment] 2017-05-03 13:57
Yes, these users are listed under iTunesConnect -> My App -> TestFlight -> Testers & Groups -> All Testers

**Comment by ohayon** [comment] 2017-05-03 14:01
Cool, so one of the things that is causing this issue is that a couple weeks ago Apple really muddied the waters between the testers that are visible in Users and Roles and the ones that are visible in the app level. The `pilot export` command has not been updated to support the new app-level stuff quite yet. So I think there is a disconnect between the list that you are getting when you call `export` and the testers that are available for deletion when you are calling `remove`. That being said, we definitely want to support what you are doing here so we can get this updates to work again for you.

Apologies for all of the questions, but would you mind just confirming that you _can_ see the tester you are trying to remove from within the `All Testers` list? We should be able to find them by email within the scope of the app when you call `remove` so I am inclined to believe that they are available in the Users & Roles section but not the app-level. Also, can you confirm that they are an external tester?

**Comment by runloop** [comment] 2017-05-03 14:06
They are definitely listed under the All Testers section within the app. But they are no longer in my external testers group.

**Comment by ohayon** [comment] 2017-05-03 14:17
Are they also listed under iTunes Connect Users?

**Comment by runloop** [comment] 2017-05-03 14:19
No, they were once external testers. Never internal testers.

**Comment by ohayon** [comment] 2017-05-03 14:44
Would you mind trying something out to try to isolate the issue? Could you in your terminal run `irb` and then do:
```
require 'spaceship'
Spaceship::Tunes.login
Spaceship::Tunes.select_team
app = Spaceship::Tunes::Application.find('<your bundle ID>')
tester = Spaceship::TestFlight::Tester.find(app_id: app.apple_id, email: '<the email you are looking for>')
puts tester
```

This should confirm that the tester is in fact being returned by the API. Hopefully this can help us figure out why the tester is nil when attempting to remove it from the app. Thanks again for all of your help!

**Comment by runloop** [comment] 2017-05-03 14:47
```
irb(main):005:0> tester = Spaceship::TestFlight::Tester.find(app_id: app.apple_id, email: 'xxx@xxx.xxx')
=> nil
```

**Comment by ohayon** [comment] 2017-05-03 14:47
And to ask one more question, because I just had a thought that maybe their API is paging, about how many testers do you have in the All Testers section?

**Comment by runloop** [comment] 2017-05-03 14:48
There are about 450 testers.

**Comment by ohayon** [comment] 2017-05-03 14:49
hmmmm... that could be it. Im going to try to add a bunch of testers to my test app to see if i can reproduce it that way. That code that I had you run in `irb` _should_ bet getting back all of the testers listed in the All Testers section, but it seems like its not if you are seeing the one there that you are trying to remove

**Comment by runloop** [comment] 2017-05-03 14:52
Could be. I just tried with the first email in the list and that was found. I scroll down with a few loads and tried another and it was nil.

**Comment by runloop** [comment] 2017-05-03 14:56
In fact, it can only find the first 5 users in the All Testers list.

**Comment by ohayon** [comment] 2017-05-03 14:58
Interesting. Thats great information to have. In my test app, I have only about 15 testers and I am able to find them all I believe, so clearly something is happening when there is a number of testers reached.

**Comment by runloop** [comment] 2017-05-03 15:02
I was able to find the first 14 testers from within my External Testers group. Then it starts returning nil.

**Comment by ohayon** [comment] 2017-05-03 15:13
Cool. I am running a script now that is adding 100 testers to my app to try to reproduce this.

**Comment by ohayon** [comment] 2017-05-03 15:37
Ok, so, it looks like we are going to be able to fix this pretty easily by adding a `limit` param on to our call to the iTC API. Just doing some more testing and then will get this fix pushed. We might need to do the same for groups based on what you mentioned about only seeing the first 14 in your group.

**Comment by ohayon** [comment] 2017-05-03 17:12
Hey @runloop, when you said 

> I was able to find the first 14 testers from within my External Testers group.

How did you go about getting only the ones from the group? Or is that whats in your "All Testers" list?

**Closed** 2017-05-03 17:47 UTC

**Comment by ohayon** [comment] 2017-05-03 17:51
@runloop, if you're familiar with how to run _fastlane_ off of master, feel free to clone it and give that a shot, otherwise, we will push a release out shortly and would love to hear back if it fixes your issue. Thanks again for being so responsive and helpful! 🚀 🐙

**Comment by KrauseFx** [comment] 2017-05-04 10:17
We also just pushed a new release, make sure to update to the most recent one 🚀

**Comment by runloop** [comment] 2017-05-04 11:08
I just updated and everything looks to be working now. Thanks for the work on this. This tool really does save me a lot of time managing my beta testers.
