### ISSUE TITLE
Unable to Login via Spaceship

### ISSUE THREAD

**Issue by Vishesh15312** [fastlane/fastlane#15663] opened 2019-11-15 13:28 UTC
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

We are using fastlane to communicate with apple developer console. All of sudden the login has stopped working and throwing the following error.
Unable to login via 

##### Command executed
 Spaceship::Portal.login

##### Complete output when running fastlane, including the stack trace and command used

```
  Service key is empty
      RuntimeError: Invalid 2 step response {"securityQuestions"=>{"questions"=>[{"id"=>133, "question"=>"What was the first film you saw in the cinema?", "number"=>1, "userDefined"=>false}, {"id"=>146, "question"=>"What was the first
      album that you purchased?", "number"=>3, "userDefined"=>false}]}, "crResetEnabled"=>false, "resetSecurityQuestionsSupportLink"=>"http://support.apple.com/kb/HT6170"}
      
	  from /usr/local/rvm/gems/ruby-2.3.1/gems/fastlane-2.68.2/spaceship/lib/spaceship/two_step_client.rb:41:in 'handle_two_step'

	  from /usr/local/rvm/gems/ruby-2.3.1/gems/fastlane-2.68.2/spaceship/lib/spaceship/client.rb:505:in 'send_shared_login_request'
        
		from /usr/local/rvm/gems/ruby-2.3.1/gems/fastlane-2.68.2/spaceship/lib/spaceship/portal/portal_client.rb:13:in 'send_login_request'
        
		from /usr/local/rvm/gems/ruby-2.3.1/gems/fastlane-2.68.2/spaceship/lib/spaceship/client.rb:700:in 'do_login'
        
		from /usr/local/rvm/gems/ruby-2.3.1/gems/fastlane-2.68.2/spaceship/lib/spaceship/client.rb:405:in 'login'
        
		from /usr/local/rvm/gems/ruby-2.3.1/gems/fastlane-2.68.2/spaceship/lib/spaceship/client.rb:121:in 'login'
        
		from /usr/local/rvm/gems/ruby-2.3.1/gems/fastlane-2.68.2/spaceship/lib/spaceship/portal/spaceship.rb:22:in 'login'
        
		from (irb):3
        
		from /usr/local/rvm/rubies/ruby-2.3.1/bin/irb:11:in '<main>'
```

**Comment by janpio** [comment] 2019-11-16 23:12
Interesting, can you help us reproduce this? What is the full code you are using that we could run to get to the same result?

Seems Apple changed something and is now asking for security questions somehow. Interesting.

**Comment by max-ott** [comment] 2019-11-18 11:08
Btw could you update to the lastest Fastlane? Looks like you are on version `2.68.2`

**Comment by janpio** [comment] 2019-11-18 13:34
Ah, that would make this a duplicate of https://github.com/fastlane/fastlane/issues/15496

**Comment by carloscuesta** [comment] 2019-11-18 14:58
In my particular case I'm using `fastlane@2.106.0`

And the error I've got is:

```
Invalid 2 step response {"securityQuestions"=>{"questions"=>[{"id"=>130, "question"=>"What was the name of your best friend as a teenager?", "number"=>1, "userDefined"=>false}, {"id"=>147, "question"=>"What is the name of your favourite sports team?", "number"=>3, "userDefined"=>false}]}, "crResetEnabled"=>false, "resetSecurityQuestionsSupportLink"=>"http://support.apple.com/kb/HT6170"}
```

**Comment by CovertLeopard** [comment] 2019-11-18 16:21
We started getting this early Friday morning as well: 

`gems/fastlane-2.104.0/spaceship/lib/spaceship/two_step_client.rb:45:in `handle_two_step': [!] Invalid 2 step response {"securityQuestions"=>{"questions"=>[{"id"=>145, "question"=>"xxxxxxxxxxxxxx?", "number"=>3, "userDefined"=>false}, {"id"=>140, "question"=>"xxxxxxxxxxxxxxxxx?", "number"=>2, "userDefined"=>false}]}, "rescueEmailAddress"=>"xxxxxxxxxxxxxxxxxxx", "crResetEnabled"=>false, "resetSecurityQuestionsSupportLink"=>"http://support.apple.com/kb/HT6170"} (RuntimeError)`

For us, it happens during fastlane deliver command.

**Comment by max-ott** [comment] 2019-11-18 16:45
Again, another old version @CovertLeopard : `fastlane-2.104.0`. Please update to the latest version (`2.136.0`), so we can help and investigate.

**Comment by carloscuesta** [comment] 2019-11-18 17:08
I was having the exact same problem with `fastlane@2.106.0` and upgrading to `2.136.0` has fixed the issue ❤️

**Closed** 2019-12-26 17:32 UTC
Labels: status: waiting-for-reply, tool: spaceship, topic: authentication
