### ISSUE TITLE
Error Domain=IDEDistributionErrorDomain Code=1 "No valid iOS Distribution signing identities belonging to team xxxx were found." UserInfo={NSLocalizedDescription=No valid iOS Distribution signing identities belonging to team xxxxx were found.}

### ISSUE THREAD

**Issue by ramazanoff** [fastlane/fastlane#9793] opened 2017-07-18 11:18 UTC
Strange error. I cant fix this problem. What should i do?

**Comment by ramazanoff** [comment] 2017-07-18 11:21
2017-07-18 17:09:03.201 xcodebuild[39995:867543] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/wv/29lz06ss3lx4prrftyptf83h0000gn/T/allpay alpha_2017-07-18_17-09-03.199.xcdistributionlogs'.
2017-07-18 17:09:04.401 xcodebuild[39995:867543] [MT] IDEDistribution: Step failed: <IDEDistributionSigningAssetsStep: 0x7fe7c8d09970>: Error Domain=IDEDistributionErrorDomain Code=1 "No valid iOS Distribution signing identities belonging to team F44VKRB3PH were found." UserInfo={NSLocalizedDescription=No valid iOS Distribution signing identities belonging to team F44VKRB3PH were found.}
error: exportArchive: No valid iOS Distribution signing identities belonging to team F44VKRB3PH were found.

Error Domain=IDEDistributionErrorDomain Code=1 "No valid iOS Distribution signing identities belonging to team F44VKRB3PH were found." UserInfo={NSLocalizedDescription=No valid iOS Distribution signing identities belonging to team F44VKRB3PH were found.}

** EXPORT FAILED **
[17:09:04]: Exit status: 70
[17:09:04]: ▸     cd /Users/c0rp/Projects/allpay_ios_v2.0
[17:09:04]: ▸     export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/c0rp/.fastlane/bin/bundle/bin:/Users/c0rp/.fastlane/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
[17:09:04]: ▸     /usr/bin/touch -c /Users/c0rp/Library/Developer/Xcode/DerivedData/allpay_wallet-bwbqywxpixjiyifdpfrlpmrfnxmr/Build/Intermediates/ArchiveIntermediates/allpay\ alpha/BuildProductsPath/Release-iphoneos/allpay\ alpha.app.dSYM
[17:09:04]: ▸ ** ARCHIVE SUCCEEDED **
[17:09:04]: 
[17:09:04]: ⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
[17:09:04]: 📋  For the complete and more detailed error log, check the full log at:
[17:09:04]: 📋  /Users/c0rp/Library/Logs/gym/allpay alpha-allpay alpha.log
[17:09:04]: 
[17:09:04]: Looks like fastlane ran into a build/archive error with your project
[17:09:04]: It's hard to tell what's causing the error, so we wrote some guides on how
[17:09:04]: to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
[17:09:04]: Before submitting an issue on GitHub, please follow the guide above and make
[17:09:04]: sure your project is set up correctly.
[17:09:04]: fastlane uses `xcodebuild` commands to generate your binary, you can see the
[17:09:04]: the full commands printed out in yellow in the above log.
[17:09:04]: Make sure to inspect the output above, as usually you'll find more error information there
[17:09:04]: 
+------------------+-----------+
|         Lane Context         |
+------------------+-----------+
| DEFAULT_PLATFORM | ios       |
| PLATFORM_NAME    | ios       |
| LANE_NAME        | ios alpha |
+------------------+-----------+
[17:09:04]: Error packaging up the application

+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | Verifying required  | 0           |
|      | fastlane version    |             |
| 2    | default_platform    | 0           |
| 💥   | gym                 | 367         |
+------+---------------------+-------------+

[17:09:04]: fastlane finished with errors

[!] Error packaging up the application

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.11.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.8.1                           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.11.6 (15G1510)                  |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

**Comment by Sega-Zero** [comment] 2017-07-18 12:30
duplicate of #9782

**Comment by KrauseFx** [comment] 2017-07-18 12:50
Yeah, let's move this to https://github.com/fastlane/fastlane/issues/9782

**Closed by KrauseFx** 2017-07-18 12:50 UTC
