### ISSUE TITLE
fastlane init error: app identifier is nil

### ISSUE THREAD

**Issue by jxbambrick** [fastlane/fastlane#1181] opened 2016-01-22 18:16 UTC
I am having trouble getting fastlane init to complete successfully. I am using Ruby 2.3.5 and Fastlane 1.52.0. Here is the error number: 887107dd56d0a634cc837d23388297d4 

When I run fastlane init, it asks for my Apple ID, and prints out the detected values. The App Id, and App Name are filled out but App Identifier is empty. I'm prompted with the message "This app identifier doesn't exist on iTunes Connect yet, it will be created for you" and "This app identifier doesn't exist on the Apple Developer Portal yet, it will be created for you". I confirm the above values and an error is thrown. 

Looking at the log: "message": "TypeError: no implicit conversion of nil into String", and "culprit": "fastlane/setup/setup_ios.rb in gsub! at line 110"

 I've opened the project in xcode, cleaned, built, and run with no errors. I've also confirmed that the bundle identifier is filled com.test.project.example. The project is originally an Ionic/Cordova hybrid project. 

Attached is the json file zipped up.  Please let me know if there's any additional information you need. 
(https://github.com/fastlane/fastlane/files/101217/sentry_887107dd56d0a634cc837d23388297d4.json.zip)

[sentry_887107dd56d0a634cc837d23388297d4.json.zip]

**Comment by ohwutup** [comment] 2016-01-23 17:03
i think this might be a dupe of https://github.com/fastlane/fastlane/issues/1167 or will at least be addressed in the same fix. @jxbambrick if you don't mind, we can close this and track progress on the other issue?

**Comment by jxbambrick** [comment] 2016-01-25 02:34
That sounds good. I think I found #1167 shortly after posting this. Thanks for the support.

**Closed** 2016-01-25 15:28 UTC
