### ISSUE TITLE
Slack action resulting in "Shell command exited with exit status 128 instead of 0"

### ISSUE THREAD

**Issue by vx8** [fastlane/fastlane#18467] opened 2021-03-29 08:47 UTC
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When trying to post a slack message using a simple slack action, the result is the following:

**Shell command exited with exit status 128 instead of 0**

##### Command executed

`lane :slack2 do |options|
	
	notification(subtitle: "TEST", message: "testing slack message push",  sound: "Hero")
	slack(
		message: "Slack test message push",
		success: true
		)
end`
##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>  ✘  ~/iPadApp  fastlane slack2
[✔] 🚀 
[10:44:42]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[10:44:45]: ------------------------------
[10:44:45]: --- Step: default_platform ---
[10:44:45]: ------------------------------
[10:44:45]: Driving the lane 'slack2' 🚀
[10:44:45]: --------------------------
[10:44:45]: --- Step: notification ---
[10:44:45]: --------------------------
[10:44:45]: -------------------
[10:44:45]: --- Step: slack ---
[10:44:45]: -------------------
+------------------+--------+
|       Lane Context        |
+------------------+--------+
| DEFAULT_PLATFORM | ios    |
| PLATFORM_NAME    |        |
| LANE_NAME        | slack2 |
+------------------+--------+
[10:44:45]: Shell command exited with exit status 128 instead of 0.

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 2    | notification     | 0           |
| 💥   | slack            | 0           |
+------+------------------+-------------+

[10:44:45]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Adds more options to the `slack` command
    https://github.com/fastlane/fastlane/pull/128 [closed] 3 💬
    04 Feb 2017

➡️  fastlane notarize fails during staple even though the package is approved
    https://github.com/fastlane/fastlane/issues/17667 [open] 8 💬
    5 days ago

➡️  Dead link provided when `fastlane run appledoc`
    https://github.com/fastlane/fastlane/issues/17503 [closed] 1 💬
    03 Jan 2021

and 13 more at: https://github.com/fastlane/fastlane/search?q=Shell%20command%20exited%20with%20exit%20status%20128%20instead%20of%200.&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
Traceback (most recent call last):
	34: from /usr/local/Cellar/fastlane/2.179.0/libexec/bin/fastlane:23:in `<main>'
	33: from /usr/local/Cellar/fastlane/2.179.0/libexec/bin/fastlane:23:in `load'
	32: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/bin/fastlane:23:in `<top (required)>'
	31: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	30: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	29: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	28: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	27: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	26: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	25: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	24: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	23: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	22: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	21: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	20: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	19: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	18: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	17: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	16: from Fastfile:176:in `block in parsing_binding'
	15: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	14: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	13: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	12: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	11: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	10: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	 9: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	 8: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane/lib/fastlane/actions/slack.rb:44:in `run'
	 7: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane/lib/fastlane/actions/slack.rb:230:in `generate_slack_attachments'
	 6: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane/lib/fastlane/helper/git_helper.rb:126:in `git_branch'
	 5: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane/lib/fastlane/helper/git_helper.rb:126:in `fetch'
	 4: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane/lib/fastlane/helper/git_helper.rb:126:in `block in git_branch'
	 3: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane/lib/fastlane/helper/sh_helper.rb:12:in `sh'
	 2: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
	 1: from /usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/usr/local/Cellar/fastlane/2.179.0/libexec/gems/fastlane-2.179.0/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': \e[31m[!] Shell command exited with exit status 128 instead of 0.\e[0m (FastlaneCore::Interface::FastlaneShellError)
 </pre>
</details>

### Environment

 ✘  ~/iPadApp  fastlane env
[✔] 🚀 
[10:45:36]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[10:45:39]: Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 11.2.3                                                  |
| Ruby                        | 2.7.2                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.24.3 (Apple Git-128)                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.179.0/libexec/bin/fastlane |
| Host                        | macOS 11.2.3 (20D91)                                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.7/2.7.2/lib                    |
| OpenSSL Version             | OpenSSL 1.1.1i  8 Dec 2020                              |
| Is contained                | false                                                   |
| Is homebrew                 | true                                                    |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 12.4                                                    |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby

default_platform :ios

ENV["SLACK_URL"] = "hidden"



lane :slack2 do |options|
	
	notification(subtitle: "TEST", message: "testing slack message push",  sound: "Hero")
	slack(
		message: "Slack test message push",
		success: true
		)
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# The Appfile can be used to specify information that's used across all fastlane
# tools, like your username or the app's bundle identifier.
#
# For more details, check out the documentation at:
# https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

# app_identifier "com.your.app" # the bundle identifier of your app
# apple_id "apple@fastlane.tools" # Your Apple ID

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.179.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.4.0        |
| slack-notifier                | 2.3.2        |
| atomos                        | 0.1.3        |
| CFPropertyList                | 3.0.3        |
| claide                        | 1.0.3        |
| colored2                      | 3.1.2        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| plist                         | 3.6.0        |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| multipart-post                | 2.0.0        |
| word_wrap                     | 1.0.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| artifactory                   | 3.0.15       |
| babosa                        | 1.0.4        |
| colored                       | 1.2          |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| excon                         | 0.79.0       |
| faraday-net_http              | 1.0.1        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.3.0        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.3        |
| gh_inspector                  | 1.1.3        |
| json                          | 2.3.0        |
| mini_magick                   | 4.11.0       |
| naturally                     | 2.2.1        |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| xcpretty-travis-formatter     | 1.0.1        |
| dotenv                        | 2.7.6        |
| bundler                       | 2.1.4        |
| simctl                        | 1.6.8        |
| jwt                           | 2.2.2        |
| uber                          | 0.1.0        |
| declarative                   | 0.0.20       |
| declarative-option            | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.2        |
| mini_mime                     | 1.0.3        |
| multi_json                    | 1.15.0       |
| signet                        | 0.15.0       |
| memoist                       | 0.16.2       |
| os                            | 1.1.1        |
| googleauth                    | 0.16.0       |
| httpclient                    | 2.8.3        |
| google-api-client             | 0.38.0       |
| google-cloud-env              | 1.5.0        |
| google-cloud-errors           | 1.1.0        |
| google-cloud-core             | 1.6.0        |
| rexml                         | 3.2.3        |
| webrick                       | 1.6.0        |
| google-apis-core              | 0.3.0        |
| google-apis-iamcredentials_v1 | 0.2.0        |
| google-apis-storage_v1        | 0.3.0        |
| rake                          | 13.0.3       |
| digest-crc                    | 0.6.3        |
| google-cloud-storage          | 1.31.0       |
| emoji_regex                   | 3.2.2        |
| jmespath                      | 1.4.0        |
| aws-partitions                | 1.435.0      |
| aws-eventstream               | 1.1.1        |
| aws-sigv4                     | 1.2.3        |
| aws-sdk-core                  | 3.113.0      |
| aws-sdk-kms                   | 1.43.0       |
| aws-sdk-s3                    | 1.93.0       |
| uri                           | 0.10.0       |
| forwardable                   | 1.3.1        |
| logger                        | 1.4.2        |
| cgi                           | 0.1.0        |
| date                          | 3.0.0        |
| timeout                       | 0.1.0        |
| stringio                      | 0.1.0        |
| zlib                          | 1.1.0        |
| ipaddr                        | 1.2.2        |
| openssl                       | 2.1.2        |
| ostruct                       | 0.2.0        |
| strscan                       | 1.0.3        |
| delegate                      | 0.1.0        |
| fileutils                     | 1.4.1        |
| io-console                    | 0.5.6        |
| open3                         | 0.1.0        |
| singleton                     | 0.1.0        |
| yaml                          | 0.1.0        |
| psych                         | 3.1.0        |
| mutex_m                       | 0.1.0        |
</details>

*generated on:* **2021-03-29**
</details>

**Comment by mariaaloysiusa** [comment] 2021-03-29 17:21
even i am facing the same issue.

**Comment by mcactive** [comment] 2021-03-29 19:07
Same issue here.. Reverting back to release 2.178.0 solves the issue

**Comment by ppamorim** [comment] 2021-03-30 14:10
Same issue here when running in our CI.

**Comment by vx8** [comment] 2021-03-30 17:35
> Same issue here.. Reverting back to release 2.178.0 solves the issue

How can I downgrade using brew? It lets me only install the latest version

**Comment by mcactive** [comment] 2021-03-30 19:03
> > Same issue here.. Reverting back to release 2.178.0 solves the issue
> 
> How can I downgrade using brew? It lets me only install the latest version

Just edit your Gemfile and change `gem "fastlane"` to `gem "fastlane", '2.178.0'`

**Comment by vx8** [comment] 2021-04-03 11:08
sadly I cannot update all our machine to use Gem instead of Brew.

Any workaround for this using Brew until it gets fixed?

Thanks

**Comment by minuscorp** [comment] 2021-04-03 14:46
```
brew uninstall fastlane
brew install fastlane@1.178.0
```

**Comment by vx8** [comment] 2021-04-03 20:13
@minuscorp already tried but get this result

`Error: No available formula or cask with the name "fastlane@2.178.0".`

**Comment by minuscorp** [comment] 2021-04-03 20:23
`brew search fastlane` might throw better results about what is uploaded in brew.

**Comment by vx8** [comment] 2021-04-03 20:29
@minuscorp  
it gives no result with this output

==> Formulae
fastlane

If you meant "fastlane" specifically:
It was migrated from homebrew/cask to homebrew/core.

**Comment by vx8** [comment] 2021-04-08 12:24
This is still occurring in version **2.180.0**

**Comment by minuscorp** [comment] 2021-04-08 14:17
Last time slack action was modified was in https://github.com/fastlane/fastlane/pull/17866 which was released in 1.171.0, I just can think that you can reproduce the issue with a local Gemfile and a bundle instead of a built brew version in one of the machines and report back to us if you can.

**Comment by ChristopherDrum** [comment] 2021-04-09 06:15
@vx8 Frustrating to hear

**Comment by Kukurijek** [comment] 2021-04-13 19:11
The issue occurs since version 2.179.0, but only on macOS 11.
Circle CI does not yet support the macOS 11 and Xcode 12.5 beta -> [Status Update](https://discuss.circleci.com/t/macos-11-big-sur-status-update/39204)
Fastlane should find a way to run unit tests on macOS 11, so this cannot happen.

**Comment by minuscorp** [comment] 2021-04-13 19:42
Tests are run in macOS 11.0 and 11.4 as I can see in circle, tests are regarding certain Xcode releases and Ruby configurations on those systems (beyond others).

**Comment by minuscorp** [comment] 2021-04-13 19:44
We are open for contributions for those requirements. Remember this is a open source project.

**Comment by Kukurijek** [comment] 2021-04-17 19:54
Sorry if it sounded too aggressive, I just said my opinion out loud 😅🙂
Btw. I found the issue, the PR comes soon 🙂

**Comment by rogerluan** [comment] 2021-04-18 13:13
According to @Kukurijek , those of you using Gemfile can point it to `:branch => master` and see if the issue is fixed

**Closed** 2021-06-18 17:30 UTC
Labels: status: waiting-for-reply
