### ISSUE TITLE
double sized ipa file 

### ISSUE THREAD

**Issue by dholdaway** [fastlane/fastlane#4378] opened 2016-04-27 07:13 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

.ipa file is larger than when i run ipa build its double the size.

##### Complete output when running fastlane, including the stack trace and command used

```
INSERT OUTPUT HERE
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
platform :ios do
desc 'Build ipa'
lane :build do
  gym(
  use_legacy_build_api: true,
  workspace: “xxx.xcworkspace”,
  scheme: “xxx.PoC”,
  export_method: "ad-hoc",
  silent: true,
  include_bitcode: false,
  include_symbols: false,
  clean: true,
  output_directory: “../CrashlyticsBetaBuilds”, # Destination directory. Defaults to current directory.
  output_name: “xxx.ipa”, # specify the name of the .ipa file to generate (including file extension)
  codesigning_identity: "iPhone Distribution:xxx xxx (xx xx xx xx)",
  )
end
end

```

### Environment

fastlane version (run `fastlane -v`):

fastlane 1.82.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
rvm 1.27.0 (master)

ruby 2.0.0p648 (2015-12-16 revision 53162) [x86_64-darwin15.2.0]

**Comment by dholdaway** [comment] 2016-04-27 07:29
we are building swift

**Comment by dholdaway** [comment] 2016-04-27 07:44
i tried adding 

sh "zip -d \"$IPA_OUTPUT_PATH\" \"SwiftSupport/*\""

but it only reduced it slightly

xcode - > archive > export -> gives me 10mb ipa
shenzhen ipa build -> gives me --> 33mb ipa
gym -> gives me --> 66mb

**Comment by TKBurner** [comment] 2016-04-27 14:08
Hi @dholdaway Thanks for reaching out. Can you share the output of when you run this lane with the --verbose flag? It'll help us look into this 👍

**Comment by KrauseFx** [comment] 2016-04-27 14:29
That's a duplicate of https://github.com/fastlane/fastlane/issues/519, right?

**Comment by dholdaway** [comment] 2016-04-27 14:57
yes

**Comment by TKBurner** [comment] 2016-04-28 14:28
@dholdaway We'll work on that ticket. Thanks for reporting this. Closing this out for housekeeping 👍

**Closed by TKBurner** 2016-04-28 14:28 UTC
Labels: awaiting-reply, gym, question
