### ISSUE TITLE
generate_push_cert 

### ISSUE THREAD

**Issue by nageshkumarmishra** [fastlane/fastlane#19884] opened 2022-02-01 15:22 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Fastlane generates the get_push_certificate method is throwing an error message in bitrise.
 

##### Command executed

get_push_certificate(
  development: isDevEnv,
  app_identifier: "NAME", 
  pem_name: "UUID", 
  p12_password: password, 
  output_path: "./ios_push_certificate",
  new_profile: proc do |profile_path| # this block gets called when a new profile was  generated
  puts profile_path # the absolute path to the new PEM file
  # insert the code to zip the folder contraining PEM file 
  zip(path: "./root/ios_push_certificate", output_path: "./root/ios_push_certificate.zip")
  end
  )

error message 
[12:06:52]: {"responseId"=>"59977cca-fcc6-4fe4-bd27-03a5cc60483e", "resultCode"=>4100, "resultString"=>"The selected team does not have a program membership that is eligible for this feature.  If you need assistance, please contact Apple Developer Program Support. https://developer.apple.com/support", "userString"=>"The selected team does not have a program membership that is eligible for this feature.  If you need assistance, please contact Apple Developer Program Support. https://developer.apple.com/support", "creationTimestamp"=>"2022-02-01T12:06:52Z", "protocolVersion"=>"QH65B2", "userLocale"=>"en_US", "requestUrl"=>"https://developer.apple.com/services-account/xxxxx/account/ios/certificate/submitCertificateRequest.action", "httpCode"=>200}

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by JimDabell** [comment] 2022-02-02 06:49
This is a duplicate of [#19878](https://github.com/fastlane/fastlane/issues/19878), which has an open pull request.

**Closed** 2022-02-11 11:12 UTC
Labels: tool: pem, status: has-pr, duplicate
