### ISSUE TITLE
Updating FastlaneSwiftRunner fails

### ISSUE THREAD

**Issue by andreaslindahl** [fastlane/fastlane#17234] opened 2020-09-14 15:02 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
After updating fastlane to version 2.159.0 I can't upgrade the FastlaneSwiftRunner project. I get the following build error: 

`Fastlane.swift:9266:12: constant cannot be declared public because its type 'Deliverfile' uses an internal type`

I also get the same error for all of the other similar rows at the end of the Fastlane.swift file:

```
public let deliverfile = Deliverfile()
public let gymfile = Gymfile()
public let matchfile = Matchfile()
public let precheckfile = Precheckfile()
public let scanfile = Scanfile()
public let screengrabfile = Screengrabfile()
public let snapshotfile = Snapshotfile()
```

`Fastlane env` gives this:

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.6                                     |
| Ruby                        | 2.6.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.24.3 (Apple Git-128)          |
| Installation Source         | ~/.rvm/gems/ruby-2.6.3/bin/fastlane         |
| Host                        | Mac OS X 10.15.6 (19G2021)                  |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.3/lib                |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.7                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.159.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 2.1.4        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.18.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday                   | 1.0.1        |
| faraday_middleware        | 1.0.0        |
| gh_inspector              | 1.1.3        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| uber                      | 0.1.0        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.356.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-sdk-core              | 3.104.3      |
| aws-sdk-kms               | 1.36.0       |
| aws-sdk-s3                | 1.78.0       |
| CFPropertyList            | 3.0.2        |
| unicode-display_width     | 1.7.0        |
| public_suffix             | 4.0.5        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| excon                     | 0.76.0       |
| unf_ext                   | 0.0.7.7      |
| fastimage                 | 2.2.0        |
| json                      | 2.3.1        |
| mini_magick               | 4.10.1       |
| dotenv                    | 2.7.6        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.1        |
| declarative               | 0.0.20       |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| os                        | 1.1.1        |
| memoist                   | 0.16.2       |
| googleauth                | 0.13.1       |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-env          | 1.3.3        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.27.0       |
| emoji_regex               | 3.0.0        |
| forwardable               | 1.3.1        |
| logger                    | 1.4.2        |
| stringio                  | 0.1.3        |
| openssl                   | 2.2.0        |
| ipaddr                    | 1.2.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.3        |
| date                      | 3.0.1        |
| fileutils                 | 1.4.1        |
| io-console                | 0.5.6        |
| zlib                      | 1.1.0        |
| rexml                     | 3.2.4        |
| psych                     | 3.2.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.6.0        |
</details>

*generated on:* **2020-09-14**
</details>

**Comment by vignesh-sankaran** [comment] 2020-09-15 02:34
I am running into this issue as well

**Comment by razor313** [comment] 2020-09-16 11:30
+1

**Comment by alexisbronchart** [comment] 2020-09-18 06:59
This seems identical to https://github.com/fastlane/fastlane/issues/17253

**Comment by rogerluan** [comment] 2020-09-18 21:06
I'm on 2.160 Xcode 11.5 and it happens as well.

**Comment by rogerluan** [comment] 2020-09-18 21:42
After some investigation, I observed that:

- We changed the declarations to be `public` to add support to SPM, in which the declaration of functions, protocols, etc have to be `public`
- Since these are public, the declaration of your local-defined protocols (e.g. Gymfile.swift, Matchfile.swift, Deliverfile.swift, etc) have to be declared as `public`.
- These are being correctly generated with `public` specifier, however, _fastlane_ is not upgrading existing files. So if you're generating the swift project for the first time, it will work, but for the majority of us it's not working 😅 
- I have noticed this behavior in the past to be honest, but I thought this was the desired behavior 🤔 because if you customize this file it would erase all your changes on every _fastlane_ release. I know this is kinda what it warns about, but see the next point 😄 
- Even if this re-generated the files, and you lost your changes, if you had another file declaring an instance of the function protocols (e.g. DeliverfileProtocol, MatchfileProtocol, etc), with your custom configs, you **will** have to add the `public` specific to those declarations.

Fixing the re-generation of those protocol files can be tricky, and I'm not sure if it's the right path. I'll kindly ask for @joshdholtz's advise here 🙏 

For the time being, this is how to fix this issue:

Add the `public` specifier to all these classes declarations: `Deliverfile.swift`, `Gymfile.swift`, `Matchfile.swift`, `Precheckfile.swift`, `Scanfile.swift`, `Screengrabfile.swift`, `Snapshotfile.swift`.

Then add the `public` specifier to all the variables that you are declaring in those files that belong to their respective protocols, such as e.g.:

```diff swift
/// Your Apple ID Username.
-    var username: String { return iTunesConnect.appleID }
+    public var username: String { return iTunesConnect.appleID }
```

**Comment by rogerluan** [comment] 2020-09-18 22:41
After applying those changes ☝️ it will start compiling, but it will crash any lane executed if you're not using SPM. I filed a report with more details here: #17275 

I fixed this issue here: https://github.com/fastlane/fastlane/pull/17276

If you want to test my fix, edit your `Gemfile`:

```ruby
gem "fastlane", :git => "https://github.com/rogerluan/fastlane.git", :branch => "fix-force-unwrap-crash"
```

**Comment by minuscorp** [comment] 2020-09-24 11:51
I'm unavailable right now, but there're changes to be made to the instances of those protocols, should be open instead of just public and see how Swift loads all the code from there, it's tricky. Meanwhile please bear in mind that SPM support was preliminar.

Thank you for your comprehension.

**Comment by willnix86** [comment] 2020-10-15 13:25
+1

**Comment by rogerluan** [comment] 2020-12-19 11:06
Given the age of this issue and its nature, alongside with the ease of implementation of the workaround available, I'm closing this issue. I also confirmed that it's easy to find this issue in GitHub when someone upgrades from v 2.158.x to a more recent version. If anyone feels strongly about reopening it, let me know 👍

**Closed by rogerluan** 2020-12-19 11:06 UTC
Labels: status: workaround available, topic: swift
