### ISSUE TITLE
Scan hangs on touching .xctests

### ISSUE THREAD

**Issue by mRs-** [fastlane/fastlane#5631] opened 2016-08-08 13:38 UTC
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

Sometimes my bamboo CI hangs when executing scan on touching the .xctests files. Don't know what the real problem is here :(
##### Complete output when running fastlane, including the stack trace and command used

```
08-Aug-2016 15:13:43    [15:13:43]: ▸ Compiling PriceTests.swift
08-Aug-2016 15:13:43    [15:13:43]: ▸ Linking MyProject_Tests
08-Aug-2016 15:13:43    [15:13:43]: ▸ ⚠️  ld: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/Developer/Library/Frameworks'
08-Aug-2016 15:13:43    [15:13:43]: ▸ Generating 'MyProject_tests.xctest.dSYM'
08-Aug-2016 15:13:43    [15:13:43]: ▸ Running script '[CP] Embed Pods Frameworks'
08-Aug-2016 15:13:45    [15:13:45]: ▸ Running script '[CP] Copy Pods Resources'
08-Aug-2016 15:13:45    [15:13:45]: Running Tests: ▸ Touching MyProject_tests.xctest
```
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:

``` ruby
scan \
    --workspace PATH_TO_WORKSPACE \
    --scheme MyProject-Tests \
    --xcargs "-derivedDataPath ../build" \
    --buildlog_path ../logs/scan \
    --output_directory ../test-reports \
    --device "iPhone 6s 9.3" \
    --sdk iphonesimulator \
    --code_coverage \
    -r
```
### Environment

fastlane version (run `fastlane -v`): scan 0.10.1

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? 
nope

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? 
nope

**Comment by wkoszek** [comment] 2016-08-08 20:35
@mRs- I've experienced that problem as well in my project. Similar conditions. Also unclear how to reproduce, and also happens only sometimes

**Comment by mRs-** [comment] 2016-08-09 09:10
Yeah I think the current solution is to install timeout on the bamboo and kill the process if its hung :(

**Comment by KrauseFx** [comment] 2016-08-09 18:18
Mh, do you think this is related to https://github.com/fastlane/fastlane/issues/4059?

**Comment by KrauseFx** [comment] 2016-08-09 18:18
It's super hard to work on a fix if we can't reproduce the issue

**Comment by mRs-** [comment] 2016-08-09 20:47
At this moment every 10th build is affected by this timeout problem. And it seems it is not related to #4059, because the compiling is completed at this state. It's really about touching the xctests…

**Comment by wkoszek** [comment] 2016-08-11 08:59
@KrauseFx @mRs- This is some another `xcodebuild` issue. 

I've made myself a single-command build switch for testing normal/fastlane flow.

https://github.com/wkoszek/sensorama-ios/blob/master/build.sh

So I have "normal" and "normal_test" (raw `xcodebuild`) and "fastlane" and "fastlane_test".

On my machine I when I run 3 times "normal_test", I reproduced it 2x in a row. Steps:

```
git clone https://github.com/wkoszek/sensorama-ios.git
cd sensorama-ios
./build.sh normal_tests
```

When it hangs:

```
wk              58763   0.0  0.3  2745748  27860 s005  S+    1:37AM   0:11.41 /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace Sensorama.xcworkspace -scheme SensoramaTests -sdk iphonesimulator -destination platform=iOS Simulator,name=iPhone 6 test
```

It's unclear what it's doing (I've attached to the PID with `sudo dtruss -ap 58763`):

```

	PID/THRD  RELATIVE  ELAPSD    CPU SYSCALL(args) 		 = return
58763/0xa9b1b1:     99940     183     12 workq_kernreturn(0x20, 0x0, 0x1)		 = 0 0
58763/0xaa0bd2:      1698      12      5 kevent_qos(0x3, 0x7FFF86C4D1E8, 0x1)		 = 0 0
58763/0xa9b1b1:     99961     180     16 kevent_qos(0x3, 0x0, 0x0)		 = 1 0
58763/0xa9b1b1:    100002 5890983     28 kevent_qos(0x3, 0x0, 0x0)		 = 1 0
58763/0xa9b1b1:    100027      81      6 workq_kernreturn(0x20, 0x0, 0x1)		 = 0 0
58763/0xaa0bd2:      1821      99      9 kevent_qos(0x3, 0x7FFF86C4D1E8, 0x1)		 = 0 0
58763/0xa9b1b1:    100055     208     24 kevent_qos(0x3, 0x0, 0x0)		 = 1 0
58763/0xa9b1b1:    100092 7992460     23 kevent_qos(0x3, 0x0, 0x0)		 = 1 0
58763/0xa9b1b1:    100106      80      7 workq_kernreturn(0x20, 0x0, 0x1)		 = 0 0
58763/0xaa0bd2:      1944      13      6 kevent_qos(0x3, 0x7FFF86C4D1E8, 0x1)		 = 0 0
58763/0xa9b1b1:    100125     168     15 kevent_qos(0x3, 0x0, 0x0)		 = 1 0
58763/0xa9b1b1:    100150 2073319     16 kevent_qos(0x3, 0x0, 0x0)		 = 1 0
58763/0xa9b1b1:    100163      93      6 workq_kernreturn(0x20, 0x0, 0x1)		 = 0 0
58763/0xaa0bd2:      2031      82      4 kevent_qos(0x3, 0x7FFF86C4D1E8, 0x1)		 = 0 0
58763/0xa9b1b1:    100175     159     10 kevent_qos(0x3, 0x0, 0x0)		 = 1 0
58763/0xa9b1b1:    100199 2110610     14 kevent_qos(0x3, 0x0, 0x0)		 = 1 0
58763/0xa9b1b1:    100210      80      4 workq_kernreturn(0x20, 0x0, 0x1)		 = 0 0
58763/0xaa0bd2:      2124      26      7 kevent_qos(0x3, 0x7FFF86C4D1E8, 0x1)		 = 0 0
58763/0xa9b1b1:    100223     136     10 kevent_qos(0x3, 0x0, 0x0)		 = 1 0
58763/0xa9b1b1:    100245 2074673     15 kevent_qos(0x3, 0x0, 0x0)		 = 1 0
58763/0xa9b1b1:    100257      88      6 workq_kernreturn(0x20, 0x0, 0x1)		 = 0 0
58763/0xaa0bd2:      2196      58      4 kevent_qos(0x3, 0x7FFF86C4D1E8, 0x1)		 = 0 0
58763/0xa9b1b1:    100272     121     11 kevent_qos(0x3, 0x0, 0x0)		 = 1 0
58763/0xa9b1b1:    100295 5531352     16 kevent_qos(0x3, 0x0, 0x0)		 = 1 0
58763/0xa9b1b1:    100314     107      9 workq_kernreturn(0x20, 0x0, 0x1)		 = 0 0
58763/0xaa0bd2:      2343       7      3 kevent_qos(0x3, 0x7FFF86C4D1E8, 0x1)		 = 0 0
58763/0xa9b1b1:    100338     223     17 kevent_qos(0x3, 0x0, 0x0)		 = 1 0
58763/0xa9b1b1:    100370 3909786     14 kevent_qos(0x3, 0x0, 0x0)		 = 1 0
58763/0xa9b1b1:    100381      84      5 workq_kernreturn(0x20, 0x0, 0x1)		 = 0 0
58763/0xaa0bd2:      2429       6      3 kevent_qos(0x3, 0x7FFF86C4D1E8, 0x1)		 = 0 0
58763/0xa9b1b1:    100393     105      8 kevent_qos(0x3, 0x0, 0x0)		 = 1 0
58763/0xa9b1b1:    100413 2072039     15 kevent_qos(0x3, 0x0, 0x0)		 = 1 0
58763/0xa9b1b1:    100427     120      6 workq_kernreturn(0x20, 0x0, 0x1)		 = 0 0
58763/0xaa0bd2:      2539      92      6 kevent_qos(0x3, 0x7FFF86C4D1E8, 0x1)		 = 0 0
58763/0xa9b1b1:    100441     211     11 kevent_qos(0x3, 0x0, 0x0)		 = 1 0
58763/0xa9b1b1:    100460  180455     13 kevent_qos(0x3, 0x0, 0x0)		 = 1 0
58763/0xa9b1b1:    100531      11      4 workq_kernreturn(0x20, 0x0, 0x1)		 = 0 0
58763/0xaa0bd2:      2619      81      9 read(0x28, "y[=\037 \0", 0x4000)		 = 504 0
58763/0xaa0bd2:      2758      24     19 workq_kernreturn(0x20, 0x0, 0x1)		 = 0 0
58763/0xaa0bd2:      2806       3      1 read(0x28, "\0", 0x4000)		 = -1 Err#35
58763/0xaa1024:        12       5      0 thread_selfid(0x0, 0x0, 0x0)		 = 11145252 0
58763/0xaa0bd2:      2812       5      2 kevent_qos(0x3, 0x7FC6B494BE00, 0x1)		 = 0 0
58763/0xa9d2eb:     87491       8      4 workq_kernreturn(0x20, 0x0, 0x1)		 = 0 0
58763/0xaa1024:       214       7      2 bsdthread_ctl(0x400, 0x8527, 0x10FF)		 = 0 0
58763/0xaa1024:       216       4      1 bsdthread_ctl(0x100, 0xA40008FF, 0xFFFFFFFF)		 = 0 0
58763/0xaa1024:       221       5      1 bsdthread_ctl(0x400, 0x8527, 0x1000)		 = 0 0
58763/0xaa1024:       229      69      2 bsdthread_ctl(0x400, 0x8527, 0x1000)		 = 0 0
58763/0xaa1024:       232       4      1 bsdthread_ctl(0x100, 0x10FF, 0xFFFFFFFF)		 = 0 0
58763/0xa9b1ad:   2837718      12      5 workq_kernreturn(0x20, 0x0, 0x1)		 = 0 0
58763/0xaa1024:       428       9      3 bsdthread_ctl(0x400, 0x8527, 0x10FF)		 = 0 0
58763/0xaa1024:       431       5      1 bsdthread_ctl(0x100, 0xA40008FF, 0xFFFFFFFF)		 = 0 0
58763/0xaa1024:       432       3      0 bsdthread_ctl(0x400, 0x8527, 0x1000)		 = 0 0
58763/0xaa1024:       434       3      0 bsdthread_ctl(0x100, 0x10FF, 0xFFFFFFFF)		 = 0 0
58763/0xa9b1ad:   2837804       7      3 workq_kernreturn(0x20, 0x0, 0x1)		 = 0 0
58763/0xaa0bd2:      2828       7      2 bsdthread_ctl(0x400, 0xAC27, 0x10FF)		 = 0 0
58763/0xaa0bd2:      2829       3      1 bsdthread_ctl(0x100, 0xA40008FF, 0xFFFFFFFF)		 = 0 0
58763/0xaa0bd2:      2830       3      0 bsdthread_ctl(0x400, 0xAC27, 0x1000)		 = 0 0
58763/0xaa0bd2:      2832       3      0 bsdthread_ctl(0x100, 0x10FF, 0xFFFFFFFF)		 = 0 0
58763/0xaa0bd2:      2871      16     12 write(0x28, "y[=\037 \0", 0x20)		 = 32 0
58763/0xaa0bd2:      2876       6      3 write(0x28, "\0", 0x10)		 = 16 0
58763/0xaa0bd2:      2879       4      1 write(0x28, "\0", 0x0)		 = 0 0
58763/0xa9b1ad:   2838543     150     12 workq_kernreturn(0x20, 0x0, 0x1)		 = 0 0
58763/0xaa1024:      1150     148     15 bsdthread_ctl(0x400, 0x8527, 0x10FF)		 = 0 0
58763/0xaa1024:      1155       8      3 bsdthread_ctl(0x100, 0xA40008FF, 0xFFFFFFFF)		 = 0 0
58763/0xaa1024:      1157       5      1 bsdthread_ctl(0x400, 0x8527, 0x1000)		 = 0 0
58763/0xaa1024:      1160       5      1 bsdthread_ctl(0x100, 0x10FF, 0xFFFFFFFF)		 = 0 0
58763/0xaa1024:      2435    2080    134 write(0x1F, "01:51:04.439 xcodebuild[58763:11145252] (LOG ARBITER) Rotating message buffer with 1 messages.\n\0", 0x5F)		 = 95 0
58763/0xa9b1b1:    100552 4425596     17 kevent_qos(0x3, 0x0, 0x0)		 = 1 0
58763/0xa9b1b1:    100564      75      6 workq_kernreturn(0x20, 0x0, 0x1)		 = 0 0
58763/0xaa1024:      2634       7      3 kevent_qos(0x3, 0x7FFF86C4D1E8, 0x1)		 = 0 0
58763/0xa9b1b1:    100575     100      8 kevent_qos(0x3, 0x0, 0x0)		 = 1 0
58763/0xa9b1b1:    100594 2073230     14 kevent_qos(0x3, 0x0, 0x0)		 = 1 0
58763/0xa9b1b1:    100615     111      5 workq_kernreturn(0x20, 0x0, 0x1)		 = 0 0
58763/0xaa1024:      2724      14      7 kevent_qos(0x3, 0x7FFF86C4D1E8, 0x1)		 = 0 0
58763/0xa9b1b1:    100634     130     16 kevent_qos(0x3, 0x0, 0x0)		 = 1 0
58763/0xa9b1b1:    100660 2576381     17 kevent_qos(0x3, 0x0, 0x0)		 = 1 0
58763/0xa9b1b1:    100669      75      4 workq_kernreturn(0x20, 0x0, 0x1)		 = 0 0
58763/0xaa1024:      2801       7      3 kevent_qos(0x3, 0x7FFF86C4D1E8, 0x1)		 = 0 0
58763/0xa9b1b1:    100681     103      9 kevent_qos(0x3, 0x0, 0x0)		 = 1 0
58763/0xaa0bd2:      2944 10000106     14 workq_kernreturn(0x4, 0x0, 0x0)		 = 0 0
58763/0xaa0bd2:      2952     112      3 __disable_threadsignal(0x1, 0x0, 0x0)		 = 0 0
dtrace: error on enabled probe ID 2199 (ID 916: syscall::thread_selfid:return): invalid user access in action #5 at DIF offset 0
58763/0xaa1024:      2811 9948640      7 workq_kernreturn(0x4, 0x0, 0x0)		 = 0 0
58763/0xaa1024:      2814      73      0 __disable_threadsignal(0x1, 0x0, 0x0)		 = 0 0
61354/0xaa10ab:        18   14355 18446744073706518 thread_selfid(0x7000006BA000, 0x83000, 0x8527)		 = 11145387 0
```

I'd tried sending it `SIGCONT` just to see if it'd wake up - no luck. I also went into derived data folder and I've touched all `.xctest` files. No luck.

**Comment by TKBurner** [comment] 2016-08-11 20:25
Hi @mRs-, when running on CI's we have a few suggestions, can you make sure all simulators are fully killed on the CI before running your lane, also if Xcode is installed on the machine can you close it. Usually these are the cause of intermittent issues like the one you are seeing. Thanks!

**Comment by nikolaykasyanov** [comment] 2016-08-15 10:32
@TKBurner it means that it's impossible to run, for example, an integration build and an ad-hoc build simultaneously, and that CI effectively becomes capable of only one job at a time, am I right?

**Comment by TKBurner** [comment] 2016-08-22 16:06
@nikolaykasyanov Thanks for following up. What are you trying to run simultaneously? Thanks!

**Comment by nikolaykasyanov** [comment] 2016-08-23 12:30
@TKBurner I may want to start an ad-hoc build while some intergration/test build (one using iOS Simulator) is running.

**Comment by TKBurner** [comment] 2016-08-23 21:24
@nikolaykasyanov Can you add the --verbose flag, so I can take a look at what is happening again? Thanks so much!

**Comment by nikolaykasyanov** [comment] 2016-08-24 19:41
@TKBurner as far as I can see from the discussion, it was suggested to make sure that all simulators are killed prior to starting a lane (https://github.com/fastlane/fastlane/issues/5631#issuecomment-239281062). Hence my concern about running multiple lanes simultaneously.

**Comment by TKBurner** [comment] 2016-08-26 16:02
@nikolaykasyanov Yup. I was just curious to see what exactly happens on your end when you do this. Thanks!

**Comment by pawelus** [comment] 2016-08-30 12:10
@TKBurner I have a Bamboo build agent with 100% reproduction rate ATM.

I've ran `bundle exec sync --verbose` but it doesn't say much:
```
30-Aug-2016 12:09:37	INFO [2016-08-30 12:09:37.87]: Running Tests: ▸ Touching IcetUITests.xctest
30-Aug-2016 12:09:44	INFO [2016-08-30 12:09:44.92]: ▸ 2016-08-30 12:09:44.921:INFO::Logging to STDERR via wiremock.org.mortbay.log.StdErrLog
```
A bunch of things I checked that may help:
* Second line is from my Pre-action for Test - this means that pre-action was run correctly
* Application is launched on the simulator screen (I can see it on the agent) but no Unit or UI tests are run - it just hangs there
* I have a second Bamboo agent with the same software configuration but better hardware (compilation times 2x faster) where this doesn't reproduce so this is for sure related to agent performance

**Comment by TKBurner** [comment] 2016-08-31 18:50
@pawelus Are you running multiple simulators? What happens if you erase your simulators before you run scan? Thanks!

**Comment by pawelus** [comment] 2016-09-01 08:52
@TKBurner All builds are using the same simulator (iPhone 5s - 9.3) and we kill and restart the simulator before we run fastlane with:
```bash
killall -m -KILL "iOS Simulator"
killall -m -KILL "Xcode"
killall -m -KILL "com.apple.CoreSimulator.CoreSimulatorService"
killall "Simulator"
xcrun instruments -s devices | grep 'iPhone 5s' | tail -n 1 | xargs -0 xcrun instruments -t 'Blank' -l 1 -D ~/simulator.trace -w
```

I have restarted that Bamboo agent yesterday and the problem disappeared. This makes me think that it might be some sort of a timeout issue related to deteriorating agent performance.

**Comment by TKBurner** [comment] 2016-09-02 14:52
@pawelus Thanks for following up. Very interesting. I'm going to leave this open to see if you run into it again. Thanks!

**Comment by pawelus** [comment] 2016-09-05 12:32
@TKBurner it didn't take long for the problem to reappear.

I've erased and recreated all simulators before build using:
```
fastlane snapshot reset_simulators
```
but it didn't help. Build still hangs exactly as before.

**Comment by pawelus** [comment] 2016-09-05 14:23
@TKBurner I have noticed that our second project doesn't hang on that agent so I compared their scanfiles.

Scanfile for the failing project:

```
scheme "project1"
output_types "junit"
device "iPhone 5s (9.3)"
code_coverage true
derived_data_path "build"
custom_report_file_name "report.xml"
configuration "Localhost"
clean false
skip_build true
```

Scanfile for the project that doesn't fail:
```
scheme "project2"
device "iPhone 5s (9.3)"
code_coverage true
derived_data_path "build"
custom_report_file_name "report.xml"
skip_build true
```

Main difference is that the failing project is using 'Localhost' configuration (which is based on 'Debug') while the non-failing one is using 'Debug'.

Second difference is that the failing one is running both Unit and UI Tests while the non-failing one has only Unit tests (1 test bundle instead of 2 for the scheme).

Also the non-failing project is significantly smaller (in terms of code and test amounts) than the failing one.

Hope this helps!

**Comment by mRs-** [comment] 2016-09-07 06:04
Newest input from me here. This seems not a problem from scan. Just right now I got the same issue directly in Xcode. It's hanging right at the touch .xctest. Don't know exactly why.

I cleaned my build folder and it's working again like a charm. Maybe we need to clean the project before?

**Comment by TKBurner** [comment] 2016-09-08 15:52
@mRs- Thanks! Anyone that is still affected, please clean your project and run `sudo gem update fastlane`. A new version of scan was released about an hour ago. Thanks!

**Comment by pawelus** [comment] 2016-09-15 12:01
@TKBurner unfortunately update to the latest scan version didn't help

**Comment by TKBurner** [comment] 2016-09-22 15:48
@pawelus So sorry for the delay in getting back to you. Can you share your full input and output? I want to see if this is an issue with the tool chain, the inputs or something else. I really want to get to the bottom of this.

**Comment by mRs-** [comment] 2016-11-21 16:47
Still broken sometimes. 

Von meinem iPhone gesendet

**Closed** 2017-02-07 17:03 UTC
Labels: auto-closed, awaiting-reply, scan, waiting-for-reply
