### ISSUE TITLE
Listing provisioning profiles in spaceship is broken

### ISSUE THREAD

**Issue by congt** [fastlane/fastlane#20060] opened 2022-03-15 00:06 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

It fails when I use "Spaceship.provisioning_profile.all" to list all provisioning profiles. The resultString is "Please update to Xcode 7.3 or later to continue developing with your Apple ID."

##### Command executed

Spaceship.provisioning_profile.all

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>/Users/cshi/.rvm/gems/ruby-2.7.4/gems/fastlane-2.204.3/spaceship/lib/spaceship/client.rb:783:in `parse_response': {"responseId"=>"7f553a6f-eebb-4169-90ac-638bd21e059f", "resultCode"=>3018, "resultString"=>"Please update to Xcode 7.3 or later to continue developing with your Apple ID.", "userString"=>"Please update to Xcode 7.3 or later to continue developing with your Apple ID.", "creationTimestamp"=>"2022-03-14T23:47:32Z", "protocolVersion"=>"QH65B2", "userLocale"=>"en_US", "requestUrl"=>"https://developerservices2.apple.com/services/QH65B2/ios/listProvisioningProfiles.action", "httpCode"=>200} (Spaceship::UnexpectedResponse)
Traceback (most recent call last):      
         3: from /Users/congt/Development/ios/lib/adc_account_manager.rb:56:in `find_or_create_provisioning_profile'
 	 2: from /Users/cshi/.rvm/gems/ruby-2.7.4/gems/fastlane-2.204.3/spaceship/lib/spaceship/portal/provisioning_profile.rb:319:in `all'
	 1: from /Users/cshi/.rvm/gems/ruby-2.7.4/gems/fastlane-2.204.3/spaceship/lib/spaceship/portal/portal_client.rb:669:in `provisioning_profiles_via_xcode_api'
/Users/cshi/.rvm/gems/ruby-2.7.4/gems/fastlane-2.204.3/spaceship/lib/spaceship/client.rb:783:in `parse_response': {"responseId"=>"7f553a6f-eebb-4169-90ac-638bd21e059f", "resultCode"=>3018, "resultString"=>"Please update to Xcode 7.3 or later to continue developing with your Apple ID.", "userString"=>"Please update to Xcode 7.3 or later to continue developing with your Apple ID.", "creationTimestamp"=>"2022-03-14T23:47:32Z", "protocolVersion"=>"QH65B2", "userLocale"=>"en_US", "requestUrl"=>"https://developerservices2.apple.com/services/QH65B2/ios/listProvisioningProfiles.action", "httpCode"=>200} (Spaceship::UnexpectedResponse)</pre>
</details>

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 12.2.1                                      |
| Ruby                        | 2.7.4                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.35.1                          |
| Installation Source         | ~/.rvm/gems/ruby-2.7.4/bin/fastlane         |
| Host                        | macOS 12.2.1 (21D62)                        |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.7.4/lib                |
| OpenSSL Version             | OpenSSL 1.1.1m  14 Dec 2021                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 13.2.1                                      |
| Swift Version               | 5.5.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.204.3 | ✅ Up-To-Date  |
| trainer  | 0.9.1   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                                           | Version      |
| --------------------------------------------- | ------------ |
| did_you_mean                                  | 1.4.0        |
| bundler                                       | 2.2.29       |
| uri                                           | 0.10.0       |
| rake                                          | 13.0.6       |
| rexml                                         | 3.2.5        |
| CFPropertyList                                | 3.0.5        |
| concurrent-ruby                               | 1.1.9        |
| i18n                                          | 1.10.0       |
| minitest                                      | 5.15.0       |
| tzinfo                                        | 2.0.4        |
| zeitwerk                                      | 2.5.4        |
| activesupport                                 | 6.1.4.7      |
| public_suffix                                 | 4.0.6        |
| addressable                                   | 2.8.0        |
| httpclient                                    | 2.8.3        |
| json                                          | 2.6.1        |
| algoliasearch                                 | 1.27.5       |
| artifactory                                   | 3.0.15       |
| ast                                           | 2.4.1        |
| jwt                                           | 2.1.0        |
| atlassian-jwt                                 | 0.2.0        |
| atomos                                        | 0.1.3        |
| aws-eventstream                               | 1.2.0        |
| aws-partitions                                | 1.567.0      |
| aws-sigv4                                     | 1.4.0        |
| jmespath                                      | 1.6.1        |
| aws-sdk-core                                  | 3.130.0      |
| aws-sdk-kms                                   | 1.55.0       |
| aws-sdk-lambda                                | 1.57.0       |
| aws-sdk-s3                                    | 1.113.0      |
| babosa                                        | 1.0.4        |
| benchmark-ips                                 | 2.7.2        |
| unf_ext                                       | 0.0.8.1      |
| unf                                           | 0.1.4        |
| domain_name                                   | 0.5.20190701 |
| http-cookie                                   | 1.0.4        |
| http-form_data                                | 2.3.0        |
| ffi                                           | 1.15.5       |
| ffi-compiler                                  | 1.0.1        |
| llhttp-ffi                                    | 0.4.0        |
| http                                          | 5.0.4        |
| msgpack                                       | 1.4.3        |
| corefoundation                                | 0.2.0        |
| ruby-keychain                                 | 0.3.2        |
| slop                                          | 4.9.1        |
| beyondclient                                  | 1.3.1        |
| build_execution                               | 1.4.0        |
| builder                                       | 3.2.4        |
| claide                                        | 1.1.0        |
| chronometer                                   | 0.2.0        |
| fuzzy_match                                   | 2.0.4        |
| nap                                           | 1.1.0        |
| netrc                                         | 0.11.0       |
| ethon                                         | 0.15.0       |
| typhoeus                                      | 1.4.0        |
| cocoapods-core                                | 1.11.2       |
| cocoapods-deintegrate                         | 1.0.5        |
| cocoapods-downloader                          | 1.5.1        |
| cocoapods-plugins                             | 1.0.0        |
| cocoapods-search                              | 1.0.1        |
| cocoapods-trunk                               | 1.6.0        |
| cocoapods-try                                 | 1.2.0        |
| colored2                                      | 3.1.2        |
| escape                                        | 0.0.4        |
| fourflusher                                   | 2.3.1        |
| gh_inspector                                  | 1.1.3        |
| molinillo                                     | 0.8.0        |
| ruby-macho                                    | 2.5.1        |
| nanaimo                                       | 0.3.0        |
| xcodeproj                                     | 1.21.0       |
| cocoapods                                     | 1.11.2       |
| cocoapods-amicable                            | 0.3.0        |
| cocoapods-atlas                               | 0.5.0        |
| starlark_compiler                             | 0.4.0        |
| cocoapods-bazel                               | 0.1.3        |
| cocoapods-check                               | 1.1.0        |
| ruby-graphviz                                 | 1.2.5        |
| cocoapods-dependencies                        | 1.3.0        |
| cocoapods-disable-podfile-validations         | 0.1.1        |
| cocoapods-fmwk                                | 1.0.0.LOCAL  |
| cocoapods-generate                            | 2.2.2        |
| cocoapods-mix-frameworks                      | 0.1.1        |
| cocoapods-query                               | 1.0.1        |
| device_parser                                 | 1.1.11       |
| eventstream-client                            | 2.0.4        |
| cocoapods-sq-command-metrics                  | 0.6.0        |
| cocoapods-sq-concise-lockfile                 | 1.0.0.LOCAL  |
| cocoapods-sq-local-development                | 1.0.0.LOCAL  |
| cocoapods-sq-log-installs                     | 1.0.0.LOCAL  |
| cocoapods-sq-modify-generate-lockfile         | 1.0.0.LOCAL  |
| cocoapods-sq-modify-info-plist                | 0.0.1        |
| cocoapods-sq-modify-test-specs                | 1.0.0.LOCAL  |
| cocoapods-sq-modify-xcschemes                 | 1.0.0.LOCAL  |
| cocoapods-sq-module-structure                 | 1.0.0.LOCAL  |
| cocoapods-sq-non-swift-devapp-swift-debugging | 1.0.0.LOCAL  |
| cocoapods-sq-ponycode                         | 1.0.0.LOCAL  |
| cocoapods-sq-short-ld-flags                   | 1.0.0.LOCAL  |
| lazy_priority_queue                           | 0.1.1        |
| generator                                     | 0.0.1        |
| stream                                        | 0.5.3        |
| rgl                                           | 0.5.7        |
| cocoapods-why                                 | 1.2          |
| coderay                                       | 1.1.3        |
| colored                                       | 1.2          |
| highline                                      | 2.0.3        |
| commander                                     | 4.6.0        |
| date                                          | 3.1.1        |
| declarative                                   | 0.0.20       |
| diff-lcs                                      | 1.4.4        |
| digest-crc                                    | 0.6.4        |
| dotenv                                        | 2.7.6        |
| emoji_regex                                   | 3.2.3        |
| ensure-encoding                               | 0.1          |
| excon                                         | 0.92.0       |
| fakefs                                        | 0.20.1       |
| faraday-em_http                               | 1.0.0        |
| faraday-em_synchrony                          | 1.0.0        |
| faraday-excon                                 | 1.1.0        |
| faraday-httpclient                            | 1.0.1        |
| multipart-post                                | 2.0.0        |
| faraday-multipart                             | 1.0.3        |
| faraday-net_http                              | 1.0.1        |
| faraday-net_http_persistent                   | 1.2.0        |
| faraday-patron                                | 1.0.0        |
| faraday-rack                                  | 1.0.0        |
| faraday-retry                                 | 1.0.3        |
| ruby2_keywords                                | 0.0.5        |
| faraday                                       | 1.10.0       |
| faraday-cookie_jar                            | 0.0.7        |
| faraday_middleware                            | 1.2.0        |
| fastimage                                     | 2.2.6        |
| memoist                                       | 0.16.2       |
| multi_json                                    | 1.15.0       |
| os                                            | 1.1.4        |
| signet                                        | 0.16.1       |
| googleauth                                    | 1.1.2        |
| mini_mime                                     | 1.1.2        |
| trailblazer-option                            | 0.1.2        |
| uber                                          | 0.1.0        |
| representable                                 | 3.1.1        |
| retriable                                     | 3.1.2        |
| webrick                                       | 1.7.0        |
| google-apis-core                              | 0.4.2        |
| google-apis-androidpublisher_v3               | 0.16.0       |
| google-apis-playcustomapp_v1                  | 0.7.0        |
| google-apis-iamcredentials_v1                 | 0.10.0       |
| google-apis-storage_v1                        | 0.11.0       |
| google-cloud-env                              | 1.5.0        |
| google-cloud-errors                           | 1.2.0        |
| google-cloud-core                             | 1.6.0        |
| google-cloud-storage                          | 1.36.1       |
| mini_magick                                   | 4.11.0       |
| naturally                                     | 2.2.1        |
| optparse                                      | 0.1.1        |
| plist                                         | 3.6.0        |
| rubyzip                                       | 2.3.2        |
| security                                      | 0.1.3        |
| simctl                                        | 1.6.8        |
| terminal-notifier                             | 2.0.0        |
| unicode-display_width                         | 1.4.1        |
| terminal-table                                | 1.8.0        |
| tty-screen                                    | 0.8.1        |
| tty-cursor                                    | 0.7.1        |
| tty-spinner                                   | 0.9.3        |
| word_wrap                                     | 1.0.0        |
| rouge                                         | 2.0.7        |
| xcpretty                                      | 0.3.0        |
| xcpretty-travis-formatter                     | 1.0.1        |
| hashdiff                                      | 1.0.1        |
| http-accept                                   | 1.7.0        |
| iniparse                                      | 1.5.0        |
| ios_simulator_util                            | 1.13.0       |
| jaro_winkler                                  | 1.5.4        |
| mustache                                      | 1.1.1        |
| open4                                         | 1.3.4        |
| redcarpet                                     | 3.5.1        |
| sassc                                         | 2.4.0        |
| sqlite3                                       | 1.4.2        |
| liferaft                                      | 0.0.6        |
| xcinvoke                                      | 0.3.0        |
| jazzy                                         | 0.13.6       |
| oauth                                         | 0.5.4        |
| jira-ruby                                     | 2.1.4        |
| method_source                                 | 1.0.0        |
| middleware                                    | 0.1.0        |
| mime-types-data                               | 3.2021.0704  |
| mime-types                                    | 3.3.1        |
| sawyer                                        | 0.8.2        |
| octokit                                       | 4.21.0       |
| parallel                                      | 1.12.1       |
| parser                                        | 3.0.0.0      |
| tty-color                                     | 0.6.0        |
| pastel                                        | 0.8.0        |
| powerpack                                     | 0.1.3        |
| thor                                          | 1.2.1        |
| thread_safe                                   | 0.3.6        |
| protobuf                                      | 3.8.5        |
| pry                                           | 0.13.1       |
| psych                                         | 3.3.0        |
| rainbow                                       | 3.0.0        |
| rangeclient                                   | 0.0.18       |
| refinement                                    | 0.5.0        |
| rest-client                                   | 2.1.0        |
| rlib                                          | 1.0.0.LOCAL  |
| rspec-support                                 | 3.10.3       |
| rspec-core                                    | 3.10.1       |
| rspec-expectations                            | 3.10.1       |
| rspec-mocks                                   | 3.10.1       |
| rspec                                         | 3.10.0       |
| rspec_junit_formatter                         | 0.4.1        |
| ruby-progressbar                              | 1.11.0       |
| rubocop                                       | 0.65.0       |
| rubocop-junit-formatter                       | 0.1.4        |
| structured_warnings                           | 0.4.0        |
| rubytree                                      | 1.0.0        |
| sq-gem_tasks                                  | 1.8.1        |
| sq-githubapp-client                           | 0.6.2        |
| sq-hubkins-yml-helper                         | 0.1.1        |
| sq-ios_default_xcconfig                       | 0.3.9        |
| sq-mobuild-curl                               | 0.7.0        |
| tty-command                                   | 0.10.0       |
| wisper                                        | 2.0.1        |
| tty-reader                                    | 0.9.0        |
| tty-prompt                                    | 0.23.0       |
</details>

*generated on:* **2022-03-14**
</details></pre>
</details>

**Comment by yugu91** [comment] 2022-03-15 07:44
Same to me

**Comment by wecail** [comment] 2022-03-15 08:12
also happend, when could this issue be fixed?

**Comment by agratoth** [comment] 2022-03-15 10:52
Same problem. Is there a solution?

**Comment by lucgrabowski** [comment] 2022-03-15 12:23
The error that you can see is returned by Apple's server. Could you check the response when using newer API: 
 `Spaceship::ConnectAPI::Profile.all`
 or
 `Spaceship::ConnectAPI::Profile.all(includes: "bundleIds,certificates")`
depending on the information that you want to fetch?

**Comment by agratoth** [comment] 2022-03-15 12:59
> The error that you can see is returned by Apple's server. Could you check the response when using newer API: `Spaceship::ConnectAPI::Profile.all` or `Spaceship::ConnectAPI::Profile.all(includes: "bundleIds,certificates")` depending on the information that you want to fetch?

`[2] pry(#<Spaceship::Playground>)> Spaceship::ConnectAPI::Profile.all
=> []
[3] pry(#<Spaceship::Playground>)> Spaceship::ConnectAPI::Profile.all(includes: "bundleIds,certificates")
Spaceship::UnexpectedResponse: {
  "errors" : [ {
    "id" : "9b40bbec-6433-4ab9-8dff-1596b33ae673",
    "status" : "400",
    "code" : "PARAMETER_ERROR.INVALID",
    "title" : "A parameter has an invalid value",
    "detail" : "A parameter 'include' has an invalid value : ''bundleIds' does not exist.'",
    "source" : {
      "parameter" : "include"
    }
  } ]
}
from /var/lib/gems/2.5.0/gems/fastlane-2.204.3/spaceship/lib/spaceship/connect_api/api_client.rb:194:in `handle_response'
[4] pry(#<Spaceship::Playground>)> 
`

**Comment by lucgrabowski** [comment] 2022-03-15 13:09
Wrong name in includes ;) 
`Spaceship::ConnectAPI::Profile.all(includes: "bundleId,certificates")`
You don't have to fetch bundleId and/or certificates if you don't need them. In such case you can execute `Spaceship::ConnectAPI::Profile.all`

**Comment by thiagohmcruz** [comment] 2022-03-15 15:23
cc @lucgrabowski  are you aware of any migration guide available if we change to the new API? I assume the old vs new models are not interchangeable right? 

For example, I get this error when downloading using the new API:
```
NoMethodError: undefined method `certificate_valid?' for #<Spaceship::ConnectAPI::Profile:0x00007fa4794069b8>
```

So IIUC we have two options:

1. Migrate code everywhere to use `Spaceship::ConnectAPI::Profile` API (is there a guide?)
2. Factor `Spaceship::Portal::ProvisioningProfile` from `Spaceship::ConnectAPI::Profile` so old code continue sto work (assuming there's a way to do that and that is the recommended approach?)

**Comment by sunnyltao** [comment] 2022-03-16 02:28
Same problem here. find_by_bundle_id method doesn't work,Does anyone know of any way to replace this method(find_by_bundle_id)?

**Comment by yugu91** [comment] 2022-03-16 03:54
> Wrong name in includes ;)
> `Spaceship::ConnectAPI::Profile.all(includes: "bundleId,certificates")`
> You don't have to fetch bundleId and/or certificates if you don't need them. In such case you can execute `Spaceship::ConnectAPI::Profile.all`

I try to use ConnectAPI it’s work but not better then Portal, Any body know about the Portal deprecated message?

**Comment by yugu91** [comment] 2022-03-16 07:30
I read the Spaceship guide, It sad 
`Set https://github.com/fastlane/fastlane/pull/8359 to use the Apple Developer Portal API instead of the Xcode API. (You probably want the Xcode API unless you have a reason not to.)`

So, You can change to AppleDevelpper API that fix:
` export SPACESHIP_AVOID_XCODE_API = false`

[https://github.com/fastlane/fastlane/blob/e874a47c6e2e0e61590a03d3b71e75e5a505d1ce/spaceship/docs/Debugging.md](url)

**Comment by lucgrabowski** [comment] 2022-03-16 21:47
I cannot reproduce the issue - I checked those spaceship calls and I didn't get the same error.
@thiagohmcruz I'm not aware of any migration guide. Old and new api are not interchangeable.

**Comment by thiagohmcruz** [comment] 2022-03-17 16:14
FYI Setting "SPACESHIP_AVOID_XCODE_API" works around the issue for us, still not clear what is causing this though. 

We'll migrate to the new API anyways, hopefully the workaround continues to work for some time...

**Comment by joshdholtz** [comment] 2022-03-18 21:45
> cc @lucgrabowski are you aware of any migration guide available if we change to the new API? I assume the old vs new models are not interchangeable right?
> 
> For example, I get this error when downloading using the new API:
> 
> ```
> NoMethodError: undefined method `certificate_valid?' for #<Spaceship::ConnectAPI::Profile:0x00007fa4794069b8>
> ```
> 
> So IIUC we have two options:
> 
> 1. Migrate code everywhere to use `Spaceship::ConnectAPI::Profile` API (is there a guide?)
> 2. Factor `Spaceship::Portal::ProvisioningProfile` from `Spaceship::ConnectAPI::Profile` so old code continues to work (assuming there's a way to do that and that is the recommended approach?)

Hello, all! Just wanted to chime in here 😊 

It is recommended to switch over to `Spaceship::ConnectAPI::Profile` if you can. The things in `Spaceship::ConnectAPI` are using the same endpoints that developer.apple.com uses these days.

`Spaceship.provisioning_profile.all` uses legacy APIs that will most likely get pulled at some point.

As for a migration guide, we sadly do not really have a one 😔 There has been so much other work that had to take precedence. The best spot to go look is probably here - https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/connect_api/models/profile.rb

Or how they get used in `sigh` - https://github.com/fastlane/fastlane/blob/master/sigh/lib/sigh/runner.rb

Hopefully this helps but let me know if you have any specifics questions and I can try to help answer!

**Comment by SWING1993** [comment] 2022-03-22 08:43
Same to me

**Comment by SunSoul** [comment] 2022-03-22 08:53
I hope my solution can help you !
i update the api get profile.
old:
downloadProfiles = Array.new
downloadProfiles += Spaceship.provisioning_profile.development.all
p.download
new:
profile_type = Spaceship::ConnectAPI::Profile::ProfileType::IOS_APP_DEVELOPMENT
downloadProfiles = Spaceship::ConnectAPI::Profile.all(filter: { profileType: profile_type }, includes: nil)
content = Base64.decode64(p.profile_content)

**Comment by thiagohmcruz** [comment] 2022-03-22 12:23
Thx for clarifying and for linking to relevant code @joshdholtz!

**Comment by lpusok** [comment] 2022-03-22 12:51
Would `Spaceship::ConnectAPI::Profile` work with Enterprise (non App Store) accounts too @joshdholtz ?

**Comment by lucgrabowski** [comment] 2022-03-23 05:02
> Would `Spaceship::ConnectAPI::Profile` work with Enterprise (non App Store) accounts too (using username+password login) @joshdholtz ?

It will also work with Enterprise account. You can give it a try in playgrounds:
Execute `fastlane spaceship` in terminal, login to your account. If you need you can choose a team with:
`Spaceship::ConnectAPI.select_team`
And later you can try fetching profiles:
`profiles = Spaceship::ConnectAPI::Profile.all`

It seems that `pry` gem needs to be installed to be able to use playgrounds (as written in https://github.com/fastlane/fastlane/blob/master/spaceship/README.md#playground)

**Comment by SunSoul** [comment] 2022-03-28 10:06
I hope my solution can help you !
i update the api get profile.
old:
downloadProfiles = Array.new
downloadProfiles += Spaceship.provisioning_profile.development.all
p.download
new:
profile_type = Spaceship::ConnectAPI::Profile::ProfileType::IOS_APP_DEVELOPMENT
downloadProfiles = Spaceship::ConnectAPI::Profile.all(filter: { profileType: profile_type }, includes: nil)
content = Base64.decode64(p.profile_content)

but i get a new problem, when i register a new device, now i can't find how to update the profile.
i just do it to update the profile before :
#profiles = Array.new
#profiles += Spaceship.provisioning_profile.development.all
#profiles += Spaceship.provisioning_profile.ad_hoc.all
#profiles.each do |p|
#    puts "Updating #{p.name}"
#    p.devices = devices
#    p.update!
#end

[models](https://github.com/fastlane/fastlane/tree/master/spaceship/lib/spaceship/connect_api/models)/profile.rb

**Comment by yugu91** [comment] 2022-03-28 11:56
> I hope my solution can help you ! i update the api get profile. old: downloadProfiles = Array.new downloadProfiles += Spaceship.provisioning_profile.development.all p.download new: profile_type = Spaceship::ConnectAPI::Profile::ProfileType::IOS_APP_DEVELOPMENT downloadProfiles = Spaceship::ConnectAPI::Profile.all(filter: { profileType: profile_type }, includes: nil) content = Base64.decode64(p.profile_content)
> 
> but i get a new problem, when i register a new device, now i can't find how to update the profile. i just do it to update the profile before : profiles = Array.new profiles += Spaceship.provisioning_profile.development.all profiles += Spaceship.provisioning_profile.ad_hoc.all profiles.each do |p| puts "Updating #{p.name}" p.devices = devices p.update! end
> 
> [models](https://github.com/fastlane/fastlane/tree/master/spaceship/lib/spaceship/connect_api/models)/profile.rb

Yes, You must delete first before create.

**Comment by SunSoul** [comment] 2022-03-29 01:48
> 

Yes, now after register a new device, i delete the old profile, then create a new one and download it for use.

**Comment by SunSoul** [comment] 2022-03-29 01:52
> > 我希望我的解决方案可以帮助你！我更新了api获取配置文件。old： downloadProfiles = Array.new downloadProfiles += Spaceship.provisioning_profile.development.all p.download new： profile_type = Spaceship：：ConnectAPI：:P rofile：:P rofileType：：IOS_APP_DEVELOPMENT downloadProfiles = Spaceship：：ConnectAPI：:P rofile.all（filter： { profileType： profile_type }， include： nil） content = Base64.decode64（p.profile_content）
> > 但是我遇到了一个新问题，当我注册新设备时，现在我找不到如何更新配置文件。我只是这样做来更新之前的配置文件：配置文件 = Array.new 配置文件 += Spaceship.provisioning_profile.development.all 配置文件 += Spaceship.provisioning_profile.ad_hoc.all 配置文件。每个都执行 |p|将"更新 #{p.name}"p.devices = devices p.update！结束
> > [models](https://github.com/fastlane/fastlane/tree/master/spaceship/lib/spaceship/connect_api/models)/profile.rb
> 
> 是的，在创建之前必须先删除。

Yes, now after register a new device, i delete the old profile, then create a new one and download it for use.

**Comment by SunSoul** [comment] 2022-03-29 02:56
> > I hope my solution can help you ! i update the api get profile. old: downloadProfiles = Array.new downloadProfiles += Spaceship.provisioning_profile.development.all p.download new: profile_type = Spaceship::ConnectAPI::Profile::ProfileType::IOS_APP_DEVELOPMENT downloadProfiles = Spaceship::ConnectAPI::Profile.all(filter: { profileType: profile_type }, includes: nil) content = Base64.decode64(p.profile_content)
> > but i get a new problem, when i register a new device, now i can't find how to update the profile. i just do it to update the profile before : profiles = Array.new profiles += Spaceship.provisioning_profile.development.all profiles += Spaceship.provisioning_profile.ad_hoc.all profiles.each do |p| puts "Updating #{p.name}" p.devices = devices p.update! end
> > [models](https://github.com/fastlane/fastlane/tree/master/spaceship/lib/spaceship/connect_api/models)/profile.rb
> 
> Yes, You must delete first before create.

Yes, now after register a new device, i delete the old profile, then create a new one and download it for use.

**Comment by CliffAgius** [comment] 2022-03-30 11:15
Any news on a fix for this as it seems this issue is breaking builds in other services like AppCenter and VisualStudio as well.  At least when I am asking about fixes over there they are pointing me here so interested if this is being worked on as it looks like there is a possible solution given above.

**Comment by IsaacDempsey** [comment] 2022-04-05 19:06
@joshdholtz It seems like the older `Spaceship.provisioning_profile` is better documented and more suited for the end user than then newer `Spaceship::ConnectAPI::Profile`. For example, the old method [create!](https://github.com/fastlane/fastlane/blob/acb7d84e7ac068e424da231c2eca39fe2ec7297d/spaceship/lib/spaceship/portal/provisioning_profile.rb#L260) has some handling for missing parameters and will populate missing devices for developer profiles etc. The newer method [create](https://github.com/fastlane/fastlane/blob/acb7d84e7ac068e424da231c2eca39fe2ec7297d/spaceship/lib/spaceship/connect_api/models/profile.rb#L74) is a bit bare bones and doesn't have any documentation. Is there any plan to integrate the new `Spaceship::ConnectAPI` framework into the older method?

**Comment by codemonkey85** [comment] 2022-05-09 21:44
If this really is the issue behind Visual Studio being unable to sync Apple development profiles, I can’t understand how it isn’t getting more attention.

**Comment by haukepribnow** [comment] 2022-05-30 19:08
As a month is almost over since the fastlane-bot got here, let me confirm: The problem still exists. The Xcode API endpoint must have changed somehow.

**Closed** 2022-09-08 17:32 UTC
Labels: status: waiting-for-reply
