### ISSUE TITLE
[Regression] match nuke breaks existing git repo

### ISSUE THREAD

**Issue by Sega-Zero** [fastlane/fastlane#13529] opened 2018-10-12 21:46 UTC
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: `2.106.1`
- Last working version: `2.105.2`

### Regression Description
After running fastlane nuke distribution I got totally broken git repo. Match cannot accept the repo password. Not sure if this related to the problem, but by looking to commit diff, I saw a p12 file now starts with `-----BEGIN RSA PRIVATE KEY-----`.

##### Complete output when running fastlane, including the stack trace and command used

```ruby
[13:30:07]: -------------------
[13:30:07]: --- Step: match ---
[13:30:07]: -------------------

+-----------------------+----------------------------------------------+
|                      Summary for match 2.106.1                       |
+-----------------------+----------------------------------------------+
| git_branch            | master                                       |
| type                  | adhoc                                        |
| app_identifier        | ["com.app.id"]       |
| force_for_new_devices | true                                         |
| force                 | true                                         |
| clone_branch_directly | true                                         |
| git_url               | git@github.com:org/repo.git |
| storage_mode          | git                                          |
| username              | ****                             |
| keychain_name         | ios-build.keychain                           |
| keychain_password     | ********                                     |
| readonly              | false                                        |
| team_id               | ****                                   |
| team_name             | <REDACTED>                   |
| verbose               | false                                        |
| skip_confirmation     | false                                        |
| shallow_clone         | false                                        |
| skip_docs             | false                                        |
| platform              | ios                                          |
+-----------------------+----------------------------------------------+

[13:30:07]: Cloning remote git repo...
[13:30:39]: Couldn't decrypt the repo, please make sure you enter the right password!
<details><summary>`./Appfile`</summary>
[13:30:42]: ▸ ```ruby
[13:30:42]: ▸ app_identifier "com.app.id"
[13:30:42]: ▸ apple_id "****"
[13:30:42]: ▸ itc_team_id "<REDACTED>"
[13:30:42]: ▸ team_id "****"
[13:30:42]: ▸ team_name "<REDACTED>"
[13:30:42]: ▸ ```
[13:30:42]: ▸ </details>
[13:30:42]: ▸ ### fastlane gems
[13:30:42]: ▸ | Gem      | Version | Update-Status |
[13:30:42]: ▸ | -------- | ------- | ------------- |
[13:30:42]: ▸ | fastlane | 2.106.1 | ✅ Up-To-Date  |
[13:30:42]: ▸ ### Loaded fastlane plugins:
[13:30:42]: ▸ **No plugins Loaded**
[13:30:42]: ▸ <details><summary><b>Loaded gems</b></summary>
[13:30:42]: ▸ | Gem                       | Version      |
[13:30:42]: ▸ | ------------------------- | ------------ |
[13:30:42]: ▸ | did_you_mean              | 1.0.0        |
[13:30:42]: ▸ | io-console                | 0.4.5        |
[13:30:42]: ▸ | CFPropertyList            | 3.0.0        |
[13:30:42]: ▸ | concurrent-ruby           | 1.0.5        |
[13:30:42]: ▸ | i18n                      | 0.9.5        |
[13:30:42]: ▸ | minitest                  | 5.11.3       |
[13:30:42]: ▸ | thread_safe               | 0.3.6        |
[13:30:42]: ▸ | tzinfo                    | 1.2.5        |
[13:30:42]: ▸ | activesupport             | 4.2.10       |
[13:30:42]: ▸ | public_suffix             | 2.0.5        |
[13:30:42]: ▸ | addressable               | 2.5.2        |
[13:30:42]: ▸ | atomos                    | 0.1.3        |
[13:30:42]: ▸ | babosa                    | 1.0.2        |
[13:30:42]: ▸ | bundler                   | 1.16.1       |
[13:30:42]: ▸ | claide                    | 1.0.2        |
[13:30:42]: ▸ | fuzzy_match               | 2.0.4        |
[13:30:42]: ▸ | nap                       | 1.1.0        |
[13:30:42]: ▸ | cocoapods-core            | 1.5.3        |
[13:30:42]: ▸ | cocoapods-deintegrate     | 1.0.2        |
[13:30:42]: ▸ | cocoapods-downloader      | 1.2.1        |
[13:30:42]: ▸ | cocoapods-plugins         | 1.0.0        |
[13:30:42]: ▸ | cocoapods-search          | 1.0.0        |
[13:30:42]: ▸ | cocoapods-stats           | 1.0.0        |
[13:30:42]: ▸ | netrc                     | 0.11.0       |
[13:30:42]: ▸ | cocoapods-trunk           | 1.3.1        |
[13:30:42]: ▸ | cocoapods-try             | 1.1.0        |
[13:30:42]: ▸ | colored2                  | 3.1.2        |
[13:30:42]: ▸ | escape                    | 0.0.4        |
[13:30:42]: ▸ | fourflusher               | 2.0.1        |
[13:30:42]: ▸ | gh_inspector              | 1.1.3        |
[13:30:42]: ▸ | molinillo                 | 0.6.6        |
[13:30:42]: ▸ | ruby-macho                | 1.3.1        |
[13:30:42]: ▸ | nanaimo                   | 0.2.6        |
[13:30:42]: ▸ | xcodeproj                 | 1.6.0        |
[13:30:42]: ▸ | cocoapods                 | 1.5.3        |
[13:30:42]: ▸ | colored                   | 1.2          |
[13:30:42]: ▸ | highline                  | 1.7.10       |
[13:30:42]: ▸ | commander-fastlane        | 4.4.6        |
[13:30:42]: ▸ | declarative               | 0.0.10       |
[13:30:42]: ▸ | declarative-option        | 0.1.0        |
[13:30:42]: ▸ | unf_ext                   | 0.0.7.5      |
[13:30:42]: ▸ | unf                       | 0.1.4        |
[13:30:42]: ▸ | domain_name               | 0.5.20180417 |
[13:30:42]: ▸ | dotenv                    | 2.5.0        |
[13:30:42]: ▸ | emoji_regex               | 0.1.1        |
[13:30:42]: ▸ | excon                     | 0.62.0       |
[13:30:42]: ▸ | multipart-post            | 2.0.0        |
[13:30:42]: ▸ | faraday                   | 0.15.3       |
[13:30:42]: ▸ | http-cookie               | 1.0.3        |
[13:30:42]: ▸ | faraday-cookie_jar        | 0.0.6        |
[13:30:42]: ▸ | faraday_middleware        | 0.12.2       |
[13:30:42]: ▸ | fastimage                 | 2.1.4        |
[13:30:42]: ▸ | jwt                       | 2.1.0        |
[13:30:42]: ▸ | memoist                   | 0.16.0       |
[13:30:42]: ▸ | multi_json                | 1.13.1       |
[13:30:42]: ▸ | os                        | 1.0.0        |
[13:30:42]: ▸ | signet                    | 0.11.0       |
[13:30:42]: ▸ | googleauth                | 0.6.6        |
[13:30:42]: ▸ | httpclient                | 2.8.3        |
[13:30:42]: ▸ | mime-types-data           | 3.2018.0812  |
[13:30:42]: ▸ | mime-types                | 3.2.2        |
[13:30:42]: ▸ | uber                      | 0.1.0        |
[13:30:42]: ▸ | representable             | 3.0.4        |
[13:30:42]: ▸ | retriable                 | 3.1.2        |
[13:30:42]: ▸ | google-api-client         | 0.23.9       |
[13:30:42]: ▸ | json                      | 2.1.0        |
[13:30:42]: ▸ | mini_magick               | 4.5.1        |
[13:30:42]: ▸ | multi_xml                 | 0.6.0        |
[13:30:42]: ▸ | plist                     | 3.4.0        |
[13:30:42]: ▸ | rubyzip                   | 1.2.2        |
[13:30:42]: ▸ | security                  | 0.1.3        |
[13:30:42]: ▸ | naturally                 | 2.2.0        |
[13:30:42]: ▸ | simctl                    | 1.6.5        |
[13:30:42]: ▸ | slack-notifier            | 2.3.2        |
[13:30:42]: ▸ | terminal-notifier         | 1.8.0        |
[13:30:42]: ▸ | unicode-display_width     | 1.4.0        |
[13:30:42]: ▸ | terminal-table            | 1.8.0        |
[13:30:42]: ▸ | tty-screen                | 0.6.5        |
[13:30:42]: ▸ | tty-cursor                | 0.6.0        |
[13:30:42]: ▸ | tty-spinner               | 0.8.0        |
[13:30:42]: ▸ | word_wrap                 | 1.0.0        |
[13:30:42]: ▸ | rouge                     | 2.0.7        |
[13:30:42]: ▸ | xcpretty                  | 0.3.0        |
[13:30:42]: ▸ | xcpretty-travis-formatter | 1.0.0        |
[13:30:42]: ▸ | ffi                       | 1.9.25       |
[13:30:42]: ▸ | mustache                  | 0.99.8       |
[13:30:42]: ▸ | open4                     | 1.3.4        |
[13:30:42]: ▸ | redcarpet                 | 3.4.0        |
[13:30:42]: ▸ | rb-fsevent                | 0.10.3       |
[13:30:42]: ▸ | rb-inotify                | 0.9.10       |
[13:30:42]: ▸ | sass-listen               | 4.0.0        |
[13:30:42]: ▸ | sass                      | 3.6.0        |
[13:30:42]: ▸ | sqlite3                   | 1.3.13       |
[13:30:42]: ▸ | liferaft                  | 0.0.6        |
[13:30:42]: ▸ | xcinvoke                  | 0.3.0        |
[13:30:42]: ▸ | jazzy                     | 0.9.3        |
[13:30:42]: ▸ </details>
[13:30:42]: ▸ *generated on:* **2018-10-12**
[13:30:42]: ▸ </details>
[13:30:42]: ▸ [13:30:42]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[13:30:42]: ▸ [13:30:42]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅
+------------------+-----------+
|         Lane Context         |
+------------------+-----------+
| DEFAULT_PLATFORM | ios       |
| PLATFORM_NAME    | ios       |
| LANE_NAME        | ios auto  |
| PRODUCE_APPLE_ID |           |
| VERSION_NUMBER   | 1.0.0 |
| BUILD_NUMBER     | 1.0.0 |
+------------------+-----------+
[13:30:42]: Invalid password passed via 'MATCH_PASSWORD'

```

**Comment by getaaron** [comment] 2018-10-13 21:29
@Sega-Zero Can you see any more helpful information if you follow the steps in https://docs.fastlane.tools/advanced/other/#manually-manage-the-fastlane-match-repo?

And can you confirm that if you downgrade to fastlane 2.105.2 that nuke distribution starts working for you again?

**Comment by Sega-Zero** [comment] 2018-10-13 21:38
Right now I can't, sorry. I had to wipe the repo completely in order to be able to put my project back to work. 
I can't also confirm that nuke works right now on 2.105.2, but it was working 17 days ago.

**Comment by getaaron** [comment] 2018-10-13 22:08
OK, this regression looks possibly related to #13405 CC @milch @janpio @KrauseFx @joshdholtz

**Comment by joshdholtz** [comment] 2018-10-15 12:14
@Sega-Zero @getaaron Heyyy, just got back from a long weekend vacation! Looking into this now and will push out a fix right away when solved

**Comment by joshdholtz** [comment] 2018-10-15 12:43
@Sega-Zero Thanks for reporting this! Got a fix for this right here ^ I will get this out today

**Closed** 2018-10-15 12:53 UTC
Labels: status: regression

**Comment by dannys42** [comment] 2018-10-15 17:10
Just curious, with the fix in, how do you recover from a now broken certificate repository?  If I try doing 'fastlane match development' for example, it says "Enter the passphrase that should be used to encrypt/decrypt your certificates" and prompts for my password.  My password prior to the nuke will not work anymore.

**Comment by joshdholtz** [comment] 2018-10-15 19:06
@dannys42 The easiest thing is to fully nuke your repo since it left it in a decrypted (plain text) state. If you don't want nuke everything, I will work on writing up some code to just encrypt what you have in there. It will be a few minutes though until I have that for you 😊

**Comment by joshdholtz** [comment] 2018-10-15 20:11
@dannys42 

## How to re-encrypt your repo
A side effect of this issue was that the repo could have become decrypted after a nuke. The following code can be put in a `Fastfile` (or run in CLI with `bundle console` without the `lane` block) to re-encrypte your repo.

⚠️ **THIS SHOULD ONLY BE DONE ONCE SO THAT YOU DO NOT DOUBLE ENCRYPT YOUR REPO** ⚠️

```rb
lane :fix_encrypt_but_only_do_this_once do
  require 'match'

  git_url = "https://github.com/joshdholtz/fastlane-match-repo.git"

  storage = Match::Storage.for_mode("git", { git_url: git_url, shallow_clone: false, git_branch: "master", clone_branch_directly: false})
  storage.download

  encryption = Match::Encryption.for_storage_mode("git", { git_url: git_url, working_directory: storage.working_directory})
  encryption.encrypt_files

  files_to_commit = Dir[File.join(storage.working_directory, "**", "*.{cer,p12,mobileprovision}")]
  storage.save_changes!(files_to_commit: files_to_commit)
end
```

**Comment by dannys42** [comment] 2018-10-17 20:58
Thanks @joshdholtz, that worked!
