### ISSUE TITLE
Regression: MATCH_TYPE environment variable not overriding default value

### ISSUE THREAD

**Issue by lkraider** [fastlane/fastlane#10640] opened 2017-10-19 01:21 UTC
### New Issue Checklist

- [ X ] Updated fastlane to the latest version
- [ X ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ X ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ X ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Steps to reproduce:
 1. Create `Matchfile` and set `type "development"`
 1. Set `MATCH_TYPE=adhoc` as environment variable
 1. Run `fastlane match`

Result: it will try to setup development credentials.
Expected: environment variable should override the default settings, as was previous behaviour and  also according to docs.

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                           |
| --------------------------- | ----------------------------------------------- |
| OS                          | 10.11.6                                         |
| Ruby                        | 2.3.1                                           |
| Bundler?                    | false                                           |
| Git                         | git version 2.10.1 (Apple Git-78)               |
| Installation Source         | /usr/local/bin/fastlane                         |
| Host                        | Mac OS X 10.11.6 (15G1611)                      |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.3.1_2/lib              |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                     |
| Is contained                | false                                           |
| Is homebrew                 | false                                           |
| Is installed via Fabric.app | false                                           |
| Xcode Path                  | /Applications/Xcode-8.2.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.62.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.54.0       |
| faraday                   | 0.9.2        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160826 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.2        |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.5.5        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
| faraday_middleware        | 0.10.0       |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.13.2       |
| io-console                | 0.4.5        |
| unicode-display_width     | 1.1.1        |
| terminal-table            | 1.7.3        |
</details>

*generated on:* **2017-10-18**
</details>

**Comment by KrauseFx** [comment] 2017-10-19 07:54
Thanks for the report, I'm trying to reproduce now 👍

**Comment by KrauseFx** [comment] 2017-10-19 07:55
I can reproduce, thanks, will look into this now 👍

**Comment by KrauseFx** [comment] 2017-10-19 08:06
There was no change in the code recently, with what fastlane version did this work?

**Comment by KrauseFx** [comment] 2017-10-19 08:17
Just pushed https://github.com/fastlane/fastlane/pull/10643, and added some comments, let's me know what you think

**Comment by lkraider** [comment] 2017-10-19 15:04
I am not sure about match, but our CI tools use env vars to enforce options during build over whatever is set in the git committed project files.

It's my impression this was the case, but could be we had been working under this assumption and everything worked by coincidence until we noticed this issue.

Either way, I'd argue FOR the environment being able to override file settings, it's usually how other tools work and enables easier config during builds (instead of parsing and rewriting files).

**Comment by milch** [comment] 2017-11-20 16:21
I'll close this issue since #10650 is now merged to master. Thanks for your input @lkraider!

**Closed by milch** 2017-11-20 16:21 UTC
Labels: status: regression

**Comment by lkraider** [comment] 2017-11-20 18:11
Awesome, thanks!
