### ISSUE TITLE
update_project_provisioning undefined method

### ISSUE THREAD

**Issue by yixiangfeng** [fastlane/fastlane#20173] opened 2022-04-13 08:09 UTC
when i run update_project_provisioning have this error
the provisioning path is correct

FastFile
```
build_configuration = "Release"
    xcodeproj = ENV["PROJECT_PATH"]
    
    UI.message "#{ENV[options[:app_path]]}"
    # Main application
    update_project_provisioning(
      xcodeproj: xcodeproj,
      profile: "#{ENV[options[:app_path]]}",
      target_filter: ENV["MY_TARGET"],
      build_configuration: build_configuration,
    )
```
```
/opt/homebrew/Cellar/fastlane/2.205.1/libexec/gems/fastlane-2.205.1/fastlane/lib/fastlane/actions/update_project_provisioning.rb:73:in `block (2 levels) in run': \e[31m[!] undefined method `[]' for nil:NilClass (NoMethodError)

            build_configuration.build_settings["PROVISIONING_PROFILE"] = data["UUID"]
```

fastlane version 2.205.1

**Comment by rogerluan** [comment] 2022-04-13 11:00
I transferred this to the right repository @yixiangfeng 🙏

**Comment by ecorreyu** [comment] 2022-04-13 12:21
Same error.

**Comment by kamvoick** [comment] 2022-04-13 12:53
Duplicate of https://github.com/fastlane/fastlane/issues/20172

This solution worked for me https://github.com/fastlane/fastlane/issues/20172#issuecomment-1097982784

**Comment by anutting** [comment] 2022-04-13 19:26
why is update_project_provisioning suddenly no longer working? for me, swapping to update_code_signing_settings in that solution does not work for me and is not a valid workaround.

**Closed** 2022-04-14 04:10 UTC
Labels: status: workaround available

**Comment by tigerw** [comment] 2022-04-14 14:58
```
> openssl pkcs7 -print_certs -text -in noisivorpelibom.mobileprovision -inform der
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 23 (0x17)
    Signature Algorithm: sha1WithRSAEncryption
        Issuer: C=US, O=Apple Inc., OU=Apple Certification Authority, CN=Apple Root CA
        Validity
            Not Before: Apr 12 17:43:28 2007 GMT
            Not After : Apr 12 17:43:28 2022 GMT
        Subject: C=US, O=Apple Inc., OU=Apple Certification Authority, CN=Apple iPhone Certification Authority
<snip>
```
Apple's intermediate certificates used to sign the mobileprovision file expired, best option is to re-generate the provisioning profiles, I suppose. See http://stackoverflow.com/a/71853423

**Comment by callMeMakerRen** [comment] 2022-04-15 10:44
> ```
> > openssl pkcs7 -print_certs -text -in noisivorpelibom.mobileprovision -inform der
> Certificate:
>     Data:
>         Version: 3 (0x2)
>         Serial Number: 23 (0x17)
>     Signature Algorithm: sha1WithRSAEncryption
>         Issuer: C=US, O=Apple Inc., OU=Apple Certification Authority, CN=Apple Root CA
>         Validity
>             Not Before: Apr 12 17:43:28 2007 GMT
>             Not After : Apr 12 17:43:28 2022 GMT
>         Subject: C=US, O=Apple Inc., OU=Apple Certification Authority, CN=Apple iPhone Certification Authority
> <snip>
> ```
> 
> Apple's intermediate certificates used to sign the mobileprovision file expired, best option is to re-generate the provisioning profiles, I suppose. See http://stackoverflow.com/a/71853423

Right Answer!
