### ISSUE TITLE
Support importing certificates & profiles without requiring Apple Dev Portal credentials

### ISSUE THREAD

**Issue by andrewtheis** [fastlane/fastlane#16203] opened 2020-03-24 02:10 UTC
#### Motivation Behind Feature
Sometimes when working on a project you may not have access to the Apple Certificates & Profiles Portal directly - perhaps a client doesn't want to give you access and is generating the certificates and provisioning profiles manually for you. Currently, the `match import` command requires an Apple ID with access to the portal, which prevents it from working in this scenario.

This scenario is arguably one that would be more common than not for users of `match import`. If you have access to the portal for the project you are working on, there are plenty of other existing commands to pull certificates and profiles in a non-destructive manner. The `import` command should focus around the case where you don't have access to the portal for your project.

#### Feature Description
Add a CLI option when using `match import` to provide the information that it is attempting to pull from the Certificates & Profiles portal, so access is no longer needed - or - reconsider if it's necessary to access the portal at all so a bypass isn't needed. 

There should not be any drawbacks or breaking changes, as this is a purely additive feature.

#### Alternatives or Workarounds
If you have to use `match` (which is the case when using GitHub Actions for CI), the only workaround is to use some of the Ruby scripts online to handle decrypting the match repo, adding the files, re-encrypting, and pushing to the Git remote manually. There are many tutorials online on how to do this, and it was the only option available prior to the `import` command.

@joshdholtz Let me know if you need any more info.

**Comment by joshdholtz** [comment] 2020-03-24 02:10
Thank you!! ❤️

**Comment by stefanomondino** [comment] 2020-03-25 15:15
possible duplicate of #16152

**Comment by sraka1** [comment] 2020-04-16 11:28
@joshdholtz Perhaps these two issues should be merged/assigned as duplicate. Also, as I already asked in the other issue - isn't the certificate ID included in the certificate itself, both as part of the name and as the "User ID" and "Organisational unit" fields?

**Comment by joshdholtz** [comment] 2020-04-16 11:31
@sraka1 Hey! I can take a look again but the look and didn’t think I saw the same ID inside the certificate as what the Developer Portal assigns it. I really would like to not require it though. I’ll take a look later today/tomorrow to see what I can find!

**Comment by stefanomondino** [comment] 2020-04-16 12:12
@sraka1 I've tried to look everywhere inside the certificate but couldn't find it. Seems like the only place you can find this ID is the developer portal (i usually click on the certificate and copy the id from the URL)

**Closed** 2020-05-24 17:32 UTC
Labels: status: waiting-for-reply
