### ISSUE TITLE
776: unexpected token at 'Bad Request'

### ISSUE THREAD

**Issue by jmei08** [fastlane/fastlane#13807] opened 2018-12-04 11:30 UTC
I get the following error whenever I run `match` these days.
776: unexpected token at 'Bad Request'

Environment: fastlane 2.108.0

complete output:
```
+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | Verifying fastlane  | 0           |
|      | version             |             |
| 2    | default_platform    | 0           |
| 💥   | match               | 63          |
| 4    | notification        | 0           |
+------+---------------------+-------------+

ERROR [2018-12-04 19:17:46.22]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: 776: unexpected token at 'Bad Request'

URL: https://api.github.com/search/issues?q=776%3A%20unexpected%20token%20at%20%27Bad%20Request%27+repo:fastlane/fastlane
➡️  784: unexpected token at 'Bad Request' (Faraday::ParsingError)
    https://github.com/fastlane/fastlane/issues/13666 [open] 54 💬
    22 hours ago

➡️  [Regression] 784: unexpected token at 'Bad Request' reintroduced in 2.19
    https://github.com/fastlane/fastlane/issues/8409 [closed] 4 💬
    19 Sep 2017

➡️  Produce fails to create a new app id
    https://github.com/fastlane/fastlane/issues/5797 [closed] 32 💬
    06 Dec 2016

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/xxxx/.fastlane/bin/bundle/lib/ruby/2.2.0/json/common.rb:155:in `parse': [!] 776: unexpected token at 'Bad Request' (Faraday::ParsingError)
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/2.2.0/json/common.rb:155:in `parse'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response/parse_json.rb:11:in `block in <class:ParseJson>'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response_middleware.rb:50:in `call'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response_middleware.rb:50:in `parse'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response_middleware.rb:39:in `process_response'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response_middleware.rb:32:in `block in call'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday-0.12.1/lib/faraday/response.rb:61:in `on_complete'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday-0.12.1/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday-0.12.1/lib/faraday/connection.rb:386:in `run_request'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday-0.12.1/lib/faraday/connection.rb:186:in `post'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.108.0/spaceship/lib/spaceship/client.rb:701:in `block in send_request'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.108.0/spaceship/lib/spaceship/client.rb:533:in `with_retry'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.108.0/spaceship/lib/spaceship/client.rb:700:in `send_request'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.108.0/spaceship/lib/spaceship/client.rb:586:in `request'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.108.0/spaceship/lib/spaceship/portal/portal_client.rb:710:in `delete_provisioning_profile!'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.108.0/spaceship/lib/spaceship/portal/provisioning_profile.rb:423:in `delete!'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.108.0/sigh/lib/sigh/runner.rb:33:in `run'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.108.0/sigh/lib/sigh/manager.rb:8:in `start'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.108.0/match/lib/match/generator.rb:76:in `generate_provisioning_profile'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.108.0/match/lib/match/runner.rb:188:in `fetch_provisioning_profile'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.108.0/match/lib/match/runner.rb:77:in `block (2 levels) in run'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.108.0/match/lib/match/runner.rb:76:in `loop'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.108.0/match/lib/match/runner.rb:76:in `block in run'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.108.0/match/lib/match/runner.rb:75:in `each'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.108.0/match/lib/match/runner.rb:75:in `run'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/actions/sync_code_signing.rb:12:in `run'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:29:in `block (2 levels) in parsing_binding'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.108.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
	from /Users/xxxx/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.108.0/bin/fastlane:23:in `<top (required)>'
	from /Users/xxxx/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/xxxx/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
```

**Comment by janpio** [comment] 2018-12-04 11:36
Hey @jmei08, this looks like a duplicate of https://github.com/fastlane/fastlane/issues/13666 - Can you read through this and see if it matches what you describe?

If yes, please follow the instruction at https://github.com/fastlane/fastlane/issues/13666#issuecomment-443705971 to help me finish debugging this 🥇

**Closed by janpio** 2018-12-04 11:36 UTC
Labels: tool: match
