### ISSUE TITLE
FastlaneCore::Project->build_settings() not using -configuration parameter

### ISSUE THREAD

**Issue by chenxiao0228** [fastlane/fastlane#6514] opened 2016-10-12 05:32 UTC
### New Issue Checklist
- [ x] Updated fastlane to the latest version
- [ x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

Scan::detect_values.rb->detect_simulator() uses FastlaneCore::Project->build_settings()

which is using command:
xcodebuild -showBuildingSettings -workspace -scheme -project

The issue is that -configuration parameter is not used to list the build settings and it will use the default configuration. This may cause unexpected return if a project has multiple scheme and configuration. e.g different deployment target for different configuration.

fastlane version (run `fastlane -v`):

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

**Comment by TKBurner** [comment] 2016-10-12 19:35
@chenxiao0228 Are you interested in submitting a PR to correct this? I'd love to see that 👍 👍 💯

**Comment by tadelv** [comment] 2016-10-15 09:37
@TKBurner @chenxiao0228 check my pull request: #6542 if it fixes your problems. Thnx! :)

**Comment by chenxiao0228** [comment] 2016-10-16 22:50
@tadelv @TKBurner I checked and it fixes the problem. Sorry I should have done it myself.

**Comment by TKBurner** [comment] 2016-10-18 20:19
@tadelv Thanks for contributing! 👍 👍 👍 💯 Email me at burner@twitter.com, I want to ask you something on a private channel.

**Comment by milch** [comment] 2016-11-15 01:23
Closing this as a duplicate of #6113.

**Closed by milch** 2016-11-15 01:23 UTC
Labels: feature, you can do this
