### ISSUE TITLE
Cocoapods 1.0 no longer automatically update spec-repos on pod install issue

### ISSUE THREAD

**Issue by thierryxing** [fastlane/fastlane#4780] opened 2016-05-23 04:27 UTC
The Cocoapods 1.0 no longer automatically update spec-repos on pod install.
http://blog.cocoapods.org/Master-Spec-Repo-Rate-Limiting-Post-Mortem/

So I think somebody may need to update the `cocoapods` action and make sure `pod repo update` executed before `pod install`.

And I find that there is a new `--repo-update` params in `pod install` command which will 'Force running `pod repo update` before install'

Thank you.

**Comment by KrauseFx** [comment] 2016-05-23 04:52
Is this is a duplicate of https://github.com/fastlane/fastlane/issues/4497, or do you mean something else?

**Closed by KrauseFx** 2016-05-23 04:52 UTC
Labels: action
