### ISSUE TITLE
match crashing to can't modify frozen String: "true"

### ISSUE THREAD

**Issue by vinaychopra90** [fastlane/fastlane#16309] opened 2020-04-15 08:28 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Trying to run match after updating a new device (register_devices) is crashing
The existing provisioning profile is deleted from the portal and match is not able to create a new one.

Individual commands sigh and cert are working fine.

match(type: "development",force_for_new_devices: true)
##### Command executed

match(type: "development", force_for_new_devices: true)

##### Complete output when running fastlane, including the stack trace and command used

Till here everything is executed in green .

[13:50:05]: Installing provisioning profile...
[13:50:07]: Provisioning profile 'a6a8a9ac-bb48-4161-87c7-8ac02f8f0107' is not available on the Developer Portal for the user vinay@--.in, fixing this now for you 🔨

+-------------------------------------+---------------------------------------------+
|                             Summary for sigh 2.145.0                              |
+-------------------------------------+---------------------------------------------+
| app_identifier                      | com.--.--                   |
| username                            | vinay@--.in                      |
| force                               | false                                       |
| cert_id                             | --                                  |
| provisioning_name                   | match Development com.--.-- |
| ignore_profiles_with_different_name | true                                        |
| team_id                             | ------                                  |
| platform                            | ios                                         |
| development                         | true                                        |
| adhoc                               | false                                       |
| developer_id                        | false                                       |
| skip_install                        | false                                       |
| skip_fetch_profiles                 | false                                       |
| skip_certificate_verification       | false                                       |
| readonly                            | false                                       |
+-------------------------------------+---------------------------------------------+

[13:50:07]: Starting login with user 'vinay@--.in'
[13:50:09]: Successfully logged in
[13:50:09]: Fetching profiles...
[13:50:10]: Verifying certificates...
[13:50:10]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you
[13:50:14]: **Creating new provisioning profile for 'com.designcapital.lemoney' with name 'match Development com.--.--' for 'ios' platform**
+------------------+-------------------------+
|                Lane Context                |
+------------------+-------------------------+
| DEFAULT_PLATFORM | ios                     |
| PLATFORM_NAME    | ios                     |
| LANE_NAME        | ios sync_signing_assets |
+------------------+-------------------------+
**[13:50:14]: can't modify frozen String: "true"**

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 💥   | match            | 17          |
+------+------------------+-------------+

[13:50:14]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  can't modify frozen String: "true" for enterprise builds
    https://github.com/fastlane/fastlane/issues/16055 [open] 39 💬
    a week ago

➡️  fastlane deliver download_metadata failed with Ruby 2.7.0p0 on macOS
    https://github.com/fastlane/fastlane/issues/16113 [open] 6 💬
    5 days ago

➡️  match always creates new certificates for appstore, fails on readonly [XCode 11]
    https://github.com/fastlane/fastlane/issues/16210 [open] 3 💬
    4 days ago

and 3 more at: https://github.com/fastlane/fastlane/search?q=can%27t%20modify%20frozen%20String%3A%20%22true%22&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
Traceback (most recent call last):
	43: from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:23:in `<main>'
	42: from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:23:in `load'
	41: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.145.0/bin/fastlane:23:in `<top (required)>'
	40: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.145.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	39: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.145.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	38: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.145.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
	37: from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	36: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.145.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	35: from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	34: from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	33: from /usr/local/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	32: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.145.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	31: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.145.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	30: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.145.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	29: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.145.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	28: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.145.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	27: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.145.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	26: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.145.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	25: from Fastfile:71:in `block (2 levels) in parsing_binding'
	24: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.145.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	23: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.145.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	22: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.145.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	21: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.145.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	20: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.145.0/fastlane/lib/fastlane/runner.rb:253:in `block in execute_action'
	19: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.145.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	18: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.145.0/fastlane/lib/fastlane/runner.rb:261:in `block (2 levels) in execute_action'
	17: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.145.0/fastlane/lib/fastlane/actions/sync_code_signing.rb:13:in `run'
	16: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.145.0/match/lib/match/runner.rb:105:in `run'
	15: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.145.0/match/lib/match/runner.rb:105:in `each'
	14: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.145.0/match/lib/match/runner.rb:106:in `block in run'
	13: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.145.0/match/lib/match/runner.rb:106:in `loop'
	12: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.145.0/match/lib/match/runner.rb:107:in `block (2 levels) in run'
	11: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.145.0/match/lib/match/runner.rb:254:in `fetch_provisioning_profile'
	10: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.145.0/match/lib/match/generator.rb:92:in `generate_provisioning_profile'
	 9: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.145.0/sigh/lib/sigh/manager.rb:8:in `start'
	 8: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.145.0/sigh/lib/sigh/runner.rb:40:in `run'
	 7: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.145.0/sigh/lib/sigh/runner.rb:135:in `create_profile!'
	 6: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.145.0/spaceship/lib/spaceship/portal/provisioning_profile.rb:262:in `create!'
	 5: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.145.0/spaceship/lib/spaceship/portal/provisioning_profile.rb:262:in `inspect'
	 4: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.145.0/spaceship/lib/spaceship/base.rb:286:in `inspect'
	 3: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.145.0/spaceship/lib/spaceship/base.rb:296:in `inspect_value'
	 2: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.145.0/spaceship/lib/spaceship/base.rb:296:in `map'
	 1: from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.145.0/spaceship/lib/spaceship/base.rb:298:in `block in inspect_value'
/usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.145.0/spaceship/lib/spaceship/base.rb:298:in `gsub!': \e[31m[!] can't modify frozen String: "true"\e[0m (FrozenError)

**ENV** 

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.1                                     |
| Ruby                        | 2.7.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.21.0 (Apple Git-122.2)        |
| Installation Source         | /usr/local/lib/ruby/gems/2.7.0/bin/fastlane |
| Host                        | Mac OS X 10.15.1 (19B88)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.7.0/lib            |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.3                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

ENV["DELIVER_USER"] = "vinay@--.in"

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :test do
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "Distribute to Crashlytics"
  lane :distribute_to_crashlytics do
    build_development
    firebase_app_distribution(
        app: "1:xxxxx:ios:xxxxxx",
        testers: "vinaychopra90@gmail.com",
        release_notes: "Lots of amazing new features to test out!",
        firebase_cli_path: "/usr/local/bin/Firebase"
    )
  end


  # FIREBASE TESTING

  # desc "My awesome app"
  #     lane :distribute do
  #         build_ios_app(...) # build_ios_app is a built-in fastlane action.
  #
  #         firebase_app_distribution(
  #             app: "1:xxxx:ios:xxxxx",
  #             testers: "tester1@company.com, tester2@company.com",
  #             release_notes: "Lots of amazing new features to test out!",
  #             firebase_cli_path: "/absolute/path/to/firebase/cli/binary"
  #         )
  #
  #     end

  #---


  desc "Build for Development Purpose"
  lane :build_development do
    # sync_signing_assets(type: "development")
    # increment_build_number
    gym(
      output_directory: "build_development",
      export_method: "development",
      silent: true
    )
  end

  desc "sync team Code Signing assets"
  lane :sync_signing_assets do |options|
    # sync_device_info
    # selecetedType = options[:type]
    match(type: "development",force_for_new_devices: true)
  end

  desc "Update iOS UDID on the Apple Developer Portal"
  lane :sync_device_info do
    register_devices(
      devices_file: "fastlane/DeviceFile.txt"
        # devices: {
        #   "vinay_iPhone11PRO" => "xxx-xxx"
        # }
    )
  end

  lane :get_dev_certs do
    cert(development: true)
    sigh(development: true)
  end

  lane :get_dev_certs_withParams do
    cert(
      username: "vinay@--.in",
      team_name: "Lemoney Online Services Private Limited",
      development: true
    )
    sigh(
      username: "vinay@--.in",
      team_name: "Some Compnay Services Private Limited",
      app_identifier: "com.--.--",
      development: true
    )
  end
  lane :sandbox do
    cert(
      username: "vinay@--.in",
      team_name: "Some Compnay Services Private Limited",
      development: true
    )
  end


end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

app_identifier "com.--.--"
apple_id "vinay@--.in"
team_id "----"

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.145.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status |
| ----------------------------------------- | ------- | ------------- |
| fastlane-plugin-firebase_app_distribution | 0.1.4   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.4.0        |
| slack-notifier                            | 2.3.2        |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.7.0        |
| terminal-table                            | 1.8.0        |
| plist                                     | 3.5.0        |
| CFPropertyList                            | 3.0.2        |
| public_suffix                             | 2.0.5        |
| addressable                               | 2.7.0        |
| multipart-post                            | 2.0.0        |
| word_wrap                                 | 1.0.0        |
| tty-screen                                | 0.7.1        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| babosa                                    | 1.0.3        |
| colored                                   | 1.2          |
| highline                                  | 1.7.10       |
| commander-fastlane                        | 4.4.6        |
| excon                                     | 0.73.0       |
| faraday                                   | 0.17.3       |
| unf_ext                                   | 0.0.7.7      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| http-cookie                               | 1.0.3        |
| faraday-cookie_jar                        | 0.0.6        |
| faraday_middleware                        | 0.13.1       |
| fastimage                                 | 2.1.7        |
| gh_inspector                              | 1.1.3        |
| json                                      | 2.3.0        |
| mini_magick                               | 4.10.1       |
| multi_xml                                 | 0.6.0        |
| rubyzip                                   | 1.3.0        |
| security                                  | 0.1.3        |
| xcpretty-travis-formatter                 | 1.0.0        |
| dotenv                                    | 2.7.5        |
| naturally                                 | 2.2.0        |
| simctl                                    | 1.6.8        |
| jwt                                       | 2.1.0        |
| uber                                      | 0.1.0        |
| declarative                               | 0.0.10       |
| declarative-option                        | 0.1.0        |
| representable                             | 3.0.4        |
| retriable                                 | 3.1.2        |
| mini_mime                                 | 1.0.2        |
| httpclient                                | 2.8.3        |
| google-api-client                         | 0.36.4       |
| emoji_regex                               | 1.0.1        |
| uri                                       | 0.10.0       |
| nanaimo                                   | 0.2.6        |
| colored2                                  | 3.1.2        |
| claide                                    | 1.0.3        |
| atomos                                    | 0.1.3        |
| xcodeproj                                 | 1.16.0       |
| bundler                                   | 2.1.4        |
| multi_json                                | 1.14.1       |
| signet                                    | 0.14.0       |
| os                                        | 1.1.0        |
| memoist                                   | 0.16.2       |
| googleauth                                | 0.12.0       |
| digest-crc                                | 0.5.1        |
| google-cloud-errors                       | 1.0.0        |
| google-cloud-env                          | 1.3.1        |
| google-cloud-core                         | 1.5.0        |
| google-cloud-storage                      | 1.26.0       |
| aws-eventstream                           | 1.1.0        |
| aws-sigv4                                 | 1.1.1        |
| aws-partitions                            | 1.296.0      |
| jmespath                                  | 1.4.0        |
| aws-sdk-core                              | 3.94.0       |
| aws-sdk-kms                               | 1.30.0       |
| aws-sdk-s3                                | 1.61.2       |
| forwardable                               | 1.3.1        |
| logger                                    | 1.4.2        |
| cgi                                       | 0.1.0        |
| timeout                                   | 0.1.0        |
| stringio                                  | 0.1.0        |
| ipaddr                                    | 1.2.2        |
| openssl                                   | 2.1.2        |
| ostruct                                   | 0.2.0        |
| strscan                                   | 1.0.3        |
| date                                      | 3.0.0        |
| delegate                                  | 0.1.0        |
| fileutils                                 | 1.4.1        |
| io-console                                | 0.5.3        |
| zlib                                      | 1.1.0        |
| singleton                                 | 0.1.0        |
| rexml                                     | 3.2.3        |
| open3                                     | 0.1.0        |
| yaml                                      | 0.1.0        |
| psych                                     | 3.1.0        |
| mutex_m                                   | 0.1.0        |
| webrick                                   | 1.6.0        |
| fastlane-plugin-firebase_app_distribution | 0.1.4        |
</details>

*generated on:* **2020-04-15**
</details>

**Comment by cosmith** [comment] 2020-04-21 09:54
This is a duplicate of #16055

**Closed** 2020-05-29 17:32 UTC
Labels: status: waiting-for-reply, tool: match, topic: ruby 2.7
