### ISSUE TITLE
Scan error: undefined method `tvos_version'

### ISSUE THREAD

**Issue by Chlup** [fastlane/fastlane#5359] opened 2016-07-11 07:30 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Unable to run scan for `tvos` target.

##### Complete output when running fastlane, including the stack trace and command used

```
[09:08:26]: Driving the lane 'ios tests_main_tvos' 🚀
[09:08:26]: ------------------
[09:08:26]: --- Step: scan ---
[09:08:26]: ------------------
[09:08:26]: xcrun xcodebuild -list -workspace app/showmax.xcworkspace
[09:08:28]: Variable Dump:
[09:08:28]: {:PLATFORM_NAME=>:ios, :LANE_NAME=>"ios tests_main_tvos"}
[09:08:28]: undefined method `tvos_version' for #<FastlaneCore::DeviceManager::Device:0x007fb831d626a8>

+------+--------+-------------+
|      fastlane summary       |
+------+--------+-------------+
| Step | Action | Time (in s) |
+------+--------+-------------+
| 1    | scan   | 2           |
+------+--------+-------------+

[09:08:28]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
/Library/Ruby/Gems/2.0.0/gems/scan-0.8.0/lib/scan/detect_values.rb:92:in `block (2 levels) in default_device_tvos': [!] undefined method `tvos_version' for #<FastlaneCore::DeviceManager::Device:0x007fb831d626a8> (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/scan-0.8.0/lib/scan/detect_values.rb:91:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/scan-0.8.0/lib/scan/detect_values.rb:91:in `detect'
	from /Library/Ruby/Gems/2.0.0/gems/scan-0.8.0/lib/scan/detect_values.rb:91:in `block in default_device_tvos'
	from /Library/Ruby/Gems/2.0.0/gems/scan-0.8.0/lib/scan/detect_values.rb:88:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/scan-0.8.0/lib/scan/detect_values.rb:88:in `default_device_tvos'
	from /Library/Ruby/Gems/2.0.0/gems/scan-0.8.0/lib/scan/detect_values.rb:24:in `set_additional_default_values'
	from /Library/Ruby/Gems/2.0.0/gems/scan-0.8.0/lib/scan.rb:27:in `config='
	from /Library/Ruby/Gems/2.0.0/gems/scan-0.8.0/lib/scan/manager.rb:4:in `work'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/actions/scan.rb:10:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:197:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:182:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:181:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:181:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:107:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/fast_file.rb:140:in `method_missing'
	from Fastfile:195:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:50:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/commands_generator.rb:51:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.48.1/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/commands_generator.rb:244:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/commands_generator.rb:20:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/cli_tools_distributor.rb:47:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'
```

Devices list:
```
$ xcrun simctl list devices
== Devices ==
-- iOS 9.3 --
    iPhone 4s (EB30F385-ACF1-4C15-A369-C3B7161E4F0B) (Shutdown)
    iPhone 5 (79BAD92D-3F9A-481A-B505-9D238E7DB6B1) (Booted)
    iPhone 5s (0B0097AA-E41E-4CAE-9854-BC86E36F8792) (Shutdown)
    iPhone 6 (7D17EC5F-5F6E-4F4F-9001-C72F36AF6F8E) (Shutdown)
    iPhone 6 Plus (20F5AFF8-07D8-45A8-BA53-8D92C10F5A8A) (Shutdown)
    iPhone 6s (D75BB680-1117-4E00-9D79-415DE782A78F) (Shutdown)
    iPhone 6s Plus (6AFC0FAE-2E07-4EEA-93C5-034F6F28F159) (Shutdown)
    iPad 2 (4E67D0D8-4DA9-4B63-82DB-F7F6AB904C93) (Shutdown)
    iPad Retina (8C313990-A61B-4A4C-8826-0DA38ED8DD7E) (Shutdown)
    iPad Air (614DBD0A-D35F-4B7B-AF4E-F286C0A2C0D6) (Shutdown)
    iPad Air 2 (72D449A5-074D-47B2-B7E9-FD06C22CB1C9) (Shutdown)
    iPad Pro (2A4E3BEF-3D19-469A-B2DE-37FBB01140F7) (Shutdown)
-- tvOS 9.2 --
    Apple TV 1080p (4B38AA8B-9C96-41F1-8948-292571D5B949) (Shutdown)
-- watchOS 2.2 --
    Apple Watch - 38mm (20CF6D3A-9FCC-4826-96C3-E18BB3DE1507) (Shutdown)
    Apple Watch - 42mm (3FE35F02-675C-4537-A2AA-75DBC73CEB5A) (Shutdown)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.iOS-9-2 --
    iPhone 4s (CDFCDF1C-1254-4E8C-A62B-03DA82E94378) (Shutdown) (unavailable, runtime profile not found)
    iPhone 5 (354D552F-E6E7-4FC8-B190-D3B0F003E3B8) (Shutdown) (unavailable, runtime profile not found)
    iPhone 5s (9CCBEF8D-B6C0-4C19-93D1-992288ED7F07) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6 (753FD575-FEC2-4B81-BBC6-D6A14FFA47A0) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6 Plus (6C308DEC-FA00-451A-AFEF-71166336B11B) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6s (B9BA0B30-D851-4A70-95D1-3CE10743F89B) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6s Plus (5BC74265-7A47-455F-9FBD-7428CC184E67) (Shutdown) (unavailable, runtime profile not found)
    iPad 2 (9A54D9B4-46E9-4710-A54E-A53998F70B80) (Shutdown) (unavailable, runtime profile not found)
    iPad Retina (4CA66045-8B90-4B0C-945C-E41A482D91A8) (Shutdown) (unavailable, runtime profile not found)
    iPad Air (629141E3-8B10-40CC-8189-1D5660E42095) (Shutdown) (unavailable, runtime profile not found)
    iPad Air 2 (6D832EE4-588D-4512-84EF-4A9586E2B5E5) (Shutdown) (unavailable, runtime profile not found)
    iPad Pro (6F84EA28-BF5B-4DDC-A7EF-7C0FD810E4E3) (Shutdown) (unavailable, runtime profile not found)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.tvOS-9-1 --
    Apple TV 1080p (25038080-87DE-4917-A766-B926EA66B7E1) (Shutdown) (unavailable, runtime profile not found)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.watchOS-2-1 --
    Apple Watch - 38mm (320AB7B3-1817-44FC-A600-2FA4456DBF5A) (Shutdown) (unavailable, runtime profile not found)
    Apple Watch - 42mm (7518C01E-3654-4188-995D-CE7CDE4AB4A3) (Shutdown) (unavailable, runtime profile not found)
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```
platform :ios do

    lane :tests_main_tvos do

        ENV["APP_IDENTIFIER"] = "com.showmax.main"

        scan(
            workspace: "app/showmax.xcworkspace",
            scheme: "showmaxTV_main",
            devices: ["Apple TV 1080p"],
            clean: true
        )
    end

end
```

### Environment

fastlane version (run `fastlane -v`):
fastlane 1.97.2

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
No

**Comment by foulkesjohn** [comment] 2016-07-11 09:15
Also seeing this issue

**Comment by foulkesjohn** [comment] 2016-07-11 09:28
This is caused by this line: https://github.com/fastlane/fastlane/blob/master/scan/lib/scan/detect_values.rb#L92

Changing `tvos_version` to `os_version` seems to resolve the issue, although I'm not 100% sure that is the best fix

**Comment by asfalcone** [comment] 2016-07-27 20:18
@Chlup @foulkesjohn I merged the PR that should fix this. I'll update when we do a `scan` release 🚀

**Closed** 2016-07-27 20:18 UTC

**Comment by asfalcone** [comment] 2016-07-27 20:36
[scan 0.9.0](https://github.com/fastlane/fastlane/releases/tag/scan/0.9.0) has been released 🦄
