### ISSUE TITLE
match - macOS Sierra keychain error

### ISSUE THREAD

**Issue by jmjordan** [fastlane/fastlane#5649] opened 2016-08-09 04:24 UTC
### Issue Description

When using macOS Sierra beta I am experiencing an issue with `match`. I receive an error saying that it cannot locate my keychain. It appears that Sierra is saving keychains with the keychain-db extension instead of keychain. If I change the keychain_name value to login.keychain-db it runs successfully.

##### Complete output when running fastlane, including the stack trace and command used

```
$ match adhoc

+-----------------------+---------------------------------------------+
|                       Summary for match 0.6.2                       |
+-----------------------+---------------------------------------------+
| git_url               |  |
| type                  | adhoc                                       |
| git_branch            | master                                      |
| app_identifier        |                         |
| username              |                      |
| keychain_name         | login.keychain                              |
| readonly              | false                                       |
| team_id               |                                  |
| verbose               | false                                       |
| force                 | false                                       |
| shallow_clone         | false                                       |
| force_for_new_devices | false                                       |
| skip_docs   false                                       |
+-----------------------+---------------------------------------------+

[21:11:03]: Cloning remote git repo...
[21:11:10]: 🔓  Successfully decrypted certificates repo
[21:11:10]: Verifying that the certificate and profile are still valid on the Dev Portal...
[21:11:11]: Installing certificate...
[21:11:11]: 🔒  Successfully encrypted certificates repo

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new

[!] Could not locate the provided keychain. Tried:
	/Users/username/Library/Keychains/login.keychain
	login.keychain```

### Environment

match 0.6.2

**Comment by TKBurner** [comment] 2016-08-11 20:53
Hi @jmjordan What happens if you unlock the login keychain prior to the match command? Do you still see this error?

**Comment by TKBurner** [comment] 2016-08-12 14:47
Hi @jmjordan Thanks for following up. Can you add the --verbose flag to your command and share the full output? Thanks!

**Comment by jmjordan** [comment] 2016-08-12 18:02
```

+-----------------------+---------------------------------------------+
|                       Summary for match 0.6.2                       |
+-----------------------+---------------------------------------------+
| verbose               | true                                        |
| git_url               | git@bitbucket.org:xxxxxxxxxxxxxxx.git |
| type                  | adhoc                                       |
| git_branch            | master                                      |
| app_identifier        | com.xxxxx.xxxxx                         |
| username              | xxxxx@mac.com                     |
| keychain_name         | login.keychain                              |
| readonly              | false                                       |
| team_id               | xxxxx                                  |
| force                 | false                                       |
| shallow_clone         | false                                       |
| force_for_new_devices | false                                       |
| skip_docs             | false                                       |
+-----------------------+---------------------------------------------+

INFO [2016-08-12 10:57:05.99]: Cloning remote git repo...
INFO [2016-08-12 10:57:05.99]: $ git clone 'git@xxxxx' '/var/folders/h9/2xhqclkj3tx2b0s1g9g4zj680000gn/T/d20160812-17817-zcv0hu'
INFO [2016-08-12 10:57:06.00]: ▸ Cloning into '/var/folders/h9/2xhqclkj3tx2b0s1g9g4zj680000gn/T/d20160812-17817-zcv0hu'...
INFO [2016-08-12 10:57:10.97]: ▸ remote: Counting objects: 184, done.
INFO [2016-08-12 10:57:11.22]: ▸ remote: Compressing objects: 100% (155/155), done.
INFO [2016-08-12 10:57:11.47]: ▸ remote: Total 184 (delta 15), reused 0 (delta 0)
INFO [2016-08-12 10:57:11.47]: ▸ Receiving objects: 100% (184/184), 271.74 KiB | 0 bytes/s, done.
INFO [2016-08-12 10:57:11.47]: ▸ Resolving deltas: 100% (15/15), done.
INFO [2016-08-12 10:57:11.49]: ▸ Checking connectivity... done.
INFO [2016-08-12 10:57:11.61]: 🔓  Decrypted 'xxxxx.cer'
INFO [2016-08-12 10:57:11.66]: 🔓  Decrypted 'xxxxx.cer'
INFO [2016-08-12 10:57:11.72]: 🔓  Decrypted 'xxxxx.p12'
INFO [2016-08-12 10:57:11.77]: 🔓  Decrypted 'xxxxx.p12'
INFO [2016-08-12 10:57:11.83]: 🔓  Decrypted 'AdHoc_xxxxx.mobileprovision'
INFO [2016-08-12 10:57:11.89]: 🔓  Decrypted 'AppStore_xxxxx.mobileprovision'
INFO [2016-08-12 10:57:11.94]: 🔓  Decrypted 'Development_xxxxx.mobileprovision'
INFO [2016-08-12 10:57:11.94]: 🔓  Successfully decrypted certificates repo
INFO [2016-08-12 10:57:11.99]: Verifying that the certificate and profile are still valid on the Dev Portal...
INFO [2016-08-12 10:57:13.50]: Installing certificate...
INFO [2016-08-12 10:57:13.50]: $ security list-keychains -d user
INFO [2016-08-12 10:57:13.51]: ▸     "/Users/<username>/Library/Keychains/login.keychain-db"
INFO [2016-08-12 10:57:13.51]: $ security find-certificate -c 'Apple Worldwide Developer Relations Certification Authority' /Users/<username>/Library/Keychains/login.keychain-db
INFO [2016-08-12 10:57:13.55]: ▸ keychain: "/Users/<username>/Library/Keychains/login.keychain-db"
INFO [2016-08-12 10:57:13.55]: ▸ version: 512
INFO [2016-08-12 10:57:13.55]: ▸ class: 0x80001000 
INFO [2016-08-12 10:57:13.55]: ▸ attributes:
INFO [2016-08-12 10:57:13.55]: ▸     "alis"<blob>="Apple Worldwide Developer Relations Certification Authority"
INFO [2016-08-12 10:57:13.55]: ▸     "cenc"<uint32>=0x00000003 
INFO [2016-08-12 10:57:13.55]: ▸     "ctyp"<uint32>=0x00000001 
INFO [2016-08-12 10:57:13.55]: ▸     "hpky"<blob>=0x88271709A9B618608BECEBBAF64759C55254A3B7  "\210'\027\011\251\266\030`\213\354\353\272\366GY\305RT\243\267"
INFO [2016-08-12 10:57:13.55]: ▸     "issu"<blob>=0x3062310B300906035504061302555331133011060355040A130A4150504C4520494E432E31263024060355040B131D4150504C452043455254494649434154494F4E20415554484F52495459311630140603550403130D4150504C4520524F4F54204341  "0b1\0130\011\006\003U\004\006\023\002US1\0230\021\006\003U\004\012\023\012APPLE INC.1&0$\006\003U\004\013\023\035APPLE CERTIFICATION AUTHORITY1\0260\024\006\003U\004\003\023\015APPLE ROOT CA"
INFO [2016-08-12 10:57:13.55]: ▸     "labl"<blob>="Apple Worldwide Developer Relations Certification Authority"
INFO [2016-08-12 10:57:13.55]: ▸     "skid"<blob>=0x88271709A9B618608BECEBBAF64759C55254A3B7  "\210'\027\011\251\266\030`\213\354\353\272\366GY\305RT\243\267"
INFO [2016-08-12 10:57:13.55]: ▸     "snbr"<blob>=0x01DEBCC4396DA010  "\001\336\274\3049m\240\020"
INFO [2016-08-12 10:57:13.55]: ▸     "subj"<blob>=0x308196310B300906035504061302555331133011060355040A0C0A4170706C6520496E632E312C302A060355040B0C234170706C6520576F726C647769646520446576656C6F7065722052656C6174696F6E733144304206035504030C3B4170706C6520576F726C647769646520446576656C6F7065722052656C6174696F6E732043657274696669636174696F6E20417574686F72697479  "0\201\2261\0130\011\006\003U\004\006\023\002US1\0230\021\006\003U\004\012\014\012Apple Inc.1,0*\006\003U\004\013\014#Apple Worldwide Developer Relations1D0B\006\003U\004\003\014;Apple Worldwide Developer Relations Certification Authority"
DEBUG [2016-08-12 10:57:13.87]: Certificate 'T9BKYSDD69.cer' is already installed on this machine
INFO [2016-08-12 10:57:13.88]: 🔒  Successfully encrypted certificates repo

Looking for related GitHub issues on fastlane/fastlane...
Search query: Could not locate the provided keychain. Tried:
	/Users/jonathan/Library/Keychains/login.keychain
	login.keychain

URL: https://api.github.com/search/issues?q=Could%20not%20locate%20the%20provided%20keychain.%20Tried:%0A%09/Users/jonathan/Library/Keychains/login.keychain%0A%09login.keychain+repo:fastlane/fastlane
Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.50.0/lib/fastlane_core/ui/interface.rb:145:in `user_error!': [!] Could not locate the provided keychain. Tried: (FastlaneCore::Interface::FastlaneError)
	/Users/<username>/Library/Keychains/login.keychain
	login.keychain
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.50.0/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.6.2/lib/match/utils.rb:14:in `import'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.6.2/lib/match/runner.rb:63:in `certificate'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.6.2/lib/match/runner.rb:17:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.6.2/lib/match/commands_generator.rb:55:in `block (3 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.50.0/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.6.2/lib/match/commands_generator.rb:121:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.6.2/lib/match/commands_generator.rb:12:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/match-0.6.2/bin/match:6:in `<top (required)>'
	from /usr/local/bin/match:23:in `load'
	from /usr/local/bin/match:23:in `<main>'
```

**Comment by edwardvalentini** [comment] 2016-08-15 20:42
+1 i have the same issue with match on sierra.

**Comment by TKBurner** [comment] 2016-08-22 16:01
@edwardsdl @jmjordan Hi, thanks for reporting this. I reached out to the team here, however I can't guarantee when this will be supported. We aren't testing against Sierra yet.

Thanks!

**Comment by jmjordan** [comment] 2016-08-22 17:56
@TKBurner, no worries. Setting an environment variable for the keychain name isn't a big deal.

**Comment by TKBurner** [comment] 2016-08-22 18:32
@jmjordan Thanks for following up. We are going to look into it here, since the release is coming soon. Have a great day!

**Comment by bassrock** [comment] 2016-09-09 06:34
Is there an update on this with Sierra and Xcode 8 now GM?

**Comment by KrauseFx** [comment] 2016-09-10 00:59
Hey everyone, sorry I don't have Sierra myself yet. Is _fastlane_ actually not working, or is it just the error message that you see?

**Comment by bassrock** [comment] 2016-09-10 01:01
@KrauseFx In sierra the keychain extension changed to keychain-db.  If you manually set the keychain path to use the new extension it works.

**Comment by edwardvalentini** [comment] 2016-09-10 01:04
@KrauseFx if you add something like this to the Fastfile it works:

def keychain_name
  mm=`sw_vers -productVersion | awk -F '.' '{print $2}'`
  if mm.to_i < 12
    "login.keychain"
  else
    "login.keychain-db"
  end
end

**Comment by ohwutup** [comment] 2016-09-12 14:09
Thanks for posting the issue @jmjordan! I am seeing this issue as well, but despite the warning that is printed, everything still works as expected. Is this breaking anyone's current workflow?

**Comment by podkovyrin** [comment] 2016-09-21 16:46
Same here with release version of Sierra. If you do clean install then keychain name is login.keychain-db, if update from previous OS X - login.keychain

**Comment by podkovyrin** [comment] 2016-09-21 19:30
Found temporary workaround: `ln -s ~/Library/Keychains/login.keychain-db ~/Library/Keychains/login.keychain`

**Comment by JagCesar** [comment] 2016-09-27 08:55
Can confirm that symlinking the keychain like @podkovyrin mentioned above is a valid workaround on a clean install of Sierra.

**Comment by larsacus** [comment] 2016-09-27 20:44
I _think_ I'm running into something similar here on Sierra (upgrade from El Cap), but I have _both_ `login.keychain` and `login.keychain-db` in my `~/Library/Keychains/` folder and don't feel comfortable symlinking `-db` to the non-db. So I can't validate the above. 😞

**Comment by TKBurner** [comment] 2016-09-27 20:53
@JagCesar @larsacus I reached out to the core team about prioritizing a better fix for this. Thanks!

**Comment by suparngp** [comment] 2016-09-28 21:17
Just tested @podkovyrin workaround and it works like a charm.

**Comment by jakubprusa** [comment] 2016-10-02 13:36
Hi, I have same problem with  `SecPolicySetValue: One or more parameters passed to a function were not valid.` and walkaround with symlink doesn't work for me

**Comment by trackvia-ios** [comment] 2016-10-04 20:08
We are having the same issue as @larsacus - both exist and we would rather not just delete the `login.keychain` unless it is confirmed that fixes the issue with no side-affects.

For the record, I am able to run `bundle exec fastlane <job>` from my logged in user, but as my jenkins user, I see the issues mentioned above.

Sounds like keychain/permission access is the root of this problem...

**Comment by trackvia-ios** [comment] 2016-10-04 20:12
Also for the record, I attempted to use @edwardvalentini's change to use dynamic `keychain_name` in calls to `match`. That seems to pass the assumed `login.keychain-db` for Sierra OS, but still throws the warnings:

```
security: SecPolicySetValue: One or more parameters passed to a function were not valid.
```

And I believe since those are being output, my `Check Dependencies` step fails during compilation.

**Comment by larsacus** [comment] 2016-10-04 20:13
@trackvia-ios I investigated my particular Sierra config more carefully, and running `security list-keychains` only returned the new `login.keychain-db`:

``` shell
$> security list-keychains
    "~/Library/Keychains/login.keychain-db"
    "/Library/Keychains/System.keychain"
```

So, I moved my old `login.db -> login.db.bak` and did the above symlink and everything seems to be working properly...

**Comment by trackvia-ios** [comment] 2016-10-04 20:17
@larsacus Wow, you are right good sir, great find! I see the same for my keychain list.

Just to confirm, you likely did something like:

```
mv ~/Library/Keychains/login.keychain ~/Library/Keychains/login.keychain.bak`
ln -s ~/Library/Keychains/login.keychain-db ~/Library/Keychains/login.keychain
```

That removes the existing login.keychain so we can create a symlink for the existing -db keychain.

Once you give the go-ahead I'll run commands and confirm fix. Thanks again!

**Comment by larsacus** [comment] 2016-10-04 20:21
@trackvia-ios Yes, that's exactly what I did. The result of `ls -l ~/Library/Keychains` being:

```
lrwxr-xr-x   1 lars.anderson  staff    17B Sep 27 16:05 login.keychain -> login.keychain-db
-rw-r--r--@  1 lars.anderson  staff   1.1M Oct  4 15:10 login.keychain-db
-rw-r--r--@  1 lars.anderson  staff   908K Sep 23 14:54 login.keychain.bak
...
```

I figured if anything went sideways I just put my "backed up" keychain back where it was, but it kind of looks like it migrates it altogether to `keychain-db`

**Comment by trackvia-ios** [comment] 2016-10-04 21:22
@larsacus You are a true lifesaver - that is exactly what was needed to make our Jenkins user and logged in user work together in harmony. 👍 

Gotta love the fastlane community!

**Comment by trackvia-ios** [comment] 2016-10-04 21:44
Just a head's up for others following at home, I am still unfortunately seeing the error:

```
security: SecPolicySetValue: One or more parameters passed to a function were not valid.
```

Running macOS Sierra 10.12 (16A319). 

Continuing to troubleshoot and will keep you all posted if I find solution.

**Comment by KrauseFx** [comment] 2016-10-04 21:45
@trackvia-ios Thanks, I do see that error too on Sierra, I just set this up on the Mac. It seems like this is just a warning, I don't know 100% for sure yet. Do you know by which command this message is caused?

**Comment by trackvia-ios** [comment] 2016-10-04 21:49
Hey @KrauseFx - thanks for jumping in. Happy to help any way possible.

It seems like a warning, as Fastlane eventually completes successfully for just the `match` component.

However, when I attempt to run `gym` to deploy to Crashlytics with the following:

```
gym(scheme: scheme,
configuration: "Release",
export_method: "ad-hoc")
```

**Comment by KrauseFx** [comment] 2016-10-04 21:57
@trackvia-ios Yeah, did you find out which command cause the error message?

**Comment by KrauseFx** [comment] 2016-10-04 22:18
Seems like it's described here https://github.com/fastlane/fastlane/issues/6233#issuecomment-250107604

**Comment by trackvia-ios** [comment] 2016-10-04 23:07
@KrauseFx I believe I've gotten around the initial issue by using the symlink for the variance in the keychain on Sierra. However, here's a little more insight into the specific failure I'm now seeing.

`fastlane` version: `1.104.0`
`match` version: `0.8.0`
`gym` version: `1.10.0`

```bash
+-----------------------+-------------------------------------------------+
|                         Summary for match 0.8.0                         |
+-----------------------+-------------------------------------------------+
| type                  | adhoc                                           |
| app_identifier        | *                                               |
| keychain_name         | login.keychain-db                               |
| git_url               | git@github.com:<Redacted>.git                   |
| username              | <Redacted>                                      |
| git_branch            | master                                          |
| readonly              | false                                           |
| team_id               | <Redacted>                                      |
| team_name             | <Redacted>                                      |
| verbose               | false                                           |
| force                 | false                                           |
| shallow_clone         | false                                           |
| force_for_new_devices | false                                           |
| skip_docs             | false                                           |
+-----------------------+-------------------------------------------------+
```

After compiling project files, we see:

```bash
▸ Generating '<AppName>.app.dSYM'
▸ Running script 'Copy Pods Resources'
▸ Running script 'Run Script'
▸ Touching <AppName>.app
❌  error: Task failed with exit 1 signal 0 {
** ARCHIVE FAILED **

The following build commands failed:
CopySwiftLibs /Users/jenkins/Library/Developer/Xcode/DerivedData/<ProjectName>-hgehrmmupuvjzhghhemrcxpuicsd/Build/Intermediates/ArchiveIntermediates/<AppName>/InstallationBuildProductsLocation/Applications/<AppName>.app
ERROR [2016-10-04 16:56:30.33]: Exit status: 65
INFO [2016-10-04 16:56:30.34]: EXCEPTION===> Error building the application - see the log above
```

Here's the specific stacktrace related to the calls to `gym`, as identified above:

```bash
from /Users/jenkins/.rvm/gems/ruby-2.2.4/gems/fastlane_core-0.52.0/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
from /Users/jenkins/.rvm/gems/ruby-2.2.4/gems/gym-1.10.0/lib/gym/error_handler.rb:53:in `handle_build_error'
from /Users/jenkins/.rvm/gems/ruby-2.2.4/gems/gym-1.10.0/lib/gym/runner.rb:101:in `block in build_app'
from /Users/jenkins/.rvm/gems/ruby-2.2.4/gems/fastlane_core-0.52.0/lib/fastlane_core/command_executor.rb:88:in `call'
from /Users/jenkins/.rvm/gems/ruby-2.2.4/gems/fastlane_core-0.52.0/lib/fastlane_core/command_executor.rb:88:in `execute'
from /Users/jenkins/.rvm/gems/ruby-2.2.4/gems/gym-1.10.0/lib/gym/runner.rb:97:in `build_app'
from /Users/jenkins/.rvm/gems/ruby-2.2.4/gems/gym-1.10.0/lib/gym/runner.rb:12:in `run'
from /Users/jenkins/.rvm/gems/ruby-2.2.4/gems/gym-1.10.0/lib/gym/manager.rb:10:in `work'
from /Users/jenkins/.rvm/gems/ruby-2.2.4/gems/fastlane-1.104.0/lib/fastlane/actions/gym.rb:22:in `run'
```

Perhaps I could try unlocking the keychain via `unlock_keychain` right before we attempt to call `gym`? Could that be causing the issue? It appears my login keychain for the jenkins user has all certs/profiles necessary...

Hope that helps! Let me know if I can provide any more diagnostics!

**Comment by ericlewis** [comment] 2016-10-04 23:14
@trackvia-ios i am also have a status code 65 exit in the same place.

**Comment by KrauseFx** [comment] 2016-10-05 02:02
I can finally reproduce the error, and I'm working on a fix 👍

**Comment by KrauseFx** [comment] 2016-10-05 03:10
I just pushed https://github.com/fastlane/fastlane/pull/6389, which will fix this issue. We'll push a release tomorrow 🚀

**Comment by JagCesar** [comment] 2016-10-05 09:19
Where are the rocket and sparkles reaction-emoji when you need them!? 😂

**Closed** 2016-10-05 14:31 UTC
Labels: feature, match, question, you can do this
