### ISSUE TITLE
"Could not find latest API Key from the Dev Portal - the server might be slow right now"

### ISSUE THREAD

**Issue by jpmcglone** [fastlane/fastlane#4181] opened 2016-04-13 03:48 UTC
I'm getting this on Circle CI when running cert, but not locally.
"Could not find latest API Key from the Dev Portal - the server might be slow right now"

```
[20:44:46]: ------------------
[20:44:46]: --- Step: cert ---
[20:44:46]: ------------------

+---------------+---------------------------------------------------+
|                      Summary for cert 1.4.0                       |
+---------------+---------------------------------------------------+
| development   | false                                             |
| force         | false                                             |
| username      | REDACTED                              |
| team_id       | REDACTED                                        |
| keychain_path | /Users/distiller/Library/Keychains/login.keychain |
+---------------+---------------------------------------------------+

[20:44:47]: Starting login with user 'REDACTED'
[20:44:48]: Variable Dump:
[20:44:48]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios testflight"}
[20:44:48]: Could not find latest API Key from the Dev Portal - the server might be slow right now

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 2    | team_id          | 0           |
| 3    | cert             | 1           |
+------+------------------+-------------+

[20:44:48]: fastlane finished with errors
```

This works locally, and I'm guessing it's because its finding the cert in the cache. 

I need it to work on Circle though. Any help would be GREATLY appreciated :D Did something change with the way you guys retrieved the API?  Does Circle need to update its install of fastlane?

**Comment by KrauseFx** [comment] 2016-04-13 05:35
I can't reproduce this error. Does it work locally for you? Could you run the `cert` directly using `cert --verbose` to get a more detailed output?

**Comment by jpmcglone** [comment] 2016-04-13 22:10
Well, the issue only happens when it runs on Circle (and I don't want to risk clearing my caches locally, as its the easiest way for me to push our build).

Is there a way to run just the cert portion of my fastlane w/ verbose on circle?

**Comment by Dahlgren** [comment] 2016-04-14 12:47
Probably related to #4113 which is resolved by #4115. Solved the issue with `Could not find latest API Key from the Dev Portal` for me.

**Comment by TKBurner** [comment] 2016-04-14 14:11
Thanks @Dahlgren for updating! 👍

**Comment by lucasfeliciano** [comment] 2016-04-21 10:10
Having the same issue.

I see the fix was merged but even if I upgrade fastlane I still get this issue

**Comment by TKBurner** [comment] 2016-04-21 13:24
Hi @lucasfeliciano! Great to hear from you. Can you run cert --verbose and share the output? That'll help us have a look. Have a great day!

**Comment by lucasfeliciano** [comment] 2016-04-22 10:35
I made this changes #4115 straight to my installed gem and it is working now.

Just saying that you should release the new version of the gem with that fix. :)

**Comment by Dahlgren** [comment] 2016-04-22 10:44
That code is already in the released gem, make sure to update your Gemfile.lock if you use bundler and that all your gems are updated.

**Comment by TKBurner** [comment] 2016-04-22 18:25
@lucasfeliciano Thanks for following up. We've now merged this change. Really glad to have you using Fastlane! 👍

**Closed by TKBurner** 2016-04-22 18:25 UTC
Labels: awaiting-reply, cert

**Comment by itinance** [comment] 2016-05-01 16:33
Having the same issue right now. Why is this one closed?

**Comment by lucasfeliciano** [comment] 2016-05-02 12:59
I realised that I was using my system version of ruby instead of the ruby from the RVM.
So when I tried to update fastlane **without `sudo`** I received a message that fastlane was already up to date. Which I don't think it should be the expected behaviour.

Once I ran the update command using `sudo` it was updated and the bug was fixed.

**Comment by TKBurner** [comment] 2016-05-03 14:26
Hi @lucasfeliciano Awesome, glad to hear the update resolved this for you. Thanks for using Fastlane 👍
