### ISSUE TITLE
Deploying screenshots -- incremental upload

### ISSUE THREAD

**Issue by fulldecent** [fastlane/fastlane#4312] opened 2016-04-21 22:51 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Test case:

Deploy an app with lots of screenshots and (for some reason) a binary that wont be accepted.

Expected:

On the second time deploying, screenshots which were already uploaded do not need to be uploaded again.

Actual:

Every deployment uploads all screenshots again.

Notes:

Uploading screenshots takes me over 30 minutes.

**Comment by TKBurner** [comment] 2016-04-22 19:19
@fulldecent Thanks for reaching out. We are going to treat this as a feature request since right now you are seeing expected behavior. We'll update on this thread as relevant. Thanks!

**Comment by lacostej** [comment] 2016-04-24 09:38
@fulldecent @TKBurner this feature is implemented and it undergoing review. See #3755

**Comment by TKBurner** [comment] 2016-04-25 20:41
Thanks for pointing this out @lacostej! Always awesome to see your contributions. I'm going to close this out since we are working on implementing this on the PR right now 👍

**Closed by TKBurner** 2016-04-25 20:41 UTC
Labels: feature, snapshot
