### ISSUE TITLE
Can't run "deliver" (Your app preview can't be uploaded because you have selected to use an app preview from a larger display size.)

### ISSUE THREAD

**Issue by exavi** [fastlane/fastlane#14589] opened 2019-04-14 14:13 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Can't deliver app to iOS AppStore due to app preview resolution errors.

I have tried delivering with various methods, using skip_screenshots=true, various flags for deliver, etc, and can't get it to work.

I have also tried deleting *all screenshots and previews* from AppStore Connect, so it does not list anything and I keep getting the same error message saying that there are invalid resolutions when really there isn't anything.

I don't know what to do, I need to deliver this. Is there a way to force it?

##### Command executed
tried:
bundle exec fastlane ios appstore
bundle exec fastlane deliver
bundle exec fastlane deliver --overwrite_screenshots

##### Complete output when running fastlane, including the stack trace and command used
[!] The request could not be completed because:
	Your app preview can't be uploaded because you have selected to use an app preview from a larger display size. Your app preview can't be uploaded because you have selected to use an app preview from a larger display size. Your app preview can't be uploaded because you have selected to use an app preview from a larger display size. Your app preview can't be uploaded because you have selected to use an app preview from a larger display size. Your app preview can't be uploaded because you have selected to use an app preview from a larger display size.

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.3                                     |
| Ruby                        | 2.5.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.20.1 (Apple Git-117)          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.14.3 (18D109)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.5.1/lib            |
| OpenSSL Version             | OpenSSL 1.0.2o  27 Mar 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.2                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | es_ES.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.60.1"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
    # carthage
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "<redacted>", workspace: "<redacted>.xcworkspace")
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    # match(type: "appstore")
    # snapshot
    gym(
        scheme: "<redacted>", 
        workspace: "<redacted>.xcworkspace",
		clean: true,
		export_method: "app-store",
		export_options: {
		      provisioningProfiles: { 
		        "<redacted>" => "AppStore Distribution"
		      }
		}
    )
    deliver(force: true, skip_screenshots: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "<redacted>" # The bundle identifier of your app
apple_id "<redacted>" # Your Apple email address

team_id "<redacted>" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.120.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| bundler                   | 1.16.1       |
| CFPropertyList            | 3.0.0        |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.10       |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.5.0        |
| cocoapods-deintegrate     | 1.0.2        |
| cocoapods-downloader      | 1.2.0        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.5        |
| ruby-macho                | 1.1.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.2        |
| cocoapods                 | 1.5.0        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.7.2        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.63.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.5        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.0        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.2.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.5.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.1        |
| tty-spinner               | 0.9.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2019-04-14**
</details>

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by exavi** [comment] 2019-04-14 14:19
forgot to mention that I have also run

`bundle exec fastlane deliver download_screenshots`

to confirm whether there are still screenshots or not (even though I have deleted them all) and it does not download anything, so really there are no screenshots uploaded and yet it keeps whining about something (that does not exist) being of a larger display size.

**Comment by janpio** [comment] 2019-04-14 18:33
Please add the _complete_ output you are getting when running these commands. 
Are you only trying to upload an app binary or is there actual metadata?

**Comment by exavi** [comment] 2019-04-16 08:14
I was trying to get anything added, app binary or binary + metadata, at the time I did not mind about screenshots as I needed to get a beta out quickly.

I think that this may be an issue on Apple's side and not on fastlane/deliver, but, the fact that it did not allow me to upload even the binary after disabling all other uploads makes me think that it might still be an issue with deliver?

After going through the AppStore/iTunes Connect website many, many times refreshing the screenshots in their "media manager" staring at a blank screen with no images nor previews, disabling and re-enabling languages, and playing with all "re-use screenshots from XXX-inch device" checkboxes in one of these various dodgy-webpage refreshes some videos *that were never visible on the AppStore nor had they been in the app version manager* appeared, I deleted them and the upload went through fine with fastlane/deliver. 

This makes me think that the "error" was correct in saying that there were app previews of invalid resolutions etc, but why that would stop a binary upload (with forced-delivery enabled) is beyond me.

I was using Apple's own browser, Safari (latest version), to view the website and the videos magically appeared.

I'm going to try to find out why AppStore Connect complained in the first place since videos were made following their instructions to the dot, both in terms of codec and resolutions, it may have something to do with the fact that they were added months ago when Apple first introduced new resolutions for the videos of the 2018 iPad Pro(s) and checks on their side may have been flaky at the time. What's strange is that it never errored before and the videos never showed up on the AppStore itself.

I'm not sure if any of this helps at all.

**Comment by janpio** [comment] 2019-04-16 09:17
> why that would stop a binary upload (with forced-delivery enabled) is beyond me.

Because deliver currently is not structured in a way that makes it easy to not touch metadata, even when just uploading a binary. There are pull requests and issues that will fix this, but they haven't been reviewed/merged yet.

**Comment by xpy** [comment] 2019-05-10 11:19
I encountered the same issue, also mentioned here fastlane/fastlane#10564 and here fastlane/fastlane#11022 . I am not sure that they are 100% related but it seems to. When Fastlane tries to update the data for any reason, it first set the `scaled` flag to `true` for display_families without screenshots, as seen here:
https://github.com/fastlane/fastlane/blob/1abd9682eac3e408cf1576c7526bb1d8582deacf/spaceship/lib/spaceship/tunes/app_version.rb#L710-L726

It doesn't take in account though, that a display_family might have a trailer and **no** screenshots, that means that upon save, said display_family will try to be saved with a `scaled` flag set to `true` **and** a trailer (app preview), which then leads to the error "Your app preview can't be uploaded because you have selected to use an app preview from a larger display size."

Fiddling around with the code, I manage to have it working by just adding the lines:
```
next if device_language_details["trailers"].nil?
next if device_language_details["trailers"]["value"].count > 0
```
after the screenshot check, to also check if there is a trailer present.

It works for me (of course) but is this the right solution? And if it is, how can I push it through as a bugfix?

**Comment by janpio** [comment] 2019-05-10 11:25
Just create a Pull Request for your change, and we will have a better look at it 🚀

**Comment by yixiang** [comment] 2019-05-18 14:30
Confirmed that xpy's fix solved my problem as well. Please create a pull request.

**Comment by xpy** [comment] 2019-05-20 06:37
@yixiang there is already a PR fastlane/fastlane#14738

**Comment by harryworld** [comment] 2019-05-27 23:00
Thanks @xpy It works for me.

**Closed** 2019-07-05 17:31 UTC
Labels: status: has-pr, status: waiting-for-reply, tool: deliver
