### ISSUE TITLE
Failed operation for adding testers to testflight

### ISSUE THREAD

**Issue by vspac** [fastlane/fastlane#10930] opened 2017-11-17 09:45 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Running `fastlane pilot add "some@email.com" -g "MyGroup" -a "app.id"` throws
```
[!] Some operations failed: <?xml version="1.0" encoding="UTF-8"?>
<String>There is no route for the path 'users/pre/int'.</String>
```

It seems that Apple changed it's API and the url fastlane is using for Internal testers is wrong:
```
{
  index: "ra/users/pre/int",
  index_by_app: "ra/user/internalTesters/#{app_id}/",
  create: nil,
  delete: nil,
  update_by_app: "ra/user/internalTesters/#{app_id}/"
}
```
### Environment
fastlane 2.64.0

**Comment by michaelochs** [comment] 2017-11-17 16:56
I am seeing the same error with boarding. My heroku is running on latest master.

**Comment by vspac** [comment] 2017-11-17 16:59
@michaelochs it seems that Apple released a new version of their API. Hopefuly fastlane/spaceship will be updated soon.

**Comment by taquitos** [comment] 2017-11-17 18:02
Yup, this is a known issue, still working on a fix 🎉

**Comment by gcox** [comment] 2017-11-20 14:50
PR #10921 looks like it was supposed to fix this, but I get the same error even after updating my boarding install to use:

```
gem 'fastlane', :git => 'https://github.com/fastlane/fastlane.git', :branch => 'master'
```

**Comment by ForestRingGames** [comment] 2017-11-20 16:20
We're also facing the same issue right now.

**Comment by taquitos** [comment] 2017-11-20 16:35
@ForestRingGames go ahead and give it another try now. We've since released a new version of _fastlane_ and also just bumped the _fastlane_ version requirement in boarding.

**Comment by ForestRingGames** [comment] 2017-11-20 16:43
@taquitos  Okay, looking forward to the fix! Will try as soon as you got something!

**Comment by taquitos** [comment] 2017-11-21 00:37
@ForestRingGames we just released 2.66.0 🎉

**Comment by pcsanwald** [comment] 2017-11-21 01:19
I just tried using 2.66.0 using `bundle exec fastlane pilot add "whatever@gmail.com" -a $FASTLANE_APP_IDENTIFIER --username $FASTLANE_ITUNES_CONNECT_USERNAME --first_name "PaulTest" --last_name "SanwaldTest" --groups "External Testers"`

and it doesn't seem to be matching the group name. This feels like maybe an error I'm making, but, I _think_ I'm following the documentation for `fastlane pilot add --help` correctly. Am I making a mistake? 

Thanks a lot for this release! super fast and awesome.

**Comment by michaelochs** [comment] 2017-11-21 08:12
After updating Heroku to latest master, I now get a different error in boarding:
> Something went wrong, please contact the application owner: uninitialized constant Spaceship::Tunes::Tester

Do I need to update the configuration in any way as well?

**Comment by gcox** [comment] 2017-11-21 14:04
@taquitos After pulling in the latest version of Boarding, adding testers is partially working. Testers actually do get added, invite gets sent, but the UI shows the `uninitialized constant Spaceship::Tunes::Tester` error message. So, at least testers are actually added 👍 

Here's the log of the event in case it helps

```
app[web.1]: Started POST "/submit" for <REDACTED> at 2017-11-21 13:54:52 +0000
app[web.1]: Processing by InviteController#submit as HTML
app[web.1]:   Parameters: {"utf8"=>"✓", "authenticity_token"=>"<REDACTED>", "first_name"=>"<REDACTED>", "last_name"=>"<REDACTED>", "email"=>"<REDACTED>"}
app[web.1]: Creating a new tester: <REDACTED> - <REDACTED>
app[web.1]: Successfully added tester: <REDACTED> to app: Downcast
heroku[router]: at=info method=POST path="/submit" host=ios-beta.downcast.fm request_id=<REDACTED> fwd="<REDACTED>" dyno=web.1 connect=0ms service=3535ms status=200 bytes=3020 protocol=http
app[web.1]: Could not add <REDACTED> to app: Downcast
app[web.1]: #<NameError: uninitialized constant Spaceship::Tunes::Tester>
app[web.1]: /app/app/services/boarding_service.rb:64:in `add_tester'
app[web.1]: /app/app/controllers/invite_controller.rb:92:in `create_and_add_tester'
app[web.1]: /app/app/controllers/invite_controller.rb:75:in `submit'
```

**Comment by taquitos** [comment] 2017-11-21 15:33
🤦‍♂️

**Comment by taquitos** [comment] 2017-11-21 15:35
fix here: https://github.com/fastlane/boarding/pull/193

**Comment by gcox** [comment] 2017-11-21 15:43
Of course heroku is down now :rage4:

**Comment by taquitos** [comment] 2017-11-21 15:46
@gcox 🤕

**Comment by gcox** [comment] 2017-11-21 16:01
Confirmed this is resolved for me now. Thanks for getting it fixed quickly!

**Comment by pcsanwald** [comment] 2017-11-26 15:47
I've just upgraded to 2.66.2, and am still seeing an error when I call:

`bundle exec fastlane pilot add "pcsanwald+fastlane@gmail.com" -a $FASTLANE_APP_IDENTIFIER --username $FASTLANE_ITUNES_CONNECT_USERNAME --first_name "PaulTest" --last_name "SanwaldTest" --groups "External Testers"`

am I doing something wrong, or is this a bug? as of 2.33, fastlane worked fine with no group specified. but since 2.66, it tells me I need to specify a group.

**Comment by spanage** [comment] 2017-11-28 20:43
@pcsanwald and I discovered that our issue was due to the space in the group name. Changing the group name to "ExternalTesters" solved the issue.

**Comment by janpio** [comment] 2017-11-28 22:24
Which would mean there probably is still a bug for group names with spaces somehow. Could you create a new issue for that please @spanage? Thanks.

**Comment by spanage** [comment] 2017-11-29 02:57
Will do. (Wasn’t sure if I was missing some magical escape character 😬)

**Comment by joshdholtz** [comment] 2018-03-09 23:43
Closing this issue as it seems like things were fixed! Comment back if things are still an issue and we can reopen 😊

**Closed by joshdholtz** 2018-03-09 23:43 UTC
Labels: status: waiting-for-reply
