### ISSUE TITLE
FastlaneCore::BuildWatcher found more than 1 matching build - it's back again in this rc1 version.

### ISSUE THREAD

**Issue by dcristolovean** [fastlane/fastlane#16663] opened 2020-06-24 13:41 UTC
### New Release Candidate Issue Checklist

- [x] Updated fastlane to the latest release candidate version (2.150.0.rcX)
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Information

- Breaking version: [`2.150.0.rc1`]
- Last working version: [before this rc1]
- State of app: [`Prepare for Submission`]
- First version of app?: [`No`]

### Issue Description

Getting an error while deploying my app for review. I found information about this in some 2019 topics, but it said it was fixed. Seems like it's back:

[12:54:17]: Selecting the latest build...
[12:54:17]: Waiting for processing on... app_id: 1406830700, app_version: , build_version: , platform: IOS
[12:54:18]: FastlaneCore::BuildWatcher found more than 1 matching build: 
4.0.30(767) for IOS - VALID
3.6.29(767) for IOS - VALID
...... and so on

##### Complete output when running fastlane, including the stack trace and command used

 Summary for precheck 2.150.0.rc1                |
+--------------------------+------------------------------------+
| default_rule_level       | warn                               |
| include_in_app_purchases | true                               |
| app_identifier           | xxx |
| username                 | [REDACTED]             |
+--------------------------+------------------------------------+
[12:53:58]: Checking app for precheck rule violations
[12:54:03]: Reading in-app purchases. If you have a lot, this might take a while
[12:54:03]: You can disable IAP checking by setting the `include_in_app_purchases` flag to `false`
[12:54:04]: Done reading in-app purchases
[12:54:05]: ✅  Passed: No negative  sentiment
[12:54:05]: ✅  Passed: No placeholder text
[12:54:05]: ✅  Passed: No mentioning  competitors
[12:54:05]: ✅  Passed: No future functionality promises
[12:54:05]: ✅  Passed: No words indicating test content
[12:54:05]: ✅  Passed: No curse words
[12:54:05]: ✅  Passed: No words indicating your IAP is free
[12:54:05]: ✅  Passed: Incorrect, or missing copyright date
[12:54:17]: ✅  Passed: No broken urls
[12:54:17]: precheck 👮‍♀️ 👮  finished without detecting any potential problems 🛫
[12:54:17]: Selecting the latest build...
[12:54:17]: Waiting for processing on... app_id: xxx, app_version: , build_version: , platform: IOS
[12:54:18]: FastlaneCore::BuildWatcher found more than 1 matching build: 
4.0.30(767) for IOS - VALID
3.6.29(767) for IOS - VALID
3.6.12(767) for IOS - VALID

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Spaceship Logs

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.5                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.5 (19F101)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.5                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

FASTLANE FILES REMOVED

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer

```
</details>

**No Appfile found**


### fastlane gems

| Gem      | Version     | Update-Status |
| -------- | ----------- | ------------- |
| fastlane | 2.150.0.rc1 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status |
| ----------------------------------------- | ------- | ------------- |
| fastlane-plugin-versioning                | 0.4.3   | ✅ Up-To-Date  |
| fastlane-plugin-firebase_app_distribution | 0.1.4   | ✅ Up-To-Date  |


<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.3.0        |
| bundler                                   | 1.17.3       |
| etc                                       | 1.0.1        |
| forwardable                               | 1.2.0        |
| CFPropertyList                            | 3.0.2        |
| concurrent-ruby                           | 1.1.6        |
| i18n                                      | 0.9.5        |
| minitest                                  | 5.14.1       |
| thread_safe                               | 0.3.6        |
| tzinfo                                    | 1.2.7        |
| activesupport                             | 4.2.11.3     |
| public_suffix                             | 4.0.5        |
| addressable                               | 2.7.0        |
| httpclient                                | 2.8.3        |
| json                                      | 2.3.0        |
| algoliasearch                             | 1.27.3       |
| atomos                                    | 0.1.3        |
| aws-eventstream                           | 1.1.0        |
| aws-partitions                            | 1.332.0      |
| aws-sigv4                                 | 1.2.0        |
| jmespath                                  | 1.4.0        |
| aws-sdk-core                              | 3.100.0      |
| aws-sdk-accessanalyzer                    | 1.8.1        |
| aws-sdk-acm                               | 1.32.1       |
| aws-sdk-acmpca                            | 1.25.1       |
| aws-sdk-alexaforbusiness                  | 1.37.1       |
| aws-sdk-amplify                           | 1.18.1       |
| aws-sdk-apigateway                        | 1.44.0       |
| aws-sdk-apigatewaymanagementapi           | 1.15.1       |
| aws-sdk-apigatewayv2                      | 1.22.1       |
| aws-sdk-appconfig                         | 1.7.1        |
| aws-sdk-applicationautoscaling            | 1.41.1       |
| aws-sdk-applicationdiscoveryservice       | 1.28.1       |
| aws-sdk-applicationinsights               | 1.11.1       |
| aws-sdk-appmesh                           | 1.25.1       |
| aws-sdk-appstream                         | 1.42.1       |
| aws-sdk-appsync                           | 1.27.1       |
| aws-sdk-athena                            | 1.28.1       |
| aws-sdk-augmentedairuntime                | 1.6.1        |
| aws-sdk-autoscaling                       | 1.38.1       |
| aws-sdk-autoscalingplans                  | 1.24.1       |
| aws-sdk-backup                            | 1.16.1       |
| aws-sdk-batch                             | 1.32.1       |
| aws-sdk-budgets                           | 1.31.1       |
| aws-sdk-chime                             | 1.29.1       |
| aws-sdk-cloud9                            | 1.24.1       |
| aws-sdk-clouddirectory                    | 1.25.1       |
| aws-sdk-cloudformation                    | 1.37.1       |
| aws-sdk-cloudfront                        | 1.30.1       |
| aws-sdk-cloudhsm                          | 1.23.1       |
| aws-sdk-cloudhsmv2                        | 1.24.1       |
| aws-sdk-cloudsearch                       | 1.21.1       |
| aws-sdk-cloudsearchdomain                 | 1.18.1       |
| aws-sdk-cloudtrail                        | 1.24.1       |
| aws-sdk-cloudwatch                        | 1.39.1       |
| aws-sdk-cloudwatchevents                  | 1.30.1       |
| aws-sdk-cloudwatchlogs                    | 1.32.1       |
| aws-sdk-codeartifact                      | 1.0.1        |
| aws-sdk-codebuild                         | 1.53.1       |
| aws-sdk-codecommit                        | 1.34.1       |
| aws-sdk-codedeploy                        | 1.32.1       |
| aws-sdk-codeguruprofiler                  | 1.6.1        |
| aws-sdk-codegurureviewer                  | 1.7.1        |
| aws-sdk-codepipeline                      | 1.32.1       |
| aws-sdk-codestar                          | 1.22.1       |
| aws-sdk-codestarconnections               | 1.5.1        |
| aws-sdk-codestarnotifications             | 1.4.1        |
| aws-sdk-cognitoidentity                   | 1.23.1       |
| aws-sdk-cognitoidentityprovider           | 1.37.1       |
| aws-sdk-cognitosync                       | 1.20.1       |
| aws-sdk-comprehend                        | 1.33.1       |
| aws-sdk-comprehendmedical                 | 1.18.1       |
| aws-sdk-computeoptimizer                  | 1.4.1        |
| aws-sdk-configservice                     | 1.46.1       |
| aws-sdk-connect                           | 1.26.1       |
| aws-sdk-connectparticipant                | 1.4.1        |
| aws-sdk-costandusagereportservice         | 1.22.1       |
| aws-sdk-costexplorer                      | 1.43.1       |
| aws-sdk-databasemigrationservice          | 1.35.1       |
| aws-sdk-dataexchange                      | 1.5.1        |
| aws-sdk-datapipeline                      | 1.20.1       |
| aws-sdk-datasync                          | 1.21.1       |
| aws-sdk-dax                               | 1.23.1       |
| aws-sdk-detective                         | 1.7.1        |
| aws-sdk-devicefarm                        | 1.34.1       |
| aws-sdk-directconnect                     | 1.31.1       |
| aws-sdk-directoryservice                  | 1.29.1       |
| aws-sdk-dlm                               | 1.30.1       |
| aws-sdk-docdb                             | 1.18.1       |
| aws-sdk-dynamodb                          | 1.49.1       |
| aws-sdk-dynamodbstreams                   | 1.20.1       |
| aws-sdk-ebs                               | 1.5.1        |
| aws-sdk-ec2                               | 1.166.1      |
| aws-sdk-ec2instanceconnect                | 1.7.1        |
| aws-sdk-ecr                               | 1.31.1       |
| aws-sdk-ecs                               | 1.65.0       |
| aws-sdk-efs                               | 1.30.1       |
| aws-sdk-eks                               | 1.38.1       |
| aws-sdk-elasticache                       | 1.37.1       |
| aws-sdk-elasticbeanstalk                  | 1.32.1       |
| aws-sdk-elasticinference                  | 1.6.1        |
| aws-sdk-elasticloadbalancing              | 1.23.1       |
| aws-sdk-elasticloadbalancingv2            | 1.45.1       |
| aws-sdk-elasticsearchservice              | 1.37.1       |
| aws-sdk-elastictranscoder                 | 1.22.1       |
| aws-sdk-emr                               | 1.30.1       |
| aws-sdk-eventbridge                       | 1.8.1        |
| aws-sdk-firehose                          | 1.29.1       |
| aws-sdk-fms                               | 1.27.1       |
| aws-sdk-forecastqueryservice              | 1.6.1        |
| aws-sdk-forecastservice                   | 1.6.1        |
| aws-sdk-frauddetector                     | 1.5.1        |
| aws-sdk-fsx                               | 1.21.1       |
| aws-sdk-gamelift                          | 1.32.1       |
| aws-sdk-glacier                           | 1.30.1       |
| aws-sdk-globalaccelerator                 | 1.19.1       |
| aws-sdk-glue                              | 1.58.1       |
| aws-sdk-greengrass                        | 1.32.1       |
| aws-sdk-groundstation                     | 1.9.1        |
| aws-sdk-guardduty                         | 1.35.1       |
| aws-sdk-health                            | 1.26.1       |
| aws-sdk-iam                               | 1.40.1       |
| aws-sdk-imagebuilder                      | 1.9.0        |
| aws-sigv2                                 | 1.0.1        |
| aws-sdk-importexport                      | 1.20.1       |
| aws-sdk-inspector                         | 1.27.1       |
| aws-sdk-iot                               | 1.51.1       |
| aws-sdk-iot1clickdevicesservice           | 1.22.1       |
| aws-sdk-iot1clickprojects                 | 1.22.1       |
| aws-sdk-iotanalytics                      | 1.30.1       |
| aws-sdk-iotdataplane                      | 1.21.0       |
| aws-sdk-iotevents                         | 1.16.1       |
| aws-sdk-ioteventsdata                     | 1.9.1        |
| aws-sdk-iotjobsdataplane                  | 1.21.1       |
| aws-sdk-iotsecuretunneling                | 1.4.1        |
| aws-sdk-iotsitewise                       | 1.5.1        |
| aws-sdk-iotthingsgraph                    | 1.8.1        |
| aws-sdk-kafka                             | 1.22.1       |
| aws-sdk-kendra                            | 1.7.1        |
| aws-sdk-kinesis                           | 1.24.1       |
| aws-sdk-kinesisanalytics                  | 1.25.1       |
| aws-sdk-kinesisanalyticsv2                | 1.17.1       |
| aws-sdk-kinesisvideo                      | 1.26.1       |
| aws-sdk-kinesisvideoarchivedmedia         | 1.25.1       |
| aws-sdk-kinesisvideomedia                 | 1.22.1       |
| aws-sdk-kinesisvideosignalingchannels     | 1.4.1        |
| aws-sdk-kms                               | 1.34.1       |
| aws-sdk-lakeformation                     | 1.5.1        |
| aws-sdk-lambda                            | 1.43.1       |
| aws-sdk-lambdapreview                     | 1.20.1       |
| aws-sdk-lex                               | 1.27.1       |
| aws-sdk-lexmodelbuildingservice           | 1.32.0       |
| aws-sdk-licensemanager                    | 1.15.1       |
| aws-sdk-lightsail                         | 1.33.1       |
| aws-sdk-machinelearning                   | 1.21.1       |
| aws-sdk-macie                             | 1.21.1       |
| aws-sdk-macie2                            | 1.3.1        |
| aws-sdk-managedblockchain                 | 1.12.1       |
| aws-sdk-marketplacecatalog                | 1.4.1        |
| aws-sdk-marketplacecommerceanalytics      | 1.24.1       |
| aws-sdk-marketplaceentitlementservice     | 1.20.1       |
| aws-sdk-marketplacemetering               | 1.26.1       |
| aws-sdk-mediaconnect                      | 1.23.1       |
| aws-sdk-mediaconvert                      | 1.51.1       |
| aws-sdk-medialive                         | 1.47.1       |
| aws-sdk-mediapackage                      | 1.29.1       |
| aws-sdk-mediapackagevod                   | 1.15.1       |
| aws-sdk-mediastore                        | 1.26.1       |
| aws-sdk-mediastoredata                    | 1.23.1       |
| aws-sdk-mediatailor                       | 1.28.1       |
| aws-sdk-migrationhub                      | 1.25.1       |
| aws-sdk-migrationhubconfig                | 1.5.1        |
| aws-sdk-mobile                            | 1.20.1       |
| aws-sdk-mq                                | 1.28.1       |
| aws-sdk-mturk                             | 1.23.1       |
| aws-sdk-neptune                           | 1.25.1       |
| aws-sdk-networkmanager                    | 1.4.1        |
| aws-sdk-opsworks                          | 1.25.1       |
| aws-sdk-opsworkscm                        | 1.35.1       |
| aws-sdk-organizations                     | 1.42.1       |
| aws-sdk-outposts                          | 1.6.1        |
| aws-sdk-personalize                       | 1.14.1       |
| aws-sdk-personalizeevents                 | 1.8.1        |
| aws-sdk-personalizeruntime                | 1.12.1       |
| aws-sdk-pi                                | 1.20.1       |
| aws-sdk-pinpoint                          | 1.42.1       |
| aws-sdk-pinpointemail                     | 1.20.1       |
| aws-sdk-pinpointsmsvoice                  | 1.17.1       |
| aws-sdk-polly                             | 1.31.1       |
| aws-sdk-pricing                           | 1.20.1       |
| aws-sdk-qldb                              | 1.6.1        |
| aws-sdk-qldbsession                       | 1.5.1        |
| aws-sdk-quicksight                        | 1.22.1       |
| aws-sdk-ram                               | 1.18.1       |
| aws-sdk-rds                               | 1.86.1       |
| aws-sdk-rdsdataservice                    | 1.19.1       |
| aws-sdk-redshift                          | 1.44.1       |
| aws-sdk-rekognition                       | 1.39.1       |
| aws-sdk-resourcegroups                    | 1.25.1       |
| aws-sdk-resourcegroupstaggingapi          | 1.27.1       |
| aws-sdk-robomaker                         | 1.25.1       |
| aws-sdk-route53                           | 1.36.1       |
| aws-sdk-route53domains                    | 1.23.1       |
| aws-sdk-route53resolver                   | 1.15.1       |
| aws-sdk-s3                                | 1.69.1       |
| aws-sdk-s3control                         | 1.20.1       |
| aws-sdk-sagemaker                         | 1.60.1       |
| aws-sdk-sagemakerruntime                  | 1.23.1       |
| aws-sdk-savingsplans                      | 1.6.1        |
| aws-sdk-schemas                           | 1.5.1        |
| aws-sdk-secretsmanager                    | 1.37.1       |
| aws-sdk-securityhub                       | 1.27.1       |
| aws-sdk-serverlessapplicationrepository   | 1.28.1       |
| aws-sdk-servicecatalog                    | 1.41.1       |
| aws-sdk-servicediscovery                  | 1.25.1       |
| aws-sdk-servicequotas                     | 1.7.1        |
| aws-sdk-ses                               | 1.31.1       |
| aws-sdk-sesv2                             | 1.6.1        |
| aws-sdk-shield                            | 1.27.1       |
| aws-sdk-signer                            | 1.22.1       |
| aws-sdk-simpledb                          | 1.20.1       |
| aws-sdk-sms                               | 1.21.1       |
| aws-sdk-snowball                          | 1.28.1       |
| aws-sdk-sns                               | 1.25.1       |
| aws-sdk-sqs                               | 1.27.1       |
| aws-sdk-ssm                               | 1.81.1       |
| aws-sdk-sso                               | 1.5.1        |
| aws-sdk-ssooidc                           | 1.4.1        |
| aws-sdk-states                            | 1.29.1       |
| aws-sdk-storagegateway                    | 1.42.1       |
| aws-sdk-support                           | 1.22.1       |
| aws-sdk-swf                               | 1.21.1       |
| aws-sdk-synthetics                        | 1.4.1        |
| aws-sdk-textract                          | 1.16.1       |
| aws-sdk-transcribeservice                 | 1.44.1       |
| aws-sdk-transcribestreamingservice        | 1.16.1       |
| aws-sdk-transfer                          | 1.22.1       |
| aws-sdk-translate                         | 1.23.1       |
| aws-sdk-waf                               | 1.31.1       |
| aws-sdk-wafregional                       | 1.32.1       |
| aws-sdk-wafv2                             | 1.6.1        |
| aws-sdk-workdocs                          | 1.24.1       |
| aws-sdk-worklink                          | 1.17.1       |
| aws-sdk-workmail                          | 1.26.1       |
| aws-sdk-workmailmessageflow               | 1.5.1        |
| aws-sdk-workspaces                        | 1.38.1       |
| aws-sdk-xray                              | 1.27.1       |
| aws-sdk-resources                         | 3.74.1       |
| aws-sdk                                   | 3.0.1        |
| babosa                                    | 1.0.3        |
| claide                                    | 1.0.3        |
| fuzzy_match                               | 2.0.4        |
| nap                                       | 1.1.0        |
| netrc                                     | 0.11.0       |
| ffi                                       | 1.13.1       |
| ethon                                     | 0.12.0       |
| typhoeus                                  | 1.4.0        |
| cocoapods-core                            | 1.9.3        |
| cocoapods-deintegrate                     | 1.0.4        |
| cocoapods-downloader                      | 1.3.0        |
| cocoapods-plugins                         | 1.0.0        |
| cocoapods-search                          | 1.0.0        |
| cocoapods-stats                           | 1.1.0        |
| cocoapods-trunk                           | 1.5.0        |
| cocoapods-try                             | 1.2.0        |
| colored2                                  | 3.1.2        |
| escape                                    | 0.0.4        |
| fourflusher                               | 2.3.1        |
| gh_inspector                              | 1.1.3        |
| molinillo                                 | 0.6.6        |
| ruby-macho                                | 1.4.0        |
| nanaimo                                   | 0.2.6        |
| xcodeproj                                 | 1.17.0       |
| cocoapods                                 | 1.9.3        |
| colored                                   | 1.2          |
| highline                                  | 1.7.10       |
| commander-fastlane                        | 4.4.6        |
| declarative                               | 0.0.10       |
| declarative-option                        | 0.1.0        |
| digest-crc                                | 0.5.1        |
| unf_ext                                   | 0.0.7.7      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| dotenv                                    | 2.7.5        |
| emoji_regex                               | 1.0.1        |
| excon                                     | 0.75.0       |
| multipart-post                            | 2.0.0        |
| faraday                                   | 1.0.1        |
| http-cookie                               | 1.0.3        |
| faraday-cookie_jar                        | 0.0.6        |
| faraday_middleware                        | 1.0.0        |
| fastimage                                 | 2.1.7        |
| jwt                                       | 2.1.0        |
| memoist                                   | 0.16.2       |
| multi_json                                | 1.14.1       |
| os                                        | 1.1.0        |
| signet                                    | 0.14.0       |
| googleauth                                | 0.13.0       |
| mini_mime                                 | 1.0.2        |
| uber                                      | 0.1.0        |
| representable                             | 3.0.4        |
| retriable                                 | 3.1.2        |
| google-api-client                         | 0.38.0       |
| google-cloud-env                          | 1.3.2        |
| google-cloud-errors                       | 1.0.1        |
| google-cloud-core                         | 1.5.0        |
| google-cloud-storage                      | 1.26.2       |
| mini_magick                               | 4.10.1       |
| multi_xml                                 | 0.6.0        |
| plist                                     | 3.5.0        |
| rubyzip                                   | 1.3.0        |
| security                                  | 0.1.3        |
| naturally                                 | 2.2.0        |
| simctl                                    | 1.6.8        |
| slack-notifier                            | 2.3.2        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.7.0        |
| terminal-table                            | 1.8.0        |
| tty-screen                                | 0.8.0        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| word_wrap                                 | 1.0.0        |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| xcpretty-travis-formatter                 | 1.0.0        |
| fastlane-plugin-firebase_app_distribution | 0.1.4        |
| fastlane-plugin-versioning                | 0.4.3        |
| mini_portile2                             | 2.4.0        |
| nokogiri                                  | 1.10.9       |
| nokogiri-plist                            | 0.5.0        |
| xcode-install                             | 2.6.4        |
</details>


*generated on:* **2020-06-24**
</details></pre>
</details>

### Mentioning
<!-- Mentioning @joshdholtz so he gets a notification of this as soon as its created -->
cc: @joshdholtz

**Comment by koxon** [comment] 2020-06-25 03:56
+1 on this. All my submissions show same issue.

**Comment by joshdholtz** [comment] 2020-06-25 13:52
@dcristolovean @koxon 👋 Hey! Can both of you let me know how you are using and experiencing this? Looking so I can replicate 😇 Curious what your `deliver` call looks like. Once you let me know I can fix right away!

**Comment by koxon** [comment] 2020-06-25 14:46
Hey @joshdholtz . We figure it out. Before we didn't need to specify the `app_version` parameter to deliver. Now we need to specify it or it fails. We tested and it works. So we can close this issue. Thank you !

**Comment by joshdholtz** [comment] 2020-06-25 14:53
@koxon Ahhhhhh! I will see if I can put a fix in when `app_version` isn’t specified! I don’t _personaly_ use that feature too often but is the expected behavior to **select / submit** the build for the current **prepare for submission** version if not `app_version` is specified?

**Comment by marcoruggine** [comment] 2020-06-26 12:10
I have the same issue, before it worked great. Is there a way to specify "latest build" instead of the precise number? because that is not going to work for us.

**Comment by joshdholtz** [comment] 2020-06-30 20:33
@marcoruggine @dcristolovean PR https://github.com/fastlane/fastlane/pull/16713 should have fixes for you! I will release this as rc5 in about 30 minutes

**Comment by joshdholtz** [comment] 2020-06-30 21:31
@marcoruggine @dcristolovean `rc5` is out if you'd like to see if that solves what you were seeing!

**Comment by marcoruggine** [comment] 2020-07-01 07:40
@joshdholtz great! I'll try it today asap.

**Comment by marcoruggine** [comment] 2020-07-02 12:27
@joshdholtz sorry for the delay, it worked!! thank you very much

**Comment by joshdholtz** [comment] 2020-07-02 12:28
🥳🥳🥳🥳🥳🥳

**Closed by joshdholtz** 2020-07-02 12:28 UTC
Labels: 2.150.0, tool: deliver

**Comment by ppamorim** [comment] 2020-08-17 09:15
@koxon Now it's not working even with `app_version`.
