### ISSUE TITLE
iPad Pro not available for Snapshot

### ISSUE THREAD

**Issue by ZevEisenberg** [fastlane/fastlane#5673] opened 2016-08-10 01:51 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
When using `snapshot`, I can't specify the iPad Pro in a way that `snapshot` understands. Possibly related to #1675

##### Complete output when running fastlane, including the stack trace and command used

```
$ bundle exec snapshot
[21:48:36]: Error setting value '["iPad Pro (12.9-inch)"]' for option 'devices'

Looking for related GitHub issues on fastlane/fastlane...

➡️   Failed to build gem native extension.
   https://github.com/fastlane/fastlane/issues/6 [closed] 0 💬
   16 Jan 2015


[!] Device 'iPad Pro (12.9-inch)' not in list of available simulators 'iPhone 5, iPhone 5s, iPhone 6, iPhone 6 Plus, iPhone 6s, iPhone 6s Plus, iPhone SE, iPad Retina, iPad Air, iPad Air 2'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Snapfile:
```ruby
# A list of devices you want to take the screenshots from
devices([
  # "iPhone 6",
  # "iPhone 6 Plus",
  # "iPhone 5",
  # "iPhone 4s",
  # "iPad Retina",
  "iPad Pro (12.9-inch)"
])

languages([
  "en-US",
  # "fr-Fr",
  # "it",
  # "zh-Hans",
  # "zh-Hant",
])

ENV["FASTLANE_SNAPSHOT"] = "1"

# The name of the scheme which contains the UI Tests
scheme "Screenshots"

configuration "Debug"

clear_previous_screenshots true

# Choose which project/workspace to use
# project "./Project.xcodeproj"
# workspace "./Project.xcworkspace"

# For more information about all available options run
# snapshot --help
```

### Environment

fastlane version (run `fastlane -v`): fastlane 1.99.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? Yes

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? Yes (rvm)

**Comment by kitefaster** [comment] 2016-08-10 03:11
It works for me with value of:
   "iPad Pro"

**Comment by ZevEisenberg** [comment] 2016-08-10 03:51
Doesn't work for me. "iPad Pro" still doesn't show up in the list. Caveat: this is after running `snapshot reset_simulators` so they have the Xcode default simulators, I think.

**Comment by kitefaster** [comment] 2016-08-10 04:00
Which version of simulators do you have installed (Xcode...Preferences...Components)?

**Comment by ZevEisenberg** [comment] 2016-08-10 04:33
8.3 and the default (10.0, which isn't listed). But the project targets 10.0.

**Comment by ZevEisenberg** [comment] 2016-08-10 18:31
Note to self: @KrauseFx suggested I run this to list available simulators:

```ruby
irb
> require 'fastlane_core'
> FastlaneCore::Simulator.all.collect { |a| a.name }
```

**Comment by ZevEisenberg** [comment] 2016-08-10 18:51
The output of the above command:

```
["iPhone 5", "iPhone 5s", "iPhone 6", "iPhone 6 Plus", "iPhone 6s", "iPhone 6s Plus", "iPhone SE", "iPad Retina", "iPad Air", "iPad Air 2"] 
```

But here's the output of `bundle exec snapshot reset_simulators`:

```
Are you sure? All your simulators will be DELETED and new ones will be created! (y/n)
y
Removing device iPhone 5 (8875079A-04C3-4CC8-BF9C-A43F25A10094)
Removing device iPhone 5s (D5ECDD85-C78D-48F7-8E9A-024BAFFF082B)
Removing device iPhone 6 (A7209C97-A047-4E81-BD33-1B3C4EAF4330)
Removing device iPhone 6 Plus (3C24D628-A516-46CD-ABCB-304090ECF277)
Removing device iPhone 6s (9AF539C8-2D54-414A-82EA-BCC1F31AC98F)
Removing device iPhone 6s Plus (2ED84EB4-04FC-4F06-89EF-09E7D3F6B185)
Removing device iPhone SE (9C273F63-63A1-40A6-B6E2-D82DC50B01EB)
Removing device iPad Retina (C77EA503-0991-451E-91AE-29C2F21F8DAE)
Removing device iPad Air (23BCFB72-4EDF-410A-BDD4-8105A8337E6C)
Removing device iPad Air 2 (E29E3353-BB83-4FE1-B37B-E9452488392E)
Removing device iPad Pro (9.7-inch) (8179751E-AF74-43B4-A41A-69F97522187A)
Removing device iPad Pro (12.9-inch) (85706162-44C7-4F0B-BBED-21ED3055AC74)
Removing device Apple Watch - 38mm (EF176ED0-37EF-429F-9757-4031EAA2E1AA)
Removing device Apple Watch - 42mm (233FB51C-F410-4706-AC4F-E283E0F6FC31)
Creating ["iPhone 4s", "com.apple.CoreSimulator.SimDeviceType.iPhone-4s"] for iOS version 10.0
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=161):
Incompatible device
Creating ["iPhone 5", "com.apple.CoreSimulator.SimDeviceType.iPhone-5"] for iOS version 10.0
Creating ["iPhone 5s", "com.apple.CoreSimulator.SimDeviceType.iPhone-5s"] for iOS version 10.0
Creating ["iPhone 6", "com.apple.CoreSimulator.SimDeviceType.iPhone-6"] for iOS version 10.0
Creating ["iPhone 6 Plus", "com.apple.CoreSimulator.SimDeviceType.iPhone-6-Plus"] for iOS version 10.0
Creating ["iPhone 6s", "com.apple.CoreSimulator.SimDeviceType.iPhone-6s"] for iOS version 10.0
Creating ["iPhone 6s Plus", "com.apple.CoreSimulator.SimDeviceType.iPhone-6s-Plus"] for iOS version 10.0
Creating ["iPhone SE", "com.apple.CoreSimulator.SimDeviceType.iPhone-SE"] for iOS version 10.0
Creating ["iPad 2", "com.apple.CoreSimulator.SimDeviceType.iPad-2"] for iOS version 10.0
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=161):
Incompatible device
Creating ["iPad Retina", "com.apple.CoreSimulator.SimDeviceType.iPad-Retina"] for iOS version 10.0
Creating ["iPad Air", "com.apple.CoreSimulator.SimDeviceType.iPad-Air"] for iOS version 10.0
Creating ["iPad Air 2", "com.apple.CoreSimulator.SimDeviceType.iPad-Air-2"] for iOS version 10.0
Creating ["iPad Pro (9.7-inch)", "com.apple.CoreSimulator.SimDeviceType.iPad-Pro--9-7-inch-"] for iOS version 10.0
Creating ["iPad Pro (12.9-inch)", "com.apple.CoreSimulator.SimDeviceType.iPad-Pro"] for iOS version 10.0
Creating ["Apple TV 1080p", "com.apple.CoreSimulator.SimDeviceType.Apple-TV-1080p"] for tvOS version 10.0
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=161):
Incompatible device
Creating ["Apple Watch - 38mm", "com.apple.CoreSimulator.SimDeviceType.Apple-Watch-38mm"] for watchOS version 3.0
Creating ["Apple Watch - 42mm", "com.apple.CoreSimulator.SimDeviceType.Apple-Watch-42mm"] for watchOS version 3.0
Creating device pair of E371E0FF-77DA-4EA6-A6E8-76904312535E and B052CEF6-8F41-4018-B539-BD8CC7023DD3
```

As you can see, the iPad Pro simulators exist, but are not seen by `Simulator.all.collect`. I wonder if it's the new format of the iPad Pro simulator names, which include parentheses and hyphens, which is throwing us off?

**Comment by jdhealy** [comment] 2016-08-10 19:15
> parentheses and hyphens, which is throwing us off

Looks to be the case here: [fastlane_core/lib/fastlane_core/device_manager.rb#L34](https://github.com/fastlane/fastlane/blob/b0ccaf3faaec12f87f1a350635010672c0a82986/fastlane_core/lib/fastlane_core/device_manager.rb#L34)

```ruby
irb(main):001:0> line = "iPad Pro (12.9 inch) (203A760E-FFFF-FFFF-85D0-1A0550113098) (Shutdown)"
=> "iPad Pro (12.9 inch) (203A760E-FFFF-FFFF-85D0-1A0550113098) (Shutdown)"
irb(main):002:0> line.match(/\s+([^\(]+) \(([-0-9A-F]+)\) \(([^\(]+)\)(.*unavailable.*)?/)
=> #<MatchData " inch) (203A760E-FFFF-FFFF-85D0-1A0550113098) (Shutdown)" 1:"inch)" 2:"203A760E-9029-4450-85D0-1A0550113098" 3:"Shutdown" 4:nil>
```

**Comment by KrauseFx** [comment] 2016-08-10 20:53
Interesting - what version of Xcode are you using?

**Comment by jdhealy** [comment] 2016-08-10 20:57
```
$ xcodebuild -version
Xcode 8.0
Build version 8S193k
```

**Comment by KrauseFx** [comment] 2016-08-10 21:01
Alright, so this is related to Xcode 8, I prepared this PR https://github.com/fastlane/fastlane/pull/5698 and will also try the latest Xcode beta

**Comment by jdhealy** [comment] 2016-08-10 21:05
I can get the same line with 7.3.1…

```
$ /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -version
Xcode 7.3.1
Build version 7D1014

$ /Applications/Xcode.app/Contents/Developer/usr/bin/simctl list devices | grep '12.9'
    iPad Pro (12.9 inch) (203A760E-9029-4450-85D0-1A0550113098) (Shutdown) (unavailable, runtime profile not found)
```

…but, with the beta `xcode-select`ed

```
$ xcode-select -p
/Applications/New/Xcode-beta.app/Contents/Developer
```

**Comment by KrauseFx** [comment] 2016-08-10 21:11
Yeah, I assume it depends on the simulators you have installed. I can reproduce the error and already work on a fix 👍

**Comment by KrauseFx** [comment] 2016-08-10 21:33
Alright, this should be fixed with https://github.com/fastlane/fastlane/pull/5698 in combination with https://github.com/fastlane/fastlane/pull/5699 👍 

🚀

**Comment by ZevEisenberg** [comment] 2016-08-11 14:27
Reading back over this thread, I realized it took a while before I revealed that I was on Xcode 8. Maybe the issue reporting template should include that? Or is it rare that the Xcode version is related to the problem? maybe only include that field during the beta period?

**Comment by TKBurner** [comment] 2016-08-12 15:00
@ZevEisenberg Thanks for following up. Xcode 8 is causing a bunch of things to pop up in Fastlane right now. You are right we should add this to the issue template. Thanks!

**Closed by TKBurner** 2016-08-12 15:00 UTC
