### ISSUE TITLE
install sigh error

### ISSUE THREAD

**Issue by shuijinliuxi** [fastlane/fastlane#5154] opened 2016-06-17 10:10 UTC
The error is ：

PDhouse-Macbook-Pro:~ xxx$ sudo gem install sigh
Password:
ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted - /usr/bin/commander

**Comment by muzoman** [comment] 2016-06-17 15:53
Yep, same error here. How is this fixed?

**Comment by muzoman** [comment] 2016-06-17 16:38
Having dug around. This is a duplicate of issue 567. The following install worked:

 sudo gem install -n /usr/local/bin snapshot

**Comment by vpolouchkine** [comment] 2016-06-20 21:02
@shuijinliuxi Does that help ^^?

**Comment by shuijinliuxi** [comment] 2016-06-22 01:02
It is right. tks ^-^

**Closed** 2016-06-22 14:12 UTC
Labels: sigh
