### ISSUE TITLE
REDO #9405 cert checker aborts execution if the desired certificate is already present

### ISSUE THREAD

**Issue by BanzaiMan** [fastlane/fastlane#10059] opened 2017-08-15 21:04 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

`fastlane match` will fail if WWDRCA certificate is already installed in the keychain.

In https://github.com/fastlane/fastlane/blob/1240fe39eaf236eb9774ec985a437b123cb10aa7/fastlane_core/lib/fastlane_core/cert_checker.rb#L64-L65, you can see that fastlane attempts to download https://developer.apple.com/certificationauthority/AppleWWDRCA.cer and install it in a keychain that the user has access to. It is assumed here that the nonzero exit status means the *failure* to import the certificate, but it does not account for the possibility the nonzero exit because the key already exists.

I believe the error manifests now on Travis CI, because we added the WWDRCA certificate to our login keychain.

See https://github.com/travis-ci/travis-ci/issues/7870#issuecomment-306892418 for more context.
 

### Environment

Sorry, I don't use fastlane to produce this.

**Comment by BanzaiMan** [comment] 2017-08-15 21:04
I'm just redoing https://github.com/fastlane/fastlane/issues/9405.

**Comment by taquitos** [comment] 2017-08-15 22:43
Given your output from the closed issue: 
```sh-session
Traviss-Mac-270:~ travis$ curl -O https://developer.apple.com/certificationauthority/AppleWWDRCA.cer
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1062  100  1062    0     0    853      0  0:00:01  0:00:01 --:--:--   854
Traviss-Mac-270:~ travis$ security import AppleWWDRCA.cer /Users/travis/Library/Keychains/login.keychain-db
1 certificate imported.
Traviss-Mac-270:~ travis$ security import AppleWWDRCA.cer /Users/travis/Library/Keychains/login.keychain-db
security: SecKeychainItemImport: The specified item already exists in the keychain.
Traviss-Mac-270:~ travis$ echo $?
1
Traviss-Mac-270:~ travis$ security delete-certificate -c "Apple Worldwide Developer Relations Certification Authority"
Traviss-Mac-270:~ travis$ security import AppleWWDRCA.cer /Users/travis/Library/Keychains/login.keychain-db
1 certificate imported.
Traviss-Mac-270:~ travis$ echo $?
0
```

Maybe if we fetch it successfully, we can:

1. check the keychain to see if it's already there
2. delete the cert that is there
3. install the cert that was downloaded

**Comment by BanzaiMan** [comment] 2017-09-30 05:46
...

**Comment by BanzaiMan** [comment] 2017-11-23 16:15
…

**Comment by taquitos** [comment] 2018-01-16 23:12
@BanzaiMan is there any way to check your keychain for the name of the cert? 
When the cert is installed, it comes up as `Apple Worldwide Developer Relations Certification Authority`

We check to see if it exists before attempting to install:
https://github.com/fastlane/fastlane/blob/1240fe39eaf236eb9774ec985a437b123cb10aa7/fastlane_core/lib/fastlane_core/cert_checker.rb#L21

https://github.com/fastlane/fastlane/blob/1240fe39eaf236eb9774ec985a437b123cb10aa7/fastlane_core/lib/fastlane_core/cert_checker.rb#L51-L56

So I haven't been able to reproduce because every time I run this, the check passes. If I manually bypass the check and force install, it does fail. I don't want to make changes until I understand why this part is failing for you:
https://github.com/fastlane/fastlane/blob/1240fe39eaf236eb9774ec985a437b123cb10aa7/fastlane_core/lib/fastlane_core/cert_checker.rb#L51-L56


I need more logging output from your build machine to be able to debug this further 😞

**Comment by taquitos** [comment] 2018-01-16 23:34
I just submitted a PR to work around your issue, let me know if that works.

**Comment by BanzaiMan** [comment] 2018-01-17 01:25
The key should have been `Apple Worldwide Developer Relations Certification Authority`, if I am to believe my 6-months-ago self in https://github.com/travis-ci/travis-ci/issues/7870#issuecomment-306892418.

**Comment by taquitos** [comment] 2018-01-17 18:02
Yeah, the code searches for that, so I wonder why it breaks for you.
Either way, the workaround should suffice 🚀

**Comment by BanzaiMan** [comment] 2018-01-17 18:28
🤞

**Comment by joshdholtz** [comment] 2018-03-05 23:57
Going to close this issue for now as it seems the fix that was put in place works? 🤞 😉

**Closed by joshdholtz** 2018-03-05 23:57 UTC
Labels: tool: fastlane_core, type: bug
