### ISSUE TITLE
Build failed to deploy on test

### ISSUE THREAD

**Issue by Ibni-Amin** [fastlane/fastlane#20763] opened 2022-10-20 11:18 UTC
2022-10-20T10:51:25.6014470Z ##[section]Starting: Publish to the App Store TestFlight track
2022-10-20T10:51:25.6027750Z ==============================================================================
2022-10-20T10:51:25.6028110Z Task         : Apple App Store Release
2022-10-20T10:51:25.6028460Z Description  : Release an app to TestFlight or the Apple App Store
2022-10-20T10:51:25.6028740Z Version      : 1.207.0
2022-10-20T10:51:25.6028950Z Author       : Microsoft Corporation
2022-10-20T10:51:25.6030890Z Help         : [More Information](https://marketplace.visualstudio.com/items?itemName=ms-vsclient.app-store)
2022-10-20T10:51:25.6031390Z ==============================================================================
2022-10-20T10:51:25.8334650Z [command]/usr/local/opt/ruby@2.7/bin/gem install fastlane
2022-10-20T10:52:03.8522340Z Successfully installed fastlane-2.210.1
2022-10-20T10:52:03.8622900Z Parsing documentation for fastlane-2.210.1
2022-10-20T10:52:03.8646230Z Installing ri documentation for fastlane-2.210.1
2022-10-20T10:52:03.8748640Z Done installing documentation for fastlane after 32 seconds
2022-10-20T10:52:03.8850720Z 1 gem installed
2022-10-20T10:52:03.9565900Z [command]/usr/local/opt/ruby@2.7/bin/gem update fastlane -i /Users/runner/.gem-cache
2022-10-20T10:52:08.8586900Z Updating installed gems
2022-10-20T10:52:08.8687130Z Nothing to update
2022-10-20T10:52:08.8790080Z Gems already up-to-date: fastlane
2022-10-20T10:52:09.1399650Z [command]/usr/local/lib/ruby/gems/2.7.0/bin/fastlane pilot upload --api_key_path /Users/runner/work/_temp/api_key***.json -i /Users/runner/work/r1/a/_ProjulV1Portal-IOS-Pipeline/ipa/output/iphoneos/Release/Projul-Test.ipa -a bundler-Id -p ****************
2022-10-20T10:52:12.9909420Z [10:52:12]: [33mSeems like launching fastlane takes a while - please run[0m
2022-10-20T10:52:13.0005270Z [10:52:12]: 
2022-10-20T10:52:13.0110270Z [10:52:12]: [36m$ [sudo] gem cleanup[0m
2022-10-20T10:52:13.0221260Z [10:52:12]: 
2022-10-20T10:52:13.0323880Z [10:52:12]: [33mto uninstall outdated gems and make fastlane launch faster[0m
2022-10-20T10:52:13.0427790Z [10:52:12]: [33mAlternatively it's recommended to start using a Gemfile to lock your dependencies[0m
2022-10-20T10:52:13.0530810Z [10:52:12]: [33mTo get started with a Gemfile, run[0m
2022-10-20T10:52:13.0623550Z [10:52:12]: 
2022-10-20T10:52:13.0717290Z [10:52:12]: [36m$ bundle init[0m
2022-10-20T10:52:13.0769620Z [10:52:12]: [36m$ echo 'gem "fastlane"' >> Gemfile[0m
2022-10-20T10:52:13.0850610Z [10:52:12]: [36m$ bundle install[0m
2022-10-20T10:52:13.0934520Z [10:52:12]: 
2022-10-20T10:52:13.1005390Z [10:52:12]: [33mAfter creating the Gemfile and Gemfile.lock, commit those files into version control[0m
2022-10-20T10:52:13.1113030Z [10:52:12]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m
2022-10-20T10:52:16.2202100Z [10:52:16]: Sending anonymous analytics information
2022-10-20T10:52:16.2302710Z [10:52:16]: Learn more at https://docs.fastlane.tools/#metrics
2022-10-20T10:52:16.2404520Z [10:52:16]: No personal or sensitive data is sent.
2022-10-20T10:52:16.2504890Z [10:52:16]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
2022-10-20T10:52:16.2771260Z [10:52:16]: Creating authorization token for App Store Connect API
2022-10-20T10:52:16.2825700Z [10:52:16]: Ready to upload new build to TestFlight (App: 000000000)...
2022-10-20T10:52:17.7567900Z [10:52:17]: Going to upload updated app to App Store Connect
2022-10-20T10:52:17.7670580Z [10:52:17]: This might take a few minutes. Please don't interrupt the script.
2022-10-20T10:52:34.7618550Z [10:52:34]: Transporter transfer failed.
2022-10-20T10:52:34.7629440Z [10:52:34]: 
2022-10-20T10:52:34.7732990Z [10:52:34]: There was a general exception while executing
2022-10-20T10:52:34.7834660Z An exception has occurred: issuerId is required
2022-10-20T10:52:34.9398100Z [10:52:34]: [iTMSTransporter] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-10-20T10:52:34.9401020Z 
2022-10-20T10:52:34.9402400Z [10:52:34]: [iTMSTransporter] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2022-10-20T10:52:34.9403140Z 
2022-10-20T10:52:34.9403990Z [10:52:34]: [iTMSTransporter] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2022-10-20T10:52:34.9404740Z 
2022-10-20T10:52:34.9405480Z [10:52:34]: [iTMSTransporter] 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
2022-10-20T10:52:34.9406150Z 
2022-10-20T10:52:34.9406990Z [10:52:34]: [iTMSTransporter] 	at com.apple.transporter.bootstrap.BootstrapperPhase1.bootstrap(BootstrapperPhase1.java:107)
2022-10-20T10:52:34.9407760Z 
2022-10-20T10:52:34.9408930Z [10:52:34]: [iTMSTransporter] 	at com.apple.transporter.bootstrap.BootstrapperPhase1.bootstrap(BootstrapperPhase1.java:78)
2022-10-20T10:52:34.9452680Z 
2022-10-20T10:52:34.9454010Z [10:52:34]: [iTMSTransporter] 	at com.apple.transporter.launcher.Launcher.launchBootstrapper(Launcher.java:37)
2022-10-20T10:52:34.9454420Z 
2022-10-20T10:52:34.9454960Z [10:52:34]: [iTMSTransporter] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-10-20T10:52:34.9455290Z 
2022-10-20T10:52:34.9455750Z [10:52:34]: [iTMSTransporter] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2022-10-20T10:52:34.9456080Z 
2022-10-20T10:52:34.9456550Z [10:52:34]: [iTMSTransporter] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2022-10-20T10:52:34.9456880Z 
2022-10-20T10:52:34.9457290Z [10:52:34]: [iTMSTransporter] 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
2022-10-20T10:52:34.9457770Z 
2022-10-20T10:52:34.9458290Z [10:52:34]: [iTMSTransporter] 	at com.apple.transporter.launcher.Application.start(Application.java:450)
2022-10-20T10:52:34.9458660Z 
2022-10-20T10:52:34.9459130Z [10:52:34]: [iTMSTransporter] 	at com.apple.transporter.launcher.Application.main(Application.java:947)
2022-10-20T10:52:34.9459480Z 
2022-10-20T10:52:34.9459770Z [10:52:34]: [iTMSTransporter] 
2022-10-20T10:52:34.9459930Z 
2022-10-20T10:52:34.9461280Z [10:52:34]: [iTMSTransporter] [2022-10-20 10:52:34 UTC] <main> DBG-X: Returning 1
2022-10-20T10:52:34.9462710Z 
2022-10-20T10:52:34.9463140Z [10:52:34]: iTunes Transporter output above ^
2022-10-20T10:52:34.9463570Z [10:52:34]: There was a general exception while executing
2022-10-20T10:52:34.9464580Z An exception has occurred: issuerId is required
2022-10-20T10:52:34.9465090Z Return status of iTunes Transporter was 1: There was a general exception while executing
2022-10-20T10:52:34.9465580Z \nAn exception has occurred: issuerId is required
2022-10-20T10:52:34.9467100Z The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
2022-10-20T10:52:34.9600380Z 
2022-10-20T10:52:34.9602160Z [!] Error uploading ipa file: 
2022-10-20T10:52:34.9602580Z  
2022-10-20T10:52:34.9879820Z ##[error]Error: The process '/usr/local/lib/ruby/gems/2.7.0/bin/fastlane' failed with exit code 1
2022-10-20T10:52:34.9898950Z ##[section]Finishing: Publish to the App Store TestFlight track

**Comment by carlosriveroib** [comment] 2022-10-20 11:46
same issue from yesterday and I didn't add anything to my fastlane

**Comment by Ibni-Amin** [comment] 2022-10-20 19:17
My Issue fixed. I just updated my machine ruby version from 2.5.XXX to 3.1.1. and then Update my project podFile of project, That worked me 😊😊.

**Comment by AntonReality** [comment] 2022-10-21 10:42
@Ibni-Amin How did you update your pod file? Updating ruby version didn't work for me.

**Comment by Stas-Buzunko** [comment] 2022-10-21 21:21
didn't work for me as well :(

**Comment by Stas-Buzunko** [comment] 2022-10-21 22:15
this comment fixed my issue https://github.com/fastlane/fastlane/issues/20773#issuecomment-1286867460
i've added ITMSTRANSPORTER_FORCE_ITMS_PACKAGE_UPLOAD=true to my .env.prod file inside the fastlane folder and it worked

**Comment by fotos** [comment] 2022-10-24 10:17
This is a duplicate of #20741.

You will find all current workarounds and solutions for this problem in #20741.

**Comment by Ibni-Amin** [comment] 2022-11-23 18:50
> There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.
> 
> Please make sure to update to the latest `fastlane` version and check if that solves the issue. Let us know if that works for you by adding a comment +1
> 
> Friendly reminder: contributions are always welcome! Check out [CONTRIBUTING.md](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md) for more information on how to help with `fastlane` and feel free to tackle this issue yourself muscle
> 
> This issue will be auto-closed if there is no reply within 1 


Yes my azure pipeline is running well nowadays I think they would be updated the fastlane versions or something else. So this issue will be closed on behalf of fatlane references.

**Closed** 2023-07-12 14:15 UTC
Labels: status: waiting-for-reply
