### ISSUE TITLE
<HTML> (Spaceship::UnexpectedResponse)

### ISSUE THREAD

**Issue by alteral** [fastlane/fastlane#19278] opened 2021-08-24 10:36 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version [`2.192.0`]
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

- fastlane fails on the `produce` step

##### Command executed

- `produce(company_name: company_name, language: 'en-US')`

##### Complete output when running fastlane, including the stack trace and command used
```
INFO [2021-08-24 10:57:38.35]: --- Step: produce ---
INFO [2021-08-24 10:57:38.35]: ---------------------

+----------------+-------------------------+
|       Summary for produce 2.192.0        |
+----------------+-------------------------+
| company_name   | ***                     |
| language       | en-US                   |
| username       | ***                     |
| app_identifier | ***                     |
| app_name       | ***                     |
| platform       | ios                     |
| skip_itc       | false                   |
| skip_devcenter | false                   |
| team_id        | ***                     |
+----------------+-------------------------+

Reading keychain entry, because either user or password were empty
Loading session from environment variable
ERROR [2021-08-24 10:57:41.24]: <HTML>
<HEAD>
<TITLE>Error</TITLE>
</HEAD>

<BODY BGCOLOR="white" FGCOLOR="black">
<H1>Error</H1>
<HR>

<FONT FACE="Helvetica,Arial"><B>
Description: Could not process this request.
</B></FONT>
<HR>
</BODY>
```

##### Command executed

- `fastlane produce associate_group group.********-ios`

##### Complete output when running fastlane, including the stack trace and command used
```
INFO [2021-08-24 11:18:06.96]: -----------------------------------------------------
INFO [2021-08-24 11:18:06.96]: Step: fastlane produce associate_group group.********-ios
INFO [2021-08-24 11:18:06.96]: -----------------------------------------------------
INFO [2021-08-24 11:18:06.96]: $ fastlane produce associate_group group.********-ios
INFO [2021-08-24 11:18:10.87]: ▸ [11:18:10]: Starting login with user 'info@********.ie'
INFO [2021-08-24 11:18:11.90]: ▸ [11:18:11]: Successfully logged in
INFO [2021-08-24 11:18:12.66]: ▸ /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/fastlane-2.192.0/spaceship/lib/spaceship/client.rb:763:in `parse_response': \e[31m[!] <HTML> (Spaceship::UnexpectedResponse)
INFO [2021-08-24 11:18:12.66]: ▸ <HEAD>
INFO [2021-08-24 11:18:12.66]: ▸ <TITLE>Error</TITLE>
INFO [2021-08-24 11:18:12.66]: ▸ </HEAD>
INFO [2021-08-24 11:18:12.66]: ▸ <BODY BGCOLOR="white" FGCOLOR="black">
INFO [2021-08-24 11:18:12.66]: ▸ <H1>Error</H1>
INFO [2021-08-24 11:18:12.66]: ▸ <HR>
INFO [2021-08-24 11:18:12.66]: ▸ <FONT FACE="Helvetica,Arial"><B>
INFO [2021-08-24 11:18:12.66]: ▸ Description: Could not process this request.
INFO [2021-08-24 11:18:12.66]: ▸ </B></FONT>
INFO [2021-08-24 11:18:12.66]: ▸ <HR>
INFO [2021-08-24 11:18:12.66]: ▸ </BODY>
INFO [2021-08-24 11:18:12.66]: ▸ \e[0m
INFO [2021-08-24 11:18:12.66]: ▸ from /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/fastlane-2.192.0/spaceship/lib/spaceship/portal/portal_client.rb:128:in `block in apps'
INFO [2021-08-24 11:18:12.66]: ▸ from /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/fastlane-2.192.0/spaceship/lib/spaceship/client.rb:337:in `block in paging'
INFO [2021-08-24 11:18:12.66]: ▸ from /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/fastlane-2.192.0/spaceship/lib/spaceship/client.rb:335:in `loop'
INFO [2021-08-24 11:18:12.66]: ▸ from /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/fastlane-2.192.0/spaceship/lib/spaceship/client.rb:335:in `paging'
INFO [2021-08-24 11:18:12.66]: ▸ from /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/fastlane-2.192.0/spaceship/lib/spaceship/portal/portal_client.rb:121:in `apps'
INFO [2021-08-24 11:18:12.66]: ▸ from /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/fastlane-2.192.0/spaceship/lib/spaceship/portal/app.rb:85:in `all'
INFO [2021-08-24 11:18:12.66]: ▸ from /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/fastlane-2.192.0/spaceship/lib/spaceship/portal/app.rb:111:in `find'
INFO [2021-08-24 11:18:12.66]: ▸ from /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/fastlane-2.192.0/produce/lib/produce/group.rb:87:in `app_exists?'
INFO [2021-08-24 11:18:12.66]: ▸ from /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/fastlane-2.192.0/produce/lib/produce/group.rb:45:in `associate'
INFO [2021-08-24 11:18:12.66]: ▸ from /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/fastlane-2.192.0/produce/lib/produce/commands_generator.rb:257:in `block (2 levels) in run'
INFO [2021-08-24 11:18:12.66]: ▸ from /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
INFO [2021-08-24 11:18:12.66]: ▸ from /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
INFO [2021-08-24 11:18:12.66]: ▸ from /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
INFO [2021-08-24 11:18:12.66]: ▸ from /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/fastlane-2.192.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
INFO [2021-08-24 11:18:12.66]: ▸ from /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
INFO [2021-08-24 11:18:12.66]: ▸ from /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/fastlane-2.192.0/produce/lib/produce/commands_generator.rb:334:in `run'
INFO [2021-08-24 11:18:12.66]: ▸ from /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/fastlane-2.192.0/produce/lib/produce/commands_generator.rb:18:in `start'
INFO [2021-08-24 11:18:12.66]: ▸ from /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/fastlane-2.192.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
INFO [2021-08-24 11:18:12.66]: ▸ from /Users/distiller/project/vendor/bundle/ruby/2.7.0/gems/fastlane-2.192.0/bin/fastlane:23:in `<top (required)>'
INFO [2021-08-24 11:18:12.67]: ▸ from /Users/distiller/project/vendor/bundle/ruby/2.7.0/bin/fastlane:23:in `load'
INFO [2021-08-24 11:18:12.67]: ▸ from /Users/distiller/project/vendor/bundle/ruby/2.7.0/bin/fastlane:23:in `<main>'
```

### Environment

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.15.5                                          |
| Ruby                        | 2.7.2                                            |
| Bundler?                    | true                                             |
| Git                         | git version 2.29.2                               |
| Installation Source         | ~/project/vendor/bundle/ruby/2.7.0/bin/fastlane  |
| Host                        | Mac OS X 10.15.5 (19F101)                        |
| Ruby Lib Dir                | ~/.rubies/ruby-2.7.2/lib                         |
| OpenSSL Version             | OpenSSL 1.0.2t  10 Sep 2019                      |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode-12.3.app/Contents/Developer/ |
| Xcode Version               | 12.3                                             |
| Swift Version               | 5.3.2                                            |

**Comment by JimDabell** [comment] 2021-08-24 10:41
This is a dupe of #19264.

**Comment by lpusok** [comment] 2021-08-24 10:44
@JimDabell Can confirm that is it unresolved tough in 2.192.0 :*(

**Comment by JimDabell** [comment] 2021-08-24 10:46
Yes, this is happening for us too in 2.192.0. Ultimately it’s caused by Apple’s servers being unavailable; the fix in 2.192.0 to retry five times is a workaround and ultimately Apple will have to fix things on their end. Fastlane can’t work if the server it needs to talk to is down.

**Comment by joshdholtz** [comment] 2021-08-24 21:44
❇️ OFFICIAL UPDATE

Ahhhhhhh, this is same issue as #19264 but happening in a different module 😱 The previous issue happened on a Apple ID version of the App Store Connect API where this issue is happening on a different legacy API.

I will fix 😊

**Comment by joshdholtz** [comment] 2021-08-24 22:16
@alteral Is this still happening for you? I _think_ I fixed it but I'm not able to actually test it since I'm not able to replicate this today 🤔

**Comment by alexzchut** [comment] 2021-08-25 07:42
@joshdholtz failing for me on 2.192.0, retried several times but failing.
using **produce group** or **produce associate_group**

**Comment by alteral** [comment] 2021-08-25 09:33
@joshdholtz, for us, `produce v2.192.0` is working like a charm today. Thanks a million!

**Closed** 2021-08-25 16:26 UTC
Labels: tool: produce
