### ISSUE TITLE
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

### ISSUE THREAD

**Issue by khantthulinn** [fastlane/fastlane#3898] opened 2016-03-23 04:09 UTC
I am new to fastlane. I run fastlane ios Development and I saw error when I upload to hockey.

This is full stack. I already try some method from https://github.com/fastlane/fastlane/issues/745
and update my cert also. 

/Users/thulinn/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:923:in `connect': [!] SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (Faraday::SSLError)
	from /Users/thulinn/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:923:in `block in connect'
	from /Users/thulinn/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
	from /Users/thulinn/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:923:in `connect'
	from /Users/thulinn/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
	from /Users/thulinn/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:852:in `start'
	from /Users/thulinn/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:1375:in `request'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:82:in `perform_request'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response/follow_redirects.rb:76:in `perform_with_redirection'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response/follow_redirects.rb:64:in `call'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/faraday-0.9.2/lib/faraday/request/url_encoded.rb:15:in `call'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/faraday-0.9.2/lib/faraday/request/multipart.rb:14:in `call'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/krausefx-shenzhen-0.14.7/lib/shenzhen/plugins/hockeyapp.rb:29:in `upload_build'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.67.0/lib/fastlane/actions/hockey.rb:50:in `run'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.67.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.67.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.67.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.67.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.67.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.67.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:18:in `block (2 levels) in parsing_binding'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.67.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.67.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.67.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.67.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.67.0/lib/fastlane/runner.rb:46:in `execute'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.67.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.67.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.67.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/fastlane_core-0.39.0/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.67.0/bin/fastlane:156:in `run'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1@global/gems/fastlane-1.67.0/bin/fastlane:162:in `<top (required)>'
	from /Users/thulinn/.rvm/rubies/ruby-2.2.1/bin/fastlane:23:in `load'
	from /Users/thulinn/.rvm/rubies/ruby-2.2.1/bin/fastlane:23:in `<main>'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/thulinn/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'

My lane is like this. How shall I do? 

 gym(
      configuration: "Debug",
      scheme: "CAGInTouch - Development",
      use_legacy_build_api: true,
    )
    hockey(
      notes: 'Test Fastlane For Development',
      notify: '0', 
      status: '2', 
      api_token: 'd02a6613d1d94e2da4dc2ab9d2ec4ddc', #fake 
      notes_type: '0',
      mandatory: '1',
    )
  end

**Comment by KrauseFx** [comment] 2016-03-23 07:54
Duplicate of https://github.com/fastlane/fastlane/issues/3899

**Closed by KrauseFx** 2016-03-23 07:54 UTC
