### ISSUE TITLE
 Could not start delivery: all transports failed diagnostics

### ISSUE THREAD

**Issue by phonggenix** [fastlane/fastlane#15413] opened 2019-09-30 11:29 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
My build machine has been working perfectly until today, I got this error: 

> [18:06:29]: Going to upload updated app to App Store Connect
[18:06:29]: This might take a few minutes. Please don't interrupt the script.
[18:10:02]: [Transporter Error Output]: Could not start delivery: all transports failed diagnostics
[18:10:02]: Transporter transfer failed.
[18:10:02]: 
[18:10:02]: Could not start delivery: all transports failed diagnostics
[18:10:02]: [iTMSTransporter] 	at com.signiant.interactivetransfer.engine.TransferEngine$5.run(TransferEngine.java:3603)
[18:10:02]: [iTMSTransporter] [2019-09-30 18:10:02 ICT] <main>  INFO: Using Signiant UDP transport
[18:10:02]: [iTMSTransporter] [2019-09-30 18:10:02 ICT] <main> DBG-X: Setting the target rate to 15000001 bytes per second.
[18:10:02]: [iTMSTransporter] [2019-09-30 18:10:02 ICT] <main> DBG-X: Setting the throttle to 12500000 bytes per second.
[18:10:02]: [iTMSTransporter] [2019-09-30 18:10:02 ICT] <Transport Protocol>  INFO: The Signiant transfer engine's status is DISCONNECTED
[18:10:02]: [iTMSTransporter] [2019-09-30 18:10:02 ICT] <main> ERROR: Could not start delivery: all transports failed diagnostics
[18:10:02]: [iTMSTransporter] 
[18:10:02]: [iTMSTransporter] 
[18:10:02]: [iTMSTransporter] 
[18:10:02]: [iTMSTransporter] Package Summary:
[18:10:02]: [iTMSTransporter]  
[18:10:02]: [iTMSTransporter] 1 package(s) were not uploaded because they had problems:
[18:10:02]: [iTMSTransporter] 	/var/folders/cm/2vh32x790xj7rfnmtz66zmfw0000gn/T/d20190930-50157-1xp37go/1479519491.itmsp - Error Messages:
[18:10:02]: [iTMSTransporter] 		Could not start delivery: all transports failed diagnostics
[18:10:02]: [iTMSTransporter] [2019-09-30 18:10:02 ICT] <main> DBG-X: Returning 1
[18:10:02]: iTunes Transporter output above ^
[18:10:02]: Could not start delivery: all transports failed diagnostics
Return status of iTunes Transporter was 1: Could not start delivery: all transports failed diagnostics
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.

Searching and I found this likely related issue on Mar 1, 2018: https://github.com/fastlane/fastlane/issues/11958
But it's has been fixed into Fastlane for a long time.

I even tried explicitly set the environment variable but no luck.

I'm using Fastlane 2.131.0, Bundler 2.0.2, XCode 11 - but using an old iTMSTransporter from iOS 10.3 due to this issue: https://github.com/fastlane/fastlane/issues/15323

I guess this can be a new issue due to some update of AppStoreConnect today?
Anyone encountering such blocking issue? Please help. Thanks a lot.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.6.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.21.0 (Apple Git-122)          |
| Installation Source         | ~/.rbenv/versions/2.6.3/bin/fastlane        |
| Host                        | Mac OS X 10.14.6 (18G95)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.3/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2r  26 Feb 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.0                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.131.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.7.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| faraday_middleware        | 0.13.1       |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| multi_json                | 1.13.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.1        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| CFPropertyList            | 3.0.1        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.12.0       |
| addressable               | 2.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| excon                     | 0.66.0       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| fastimage                 | 2.1.7        |
| json                      | 2.2.0        |
| rubyzip                   | 1.2.4        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.0.2        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| mime-types-data           | 3.2019.0904  |
| mime-types                | 3.3          |
| google-cloud-env          | 1.2.1        |
| google-cloud-core         | 1.3.1        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
</details>

*generated on:* **2019-09-30**
</details>

**Comment by phonggenix** [comment] 2019-09-30 11:33
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.6.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.21.0 (Apple Git-122)          |
| Installation Source         | ~/.rbenv/versions/2.6.3/bin/fastlane        |
| Host                        | Mac OS X 10.14.6 (18G95)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.3/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2r  26 Feb 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.0                                        |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.131.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.7.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| faraday_middleware        | 0.13.1       |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| multi_json                | 1.13.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.1        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| CFPropertyList            | 3.0.1        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.12.0       |
| addressable               | 2.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| excon                     | 0.66.0       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| fastimage                 | 2.1.7        |
| json                      | 2.2.0        |
| rubyzip                   | 1.2.4        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.0.2        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| mime-types-data           | 3.2019.0904  |
| mime-types                | 3.3          |
| google-cloud-env          | 1.2.1        |
| google-cloud-core         | 1.3.1        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
</details>


*generated on:* **2019-09-30**
</details>

**Comment by EvelinJK** [comment] 2019-09-30 11:45
We have exactly the same issue and error message since updating to XCode 11 and are still searching for a solution. (Using Fastlane 2.131 but it also happened with an older version before we updated.)

Can't get it to work with either newest iTMSTransporter for Xcode 11.0+ nor with old  iTMSTransporter and XCode 10.3. 

The suggested fixes in #11953 with the `DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS = "-t DAV"` do not work for us neither.

**Comment by phonggenix** [comment] 2019-09-30 11:54
Updated:

Project 1:
- 1st and 2nd try: failed
- The 3rd try: it successfully uploaded to TestFlight 5 mins ago 😮 

Project 2:
- 1st try: failed
- I'm doing a 2nd try... waiting...

Can it possibly be some hiccups of AppStoreConnect?! 😕

**Comment by phonggenix** [comment] 2019-09-30 12:26
Updated:

Project 2 also successfully uploaded to TestFlight *without any change* in Fastlane config or anything else.

@EvelinJK I believe in your case, AppStoreConnect went back to normal at the upload time, and there's nothing do to with DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS. Can you please try again without `export DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS="-t DAV #"`?

**Comment by Mikilll94** [comment] 2019-09-30 14:48
I am having problem that some of my uploads fails and some are passing.

**Comment by jaleksynas** [comment] 2019-09-30 15:09
Seems a Duplicate of https://github.com/fastlane/fastlane/issues/15375

**Comment by Toldy** [comment] 2019-09-30 15:30
Maybe fastlane will migrate to `xcrun altool --upload-app` ?

By the time you can maybe do it like this: https://stackoverflow.com/questions/56436345/how-to-upload-to-app-store-from-command-line-with-xcode-11

**Comment by JimHowell20** [comment] 2019-09-30 16:45
same issue here, using DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS="-t DAV #" fixed it for me as well

**Comment by matcartmill** [comment] 2019-09-30 19:43
^ Same.

**Comment by Mikilll94** [comment] 2019-09-30 19:50
> same issue here, using DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS="-t DAV #" fixed it for me as well

But where to set this variable on Azure DevOps?

**Comment by matcartmill** [comment] 2019-09-30 19:59
> > same issue here, using DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS="-t DAV #" fixed it for me as well
> 
> But where to set this variable in Azure DevOps?

@Mikilll94 Doesn't Azure have a `Pipeline Variables` section? If so, I'd recommend trying there first.

**Comment by markmiscavage** [comment] 2019-09-30 20:09
Same issue here. `DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS="-t DAV #"` hasn't worked for me (been doing the export directly in Bitrise script rather than fastlane config).

**Comment by nan140114** [comment] 2019-09-30 22:23
> same issue here, using DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS="-t DAV #" fixed it for me as well

Same.

**Comment by phonggenix** [comment] 2019-10-01 09:43
Yesterday, my project has DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS set in Fastfile, but sometimes it still failed and some other times it succeeded uploading.

Today, my project got 1 failed upload (still with this "Could not start delivery: all transports failed diagnostics" error) and then 3 consecutive uploads to TestFlight. This time I didn't set DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS by any ways (Fastfile, export environment variable, etc.) and didn't change anything - I just retried.

So I guess this has nothing to do with DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS but rather a random hiccups or something like that of AppStoreConnect? 🙄 🤔

**Comment by EvelinJK** [comment] 2019-10-01 11:08
It did not work for us when we added the DELIVER... in the Fastfile.
It only worked when we executed it in the **console** before we executed our fastlane command to build and upload our project (which by the way uses React & Cordova). 

We have not tried it a second time after it was successful, but will next week when we have to publish our production build. So we'll see if this method is still working by then.

**Comment by Mikilll94** [comment] 2019-10-02 15:07
Today everything is fine.

**Comment by mollyIV** [comment] 2019-10-02 17:02
Hello 👋 

this issue most probably relates to https://github.com/fastlane/fastlane/issues/15375. I would suggest to update `fastlane` version to the newest one: [2.132.0](https://github.com/fastlane/fastlane/pull/15417). This version includes the fix, cheers 🙇

**Closed** 2019-11-09 17:33 UTC
Labels: status: waiting-for-reply, topic: itunes transporter, topic: xcode11
