### ISSUE TITLE
git push was 1 instead of 0

### ISSUE THREAD

**Issue by MaikoHermans** [fastlane/fastlane#7588] opened 2016-12-19 21:07 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I'm trying to update the build version with each build and pushing this to git. However I get an error on 
`push_to_git_remote` saying `Exit status of command 'git push origin development:development --tags' was 1 instead of 0.
error: src refspec development does not match any.` I'm not sure what's causing this. Does anyone know what it could possibly be?

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[[Ridin-3.0] $ /bin/sh -xe /var/folders/36/fw72k_5d2sz_8c23qyk8_wzr0000gn/T/hudson8439619901363060567.sh
+ fastlane beta
[21:52:03]: [32m-------------------------------------------------[0m
[21:52:03]: [32m--- Step: Verifying required fastlane version ---[0m
[21:52:03]: [32m-------------------------------------------------[0m
[21:52:03]: Your fastlane version 2.1.1 matches the minimum requirement of 1.111.0  ✅
[21:52:03]: [32m------------------------------[0m
[21:52:03]: [32m--- Step: default_platform ---[0m
[21:52:03]: [32m------------------------------[0m
[21:52:03]: [32mDriving the lane 'beta' 🚀[0m
[21:52:03]: [32m-------------------------------------[0m
[21:52:03]: [32m--- Step: ensure_git_status_clean ---[0m
[21:52:03]: [32m-------------------------------------[0m
[21:52:03]: [32mGit status is clean, all good! 💪[0m
[21:52:03]: [32m------------------------------------[0m
[21:52:03]: [32m--- Step: increment_build_number ---[0m
[21:52:03]: [32m------------------------------------[0m
[21:52:03]: [4m[36m$ cd /Users/maiko/build/workspace/Ridin-3.0 && agvtool next-version -all && cd -[0m[0m
[21:52:05]: ▸ [35mSetting version of project Ridin' to:[0m
[21:52:05]: ▸ [35m6.[0m
[21:52:05]: ▸ [35mAlso setting CFBundleVersion key (assuming it exists)[0m
[21:52:05]: ▸ [35mUpdating CFBundleVersion in Info.plist(s)...[0m
[21:52:05]: ▸ [35mUpdated CFBundleVersion in "Ridin'.xcodeproj/../Ridin'/Info.plist" to 6[0m
[21:52:05]: ▸ [35m/Users/maiko/build/workspace/Ridin-3.0[0m
[21:52:07]: [32m----------------------------------------[0m
[21:52:07]: [32m--- Step: changelog_from_git_commits ---[0m
[21:52:07]: [32m----------------------------------------[0m
[21:52:07]: [32mCollecting Git commits between werkend and HEAD[0m

no message
fastfile geupdate
no message
Updated fastfile
remove ensure_git_in_sync
Version updated
fastfile updated met changelog
Fastfile aangepast
updated version
Removed test product
versie opgehoogd
Updating build number
Update Appfile
Update fast file/appfile
Set team id
remove snapshot
Update fast file to store screenshots and sign ipa
no message
Changed pilot fastlane file
Update scheme name in fast file
no message
Updated fast file. Set versioning
updated fast file
Commented out cocoapods
Updated fast line file
fastlane added
hopelijk werkt het nu weer
Merge branch 'development' of https://git.mhermans.com/maikohermans/Ridin into development
Revert "signing aangepast"
This reverts commit c2bea2d44b85017e79045ab9bea3fcd926a05299.
zucht
Merge branch 'development' of https://git.mhermans.com/maikohermans/Ridin into development
Revert "signing aangepast"
This reverts commit c2bea2d44b85017e79045ab9bea3fcd926a05299.
Merge branch 'development' of https://git.mhermans.com/maikohermans/Ridin into development
# Conflicts:
#	Ridin.xcodeproj/project.xcworkspace/xcuserdata/fhict.xcuserdatad/UserInterfaceState.xcuserstate
project naam veranderd naar “ridin”

[21:52:07]: [32m------------------[0m
[21:52:07]: [32m--- Step: sigh ---[0m
[21:52:07]: [32m------------------[0m

+-------------------------------------+---------------------------------+
|                        [32mSummary for sigh 2.1.1[0m                         |
+-------------------------------------+---------------------------------+
| adhoc                               | false                           |
| development                         | false                           |
| skip_install                        | false                           |
| force                               | false                           |
| app_identifier                      | com.mhermans.com.mhermans.ridin |
| username                            | mwmhermans@outlook.com          |
| team_id                             | 537UN6KEVU                      |
| ignore_profiles_with_different_name | false                           |
| skip_fetch_profiles                 | false                           |
| skip_certificate_verification       | false                           |
+-------------------------------------+---------------------------------+

[21:52:07]: Starting login with user 'mwmhermans@outlook.com'
[21:52:15]: Successfully logged in
[21:52:15]: Fetching profiles...
[21:52:21]: [32mFound 1 matching profile(s)[0m
[21:52:21]: [33mDownloading provisioning profile...[0m
[21:52:24]: [32mSuccessfully downloaded provisioning profile...[0m
[21:52:24]: Installing provisioning profile...
[32m/Users/maiko/build/workspace/Ridin-3.0/AppStore_com.mhermans.com.mhermans.ridin.mobileprovision[0m
[21:52:25]: Setting Provisioning Profile type to 'app-store'
[21:52:25]: [32m-----------------[0m
[21:52:25]: [32m--- Step: gym ---[0m
[21:52:25]: [32m-----------------[0m
[21:52:25]: [4m[36m$ xcodebuild -list -project ./Ridin\'.xcodeproj[0m[0m
[21:52:28]: [4m[36m$ xcodebuild clean -showBuildSettings -scheme Ridin\' -project ./Ridin\'.xcodeproj[0m[0m

+----------------------+-------------------------------+
|                [32mSummary for gym 2.1.1[0m                 |
+----------------------+-------------------------------+
| scheme               | Ridin'                        |
| export_method        | app-store                     |
| project              | ./Ridin'.xcodeproj            |
| destination          | generic/platform=iOS          |
| output_name          | Ridin'                        |
| clean                | false                         |
| output_directory     | .                             |
| silent               | false                         |
| use_legacy_build_api | false                         |
| buildlog_path        | ~/Library/Logs/gym            |
| xcode_path           | /Volumes/Untitled 1/Xcode.app |
+----------------------+-------------------------------+

[21:52:30]: [4m[36m$ set -o pipefail && xcodebuild -scheme Ridin\' -project ./Ridin\'.xcodeproj -destination 'generic/platform=iOS' -archivePath /Users/maiko/Library/Developer/Xcode/Archives/2016-12-19/Ridin\'\ 2016-12-19\ 21.52.30.xcarchive archive | tee /Users/maiko/Library/Logs/gym/Ridin\'-Ridin\'.log | xcpretty[0m[0m
[21:52:33]: ▸ [35m[33m>[0m [39;1mBuilding[0m Ridin'/Ridin' [Release][0m
[21:52:33]: ▸ [35m[33m>[0m [39;1mCheck Dependencies[0m[0m
[21:52:49]: ▸ [35m[33m>[0m [39;1mCompiling[0m RBCollectionViewInfoFolderLayout.m[0m
[21:52:50]: ▸ [35m[33m>[0m [39;1mCompiling[0m Ridin\'_vers.c[0m
[21:52:50]: ▸ [35m[33m>[0m [39;1mCompiling[0m RBCollectionViewInfoFolderLayout.m[0m
[21:52:50]: ▸ [35m[33m>[0m [39;1mCompiling[0m Ridin\'_vers.c[0m
[21:52:50]: ▸ [35m[33m>[0m [39;1mLinking[0m Ridin\'[0m
[21:52:52]: ▸ [35m[33m>[0m [39;1mLinking[0m Ridin\'[0m
[21:52:52]: ▸ [35m[33m>[0m [39;1mCompiling[0m CollectionViewCell.xib[0m
[21:52:54]: ▸ [35m[33m>[0m [39;1mCompiling[0m LaunchScreen.storyboard[0m
[21:52:54]: ▸ [35m[33m>[0m [39;1mCompiling[0m Main.storyboard[0m
[21:53:11]: ▸ [35m[33m>[0m [39;1mProcessing[0m Info.plist[0m
[21:53:11]: ▸ [35m[33m>[0m [39;1mGenerating 'Ridin\'.app.dSYM'[0m[0m
[21:53:12]: ▸ [35m[33m>[0m [39;1mTouching[0m Ridin\'.app[0m
[21:53:32]: ▸ [35m[33m>[0m [39;1mSigning[0m /Users/maiko/Library/Developer/Xcode/DerivedData/Ridin\'-axvwnmzgklwibxduybomffzhuzzu/Build/Intermediates/ArchiveIntermediates/Ridin\'/InstallationBuildProductsLocation/Applications/Ridin\'.app[0m
[21:53:34]: ▸ [35m[33m>[0m [39;1mTouching[0m Ridin\'.app.dSYM[0m
[21:53:41]: ▸ [35m[33m>[0m [39;1mArchive[0m Succeeded[0m
[21:53:42]: [33mGenerated plist file with the following values:[0m
[21:53:42]: ▸ [35m-----------------------------------------[0m
[21:53:42]: ▸ [35m{[0m
[21:53:42]: ▸ [35m  "method": "app-store",[0m
[21:53:42]: ▸ [35m  "uploadSymbols": true,[0m
[21:53:42]: ▸ [35m  "uploadBitcode": false[0m
[21:53:42]: ▸ [35m}[0m
[21:53:42]: ▸ [35m-----------------------------------------[0m
[21:53:42]: [4m[36m$ /usr/bin/xcrun /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.1.1/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/36/fw72k_5d2sz_8c23qyk8_wzr0000gn/T/gym_config20161219-91644-1wxazml.plist' -archivePath /Users/maiko/Library/Developer/Xcode/Archives/2016-12-19/Ridin\'\ 2016-12-19\ 21.52.30.xcarchive -exportPath '/var/folders/36/fw72k_5d2sz_8c23qyk8_wzr0000gn/T/gym_output20161219-91644-1uyd41a' [0m[0m
[21:55:18]: Compressing 1 dSYM(s)
[21:55:18]: [4m[36m$ cd '/Users/maiko/Library/Developer/Xcode/Archives/2016-12-19/Ridin' 2016-12-19 21.52.30.xcarchive/dSYMs' && zip -r '/Users/maiko/build/workspace/Ridin-3.0/Ridin'.app.dSYM.zip' *.dSYM[0m[0m
sh: line 0: cd: /Users/maiko/Library/Developer/Xcode/Archives/2016-12-19/Ridin: No such file or directory

[21:55:18]: [32mSuccessfully exported and compressed dSYM file[0m
[21:55:18]: [32mSuccessfully exported and signed the ipa file:[0m
[21:55:18]: /Users/maiko/build/workspace/Ridin-3.0/Ridin'.ipa
[21:55:18]: [32m-------------------[0m
[21:55:18]: [32m--- Step: pilot ---[0m
[21:55:18]: [32m-------------------[0m
[21:55:19]: Login to iTunes Connect (mwmhermans@outlook.com)
[21:55:23]: Login successful
[21:55:24]: [32mReady to upload new build to TestFlight (App: 1130588788)...[0m
[21:55:30]: Going to upload updated app to iTunes Connect
[21:55:30]: [32mThis might take a few minutes. Please don't interrupt the script.[0m
[21:58:12]: [32miTunes Transporter successfully finished its job[0m
[21:58:13]: [32m------------------------------------------------------------------------------------------------------[0m
[21:58:13]: [32mSuccessfully uploaded package to iTunes Connect. It might take a few minutes until it's visible online.[0m
[21:58:13]: [32m------------------------------------------------------------------------------------------------------[0m
[21:58:13]: Successfully uploaded the new binary to iTunes Connect
[21:58:13]: [33mSkip waiting for build processing[0m
[21:58:13]: [33mThis means that no changelog will be set and no build will be distributed to testers[0m
[21:58:13]: [32m---------------------------------[0m
[21:58:13]: [32m--- Step: commit_version_bump ---[0m
[21:58:13]: [32m---------------------------------[0m
[21:58:13]: [4m[36m$ git rev-parse --show-toplevel[0m[0m
[21:58:13]: ▸ [35m/Users/maiko/build/workspace/Ridin-3.0[0m
[21:58:13]: [4m[36m$ git diff --name-only HEAD[0m[0m
[21:58:13]: ▸ [35mRidin'.xcodeproj/project.pbxproj[0m
[21:58:13]: ▸ [35mRidin'/Info.plist[0m
[21:58:13]: [4m[36m$ git ls-files --other --exclude-standard[0m[0m
[21:58:13]: ▸ [35mAppStore_com.mhermans.com.mhermans.ridin.mobileprovision[0m
[21:58:13]: ▸ [35mRidin'.ipa[0m
[21:58:13]: [4m[36m$ git add /Users/maiko/build/workspace/Ridin-3.0/Ridin\'.xcodeproj/project.pbxproj /Users/maiko/build/workspace/Ridin-3.0/Ridin\'/Info.plist[0m[0m
[21:58:14]: [4m[36m$ git commit -m 'Version Bump by fastlane'[0m[0m
[21:58:14]: ▸ [35m[detached HEAD a2ece25] Version Bump by fastlane[0m
[21:58:14]: ▸ [35m2 files changed, 4 insertions(+), 4 deletions(-)[0m
[21:58:14]: [32mCommitted "Version Bump by fastlane" 💾.[0m
[21:58:14]: [32m-------------------------[0m
[21:58:14]: [32m--- Step: add_git_tag ---[0m
[21:58:14]: [32m-------------------------[0m
[21:58:14]: Adding git tag 'appstore-6' 🎯.
[21:58:14]: [4m[36m$ git tag -am appstore-6\ \(fastlane\) 'appstore-6'[0m[0m
[21:58:14]: [32m--------------------------------[0m
[21:58:14]: [32m--- Step: push_to_git_remote ---[0m
[21:58:14]: [32m--------------------------------[0m
[21:58:14]: [4m[36m$ pwd[0m[0m
[21:58:14]: ▸ [35m/Users/maiko/build/workspace/Ridin-3.0[0m
[21:58:14]: [4m[36m$ git push origin development:development --tags[0m[0m
[21:58:14]: ▸ [35merror: src refspec development does not match any.[0m
[21:58:14]: ▸ [35merror: failed to push some refs to 'https://git.mhermans.com/maikohermans/Ridin.git/'[0m
+-----------------------------+--------------------------------------------------------------------+
|                                           [33mLane Context[0m                                           |
+-----------------------------+--------------------------------------------------------------------+
| DEFAULT_PLATFORM            | ios                                                                |
| PLATFORM_NAME               |                                                                    |
| LANE_NAME                   | beta                                                               |
| GIT_REPO_WAS_CLEAN_ON_START | true                                                               |
| BUILD_NUMBER                | 6                                                                  |
| FL_CHANGELOG                | no message                                                         |
|                             | fastfile geupdate                                                  |
|                             | no message                                                         |
|                             | Updated fastfile                                                   |
|                             | remove...                                                          |
| SIGH_PROFILE_PATH           | /Users/maiko/build/workspace/Ridin-3.0/AppStore_com.mhermans.co... |
| SIGH_PROFILE_PATHS          | ["/Users/maiko/build/workspace/Ridin-3.0/AppStore_com.mhermans.... |
| SIGH_UDID                   | 1f64a01f-2bb8-4b98-87b5-7a379814ee26                               |
| SIGH_UUID                   | 1f64a01f-2bb8-4b98-87b5-7a379814ee26                               |
| SIGH_PROFILE_TYPE           | app-store                                                          |
| IPA_OUTPUT_PATH             | /Users/maiko/build/workspace/Ridin-3.0/Ridin'.ipa                  |
| XCODEBUILD_ARCHIVE          | /Users/maiko/Library/Developer/Xcode/Archives/2016-12-19/Ridin'... |
+-----------------------------+--------------------------------------------------------------------+
[21:58:14]: [31mExit status of command 'git push origin development:development --tags' was 1 instead of 0.
error: src refspec development does not match any.
error: failed to push some refs to 'https://git.mhermans.com/maikohermans/Ridin.git/'
[0m

+------+-------------------------------------+-------------+
|                     [32mfastlane summary[0m                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | ensure_git_status_clean             | 0           |
| 4    | increment_build_number              | 3           |
| 5    | changelog_from_git_commits          | 0           |
| 6    | sigh                                | 17          |
| 7    | gym                                 | 173         |
| 8    | pilot                               | 174         |
| 9    | commit_version_bump                 | 1           |
| 10   | add_git_tag                         | 0           |
| 💥    | [31mpush_to_git_remote[0m                  | 0           |
+------+-------------------------------------+-------------+

[21:58:14]: [31mfastlane finished with errors[0m
[31m
[!] Exit status of command 'git push origin development:development --tags' was 1 instead of 0.
error: src refspec development does not match any.
error: failed to push some refs to 'https://git.mhermans.com/maikohermans/Ridin.git/']

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.3.0                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.rvm/gems/ruby-2.3.0/bin/fastlane         |
| Host                | Mac OS X 10.12.2 (16C67)                    |
| Ruby Lib Dir        | ~/.rvm/rubies/ruby-2.3.0/lib                |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2                                         |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.1.1"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "Walkin") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "Walkin") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.mhermans.walkin" # The bundle identifier of your app
apple_id "mwmhermans@outlook.com" # Your Apple email address

team_id "537UN6KEVU"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.1.1   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.13.6       |
| io-console                | 0.4.5        |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.8.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| plist                     | 3.2.0        |
| addressable               | 2.3.8        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.1        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| faraday_middleware        | 0.10.1       |
</details>

*generated on:* **2016-12-19**
</details>]

**Comment by MaikoHermans** [comment] 2016-12-19 21:19
@fastlane-bot 

The app gets uploaded to TestFlight without any problems so I think something else is wrong

**Comment by kirakik** [comment] 2016-12-20 15:30
Getting the same error, it seems like the `push_to_git_remote` action isn't working properly

**Comment by MaikoHermans** [comment] 2016-12-20 16:22
@KrauseFx Have you seen or heard about this issue before?
could it be related to #183

**Comment by kirakik** [comment] 2016-12-20 16:37
In my case Bitrise (not Jenkins) is my CI, not sure it's related

**Comment by MaikoHermans** [comment] 2016-12-20 16:54
@kirakik I don't think the CI is related.
I'm looking into it and right now I'm suspecting it might have something to do with the fact that I'm not using the ssh link for my gitlab repo's. I'm not sure if this is the case for you as well?

I tried creating a tag and running the exact git push command that fastlane does and it goes true.
**after**  
I had to enter my username and password

**Comment by ShurupuS** [comment] 2017-01-23 10:44
same for me Jenkins/Fastlane

**Comment by MaikoHermans** [comment] 2017-01-23 11:25
I have fixed it by doing to following:

```ruby
push_to_git_remote(
      remote: "origin",         # optional, default: "origin"
      local_branch: "HEAD",  # optional, aliased by "branch", default: "master"
      remote_branch: "development", # optional, default is set to local_branch
      force: true,    # optional, default: false
      tags: true     # optional, default: true
    )
```

**Comment by ShurupuS** [comment] 2017-01-23 12:03
It works now, but it's bad for me to hardcode the branch name, because jenkins starts the builds from different branches..

**Comment by MaikoHermans** [comment] 2017-01-23 12:05
You could always use a specific lane for a specific branch ofcourse

**Comment by ShurupuS** [comment] 2017-01-30 07:24
@KrauseFx may be you can participate in solving this? The issue is really annoying. I can provide any relevant info to investigate this

**Comment by ShurupuS** [comment] 2017-01-30 10:00
@KrauseFx @MaikoHermans Solved the issue by forced Jenkins to checkout the remote branch to the local one. In Jenkins this setting name is: **Checkout to specific local branch** Hope it helps. By default, Jenkins take the specific commit and changes it as detached HEAD, so as I see - this is the main reason for this issue.

**Comment by ohayon** [comment] 2017-02-28 21:48
Going to close this issue as it looks like it has since been solved! 🚀  Feel free to continue discussion if more issues crop up! 🐙

**Closed by ohayon** 2017-02-28 21:48 UTC
