### ISSUE TITLE
undefined method `<<' for nil:NilClass

### ISSUE THREAD

**Issue by dzungpv** [fastlane/fastlane#6731] opened 2016-10-25 12:25 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I update to Mac 10.12.1 and cannot run fastlane.
##### Complete output when running fastlane, including the stack trace and command used

```
[19:03:58]: Writing to 'fastlane/metadata/en-CA/keywords.txt'
[19:03:58]: Writing to 'fastlane/metadata/ru/keywords.txt'
[19:03:58]: Writing to 'fastlane/metadata/zh-Hant/keywords.txt'
[19:03:58]: Writing to 'fastlane/metadata/es-MX/keywords.txt'
[19:03:58]: Writing to 'fastlane/metadata/en-GB/keywords.txt'
[19:03:58]: Writing to 'fastlane/metadata/en-US/keywords.txt'
[19:03:58]: Writing to 'fastlane/metadata/ja/keywords.txt'
[19:03:58]: Writing to 'fastlane/metadata/pt-PT/keywords.txt'
[19:03:58]: Writing to 'fastlane/metadata/id/keywords.txt'
[19:03:58]: Writing to 'fastlane/metadata/zh-Hans/keywords.txt'
[19:03:58]: Writing to 'fastlane/metadata/de-DE/keywords.txt'
[19:03:58]: Writing to 'fastlane/metadata/th/keywords.txt'
[19:03:58]: Writing to 'fastlane/metadata/es-ES/keywords.txt'
[19:03:58]: Writing to 'fastlane/metadata/it/keywords.txt'
[19:03:58]: Writing to 'fastlane/metadata/pt-BR/keywords.txt'
[19:03:58]: Writing to 'fastlane/metadata/tr/keywords.txt'
[19:03:58]: Writing to 'fastlane/metadata/nl-NL/keywords.txt'
[19:03:58]: undefined method `<<' for nil:NilClass
[19:03:58]: An error occured during the setup process. Falling back to manual setup!
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.1                                     |
| Ruby                | 2.3.1                                       |
| Bundler?            | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.0                                         |
| Git                 | git version 2.8.4 (Apple Git-73)            |
| Installation Source | /usr/local/bin/fastlane                     |
| Host                | Mac OS X 10.12.1 (16B2555)                  |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.3.1_2/lib          |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |

### fastlane files:

**No Fastfile found**

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.xxx" # The bundle identifier of your app
apple_id "xxx@xxx.com" # Your Apple email address

team_id "XXXXXXXX"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| spaceship           | 0.36.2  | ✅ Up-To-Date  |
| fastlane_core       | 0.53.0  | ✅ Up-To-Date  |
| deliver             | 1.14.4  | ✅ Up-To-Date  |
| snapshot            | 1.16.2  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| pem                 | 1.3.2   | ✅ Up-To-Date  |
| cert                | 1.4.3   | ✅ Up-To-Date  |
| sigh                | 1.11.2  | ✅ Up-To-Date  |
| produce             | 1.2.1   | ✅ Up-To-Date  |
| gym                 | 1.11.3  | ✅ Up-To-Date  |
| pilot               | 1.11.1  | ✅ Up-To-Date  |
| scan                | 0.13.1  | ✅ Up-To-Date  |
| supply              | 0.7.1   | ✅ Up-To-Date  |
| match               | 0.9.0   | ✅ Up-To-Date  |
| screengrab          | 0.5.5   | ✅ Up-To-Date  |
| fastlane            | 1.106.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded***

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| terminal-table            | 1.4.5        |
| json                      | 1.8.3        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.9.2        |
| faraday_middleware        | 0.10.0       |
| dotenv                    | 2.1.1        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| plist                     | 3.1.0        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| krausefx-shenzhen         | 0.14.10      |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.8.3        |
| activesupport             | 4.2.7.1      |
| colored                   | 1.2          |
| claide                    | 1.0.1        |
| xcodeproj                 | 1.3.3        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| addressable               | 2.3.8        |
| credentials_manager       | 0.16.2       |
| multi_xml                 | 0.5.5        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160826 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| xcode-install             | 2.0.7        |
| word_wrap                 | 1.0.0        |
| multi_json                | 1.12.1       |
| babosa                    | 1.0.2        |
| excon                     | 0.54.0       |
| gh_inspector              | 1.0.2        |
| fastlane_core             | 0.53.0       |
| bundler                   | 1.13.6       |
| mini_magick               | 4.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.19       |
| io-console                | 0.4.5        |
</details>

*generated on:* **2016-10-25**
</details>

**Comment by Jianbo-Zhu** [comment] 2016-10-25 13:00
Hi I'm having a similar issue on ubuntu 14.04 while doing `deliver init`.

> [12:53:06]: Writing to 'fastlane/metadata/nl-NL/description.txt'
[12:53:06]: Writing to 'fastlane/metadata/nl-NL/keywords.txt'
[12:53:06]: Writing to 'fastlane/metadata/nl-NL/release_notes.txt'
[12:53:06]: Writing to 'fastlane/metadata/nl-NL/support_url.txt'
[12:53:06]: Writing to 'fastlane/metadata/nl-NL/marketing_url.txt'
[12:53:06]: Writing to 'fastlane/metadata/nl-NL/name.txt'

> and 180 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60%3C%3C'%20for%20nil&type=Issues&utf8=✓
/var/lib/gems/2.3.0/gems/deliver-1.14.4/lib/deliver/setup.rb:48:in `block (2 levels) in generate_metadata_files': [!] undefined method `<<' for nil:NilClass (NoMethodError)
	from /var/lib/gems/2.3.0/gems/deliver-1.14.4/lib/deliver/setup.rb:42:in `each'
	from /var/lib/gems/2.3.0/gems/deliver-1.14.4/lib/deliver/setup.rb:42:in `block in generate_metadata_files'
	from /var/lib/gems/2.3.0/gems/deliver-1.14.4/lib/deliver/setup.rb:41:in `each'
	from /var/lib/gems/2.3.0/gems/deliver-1.14.4/lib/deliver/setup.rb:41:in `generate_metadata_files'
	from /var/lib/gems/2.3.0/gems/deliver-1.14.4/lib/deliver/setup.rb:28:in `generate_deliver_file'
	from /var/lib/gems/2.3.0/gems/deliver-1.14.4/lib/deliver/setup.rb:6:in `run'
	from /var/lib/gems/2.3.0/gems/deliver-1.14.4/lib/deliver/commands_generator.rb:73:in `block (2 levels) in run'
	from /var/lib/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /var/lib/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /var/lib/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /var/lib/gems/2.3.0/gems/fastlane_core-0.53.0/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /var/lib/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /var/lib/gems/2.3.0/gems/deliver-1.14.4/lib/deliver/commands_generator.rb:128:in `run'
	from /var/lib/gems/2.3.0/gems/deliver-1.14.4/lib/deliver/commands_generator.rb:12:in `start'
	from /var/lib/gems/2.3.0/gems/deliver-1.14.4/bin/deliver:5:in `<top (required)>'
	from /usr/local/bin/deliver:23:in `load'
	from /usr/local/bin/deliver:23:in `<main>'

and when I try to do a `fastlane env`, I got below error -

> /var/lib/gems/2.0.0/gems/fastlane-1.106.1/lib/fastlane/environment_printer.rb:118:in ``': [!] No such file or directory - sw_vers (Errno::ENOENT)
	from /var/lib/gems/2.0.0/gems/fastlane-1.106.1/lib/fastlane/environment_printer.rb:118:in `print_system_environment'
	from /var/lib/gems/2.0.0/gems/fastlane-1.106.1/lib/fastlane/environment_printer.rb:7:in `get'
	from /var/lib/gems/2.0.0/gems/fastlane-1.106.1/lib/fastlane/commands_generator.rb:235:in `block (2 levels) in run'
	from /var/lib/gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /var/lib/gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /var/lib/gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /var/lib/gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /var/lib/gems/2.0.0/gems/fastlane_core-0.53.0/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /var/lib/gems/2.0.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /var/lib/gems/2.0.0/gems/fastlane-1.106.1/lib/fastlane/commands_generator.rb:246:in `run'
	from /var/lib/gems/2.0.0/gems/fastlane-1.106.1/lib/fastlane/commands_generator.rb:23:in `start'
	from /var/lib/gems/2.0.0/gems/fastlane-1.106.1/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /var/lib/gems/2.0.0/gems/fastlane-1.106.1/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'

**Comment by cjwirth** [comment] 2016-10-25 14:34
Seems to be caused by https://github.com/fastlane/fastlane/pull/6665 . It worked when I commented out the lines that were added there. I haven't investigated any more than that, though.

**Comment by gokeji** [comment] 2016-10-25 17:36
@cjwirth Good find. I also removed the changes from that commit and now `download_metadata` is working.

**Comment by steddyman** [comment] 2016-10-25 19:32
Confirmed.  Fixes it for me too.  Change needs reverting.

**Comment by KrauseFx** [comment] 2016-10-25 21:08
This is fixed with https://github.com/fastlane/fastlane/pull/6737, sorry for introducing this issue. Preparing a new release now 👍

**Closed by KrauseFx** 2016-10-25 21:08 UTC

**Comment by dzungpv** [comment] 2016-10-26 09:10
But how can i build fastlane, i am not know any about ruby. I want run but this fix version but it not release

**Comment by KrauseFx** [comment] 2016-10-26 17:00
@dzungpv Did you update to the latest version of _deliver_?
