### ISSUE TITLE
Match hangs on "Cloning remote git repo"

### ISSUE THREAD

**Issue by rborkow** [fastlane/fastlane#5537] opened 2016-07-28 17:02 UTC
See also #5473 

### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [x ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Match hangs on the cloning remote git repo step with no additional output/feedback.

##### Complete output when running fastlane, including the stack trace and command used

```
match development --verbose

+-----------------------+---------------------------------+
|                 Summary for match 0.6.1                 |
+-----------------------+---------------------------------+
| verbose               | true                            |
| git_url               | https://github.com/rborkow/xxxx |
| type                  | development                     |
| username              | xxx@xxx.xxx                   |
| git_branch            | master                          |
| keychain_name         | login.keychain                  |
| readonly              | false                           |
| force                 | false                           |
| shallow_clone         | false                           |
| force_for_new_devices | false                           |
| skip_docs             | false                           |
+-----------------------+---------------------------------+

INFO [2016-07-28 09:53:13.52]: Cloning remote git repo...
INFO [2016-07-28 09:53:13.52]: $ git clone 'https://github.com/rborkow/xxxx' '/var/folders/81/bzqxr8hs1pg9chyb8jxlqvzm0002bl/T/d20160728-67095-w632e8'
INFO [2016-07-28 09:53:13.54]: ▸ Cloning into '/var/folders/81/bzqxr8hs1pg9chyb8jxlqvzm0002bl/T/d20160728-67095-w632e8'...
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
N/A

### Environment

fastlane version (run `fastlane -v`): 1.99.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? No

**Comment by CurlyHeir** [comment] 2016-07-28 18:43
try to run only match from console passing **--verbose** flag

the reason is - probably you dont have login and password stored in your keychain (check in Keychain Access -> login keychain -> passwords ) 
if clone this repo manually and pass credentials, match will work normally after.

**Comment by rborkow** [comment] 2016-07-28 19:11
That didn't work, but changing the git repo url to be "git@github.com:rborkow/xxxx.git" led to a successful run.

**Comment by vpolouchkine** [comment] 2016-07-29 19:29
I was not able to repro this using a https://github.com/foo/bar.git link; works fine. I'm going to close this as it sounds like you're up and running.

**Closed by vpolouchkine** 2016-07-29 19:29 UTC
Labels: match

**Comment by KrauseFx** [comment] 2016-08-01 02:25
When match hangs, it almost certainly is caused by missing auth token. Best way to enter the credentials is to copy and run the clone command manually and see what kind of prompt is shown

**Comment by KrauseFx** [comment] 2016-09-10 05:27
Also I just prepared https://github.com/fastlane/fastlane/pull/6068 👍
