### ISSUE TITLE
init fails despite entering in the correct Apple ID credentials: af8f4ab25f99135a69e22363ab0f291e

### ISSUE THREAD

**Issue by Apocryphon** [fastlane/fastlane#1206] opened 2016-01-25 22:11 UTC
Please see crash report for af8f4ab25f99135a69e22363ab0f291e

**Comment by KrauseFx** [comment] 2016-01-25 22:24
Stacktrace

```
Spaceship::Client::UnexpectedResponse: {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Unauthorized access"], "info"=>nil}, "statusCode"=>"ERROR"}
  from /usr/local/bin/fastlane:23:in `<main>'
  from /usr/local/bin/fastlane:23:in `load'
  from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.53.0/bin/fastlane:155:in `<top (required)>'
  from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.53.0/bin/fastlane:149:in `run'
  from commander/delegates.rb:15:in `run!'
  from commander/runner.rb:68:in `run!'
  from commander/runner.rb:428:in `run_active_command'
  from commander/command.rb:153:in `run'
  from commander/command.rb:178:in `call'
  from commander/command.rb:178:in `call'
  from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.53.0/bin/fastlane:40:in `block (2 levels) in run'
  from fastlane/setup/setup.rb:19:in `run'
  from fastlane/setup/setup_ios.rb:29:in `run'
  from fastlane/setup/setup_ios.rb:134:in `detect_if_app_is_available'
  from spaceship/tunes/spaceship.rb:30:in `select_team'
  from spaceship/tunes/tunes_client.rb:83:in `select_team'
  from spaceship/tunes/tunes_client.rb:45:in `teams'
  from spaceship/client.rb:268:in `parse_response'
```

**Comment by patgoley** [comment] 2016-01-26 05:34
Also experiencing this issue with a similar stack trace. c4da24f26082420bedb16d9c2556112c

**Comment by patgoley** [comment] 2016-01-26 07:39
The unexpected response is coming from Spaceship::App.find(self.app_identifier) in detect_if_app_is_available in setup_ios.rb. What's strange though is that this call succeeds with the same account and bundle id if I run it with spaceship directly.

**Comment by patgoley** [comment] 2016-01-26 09:38
@Apocryphon If you try to log into iTunes Connect on the web, do you happen to get an error message? I was having this same problem and when attempting to log in, got an error saying "Your Apple ID isn't enabled for iTunes Connect". I have fixed the issue for me in this pull request: https://github.com/fastlane/fastlane/pull/1210.

**Comment by lacostej** [comment] 2016-01-26 14:37
I had the same issue on a new project, until I realized that I hadn't accepted the invitation to the team on ITC (only on developer). And fastlane isn't able to know that it seems :)

**Comment by djnbc** [comment] 2016-01-26 17:52
I have ran into this as well: 2e0b413e8e23d50631bdd2b25631e2fe

**Comment by patgoley** [comment] 2016-01-26 17:59
The problem here as @lacostej said is that the apple id doesn't have access to iTunes Connect for whatever reason. This results in a 401 in PortalClient which causes the exception. @samrobbins In this scenario, would we like to abort fastlane init with a sensible error message? Or notify the user and continue the process, skipping any iTunes Connect interactions (deliver, produce, etc).

**Comment by jxbambrick** [comment] 2016-01-29 00:39
I'm experiencing this problem and am not able to run "fastlane init". It's failing when I select between one of two teams. Both team's cause the same problem. Here's the event id: 6b49eb3acd5714e459520ba7cb21b4fd. I confirmed on Member Center, that the email address used has accepted the invitation. I am currently copying an old fastlane file into the directory for the time being. Any recommendations on work arounds?

**Comment by mikeghen** [comment] 2016-02-13 20:49
I had a similar problem and decided that I don't need ITunes Connect. @patgoley made a good comment. I just ran `sigh` and it worked fine using the creds that caused `fastlane init` to fail.

**Comment by aceontech** [comment] 2016-02-16 15:59
+1

Same thing happening with me.

**Comment by vpolouchkine** [comment] 2016-04-06 21:42
It looks like there hasn’t been any recent activity on this issue in some time, so I’m closing it. If this is still a problem, feel free to re-open a new issue and I’d be happy to help :+1:

**Closed by vpolouchkine** 2016-04-06 21:42 UTC
Labels: fastlane
