### ISSUE TITLE
spaceship crash on provisioning development macos

### ISSUE THREAD

**Issue by sp-miguel-ibero** [fastlane/fastlane#20076] opened 2022-03-17 09:12 UTC
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Fastlane spaceship crashing with "The relationship 'devices' is required but was not provided with this request." error during a `match development --platform=macos` call 

##### Command executed
`fastlane match development  --force --app_identifier=es.socialpoint.MonsterCity --platform=macos --clone_branch_directly=true --force_for_new_devices=true  --team_id=PD2V9367QH`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
+--------------------------------+-------------------------------------------------------------------+
|                                     Summary for match 2.204.3                                      |
+--------------------------------+-------------------------------------------------------------------+
| force                          | true                                                              |
| app_identifier                 | ["es.socialpoint.MonsterCity"]                                    |
| platform                       | macos                                                             |
| clone_branch_directly          | true                                                              |
| force_for_new_devices          | true                                                              |
| git_url                        | ---                                                               |
| git_branch                     | team/PD2V9367QH                                                   |
| team_id                        | PD2V9367QH                                                        |
| api_key_path                   | /var/folders/tg/fc9n_wc10kv8fs5651nfd3v40000gp/T/tmpyd1bvg7n.json |
| type                           | development                                                       |
| readonly                       | false                                                             |
| generate_apple_certs           | true                                                              |
| skip_provisioning_profiles     | false                                                             |
| username                       | miguel.ibero@socialpoint.es                                       |
| storage_mode                   | git                                                               |
| shallow_clone                  | false                                                             |
| keychain_name                  | login.keychain                                                    |
| include_all_certificates       | false                                                             |
| force_for_new_certificates     | false                                                             |
| skip_confirmation              | false                                                             |
| safe_remove_certs              | false                                                             |
| skip_docs                      | false                                                             |
| derive_catalyst_app_identifier | false                                                             |
| fail_on_name_taken             | false                                                             |
| skip_certificate_matching      | false                                                             |
| skip_set_partition_list        | false                                                             |
| verbose                        | false                                                             |
+--------------------------------+-------------------------------------------------------------------+

Cloning remote git repo...
Checking out branch team/PD2V9367QH...
🔓  Successfully decrypted certificates repo
Verifying that the certificate and profile are still valid on the Dev Portal...
Creating authorization token for App Store Connect API
Installing certificate...

+-------------------+-------------------------------------------------+
|                        Installed Certificate                        |
+-------------------+-------------------------------------------------+
| User ID           | 6TQ4W5TZ75                                      |
| Common Name       | Apple Development: Created via API (6TQ4W5TZ75) |
| Organisation Unit | PD2V9367QH                                      |
| Organisation      | Socialpoint                                     |
| Country           | US                                              |
| Start Datetime    | 2022-03-15 13:15:36 UTC                         |
| End Datetime      | 2023-03-15 13:15:35 UTC                         |
+-------------------+-------------------------------------------------+

+-------------------------------------+-------------------------------------------------------------------+
|                                        Summary for sigh 2.204.3                                         |
+-------------------------------------+-------------------------------------------------------------------+
| app_identifier                      | es.socialpoint.MonsterCity                                        |
| username                            | miguel.ibero@socialpoint.es                                       |
| force                               | true                                                              |
| cert_id                             | NGP4928278                                                        |
| provisioning_name                   | match Development es.socialpoint.MonsterCity macos                |
| ignore_profiles_with_different_name | true                                                              |
| api_key_path                        | /var/folders/tg/fc9n_wc10kv8fs5651nfd3v40000gp/T/tmpyd1bvg7n.json |
| team_id                             | PD2V9367QH                                                        |
| fail_on_name_taken                  | false                                                             |
| include_all_certificates            | false                                                             |
| platform                            | macos                                                             |
| development                         | true                                                              |
| adhoc                               | false                                                             |
| developer_id                        | false                                                             |
| skip_install                        | false                                                             |
| skip_fetch_profiles                 | false                                                             |
| skip_certificate_verification       | false                                                             |
| readonly                            | false                                                             |
+-------------------------------------+-------------------------------------------------------------------+

Creating authorization token for App Store Connect API
Fetching profiles...
Verifying certificates...
No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you
Creating new provisioning profile for 'es.socialpoint.MonsterCity' with name 'match Development es.socialpoint.MonsterCity macos' for 'macos' platform
An error occurred while verifying your certificates and profiles with the Apple Developer Portal.
If you already have your certificates stored in git, you can run `fastlane match` in readonly mode
to just install the certificates and profiles without accessing the Dev Portal.
To do so, just pass `readonly: true` to your match call.

Looking for related GitHub issues on fastlane/fastlane...

/Library/Ruby/Gems/2.6.0/gems/fastlane-2.204.3/spaceship/lib/spaceship/connect_api/api_client.rb:194:in `handle_response': [!] { (Spaceship::UnexpectedResponse)
"errors" : [ {
"id" : "8092e0e7-a127-4737-a90c-8cc14586daec",
"status" : "409",
"code" : "ENTITY_ERROR.RELATIONSHIP.REQUIRED",
"title" : "Relationship is required but was not provided.",
"detail" : "The relationship 'devices' is required but was not provided with this request.",
"source" : {
"pointer" : "data/relationships/devices"
}
} ]
}
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.204.3/spaceship/lib/spaceship/connect_api/api_client.rb:124:in `post'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.204.3/spaceship/lib/spaceship/connect_api/provisioning/client.rb:39:in `post'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.204.3/spaceship/lib/spaceship/connect_api/provisioning/provisioning.rb:234:in `post_profiles'
from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `post_profiles'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.204.3/spaceship/lib/spaceship/connect_api/models/profile.rb:76:in `create'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.204.3/sigh/lib/sigh/runner.rb:182:in `create_profile!'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.204.3/sigh/lib/sigh/runner.rb:54:in `run'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.204.3/sigh/lib/sigh/manager.rb:8:in `start'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.204.3/match/lib/match/generator.rb:109:in `generate_provisioning_profile'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.204.3/match/lib/match/runner.rb:269:in `fetch_provisioning_profile'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.204.3/match/lib/match/runner.rb:112:in `block (2 levels) in run'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.204.3/match/lib/match/runner.rb:111:in `loop'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.204.3/match/lib/match/runner.rb:111:in `block in run'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.204.3/match/lib/match/runner.rb:110:in `each'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.204.3/match/lib/match/runner.rb:110:in `run'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.204.3/match/lib/match/commands_generator.rb:69:in `block (3 levels) in run'
from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.204.3/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.204.3/match/lib/match/commands_generator.rb:188:in `run'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.204.3/match/lib/match/commands_generator.rb:26:in `start'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.204.3/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.204.3/bin/fastlane:23:in `<top (required)>'
from /usr/local/bin/fastlane:23:in `load'
from /usr/local/bin/fastlane:23:in `<main>
</pre>
</details>

### Environment

swift-driver version: 1.45.2 <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 12.2.1                                                         |
| Ruby                        | 2.6.8                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.32.0 (Apple Git-132)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 12.2.1 (21D62)                                           |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 13.3                                                           |
| Swift Version               | 5.6                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.204.3 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| atomos                          | 0.1.3        |
| CFPropertyList                  | 2.3.6        |
| claide                          | 1.0.3        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| rexml                           | 3.2.5        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.7.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.79.0       |
| faraday-net_http                | 1.0.1        |
| ruby2_keywords                  | 0.0.4        |
| faraday                         | 1.3.0        |
| unf_ext                         | 0.0.7.7      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.3        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.0.0        |
| fastimage                       | 2.2.3        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.1.0        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.0        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 1.17.2       |
| simctl                          | 1.6.8        |
| jwt                             | 2.2.2        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| declarative-option              | 0.1.0        |
| representable                   | 3.0.4        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.0.2        |
| multi_json                      | 1.15.0       |
| signet                          | 0.15.0       |
| memoist                         | 0.16.2       |
| os                              | 1.1.1        |
| googleauth                      | 0.16.0       |
| httpclient                      | 2.8.3        |
| webrick                         | 1.4.4        |
| google-apis-core                | 0.3.0        |
| google-apis-playcustomapp_v1    | 0.3.0        |
| google-apis-androidpublisher_v3 | 0.5.0        |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.1.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.2.0        |
| google-apis-storage_v1          | 0.3.0        |
| rake                            | 12.3.3       |
| digest-crc                      | 0.6.3        |
| google-cloud-storage            | 1.31.0       |
| emoji_regex                     | 3.2.2        |
| jmespath                        | 1.4.0        |
| aws-partitions                  | 1.432.0      |
| aws-eventstream                 | 1.1.1        |
| aws-sigv4                       | 1.2.3        |
| aws-sdk-core                    | 3.113.0      |
| aws-sdk-kms                     | 1.43.0       |
| aws-sdk-s3                      | 1.91.0       |
| forwardable                     | 1.2.0        |
| logger                          | 1.3.0        |
| date                            | 2.0.0        |
| stringio                        | 0.0.2        |
| zlib                            | 1.0.0        |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.2        |
| ostruct                         | 0.1.0        |
| strscan                         | 1.0.0        |
| io-console                      | 0.4.7        |
| fileutils                       | 1.1.0        |
| etc                             | 1.0.1        |
| libxml-ruby                     | 3.2.1        |
| psych                           | 3.1.0        |
| mutex_m                         | 0.1.0        |
</details>

*generated on:* **2022-03-17**
</details>

**Comment by abarisic86** [comment] 2022-03-17 13:12
Revert Fastlane to `2.176.0`

**Comment by sp-miguel-ibero** [comment] 2022-03-17 16:58
same outcome with `2.176.0`

**Comment by joshdholtz** [comment] 2022-03-17 17:15
✨ Official Update

This appears to be a duplicate of #20071. Going to close this so we can keep everything together in one issue 🙃

**Closed by joshdholtz** 2022-03-17 17:15 UTC
