### ISSUE TITLE
[Regression] Incrementing build numbers via increment_build_number and Apple Generic Versioning

### ISSUE THREAD

**Issue by mrchristopher124** [fastlane/fastlane#9517] opened 2017-06-18 18:42 UTC
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Captured Output

Command Used: `staging_hockeyapp`
<details><summary>Output/Log</summary>

```

Successfully loaded Appfile at path '...'
- app_identifier: 'XYZ'
- team_id: 'XYZ'
-------
Successfully loaded Appfile at path '...'
- app_identifier: 'XYZ'
- team_id: 'XYZ'
-------
DEBUG [2017-06-18 11:34:10.49]: Checking if there are any plugins that should be loaded...
INFO [2017-06-18 11:34:10.52]: -------------------------------------------------
INFO [2017-06-18 11:34:10.52]: --- Step: Verifying required fastlane version ---
INFO [2017-06-18 11:34:10.52]: -------------------------------------------------
INFO [2017-06-18 11:34:10.52]: Your fastlane version 2.39.1 matches the minimum requirement of 2.3.1  ✅
INFO [2017-06-18 11:34:10.52]: ------------------------------
INFO [2017-06-18 11:34:10.52]: --- Step: default_platform ---
INFO [2017-06-18 11:34:10.52]: ------------------------------
INFO [2017-06-18 11:34:10.53]: Driving the lane 'ios staging_hockeyapp' 🚀
INFO [2017-06-18 11:34:10.53]: ----------------------------------
INFO [2017-06-18 11:34:10.53]: --- Step: ensure_xcode_version ---
INFO [2017-06-18 11:34:10.53]: ----------------------------------
INFO [2017-06-18 11:34:10.61]: gem 'xcode-install' is already installed
INFO [2017-06-18 11:34:10.61]: $ xcversion selected
INFO [2017-06-18 11:34:26.44]: ▸ Xcode 8.3.3
INFO [2017-06-18 11:34:26.44]: ▸ Build version 8E3004b
INFO [2017-06-18 11:34:26.45]: Selected Xcode version is correct: 8.3.3
INFO [2017-06-18 11:34:26.45]: -------------------------------------
INFO [2017-06-18 11:34:26.45]: --- Step: ensure_git_status_clean ---
INFO [2017-06-18 11:34:26.45]: -------------------------------------
INFO [2017-06-18 11:34:26.45]: $ git status --porcelain
INFO [2017-06-18 11:34:27.02]: Git status is clean, all good! 💪
INFO [2017-06-18 11:34:27.02]: ----------------------------
INFO [2017-06-18 11:34:27.02]: --- Step: reset_git_repo ---
INFO [2017-06-18 11:34:27.02]: ----------------------------
INFO [2017-06-18 11:34:27.02]: $ git reset --hard HEAD
INFO [2017-06-18 11:34:27.46]: ▸ HEAD is now at e360cea set apple versioning at main project level for fastlane
INFO [2017-06-18 11:34:27.46]: $ git clean -qfdx
INFO [2017-06-18 11:34:27.48]: Git repo was reset and cleaned back to a pristine state.
INFO [2017-06-18 11:34:27.48]: ------------------------------------
INFO [2017-06-18 11:34:27.48]: --- Step: increment_build_number ---
INFO [2017-06-18 11:34:27.48]: ------------------------------------
WARN [2017-06-18 11:34:28.26]: Lane Context:
INFO [2017-06-18 11:34:28.26]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios staging_hockeyapp", :GIT_REPO_WAS_CLEAN_ON_START=>true}
ERROR [2017-06-18 11:34:28.26]: Apple Generic Versioning is not enabled in this project.
Before being able to increment and read the version number from your Xcode project, you first need to setup your project properly. Please follow the guide at https://developer.apple.com/library/content/qa/qa1827/_index.html
INFO [2017-06-18 11:34:28.26]: Successfully generated documentation at path '...'

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | Verifying required     | 0           |
|      | fastlane version       |             |
| 2    | default_platform       | 0           |
| 3    | ensure_xcode_version   | 15          |
| 4    | ensure_git_status_cle  | 0           |
|      | an                     |             |
| 5    | reset_git_repo         | 0           |
| 💥   | increment_build_numbe  | 0           |
|      | r                      |             |
+------+------------------------+-------------+

ERROR [2017-06-18 11:34:28.29]: fastlane finished with errors


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.3.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rvm/rubies/ruby-2.3.3/bin/fastlane       |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.3/lib                |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.3.1"

default_platform :ios

platform :ios do
  before_all do
    ensure_xcode_version(version: "8.3.3")
    ensure_git_status_clean
    reset_git_repo
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    # cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Staging Build to HockeyApp"
  desc "This will also make sure the profile is up to date"
  lane :staging_hockeyapp do

    increment_build_number(
      xcodeproj: '...'
    )    
    commit_version_bump(
      xcodeproj: '...'
    )

    push_to_git_remote(
      remote: 'origin',         # optional, default: 'origin'
      local_branch: 'staging',  # optional, aliased by 'branch', default: 'master'
      remote_branch: 'staging', # optional, default is set to local_branch
      force: false               # optional, default: false
    )
    
    match(
      git_branch: "...",
      git_url: "...",
      app_identifier: "...",
      team_id: "...",
      type: "enterprise", 
      readonly: true)

    gym(
      workspace: "....",
      configuration: "Release-Staging",
      scheme: "XYZ",
      silent: false,
      clean: true,
      include_bitcode: false,
      include_symbols: true,
      output_directory: "./Build", # Destination directory. Defaults to current directory.
      output_name: "XYZ-staging.ipa",       # specify the name of the .ipa file to generate (including file extension)
      sdk: "iphoneos10.3"                     # use SDK as the name or path of the base SDK when building the project.
    )

    hockey(
      api_token: 'XYZ',
      ipa: './Build/XYZ-staging.ipa',
      notify: '0',
      notes: last_git_commit[:message] + "\n(Uploaded automatically via fastlane)"
    )

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "..." # The bundle identifier of your app
#apple_id "..." # Your Apple email address

team_id "..."  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.39.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.13.7       |
| io-console                | 0.4.5        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.1        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.1       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| faraday_middleware        | 0.10.1       |
| json                      | 2.0.2        |
</details>

*generated on:* **2017-06-18**
</details>

### Regression Pull Request

It's our opinion that this pull request caused the regression:

https://github.com/fastlane/fastlane/pull/9474

**Comment by mrchristopher124** [comment] 2017-06-19 18:05
Note that rolling back to 2.39.0 resolves this issue.

**Comment by PetrosIchor** [comment] 2017-06-19 20:46
You can also add those missing values.  Ran into it myself this morning.  Adding them to the project fixed it.

**Comment by ohayon** [comment] 2017-06-19 20:48
Apologies for this issue! A hotfix is going out right now that will fix the issue! Stay tuned! 🚀

**Comment by ohayon** [comment] 2017-06-19 20:54
New release just went out! Give it a shot and let us know if this is still an issue for you all!

**Comment by mpirri** [comment] 2017-06-19 20:56
We just shipped `fastlane` 2.39.2 with a fix for this issue. When you have a chance, @mrchristopher124 , can you update and see if it fixed the issue?  Thanks so much!

**Comment by lbrownell-gpsw** [comment] 2017-06-19 23:17
We've had a related issue that cropped up in 2.39.1 and is still in 2.39.2.  We use the xcodeproj argument to increment_build_number and increment_version_number, as we're not in the directory that contains the xcodeproj file, and that seems to be ignored.  Rolling back to 2.39.0 works.

**Comment by afgallo** [comment] 2017-06-20 16:45
Hi @ohayon this is still an issue for me after upgrading from 2.25.0 to 2.39.2. Should I rollback to 2.25.0?

**Comment by ohayon** [comment] 2017-06-20 18:20
Hey @lbrownell-gpsw thanks for all of that information! This action is really only supposed to work for setups that have AGV enabled. If you want to set the build number to an explicit value, you can use the `set_info_plist_value` command. Does that help out at all?

@afgallo - do you have Apple Generic Versioning enabled? https://developer.apple.com/library/content/qa/qa1827/_index.html

**Comment by lbrownell-gpsw** [comment] 2017-06-20 22:30
@ohayon I've issued a PR to that app group to make us AGV-proper.  If that fails, I'll look at `set_info_plist_value` (plist buddy!).  Thanks!

**Comment by afgallo** [comment] 2017-06-20 22:58
nope, doesn't seem so @ohayon 

![image](https://user-images.githubusercontent.com/9999415/27359555-ccb503f8-55f2-11e7-9ef4-cb59a7e42f4b.png)

**Comment by afgallo** [comment] 2017-06-21 12:19
OK @ohayon followed the steps [here](https://stackoverflow.com/questions/39673280/how-to-set-current-project-version-in-xcode-8) and all works now. Still confused as to why this happened but suspect was due to the fastlane upgrade. Cheers!

**Comment by mrchristopher124** [comment] 2017-06-21 14:25
Fix works for me. Updated to 2.39.2 and we're back in action. Thanks!

**Comment by mpirri** [comment] 2017-06-21 14:28
Looks like this is working everyone now, so I'm going to close this issue.  If anyone is still having issues or has any other questions, please feel free to open another issue on github.

Thanks for all your help and patience with this, folks!

**Closed by mpirri** 2017-06-21 14:28 UTC

**Comment by ohayon** [comment] 2017-06-21 17:49
Hey @afgallo - This happened because even though in your case, the build number was getting set, `agvtool` was returning a non-zero exit code, so this could cause some unintended behavior. We want to make sure that people who are using the `increment_build_number` action are using AGV so that all behavior is expected.

**Comment by afgallo** [comment] 2017-06-21 19:15
Cool thanks for taking the time to explain it to me @ohayon. It all makes sense now!
