### ISSUE TITLE
get_build_number from project fails if not only digits

### ISSUE THREAD

**Issue by nmayafit** [fastlane/fastlane#1065] opened 2016-01-06 20:43 UTC
I tried to use get_build_number(xcodeproj: "test.xcodeproj") where the build number contains also letter e.g TE102.
The letters let me know the environment.
The lane failed with the error "agvtool what-version -terse' was 6 instead of 0. (RuntimeError)"

**Comment by RuiAAPeres** [comment] 2016-01-11 11:56
Having the same issue. cc @KrauseFx

**Comment by nmayafit** [comment] 2016-01-11 11:59
I solved it by using Shenzhen:
Shenzhen::PlistBuddy.print(options[:plist], 'CFBundleVersion')
Although this one will only grab the build number.

In order to set it I am running sh before the gym that changes the build number:

orig=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" ../Plists/info.plist)
echo "Old build version is ${orig}"

buildNumber=${orig:2}
buildText=${orig:0:2}
buildNumber=$(($buildNumber + 1))
orig=$buildText$buildNumber

/usr/libexec/PlistBuddy -c "Set :CFBundleVersion $orig" ../Plists/info.plist
echo "Updating TEST build version to ${orig}"

**Comment by crazyyuan** [comment] 2016-03-03 08:43
Having the same issue @nmayafit

**Comment by vpolouchkine** [comment] 2016-04-08 18:16
@crazyyuan Is this still an issue for you?

**Comment by nmayafit** [comment] 2016-04-10 06:49
Its still an issue for me. Rather not use Shenzhen only for this tweak.

**Comment by TKBurner** [comment] 2016-04-11 20:47
@nmayafit Thanks for following up. We are going to take another look 👍

**Comment by robegamesios** [comment] 2016-04-11 23:52
question about get_build_number(xcodeproj: "test.xcodeproj"), should it get it from the info.plist Bundle version instead of Current Project Version in Build Settings?  My issue is it picks it up from Current Project Version but the Current Project Version does not pick it up from the info.plist Bundle version. And so they are out of sync.  And I don't want to keep updating the Current Projecton Version in  build settings . thanks

**Comment by TKBurner** [comment] 2016-04-12 20:27
@robegamesios Thanks for following up. We are going to have a look as there have been a couple reports recently 👍

**Comment by asfalcone** [comment] 2016-04-19 19:21
@nmayafit Can you provide an example project where this is reproducible? I cannot reproduce the problem you described by running `get_build_number` on a project with a non-integer build number.

![image](https://cloud.githubusercontent.com/assets/1848683/14652443/59b1cbda-0642-11e6-8065-67643ffd0cac.png)

**Comment by asfalcone** [comment] 2016-04-19 19:30
@nmayafit Actually I think this is related to Xcode 7.3 changes and the version of `xcodeproj` that you have installed. I was able to reproduce after running `update_app_identifier` on my project. Check out the resolution to this issue [here](https://github.com/fastlane/fastlane/issues/3945#issuecomment-202529688).

**Comment by asfalcone** [comment] 2016-05-16 18:36
I'm going to close this issue since it has been open for a while without follow up.

**Closed by asfalcone** 2016-05-16 18:36 UTC
Labels: action, awaiting-reply, bug
