### ISSUE TITLE
Error upload .aab android to play store

### ISSUE THREAD

**Issue by Kyba1985** [fastlane/fastlane#16588] opened 2020-06-10 13:19 UTC
Hi , i'm using:

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.149.1 | ✅ Up-To-Date  |

line execution instructions:

  desc "Build a release app bundle"
  lane :releasebundle do
    gradle(task: 'bundle', build_type: 'Release')
    upload_to_play_store(
      track: 'internal',
      package_name:'com.goodsoftw.pannelloorariotreninew',
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_apk:true,
      skip_upload_aab:false,
      json_key: '/Users/francescogodino/AndroidStudioProjects/pannello_orario_treni/fastlane/service_account2.json'
    )
    end

### Issue Description

Cannot upload apk or aab to google play with client api. Error on terminal during fastlane build:

[!] Google Api Error: Invalid request - Access Not Configured. Google Play Developer API has not been used in project 18049999557 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/androidpublisher.googleapis.com/overview?project=18049999557 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.

All setup steps are done and if i go to the suggested link i see that the api is enabled. 

##### Command executed

 fastlane android releasebundle --verbose

##### Complete output when running fastlane, including the stack trace and command used

ERROR [2020-06-10 15:07:24.71]: fastlane finished with errors
Traceback (most recent call last):
        49: from /usr/local/bin/fastlane:23:in `<main>'
        48: from /usr/local/bin/fastlane:23:in `load'
        47: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/bin/fastlane:23:in `<top (required)>'
        46: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
        45: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
        44: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
        43: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        42: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
        41: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        40: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        39: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        38: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
        37: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        36: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
        35: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
        34: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        33: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        32: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/lane.rb:33:in `call'
        31: from Fastfile:27:in `block (2 levels) in parsing_binding'
        30: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
        29: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        28: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
        27: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
        26: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:253:in `block in execute_action'
        25: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
        24: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:261:in `block (2 levels) in execute_action'
        23: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/actions/upload_to_play_store.rb:33:in `run'
        22: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/supply/lib/supply/uploader.rb:13:in `perform_upload'
        21: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/supply/lib/supply/uploader.rb:318:in `upload_bundles'
        20: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/supply/lib/supply/uploader.rb:318:in `each'
        19: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/supply/lib/supply/uploader.rb:320:in `block in upload_bundles'
        18: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/supply/lib/supply/client.rb:344:in `upload_bundle'
        17: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/supply/lib/supply/client.rb:80:in `call_google_api'
        16: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/supply/lib/supply/client.rb:345:in `block in upload_bundle'
        15: from /Library/Ruby/Gems/2.6.0/gems/google-api-client-0.38.0/generated/google/apis/androidpublisher_v3/service.rb:458:in `upload_edit_bundle'
        14: from /Library/Ruby/Gems/2.6.0/gems/google-api-client-0.38.0/lib/google/apis/core/base_service.rb:360:in `execute_or_queue_command'
        13: from /Library/Ruby/Gems/2.6.0/gems/google-api-client-0.38.0/lib/google/apis/core/http_command.rb:102:in `execute'
        12: from /Library/Ruby/Gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
        11: from /Library/Ruby/Gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
        10: from /Library/Ruby/Gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
         9: from /Library/Ruby/Gems/2.6.0/gems/google-api-client-0.38.0/lib/google/apis/core/http_command.rb:110:in `block in execute'
         8: from /Library/Ruby/Gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
         7: from /Library/Ruby/Gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
         6: from /Library/Ruby/Gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
         5: from /Library/Ruby/Gems/2.6.0/gems/google-api-client-0.38.0/lib/google/apis/core/http_command.rb:113:in `block (2 levels) in execute'
         4: from /Library/Ruby/Gems/2.6.0/gems/google-api-client-0.38.0/lib/google/apis/core/upload.rb:250:in `execute_once'
         3: from /Library/Ruby/Gems/2.6.0/gems/google-api-client-0.38.0/lib/google/apis/core/upload.rb:174:in `process_response'
         2: from /Library/Ruby/Gems/2.6.0/gems/google-api-client-0.38.0/lib/google/apis/core/http_command.rb:193:in `process_response'
         1: from /Library/Ruby/Gems/2.6.0/gems/google-api-client-0.38.0/lib/google/apis/core/api_command.rb:121:in `check_status'
/Library/Ruby/Gems/2.6.0/gems/google-api-client-0.38.0/lib/google/apis/core/http_command.rb:227:in `check_status': Invalid request (Google::Apis::ClientError)
        35: from /usr/local/bin/fastlane:23:in `<main>'
        34: from /usr/local/bin/fastlane:23:in `load'
        33: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/bin/fastlane:23:in `<top (required)>'
        32: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
        31: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
        30: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
        29: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        28: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
        27: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        26: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        25: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        24: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
        23: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        22: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
        21: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
        20: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        19: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        18: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/lane.rb:33:in `call'
        17: from Fastfile:27:in `block (2 levels) in parsing_binding'
        16: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
        15: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        14: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
        13: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
        12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:253:in `block in execute_action'
        11: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
        10: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:261:in `block (2 levels) in execute_action'
         9: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/actions/upload_to_play_store.rb:33:in `run'
         8: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/supply/lib/supply/uploader.rb:13:in `perform_upload'
         7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/supply/lib/supply/uploader.rb:318:in `upload_bundles'
         6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/supply/lib/supply/uploader.rb:318:in `each'
         5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/supply/lib/supply/uploader.rb:320:in `block in upload_bundles'
         4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/supply/lib/supply/client.rb:344:in `upload_bundle'
         3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/supply/lib/supply/client.rb:79:in `call_google_api'
         2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/supply/lib/supply/client.rb:94:in `rescue in call_google_api'
         1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': [!] Google Api Error: Invalid request - Access Not Configured. Google Play Developer API has not been used in project 18049999557 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/androidpublisher.googleapis.com/overview?project=18049999557 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry. (FastlaneCore::Interface::FastlaneError)

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.5                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.21.1 (Apple Git-122.3)                           |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.5 (19F96)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.3.1                                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.16.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.0        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.73.0       |
| faraday                   | 1.0.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.0        |
| googleauth                | 0.12.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.2        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.5.1        |
| google-cloud-storage      | 1.26.2       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.1.4        |
| aws-sdk-core              | 3.98.0       |
| aws-sdk-kms               | 1.33.0       |
| aws-sdk-s3                | 1.67.1       |
| CFPropertyList            | 3.0.2        |
| json                      | 2.3.0        |
| aws-partitions            | 1.327.0      |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |

**Comment by titoasty** [comment] 2020-06-11 13:11
same here, and fastlane run validate_play_store_json_key is successful.

**Comment by zhjuncai** [comment] 2020-06-12 01:14
same issue here.
I had done following settings:
- enable the Google Play Android Developer in google developer console project
- Link the project to API Access in google play

```
DEBUG [2020-06-12 08:59:01.12]: All plugins are up to date
ERROR [2020-06-12 08:59:01.12]: fastlane finished with errors
DEBUG [2020-06-12 08:59:01.12]: All plugins are up to date
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
FastlaneCore::Interface::FastlaneError: [!] Google Api Error: Invalid request - Access Not Configured. Google Play Developer API has not been used in project 191456452566 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/androidpublisher.googleapis.com/overview?project=191456452566 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/supply/lib/supply/client.rb:94:in `rescue in call_google_api'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/supply/lib/supply/client.rb:79:in `call_google_api'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/supply/lib/supply/client.rb:344:in `upload_bundle'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/supply/lib/supply/uploader.rb:320:in `block in upload_bundles'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/supply/lib/supply/uploader.rb:318:in `each'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/supply/lib/supply/uploader.rb:318:in `upload_bundles'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/supply/lib/supply/uploader.rb:13:in `perform_upload'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/actions/upload_to_play_store.rb:33:in `run'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:261:in `block (2 levels) in execute_action'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:253:in `block in execute_action'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:47:in `block (2 levels) in parsing_binding'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.149.1/bin/fastlane:23:in `<top (required)>'
  /usr/local/bin/fastlane:23:in `load'
  /usr/local/bin/fastlane:23:in `<top (required)>'
```

**Comment by zemos** [comment] 2020-06-12 08:01
It also happens to me. I tried to generate new key, disable/enable Google Play Android Developer in developer console. Nothing helped. Key validation passes with success.

**Comment by jogee** [comment] 2020-06-12 11:03
Same issue here, has anyone tried with an older version?

**Comment by zemos** [comment] 2020-06-12 11:12
I tried on 2.146 and this also happens.

**Comment by samouds** [comment] 2020-06-12 12:39
Same here ! version : 2.137.0

**Comment by jogee** [comment] 2020-06-12 12:50
Probably duplicate of #16593

**Closed** 2020-06-13 21:49 UTC
Labels: tool: supply
