### ISSUE TITLE
Spaceship– 'Bad Request' and crash on `match development`

### ISSUE THREAD

**Issue by cartfisk** [fastlane/fastlane#5798] opened 2016-08-18 20:47 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When running match development to generate certificates to share, spaceship crashes while trying to create new ones. Also crashes if there is a generated certificate but you have an empty match repo. To be clear, I am trying to run `match` standalone to troubleshoot, thus why my fastfile includes no mention of it.

##### Complete output when running fastlane, including the stack trace and command used

```

+-----------------------+------------------------------------------+
|                     Summary for match 0.6.2                      |
+-----------------------+------------------------------------------+
| git_url               | XXXXXXXXXXX |
| type                  | development                              |
| git_branch            | master                                   |
| username              | XXXXXXXXXXX                            |
| keychain_name         | login.keychain                           |
| readonly              | false                                    |
| team_id               | XXXXXXXXXX                               |
| verbose               | false                                    |
| force                 | false                                    |
| shallow_clone         | false                                    |
| force_for_new_devices | false                                    |
| skip_docs             | false                                    |
+-----------------------+------------------------------------------+

[15:34:19]: Cloning remote git repo...
[15:34:19]: 🔓  Successfully decrypted certificates repo
[15:34:19]: Verifying that the certificate and profile are still valid on the Dev Portal...
[15:34:21]: To not be asked about this value, you can specify it using 'app_identifier'
The bundle identifier of your app: XXXXXXXXXXX
[15:34:31]: Couldn't find a valid code signing identity in the git repo for development... creating one for you now

+---------------+----------------------------------------------------+
|                       Summary for cert 1.4.1                       |
+---------------+----------------------------------------------------+
| development   | true                                               |
| force         | true                                               |
| username      | XXXXXXXXXXX                             |
| team_id       | XXXXXXXXXXX                                         |
| keychain_path | /Users/carterkonz/Library/Keychains/login.keychain |
+---------------+----------------------------------------------------+

[15:34:31]: Starting login with user 'XXXXXXXXXXX'
[15:34:33]: Successfully logged in
[15:34:33]: 🔒  Successfully encrypted certificates repo

Looking for related GitHub issues on fastlane/fastlane...

➡️  crash on ad_hoc provisioning profile delete
   https://github.com/fastlane/fastlane/issues/3427 [closed] 1 💬
   08 Mar 2016

➡️  crash on ad_hoc provisioning profile delete!
   https://github.com/fastlane/fastlane/issues/3485 [closed] 0 💬
   08 Mar 2016

/Users/carterkonz/.rbenv/versions/2.3.1/lib/ruby/2.3.0/json/common.rb:156:in `parse': [!] 784: unexpected token at 'Bad Request' (Faraday::ParsingError)
	from /Users/carterkonz/.rbenv/versions/2.3.1/lib/ruby/2.3.0/json/common.rb:156:in `parse'
	from /Users/carterkonz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response/parse_json.rb:11:in `block in <class:ParseJson>'
	from /Users/carterkonz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:48:in `parse'
	from /Users/carterkonz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:39:in `process_response'
	from /Users/carterkonz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:32:in `block in call'
	from /Users/carterkonz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
	from /Users/carterkonz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Users/carterkonz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Users/carterkonz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /Users/carterkonz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
	from /Users/carterkonz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spaceship-0.31.2/lib/spaceship/client.rb:411:in `block in send_request'
	from /Users/carterkonz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spaceship-0.31.2/lib/spaceship/client.rb:328:in `with_retry'
	from /Users/carterkonz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spaceship-0.31.2/lib/spaceship/client.rb:410:in `send_request'
	from /Users/carterkonz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spaceship-0.31.2/lib/spaceship/client.rb:385:in `request'
	from /Users/carterkonz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spaceship-0.31.2/lib/spaceship/portal/portal_client.rb:284:in `create_certificate!'
	from /Users/carterkonz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spaceship-0.31.2/lib/spaceship/portal/certificate.rb:298:in `create!'
	from /Users/carterkonz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cert-1.4.1/lib/cert/runner.rb:137:in `create_certificate'
	from /Users/carterkonz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cert-1.4.1/lib/cert/runner.rb:37:in `run'
	from /Users/carterkonz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cert-1.4.1/lib/cert/runner.rb:6:in `launch'
	from /Users/carterkonz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/match-0.6.2/lib/match/generator.rb:19:in `generate_certificate'
	from /Users/carterkonz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/match-0.6.2/lib/match/runner.rb:49:in `certificate'
	from /Users/carterkonz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/match-0.6.2/lib/match/runner.rb:17:in `run'
	from /Users/carterkonz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/match-0.6.2/lib/match/commands_generator.rb:55:in `block (3 levels) in run'
	from /Users/carterkonz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Users/carterkonz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Users/carterkonz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/carterkonz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane_core-0.50.2/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
	from /Users/carterkonz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Users/carterkonz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/match-0.6.2/lib/match/commands_generator.rb:121:in `run'
	from /Users/carterkonz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/match-0.6.2/lib/match/commands_generator.rb:12:in `start'
	from /Users/carterkonz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/match-0.6.2/bin/match:6:in `<top (required)>'
	from /Users/carterkonz/.rbenv/versions/2.3.1/bin/match:23:in `load'
	from /Users/carterkonz/.rbenv/versions/2.3.1/bin/match:23:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
fastlane_version "1.96.0"

default_platform :ios

platform :ios do
  before_all do
    ENV["SLACK_URL"] = "XXXXXX"
    unlock_keychain(
      path: "~/Library/Keychains/login.keychain",
      password: "XXXXXX"
    )

  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :dev do
    recreate_schemes(
      project: 'XXXXXX.xcodeproj'
    )
    increment_build_number({
      build_number: latest_testflight_build_number(
        app_identifier: "XXXXXX"
      ) + 1
    })
    # match(type: "appstore") # more information: https://codesigning.guide
    # Build your app - more options available
    cert
    sigh(
      app_identifier: "XXXXXX"
    )
    gym(
      scheme: "XXXXXX"
    )
    # Upload to Testflight
    pilot(
      app_identifier: "XXXXXX",
      skip_waiting_for_build_processing: true
    )

  end

  after_all do |lane|

  end

  error do |lane, exception|

  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```

### Environment

fastlane version (run `fastlane -v`): 1.101.0

- [ ] Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

- [x] Do you use a Ruby environment manager (e.g. [ ] `chruby`, [x] `rbenv`, [ ] `rvm`)?

**Comment by cartfisk** [comment] 2016-08-18 21:15
I have checked the Code Signing Troubleshooting Guide.

**Comment by KrauseFx** [comment] 2016-08-18 21:19
This seems like a server error. Did the setup work for you before?

**Comment by cartfisk** [comment] 2016-08-18 21:21
No, this is the first time I have attempted to set up match.

**Comment by andyshephard** [comment] 2016-08-18 21:23
I've actually been trying to set up 'match' and 'cert' for the past couple of hours now, getting the same 'Bad Request' error.

**Comment by z-lake** [comment] 2016-08-18 21:25
Same here. I've been trying to run match adhoc for a couple of hours to no avail

**Comment by kdawgwilk** [comment] 2016-08-18 21:46
I am experiencing on a setup with match that worked previously.  I had to nuke match's development certs and pp because a developer attempted the "Fix Issue" button :( and when I tried to re-create everything after the nuke I started getting server errors when trying to create new certs

**Comment by BennettSmith** [comment] 2016-08-18 21:57
Having the same issue here.  We have been using match without issue for a while. Today we did a nuke of development and then ran "match development".  We get the bad request error.  :-(

**Comment by jverdi** [comment] 2016-08-18 22:21
+1 - unexpected token at 'Bad Request' for me when running match. This setup was previously working fine

**Comment by raphagodoi** [comment] 2016-08-18 22:49
+1 - unexpected token at 'Bad Request' for me when running match. This setup was previously working fine

**Comment by KrauseFx** [comment] 2016-08-18 23:49
Thanks everybody, I can reproduce, and I'm already working on a fix 🚀

**Comment by KrauseFx** [comment] 2016-08-19 00:17
Pull request is ready, we'll push a new release in a few minutes https://github.com/fastlane/fastlane/pull/5803 🚀

**Comment by KrauseFx** [comment] 2016-08-19 00:39
The new release is live, please update using `[sudo] gem update spaceship` or if you're using `bundler`, use `bundle update` 🚀 
Please let us know if that solves the problem for you 👍

**Comment by cartfisk** [comment] 2016-08-19 00:50
@KrauseFx Working flawlessly, thank you! 🍰 Excellent support, gotta hand it to you. We really appreciate it.

**Comment by jverdi** [comment] 2016-08-19 01:39
I can also confirm that the fix is working 👍 
thanks for the quick turnaround

**Comment by raphagodoi** [comment] 2016-08-19 02:28
Nike work @KrauseFx everything woking here! Thanks!

**Comment by CareerFairPlus** [comment] 2016-08-19 21:28
I'm seeing the same issue with PEM @KrauseFx.  Can you release a fix for that to please?

**Comment by KrauseFx** [comment] 2016-08-19 21:30
@CareerFairPlus Have you updated to the latest version of spaceship that was released a few minutes ago?

**Comment by CareerFairPlus** [comment] 2016-08-19 21:36
Yes, I'm on 0.31.5

**Comment by asfalcone** [comment] 2016-08-22 18:46
@CareerFairPlus `0.31.7` is the latest release.

**Comment by asfalcone** [comment] 2016-08-22 18:49
i'm going to close this issue since the origin problem with `cert` and `match` have been fixed. 

If, after updating to 0.31.7, you're still seeing `Bad Request` please follow #5827 where we will continue to look for a fix for the remaining issues.

**Closed by asfalcone** 2016-08-22 18:49 UTC
Labels: spaceship
