### ISSUE TITLE
Badge action fail with fastlane 2.19.1

### ISSUE THREAD

**Issue by AymenFarrah** [fastlane/fastlane#8428] opened 2017-03-03 09:03 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

im using badge action --verbose, badge **update my app icon but fail after**, so i had this error : 

i use the action badge from a Lane in the fast file

```
 --- Step: Verifying required fastlane version ---
INFO [2017-03-03 09:52:33.58]: -------------------------------------------------
INFO [2017-03-03 09:52:33.58]: Your fastlane version 2.19.1 matches the minimum requirement of 2.6  ✅
INFO [2017-03-03 09:52:33.58]: ------------------------------
INFO [2017-03-03 09:52:33.58]: --- Step: default_platform ---
INFO [2017-03-03 09:52:33.58]: ------------------------------
INFO [2017-03-03 09:52:33.58]: Driving the lane 'ios addBadge' 🚀
INFO [2017-03-03 09:52:33.59]: -------------------
INFO [2017-03-03 09:52:33.59]: --- Step: badge ---
INFO [2017-03-03 09:52:33.59]: -------------------
INFO [2017-03-03 09:52:33.67]: gem 'badge' is already installed
DEBUG [2017-03-03 09:52:33.79]: Verbose active...
DEBUG [2017-03-03 09:52:33.79]: Parameters: {:dark=>nil, :custom=>nil, :no_badge=>true, :shield=>"37.0-BASKET-blue", :alpha=>nil, :shield_io_timeout=>nil, :glob=>nil, :alpha_channel=>nil, :shield_gravity=>nil, :shield_no_resize=>true}
INFO [2017-03-03 09:52:33.79]: Start adding badges...
DEBUG [2017-03-03 09:52:33.79]: Trying to load image from shield.io. Timeout: 10s
DEBUG [2017-03-03 09:52:34.21]: Adding shield.io image ontop of icon
DEBUG [2017-03-03 09:52:34.21]: Adding shield.io image ontop of icon
INFO [2017-03-03 09:52:38.13]: Badged \o/!


```

```
DEBUG [2017-03-03 09:52:38.14]: /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
/usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
Fastfile:92:in `block (2 levels) in parsing_binding'
/usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/lane.rb:33:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/lane.rb:33:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
/usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
/usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
/usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
/usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
/usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/commands_generator.rb:105:in `block (2 levels) in run'
/usr/local/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
/usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
/usr/local/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
/usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/commands_generator.rb:302:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
/usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/cli_tools_distributor.rb:65:in `take_off'
/usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/bin/fastlane:15:in `<top (required)>'
/usr/local/bin/fastlane:23:in `load'
/usr/local/bin/fastlane:23:in `<main>'

```

```
ERROR [2017-03-03 10:00:12.82]: fastlane finished with errors
/usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane_core/lib/fastlane_core/ui/interface.rb:146:in `user_error!': [!] Could not find action, lane or variable ' '. Check out the documentation for more details: https://docs.fastlane.tools/actions (FastlaneCore::Interface::FastlaneError)
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/runner.rb:160:in `rescue in trigger_action_by_name'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:92:in `block (2 levels) in parsing_binding'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/commands_generator.rb:105:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/commands_generator.rb:302:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/cli_tools_distributor.rb:65:in `take_off'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/bin/fastlane:15:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

Badge work but fail after succeed immediately

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.19.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.8.1        |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.4.3        |
| activesupport             | 4.2.8        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.55.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170223 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.5       |
| faraday_middleware        | 0.11.0.1     |
| net-ssh                   | 4.1.0        |
| net-sftp                  | 2.1.2        |
| net-scp                   | 1.2.1        |
| colorize                  | 0.8.1        |
</details>

**Comment by hjanuschka** [comment] 2017-03-03 09:36
can you share your fastfile?

**Comment by AymenFarrah** [comment] 2017-03-03 09:40
in my fast file i have many lanes:

in header i have 
```

#encoding: utf-8
Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8

fastlane_require 'net/ssh'
fastlane_require 'net/sftp'
fastlane_require 'net/scp'
fastlane_require 'fileutils'
fastlane_require 'colorize'
default_platform :ios
```


```
 lane :addBadge do 
     badge(shield: "37.0-BASKET-blue", no_badge: true, shield_no_resize: true)
  end

```
so i call this lane on command line with : fastlane addBadge --verbose and got fail after updating icons

**Comment by hjanuschka** [comment] 2017-03-03 09:53
strange, i can confirm that the above lane - works for me.
![icon-60 2x](https://cloud.githubusercontent.com/assets/2891702/23546328/5aee66d6-ffff-11e6-88bc-6974aa4a141f.png)

i suspect something else in the fastfile, right after the badge call - as the initial error points out 

`Could not find action, lane or variable ' '.` -> looks like calling a action with ` ` - maybe resulting from variable, could you share more parts of your fastfile? - maybe something in the `before_each`/`after_each`

**Comment by AymenFarrah** [comment] 2017-03-03 11:01
i have nothing in my fastfile: such as before_all after_all before_each after_each

i have multiple lane separately that do some operations/actions  (increment_build, badge etc)

and i cant run a lane with badge as an action!

the error is : trigger_action_by_name

and in doc i found:
```

    # This is being called from `method_missing` from the Fastfile
    # It's also used when an action is called from another action
    # @param from_action Indicates if this action is being trigged by another action.
    #                    If so, it won't show up in summary.
    def trigger_action_by_name(method_sym, custom_dir, from_action, *arguments)
```

this mean that an action is called from another action ! but i have only one action is badge

**Comment by juli1quere** [comment] 2017-03-03 11:14
What if you remove every other lanes / code from your `fastfile` and call `fastlane addBadge`? Does it works ?

**Comment by AymenFarrah** [comment] 2017-03-03 11:20
there is my fastfile with only one lane addBadge, still not working i have the same issue

```
#encoding: utf-8
Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8

fastlane_require 'net/ssh'
fastlane_require 'net/sftp'
fastlane_require 'net/scp'
fastlane_require 'fileutils'
fastlane_require 'colorize'


fastlane_version "2.19.1"

default_platform :ios

platform :ios do

  #Add a badge
  lane :addBadge do 
     iconText = "37.0" + "-" + "BASKET" + "-blue"
     badge(shield: iconText, no_badge: true, shield_no_resize: true)
  end

end

```


`[12:19:11]: Could not find action, lane or variable ' '. Check out the documentation for more details: https://docs.fastlane.tools/actions
`

**Comment by juli1quere** [comment] 2017-03-03 11:37
I tried this precise `Fastfile`, and it works. 
![icon-76](https://cloud.githubusercontent.com/assets/231661/23549770/0df64678-000e-11e7-9b52-f1a25da89be4.png). 

Maybe you could try by removing everything before `fastlane_version "2.19.1"`.

**Comment by AymenFarrah** [comment] 2017-03-03 11:38
ok thank you for help! i will try to re install fastlane ! mysterious

**Comment by juli1quere** [comment] 2017-03-03 11:40
Maybe you could try in a `bundler` environment. It would be easier for us to reproduce the issue.

**Comment by AymenFarrah** [comment] 2017-03-03 11:43
i will try in `bundler` if it helps, easy to install it ?
otherwise i try this, still not works

```
fastlane_version "2.19.1"
default_platform :ios
platform :ios do

  #Add a badge
  lane :addBadge do 
     iconText = "37.0" + "-" + "BASKET" + "-blue"
     badge(shield: iconText, no_badge: true, shield_no_resize: true)
  end

```
end

**Comment by AymenFarrah** [comment] 2017-03-03 11:47
```
➜  MyProjectWorkspace git:(dev) ✗ fastlane addBadge
[12:41:26]: -------------------------------------------------
[12:41:26]: --- Step: Verifying required fastlane version ---
[12:41:26]: -------------------------------------------------
[12:41:26]: Your fastlane version 2.19.1 matches the minimum requirement of 2.19.1  ✅
[12:41:26]: ------------------------------
[12:41:26]: --- Step: default_platform ---
[12:41:26]: ------------------------------
[12:41:26]: Driving the lane 'ios addBadge' 🚀
[12:41:26]: -------------------
[12:41:26]: --- Step: badge ---
[12:41:26]: -------------------
[12:41:26]: Start adding badges...
[12:41:26]: './Resources/AppIcon.appiconset/Icon-29-1.png'
[12:41:26]: './Resources/AppIcon.appiconset/Icon-29@2x-1.png'
[12:41:26]: './Resources/AppIcon.appiconset/Icon-29@2x.png'
[12:41:26]: './Resources/AppIcon.appiconset/Icon-29@3x-1.png'
[12:41:27]: './Resources/AppIcon.appiconset/Icon-40.png'
[12:41:27]: './Resources/AppIcon.appiconset/Icon-40@2x-1.png'
[12:41:27]: './Resources/AppIcon.appiconset/Icon-40@2x.png'
[12:41:27]: './Resources/AppIcon.appiconset/Icon-40@3x.png'
[12:41:27]: './Resources/AppIcon.appiconset/Icon-60@2x.png'
[12:41:27]: './Resources/AppIcon.appiconset/icon-60@3x.png'
[12:41:27]: './Resources/AppIcon.appiconset/Icon-76.png'
[12:41:27]: './Resources/AppIcon.appiconset/Icon-76@2x.png'
[12:41:27]: './Resources/AppIcon.appiconset/Icon-83.5@2x.png'
[12:41:30]: Badged \o/!
+------------------+--------------+
|          Lane Context           |
+------------------+--------------+
| DEFAULT_PLATFORM | ios          |
| PLATFORM_NAME    | ios          |
| LANE_NAME        | ios addBadge |
+------------------+--------------+
[12:41:30]: Could not find action, lane or variable ' '. Check out the documentation for more details: https://docs.fastlane.tools/actions
```

**Comment by juli1quere** [comment] 2017-03-03 11:51
It seems you are calling the lane from a CI no ? If it is, can you try from your local computer ?

About `bundler`, it's pretty straight forward. You can [look at this](https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile)

**Comment by AymenFarrah** [comment] 2017-03-03 11:53
No im really calling the lane from my local computer on command line:
➜  MyProjectWorkspace git:(dev) ✗ fastlane addBadge

**Comment by AymenFarrah** [comment] 2017-03-03 12:00
and with bundler i have this Gemfile:

```
source "https://rubygems.org"
gem "fastlane"
gem "badge"
```

same issue ! icon is badged but got the lane error : Could not find action, lane or variable ' '. Check out the documentation for more details: https://docs.fastlane.tools/actions

**Comment by mfurtak** [comment] 2017-03-03 13:09
Hi @AymenFarrah 

If you run `fastlane run badge --shield "37.0-BASKET-blue" --no_badge true --shield_no_resize true` from your command line does it complete without errors?

**Comment by AymenFarrah** [comment] 2017-03-03 14:10
Hi @mfurtak 

I have invalid option: --shield

**Comment by AymenFarrah** [comment] 2017-03-03 14:15
when i try on command line just, fastlane run badge it work

```
➜  myProject git:(basket) ✗ fastlane run badge
[15:10:54]: -------------------
[15:10:54]: --- Step: badge ---
[15:10:54]: -------------------
[15:10:54]: Start adding badges...
[15:10:54]: './Resources/AppIcon.appiconset/Icon-29-1.png'
[15:10:54]: './Resources/AppIcon.appiconset/Icon-29@2x-1.png'
[15:10:54]: './Resources/AppIcon.appiconset/Icon-29@2x.png'
[15:10:54]: './Resources/AppIcon.appiconset/Icon-29@3x-1.png'
[15:10:54]: './Resources/AppIcon.appiconset/Icon-40.png'
[15:10:54]: './Resources/AppIcon.appiconset/Icon-40@2x-1.png'
[15:10:54]: './Resources/AppIcon.appiconset/Icon-40@2x.png'
[15:10:54]: './Resources/AppIcon.appiconset/Icon-40@3x.png'
[15:10:54]: './Resources/AppIcon.appiconset/Icon-60@2x.png'
[15:10:54]: './Resources/AppIcon.appiconset/icon-60@3x.png'
[15:10:54]: './Resources/AppIcon.appiconset/Icon-76.png'
[15:10:54]: './Resources/AppIcon.appiconset/Icon-76@2x.png'
[15:10:54]: './Resources/AppIcon.appiconset/Icon-83.5@2x.png'
[15:10:58]: Badged \o/!
[15:10:58]: Result: true
```

but when i call juste badge in my lane , so my fastfile look like:

```
fastlane_version "2.19.1"
default_platform :ios
platform :ios do
  #Add a badge
  lane :addBadge do      
     badge
  end
end

```

i got the error:

```
➜  myProject git:(basket) ✗ fastlane addBadge                                                                        
[15:11:39]: -------------------------------------------------
[15:11:39]: --- Step: Verifying required fastlane version ---
[15:11:39]: -------------------------------------------------
[15:11:39]: Your fastlane version 2.19.1 matches the minimum requirement of 2.19.1  ✅
[15:11:39]: ------------------------------
[15:11:39]: --- Step: default_platform ---
[15:11:39]: ------------------------------
[15:11:39]: Driving the lane 'ios addBadge' 🚀
[15:11:39]: -------------------
[15:11:39]: --- Step: badge ---
[15:11:39]: -------------------
[15:11:39]: Start adding badges...
[15:11:39]: './Resources/AppIcon.appiconset/Icon-29-1.png'
[15:11:39]: './Resources/AppIcon.appiconset/Icon-29@2x-1.png'
[15:11:39]: './Resources/AppIcon.appiconset/Icon-29@2x.png'
[15:11:39]: './Resources/AppIcon.appiconset/Icon-29@3x-1.png'
[15:11:39]: './Resources/AppIcon.appiconset/Icon-40.png'
[15:11:39]: './Resources/AppIcon.appiconset/Icon-40@2x-1.png'
[15:11:39]: './Resources/AppIcon.appiconset/Icon-40@2x.png'
[15:11:39]: './Resources/AppIcon.appiconset/Icon-40@3x.png'
[15:11:40]: './Resources/AppIcon.appiconset/Icon-60@2x.png'
[15:11:40]: './Resources/AppIcon.appiconset/icon-60@3x.png'
[15:11:40]: './Resources/AppIcon.appiconset/Icon-76.png'
[15:11:40]: './Resources/AppIcon.appiconset/Icon-76@2x.png'
[15:11:40]: './Resources/AppIcon.appiconset/Icon-83.5@2x.png'
[15:11:43]: Badged \o/!
+------------------+--------------+
|          Lane Context           |
+------------------+--------------+
| DEFAULT_PLATFORM | ios          |
| PLATFORM_NAME    | ios          |
| LANE_NAME        | ios addBadge |
+------------------+--------------+
[15:11:43]: Could not find action, lane or variable ' '. Check out the documentation for more details: https://docs.fastlane.tools/actions

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | badge                               | 4           |
+------+-------------------------------------+-------------+

[15:11:43]: fastlane finished with errors
```

**Comment by mfurtak** [comment] 2017-03-03 14:57
Sorry about that, I got my syntax wrong. One more try on the full command?

```
fastlane run badge shield:"37.0-BASKET-blue" no_badge:true shield_no_resize:true
```

I believe there's something strange about your `Fastfile`, but I'm just trying to eliminate the `badge` action as a reason :+1:

**Comment by AymenFarrah** [comment] 2017-03-03 14:59
`fastlane run badge shield:"37.0-BASKET-blue" no_badge:true shield_no_resize:true`

it works and finished by
```
[15:58:12]: Badged \o/!
[15:58:12]: Result: true
```

**Comment by mfurtak** [comment] 2017-03-03 15:02
Can you try deleting your `Fastfile` and starting a new blank one? When you make your new one, please do not paste in any content from the old one. If you type it out fresh again, do you still have the problem?

Sorry for the strange request, but this is a very strange problem! 😅

**Comment by AymenFarrah** [comment] 2017-03-03 15:05
ohh my god! it was my fastfile ??!
so strange! 
i delete my old fastfile and redo with
`fastlane init`
and it works !!!

**Comment by AymenFarrah** [comment] 2017-03-03 15:06
i'm using sublimeText to edit it but other lane works ! only badge is down

**Comment by mfurtak** [comment] 2017-03-03 15:12
OK, my suspicion is that some strange whitespace characters got into your file and fastlane was trying to treat them like a call to an action. 🤔 

Anyhow, are you all set? If so, can I close this issue out?

**Comment by AymenFarrah** [comment] 2017-03-03 15:13
Thank you ! here my old Fastfile (i add .txt to extension to upload it), could you try to figure out whats wrong with this file (and u should delete txt extension to try it) ?
[Fastfile.txt](https://github.com/fastlane/fastlane/files/817099/Fastfile.txt)

**Comment by AymenFarrah** [comment] 2017-03-03 15:15
Ok you can close issue, the are some white spaces before badge action!
Thank you

**Comment by mfurtak** [comment] 2017-03-03 15:20
I can reproduce the behavior with the file you provided. Thanks very much! 🚀

**Closed by mfurtak** 2017-03-03 15:20 UTC

**Comment by mfurtak** [comment] 2017-03-03 15:25
Hey, one more question. When you originally put this `badge` code together, did you copy this example from the web? If so, do you remember from where?

**Comment by AymenFarrah** [comment] 2017-03-03 15:34
no i remember that a copy an existing lane (i dont remember which one i do it yesterday) and then i change the lane name and put badge action
so it seems that i have the whitespace in my fastfile but it works, only badge lane dont work

**Comment by mfurtak** [comment] 2017-03-03 15:54
Sure, because of the way Ruby works, only the code you try to run will actually be evaluated. Because the strange characters are part of the badge lane, it only has problems when you run that lane.

Anyway, a challenging mystery! Thanks 🙌

**Comment by AymenFarrah** [comment] 2017-03-03 15:58
but fastlane could evaluate/compile the fastfile before running the different lanes!
Anyway thank you for your help!

**Comment by AymenFarrah** [comment] 2017-03-03 15:58
👍 👍 👍
