### ISSUE TITLE
no implicit conversion of nil into String - dsym_zip

### ISSUE THREAD

**Issue by valeIT** [fastlane/fastlane#916] opened 2015-11-27 15:24 UTC
I'm trying to use pilot to submit to test flight, but I keep getting an error while creating the dsym file.

The error I get is on this line in fastlane/action/dsym_zip.rb -> `params[:dsym_path] ||= File.join("#{File.basename(archive, '.*')}.app.dSYM.zip")`

I'm using `gym(scheme: "My Scheme")` to build. In the documentation it says that if it's in the default place dsym_zip will work without argument. Am I missing something?

```
  "event_id": "e3651e9b4b75ec05321ca9bf820a8102",
  "message": "TypeError: no implicit conversion of nil into String",
  "timestamp": "2015-11-27T14:40:31",
  "time_spent": null,
  "level": 40,
  "project": null,
  "platform": "ruby",
  "logger": "",
  "culprit": "fastlane/actions/dsym_zip.rb in basename at line 12",
```

Error:

```
"exception": {
    "values": [
      {
        "type": "TypeError",
        "value": "no implicit conversion of nil into String",
        "module": "",
        "stacktrace": {
          "frames": [
            {
              "pre_context": [
                "  warn \"unable to load executable-hooks/hooks\" if ENV.key?('ExecutableHooks_DEBUG')\n",
                "end\n",
                "\n"
              ],
              "post_context": [
                null,
                null,
                null
              ],
              "abs_path": "/Users/vale/.rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks",
              "function": "<main>",
              "lineno": 15,
              "in_app": false,
              "context_line": "eval File.read($0), binding, $0\n",
              "project_root": null,
              "filename": "/Users/vale/.rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks"
            },
            {
              "pre_context": [
                "  warn \"unable to load executable-hooks/hooks\" if ENV.key?('ExecutableHooks_DEBUG')\n",
                "end\n",
                "\n"
              ],
              "post_context": [
                null,
                null,
                null
              ],
              "abs_path": "/Users/vale/.rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks",
              "function": "eval",
              "lineno": 15,
              "in_app": false,
              "context_line": "eval File.read($0), binding, $0\n",
              "project_root": null,
              "filename": "/Users/vale/.rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks"
            },
            {
              "pre_context": [
                "end\n",
                "\n",
                "gem 'fastlane', version\n"
              ],
              "post_context": [
                null,
                null,
                null
              ],
              "abs_path": "/Users/vale/.rvm/rubies/ruby-2.0.0-p353/bin/fastlane",
              "function": "<main>",
              "lineno": 23,
              "in_app": false,
              "context_line": "load Gem.bin_path('fastlane', 'fastlane', version)\n",
              "project_root": null,
              "filename": "/Users/vale/.rvm/rubies/ruby-2.0.0-p353/bin/fastlane"
            },
            {
              "pre_context": [
                "end\n",
                "\n",
                "gem 'fastlane', version\n"
              ],
              "post_context": [
                null,
                null,
                null
              ],
              "abs_path": "/Users/vale/.rvm/rubies/ruby-2.0.0-p353/bin/fastlane",
              "function": "load",
              "lineno": 23,
              "in_app": false,
              "context_line": "load Gem.bin_path('fastlane', 'fastlane', version)\n",
              "project_root": null,
              "filename": "/Users/vale/.rvm/rubies/ruby-2.0.0-p353/bin/fastlane"
            },
            {
              "pre_context": [
                "\n",
                "begin\n",
                "  FastlaneCore::UpdateChecker.start_looking_for_update('fastlane')\n"
              ],
              "post_context": [
                "rescue => ex\n",
                "  FastlaneCore::CrashReporting.handle_crash(ex)\n",
                "ensure\n"
              ],
              "abs_path": "/Users/vale/.rvm/gems/ruby-2.0.0-p353@global/gems/fastlane-1.41.1/bin/fastlane",
              "function": "<top (required)>",
              "lineno": 158,
              "in_app": false,
              "context_line": "  FastlaneApplication.new.run\n",
              "project_root": null,
              "filename": "/Users/vale/.rvm/gems/ruby-2.0.0-p353@global/gems/fastlane-1.41.1/bin/fastlane"
            },
            {
              "pre_context": [
                "\n",
                "    default_command :trigger\n",
                "\n"
              ],
              "post_context": [
                "  end\n",
                "end\n",
                "\n"
              ],
              "abs_path": "/Users/vale/.rvm/gems/ruby-2.0.0-p353@global/gems/fastlane-1.41.1/bin/fastlane",
              "function": "run",
              "lineno": 152,
              "in_app": false,
              "context_line": "    run!\n",
              "project_root": null,
              "filename": "/Users/vale/.rvm/gems/ruby-2.0.0-p353@global/gems/fastlane-1.41.1/bin/fastlane"
            },
            {
              "pre_context": [
                "      never_trace!\n",
                "    ).each do |meth|\n",
                "      eval <<-END, binding, __FILE__, __LINE__\n"
              ],
              "post_context": [
                "          ::Commander::Runner.instance.#{meth}(*args, &block)\n",
                "        end\n",
                "      END\n"
              ],
              "abs_path": "/Users/vale/.rvm/gems/ruby-2.0.0-p353@global/gems/commander-4.3.5/lib/commander/delegates.rb",
              "function": "run!",
              "lineno": 15,
              "in_app": false,
              "context_line": "        def #{meth}(*args, &block)\n",
              "project_root": null,
              "filename": "commander/delegates.rb"
            },
            {
              "pre_context": [
                "      parse_global_options\n",
                "      remove_global_options options, @args\n",
                "      if trace\n"
              ],
              "post_context": [
                "      else\n",
                "        begin\n",
                "          run_active_command\n"
              ],
              "abs_path": "/Users/vale/.rvm/gems/ruby-2.0.0-p353@global/gems/commander-4.3.5/lib/commander/runner.rb",
              "function": "run!",
              "lineno": 68,
              "in_app": false,
              "context_line": "        run_active_command\n",
              "project_root": null,
              "filename": "commander/runner.rb"
            },
            {
              "pre_context": [
                "      if alias? command_name_from_args\n",
                "        active_command.run(*(@aliases[command_name_from_args.to_s] + args_without_command_name))\n",
                "      else\n"
              ],
              "post_context": [
                "      end\n",
                "    end\n",
                "\n"
              ],
              "abs_path": "/Users/vale/.rvm/gems/ruby-2.0.0-p353@global/gems/commander-4.3.5/lib/commander/runner.rb",
              "function": "run_active_command",
              "lineno": 428,
              "in_app": false,
              "context_line": "        active_command.run(*args_without_command_name)\n",
              "project_root": null,
              "filename": "commander/runner.rb"
            },
            {
              "pre_context": [
                "    #\n",
                "\n",
                "    def run(*args)\n"
              ],
              "post_context": [
                "    end\n",
                "\n",
                "    #:stopdoc:\n"
              ],
              "abs_path": "/Users/vale/.rvm/gems/ruby-2.0.0-p353@global/gems/commander-4.3.5/lib/commander/command.rb",
              "function": "run",
              "lineno": 153,
              "in_app": false,
              "context_line": "      call parse_options_and_call_procs(*args)\n",
              "project_root": null,
              "filename": "commander/command.rb"
            },
            {
              "pre_context": [
                "      meth = @when_called.shift || :call\n",
                "      options = proxy_option_struct\n",
                "      case object\n"
              ],
              "post_context": [
                "      when Class then meth != :call ? object.new.send(meth, args, options) : object.new(args, options)\n",
                "      else object.send(meth, args, options) if object\n",
                "      end\n"
              ],
              "abs_path": "/Users/vale/.rvm/gems/ruby-2.0.0-p353@global/gems/commander-4.3.5/lib/commander/command.rb",
              "function": "call",
              "lineno": 178,
              "in_app": false,
              "context_line": "      when Proc then object.call(args, options)\n",
              "project_root": null,
              "filename": "commander/command.rb"
            },
            {
              "pre_context": [
                "      meth = @when_called.shift || :call\n",
                "      options = proxy_option_struct\n",
                "      case object\n"
              ],
              "post_context": [
                "      when Class then meth != :call ? object.new.send(meth, args, options) : object.new(args, options)\n",
                "      else object.send(meth, args, options) if object\n",
                "      end\n"
              ],
              "abs_path": "/Users/vale/.rvm/gems/ruby-2.0.0-p353@global/gems/commander-4.3.5/lib/commander/command.rb",
              "function": "call",
              "lineno": 178,
              "in_app": false,
              "context_line": "      when Proc then object.call(args, options)\n",
              "project_root": null,
              "filename": "commander/command.rb"
            },
            {
              "pre_context": [
                "\n",
                "      c.action do |args, options|\n",
                "        if Fastlane::FastlaneFolder.setup?\n"
              ],
              "post_context": [
                "        else\n",
                "          create = agree('Could not find fastlane in current directory. Would you like to set it up? (y/n)'.yellow, true)\n",
                "          Fastlane::Setup.new.run if create\n"
              ],
              "abs_path": "/Users/vale/.rvm/gems/ruby-2.0.0-p353@global/gems/fastlane-1.41.1/bin/fastlane",
              "function": "block (2 levels) in run",
              "lineno": 35,
              "in_app": false,
              "context_line": "          Fastlane::CommandLineHandler.handle(args, options)\n",
              "project_root": null,
              "filename": "/Users/vale/.rvm/gems/ruby-2.0.0-p353@global/gems/fastlane-1.41.1/bin/fastlane"
            },
            {
              "pre_context": [
                "\n",
                "      dot_env = Helper.is_test? ? nil : options.env\n",
                "\n"
              ],
              "post_context": [
                "    end\n",
                "\n",
                "    # Helper to convert into the right data type\n"
              ],
              "abs_path": "/Users/vale/.rvm/gems/ruby-2.0.0-p353@global/gems/fastlane-1.41.1/lib/fastlane/command_line_handler.rb",
              "function": "handle",
              "lineno": 31,
              "in_app": false,
              "context_line": "      Fastlane::LaneManager.cruise_lane(platform, lane, lane_parameters, dot_env)\n",
              "project_root": null,
              "filename": "fastlane/command_line_handler.rb"
            },
            {
              "pre_context": [
                "      started = Time.now\n",
                "      e = nil\n",
                "      begin\n"
              ],
              "post_context": [
                "      rescue => ex\n",
                "        Helper.log.info 'Variable Dump:'.yellow\n",
                "        Helper.log.info Actions.lane_context\n"
              ],
              "abs_path": "/Users/vale/.rvm/gems/ruby-2.0.0-p353@global/gems/fastlane-1.41.1/lib/fastlane/lane_manager.rb",
              "function": "cruise_lane",
              "lineno": 43,
              "in_app": false,
              "context_line": "        ff.runner.execute(lane, platform, parameters)\n",
              "project_root": null,
              "filename": "fastlane/lane_manager.rb"
            },
            {
              "pre_context": [
                "\n",
                "      path_to_use = Fastlane::FastlaneFolder.path || Dir.pwd\n",
                "      begin\n"
              ],
              "post_context": [
                "          # Call the platform specific before_all block and then the general one\n",
                "          before_all_blocks[current_platform].call(current_lane) if before_all_blocks[current_platform] && current_platform\n",
                "          before_all_blocks[nil].call(current_lane) if before_all_blocks[nil]\n"
              ],
              "abs_path": "/Users/vale/.rvm/gems/ruby-2.0.0-p353@global/gems/fastlane-1.41.1/lib/fastlane/runner.rb",
              "function": "execute",
              "lineno": 46,
              "in_app": false,
              "context_line": "        Dir.chdir(path_to_use) do # the file is located in the fastlane folder\n",
              "project_root": null,
              "filename": "fastlane/runner.rb"
            },
            {
              "pre_context": [
                "\n",
                "      path_to_use = Fastlane::FastlaneFolder.path || Dir.pwd\n",
                "      begin\n"
              ],
              "post_context": [
                "          # Call the platform specific before_all block and then the general one\n",
                "          before_all_blocks[current_platform].call(current_lane) if before_all_blocks[current_platform] && current_platform\n",
                "          before_all_blocks[nil].call(current_lane) if before_all_blocks[nil]\n"
              ],
              "abs_path": "/Users/vale/.rvm/gems/ruby-2.0.0-p353@global/gems/fastlane-1.41.1/lib/fastlane/runner.rb",
              "function": "chdir",
              "lineno": 46,
              "in_app": false,
              "context_line": "        Dir.chdir(path_to_use) do # the file is located in the fastlane folder\n",
              "project_root": null,
              "filename": "fastlane/runner.rb"
            },
            {
              "pre_context": [
                "          before_all_blocks[current_platform].call(current_lane) if before_all_blocks[current_platform] && current_platform\n",
                "          before_all_blocks[nil].call(current_lane) if before_all_blocks[nil]\n",
                "\n"
              ],
              "post_context": [
                "\n",
                "          # `after_all` is only called if no exception was raised before\n",
                "          # Call the platform specific before_all block and then the general one\n"
              ],
              "abs_path": "/Users/vale/.rvm/gems/ruby-2.0.0-p353@global/gems/fastlane-1.41.1/lib/fastlane/runner.rb",
              "function": "block in execute",
              "lineno": 51,
              "in_app": false,
              "context_line": "          return_val = lane_obj.call(parameters || {}) # by default no parameters\n",
              "project_root": null,
              "filename": "fastlane/runner.rb"
            },
            {
              "pre_context": [
                "\n",
                "    # Execute this lane\n",
                "    def call(parameters)\n"
              ],
              "post_context": [
                "    end\n",
                "\n",
                "    # @return [String] The lane + name of the lane. If there is no platform, it will only be the lane name\n"
              ],
              "abs_path": "/Users/vale/.rvm/gems/ruby-2.0.0-p353@global/gems/fastlane-1.41.1/lib/fastlane/lane.rb",
              "function": "call",
              "lineno": 36,
              "in_app": false,
              "context_line": "      block.call(parameters || {})\n",
              "project_root": null,
              "filename": "fastlane/lane.rb"
            },
            {
              "pre_context": [
                "\n",
                "    # Execute this lane\n",
                "    def call(parameters)\n"
              ],
              "post_context": [
                "    end\n",
                "\n",
                "    # @return [String] The lane + name of the lane. If there is no platform, it will only be the lane name\n"
              ],
              "abs_path": "/Users/vale/.rvm/gems/ruby-2.0.0-p353@global/gems/fastlane-1.41.1/lib/fastlane/lane.rb",
              "function": "call",
              "lineno": 36,
              "in_app": false,
              "context_line": "      block.call(parameters || {})\n",
              "project_root": null,
              "filename": "fastlane/lane.rb"
            },
            {
              "abs_path": "Fastfile",
              "function": "block (2 levels) in parsing_binding",
              "lineno": 32,
              "in_app": false,
              "project_root": null,
              "filename": "Fastfile"
            },
            {
              "pre_context": [
                "      # confusing\n",
                "      if class_ref && class_ref.respond_to?(:run)\n",
                "        # Action is available, now execute it\n"
              ],
              "post_context": [
                "      else\n",
                "        raise \"Action '#{method_sym}' of class '#{class_name}' was found, but has no `run` method.\".red\n",
                "      end\n"
              ],
              "abs_path": "/Users/vale/.rvm/gems/ruby-2.0.0-p353@global/gems/fastlane-1.41.1/lib/fastlane/fast_file.rb",
              "function": "method_missing",
              "lineno": 149,
              "in_app": false,
              "context_line": "        return self.runner.execute_action(method_sym, class_ref, arguments)\n",
              "project_root": null,
              "filename": "fastlane/fast_file.rb"
            },
            {
              "pre_context": [
                "      verify_supported_os(method_sym, class_ref)\n",
                "\n",
                "      begin\n"
              ],
              "post_context": [
                "          Actions.execute_action(class_ref.step_text) do\n",
                "            # arguments is an array by default, containing an hash with the actual parameters\n",
                "            # Since we usually just need the passed hash, we'll just use the first object if there is only one\n"
              ],
              "abs_path": "/Users/vale/.rvm/gems/ruby-2.0.0-p353@global/gems/fastlane-1.41.1/lib/fastlane/runner.rb",
              "function": "execute_action",
              "lineno": 127,
              "in_app": false,
              "context_line": "        Dir.chdir(custom_dir) do # go up from the fastlane folder, to the project folder\n",
              "project_root": null,
              "filename": "fastlane/runner.rb"
            },
            {
              "pre_context": [
                "      verify_supported_os(method_sym, class_ref)\n",
                "\n",
                "      begin\n"
              ],
              "post_context": [
                "          Actions.execute_action(class_ref.step_text) do\n",
                "            # arguments is an array by default, containing an hash with the actual parameters\n",
                "            # Since we usually just need the passed hash, we'll just use the first object if there is only one\n"
              ],
              "abs_path": "/Users/vale/.rvm/gems/ruby-2.0.0-p353@global/gems/fastlane-1.41.1/lib/fastlane/runner.rb",
              "function": "chdir",
              "lineno": 127,
              "in_app": false,
              "context_line": "        Dir.chdir(custom_dir) do # go up from the fastlane folder, to the project folder\n",
              "project_root": null,
              "filename": "fastlane/runner.rb"
            },
            {
              "pre_context": [
                "\n",
                "      begin\n",
                "        Dir.chdir(custom_dir) do # go up from the fastlane folder, to the project folder\n"
              ],
              "post_context": [
                "            # arguments is an array by default, containing an hash with the actual parameters\n",
                "            # Since we usually just need the passed hash, we'll just use the first object if there is only one\n",
                "            if arguments.count == 0\n"
              ],
              "abs_path": "/Users/vale/.rvm/gems/ruby-2.0.0-p353@global/gems/fastlane-1.41.1/lib/fastlane/runner.rb",
              "function": "block in execute_action",
              "lineno": 128,
              "in_app": false,
              "context_line": "          Actions.execute_action(class_ref.step_text) do\n",
              "project_root": null,
              "filename": "fastlane/runner.rb"
            },
            {
              "pre_context": [
                "\n",
                "      begin\n",
                "        Helper.log_alert(\"Step: \" + step_name) if step_name\n"
              ],
              "post_context": [
                "      rescue => ex\n",
                "        exc = ex\n",
                "        error = caller.join(\"\\n\") + \"\\n\\n\" + ex.to_s\n"
              ],
              "abs_path": "/Users/vale/.rvm/gems/ruby-2.0.0-p353@global/gems/fastlane-1.41.1/lib/fastlane/actions/actions_helper.rb",
              "function": "execute_action",
              "lineno": 37,
              "in_app": false,
              "context_line": "        yield\n",
              "project_root": null,
              "filename": "fastlane/actions/actions_helper.rb"
            },
            {
              "pre_context": [
                "              raise \"You have to call the integration like `#{method_sym}(key: \\\"value\\\")`. Run `fastlane action #{method_sym}` for all available keys. Please check out the current documentation on GitHub.\".red\n",
                "            end\n",
                "\n"
              ],
              "post_context": [
                "          end\n",
                "        end\n",
                "      rescue => ex\n"
              ],
              "abs_path": "/Users/vale/.rvm/gems/ruby-2.0.0-p353@global/gems/fastlane-1.41.1/lib/fastlane/runner.rb",
              "function": "block (2 levels) in execute_action",
              "lineno": 142,
              "in_app": false,
              "context_line": "            class_ref.run(arguments)\n",
              "project_root": null,
              "filename": "fastlane/runner.rb"
            },
            {
              "pre_context": [
                "    class DsymZipAction < Action\n",
                "      def self.run(params)\n",
                "        archive = params[:archive_path]\n"
              ],
              "post_context": [
                "\n",
                "        dsym_folder_path = File.expand_path(File.join(archive, 'dSYMs'))\n",
                "        zipped_dsym_path = File.expand_path(params[:dsym_path])\n"
              ],
              "abs_path": "/Users/vale/.rvm/gems/ruby-2.0.0-p353@global/gems/fastlane-1.41.1/lib/fastlane/actions/dsym_zip.rb",
              "function": "run",
              "lineno": 12,
              "in_app": false,
              "context_line": "        params[:dsym_path] ||= File.join(\"#{File.basename(archive, '.*')}.app.dSYM.zip\")\n",
              "project_root": null,
              "filename": "fastlane/actions/dsym_zip.rb"
            },
            {
              "pre_context": [
                "    class DsymZipAction < Action\n",
                "      def self.run(params)\n",
                "        archive = params[:archive_path]\n"
              ],
              "post_context": [
                "\n",
                "        dsym_folder_path = File.expand_path(File.join(archive, 'dSYMs'))\n",
                "        zipped_dsym_path = File.expand_path(params[:dsym_path])\n"
              ],
              "abs_path": "/Users/vale/.rvm/gems/ruby-2.0.0-p353@global/gems/fastlane-1.41.1/lib/fastlane/actions/dsym_zip.rb",
              "function": "basename",
              "lineno": 12,
              "in_app": false,
              "context_line": "        params[:dsym_path] ||= File.join(\"#{File.basename(archive, '.*')}.app.dSYM.zip\")\n",
              "project_root": null,
              "filename": "fastlane/actions/dsym_zip.rb"
            }
          ]
        }
      }
    ]
  }
}
```

I also tried running a lane with only `gym(scheme: "My Scheme")` and `dsym_zip` in it but got the same error

**Comment by ohwutup** [comment] 2016-03-11 19:32
Thanks for raising the issue @valeIT ! This has been iterated upon quite a bit since this issue was posted, I am going to close the issue for now, please just update your tools, try reproducing and comment here if there is still an issue and we will happily reopen the issue and discuss. Thanks :lollipop:

**Closed by ohwutup** 2016-03-11 19:32 UTC
