### ISSUE TITLE
Deliver: transporter silently fails

### ISSUE THREAD

**Issue by meyskens** [fastlane/fastlane#4227] opened 2016-04-15 13:12 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Deliver

```
INFO [2016-04-15 15:06:54.40]: Uploading binary to iTunes Connect
INFO [2016-04-15 15:06:54.44]: Wrote XML data to '/tmp/1104281920.itmsp'
INFO [2016-04-15 15:06:54.48]: Going to upload updated app to iTunes Connect
INFO [2016-04-15 15:06:54.48]: This might take a few minutes, please don't interrupt the script
DEBUG [2016-04-15 15:06:54.54]: /Applications/Xcode.app/Contents/Applications/Application\ Loader.app/Contents/MacOS/itms/java/bin/java -Djava.ext.dirs=/Applications/Xcode.app/Contents/Applications/Application\ Loader.app/Contents/MacOS/itms/java/lib/ext -XX:NewSize=2m -Xms32m -Xmx1024m -Xms1024m -Djava.awt.headless=true -Dsun.net.http.retryPost=false -classpath /Applications/Xcode.app/Contents/Applications/Application\ Loader.app/Contents/MacOS/itms/lib/itmstransporter-launcher.jar com.apple.transporter.Application -m upload -u meyskens@me.com -p YourPassword -f /tmp/1104281920.itmsp -t Signiant -k 100000 2>&1
INFO [2016-04-15 15:06:54.74]: ------------------------------------------------------------------------------------------------------
INFO [2016-04-15 15:06:54.74]: Successfully uploaded package to iTunes Connect. It might take a few minutes until it's visible online.
INFO [2016-04-15 15:06:54.74]: ------------------------------------------------------------------------------------------------------
INFO [2016-04-15 15:06:54.74]: Finished the upload to iTunes Connect
INFO [2016-04-15 15:06:55.90]: Selecting the latest build...
ERROR [2016-04-15 15:06:57.07]: []
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: '7b14a6a0caccf8b28ff7a27552654a1f'
The crash report has been stored locally '/tmp/sentry_7b14a6a0caccf8b28ff7a27552654a1f.json'
/Users/innovatetechnologies/.rvm/gems/ruby-2.1.5/gems/fastlane_core-0.41.2/lib/fastlane_core/ui/interface.rb:127:in `crash!': [!] Could not find build (FastlaneCore::Interface::FastlaneCrash)
	from /Users/innovatetechnologies/.rvm/gems/ruby-2.1.5/gems/fastlane_core-0.41.2/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/innovatetechnologies/.rvm/gems/ruby-2.1.5/gems/deliver-1.11.0/lib/deliver/submit_for_review.rb:81:in `find_build'
	from /Users/innovatetechnologies/.rvm/gems/ruby-2.1.5/gems/deliver-1.11.0/lib/deliver/submit_for_review.rb:58:in `block in wait_for_build'
	from /Users/innovatetechnologies/.rvm/gems/ruby-2.1.5/gems/deliver-1.11.0/lib/deliver/submit_for_review.rb:57:in `loop'
	from /Users/innovatetechnologies/.rvm/gems/ruby-2.1.5/gems/deliver-1.11.0/lib/deliver/submit_for_review.rb:57:in `wait_for_build'
	from /Users/innovatetechnologies/.rvm/gems/ruby-2.1.5/gems/deliver-1.11.0/lib/deliver/submit_for_review.rb:42:in `select_build'
	from /Users/innovatetechnologies/.rvm/gems/ruby-2.1.5/gems/deliver-1.11.0/lib/deliver/submit_for_review.rb:5:in `submit!'
	from /Users/innovatetechnologies/.rvm/gems/ruby-2.1.5/gems/deliver-1.11.0/lib/deliver/runner.rb:87:in `submit_for_review'
	from /Users/innovatetechnologies/.rvm/gems/ruby-2.1.5/gems/deliver-1.11.0/lib/deliver/runner.rb:30:in `run'
	from /Users/innovatetechnologies/.rvm/gems/ruby-2.1.5/gems/deliver-1.11.0/lib/deliver/commands_generator.rb:49:in `block (2 levels) in run'
	from /Users/innovatetechnologies/.rvm/gems/ruby-2.1.5/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/innovatetechnologies/.rvm/gems/ruby-2.1.5/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/innovatetechnologies/.rvm/gems/ruby-2.1.5/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/innovatetechnologies/.rvm/gems/ruby-2.1.5/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/innovatetechnologies/.rvm/gems/ruby-2.1.5/gems/fastlane_core-0.41.2/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Users/innovatetechnologies/.rvm/gems/ruby-2.1.5/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/innovatetechnologies/.rvm/gems/ruby-2.1.5/gems/deliver-1.11.0/lib/deliver/commands_generator.rb:132:in `run'
	from /Users/innovatetechnologies/.rvm/gems/ruby-2.1.5/gems/deliver-1.11.0/lib/deliver/commands_generator.rb:12:in `start'
	from /Users/innovatetechnologies/.rvm/gems/ruby-2.1.5/gems/deliver-1.11.0/bin/deliver:5:in `<top (required)>'
	from /Users/innovatetechnologies/.rvm/gems/ruby-2.1.5/bin/deliver:23:in `load'
	from /Users/innovatetechnologies/.rvm/gems/ruby-2.1.5/bin/deliver:23:in `<main>'
	from /Users/innovatetechnologies/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
	from /Users/innovatetechnologies/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
```

```
Innovates-Mac:fastlane innovatetechnologies$ /Applications/Xcode.app/Contents/Applications/Application\ Loader.app/Contents/MacOS/itms/java/bin/java -Djava.ext.dirs=/Applications/Xcode.app/Contents/Applications/Application\ Loader.app/Contents/MacOS/itms/java/lib/ext -XX:NewSize=2m -Xms32m -Xmx1024m -Xms1024m -Djava.awt.headless=true -Dsun.net.http.retryPost=false -classpath /Applications/Xcode.app/Contents/Applications/Application\ Loader.app/Contents/MacOS/itms/lib/itmstransporter-launcher.jar com.apple.transporter.Application -m upload -u meyskens@me.com -p YourPassword -f /tmp/1104281920.itmsp -t Signiant -k 100000
Error: Could not find or load main class com.apple.transporter.Application
````
### Environment

fastlane version (run `fastlane -v`):
1.81.0
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
No

Note I use Xcode 6.0.1 due compatibility issues

**Comment by vpolouchkine** [comment] 2016-04-15 16:38
Looks like we're not looking in the right place for Xcode 6, potentially relevant: http://stackoverflow.com/questions/28461768/xcode-organizer-trying-to-access-transporter-at-wrong-directory-path

**Comment by meyskens** [comment] 2016-04-15 16:44
The stackoverflow link doesn't seem relevant. `itmstransporter-launcher.jar` doesn't seem to be present. Doing a `find /` to see if it is somewhere present. In meanwhile I am trying to inject the Application Loader 3.0 app into old Xcode to work this around.

**Comment by meyskens** [comment] 2016-04-15 16:46
follow up: no `itmstransporter-launcher.jar` found on the entire drive.

**Comment by meyskens** [comment] 2016-04-15 18:57
After some futher looking it seems to be since commit ac4d587e67868aa167408257f3a00b7c1cdea829 
Only the Xcode 7+ transporter (not even the standalone app) seems to have the Java libraries. Replacing the Xcode 6 itms folder seems to work for deliver but not sure if it broke the code signing (which is in the application loader frameworks).

**Comment by vpolouchkine** [comment] 2016-04-15 19:32
Thanks for investigating this. We'll take a look on our end as well.

**Comment by mfurtak** [comment] 2016-04-19 15:38
Hi @meyskens - thanks for the report! 👍 

If you set the environment variable `FASTLANE_ITUNES_TRANSPORTER_USE_SHELL_SCRIPT` equal to `1` and then run **deliver** are you back in business?

**Comment by mfurtak** [comment] 2016-04-20 17:32
@meyskens I've reproduced your situation locally, and will be working on making the current logic more robust to failure.

In the mean time, I'm curious if the work-around above helps. If you have time to check it out, please let me know! 👍

**Comment by mfurtak** [comment] 2016-04-20 19:13
I've shipped #4284 as an improvement to the silent failure problem as part of [`fastlane_core` 0.4.3](https://github.com/fastlane/fastlane/releases/tag/fastlane_core/0.41.3) 🚀

**Comment by nAviram** [comment] 2016-04-26 11:19
Hi @mfurtak !
I'm also with Xcode 6.4 - and I have the same issue - and I tried to set the environment variable FASTLANE_ITUNES_TRANSPORTER_USE_SHELL_SCRIPT equal to 1 

but it didn't work.

**Comment by meyskens** [comment] 2016-04-26 13:20
@nAviram thanks for testing. I replaced the itms (the java libs) folder within Xcode 6 with the content of Xcode 7 therefore was not able to quickly test them without reverting my workaround.

**Comment by nAviram** [comment] 2016-04-26 13:33
hey @meyskens -  Did the replacement work? are you able to upload now?

**Comment by mfurtak** [comment] 2016-04-26 14:19
Hi all - I'm going to close this issue since the silent failure part has been addressed.

I'll use #4339 to make further updates about the Xcode 6 situation. 👍

**Closed by mfurtak** 2016-04-26 14:19 UTC
Labels: awaiting-reply, deliver
