### ISSUE TITLE
Archive Failed after updating to latest version

### ISSUE THREAD

**Issue by hufkens** [fastlane/fastlane#1005] opened 2015-12-19 10:01 UTC
After updating to the latest version the Archive of my app fails. Any ideas?

```▸ Touching WeeTrains.app.dSYM
** ARCHIVE FAILED **
[10:55:14]: Exit status: 65
[10:55:14]: Variable Dump:
[10:55:14]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios alpha", :SIGH_PROFILE_PATH=>"/Users/alain/Work/Projects/WeeTaps/WeeTrains/AdHoc_com.weetaps.WeeTrains.mobileprovision", :SIGH_PROFILE_PATHS=>["/Users/alain/Work/Projects/WeeTaps/WeeTrains/AdHoc_com.weetaps.WeeTrains.mobileprovision"], :SIGH_UDID=>"edb33417-221b-4ba9-90b8-f30ae4c833bf", :SIGH_PROFILE_TYPE=>"ad-hoc"}
[10:55:14]: Error building the application - see the log above```

Crash log ID : 16c059e37e5228cd4bb79ad7b11f5ca4

**Comment by hufkens** [comment] 2015-12-19 13:13
I turned off crash logging and now it worked.

**Comment by hufkens** [comment] 2015-12-19 19:18
It's failing again, and I haven't really changed anything 😕

```** ARCHIVE FAILED **
[20:16:28]: Exit status: 65
[20:16:28]: Variable Dump:
[20:16:28]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios alpha", :SIGH_PROFILE_PATH=>"/Users/alain/Work/Projects/WeeTaps/WeeTrains/AdHoc_com.weetaps.WeeTrains.mobileprovision", :SIGH_PROFILE_PATHS=>["/Users/alain/Work/Projects/WeeTaps/WeeTrains/AdHoc_com.weetaps.WeeTrains.mobileprovision"], :SIGH_UDID=>"edb33417-221b-4ba9-90b8-f30ae4c833bf", :SIGH_PROFILE_TYPE=>"ad-hoc"}
[20:16:28]: Error building the application - see the log above

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | cocoapods                           | 12          |
| 4    | sigh                                | 44          |
| 5    | gym                                 | 214         |
+------+-------------------------------------+-------------+

[20:16:28]: fastlane finished with errors
-------------------------------------------------------------------------------------------
😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.
👍  This makes resolving issues much easier and helps improve fastlane.
🔒  The reports will be stored securely on getsentry.com.
✨  Once crash reporting is enabled, you get a clean output when something goes wrong.
🙊  More information about privacy: https://github.com/KrauseFx/fastlane/releases/tag/1.33.3
-------------------------------------------------------------------------------------------
/Library/Ruby/Gems/2.0.0/gems/gym-1.2.0/lib/gym/error_handler.rb:52:in `handle_build_error': Error building the application - see the log above (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.2.0/lib/gym/runner.rb:81:in `block in build_app'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.31.0/lib/fastlane_core/command_executor.rb:61:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.31.0/lib/fastlane_core/command_executor.rb:61:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.2.0/lib/gym/runner.rb:77:in `build_app'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.2.0/lib/gym/runner.rb:10:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.2.0/lib/gym/manager.rb:8:in `work'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/actions/gym.rb:22:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/actions/actions_helper.rb:37:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/runner.rb:128:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/runner.rb:127:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/runner.rb:127:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:46:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/runner.rb:51:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/bin/fastlane:37:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/bin/fastlane:155:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.48.0/bin/fastlane:161:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'```

**Comment by JaviSoto** [comment] 2015-12-19 19:51
Hi!

If you look at the beginning of the gym output, there's a line that tells you where the xcodebuild is being saved to. Do you mind taking a look at that one, and perhaps save the error from it? Thanks!

**Comment by hufkens** [comment] 2015-12-19 20:26
The weird part is that it sometimes works. I wanted to generate a new log, and it worked. And the next time it didn't:

here's the last part from the gym.log and I also added the ID from a previous crash log above:
```
CodeSign /Users/alain/Library/Developer/Xcode/DerivedData/WeeTrains-afoyqcqxourcjfavwvnsyapasfij/Build/Intermediates/ArchiveIntermediates/WeeTrains/InstallationBuildProductsLocation/Applications/WeeTrains.app
    cd /Users/alain/Work/Projects/WeeTaps/WeeTrains
    export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    
Signing Identity:     "iPhone Distribution: Alain Hufkens (9Y2DK26F2M)"
Provisioning Profile: "com.weetaps.WeeTrains AdHoc"
                      (edb33417-221b-4ba9-90b8-f30ae4c833bf)

    /usr/bin/codesign --force --sign 026D463EFDA2C4275B9C580734AD97974E3D533B --entitlements /Users/alain/Library/Developer/Xcode/DerivedData/WeeTrains-afoyqcqxourcjfavwvnsyapasfij/Build/Intermediates/ArchiveIntermediates/WeeTrains/IntermediateBuildFilesPath/WeeTrains.build/Beta-iphoneos/WeeTrains.build/WeeTrains.app.xcent --timestamp=none /Users/alain/Library/Developer/Xcode/DerivedData/WeeTrains-afoyqcqxourcjfavwvnsyapasfij/Build/Intermediates/ArchiveIntermediates/WeeTrains/InstallationBuildProductsLocation/Applications/WeeTrains.app

Validate /Users/alain/Library/Developer/Xcode/DerivedData/WeeTrains-afoyqcqxourcjfavwvnsyapasfij/Build/Intermediates/ArchiveIntermediates/WeeTrains/InstallationBuildProductsLocation/Applications/WeeTrains.app
    cd /Users/alain/Work/Projects/WeeTaps/WeeTrains
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    export PRODUCT_TYPE=com.apple.product-type.application
    builtin-validationUtility /Users/alain/Library/Developer/Xcode/DerivedData/WeeTrains-afoyqcqxourcjfavwvnsyapasfij/Build/Intermediates/ArchiveIntermediates/WeeTrains/InstallationBuildProductsLocation/Applications/WeeTrains.app

Touch /Users/alain/Library/Developer/Xcode/DerivedData/WeeTrains-afoyqcqxourcjfavwvnsyapasfij/Build/Intermediates/ArchiveIntermediates/WeeTrains/BuildProductsPath/Beta-iphoneos/WeeTrains.app.dSYM
    cd /Users/alain/Work/Projects/WeeTaps/WeeTrains
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /usr/bin/touch -c /Users/alain/Library/Developer/Xcode/DerivedData/WeeTrains-afoyqcqxourcjfavwvnsyapasfij/Build/Intermediates/ArchiveIntermediates/WeeTrains/BuildProductsPath/Beta-iphoneos/WeeTrains.app.dSYM
```

**Comment by JaviSoto** [comment] 2015-12-19 20:32
There doesn't seem to be anything that points to the problem on that part. Is there any other reference to an error further up?

Question: are you using the legacy build API? (the `use_legacy_build_api` parameter). If you're not, do you mind trying with it?

**Comment by hufkens** [comment] 2015-12-19 20:36
I'll try.
this is my fatslane setup for alpha
```
desc "Submit a new Aplha Build to Fabric Crashlytics"
  lane :alpha do
    sigh(adhoc: true)
    ENV["PROFILE_UDID"] = lane_context[SharedValues::SIGH_UDID]
    gym(configuration: "Beta")
    crashlytics(
      crashlytics_path: './Crashlytics.framework', 
      api_token: '',
      build_secret: '',
      ipa_path: './WeeTrains.ipa',
      groups: 'dev-team',
      notifications: true
    )
  end
```

**Comment by hufkens** [comment] 2015-12-19 20:38
And it's exactly the same setup for my other app that seems to build without issues. 
Thanks for the fast follow up 👍

**Comment by hufkens** [comment] 2015-12-19 20:58
Looks like the use_legacy_build_api works for me now. Not really sure what has changed? I haven't worked on that project since a month or so. But it always worked before and I always updated Fastlane. 

I'll keep it for now. Thanks

**Comment by hufkens** [comment] 2015-12-20 08:31
Mmm, the result with 'use_legacy_build_api' is the same as without. On the second run, the archive failed error was back.

**Comment by hufkens** [comment] 2015-12-22 19:41
Still no idea? I keep getting mixed results (legacy is on) and all provisioning profiles should be correct. I only have this issue with one specific project. 

Anyway I hope you can help me. Here's another crash report ID: c3261b8767375693d03c0f7955d2136f

**Comment by NikolaevSergey** [comment] 2016-01-08 07:05
Same issue
And it's specific for one project too.

**Comment by vorobievalex** [comment] 2016-01-14 20:33
Just had the same issue.
Root cause was that xcodebuild exit status was 65 just like in the log here. There was an error message in the middle of xcodebuild log above. So it was not related to fastlane.

However some more verbose error message from fastlane would help. Appreciate if log could contain something like: "xcodebuild exit status was 65, so failing" and xcodebuild command arguments again, so it is obvious where to dig further.

**Comment by ffittschen** [comment] 2016-01-16 21:31
I had the same problem a few weeks ago, it seems to be a Xcode bug.. 

You could try to use `gym --use_legacy_build_api true ` as described here: https://github.com/fastlane/gym#usage

**Comment by vpolouchkine** [comment] 2016-04-06 21:24
It looks like there hasn’t been any recent activity on this issue in some time, so I’m closing it. If this is still a problem, feel free to re-open a new issue and I’d be happy to help :+1:

**Closed by vpolouchkine** 2016-04-06 21:24 UTC
Labels: gym

**Comment by tomaskraina** [comment] 2016-09-07 19:08
I'm having the same issue on hosted CI bitrise.io.

Currently, I'm trying to run `gym` with `use_legacy_build_api: true`, will see if that helps although I had some issues with it in the past too.

**Comment by TKBurner** [comment] 2016-09-12 15:28
@tomaskraina Were you able to get up and running? Thanks!

**Comment by MarcPilgaard** [comment] 2016-09-23 11:41
I am struggling with some of the same problems. When building with the default `fastlane beta`. I receive error 65 during Touching xxx.app.dSYM. The log files doesn't display any error messages. I am currently using xcode 8 on OS X running El Capitan. I am using the parameter `use_legacy_build_api: true` without succese.

**Comment by TKBurner** [comment] 2016-09-26 17:56
@MarcPilgaard Great to hear from you! Can you make sure your build export settings have `dwarf w/DsYM`? If that doesn't work please open a new ticket and share the full input and output. I'd love to look into this!
