### ISSUE TITLE
exportArchive  error: doesn't include the com.apple.application-identifier entitlement

### ISSUE THREAD

**Issue by iT-Boyer** [fastlane/fastlane#16740] opened 2020-07-03 10:45 UTC
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

```ruby
gym(scheme:"Blink",
              outputDirectory: "build",
                  configuration: "Debug",
                exportMethod: "development",
                 exportXcargs: "-allowProvisioningUpdates",
                                  sdk: iossdk
        )
```

### Environment

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.150.0 | 🚫 Update available |

### Loaded fastlane plugins:

| Plugin                | Version | Update-Status |
| --------------------- | ------- | ------------- |
| fastlane-plugin-pgyer | 0.2.2   | ✅ Up-To-Date  |
| fastlane-plugin-pgyer | 0.2.2   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| CFPropertyList            | 2.3.6        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.2        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.71.0       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.0.2        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| memoist                   | 0.16.2       |
| multi_json                | 1.14.1       |
| os                        | 1.0.1        |
| googleauth                | 0.9.0        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.0        |
| google-cloud-core         | 1.4.1        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.337.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.1        |
| aws-sdk-core              | 3.102.1      |
| aws-sdk-kms               | 1.35.0       |
| aws-sdk-s3                | 1.72.0       |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.16.0       |
| faraday                   | 0.17.3       |
| signet                    | 0.14.0       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
| fastlane-plugin-pgyer     | 0.2.2        |
</details>

*generated on:* **2020-07-03**
</details>

** EXPORT FAILED **
```sh
+ xcodebuild -exportArchive -exportOptionsPlist /var/folders/_0/nw319hp500bc6j6n7dvg799r0000gn/T/gym_config20200703-92277-15mxovi.plist -archivePath '/Users/jhmac/Library/Developer/Xcode/Archives/2020-07-03/Blink 2020-07-03 18.27.03.xcarchive' -exportPath /var/folders/_0/nw319hp500bc6j6n7dvg799r0000gn/T/gym_output20200703-92277-p9bn3v -allowProvisioningUpdates

2020-07-03 18:27:38.248 xcodebuild[92986:13845507] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/_0/nw319hp500bc6j6n7dvg799r0000gn/T/Blink_2020-07-03_18-27-38.247.xcdistributionlogs'.
2020-07-03 18:27:38.396 xcodebuild[92986:13845582] CFURLRequestSetHTTPCookieStorageAcceptPolicy_block_invoke: no longer implemented and should not be called

error: exportArchive: Provisioning profile "iOS Team Provisioning Profile: **.iBlink" doesn't include the com.apple.application-identifier entitlement.

Error Domain=IDEProfileQualificationErrorDomain Code=8 "Provisioning profile "iOS Team Provisioning Profile: **.iBlink" doesn't include the com.apple.application-identifier entitlement." UserInfo={NSLocalizedDescription=Provisioning profile "iOS Team Provisioning Profile: **.iBlink" doesn't include the com.apple.application-identifier entitlement., IDEProfileQualificationError_RequiredEntitlements={
    "application-identifier" = "ZQ***8B.com.**.iBlink";
    "com.apple.application-identifier" = "ZQ**8B.com.**.iBlink";
    "com.apple.developer.team-identifier" = ZQ**8B;
    "keychain-access-groups" =     (
        "ZQ**8B.com.**.iBlink"
    );
}, IDEDistributionIssueSeverity=3, IDEProfileQualificationErrorMissingEntitlements=(
    "com.apple.application-identifier"
), IDEProfileQualificationError_Profile=<IDEEmbeddedProvisioningProfile 0x7fe78010df90: name: iOS Team Provisioning Profile: com.**.iBlink, UUID: 8a9799**9475dd8, teamName: Ti** (Beijing) Co., Ltd., teamIdentifierPrefixes: (
    ZQ**8B
), entitlements: {
    "application-identifier" = "**.iBlink";
    "com.apple.developer.applesignin" =     (
        Default
    );
    "com.apple.developer.team-identifier" = ZQ**8B;
    "get-task-allow" = 1;
    "keychain-access-groups" =     (
        "ZQ**288B.*",
        "com.apple.token"
    );
}, appIdentifierName: XC com jinher iBlink, applicationIdentifierPrefixes: (
    ZQJGJL288B
), dateCreated: 2020-07-03 10:05:49 +0000, dateExpired: 2021-07-03 10:05:49 +0000, certificateKinds: {(
    "1.2.840.113635.100.6.1.2",
    "1.2.840.113635.100.6.1.12"
)}, certificateSHA1Hashes: {(
    9A122CE677935C64E5***54A6E23099137,
   ...
)}, supportedUDIDs: {(
    "0000802***2201d2002e"
)}, isUniversal: 0, isXcodeManaged: 1, platforms: {(
    <DVTPlatform:0x7fe817c16090:'com.apple.platform.watchos':<DVTFilePath:0x7fe817c16010:'/Applications/Xcode.app/Contents/Developer/Platforms/WatchOS.platform'>>,
    <DVTPlatform:0x7fe817c13270:'com.apple.platform.iphoneos':<DVTFilePath:0x7fe817c12ef0:'/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform'>>
)}, filePath: <DVTFilePath:0x7fe7b7c93c90:'/Users/jhmac/Library/MobileDevice/Provisioning Profiles/8a9799**709475dd8.mobileprovision'>>}
```

**Comment by joshdholtz** [comment] 2020-07-03 17:57
@iT-Boyer Heyyy 👋 It looks like something might be misconfigured in your entitlements file? 👇 

```
Provisioning profile "iOS Team Provisioning Profile: **.iBlink" doesn't include the com.apple.application-identifier entitlement.
``

**Comment by iT-Boyer** [comment] 2020-07-04 11:49
I use `allowProvisioningUpdates` , it's ok   when build the app use Xcode .
![屏幕快照 2020-07-04 下午7 41 22](https://user-images.githubusercontent.com/4022953/86511839-6eceac00-be2f-11ea-964d-45a0d25ecb70.png)

How to set the `com.apple.application-identifier`  in fastfile?
@joshdholtz

**Comment by iT-Boyer** [comment] 2020-07-06 02:42
I try:
.
├── Blink.xcarchive
└── blink.plist
![截屏2020-07-06 上午10 41 15](https://user-images.githubusercontent.com/4022953/86550543-3d5ff880-bf75-11ea-8bc5-d715506bdf9b.png)

 it‘s wrong to compile directly with the command：
```
xcodebuild -exportArchive -exportOptionsPlist blink.plist -archivePath 'Blink.xcarchive' -exportPath Blink.ipa
```

**Comment by MoOx** [comment] 2020-08-05 17:33
Duplicate of #16681 ?

**Closed** 2020-09-20 17:32 UTC
Labels: status: waiting-for-reply, tool: gym
